### ISSUE TITLE
Mouse cursor hiding options seem slightly unintuitive

### ISSUE THREAD

**Issue by morganwillcock** [renpy/renpy#1003]
I was trying to disable the mouse cursor hiding and could only find the config option which sets the timeout (config.mouse_hide_time). The documentation doesn't say how to stop hiding the cursor, only that it will be hidden. I thought that maybe setting it to 0 would stop it but it actually just hides it all the time (although you can still use the mouse in the game, even though you can't see it). So I spent a while searching for something like <pre>config.mouse_hide = True</pre> ...but couldn't find it.

So I ended up searching the repository and found this in the launcher <pre>config.mouse_hide_time = 86400 * 366</pre> ...which would seem to indicate that there is no way to stop hiding the cursor, you just set it high value a hope you don't reach it.

Would it be possible to add <pre>config.mouse_hide</pre> (defaulting to True) to give an option that makes it a bit more obvious on how to turn it off and isn't dependent on a timer? Feel feel to close this issue if you think it's unnecessary.

**Comment by nyaatrap** [comment]
I think this tricky python expression works:
    define config.mouse_hide_time = float('inf')
Though it'd be good that just setting it False disable mouse hiding.

**Comment by renpytom** [comment]
To None. I'll be implmeneting this in the next few days.

**Comment by morganwillcock** [comment]
Many thanks.

**Comment by pratomoastan** [comment]
Wah Cool !~
