### ISSUE TITLE
Failed launch project in 6.99.10 and 6.99.11

### ISSUE THREAD

**Issue by Arisae** [renpy/renpy#1010]
I can't launch project for my existing projects in the Ren'Py 6.99.10 and 6.99.11.
**Nothing will happen when I click the Launch Project.**

I've checked **incompatible changes** and run **Check Script(Lint)**, there's no errors found.

My previous version is **6.99.7.858**, and I'm using **Windows 10**.
_The log.txt calls my Windows version is Windows-8-6.2.9200 in 6.99.7_

What should I working for the latest version?

**Comment by renpytom** [comment]
Can you send me the full files for your project, please?

**Comment by Arisae** [comment]
Sent it!

**Comment by Arisae** [comment]
Thank you PyTom!
