### ISSUE TITLE
renpy.game.script.namemap.value stores wrong directory

### ISSUE THREAD

**Issue by anxtdghiov** [renpy/renpy#1014]
A lookup of the namemap returns invalid files (unless renpy is run from the game directory):

`filename = renpy.game.script.namemap.get(renpy.game.context().current, None).filename`

The returned filename is relative to the current working directory, which appears to be a bug. The .linenumber is correct. A workaround to get to the .rpy file that works for me is the following:

`filename = re.sub(os.getcwd() + "(.*)c$", config.searchpath[0] + "\g<1>", filename)`

And it also seems that the valid .rpy is contained in renpy.game.context().current[0]

(running on Arch Linux  4.6.4-1 x86_64 with renpy-nightly-2016-08-18-708b6af-sdk)

**Comment by renpytom** [comment]
This is an implementation detail, not a public API. You can't rely on it. What are you trying to accomplish.

**Comment by anxtdghiov** [comment]
Besides just reporting a potential bug, I was trying to make an edit text/code button if config.developer is set and push modified dialogue changes to .rpy files.

Since I guess the forum is more appropriate I've placed a topic here, in case you're interested:
https://lemmasoft.renai.us/forums/viewtopic.php?f=45&t=39968

**Comment by renpytom** [comment]
I believe you want renpy.get_filename_line.

**Comment by anxtdghiov** [comment]
Yes, that works, thanks.
