### ISSUE TITLE
Editra fails to launch in 6.99.11

### ISSUE THREAD

**Issue by Sapphicatific** [renpy/renpy#1020]
Ren'Py Version:  renpy-6.99.11-sdk
OS:  Windows 8

Story:  I went to use this version of Ren'Py for the first time and it prompted me to download Editra; I did and tried to edit my script.  It gave me the screenshot attached.  The editor never popped up.

![error](https://cloud.githubusercontent.com/assets/21211342/17917306/c239ab5e-6980-11e6-8764-7c316652c940.png)

Then I tried manually starting Editra from the .exe in the file.  Nothing.  Not even an error message.  

Then I tried deleting the whole 'Editra' folder to see if Ren'Py would redownload it, but when I tried to edit a script it just said that it couldn't find the file it needed.

**Comment by renpytom** [comment]
This has been fixed in the nightly, which should become a prerelease soon.
