### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by XaDos** [renpy/renpy#1025]
Every time I use Ren'Py on a Lenovo G450, some graphic issues happen. However, the new GUI is totally broken for me:
![sin titulo](https://cloud.githubusercontent.com/assets/5888581/18295138/4a95fa1c-7475-11e6-8d0f-56359ad7288e.png)

Doesn't happen on a different PC.

**Comment by renpytom** [comment]
It looks like this is a graphic driver bug.

If you can't upgrade, try hitting ctrl-G and choosing the directX renderer.
