### ISSUE TITLE
unable to build Android on 9/11/16 nightly

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#1029]
Attempt from linux: http://pastebin.com/6aFYa5qQ
Attempt from W7: http://pastebin.com/vyLNqHpV

**Comment by renpytom** [comment]
The Linux problem appears to be the Android toolchain choking on a file named:

/home/javabean/Downloads/renpy-nightly-2016-09-11-f8644ab-sdk/rapt/assets/x-game/x-assets/x-character/x-largo/x-Prightarmslingleftarmcastsitting/x-tBL/x-WoverclockedChopsticksAtNight/x-largo_Prightarmslingleftarmcastsitting_tBL_WoverclockedChopsticksAtNight_hBL_Fnormal_eB_m1.png.orig

Which is 284 characters long. I'm guessing the Android build chain doesn't like filenames of that length, in which case the solution is to choose more reasonable filenames.

I'm not sure what the W7 problem is, as it would depend on what step of the build process you're on. Can you send me the the android.txt file. (In the nightly, it'll be in renpy-6.99.12/tmp/gamename/android.txt )

**Comment by renpytom** [comment]
Reading a little more, it looks like there's a limit of 100 characters for the filename part. x-largo_Prightarmslingleftarmcastsitting_tBL_WoverclockedChopsticksAtNight_hBL_Fnormal_eB_m1.png.orig is 101 - you should keep it under 98, since Ren'Py adds an x- to each name to ensure it doesn't conflict with names android would interpret.

**Comment by evilantishad0w** [comment]
Thank you.

**Comment by evilantishad0w** [comment]
The pastebin posted earlier *is* the W7 android.txt file.

**Comment by evilantishad0w** [comment]
<renpytom> Um... do you have a rapt/android-sdk-r<version>/tools/android.bat file?
<renpytom> Since it looks like it's missing that.
<Javabean> no, that file(actually there is a big difference between this one on debian and that one on win7) was not there in windows 7... let me redo the whole thing and see if it comes back on win7
<Javabean> no, on redoing the installation the file does NOT get created... neither do all of the other ones that are present on this debian

**Comment by renpytom** [comment]
This is probably obsolete by now.
