### ISSUE TITLE
Using from __future__ import print_function universally

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#1038]
"from __future__ import print_function" is used in a few places, but mostly the print statement is used.

Porting ren'py to Python3 probably should happen sometime in the next 3 years. As a first step, I suggest dealing with the print statements.

**Comment by renpytom** [comment]
I agree, although there's an issue of how to enable this in the compiler. Are you planning on following this with a pull request?

**Comment by jsfehler** [comment]
Which compiler are you talking about? The cython compiler?

But yes, I'll follow with a PR if nothing requires hacking at significant amounts of C code.
(lint.py seems to work fine with print_function, so there's that.)

**Comment by renpytom** [comment]
No, the python complier module, which is used to compile the code inside .rpy files. Don't worry too much about that, I can deal with it. We can also probably wait to deal with the cython code, as it's fairly simple, and I think we have to deal with it all at once.

I write a lot of python3 for work, so getting off the print statement entirely would make my life better. I'm looking forward to the PR.

**Comment by renpytom** [comment]
I made the change to the compiler yesterday, so this is done. Thanks for sending the PR, and moving Ren'Py forward.
