### ISSUE TITLE
No configurable/usable keymap on Android TV

### ISSUE THREAD

**Issue by bobobo1618** [renpy/renpy#1043]
Since Android TV devices frequently use remotes with only directional, selector and back buttons, the default keymap renders them unable to do basic things like access the menu.

I think ideally, in game the left/right buttons would be mapped to forward/back through text while the actual back button summoned the menu.

**Comment by renpytom** [comment]
I don't have an Android TV device to test with. Can you suggest additions to config.keymap?

**Comment by bobobo1618** [comment]
I would but I have no idea how to map the keys on an Android TV remote. Should it be treated as a keyboard or as a controller and how should the back and select buttons be specified?

That was my bigger problem, I should have elaborated that a bit more.

**Comment by renpytom** [comment]
Closing as old, and it seems like Android TV isn't much of a thing.
