### ISSUE TITLE
crash on iap.rpy on Android

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#1051]
With the latest nightly, tried building and launching a game with Google Play IAP enabled:
![screenshot_2016-10-10-16-04-41](https://cloud.githubusercontent.com/assets/2202152/19238835/991f1ee0-8f03-11e6-99c3-3a1308a7e2f6.jpg)

**Comment by renpytom** [comment]
This was fixed in 9522de18490e1b1673a1b14b3df4808be00e3f46, which missed the nightly due to a forgotten git push command.
