### ISSUE TITLE
Easier local (dynamic) variables

### ISSUE THREAD

**Issue by Alex-Tracer** [renpy/renpy#1056]
Right now if I want to declare "local" variable (variable that is valid only for current label) I have to use `renpy.dynamic` and then init my variable.
So the code basically looks like this:

``` renpy
label my_utility_function:
    $ renpy.dynamic('x')
    $ x = 42
    # ...
    return
```

If I want to have many local variables I can write

``` renpy
label my_utility_function:
    $ renpy.dynamic('x', 'y', 'z')
    $ x = 42
    $ y = 13
    $ z = x + y
    # ...
    return
```

That's mostly OK but probably it could be better. I don't rally like additional statement (with renpy.dynamic) and it's a bit easy to forget to update arguments of `dynamic` when new variable is added or removed.

Maybe it's possible to add some syntax sugar for the case?
I would prefer to mark a variable as "context dynamic" at the point of declaration.
One option to do that is to introduce new keyword or new syntax:

```
local x = 42
temp x = 42
dynamic x = 42
$$ x = 42
```

Another option is to introduce a naming convention when variables with special names handled diffidently. Like, "__" prefixed variable means "dynamic".
Example:

```
$ __x = 42
```

Probably this option is more difficult to implement and it may break some existing code but it does not introduce any new keywords.

**Comment by renpytom** [comment]
You almost certainly want renpy.dynamic, not renpy.context_dynamic. But I guess my question is - what sorts of functions are you writing that requires such variables in the first place?

**Comment by Alex-Tracer** [comment]
> You almost certainly want renpy.dynamic, not renpy.context_dynamic.

Oh, my bad. You totally right. I was using `renpy.context_dynamic` but `renpy.dynamic` is what I actually wanted. I'll update description.

> But I guess my question is - what sorts of functions are you writing that requires such variables in the first place?

That's mostly utility functions that can be from different parts of the game.

Example:
```renpy
label cast_mass_spell(spell):
    $ renpy.dynamic("loop_char_list", "loop_char_iterator", "loop_char", "number_of_affected_characters")
    $ number_of_affected_characters = 0
    $ loop_char_list = get_all_chars()
    $ loop_char_iterator = 0
    while loop_char_iterator < len(loop_char_list):
        $ loop_char = loop_char_list[loop_char_iterator]
        call cast_spell_single(spell, loop_char)
        if _return:
            $ number_of_affected_characters += 1
        $ loop_char_iterator += 1
    $ loop_char = None
    $ loop_char_iterator = None
    if number_of_affected_characters == 0:
        "There is nobody here"
    return
```

**Comment by Alex-Tracer** [comment]
With naming contract approach the code conversion is straightforward:
```renpy
label cast_mass_spell(spell):
    $ __number_of_affected_characters = 0
    $ __char_list = get_all_chars_in_current_room()
    $ __char_iterator = 0
    while __loop_char_iterator < len(__char_list):
        $ __char = __char_list[__char_iterator]
        call cast_spell_single(spell, __char)
        if _return:
            $ __number_of_affected_characters += 1
        $ __char_iterator += 1
    if __number_of_affected_characters == 0:
        "There is nobody here"
    return
```
Obviously, that's way it's a bit ugly. So I don't think that's a good option.

**Comment by Alex-Tracer** [comment]
With special keyword option it's straightforward in simple cases too:
```renpy
label cast_mass_spell(spell):
    dyn number_of_affected_characters = 0
    dyn char_list = get_all_chars_in_current_room()
    dyn char_iterator = 0
    while loop_char_iterator < len(char_list):
        dyn char = char_list[char_iterator]
        call cast_spell_single(spell, char)
        if _return:
            $ number_of_affected_characters += 1
        $ char_iterator += 1
    if number_of_affected_characters == 0:
        "There is nobody here"
    return
```
However if we have branches we might need to write the keyword multiple times:
```renpy
label example_3(x):
    if x:
        dyn y = 10
    else:
        dyn y = x * 10
    dyn z = y * 3
    return z
```

Also to handle loops properly RenPy will have to check if the variable is already marked as dynamic in current scope. Should not be difficult trough.

**Comment by jsfehler** [comment]
If you need reusable functions, what's the advantage to not writing it in python?

**Comment by Alex-Tracer** [comment]
There few reasons for that.
1. Quite often such functions call quite a lot of "normal RenPy" code
2. There are multiple people on the project and most of them don't know Python well
3. Migrating big parts of RenPy code to RenPy Python API often is not trivial
4. As far as I know RenPy can't really well save/restore Python state.

So if I do a loop like from the example above in Python and call RenPy label inside of loop and this label contains interactive actions then (whoops) my Python loop is broken. See also https://github.com/renpy/renpy/issues/959

**Comment by jsfehler** [comment]
You need to separate your concerns. Something along the lines of the following:
`
def cast_mass_spell(spell):
    number_of_affected_characters = 0
    char_list = get_all_chars_in_current_room()
    for char in char_list:   
         if cast_spell_single(spell, char):
            number_of_affected_characters += 1
    return number_of_affected_characters

label whatever:
    $ x = cast_mass_spell(some_spell)    
    if x == 0 :
        "There is nobody here"
    return`

seems like it would serve you much better.

**Comment by Alex-Tracer** [comment]
In your example you assume that `cast_spell_single` is Python function but it's a RenPy label.
Also `x` variable still leaks to the global context. So it still have to be declared `dynamic`.

**Comment by jsfehler** [comment]
Let's assume you can rewrite cast_spell_single to be a function.
You then cart off both functions to a utils file your non-programmers don't have to look at.

In this scenario, is there a problem x being a global variable? Every time you define x, it's getting set to the result of casting the mass spell.

**Comment by renpytom** [comment]
Sometimes you can't rewrite it into a function. For example, if there's an interaction in the middle that wants rollback, you need to use a chain of Ren'Py calls to get there. 

At the same time - I'm not 100% convinced we want to make dynamic variables much easier. They have some specific uses in Ren'Py libraries, but they're rather confusing. Recursive labels are probably a bad idea, and so it probably just makes sense to use unique names for the variables set by each label.

**Comment by Alex-Tracer** [comment]
> Sometimes you can't rewrite it into a function. For example, if there's an interaction in the middle that wants rollback, you need to use a chain of Ren'Py calls to get there.

Yes, absolutely.

> They have some specific uses in Ren'Py libraries, but they're rather confusing.

Well, if compared to traditional RenPy variables then yes. If compared to Python variables then no.

> Recursive labels are probably a bad idea, and so it probably just makes sense to use unique names for the variables set by each label.

The problem is, there is *no intention* to make they recursive. The whole idea is to avoid *accidental* clash of variable names from different pars of big project.

**Comment by Alex-Tracer** [comment]
One more possible approach: Introduce "functions". "Function" has same structure as "label" construct but
1) "func" (or other keyword) instead of `label` keyword.
2) All execution paths in function must end with `return`.
3) You can only `call` function. You can't `jump` to it.
4) All variables in the function are "dynamic" by default. However you can switch them back to usual behavior via RenPy API call.

Probably this is better than both previous approaches.

This way my very first code example will look like this:
```renpy
func cast_mass_spell(spell):
    $ number_of_affected_characters = 0
    $ char_list = get_all_chars_in_current_room()
    $ char_iterator = 0
    while loop_char_iterator < len(char_list):
        $ char = char_list[char_iterator]
        call cast_spell_single(spell, char)
        if _return:
            $ number_of_affected_characters += 1
        $ char_iterator += 1
    if number_of_affected_characters == 0:
        "There is nobody here"
    return
```

**Comment by renpytom** [comment]
Closing - I don't think any of this is happening.
