### ISSUE TITLE
transform can not be applied to text object in screen

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#1061]
```
transform fadein:
  on show:
    alpha 0.0
    linear 2.0 alpha 1.0
  on hide:
    linear 2.0 alpha 0.0

screen test1: # doesn't work
  vbox:
    align (0.5,0.5)
    text "Hello world!" at fadein

screen test2: # works
  vbox:
    align (0.5,0.5)
    at fadein
    text "Hello world!"
```

There are a number of similar consistency issues with screen elements, and it's annoying...  Should perhaps throw an exception if it's not going to work.

**Comment by renpytom** [comment]
I think the current behavior is consistent. Show and hide only work on things directly in a screen, and not stuff below those things.  (And this is, I think, the logical behavior, if you consider hide - what does it mean to have text that is in the process of dissolving out while the vbox it's in is hidden.)

**Comment by evilantishad0w** [comment]
What you're saying is, some transform behavior would be applied to that text object, but that transform would not receive the show/hide.  Is this documented anywhere?  This tripped me up in the past and just tripped up someone else in channel.

**Comment by renpytom** [comment]
Yes, the definition of at.

https://www.renpy.org/doc/html/screens.html#user-interface-statements
