### ISSUE TITLE
not everything is showing up

### ISSUE THREAD

**Issue by 4kemi** [renpy/renpy#1062]
Whenever I open Ren'py, it doesn't show anything in my projects list. If I create a new project, the titles for the themes and colors won't appear. I don't know how to select a script editor because it doesn't show any choices (and yes, I made sure I had a script editor (jEdit)). Someone please help?? I really want to be able to use this program with limited problems.

**Comment by renpytom** [comment]
Is there anything special about your computer - the language you use, anything like that?

**Comment by 4kemi** [comment]
Yes, actually. I have English as my default but Korean and Japanese as languages I can switch to.

**Comment by renpytom** [comment]
I believe this has been fixed a while back.
