### ISSUE TITLE
Issues on 6.99.12 launcher translation

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#1064]
I was working translating ren'py launcher with the recent nightly build. It mostly worked, but I found several issues.
- While translate_font can change default font, it doesn't change _default font. Thus the developer menu can't be translated because of font issue.
- "Back" in the quick menu means "rollback", on the other hand "Back" in the launcher means "return". I need to translate them into different words.
-  Several comments are commented by '#', not '##'. Therefore, they will not be included in generated translation files. Those lines are:
1. line17 in gui.rpy # GUI Configuration Variables 
2. line167 in gui.rpy # The color of button text
3. line173 in gui.rpy # The horizontal alignment of the button text. 
4. line397 in gui.rpy # Mobile devices
5. line119 in screens.rpy # If there's a side image, display it above the text. 
6. line251 in screens.rpy # Ensure this appears on top of other screens.
7. line254 in screens.rpy # Add an in-game quick menu.
8. line358 in screens.rpy # This ensures that any other menu screen is replaced.
9. line363 in screens.rpy # This empty frame darkens the main menu.
10. line424 in screens.rpy # Add the backgrounds.
11. line437 in screens.rpy # Reserve space for the navigation section.
12. line616 in screens.rpy # The page name, which can be edited by clicking on a button.
13. line671 in screens.rpy  # range(1, 10) gives the numbers from 1 to 9.
14. line143 in options.rpy ## (space)

**Comment by nyaatrap** [comment]
BTW, layout.ARE_YOU_SURE is still used? I found this line in a generated common.rpy file, but never see it in a game.

**Comment by renpytom** [comment]
This should be fixed as of 3b21ab2. The _default font can be changed by setting gui.system_font, which should be set by default when a new game is created, assuming translate_font is called. 

layout.ARE_YOU_SURE isn't used directly. It's there so that creators can use it, to get something that is translated into the native language regardless of the question.

**Comment by nyaatrap** [comment]
On the select accent and background colors screen in the create new project, change/update gui menus in the launcher, it shows a preview of new gui with translated texts. But because it doesn't use translated font, it only shows wall of tofus (blank characters) instead of actual texts.

**Comment by nyaatrap** [comment]
and minor issue

    # options.rpy:146
    old "## Icon ########################################################################'"
space before ####### line and single quote at the end of this line makes this section title weird.

**Comment by nyaatrap** [comment]
one the line 91 in front_page.rpy,

                    text "PROJECTS:" style "l_label_text" size 36 yoffset 10

is not translatable.

**Comment by nyaatrap** [comment]
Is there a way to break lines on comment translations?
Width of translated files are too wide.

![clipboard 1](https://cloud.githubusercontent.com/assets/3129985/20589238/9d72829c-b25e-11e6-8e3c-3499b57db20a.png)

**Comment by renpytom** [comment]
I can try to add something to do it. For Japanese, how many characters fit on a line together?

**Comment by nyaatrap** [comment]
I think 40, which is half of english letter width, because japanese (and chinese) character width is nearly double than english.
(I think 80 letters for one line in english?)

**Comment by renpytom** [comment]
I've uploaded a change to make this code use the same line breaking routine Ren'Py uses elsewhere. If you could test it, I'd appreciate it - I don't have the translation yet, so it would be hard for me to do myself. 

Since we're not displaying on the screen, but putting characters into a file, breaking by pixels is a non starter. There needs to be a certain number of characters on each line since the line can be displayed in a user-chosen font. 

There's also a second fix that fixes the preview of the new GUI in the launcher.

**Comment by nyaatrap** [comment]
I wanted to check it, but somewhat direct importing these files crashed my ren'py folder. I think I did something wrong, but could you add these on nightly or prerelease which I can update?

**Comment by renpytom** [comment]
I've uploaded a new nightly. (The shared fonts changes broke it.)

**Comment by nyaatrap** [comment]
Thanks, it looks good for me.
![clipboard 1](https://cloud.githubusercontent.com/assets/3129985/20648945/3ccfa488-b4f7-11e6-8d7e-01bf725c8f97.png)

**Comment by renpytom** [comment]
Okay. Let's keep this open until the translation gets merged.

**Comment by nyaatrap** [comment]
While I'm editing launcher translation, I got this error several times when I click preferences on the launcher. This is an error I frequently got, so I think I should report it.

    I'm sorry, but an uncaught exception occurred.
    
    While running game code:
      File "game/preferences.rpy", line 237, in script
      File "renpy/common/000statements.rpy", line 471, in execute_call_screen
        store._return = renpy.call_screen(name, *args, **kwargs)
      File "game/preferences.rpy", line 51, in execute
      File "game/preferences.rpy", line 51, in execute
      File "game/preferences.rpy", line 53, in execute
      File "game/preferences.rpy", line 53, in <module>
      File "game/preferences.rpy", line 44, in scan_translations
    AttributeError: 'NoneType' object has no attribute 'replace'
    
    -- Full Traceback ------------------------------------------------------------
    
    Full traceback:
      File "game/preferences.rpy", line 237, in script
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\ast.py", line 1706, in execute
        self.call("execute")
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\ast.py", line 1724, in call
        return renpy.statements.call(method, parsed, *args, **kwargs)
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\statements.py", line 145, in call
        return method(parsed, *args, **kwargs)
      File "renpy/common/000statements.rpy", line 471, in execute_call_screen
        store._return = renpy.call_screen(name, *args, **kwargs)
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\exports.py", line 2521, in call_screen
        rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\ui.py", line 285, in interact
        rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\display\core.py", line 2504, in interact
        scene_lists.replace_transient()
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\display\core.py", line 809, in replace_transient
        self.remove(layer, tag)
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\display\core.py", line 1094, in remove
        self.hide_or_replace(layer, remove_index, "hide")
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\display\core.py", line 1018, in hide_or_replace
        d = oldsle.displayable._hide(now - st, now - at, prefix)
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\display\screen.py", line 443, in _hide
        self.update()
      File "C:\Users\mizuki\Desktop\renpy-6.99.12-sdk\renpy\display\screen.py", line 578, in update
        self.screen.function(**self.scope)
      File "game/preferences.rpy", line 51, in execute
      File "game/preferences.rpy", line 51, in execute
      File "game/preferences.rpy", line 53, in execute
      File "game/preferences.rpy", line 53, in <module>
      File "game/preferences.rpy", line 44, in scan_translations
    AttributeError: 'NoneType' object has no attribute 'replace'
    
    Windows-8-6.2.9200
    Ren'Py 6.99.12.1945
    Ren'Py Launcher 6.99.12.1945

**Comment by nyaatrap** [comment]
line 1078 in screens,

        label ("Left Trigger\nLeft Shoulder")

_ is missing

**Comment by nyaatrap** [comment]
A function "translate_define" doesn't have help argument as documented.

      File "launcher/game/tl/japanese/style.rpy", line 3, in <module>
        translate_define("japanese", "gui.test", 0, help="test")
    TypeError: translate_define() got an unexpected keyword argument 'help'

**Comment by nyaatrap** [comment]
On the change theme screen in the launcher, the preview panel try to show translated buttons, but it shows blank characters because font is missing. This problem only happens with a project that uses legacy theme gui.

**Comment by renpytom** [comment]
I've added a new gui.language variable that sets style.default.language, and updated tl/japanese/style.rpy to set it.

This added two new comments to gui.rpy  that need to be translated.

**Comment by nyaatrap** [comment]
Thanks, translation is done.

**Comment by renpytom** [comment]
Thank you for working with me on this. Because of this, Ren'Py will be better - not just in Japanese, but in all languages. 

I'm closing this issue now.
