### ISSUE TITLE
Getting errors installing AndroidSDK through android.py

### ISSUE THREAD

**Issue by SandipanGuha** [renpy/renpy#1069]
## First issue:
```
C:\Users\Sandipan Guha\Documents\pyworks\rapt>python android.py installsdk
Traceback (most recent call last):
  File "android.py", line 10, in <module>
    import rapt.interface as interface
  File "buildlib\rapt\interface.py", line 8, in <module>
    import plat
ImportError: No module named 'plat'
```
- fixed by updating replacing `import plat` with `import rapt.plat as plat` 
**Success**

## Second issue:
```
C:\Users\Sandipan Guha\Documents\pyworks\rapt>python android.py installsdk
Traceback (most recent call last):
  File "android.py", line 11, in <module>
    import rapt.install_sdk as install_sdk
  File "buildlib\rapt\install_sdk.py", line 240
    os.chmod(plat.path("android-sdk/tools/android"), 0755)
                                                        ^
SyntaxError: invalid token
```
- `platform.win32_ver()` not returning `True` in _plat.py_. Yet I'm using Win10 x64
 **Failed**

- tried importing [win32_ver.py](http://bugs.python.org/file38102/win32_ver.py) and replacing `if platform.win32_ver()[0]:` with `if platform.win32_ver()[0] or win32_Ver.win32_ver()[0]:` in _plat.py_, still returning `False` 
**Updated Console:** 
```
C:\Users\Sandipan Guha\Documents\pyworks\rapt>python android.py installsdk
('10', '10.0.10240', 'SP0', 'Multiprocessor Free')
Traceback (most recent call last):
  File "android.py", line 11, in <module>
    import rapt.install_sdk as install_sdk
  File "buildlib\rapt\install_sdk.py", line 240
    os.chmod(plat.path("android-sdk/tools/android"), 0755)
                                                        ^
SyntaxError: invalid token
```
**Failed**

**Current result:** _Installation Failed_

**Comment by renpytom** [comment]
Are you using python3? Only python 2 is supported at this time.

**Comment by SandipanGuha** [comment]
Is support for Python 3+ under development? If not, can you please suggest effective way to port python app to Android for Python 3+?

**Comment by renpytom** [comment]
Only python 2 is supported at this time. That'll change sometime in the future, but it's not a priority at the moment.

**Comment by ABDABADO** [comment]
> ## First issue:
> ```
> C:\Users\Sandipan Guha\Documents\pyworks\rapt>python android.py installsdk
> Traceback (most recent call last):
>   File "android.py", line 10, in <module>
>     import rapt.interface as interface
>   File "buildlib\rapt\interface.py", line 8, in <module>
>     import plat
> ImportError: No module named 'plat'

I have the same problem but I do not quite understand what you mean change the plat please elaborate on this more and if you have a file can you attach it please thanks so much

**Comment by ABDABADO** [comment]
> Are you using python3? Only python 2 is supported at this time.

Iam having problem on first issue my file is normal like correct and i still get the same error
