### ISSUE TITLE
decode unicode for player name in inserted text

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#1072]
Not sure if the name display is a feature, having trouble tracking down the documentation...

```
define e = Character("Eileen")
define r = Character(u"Rene\xe9")

...

"I'll say hello to [e]." # shows "Eileen"
"Then I'll see what [r] has to say." # exception
```

**Comment by evilantishad0w** [comment]
```
$ shi = u"Shin\xe9"
"Then I'll see what [shi] has to say." # also exception
```

**Comment by renpytom** [comment]
Memo to self: A character object should unicode() to the current value of its name.

**Comment by remeranAuthor** [comment]
Okay! I apologize.  I'm the person in IRC who was having this issue last night. I understand now that [characterObject] was never the correct syntax and it's actually a little peculiar that it works at all for characters with names that are all ascii. I did [shi.name] and it works with no errors, whereas [shi] doesn't.

I'll just replace all [shi] with [shi.name] in my script for now! Thank you all so much for your help!
