### ISSUE TITLE
suggestion for Movie()

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#1079]
It'd make Movie() slightly less confusing to creators if the "channel" parameter were made optional, and would create a randomly-named unused channel if omitted.  (This might result in the creation of a lot of redundant channels in a game with a lot of movies, but the creator can specify a channel in that case.)

**Comment by Kuroonehalf** [comment]
Additional request/suggestion for Movie(): allow movie play source to be an image displayable.

I'm currently working on some UI elements that are deforming shapes, animated by using movie masks, where it's wholly unnecessary for the displayable being masked to be a movie as well. I'd wager it's also more resource intensive as a result than it should need to be.

**Comment by renpytom** [comment]
Kuroonehalf, we already support what you want, using the AlphaMask displayable. The only reason Movie has a mask parameter is that the two movies need to be in lockstep.
