### ISSUE TITLE
show before scene change not taking place

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#1084]
```
eileen mouthopen "Goodbye."
show eileen mouthclosed
scene newscene
with dissolve
```
Adding 'pause 0' before 'scene' is a workaround.

**Comment by xavi-mat** [comment]
If I understand it correctly, this is the expected behaviour.

> The show statement does not cause an interaction to occur. For the image to actually be displayed to the user, a statement that causes an interaction (like the say, menu, pause, and with statements) must be run.
https://www.renpy.org/doc/html/displaying_images.html#show-statement

**Comment by evilantishad0w** [comment]
I'd thought the above example code showed the image change in earlier versions of Ren'py, but apparently not.  *shrug*

**Comment by renpytom** [comment]
It's always been this way. 

```
eileen mouthopen "Goodbye."
show eileen mouthclosed
with None
scene newscene
with dissolve
```

Is probably the preferred way to write this, though

```
eileen mouthopen "Goodbye."
show eileen mouthclosed
scene newscene with dissolve
```

Is a more concise equivalent.
