### ISSUE TITLE
update failure from preferences screen

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#1085]
In launcher, clicking 'update' when 'preferences' is shown (such as, when you've just changed update channels) produces a confusing error:
```
NameError: global name 'path' is not defined
```
If difficult to fix exact issue, suggest blocking updating straight from preferences.

**Comment by renpytom** [comment]
I'm unable to repeat this. 

Can you send me the update/log.txt file, which has the full error message in it?

**Comment by evilantishad0w** [comment]
[log.txt](https://github.com/renpy/renpy/files/632980/log.txt)

**Comment by evilantishad0w** [comment]
Inducing error, using W7 x64:

(1) Start launcher.
(2) Click "Preferences"
(3) Click "Update Channel", switch from Release to Nightly (or vice-versa)
(4) Without clicking "Return", click "update".
(5) Accept update, error occurs when update is nearly complete.
