### ISSUE TITLE
Key pressing issues on gamepads

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#1086]
There are key pressing issues on gamepads:

- config.pad_bindings["pad_lefttrigger_pos"] = [ "skip" ] only activates skip, but never stops.
- D-keys navigations only move one focus on one pressing. To navigate far buttons, it requires to be pressed many times.

**Comment by renpytom** [comment]
For the first one, I've added pad_lefttrigger_zero, and a stop_skipping binding. So you can do:

```
init python:
    config.pad_bindings["pad_lefttrigger_pos"] = [ "skip" ]
    config.pad_bindings["pad_lefttrigger_zero"] = [ "stop_skipping" ]
```

I don't plan to change the second one - I don't like think the gamepad should get key repeat. It's something a UI needs to be designed for.
