### ISSUE TITLE
Request: im.matrix.brightnesscutoff(alpha,invert=False)

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#1091]
This function would receive a float argument 'alpha' between 0 and 1, and make any pixel with brightness bellow that number pure white, and any pixel above that pure black.

Invert would switch the whites and blacks.

Here's a practical example of the intended behavior.
Using this as our base image
![gradient](https://cloud.githubusercontent.com/assets/12227163/21081547/42d58e0e-bfc1-11e6-9e05-2dde27fcee0c.jpg)
 
If we did `im.MatrixColor("mask.png", im.matrix.brightnesscutoff(0.5))` we would get:
![cutoff05](https://cloud.githubusercontent.com/assets/12227163/21081510/a826b93c-bfc0-11e6-9287-67e9c395b3e6.jpg)

And `im.MatrixColor("mask.png", im.matrix.brightnesscutoff(0.8))` we'd get:
![cutoff08](https://cloud.githubusercontent.com/assets/12227163/21081541/ff23e5f2-bfc0-11e6-90fe-f280567b7b9a.jpg)

This, coupled with im.AlphaMask() should allow devs to do things such as curved health bars, or other progressive cutoff image elements that aren't straight, which is something I've personally been wanting for a while.

**Comment by renpytom** [comment]
This isn't possible with matrices.
