### ISSUE TITLE
Setting config.quit_action to ui.gamemenus always open up the save screen

### ISSUE THREAD

**Issue by DragoonHP** [renpy/renpy#1097]
No matter what value is provided for ui.gamemenus, it will always open the save screen

```
config.quit_action = ui.gamemenus("_quit_prompt")
config.quit_action = ui.gamemenus("_quit_prompt_dummy_name")
config.quit_action = ui.gamemenus("_main_menu_prompt")
```
all open the save screen,
(It worked perfectly in v6.99.11.1749)

**Comment by renpytom** [comment]
This is fixed in git, and I'll be getting a 6.99.12.1 into prerelease ASAP.

That being said, I'd suggest that:

```
define config.quit_action = Quit(confirm=True)
```

or 

```
define config.quit_action = ShowMenu("my_screen")
```

are the modern way of doing the same thing, that doesn't involve the use of internal labels.
