### ISSUE TITLE
Python 3 porting

### ISSUE THREAD

**Issue by caryoscelus** [renpy/renpy#1098]
Is anybody currently working on this? I'll try it if nobody else does.

Do you plan to switch quickly or with a transition period? I.e. should the porting effort be compatible with both versions (e.g. using six) or only py3?

**Comment by caryoscelus** [comment]
Closing this in favour of more specific code discussion in https://github.com/renpy/renpy/pull/1100

**Comment by kibertoad** [comment]
I believe we still need an issue to track the progress, for Issues and PRs serve different purposes.

**Comment by Zenadix** [comment]
+1, I think it's important to have Python 3 compatibility.

**Comment by monospacedmagic** [comment]
This Ren'Py Python 3 port based on https://github.com/renpy/renpy/commit/01f536fc698ee5cf68f512e8125469573afac0be appears to work already: https://github.com/nx-python/renpy/tree/renpy-py3

**Comment by kibertoad** [comment]
This is more relevant than ever, given https://pythonclock.org/
Are there any plans to drop Python 2 support at any point?

**Comment by renpytom** [comment]
Closing, now that Ren'Py 8.0 has nightlies being build.
