### ISSUE TITLE
imagebutton 'focus_mask True' doesn't work at all on Android OS

### ISSUE THREAD

**Issue by lukurenpy** [renpy/renpy#1105]
Hello,
I noticed that `focus_mask` doesn't work at all on Android OS. Anywhere I tap on the screen, it will select the last added imagebutton, this might be because of `focus_mask` not working.
On desktop `focus_mask True` works as intended, I can select by clicking any imagebutton.

Possible related information:
In Ren'Py's documentation in Android section there is this: 

> Ren'Py can't handle transparency in buttons and imagemaps. (This is due to performance problems on some devices with the display modes needed to support deciding which pixels are transparent.)

So it might be related.

Device used for testing: OnePlus X (Snapdragon 801, Quad-core 2.3 GHz Krait 400 (ARM architecture), Adreno 330)

Is there a workaround for this issue on Android?

**Comment by renpytom** [comment]
Nope. It's a limit to the Android and iOS platforms.
