### ISSUE TITLE
Issue with ALSA when trying to run Ren'Py 6.99.11 or higher on Travis CI

### ISSUE THREAD

**Issue by NumberA** [renpy/renpy#1109]
Hey! I'm trying to integrate a Ren'Py project here on GItHub with Travis CI as descibed in [this](http://fuckyeahrenpy.tumblr.com/post/115884786323/automatically-testing-a-renpy-game-using-travis) tutorial. Unfortunately, when I try to build it fails with "Exception: ALSA: Couldn't open audio device: No such file or directory".

To troubleshoot, I reached out to [ExcaliburZero](https://gist.github.com/ExcaliburZero), author of the original tutorial, and he suggested I try dropping back to an older version of Ren'Py (he suggested 6.99.3). I did so, and that fixed the ALSA error, but then I got a bunch of Expression Expected lint errors.

I was able to repro these Expression Expected errors on an Ubuntu VM by running my project (available on GitHub [here](https://github.com/NumberA/ProjectGaymore)) through Lint from the 6.99.3 Ren'Py SDK. I ran Lint from command line using **./renpy.sh "../ProjectGaymore/" lint**. When I ran the same command from the 6.99.12 Ren'Py SDK it completed without errors (printing some statistics to the terminal and then closing).

The final stage of my investigation was to return to the Travis CI tests and increment the Ren'Py SDK version I was running them against until the error switched from lint errors to ALSA exceptions. That happened between 6.99.10 and 6.99.11.  My test logs are available [here](https://travis-ci.org/NumberA/ProjectGaymore/builds) if they're useful.

From what I can tell, the Travis CI test environment is 	Ubuntu 12.04 LTS Server Edition 64 bit ([source](https://docs.travis-ci.com/user/ci-environment/)). Is that an OS that we can expect Ren'Py to work in?

Please let me know if you need any more information or if there's anything I can do to help get to the bottom of this.

**Comment by renpytom** [comment]
So, I just checked Ren'Py, and if you do:

export SDL_AUDIODRIVER=dummy

then it seems to run without using ALSA. The expression errors come from trying to run new code on an older Ren'Py - it all corresponds to new features that aren't supported by the old version of the engine.

**Comment by NumberA** [comment]
Thanks for getting back to me! In which file do I add the export line?

**Comment by renpytom** [comment]
I don't know. An environment variable is a standard unix concept, so I assume Travis supports them somehow, but I don't know exactly how.

**Comment by ExcaliburZero** [comment]
You should be able to add the export line in the `.travis.yml` file. It should probably go in the script section, and be listed above the command where you run renpy lint.

**Comment by NumberA** [comment]
OK! If it's adding an environment variable to a .travis.yml then I can Google that :) I likely won't get a chance to work on this before the weekend, but when I do I'll update this thread with the results.

**Comment by NumberA** [comment]
It worked :D Here's the Tumblr post where ExcaliburZero sets out how to add Travis CI support ot a Ren'Py project on GitHub and [here ](https://gist.github.com/NumberA/588baf4398c89d4cd64c40cd718e0ed5)is the updated .travis.yml
