### ISSUE TITLE
Scaling window make text in Help goes out-of-frame (new GUI)

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1113]
1280x720 (TAB) ![screenshot0001](https://cloud.githubusercontent.com/assets/24704640/21969489/6536fcd8-dba7-11e6-93fa-f33f521136d3.png)
1251x703 (ideal) ![screenshot0004](https://cloud.githubusercontent.com/assets/24704640/21969501/7f3b6c0e-dba7-11e6-88d6-e74c007c0ab3.png)
1176x662 (CTRL, H) ![screenshot0002](https://cloud.githubusercontent.com/assets/24704640/21969538/b733b10c-dba7-11e6-98fd-88cc1b57c777.png)
960x540 (TAB, H, g all over the text) ![screenshot0003](https://cloud.githubusercontent.com/assets/24704640/21969566/ebf7905c-dba7-11e6-9368-4b910e4d8f09.png)

**Comment by renpytom** [comment]
Heh. I was working on this for a while when you filed the report. Thank you, though - this is a really good catch.
