### ISSUE TITLE
How can i import and use python package(standrd and 3rd) in Renpy?

### ISSUE THREAD

**Issue by decemer** [renpy/renpy#1115]
How can i import and use python package(standrd and 3rd) in Renpy?
---------------
for example
`init python: import socket`
how to store in game file folder?
can it run in PC,IOS,Android?

**Comment by renpytom** [comment]
If it's present in Ren'Py, that works. You need it on two lines:

```
init python:
    import socket
```

Only do imports in init python blocks. It will work on all platforms, although individual modules may not work on some places. (For example, you need to enable the NETWORK permission on Android to access the internet.)

To include a pure-python module that isn't included with Ren'Py, drop the .py file into the game directory.

**Comment by decemer** [comment]
Thanks for the clarification
