### ISSUE TITLE
Graphical trash on the next lines using outlines at say_dialogue

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1117]
Watch gif example
![1](https://cloud.githubusercontent.com/assets/24704640/22206026/1e204440-e182-11e6-8a4f-4a29ff83681f.gif)
graphical trash appears only from this outlines code
```
init -1 style say_dialogue:
    xpos 220
    xanchor gui.text_xalign
    xsize 840
    line_spacing 3
    ypos gui.text_ypos
    justify True
    text_align gui.text_xalign
    layout ("subtitle" if gui.text_xalign else "tex")
    outlines [(2, gui.text_outline_color, 0, 1),(1.5, gui.text_outline_color, 0, 0)]
```

**Comment by renpytom** [comment]
Check out the "Slow Text Concerns" section here:

https://www.renpy.org/doc/html/text.html#slow-text-concerns

**Comment by Ria-kon** [comment]
Thanks
