### ISSUE TITLE
Renpy.exe won't run in windows if path name has long line of japanese text 

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#1119]
c:\単語\renpy.exe is fine to run on Windows10, But when path name contains long Japanese letters like c:\長い長い長文をフォルダ名にして\renpy.exe, it will not run. 
Tested with 6.99.12.2.2029.

**Comment by nyaatrap** [comment]
It looks more critical problem, since window's default folder name '新しいフォルダー' ('New folder' in English) is considered invalid name for ren'py.

**Comment by renpytom** [comment]
Is there any feedback at all - a traceback or anything like that - or is this a failure to start at the exe level?

**Comment by nyaatrap** [comment]
It's completely failed at the exe level in c:\新しいフォルダー\renpy
![clipboard-1](https://cloud.githubusercontent.com/assets/3129985/22497205/3c7ec4c6-e893-11e6-8b9e-d8c28b50c36c.png)

**Comment by renpytom** [comment]
Just to double-check, your system encoding is set to Japanese, right? (I'm assuming yes, but I want to be sure before I get started on the fix.)

**Comment by nyaatrap** [comment]
Sure. It's not just me, the same issue is reported form other two users.

**Comment by renpytom** [comment]
I'm unable to repeat this on Windows 10, using a Japanese non-unicode language. (Or under other circumstances.) I'd like to be responsive here, but I'm not sure what I can do, exactly, without any idea of what could be causing this problem.

![image](https://cloud.githubusercontent.com/assets/379804/22537541/5288cf28-e8c0-11e6-92e4-b05147bc4cad.png)

**Comment by nyaatrap** [comment]
Weird. I set my OS language into English, It works.
![clipboard-1](https://cloud.githubusercontent.com/assets/3129985/22538393/6b0c42ba-e955-11e6-97b3-eb340fc2007d.png)
Then I set back my OS language into Japanese, I doesn't work.
![clipboard-2](https://cloud.githubusercontent.com/assets/3129985/22538401/7e53f20a-e955-11e6-8b2a-cdfcebb28a80.png)

**Comment by renpytom** [comment]
Can you tell me how to set my OS language to Japanese? I already have the non-unicode language set, but I don't know how to set the interface language.

**Comment by nyaatrap** [comment]
On settings menu in Window10 (shown in the above screenshot), I added US English by hitting '+add language' button, then downloaded its language pack. After that, chosen a new language then set as default.

**Comment by renpytom** [comment]
I landed a fix for this, as seen above. I think it was a bug in dirname on windows - weirdest thing. The function is so simple, it's easier for me to just reimplement it than to figure out what's going on. I'll be in the next nightly, which might be late, since I'm too tired to take windows out of Japanese mode, and I have no idea if Ren'Py will build there.

**Comment by renpytom** [comment]
I'm pretty sure this has been fixed, so I'm closing the issue.
