### ISSUE TITLE
Font length randomly changes with "extend"

### ISSUE THREAD

**Issue by Archer222** [renpy/renpy#1122]
I attached a gif that showcases this issue, whenever I used the function "extend" with the new UI, the font changes. I tried different fonts and font sizes and the issue seems to persist. 
edit: tested some more, bug only occurs if you rescale the window. Original window size works perfectly.

![53971ff477440aa50d82a5f58d86a79d](https://cloud.githubusercontent.com/assets/19827967/22587609/a570a862-ea02-11e6-9a19-2e61bc96c00c.gif)

**Comment by XelaPy** [comment]
Make sure that whatever holds the text has fixed size. That might fix this.

**Comment by renpytom** [comment]
Actually, this is very likely the issue that led to the adjust_spacing property.

https://www.renpy.org/doc/html/style_properties.html#style-property-adjust_spacing

Giving it adjust_spacing False will cause the text to jump around when the window is scaled, but not during extend. Pick your poison - there's no way to make things work right in both cases.
