### ISSUE TITLE
console suggestions

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#1126]
* Allow Shift-O to operate when an exception has occurred

* Run the console in the "console output window" instead of in the game when the console output window is turned on

**Comment by XelaPy** [comment]
Maybe preserve history after Shift+R as well?

**Comment by nyaatrap** [comment]
I'd support this suggestion. The console is one of the best debugging tool in ren'py, but it's hard to work when exception is occurred.

**Comment by renpytom** [comment]
While it might seem obvious to run the console in the console window, that would be a whole new code path. I've improved the current console quite a bit, so I'm going to close this bug now.
