### ISSUE TITLE
Auto-advance text not working

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#1132]
I had a report from an user on Steam, so I tried myself on several of my games.
I tried with games built in the last few Ren'Py versions (from 2016 onward) and indeed in none the feature works. I try changing the text-speed, auto-advance, etc. Then I go back to the game, but the text never advances.
I even tried with "The Question" game... same behavior. The text never advances automatically to the next dialog line.
I'm missing something obvious? otherwise I think it's bug :)

**Comment by vollschauer** [comment]
Yes, I can remember that by some of the games I played on Steam didn't work the AFM, but I just tested it and it works. How do you toggle the afm in "The Question" ? there is no quick menu to do so!? 
That was the latest change made to AFM: https://github.com/renpy/renpy/pull/1108
Can you check "The Tutorial" I tested it there....

**Comment by jacknorton** [comment]
In the question just used ESC key and accessed preferences screen from there :)
Tried in the tutorial, same behavior.
I am using Windows 7 BTW. Maybe it's related to OS? not sure, but here doesn't work on ANY game I've tried, both on Steam or not.

**Comment by vollschauer** [comment]
Still strange, well I'm on Linux. About the preferences screen, I don't see any toggle of afm ;)
I know I don't need to tell you about config.default_afm_enable and _preferences.afm_enable,
but I'm doing it anyway. Maybe Tom knows whats going on ....
![image](https://cloud.githubusercontent.com/assets/5165216/22924123/42526248-f2a4-11e6-94c6-136d24dc8e14.png)

**Comment by renpytom** [comment]
Hm... it looks like AFM is not turned on by default in The Question, for some reason. I'll look into it.

**Comment by jacknorton** [comment]
Ah I wasn't aware there was a config :D I thought that if the option was in the preferences screen, was enabled by default. That might explain it then :)

**Comment by jacknorton** [comment]
Wait looking in Ren'Py docs:
"Controls the default state of the afm_enable preference. If False, auto-forward-mode is disabled by default. If True, it is enabled by default. If None, the afm_enable preferences is ignored. (Auto-forward will occur when the auto-forward speed is non-zero.)"
Since in my options file there's no config.default_afm_enable, I thought the default should happen, so that if the auto-forward speed in options is not zero, should work?

**Comment by renpytom** [comment]
You need to explicitly set config.default_afm_enable to None. This is done by the compatibility code when an older version released game is used with a newer Ren'Py, but you have to do it yourself if the script_version is not set.

This wasn't documented as an incompatible change. It is now.
