### ISSUE TITLE
RenPy freezes when drawing specific canvas lines

### ISSUE THREAD

**Issue by bitsawer** [renpy/renpy#1135]
While implementing a custom displayable for drawing some visuals I noticed that certain coordinates will cause the application (and the drawing code) to hang up and freeze. The simplest test case is this:

        def render(self, width, height, st, at):
            render = renpy.Render(10, 10)
            canvas = render.canvas()
            canvas.line("ff0", (0.0, 0), (0, 0)) #Works
            canvas.aaline("ff0", (0.0, 0), (0, 0)) #Works
            canvas.line("ff0", (0.9, 0), (0, 0)) #Hangs
            canvas.aaline("ff0", (0.9, 0), (0, 0)) #Works
            canvas.lines("ff0", False, [(0.9, 0), (0, 0)]) #Hangs

Only .line() and .lines() seem to be affected, interestingly .aaline() works fine.

Might be some kind of floating point rounding issue that causes an infinite loop in the drawing code? I guess it might be caused by the underlying Pygame rather than RenPy itself.

Rounding all coordinates to ints before passing them to the drawing code seems to fix the issue, but it would be nice not to have to worry about that.

**Comment by renpytom** [comment]
Fixed by renpy/pygame_sdl2 ce2578c.
