### ISSUE TITLE
Possibility to mark variable for forced save

### ISSUE THREAD

**Issue by alexei-osipov** [renpy/renpy#1138]
**Preface**
Probably everyone who made a decent game with RenPy is aware that RenPy does not save (includes into game save file) variables that have same value. To check if value is same Renpy just checks if object is same or not via Python "is" operator ([see `get_changes()` in python.py](https://github.com/renpy/renpy/blob/67c893fb41089c24b6b572b10cedf26b134aff3a/renpy/python.py#L121)). That works fine for numbers and strings but anything more complex (like lists, sets, custom object) is not saved even if the object was modified.

Example:
```RenPy
init:
    define inventory = ['rusty_sword']
label add_shield:
    $ inventory.append('wooden_shield')
```
If you modify the list by calling `add_shield` and then try to save a game the list will not be saved because the object reference is same as before. After game load the list value will be `['rusty_sword']`.

Common workaround for this problem is to move declaration of such variables to a labels that executes after game `start`.
```RenPy
label init_variables:
    $ inventory = ['rusty_sword']
    return
label add_shield:
    $ inventory.append('wooden_shield')
label start:
    call init_variables
    jump real_start
```
Problems with this workaround:
- This makes game initialization sequence more complex.
- This forces you to put initialization of some variables to different places. Not to the places where it's logical to define certain variable.
- There is no initial value (value that is accessible before `start`). This causes issues if you plan to use something like `renpy.call_replay` (you have to reproduce initialization).

**Suggestion**
Add a way to explicitly mark a variable to be included in save file.
Probably the best if we had
1. a keyword to mark such variables, like "persist"
```RenPy
init:
    define persist inventory = ['rusty_sword']
```
2. RenPy python API method. Something like `add_to_persist`:
```RenPy
init:
    define inventory = ['rusty_sword']
    $ renpy.add_to_persist('inventory')
```

Note: keyword and method name are just examples.

Note: there a way to achieve same as 2 in RenPy already via
`renpy.game.log.ever_been_changed['NAME_OF_MY_VARIABLE'] = True`
however it's not part of public API so it's kind evil.

**Comment by renpytom** [comment]
You're looking for the default statement, which was added a few releases ago. It does everything you want, I think. (I woud link the docs, but I am on my phone.)

**Comment by alexei-osipov** [comment]
Hmm, that's funny because I've checked docs for `default` keyword just before posting this issue. I've got impression that this is not related to my issue :/

**Comment by renpytom** [comment]
I hate to say it, but I think your impression is wrong. The default keyword sets the variable - if it hasn't been set before - in all relevant circumstances. Before start, before replay, and even after a load. Since it's set after the end of the init phase, the variable will be marked as changed and saved. 

Have you tried it, and is it going wrong somehow? The default statement should be exactly what "define persist" is above.

**Comment by alexei-osipov** [comment]
Sorry for long delay with answer.

I've tried `default` and, sadly, it works exactly as you described but not as I need.

Simple example:
```renpy
default x = []
init 1000:
    $ x.append('hello')
```
fails with error (because `x` is not defined).

However
```renpy
define x = []
init 1000:
    $ x.append('hello')
```
works fine but `x` is not included into save.

So I still have to call `$ x = []` after game start to make it included into save files.

**Comment by renpytom** [comment]
You could also do:

```
default x = [ 'hello' ]
```

Or for more complicated stuff:

```
init python:
    x_default = [ ]
    for i in range(100):
        x_default.append(i)

default x = x_default
```

**Comment by alexei-osipov** [comment]
```
default x = [ 'hello' ]
```
The actual code in my case is much more complex. `x` is a custom object with may properties. And I want to have it accessible during "init phase" (i.e. before "start"). Right now I can't do that.

As workaround I had to partially split my object in two parts. One is immutable and accessible during `init` phase and second part is mutable and populated after "start". The problem is such split is not very logical in my case. And I have not just one but dozen of such objects all split into two parts. Just because I can't tell RenPy "please include this variable (containing custom object) into save file even if it looks like it's value was never changed after init (because I modify object fields not object reference itself)".
