### ISSUE TITLE
how to update screen?

### ISSUE THREAD

**Issue by LuoboDcom** [renpy/renpy#1149]
The question has been asked in 
[https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=42962&p=446998#p446998](https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=42962&p=446998#p446998)

Simplified question like :  click the button (or other view ),then update the button to a image.

My question  is click a frame ( area), then update it .( please look the url , there has images)

**Comment by renpytom** [comment]
This isn't a bug in Ren'Py. Please ask your question in a new thread on LSF - when it's at the bottom of an answered topic like that, people may not find it to help you.
