### ISSUE TITLE
Unnecessary showing of the saybox

### ISSUE THREAD

**Issue by barsunduk** [renpy/renpy#1150]
I have some characters with `window_background=None` ("centered" for example). RenPy shows me empty `saybox` every time, then hides it.
If I do `window hide`, then show text, then `window auto` - all works. But add a lines for EACH character phrase - I think, it's not correct.
P.S. This bug was not present in old GUI
P.P.S. I'd like to see `quick_menu=True/False` parameter in the Character(...)

**Comment by renpytom** [comment]
This isn't a bug. You can revert to the old GUI's behavior by setting config.window = "hide" in options.rpy.

The quick menu isn't related to the character, so it would be hard to add quick_menu=False to Ren'Py. I'll think about it, though. My general feeling is the quick menu should be up all the time, even during transitions and dialogue.

**Comment by barsunduk** [comment]
Thank you very much!
