### ISSUE TITLE
Console output crashes (probably unicode bug?)

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#1154]
[code]
-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 230, in script
    python:
  File "C:\- indie dev -\games\renpy\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\- indie dev -\games\renpy\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 246, in <module>
    for new_item in rpg.create_token_list(library,[("gen/F_Coal",5,90,15),("gen/R_glittering_dust",5,90,15),("gen/R_animal_blood",5,90,15),("gen/R_animal_feather",5,90,15),("gen/R_sugar",5,90,15),("gen/R_salt",5,90,15),("gen/R_animal_bone",5,90,15),("gen/R_bear_blood",5,90,15),("gen/R_springwater", 5,90,15),("gen/M_copper_ore", 6,90,15),]):
  File "toa_rpg_framework/Core.py", line 84, in create_token_list
  File "toa_rpg_framework/Core.py", line 77, in create_item_token
  File "toa_rpg_framework/Item.py", line 118, in __init__
  File "toa_rpg_framework/Core.py", line 121, in get_reference_item
  File "toa_rpg_framework/Core.py", line 63, in create_item
LookupError: unknown encoding: cp850

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
 0.6.0
[/code]
The line in question is just a simple:
print ("Used class definition for %s" % id_string)
even if I remove that, it crashes with same encoding error a few lines later. Before this was working fine, I think has something to do with unicode support? Thanks

**Comment by renpytom** [comment]
Ren'Py doesn't ship with the cp850 codec, so you'll have to change your code not to use it. I don't believe that this is actually a bug in Ren'Py itself, however - just the usual sort of changes you have to make to plug two bits of software together.

**Comment by jacknorton** [comment]
Hi, sorry to re-open this. But I think it's not related to encoding at all. I use console to print debug info, and even a very simple function like this:
`    def MoraleUpdate():
        EnemyRatio=1;PartyRatio=2
        print ("%s %s" % (EnemyRatio,PartyRatio))`
returns that unknown encoding. But I'm just trying to print two numbers, nothing fancy! :)
I tried to change %s to %d or any other combinations but still crashes. Thanks
