### ISSUE TITLE
Quickmenu disappear after using renpy.retain_after_load()

### ISSUE THREAD

**Issue by zedraxlo** [renpy/renpy#1160]
If I define a screen like:
```
screen test():
    textbutton "return" action Return()
```

then write these in script:
```
    "Hello, world."
    $ renpy.retain_after_load()
    call screen test
```

When entering that screen and save game, then go back to main menu and load game, the quickmenu will disappear.

**Comment by renpytom** [comment]
Can you include a fuller script, please? Is the code at the bottom right after label start, or are you manipulating the quick_menu variable at all.

**Comment by zedraxlo** [comment]
I created a new project and insert these code after "Hello, world.", that's all.
