### ISSUE TITLE
setting config.developer="auto" no longer generates the script_version.txt

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#1164]
In 6.99.12.4, if you set config.developer to "auto", the script_version.txt file is never generated, resulting in all games being set in developer mode when end user plays it.
Before I thought was a mistake on my part because I used:
build.classify('**.txt', None)
however even after removing that line, the behavior was still the same. Thanks

**Comment by renpytom** [comment]
As a quick workaround, do:

```
define build.script_version = True
```
