### ISSUE TITLE
style default: properties changes transform behavior

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#1171]
Sorry I couldn't make a simple demo to replicate this bug. But I confirmed when I use:

    style default:
        properties gui.text_properties()

My transform's animations become buggy, as if sprite's positions are reset before promoting new animation.
When I commented out this line, my transforms work as expected.
Do you have any idea why this line changes transform behavior?

**Comment by renpytom** [comment]
Sorry for the loooong delay. 

I don't know what the answer to this is, but I can guess. If you defined gui.text_xalign, that will set the xalign properties of every displayable. If a transform is not directly controlling xalign, then this will cause a problem. 

I'm disabling the ability to set gui.text_xalign.
