### ISSUE TITLE
"Ren'py has stopped working" when trying to run .exe

### ISSUE THREAD

**Issue by SomeGuyIGuess** [renpy/renpy#1173]
Title pretty much says it all. I use Windows 10 and am trying to run the latest version of Ren'py (6.99.12.4.2187, to be exact). If any other details or info are needed, let me know please. I want to get back to coding!! ;_;

**Comment by SomeGuyIGuess** [comment]
To give an update on this situation of mine, I restarted my computer in Safe Mode to see if Ren'py would open. It DID in fact open. In the settings of Ren'py, I unchecked "Hardware Rendering" and exited the program. After restarting my computer normally, I ran the program and it WORKED.

Perhaps this must mean by graphics card received a driver update and caused this issue? I don't know THAT much about computers so I may very well be completely incorrect. If anyone else is having this issue, this may help I suppose.

Even though the situation is fixed, I do wonder if having "Hardware Rendering" unchecked will have an impact on my VN. If anyone knows, I'd love some info on that.

**Comment by renpytom** [comment]
Sorry about the long delay. This is very unlikely to be a problem with Ren'Py, but rather something about your computer and drivers.

The lack of hardware rendering will slow Ren'Py down, and may also cause certain things to be rendered incorrectly.
