### ISSUE TITLE
Blocking when sound plays.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1174]
https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=43738

**Comment by renpytom** [comment]
Can't repeat.

**Comment by morganwillcock** [comment]
This might be the same blocking issue I’m seeing, where the first time a sound plays I get a large delta time between frames. Is there any testing or log output that I could provide, which might be helpful?

**Comment by renpytom** [comment]
Can

**Comment by morganwillcock** [comment]
I can't recreate it 100% of the time, but I think it isn't the audio playback that causes blocking. It's easiest to test on Linux by clearing the disk caches with `echo 3 | sudo tee /proc/sys/vm/drop_caches` once a game has started and then cause some disk activity. Playing audio seems to cause the frameskips some of the time, but you can exaggerate the effect by doing something like installing package updates while an animation is running with redraw 0.

I've tested on the pre-release and the result is the same, but both the release and pre-release do seem to run smoother than when I was looking at this issue a year ago.

**Comment by renpytom** [comment]
I've had several tries over this week, and I can't tell what it is. What does your animation look like. I'm currently trying a move, but it's possible some other ATL is causing it. I'm really stumped here, as I've been unable to repeat the problem.

**Comment by morganwillcock** [comment]
I'll try getting a screen recording. I'm testing with a UDD that just blits a box onto the screen and updates 1 pixel in the x and y position per loop (so there is an obvious stutter). When I measured deltatime between frames ([here](https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=39601&p=432828&hilit=cache+audio#p425841)) you can see it spike to nearly 0.2 seconds the first time an audio clip is played, but subsequent audio playback doesn't have the same issue.

**Comment by renpytom** [comment]
Is it possible to get the code you're using, too? I've been trying to put sleeps in the appropriate places, but it's been rock-solid here. I'm wondering if there's something about the video or audio that's causing contention on, for example, the GIL. What I've been doing releases the GIL, but it's possible something else is keeping it stuck.

**Comment by renpytom** [comment]
(And my apologies for the very hurry-up-and-wait nature of my interactions on this - it's a hard problem for me, since I spend time to track it down before writing back.)

**Comment by morganwillcock** [comment]
No problem. I've updated to the newest pre-release and re-tested with a new project. Just replacing the script with the following shows the problem for me:
<pre>init python:

    class Bouncer(renpy.Displayable):

        def __init__(self, speed=1, size=10, **kwargs):

            # Pass additional properties on to the renpy.Displayable
            # constructor.
            super(Bouncer, self).__init__(**kwargs)

            self.speed = speed
            self.size = size

            # The width and height of the Render.
            self.width = 640
            self.height = 480

            # The start position.
            self.x = 0
            self.y = 0

            # The start movement
            self.dx = speed
            self.dy = speed

            # colours (R, G, B, A)
            self.bg = (0, 0, 0)
            self.fg = (255, 0, 255)

        def render(self, width, height, st, at):

            # Calculate new position
            self.x += self.dx
            self.y += self.dy

            # Calculate new movement
            if self.x == 0 or self.x + self.size == self.width:
                self.dx *= -1
            if self.y == 0 or self.y + self.size == self.height:
                self.dy *= -1

            # Create the render we will return.
            render = renpy.Render(self.width, self.height)

            # Get the canvas for the render.
            canvas = render.canvas()

            # Draw Bouncer
            canvas.rect(self.fg, (self.x, self.y, self.size, self.size), width=0)

            # Request instant redraw
            renpy.redraw(self, 0)

            # Return the render.
            return render

        def event(self, ev, x, y, st):
            import pygame

            if ev.type == pygame.MOUSEBUTTONDOWN:
                # left click
                if ev.button == 1:
                    renpy.sound.play('audio/sound.ogg', channel=1)

        def visit(self):
            return []

    bouncer = Bouncer()

label start:

    show expression bouncer as bouncer
    $ renpy.pause(60, hard=True)
    return</pre>

I can recreate the problem by running this loop at the same time as the game:
<pre>while true; do
        sleep 2
        echo Dropping cache...
        echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null
        echo Done.
done</pre>
I might have to re-test it on my Mac to get a smooth video capture, but will have a try later today.

**Comment by morganwillcock** [comment]
[Here](https://www.dropbox.com/s/zi258myln4ve5f9/out.ogv?dl=1) is a capture on a Linux desktop. Recording the video at the same time as running the test has exaggerated the problem a little, but you can see that when the disk cache is flushed the render appears to decelerate and then accelerate.

**Comment by morganwillcock** [comment]
I've tried the nightly build and I can't recreate the same slow-down and speed-up effect now, so I think your changes have sorted it. Thank you for following this up.
