### ISSUE TITLE
issue with dialogue

### ISSUE THREAD

**Issue by ablurr** [renpy/renpy#1180]
every time I try to use dialogue for w = ('Willow') it always has something wrong with it, but earlier today it was working fine. I then changed the dialogue to be said be h = ('Harper') and all of a sudden it'll work. I don't know what is going on, or if I'm doing something wrong. The only thing I changed was the letter before the dialogue. 

![ren py problem2](https://cloud.githubusercontent.com/assets/28639725/25979257/efac65ca-368c-11e7-84b1-56644b8457cc.PNG
![ren py problem](https://cloud.githubusercontent.com/assets/28639725/25979264/fb965f80-368c-11e7-8f5b-4b4821ca9600.PNG)
)

**Comment by renpytom** [comment]
#EFCLAA isn't a valid color. (Each component needs to be between 0-9 or A-F, which L isn't. Maybe try #EFCCAA ?

**Comment by ablurr** [comment]
Thank you so much!!!!
