### ISSUE TITLE
CJK font problem

### ISSUE THREAD

**Issue by kj415j45** [renpy/renpy#1189]
CJK current font(at least Chinese): `DroidSansFallback`
It doesn't have english characters, so those will show `□`

I recommand use: `Microsoft YaHei` or `SimHei`
They have almost all characters in UTF-8

**Comment by renpytom** [comment]
I just checked, and it looks like the font does support English. The characters are there, and I was able to display them in Ren'Py. 

Is it possible you could be using some other block of character. (Double-width ASCII, for example?)

**Comment by kj415j45** [comment]
¯\_(ツ)_/¯
It looks just ok in Windows, but it show `□` on Raspberry Pi(Ubuntu Mate 16.04.2(Renpy 6.99.8.959(armhf)))
![image](https://cloud.githubusercontent.com/assets/18349191/26617002/485f6686-4605-11e7-8dd2-5aa410fa23cd.png)

**Comment by renpytom** [comment]
It works well on Linux, too. Raspberry Pi isn't a supported platform at the moment, so I'm not sure what I can do here. Perhaps compile freetype yourself?

**Comment by kj415j45** [comment]
Will try it, If it works, I'll close this issue
Thanks a lot

**Comment by kj415j45** [comment]
![default](https://user-images.githubusercontent.com/18349191/28012625-f4b2a670-6598-11e7-9e93-2b2cba89db0b.png)
As you see, my issue was solved.

But I solved it by download `DroidSansFallback.ttf` from the internet and replace `/usr/share/fonts-droid-fallback/truetype/DroidSansFallback.ttf`(Simplified/Traditional Chinese use a symbol link link to it)

I'm not sure why DroidSansFallback on rpi died, and i forgot to backup the broken one :p

I hope you can report this issue to linux-package-repo, because i'm so lazy :p
