### ISSUE TITLE
Drag does not respect absolute positions

### ISSUE THREAD

**Issue by Dreamer23** [renpy/renpy#1191]
The "dragged" method does not seem to check the absolute x and y coordinates of potential hits, rather using their relative ones.

Below is a sample script.py, utilizing a 100x100px frame.png.
It contains two drag targets at 0,200 and 200,200 and a draggable at 0,0
The dragged method is defined to move the object to 500,500 if it is dragged to a valid target, and otherwise to 500,0.

Expected:
a) Drag the object to one of the two targets to have it snap to 500,500, snap to 500,0 otherwise
b) When accessing or setting the x / y coordinate of any drag object, it should return the absolute value on the screen, not the value relative to its parent. Alternatively, there should be extra attributes called "absolute_x" and "absolute_y"

Actual:
When the object is dragged to anything within 0-100,0-100, it snaps to 500,500 (because both drag targets are at 0,0 within their fixed layout), otherwise it snaps to 500,0 (e.g. when dragged onto one of the legitimate drag targets)

I guess as a workaround nothing should be added to containers but rather everything directly to ui (using absolute layout positions), but that seems incredibly inconvenient.

Demonstration code:
```
init python:
    
    def dragged_method(self, where):
        if not where:
            # Snap to 500,0 if no drag target is found
            self[0].snap(500,0)
        else:
            # Snap to 500,500 if a drag target is found
            self[0].snap(500,500)
        
    def add_drags():
        draggroup = DragGroup()
        
        # Create one drag target at 0, 200
        left_container = Fixed(xpos = 0, ypos = 200, width = 100, height = 100)
        left_drag = Drag(d="frame.png",draggable=False)
        left_container.add(left_drag)
        ui.add(left_container)
        draggroup.add(left_drag)
        
        # Create a second drag target at 200, 200
        right_container = Fixed(xpos = 200, ypos = 200, width = 100, height = 100)
        right_drag = Drag(d="frame.png",draggable=False)
        right_container.add(right_drag)
        ui.add(right_container)
        draggroup.add(right_drag)
        
        #Create a draggable. Can be in no container or in a third container.
        # Using no container for simplicity / demonstration purposes
        draggable = Drag(d="frame.png",droppable=False, dragged=dragged_method)
        draggroup.add(draggable)
        ui.add(draggable)

screen dummy_screen:
    $ add_drags()

label start:
    call screen dummy_screen
```

**Comment by renpytom** [comment]
This kind of fell through the cracks, but looking at it after all this time, it's clear why this is invalid - a drag can't belong to both a DragGroup and another displayable like this.
