### ISSUE TITLE
Developer options in android port.

### ISSUE THREAD

**Issue by Hunter1212** [renpy/renpy#1192]
I'm trying to port over games based on ren'py to android. The port is good enough, but even though I enabled Developers options before the port, and it worked inside windows, I'm unable to get it on android yet. Is there a way to have dev console in the android port too?

**Comment by renpytom** [comment]
The dev console isn't supported on Android. It might work if you wire a keyboard to the device, though.

**Comment by Hunter1212** [comment]
Or through a wireless one too? Will it work through  the hacker's keyboard? I think that needs to be updated though.

**Comment by renpytom** [comment]
I don't know. I suspect it would work if you can get the keystrokes to Ren'Py, though the android build might also be enabling developer mode. Android isn't meant as a development platform in any case, so I don't plan on supporting the developer tools there.

**Comment by Hunter1212** [comment]
Okay, not but could it be possible to get some tools like the console?
