### ISSUE TITLE
Stop screen from scaling in over an android port.

### ISSUE THREAD

**Issue by Hunter1212** [renpy/renpy#1193]
I'm porting over games made in ren'py engine for windows to android. Some of the games I ported have a resolution of 800:600 or sometimes other too. When ported over to android, any game which isn't a 16:9 ratio visuals, scales to adjust and cuts off parts of the game, rendering it unable to play, or move forward in the game  But when these games are played in windows, the screen seems to adjust and it shows perfectly, not stretching or scaling to the desktop screen, showing black screen for the rest of the part. Is there a way for android too, disable the scaling and all.

**Comment by renpytom** [comment]
Can you take a screenshot of this? Unless something is totally wrong, Ren'Py will put black bars on both sides, and it'll work. Which version of Ren'Py are you using?

**Comment by Hunter1212** [comment]
Here are the screens : https://imgur.com/a/uJbN3

**Comment by renpytom** [comment]
It looks like your screens are getting adjusted by the "small" variant styles at the bottom of screens.rpy. You may want to remove those styles, or else re-customize them to better fit your game.

**Comment by Hunter1212** [comment]
Okay, I don't want to repackage the while thing. The screen.py script has variant set to None. Is there a way to fix just for the android port editing the py file?
