### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'copy_on_change'

### ISSUE THREAD

**Issue by XelaPy** [renpy/renpy#1194]
Only happens when screen containing the viewport is not predicted (predict False screen statement), upon exiting the engine.

```python
    viewport:
  File "D:\Coding\RenPy\renpy\sl2\slast.py", line 1088, in copy_on_change
    c.copy_on_change = True
AttributeError: 'dict' object has no attribute 'copy_on_change'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
```

**Comment by renpytom** [comment]
I'm unable to repeat this problem. Can you give me more information - ideally an example that repeats the problem? At the very least, I'd need to see the complete call stack, and not the end of it, since it's lamost certainly an issue with multiple screen language statements and not just one.

**Comment by XelaPy** [comment]
I'll see if this can be isolated somehow tomorrow.

**Comment by XelaPy** [comment]
Sadly, screen itself was changed several times and content loaded into it is completely different now. I'm unable to repeat this problem either :(

If we get this issue again, I'll try to isolate it.
