### ISSUE TITLE
Documentation: What is SL2?

### ISSUE THREAD

**Issue by Klaim** [renpy/renpy#1196]
In the online documentation we can currently read there https://www.renpy.org/doc/html/screen_python.html#ui-functions :

> With the advent of SL2, UI Functions are deprecated and not recommended.

Searching for SL2 in the documentation only result in the same page.

 1. Is this an obsolete information?
 2. What is SL2?
 3. Shouldn't it be explained in the documentation? Or if it is an external library, provide a link to it's documentation?

I only see code here that use `renpy.sl2` but I still don't know what it is and if I should use it instead of ui functions.

**Comment by Uzume** [comment]
SL2 refers to a rewrite of the rpy screen language (as a performance optimization) that is associated with Ren'Py 6.18 release. The deprecation refers to fact that the Python ui functions have not changed and thus can be far less optimal (in terms of performance) than direct use of the new screen language (SL2). So though they are still functionally equivalent they are not in general equivalent in terms of performance.

**Comment by Klaim** [comment]
Thanks @renpytom for the clarifying patch and @Uzume for the clarification.
However now I'm not sure what I should do. I am setting up a custom window that,\
from what I understand, need to be written in Python (the displayed data changes contextually).
Are you suggesting that for performance reasons I should wrap the python code into a window described using the screen language instead of the reverse? Or is there a way to, without losing performance, use the new screen language implementation from python?
