### ISSUE TITLE
dict update and rollback

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1197]
Rollback don't delete/cancel if we use dict.update
It`s big problem because I cannot use dict in game...

**Comment by renpytom** [comment]
Oh, that's a big oversight to find years later. 

As a workaround until the fix is released, I'd suggest:

```
init python:
    def dict_update(d, update):
        for k, v in update.items():
            d[k] = v
```

And turn:

```
d.update(things)
```

to 

```
dict_update(d, things)
```
