### ISSUE TITLE
"default" statement does not work as described

### ISSUE THREAD

**Issue by Alex-Tracer** [renpy/renpy#1198]
Seems like '[default](https://github.com/renpy/renpy/issues/577)' statement does not work properly.
If I add it to an existing game it works fine immediately after first load but after any save/reload attempt to access it results in NameError.

Steps to reproduce:
1) Create a game with this code:
```renpy
#default x = 1

label start:    
    "Save NOW! Then close game, enable commented lines and load this save"
    jump test
    
label test:
    #if x == 1:
    #    "x is 1"
    "Save NOW AGAIN and then load this save!"
    jump test2
    
label test2:
    #if x == 1:
    #    "x is still 1"
    return 
```
2) Run the game and create a save just after game start.
3) Uncomment all commented lines (this is same as adding 'default' statement in new game version).
4) Load game save and click once (you will see "x is 1")
5) Click again and save game into a new slot
6) Load game from that new slot.

Actual result: NameError exception:
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    if x == 1:
  File "game/script.rpy", line 26, in <module>
    if x == 1:
NameError: name 'x' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    if x == 1:
  File "D:\X\RenpySDK\renpy-6.99.12.4-sdk\renpy\ast.py", line 1656, in execute
    if renpy.python.py_eval(condition):
  File "D:\X\RenpySDK\renpy-6.99.12.4-sdk\renpy\python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\X\RenpySDK\renpy-6.99.12.4-sdk\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 26, in <module>
    if x == 1:
NameError: name 'x' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
test_default 1.0
```

Expected result: text "x is still 1"

RenPy version: 6.99.12.4.2187

**Comment by Andykl** [comment]
but why don`t use?
label start:
    default x = None

**Comment by Andykl** [comment]
if we change code us

label start:
    default x = 1
    "Save NOW! Then close game, enable commented lines and load this save"
    jump test

label test:
    if x == 1:
        "x is 1"
    "Save NOW AGAIN and then load this save!"
    jump test2

label test2:
    if x == 1:
        "x is still 1"
    return
it`s worked.
But you mast use variable here you may use
label after_load
https://www.renpy.org/doc/html/python.html?#default-statement

**Comment by Alex-Tracer** [comment]
What's the point in the `default` keyword if you still have to use `after_load` to "fix" it?

It's doesn't look like it's described in the doc.

**Comment by renpytom** [comment]
I need to look into this. It's possible it's a transient with game start.

**Comment by Alex-Tracer** [comment]
Thanks, Tom!
