### ISSUE TITLE
screen on statement and rollback problems

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1199]
So I ran into a problem, “screen on statements” only start their execution after the screen has loaded, and “action Show(screen) “flickers” in high resolution, which obviously detracts from the gaming experience, and I would prefer to simply use:

show screen cabinet_main
Instead of:
show screen cabinet_main
show screen cabinet_time
 
With screens:
screen cabinet_main:
    on “show” action Show(“cabinet_time”)
    on “hide” action Hide(“cabinet_time”)
        zorder 0
    add "images/locations/cabinet_pic/cabinet_main.png"
    add "candle_anim" pos (566, 547)
screen cabinet_time:
    if _daytime:
        add "images/locations/cabinet_pic/cabinet_day.png" pos (614, 0)
    else:
        add "images/locations/cabinet_pic/cabinet_night.png" pos (614, 0)
    if not _curtain_open:
        add "images/locations/cabinet_pic/curtain_close.png" pos (550, 0)
 
Also, I found a problem with the rollback function, it doesn’t save the result if in  “action” function we use other functions on top of the “Return() action, for example if we use:  [SetVariable(“time”, 4), Hide(“some_screen”), Return()], after rollback the screen won’t show back, and the variable won’t return to the original value. As far as I understand, rollback only saves the value under the “_return” variable.

**Comment by renpytom** [comment]
I've fixed the ```on "show" action Show("cabinet_time")``` issue. Could you please give me an example of the rollback problem? It's not clear to me what it is.

**Comment by Andykl** [comment]
[example](https://drive.google.com/file/d/0B3UNluHeC5iGQWZUc3JJYUx5NGc/view?usp=sharing)

**Comment by Andykl** [comment]
@renpytom If this is a bad example, say, because this topic worries me very much.
Solving this problem will allow me to greatly improve my code

**Comment by renpytom** [comment]
Sorry, but I've looked at this, and I'm not able to understand what the problem with rollback is. I need a minimal example, ideall one with the latest nightly build.
