### ISSUE TITLE
action Language() NVL problem.

### ISSUE THREAD

**Issue by roxygen** [renpy/renpy#1203]
After changing the game language through action Language, Renpy displays the previous line for the second time. 
Initially I thought the problem in my game. But then I created an empty project with the default screens to test and check the Tutorial. The bug repeats on other people's computers.

Renpy version is 6.99.12.4.2187.

https://www.dropbox.com/s/wzza6nfgmrw7iup/2017-06-17_09-58-18.mp4?dl=0
[test_tr.zip](https://github.com/renpy/renpy/files/1082264/test_tr.zip)

![pythonw_2017-06-14_22-31-21](https://user-images.githubusercontent.com/3707285/27249625-33a1828c-5344-11e7-8c75-75a188af9677.png)
![pythonw_2017-06-16_21-06-11](https://user-images.githubusercontent.com/3707285/27249645-9e4460a0-5344-11e7-9b6f-80491cbea244.png)

**Comment by lgb** [comment]
Reproduced only in NVL-mode, normal mode work fine
