### ISSUE TITLE
Inconsistent newline style with new GUI template

### ISSUE THREAD

**Issue by ishitatsuyuki** [renpy/renpy#1214]
tldr, results:
```
find . -name "*.rpy" | xargs file
./game/gui.rpy:     UTF-8 Unicode (with BOM) text, with CRLF line terminators
./game/screens.rpy: UTF-8 Unicode (with BOM) text, with CRLF line terminators
./game/options.rpy: UTF-8 Unicode (with BOM) text, with CRLF line terminators
./game/script.rpy:  UTF-8 Unicode (with BOM) text
```

Also this.

```
./game/tl/None/common.rpym: UTF-8 Unicode (with BOM) text, with CRLF, LF line terminators
```

I'm using Japanese language for the launcher. Version is `Ren'Py 6.99.12.4.2187`.

I think there's some conversion made. Here's the results about source:

```
find /usr/share/renpy/gui -name "*.rpy" | xargs file
/usr/share/renpy/gui/game/testcases.rpy:  ASCII text
/usr/share/renpy/gui/game/script.rpy:     ASCII text
/usr/share/renpy/gui/game/screens.rpy:    UTF-8 Unicode text
/usr/share/renpy/gui/game/options.rpy:    UTF-8 Unicode (with BOM) text
/usr/share/renpy/gui/game/guisupport.rpy: Python script, ASCII text executable
/usr/share/renpy/gui/game/gui.rpy:        ASCII text
```

From the conventions of Git, I would like to suggest to convert to CRLF depending on platform.

IMO, adding BOM just makes it invalid ASCII and resulting in junk first byte in some UNIX commands. It should be omitted for UTF-8.

**Comment by renpytom** [comment]
BOM is required in certain editors to force utf-8 mode, rather than the system encoding.

We should be normalizing line endings to CRLF on release. I'll check that's happening.
