### ISSUE TITLE
Update to 64-bit in Windows

### ISSUE THREAD

**Issue by zedraxlo** [renpy/renpy#1219]
We made a new game which base resolution is 2560*1440, when loading an image which is 7111*4000, the engine crashed, with:
Exception: Could not load image u'images/cg/cg99.jpg': error('Out of memory',)

So, will Ren'Py update to 64-bit in Windows?

**Comment by renpytom** [comment]
I'll take care of it someone, but it seems like it's a bad idea to make a game that can only be run on 64-bit windows.
