### ISSUE TITLE
Creator-Defined Statements is not working...!?

### ISSUE THREAD

**Issue by vollschauer** [renpy/renpy#1224]
https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=45237

I have also tested it with the example here: https://www.renpy.org/doc/html/cds.html#example
and with the latest nigthly, looks like it's broken ....

**Comment by renpytom** [comment]
CDSes work, since play, queue, and stop all use the same mechanism. 

My guess is that you'e trying to use the CDS in the same file in which it is defined. This isn't allowed, it has to be define in a file loaded before it is used.
