### ISSUE TITLE
show layer master at tr_shake nullifies renpy.transition(dissolve)

### ISSUE THREAD

**Issue by Samukun** [renpy/renpy#1225]
Looks like if you shake the screen using

show layer master at tr_shake

then, renpy.transition(dissolve) stops working to dissolve live composite characters.

tr_shake is just

    transform tr_shake:
        ease 0.02 xpos -0.02
        ease 0.04 xpos 0.02
        ease 0.02 xpos 0.0
        repeat 4

**Comment by renpytom** [comment]
I'm not sure what the problem is. I've tried thing, and it looks like Ren'Py is working as intended. Since show layer at works on a layer, it is applied before transitions. 

You might want to try something like:

```
label main_menu:
    return

transform tr_shake:
    ease 0.02 xpos -0.02
    ease 0.04 xpos 0.02
    ease 0.02 xpos 0.0
    repeat 4


label start:

    show layer master at tr_shake
    show eileen happy at left

    "A"

    show layer master at tr_shake
    with None
    show eileen happy at right
    $ renpy.transition(dissolve)

    "B"
```

The extra with None  applies the show layer so the shaking happens on both sides of the transition.

**Comment by renpytom** [comment]
I've been unable to replicate this.

**Comment by renpytom** [comment]
"do you know why the screen shakes ONE time every say line
is that a bug?"

**Comment by Samu-kun** [comment]
I haven't been able to follow up on this issue, but I'll try to get the game data to you soon.

The screen doesn't shake one time after every say line on this end though. It'd be a more serious issue in that case.

**Comment by vollschauer** [comment]
I run into this behavior with the one shake after every say line and PM Tom about this issue ....

**Comment by vollschauer** [comment]
The "one" shake issue is gone, thanks Tom. 
But in this test scenario the second tr_shake is not applied/executed.
```
    "Test1"
    show layer master at tr_shake
    "Test2"
    "Test3"
    show layer master at tr_shake
    "Test4"
```

**Comment by vollschauer** [comment]
Solved my problem, thanks!
