### ISSUE TITLE
Custom path failed on Android  by prefix x-

### ISSUE THREAD

**Issue by UzminTid** [renpy/renpy#1226]
When building apk  renPy will add "x-" prefix to every file/folder  

This cause a problem when i try to load some file in python mode (4 example language)
`...`
`tl_dir = os.path.join(config.gamedir, "tl") # I have tl folder in my gamedir `
`...`
(this work perfectly on PC)

but when we go to android everything changed ,tl floder was renamed into x-tl by renPy
and game failed to load those resource

change os.path.join(config.gamedir, "tl")  into os.path.join(config.gamedir, "x-tl")  fix nothing because renPy refuced to build

**Comment by renpytom** [comment]
I'm confused by your code. Are you using renpy.file to open files? Opening them in other ways is not supported on Android, since the files are not sent to disk.

**Comment by UzminTid** [comment]
Thankyou @renpytom  I managed to remove those code and now my game run  perfectly  on android too!!：）

**Comment by UzminTid** [comment]
For other who confused when loading files [https://www.renpy.org/doc/html/file_python.html](url)

**Comment by UzminTid** [comment]
close #1226
