### ISSUE TITLE
If action executes both possible commands before choosing the appropriate one

### ISSUE THREAD

**Issue by Oktober13** [renpy/renpy#1227]
`If((bkg_page+1)>21,SetVariable('scene_background', gallery_bkg_items[0]),SetVariable('scene_background', gallery_bkg_items[bkg_page+1]))`

gallery_bkg_items is a list filled with 22 renpy images, indexed from 0 to 21.
bkg_page is the current gallery page.

`SetVariable('scene_background', gallery_bkg_items[bkg_page+1])`
Above code will fail when bkg_page is equal to 21, because scene_background attempts to index into the nonexistent 22 cell of gallery_bkg_items.

I attempted to solve this by placing that code in an if statement, which should ensure it only runs when bkg_page is less than 21. This is throwing the same error as before, implying that If() action is still running that snippet prior to choosing a course of action.

Code works fine in a normal if statement; the sole issue seems to be with the If(condition,result,result) action. I can't use traditional if statements because I'm embedding this code into an ImageButton.

Full error traceback attached below:
[error.txt](https://github.com/renpy/renpy/files/1237590/error.txt)

**Comment by renpytom** [comment]
This is correct. 

You can now use the Python ternary statement to avoid it:

```
SetVariable('scene_background', gallery_bkg_items[0]) if (bkg_page+1)>21 else SetVariable('scene_background', gallery_bkg_items[bkg_page+1])
```
