### ISSUE TITLE
IOError: [Errno 13] Permission denied: 'files.txt'

### ISSUE THREAD

**Issue by AnakinJ2** [renpy/renpy#1229]
It seems like the developer code of Ren'Py is deny acess to create the files.txt that list the names of the imagens inside game folder. This error is messing me up a lot...
You can see the bug here
[traceback.txt](https://github.com/renpy/renpy/files/1248801/traceback.txt)

**Comment by renpytom** [comment]
I can't find the code that caused that error in Ren'Py. The correct version of the line is here:

https://github.com/renpy/renpy/blob/master/renpy/common/_developer/developer.rpym#L520

Did something change your Ren'Py installation? I don't believe this is an error in Ren'Py proper.
