### ISSUE TITLE
Jpeg format is ignored by renpy functions

### ISSUE THREAD

**Issue by DarkTl** [renpy/renpy#1232]
While renpy supports jpeg files just like it supports jpg, functions like has_image don't see jpeg pictures.

**Comment by renpytom** [comment]
This is a misunderstanding of what has_image is supposed to do. It checks for a defined image, not a file on disk. 

So if "images/bg room.jpg" exists.

renpy.has_image("bg room") -> True
renpy.loadable("images/bg room.jpg") -> True

**Comment by DarkTl** [comment]
Sorry, I didn't described it clear enough.

Putting bg 1.jpg in images folder and executing renpy.has_image("bg 1") returns True.
But putting bg 1.jpeg and executing renpy.has_image("bg 1") returns False.

**Comment by renpytom** [comment]
Oh, understood. I'll take care of this soon. It's more of an extension than a format, hence my confusion.
