### ISSUE TITLE
Screen transform problem related to atl_st_offset

### ISSUE THREAD

**Issue by arowana-vx** [renpy/renpy#1243]
In the latest nightly (6.99.13.2717), some of my screen animations are acting weirdly. In particular, transforms are restarting/repeating when they aren't supposed to. Here is a sample script to demonstrate:

```
define e = Character("Eileen") 

transform frame_trans:
    align (0.5, 0.5)
    on hide:
        linear 5 zoom 0 

screen test_screen():
    timer 0.5 action Hide("test_screen")
    frame:
        at frame_trans
        text "Hello." size 200       

label start:
    scene bg room
    e "You've created a new Ren'Py game."
    show screen test_screen
    e "This word will disappear in 5 seconds. Click to advance before the word disappears."
    e "If you keep clicking before the word fully disappears, the transform repeats."
    e "Hmm, I wonder what's going on?"
    return
```

I suspect [this recent commit](https://github.com/renpy/renpy/commit/b56772e148bebdf4687c9c675e51a44460f9bf38) for clearing atl_st_offset is related to the problem, since removing it makes my screens act normally again. Let me know if I should provide any more information, and thanks!

**Comment by renpytom** [comment]
Thanks for another very useful report. I had a pretty good idea of what was wrong once I finished reading the code you provided.
