### ISSUE TITLE
voice clips restart on "voice sustain"

### ISSUE THREAD

**Issue by arowana-vx** [renpy/renpy#1245]
Thanks for fixing my last issue so quickly! Another issue I found in the latest nightly (6.99.13.2733): when using "voice sustain", voice clips replay from the beginning. I suspect it's related to [this recent commit](https://github.com/renpy/renpy/commit/c94d223b05fd8496898181d097c82f8e7d892d7a).

Below is a short example to demonstrate ("line.ogg" is in the attached ZIP). 
[line.ogg.zip](https://github.com/renpy/renpy/files/1287123/line.ogg.zip)

If you click to advance the text before the voice clip has finished playing, the voice clip will restart from the beginning when you reach the next line of text (right after "voice sustain"). I would expect the voice clip to continue playing without restarting, which is what it has done in the past.
```
define e = Character("Eileen") #, what_slow_cps=0)

label start:
    scene bg room
    voice "line.ogg"
    e "Once upon a time..."
    voice sustain
    e "...or what just seems like a very long time ago..."
    voice sustain
    e "...my father told me stories about the mermaids."
    return
```

Let me know if you need more information, and thanks again!

**Comment by renpytom** [comment]
Fixed, and thank you. Keep 'em coming.
