### ISSUE TITLE
Viewport overflow with long texts

### ISSUE THREAD

**Issue by arowana-vx** [renpy/renpy#1247]
Sorry, turns out I did run into another issue after all!

When I have a viewport with long texts, the bottom of the text overflows at certain scrollbar positions. At first, I thought maybe I made a mistake with the area or padding. But the overflow disappears/viewport looks normal at other scrollbar positions, which seems really strange. I don't think this behavior would be intentional?

I am testing in 6.99.13.2743. I tried in an older version (6.99.13.2527) and did not have this issue, so I'm guessing a relatively recent change caused it?

Here's an example script:
```
define e = Character("Eileen")

screen viewport_example():
    side "c r":
        area (100, 100, 600, 300)
        viewport id "vp":
            draggable True

            vbox:
                text "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                null height 20
                text "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"

        vbar value YScrollValue("vp")

label start:
    scene bg room
    show screen viewport_example
    e "Here is a viewport with really long text. As you drag the scrollbar down, some of the text will overflow at the bottom."
    return
```

Example of overflow from that script:
![screenshot0033](https://user-images.githubusercontent.com/31723553/30261033-7e7fd816-967f-11e7-9800-01034e7d3f61.png)

As always, let me know if you need more information, and thanks!

**Comment by renpytom** [comment]
I'm unable to repeat this after quite a bit of trying.

Can you try:

```
screen viewport_example():

    default adjustment = ui.adjustment()

    side "c r":
        area (100, 100, 600, 300)
        viewport id "vp":
            draggable True
            mousewheel True
            yadjustment adjustment

            vbox:
                text "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                null height 20
                text "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"

        vbar adjustment adjustment style "vscrollbar"

    hbox:
        text "[adjustment.value]"
        textbutton "Update" action renpy.restart_interaction
```

Please? This adds a display of the vertical scrolling position, which updates when you hit the update button. I'm curious if you can repeat this with the current version - if so, hitting the button and letting me know what the result is might help. 

Thanks.

**Comment by arowana-vx** [comment]
Thanks for looking into this! I tried again with the current version (6.99.13.2745), this time on two computers.

The overflow is still happening on my Macbook (2880x1800 with Retina display). However, it did not happen on a smaller PC (1366x768). Maybe it's related to the window resolution? When I shrunk the game window on my Macbook, the overflow immediately went away.

Here are some screenshots from the Macbook with the display you provided, using the normal windowed mode.

(this is where the overflow starts to appear)
![screenshot0035](https://user-images.githubusercontent.com/31723553/30307309-128c49ba-9732-11e7-8a79-3d5dd2cab79c.png)

(this is where the overflow starts to disappear)
![screenshot0036](https://user-images.githubusercontent.com/31723553/30307308-128ad8a0-9732-11e7-972b-b6e752a46738.png)

I hope that helps! Let me know if there's anything else I can do.

**Comment by renpytom** [comment]
Thanks for figuring that out. Scaling up the window on my Linux box lets me repeat the problem, which is the first step in being able to fix it.
