### ISSUE TITLE
Transitions NPOT issue on i965GM

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1252]
Issue with all transitions. OpenGL 2.0.
Using latest build for 2017-09-17.
In the nightly build for 2017-08-19 everything working fine (like in NPOT OFF)
Tech-info for GPU: https://www.techpowerup.com/gpudb/1233/i965gm

NPOT OFF:
![2017-09-17_21-44-53](https://user-images.githubusercontent.com/24704640/30523975-da65453e-9bf3-11e7-9978-7c803bcc5ede.gif)

NPOT ON:
![2017-09-17_21-46-26](https://user-images.githubusercontent.com/24704640/30523974-da65286a-9bf3-11e7-9110-b7194232cf03.gif)

**Comment by renpytom** [comment]
Can you send me the log.txt file? I'll see what I can do, but this is a 10 year old GPU. Hopefully, I can at least detect the issue and work around it.

**Comment by Ria-kon** [comment]
[log.txt](https://github.com/renpy/renpy/files/1310028/log.txt)

**Comment by renpytom** [comment]
I'm considering this an important issue, but I may do the first prerelease without a fix just to get it out there and see how bad it is.

**Comment by Ria-kon** [comment]
Fix approved, all working.
