### ISSUE TITLE
6.99.13 Prerelease Issues

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1255]
- [x] In the minigame, Eileen and Player's names are swapped.
- [x] In the minigame, the beep sound happens even if the game is not in progress.
- [x] Paper frame tiled has a rendering glitch.
- [x] Screenshots don't save with special characters in filepath https://lemmasoft.renai.us/forums/viewtopic.php?f=32&t=45862
- [x] .7z not uncompressing. https://lemmasoft.renai.us/forums/ucp.php?i=pm&mode=view&p=261581
- [x] What happens if we're in a read-only dmg on mac?
- [x] Persistent files written by 6.99.13 may not be readable on 6.99.12.
- [x] The director is slow in large games. #1265 
- [x] Mention projects.txt in the changelog.
- [x] Title in wrong place for  Android The_question.
- [x] Error linting an unclosed text tag. "test {foo)"

**Comment by Nanashi7** [comment]
I don't know if this is the correct place to report this, if not I apologize.
In the spanish translation of the Ren'Py Launcher there seems to be a little typo. The "Build Distributions" button reads "Construir Distibuciones" when it should be "Construir Distribuciones".
![prtscr capture](https://user-images.githubusercontent.com/25247493/31176080-2b123934-a8d7-11e7-887e-7378f76b6842.PNG)

**Comment by renpytom** [comment]
This is a fine place, but it's often easier if you just file a new issue. Not a big deal, I made the change. Thank you.
