### ISSUE TITLE
gui.show_name both in options.rpy and gui.rpy

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1256]
What's the difference? Working only options.rpy, 'cause gui.rpy initializing first.

gui.rpy:

/## Should we show the name and version of the game?
define gui.show_name = True

options.rpy:
/## Determines if the title given above is shown on the main menu
/## screen. Set this to False to hide the title.

define gui.show_name = True

**Comment by renpytom** [comment]
I've removed the one in gui.rpy, it should be gone now. (Is it present somewhere?)

**Comment by Ria-kon** [comment]
Oh, sorry, too old issue =D

**Comment by renpytom** [comment]
Thank you. While I have you, I made a few minor text fixes to the tutorial during testing.
