### ISSUE TITLE
im_matrix() documentation

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1257]
Double *, no division
> These operations are invoked using the standard
    mathematical operators (\*, \*, +, and -, respectively). If two
    im.matrix objects are multiplied, matrix multiplication is
performed, otherwise scalar multiplication is used.

**Comment by renpytom** [comment]
This is correct. Right before this, I point out the four operations, and this points out that there is matrix and scalar multiplication. (It's a bit confusing, but the common notation for this sort of thing.)
