### ISSUE TITLE
how to add new attribute to Character Class?

### ISSUE THREAD

**Issue by e212156822000** [renpy/renpy#1259]
## Context of the issue

I wan to make a screen like this:

![image](https://user-images.githubusercontent.com/11701668/31043571-16e17ca6-a5f1-11e7-93dd-a4fd876931ac.png)

Hurrie Cobber is a character name, and in order to show **Energy value** , **Intimacy value** and **presents list** , I would like to add some attribute into Character Class.

## Expected result

I could compile this kind of code in renpy.
``` python
define Hurrie = Character('Hurrie Cobber', color="#c8ffc8", energy_value="100" , intimacy_value="0" , presents=list["unpacked", "wine","ring"]) 
```

## Conclusion
I don't know if I could ask this kind of question here , or I should go to renpy's forum. lol.
Please give me some hints to fix it , thank you very much.

**Comment by renpytom** [comment]
The character class isn't meant for you to change like this. 

What you probably want to do is to use the character namespace so you can share a name between the Character and your own object. 

```
define character.Hurrie = Character("Hurrie Cobber", ...)
define Hurrie = MyObject(energy_value=100)
```

This is probably more appropriate for the Lemma Soft Forums, as there's no bug here.
