### ISSUE TITLE
Translations need to be updated.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1262]
This is a bug that is intended to never be closed. It's here so translators can subscribe. I'll add comments to this issue when translations change after the initial prerelease of Ren'Py. The idea here is that translators can subscribe to this issue, so that github can email them when there's something to change.

**Comment by renpytom** [comment]
I've recently added two major translation updates. 

The first is an error message in the launcher that displays when Ren'Py is run from a mac disk image. This is every important, since it can be the first thing a new creator sees. 

The second is a message in the common code that is displayed when a screenshot fails to save.

**Comment by renpytom** [comment]
I had to add a new translation at the last minute. I'm planning on releasing 6.99.13 today or tomorrow.

**Comment by renpytom** [comment]
Just to let everyone know, 6.99.14.1 is done. There are a few new strings, one on the front page of the launcher. If people can let me know you're working on it, I'll hold up the release until you're finished.

**Comment by xavi-mat** [comment]
I'll try to translate most of Spanish missing strings today or tomorrow.

**Comment by renpytom** [comment]
Everybody: 6.99.14.2 is almost done, so please get your translations in soon. (And let me know if you're planning on working on this in the next few days.)

**Comment by renpytom** [comment]
Landed a number of new changes to 6.99.14.2, allowing the self-voicing mode to be translated. Please let me know ASAP if I should hold up the final release so this can be translated.

**Comment by fblampe** [comment]
I added some new German translations for the launcher main menu in this PR: https://github.com/renpy/renpy/pull/1599

**Comment by renpytom** [comment]
Closing, as this was never used for what it was intended.
