### ISSUE TITLE
.13 performance x3 slow

### ISSUE THREAD

**Issue by Samukun** [renpy/renpy#1265]
Ren'Py 6.99.13.2808 reload times are multiple times longer than the last stable version of renpy.

6.99.13: Reload duration 28 seconds
6.99.12: Reload duration 5 seconds

This is probably highly dependent on the game, but overall performance in .13 roughly x3 slower, from loading graphics to skipping, leading to slow development and user experience.

**Comment by renpytom** [comment]
Do you have an example of this? I haven't seen this, but it's possible something is being triggered, and if that's the case, I need to figure out what.

**Comment by renpytom** [comment]
This has been fixed as of last night, mostly by 4faee5feba5377d9ed05caa49dea49602d79f02a . Previously, Ren'Py had to recompile everything while the director was active, now it doesn't have to do so. On my computer, reloads with the director now take 3 seconds, down from 17-ish, though that varies based on machine performance.
