### ISSUE TITLE
Interactive Director: Attribute hierarchy issue

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#1269]
The ID will only let you add an image if you've selected as many attributes as the image with the most attributes within that statement. This is very problematic for certain common sprite declaration conventions. For example, say you declared the following images:
> Eileen streetclothes happy
> Eileen streetclothes happy glasses

The system will not enable the Add button until you've selected "streetclothes", "happy", **and** "glasses" as the attributes, meaning you can't show Eileen without glasses using the director. The system should be able to check that "Eileen streetclothes happy" is a valid declared sprite, and should allow you to add it.

Additionally, ideally the system should be able to interpret the hierarchy of the attributes declared. With an expansion of the example above, after you've selected Eileen as the statement then only the costumes should show up on the attribute list. After you've selected the costume then the list is replaced by the available expressions. And once you've selected the expression you may chose to add the glasses or not.
Let me know if my explanation of the system didn't make sense to you and I'll elaborate further.

**Comment by renpytom** [comment]
This is fixed by a817a3d7. It doesn't interpret the attribute heirarchy, but it does try to understand them.
