### ISSUE TITLE
Could not load WebP image in RasPi

### ISSUE THREAD

**Issue by ricke00** [renpy/renpy#1273]
Always thank you for *@renpytom* and *Ren’Py peoples*. #1272 was fixed. But however, in the latest prerelease, **WebP** does not work for **RasPi**.

Traceback:

`Exception: Could not load image u’123.webp’: error(‘Unsupported image format’,)`

**Comment by renpytom** [comment]
This should be fixed in renpy/renpy-deps@3c64bb7a354068e850eec3eeda7e441232b39fee , which I'll try to get out in a release shortly.

**Comment by ricke00** [comment]
Thank you PyTom :)
