### ISSUE TITLE
build.mac_identity typo in options.rpy

### ISSUE THREAD

**Issue by donzors** [renpy/renpy#1275]
Minor issue, but I noticed in the the newest options.rpy that the line for code signing a MacOS package is wrong.

Currently lists: define build.mac_identity = "Developer ID Application: Guy Shy (XHTE5H7Z42)"

But after some trouble shooting, I had to change it to:
define build.mac_identity = "Guy Shy (XHTE5H7Z42)"

and obviously, inserting my own dev name and id number.

Submitting this to potentially save people a headache when troubleshooting signing MacOS packages.

**Comment by renpytom** [comment]
Hm... would you mind dropping to the command line and running:

certtool y | grep "Common Name" 

? I'm using "Developer ID Application: Tom Rothamel (XHTE5H7Z79)" as the setting to sign Ren'Py itself, so it seems to work, and I'm not sure that I want to change it without reason.

**Comment by donzors** [comment]
Sure, here is the output:

Common Name     : Mac Developer: donny.campbell@gmail.com (2Y33FRM9FU)

In my options.rpy, I had used this line for my mac build, otherwise it would throw an error:

define build.mac_identity = "donny.campbell@gmail.com (2Y33FRM9FU)"
