### ISSUE TITLE
Additional Project Directories

### ISSUE THREAD

**Issue by Nanashi7** [renpy/renpy#1283]
This is only a suggestion, but from what I've seen, Ren'Py searches for game projects in a single, user defined directory, wich is very nice, but would it be possible to include, aside from the default, a list of additional directories for Ren'Py to browse projects? This could be an useful way to organize our projects, specially for people working on more than one game at once, or people who keep different projects on different storage devices.

**Comment by morganwillcock** [comment]
I believe such a feature was just added:

[https://www.renpy.org/doc/html/changelog.html](https://www.renpy.org/doc/html/changelog.html)

> When a file named projects.txt is present in the projects directory, it is expected to contain a list of full paths to directories, one per line. Those paths are treated as projects and displayed in the launcher.

**Comment by renpytom** [comment]
Correct, this was added recently. Closing now.
