### ISSUE TITLE
Ren'Py 6.99.13 platform-tools bad hashsum

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1284]
When you installing RAPT, Launcher downloading old android-sdk. By downloading, Launcher (like the sdk manager too...) gives you error with bad hashsum and abort installation so you need to manually download platform-tools (from here https://developer.android.com/studio/releases/platform-tools.html), unpack it and then you can (if you need, of course. I not checked it yet, but it seems ok to not-) update android-sdk.

Also, with this error your set-up SDK operation in Launcher will give you normal  "It looks like you're ready to start packaging games" but Ant don't think so.

I met this problem on 2 computers (Windows and Ubuntu).

**Comment by renpytom** [comment]
Sorry for the delay. 

Can you try this again, and see if the problem still exists? I just tried it on my windows box, and it went through without a problem. I'm wondering if it's an issue on Google's end that has been resolved, or perhaps a regional issue. 

If it fails, please send me renpy-6.99.13-sdk/tmp/<currentproject>/android.txt. That will contain a lot more info as to what's going on. 

Thank you.

**Comment by Ria-kon** [comment]
Yep, for now problem solved. I think, this is Google's problem because I already know that this wasn't the first time (They started in 2010: https://stackoverflow.com/questions/2287482/how-can-i-install-android-sdk-set-up-revision-4-and-launch-emulator. In 2014 this still on the case: https://stackoverflow.com/questions/26499617/android-sdk-manager-download-finished-with-wrong-checksum. And continues in 2017: https://stackoverflow.com/questions/47050602/travis-android-platform-tools-v26-0-2-not-installing)

So, I just left this issue for future generations.
