### ISSUE TITLE
lint add execute_default_statement()

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1287]
I suggest adding a execute_default_statement () in lint function.
so that she does not swear by the absence of a character on every line where he says.
I use characters in the default because I need to keep the fields of this object in the game.

I also suggest adding the option to the function renpy.register_statement() to pass to the argument a block of value that can either expect the block and not.
this can come in handy (I had to redefine this function) when the statement can receive ATL.

**Comment by renpytom** [comment]
Sorry, I don't understand this bug. 

Can you send me some sample code that triggers the lint error you'd hope to avoid?

**Comment by Andykl** [comment]
Ok, for example, I defined the character xandria
`
default xandria = Character("Xandria", image="xandria")
`
And during the game I change the fields of this object, and to keep it I put the character in the default statement
but with lint I get
"Could not evaluate 'xandria' in the who part of a say statement."
on each line where this character says.

To solve this problem, I duplicate the declaration in the init block.
I suggest adding the execute_default_statement() to the beginning of the lint function.
This is not a bug, but an offer.
