### ISSUE TITLE
predict_call function error

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1289]
in execution.py:719 self.predict_return_stack = None

but in execution.py:633 self.predict_return_stack = list(self.predict_return_stack)

error when we execute predict_call in ast.Call.predict()

**Comment by renpytom** [comment]
Sure, but in 697, it's set to return_stack, and should be that way throughout the prediction context. 

How are you calling ast.Call.predict()?

**Comment by Andykl** [comment]
I could not repeat the error, but under some conditions when the debug_image_cache is enabled, I sometimes get out this:
...
File "C: \ renpy \ renpy \ ast.py", line 1352, in predict
     return [renpy.game.context ().predict_call(label, self.next.name)]
File "C: \ renpy \ renpy \ execution.py", line 633, in predict_call
     self.predict_returnstack = list (seltpredict_return_stack)
TypeError: 'NoneType' object is not iterable

if it happens again, I'll try to understand where it comes from.
