### ISSUE TITLE
Speech to text for renpy

### ISSUE THREAD

**Issue by felixcandra** [renpy/renpy#1291]
hello, im new to renpy and both python but i have a project to make a VN with speech recognition to pick the choice for route choosing.

is it possible to add this python code:
import speech_recognition as sr
r = sr.Recognizer()

with sr.Microphone() as source:
	print('Say something')
	audio = r.listen(source)

try:
	print('what you said: \n ' + r.recognize_google(audio))
 
except Exception as e:
        print (e)

into renpy's menu choice? (i already installed the pyaudio and speechrecognition in python)

edit:
i tried to install pyaudio and speechrecognition into the game's directory, write init python and write the import syntax just like above untill the r = sr.Recognizer() syntax, but when i tried to run the project this error occurs 
![image](https://user-images.githubusercontent.com/15239895/32428364-4727aa30-c300-11e7-8941-97a89a784a7f.png) even though there's Recognizer attribute within the module 
![image](https://user-images.githubusercontent.com/15239895/32428478-db5836d4-c300-11e7-8bd8-ffa896533481.png)

**Comment by renpytom** [comment]
This isn't a supported Ren'Py API. You could plausibly add it yourself, but it's not something I'm planning on adding, or plan to support you on. Yo may need:

```
init python:
    import sr
```

To gain access to the sr module.
