### ISSUE TITLE
Syntax highlighting for editors is out of date

### ISSUE THREAD

**Issue by morganwillcock** [renpy/renpy#1296]
It seems that the syntax highlighting for supplied editors is a little out of date, as an example, I don't think that vpgrid is present in Editra or jEdit highlighting. The supplied version of jEdit (the program itself) is also quite old, but when using a newer version there is no RenPy mode file available that can be imported within the jEdit configuration. Would it be possible to get the editor customisations as part of the main build, rather than have them only be downloaded with the editors? Or perhaps submit the mode file for inclusion within jEdit so all newer release would have the highlighting?

I guess this would also be linked in with editor selection, but perhaps it would be easier in the long run to suggest installing the Atom language package if `apm` is in your path, give you the jEdit mode file and suggest using jEdit if Java is in your path, or suggest downloading the Editra package if neither of those apply.

**Comment by renpytom** [comment]
I've updated the Ren'Py highlighting for both editors, but not the version, as I'd like to move to atom at some point and don't want tp spend alot of time on this. You can try to pull the customizations out of jedit, but I don't know how they'll work on a newer version.
