### ISSUE TITLE
Sudden Missing Project

### ISSUE THREAD

**Issue by Ruler-Of-Stars** [renpy/renpy#1299]
For some reason, my project, "Inventor Dead" suddenly went missing... I still have the files, so I haven't deleted the game, but it's gone from the Renpy launcher! 
![still there](https://user-images.githubusercontent.com/33796474/32987150-2edce1ac-cc97-11e7-8bdd-d0719c7f1fa3.png)

(The boxed folder is the contents for Inventor Dead)

![launcher](https://user-images.githubusercontent.com/33796474/32987156-68fd05ba-cc97-11e7-96f9-7a8d18f70a9a.png)

This is what the launcher looks like for me (I just got Renpy recently)

**Comment by renpytom** [comment]
Chances are, the projects directory in preferences got unsent. What you want to do is to go into preferences, click the directory name, and pick documents.
