### ISSUE TITLE
Screen manipulations in console restart game

### ISSUE THREAD

**Issue by DarkTl** [renpy/renpy#1303]
Statements like renpy.show_screen(screen_name) or renpy.call_screen(screen_name) work fine in console.

However statements like show screen screen_name or call screen screen_name immediately return game to main menu, pretty much like renpy.full_restart does.

**Comment by renpytom** [comment]
Do you have an example of this? I  just tried it here, and it worked, running the command

```
show screen _image_load_log
```

So I'd like  to know what the screen and the rest of the game looks like. (And if you can repeat this in a minimal project.)

**Comment by DarkTl** [comment]
Pretty much any screen in any project, like show screen help in tutorial.

However, just now I checked updates, and after updating to 6.99.13.2919 it doesn't happen anymore.

**Comment by renpytom** [comment]
Okay, I'll close this out, then. I'm not sure we can expect menu screens like help to work from the console, as they're meant to run in a menu context.
