### ISSUE TITLE
Nightly 10-24: ZeroDivisionError

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1306]
Everything start to work at nightly 10-23. Also checked 10-25 and 10-26, same issue.

I don't checked it on others computers yet, but... this one notebook is REALLY OLD. Like, well, hello to 8 mb VRAM and 4:3 aspect ratio. 

Possible problem 
`        renpy.display.interface.frame_duration = 1.0 * abs(vsync) / info.refresh_rate`
in here: https://github.com/renpy/renpy/commit/7f2b53ec9acb314900fa2c62289058ea7703b946
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 198, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 437, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 437, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 363, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 380, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
ZeroDivisionError: float division by zero
```
Log: [log.txt](https://github.com/renpy/renpy/files/1504310/log.txt)
Full traceback: [traceback.txt](https://github.com/renpy/renpy/files/1504311/traceback.txt)

**Comment by renpytom** [comment]
I'll protect against that, but it looks like your computer is reporting a monitor refresh rate of 0.

**Comment by morganwillcock** [comment]
When I tested this a while ago, it was always returning 0 on iOS and Linux; it might not be computer specific.

https://github.com/renpy/renpy/issues/935
