### ISSUE TITLE
Call screen action leads to ctd

### ISSUE THREAD

**Issue by DarkTl** [renpy/renpy#1308]
An attempt to use Call as a screen action for a button results in ctd. Doesn't matter if from_current is specified or not. Like,

action Call("detective_agency_files", from_current=True)

leads to

File "renpy/common/00action_control.rpy", line 95, in __init__
self.from_current = from_current
NameError: global name 'from_current' is not defined

**Comment by Ria-kon** [comment]
Is this an older version of Ren'py, yes? Try to update to 6.99.13.
https://github.com/renpy/renpy/issues/1288

**Comment by DarkTl** [comment]
No. It's in 6.99.13.

**Comment by renpytom** [comment]
Since that line no longer exists in 6.99.13.1 (I think it went away before the 6.99.13 final), I'm going to close this issue.
