### ISSUE TITLE
.android.json content order changes on every build

### ISSUE THREAD

**Issue by GMMan** [renpy/renpy#1309]
I use Git to keep track of my project files, and it gets a bit annoying that .android.json's contents seem to change on every build, even though I only clicked on the build button. Looks like it's just the order of the elements that change. Ren'Py should either not rewrite the config when building, or at least keep everything in the same order (so it's easier to check differences if the file actually changes).

**Comment by renpytom** [comment]
Do you have examples? It shouldn't change on the build, so I'm curious what in it is changing.

**Comment by GMMan** [comment]
Here's one that's checked in:
```
{"layout": null, "name": "Winds of Change", "package": "klace.windsofchange.android", "orientation": "sensorLandscape", "include_pil": false, "expansion": false, "source": false, "icon_name": "Winds of Change", "version": "1.0", "target_version": 14, "permissions": ["VIBRATE"], "include_sqlite": false, "store": "none", "numeric_version": "100"}
```

Here's what was in my working directory after a build:
```
{"layout": null, "orientation": "sensorLandscape", "package": "klace.windsofchange.android", "include_pil": false, "expansion": false, "name": "Winds of Change", "source": false, "icon_name": "Winds of Change", "version": "1.0", "target_version": 14, "permissions": ["VIBRATE"], "include_sqlite": false, "store": "none", "numeric_version": "100"}
```

**Comment by GMMan** [comment]
I think you typoed the issue number.

**Comment by renpytom** [comment]
Yep, sorry about that. Thanks for letting me know.

**Comment by renpytom** [comment]
Should be fixed now.
