### ISSUE TITLE
Please ship the source files for sphinx documentation

### ISSUE THREAD

**Issue by apoleon** [renpy/renpy#1310]
Please consider to ship the source files for Renpy's sphinx documentation. At the moment the source tarball provided at https://www.renpy.org/latest.html contains only the prebuilt documentation. This makes it more difficult to modify the documentation. Especially for Linux distributions it is preferable to rebuild documentation directly from source, so that multiple copies of jquery/bootstrap etc. can be replaced with a single package.

**Comment by renpytom** [comment]
I'd be happy to do this.

What would work best for you? Right now, Ren'Py builds its documentation in the following way:

* A Ren'Py project (located in sphinx/game) is run. This reflects on the contents of Ren'Py and generates many include files.
* Sphinx is then run to generate the web and include-with-Ren'Py versions of the documentation.

So I guess the question is - should the generator game be included, the include files, or both?

**Comment by apoleon** [comment]
Great! What I'm doing right now is to remove the doc package with all prebuilt documentation and instead I replace it with the entire sphinx directory. Then I run sphinx/source/conf.py with sphinxdoc which produces the web documentation. Right now I'm not sure whether this step also triggers the scripts in sphinx/game. I'm completely happy with also building the generator game from source if you tell me how to do it.

**Comment by renpytom** [comment]
Okay, tomorrow's nightly will include the sphinx directory. It includes a build.sh that shows how I build the Ren'Py docs, which you can use as a starting point.
