### ISSUE TITLE
Grid that has too many elements prevent Fixed autosizing in future elements

### ISSUE THREAD

**Issue by GMMan** [renpy/renpy#1311]
Sample project: https://github.com/GMMan/renpy-grid-bug

Of interest is the `myGallery` screen in `gallery_new.rpy`. It has a vbox that contains a grid and another screen. Inside the second screen it contains a vbox consisting of a frame, text, and another grid. That grid lays out some buttons. The problem is when I have more than 2 rows in the first grid, all of the buttons fail to render correctly in the second grid.

With two rows:
![image](https://user-images.githubusercontent.com/2154355/33520141-274022e8-d772-11e7-8318-1d2306cada8c.png)

With three rows:
![image](https://user-images.githubusercontent.com/2154355/33520143-30e5b57e-d772-11e7-8a04-75b088f5b7ab.png)

It looks like the automatic `Fixed` inside the button couldn't calculate its size properly, ends up having size (0, 0), and never rendering. This also happens if I specifically specify a `Fixed` as the only child; ~~have not tried styling it yet with a constant size~~ it will render if a minimum size is set, but of course using alignments will produce incorrect results.

An observation: When there are three rows, the buttons are off-screen. Maybe the buttons aren't being calculated when they scroll into view?

**Comment by renpytom** [comment]
Is this inside a viewport? If so, you probably want to give the viewport an explicit child_size to make sure it offers the Grid and Fixed inside it enough space to render properly.

**Comment by GMMan** [comment]
Would setting a child_size cause the scrollbar to show even when all contents would fit on a single screen? The number of child elements depend on game progress, so there may be more or less items at different points.

**Comment by renpytom** [comment]
No, it only effects the size offered to the child, not how big the child actually renders. You should be good if you just put an absurdly big number there.

**Comment by GMMan** [comment]
That seems to have done the trick. However, I'm still wondering whether this should be automatic. The docs seem to indicate child_size is for setting a size different to what's automatically calculated, though I pretty much want what's automatically calculated, just with it being consistent in all child displayables.

**Comment by renpytom** [comment]
I've made Ren'Py set child_size automatically.
