### ISSUE TITLE
Alt Gr not working inside the developer console

### ISSUE THREAD

**Issue by Palantogames** [renpy/renpy#1314]
Since the last update (6.99.13.2919) everything that has to be accessed by holding down Alt Gr: @€{}[]|²³\
doesn't seem to work inside the developer console anymore if you use a german keyboard layout.
If I switch to en-US those symbols work. But since I can't find anything you'd do with the Alt Gr key on an english keyboard I don't know if it's just the Alt Gr not working or if it's just the german layout that's not working. The Alt Gr key is working everywhere else and someone tested it with me, in his older ren'py version it worked, when he updated to the lates version it didn't work anymore. Same with mine, in older versions it works in the latest it doesnt.

Edit: It's not the german layout only. It seems to be Alt Gr in general. On the finish keyboard it starts the skipping process even when inside the console.

**Comment by renpytom** [comment]
This has been fixed in master, and AltGr should work properly in the nightly builds.
