### ISSUE TITLE
[Documentation] Invalid link in Ren'Py Android Documentation.

### ISSUE THREAD

**Issue by ricke00** [renpy/renpy#1315]
Hello PyTom,

I don't know where I can report for the documentations, so I report here.

In the Required Language tab, Android page, Ren'Py Documentation, the license link is invalid.
The link call the 404 Not Found, please change its link to https://www.renpy.org/l/license.

https://renpy.org/doc/html/android.html#required-language

> This program contains free software licensed under a number of licenses, including the GNU Lesser General Public License. A complete list of software is available at https://www.renpy.org/l/license/.

**Comment by renpytom** [comment]
I've fixed the website instead.
