### ISSUE TITLE
Jump and Call actions are not equivalent to renpy.jump/call

### ISSUE THREAD

**Issue by Klaim** [renpy/renpy#1318]
I wanted to store actions for later in python block (I tried in several different ways but failed so far):

```
label on_talk:
    ...

label kikoo:
    ...


label chapter_1:

    python:
        action_on_talk = Jump("on_talk")
        action_kikoo = Call("kikoo")

```

Result:
```

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter-1.rpy", line 22, in script
    python:
  File "game/chapter-1.rpy", line 24, in <module>
    action_kikoo = Call("kikoo")
  File "renpy/common/00action_control.rpy", line 95, in __init__
    self.from_current = from_current
NameError: global name 'from_current' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter-1.rpy", line 22, in script
    python:
  File "E:\SDK\renpy\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\SDK\renpy\renpy\python.py", line 1764, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chapter-1.rpy", line 24, in <module>
    action_kikoo = Call("kikoo")
  File "renpy/common/00action_control.rpy", line 95, in __init__
    self.from_current = from_current
NameError: global name 'from_current' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
My Master 0.0

```

However if I do this instead:

label chapter_1:

    python:
        action_on_talk = lambda: renpy.jump("on_talk")
        action_kikoo = lambda: renpy.call("kikoo")

Then the code behave as expected, that is, no error and I can call these objects to trigger the jump/call call.
My assumptions come from the documentation for Actions: "Along with these actions, an action may be a function that does not take any arguments. The function is called when the action is invoked."
and the description of the Jump and Call actions. The doc for Jump action is not clear if it actually do a call to renpy.jump() but Call is clear on it.

So are these two examples (actions vs function) supposed to be equivalent, assuming that I will call them manually from my code's system?

**Comment by renpytom** [comment]
There's a bug in Call that will be fixed in the next release of Ren'Py. That's what's causing your problem, not something fundamental.

**Comment by Klaim** [comment]
Thanks!
