### ISSUE TITLE
purge_unreachable recursively trying to purge its own console output

### ISSUE THREAD

**Issue by BlackDragonHunt** [renpy/renpy#1320]
Apologies for the vague report, but I have no idea where to even begin isolating the issue into something I can replicate from a fresh project. I'm running into an odd issue where, over time, purge_unreachable seems to be recursively purging its own console output, meaning actions progressively take longer and longer as the console tries to print everything—until it gives up and crashes. 

![2017-12-21_06-29-26](https://user-images.githubusercontent.com/680110/34256392-ada4bffe-e61a-11e7-8df5-a71dbdb2d470.png)

It also appears to exhibit similar behavior when opening and closing the in-game developer console,

![2017-12-21_06-56-46](https://user-images.githubusercontent.com/680110/34256719-510c438c-e61c-11e7-8ebe-f07d12ba6417.jpg)

**Comment by renpytom** [comment]
Setting config.debug is probably a bad idea at this point, but I've fixed the problem.
