### ISSUE TITLE
pythonw.exe has stopped working (6.99.14.3081)

### ISSUE THREAD

**Issue by zedraxlo** [renpy/renpy#1324]
When running our 2K project, when holding skipping button and not release, I see the texture using memory increasing very fast, when reaching 1G, game crashed.

**Comment by renpytom** [comment]
Do you have a project I can look at?

**Comment by renpytom** [comment]
(We've changed the way garbage collection works, and this could plausibly be causing this problem, if there's a loop of objects keeping memory alive. But I want to go ahead and look at the game to see if the loop is in Ren'Py or the game proper.)

**Comment by zedraxlo** [comment]
Sure, I'll PM you a Steam key and test branch password when upload finished.
Uploading now.

**Comment by zedraxlo** [comment]
6.99.14.3105:
Bug is not been fixed.
Even config.manage_gc is set to True or False, when in chapter 2, game will crashed when memory gained 900M.

**Comment by renpytom** [comment]
f332b2dcec6e3b14d4e34e19de276bc3c4538a54 should fix the problem. 

Basically, Ren'Py was skipping through your game fast enough the image predictor didn't run. Since one of the things the image predictor does is clear the image cache of old items, that never happened, and memory leaked.

**Comment by zedraxlo** [comment]
6.99.14.3113
I think the memory leak issue is solved.
But can you tell me how to handle the transforms between menus? They are invalid after engine updated.

**Comment by renpytom** [comment]
Please open a new bug, with a small example showing what the problem is.
