### ISSUE TITLE
Possible bug with used screens in 99.14

### ISSUE THREAD

**Issue by DarkTl** [renpy/renpy#1325]
Let's say we have a screen like

```
screen stop_skipping:
    on "show":
        action SetVariable("_skipping", False)
    on "hide":
        action SetVariable("_skipping", True)
```

and it's used by another screen, like

```
screen test_screen:
    use stop_skipping
    button:
        text "Close"
        action Return ("something")
```

In 99.13 calling the test_screen via renpy.call_screen("test_screen") stopped skipping until screen returned the value, then _skipping became True again. In 99.14 it remains False after test_screen returns the value.
It can be fixed by adding Hide before Return, like 

```
button:
     text "Close"
     action Hide("test_screen"), Return ("something")
```

I wonder if it's a bug or a new feature.

**Comment by renpytom** [comment]
Hm... this is the config.zap_transient change mentioned in the documentation. I need to think about if I want it to apply in the call screen case.
