### ISSUE TITLE
Launch problem on macOS

### ISSUE THREAD

**Issue by morganwillcock** [renpy/renpy#1326]
This may be 10.13 or APFS specific as I've not had this problem before, but the current release and pre-release versions won't launch through Finder or by using `open`. I can run it with no problems using ./renpy from within the app package contents, but can't run it any other way. I right-clicked and chose open to allow through Gatekeeper and I'm not getting any prompts about signing issues. This was on an APFS volume, but I have also tried on an HFS+ disk (although I imagine Gatekeeper functionality may still end up involving the APFS formatted system disk).

<pre>$ open renpy.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/mwillcock/renpy/renpy.app.

$ open renpy/renpy.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/renpy/renpy.app.</pre>

I tried to catch the file system structure and what it was running at the time, the command line being:

<pre>/private/var/folders/gt/_66gwh1146sdxt2zfb3l0fwm0000z8/T/AppTranslocation/4B725EA9-0955-42CE-8597-0C7401D5D972/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/renpy -EO /private/var/folders/gt/_66gwh1146sdxt2zfb3l0fwm0000z8/T/AppTranslocation/4B725EA9-0955-42CE-8597-0C7401D5D972/d/renpy.app/Contents/MacOS/../../../renpy.py -psn_0_508028</pre>

...and this is a directory listing immediately after launch, from within /private/var/folders/gt/_66gwh1146sdxt2zfb3l0fwm0000z8/T/AppTranslocation (this may or may not be complete, as these files disappear immediately after the launch failure):

<pre>$ ls -R
AB596F4A-C6EA-4F8B-95A9-82052B9A954A

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A:
d

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d:
renpy.app

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app:
Contents

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents:
Info.plist	MacOS		Resources	_CodeSignature

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS:
lib	renpy

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib:
darwin-x86_64

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64:
Lib				libSDL2-2.0.0.dylib		libavformat.57.dylib		libjpeg.62.dylib		libswscale.4.dylib		renpy
Modules				libSDL2_image-2.0.0.dylib	libavresample.3.dylib		libpng12.0.dylib		libz.1.dylib			zsync
eggs				libSDL2_ttf-2.0.0.dylib		libavutil.55.dylib		libpython2.7.dylib		python				zsyncmake
libGLEW.1.7.0.dylib		libavcodec.57.dylib		libfreetype.6.dylib		libswresample.2.dylib		pythonw

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib:
MacOS.so	_abcoll.pyo	_functools.so	_locale.so	_renpy.so	_sha256.so	_struct.so	binascii.so	copy_reg.pyo	gestalt.so	linecache.pyo	posixpath.pyo	select.so	strop.so	warnings.pyo
UserDict.pyo	_bisect.so	_heapq.so	_lsprof.so	_renpybidi.so	_sha512.so	_weakrefset.pyo	bz2.so		datetime.so	grp.so		math.so		pyexpat.so	site.pyo	time.so		zlib.so
_File.so	_collections.so	_io.so		_md5.so		_scproxy.so	_socket.so	abc.pyo		cPickle.so	fcntl.so	itertools.so	operator.so	pygame_sdl2	ssl.pyo		types.pyo
_Res.so		_ctypes.so	_json.so	_random.so	_sha.so		_ssl.so		array.so	cStringIO.so	genericpath.pyo	lib-dynload	os.pyo		renpy		stat.pyo	unicodedata.so

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib/lib-dynload:
dynload.txt

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib/pygame_sdl2:
__init__.pyo	compat.pyo	display.so	error.so	font.so		image.so	key.so		mouse.so	pygame_time.so	rwobject.so	sprite.pyo	sysfont.pyo	transform.so
color.so	controller.so	draw.so		event.so	gfxdraw.so	joystick.so	locals.so	power.so	rect.so		scrap.so	surface.so	time.pyo	version.pyo

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib/renpy:
__init__.pyo		audio			display			gl			parsersupport.so	pydict.so		style.so		styledata		text

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib/renpy/audio:
renpysound.so

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib/renpy/display:
accelerator.so	render.so

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib/renpy/gl:
gl.so			gl1.so			gldraw.so		glenviron_fixed.so	glenviron_limited.so	glenviron_shader.so	glrtt_copy.so		glrtt_fbo.so		gltexture.so

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib/renpy/styledata:
style_activate_functions.so		style_hover_functions.so		style_insensitive_functions.so		style_selected_functions.so		style_selected_idle_functions.so	styleclass.so
style_functions.so			style_idle_functions.so			style_selected_activate_functions.so	style_selected_hover_functions.so	style_selected_insensitive_functions.so	stylesets.so

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Lib/renpy/text:
ftfont.so	textsupport.so	texwrap.so

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/Modules:
Setup

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/MacOS/lib/darwin-x86_64/eggs:
pyasn1-0.1.7-py2.7.egg	rsa-3.1.4-py2.7.egg

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/Resources:
icon.icns

./AB596F4A-C6EA-4F8B-95A9-82052B9A954A/d/renpy.app/Contents/_CodeSignature:
CodeDirectory		CodeRequirements	CodeRequirements-1	CodeResources		CodeSignature</pre>

**Comment by renpytom** [comment]
Are you using the .dmg?

**Comment by morganwillcock** [comment]
This was the zip file, extracted to my home folder and then copied to the applications folder (to see if that made any difference).

**Comment by renpytom** [comment]
Can you please try the version from the .dmg, and see if that fixes things. MacOS is getting finicky about .zips, and I think you might be getting bit by it.

**Comment by morganwillcock** [comment]
It does seem that getting it via the dmg file is changing something, as that will launch where the other one does not.

I thought it would be the quarantine flags being different:
<pre>$ xattr -l ~/from_zip/renpy-6.99.13-sdk/renpy.app/Contents/MacOS/renpy
com.apple.quarantine: 0081;5a426703;Firefox;DDB11BE2-7C7E-481E-9C9E-F562E28EA150
$ xattr -l ~/from_dmg/renpy-6.99.13-sdk/renpy.app/Contents/MacOS/renpy
com.apple.quarantine: 0181;5a455092;Firefox;F1705C1C-9B3B-402C-9762-A4906E17EB39</pre>

...so then I cleared the attribute on each file:
<pre>find ~/from_zip/renpy-6.99.13-sdk -type f -exec xattr -d com.apple.quarantine {} \;
$ xattr -l ~/from_zip/renpy-6.99.13-sdk/renpy.app/Contents/MacOS/renpy
$ open ~/from_zip/renpy-6.99.13-sdk/renpy.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/mwillcock/from_zip/renpy-6.99.13-sdk/renpy.app.</pre>

...and then on each directory (I wasn't expecting directories to have them set), and then it worked:
<pre>find ~/from_zip/renpy-6.99.13-sdk -type d -exec xattr -d com.apple.quarantine {} \;
open ~/from_zip/renpy-6.99.13-sdk/renpy.app
</pre>

--> opened fine

Feel free to close the issue if you think this isn't Ren'Py specific and affects any application coming from a zip file.

**Comment by renpytom** [comment]
Yeah, I think this is just an example of Apple being user-hostile, and the .dmg is the workaround for it.

**Comment by morganwillcock** [comment]
I imagine they probably wouldn't let you deliver it through the app store either, because of sandbox restrictions (and apparently you would even have to strip all the PowerPC code from the Python binaries). I think this is probably the last Mac I will own...

Thank you for pointing me in the right direction.
