### ISSUE TITLE
Flickering transparent background during transitions

### ISSUE THREAD

**Issue by Dumcem** [renpy/renpy#1327]
If I leave the background transparent, without completely covering it with a background image, it will flicker black when an image appears on it with a dissolve effect, and will return transparent after the transition is complete. Same thing if the dissolve effect is used to hide the image.

A simple test code that shows the problem ("test_image.jpg" can ben any image not big enough to cover the entire screen):

    image bg black = Solid((0, 0, 0, 255))

    image bg test_image = "test_image.jpg"

    image test_parameterized_text = ParameterizedText(color="#fff", text_align=0.5)

    label start:

        pause 1

        scene bg test_image
        with fade
    
        pause 2
    
        scene bg black with Dissolve(1.0)
    
    
        scene bg test_image
        with dissolve
    
        show test_parameterized_text "Lorem ipsum dolor sit amet, consectetur adipisci elit,\nsed eiusmod tempor incidunt ut labore et dolore magna aliqua." at truecenter
        with dissolve
    
        pause 2
    
        hide test_parameterized_text
        with dissolve
    
        scene bg black with Dissolve(1.0)

        return

**Comment by renpytom** [comment]
Sorry, but this isn't a bug. You want to make sure the background is always covered completely.
