### ISSUE TITLE
Extract Dialogue permission error (errors improvement)

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1332]
So, it's simple. If I press "extract dialogue", launcher gives me an error. 
Checked by Lint, there were no errors at all. Checking through game I didn't find any bugs or errors too.
Problem in write permissions for project directory. Without admin/sudo rights, Launcher can't create dialogue.txt and gives you unnamed error that not so easy to found out.

**Comment by renpytom** [comment]
Do you have permissions to write the projects directory? At the end of the day, Ren'Py can't resolve permission problems where it's installed.

**Comment by Ria-kon** [comment]
Now I have. I recursively changed rights of all project to my user and error gone. I don't ask for autoresolve this error, I just would prefer if Ren'Py can identify this kind of error.
