### ISSUE TITLE
Possible bug with saves and rollback

### ISSUE THREAD

**Issue by DarkTl** [renpy/renpy#1334]
In order to disable rollback we used these lines
```
define config.rollback_enabled = False
define config.hard_rollback_limit = 0
define config.rollback_length = 1
```
Turns out it leads to saves instability. If you make a save, then quit the game and recompile the rpyc with part of the code where game should return after loading this save, you will get this error
```
While running game code:
  File "renpy/common/00action_file.rpy", line 432, in __call__
    renpy.load(fn)
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?
```
following by
```
While running game code:
  File "renpy/common/00start.rpy", line 266, in script
    python:
  File "renpy/common/00start.rpy", line 270, in <module>
    renpy.call_in_new_context("_main_menu")
KeyError: u'_main_menu_screen'
```
This happens even if nothing at all was changed in the code, just deleting rpyc is sufficient.
But as long as you don't touch the rpyc, everything is stable. Deleting these rollback lines helps too, naturally. 
Any project is affected, even renpy's tutorial (tested on 99.13). I figured there is a bug during loading a save, unless we used these lines improperly.

**Comment by DarkTl** [comment]
99.14 is also affected, but less. CTD don't happen if save was made when no actors talked.

**Comment by Andykl** [comment]
It would also be nice to note in the documentation that config.rollback_length = 0 makes the log infinite and does not disconnect it, and in long games this makes the save very long.

**Comment by renpytom** [comment]
Documented that you can increase config.rollback_length, but not decrease it.
