### ISSUE TITLE
With() action does not use transitions when given move, ease

### ISSUE THREAD

**Issue by Emperrific** [renpy/renpy#1335]
I'm trying to get something to slide down onto a screen when it enters, but the With() action doesn't seem to be working if I provide a move or ease transition.

```
image header thing = "someimage.png"
default header_toggle = False

screen some_screen:
	textbutton "Do Header":
        action NullAction()
        hovered [SetVariable("header_toggle", True), With(moveintop)]
        unhovered [SetVariable("header_toggle", False), With(moveouttop)]
        xalign 0.5
        yalign 0.75

    if header_toggle:
        add "header thing"
```

This adds and removes the header properly but without the transition. If I switch it to dissolve instead, it does so with the transition.

I'm on the 6.99.14 prerelease, but I also tried it out on 6.99.13 and it seems to have the same issue.

**Comment by renpytom** [comment]
I suspect it actually is using them, but MoveTransitions only work with images displayed on the master layer. They don't work with a screen, for a whole bunch of reasons - it's shown on the screens layer, and the screen itself is really a Fixed, so it'll move on a unit. 

So this isn't a bug, it's Ren'Py working as expected.
