### ISSUE TITLE
Transform with "on replace/replaced" will become invalid sometimes when screen change

### ISSUE THREAD

**Issue by zedraxlo** [renpy/renpy#1341]
Example code:
transform tf1():
    on replaced:
        xpos 0
        linear 1.0 xpos 1280
    on replace:
        xpos 1280
        linear 1.0 xpos 0

screen someone():
    add "something" at tf1

**Comment by renpytom** [comment]
Sorry, but do you have an example game where this issue is triggered? I don't know what sequence of events would cause this problem with 1 screen.

**Comment by zedraxlo** [comment]
Still the last project I sent to you, hope you didn't uninstall it.
The transforms between screens when at main menu.

**Comment by zedraxlo** [comment]
Bug not solved at 3158.
