### ISSUE TITLE
Animation glitches when showing the say screen

### ISSUE THREAD

**Issue by arowana-vx** [renpy/renpy#1346]
Some animations in my textbox/say screen have gotten glitchy in the latest prerelease. My ConditionSwitch animations, in particular, are having issues.

I think the glitches are triggered when I use renpy.show("say") or Show("say"). However, using "window show" does not seem to cause the same problems. 

Here is a test game with one example:
[textbox_test.zip](https://github.com/renpy/renpy/files/1618193/textbox_test.zip)
I saw this glitch in the latest prerelease (6.99.14.3122), but not in the last official release (6.99.13.2129).

Let me know if you need more info, and thanks!

**Comment by renpytom** [comment]
Can you check the next nightly to see if it fixes the problem?

**Comment by arowana-vx** [comment]
Just checked, and my textbox looks good now. Thanks for the speedy fix!
