### ISSUE TITLE
Character(kind=centered) doesn't work

### ISSUE THREAD

**Issue by Dumcem** [renpy/renpy#1347]
Not sure if this is a bug or a wanted behaviour. In Ren'Py 6.99.13.2919, if I try to use this code:

`define new_centered = Character(kind=centered)`

to define a character basing it on the special character "centered", I get the error "NameError: name 'centered' is not defined". Of course, there's a workaround described [here](https://lemmasoft.renai.us/forums/viewtopic.php?t=25130), consisting in stealing the definition of "centered" with a code like:

`define new_centered = Character(None, what_style="centered_text", window_style="centered_window")`

But maybe, if possibile, it would be more intuitive to make the "kind=centered" approach functional.

**Comment by Ria-kon** [comment]
Well, all is easy. 
The "centered" character initializes in 1400 order (https://raw.githubusercontent.com/renpy/renpy/3eb0bcbc3e98dd65a7bd711b02e96c9a1a114502/renpy/common/00definitions.rpy).
Your kind=centered must be 1401 or newer.

So, code
```
init 1401:
    $ new_centered = Character(kind=centered)
```
...is working.
