### ISSUE TITLE
Rollback blocked on language switch

### ISSUE THREAD

**Issue by Saketai** [renpy/renpy#1349]
On 6.99.13 and later, after switching languages, it becomes impossible to roll back past the point of the switch. A repro script is attached. It seems to have been introduced with say-with-arguments (548028f5b571178706f64fedf48b41e73b176200, or the one after, since that one crashes on the first say).

Repro:
1. Advance in the repro script.
2. Switch the language with the Q key.
3. Attempt to roll back.

Expected: Rollback to the earlier lines.
Actual: Nothing happens.

```
label main_menu:
    return

label start:
    show screen translations
    translate None node1:
        "Test 1."
    translate None node2:
        "Test 2."
    translate None node3:
        "Test 3."
    jump start

translate pig_latin node1:
    "Esttay 1."
translate pig_latin node2:
    "Esttay 2."
translate pig_latin node3:
    "Esttay 3."

screen translations():
    key "q" action Language("pig_latin")
    key "e" action Language(None)
    text "Active language: [renpy.game.preferences.language]" xcenter 0.5 yalign 0.1
```

**Comment by renpytom** [comment]
This is expected. Rolling back with a language that was not used to initially play the game has the potential to put Ren'Py into an inconsistent state, so it has been blocked.
