### ISSUE TITLE
Can't show Chinese characters

### ISSUE THREAD

**Issue by dahliavkarma** [renpy/renpy#135]
Hi,
I'm trying to make a game in Chinese and in the game those Chinese characters look like □□□□□□□□□□.
I've also tried in Japanese and it has the same problem.
I'm using renpy 6.15.7.374 on Ubuntu 12.04. I'm using jEdit as the code editor now but I've tried Editra and gedit (and they can't solve the problem). I've also tried different encodings but it doesn't work.
(Sorry I can't upload images... (It seems Github can't process those images?
Thanks :)

**Comment by jyol** [comment]
where do I put this line of code?
