### ISSUE TITLE
Linting python code in .rpy files

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#1350]
Currently, Ren'Py's linter validates that a python expression runs, but not if the code is PEP8 compliant.

Is it possible to take the compiled python expression, write it to a temporary file, and execute https://github.com/PyCQA/pycodestyle against this temp file? 

pycodestyle provides an API for third party usage: https://pycodestyle.readthedocs.io/en/latest/api.html

**Comment by renpytom** [comment]
I don't think Ren'Py will be enforcing style in lint, closing.
