### ISSUE TITLE
Zoom no longer applied to different attributes of the same image tag

### ISSUE THREAD

**Issue by arowana-vx** [renpy/renpy#1352]
Not sure if this is a bug or an intentional change, but I'm reporting it just in case. In 6.99.13, I was able to specify the zoom for one image, and it would automatically be applied to other images with the same image tag. However, this doesn't always seem to work in 6.99.14.

A short test script to demonstrate:

```
image test 1:
    Solid("#fff", xysize=(200, 200))
    align (0.25, 0.5) zoom 0.5

image test 2:
    Solid("#ff0", xysize=(200, 200))

label start:
    show test 1
    "This square is at 50\% zoom."

    show test 2
    "This square stays at 50\% zoom in 6.99.13, but goes back to 100\% zoom in 6.99.14."

    return
```

Strangely, the "align" is still applied to the second image even though the "zoom" isn't. I would've expected them to both be applied or both not be applied.

The specific versions I tested in were 6.99.13.29.19 and 6.99.14.3135. Let me know if you need more information, and thanks!

**Comment by renpytom** [comment]
This is an intentional change. I don't think it makes sense for test 2 to have different zooms depending on how it's shown. 

```
show test 1:
    zoom .5

show test 2
```

Should still keep the zoom factor.

**Comment by arowana-vx** [comment]
Got it, thanks for the quick response! I can see why repeatedly applying zoom would be more problematic than align. Will wait to see what you decide. :)

**Comment by Gouvernathor** [comment]
This has been adressed in some issue since, and documented more clearly.
