### ISSUE TITLE
Self-Voicing Translations with Espeak-ng and Windows Default

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1353]
"Self-voEECHing disAbled"  (c) Russian voices in English Ren'Py =)
So, this is issue with (at least) Linux Espeak, using for self-voicing Ren'py. Well, Espeak-ng, because old Espeak gone long ago. For most parts it works good (No, really. For technical and proofing measures it's really good, just always remember about earsbleed), but in some interface cases Espeak-ng (I don't know about other speech synthesators) starts to do it wrong.

So, here's the video with russian self-voicing of default project.

[Self-voicing with Espeak.mkv](https://github.com/renpy/renpy/files/1631777/self-voicing.with.Espeak.lol.mkv.zip)

# List of all issues:

Double voicing:
- 'Auto' in Quick menu
- Save slots in Save menu (and Load slots in Load menu)
- 'All mute' in Preferences

No voicing for translation:
- 'Q.Save' and 'Q.Load' in Quick Menu
- Many first parts of preferences at Preferences (exc. 'Transitions')

No translation, but voicing:
- '<' and '>'
- Bars in Preferences

Translation voiced, but without needed description (like anywhere else. More of this in Launcher):
- 'Transitions' in Preferences

Needed voicing, but no translation:
- File pages in Save/Load menus. First part (file page) in English, second in Russian.

### In Ren'Py Launcher (no video):
- 'Edit' not translating like 'open directory'
- 'Language' in options not translating.
- 'Viewport vertical scrollbar' in options has no translation, but voicing. 'Activate' and 'deactivate' too.
- And in Navigation and some submenus with many choices and text Espeak starts to read everything, but this is not a bug; just bad feature, because choices themselfs not voicing,

**Comment by Ria-kon** [comment]
And here we go again. Now, with Windows in Tutorial.

[pythonw 2018-02-01 17-51-58-333.avi.zip](https://github.com/renpy/renpy/files/1692195/pythonw.2018-02-01.17-51-58-333.avi.zip)

# List of all issues:

Double voicing:
- 'Auto' in Quick menu
- 'All mute' in Preferences

No voicing for translation:
- 'Q.Save' and 'Q.Load' in Quick Menu
- Many first parts of preferences at Preferences (exc. 'Transitions')

No translation, but voicing:
- '<' and '>'

Translation voiced, but without needed description:
- 'Transitions' in Preferences

Needed voicing, but no translation:
- File pages in Save/Load menus. First part (file page) in English, second in Russian.

No voice:
- Bars at Preferences

**Comment by renpytom** [comment]
This should be fixed in the latest nightly. All the text can be transated. 

The one problem that remains is the doubled text on file save / load slots, and that's mostly just so it works with every (or at least a large number) of games, even ones that don't have numbers on slots.

**Comment by lazykoder** [comment]
Espeak is good for horror novels with its scarry sound, that makes ears bleed 😅 for other cases, I'd consider using RHVoice. Even english voices in RHVoice sound much better In my opinion.
