### ISSUE TITLE
$ renpy.transition strange behaviour

### ISSUE THREAD

**Issue by Dumcem** [renpy/renpy#1358]
Strange behaviour with this code:

```
    image bg black = Solid((0, 0, 0, 255))
    image bg white = Solid((255, 255, 255, 255))

    image test_img = "test_image.jpg"


    label start:
    
        scene bg black
    
        window show
    
        "Start."
    
        show test_img at center
    
        $ renpy.transition(Dissolve(5.0))
        scene bg white
    
        "test_image won't show."
    
        scene bg black
    
        show test_img at center
    
        pause 0.0
    
        $ renpy.transition(Dissolve(5.0))
        scene bg white
    
        "Now, test_image is shown."

        return
```

Something prevents "test_image" from appearing if it is followed by a scene change with the renpy.transition(Dissolve(5.0)) function. Curiously, putting a "pause 0.0" in the middle (like in the second part of the code) prevents the problem.

Fun fact: removing "show window" from the beginning of the code makes the "test_image" appear, but also prevents renpy.transition(Dissolve(5.0)) from working correctly.

Another code triggering a (different) strange behaviour is this:

```
    image bg black = Solid((0, 0, 0, 255))

    image test_img first = "test_image_1.jpg"
    image test_img second = "test_image_2.jpg"


    label start:
    
        scene bg black
    
        "Start."
    
        window hide
    
        show test_img first with Dissolve(0.2)
    
        $ renpy.transition(Dissolve(1.0), layer="master")
        show test_img second
    
        window show
    
        "The test_img will blink instead of fading smoothly."
    
        return
```

In this case, "test_image" won't change smoothly; instead, it will blink while "first" and "second" abruptly exchange with each other. Removing either "window hide" or "window show" prevents the problem. Curiously, removing the Dissolve(0.2) effect from "show test_img first" will prevent "first" from appearing.

**Comment by renpytom** [comment]
I think you're confused by what renpy.transition does. It doesn't take effect until the next interaction. Since the scene and show statements don't cause an interaction, you're having some interesting side effect. Without changing what happens, your first example could be rewritten as:

```
        "Start."
    
        show test_img at center
    
        scene bg white
    
        $ renpy.transition(Dissolve(5.0))
        "test_image won't show."
```

Which should make it obvious why the test image isn't showing. 

The second one is more complicated, but window show is implemented in terms of renpy.with_statement, which will reset the transition. 

I kind of think you'd do better with renpy.with_statement, rather than renpy.transition. (But with_statement goes after the show statement.) Either way, I don't think there's a bug in Ren'Py here.

**Comment by Dumcem** [comment]
Ok, I'm probably using renpy.transition in an improper way: I use it to make the transitions appen without blocking the game flow (particularly, to make characters change expressions while slow text appears in the textbox). Perhaps there's a better way to obtain the effect I want, but renpy.with_statement seems not to be the solution, since it blocks the game in the same way "with" does, forcing Ren'py to wait for the end of the transition before doing what's next (like showing text, etc). Or maybe I'm missing something really important... anyway, thank's for the suggestion.
