### ISSUE TITLE
Mixing im.MatrixColor images with their unaltered versions causes UnboundLocalError

### ISSUE THREAD

**Issue by StefanGagne** [renpy/renpy#1359]
This is my first time submitting an issue, so apologies if it's badly formatted. This is with the nightly build from January 20th, 2018. This error does not happen in release 6.99.14.

Using the following code and the attachment (although it seems to happen with any image file):
```
image test_dimmed = im.MatrixColor(
  "bugtest.png",
  im.matrix.brightness(-0.5) * im.matrix.opacity(0.5))

image test_bright = "bugtest.png"

image test_composite: 
  "test_dimmed" 
  "test_bright"

show test_composite
```

...I get this error:
UnboundLocalError: local variable 'default_bounds' referenced before assignment

Interestingly, if this dimmed frame is commented out, it works fine. If you show the bright frame before the dimmed frame, it's also fine.  It also works fine if the two frames reference different image files.

It only breaks if you show the dim frame, then the bright frame.

(I know this is a useless animation, but it was part of a more complex animation; I did a bunch of testing to boil it down to the simplest repro steps, using a default freshly created empty renpy game. This is the smallest chunk of code that still throws the error.)

Attached is the image I was using:
![bugtest](https://user-images.githubusercontent.com/35638264/35187254-f3e84648-fdee-11e7-9e8a-57357c128795.png)

And here's the traceback:
[traceback.txt](https://github.com/renpy/renpy/files/1649205/traceback.txt)

**Comment by renpytom** [comment]
Confirmed fixed.
