### ISSUE TITLE
[Enhancement] Image location picker refined cursor positioning

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#1361]
The current image location picker tool is incredibly handy and works great. However, there is a feature from ShareX's area capture functionality that I love that I think would make the location picker even better to use. When you enable area capture in ShareX, pressing the up/down/left/right arrow keys move the mouse cursor a pixel in the respective direction. Pretty straightforward, but I find this makes selecting with pixel precision so much easier, and I would like this functionality to benefit Ren'py devs as well.

**Comment by renpytom** [comment]
I don't see an obvious way to make this work on Ren'Py. Ren'Py uses a drag-based approach to choosing the corners of the image, and so it's not clear how that would work with the keyboard.
