### ISSUE TITLE
VP8/VP9 WebM video shows a black frame with renpy.movie_cutscene() at the start of playback

### ISSUE THREAD

**Issue by AXYPB** [renpy/renpy#1364]
When using `renpy.movie_cutscene()` with a WebM file containing VP8 or VP9 video, the first frame will display a full black frame as playback begins. This is undesirable when the video does not begin with a black frame. 

According to renpytom, this may be due to a video buffering fault, which causes Ren'Py to display transparency before the first frame is loaded. When running a project from the launcher, this can go unnoticed by the developer, but built distributions will always show a black screen for a fraction of a second as full screen video playback begins. This issue is present in games built in version 6.99.12.1918, and possibly earlier versions that support VP9 video.

**Comment by renpytom** [comment]
This has been fixed.
