### ISSUE TITLE
Videos skipping in 6.99.14

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1376]
One of my beta-testers found that credits video (vp9, opus, fullscreen video) do not appear, so game just skips to main menu. I already know about such bug in new Ren'Py, but I think it was only in 6.99.13, solved in 6.99.14. But after random change of graphical preferences at Shift+G and reload, video start to work. Switching back to default preferences, video work too.

From beta-tester:
[DxDiag.txt](https://github.com/renpy/renpy/files/1693050/DxDiag.txt)
[log.txt](https://github.com/renpy/renpy/files/1693051/log.txt)

After release (tomorrow) I'll check more people about this issue. If this is only one - okay, this was just missclick, but I'm afraid of situation like in Ren'Py 6.99.13 (when 19 don't saw any video, but 8 saw) or something like that.

**Comment by Ria-kon** [comment]
I tried to reencode into vp8, but now got such bug (tested on android):
1. I see only black screen. After click on screen - "return" - and back to main menu. I can wait any time - minutes, hours, but only after click I can back to main menu.
2. Other beta-tester's phone just skips video to main menu.

**Comment by renpytom** [comment]
Closing, feel free to re-open if the problem exists in 7.4.5 or later.
