### ISSUE TITLE
Saved data locations should follow the XDG Base Directory specification on POSIX systems

### ISSUE THREAD

**Issue by bmwalters** [renpy/renpy#1377]
Currently, the directory `~/.renpy` is used for most of the saved data in Ren'Py games, including game saves and persistent settings. Ideally, Ren'Py should follow the [XDG Base Directory specifications](https://standards.freedesktop.org/basedir-spec/latest/) (see also: the [Arch Wiki](https://wiki.archlinux.org/index.php?title=XDG_Base_Directory_support)) for these files.

This is an interesting task to handle, because existing saved data in the old location should still be read by the engine. The Dolphin Emulator guys [solved this by checking if there was an existing `~/.dolphin` directory](https://github.com/dolphin-emu/dolphin/pull/2304/files#diff-02678fc2bf0e2cf72f4e575a944641a9R160) before assuming they should use the ones defined by the XDG_ environment variables. This is more difficult in Ren'Py because each game is in its own subdirectory of `~./renpy`.

This is very similar to issue #514 which proposes using the "Saved Games" folder on Windows Vista. #548 is also related.

**Comment by renpytom** [comment]
I'd rather than keep Ren'Py looking for files in the same place it's always been, than change just to comply with XDG. Given that this would break old saves and new multipersistent data, is there any articulable benefit to the change?

**Comment by bmwalters** [comment]
The main benefits are all related to organization, primarily enabling easier backups (`rsync` your `~/.local/share` and `~./config` as opposed to `~/.app_x/persisted`, everything in `~/.app_y` except for `shader_cache`, etc.) and reducing the number of files in the home directory.

It's possible to implement the change in a backwards-compatible way by falling back to the current path if there are existing files there. Other projects have set a precedent for this, but as I mentioned it might be different in the case of Ren'Py.

If the logic for handling these locations becomes "more than it's worth" then I can understand foregoing this change, but it's one that quite a few users would appreciate.

**Comment by renpytom** [comment]
I've decided that I'm not going to change this. 

The reason is because this ~/.renpy has been used by Ren'Py for a very long time. What's more, since Ren'Py's distribution model is that applications are distributed with an associated copy of Ren'Py, this means that there are thousands of applications out there that will be saving their data into ~/.renpy/`application` , and that won't change even if I make this change. 

The .renpy directory is a namespace that is shared by thousands of programs. I don't think that it's possible to change that, or even that it makes a lot of sense to try. What's more, I think trying to split that namespace across a pair of directories will lead to a ton of confusion for near zero benefit. 

Why near zero? I just took a look at my .local/share, and found things like the cpan build directory and the system Trash. By contrast, important directories like .ssh are in the home directory, and need to be backed up. 

Making this change would also increase user support costs, as it would become impossible to know which games save to ~/.renpy and which save to ~/.local/share/renpy. 

Therefore, I am rejecting this change request.

**Comment by Hasshu** [comment]
@renpytom Please, reconsider. These discussions on Reddit should serve as a good illustration of why it is a problem:
* [I'm tired of .folders littering my home directory -- want to do something about it. (r/linux)](https://www.reddit.com/r/linux/comments/971m0z/im_tired_of_folders_littering_my_home_directory/)
* [Dotfile madness (r/programming)](https://www.reddit.com/r/programming/comments/amp06h/dotfile_madness/)

**Comment by renpytom** [comment]
Sorry, but I think that my rejection was well-considered, and linking to posts on social media doesn't change that. Ren'Py will respect symlinks that you create, if you choose to symlink .renpy somewhere else.

**Comment by Hasshu** [comment]
I see. It's disheartening that even worthy software is often being held back by appeal to tradition.

**Comment by Arkaeriit** [comment]
I know it's only a band-aid but in order not to have a .renpy in my home folder I put the game folder in ~/.local/share and I put this script under the name of the game in ~/.local/bin:
```sh
#!/bin/sh
# Variable related to the game
GAMEdir="$XDG_DATA_HOME/game name"
GAMEexe="$GAMEdir/game_launcher.sh"

# Save files instalation
mkdir -p "$GAMEdir/.renpy"
rm -Rf "$HOME/.renpy"
cp -Rf "$GAMEdir/.renpy" "$GAMEdir/renpySave"
mv  "$GAMEdir/.renpy" "$HOME/.renpy"

# Launching game
"$GAMEexe"

# Backup save files in the game directory
mv "$HOME/.renpy" "$GAMEdir/.renpy"
```

This make a .renpy folder in the game directory and only put the .reply folder in the home directory when we launch the game. It doesn't work when we try to open two renpy games at the same time.

**Comment by Moth-Tolias** [comment]
if i or another party were to submit a PR with code that - only on linux - changed the defaults to comply with the XDG Base Directory specifications, and used ~./renpy as a fallback, would it be accepted?

as it stands, every visual novel i will ever play will be taking a shit in my home folder, forever, because that's where they've always historically chosen to drop their trousers - despite there being a perfectly acceptable outhouse within arm's reach.

i hope my colourful expression does not cause offence, but i want to stress how unpleasant i find this situation.

**Comment by renpytom** [comment]
No, for the reasons given above. 

I've deleted the rest of your message as inappropriate.

**Comment by lmarianski** [comment]
You already do this kind of thing on Windows, though: https://github.com/renpy/renpy/blob/master/renpy.py#L127-L132

**Comment by Baerbeisser** [comment]
> I've decided that I'm not going to change this.

Fine, how do _i_ change that? What do i need to edit, do i have to use some converters tp dp that?

> The .renpy directory is a namespace that is shared by thousands of programs. I don't think that it's possible to change that, or even that it makes a lot of sense to try. What's more, I think trying to split that namespace across a pair of directories will lead to a ton of confusion for near zero benefit.

The solution outlined in the original question provides a way with zero confusion: if it's there (old ren'py's ~/.renpy) use it, if not (newer ren'py), use XDG_DATA_HOME.

**Comment by BirdInFire** [comment]
> > I've decided that I'm not going to change this.
> 
> Fine, how do _i_ change that? What do i need to edit, do i have to use some converters tp dp that?
> 
> > The .renpy directory is a namespace that is shared by thousands of programs. I don't think that it's possible to change that, or even that it makes a lot of sense to try. What's more, I think trying to split that namespace across a pair of directories will lead to a ton of confusion for near zero benefit.
> 
> The solution outlined in the original question provides a way with zero confusion: if it's there (old ren'py's ~/.renpy) use it, if not (newer ren'py), use XDG_DATA_HOME.

in my case i used a sandbowing software to trick renpy to move it, because for him it's in the right place.

**Comment by Baerbeisser** [comment]
Thanks, but i would rather edit the source.

**Comment by BirdInFire** [comment]
> Thanks, but i would rather edit the source.

editing the source will not fix the dozen of renpy game already made with this address hard coded in it.

**Comment by Baerbeisser** [comment]
Foun it with `grep -Irn '/.renpy'`, should have thought of it sooner.

**Comment by Baerbeisser** [comment]
Btw, found `RENPY_PATH_TO_SAVES` in 8 of 11 games i own. Those who don't have it, are all below 7.5, so i guess this is a new feature?

**Comment by shmerl** [comment]
I can confirm, this patch workaround works perfectly with a 7.4 based game.

**Comment by Vinfall** [comment]
If you have to modify the python script for lower version of Ren'Py, actually you can just use `XDG_DATA_HOME` (or altogether) like this:

```diff
--- game.py	2024-07-03 12:31:04.000000000 +0000
+++ game.py	2024-07-03 12:26:40.000000000 +0000
@@ -105,6 +105,12 @@
     # No save directory given.
     if not save_directory:
         return os.path.join(gamedir, "saves")
+    # Try $XDG_DATA_HOME first, if any
+    if "XDG_DATA_HOME" in os.environ:
+        return os.environ["XDG_DATA_HOME"] + "/renpy/" + save_directory
+    # Then fallback to $RENPY_PATH_TO_SAVES as failsafe
+    if "RENPY_PATH_TO_SAVES" in os.environ:
+        return os.environ["RENPY_PATH_TO_SAVES"] + "/" + save_directory
 
     # Search the path above Ren'Py for a directory named "Ren'Py Data".
     # If it exists, then use that for our save directory.
```

**Comment by CelDaemon** [comment]
This really should be fixed, it's fine to just write to `~/.renpy/<game>` if it exists, and otherwise prefer the XDG directories.

**Comment by Baerbeisser** [comment]
It is, but not in games that still use a Ren'py version older than 7.5. That's up to the game's dev to update the Ren'py version or backport that feature. Complain there.

**Comment by CelDaemon** [comment]
> It is, but not in games that still use a Ren'py version older than 7.5. That's up to the game's dev to update the Ren'py version or backport that feature. Complain there.

Oh seriously? My apologies I didn't realise.
Glad it's fixed for newer games then, I'll just use the patch to fix the older games.
