### ISSUE TITLE
iOS software keyboard can't be dismissed

### ISSUE THREAD

**Issue by robertpeacock22** [renpy/renpy#1382]
I'm working with someone else's legacy code. Their game has two places where text input is expected. In both places, the iOS software keyboard slides up across the bottom half of the screen, sliding the game screen up so that 95% of it is now off the screen. The iOS keyboard is then effectively unable to be dismissed. Every time the dismiss button is tapped, the keyboard slides away but immediately slides back up again.

Apart from making the dismiss button work, which is my highest priority, is there a way that I can make the keyboard cover the game screen rather than push it offscreen?

**Comment by renpytom** [comment]
Okay, sorry about the inconvenience. The keyboard is going to be up whenever you have an editable text input on the screen. So what you should have happen is that the editable input becomes a static text once the dismiss button has been pressed.

You might also want to redesign things such that pressing enter on the keyboard is enough to dismiss the dialogue.

The _text_rect variable controls the area of the screen that's presented to the user. Note that if the game is running in landscape mode, that space is going to be necessarily limited. But this does take a (x, y, w, h) tuple that should let you control the portion that's shown.

The keyboard will be displayed when _text_rect is not None. So if you're using it, you'll need to set it to None when it's time for the keyboard to go away. (That's necessary, but not sufficient - even if it is None, if there's an editable input, the keyboard will show up.)

**Comment by robertpeacock22** [comment]
Thanks for the insight, Tom. What about the issue of the game content being slid almost entirely off-screen? I can actually deal with the keyboard being up the whole time, and redesign the screen in question so that all of the content appears in the top half above the keyboard, but as it is, the keyboard appearing slides about 80-90% of the content off the screen. Is there a way I can make the keyboard slide over top of the scene?

**Comment by renpytom** [comment]
That's what _text_rect is for. It's passed to SDL_SetTextInputRect, which then tells the system what part of the screen it should focus on.

**Comment by robertpeacock22** [comment]
Ahhh, gotcha. Thank you. I will play with that tonight and see if I can figure it out.

**Comment by robertpeacock22** [comment]
Where the `hbox` containing the `input` is defined, if I declare

`$ store._text_rect = (0,0,0,0)`

the keyboard no longer pushes the game content off-screen (the keyboard now just obscures 50% of the game content). However, none of the four numbers appear to have any effect when changed. I feel like I'm possibly going about this the wrong way. Am I completely misusing `_text_rect`?
