### ISSUE TITLE
Custom animated mouse jitter

### ISSUE THREAD

**Issue by misterJL** [renpy/renpy#1384]
Upgraded to Feb 4 release, animated mouse cursor jitters around constantly.
Verified in multiple projects.

Animated simply by using -  define config.mouse

Works fine in Jan release.

**Comment by renpytom** [comment]
I can't repeat this on 6.99.14.2. Can you try it there, and let me know if it's working or not?

**Comment by misterJL** [comment]
Thanks for response.
I tried 6.99.14.2, same issue. Also ran tests on another computer to verify nothing weird was happening on my main. Still present.

[mouse test.zip](https://github.com/renpy/renpy/files/1756749/mouse.test.zip)
