### ISSUE TITLE
updater.rpy question

### ISSUE THREAD

**Issue by mbrickn** [renpy/renpy#1387]
Howdy!

In renpy/launcher/game/updater.rpy

`
    UPDATE_URLS = {
        "Release" : "http://update.renpy.org/release/updates.json",
        "Prerelease" : "http://update.renpy.org/prerelease/updates.json",
        "Experimental" : "http://update.renpy.org/experimental/updates.json",
        "Nightly" : "http://nightly.renpy.org/current/updates.json",
        }
`

The URLs listed are in http. While update.renpy.org doesn't use https, nightly.renpy.org does. 

I don't have a proper computer to test this on currently or else I would run it myself to see if it works. (And assuming it did, submit it as a PR)

I'm not sure if this would actually improve anything, since regular http works just fine, and it looks like you're verifying downloads with a key?

Thank you for your time!

**Comment by renpytom** [comment]
We do not want these as https, as the updater doesn't support https at the moment.

**Comment by mbrickn** [comment]
Understood, thank you for your time!
