### ISSUE TITLE
Rapt 

### ISSUE THREAD

**Issue by oxfire** [renpy/renpy#1390]
I download the jdk and its still says I need to download the jdk

**Comment by Ria-kon** [comment]
You'll need to download JDK x86. JDK 9 still distributing only on x64, so use JDK 8

**Comment by oxfire** [comment]
Can I get a link

**Comment by JenflowStaff** [comment]
The Link is: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

I wasn't sure what OS you are running, so just get the x86 package of whatever OS you need.

**Comment by renpytom** [comment]
This has been dealt with on Discord, I think.
