### ISSUE TITLE
Vertical/Horizontal Bar properties inconsistent with documentation

### ISSUE THREAD

**Issue by qirien** [renpy/renpy#1392]
The documentation for Bar Properties says:
"Note that the valid sides of a bar depend on the value of the bar_vertical property. If it's True, the top and bottom sides are relevant. Otherwise, the left and right sides are used."

However, if you have a bar with a style that includes both top/bottom and left/right properties, such as:

style decreased_bar:
    top_bar Frame(Solid("#aaaaaa"))
    bottom_bar Frame(Solid("#d1282d"))
    left_bar Frame(Solid("#d1282d"))
    right_bar Frame(Solid("#aaaaaa"))

Ren'Py will always use the last values given (left and right), whether the bar is vertical or horizontal.

This is relevant to me as I'm trying to use one style of bar for a bar that is generated and may be horizontal or vertical.  I would like it to use top/bottom if it's a vertical bar, and left/right if it's a horizontal bar.

Am I reading the documentation wrong, or is this not the intended behavior?

**Comment by renpytom** [comment]
Okay, so what's happening here is that internally, top and left are aliased, and bottom and right are aliased. 

Because of this, you can't have a single bar style for vertical and horizontal. (But you couldn't anyway, since bar_vertical is also part of the style.)

**Comment by qirien** [comment]
Well, I was setting bar_vertical programatically as part of the screen code, so I guess I can set those other ones programatically also.  Thank you for looking into it!

**Comment by renpytom** [comment]
Closing this, as I think it's been solved.
