### ISSUE TITLE
Wrap `python hide` blocks in functions?

### ISSUE THREAD

**Issue by eevee** [renpy/renpy#1397]
`python hide` blocks are executed as though they were top-level code, which has some interesting effects on scoping.  For example:

```
python hide:
    import re
    print ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])
```

This produces a `NameError`.  Disassembly shows the `import` is writing into locals, whereas the generator expression (which has its own scope) is trying to read from globals.  A similar problem occurs when trying to create a closure; when it's called later, nothing it closed over exists any more.

I think this is because top-level declarations _don't actually close over_ outer variables — the outer scope is module scope anyway, which is expected to always exist.  But assignments write into locals no matter where they happen; it just so happens that in any top-level scope in normal Python, locals and globals are the same namespace.

So how about implicitly wrapping every `python hide` block in a function that's immediately executed?  i.e., treat the above as:

```
python hide:
    def _scope():
        import re
        print ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])
    _scope()
```

The local scope is initially empty and discarded at the end of the block anyway, so offhand I don't _think_ this should make any visible difference, except that it'd make closures work.

----

Incidentally, since the global scope is the store, the `global` statement works perfectly well for reading and writing store values within a `hide` block.  Might be worth documenting.

**Comment by renpytom** [comment]
Did you test your example? 

I just ran:

```
label start:
    python hide:
        import re
        print ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])
```

And it did not cause a NameError. Is there something else special about doing this? Do you have a traceback when it comes to the name error?

Python should handle this properly, and from what I'm seeing, it does.

**Comment by eevee** [comment]
Well that's interesting.  I _do_ get a NameError from exactly the same script, on master:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2, in script
    python hide:
  File "game/script.rpy", line 4, in <module>
    print ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])
  File "game/script.rpy", line 4, in <genexpr>
    print ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])
NameError: global name 're' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2, in script
    python hide:
  File "/home/eevee/dev-foreign/renpy.venv/renpy.git/renpy/ast.py", line 848, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/eevee/dev-foreign/renpy.venv/renpy.git/renpy/python.py", line 1821, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 4, in <module>
    print ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])
  File "game/script.rpy", line 4, in <genexpr>
    print ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])
NameError: global name 're' is not defined

Linux-4.14.15-1-ARCH-x86_64-with-glibc2.2.5
Ren'Py 6.99.14.2.0
test 1.0
Sat Mar  3 20:15:47 2018
```

It doesn't work in the Python REPL, either:

```
>>> code = compile("""import re\nprint ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])""", "", "exec")
>>> exec code in {}, {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "", line 2, in <module>
    
  File "", line 2, in <genexpr>
    
NameError: global name 're' is not defined
```

Preserving the namespace dicts shows `re` ends up in locals, and `dis.dis()` shows that the genexp is trying to read `re` specifically with `LOAD_GLOBAL`.

**Comment by renpytom** [comment]
This is very strange. 

Are you running a nightly downloaded from renpy.org? I just tried it here, with both an official Ren'Py, and the python that uses ubuntu. 

How do you disassemble the genexpr? I'm not that familiar with dis, so I don't know how to get at a genexp like that.

**Comment by eevee** [comment]
I've been using the binary bits from the latest renpy.org nightly with a git clone.  Just tried using only the nightly, with the same result.  Python is just the stock Arch Linux build (of 2, though it doesn't work on 3 either).

The genexp's code object is squirrelled away as a constant on the main code object:

```
>>> code = compile("""import re\nprint ' '.join(re.escape(s) for s in ['abc', 'def', 'ghi'])""", "", "exec")
>>> import dis
>>> dis.dis(code.co_consts[3])
  2           0 LOAD_FAST                0 (.0)
        >>    3 FOR_ITER                20 (to 26)
              6 STORE_FAST               1 (s)
              9 LOAD_GLOBAL              0 (re)
             12 LOAD_ATTR                1 (escape)
             15 LOAD_FAST                1 (s)
             18 CALL_FUNCTION            1
             21 YIELD_VALUE         
             22 POP_TOP             
             23 JUMP_ABSOLUTE            3
        >>   26 LOAD_CONST               0 (None)
             29 RETURN_VALUE        
```

I spent so long figuring out why this _doesn't_ work that now I can't imagine any reason why it _could_ work, but I've yet to find any explicit documentation either way.  It certainly shouldn't vary between Python builds; does it work in the REPL for you?

**Comment by renpytom** [comment]
Ah, I'm kind of a moron. Turns out that the game I tossed the code into had imported re elsewhere, so it was available in the global scope.
