### ISSUE TITLE
`call ... from` breaks local labels

### ISSUE THREAD

**Issue by eevee** [renpy/renpy#1398]
Consider:

```
label noop:
    return

label start:
    "This is the first line."
    call noop
    "This is the second line."
    jump .inner

label .inner:
    "This is the third line."
    return
```

This works fine.  Now do "Add from clauses to calls, once" and the `call noop` line will become `call noop from _call_noop`.  Result:

```
  File "game/script.rpy", line 8, in script
    jump .inner
ScriptError: could not find label '_call_noop.inner'.
```

I had to completely strip my game of local labels at the last minute because of this; whoops  :)

Two bugs here:

① An implicit `call ... from` label should probably just not call `set_global_label`?  Since the whole point of them is that they're added transparently by the compiler, without affecting the rest of the script.  (I wonder whether `menu` label should or shouldn't?)

② Sublexers don't affect the `global_label` of the parent lexer.  Nesting labels isn't supposed to have any semantic meaning, but it does affect how local labels get their fully-qualified names:

```
label one:
    label two:
        jump .inner  # two.inner

label .inner:  # one.inner
    return
```

(Fixing this would fix the `ScriptError` in the example above, but would cause `jump start.inner` elsewhere to stop working.)

Arguably this is useful behavior, in which case the bug is just in the documentation.  :)

**Comment by renpytom** [comment]
For the record, it looks like this is a problem. I need to figure out what I want Ren'Py to do here, and then I'll make the change.

**Comment by Loraty** [comment]
This is not fixed:

```
While running game code:
  File "game/script.rpy", line 4, in script
    jump .one
ScriptError: could not find label '_call_two.one'.
```

When running this code:

```

label start:
    call two from _call_two
    jump .one
    
label .one:
    return
    
label two:
    return
```
