### ISSUE TITLE
Lint for execution continuing past the end of a file

### ISSUE THREAD

**Issue by eevee** [renpy/renpy#1399]
If you have multiple script files, and one of them doesn't end in a `return` or `jump` or similar, Ren'Py will happily continue executing at the top of whatever file happens to come next in alphabetical order.

This seems like it would _usually_ be a mistake or, at best, a very brittle design.  Perhaps there should be a lint check for it?  Somewhat complicated by the possibility that the last thing in a file is an `init` or `early` block.

Could also be a runtime error — dummy AST node inserted between files that explodes when executed? — but I assume that's out due to risk of breaking existing games.

**Comment by renpytom** [comment]
That isn't the case. Hitting the end of a file is like hitting a return 
statement.

https://github.com/renpy/renpy/blob/master/renpy/parser.py#L2617

Is where  that return statement is being inserted.

**Comment by eevee** [comment]
I'm 0 for 2!  I could swear this happened to me a week or so ago — I distinctly remember being surprised that a route at the end of a file was abruptly jumping into something else — but indeed I can't reproduce it now.  Maybe I was doing something really weird to the call stack.

**Comment by renpytom** [comment]
Yeah, if you have a call on the stack when it happens, then you'd get it going back to wherever the call came from.
