### ISSUE TITLE
Exclude game/saves from builds by default

### ISSUE THREAD

**Issue by eevee** [renpy/renpy#1400]
This seems to be a common gotcha (especially `persistent`) — I've seen several places advise _deleting_ all your saves before building, which is drastic and unnecessary.

Anyone who wants to ship a starting set of save files can just reclassify those individually.

**Comment by renpytom** [comment]
This has been done since time immemorial.

**Comment by renpytom** [comment]
Sorry, that came out snarkier than I meant it to. I'm sick, please forgive me, and I appreciate the report. But 

https://github.com/renpy/renpy/blob/master/renpy/common/00build.rpy#L137

should put into place a build rule that removes the saves directory, and its contents, before building a game. Did you not experience this?

**Comment by eevee** [comment]
Huh, whoops.  I was in a huge end-of-jam rush a couple days ago and must've confused a fresh build with an existing copy.  Sorry for the bogus report  :)
