### ISSUE TITLE
Docs clarification/typos - Incompatible changes page, 6.99.11

### ISSUE THREAD

**Issue by yoshifan** [renpy/renpy#1401]
I mainly wanted to ask for clarification on the `config.quit_action` change, but there happen to be a couple of typos too.

1. > The order of exection of ``style`` and ``translate`` statements ...

   exection -> execution

2. > The :var:`config.quit_action` variable has changed it's default to one
that cause the quit prompt to be displayed of the in-game context. To
revert to the old behavior, add the code::

   it's -> its, cause -> causes

   I still had trouble reading what the change was, though. Not sure if it's just me. Would this be an accurate clarification?:

   > The :var:`config.quit_action` variable has changed its default to one
that displays the yes/no quit prompt only when in the in-game context,
not the main-menu context. To revert to the old behavior of always
displaying the quit prompt, add the code::

(Also: Hi, was around Lemma Soft forums as SleepKirby a while back. Came back to try and finish an ancient project.)

**Comment by renpytom** [comment]
I'll fix these, but basically before the change, when you hit Quit at the main menu, it would ask "Are you sure you want to quit?" Now, since there's no data to lose while you're at the main menu, Ren'Py will simply quit.

**Comment by yoshifan** [comment]
OK, sounds like I was on the right track. Thanks for clearing that up.
