### ISSUE TITLE
VP9 alpha channel is ignored

### ISSUE THREAD

**Issue by eevee** [renpy/renpy#1402]
Just so this doesn't fall through the cracks: you told me on Twitter that this is _supposed_ to work, but it doesn't for me.

Here's a [small VP9 WebM video with an alpha channel](https://github.com/renpy/renpy/files/1778973/test.zip), generated from a pixel art GIF with:

```
ffmpeg -i walk.gif -c:v libvpx-vp9 -b:v 1M test.webm
```

When added to a new game and run against a nightly:

```
image sprite = Movie(channel='movie', play='test.webm')
label start:
    show sprite at truecenter
    "Hmm..."
```

The result is:

![screenshot_20180304_133815](https://user-images.githubusercontent.com/94112/36950870-4bb2804e-1fb1-11e8-93f9-9efde3518e97.png)

Firefox and Chromium both respect the alpha channel, as expected.  Curiously, VLC 2.2.8 composites onto a _white_ background, just like Ren'Py.

----

Incidentally, [the documentation](https://www.renpy.org/doc/html/movie.html#movie-displayables-and-movie-sprites) says the `channel` argument "should never _not_ be left at the default of 'movie'," but both examples ignore that advice:

```
image eileen movie = Movie(channel="eileen", play="eileen_movie.webm", mask="eileen_mask.webm")
```

```
image main_menu = Movie(channel="main_menu", play="main_menu.ogv")
```

**Comment by renpytom** [comment]
Looking at this, it seems that ffmpeg doesn't support a webm with an alpha channel. I'm not sure why I thought this would work - perhaps I was mistaken, or perhaps I was testing with a version of ffmpeg that was linked against libvpx, rather than one that used its native decoder. 

I apologize for sending you down the wrong path.

**Comment by eevee** [comment]
Huh, strange.  Firefox [appears to use ffvp9](https://bugzilla.mozilla.org/show_bug.cgi?id=1210219), and it handles the alpha channel correctly; but on the other hand `ffplay` doesn't, and the only ffmpeg ticket I found about this [was closed invalid, saying to use libvpx instead](https://trac.ffmpeg.org/ticket/5792#comment:1).  Can't seem to find anything about whether this is planned for the future or why it works in Firefox.

**Comment by eevee** [comment]
Looks like the VP9 alpha channel is stored as a separate stream in the _container_, and Firefox handles decoding that stream at some higher level.  So fixing this would require doing the same thing in Ren'Py, or doing the same thing in libavformat.  Yikes.

**Comment by Palantogames** [comment]
Well we use vp9 .webm too, and it does work but only with a mask video... so in a way it does work but not really at the same time ;)

**Comment by renpytom** [comment]
I don't think this is going to happen. The side_mask argument to Movie is now the preferred way to do this.
