### ISSUE TITLE
Enable TTS for built games

### ISSUE THREAD

**Issue by hotpxl** [renpy/renpy#1412]
I guess this is more of a usage question. I downloaded a game built using RenPy, and it does not have TTS option in the settings. Can I modify the code to manually enable this? I tried editing config.py and set `tts_voice = "Alex"` since I'm on Mac but it gives me no results.

**Comment by renpytom** [comment]
Which game is it? 

TTS is enabled by pressing the 'v' key in any game that supports it. It was a relatively (in the past few years) recent addition, so older games might not. You can often get an older game working by downloading the Ren'Py SDK, and moving the game into the Ren'Py SDK (That is, next to the_question), then selecting it in the launcher and launching it.

Hope this helps.

**Comment by hotpxl** [comment]
Sure. It's DDLC 
Nothing happens when I press `v`. I'll try the SDK approach then.
