### ISSUE TITLE
[6.99.14.2] NVL Text displayed instantly regardless of the Text Speed preference/<slow> property

### ISSUE THREAD

**Issue by Rastagong** [renpy/renpy#1418]
Hey there!  
I'm having some problem with NVL text in the new minor release of Ren'Py (6.99.14.2).

# The problem
Basically, any NVL line **is displayed instantly** on the screen instead of being displayed character by character. This happens regardless of:  
* the Text Speed preference
* the `slow` parameter of the dialogue Character speaking  

# Reproducing the bug
Generate a new project with Ren'Py 6.99.14.2, and change Eileen's dialogue character to NVL mode: `define e = Character("Eileen", kind=nvl)`  
Launch the project, set the text speed somewhere in the middle of the bar in the config menu, and start the story. The lines spoken by Eileen appear instantly on screen:  
![2018-03-29_13-16-49](https://user-images.githubusercontent.com/720624/38088418-066af75a-335c-11e8-930a-3fb4f29f25ce.gif)

When you attempt the same test but with Ren'Py 6.99.14.1 (make sure to recompile the project), the text appears character by character, which is the expected behaviour:  
![2018-03-29_13-17-47](https://user-images.githubusercontent.com/720624/38088442-23cfe0a8-335c-11e8-9885-1e7cba0b32ff.gif)

# Cause of the bug
Did a bit of debugging and tried out the nightly builds, and I believe the change made in `renpy/sl2/slast.py` in commit [#f69c46c7e](https://github.com/renpy/renpy/commit/f69c46c7e63229603f75e9914316acdae231920b) is responsible.

I don't understand much about this commit myself, ahaha, but here's what I think causes the problem:

With this change, in NVL mode, screen language evaluation renders a new Text element instead of using the Text element that is processed by the `display_say()` function used by the Character class. More specifically, it seems that [the assignation of the `slow` property on the Text element by the dialogue Character](https://github.com/renpy/renpy/blob/458de8bedd2642f1227b7faba597d579141ff779/renpy/character.py#L547) (`what_text.slow = slow`) is missed.  
At first the assignation of `slow` occurs as expected, but then screen evaluation generates **another** Text element instead, and the assignation doesn't occur on this one.      
Since the `slow` property is not present on the Text element, during rendering, [the `slow_cps` property is set to False](https://github.com/renpy/renpy/blob/458de8bedd2642f1227b7faba597d579141ff779/renpy/text/text.py#L1791), and the text is displayed instantly, unless the user specifically styled the dialogue Character otherwise with the `what_slow_cps` parameter.

# Solution
I have no idea, I hope it's not too much trouble to fix! I'll just use `what_slow_cps` in the meantime.

That said, I'm realising that the `slow` parameter passed to ADVCharacter might be redundant with `what_slow_cps` anyway? So in the long term, it might be preferable to just provide a default value for `what_slow_cps` in ADVCharacter.  
Well, I might be completely wrong too, there may well be a dedicated purpose to `slow` as a Character parameter too.

**Comment by Rastagong** [comment]
Oh okay, just realised that using `what_slow_cps` would make the text be displayed one character after the other **all the time**, for all paragraphs, so yeah, that's clearly not a solution.

**Comment by renpytom** [comment]
I think this was fixed by ee381010a583970ec8db4adbd4753214b673c4ef . Could you check out the 6.99.14.3 prerelease at https://renpy.org/release/6.99.14.3 , and confirm it's been solved?

**Comment by Rastagong** [comment]
Yup, it works perfectly with this build! Thanks a bunch. :)

**Comment by renpytom** [comment]
Thanks for a well-written and complete bug report.
