### ISSUE TITLE
GL Rewrite Goals

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1422]
- [ ] Use UGUU to unify GL and GLES into a single codebase.
- [ ] Upgrade ANGLE.
- [ ] Generate shaders, allowing the creator to intercept some pipeline stages.
- [ ] Support for Matrixcolor in shaders.
- [ ] Support for texture-mapped geometry.
- [ ] Support for mipmapping textures on upload.
- [ ] Support variable aspect ratios within a range.

**Comment by tcyrus** [comment]
Link to [UGUU](https://github.com/renpy/uguu)

**Comment by renpytom** [comment]
UGUU is now developed as part of Ren'Py, and has been for a while.
