### ISSUE TITLE
Developer Menu and Interactive Director Showing Not Completely in English

### ISSUE THREAD

**Issue by Malystraza** [renpy/renpy#1428]
On version 6.99.14.3.3347, when I open the Director menu or the Interactive Director, certain elements are using the Cyrillic alphabet, rather than Latin/English alphabet (see attached screenshots - clicking the '+' sign in ID will show other such errors).

![2018-04-12 1](https://user-images.githubusercontent.com/38321759/38680006-3ec4fe7a-3e33-11e8-8293-f6bb03662584.png)
![2018-04-12](https://user-images.githubusercontent.com/38321759/38680010-406441f0-3e33-11e8-8bb8-39b0965da4dd.png)

**Comment by renpytom** [comment]
Thank you for the report. This has been fixed by 20e50a9e06108a6bff445f44219e42150813f008 , which will be part of the Ren'Py 7 prerelease coming soon.
