### ISSUE TITLE
LayeredImage doesn't report the source file/line when exceptions occur.

### ISSUE THREAD

**Issue by SpikyCaterpillar** [renpy/renpy#1437]
In 7.0.0.51 on Debian, sticking:
`attribute from_u1 "ellen/uniform1.png" at fadeoutonreplace:`
in a LayeredImage crashes with a traceback complaining that 'fadeoutonreplace' is not defined in file "<string>", line 1.

**Comment by renpytom** [comment]
Same issue as #1438, fixed.
