### ISSUE TITLE
Allow code to be executed at each choice

### ISSUE THREAD

**Issue by Klaim** [renpy/renpy#1446]
Add a way to plug a callback that will be executed each time a choice is made.

This is to help with cases where you want something to happen at each choice taken, not necessarilly related to the choice, without having to copy-paste code at the point the choice goes to.

Typically, it would help with calling `renpy.fix_choice()` automatically after each choice, instead of having to call it at the beginning of each section after a choice (which makes hard to update or move the script).

Something like that would be ok I think:

     # somewhere in configuration:
    config.on_choice_taken = None # You can set your own callback here, not sure about the parameters.
    
Example:
   
    init python:
 
        yes_count = 0    

        def count_yes(choice_string):
           renpy.fix_choice()
           if choice_string == "Yes":
               global yes_count
               yes_count = yes_count + 1

     # somewhere in configuration:
    config.on_choice_taken = count_yes

    # somewhere in the game script:
    menu "Are you sure?":
       "Yes":  # count_yes++
            "Then everything is ok." 
        "No"  
            "Then we are lost, forever."

**Comment by renpytom** [comment]
This exists already, as the menu variable. It takes a function that is called to present the menu choice to the player. It defaults to renpy.display_menu, but you can replace it with your own function with the same signature, that proxies calls to renpy.display menu. For example:

```
init python:
    def menu(items, interact=True, screen="choice"):
        rv = renpy.display_menu(items, interact=interact, screen=screen)
        renpy.fix_choice()
        return rv
```

**Comment by Klaim** [comment]
Oh I see, thank you! I was looking for a function call or a config variable but that way works too, totally missed that.

**Comment by Andykl** [comment]
Read the documentation first https://renpy.org/doc/html/store_variables.html#var-menu
You must change store variable "menu" on your function before this menu.
And remember what the menus return № of choisen item.

**Comment by Klaim** [comment]
Hi, thanks @Andykl  for taking the time to help me, it's very much appreciated!

First, I tried the solution that @renpytom  provided the same way he wrote it because it seems to apply to all menu calls and this is what I want. I tried both defining `menu` function and doing `menu = my_menu` and they are both called when any following menu is displayed, so basically both seems to do the expected behavior.

Second, I do return the result `renpy.display_menu` which is (I checked) the number of the item chosen (see in the repro case I provided). This also clarifies that the line `renpy.fix_rollback()` in my example is correctly called just after the chose is made, not before.

Third, this *still does not fix my issue:* I can still rollback and do another choice with this repro case. So far the only way I managed to make it work is to call `renpy.fix_rollback()` as first line of the chosen label to jump to. So basically, it does not seem to work as long as It's called inside the menu function, but it does work outside of it or something like that.

Just to be sure everything is clear, as of Renpy 7.0.0.196, I re-created an empty project and just used the repro case as follow.

This does not work: I can rollback and change the menu choice:

```
init python:

    # Called each time there is a choice taken:
    def menu(items, interact=True, screen="choice"):
        rv = renpy.display_menu(items, interact=interact, screen=screen)
        renpy.fix_rollback() # Automatically force fixed choice!
        return rv


label start:


    "Before the question..."
    menu:
        "The question?"

        "Yes":
            "OK"
        "No":
            "Too bad"

    "After the question"


```


This works: I can rollback but I cannot change the choice:

```

label start:


    "Before the question..."
    menu:
        "The question?"

        "Yes":
            $ renpy.fix_rollback()
            "OK"
        "No":
            $ renpy.fix_rollback()
            "Too bad"

    "After the question"


```

I can add a menu function, it does not change a thing: as soon as the rollback is done after the menu function is called, it is taken into account, otherwise it is not.
Please consider trying this example for yourself, see if I'm doing something wrong.

Did I miss something else? Another confiugration variable which reference to might be missing in the related doc pages?

Or maybe do you have a working example? That would help me a lot. I'm tired of copy-pasting that command at each possibility.

**Comment by Andykl** [comment]
Hm, i looked code of fix_rollback code, it fixed choice of last interaction.
But if you fix_rollback in menu function it does not work because menu interaction not completly done.
```
            def menu(items, interact=True, screen="choice"):
                rv = renpy.display_menu(items, interact=interact, screen=screen)
                rlb = renpy.game.log
                if not rlb.rollback_is_fixed:
                    rlb.fixed_rollback_boundary = rlb.log[-1].context.current
                return rv
```
This code is work.

**Comment by Klaim** [comment]
@Andykl Thanks for your patience and help, this code does work in my test. I'll try it in my game too now (sorry for the delay)

Indeed it looks like a hack. To me some option or function is missing that does exactly that. Would it be ok to simply provide an alternative to fix_rollback() that just do the part relying on the game log?
Or is that more general anyway and should replace the code of fix_rollback()?

**Comment by Gouvernathor** [comment]
This seems fixed.
