### ISSUE TITLE
Improving tutorial to present layered image functionality

### ISSUE THREAD

**Issue by Alexandre-T** [renpy/renpy#1450]
As I am one of your Patreon sponsors, I had access to your layered image conversion article. If you want, I can help you by improving the tutorial with a new menu which describes this new and excellent functionality.

As English is not my native language, you certainly have to revise some sentences. Afterwards, I will translate this example in French.

If you agree, I will do it next week and pull a request attached to this issue.

**Comment by renpytom** [comment]
I like the idea, but what are you going to use for the image we'll demonstrate with?

**Comment by Alexandre-T** [comment]
Tutorial needs to remind simple. Creators need a clean example not a heavy sample which could be difficult to understand. So, I think that a face with two or three different expressions should be enough.

I have three proposals:
* If you and the team behind Arcade Spirits agree, we could use Naomi’s face with two or three expressions (happy, laughing and sad, as an example). Of course, I will add some link to quote their work.
* I could ask to my wife to do a little artwork, but her planning is heavy and she needs some time to do it.
* I could use gimp to create the layers from Eileen’s face.

**Comment by renpytom** [comment]
I'm talking to an artist about this. I think this would be good, but it probably makes sense to let Ren'Py 7 come out, let people get some experience with layered images, and then add it to the tutorial. This way we don't have to change and retranslate the tutorial.

**Comment by Alexandre-T** [comment]
Yes, it is. It makes sense to let Ren'Py 7 come out. I don't know if you have some "standby" tag in your issue, so I close it and we will open when people get some experience with layered images.
