### ISSUE TITLE
[rapt] Android build failed - cannot find build.xml

### ISSUE THREAD

**Issue by Kowoon** [renpy/renpy#1452]
The Android team has decided to remove all old and obsolete scripts from SDK in march release of 25.3.0 SDK Tools: https://developer.android.com/studio/releases/sdk-tools
Changes:
Obsolete/deprecated tools have been removed:
- ...
- ant scripts have been removed

**Comment by renpytom** [comment]
I haven't been able to repeat this. Ren'Py downloads an older build of Android, so this still works. At some point soon, I'm going to rewrite things to use Android Studio and related tools, but that'll be after Ren'Py 7 is out. Perhaps as soon as 7.0.1, something like that.

**Comment by renpytom** [comment]
Are  you upgrading android past what ships with Ren'Py?
