### ISSUE TITLE
Movie sprites with masks getting out of sync

### ISSUE THREAD

**Issue by Emperrific** [renpy/renpy#1455]
I defined a movie sprite in the normal way

```image person something = Movie(channel="person", play="person-movie.webm", mask="person-mask.webm")```

Usually this works fine, but sometimes when transitioning from one to another movie sprite of the same name, I end up with the movie and the mask getting out of sync, even though they were created based on the same image sequence. See below.

![screenshot0001 2](https://user-images.githubusercontent.com/19784930/39873964-0b2fb4be-5432-11e8-99ef-e237e96217c6.png)

**Comment by ksiadz** [comment]
This is still happening. 

```python
    image hime = Movie(play="images/characters/hime/emiko_test_1080.webm", mask="images/characters/hime/a-emiko_test_1080.webm")
    image aa = Movie(play="images/characters/hime/emiko_test_1080.webm", mask="images/characters/hime/a-emiko_test_1080.webm")
```

Frames seem to get out of sync after the first animation loop ends. 

The way I am generating my webms:

```bash
ffmpeg -framerate 30 -i Scene1_%03d.png -filter_complex "alphaextract[a]" -map 0:v -c:v libvpx-vp9 -crf 0 -b:v 0 miyu-happy-pants.webm -map "[a]" -c:v libvpx-vp9 -crf 0 -b:v 0 a-miyu-happy-pants.webm
```

The only way I was able to mitigate it was to make the animations full scree, but then my sprits cannot be shown at the same time by positioning them on the left/centre/right.
