### ISSUE TITLE
Mac Touch Bar Functionality

### ISSUE THREAD

**Issue by kawaiidesune** [renpy/renpy#1457]
Hello,

So, I'd like to add functionality to have Ren'Py work with [the Touch Bar that is included in the new 15" MacBook Pro](https://developer.apple.com/macos/touch-bar/) (the link is to the Apple developer documentation on the subject). Ideally, this would also include expanding the Ren'Py documentation and language so that the touch bar menu would support both story choices and custom menu functionality.

**Comment by renpytom** [comment]
Sorry for not replying in so long. I thought I had replied, but I didn't.

My feeling is I don't want it. It's a platform-specific feature, and one that's only available on a small number of expensive laptops. That's not something I'd want to add to Ren'Py.
