### ISSUE TITLE
Additional project directories

### ISSUE THREAD

**Issue by Solybum** [renpy/renpy#1459]
Due to how the projects are handled (all in a single directory) is a bit complicated to get a structure for version control.

During a brief talk in DIscord someone suggested multiple project directories/favorites and while this is fine is probably more work than what I had in mind.

My idea was to be able to either override the projects directory or include a new one (temporarily) by passing parameters to renpy
After some tinkering came up with this.
```py
add_project_path_arg = "--add-project-dir="
for x in range(1, len(sys.argv)):
    add_project_path = sys.argv[x]
    if add_project_path.startswith(add_project_path_arg) == True:
        # Remove --add-project-dir=, then quotes
        add_project_path = add_project_path[len(add_project_path_arg):]
        add_project_path = add_project_path.strip('"')
        self.scan_directory(add_project_path)
```
After https://github.com/renpy/renpy/blob/master/launcher/game/project.rpy#L443

However, when you pass an argument to renpy, it attempts to launch a game directly.
I suppose an easy fix would be to **not** launch a game and continue normally if there is a "tag" at the beginning of the argument, like (double) dash (don't really see any game having that at the beginning of its name, and in such cases a new argument could be used) but again, I don't even know where that is handled.

I don't know if it would be good to submit the snippet in a PR due to the fact that it will not work unless the arguments issue is solved, also I realize this might not the best way to approach it but there is the idea.

**Comment by renpytom** [comment]
Search the changelog for projects.txt . That's how  you can do this right now.

**Comment by Solybum** [comment]
I missed that entirely, I was looking specifically for command line stuff.
I'll close the issue then since there wouldn't really be a need for this.
Thank you!
