### ISSUE TITLE
Renpy.exe and all exe game made from renpy can't run on Windows 10

### ISSUE THREAD

**Issue by NickGrimmXXX** [renpy/renpy#1467]
Hello,
all my game made from renpy can't run on Windows 10. When i launch (game).exe nothing happened.
I already run exe application as Administrator and using compatible mode.
I already use japanesse unicode and try many problem solving but still don't work.
Please help me and sorry for my bad english.
Thanks.

**Comment by NickGrimmXXX** [comment]
@renpytom please help me

**Comment by renpytom** [comment]
I don't know what this would be. Certainly, it runs on Windows 10.

There is an issue that will cause a problem if the path to Ren'Py is not representable in the system encoding. (For example, if your user name is Russian and your system is set to Japanese, you might have a problem.)

**Comment by NickGrimmXXX** [comment]
"There is an issue that will cause a problem if the path to Ren'Py is not representable in the system encoding."

my user name is "Home" and using English Format. Only "Current Language for non-Unicode Programs" i set to Japanesse (Japan).
can you give other example tom?
because i don't understand.

**Comment by renpytom** [comment]
Sorry, that's the only issue I  know of. Look for log.txt or traceback.txt files that might describe the problem.

**Comment by NickGrimmXXX** [comment]
![renpy problem](https://user-images.githubusercontent.com/39650028/40578009-142d256c-6137-11e8-8e84-61238f96ff9b.jpg)

"Importing _renpysteam: ImportError('DLL load failed: The specified module could not be found.',)"

how to fix that @renpytom ???

**Comment by NickGrimmXXX** [comment]
![other game](https://user-images.githubusercontent.com/39650028/40578073-d681f30e-6137-11e8-81b0-49e3bf63632e.jpg)

"Importing _renpysteam: ImportError('No module named _renpysteam',)"

**Comment by NickGrimmXXX** [comment]
@renpytom  please help

**Comment by tcyrus** [comment]
@NickGrimmXXX, check if `_renpysteam.pyd` is in `lib\windows-i686\Lib` and `steam_api.dll` is in `lib\windows-i686`

**Comment by Andykl** [comment]
I work on Windows 10 1803 and I run the game without _renpysteam
![image](https://user-images.githubusercontent.com/27142420/42138232-b3793764-7d93-11e8-93f1-80defa163f74.png)
Post you error code.

**Comment by renpytom** [comment]
I don't believe this is a problem with Ren'Py. It's more likely to be a problem with the user's video drivers, something like that. I'd suggest updating all video drivers, and uninstalling things like game optimizers and antivirus software that could interfere with OS semantics.

**Comment by ParaPredeath** [comment]
I can't download Ren'py on my windows 10 does it not work with S mode active?
