### ISSUE TITLE
Adding a timer event or method to CDDs

### ISSUE THREAD

**Issue by Dogeek** [renpy/renpy#1473]
It would be great to add a timer method that triggers every x milliseconds (renpy.redraw being highly inconsistent in terms of time measurement (compared to time.clock())

the issue with redraw is that the number of seconds seems to be dependant on the framerate. The higher the framerate the game runs at, the faster the redraw is triggered, which means inconsistent behaviors for minigames across different specs and devices. It can be critical, for time-dependant minigames, as that can make the minigame way harder on high end machines, and ridiculously easy on lower end ones.

**Comment by renpytom** [comment]
Look at the st argument to render. It gives you the number of seconds the displayable has been show (including fractional seconds), which should let you then run a minigame at the correct speed.
