### ISSUE TITLE
Renpy crashes after selecting german in the language settings

### ISSUE THREAD

**Issue by Martin1995** [renpy/renpy#1474]
Hello i have a problem with an in program bug that occurs if i switch to german language.
the only thing that helps getting rid of this error is to delete persistent in~/.renpy/launcher-4/ but that also resets it.
maybe you have an solution for this.
Thank you for your help
System Information:
Arch Linux x86_64
LTS Kernel

Backtrace that renpy shows on screen:
[renpy  backtrace set to german language.txt](https://github.com/renpy/renpy/files/2064001/renpy.backtrace.set.to.german.language.txt)

**Comment by renpytom** [comment]
I believe this is fixed in the 7.0.0 prerelease.

**Comment by renpytom** [comment]
You should be able  to install the 7.0 final release.

**Comment by Martin1995** [comment]
Then i have to install it from your website, because my packagemanager is only showing version 6.99.14.3
`$ yaourt renpy`
`1 community/renpy 6.99.14.3-1 [installed]`
  `  The Ren'Py Visual Novel Engine`
`2 community/renpy-demos 6.99.14.3-1 [installed]`
    `The Ren'Py Visual Novel Engine`
`

**Comment by renpytom** [comment]
I don't support packaged versions of Ren'Py, you'll have to talk to your
distribution about that.

**Comment by Martin1995** [comment]
Thanks for the help version 7 does its job, i uninstall the old version on my system
