### ISSUE TITLE
Updater error UnicodeDecodeError for Linux

### ISSUE THREAD

**Issue by maxlefou** [renpy/renpy#1481]
I have a game that is compiled for the 3 platforms and uses the updater.
I recently compiled an update for this game with Windows 10.

While using the updater to update a copy of the game under Windows works perfectly, doing the same on Linux doesn't work at all and gives the following error:
`UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 53: invalid continuation byte`

But when I try again after compiling the game's updates under Linux and not windows, this works perfectly everywhere.

Noticed this problem with 6.99.14.3.3347 and 7.0.0.196.
I suspect Atom to be the culprit since I started using it with these versions and noticed this problem since. But I'm not sure.

**Comment by renpytom** [comment]
Can you post the full traceback? This seems more likely to be some sort of corrupt filename or file contents.

**Comment by renpytom** [comment]
No idea here. Can I get the game, so I can try it? Those lines don't  seem to exist in Ren'Py.

**Comment by maxlefou** [comment]
[Here](https://maxlefou.itch.io/kwk). The files are not updated yet in there so the updater should be active and work with this version.

**Comment by renpytom** [comment]
Okay, so the problem is with cache/Copie de bytecode (conflit du 16-05-2018 ? 18h08).rpyb , which has an invalid filename. Delete that file and rebuild, and the immediate problem goes away. In general, non-ASCII filenames are unreliable, and should be avoided. This is one step worse, as it's not even utf-8.

**Comment by maxlefou** [comment]
Thanks for the reply and the find out. All of this because of my cloud service doing garbage... -_-
