### ISSUE TITLE
Default var = value after load -> rollback get deleted

### ISSUE THREAD

**Issue by Palantogames** [renpy/renpy#1489]
Sorry for the cryptic title!
The problem is, variables that get implemented in a patch, get loaded but once a player does a rollback they get deleted even though that shouldn't be the case for defaulted variables...
We tested the same things in 6.99 as in the latest version, before the update it worked, now it doesn't.

Try something simple like this:
```
#default v1 = 0
   
label start:
    "Day1:"
    "save now"
    jump d2

label d2:
    "Day2:"
    return
```
play once, save, quit, enable the default, play again and check for the variable on "Day1:" as well as on "Day2:", day2 has the variable set, day1 not

**Comment by Palantogames** [comment]
Not entirely sure yet, but it could have been happening because I didn't add a return at the end of the after_load label. Close it for now since I'm not sure it's a bug on your end.

**Comment by renpytom** [comment]
Okay, closing, feel free to reopen it if it reoccurs.
