### ISSUE TITLE
Voicing inside menu prompts

### ISSUE THREAD

**Issue by GMMan** [renpy/renpy#1496]
I'd like to do something like this:
```rpy
menu:
    voice "se/z00078.ogg"
    char_valessa "Gold and White — The Triumvirate's Standard.\nI would have never made such a deduction, but...\nOnly they could wield the spirits in this fashion."
    
    "{image=icons/651.png} \"Wait, what's The Triumvirate...?\"":
        # ...

    "{image=icons/651.png} \"Why would they do such a thing...?\"":
        # ...
```
where the voice is inside the menu and applies to the prompt on the next line. Unfortunately, that doesn't seem to be supported. Could this be made possible? (I actually also have a line setting the channel volume before the voice command.)

**Comment by renpytom** [comment]
It should work if you put it immediately before the menu.

**Comment by GMMan** [comment]
Yeah, I just checked that inside Ren'Py 7.0.0, seems to work now when it didn't in 6.99.14. Currently stuck on the latter until I hammer out a few incompatibilities with the former.
