### ISSUE TITLE
sl imagebutton selected

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1498]
Add to the screen language the ability to specify only the selected state instead of duplicating in selected_idle and selected_hover

**Comment by renpytom** [comment]
I don't think I'll be doing this. I think there's too much ambiguity here, especially in the auto case - if button_hover.png and button_selected.png exist, and button_selected_hover.png does not, which one should we pick? I don't think there's a good and obvious answer there, and so I think the right solution is to requires the creator to resolve this.
