### ISSUE TITLE
RENPY_DEPS_INSTALL uses "::" to separate paths instead of os.pathsep

### ISSUE THREAD

**Issue by Uzume** [renpy/renpy#1499]
I considered directly making a pull request but I instead decided to first bring the issue up here for discussion in case there is some amazing good reason for this that I cannot understand.

It seems `os.pathsep` is designed exactly for this purpose so this seem like a bug to me.

For reference `RENPY_DEPS_INSTALL` seems to have been introduced in 2006 f9bb838e48d6c6c945ff381b69d75abd141b2434 but `::` path separation syntax was first introduced in 2009 a0fda2f058f5fc1d6696b0774be48946b5464779

**Comment by renpytom** [comment]
Not a good reason, other than perhaps os.pathsep not existing (or more likely, me not knowing about it) when that was written. I made the change, as I wanted to make sure we still support :: for compatibility with scripts that build Ren'Py.

**Comment by Uzume** [comment]
I had a feeling there were probably some external build script dependencies and exactly why I brought it here instead of directly making a pull request.

Thanks for the quick turn around.
