### ISSUE TITLE
sl define statement

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1501]
I suggest adding a define statement in sl to define constants (for example, the number of objects in the container), because default statement mark his varable how non_const.

**Comment by renpytom** [comment]
This isn't necessary, as inside a screen Ren'Py performs some fairly sophisticated static analysis to determine what is const and what is not. As a result, there's no need to add a  statement that can be written incorrectly. (Such static analysis would be too complicated to do over the entire program, hence the define statement.)
