### ISSUE TITLE
Adding player name in Character name error

### ISSUE THREAD

**Issue by LeLi977** [renpy/renpy#1507]
I tried to enter the code for players to choose their own name, when I add player's dialog, there was an error

first, I tried :
`define p = Character("[player_name]")`
and
`    $ player_name = renpy.input("What is your name?")`
`    $ player_name = player_name.strip()`
then an error occurs

then I tried the code on the internet :
`define p = Character('[name]')`
and
`    $ player = renpy.input("What is your name?")`
   ` $ player = player.strip()`
and still error

( the player dialog is very simple ):
`    p " Thanks "`

**Comment by renpytom** [comment]
The first one should work. Please post the error message.

**Comment by LeLi977** [comment]
![capture-20180724-225358](https://user-images.githubusercontent.com/40972918/43150777-f536b86c-8f94-11e8-9818-4a540d028229.png)
Here you are

**Comment by fblampe** [comment]
This works for me with Ren'Py 7.0.0196:

```python
define pc = Character("[playername]", color="#3399CC")

label start:
    python:
        playername = renpy.input("What's your name?")
        playername = playername.strip()

        if not playername:
            playername = "Mario"
```

**Comment by Andykl** [comment]
It is not repeated in the latest release.
Could not repeat on version 7.0.0.196 with this code
Perhaps you have changed the substitution config?
