### ISSUE TITLE
When Ren'Py update initializes JSON value error

### ISSUE THREAD

**Issue by dariusstutts** [renpy/renpy#1508]
When attempting to edit  a script Renpy updates, then the update fails due to a value error: json package could not be decoded .

Error occurs when  -- Edit File>script.rpy>Select Editor>atom
![renpy update error](https://user-images.githubusercontent.com/37722467/42471790-07d8c9ba-838d-11e8-9cfb-b6e2ddd30eef.PNG)

**Comment by renpytom** [comment]
Do you know what version you're on? (It's under about.)

**Comment by marppel** [comment]
Im also having the same problem when trying to download an editor for script.rpy. I tested it out on version 7.1.0 and 7.1.1 Both gave the same error.
