### ISSUE TITLE
audio partial playback keeps looping from position

### ISSUE THREAD

**Issue by DevonAA** [renpy/renpy#1518]
Playing music with the partial playback functionality results in playing it **always** from that position.

The documentation here https://www.renpy.org/doc/html/audio.html#partial-playback says:

> **from**: Specifies the position in the file at which the **_first_** play-through begins playing.

So it should play the whole file when it starts looping after the initial playback.

This can be verified by using the console command:
renpy.play("<from 110>yourexample2minutemusic.opus",channel='music')

Ren'Py Version used: 7.0.0.196

I would like to use this function the way it is documented.
(For a transition between indoor club scene with bass music and an outdoor 'in front of the club'-scene where the same music plays but modified to sound dull. If this works I can read the position of the currently playing music and set it for the new one if the player moves to the inside or outside of the club)

**Comment by vollschauer** [comment]
I don't want do get this changed, it does exactly what it should do, starting from a specified position regardless if it's the first/second or whatever play-though. If you need to start the second one from the beginning then maybe you should queue the track?

**Comment by DevonAA** [comment]
> I don't want do get this changed, it does exactly what it should do, starting from a specified position regardless if it's the first/second or whatever play-though.
In that case the documentation is wrong and the word 'first' should be removed. I can see why this would be bad to change for existing projects.

I've not used the queue function yet. Will look into that.

**Comment by renpytom** [comment]
The documentation for loop says:

```
loop
    Specifies the position in the file at which the second and later
    play-throughs begin playing. (This defaults to the start time
    given by from if specified, or to the start of the file.)
```

So I think the documentation explains this. You can do <from 42 loop 0> if you want to start 42s in, then go back to the start for a second playthrough. I'm closing this.
