### ISSUE TITLE
Viewports with scrollbars have parameters passed to the side layout

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#1519]
This does not occur if there are no scrollbars for the viewport.

Example code:
```
screen viewport_test:
    frame:
        background "#00ff00"
        viewport:
            scrollbars "horizontal"
            xfill False
            yfill False
            xpos 200

            hbox:
                for x in range(0, 10):
                    text "Test {}".format(str(x))
```
Expected Result:
xfill, yfill, and xpos are passed to the viewport.

Actual Result:
xfill, yfill, and xpos are passed to the side layout.

Style Inspector reveals the viewport has:
```
displayable:
    (no properties affect the displayable)

style viewport:
    xfill True
    yfill True
```
The side inherits the xfill, yfill, and xpos from the displayable.

**Comment by renpytom** [comment]
This is intended behavior, and is documented. xpos and ypos are more useful on the side, and you can use viewport_yfill if you want to. I'll change the docs to match the behavior.

**Comment by jsfehler** [comment]
Thanks, viewport_yfill works. Documentation updates to specify which parameters the "viewport_" prefix can be used for would be helpful.
