### ISSUE TITLE
Add wrap_spacing style property to Box

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1521]
If I have list with unknown length and must place in screen in grid style i have 2 variant
1.
```
vbox:
    spacing 25
    for i in range(0, len(items), BOX_WIDTH):
        hbox:
            spacing 10
            for name in items[i: i + BOX_WIDTH]:
                child
```
2.
```
python:
    height, overlap = divmod(items, BOX_WIDTH)
    if overlap:
        height += 1
grid BOX_WIDTH, height:
    yspacing 25
    xspacing 10
    for name in items + [Null()] * (BOX_WIDTH - overlap):
        child
````
In now with box_wrap the box doing wrap with 0px spacing
My offer is to add wrap_spacing style property to Box
for writing more simple code
```
vbox:
    box_wrap True
    spacing 25
    wrap_spacing 10
    for name in items:
        child
```
If the offer is accepted then I can do it myself.

**Comment by renpytom** [comment]
I like the idea, but am I understanding it right that you want to space out the first thing on the second line differently? I'm wondering if first_indent and rest_indent could be reused for this.

**Comment by renpytom** [comment]
Okay, I think my confusion is I wasn't sure about what it was you wanted. wrap_spacing handles the other dimension of a vbox/hbox - the space between lines of an hbox, or columns of a vbox, once a wrap has occured. 

That makese sense, though I thin box_wrap_spacing might be a better name for it.
