### ISSUE TITLE
LayeredImage side image forgetting attributes

### ISSUE THREAD

**Issue by arowana-vx** [renpy/renpy#1523]
Another LayeredImage issue, this time specifically for side images. I've noticed my side images "forgetting" previous attributes when given new attributes, even though the attributes are from different groups and shouldn't conflict. Normal, non-side images don't have this issue, so this behavior at the very least seems inconsistent.

To demonstrate, here are the definitions for two images. The images are identical, except the first image is a normal image and the second image is a side image.
```
layeredimage palette:
    group blue:
        attribute sky default:
            Solid("#BFEFFF", xysize=(100,100))
        attribute cyan:
            Solid("#00ffff", xysize=(100,100))
    group red:
        pos (100, 0)
        attribute rose default:
            Solid("#ffe4e1", xysize=(100,100))
        attribute magenta:
            Solid("#FF00FF", xysize=(100,100))

layeredimage side side_palette:
    group blue:
        attribute sky default:
            Solid("#BFEFFF", xysize=(100,100))
        attribute cyan:
            Solid("#00ffff", xysize=(100,100))
    group red:
        pos (100, 0)
        attribute rose default:
            Solid("#ffe4e1", xysize=(100,100))
        attribute magenta:
            Solid("#FF00FF", xysize=(100,100))
```

Run the following test script. In every case, I would expect the side image to match the normal image, but the behavior deviates at the very end.
```
define e = Character("Eileen", image="side_palette")

label start:
    show palette:
        align (0.5, 0.5)
    e "Default settings for both the normal and side image. They look identical."
    show palette magenta
    e magenta "Turn on 'magenta' for both images. They still look identical."
    show palette cyan
    e cyan "Turn on 'cyan' for both images. Note the side image loses the 'magenta' attribute, but the normal image does not. I would expect the side image to match the normal image instead."
    return
```

Potentially related to #1517, though that seems to be the opposite problem (forgetting older attributes _unless_ a new attribute is given, whereas here we're forgetting older attributes _when_ a new attribute is given).

Again, I'm using 7.0.1.297.

**Comment by renpytom** [comment]
I believe this is fixed as of a few days ago.
