### ISSUE TITLE
renpy.show_screen() not working from custom displayble?

### ISSUE THREAD

**Issue by newbiemate** [renpy/renpy#1528]
Here I have a custom displayable:

```
init 1 python:
    class CustomDisplayable(renpy.Displayable):
        def __init__(self, **kwargs):
            super(CustomDisplayable, self).__init__(**kwargs)
    
        def render(self, width, height, st, at):
            render = renpy.Render(width, height)
            renpy.show_screen("test_screen")
            return render

            
screen test_screen:
    $ print "I am called"
    text "World" xpos 100 ypos 0
            
screen begin:
    add CustomDisplayable()
    
    text "Hello" xpos 0 ypos 0
            
label start:
    call screen begin()
    return
```

But `"I am called"` is never shown, and I don't see the renpy text "World" either. Is this expected behavior? I expected it to show the screen after `show_screen()` was called.

**Comment by Andykl** [comment]
It looks like a poor understanding of CDD.
Render should not cause side effects.

**Comment by newbiemate** [comment]
Does this cause a side-effect? I don't think it's modifying any data, it's just calling to show a certain screen from within the cdd.

What is the proper way of showing a screen from within a cdd, if the above is not appropriate?

**Comment by renpytom** [comment]
While the screen would show if you called renpy.restart_interaction(), that's probably a bad way to do it, as you'd be showing the screen 60 times a second. 

I'd suggest adding to the begin screen the line:

```
    on "show" action Show("test_screen")
```

Or just integrate the two into a single screen.

**Comment by newbiemate** [comment]
@renpytom Thanks, that worked. But what if I want to show two different screens based on some condition? ie, 

        def render(self, width, height, st, at):
            render = renpy.Render(width, height)
            renpy.show_screen("test_screen")
            if False:
                renpy.show_screen("other_screen")            
            return render


Doing 

screen begin:
    on "show" action Show("test_screen")
    on "show" action Show("other_screen")

Would show both screens even though the `other_screen` has a false condition.


I guess, is it not recommended to show screens from a CDD?

**Comment by Andykl** [comment]
CDD are used when you want to describe displayable with your own behavior, but this is a very rare thing.
Most of what you need either already exists in RenPy, or is described by functions and classes that are not inherited from the renpy.Displayable
You may write
`on "show" action [Show("test_screen"), If(condition, Show("other_screen")]`
