### ISSUE TITLE
label label_name hide: not hiding from Generate Translations

### ISSUE THREAD

**Issue by RenpyRemix** [renpy/renpy#1531]
Firstly, tbh I do not know the expected behaviour, so this might be moot.

```
label start:
    "Start"
    "End"
    return

label no_translate hide:
    "This should not generate"
    return

label no_translate2 hide:
    "This should not generate either "
    return
```
Results in:
```
# game/script.rpy:9
translate german start_0f94cc11:

    # "Start"
    ""

# game/script.rpy:10
translate german start_4d846f38:

    # "End"
    ""

# game/script.rpy:14
translate german start_14497c04:

    # "This should not generate"
    ""

# game/script.rpy:18
translate german start_4af396a8:

    # "This should not generate either "
    ""
```
Note the "hide" labels phrases appear yet they *pretend* to be part of label start.

Is this expected behaviour? If so, just resolve and archive, though I'd expect all dialogue in a hide label to be skipped in translation.

**Comment by renpytom** [comment]
This is correct and intended behavior. The point of the hide clause is to let you introduce a new label after translation without changing the translation identifiers, not to provide portions of the game that are not translated at all.
