### ISSUE TITLE
Add support for Patreon API

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1532]
I will add Patreon API to my game in the near future (maybe next month).
Will the support of the Patreon be implemented in the Ren'Py?
If so, I can do it directly in Ren'Py as a plug-in.

**Comment by renpytom** [comment]
I don't plan to support the Patron API  in Ren'Py. I think it would need a server component.

**Comment by Dogeek** [comment]
You can use requests to make requests to patreon. You'll need an oauth token and app key to authenticate, but that should most likely work.

**Comment by renpytom** [comment]
Note that you need to be really careful about doing that from inside a game itself. My suspicion from a quick look at the patreon API  is that someone  with your key could  do all sorts of badness, like getting patron personal details.

**Comment by Dogeek** [comment]
An alternative is to make the requests you need using node.js on your webserver, and expose the relevant info in a json you can then request from your game, and parse normally.

Keep in mind though that requests is unsupported on mobile platforms in renpy games.
