### ISSUE TITLE
Strange behaviour with justify and extend character

### ISSUE THREAD

**Issue by Dumcem** [renpy/renpy#1533]
Hi,
there’s a strange behaviour when I justify the dialogue text, and then use the extend character.
Take the following code (with “justify True” added in “style say_dialogue”):

```
label start:

    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

    extend " Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

    return
```

The first part of the text will appear – apparently – normal. But when the visual novel arrives to the extend character, the text already showing will move slightly, like if the spaces between the words were adapting themselves to the new lines. It seems that the justification doesn’t happen in the whole space the text can occupy, but only into an invisible box wrapping the text which is actually showing. 
This can be a bit unpleasant to see, expecially in some cases, when the change of spaces dimensions is so evident that text seems to move on the right.

**Comment by renpytom** [comment]
This is a support issue that fell through the cracks, and can be fixed with ``adjust_spacing False``.
