### ISSUE TITLE
Using (UP|DOWN) keys to focus on buttons behaves weirdly when buttons overlap even slightly

### ISSUE THREAD

**Issue by DipeshAggarwal** [renpy/renpy#1537]
When using keyboard to focus on buttons, if the buttons are overlapping even slightly, Ren'Py will focus on the second next button instead of focusing on the next button.

```
    vbox:
        xalign 0.5
        yalign 0.5
        spacing -5

        for i in range(0, 6):
            button:
                xysize(250, 45)

                idle_background Solid("#0000ff")
                hover_background Solid("#00ffff")

                text "[i]" xalign 0.1*i yalign 0.1*i

                action NullAction()
```

**Comment by renpytom** [comment]
Overlapping buttons will behave weirdly in other ways as well, don't use them.

**Comment by DragoonHP** [comment]
Ah okay. I think I can get away with making sure the buttons don't overlap.

But just for clearity, is there no way to make this work correctly? I noticed thast focus code looks for the next possible selectable element below the area of the current element.
