### ISSUE TITLE
VPGrid wrong documentation

### ISSUE THREAD

**Issue by DarkTl** [renpy/renpy#1539]
> vpgrid doesn't take transpose, as it doesn't make sense. When you give it cols but not rows, it fills left to right first. When you give it rows but not cols, it fills top to bottom first.

from the lemma.

Yet docs still mention transpose (https://www.renpy.org/doc/html/screens.html#vpgrid)

**Comment by renpytom** [comment]
When you give it both, it takes transpose. That's the only time it makes sense.

**Comment by DarkTl** [comment]
```
File "game/code/screens.rpy", line 179: u'transpose' is not a keyword argument or valid child for the vpgrid statement.
    transpose True
```
Nope.
