### ISSUE TITLE
wrong translate with add string

### ISSUE THREAD

**Issue by malikiz** [renpy/renpy#1556]
I have a list of items and they are translated. But when I add a line to these names, the translation becomes standard

```
itemName = items[i].name
renpy.say(None, itemName) ## for test, and here alright
renpy.say(None,tr_sure+itemName+"?") ## here I get the default translate
```

**Comment by Andykl** [comment]
You must write
renpy.say(None, __(tr_sure) + __(itemName) + "?")
RenPy looks for the finished string in translation. If you have a line break in translsate, this will not work.
