### ISSUE TITLE
Picking function error

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1559]
Whan we define func in screen scope:
```
screen test:
    python:
        def bar():
            pass
    textbutton "text" action Return() align (0.5, 0.5)
```
and call this screen it's work fine.
But if we show and hide screen - take an error PicklingError: Can't pickle <function bar at 0x047557F0>: it's not found as store.bar
```
label start:
    "1" # Save work
    call screen test # Save work
    "2" # Save work
    show screen test
    "3" # Save work
    hide screen test
    "4" # Exception
    return
```
Reference to func saving in rollback.log
`1 log.log[5].context.scene_lists.layers['screens'][0].displayable.scope['bar'] = <function>`

**Comment by renpytom** [comment]
This is a bug in your code. Local functions can't be pickled in python.

**Comment by Andykl** [comment]
I created this bugtracker because there is a different behavior in similar situations.

```
label start:
    "1"
    call screen test
    "2"
    return
# Works fine
label start:
    "1"
    show screen test
    "2"
    hide screen test
    return
# Get an exception
```
I want to understand if have we rights to create functions in the scope of the screen, or all functions are required to be declared in the blocks of the init python.
I think that such a possibility would have been correct. Because in rare case i need function that have sense only on one screen.

**Comment by renpytom** [comment]
Neither of these should work. The call screen probably works because the screen doesn't live long enough to be saved. I can't really enforce it, but defining functions and classes outside of an init block or python hide block is a bad idea.
