### ISSUE TITLE
Unused enable_fast_dissolve config variable?

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1561]
While reading the RenPy code I met the configuration variable enable_fast_dissolve, and fast_dissolve field in GLDraw. But they are do nothing.
Is this left for backwards compatibility or forgotten to remove?

**Comment by renpytom** [comment]
Left for backwards compatibility. Removing a config variable would be bad, as it would prevent.

```
define config.enable_fast_dissolve = True
```

From working. (Which would, in turn, stop an old game from working.) We undocument the variable and move on.
