### ISSUE TITLE
Android SDK problem

### ISSUE THREAD

**Issue by nkrapivin** [renpy/renpy#1562]
I created sdk.txt file w/ one line that is full path to my android sdk. Copied this file to rapt folder and to root folder of renpy. That doesn't worked :(

**Comment by renpytom** [comment]
What version of the SDK do you have? Ren'Py works with the newest versions only.

**Comment by nkrapivin** [comment]
Eh, 24.1.1, latest with old SDK Manager, because I am also creating a platformer on GameMaker.

**Comment by nkrapivin** [comment]
But at first time I tried to let it install latest sdk, it throws out an exception when RenPy can't install platforms;android-28, That's because of a bad command maybe?
