### ISSUE TITLE
Add the ability to specify the transformation applied to Drag

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1572]
In the screen language
```
draggroup:
    drag:
        ...
        at trans
```
We receive an error "Exception: Only drags can be added to a drag group." because Drag object has wrapped in Transform.

**Comment by renpytom** [comment]
I don't think this makes much sense.

The only properties that it would make sense to specify for a drag are the position properties. But those are controlled by the drag and drop system, and so we wouldn't want a transformation that also specifies them. The rest of them would be identical when specified inside the Drag as to being specified outside it. 

At the same time, it means that (if we allowed multiple transforms) we'd have to search arbitrarily inside the drag to get the position. 

So I don't think this is something that makes sense to do.
