### ISSUE TITLE
Curious 'window auto' behavior

### ISSUE THREAD

**Issue by zicodxx** [renpy/renpy#1576]
I've recently noticed a weird behavior in the showing of the say box when using 'window auto'.

Assuming, you have the following choice:
```
    menu:
        "Stay and talk.":
            [dialogue happens]
        "Go outside.":
            jump outside_01

label outside_01:
        scene bg outside with dissolve
```
If you then select "Go outside", the say box immediately shows up, just to fade out when the scene transitions to the outside scene. 
This can be fixed by putting the scene statement into the choice, in which case the say box stays hidden until the dissolve to outside is done, but if outside_01 is called from multiple choices, that's pretty redundant. Strangely enough, adding 'window auto' before the jump statement, somehow fixes the issue as well - no say box visible before the transition:
```
        "Go outside.":
            window auto
            jump outside_01
```
Since I'm using window auto to begin with, that shouldn't make a difference, should it?

Now the question is: Is the appearance of the say box between the decision and new label a bug or intended? And if it is intended, what would be the suggested way to solve it? I can pack 'window auto' in each decision, but it doesn't seem right to me.

**Comment by renpytom** [comment]
This should be fixed in the nightlies at this point.
