### ISSUE TITLE
OpenCV in renpy

### ISSUE THREAD

**Issue by Aditya-Khadilkar** [renpy/renpy#1585]
Is it possible to use the Open Computer Vision module of python in renpy? I want to access the webcam and do some image processing... How do I do that with renpy?

**Comment by Andykl** [comment]
You may import any pure-puthon modules - [doc](https://renpy.org/doc/html/python.html#first-and-third-party-python-modules-and-packages)
But this module must return types that Ren'Py can display or write code to convert.

**Comment by renpytom** [comment]
It's not supported, and I have no plans to support it. I think it requires the numpy stack, and that's something large that isn't related enough to VN development to include in Ren'Py. 

It might make sense to use a second process to capture images, and communicate using the subprocess file or by writing files to disk.
