### ISSUE TITLE
Pass Disabled Menu Choices to the Choice Screen

### ISSUE THREAD

**Issue by qirien** [renpy/renpy#1587]
One feature that several people have requested (see this workaround: https://lemmasoft.renai.us/forums/viewtopic.php?f=51&t=25460) is to be able to show but disable menu options that would normally be hidden because they did not pass a conditional.  This way players can see what they might need to pass certain checks, or know that there are more options during a certain scene if they make different choices. 

While it is possible to work around this with multiple if statements or by using custom menu code, it seems like a better fix would be for Ren'Py to simply pass the conditional on to the choice screen and let the decision about how/whether to show the item happen there.

For example, right now in order to show disabled menu options you would need to write:
```
menu door_menu:
    "How do you want to open the door?"
    "Use the key - key required":
        jump door_menu
    "Use the key" if has_key:
        call door_key
    "Bash down the door - strength 5 required" if strength < 5:
        jump door_menu
    "Bash down the door" if strength >= 5:
        call door_bash
```

When it would be nice if you could accomplish the same thing by writing just:
```
menu door_menu:
    "How do you want to open the door?"
    "Use the key" if has_key:
        call door_key
    "Bash down the door" if strength >= 5:
        call door_bash
```
and editing screens.rpy to check conditionals and show/disable buttons based on the results.

**Comment by renpytom** [comment]
This will be in 7.1.2.
