### ISSUE TITLE
enhancement - feedback mode

### ISSUE THREAD

**Issue by johndpope** [renpy/renpy#1589]
expose some buttons to allow end user to engage with author when in feedback mode

eg. 
still following
losing you 
you lost me 

<img width="1078" alt="screen shot 2018-10-08 at 3 24 09 pm" src="https://user-images.githubusercontent.com/289994/46629260-37be5000-cb0e-11e8-80b7-b7155caddbd8.png">
https://www.lem.ma/content/AokWNSqz-WZ4rtpei4Blmw?book_id=C_pMkUEZmKH2UE_1SB45cQ

<img width="2557" alt="screen shot 2018-10-08 at 3 19 11 pm" src="https://user-images.githubusercontent.com/289994/46629050-8b7c6980-cb0d-11e8-841c-b4e843dc8b8d.png">

suggestions
<img width="1382" alt="screen shot 2018-10-08 at 3 22 24 pm" src="https://user-images.githubusercontent.com/289994/46629188-fa59c280-cb0d-11e8-9399-8e70c7768816.png">

point to google analytics tracker.

This would increase engagement between author / illustrator / content team with end user.
problematic areas of story could be targeted and fixed.

**Comment by renpytom** [comment]
While I like this, I'm not sure it really belongs in Ren'Py proper. Wouldn't this just be a series of buttons that could either use requests to make a web request, or use OpenURL to open a web browser?

**Comment by johndpope** [comment]
needs some integration - to capture timing / points of story. 
it's for proof reading the game so to speak. 
why does my game suck ? 
as game creator - I allow end users to toggle this feedback mode on.

settings -> enable feedback mode

from here - imagine you could have something as basic as thumbs up / thumbs down / or more elaborate.
the clicking / toggling would merely throw data out to google analytics.

**Comment by renpytom** [comment]
Hm... 

I like this. I'm going to add this to Ren'Py, or at least as a framework that can easily be added to Ren'Py.

**Comment by johndpope** [comment]
so I had a sleep on this and don't want to shock you with scope creep - but your positive feedback has encouraged me to dig more ideas. 
while the above feedback would benefit the author which is great / it's entirely closed off from others. 

What about turning this concept on it's head and opening the feedback up to wider audience? 
I frequently listen on soundcloud to an artist who mixes up an hour of music and when I love a transition / mix I comment. It maybe just an emoji here and there - but it encourages him to create more content. and each time stamp - there can be a comment. If these comments could be surfaced - I think it would be awesome experience. 

The pro with google analytics - there's an existing api. 
The con is the data is not so public.
I'm wondering if itch team could build out such functionality / that way can just plugin this functionality. 
they could handle the necessary authentication - 

I'm sure a lot of games could benefit from this stream of tweets / "scratches?". 
@fasterthanlime / @GranPC/  @leafo / @quyse	

I'm imaging something akin to facebook / soundcloud ux where you can see comments from readers in a timeline. though the timeline is harder - if the comments just appears on screen in context - this would be magic enough.

<img width="856" alt="screen shot 2018-10-09 at 11 04 11 am" src="https://user-images.githubusercontent.com/289994/46678658-1d8a7d80-cbb3-11e8-983d-6ab559d2838b.png">

<img width="871" alt="screen shot 2018-10-09 at 11 04 18 am" src="https://user-images.githubusercontent.com/289994/46678650-1a8f8d00-cbb3-11e8-92eb-589588b978d8.png">

**Comment by johndpope** [comment]
did some digging
facebook calls this live video comments
https://developers.facebook.com/docs/videos/live-video/production-broadcasts

maybe able to decouple this entirely using separate window
https://github.com/johndpope/live-comments-teleprompter

**Comment by renpytom** [comment]
I'll note that I plan to take on the google analytics stuff soon, probably as a plug-in I do as a patreon article rather than something intended for Ren'Py proper. 

The rest of this is unlikely to occur, as they seem to require incompatible technologies.

**Comment by johndpope** [comment]
yeah I get that.  node / html going to be troublesome. 
with the basic feedback - it occurred to me that the author may want to be more granular about feedback - was it the story / visuals / sounds / dialog that was bad....
I'm imaging a list of items with thumbs up / thumbs down beside.

**Comment by johndpope** [comment]
Noteworthy feedback https://docs.google.com/document/d/1RRG5UdJX04cNBcfImdYumUWWV4KFwQfZsWugoabOInI

**Comment by johndpope** [comment]
Was this (analytics) well received?
