### ISSUE TITLE
Android packing failed.

### ISSUE THREAD

**Issue by xiaosaohuo** [renpy/renpy#1590]
Ren'Py 7.1.1.928

Updating project.

Creating assets directory.

Packaging internal data.

I'm using Gradle to build the package.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download auto-value.jar (com.google.auto.value:auto-value:1.5.2)
      > Could not get resource 'https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download jimfs.jar (com.google.jimfs:jimfs:1.1)
      > Could not get resource 'https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download guava.jar (com.google.guava:guava:22.0)
      > Could not get resource 'https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download protobuf-java.jar (com.google.protobuf:protobuf-java:3.4.0)
      > Could not get resource 'https://jcenter.bintray.com/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download bcpkix-jdk15on.jar (org.bouncycastle:bcpkix-jdk15on:1.56)
      > Could not get resource 'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download bcprov-jdk15on.jar (org.bouncycastle:bcprov-jdk15on:1.56)
      > Could not get resource 'https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download fastutil.jar (it.unimi.dsi:fastutil:7.2.0)
      > Could not get resource 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.2.0)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download antlr4.jar (org.antlr:antlr4:4.5.3)
      > Could not get resource 'https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download juniversalchardet.jar (com.googlecode.juniversalchardet:juniversalchardet:1.0.3)
      > Could not get resource 'https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download gson.jar (com.google.code.gson:gson:2.7)
      > Could not get resource 'https://jcenter.bintray.com/com/google/code/gson/gson/2.7/gson-2.7.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/google/code/gson/gson/2.7/gson-2.7.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.2.0)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.0/kotlin-stdlib-1.2.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.0/kotlin-stdlib-1.2.0.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download proguard-base.jar (net.sf.proguard:proguard-base:5.3.3)
      > Could not get resource 'https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.3.3/proguard-base-5.3.3.jar'.
         > Could not GET 'https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.3.3/proguard-base-5.3.3.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download commons-compress.jar (org.apache.commons:commons-compress:1.12)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/commons/commons-compress/1.12/commons-compress-1.12.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/apache/commons/commons-compress/1.12/commons-compress-1.12.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download httpclient.jar (org.apache.httpcomponents:httpclient:4.2.6)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download httpcore.jar (org.apache.httpcomponents:httpcore:4.2.5)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download commons-codec.jar (commons-codec:commons-codec:1.6)
      > Could not get resource 'https://jcenter.bintray.com/commons-codec/commons-codec/1.6/commons-codec-1.6.jar'.
         > Could not GET 'https://jcenter.bintray.com/commons-codec/commons-codec/1.6/commons-codec-1.6.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out
   > Could not download FastInfoset.jar (com.sun.xml.fastinfoset:FastInfoset:1.2.13)
      > Could not get resource 'https://jcenter.bintray.com/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48] failed: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 8s

The build seems to have failed.

**Comment by renpytom** [comment]
It looks like your computer is blocking access to jcenter.bintray.com. That's likely to be a local problem, more than a Ren'Py one.

**Comment by xiaosaohuo** [comment]
> 您的计算机似乎阻止访问jcenter.bintray.com。这可能是一个本地问题，而不是Ren'Py问题。

No, I have been updated successfully, but I failed many times only once, because I reinstalled the system, RENPY to download again, so it has been failed!
