### ISSUE TITLE
"tooltip" property not available on all displayables

### ISSUE THREAD

**Issue by xavi-mat** [renpy/renpy#1591]
https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=52157&p=497328#p497327

Doc says that tooltip property is available on all displayables:
Here: https://www.renpy.org/doc/html/screen_actions.html#tooltips
And in the "common properties" list, here: https://www.renpy.org/doc/html/screens.html#user-interface-statements

But only buttons and actionable bars react to tooltip property.
Not even mouseareas or informative-bars, that have the hovered property.
(Bars trigger the tooltip if user can drag them (like sound bar), they don't if are only informative.)
```
screen tooltip_example():
    default xx = 0  # Check if hovered works for mousearea and bar.
    vbox:
        textbutton "North":
            action Return("n")
            tooltip "To meet a polar bear."
        label "try label":
            tooltip "This is a label"
        mousearea:
            xysize (200,50)
            hovered SetScreenVariable("xx", 1)
            unhovered SetScreenVariable("xx", 0)
            tooltip "This is a mousearea"
        bar range 100 value Preference("sound volume"):
            hovered SetScreenVariable("xx", 2)
            unhovered SetScreenVariable("xx", 3)
            tooltip "This is a bar that changes a preference."
        bar range 100 value 37:
            hovered SetScreenVariable("xx", 4)
            unhovered SetScreenVariable("xx", 5)
            tooltip "This is an only-informative bar."
        text "[xx]"


        $ tooltip = GetTooltip()

        if tooltip:
            text "[tooltip]"
```

I think tooltip could be interesting to give info to the player even in non-button displayables (like an explanation of what a points-bar means). If not "all displayables" at least for informative bars and mouseareas.

**Comment by Andykl** [comment]
I think it's impossible, because tooltip changed only in display.focus.set_focused function. This function called only for Displayable with focusable != None.

And I think adding this will be get strange behavior:
```
fixed:
    tooltip "fixed"
    label "label" tooltip "label"
    button:
        fixed:
            add img tooltip "img"
            text "text" tooltip "text"
        tooltip "button"
```
Which tooltip must be selceted on idle and hover this button?

**Comment by renpytom** [comment]
I think Ren'Py is doing the right thing here - when a displayable gains foucus, it sets the tooltip. 

For the informitive bar case, I'd suggest putting it in an empty button. 

```
button:
    style 'empty'
    action NullAction()
    tooltip "Whatever". 

    bar range 100 value 37
```
