### ISSUE TITLE
KeyError when trying to change screen variables contained inside another screen

### ISSUE THREAD

**Issue by DragoonHP** [renpy/renpy#1595]
This error happens when a screen is shown inside another screen using `use` and the variable is defined under the second screen

```
screen load():
    tag menu
    use file_slots(_("Load"))

screen file_slots(title):
    default change_me = False
    textbutton _("Click Me") action ToggleScreenVariable("change_me") xalign 0.5 yalign 0.5
```

`renpy.current_screen().scope` only returns scope for just the load screen and not the screen contained within it `file_slots`

Based on this > https://lemmasoft.renai.us/forums/viewtopic.php?p=497650#p497650

**Comment by renpytom** [comment]
I have added SetLocalVariable and ToggleLocalVariable to solve this (at some performance cost).
