### ISSUE TITLE
Report text tag errors more properly.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1598]
At  least to the level of the  tag in question,.

**Comment by fblampe** [comment]
Hi, I'd be interested to work on this, but I'm not quite sure what you're referring to.

The messages seem already quite detailed to me (see below). The file and line number as well as the problematic tag are all given, so I'm not sure what could be added..?

```
While running game code:
  File "game/script.rpy", line 21, in script
    "Professor {cps/=2}Eileen's{/cps} lectures are usually interesting, but today I just couldn't concentrate on it."
Exception: Unknown text tag u'cps/=2'
```
