### ISSUE TITLE
Can't Build a distribution

### ISSUE THREAD

**Issue by FaradayAwerty** [renpy/renpy#1607]
![deepinscreenshot_python2 7_20181028221357](https://user-images.githubusercontent.com/40428645/47620742-c7985e00-dafe-11e8-95f1-9e56f31a2508.png)
This is the error message I get.
For some reason ren'py can't find some library.

**Comment by renpytom** [comment]
This looks like a distribution-specific issue. Please contact your distributor for support, though some of them remove files required for Ren'Py to produce distributions. Alternatively, use a version of Ren'Py downloaded from renpy.org.
