### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by ShehriyarQureshi** [renpy/renpy#1612]
I noticed that e.g. the bootstrap function in `renpy/bootstrap.py` is quite long. Should we work on refactoring code where possible? It will make it easier for contributors, especially new, to better understand the code base.

I'd like to know your thoughts.

**Comment by renpytom** [comment]
I lean against it. I tend to not like refactoring for refactoring's sake  - I think the risk of breaking something makes it not worth it.

**Comment by ShehriyarQureshi** [comment]
I see. It is quite a big project and there isn't a lot of test coverage to see if something did break. Talking about test coverage, @renpytom shouldn't we try to have some test coverage? I mean the project will get updated and some stuff does mess up so wouldn't it be better to try to have some test coverage?

**Comment by renpytom** [comment]
It certainly would be nice to have more test coverage. At the same time, there are limited resources, and it's hard to test an engine like Ren'Py that combines a custom gui toolkit with a custom language interpreter.

**Comment by ShehriyarQureshi** [comment]
It certainly is hard. Should I try and see if I can create some small tests for the python portion of the engine?

**Comment by renpytom** [comment]
Sure. I'd like to know what you get - I'm not good at testing myself. 

I do like pytest as a framework: https://docs.pytest.org/en/latest/

**Comment by ShehriyarQureshi** [comment]
I also like pytest. Have used it a little. I'm not too good with testing myself but I'll see what I can do. Should be a good learning experience :smile:
