### ISSUE TITLE
Seen texts are broken if game is recompiled from a different directory

### ISSUE THREAD

**Issue by Beuc** [renpy/renpy#1628]
Hi,

AFAICS the "seen texts" are stored in savegames using unique identifiers, that contains the fullpath for each script that contain said texts.
However this full path appears to come from the release's .rpyc files, which reference the full original path from the developer computer.
(Note: this is a minor information leak vulnerability, e.g. it typically contains the developer's local login name.)

If the developer renames the directory, removes the .rpyc files, and re-releases the game, people updating to that new (identical) version will have their "seen texts" reset, and will have to manually skip them one by one.

It would make sense to store the path from the "game/" folder downwards only, to avoid both breaking seen texts and leaking the developer full path.

**Comment by renpytom** [comment]
Well, deleting the .rpyc will break the saves entirely. So that's not really a problem.

That being said, it shouldn't store the full path, so I'll look into eliding that going forwards.

**Comment by renpytom** [comment]
b159a34e447abde87bc7e5cd60dd325d2a59cc7a elides the filenames used as part of statement names.
