### ISSUE TITLE
CDS Improvements.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1629]
- [x] It should be possible for a CDS to return a list of strings to be translated.
- [x] There should be some way to tell the lexer to parse a subblock as Ren'PY code. 
- [x] There should be a way to jump to a subblock. (Basically, it should be possible to implement if as a CDS.)

**Comment by renpytom** [comment]
See 4d7a93f0

**Comment by Andykl** [comment]
Need to add for a statemetns like container (SL) the ability to add an ParseError to the list of found ones and move on to the next fragment instead of blocking the parsing of the entire statement.

**Comment by renpytom** [comment]
I believe this is done.
