### ISSUE TITLE
LayeredImage errors in 7.1.2 prerelease

### ISSUE THREAD

**Issue by arowana-vx** [renpy/renpy#1635]
While trying the 7.1.2 prerelease, I noticed a lot of my LayeredImages (which had worked in 7.1.1) suddenly disappearing or throwing errors about not accepting attributes. I believe the problem occurs for LayeredImages with multiple groups.

Here is a test script to demonstrate the issue. Note that both layeredimages contain the 'cyan' attribute, but trying to show the second one gives an error.
```
layeredimage one_group: ##### layeredimage with one group
    align (0.5, 0.5)
    group blue:
        attribute sky default:
            Solid("#BFEFFF", xysize=(100,100))
        attribute cyan:
            Solid("#00ffff", xysize=(100,100))

layeredimage two_group: ##### similar layeredimage with two groups
    align (0.5, 0.5)
    group blue:
        attribute sky default:
            Solid("#BFEFFF", xysize=(100,100))
        attribute cyan:
            Solid("#00ffff", xysize=(100,100))
    group red:
        pos (100, 0)
        attribute rose default:
            Solid("#ffe4e1", xysize=(100,100))
        attribute magenta:
            Solid("#FF00FF", xysize=(100,100))

label start:
    show one_group cyan
    "This image shows up correctly."
    hide one_group
    show two_group cyan
    "This image doesn't show up and gives the error message: Image 'two_group' does not accept attributes 'cyan'."
    return
```
I checked this script in two versions of Ren'Py - the error occurred in 7.1.2.1029 (prerelease), but did not occur in 7.1.1.929 (last official release). Let me know if you need any more info, and thanks for your help!

**Comment by renpytom** [comment]
Fixed it. Thanks for a great replication, as always.
