### ISSUE TITLE
FLIF Image Format Support

### ISSUE THREAD

**Issue by kobaltcore** [renpy/renpy#1643]
This proposition was made once before on the Lemmasoft forums, [right here](https://lemmasoft.renai.us/forums/viewtopic.php?f=32&t=46457#p469237), however it went stale and did not receive a definitive answer. Since I couldn't find an issue for this topic/feature request on here I created this issue to hopefully keep track on what the status of FLIF support is.

From the official website:

> [FLIF](http://flif.info) is a novel lossless image format which outperforms PNG, lossless WebP, lossless BPG, lossless JPEG2000, and lossless JPEG XR in terms of compression ratio.

It would be nice to have support for a more efficient format than lossless WebP (which FLIF allegedly outperforms by about 14%).

As far as I can tell, `sdl_image` does not yet support FLIF images, so I'm not sure how much effort it would take to implement support for this filetype.

**Comment by renpytom** [comment]
My consideration for FLIF is basically - do I expect this to be a popular image format with tools to support it. As far as I can tell, it's not really being considered for inclusion in say, web browsers. Nor is it in any paint program that I can find. 

I think if there was some use, it'd make sense to support it, but for now, I don't think it does. (New image formats come around every year or so, but few achieve this level of support.)

**Comment by renpytom** [comment]
Closing this until something changes. (For example, FLIF is added to SDL_image.)
