### ISSUE TITLE
Incorrect Language Detection on Spanish Windows

### ISSUE THREAD

**Issue by DgrantX7** [renpy/renpy#1644]
My OS's language is spanish. However, when I launched the ren'py launcher for the first time, it was displayed in russian by default. Same with The Question and the tutorial. Once I go to options and change the language to english, it doesn't happen again, so I guess the problem occurs in the new auto detection feature. I tested this in two different PCs running windows 7 and 10 respectively, both with Spain's Spanish language.

**Comment by DgrantX7** [comment]
PyTom already fixed it.
Thank you, PyTom!

**Comment by renpytom** [comment]
Thanks for the report, and sorry for not following up for now. Your report directly lead to the 7.1.3 release, and did so before very many people could be affected by the problem. Thank you so much!

**Comment by DgrantX7** [comment]
It's ok, I'm glad I was able to help.
