### ISSUE TITLE
Reload (Shift + R) stops working, closes game

### ISSUE THREAD

**Issue by fullmontis** [renpy/renpy#1649]
Ren'Py version 7.1.3.1092, using ubuntu 18.04

Sometimes while working on the script the reload function will stop working. If I reload the game with Shift + R after doing some modifications to the scripts, the game closes, and I have to manually reopen it in the renpy launcher. It doesn't even seem to crash because there is no dump information. If I restart the game, it restores it from the point from which I was trying to reload, and the reload still closes the game.

It also doesn't automatically reload whenever the file is edited. 

It seems to be solved if I restart the Ren'Py launcher, when it happens.

It has happened at least three or four times in the last few days. Unfortunately I can't pinpoint it to a specific issue so I will try and see what I did specifically to make it happen when it happens again.

**Comment by Andykl** [comment]
I've met with this, too, and I've catch the traceback that's going on.
```

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00keymap.rpy", line 421, in script
    python hide:
  File "C:\renpy.git\renpy\ast.py", line 910, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy.git\renpy\python.py", line 1959, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 421, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 440, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "C:\renpy.git\renpy\loadsave.py", line 398, in save
    roots = renpy.game.log.freeze(None)
  File "C:\renpy.git\renpy\python.py", line 1856, in freeze
    self.complete(False)
  File "C:\renpy.git\renpy\python.py", line 1466, in complete
    self.current.stores[name], self.current.delta_ebc[name] = sd.get_changes(begin)
AttributeError: 'NoneType' object has no attribute 'stores'
```
It happens more often if the code is short.

**Comment by zorroartico** [comment]
I am getting the same problem with the following statement:

_**AttributeError: 'NoneType' object has no attribute 'stores'**_

The resulting screen alternates back and forth with black screen showing "saving the game" and the grey screen. NoneType usually means that the object is set to None when it is not supposed to. Ren'Py needs to access an attribute of this object, but can't. Has anyone solved this problem yet?

**Comment by renpytom** [comment]
I believe this has been fixed.
