### ISSUE TITLE
The Question uses files from launcher/game/fonts/

### ISSUE THREAD

**Issue by Beuc** [renpy/renpy#1656]
This means this game's preferences screen will crash if we test a Distribution of it.
(I saw that in renpyweb but this also applies to standard pc/mac/android distributions)

**Comment by renpytom** [comment]
Yes.

The alternative is to massively increase the size of Ren'Py by doubling the fonts. I'd prefer not to do that.

**Comment by Beuc** [comment]
OK. We're talking about a couple megs compressed, but I was thinking of copying / symlinking them, so as to have a clean example for "the question".

**Comment by Gouvernathor** [comment]
This is not doable, as symlinks don't work with all platforms.
