### ISSUE TITLE
Autoadjust/Autoresize textbox in new GUI

### ISSUE THREAD

**Issue by Ria-kon** [renpy/renpy#1657]
In old GUI there was one default feature where text autoadjusts vertically if there was not enough space for it and textbox wasn't bordered.
However, in new GUI this feature was removed and now text go beyond the screen. 

If I set textbox_height variable to None, it will repeat old behavior, but from bottom string, so if I had textbox background for 2 strings, all strings will have a start from left-bottom corner. This isn't good, I need only exceptions, not the rule and always-floating beginning of text.

Is there any possibilities to return old behavior (or bypass it not by massive code constructions), so I can solve my problem with few too big strings?

p.s. https://lemmasoft.renai.us/forums/viewtopic.php?t=45097 
p.p.s. This is for mobile build. I just wanted to add some size to text and met this issue. I really have no desire to do two different versions just because of this.

**Comment by renpytom** [comment]
This is a bad feature - it means text starts in a different place in different screen, which hurts readability. 

That being said, you should be able to edit the say screen to support it. Someting like:

```
style window:
    xalign 0.5
    xfill True
    yalign gui.textbox_yalign
    yminimum gui.textbox_height

    background Frame("gui/textbox.png", xalign=0.5, yalign=1.0)
```

Will restore the old behavior. (This replaces the style in screens.rpy.)
