### ISSUE TITLE
LayeredImage side image attributes conflict

### ISSUE THREAD

**Issue by Dumcem** [renpy/renpy#1663]
I'm not sure if this way of using layered images was intended to be permitted or not, so I'm reporting it.

Given the following images:

side_testchara_base.png
side_testchara_extra_blush-1.png
side_testchara_extra_sweatdrop-1.png

and the following code:

    layeredimage side testchara:

        always:
            "side_testchara_base"

        group extra auto prefix "ex1"
        group extra auto prefix "ex2"

    define testchara = Character("Test Chara", color="#f44", image="testchara")

    label start:

        testchara ex1_blush-1 "Works!"

        testchara ex2_sweatdrop-1 "Works!"

        testchara ex1_blush-1 ex2_sweatdrop-1 "Error!"

        return

before the 7.1 update, this allowed to use the same set of images to create more groups with the same name, but different prefixes to call them. This was usefull, for example, to combine a large number of expression variants which don't exclude each other (in this minimal example, a blush effect and a sweat drop, but there could be a lot more) without duplicating them with different names. However, since 7.1 this code gives the following error:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    testchara ex1_blush-1 ex3_sweatdrop-1 "Error!"
  File "renpy/common/00layeredimage.rpy", line 724, in _choose_attributes
    raise Exception("The attributes for {} conflict: {}".format(tag, " ".join(both)))
Exception: The attributes for side conflict: ex3_sweatdrop-1 ex1_blush-1

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    testchara ex1_blush-1 ex3_sweatdrop-1 "Error!"
  File "F:\Lavorazioni\VN\Renpy\renpy-7.1.3\renpy\ast.py", line 678, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "F:\Lavorazioni\VN\Renpy\renpy-7.1.3\renpy\exports.py", line 1229, in say
    who(what, *args, **kwargs)
  File "F:\Lavorazioni\VN\Renpy\renpy-7.1.3\renpy\character.py", line 971, in __call__
    self.resolve_say_attributes(False, wanted=speaking)
  File "F:\Lavorazioni\VN\Renpy\renpy-7.1.3\renpy\character.py", line 900, in resolve_say_attributes
    new_image = images.apply_attributes(layer, self.image_tag, tagged_attrs, wanted, remove)
  File "F:\Lavorazioni\VN\Renpy\renpy-7.1.3\renpy\display\image.py", line 903, in apply_attributes
    return self.choose_image(nametag, required, optional, name)
  File "F:\Lavorazioni\VN\Renpy\renpy-7.1.3\renpy\display\image.py", line 920, in choose_image
    newattrs = ca(tag, ca_required, ca_optional)
  File "renpy/common/00layeredimage.rpy", line 724, in _choose_attributes
    raise Exception("The attributes for {} conflict: {}".format(tag, " ".join(both)))
Exception: The attributes for side conflict: ex3_sweatdrop-1 ex1_blush-1

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Test 1.0
Sun Dec 09 15:46:17 2018
```

With some testing, I also noticed that this error can be avoided using:
define config.say_attributes_use_side_image = False

**Comment by Glairhaidh** [comment]
I'm having the same issue.

I'm not sure why this error does not occur every time for a given line of script. I had played through my game a 100 times and 99 times out of 100 it was fine. One of my players reported a bug and I was able to replicate it.

Oddly enough the error happens for some elements of the group and for some it doesn't.

define config.say_attributes_use_side_image = False fixes the problem, I'm not sure why it works though.

Example:
```
#renpy game image defs
layeredimage character1:
    group body:
        attribute costume:
            "images/character1 sprite/character1costume.png" default
    group face:
        attribute sad:
            "images/character1 sprite/character1sad.png"
        attribute angry:
            "images/character1 sprite/character1angry.png"
    group eyes:
        attribute shock:
            "images/character1 sprite/character1shock.png"  
        attribute sidelook1:
            "images/character1 sprite/character1sidelook1.png"  

#renpy game script with the error
 character1 sad shock "This used to work!" "Error!"

#renpy game script with that works, even though it follows the same logic
 character1 sad sidelook1 "This works!" "No error!"
```

**Comment by Gouvernathor** [comment]
The solution to the first problem is to use `multiple` groups, which allow several of their attributes to be shown at once.
Maybe what you're describing has been changed without notice, I don't know, but now it's not supported - on the contrary, being able to have attributes be spread over different zorders, while belonging to the same group, is a feature.

The second issue doesn't seem related to the first one.
