### ISSUE TITLE
Pass parameters through an ImageReference not working anymore

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#1667]
Back in August this was added:
https://github.com/renpy/renpy/commit/d2550f31d7b3e5920fe5bf2c75b0a4f268962e7e
to support stuff like:
`    default mainc="joshua"
    image i_pc = "[mainc]"`
so that in the game you could use:
show i_pc uniform1 sad
to display both a male/female protagonist just by changing the mainc variable. Now this doesn't work anymore.

**Comment by renpytom** [comment]
I think this can be closed now.
