### ISSUE TITLE
Crash on some Android devices.

### ISSUE THREAD

**Issue by lee-yunseok** [renpy/renpy#1668]
My updated(**Ren'Py 7.1.3.1092** applied) app crashes on **Android 8.0**. This has been reported to occur only in the **expansion APK(with obb)**, Google Play. No error reporting for a single APK(demo version and other store) yet. I have no problems in my two Android devices, so I can't figure out what caused the crash.

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

SDL_main
```

***
pid: 0, tid: 0 >>> github.io.yggdrasilstudio.kndwteen <<<

backtrace:
```
  #00  pc 00000000000016fc  /data/app/github.io.yggdrasilstudio.kndwteen-PhqUeVImbv12os7LZQoqrw==/lib/arm/libmain.so (SDL_main+79)
  #01  pc 000000000000131f  /data/app/github.io.yggdrasilstudio.kndwteen-PhqUeVImbv12os7LZQoqrw==/lib/arm/libmain.so (Java_org_libsdl_app_SDLActivity_nativeInit+230)
  #02  pc 000000000002bdb1  /data/app/github.io.yggdrasilstudio.kndwteen-PhqUeVImbv12os7LZQoqrw==/oat/arm/base.odex
```

***
The reported device:

**LG G7 ThinQ**
Qualcomm SDM845 (Snapdragon SDM845)
4x Qualcomm Kryo 280
3646MB RAM
Qualcomm Adreno 630(650Mhz) GPU
1440x3120px(560DPI)
OpenGL ES 3.2

**Comment by lee-yunseok** [comment]
Now I have figured out the cause of the problem. It is related to the Adreno GPU.

**Comment by renpytom** [comment]
Do you know what makes you think that?

**Comment by lee-yunseok** [comment]
I thought it was related with the Adreno GPU(not Ren'Py's fault). And the backtrace, only three lines were recorded there.

I built the app by reducing the size of the presplash image to 800*480(1280*720 before) and add monocolored border. It worked on the Firebase Test Lab, I re-submitted updated APK to Google Play and it was restored.
