### ISSUE TITLE
A few spelling errors in the tutorial

### ISSUE THREAD

**Issue by Crystalwarrior** [renpy/renpy#1674]
In in-depth tutorial section, for characters and displayables. First one is `thay's` which should be `that's`, second is `In face` which should be `In fact`

![default](https://user-images.githubusercontent.com/3470436/50548454-e087d180-0c5d-11e9-8d4b-4762f83198b5.png)
![default](https://user-images.githubusercontent.com/3470436/50548456-e7164900-0c5d-11e9-8e32-d664170c81c7.png)

**Comment by renpytom** [comment]
The first one was fixed in fd3f50d2231806723be3e93e4829f8a179ce7287 .
