### ISSUE TITLE
im.matrix multiplication is wrong.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1676]
For im.matrix objects, A * B does what in all mathematics is written B * A. This should be fixed with compatibility for older games.

**Comment by celinarose** [comment]
https://github.com/renpy/renpy/blob/6445f3a9c58d9768113b2b71d7c6c8364096a061/renpy/display/im.py#L1271
I want to help out with this issue: plan on switching a and b in this line. I do not get how backwards compatibility for older games will be affected/implemented; could you give me some suggestions?

**Comment by renpytom** [comment]
The main problem is that for older games, doing:

im.matrix.desaturate() * im.matrix.tint()

will now have changed results. The actual fix is pretty simple, as you rightly declared - the real problem here is the messaging and education for creators that goes along with an incompatible change, along with making a config variable control if this happens, and then setting that variable to False in 00compat.rpy. 

The actual change is pretty simple, but the point of the bug is to defer it until the soft stuff can be done.

**Comment by Gouvernathor** [comment]
This can probably be considered as solved, with the new `matrixcolor` transform property making the im.matrixvariable obsolete.
