### ISSUE TITLE
Python-TK Error when the user cancels selecting a directory

### ISSUE THREAD

**Issue by GanstaKingofSA** [renpy/renpy#1678]
Type of Issue: Ren'Py Bug
Versions Affected: From testing, 6.99.12.4 - 7.1.3 (macOS and Linux ONLY)

Description

If the user decides to go to **Preferences -> Projects directory** and decides to cancel selecting a directory if they changed their mind, Ren'Py will throw a `Ren'Py was unable to run python with tkinter to choose the directory. Please install the python-tk or tkinter package error.` error. So far from testing it goes way back to 6.99.12.4 from testing (as I am using that SDK for the mod SDK) and also on 7.1.3 after testing it.

Screenshots:
![capture](https://user-images.githubusercontent.com/40864681/50742436-c35c8100-11d0-11e9-9837-ef9826702581.PNG)

Additional Notes:
This doesn't affect Windows. Only the Linux/Unix operating systems.

**Comment by vollschauer** [comment]
The error is:
File "/xxx/RenPy/renpy-7.1.3-sdk/launcher/game/tkaskdir.py", line 50, in <module>
    sys.stdout.write(result.encode("utf8"))
AttributeError: 'tuple' object has no attribute 'encode'
