### ISSUE TITLE
Apparently "FileCurrentScreenshot" doesn't work if there's a gap between commands?

### ISSUE THREAD

**Issue by whiteangel123** [renpy/renpy#1680]
Uh, hi, I have this code that has been working as of Renpy 6.99.14. Problem is, upon upgrading to 7.1.0 (and beyond), it stops working. I've posted this issue before, was declared closed with the 7.1.3 update, but I found that the problem is still occurring. 

In screens.rpy:
[https://66.media.tumblr.com/c05b8ee80aa4a7aeef4229d2ad352f77/tumblr_inline_pl2gpp5eqr1r3kenu_540.png](url)

[https://66.media.tumblr.com/32c69d870a096b2f7b885655d2cb0c37/tumblr_inline_pl2gpxB2Y01r3kenu_540.png](url)

In Script.rpy:

[https://66.media.tumblr.com/ab722cd5123d82454d8bf97bac301941/tumblr_inline_pl2gqor5yX1r3kenu_540.png](url)

This will result in the part where the screenshot should have been being blank.
I managed to make the screenshot show onscreen by changing the code from this:
`key "input_enter" action [FileTakeScreenshot(), Jump("done"),  ]`

To this:
`key "input_enter" action [FileTakeScreenshot(), Show("rolls"),  ]`

But then I'm stuck at the "rolls" screen, and unable to return to the main script to proceed to the next dialogue.  If there's a better way to have some kind of animation drop on top of the name input screen as transition (curtain covers name input, and when the curtain lifts the name input is gone and we proceed with the game), then I would love to hear it. Because as of now the Screenshot is the only way I can make this happen.

**Comment by whiteangel123** [comment]
I've posted the same issue here previously and my issue is closed, but it turns out it's still happening. 
I've edited the initial post to clarify what was the problem. To reiterate, this code is working in older builds of Ren'py, but suddenly stops working in 7.1 and 7.1.3. 

I was wondering if there's something that changed in the engine itself that caused the code to stop working. I can't revert to the older engines anymore. The last engine build my game is 100% functional in was Ren'py 6.16, but for some reason my game crash every time I try to run them in 6.16 now.

**Comment by renpytom** [comment]
So, I think I fixed this. The new behavior should be better, and might cover @whiteangel123 's case. If not, you can set config.auto_clear_screenshot = False, which should totally revert to the old behavior. 

See the writeup for commit b8fe298 for a better description of the changes.

**Comment by whiteangel123** [comment]
@renpytom : Thank you so much Tom!! I see, so there is a behaviour that deletes the screenshot... Now it makes sense.
Can I clarify if you mean there's a new engine build or if I should just write "config.auto_clear_screenshot = False" in 7.1.3?
