### ISSUE TITLE
Characters aren't showing up

### ISSUE THREAD

**Issue by Nazokonn** [renpy/renpy#1683]
For some reason, Characters are being replaced by these sillohoutes which have the characters Code sign on them. When you released an update the problem briefly went away, but now its back again. Could you please try to fix this. Thanks

-Nazokonn

**Comment by renpytom** [comment]
This is unlikely to be a bug in Ren'Py. This is the normal behavior that occurs if you show a sprite that does not exist.

**Comment by Nazokonn** [comment]
But the sprites do exist. But for some reason my recent sprites i am using don't show up. and there is no difference between the sprites that work and the ones that don't work. Maybe im just doing something wrong. Do you know how to fix it.

-Nazokonn

**Comment by renpytom** [comment]
Can you hit shift+D, take a file list, and attach it here? Also, I'd like to see the scripts that show the images.

**Comment by Nazokonn** [comment]
What do you mean
