### ISSUE TITLE
Problems with Android SDK 

### ISSUE THREAD

**Issue by occhep** [renpy/renpy#1692]
So I just begun using the engine a few days ago, and when I tried to build apk Ren'py keeps telling me to install SDK even though I have installed it a lot of times (from the launcher).
I know this issue has been there before, but I can't seem to find any solutions. Please help.

**Comment by renpytom** [comment]
You'll need to make a change to rapt/buildlib/rapt/install_sdk.py, as described at:

https://github.com/renpy/rapt/commit/c37fd1ca51e235b52162ac2f0ea39d2bd9488835

**Comment by occhep** [comment]
Thanks a lot, you are a life saver.
