### ISSUE TITLE
libEGL warning: DRI2: failed to authenticate

### ISSUE THREAD

**Issue by COOLIRON2311** [renpy/renpy#1699]
renpy is unable to utilise a hardware video acceleration due to this error. Switching to experimental (both fake and full KMS) does not help.
Platform: 
Raspberry Pi 3
Kernel:
Linux 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

**Comment by renpytom** [comment]
I believe this problem is because you do not have OpenGL support enabled. 

Run:

sudo raspi-config

Then pick:

Advanced Options
GL Driver
GL (Fake KMS)

That should make things work after a reboot.

**Comment by COOLIRON2311** [comment]
@renpytom As I said before, both fake and full kms don’t work. I think that the reason for that is that in Raspbian Stretch the library is called "libbrcmGLESv2.so", not "libGLESv2.so" as in Jessie. (I am on Stretch)

**Comment by renpytom** [comment]
Those are the broadcom drivers. You want the accelerated mesa ones. 

Do you have libgl1-mesa-dri installed?

**Comment by COOLIRON2311** [comment]
@renpytom Yes, I do have libgl1-mesa-dri installed. I've searched about 8-10 bug-trackers, got banned in google but found the solution of my problem. The reason was that raspi-config on Stretch doesn't disable 99-fbturbo.conf in /usr/share/X11/xorg.conf.d/. However, the issue can be solved by manually renaming this file, renpy then works flawlessly.
Source:

**Comment by renpytom** [comment]
I think this is done - or at least not a problem with Ren'Py. Thanks for working through it with me.
