### ISSUE TITLE
Android builds use icon, orientation, version number and name of previously built projects

### ISSUE THREAD

**Issue by computerartclub** [renpy/renpy#1700]
Creating Android builds for new projects with Renpy 7.1.3.1092 will result in a package that has all the configuration settings from existing android builds (name, orientation, version number, icon). It will also seems to overwrite files with the same name in the distribution folder and I believe it also installs over the unrelated existing app on an android device.

The error is (temporarily?) partially resolved when Renpy is reinstalled and RAPT is downloaded again, which, in my case, seemed to fix the version number and orientation issue but not the adaptive icon issue.
This issue seems to have arisen since at least Renpy 7.1.1.

Issue has been experienced by both ComputerArtClub and Imperf3kt.

Relevant Lemmasoft threads:
https://lemmasoft.renai.us/forums/viewtopic.php?p=504041#p504041
https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=52576 (see post by ComputerArtClub)

**Comment by renpytom** [comment]
How do you have "Do you want to automatically update the generated project?" set? Just looking at this, It sure seems like you have it set to "No."

**Comment by computerartclub** [comment]
Thank you for your time PyTom, you are right, that has solved it on my new installation and was probably also the cause on the old installation. Sorry about that!
