### ISSUE TITLE
splashscreen label doesn't display transitions if skip transitions is on

### ISSUE THREAD

**Issue by maxlefou** [renpy/renpy#1702]
Example:
- Create a simple splash screen in script.rpy like below:
```
label splashscreen:
    scene black onlayer background
    show splashlogo with dissolve
    pause 5.0
    hide splashlogo with dissolve
    return
```
- Go to the game options and enable "Transitions" in "Skip"
- Restart the game. The transitions (and the pauses) set in the splash screen will be skipped (in the sample here, it will completely skip the splash screen)

Maybe it would be a good thing to actually make skipping specifically disabled for splashscreen. :)

**Comment by renpytom** [comment]
Not a bug. If skip transitions is on, Ren'py skips transitions. This seems like the obviously correct behavior to me.
