### ISSUE TITLE
iOS should use a Storyboard instead of LaunchImages

### ISSUE THREAD

**Issue by btrdurfee** [renpy/renpy#1705]
When creating a new Xcode project, Ren'py should create a LaunchScreen.storyboard instead of image assets. This will allow the game to take up the full screen on devices without physical home buttons, such as the 11-inch iPad and iPhone X.

**Comment by renpytom** [comment]
I don't know iOS well enough to do this, but it does strike me as something I should do the next time I revisit iOS.

**Comment by btrdurfee** [comment]
it's actually pretty simple.

The launch board is really just an XML file. I created one that has a black background with my window_icon centered, then included the window_icon in the project. I added both the LaunchScreen.storyboard and window_icon.png in my project folder with Info.plist.

In the info.plist, you have to specify the storyboard name value using the UILaunchStoryboardName key, in place of the launch xcasset key/value.

`
<?xml version="1.0" encoding="UTF-8"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="14313.18" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" useTraitCollections="YES" useSafeAreas="YES" colorMatched="YES" initialViewController="01J-lp-oVM">
    <device id="retina5_9" orientation="landscape">
        <adaptation id="fullscreen"/>
    </device>
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="14283.14"/>
        <capability name="Safe area layout guides" minToolsVersion="9.0"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <scenes>
        
        <scene sceneID="EHf-IW-A2E">
            <objects>
                <viewController id="01J-lp-oVM" sceneMemberID="viewController">
                    <view key="view" contentMode="scaleToFill" id="Ze5-6b-2t3">
                        <rect key="frame" x="0.0" y="0.0" width="812" height="375"/>
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <imageView userInteractionEnabled="NO" contentMode="center" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="window_icon.png" translatesAutoresizingMaskIntoConstraints="NO" id="j6j-Tj-7fj">
                                <rect key="frame" x="281" y="63" width="250" height="249"/>
                                <color key="tintColor" white="1" alpha="1" colorSpace="custom" customColorSpace="genericGamma22GrayColorSpace"/>
                            </imageView>
                        </subviews>
                        <color key="backgroundColor" white="0.0" alpha="1" colorSpace="custom" customColorSpace="genericGamma22GrayColorSpace"/>
                        <constraints>
                            <constraint firstItem="j6j-Tj-7fj" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" id="0kE-73-j4h"/>
                            <constraint firstItem="j6j-Tj-7fj" firstAttribute="top" secondItem="Bcu-3y-fUS" secondAttribute="top" constant="63" id="VNN-ui-FhT"/>
                            <constraint firstItem="j6j-Tj-7fj" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" id="zs4-Wa-w3X"/>
                        </constraints>
                        <viewLayoutGuide key="safeArea" id="Bcu-3y-fUS"/>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
            <point key="canvasLocation" x="53" y="375"/>
        </scene>
    </scenes>
    <resources>
        <image name="window_icon.png" width="250" height="250"/>
    </resources>
</document>
`

**Comment by renpytom** [comment]
This was finished in the 7.4 series.
