### ISSUE TITLE
Ability to reliably anchor text to baseline

### ISSUE THREAD

**Issue by mal** [renpy/renpy#1706]
When positioning text displayables, it would be really nice to be able to have the `yanchor` match the font's baseline. This would make it much easier to position text that must overlay a background image. A good example of this would be a form upon which a dynamic character name needs to appear.

This is currently achievable via trial and error (see example image and code below the fold; middle line) until reaching the correct `yanchor`, however any tags in the text that result in a `bbox` adjustment ruin this (example; bottom line).

This case, being able to annotate text with displayables without destroying it's positioning, opens up very interesting possibilities when it comes to dynamically generated and translatable annotated documents. For instance making effects such as this achievable:

![correct](https://user-images.githubusercontent.com/591257/52181110-3401b800-27e6-11e9-93c2-b5b4eed6f18e.jpg)

<details><summary>Example Image</summary>

![screenshot from 2019-02-03 18-51-56](https://user-images.githubusercontent.com/591257/52181017-de78db80-27e4-11e9-984f-5a6c67984c47.png)
</details>

<details><summary>Example Ren'Py code</summary>

```renpy
label main_menu:
    pass

label start:
    show screen default
    show screen ideal
    show screen broken
    $ renpy.pause()

image annotation:
    Text('dynamically')
    rotate -20

screen default: # default yanchor, baseline doesn't align
    fixed:
        pos 30, 30
        add Solid('#f00', maximum=(580, 1)) ypos 10
        text 'default'
        text 'too {size=+5}low{/size}' xpos 100
        text '{size=-1}baselines{/size} {size=+15}doesn\'t{/size} {size=-3}align{/size}':
            xpos 250

screen ideal: # yanchor set by trial and error, provides desired result
    fixed:
        pos 30, 130
        add Solid('#f00', maximum=(580, 1)) ypos 1
        text 'trial&error' yanchor .7675
        text 'works {size=+5}well{/size}' xpos 100 yanchor .7675
        text '{size=-1}baselines{/size} {size=+15}all{/size} {size=-3}match{/size}':
            xpos 250
            yanchor .7675

screen broken: # bounding box expansion ruins trial and error solution
    fixed:
        pos 30, 230
        add Solid('#f00', maximum=(580, 1)) ypos 1
        text 'broken' yanchor .7675
        text 'works {size=+5}until{/size}' xpos 100 yanchor .7675
        text '{size=-1}bbox{/size} {image=annotation} {size=-3}resizes{/size}':
            xpos 250
            yanchor .7675
```
</details>

**Comment by mal** [comment]
Thanks for the crazy fast turn around on this @renpytom!

Unfortunately there seems to be an edgecase when the text displayable uses variable font sizes. Updating the example above, it's possible to see that the middle displayable ("bit low") has been pushed down by the larger secondary size on the word "low", and the final displayable (using smaller fonts) sits one pixel too low (or alternatively the first displayable sits one pixel too high, not sure which).

```renpy
screen broken: # mixed font sizes lead to odd results
    fixed:
        pos 30, 230
        add Solid('#f00', maximum=(580, 1))
        text 'perfect' yanchor renpy.BASELINE
        text 'bit {size=+5}low{/size}' xpos 100 yanchor renpy.BASELINE
        text '{size=-1}nicely{/size} {image=annotation} {size=-3}bound{/size}':
            xpos 250
            yanchor renpy.BASELINE
```

![untitled](https://user-images.githubusercontent.com/591257/52207298-eda76a00-2874-11e9-9777-36c3124ad277.png)

**Comment by renpytom** [comment]
I believe that they should all be lined up with each other. (Except for the image, which I'm not going to to touch.)

**Comment by mal** [comment]
Brilliant! Thanks Tom! This is going to be really useful!

**Comment by mal** [comment]
Sorry to haunt you with this again, but just been testing this out in the pre-release and it seems that using outlines forces some additional misalignment.

```renpy
screen broken: # outlines cause additional issues :(
    fixed:
        pos 30, 230
        add Solid('#f00', maximum=(580, 1))
        text 'perfect' yanchor renpy.BASELINE
        text 'bit {size=+5}low{/size}':
            xpos 100
            yanchor renpy.BASELINE
            outlines ((5, '0f77', 0, 0),)
        text '{size=-1}nicely{/size} {image=annotation} {size=-3}bound{/size}':
            xpos 250
            yanchor renpy.BASELINE
```

![screenshot from 2019-02-09 06-43-04](https://user-images.githubusercontent.com/591257/52517645-18f3d580-2c36-11e9-8e91-f29f1daf8387.png)

**Comment by mal** [comment]
@renpytom would it be possible to reopen this issue again in light of the comment above and the attempted fix (https://github.com/renpy/renpy/pull/1712)?
