### ISSUE TITLE
Switching from fullscreen to window is broken in 7.1.4

### ISSUE THREAD

**Issue by KosMos-pv** [renpy/renpy#1708]
If I switch from fullscreen to windowed mode in preferences screen, the game is shown in a very small window and I need to manually resize it. But if I use F11 or Alt-Enter there is no problem - window size is remembered.
This happens in both prerelease 7.1.4.1213 and nightly 7.1.4.1222. In stable 7.1.3.1092 no problems at all.
My screens.rpy is not modified and I tested in different projects that use default non-modified screens.rpy. My test projects use 1920*1080 resolution, but my native resolution is 1366*768.
I tried to create a new project with 1280*720, but result is the same.

**Comment by renpytom** [comment]
Can you please post the log.txt from a session where this happens? That will help me figure out what's going wrong.

**Comment by KosMos-pv** [comment]
[log.txt](https://github.com/renpy/renpy/files/2831346/log.txt)
Started a game in window mode (before this I cleared persistent), the switched to fullscreen in preferences and back to window. The window is small. After that I closed the game.
