### ISSUE TITLE
Clicking on window mode in settings resizes window if already windowed

### ISSUE THREAD

**Issue by KosMos-pv** [renpy/renpy#1716]
I think it's from last changes which I described in #1708. Now there is a strange behaviour if I click on Windowed option in preferences. If I'm in fullscreen this switch works normally, but when I'm already in windowed mode and click on Windowed again the window is resized. When I switch to fullscreen and back to window, size of window is correct, but second click resizes. Yes, this is very uncommon that player will click in Windowed option again, but this should be fixed.
Here is a log from last session where I switched from window to fullscreen and back to window and clicked Windowed again.
[log.txt](https://github.com/renpy/renpy/files/2857223/log.txt)

**Comment by renpytom** [comment]
This is intentional. Clicking again on the window preference resizes the game to it's 1:1 resolution.

**Comment by KosMos-pv** [comment]
OK, but if I have a lower native resolution than game's default this resize looks weird.
https://i.imgur.com/k0Rx8U1.png - here is fullscreen screenshot from my desktop, hewn I returned from fullscreen. Here is all right and works like in earlier versions.
But if I click again on Window or even if I minimize and restore the game I get this - https://i.imgur.com/asPQXOX.png
In previous versions window did not resize on minimizing and restoring back.

**Comment by vollschauer** [comment]
Just change the "Windowed" option to your needs, you don't have to stick to the default behavior. I don't see any issue here....

**Comment by KosMos-pv** [comment]
My visual novel uses a different GUI, but this is also happens. My button for changing to window uses a simple function, that was used in older versions of engine.
textbutton _("Оконный") style "menu_choice_button" xfill True action Preference("display", "window")
And first time it restores to normal sized window like in first screenshot, but if I stay in preferences screen and minimize game and restore it back the window is resized. This also happens if I click on window button again.
Are the black borders are intended if I click Window again or minimize window and restore it back? I think it's not normal even this scenario is very rare (user will not click twice on Window button). But if user minimize game with preferences screen opened the window is resized automatically even there was no changes in screen.
In 7.1.3 there is no such behaviour. But this happens in 7.1.4.1230/

**Comment by KosMos-pv** [comment]
OK, I fixed this by replacing action Preference("display", "window") to Preference("display", "any window").
Yes, this was strange, but now there is no resizing if we accidentally click on Window button again.
