### ISSUE TITLE
{space} tag causes screen issues when decreasing window size of renpy

### ISSUE THREAD

**Issue by sdn3rd** [renpy/renpy#1719]
{space} tag causes screen issues when decreasing window size of renpy

```
screen letter(text):
    fixed:
        align (0.5, 0.5)
        fit_first True
        add "images/ui/scroll_base.png" zoom 0.95
        fixed:
            yoffset 20
            xsize (get_width(Transform("images/ui/scroll_base.png", zoom=0.95)) - 300)
            ysize (get_height(Transform("images/ui/scroll_base.png", zoom=0.95)) - 220)
            align(0.5, 0.5)
            side "c l b":
                spacing 10
                viewport id "vp":
                    draggable True
                    mousewheel True
                    text _(texts):
                        xalign 0.5
                        size 35
                vbar value YScrollValue("vp") unscrollable "hide"
                textbutton _("Finish"):
                    yalign 1.0
                    xalign 0.5
                    action Return()
```

As seen here:
![image](https://user-images.githubusercontent.com/5367766/52875774-296aeb00-3123-11e9-9780-146029058c05.png)

Removal of {space} tag prevents this from happening, it does not seem the tag is handled the same across all languages either.

Once removed:
![image](https://user-images.githubusercontent.com/5367766/52875903-86ff3780-3123-11e9-8104-dbf93eebb4fb.png)

**Comment by renpytom** [comment]
Can you please post the text that uses this screen, especially how you're using the {space} tag? 

Also, the get_width and get_heigt functions, as these seem quite suspicious, as a bad xsize or ysize might be able to cause the problem you're seeing.

**Comment by sdn3rd** [comment]
`translate english strings:

    # mechanics\letters.rpy:166
    old "{space=30}- Василиск тебя задери! Ричи! Можно поосторожнее?! {p}– исходящий праведным гневом Сэмуэль Стем даже хотел замахнуться кулаком на молодого паренька, но вовремя одумался. {p}Все-таки на факультете Когтевран, да и, чего греха таить, во всей школе, Ричард Граймс считался человеком несколько не от мира сего, и рукоприкладствовать, по отношению к нему, было несколько некрасиво. {p} {space=10}- П-прости, пожалуйста, Сэм. Этот котелок очень тяжелый. - Выражение глубочайшего осознания собственного проступка на лице виновника, несколько охладило пыл Сэма. Но, все же тащить полный котел непонятной бурды через всю гостиную... Эх, Ричи и правда, странный парень. Немудрено, что этот щуплый студент, за своим котлом даже дороги-то не видел. Вот и наткнулся на кресло, где уютно развалился Сэмуэль с очередным номером «Пророка». И закономерно окатил его озвученной выше бурдой, испортив новые брюки. {p} {space=30}В гостиной студентам, в соответствии со школьными правилами, необязательно было одевать мантию, и лишь этот факт уберег мантию Сэма от печального конца. {p} {space=10}- Ладно, Ричи, к дементорам штаны, они все равно мне никогда не нравились, - отшутился Стем. {p}Стоит признать, что, несмотря на напускную язвительность, он был довольно добрым и отзывчивым человеком и относился к странному сокурснику с долей сочувствия и симпатии. {p} {space=10}– Пошли я помогу тебя дотащить остатки твоего варева до... куда бы ты там это не нес. {p}{p}{p} {space=10}- И что должно получиться в итоге? Кроме мерзкого запаха, разумеется? – котелок, в котором постоянно что-то булькало и скворчало, и правда, разносил по комнате весьма специфический запах. {p}Хотелось даже открыть окно, но, вот только, выручай-комната его не предусмотрела. Странно, учитывая, что она должна подстраиваться под требования ситуации. Эту магическую комнату, постоянно плавающую в пространстве, на днях Сэму показал Ричард. Как он ее раскопал – загадка. Ричи вообще полон загадок. Несмотря на его заторможенность, социофобию и другие странности, никто не укорил бы студента в низком интеллекте. Он заслуженно попал на Когтевран – факультет истинных «грызунов науки». Основной страстью Ричарда, было зельеварение, в этой области, он достиг поистине высоких результатов. Даже сам профессор Снейп, периодически хвалил его. Хотя, делал он это, с неизменным выражением лица: - «Вы все насекомые, почему я вообще вас чему-то учу». И, на сей раз, Ричи решил показать Сэму какое-то свое очередное открытие, которое, по его словам, «очень-очень важное». Почему именно Сэму? Скорее всего, потому, что лишь он проявлял к странному студенту человечность и порой даже интерес к его исследованиям. {p} {space=10}- Получится! Должно получиться, да! – в глазах Ричи горел фанатичный огонек спятившего ученого. {p} {space=10}- Должно, дружище, я не спорю. Спокойнее. Только вот, что именно? В чем суть рецепта-то? Зелье из класса метамагии? Или может прямого заклинательного воздействия? {p} {space=10}- А? Метамагии? Нет! Чушь-чушь-чушь! Нет, состав экспериментальной субстанции содержит толченную мандрагору! Мандрагора не используется в метамагии. Сэм, ты чего? – искренне удивился Граймс. {p} {space=10}- Ну, дружище, не все же такие мастера в области Снейпопоклонности, я не знал, - с улыбкой парировал Сэмуэль. – Ну, не томи, приятель, что за зелье ты тут варишь уже полдня? {p} {space=10}- Полдня? Я варю его уже месяц! Четырнадцать подходов, отжим, возгонка, кристаллизация, снова варка! Это будет мой шедевр! Ш-шедевр, что даже сам Северус Снейп снимет передо мной шляпу! {p} {space=10}- Хмм... Если бы он её еще носил. А так, он больше привык снимать скальпы с нерадивых студентов. Ладно, ты хоть сегодня ответишь мне на вопрос? Что это за зелье? – в голосе Сэма сверкнуло неплохо скрываемое раздражение. {p} {space=10}- Зелье? Ааа. По завершению эксперимента мы получим зелье ментальной интервенции. Понимаешь? Любой, кто выпьет его, станет открытым трактатом для субъекта эксперимента. Все его мысли легко можно будет увидеть! – фанатичный огонек потихоньку превращался в пламя. {p} {space=10}-Воу-воу, Ричи. Серьезно? Да ты тут времени не теряешь. Если твоя штука сработает, ты попадешь на обложку «Пророка». А окклюменция сможет заблокировать эффект, этой твоей штуки? {p} {space=10}- Нет! Ничто не сможет блокировать действие, именно для этого я добавил тысячелистник! Я же при тебе его кидал в котелок, - казалось, Ричард немного обиделся на невнимательность товарища. {p} {space=10}- Да-да, корень, конечно, как я сразу не понял. На ком тестировать-то будем твое чудо-варево? Есть кандидаты? Только не говори, что на мне, я не собираюсь позволять тебя копаться у меня в голове. {p} {space=10}- Я... Я еще не думал об этом, - Ричи повернулся к Сэму в полной растерянности. {p} {space=10}- Ладно, нальешь мне своего зелья, я его кому-нибудь тайком скормлю, не проблема. {p} {space=10}- Да... Да! Именно так. Эффективно. Рационально. Спасибо Сэм! Сейчас, я только добавлю свой волос, чтобы ментальное перенаправление мыслей, осуществлялось именно в мою сторону. {p} {space=10}- Добавляй, приятель, добавляй. Только не из носа, пожалуйста, - глупо хихикнул над собственной несмешной шуткой Сэм. Его мысли уже были заняты поиском потенциальной жертвы.\n\n{p} {space=10}- Сэнди, ты прекрасно сегодня выглядишь. Угостить тебя тыквенным соком?\n\n{p} {space=10}- У тебя получилось? – Ричард жадно впился глазами в Сэма в ожиданиях ответа, как только он вошел в спальню. {p} {space=10}- Конечно, ничего сложного, как карточку Дамблдора в шоколадных лягушках вытащить. – Сэм был явно доволен собой. {p} {space=10}- И кто? Кто объект эксперимента? Кто выпил зелье? – Ричи был настолько переполнен эмоциями, что начал нелепо приплясывать, заваливаясь на одну сторону. Что несказанно позабавило, и так довольного Сэма. {p} {space=10}- Сэнди, наша мисс зазнайка. {p} {space=10}- Сэнди?! П-по-почему именно С-сэнди? – Ричи замер посреди спальни каменным големом. {p} {space=10}- Ну, а почему нет? Интересно будет узнать, о чем думает это воображала. А то вся из себя такая одухотворенная, слова ей не скажи, пошлую шутку не пошути, «фи-фи-фи». Эй, ты чего так побледнел? {p} {space=10}- Н-ничего, просто я... просто побледнел! – теперь Ричи стал стремительно заливаться краской. {p} {space=10}- Ты чего, в нее втюрился что ли? Вот это неожиданность, я-то думал, ты кроме своих зелий и котлов не способен никого заметить, - Сэм разразился веселым хохотом, шлепнув ладонью по колену, - Во дела! {p} {space=10}- Прекрати, ничего я не втюрился, просто она такая... В общем, хватит об этом, результаты эксперимента должны появиться через час, идём пока в гостиную, мне нужно находиться в непосредственной близости к объекту, для успешного функционирования ментальной передачи.\n\n{p} {space=10}- А Сэнди и правда, ничего, да, Рич? – ухмыльнувшись, Сэм чмокнул губами в сторону Сэнди, скосив глаза при этом на Ричарда. Он был намерен выжать из открывшейся правды все возможные и невозможные шутки. {p} {space=10}- А? А? Чушь-чушь-чушь! Ее внешность не имеет отношения к эксперименту, забудем об этом, - снова залился краской юный гений. А внешностью Сэнди, стоит отметить, действительно выделялась на факультете. Невысокая, крайне стройная, создающая впечатление миниатюрности и хрупкости, но, вместе с тем, элегантности и женственности. Огромные голубые глаза на маленьком личике и, чуть вздернутый, тонкий нос. И как приятное дополнение, прямые, длинные, всегда идеально расчесанные, черные, как плащ дементора, волосы. {p} {space=10}- Не будем, так не будем. Но, надо будет мне за ней приударить, такая милашка, - Сэм настолько развалился в своем кресле, что казалось, если он расслабится еще хоть на йоту, то просто стечет на пол, как желе. {p} {space=10}- Приударить? Я не понимаю твоих архаизмов! – в глазах Ричарда сверкнуло что-то отдаленно напоминающее ярость. {p} {space=10}- Ого, да у тебя все серьезно, дружище. И к слову – это был не архаизм. Это... {p} {space=10}-Ричи. У Сэма в прямом смысле отвисла челюсть. Ведь это Сэнди бесцеремонно прервала его речь, подойдя к двум приятелям. {p} {space=10}- Привет Сэн... {p} {space=10}- Ричи, - Сэнди снова перебила Сэма в упор глядя только на Ричарда, - Я хотела сказать, что я... Я даже не знаю, что я хочу сказать, прости. Но если тебе будет интересно, я хотела бы с тобой пообедать. Или поужинать. Или погулять, поговорить о твоих научных исследованиях.  Могу я составить тебе компанию? Лицо Сэнди выражало крайнюю степень смущения, но она мужественно терпела это, и выдавливала из себя слово за словом. {p} {space=10}- Э-э-э, к-конечно, мы можем, то есть ты можешь быть компанией. Моей, да. – Ричи выглядел еще хуже, весь красный, как письмо-кричалка, он вжался в свое кресло, как в последний оплот. {p} {space=10}- Спасибо, Ричи, тогда до завтра? – Сэнди вздохнула свободнее и улыбнулась. {p} {space=10}- Д-до з-завтра. На этой ноте девочка развернулась, и, так и не удостоив Сэма даже взглядом, ушла. Тот же, подозрительно сощурив глаза, обернулся к Граймсу. {p} {space=10}- Ричи, это очень напоминает действие любовного зелья, какого василиска?! Твое варево сработало с побочным эффектом? Она же просто тащит тебя на свиданку! {p} {space=10}- Сэм, - глядя куда-то в пространство, странным, неживым голосом ответил Ричард, - Сэм, я видел ее мысли. И ты не представляешь, что в них было."
    new _p("""
{p} {space=10}-	Where’s a basilisk when you need it?! Richie! Try to be more careful!
{p}Samuel Stem in his rightful anger almost raised his hand at his young student, but managed to regain his composure. Even for Ravenclaw, Richard Grymes was considered to be too out of this world, and assaulting such a boy would only bring more trouble.
{p} {space=10}-	I am sorry, Sam. This cauldron is just too heavy. Words couldn’t describe the look of guilt on boy’s face, calming down Sam even further.
{p}Still, carrying a cauldron full of some suspicious liquid across the common room… damn. Richie is really too weird even for this school. It’s hardly surprising that this puny student couldn’t see anything carrying the cauldron, tripping over the armchair, Sam was sitting with the latest issue of “Oracle”. Spilling the aforementioned liquid all over and destroying Sam’s new trousers.
Common room is one of the few places at school, where uniform rules are lax, a fact that undoubtedly saved Sam’s robes from sharing the fate of his trousers.
{p} {space=10}-	Fine, Richie, to hell with my trousers, I didn’t like them that much, Sam said breaking the tension.
While others sometimes thought of him as ruthless, inside he was a kind and compassionate. He felt somewhat bad for his fellow student.
{p} {space=10}– Come on, I’ll help you with what’s left of your concoction… where were you caring it to?


{p} {space=10}-	So, what were you trying to make? Besides a putrid smelling liquid?
{p}The cauldron continued to make bubbling and even wheezing sounds, with a smell that could rival an ogre’s breath. Opening a window would have been an option, if they weren’t in the Room of Requirement, which for some reason this time didn’t provide everything that was required, unlike the name would suggest. This room, that ever shifted across the school, was found and shown to Sam by Richie. How the latter one found it himself remained a mystery. Richie himself, was a complete mystery in fact. Despite his slowness, social awkwardness and other quirks, no one would accuse him of being dim-witted or stupid. He was one of the better Ravenclaw students, and truly was an embodiment of this house virtues. He was especially passionate about potions, and had surprising skill with them. Even earning occasional praise from Professor Snape. Though somehow, even during those rare moments, Snape’s face would keep the usual expression of “You simpletons, why am I even bothering to teach you”. And so, this time Richie decided to show his new concoction to Sam, which he described as “Something utterly important”. Why did he choose Sam? Probably because, he did show him occasional compassion and even interest in his research he postulated.
{p} {space=10}-	It will work! It has to work, yes! – Richie had a glint of madness in his eyes, typical for most Ravenclaw.
{p} {space=10}-	Richie, I don’t doubt you. Just, relax. What has to work? What is this recipe? It looks like something from polymagic? Or is it something along the lines of direct interaction?
{p} {space=10}-	What? Polymagic? No-no-no! This experimental brew has grounded mandragora! You would never use mandragora for polymagic. What are you on Sam? – Grimes was truly surprised by the remark.
{p} {space=10}-	Well, my friend, not everyone are as adept at the Snapespering as you – parried Samuel with a cunning smile – So, what is that? What have you been brewing here for so long?
{p} {space=10}-	Long? This isn’t long at all! I spent the last month on this! Fourteen complete cycles of brewing, crystallisation and distilling, brewing again! This is my magnum opus! After this even Severus Snape will have to tip his hat to me!
{p} {space=10}-	Hmm, if only he wore one. I guess he is more used to taking off his students’ scalps than anything else. So, can you finally tell me – what is this potion? – Sam’s voice did little to cover his annoyance.
{p} {space=10}-	Potion? Ah, yes. By the end of the experiment we will receive a potion of mental intervention. Do you get it? Anyone who drinks it will become an open book to the subject of experimentation. All of their thoughts will be easily seen! – the glint of madness slowly turned into an untamed flame.
{p} {space=10}-	Hold your horses, Richie, are you serious? I guess you didn’t waste your time here. If this actually works, you’ll get to be on a cover of the “Oracle”. What about occlumency, wouldn’t block your potion?
{p} {space=10}-	No! Nothing will be able to stop it, I have added the millefolium just for that. You saw me adding it, - Richard looked as if he was insulted by his friends remissness.
{p} {space=10}-	Yes-yes, that root, how could I have missed it! So, who will be your test subject? Any candidates? Don’t tell me, you planned to test it on me, I won’t allow you to dig through my mind.
{p} {space=10}-	I… I hadn’t thought about that… Richie turned to Sam, with the lost look on his face.
{p} {space=10}-	Fine, pour me some of it, and I’ll trick someone into drinking it.
{p} {space=10}-	Yes… Yes! Just like that. Effective! Rational! Thank you, Sam! Let me just add my hair to it, so that thoughts will be directed to me.
{p} {space=10}-	Sure, make sure you do it right, Sam said without thinking, his thoughts were occupied with a query to find a potential victim.




{p} {space=10}-	Sandy, you look great today. Do you want some pumpkin juice?


{p} {space=10}-	Did you do it? Richard asked Sam, as soon as he entered the bedroom.
{p} {space=10}-	Of course, piece of cake, like getting a Dumbledore card from a chocolate frog. – Sam looked very satisfied with himself.
{p} {space=10}-	So, who was it? Who will be the subject of our experiment? Who drank it? – Richie was bursting with excitement, prancing about and barely holding himself together. This put an even bigger smile on Sam’s face.
{p} {space=10}-	Sandy, our miss know-it-all of course.
{p} {space=10}-	Sandy? W-why Sandy? – Richie stopped in his tracks, as if he was a stone golem.
{p} {space=10}-	Why not? Wouldn’t you like to know what that little minx thinks? Aren’t you annoyed by her attitude, so pure, you can’t even joke next to her, as soon as you get a bit crude, you won’t hear the end of it. Hey, what’s wrong, why did you suddenly become pale?
{p} {space=10}-	No-nothing, I just… went pale for no reason! Now Richie suddenly started to change colour as well, but to bright red.
{p} {space=10}-	No way! So you like her? And here I thought that only a new cauldron could cause such an expression from you. Sam couldn’t contain his laughter any longer, slapping his hand against his knee. Surprised doesn’t even begin to cover it!
{p} {space=10}-	Stop it! I do NOT like her, it’s just she is so… ugh… Stop, we have to concentrate on our experiment. The potion should take an effect in an hour, and I have to be close by, so let’s get to the common room.
{p} {space=10}-	You know, Sandy is a real looker Richie, don’t you think? Sam said toward Sandy upon seeing Sandy while approaching the common room, sneakily checking for Richard’s reaction. He planned to milk the sudden discovery for maximum entertainment value.
{p} {space=10}-	What?! S-stop it! Her looks have nothing to do with our experiment, forget about her looks! Red as a stop light, Sam quipped back.
{p}Truth to be told, Sandy really was one of the better looking girls in the house. Not too short, fit, creating a delicate impression, that was full of elegance and femininity. Such large blue eyes on a small face, complemented with a small and delicately sloped nose. And to top it off, long elegant and perfectly straight black hair that glistened like it was the finest of silks and fell right above her perfectly shaped bottom.
{p} {space=10}-	Sure then, you don’t want to talk about it, I understand, said Richie. But I definitely should try hitting on her, she is too good to pass up. Sam fully relaxed in his armchair, to the point where if he were to relax further, he might just disappear into it.
{p} {space=10}-	Hit on her? What do you mean by that! Richard’s eyes had a hint of rage in them.
{p} {space=10}-	Wow, that serious, my friend? I was just voicing my opinion. I…
{p} {space=10}-	Richie, said Sam in what might be mistake as a calm voice.
{p}If it was possible, Sam’s jaw would break the floor. Because it was Sandy who interrupted their talk so abruptly, coming close to the two pals.
{p} {space=10}-	Hello San…
{p} {space=10}-	Richie, Sandy interrupted Sam once again, looking straight at Richard. I wanted to tell you, that I… I don’t know what I want to say, I am sorry. But if you are interested, I would like to have lunch with you. Or dinner. Or we may take a walk, talk about your experiments. Perhaps I can I keep you company?
{p}Sandy’s face had an extreme look of shyness on it, but she kept on talking, pushing the words out one by one.
{p} {space=10}-	Emmm, o-of course we can, I mean you can keep me company. My company, yes. Richie looked even worse, discovering ever-new shades of rose, it looked if he really was trying to disappear into his armchair.
{p} {space=10}-	Thank you, Richie, then I’ll see you tomorrow? Sandy looked relieved and smiled.
{p} {space=10}-	Ye-yes, t-tomorrow.
{p}On that note, Sandy turned around, continuing to ignore Sam and left. As soon as she did, Sam gave an inquisitive look to Grimes.
{p} {space=10}-	Richie, this looks very much like an effect of some charm potion, what in Merlin’s beard was it?! Did your potion had some side-effect? If I wasn’t here, I think she would have just dragged you with her on a date right then and there!
{p} {space=10}-	Sam, answered Richard with his gaze wandering off in some far away realm. Sam, I saw her thoughts. And you cannot possibly imagine what was in them!

""")
`
