### ISSUE TITLE
Outline scaling isn't quite right

### ISSUE THREAD

**Issue by mal** [renpy/renpy#1729]
These are two related issues found with outlines when trying to solve #1712.

**Positional drift with absolutes:**

The texture size appears to be calculated ignoring that `o`, `xo` and `yo` of an outline may be `absolute`, but offset and borders are calculated to respect absolutes. This mismatch leads to positional drift when scaling as the gap between the two grows wider.

**Stepped scaling:**

Culprit appears to be this line, which truncates the sample _before_ scaling rather than afterwards:
https://github.com/renpy/renpy/blob/b639e0bca5882a558b79d103efd77f4fe6c97548/renpy/text/text.py#L847

**Test case**

```renpy
init python:
    gui.init(290, 100) # intentionally small for easy scaling

label main_menu:
    $ _confirm_quit = False
    return

label start:
    show screen outlines
    $ renpy.pause()

screen outlines:
    fixed:
        pos 30, 80
        add Solid('#f00', maximum=(230, 1), ypos=4)
        text '_drift_':
            yanchor 1.
            outlines ((absolute(1), 'f707', 0, absolute(-30)),)
        text '_{u}step{/u}_':
            xpos 65
            yanchor 1.
            outlines ((1, '70f7', 0, -30),)
        text '_vanilla_':
            xpos 130
            yanchor 1.
```

**Problem**

_`_drift_` moves steadily away from the anchor as the texture size expands too fast, while `_step_` jitters due to int truncation of `oversample`_
![7.1.4-pre](https://user-images.githubusercontent.com/591257/53042953-4551f200-347f-11e9-8169-96b998236196.gif)

**Expected**

_`_drift_` stays anchored as the outline stays a fixed 30px away at any scale, while `_step_` also remains anchored and it's outline scales away from it_
![7.1.4-patch](https://user-images.githubusercontent.com/591257/53043075-95c94f80-347f-11e9-88bf-348fa8497bfd.gif)

---

The expected example was produced using [this branch](https://github.com/renpy/renpy/compare/master...mal:outlines), however it includes a wide ranging change that I'm sceptical is the "correct" way to solve this, and may have other consequences, which is why it is not in PR form. Linked here in case it can be useful in some way, feel free to merge in whole or part as may be required.

**Comment by renpytom** [comment]
Okay, just made a series of changes to  the way Ren'Py renders text, which should address your issues. 

The main one is that when text is scaled, it should remain aligned at the baseline of the text. This prevents the text from drifting out of position as in your example. I do want to keep everything integer-aligned, so there does appear to be a little more jumping than in your second example. It's hard to tell from your compressed image, but I believe using integer pixel alignment should yield better visual results when the image is not being resized. 

The other change was to add a new style property, ``outline_scaling``. I think the current scaling behavior is better for common clases, like a pair of outlines put together to form a dropshadow. There's an issue with the alternative linear scaling where if you have multiple outlines, they may scale at different break-points, and hence the relative spacing between outlines changes and looks terrible.  For single outlines and thick outlines, it's less of a problem. So as a result, I've added the outline scaling property to allow the creator to choose between step and linear scaling. 

And I think that's about it. If you can figure out how to prevent the jumping up and down while scaling, that would be helpful - but I haven't been able to, and I think the solution of rewriting everything to use floats isn't acceptable.

**Comment by mal** [comment]
This is great, thanks for looking into it, Tom. Completely agree on the floats front, that branch was very much the result of throwing stuff at the wall repeatedly, I'm glad you've been able to find a nicer solution. 🙂

I've taken https://github.com/renpy/renpy/commit/2b0691233e63f40940dc6d2e838c962172d392b7 for a spin, and I can't find any evidence of the `outline_scaling` property mentioned. However I did twig on a potential solution to the positional stepping, which I believe addresses your concern around outlines stepping at different times: https://github.com/renpy/renpy/pull/1733.

**Comment by renpytom** [comment]
Ah, didn't push it - f5c1e108c58ffb6fc444e7b77e142cd10ac9fd3a has outline_scaling.

**Comment by mal** [comment]
Aha, just had a play around with that, `outline_scaling linear` definitely solves my particular bug bear, so huge thanks for facilitating that, this stuff's been driving me nuts for a week! 😅

I wasn't 100% clear on what your "prevent the jumping up and down while scaling" comment referred to, so I'll address both possibilities:

1. If referring to outlines jumping positionally at break-points in `step` mode, then I think #1733 should solve that issue, without compromising on the lock-step nature of outline sizing.
2. If talking about the inconsistent baseline jitter while scaling, unfortunately I could never get to the bottom of it. My gut feeling initially was that it was potentially the result of the scaling, integer truncation and unscaling combination, possibly in conjunction with `size_only` mode returning prior to the bounding box expansion, but despite multiple attempts tweaking bits and pieces (including all the float madness) I could never verify either factor to be the direct cause. It's odd, but assuredly more of a curiosity than any kind of problem at this point.

Once #1733 is dealt with (irrespective of whether approved or rejected), I think this one will be good to close out. Thanks again, these changes will be massively helpful!

**Comment by renpytom** [comment]
I think with #1733 in, we're good to go.
