### ISSUE TITLE
Could not find required library SDL2 while building renpy from source

### ISSUE THREAD

**Issue by plantysnake** [renpy/renpy#1736]
Hi. I've been trying to build Ren'Py from source on my PC from Windows.
And I got this
`D:\Renpy\renpy\module>workon renpy
(renpy) D:\Renpy\renpy\module>python setup.py install
Could not find required library SDL2.`
In the files I looked  through I found this
`include("SDL.h", directory="SDL2")`

But there isn't such dir there...
What should I do?

P.S. I already built SDL2 in (renpy) virtualenv

**Comment by plantysnake** [comment]
And more

I needed to search through all renpy rep to find some piece of advise. Why is this build info so unclear?
(For other platforms than linux)

**Comment by renpytom** [comment]
The answer is simply that windows building is hard. You can see the scripts I use to build it at https://github.com/renpy/renpy-deps . build.sh being the main one. Unfortunately, I've yet to get to the point where the process is foolproof enough that I'd feel comfortable with other people building Ren'Py on Windows.

**Comment by plantysnake** [comment]
1st of all
When building SDL2 you need to:
1) do this:
`git clone https://www.github.com/renpy/pygame_sdl2
pushd pygame_sdl2
git clone https://www.github.com/renpy/pygame_sdl2_windeps
`
2) change line in setuplib.py
`if windows:
    cython_command = os.path.join(os.path.dirname(sys.executable), "Scripts", "cython.exe")
else:
    cython_command = "cython"`
to
`if windows:
    cython_command = os.path.join(os.path.dirname(sys.executable), "cython.exe")
else:
    cython_command = "cython"`
3) Just build.
4) ???
5) Profit!
So error `WindowsError: [Error 2]` in SDL2 installation goes away.

But Ren'Py is still searching for SDL.h in SDL2 dir

**Comment by plantysnake** [comment]
@renpytom 

> Next, set RENPY_DEPS_INSTALL To a \:-separated (\;-separated on Windows)
> list of paths containing the dependencies...

What are this dependencies?
Cause I already tried to clone https://github.com/renpy/renpy-deps
But there isnt anything that looks alike
