### ISSUE TITLE
Regression: speaking_attribute can't be suppressed

### ISSUE THREAD

**Issue by mal** [renpy/renpy#1738]
A change in eab5170ae1041183fdb6d138015445088d6d94ca switched the `speaking_attribute` from being prepended to the temporary attribute list to being appended (unsure if this was intentional, the comment message makes no mention of it). As noted in https://github.com/renpy/renpy/pull/1735 the reason for prepending was to allow temporary say attributes the chance to suppress the `speaking_attribute` for cases such as lines of internal character monologue/unspoken thoughts.

The test case presented on the original issue can be used to show the issue: the third lines applies a `-speak` temporary attribute that should suppress the `speaking_attribute`, but as of eab5170ae1041183fdb6d138015445088d6d94ca this is no longer the case.

Switching back to a prepend resolves this issue.

```renpy
label main_menu:
    $ _confirm_quit = False
    pass

layeredimage alice:
    always:
        Text('always', yoffset=-20)
    group A:
        attribute alpha default Text('alpha')
        attribute beta Text('beta')
    group B:
        attribute nospeak default Null(height=21, yoffset=20)
        attribute speak Text('speak', yoffset=20)

define config.speaking_attribute = 'speak'

define alice = Character('Alice', image='alice')

label start:
    show alice at Position(pos=(.25, .5)) with dissolve
    alice 'With no explicit attrs, use the speaking attr.'
    alice @ beta 'Use speaking attr when using tmp attrs too.'
    alice @ -speak 'But allow speaking attr to be suppressed by tmp attrs.'
```

**Comment by renpytom** [comment]
Got it. I missed that part. I've merged your PR.
