### ISSUE TITLE
Thumbnails of the save slots are cropped on iOS

### ISSUE THREAD

**Issue by lee-yunseok** [renpy/renpy#1743]
Thumbnails are cropped on iPhone 6s Plus

Built with Ren'Py 7.1.3.1092

**Comment by renpytom** [comment]
I'm not able to repeat this on the iPhone 6S simulator. Can you take a screenshot of the problem, and take the logfile of Ren'Py running on the device.

Thanks.

**Comment by lee-yunseok** [comment]
Screenshot is here. But how can I get the  logfile in real iphone?

![img-1523](https://user-images.githubusercontent.com/5509466/53966912-7eed5300-4137-11e9-8692-7797703039e3.png)

**Comment by renpytom** [comment]
It's kicked out to Xcode when you run the app under xcode.

**Comment by lee-yunseok** [comment]
After many tries with each different settings I gave up.

Because the iPhone 6s plus is different from other devices, renpy take screenshot then the screenshot is always cropped.

iPhone 6 Plus and 6s Plus has different pixels between rendered and physical. As my attached above, any photos or screenshots from the device has 2208x1242 rendered pixels using factor scale. But the physical pixels on device has 1920x1080 with downsample after rendered 2208.

So renpy takes 1920x1080 screenshot from bottom-left to top-right, as a result, the file is saved as if it were cropped. I think this is not Ren'Py's fault if in other iphone devices has no problem with screenshot.
