### ISSUE TITLE
iOS build crashes due to outline scaling

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#1749]
When building and running the current prerelease 7.1.4 on iOS, the game crashes as soon as the main menu appears. This is the last message in the debug window:

AttributeError: 'renpy.styledata.styleclass.Style' object has no attribute 'outline_scaling'

This happens at runtime, just as the main menu is appearing. I hear the menu music start and then the app immediately closes.

The game plays fine when launched from the launcher.

**Comment by renpytom** [comment]
I just rebuilt everything. Can you update (It'll now be 7.2.0), and try it again?

**Comment by rdurfee** [comment]
I just tried 7.2 pre.  I got the same crash.

**Comment by rdurfee** [comment]
I deleted the xcode project and re-built it and it works, so I guess it's something with the upgrade?

**Comment by renpytom** [comment]
Oh, no - I think that's normal - you have to do that when you upgrade Ren'Py.
