### ISSUE TITLE
ProbablyCake - Dialogue bleep makes game Lag

### ISSUE THREAD

**Issue by ProbablyCake** [renpy/renpy#1760]
Hi Tom, thanks for taking the time to check this out.

So as mentioned earlier, the game lags only when the character dialogue has bleeps. Without sound it's fine...

I've modified the project to show to scenes with custom animations to demonstrate to you the problem. 

Edit: Updating downloading link to include the necessary audio files needed to run project:
https://www51.zippyshare.com/v/Ei7iVGki/file.html

if zippyshare doesn't work, here's a github link:
[Unioncopy.zip](https://github.com/renpy/renpy/files/2948108/Unioncopy.zip)

Thanks

**Comment by ProbablyCake** [comment]
https://www57.zippyshare.com/v/Z8A0eMtk/file.html

As it turns out the debug version of the game I sent you was missing the main menu theme, sorry about that, if you do not have access to the game menu I've attached the link in this comment. Simply direct mainmenu.wav into game/sound/music

Sorry for the inconvenience

**Comment by renpytom** [comment]
Closing this, since I wasn't able to repeat it. Thank you for the work you did putting this example together.
