### ISSUE TITLE
Xcode PRODUCT_NAME is set to the folder name not the display_name

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#1762]
When creating the Xcode project, RenPy sets the $PRODUCT_NAME to the project's folder name. RenPy should set it to **build.display_name** or **config.name** if they are set.

Also the version is not updated to be the value in **config.version**.

It would also be nice if you could create an image for the app icon similar to Android, and have it create the proper icon assets based on that image.

**Comment by renpytom** [comment]
This will be fixed in 7.2.1.
