### ISSUE TITLE
The tutorial dialogues and examples do not match.

### ISSUE THREAD

**Issue by lee-yunseok** [renpy/renpy#1763]
Translating **Transforms and Animation**. However the tutorial dialogues and examples does not match. Also please check this five>four: https://github.com/renpy/renpy/pull/1722/commits/e9afa2be3cca65352a6cee515913f204261fb3d5

It seems that example was five lines of code in the past.

![renpy_tutorial_dialogue](https://user-images.githubusercontent.com/5509466/54094362-9c464980-43e3-11e9-9bb5-35816fcd9b95.png)

**Comment by renpytom** [comment]
I don't believe this is a problem. This doesn't count the image statement itself as a line of ATL. So the second and fourth lines are the pause statements. 

There are five lines total:

```
1.        "eileen vhappy"
2.        pause .5
3.        "eileen happy"
4.        pause .5
5.        repeat
```

**Comment by renpytom** [comment]
(The last two lines are hidden, but the scrollbar shows they're there.)

**Comment by lee-yunseok** [comment]
Checked it. I have not seen the scrollbar before. Thank you for confirm.
