### ISSUE TITLE
In show at Position, ypos is ignored if user is skipping text

### ISSUE THREAD

**Issue by MrTAToad** [renpy/renpy#1764]
When the player is skipping text, characters that are moving can have their vertical position modified when they shouldn't be

**Comment by renpytom** [comment]
Do you have any examples of this? It's possible in certain circumstances (like if something is moving, and you skip to a transition where it is not, without finishing the move). But that's a behavior, and not a bug.

**Comment by MrTAToad** [comment]
Unfortunately I don't now, as I stopped it all by putting in pauses
