### ISSUE TITLE
Console issue

### ISSUE THREAD

**Issue by zedraxlo** [renpy/renpy#1767]
There is a bug with console.
Steps to reappear:
- Start project "The Question"
- Press "Start"
- Skip to somewhere
- Press "Shift+O" to open console
- Input "jump marry"
- Wait jump finish
- Press "Shift+O", console not being open, but game rollbacked to where last time open console.

**Comment by renpytom** [comment]
A very weird bug - turned out that we were never running the proper jump function. It's fixed now.
