### ISSUE TITLE
Variable is not defined unless I use 'init python'

### ISSUE THREAD

**Issue by mcoirad** [renpy/renpy#1770]
Possibly related to #1198 . Did that get resolved?
I've got some code that doesn't work:
```
label start:
    default test_var = 1

    call test_scene

    return

label test_scene:

    # This does not work
    image test_image = ("/path/image_name" + str(test_var) +").png")
```

On the other hand this works:
```
init python:
    test_var = 1

# The game starts here.

label start:

    call test_scene

    return

label test_scene:

    # This now works
    image test_image = ("/path/image_name" + str(test_var) +").png")
```

However, its not a solution because this is a variable I want to save, and I don't want to overwrite it at the beginning of every game.

**Comment by renpytom** [comment]
This isn't a bug in Ren'Py. The image statement run at init time, while the default statement runs at game start. As a result, the image statement runs after the default statement, and you get this bug. 

I'd consider using a DynamicImage here:

```
default test_var = 1
image test_image = "/path/image_name[test_var].png"


label start:

    call test_scene

    return
```

**Comment by mcoirad** [comment]
Thanks for the help!

I just want to note for whoever comes next that the above code fixes the problem, but that using the "+" method of concatenation like I did originally can also be a source the undefined error.

```
default test_var = 1
image test_image = "/path/image_name" + str(test_var) + ".png"


label start:

    call test_scene

    return
```
