### ISSUE TITLE
renpy.show can't find images depending on the folder depth.

### ISSUE THREAD

**Issue by lee-yunseok** [renpy/renpy#1771]
I have a problem with display the image.

Images on **dlc/first/images/**

1. Images are defined randomly(random_img) so I didn't define the image with absolute path.
2. expression can show the image but it can't unlock the gallery.
3. So I using **renpy.show** but it can't found the image depending on folder depth.

How can Ren'Py find images in the **dlc/first/images/** using renpy.show?

**Comment by vollschauer** [comment]
I would recommend using the forum with a proper example...

**Comment by lee-yunseok** [comment]
@vollschauer Because I think this is a bug. If the image exists in **dlc** then **renpy.show** can find and display it but **dlc/first/images** is can’t find image even if I write full path like this;

$ renpy.show(‘dlc/first/images/1.webp’)

**Comment by renpytom** [comment]
Not a bug. renpy.show doesn't take image filename in the image name argument.

**Comment by lee-yunseok** [comment]
@renpytom Thanks for the answer. I will have to try another way.
