### ISSUE TITLE
Follow Shortcuts in Launcher

### ISSUE THREAD

**Issue by zombiepigdragon** [renpy/renpy#1773]
In a lot of programs with a Launcher screen like Ren'Py, where the list of projects is determined by reading a folder, shortcuts are followed, allowing users to store specific projects in alternate locations. Is there a way to do this? If not, I (probably) can add the ability to do this.

**Comment by vollschauer** [comment]
When a file named projects.txt is present in the projects directory, it is expected to contain a list of full paths to directories, one per line. Those paths are treated as projects and displayed in the launcher.

https://www.renpy.org/doc/html/changelog.html#id26

**Comment by zombiepigdragon** [comment]
Okay, thanks! IMO, that feature should be mentioned in the launcher somewhere, I didn't realize it was a thing until you posted that.
