### ISSUE TITLE
Different var for predicting and showing

### ISSUE THREAD

**Issue by mal** [renpy/renpy#1775]
In `resolve_say_attributes` there is both a `new_image` and a `show_image` variable. `new_image` is used for predicting, but `show_image` is used for showing. I think `show_image` can be removed in favour of `new_image` to simplify the code slightly, but not 100% so thought I'd flag it just in case.

https://github.com/renpy/renpy/blob/210935c4c61db3abe44fe0531c354332eec769d2/renpy/character.py#L885-L905

**Comment by renpytom** [comment]
This is, as best as I can tell, invalid. 

The two variables do different things.``new_image`` is the image being shown, ``show_image`` is the set of attributes used to show it. This is different when the two images differ.

It does look like predict_show should take ``show_image``, so I'm making that change.

**Comment by mal** [comment]
Fixed by https://github.com/renpy/renpy/commit/e623134867ae4c4073e2ef457d878f63bafe6065.
