### ISSUE TITLE
Requests work on iOS?

### ISSUE THREAD

**Issue by lee-yunseok** [renpy/renpy#1778]
In 7.1.3.1092 import requests is work on iOS with news system(Not update but it worked),
But 7.2.1.457 it is not working on iOS, both simulator and physical device.

The program crashes after showing the launchimage.

**Comment by renpytom** [comment]
I have rebuilt iOS for 7.2.2, and tested that it works in the simulator.

**Comment by lee-yunseok** [comment]
It also works in real iPhone.
