### ISSUE TITLE
Various Ren'Py Games Open on Wrong Monitor On Linux

### ISSUE THREAD

**Issue by Simmonz** [renpy/renpy#1779]
I have two multi monitor setups on Linux and every RenPy game I have tried in recent months have always opened on my right monitor. The issue is my main monitor is on the left. It is properly set as my primary monitor but RenPy games always want to open on the right monitor and always go to the right screen when set to fullscreen. I can't find any way to set which monitor to use in the config files. 

This has happened on 2 of my systems. These 2 use different distros, kernels, Mesa versions, and CPU. On my wife's Windows 10 system RenPy games always opens on her primary monitor regardless of which side it is on. 

I have had the issues with The Last Birdling, Con-Amore, Blind Love, and Amplitude. All made by different developers but all using Ren'Py. I'm not sure of what to do except switch my monitor setup orientation every time I want to play a Ren'Py game which I would rather avoid.

Games using Unity, Unreal 4, Godot and various other engines don't seem to give me this issue so while it is an OS issue, as it only happens to me on Linux,  it is specific to the Ren'Py engine.

My system specs:

AMD Ryzen 5 2600X | 16GB DDR4-3000 CL15 | MSI RX 580 8GB Gaming X | Mesa 18.3.4 | Manjaro 18.0.4 | Mate | Kernel 5.0.1-1-MANJARO

AMD X3 710 | 6GB DDR3-1333 | MSI Radeon HD5450 1GB | Mesa 18.2.8 | Linux Mint 19.1 | Mate | Kernel 4.18.0-16.generic

**Comment by renpytom** [comment]
Can you please check out the latest version of Ren'Py (the SDK) to see if the problem still persists? There was a change to the fullscreen mode, so maybe that helps. 

Fundamentally, though, I'm not sure if there's anything I can do here. Ren'Py just asks the OS to place it on the screen, and then it's up to the OS to decide where it goes.

**Comment by Simmonz** [comment]
> Can you please check out the latest version of Ren'Py (the SDK) to see if the problem still persists? There was a change to the fullscreen mode, so maybe that helps.
> 
> Fundamentally, though, I'm not sure if there's anything I can do here. Ren'Py just asks the OS to place it on the screen, and then it's up to the OS to decide where it goes.

So good news, I tried launching the "question" game from the SDK for Ren'Py version 7.2.1 and it launches on the correct monitor. So it was a bug with the engine but it got patched either with the most recent update or sometime prior. So hopefully going forward as developers update their engine it won't be an issue. Thanks for the suggestion and the help.
