### ISSUE TITLE
Improvement: Edit Directory

### ISSUE THREAD

**Issue by Klaim** [renpy/renpy#1787]
In addition to all the Edit buttons, it would be useful to have a Edit Directory button that simply (if possible) send the directory path to the current editor.
Using VS Code as an example: "code path/to/project/root/dir".

This would be a shortcut to edit the project as a workspace.
It's of course a minor issue but that would help having to open the directory separately or click on "base" then right click to open the editor in that directory.
The "All script files" is similar with the difference that I need to see more than the script files so the simplest way is to open the directory directly in the editor.

Of course this is a super minor improvement. Thanks for your excellent work!

**Comment by rdurfee** [comment]
If you use one of the supported editors, like Atom, there is a "Open Project" link which does this. It would be awesome if this was supported with Visual Studio Code.

**Comment by Klaim** [comment]
I didn't know that, probably because I mainly use VSCode by using the "System Editor". As you say if it was supported like the other editors it would work indeed.

**Comment by renpytom** [comment]
With the new VS Code support, this can be closed.
