### ISSUE TITLE
Documentation improvement: Include supported Python version

### ISSUE THREAD

**Issue by makusu2** [renpy/renpy#1789]
I've been looking, and I can't figure out what version of Python I can use in python code blocks. It'd be really helpful to have that somewhere easily accessible.
Note: I'm not referring to the python version used in design of Ren'Py, I'm referring to the syntax that I'm allowed to use; for example, await/async.

**Comment by renpytom** [comment]
It's Python 2.7.

**Comment by makusu2** [comment]
Ah, thank you! It would still be nice to include it in the documentation, for future users.

**Comment by renpytom** [comment]
I agree. Done.
