### ISSUE TITLE
vcentered problem

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#179]
I added the below line to testcase.
vcentered "{font=mikachan.ttf}あ あ あ あ{/font}"
But it had typographic error.

![screenshot0001](https://f.cloud.github.com/assets/1556311/1365364/82e54d54-385b-11e3-9a1d-bb2874ceed82.png)
![sss](https://f.cloud.github.com/assets/1556311/1365379/768c581c-385c-11e3-96f8-487adf56f223.png)

**Comment by renpytom** [comment]
I don't think there's a good way to improve this, so closing the issue.
