### ISSUE TITLE
build.classify

### ISSUE THREAD

**Issue by nullwanton** [renpy/renpy#1805]
OS dependant folder's have stopped working, as far as the latest windows 10 goes, unless it's just my install.. if you want multiple folder with different image types, during a build,, like

    build.classify('game/images/android/**.**', 'android')
    build.classify('game/images/x86-x64/**.**', 'windows linux')

on the latest version of windows, both folder's are included, whether you are building a android, or windows version

it used to work fine, but i never bother updating windows 10 for 6 months for something, and now its it does'nt work

**Comment by renpytom** [comment]
I don't know what caused this, but it's working in 8.0.
