### ISSUE TITLE
First dialogue duplicated in translation if replay starts in NVL mode

### ISSUE THREAD

**Issue by npckc** [renpy/renpy#1806]
First dialogue duplicated in translation if replay starts in NVL mode.

Attached file: 
In "None" language, if you select Replay Start, the first text is not duplicated. 
In "Test" language, if you select Replay Start, the first text is duplicated.

[nvltest.zip](https://github.com/renpy/renpy/files/3126947/nvltest.zip)

**Comment by renpytom** [comment]
I fixed this one a while back.
