### ISSUE TITLE
RenPy uses the old SDL controller database and database format

### ISSUE THREAD

**Issue by daggerstab** [renpy/renpy#1816]
SDL has changed their controller database format in version 2.0.6 and it uses a different way to generate device GUIDs. This means that it's impossible to update the copy of the controller mappings database packaged with RenPy with the latest version from https://github.com/gabomdq/SDL_GameControllerDB.

For comparison, RenPy's gamecontrollerdb.txt contains about 90 entries, while the latest one on Github contains about 400.

**Comment by renpytom** [comment]
This has been resolved in the Ren'Py 7.4. series. It looks like we're on an update gamecontrollerdb.txt, too.
