### ISSUE TITLE
SL2 keyword to expose underlying displayable instances

### ISSUE THREAD

**Issue by mal** [renpy/renpy#1830]
This proposal is for a new SL keyword: `as`. The concept for it is to expose instances of displayables produced by SL2 to the local screen scope for direct manipulation.

A simple use case for this is creating a buttons to change the elevation of the current `drag`, as shown below, however it opens up new possibilities across all displayables.

```renpy
screen items(value):
    drag as mydrag:
        hbox:
            text value
            textbutton 'move to top' action Function(mydrag.top)
            textbutton 'move to bottom' action Function(mydrag.bottom)
```

**Comment by renpytom** [comment]
f360a53edaee1a5bb715c408fe80709efef0c82a and 37c4fb3f4ba819f231c7472487f0af5ce1dd0a5c fix  this.

**Comment by mal** [comment]
This is super cool, thanks Tom! Will be having a play around with this later today! 😁
