### ISSUE TITLE
"show text" is not scanned for translation

### ISSUE THREAD

**Issue by Beuc** [renpy/renpy#1848]
Hi,

AFAICS this line:
```
show text "Hello!"
```
is not scanned for translation.
A work-around:
```
$ hello = __("Hello!)"
show text "[hello]"
```
I was wondering if this was by design or if this should be fixed?

**Comment by renpytom** [comment]
```
show text _("Hello") 
```

works for this reason, and should cause the translation to occur. That being said, modern games should just use screen language for this sort of thing.

**Comment by Beuc** [comment]
That makes sense, thanks!
