### ISSUE TITLE
Rollback sometimes forgets Positions

### ISSUE THREAD

**Issue by mal** [renpy/renpy#1852]
Time for a properly weird one. If a `say` statement applies an image attribute immediately after (i.e. no transition or other rollback entry) a `show ... at ...` statement using a `Position` not pre-defined by Ren'Py, reload and rollback forget the image's positioning.

~~That `tc = truecenter` seems to function fine, while `tc = Position(align=(.5, .5))` seems like the oddest part of this particular issue.~~ This appears to be down to `truecenter` being an `ATLTransform` rather than a `Position`. Using a creator defined transform does not yield the behaviour reported here. Verified other types of `Transform` work as intended.

Seeing this on a clean untar of `7.3.0.200-pre`.

```renpy
label main_menu:
    $ _confirm_quit = False
    return

image box = Solid('f37', xysize=(320, 240))
image box y = Solid('ff7', xysize=(320, 240))

define box = Character('Box', image='box')

# define tc = truecenter # works fine
# define tc = Transform(xalign=0.5, yalign=0.5) # works fine
# transform tc: # works fine
#     align (.5, .5)
define tc = Position(xalign=0.5, yalign=0.5) # breaks on rollback/reload

label start:
    show box at tc
    box y 'Yellow box in truecenter of screen.\nReload now and it\'ll lose positioning ...'
    '... or rollback now, and see positioning get forgotten.'
    return
```

**Comment by renpytom** [comment]
Position is obsolete and undocumented, so I don't think there's an issue here.

**Comment by mal** [comment]
Ah, wasn't aware of that, all good then 👍
