### ISSUE TITLE
Menu with speaker - speaker side image, name, and caption does not save/load

### ISSUE THREAD

**Issue by hybridfurie** [renpy/renpy#1861]
To reproduce as of 7.2.2.491, change line 43 of The Question script.rpy
from:
        `"As soon as she catches my eye, I decide..."`
to:
        `s "As soon as she catches my eye, I decide..."`

Save when choices appear, you'll be able to see caption, name, and choices (you would also see a side image if one was assigned to the character)

Load (seems to occur for both quicksave/quickload and save/load)
Choices will be loaded but name and caption will not (nor will the side image if it was assigned to the character).

If you save/load with a caption but without a speaker (as in the original code), the caption loads correctly.

**Comment by renpytom** [comment]
Fixed. You'll have to click "Force Recompile" after you update Ren'Py.
