### ISSUE TITLE
7.3 Prerelease RAPT install fail loop

### ISSUE THREAD

**Issue by RenpyRemix** [renpy/renpy#1866]
System:
Windows 10 with the 64bit JDK 8 already installed.

A couple weeks ago I built an apk (likely in 7.2.2) successfully then had a drive seize and lost the renpy sdk folder. Re-installed Ren'Py, upgraded to the 7.3 pre-release and tried another apk build...

The Launcher does the "... need to download RAPT" bit 
click 'Yes'
download runs 
(the folder ./rapt/ appears alongside the usual folders in the renpy-sdk folder)
Launcher restarts...
Click [Android] and it begins the "... need to download RAPT" bit... again.

I've tried deleting the rapt folder, same thing

If you cannot replicate it, feel free to ping me on Discord - Remix#1655

**Comment by renpytom** [comment]
Did you upgrade the prerelease before this happened? I think you might get this if the launcher and rapt are out of sync with each other.

**Comment by RenpyRemix** [comment]
It was basically a clean install of 7.2.2 followed by upgrade to a nightly for a few days then upgrade to the 7.3 prerelease.

**Comment by renpytom** [comment]
Can you try installing the current 7.3 directly? I can think of path dependencies that will fix.

**Comment by RenpyRemix** [comment]
That has got past the RAPT part ok... and after some minutes... apk build is ok and tested

**Comment by renpytom** [comment]
Okay. I'm going to close this, then. 

My feeling is thar what happened is I updated the Ren'Py prerelease past the version you had. When Ren'Py downloaded rapt, it would check the hash against your version, and they wouldn't match.  I suspect that updating Ren'Py to the newer prerelease and then installing rapt probably would have made things work, though it's hard to know for sure.
