### ISSUE TITLE
JPEG2000 with Alpha support

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1877]
Similar to https://github.com/renpy/renpy/issues/1643 but I am looking for JPEG2000 specifically lossy compression (to save space) and alpha channel so I can use it in sprites.  At least until RenPy supports animated files which support alpha channels like APNG or others here https://www.digitalrebellion.com/blog/posts/list_of_video_formats_supporting_alpha_channels

**Comment by renpytom** [comment]
I don't have plans to add this format. Similar to #1643, I look to see the popularity of a a format, considering the adoption in tools like image editors and web browsers. Jpeg 2000 doesn't have any adoption, and so I have no plans to support it. 

I'd suggest looking at .webp, which supports the same things, and is supported.
