### ISSUE TITLE
gallery unlock_image does not unlock all images

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1887]
On https://www.renpy.org/doc/html/rooms.html?highlight=gallery#Gallery it states 

    # The final two buttons contain images that show multiple pictures
    # at the same time. This can be used to compose character art onto
    # a background.
    g.button("dawn mary")
    g.unlock_image("dawn1", "mary dawn wistful")
    g.unlock_image("dawn1", "mary dawn smiling")
    g.unlock_image("dawn1", "mary dawn vhappy")

So what I am doing is something similar, but I am getting that the images are locked.  But according to the documentation `unlock_image` should automatically unlock them

I tried to work around it like this

    g.button("dawn mary")
    g.image("dawn1", "mary dawn wistful")
    g.image("dawn1", "mary dawn smiling")
    g.image("dawn1", "mary dawn vhappy")
    g.unlock("dawn1", "mary dawn wistful")
    g.unlock("dawn1", "mary dawn smiling")
    g.unlock("dawn1", "mary dawn vhappy")

But I got the 3rd image is locked

**Comment by renpytom** [comment]
Could you use shift+O to go to the console, and then run:

```
renpy.seen_image("dawn1")
renpy.seen_image("mary dawn wistful")
```

Or better yet, please post your actual code, as you can't expect me to support something in the absctract like this.

**Comment by trajano** [comment]
I tried to do the better one.  To test the scenario just go to "Gallery" on the main menu.  Then click on a picture of the sword.  I am more thinking it's just an off-by-one bug in Ren'Py.

**Comment by trajano** [comment]
Doing this 
```

    g.unlock_image("bg holodeck", "sword")
    g.unlock_image("bg holodeck", "sword aim")
    g.unlock_image("bg holodeck", "sword fire")
```
disables the button (because it thinks the image is locked)

**Comment by trajano** [comment]
![image](https://user-images.githubusercontent.com/110627/59568130-8a102300-9044-11e9-906e-bc59efe8dce5.png)

**Comment by renpytom** [comment]
Okay, now please try in the console, 

```
show bg holodeck
show sword aim
renpy.seen_image("bg holodeck")
renpy.seen_image("sword aim")
```

**Comment by trajano** [comment]
I think something broke, this worked a few minutes ago
![image](https://user-images.githubusercontent.com/110627/59568320-10c5ff80-9047-11e9-8254-90465fd2d3ef.png)

**Comment by renpytom** [comment]
You'll need to run the game to use the show commands.

**Comment by trajano** [comment]
I'm pretty sure I am running the game, that screenshot above is only possible when I do Shift-O.  I tried restarting RenPy already and recompile everything.  Let me reboot maybe something's stuck.

**Comment by trajano** [comment]
Just rebooted.  No luck.  I'm pretty did see those `show` commands working at one point.

**Comment by trajano** [comment]
I have to "Start" the adventure for it to work.  I was doing it as soon as I started up the game.  Here's the output

![image](https://user-images.githubusercontent.com/110627/59568410-4f0fee80-9048-11e9-9afe-d1f5ce33a14c.png)

**Comment by renpytom** [comment]
I took your example, changed gallery_init.rpy to be:

```
init python:
    g = Gallery()

    g.button("sword")
    g.unlock_image("bg holodeck", "sword")
    g.unlock_image("bg holodeck", "sword aim")
    g.unlock_image("bg holodeck", "sword fire")

    g.transition = dissolve
```

And then changed script.rpy to be:

```
label start:

    scene bg holodeck
    show sword aim

    # These display lines of dialogue.

    e "You've created a new Ren'Py game."

    e "Once you add a story, pictures, and music, you can release it to the world!"

    # This ends the game.

    return
```

When I did this, the game unlocked the appropriate image and worked normally.

**Comment by renpytom** [comment]
(I did need to play through once to trigger the unlock.)

**Comment by trajano** [comment]
I made the changes you did.  When I went to the gallery I got this for the first image

![image](https://user-images.githubusercontent.com/110627/59568481-29cfb000-9049-11e9-9a2f-2cd134b8a922.png)

The other two work fine.

**Comment by trajano** [comment]
When I did this for the script. It worked.
```
    scene bg holodeck
    show sword
    pause
    show sword aim
    pause
    show sword fire
``` 
But that still does not address the `unlock_image` problem.

**Comment by renpytom** [comment]
What's the problem now, in words? From what I can see, it seems to be working correctly.

**Comment by trajano** [comment]
I don't want to go through the game to unlock the images. I just want to go to gallery immediately.

**Comment by renpytom** [comment]
Oh, in that case just leave unlock out entirely. If you do:

```
    g = Gallery()

    g.button("sword")
    g.image("bg holodeck", "sword")
    g.image("bg holodeck", "sword aim")
    g.image("bg holodeck", "sword fire")

    g.transition = dissolve

```

Then they'll all be unlocked by default.

**Comment by trajano** [comment]
OHHH!!!!
Then this example

    # A button that contains an image that automatically unlocks.
    g.button("dawn")
    g.image("dawn1")
    g.unlock("dawn1") ### THIS NEEDS TO BE REMOVED

Because I was thinking I needed to unlock them.

**Comment by renpytom** [comment]
Yep. Everything working now?

**Comment by trajano** [comment]
Or maybe change the text to say 

> A button that contains an image that automatically unlocks when it was seen (this is stored in the Persistent data)

Then add another example above it.

```
# A button that contains an image (there's no lock and will always be available)
g.button("dawn")
g.image("dawn1")


```

Closing now since I know how it works.  It's just the documentation could have some improvement.

**Comment by trajano** [comment]
I'll probably add another bug for a slightly more complex example.  My objective for this bug was to just wanted to show something regardless whether it is seen or not.

So the scenario is "what if I want the holodeck background, which is only in the gallery but not hit in game" but I still want the transparent images locked.

**Comment by renpytom** [comment]
You can can write:

```
    g.button("sword")
    g.image("bg holodeck", "sword")
    g.unlock("sword")
```

to condition it on a single image.

**Comment by trajano** [comment]
Hmm  I should try that too.  In the end I cheated by doing 
`scene bg holodeck` at the label start: but it gets wiped shortly after.
