### ISSUE TITLE
Update Ren'Py statements parse to use catch_error

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#1895]
This means improving all statements so that they use Lexer.catch_error to output as many parse errors as possible per statement at a time.
This is a long task as each statement must be treated individually.

**Comment by renpytom** [comment]
No. 

We mostly don't want this. Error handling in a parser is a complex thing, but we really don't want a single mistake to produce a lot of errors for a single statement. That'll just produce tons of spurious errors, for very little benefit, and will likely produce a lot of frustration for the user.
