### ISSUE TITLE
`slow_done` event does not change the animation

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1904]
I created two animations.  One to represent talking the other to represent being quiet.  The "show" event works correctly and changes the animation, but the "slow_done" event even if it is fired (according to the logs) does not change the animation for the character
```
init python:
     def callback(event, interact=True, **kwargs):
        renpy.log(event)
        
        if event == "show":
            renpy.show("sword fire")
        elif event == "show_done":
            pass
            # renpy.show("sword aim")
        elif event == "slow_done":
            renpy.show("sword aim")
 
define e = Character("Sword", callback=callback)
```

**Comment by renpytom** [comment]
Can you try renpy.restart_interaction() after renpy.show ? At the minimum, you'll need this to cause the screen to update.

**Comment by trajano** [comment]
To be more precise, add `renpy.restart_interaction()` in the "slow_done" event.

```
        elif event == "slow_done":
            renpy.show("sword aim")
            renpy.restart_interaction()
```

And yes it works.

**Comment by trajano** [comment]
I am thinking it should be noted somewhere in https://www.renpy.org/doc/html/character_callbacks.html
