### ISSUE TITLE
Saves and console and label flow bugs

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#1905]
Glitches on the display of the saves :
![Screenshot_33](https://user-images.githubusercontent.com/44340603/60119771-86387b00-977f-11e9-8ac2-c8082e7651e1.png)
Doesn't appear on every game (The Question works fine for example) but on some, this glith appears but only when launched from Renpy version 7.3.0 (and not from version 7.2.2 for example).
![Screenshot_34](https://user-images.githubusercontent.com/44340603/60125961-32cd2980-978d-11e9-9ff9-cbc7a911922b.png)
Here is a comparison between my game launched with Renpy 7.2.2 (top) and with 7.3.0 (bottom).
If you want to make it appear, you can launch Witch Trainer Silver Edition with Ren'py 7.3.0 and compare.

There is also a glitch with the console, when you call a label or perform a rollback from the console, you close it and you hit Shift+O to get it again, it seems like the game doesn't call the console, gets back where you first called the console but without reverting all the variables to their original values. Thus corrupting the save, sometimes permanently.

**Comment by renpytom** [comment]
I'm going to need you to present a game, with included source code, where I can repeat this. Otherwise, there's not much I can do to fix the problem.

**Comment by renpytom** [comment]
https://lemmasoft.renai.us/forums/viewtopic.php?p=513850#p513850

Seems to be related, and has a demo game included.

**Comment by Gouvernathor** [comment]
Sorry, haven't thought of it. Here is an exported alpha version of the game I'm developping (where I spotted the glitch.
https://mega.nz/#!yRphnACR!FEjkYkjEaWFFqb1kcxWbdDShv-YAkVbHq1G6Hl3EFPY
Note that the save glitch happens when you launch from Renpy 7.3.0, but not when you launch it separately. This might be because it was exported with 7.2.2, but I'm not sure about that last bit.

**Comment by Andykl** [comment]
Yes, it's relaited to lemma topic.
A smaller version of the code where it repeats.
```
label main_menu:
  $_confirm_quit = False
  return

screen pages:
    vbox:
        align (0.5, 0.5)
        spacing 50
        hbox:
            spacing 50
            for i in range(4):
                fixed:
                    xysize (100, 100)
                    imagebutton:
                        focus_mask True
                        idle "#022"
                        hover "#042"
                        action Return()
                    text "[i]" align (0.5, 0.5)
        hbox:
            spacing 50
            for i in range(4):
                fixed:
                    xysize (100, 100)
                    imagebutton:
                        focus_mask True
                        idle "#022"
                        hover "#042"
                        action Return()
                    text str(i) align (0.5, 0.5)

label start:
    call screen pages
    return
```

**Comment by Andykl** [comment]
This is caused by b762b5267ca6be51a82c10908ba7e053f0f28f86
