### ISSUE TITLE
multiple 4k movie sprites terminate game without traceback

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1908]
I was attempting instead of having two different set of movie sprites for full body vs close up, I was just going to use one large one and just use the transforms to pick and choose the parts I want to show and animate the transition so it looks like it is zooming it from far to close up.

To do this, I use 4K portait sized (1920x2160 resolution) movies.  Just to test the limits of Ren'py.

When I attempted to use this, the game just crashes.  It's likely a memory issue, but generally Ren'py gives a traceback for errors before.  However, in this specific scenario it just terminates with no trace back or log message.

**Comment by renpytom** [comment]
It tries, but it's not invincible. I'm not going to treat this as a bug.

**Comment by trajano** [comment]
It's more of a nice to have, since it saves having to render two sets but if it can't be done then it can't be done.

Mind you I am running on a PC with 32GB of RAM and a GTX 1060 video card,

**Comment by renpytom** [comment]
And none of that matters, since on Windows you're limited to 2GB, because Ren'Py isn't a 64-bit app yet.

**Comment by trajano** [comment]
Oh! I didn't realize that Ren'py wasn't 64-bit.  That changes a few design decisions then.

**Comment by trajano** [comment]
Anyway I'll continue the threada on the forum https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=55795&p=513867#p513867
