### ISSUE TITLE
renpy.display.anim not documented

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1912]
I noticed that the `renpy.display.anim` module is not documented in https://www.renpy.org/doc/html/py-function-class-index.html is it going to be deprecated and removed in future releases?

Just asking because I implemented https://lemmasoft.renai.us/forums/viewtopic.php?p=514125#p514125 which uses the APIs in that module.

**Comment by renpytom** [comment]
It's retained for compatibility with older programs, but I'd recommend not using it in newer designs. Should we have a major compatibility break - like moving to a Python 3 Ren'Py - I may consider removing it.
