### ISSUE TITLE
layeredimage leaks RevertableLists into the script AST

### ISSUE THREAD

**Issue by CensoredUsername** [renpy/renpy#1914]
`RawLayeredImage.children` is a `RevertableList`, as well as `layeredimage.RawConditionGroup.conditions`. Both of these end up in the stored script AST, which previously never contained any `RevertableList` instances.

**Comment by renpytom** [comment]
Sure, this is a side effect of the changes to UserStatement. I don't believe this matters, though.

**Comment by CensoredUsername** [comment]
Fair enough, I wasn't sure if it was intended.
