### ISSUE TITLE
7.3.1.311 Launcher - Open Directory not working on Win 10 ... and

### ISSUE THREAD

**Issue by RenpyRemix** [renpy/renpy#1917]
As the topic states:

Windows 10
Ren'Py Version 7.3.1.311

None of the buttons to open folders seem to work (e.g. Open Directory - game / base / images / gui)
Preferences no longer has [ ] Console Output checkbox (if it's ON by default, that suits me fine)

I have tried a system restart, no luck there...

**Comment by renpytom** [comment]
Question: Could you have RENPY_VARIANT or RENPY_EMULATOR set?

**Comment by RenpyRemix** [comment]
I'd only know how to do those on a per project basis (environment.txt in the game folder iirc) and do not (as yet) use them anywhere...

Nothing changed (other than a few simple lines in a few .rpy files) since 7.3 when the Launcher worked fine. (also no recent Windows updates)

Trying to quickly ask in  #social on discord to see if anyone else has this issue.
