### ISSUE TITLE
config.say_attribute_transition broken as of 7.3.0 and later

### ISSUE THREAD

**Issue by StefanGagne** [renpy/renpy#1918]
Attached is a zipped up simple Renpy project which uses say_attribute_transition to have soft dissolves between character facial expressions. Before 7.3.0 these were working, but after it's a hard snap with no transition at all.

[Test.zip](https://github.com/renpy/renpy/files/3348144/Test.zip)

In the game, we have:

init python:
    config.say_attribute_transition = Dissolve(0.5, alpha=True)
    config.say_attribute_transition_layer = "master"

And then expressions are done normally:

sue "Okay, this is my normal expression, arms slack."
sue frustrated "Now I'm frustrated, arms crossed."
sue smug "Now I'm smug, arms slack."
sue displeased "Now I'm displeased, arms crossed."

They work, but the 0.5 second dissolve does not occur.

**Comment by renpytom** [comment]
Fixed in f6029db1.
