### ISSUE TITLE
Composite with movie and Null() displayable on ConditionSwitch does not resolve correctly.

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1920]
(I'll make a tester for this later, because it is a bit complicated)

Here's the concept.
```
image composite mike = Composite(
    (853, 1440),
    (0, 0), "mike body",
    (283, 500), "mike mouth"
)
```

`mike body` is an animation where the person is talking already and I am just going to overlay a "closed mouth" when he is not speaking

```
image mike mouth:
  ConditionSwitch(
    "IsSpeaking('mike')", "mike talking",
    "True",  "mike quiet"
  )
```

When `mike talking` is a displayable which is a set of image frames that I animate as a DynamicDisplayable, it works correctly.  They're 267x91.

I'm trying to remove that displayable since the video is already talking that way I can save on some resources by using `Null()` as 

```
image mike mouth:
  ConditionSwitch(
    "IsSpeaking('mike')", Null(width=267, height=91),
    "True",  "mike quiet"
  )
```

When I do that, the character just keeps on talking.  It does not switch to quiet displayable.  When I check the console IsSpeaking("mike") is already false.   However it does stop once I continue to the next dialog.

**Comment by renpytom** [comment]
ConditionSwitch only evaluates once per interaction, so if you go in expecting it to change when the speaking stops, it probably won't work.

**Comment by trajano** [comment]
I added 
`renpy.restart_interaction()` as per the other bug on `slow_done` that seems to have done it.  I wonder why I had to do that for this case but not before. Anyway closing.
