### ISSUE TITLE
How to execlude file_list from package?

### ISSUE THREAD

**Issue by DinakiS** [renpy/renpy#1925]
For example I want to create a package with an extra content.
```
build.classify('extra/**', 'extra')

build.package('with-extra', 'zip', 'windows linux all extra')
```
How to exclude `extra` from the regular build? Is there something like `windows linux all -extra`?

**Comment by renpytom** [comment]
Closed as a stale support request, but the answer would be. 

build.package("normal", "zip", "windows linux all")
