### ISSUE TITLE
Provide a way of playing PCM data that is stored in memory

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1927]
I'm queueing a bunch of blips and silences together using a function below, but I still find that for really high CPSes, there is still a bit of a gap and from https://github.com/renpy/renpy/blob/master/renpy/audio/renpysound.pyx#L100 it looks like it plays on a per file basis.  

*UPDATED TO MATCH DESCRIPTION*

So I what I am wondering is if we can have Ren'py support playing audio stream data that is stored in memory (no physical temporary files).  I'm presuming `wave` format audio since it is uncompressed and Python has it as part of the standard lib (though it is not present in Ren'py at the moment also note `audioop` is not compiled in Android, but it is present in the PC).

To manage the stream in memory we would use the `io.BytesIO` class as the in-memory I/O.  We can store the PCM data there it'd be up to the developer to implement it as an LRU cache if they want.

I think the change would be somewhere along the lines of

```
def renpy.play(file): 
   if (file is  io.BufferedIOBase):
     play the object
   else:
     # as before 
     load up the file handle and then play
```

*ORIGINAL*

```renpy.build_playable(filenames)``` which will assemble a single file for `renpysound.play`  instead of a queue of files that gets played individually by renpysound.

```
        def queue_blips(who, what, cps):
            """
            Queue the blips.  This creates a blip every other character and resets the blip when a comma or space is detected.
            If the CPS is higher frequency than the blip length, it switches to Wendy Oldbag mode where it just beeps as fast
            as it can.
            """
            tokens = textsupport.tokenize(unicode(what))
            odd = False
            queue = []
            cps_stack = []
            # queue.append("<silence %0.3f>" % (1.0/cps))
            for token_type, token_text in tokens:
                if token_type == TEXT:
                    if cps > (1.0 / blip_length):
                        # Wendy Oldbag Speed at this point assume 0.05 seconds and just keep on playing until it reaches the end of the segment.
                        beeps_needed = int(len(token_text) / cps / blip_length)
                        for i in xrange(beeps_needed):
                            queue.append("<from 0 to %0.3f>%s" % (blip_length, blip_sound))
                    elif cps == 0:
                        pass
                    else:
                        speed = 1.0/cps
                        for letter in token_text:
                            odd = not odd
                            if letter in ', ':
                                queue.append("<silence %0.3f>" % speed)
                                odd = False
                            else:
                                if odd:
                                    queue.append("<from 0 to %0.3f>%s" % (speed, blip_sound))
                                else:
                                    queue.append("<silence %0.3f>" % speed)

                if token_type == TAG:
                    match_cps_multiplier = re.match( r'cps=\*([0-9\.]+)', token_text)
                    match_cps = re.match( r'cps=([0-9\.]+)', token_text)
                    match_close_cps = re.match( r'/cps', token_text)
                    if match_cps_multiplier:
                        cps_stack.append(cps)
                        cps *= float(match_cps_multiplier.group(1))
                    elif match_cps:
                        cps_stack.append(cps)
                        cps = float(match_cps.group(1))
                    elif match_close_cps:
                        cps = cps_stack.pop()
                    odd = False
            renpy.sound.queue(queue, clear_queue=True, tight=True)
```

**Comment by renpytom** [comment]
No. Ren'Py is not going to become a sound editor,.

**Comment by trajano** [comment]
I don't need it to be a sound editor, I just need to make it so that the sound effects work as expected when being queued.

**Comment by renpytom** [comment]
I'd say Ren'Py should be fine playing files of about .25 seconds or longer. IF you want 0.05 second blips, then that's not something Ren'Py can do - we'd have to be opening multiple files per audio callback. 

You were asking to "assemble a single file for renpysound.play". That's something that's outside the scope of Ren'Py.

**Comment by renpytom** [comment]
Ren'Py should already be sample-seamless so long as the queued file is given enough time to load from disk and be partially decoded before it is played.

**Comment by trajano** [comment]
The reason I suggested to assemble a single file is because that seemed to be the simplest solution I can think of.  But yah for short blips the I/O time is killer.  It's not like the images which are in memory for the most part and can just seek. (unless I am missing something).

If you can make it so that it just seeks and such it may be better.  Or if it is small keep it in memory the blips are 0.05 seconds long anyway.  Perhaps an in-memory file.  so if I do a python load file into memory and somehow reference that.

The concept can probably be extended to simple images too say if I want rounded rectangles rather than creating an image that I store, I basically create the image and store it in memory.  But we need a way of referencing this "in-memory files" as part of the rpy code.

**Comment by trajano** [comment]
Actually if we can make it so it is a "native raw" format in memory that way we save on decode time would make things better.  Not sure what that format would be it's not like images which can be a byte stream of RGBA.

**Comment by renpytom** [comment]
I'll reopen it, for the ability to play a python string containing PCM data. Not sure how that will work yet.

**Comment by trajano** [comment]
I don't want ren'py to be the editor if I can avoid it.  what I coded above should be sufficient as it is.  You're sort of doing it already in a way by doing the `<silence>` except for the one part where I specify the file (unless we can have some sort of way of "caching" the decoded PCM stream) because I am playing the same file with perhaps different lengths.

**Comment by trajano** [comment]
But only do it for short sound fx that is no more than 3 seconds.  So we don't blow the memory and does not use `<loop>` because that kinda blows things apart.

**Comment by trajano** [comment]
Perhaps an LRU cache that retains the last 30 (or something configurable) so we don't blow the memory.

**Comment by trajano** [comment]
I think first stage would be get rid of "_silence.ogg" file reading and make it read from some cached version.

**Comment by trajano** [comment]
Python has this library that I can use.  I can try to create a file temporarily using this but I was wondering if there's a way of just keeping it in memory rather than doing more disk IO.  https://docs.python.org/2.7/library/wave.html

**Comment by trajano** [comment]
So code wise it would be something like this
```
import wave
blip = "audio/sfx-blipfemale.wav"
blipwave = wave.open(blip, "rb")

blipwaveframes = blipwave.readframes(blipwave.getnframes())
audio_length = blipwave.getnframes() / blipwave.getframerate()
blipwave.close()

blipout = wave.open("bliptemp.wav", "wb")
blipout.setframerate(blipwave.getframerate())
blipout.setsampwidth(blipwave.getsampwidth())
blipout.setnchannels(blipwave.getnchannels())

seconds = 1.0
gap_byte_length = (seconds *  blipwave.getframerate() - blipwave.getnframes()) * blipwave.getsampwidth() 
gap = b'\0' * int(gap_byte_length)
print ((seconds *  blipwave.getframerate() - blipwave.getnframes()) * blipwave.getsampwidth() )

blipout.writeframesraw(blipwaveframes)
blipout.writeframesraw(gap)
blipout.writeframesraw(blipwaveframes)
blipout.writeframesraw(gap)
blipout.writeframesraw(blipwaveframes)
blipout.writeframesraw(gap)
blipout.writeframesraw(blipwaveframes)
blipout.writeframesraw(gap)
blipout.writeframes(blipwaveframes)

blipout.close()
```

**Comment by trajano** [comment]
Close, but I didn't realize that renpy does not include `wave` :(

**Comment by trajano** [comment]
Hmm this didn't work 
`pip install --target game/python-packages wave`

**Comment by trajano** [comment]
Can we add the wave and chunk standard modules into renpy?

**Comment by renpytom** [comment]
I don't think so. They're pretty simple, so the few users that want them can just copy them from python 2.7 (or whatever version of Python they want.) 

What's more, your approach involves writing a temporary file to disk. That would defeat any caching Ren'Py does, now or in the future, so it's not something I'd want to support. I'm more likely to come up with a way that would let you just load files containing raw samples and play them with Ren'Py. 

Also, github is not a forum. It's a place to track bug and feature requests. Posting 5 times in a single hour, without any intervening responses, is inappropriate.

**Comment by trajano** [comment]
Yah I figured out how to get the two modules in and how to read the file, but there was no "write out to cache" capability that I found in the documentation.  If I can do that, then maybe I can leverage Ren'py's cache.

```
        def queue_blips(who, what, cps):
            """
            Queue the blips.  This creates a blip every other character and resets the blip when a comma or space is detected.
            If the CPS is higher frequency than the blip length, it switches to Wendy Oldbag mode where it just beeps as fast
            as it can.
            """
            computed_blip_file = "cache/%d.wav" % ( hash( (who, what, cps) ) )
            # use cache copy if available
            if renpy.loadable(computed_blip_file):
                renpy.sound.play(computed_blip_file)
                return

            tokens = textsupport.tokenize(unicode(what))
            odd = False

            # ??? how do you write to  cache?
            blipout = wave.open(renpy.file(computed_blip_file), "wb")
            blipout.setframerate(blip_framerate)
            blipout.setsampwidth(blip_sample_width)
            blipout.setnchannels(blip_channels)

            cps_stack = []
            # initial character gap

            def silence(seconds):
                silence_byte_length = seconds *  blip_framerate * blip_sample_width
                return b'\0' * int(silence_byte_length)

            def blip(seconds):
                silence_byte_length = (seconds *  blip_framerate - blip_frame_length) * blip_sample_width
                return blip_frames + b'\0' * int(silence_byte_length)

            # queue.append("<silence %0.2f>" % (1.0/cps))
            blipout.writeframesraw(silence(1.0/cps))

            for token_type, token_text in tokens:
                if token_type == TEXT:
                    if cps > (1.0 / blip_length):
                        # Wendy Oldbag Speed at this point assume 0.05 seconds and just keep on playing until it reaches the end of the segment.
                        beeps_needed = int(len(token_text) / cps / blip_length)
                        for i in xrange(beeps_needed):
                            # queue.append("<from 0 to %0.3f>%s" % (blip_length, blip_sound))
                            blipout.writeframesraw(blip(blip_length))
                    elif cps == 0:
                        pass
                    else:
                        speed = 1.0/cps
                        for letter in token_text:
                            odd = not odd
                            if letter in ', ':
                                # queue.append("<silence %0.3f>" % speed)
                                blipout.writeframesraw(silence(speed))
                                odd = False
                            else:
                                if odd:
                                    # queue.append("<from 0 to %0.3f>%s" % (speed, blip_sound))
                                    blipout.writeframesraw(blip(speed))
                                else:
                                    # queue.append("<silence %0.3f>" % speed)
                                    blipout.writeframesraw(silence(speed))

                if token_type == TAG:
                    match_cps_multiplier = re.match( r'cps=\*([0-9\.]+)', token_text)
                    match_cps = re.match( r'cps=([0-9\.]+)', token_text)
                    match_close_cps = re.match( r'/cps', token_text)
                    if match_cps_multiplier:
                        cps_stack.append(cps)
                        cps *= float(match_cps_multiplier.group(1))
                    elif match_cps:
                        cps_stack.append(cps)
                        cps = float(match_cps.group(1))
                    elif match_close_cps:
                        cps = cps_stack.pop()
                    odd = False
            blipout.close()
            renpy.sound.play(computed_blip_file)
```

**Comment by renpytom** [comment]
Reopening, since I'd like to provide a wayt to do this that doesn't involve the use of undocumented internals.

**Comment by renpytom** [comment]
Closing, now that https://www.renpy.org/doc/html/audio.html#AudioData exists.
