### ISSUE TITLE
config.window = "show" locks up nvl_menu

### ISSUE THREAD

**Issue by methanoliver** [renpy/renpy#1934]
I think this is properly called a bug. Here's a minimal replication example `script.py`, to be dropped into a freshly initialized project on version 7.3.2.320:

```

define narrator = Character(kind=nvl)
define config.empty_window = nvl_show_core
define config.window_hide_transition = dissolve
define config.window_hide_transition = dissolve

define config.window = "show"

image bg red = Solid("#f00")
image bg white = Solid("#fff")

label start:

    scene bg white
    
    "I wish to keep the NVL mode window on screen during scene transitions, 
     while keeping the ability to hide and show it explicitly."
    "The problem is the nvl_menu."
    nvl clear
    "If config.window is None, the window hides on scene transitions
     and show statements, which isn't what I needed."
    show bg red
    "If config.window is 'auto', everything behaves as desired,
     but both window transitions fire when the menu is shown."
    "And if config.window is 'show', nvl_menu locks up, waiting on a transition
     that never happens."

    menu (nvl=True):
        "This is option one.":
            $ var = "one"
        "This is option two.":
            $ var = "two"
    
    "You picked [var]"

    return
```

I did eventually produce a workaround that permitted me to get it to *somewhat* work:
```
define config.window = "auto"
define config.empty_window = nvl_show_core
define config.window_hide_transition = None
define config.window_show_transition = None
define config.window_auto_hide = [ 'menu', 'call_screen' ]
```

Then, I can hide the window with a transition by using `window hide dissolve` / `window auto show dissolve` and achieve most of the functionality I wanted. However, if the menu contains a prompt line and `config.narrator_menu = False`, it will *still* lock up while waiting for a transition that will never run, and some combinations of other configuration parameters can still trigger the same bug while loading a game saved with the menu on screen or rolling back.

Even figuring out that this is what is happening took me an unhealthy amount of time and shotgun debugging, because there's no error message, no trace output, and everything *else* still works, the game is just stuck and the menu never appears for no obvious reason. Unfortunately, I don't know RenPy innards enough to fix it myself and send you a PR.

**Comment by methanoliver** [comment]
Some more information that might help in tracking the root cause down: `config.choice_layer = 'transient'` (or adding a new layer on top with `config.layers` and using that) prevents this example from locking up, even though it doesn't look as expected upon rendering due to the NVL background being duplicated.

**Comment by renpytom** [comment]
Fixed. Sorry about the delay on this, as I first was travelling, and then had some medical issues. 

What wound up happening was that Ren'Py was not being told that the nvl_window provides the text window. It would then call nvl_show_core to show it again, which would remove the menu. The commit above fixes this problem.
