### ISSUE TITLE
Ren'py does not play MONO WAV files

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1943]
I am trying to play a "wav" file in renpy I also tried to put call it directly using

    renpy.play("audio/sfx-blipfemale.wav")

But it does not make a sound.  The audio file does play on VLC.

Checking the data in ffmpeg
```
λ ffmpeg -i sfx-blipfemale.wav sfx-blipfemale.mp3
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'sfx-blipfemale.wav':
  Duration: 00:00:00.05, bitrate: 137 kb/s
    Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 16364 Hz, mono, u8, 130 kb/s
File 'sfx-blipfemale.mp3' already exists. Overwrite ? [y/N] n
Not overwriting - exiting
```

The files are in https://github.com/trajano/MyRenPyTest/tree/wright-blip/game/audio

MP3s and Ogg works fine though.

**Comment by renpytom** [comment]
With a quick look, it seems like wav playback is broken.

**Comment by trajano** [comment]
Actually, it's more like MONO does not work.  I converted it to stereo and it starts to work. 

ffmpeg -i sfx-blipfemale.wav -ac 2 sfx-blipfemale.stereo.wav the code change I referenced should show that it works with stereo files but not mono files.

**Comment by trajano** [comment]
@renpytom it may be a separate thing, but do you want me to create a separate bug to track WAV playback on Android does not work (even with the stereo files) do you want me to do it here or rapt?

**Comment by renpytom** [comment]
Doing it here is good, I look at this bug tracker far more often.

**Comment by trajano** [comment]
I just tested the Android one, it works so that means as you said the generated one does not work.  There's presently no capability at this point for it.  However, it did give me a way of refining #1927
