### ISSUE TITLE
App Instantly Crashing on Startup [Android 9.0]

### ISSUE THREAD

**Issue by OrangeFlare** [renpy/renpy#1944]
Logcat shows Android complaining about something to do with the Play Store and Licensing
This error is preventing the app from launching at all

Here's a version that's slightly easier on the eyes
https://pastebin.com/aXcysVsM

`07-18 10:39:52.230 18716 18716 E LicenseChecker: Could not decode from Base64.
07-18 10:39:52.230 18716 18716 E LicenseChecker: com.google.android.vending.licensing.util.Base64DecoderException: Bad Base64 input character at 3: 95(decimal)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at com.google.android.vending.licensing.util.Base64.decode(Base64.java:546)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at com.google.android.vending.licensing.util.Base64.decode(Base64.java:474)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at com.google.android.vending.licensing.util.Base64.decode(Base64.java:420)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at com.google.android.vending.licensing.LicenseChecker.generatePublicKey(LicenseChecker.java:112)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at com.google.android.vending.licensing.LicenseChecker.<init>(LicenseChecker.java:95)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run(DownloaderService.java:768)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at android.os.Handler.handleCallback(Handler.java:873)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at android.os.Looper.loop(Looper.java:193)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at java.lang.reflect.Method.invoke(Native Method)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-18 10:39:52.230 18716 18716 E LicenseChecker: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-18 10:39:52.230 18716 18716 D AndroidRuntime: Shutting down VM
07-18 10:39:52.230 18716 18716 E AndroidRuntime: FATAL EXCEPTION: main
07-18 10:39:52.230 18716 18716 E AndroidRuntime: Process: me.orangeflare.cmds, PID: 18716
07-18 10:39:52.230 18716 18716 E AndroidRuntime: java.lang.IllegalArgumentException: com.google.android.vending.licensing.util.Base64DecoderException: Bad Base64 input character at 3: 95(decimal)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.google.android.vending.licensing.LicenseChecker.generatePublicKey(LicenseChecker.java:121)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.google.android.vending.licensing.LicenseChecker.<init>(LicenseChecker.java:95)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run(DownloaderService.java:768)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: Caused by: com.google.android.vending.licensing.util.Base64DecoderException: Bad Base64 input character at 3: 95(decimal)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.google.android.vending.licensing.util.Base64.decode(Base64.java:546)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.google.android.vending.licensing.util.Base64.decode(Base64.java:474)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.google.android.vending.licensing.util.Base64.decode(Base64.java:420)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	at com.google.android.vending.licensing.LicenseChecker.generatePublicKey(LicenseChecker.java:112)
07-18 10:39:52.230 18716 18716 E AndroidRuntime: 	... 9 more
07-18 10:39:52.232  1258  3238 W ActivityManager:   Force finishing activity me.orangeflare.cmds/org.renpy.android.DownloaderActivity
07-18 10:39:52.236  1258  1342 I ActivityManager: Showing crash dialog for package me.orangeflare.cmds u0`

**Comment by renpytom** [comment]
This looks like you gave it an invalid value for build.google_play_key.
