### ISSUE TITLE
Allow changing the console fonts

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1946]
Since I am trying to develop a portrait mode game, I set the resolution to 1080x1920, but the resulting console gets very difficult to read is there a way of changing the console font sizes?

![image](https://user-images.githubusercontent.com/110627/61509120-16eb2b00-a9bb-11e9-9e6b-a69953205823.png)

**Comment by renpytom** [comment]
Adjust the size property of the _console_text style.

**Comment by trajano** [comment]
Is that documented anywhere?  I didn't find "_console_text" when I did the search on the renpy documentation
This did work though
```
style _console_text:
    size 30

```

**Comment by renpytom** [comment]
Well, no. It's a console internal. So it's possible in some future version of Ren'Py, this will stop working. That's unlikely, and it won't break the game even if it does, since that will then create a useless style.
