### ISSUE TITLE
dir() has been crippled to make it useless in the console

### ISSUE THREAD

**Issue by jack4455667788** [renpy/renpy#1947]
the dir() function truncates its output in the console to some stupidly small amount of characters.  This change happened somewhere around 7.2 / 7.3 but it is not in the list of changes. It also appends "..." to the output.

The dir() command is very useful for debugging, and crippling it in this way is not cricket or acceptable.

Can you please fix what you broke?  Or provide the detail as to what I need to change to revert to a working/useful dir() function?

Thanks!

**Comment by renpytom** [comment]
There's a command in the console that changes this, help should tell you about it.

**Comment by rapsys** [comment]
To the next one that was looking for the answer, type "long" in console.
