### ISSUE TITLE
gui.init() should also resize the window

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1950]
This is a very unlikely scenario, but I am adding it as a concept for scenes that switch between landscape  and portrait.  For the most part it works, but the window does not resize.
```
label pmui_rotate:
    python:
        gui.init(config.screen_height, config.screen_width)
        renpy.rollback()
    return
```

**Comment by renpytom** [comment]
I don't feel that changing aspect ratio like this is a feature that I plan to support.  Changing config variables, like config.screen_heigh and config.screen_width, is also not supported outside of the init blocks. What's more, portions of Ren'Py will likely actively work against this, as any caching of virtual sizes will become suspect. 

Basically, changing the virtual size of the game outside of the init phase is not supported.

**Comment by trajano** [comment]
then perhaps throw a hard exception when executing `gui.init` again.

**Comment by renpytom** [comment]
df32d311 throws a hard exception when gui.init is called outside of the init phase.
