### ISSUE TITLE
rollback capable of breaking "notify" screen in renpy default GUI

### ISSUE THREAD

**Issue by Belgerum** [renpy/renpy#1951]
So, I think I've found an issue with the notify screen in the renpy default GUI and how it behaves with rollback.

This error occurs with all of my games, as well as all new projects I create with renpy.

The issue can be replicated by using a quick save/screenshot button, advancing dialogue a few times, and when the notify screen starts to fade away, rollback. This has the potential to make the notify screen reappear permanently, and not hide until another notify message is sent.

here's some quick video footage of me replicating the issue:
[Footage of issue.zip](https://github.com/renpy/renpy/files/3413927/Footage.of.issue.zip)

**Comment by jackmcbarn** [comment]
Do we still need 8e04c76 now that we have 0aaf668? The former has the side effect of making all notifications immediately disappear on rollback.

**Comment by renpytom** [comment]
I don't think  8e04c76 hurts anything. A rollback is an out-of-game operation, and I'm fine with those clearing notifications.
