### ISSUE TITLE
Future versions of Ren'Py won't work on macOS Catalina

### ISSUE THREAD

**Issue by alicerunsonfedora** [renpy/renpy#1958]
<img width="532" alt="Screen Shot 2019-07-23 at 17 11 38" src="https://user-images.githubusercontent.com/13445064/61748214-be76ad80-ad6d-11e9-8014-e428457fd71a.png">

Starting with macOS 10.15 Catalina, the system will force all applications, installers, and packages built on or after June 1, 2019 to be notarized (eg. [code sent to Apple to verify that there isn't any malware](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution)).  As stated on Apple Developer:

> Beginning in macOS 10.14.5, all new or updated kernel extensions and all software from developers new to distributing with Developer ID must be notarized in order to run. Beginning in macOS 10.15, notarization is required by default for all software.

While this doesn't affect opening it, it can get annoying if you're also attempting to run Ren'Py from the command line since all of the files inside are also affected by this.

More details on notarization: https://developer.apple.com/videos/play/wwdc2019/703/

**Comment by alicerunsonfedora** [comment]
Also submitted an issue via Feedback Assistant on Catalina:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/13445064/61749475-ddc30a00-ad70-11e9-896e-77f5eddec6ab.png">

**Comment by renpytom** [comment]
I've gone ahead and disabled code-signing for the time being. As far as I can tell, if code is signed but not notarized, it won't run on Catalina. At the same time, as far as I can tell, unsigned code can run in the way it always has been run. So it's probably better to distribute unsigned versions of Ren'Py and let people disable gatekeeper to run them (or use itch.io, steam, or other launchers to run them).

**Comment by alicerunsonfedora** [comment]
A temporary bypass for this can be by running `xattr -d com.apple.quarantine *` in the Ren'Py SDK folder.

**Comment by renpytom** [comment]
Closed, since it's working as of 7.3.3.

**Comment by Pichuminer** [comment]
> A temporary bypass for this can be by running `xattr -d com.apple.quarantine *` in the Ren'Py SDK folder.

This command now doesn't work for me.
xattr: LICENSE.txt: No such xattr: com.apple.quarantine
xattr: doc: No such xattr: com.apple.quarantine
xattr: dranotherstory: No such xattr: com.apple.quarantine
xattr: gui: No such xattr: com.apple.quarantine
xattr: launcher: No such xattr: com.apple.quarantine
xattr: lib: No such xattr: com.apple.quarantine
xattr: log.txt: No such xattr: com.apple.quarantine
xattr: module: No such xattr: com.apple.quarantine
xattr: renpy: No such xattr: com.apple.quarantine
xattr: renpy.app: No such xattr: com.apple.quarantine
xattr: renpy.exe: No such xattr: com.apple.quarantine
xattr: renpy.py: No such xattr: com.apple.quarantine
xattr: renpy.sh: No such xattr: com.apple.quarantine
xattr: the_question: No such xattr: com.apple.quarantine
xattr: tmp: No such xattr: com.apple.quarantine
xattr: tutorial: No such xattr: com.apple.quarantine
xattr: update: No such xattr: com.apple.quarantine

**Comment by rittamdebnath** [comment]
Please can someone give the solution to this problem. I have downloaded the latest version, it opens for split second and closes.

**Comment by PierreRoq** [comment]
> Please can someone give the solution to this problem. I have downloaded the latest version, it opens for split second and closes.

I ran into the same problem and the solution was given to me on the Discord : you have to copy the folder into the Applications to make it work.
