### ISSUE TITLE
Program freezes when attempting rollback (unresponsive, single core usage at 100%)

### ISSUE THREAD

**Issue by Rockspecht** [renpy/renpy#1959]
I've written a blackjack minigame for a visual novel, however certain parts of it seem to mess with Renpy's rollback function.
The file is a little lengthy (around 280 lines or so, including comments and empty lines) so I've uploaded it to mediafire in order to not post the entire thing here.

http://www.mediafire.com/file/ee8qx7kyjyx52j2/Blackjack_new.rpy/file

So from my observation, once it has passed line 150 and I even attempt to roll back using the mouse wheel, the program becomes unresponsive and locks up on a single CPU core running at 100%.
Suspending or locking rollback causes the same behavior.

**Comment by Rockspecht** [comment]
Alright, I've figured it out. It was the usage of itertools that Renpy didn't like.

So setting up an interator like this
`playerListIterator = itertools.cycle(listOfPlayers)`
and then using it by
`currentPlayer = next(playerListIterator)`
seems to currently do something that Renpy's rollback doesn't like whatsoever.

**Comment by renpytom** [comment]
Sorry I wansn't able to get to this - it fell through the cracks after some medical issues. 

In general, iterators and rollback don't really play well.
