### ISSUE TITLE
Dialog does not trigger "show" event

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1960]
I have a transform that I want to execute during show and hide of the character dialog.  However, it does not appear to be triggered

```
transform saybox_namebox_transform(xoffset, yoffset, degs, yoffset_transform = 40, easein = 0.15):
    rotate_pad True
    on show:
        rotate 0
        xoffset pmui.scale_p(xoffset)
        yoffset pmui.scale_p(yoffset)
        easein easein rotate degs yoffset pmui.scale_p(yoffset-yoffset_transform)
```

This may be similar to https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=56268&p=515735#p515735

**Comment by renpytom** [comment]
I looked at your example, and it's not supposed to work. 

The show event is only delivered to the direct children of screens, and the hide event is only delivered to the direct children of a non-transient screen. You code appears to expect it to  be available inside of both a background style property and the child of a DynamicDIsplayable. 

When used correctly, this works. (Note that hide events are not delivered for transient screens, like say.)

**Comment by trajano** [comment]
So based on what you said, I should be able to "tweak" it such that `screen say()` calls `renpy.show` to show the dialog itself.

**Comment by renpytom** [comment]
No, that's not something that I said. I explained when the show event will be delivered. 

I don't believe that this issue is an issue with Ren'Py.
