### ISSUE TITLE
Shader error: 'highp' : precision is not supported in fragment shader

### ISSUE THREAD

**Issue by Beuc** [renpy/renpy#1963]
I just got a report from a RenPyWeb user getting this on a tablet:
```
  File "glenviron_shader.pyx", line 315, in renpy.gl.glenviron_shader.check_status
Exception: Shader error: ERROR: 0:3: 'highp' : precision is not supported in fragment shader
```
I requested more info on the hardware, but looking at the code, it sounds like Ren'Py assumes 'highp' is available everywhere.

In the OpenGL wikibooks I wrote a few years back, I used this kind of boilerplate:
https://gitlab.com/wikibooks-opengl/modern-tutorials/blob/master/common-sdl2/shader_utils.cpp#L90
```
		"#ifdef GL_ES                        \n"
		"#  ifdef GL_FRAGMENT_PRECISION_HIGH \n"
		"     precision highp float;         \n"
		"#  else                             \n"
		"     precision mediump float;       \n"
		"#  endif                            \n"
		"#else                               \n"
		// Ignore unsupported precision specifiers
		"#  define lowp                      \n"
		"#  define mediump                   \n"
		"#  define highp                     \n"
		"#endif                              \n";
```
Not sure how current this is in 2019.

**Comment by Beuc** [comment]
The hardware is a Huawei Mediapad 10 Link running Android 4.4.
According to the specs it carries a Vivante GC4000 GPU:
https://www.gsmarena.com/huawei_mediapad_10_link-5507.php
which should fully supported GLES 1-3:
https://bensontao.wordpress.com/2013/12/04/vivante-vega-gpu-geometry-and-tessellation-shader-overview/

The lack of 'highp' is not detected by Ren'Py and RenPyWeb quickly crashes with a JavaScript error ("cannot read property 'createImageData' of null").

I asked the user if they can test with a RAPT version for comparison just to make sure.

**Comment by Beuc** [comment]
The user (who decided not to comment here, so I'll proxy) couldn't compare with RAPT since RAPT now requires Android 5.0 (since 7.2 or 7.3 AFAICS, I didn't find the info in the Ren'Py changelog).
I unearth my first smartphone but it already supported 'highp' so I cannot test personally (however I could check the funny results that a native 'lowp' can produce ;)).

**Comment by Beuc** [comment]
I send a build following #1965 to the user to see if this fixes the issue.

**Comment by renpytom** [comment]
This has been merged in, and I handled in in gl2, so I think this can be closed.
