### ISSUE TITLE
Gaps when using Frame and At then AlphaMask as a background

### ISSUE THREAD

**Issue by trajano** [renpy/renpy#1964]
I found some odd one pixel gaps when rendering a frame.

![image](https://user-images.githubusercontent.com/110627/62022195-101d9e80-b199-11e9-8cc1-061a6785b3e3.png)

when I

    show choice selected frame at truecenter:
       size (400,400)

It appears to render correctly with no gaps.

![image](https://user-images.githubusercontent.com/110627/62022288-90440400-b199-11e9-9f13-87ef66f55025.png)

I tried upgrading to the nightly to see if it will fix the problem as you had some changes regarding gl2 but the results above were from nightly. 

After playing with it a bit I think I narrowed it down to the fact that I am using transparent colors and the frame components are overlapping a bit

![image](https://user-images.githubusercontent.com/110627/62023430-d6e82d00-b19e-11e9-8c44-3ddd061fb75f.png)

```
image choice frame:
    Frame(
        Composite(
            (105, 150),
            (0, 0), AlphaMask(Solid(pmui.choice_box_color), "portrait-mode-ui/ui/rect-alphamask.png"),
            (0, 0), "portrait-mode-ui/ui/rect-dropshadow.png",
        ),
        top=45, left=45, bottom=45, right=0
    )
    subpixel True
    zoom pmui.scale
```

**Comment by renpytom** [comment]
Ren'Py uses more precise positioning when things are scaled to integer values, and proper display of Frame depends on that. Using size here ensures the sizes and positions are all integers. 

Gl2 should  bring a new implemention of Frame that fixes this, so I don't think I will address this before then.

**Comment by renpytom** [comment]
7.4 is out, and gl2 is the default, so I'm closing this.
