### ISSUE TITLE
live composite side image error

### ISSUE THREAD

**Issue by judithan** [renpy/renpy#1966]
[errorfile.zip](https://github.com/renpy/renpy/files/3459114/errorfile.zip)
I'm trying to create a live composite image that has a variable for the body base, mouth, and eyes, and then display that as a side image as well, but whenever the side image and main image are both displayed an error occurs

**Comment by renpytom** [comment]
I've made a fix for this. You can add this to your version of Ren'Py by downloading:

https://raw.githubusercontent.com/renpy/renpy/master/renpy/display/layout.py

And using it to replace renpy-6.3.2-sdk/renpy/display/layout.py. 

Thank you for putting together a good demonstration of the error, it eased tracking down this problem quite a bit.
