### ISSUE TITLE
pickle and threading conflict

### ISSUE THREAD

**Issue by Beuc** [renpy/renpy#1968]
Hi,

I'm experimenting with fetching URLs in the background so as not to block the game on network error.

I'm getting some success but I get all kind of weird issues on saving as soon as I start a thread, even if I exclude it from pickling.

Here's a reasonably simple test case that occurs on second save; I have a more complex download example where the same error happens on first save. Seems like starting a thread somewhat taints the environment?

```
init python:
    import threading, time
    class Test:
        def __init__(self):
            self.thread = None
        def __getstate__(self):
            self.thread = None
            return self.__dict__
        def send(self, ignored):
            self.thread = threading.Thread(target=lambda:time.sleep(1))
            self.thread.start()
        def isAlive(self):
            return self.thread and self.thread.isAlive()


label start:
    $ config.use_cpickle = False
    "Start"
    $ t = Test()
    $ t.send('')
    show text "request in progress"
    while t.isAlive():
        pause 0.1
    hide text
    "Save here (OK)"
    "Then save here (KO)"
    "End"
```

```
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/pickle.py", line 817, in whichmodule
  File "/home/tom/ab/x64lucid-deps/install/python/pygame_sdl2/__init__.py", line 33, in __getattr__
NotImplementedError: Could not import pygame_sdl2.mixer: No module named mixer
```

Adding `self.thread=None` in isAlive can also trigger the issue (while it should lessen its probability).

(also sadly this technique doesn't help when the user rollsback, ren'py becomes unresponsive)

Any clue on what is causing the exception?

**Comment by jsfehler** [comment]
How about:
```
    class Test:
        def __init__(self):
            self.thread = None
        def __getstate__(self):
            self.thread = None
            return self.__dict__
        def send(self, ignored):
            renpy.invoke_in_thread(lambda:time.sleep(1))
        def isAlive(self):
            return self.thread and self.thread.isAlive()
```

**Comment by Beuc** [comment]
That sounds interesting.
Question is: how do we know when the thread is finished? With this Test.isAlive is broken.

**Comment by renpytom** [comment]
You're not allowed to store a thread (or anything else unpickleable, like iterators) in the Ren'Py store. I'd suggest not storing the thread - use invoke_in_thread to call a function or method, and have that
update some piece of data when th callable finishes.

**Comment by Beuc** [comment]
> I'm getting some success but I get all kind of weird issues on saving as soon as I start a thread, **even if I exclude it from pickling.**

**Comment by renpytom** [comment]
Okay, how are you excluding it from pickling? Since in your example, you create a Test object with a thread field, and then refer to that from `t`. So that will cause it to be pickled. It's pretty hard to safely create a thread from the Ren'Py context, but something like:

```
init python:
     class MyThread(object):
           def __init__(self)
                 self.done = False
                 t = threading.Thread(target=self.run)
                 t.start()
           def run(self):
                time.sleep(10)
                self.done = True
```

**Comment by Beuc** [comment]
With `__getstate__` [(doc)](https://docs.python.org/2/library/pickle.html#example), sorry if that wasn't obvious.
```
        def __getstate__(self):
            self.thread = None
            return self.__dict__
```
which incidentally fixed some occurrences of the error, but not all.

Also the error is quite different from what you get when pickling a thread (which would be "can't pickle lock objects").
(As for my project I implemented some work-around with invoke_in_thread meanwhile)

I smell a bug of sorts, hence this issue.

**Comment by renpytom** [comment]
Sorry this took so long to address, I had a trip, and then some medical problems, and between them this fell through the cracks. 

There's basically two ways the thread can leak out. The first is through the state of the object. While __getstate__ would kind of prevent that, I think it's better to copy and edit the state. Then it can also leak out when the .thread field is updated, through the Ren'Py rollback system. Here's my fix for it:

```
init python:
    import threading, time
    class Test(NoRollback):
        def __init__(self):
            self.thread = None
        def __setstate__(self, value):
            self.__dict__.update(value)
        def __getstate__(self):
            rv = self.__dict__.copy()
            rv['thread'] = None
            return rv
        def send(self, ignored):
            self.thread = threading.Thread(target=lambda:time.sleep(1))
            self.thread.start()
        def isAlive(self):
            return self.thread and self.thread.isAlive()
```

Unless there is some super-pressing reason, I would probably avoid creating this object outside of an init block. It would probably be better to have a singleton that's created during the init phase, and then have other code simply make requests of that singleton.

**Comment by Beuc** [comment]
Thanks! (I hope you recovered well :))
I had first made tests with inheriting NoRollback and I'm surprised it was not enough?
When that failed, I experimented with disabling pickling -- I didn't expect I needed both.
