### ISSUE TITLE
renpy.sound.play() doesn't work at all in Ren'Py 7.3.2 (but it does work in 7.2.2)

### ISSUE THREAD

**Issue by RawleNyanzi** [renpy/renpy#1975]
The method renpy.sound.play() does not work at all in Ren'Py 7.3.2. The last version I know of where it does work is 7.2.2. I've attached a short example project to illustrate the issue; test it in both 7.3.2 and 7.2.2 to hear the difference. To make switching between versions easier, the zip file is just the project folder full of the code and assets, not an executable program on its own.
[Sound Does Not Work.zip](https://github.com/renpy/renpy/files/3485852/Sound.Does.Not.Work.zip)

**Comment by DarkTl** [comment]
Works after converting sound to ogg format. Must be wav issue.

**Comment by renpytom** [comment]
This has been fixed by e6546189eb3fbd0140b067a0f76a96d25a243844.
