### ISSUE TITLE
Webm color range issue

### ISSUE THREAD

**Issue by DabManTrips** [renpy/renpy#1976]
Webm file plays fine and correct color range outside of renpy but when loaded in renpy the color range dramatically changes.

**Comment by Khailz** [comment]
I've had the same issue before. Depending on the color range selected at render, Renpy will change it to a more saturated look. Preserving RGB coloring and rendering at certain settings helps to keep correct color formatting, but it's hit or miss.

**Comment by renpytom** [comment]
The relevant libraries have been updated in 7.4, so I'm closing this. Please re-open if you think this is still a problem.
