### ISSUE TITLE
Regression: "TypeError: list indices must be integers, not ChoiceReturn" menu statement

### ISSUE THREAD

**Issue by uyjulian** [renpy/renpy#1982]
Sample code: 
```rpy

label start:
    
    window show
    
    menu:
        "Choose an option."

        "Choose me.":
            pass

    "No error occurred."
```
Place the sample code in `first.rpy` in the project directory. Don't put any additional files.

In Ren'Py 7.1.1, the sample code works as expected.  
In Ren'Py 7.1.2, the following error occurs: 
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/_start.rpy", line 6, in script
    menu:
TypeError: list indices must be integers, not ChoiceReturn

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/_start.rpy", line 6, in script
    menu:
  File "/Users/julian/Desktop/rypx/y/renpy/ast.py", line 1567, in execute
    next_node(self.items[choice][2][0])
TypeError: list indices must be integers, not ChoiceReturn

Darwin-18.7.0-x86_64-i386-64bit
Ren'Py 7.1.2.1090
 
Sat Aug 24 13:19:10 2019
```

This regression still exists in Ren'Py 7.3.2.

**Comment by uyjulian** [comment]
I've traced this issue to commit 56fe28955a44583978da4d8bfc054b7205a3a176

**Comment by renpytom** [comment]
Fixed, but this was a borderline case as a regression - in general, for code that isn't running at an old script_version (which would have fixed this), running without screens defined isn't supported. And even with screens, we may ask that you upgrade your game. 

So realize that you can't expect to run arbitrarily old scripts on a modern Ren'Py without enabling the compatibility mode.
