### ISSUE TITLE
Provide a way to load Hi-DPI images

### ISSUE THREAD

**Issue by jackoalan** [renpy/renpy#1985]
As displays of 3840x2160+ resolution become more commonplace, content creators will naturally want to increase the resolution of their artwork to take advantage. Ren'Py has creators work in a virtual screen resolution (of something like 1280x720) where a lot of time is spent scripting layout coordinates.

For creators that want to produce a "4K remastered" version of their visual novels, it is not enough to simply increase the resolution of the images. The virtual screen resolution and *all* layout coordinates must be proportionally increased.

A more convenient solution would be to keep the virtual resolution and have the image indicate that it is a "Hi-DPI" version of a natively-sized image. For instance, a 720p image could be named `image.png` and the remastered 2060p version could be named `image@3x.png`. The 3x image is placed and transformed as if it were the 1x. Users could opt-in to substituting these Hi-DPI images via the visual novel preferences (once they've verified their graphics hardware can handle it).

A prototype of this feature is implemented in my Ren'Py fork. Passing `define config.hidpi_textures = True` will enable the functionality.

jackoalan/renpy@a3754fce

**Comment by susan-shu-c** [comment]
Interested in this as well

**Comment by susan-shu-c** [comment]
Seems to be in the Custom configuration - does that close this issue?

**Comment by renpytom** [comment]
This has been added to Ren'Py 8.1/7.6 (with a different implementation), so I'm closing this issue.
