### ISSUE TITLE
maxsize will upscale smaller images

### ISSUE THREAD

**Issue by mal** [renpy/renpy#1987]
I'm not sure if this is a bug or expected behaviour. The original changelog entry for `maxsize` suggests that images will only be scaled down to fit within the defined bounds, a description that appears to match up with the name. Actual behaviour differs from this in that smaller images will scaled up until one of their dimensions touches the bounds. The documentation proper doesn't preclude this, but neither does it appear to acknowledge it, hence the uncertain as to classifying it as a bug.

When using it, I was expecting images that were already sized within the bounds would be left untouched. The use case being to define an area in which a arbitrary displayable could be placed while being certain that larger displayables would be suitably scaled down to fit the area on an as needed basis. Unfortunately the upscaling negatively impacts the situation when using a smaller displayable.

If intended, `maxsize` seems like an odd name, and perhaps `minsize` (upscale only), `maxsize` (downscale only) and `fitsize`(? there are probably better names) (current `maxsize` behaviour), might be worth considering?

Test case follows:

```renpy
label main_menu:
    $ _confirm_quit = False
    return


image box = Solid('f777', xysize=(150, 150))


label start:
    scene
    show box at top
    'normal box 150x150'
    show expression Transform('box', maxsize=(100, 250)) at topleft
    'maxsize 100x250 - {color=7f7}shrinks{/color} to 100x100'
    show expression Transform('box', maxsize=(250, 100)) at topright
    'maxsize 250x100 - {color=7f7}shrinks{/color} to 100x100'
    show expression Transform('box', maxsize=(250, 250)) at truecenter
    'maxsize 250x250 - {color=f77}grows{/color} to 250x250'
    'fin'
    return
```

Potential fix if no upscaling is desired (**untested**):

https://github.com/renpy/renpy/blob/6754d50c12e58914bb6d5760946b074545c25b00/renpy/display/accelerator.pyx#L208
```diff
-        mul = min(maxsizex / width, maxsizey / height)
+        mul = min(maxsizex / width, maxsizey / height, 1)
```

**Comment by mal** [comment]
This now also applies to `minsize`, which will present the same problem in the inverse, shrinking any images that already exceed the minimum size specified.

**Comment by renpytom** [comment]
Since we have the ``fit`` property now, this is resolved. Right?

**Comment by mal** [comment]
Yup 👍
