### ISSUE TITLE
str() crashes on LinuxOS

### ISSUE THREAD

**Issue by barsunduk** [renpy/renpy#1988]
> Failure:
> Your build has failed our review because it crashes frequently on SteamOS and Linux.
> 
> After beginning a tournament, the user can move a few arrows before receiving an exception error. The error can be ignored but happens in every tournament.
> 
> Here are the details:
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> File "game/script.rpy", line 106, in script call
> call arrows(0) from _call_arrows
> File "game/arrows.rpy", line 863, in script
> call screen gameArrows
> File "renpy/common/000statements.rpy", line 531, in execute_call_screen
> store._return = renpy.call_screen(name, *args, **kwargs)
> File "game/arrows.rpy", line 675, in set_speech
> while str(s) == str(speech):
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

**on windows it's ok.**

**Comment by renpytom** [comment]
This isn't a bug in Ren'Py, this is a bug in your game. I'd suggest:

while unicode(s) == unicode(speech):

But again, nothing to do with Ren'Py.
