### ISSUE TITLE
Functions are not documented

### ISSUE THREAD

**Issue by qirien** [renpy/renpy#1989]
I keep finding useful functions on Lemmasoft that are not documented in the Ren'Py documentation. It would be great to add these.  I would add these but I have no idea how to generate documentation, etc; however, I have written up some text that someone who does could copy/paste in.

- renpy.random.shuffle
(should go in other.html, in the renpy.random section at the bottom)
renpy.random.shuffle(seq)
Shuffles the elements of the sequence seq in place. Returns None.
Example:
```
define song_list = ["song1.ogg", "song2.ogg", "song3.ogg"]
renpy.random.shuffle(song_list)
play music song_list
```

- RoundRect(color)
(should go in displayables.html, in the Image-Like Displayables section)
Returns a Frame displayable in the shape of a rounded rectangle using the given color.
Example:
```
screen say:
     background RoundRect("#f00")
```

**Comment by qirien** [comment]
OK, thanks. I didn't know you could do a rounded rectangle with a Frame - is that documented somewhere?

**Comment by renpytom** [comment]
It's not really documented directly, it's just that it kind of falls out off the definition of what a Frame is. You can take a roundrect picture, separate out the corners, and you now have RoundRect.

**Comment by qirien** [comment]
Oh, so the only way to generate a rounded rectangle programatically from just an RGB value is still RoundRect, which is obsolete?

I'm using RoundRect to generate speech bubble backgrounds based on the speaker's character color for a texting-style interface... since we have like 30 characters it would be kind of a pain to create images for them all.  But I also don't want to use obsolete functions...

**Comment by renpytom** [comment]
Closing this.

I'd expect RoundRect to work into the future - I don't remove obsolete functions without a good reason - but it's not something I plan to document, either.
