### ISSUE TITLE
feature request: extract dialogue for another language than the default one

### ISSUE THREAD

**Issue by zeograd** [renpy/renpy#1992]
When performing voice dubbing for another language than the native/default one, it would be interesting to have the spreadsheet export with id, actor and translated text
I guess that adding a language selector on the Extract dialog screen and applying translation during the export could answer this use case.

So far, we can rely on the tl/*/script.rpy at best which isn't adapted for spreading work across multiple voice actors nor tracking progression.

Thanks in advance.

**Comment by kyouryuukunn** [comment]
I sent pull request.
#3339
