### ISSUE TITLE
Switching to fullscreen doesn't show images

### ISSUE THREAD

**Issue by lunalucid** [renpy/renpy#2013]
All images (background images, button images, etc) disappear and default to a black background when switching to fullscreen mode.

**Comment by renpytom** [comment]
Only on windows. It's probably not due to clearing the texture cache when switching screen modes.

**Comment by lunalucid** [comment]
When opening the game back up (while the setting is still full screen), images show up but if switched to windowed, it's back to black again so yeah it's both ways. But restarting the game fixes it.

**Comment by morganwillcock** [comment]
I'm seeing a similar issue where either images are missing entirely or incorrect images are used in-place of what should be there. It seems to be triggered by switching to fullscreen, but switching back doesn't always fix it for me.

Main menu on the tutorial:
![render](https://user-images.githubusercontent.com/14958747/66270264-49355780-e849-11e9-95bd-06b3cbb17a55.PNG)

After playing pong:
![render](https://user-images.githubusercontent.com/14958747/66270268-4fc3cf00-e849-11e9-8741-3c66a0ef5d5a.gif)

This is with version 7.3.3.568 on Windows.

**Comment by renpytom** [comment]
This should be fixed by version 7.3.4. Thanks for the reports!
