### ISSUE TITLE
Comments are blank lines (ie:'\n') when viewed in ast.Python.code.source

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#2026]
When examining python statements, lines where comments were are just blank lines. I'm unclear if this is the intended behaviour, if comments should be preserved, or if comments should be removed along with the line entirely.

Use case for this is running pycodestyle inside Ren'Py's linter. The blank lines are causing false positives.

**Comment by renpytom** [comment]
This is the intended behavior. The blank lines are needed to make sure that the error messages line up with the lines inside the file. Comments are stripped out before Python is parsed, hence why comments are not present. 

I think you'll have to just disable such warnings in the linter.

**Comment by jsfehler** [comment]
I was afraid of that, but makes sense. Thanks.
