### ISSUE TITLE
RenPy linter fails to start

### ISSUE THREAD

**Issue by outkats** [renpy/renpy#2027]
Having a problem linting code after a recent change we made to our game. The linter fails, but the game itself works.

Traceback:
```
I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
TypeError: not enough arguments for format string

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Renpy\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "D:\Renpy\renpy\main.py", line 574, in main
    run(restart)
  File "D:\Renpy\renpy\main.py", line 102, in run
    if not renpy.arguments.post_init():
  File "D:\Renpy\renpy\arguments.py", line 287, in post_init
    return commands[command]()
  File "D:\Renpy\renpy\lint.py", line 761, in lint
    check_show(node, False)
  File "D:\Renpy\renpy\lint.py", line 355, in check_show
    image_exists(name, expression, tag, precise=precise)
  File "D:\Renpy\renpy\lint.py", line 279, in image_exists
    report("'{}' is not an image.".format(" ".join(name)) )
  File "D:\Renpy\renpy\lint.py", line 63, in report
    out += msg % args
TypeError: not enough arguments for format string

Windows-8-6.2.9200
Ren'Py 7.3.4.578
HS 0.4.0.0
Fri Oct 04 22:34:20 2019
```
The error in lint.py seems to come from this line which raises an unhandled TypeError:
```
    report("'{}' is not an image.".format(" ".join(name)) )
```

I added a small exception handling block on this line using the following to see what line in our code was causing the issue since the normal lint report doesn't get generated in this case:
```
    try:
       report("'{}' is not an image.".format(" ".join(name)) )
    except TypeError:
       report("TypeError encountered when running image_exists()")
```

This led to the following (valid, working) line of code in our game:
```
    show text "High score: %s (%s)" % (high_score, player_name) at Position(xcenter=0.5,ycenter=0.05)`
```

It seems that the linter blows up when Python's string format operator is used to alter text right before it is displayed as a text displayable.
Assigning the text to a variable beforehand (as shown below) does allow us to work around the error, but seeing as the error crashes the linter itself, I figured I'd report it
```
    $ high_score_txt = "High score: %s (%s)" % (high_score, player_name)
    show text "[high_score_txt]" at Position(xcenter=0.5,ycenter=0.05)
```

**Comment by renpytom** [comment]
Fixed. 

Note that Position is obsolete and shouldn't be used, and that the use of expressions with show text isn't documented. The second use of show text is how they are expected to be used.
