### ISSUE TITLE
android-presplash template image is incorrectly named

### ISSUE THREAD

**Issue by maim-lain** [renpy/renpy#2029]
My presplash image wasn't loading, but then I realized the template image renpy provides has the wrong filename.

In the `renpy-sdk/rapt/templates` folder the presplash image is named `renpy-presplash.jpg` when it should be named `android-presplash.jpg`

**Comment by renpytom** [comment]
This isn't a bug, exactly. These files aren't intended as templates for you to edit. They're templates that are used by rapt if you don't supply an android-presplash.jpg file.
