### ISSUE TITLE
Ren'Py 7.3.4 Unable to make a ZIP Distribution of the SDK

### ISSUE THREAD

**Issue by GanstaKingofSA** [renpy/renpy#2032]
**Description**
Currently in the latest version of Ren'Py when the user selects `Open launcher project` and tries to build the Ren'Py Launcher with `sdk` selected, it will give the user a traceback error like the one below.

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/distribute.rpy", line 1512, in <module>
  File "game/distribute.rpy", line 1519, in _execute_python_hide
  File "game/distribute.rpy", line 572, in __init__
  File "game/package_formats.rpy", line 398, in wait_parallel_threads
  File "game/distribute.rpy", line 1299, in done
  File "game/distribute.rpy", line 122, in hash_file
IOError: [Errno 2] No such file or directory: 'E:\\renpy-7.3.4-sdk\\renpy-7.3.4-dists\\renpy-7.3.4-sdk.zip'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "launcher/game/distribute.rpyc", line 1512, in script
  File "E:\renpy-7.3.4-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\renpy-7.3.4-sdk\renpy\python.py", line 2008, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/distribute.rpy", line 1512, in <module>
  File "game/distribute.rpy", line 1519, in _execute_python_hide
  File "game/distribute.rpy", line 572, in __init__
  File "game/package_formats.rpy", line 398, in wait_parallel_threads
  File "game/distribute.rpy", line 1299, in done
  File "game/distribute.rpy", line 122, in hash_file
IOError: [Errno 2] No such file or directory: 'E:\\renpy-7.3.4-sdk\\renpy-7.3.4-dists\\renpy-7.3.4-sdk.zip'

Windows-8-6.2.9200
Ren'Py 7.3.4.596
Ren'Py Launcher 7.3.4.596
Thu Oct 10 18:09:15 2019
```

I know this is mainly a issue that only Tom can see when he builds Ren'Py updates for release but wanted to point that out as I have encountered it on it along with my own modification of the SDK.

**Comment by renpytom** [comment]
That isn't supported as a way to build a valid Ren'Py distro. ./distribute.py is used, but it's still pretty specific to Ren'Py. I'm not really supporting third parties building modified sdks - It's hard enough to build the official release for all the supported platforms.

**Comment by GanstaKingofSA** [comment]
I totally respect your standpoint and didn't know you used a alternate way to build the SDK for release than what devs normally use to build their mods in Ren'Py. I managed to get it working now with a few edits so I am going to close this issue unless this is re-opened to add said feats into it.

**Comment by renpytom** [comment]
Offhand, do you have the edits you made? I'm not overly-opposed to letting people make their own distros, it's just a ton of work and hard to support.

**Comment by GanstaKingofSA** [comment]
Yes. Currently my new release of the distro has it. I totally understand that support for many off-hand distros is a lot of work and hard so apologies if I originally came hostile or disappointed in my last comment.

- Windows - What I did was downgrade `distribute.rpy` that 7.3.4 came with to and I do mean this low of a downgrade, to 6.99.12.4's `distribute.rpy` to get Ren'Py on Windows to actually distribute .zip for Windows and Mac and .tar.bz2 for Linux and also add 6.99.12.4's `distribute_gui.rpy` due to a error reading the project name to replace 7.3.4's own `distribute_gui.rpy`. 

MacOS, it's a different story since it actually builds Ren'Py just fine and makes the .zip with a workable .exe and .app for both environments in that 1 ZIP. I haven't yet tested Linux (12 AM on this message so will do so in the few hours I am awake to mention it.

In the last error it appears on Windows' end it is coming from these main lines when it jumps to build the .zip and .tar.bz2. Ren'Py will actually build .tar.bz2 but not .zip without the 6.99 file downgrade.
```
  File "game/distribute.rpy", line 1512, in <module>
  File "game/distribute.rpy", line 1519, in _execute_python_hide
  File "game/distribute.rpy", line 572, in __init__
  File "game/package_formats.rpy", line 398, in wait_parallel_threads
  File "game/distribute.rpy", line 1299, in done
  File "game/distribute.rpy", line 122, in hash_file
```

Exactly I know this will not build a .dmg but from what I can see in testing is that Ren'Py skips building a .dmg at all so this can be just a seperate way to do .dmg. This is basically you building Ren'Py via distribute.py but in the launcher and people downloading the sdk zip off the renpy site for all OS versions + updates + editors + Android/iOS/Web. I will clarify you will need to download or transfer over development atom, editra, web, rapt, renios, jedit, raspi (especially raspi since there is no download for that in 7.3.4) to the launcher for those to build with actual files but they all get built as well with no issues on 7.3.4 for Mac and the 6.99.12.4 add-ins to 7.3.4 for Windows. Again Linux I will have to test in a few more hours.

Image below is with it now building all 7.3.4 with no Errno2 error with said fix/patch for Windows.
![Capture3](https://user-images.githubusercontent.com/40864681/66730554-23471e80-ee18-11e9-8c66-4eaec57c7f5c.PNG)
