### ISSUE TITLE
Doesn't open in macOS Catalina

### ISSUE THREAD

**Issue by specter78** [renpy/renpy#2034]
I tried with ren'py 7.3.4 but it just doesn't open. Same result with 7.3.3 and 7.3.2.

**Comment by renpytom** [comment]
I had similar feedback from another user. To get it working on Catalina:

1) Download the DMG.
2) Double click the DMG to mount it.
3) Copy the files out of the DMG to another location (like Applications)
4) Run renpy.app, and when macOS asks if you want to run a download app, say yes.

**Comment by specter78** [comment]
For some reason, after copying the entire sdk, the app doesn't open in downloads folder but opens in applications folder.

**Comment by StudioErrilhl** [comment]
Just wanted to note that upgrading to Catalina, from Mojave with Renpy already installed (and updated to 7.3.4) and working - Renpy works fine - no issues at all.

**Comment by ShivaThomas** [comment]
**BUG**: As long as Renpy is not in the Applications folder, it will not execute. This is only happening since MacOs 10.15.

**WORKAROUND**: Moving Renpy to the Applications folder is a useful workaround. 😃 

**Additional info**: When you try to execute Renpy from the command line you get an error message:

> LSOpenURLsWithRole() failed for the application /Users/shiva/Downloads/renpy-7.3.5-sdk/renpy.app with error -10810.

**Comment by kotori2** [comment]
There’s a new feature for files permission in Catalina, which make apps unable to read some of your user folders such as `/home/username/Documents` without granting permission. Simply put it out from those folders will work.

**Comment by renpytom** [comment]
I've been running Ren'Py in Catalina for some time, so I'll close this.
