### ISSUE TITLE
Lint not working properly

### ISSUE THREAD

**Issue by MatheusOPP** [renpy/renpy#2041]
Not the same problem as #2027 or #2040, though it was mentioned in the latter.

I'm having some trouble with the "Check Script (Lint)" feature when running it in one of my projects, even after applying the change in 56987e4 (before that I had the same problem as #2027 and #2040). For reference, I have a file in which I initialize all audio related variables (with the path of music, voice, etc) called audio.rpy, another one in which I do the same for images called images.rpy, etc. I also have various files with parts of the story script inside proper labels (e.g. a character_route_01.rpy file with a character_route_01 label) that are called in the main script.rpy file or even inside any of the other labels that are called there, but that aren't supposed to run at all unless said labels are called during the story flow. In those labels I put all kinds of statements you're expected to use for story scripts (play music, show, scene, voice dialogue statements, etc), sometimes referencing the declared variables in the case of statements that need them (such as "play music m01" or "voice character01Surprise").

When playing the game itself, all of it works well so long as I have declared the used variables in one of the files I mentioned (audio.rpy, images.rpy, etc). However, when checking for errors with lint, it returns me a txt file with more than 20 thousands lines pointing errors in scripts that only get called very late in the story (or aren't even called at all) due to undeclared variables (e.g. "is not an image" errors for images and "unable to evaluate voice filename" for voices), even though said variables are declared in the files I mentioned (audio.rpy, images.rpy, etc).

I first thought it was due to code priority, so I tried putting the code inside those files in init blocks with an offset that made then run before anything, but that didn't solve the problem. I then thought it might be a problem with lint checking the files in alphabetical order, so I tried putting all the "variable-initializing" code in audio.rpy, images.rpy and such in a file that preceeded all files alphabetically (a.rpy), but that also didn't solve the problem. So I'm at a complete loss as to what may be causing this. 

Is this expected, is this a bug or am I doing something very wrong?

**Comment by renpytom** [comment]
Hm...

I guess the question is, when are you defining m01? If you're defining them with define or in an init python block. On the other hand, if you're defining it at runtime, Ren'Py can't terll, and will give you an error like this.

**Comment by MatheusOPP** [comment]
Hm, with that tip I just noticed what I was doing wrong.

The declared stuff in those files was inside an init block, but some of it was initialized with default, which, I guess, was making those errors show up. Using define instead solved it, but that brought up another problem in that I want to change the value of those variable during runtime, and define shouldn't be used in that case according to the documentation since they're treated as constants. So instead I put all of that inside an init python block, removed the defines and now all's well. You can close this. Thanks for the help.
