### ISSUE TITLE
Feature-Request: Developer console pretty-print

### ISSUE THREAD

**Issue by multimokia** [renpy/renpy#2049]
As someone who sits through the developer console fairly often, looking through fairly large lists/dicts, I find it's fairly easy to get lost while looking for data.

I think it would be handy if console pretty-printing (or printing in json form) could be implemented, as it'd make looking though dicts like these a fair bit easier:
![image](https://user-images.githubusercontent.com/22531674/67784789-ab493d00-fa42-11e9-8b10-10ae62cc694f.png)

Thanks!

**Comment by ooa113y** [comment]
While a bit awkward, you can already do `import json` followed by `print(json.dumps(your_variable, indent=True))` to get a JSON representation. You can wrap that in your own function in the script to make it easier to call.

**Comment by multimokia** [comment]
Yep, I ended up doing that myself but via prettyprint (added the py file) since it seems to handle some things better than json did.

Made a console command out of it which was handy
