### ISSUE TITLE
Argument parsing on Windows breaks if an argument is two characters long

### ISSUE THREAD

**Issue by morganwillcock** [renpy/renpy#2057]
By the time that the bootstrap has started on Windows, argument values in sys.argv may already be incorrect, if any of the arguments are 2 characters in length.

This works fine:
`renpy launcher distribute --dest D:\buildtest --package mac C:\Path\To\Game`

This doesn't work:
`renpy launcher distribute --dest D:\buildtest --package pc C:\Path\To\Game`

Printing the sys.argv values during bootstrap shows there was a problem with the value 'pc', which results in an invalid item in the package arguments list later on (so nothing gets built):
<pre>D:\RenPy\renpy.py launcher distribute --dest D:\\buildtest --package pc??? C:\\Path\\To\\Game</pre>

Altering an earlier argument to make it 2 characters in length moves the problem. For example:
`renpy la distribute --dest D:\buildtest --package pc C:\Path\To\Game`
gives argv values of:
<pre>D:\RenPy\renpy.py la??? distribute --dest D:\\buildtest --package pc C:\\Path\\To\\Game</pre>

I think this is probably a character encoding issue with the .exe wrapper, but I couldn't obviously see where this is configured or built, to investigate any further.

Thanks!

**Comment by morganwillcock** [comment]
Possibly more seriously, it also breaks launching the game.

These start the game:
<pre>
D:\RenPy\renpy g
D:\RenPy\renpy gam
D:\RenPy\renpy game
</pre>
This falls back to starting the launcher:
<pre>
D:\RenPy\renpy ga
</pre>

**Comment by renpytom** [comment]
Noted. As a workaround until I can get to it, I'd suggest using:
```
lib\windows-i686\python.exe -EOO renpy.py launcher distribute --dest D:\buildtest --package pc C:\Path\To\Game
```

**Comment by renpytom** [comment]
I believe this has been fixed, as of a while ago.
