### ISSUE TITLE
7.3.5 doesn't work on RPi

### ISSUE THREAD

**Issue by lee-yunseok** [renpy/renpy#2058]
Message from terminal,

> Ren'Py platform files not found in:
> 
> /home/pi/Downloads/renpy/lib/linux-aarch64
> 
> Please compile the platform files using the instructions in README.md
> or point them to an existing installation using ./after_checkout.sh <path>.
> 
> Alternatively, please set RENPY_PLATFORM to a different platform.

[log.txt](https://github.com/renpy/renpy/files/3822683/log.txt)

**Comment by renpytom** [comment]
Right now, the raspberry pi 4b isn't supported.  (You might be able to get it working by symlinking lib/linux-arm to lib/linux-aarch64).

**Comment by lee-yunseok** [comment]
Thank you for confirm. It worked :)
