### ISSUE TITLE
Problem on changing android icon

### ISSUE THREAD

**Issue by Asuramaru69** [renpy/renpy#2072]
I already tried the tutorials that are given whether in documentation and in patreon..
Literally,I only need to change my both my icon which is foreground and background into 432x432 and put into the game’s base
The following icon need to be named like this:
android-icon_background.png
android-icon_foreground.png

Even though I tried that..The package still using the default one 

Maybe this is the problem I guess?
I tried to use android studio to check whats the problem and I found that there are duplicates of foreground pictures in the same file like xhdpi...but the name is different

Thanks
and srry if I got anything wrong

**Comment by sonejostudios** [comment]
I've got the same problem with RenPy 7.3.5, but the Android builds doesn't have the placeholder icons but the icons of The Question!
Is this a bug?

**Comment by sonejostudios** [comment]
SOLVED!
I had to reconfigure the apk before building to update the icons.
In Ren'Py-Launcher: Android -> Configure, then Build Package
