### ISSUE TITLE
Auto-forward mode not working with self voicing

### ISSUE THREAD

**Issue by StefanGagne** [renpy/renpy#2076]
Something raised to my attention by a visually impaired player of my game today -- clicking Auto Forward does nothing if self-voicing mode has been enabled. I tested myself and confirmed that the toggle doesn't toggle on with voicing activated, but once you turn off voicing, it works as intended.

Would it be possible to implement auto-forward in such a way as it detects when the line of dialogue is done being read aloud, and then forwards the user? This would be of tremendous help to visually impaired players. Thanks!

**Comment by renpytom** [comment]
Closed by 9366678fe .
