### ISSUE TITLE
Iconsistent use of images and audio directory

### ISSUE THREAD

**Issue by ReneFrijhoff** [renpy/renpy#2077]
There is an inconsistency in the use of the images and audio directory. For the images directory the 'images' part of the directory doesn't need to be specified in the path, however for the 'audio' directory it's mandatory to be specified in the path otherwise it can't find the file.

images path: image bg office1="story/office/spy_office1.png"
audio path: play sound "audio/soundfx/telephone_ring.ogg"

**Comment by Kassy2048** [comment]
@renpytom The fix breaks [_imagemap_auto_function()](https://github.com/renpy/renpy/blob/d6a72cfef3693f5cc9aab084df33a0aa13a00faf/renpy/common/00defaults.rpy#L162) as this method uses renpy.loadable() without specifying the directory where to look for the file. It might break other parts of the code that use renpy.loadable() directly as well.
