### ISSUE TITLE
enabling self-voicing with "V" gives no discernable feedback.

### ISSUE THREAD

**Issue by stickbear2015** [renpy/renpy#2078]
As someone that relies on self-voicing, and I appreciate the effort that goes into developing such a system in your engine for game developers to use, when I press V, (that's the key that's assigned to enable/disable self-voicing in the game I'm currently playing. anyhow, when you press V, you would expect it to say something like "self-voicing enabled." but it doesn't. Is this something that can be fixed at an engine level? Or do I need to poke the individual dev to mod something at a game level.
Note: you can get around it by hitting "V" again and it'll of course say "self-voicing disabled" but that feels clunky to me.
If this is something that needs to be fixed on a game level I'll happily work with the developer(s) of the game(s) effected to resolve it.
Thanks.

**Comment by stickbear2015** [comment]
one thing I forgot to note.
This only happens the first time you press "V" to enable self-voicing. If you turn it off and back on during that session it talks as it should and you get the feedback you should.

**Comment by Gouvernathor** [comment]
Seems like this was fixed.

**Comment by renpytom** [comment]
This might have been fixed a while ago. Ren'Py does say "Self-voicing enabled." when it's first enabled.
