### ISSUE TITLE
Specialized Partial Reloading

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2080]
Right now the change of any file - including things like images or sound files, requires Ren'Py to go through a full reload cycle. With the new renpy.flush_cache_file, that doesn't seem all that necessary anymore.

What I'd like to do is to have a list of file extensions, and functions that are used to reload files with those extensions. At the very least, we should be able to mark image and audio files as and use specialized functions to reload them.

**Comment by Andykl** [comment]
Fixed by 56a4ee81bcd29531318d578f858311b38f49832a
