### ISSUE TITLE
config.gc_print_unreachable does not affect logging of removed unreachables to stdout

### ISSUE THREAD

**Issue by TropeCode** [renpy/renpy#2086]
When `config.gc_print_unreachable = False` and `config.debug = True`, removed unreachables are logged to standard output. The first config variable should prevent this.

It's caused by the following lines in `python.rpy`.
```python
if renpy.config.debug:
    print("Removing unreachable:", o, file=renpy.log.real_stdout)
    pass
```
The condition should probably be changed to:
```python
if renpy.config.debug and renpy.config.gc_print_unreachable:
```

**Comment by renpytom** [comment]
Sorry about missing this, it's been a rough few years.

This actually isn't right, as there are two different kinds of unreachable objects here. config.debug causes objects that are unreachable by Ren'Py's load-save system to be printed, while config.gc_print_unreachable causes objects that are unreachable by Python's garbage collector to be printed.
