### ISSUE TITLE
Add "config.atl_one_frame" to the Configuration variables wiki page

### ISSUE THREAD

**Issue by minutekiwi** [renpy/renpy#2087]
What it says on the tin, it's [missing from this page.](https://www.renpy.org/doc/html/config.html)

The only place it shows up in the wiki is in the Incompatible Changes part of 6.99.13. Since I've had to look for it a couple times, I figure it's worth adding to the config officially.

> ATL Transforms now show at least one frame whenever a pause or interpolation occurs. When a game doesn't expect this, it can show up as a series of rapidly displayed single frames. 

...Is the original description.

As always, thank you for your hard work on Ren'Py.

**Comment by Moshibit** [comment]
Not only that config is missing, there are several that are not on that page of the documentation, some are only in the Changelog, Incompatible Changes, and others are in specific pages such as NVL. The documentation is missing some things that are in the source code such as the renpy.curry function. Despite this, the documentation is almost complete.

**Comment by renpytom** [comment]
Generally, stuff that is only in incompatible changes shouldn't be documented, as it's intended for older games, not new use.
