### ISSUE TITLE
python: ScriptError: could not find label 'start

### ISSUE THREAD

**Issue by Dizease** [renpy/renpy#2088]
Hello!
i tried to launch your game recently but the problem is that it wont start because of that error message i put in the title...
i saw some replies to that problem but thing is that i can't seem to find that blank game fil you're talking about
i you could help me that would be great :)
[renpy (1).zip](https://github.com/renpy/renpy/files/4047093/renpy.1.zip)

**Comment by renpytom** [comment]
You're missing an actual game here.
