### ISSUE TITLE
Issue about Xcode project.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2093]
If export the project to Xcode, get 'Building for iOS Simulator, but linking in object file built for macOS', 'Could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame', 'Launch images are deprecated in iOS 13.0. Use a launch storyboard or XIB instead.' and ''UILaunchImages' has been deprecated, use launch storyboards instead.' error messages, and can't test application with the emulator with a 'The operation couldn't be completed. (Mach error -308- (ipc/mig) server died)' message.
Please resolve it as soon as possible.
Thank you for all your effort.

**Comment by maartene** [comment]
Same issue.
I've submitted a bug report with Apple: FB8977378

**Comment by maartene** [comment]
Issue seems solved in Xcode Beta 12.5 beta 2.

Note: you need to manually change Plist.info entry:
**Bundle version** (technical name: **CFBundleVersion**) to type "String" and enter a valid version in the #.#.# format. I.e. "1.2.4"

![Info.plist](https://user-images.githubusercontent.com/5150271/109661775-9fa3e400-7b6a-11eb-99aa-f369800f46ae.png)
