### ISSUE TITLE
Self Voice not Goes to Audio Output of Stream

### ISSUE THREAD

**Issue by daniloferrari** [renpy/renpy#2098]
I'm vissually impaired streamer.

I have a chat tts reader, because that, I use Virtual Audio Cable to hide the app voice.

Playing visual novels made in Ren'py, wen I set the audio game to audio output of the stream, self voice reading no go tho the same output. On the stream, plays just the normal sound of the game.

Wold be god, if the self voice goas to the seme output of the game, or, have an way to set their output.

Thanks.

**Comment by renpytom** [comment]
Hm...

I really don't have a lot of control of where the output of the tts goes. It depends on what platform you're on, but if you're on windows, Ren'Py does text-to-speech by passing the text to the windows SAPI (speech API), and that is what you're actually hearing. 

You might be able to use VAC to divert SAPI somewhere else. You can also use shift+A to get access to the accessibility menu, and then choose clipboard voicing to better integrate with screenreaders.

**Comment by daniloferrari** [comment]
I tried SHIFT + A, but for me is not working.

But by star menu, went to Narrator Voice configs and change de output of speek for de correct device. Not worked.

I not use screen readers, because I'm low vision, use magnification and high contrast.

Voice is used in situations like that to long text.

Searched in mi computer, but not capable to find Sisten Voice Settings. Windows used to have...

Now trying to find a way to put sistem sounds to VAC, to se if solves.

**Comment by daniloferrari** [comment]
In Apps Volume, tried to change output of systen sounds. Bot in the two dropdow menus, is not possible to change.

In narretor seting tried to change speed of voice, but not iterfered in self-voice.

Because this, I'm thinking that is a thing separate of narrato. But systen voice settings desapeard.

In speach setings, when we set voice comand, can change voice speed, but not aplly to self voice.

Confused now.

**Comment by renpytom** [comment]
Sure. Unfortunately, this is entirely a Windows thing - other than asking Windows to perform TTS, Ren'Py isn't involved. There is a limited amount of help I can give you, as I don't have detailed knowledge of how Windows TTS works.
