### ISSUE TITLE
Text Interpolating Data - 2 Variables from Object

### ISSUE THREAD

**Issue by xxSithRagexx** [renpy/renpy#2113]
It appears that Renpy does not preform as expected while interpolating data in Say() text when using two variables form an object:

`"The current time of day is [myObj.day_times[myObj.current_time]]" = "The current time of day is [myObj.day_times[myObj.current_time]]"`

The causes the interpolating to fail, and my raw text is displayed on the screen. However, if one of myObj.current_time is replaced with 0, it will show the proper value of the index.

`"The current time of day is [myObj.day_times[0]]" = "The current time of day is Morning"`

If I bracket myObj.current_time it will display the value as expected:

`"[myObj.current_time]" = "0"`

There is either a trick not explained in the documentation, the above should work according to the example, or there is a bug in the code that causes references to object values within a list index to kill interpolation.

**Comment by renpytom** [comment]
Double interpolation like that is not supported. Interpolating with a constant is. Please check out the python documentation for str.format, which is what Ren'Py uses.

**Comment by xxSithRagexx** [comment]
> Double interpolation like that is not supported. Interpolating with a constant is. Please check out the python documentation for str.format, which is what Ren'Py uses.

Interesting. If I were to use str.format(), it I could get my results by: "This is what I want: {}".format(myList[listIndex]).

Is there a Ren'Py equivalent since it uses str.format?

**Comment by renpytom** [comment]
Just use a temporary variable to store the results of the expression.
