### ISSUE TITLE
Please remove renpy's vendored libs from LD_LIBRARY_PATH before trying to call programs that are not part of the renpy distribution

### ISSUE THREAD

**Issue by fluffymormegil** [renpy/renpy#2116]
Vendoring zlib in your Linux binary package turns out to break attempts to call external programs like web browsers and file managers:

```
thunar: /home/mormegil/tools/renpy-7.3.5-sdk/lib/linux-x86_64/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/x86_64-linux-gnu/libpng16.so.16)
```

(the above triggered when I tried to browse a directory from the launcher)

```
XPCOMGlueLoad error for file /usr/lib/firefox-esr/libmozgtk.so:
/home/mormegil/tools/renpy-7.3.5-sdk/lib/linux-x86_64/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/x86_64-linux-gnu/libpng16.so.16)
Couldn't load XPCOM.
```

(the above triggered when I clicked "Documentation" in the launcher)

Please remove your vendored libs dir from LD_LIBRARY_PATH before trying to call system programs. (Also, for the love of bod, why are you vendoring zlib on Linux? We're pretty much guaranteed to have zlib installed, and even Debian stable has a newer one than the one you're shipping.)

**Comment by renpytom** [comment]
This will be taken care of in the next release. 

As for zlib, it's because the same libraries and versions are used on all platforms, and while a libc is always there, zlib is often not.
