### ISSUE TITLE
Use Black as a code formatter

### ISSUE THREAD

**Issue by GimmiRuski** [renpy/renpy#2119]
I've created a test branch and made a commit [here](https://github.com/GimmiRuski/renpy/commit/36312bdecc39f1d0888650914f65306bdd46eff3) using [Black](https://github.com/psf/black) to see how the code looks like after formatting it.

Line length is configurable. In the test commit I didn't pass any parameters, so the default length is 88 characters as stated [here](https://github.com/psf/black#command-line-options).

For files like [this](https://github.com/GimmiRuski/renpy/blob/36312bdecc39f1d0888650914f65306bdd46eff3/sphinx/source/keywords.py) one, if formatting is not desired, the statement `# fmt: off` could be used as explained [here](https://github.com/psf/black#the-black-code-style).

If the idea sounds good, I'll take care of creating different pull requests, each formatting a small section of the code base, allowing for an incremental review of the changes. Also, I could try to integrate this as GitHub actions for the main repo and pull requests.

What do you think?

**Comment by renpytom** [comment]
I have a feeling that a tool that describes itself as "uncompromising" is not something I'd like to use. I'll show as an example:

https://github.com/GimmiRuski/renpy/commit/36312bdecc39f1d0888650914f65306bdd46eff3#diff-0eb50146ed6d2632ca8e8e6abbd76550L271

I also tend to like spaces between the parenthesis that define a dict, list, or tuple and the contents of that tuple. Some other tool (YAPF is linked from Blacks page) that is more configurable, and able to address partial files, might be more appropriate. 

Thanks.

**Comment by GimmiRuski** [comment]
You're right, some of the formatting results are not the best.

But, if you like the idea of using a code formatter, I could try to look into the one you suggested and see if I can write down a configuration file that conforms with the current code style of the repository.
