### ISSUE TITLE
When deleting the newest savefile, "Yes" button always being selected

### ISSUE THREAD

**Issue by zedraxlo** [renpy/renpy#2120]
So, in file 00action_file.rpy, line 512 and 513 should be delete or change to:

def get_selected(self):

     if not self.confirm:
         return False
     return __newest_slot() == __slotname(self.name, self.page, self.slot)

**Comment by renpytom** [comment]
(Has this been fixed or merged in? I realize that I haven't had a release cycle in a while, but I'll still get to this.)
