### ISSUE TITLE
Doesnt run RenPy 7.3.5

### ISSUE THREAD

**Issue by DrKirsan** [renpy/renpy#2136]
Hi, after update win10 or after update i have a trouble to open RenPy.exe. When I open it the proccess run and stop. Here log file.
[log.txt](https://github.com/renpy/renpy/files/4334277/log.txt)
Why it runs with support win8?

**Comment by renpytom** [comment]
I can't really help with this, as some other program is causing Ren'Py to crash. Look for things like antivirus programs and 'game optimizer' programs, as they have historically been the cause of this crash. They claim to make your computer better, but change things in a way that breaks stuff. 

The Windows 8 thing is a red herring - there isn't enough of a difference between 8 and 10 to be worth detecting.

**Comment by DrKirsan** [comment]
fix it by installing OpenAL
