### ISSUE TITLE
Problem with screen as modal

### ISSUE THREAD

**Issue by ratalaika** [renpy/renpy#2137]
Hello,

We're working adding gamepad support to a game and for some reason when pausing the game the menu bellow is still accesible with dpad or left stick even thought the screen has been set as modal.
Also  opening the options screen doesnt have "focus test" highlighted by default, default_focus doesnt do anything.
If you're opening it from the main menu, the "options" button from the screen below is still focused

Repro project:
https://www.dropbox.com/s/wa7garo4ko1z8uj/focustest-1.0-pc.zip?dl=0

Steps:
1. Open
2. Press ESC
3. Select any slow and press down key on keyboard and you will see Auto get's selected

Thank you very much.

**Comment by renpytom** [comment]
Sorry about the delay, iOS was a problem.

This should be an easy to backport fix. However, in your repro, the options screen was below the quick menu, so the modal didn't apply. (Modal only applies to screens below the modal one.) To make this work, it probably makes sense to change the options screen's zorder to 101 or larger.
