### ISSUE TITLE
with statements after call screen behaving

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2139]
Given the following screen :
```
screen whatever:
    textbutton _("Continue") action [Return()]
```
The following code makes the screen disappear immediately after the click on the button, then waits 3 seconds, then shows the say dialog :
```
call screen whatever with None
with Dissolve(3)
e "hey"
```
Which is a contradiction to the last paragraph of [this section](https://www.renpy.org/doc/html/screens.html#call-screen) of the doc.

Furthermore, the following unexpectedly works exactly as the doc's specifications says :
```
call screen whatever with None
with fade
e "hey"
```

**Comment by Andykl** [comment]
It's controlled by `config.implicit_with_none`. If it's True - Ren'py did a hidden with None after each interaction. You may disable it in general by set this to False or just in case with `call screen whatever(_with_none=False) with None`
