### ISSUE TITLE
Loading Screen / Ability to get the files being loaded by Ren'Py

### ISSUE THREAD

**Issue by hell-oh-world** [renpy/renpy#2144]
Would it be cool to allow the users to create loading screen that is literally based on how Ren'Py loads things such as audios, images etc.? I mean this sounds like a lost cause, because of how Ren'Py works (screen prediction etc.). Anyways, these are the expected outcomes:

1. For Visual Novels with chapters or episodes, having something like `episode_x_assets_to_load.rpy` which contains the assets that are needed for the scripts of `episode x`.
2. The said `rpy` files will enable the devs to get the total number of files that are needed to be loaded.
3. With the total number of files, the devs can use this with regards to the loading progress.
4. Having the ability to determine the current asset being loaded in the said `rpy` file and to determine the number of files already loaded can be used as an indicator for the current loading progress.
5. Together with the total number of assets that needed to be loaded plus the current number of assets already loaded, a proper loading progress can be made before each start of episode or chapter of vns.

With this kind of process, a per stage loading can be made, unlike those games that load it all at once. Which simply means a nice looking progress detail for each stage of the vn 😉 .

**Comment by renpytom** [comment]
Is this a proposed pull request, or a feature request? 

I could certainly see something like - an API that compares the prediction cache with forced predictions. That being said, I'm not totally sure why this would be superior to Ren'Py's existing approach. Aren't loading screens something from the bad old days?

**Comment by hell-oh-world** [comment]
Well, I'm not really saying that this is superior to RenPy's approach. You could prolly consider this a more intuitive way displaying things about renpy's behind the curtains workflow. Users will be aware, especially players on what's currently happening. I guess this is prolly useless if you have a minimal amount of assets and low file sizes for each, as RenPy will load them in a breakneck manner. But if you have large-scale games, such as those episodical ones, this could be used to give information to users rather than making the game stutter or doing nothing while it loads things. Hope it made sense. Thanks, @renpytom , and yeah this could be more like of a feature request, as I am a dev and fan of the engine. 😉

**Comment by renpytom** [comment]
The thing to realize is that the player is limited by how fast they can read, and so in general, Ren'Py should be able to keep up. It actually predicts what the player could be looking at in the future, and loads that before the player actually gets to that. There's an article (now free) on my patreon that describes how to diagnose issues with prediction. 

I don't think that "triple-A" games have loading screens because they're good. They're there because the companies that make them have priorities other the fluidly streaming game assets. And, to be fair, because other genres are harder to predict than visual novels are. 

So I don't think I'll be adding loading screen support. Ren'Py games - even big ones - shouldn't need them.

**Comment by hell-oh-world** [comment]
So the predictions happen as you gradually interact? Would that also mean more chance of having _stutters or lags while **in-game**_ because it tries to load things for future interactions? I mean, having a game that doesn't yield a single lag or stutter while it is being played is much more fluid than having gameplay that makes you stop intermittently because of the loading happening at the same moment as you play it? I guess this would make more sense if the game has a big chunk of assets that are needed for the next interaction, as RenPy might slow down before that interaction to load things up, no?

The thing is, what I'm trying to say is to save users or players from unexpected stutters or lag due to the prediction system of the game and to just collect or group the scattered loading of assets around the game into a single moment of loading of assets, which will happen before the current gameplay happens. In that way, players will have continuous gameplay as the assets were already loaded for the entire gameplay. To be honest, this sounds more fluid to me, I mean, no offense of course.

**Comment by uyjulian** [comment]
Image loading occurs on a different thread.
