### ISSUE TITLE
Not running in macOS Catalina 10.15.3 (without going into package files)

### ISSUE THREAD

**Issue by Lisette12** [renpy/renpy#2145]
For anyone with the same problem as me and needs a quick solution:

1. open package contents of renpy
2. go to Contents/MacOS/renpy
3. run that

why this works? IDK

For the people who fix bugs and stuff:

clicking on the application does not cause renpy to run but clicking show package contents and running renpy the unix executable causes renpy to run normally. this is annoying to do every time I want to run renpy. renpy ver is 7.3.5.606 downloaded from renpy website. also terminal posts this when I run it by unix executable , might be related?

```
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
```

Idk Im not a coder just made this account to post this. pls fix

**Comment by uyjulian** [comment]
Did you disable app translocation?

**Comment by Lisette12** [comment]
the what? I have no idea what the heck that is. Should I do that?

**Comment by rdurfee** [comment]
Did you drag the renpy-sdk folder into your Applications folder? It won't run if it's not in Applications.
