### ISSUE TITLE
Blitting a render onto another render renders at a wrong size

### ISSUE THREAD

**Issue by altskop** [renpy/renpy#2152]
Hi!
Came across a weird issue I'm not able to troubleshoot so figured I'd post it here.

I made a UDD class for a rectangle with borders of a different color. It's done by first rendering a Solid the color of borders, then another Solid (rectangle color) and blitting the latter onto the former. In the end I expect to end up with a first render containing the second one.

Here's the code for the render method:

```
def render(self, width, height, st, at):
     # Create a render for a solid to be act as a base layer
      frame_solid = Solid(self.secondary_color, xsize=width, ysize=height)
      r = renpy.render(frame_solid, width, height, st, at)
      # print(r.width, r.height) >> 1280, 720

      # Create another render for a solid to be placed on top of base
      # self.border_size in this test is 2 
      inner_solid = Solid(self.color, xsize=width-self.border*2, ysize=height-self.border*2)
      inner_r = renpy.render(inner_solid, width-self.border*2, height-self.border*2, st, at)
      # print(inner_r.width, inner_r.height) >> 1276, 716

      r.blit(inner_r, (self.border, self.border))
      # print(r.width, r.height) >> 1280, 720

      return r
```

The problem is that during the blit, the second render seems to be drawn at a wrong size (too large). It overlaps the bottom/right sides of the base layer.

While troubleshooting, I have played around with size values of the second render to see if they make a difference. Once I went under 10 pixels in height or width, the second solid became considerably smaller (but still not at a 10 pixel size).

Here are two screenshots of the two cases I was able to get to:

[Second render (black) too large for first render (red)](https://i.imgur.com/Jno1s3B.png)

[Second render is supposed to be drawn at 1px width & height but is still wrong size](https://i.imgur.com/di3RgwY.png)

Either I'm not understanding how blit() is supposed to work, or it is bugged. Either way, I would appreciate any pointers in finding a workaround of perhaps even a solution.

**Comment by Andykl** [comment]
```
class BordersFrame(renpy.Displayable):

    def __init__(self, primary_color, secondary_color, xborder, yborder, **properties):
        super(BordersFrame, self).__init__(**properties)

        self.primary = Solid(primary_color)
        self.secondary = Solid(secondary_color)

        self.xborder = xborder
        self.yborder = yborder

    def render(self, width, height, st, at):

        primary_r = renpy.render(self.primary, width, height, st, at)
        secondary_r = renpy.render(self.secondary, width - self.xborder * 2, height - self.yborder * 2, st, at)

        render = renpy.Render(width, height)

        render.blit(primary_r, (0, 0))
        render.blit(secondary_r, (self.xborder, self.yborder))

        return render
```
This what you need. 
`Solid.render` under the hood makes a texture of 10x10 pixels and extends it to a given size. If you blit something else in that Render, it will be extended with it.
So you create a separate Render object on which you blit the first and then the second. This object will not care what children renderers do with self.
