### ISSUE TITLE
how can i print chinese in console

### ISSUE THREAD

**Issue by luul11** [renpy/renpy#2153]
using renpy,i need to show printing chinese information in console.
But it always shows unintelligible text.
![image](https://user-images.githubusercontent.com/27540770/78519996-96de4d00-77f7-11ea-8360-087d2b8cbf99.png)

**Comment by renpytom** [comment]
Make sure your terminal is set to utf-8. If you can't do that, ignore the windows console - set gui.interface_font to something that supports Chinese, and then use shift+O to access the console to see it.

**Comment by luul11** [comment]
![image](https://user-images.githubusercontent.com/27540770/78520629-d9a12480-77f9-11ea-9f6d-99a29b90c107.png)
I HAVE ALREADY changed the fonts.
But how can I make the py environment to use UTF-8?
In fact,I used to use python 2.7 or 3 ,by the statement'coding= utf-8'.But it doesnot work in renpy.
And I cannot use shift+O while i start the game.
Two days ago,I could use shift+O ,and now it doesnot work.

**Comment by renpytom** [comment]
I don't know how to solve the console text encoding. 

I'd suggest figuring out why shift+O doesn't work.

**Comment by luul11** [comment]
Debugging game without shift+O  is really very difficult.I have to restart the game again and again.And  I have to restart the game form the start of the game. So have anyone meet the same problem?

**Comment by luul11** [comment]
I have overcame the problem.
It is the inputting method fault
