### ISSUE TITLE
webp presplash image?

### ISSUE THREAD

**Issue by Beuc** [renpy/renpy#2157]
I'm contemplating adding support for "web-presplash.webp", which would incidentally allow animated presplash (e.g. https://mathiasbynens.be/demo/animated-webp-supported.webp) in RenPyWeb.

However I remember that web-presplash.gif support proposal was met with strong opposition ;) IIRC due to color limitations, which wouldn't be the case for webp.

What is your take on this?

**Comment by renpytom** [comment]
I'm fine with it.

**Comment by Beuc** [comment]
Thanks. I pushed f7d8fea29c47078307a32a9412a0c89dc1b962b9 with a default classification change.
I considered adding .webp alternative to presplash.png, but realized we would also need to change android-presplash.* and ios-presplash.*, so I didn't. Let me know if you want to me to harmonize this across all platforms.
