### ISSUE TITLE
Graphics acceleration detected only on second instance of game

### ISSUE THREAD

**Issue by Phr33d0m** [renpy/renpy#2162]
Hi, I've been having this issue since ever. When I launch any renpy game (it happens with ALL games, including the SDK) the first time, I get the "no graphics acceleration" window. If I open the game again (*without closing the first instance/window*) it correctly catches the graphics acceleration and works flawlessly.

I have to do this "open-2-times" every single time, which makes no sense - as, at some point, renpy **does** detect I have graphics accel.

Short video displaying the issue:
https://0x0.st/iQXo.mp4 or https://transfer.sh/14Zdm3/renpybug.mp4

OS: Linux (Arch x64)
GFX: nvidia 970 (binary nvidia drivers 440.80)
DE: Plasma

**Comment by renpytom** [comment]
Can you grab a log.txt from when it fails?  That will be created in the folder with renpy.sh.

**Comment by Phr33d0m** [comment]
@renpytom Of course, let me get you both instances' log files.

[log-1st-instance-noaccel.txt](https://github.com/renpy/renpy/files/4478478/log-1st-instance-noaccel.txt)
[log-2nd-instance-yesaccel.txt](https://github.com/renpy/renpy/files/4478479/log-2nd-instance-yesaccel.txt)

I'm guessing something with testing the textures is failing the 1st time:
```- Incorrect pixel color in 64px texture: (2, 2, 2)```
But works the 2nd time:
```- 64px textures work.
- 128px textures work.
- 256px textures work.
- 512px textures work.
- 1024px textures work.
- 2048px textures work.
```

**Comment by renpytom** [comment]
I believe the gl2 renderer won't have this problem, so closing this.
