### ISSUE TITLE
Doc not clear about defining/defaulting/initing persistent variables

### ISSUE THREAD

**Issue by xavi-mat** [renpy/renpy#2166]
The `persistent` section of the doc ( https://renpy.org/doc/html/persistent.html ). Does not talk about how to initialize them. (There has been some questions about it on discord). If there is no difference with `default, define, init` for `persistent` variables,  probably a sentence like this will be enough: "persistent variables can be initialized with `default`, `define` or in an `init` block"). If *there is* a difference, or a best practice, I think it should be explicit.

According to the changelog on version 6.99.7, 

> “The define statement can now be used to define [...] persistent variables”
https://www.renpy.org/doc/html/changelog.html#define-improvements

That information is nowhere to be found on the doc sections about persistent or define.
Moreover, those sections contain expressions that I find confusing:

> “Variables that are defined using the define statement are treated as constant, are not saved or loaded, and should not be changed.”
https://renpy.org/doc/html/python.html#define-statement

Persistent variables will be changed somewhere (I'd suggest adding: "except persistent variables").

> “Variables that have their value set in an init python block are not saved, loaded, and do not participate in rollback. Therefore, these variables should not be changed after init is over.”
https://renpy.org/doc/html/python.html#init-python-statement

Again, persistent variables will be changed. (the same suggestion: "except persistent variables").

**Comment by Gouvernathor** [comment]
Well, since persistent variables are supposed to be changed, the very quote you take from the doc infers the conclusion that affecting values to persistent via `init` or `define` serves no purpose.

That being said, documenting the `default persistent.x` behavior could be considered.
