### ISSUE TITLE
Can't use "draggable" option in viewports with imagebuttons.

### ISSUE THREAD

**Issue by Komisari** [renpy/renpy#2167]
As the title says, I have a viewport with a _draggable,mousewheel and edgescroll_ option.
Inside the viewport, there is a hbox with only imagebuttons.

I can use the edgescroll and mousewheel to scroll in the viewport. But I CAN'T drag the image to scroll WHILE the mouse/finger/cursor is on the imagebuttons. If they're not in the imagebutton, I can drag it.

I've tried with a vpgrid, same result!

**Comment by Andykl** [comment]
This refers to #1872. 
This change requires a review of how the focus works, because the moment the button is clicked is considered to be the focus, but if the action is ignored the focus must go to viewport, and Ren'Py does not have the focus transfer functionality.

**Comment by renpytom** [comment]
I believe the appropriate changes have been made, and this has been resolved.

**Comment by LaytaLoiselle** [comment]
> I believe the appropriate changes have been made, and this has been resolved.

Hi! I'm on it, did you find a solution? I'm completely stuck on this issue.

**Comment by renpytom** [comment]
Have you tried it in the nightly builds of 8.1? It should be fixed there.

**Comment by LaytaLoiselle** [comment]
I'm on the latest version (8.0.3) but maybe I have to play with focus properties?

**Comment by renpytom** [comment]
The nightly builds of 8.1 are newer than 8.0.3. You can try them out at https://nightly.renpy.org.

**Comment by LaytaLoiselle** [comment]
Wow ok yes it works! Big thanks !
