### ISSUE TITLE
Games start with value 'zoomout' on variable "i"

### ISSUE THREAD

**Issue by xavi-mat** [renpy/renpy#2172]
https://github.com/renpy/renpy/blob/f937f4bf42df420397090ddb7cf7b1aafdf27efa/renpy/common/00library.rpy#L300

In a new game, the variable `i` starts with the value `'zoomout'`.

**Comment by jsfehler** [comment]
There's no block scoping in Python, but there is an i in Ren'Py, apparently.

Add a `del i` after that loop and the problem is solved.
