### ISSUE TITLE
Special characters in Android "short name" cause non-obvious error

### ISSUE THREAD

**Issue by kdhunter** [renpy/renpy#2173]
If, when specifying the "short name" for your Android game, you include an ampersand character (&), your build will end up failing with a non-obvious error about "S needing to end with a ; character" in rapt\project\app\src\main\res\values\strings.xml.  The specific line it complains about is the one for <string name="iconName">...</string>

I would suggest that some filtering be introduced into the launcher to prevent the user from entering characters that are going to cause problems with the short name, or else the short name should be appropriately "escaped" when building strings.xml so that error does not occur.

**Comment by renpytom** [comment]
This was fixed by renpy/renpy-build@9042df24092c96f514dd3810f37de7759f08b3bd .
