### ISSUE TITLE
master no longer respects `config.use_cpickle`, but still documents it

### ISSUE THREAD

**Issue by mathrick** [renpy/renpy#2175]
52e447f8b7 has removed all the code which respects the `config.use_cpickle` flag. Either it should be reinstated, or the docs should be updated to remove the mention of that config flag (or, even better, mention that there *used* to be a flag, but it's been removed), and the release notes should point that out as an incompatible change.

**Comment by langbakk** [comment]
Where is it documented? Couldn't find it in https://www.renpy.org/doc/html/config.html

**Comment by Andykl** [comment]
https://www.renpy.org/doc/html/save_load_rollback.html?highlight=use_cpickle#what-ren-py-can-save

**Comment by renpytom** [comment]
That should probably go away, but the master branch is still very much a work in progress. Since cPickle isn't in Python3, and the goal of the master branch is to work with python 3 (It's not competely there yet), it had to be eliminated.

**Comment by mathrick** [comment]
@langbakk: It's mentioned in two places -- one [in the docs](../blob/master/sphinx/source/save_load_rollback.rst#what-renpy-can-save), other in [config.py](../blob/master/renpy/config.py#L320).

@renpytom: `six` exposes cPickle [compatibility module](https://six.readthedocs.io/#module-six.moves) though. The old code was using it, and it will continue to work fine on Python 3. Unless `master` is going to drop Python 2.x compatibility entirely, which doesn't seem to be the intent from reading that commit, there's no reason to remove that setting, because it's still very important for debugging on Python 2.x. The docs should add a note that it doesn't do anything on Python 3, but otherwise bring the old code back. I can whip up a PR for that.

**Comment by mathrick** [comment]
Ah, I get it now, you're moving away from `six` to use `future` instead. Since it's trivially fixed in `renpy.compat` without using `six`, I just made the PR do it that way.
