### ISSUE TITLE
Need help: Problem in using the show statement for atl

### ISSUE THREAD

**Issue by RyanSP-main** [renpy/renpy#2178]
I have recently started using Ren'py and I have encountered a major problem:
My script involves the use of this label-
label astro:
    image blinky:
        "ast1.png"
        0.3
        "ast2.png"
        0.3
        repeat
    show blinky at left
    return
That is used by the statement- call astro which is inside the Start label
My program has a condition in which the program finally jumps to the Start label again
However I encounter this error:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 88, in script call
    call endgo
  File "game/script.rpy", line 70, in script
    show ast1 at left
TypeError: 'unicode' object is not callable

Is there some error in my code? How can it be fixed?

**Comment by RyanSP-main** [comment]
ast1.png is in another condition statement when it returns back to main menu

**Comment by vollschauer** [comment]
Please use the forum for your question...
https://lemmasoft.renai.us/forums/viewforum.php?f=8

**Comment by Andykl** [comment]
It seems you have `left = "some string"` somewhere in your code. Not a Ren'Py bug.
