### ISSUE TITLE
config.allow_skipping isn't working

### ISSUE THREAD

**Issue by d4v1do** [renpy/renpy#2182]
I wanted to use "config.allow_skipping" to prevent the user from skipping important events. But it does not work. I should probably mention that this is all done in the splash screen. But does that have something to do with it? I hope someone can help me.

**Comment by Andykl** [comment]
config.allow_skipping is configuration variable to enable or disable skipping in general.
Note:
```
Ren'Py's implementation makes the assumption that, once the GUI system has initialized,
configuration variables will not change. Changing configuration variables outside of
init blocks can lead to undefined behavior. Configuration variables are not part of the 
save data.
```

The thing you need is `_skipping` store variable. https://renpy.org/doc/html/store_variables.html#var-_skipping
```
label some_event:
    $_skipping = False
    your event
    $_skipping = True
    return
```
Please use the forum or Discord channel for your questions in future. GitHub used for bugs and issues for Ren'Py itself.
https://lemmasoft.renai.us/forums/viewforum.php?f=8
https://discord.gg/6ckxWYm

**Comment by d4v1do** [comment]
Sorry for blocking the forum. The problem: `$_skipping = False/True` does not work either. I had put my last hope on the config command, because otherwise I had already exhausted everything.

**Comment by renpytom** [comment]
What are you trying to do, exactly? Skipping is generally disabled in the splashscreen.

**Comment by d4v1do** [comment]
I want to prevent the user from skipping pimages. Here is a simplified version of my code:
```
label splash:
    $_skipping = False
    scene black
    with Pause(1)
    play sound click
    show logo with dissolve
    with Pause(3)
    hide logo with dissolve
    $_skipping = True
    return
```

**Comment by renpytom** [comment]
You probably want to use 

```
$ renpy.pause(1)
```
rather than 

```
with Pause(1)
```

The latter advances through all of the images with a single click. Clicking isn't considered "skipping" in the sense that's being used here, it's normal advancing of the game.

**Comment by d4v1do** [comment]
Thanks a lot for your help! And again sorry for blocking the forum.
