### ISSUE TITLE
Game fails to start correctly in fullscreen mode

### ISSUE THREAD

**Issue by jtakeshi-nd** [renpy/renpy#2183]
Issue is with National Park Girls (https://store.steampowered.com/app/1036580/National_Park_Girls/). System is Ubuntu 18.04, using nvidia-435 drivers. GPU is GeForce 1050Ti. Ren'Py version is 7.3.4.596.

May be related to https://github.com/renpy/renpy/issues/2162 .

Upon opening the game in fullscreen mode, a warning is shown: 
![renpy_error](https://user-images.githubusercontent.com/55858598/80636993-49d34c80-8a2c-11ea-92da-0c40e6b12550.png). After proceeding, the game loads, but graphics are incredibly slow (much worse than on my laptop with only integrated graphics), and some things don't even show up properly.

The log indicates this error: 
Incorrect pixel color in 64px texture: (0, 0, 0)

I believe the error originates from line 222 of https://github.com/renpy/renpy/blob/master/renpy/gl/gltexture.pyx . 

A workaround is to start the game in windowed mode - the game works fine in that case. One annoying part of this bug is that the button to switch to windowed mode will not render properly, but F11 was able to knock the game into windowed mode. As long as the game is closed in windowed mode, it will restart in windowed mode.

This issue was not present on my laptop (also Ubuntu 18.04, but no GPU), nor on the original computer running Windows, nor in other Ren'Py games (Katawa Shoujo, Highway Blossoms, Doki Doki Literature Club!). Error persisted with downgraded graphics drivers (nvidia-430).

Attached is a log file, along with a log file from a successful run.

[log.txt](https://github.com/renpy/renpy/files/4554083/log.txt)
[log_working.txt](https://github.com/renpy/renpy/files/4554084/log_working.txt)

**Comment by tomu123** [comment]
I have exactly the same error. When i restart my laptop, it works fine but after some time i close the game and open it graphics are slow and image of saving files in-game are bluish.

**Comment by jtakeshi-nd** [comment]
Same issue is present with First Snow (https://store.steampowered.com/app/1259430/First_Snow/), workaround is the same.

**Comment by SmoochySix4** [comment]
Is there a fix for this? Still having the issue when trying to play in full-screen mode.

**Comment by renpytom** [comment]
This has been fixed in the gl2 renderer, which is now the default.
