### ISSUE TITLE
Global variable declared in INIT block not found in INIT PYTHON block.

### ISSUE THREAD

**Issue by newbiemate** [renpy/renpy#2186]
Here is a sample to demonstrate the problem.

```
init 1:
    default MONEY = 0
    default NAME = "BOB"


init 2 python:
    
    
    MONEY = 100
    TOGETHER = "MARY and %s" % NAME
    
label start:
    $ renpy.say("bob", "Hey, check out my %s, says %s" % (MONEY, TOGETHER))
```

**The error I receive is:**
```
TOGETHER = "MARY and %s" % NAME
NameError: name 'NAME' is not defined
```

When the `init 1` block runs, it should set the global variables, so by the time `init 2 python` runs, it should be able to use those globals in the `TOGETHER` statement?

---
Is this a bug or expected behavior? If the latter, how would I reference the global declared in the init block inside the python init block?

Using renpy  7.3.5

**Comment by gejang** [comment]
Just an additional note, this also does not work with the same error above:

```
default MONEY = 0
default NAME = "BOB"

init 999 python:
    
    global MONEY 
    
    MONEY = 100
    TOGETHER = "MARY and %s" % NAME
    
label start:
    $ renpy.say("bob", "Hey, check out my %s, says %s" % (MONEY, TOGETHER))
```

**Comment by Andykl** [comment]
Default statement actually doesn't execute in init time. It mean this variable doesn't exists before real script run (splashscreen is the first label where it's exists). Probably you need use define statment.

**Comment by newbiemate** [comment]
@Andykl 

Using the `define` statement works... but I thought `define` was used for declaring variables as a CONST (they do not change). Whereas `default` is used for when the variables will change. 

Is this still the rule?

**Comment by newbiemate** [comment]
I'll just close this issue and use hardcoded values for now. It would be nice if there was a code style guide on using default/define though.
