### ISSUE TITLE
The `at transform` syntax doesn't get recognized inside a custom screen statement.

### ISSUE THREAD

**Issue by hell-oh-world** [renpy/renpy#2187]
I'm trying to implement a custom screen statement using the `renpy.register_sl_statement` class. The code is working well, except that any anonymous `atl` doesn't get passed. So this is somehow my code looks like:
```py
# in a file something like 01early.rpy
python early:
    renpy.register_sl_statement("my_statement", positional=0, children="many").add_property_group("ui").add_property_group("position")
```
```py
# the screen statement screen
screen my_statement(**properties):
    frame:
        properties properties
```
```py
# implementation in other screens
screen sample:
    my_statement:
        background "#f00"
        at transform:
            alpha 0.5
```
Pytom said that the `at transform` or the anonymous atl is kinda new in Ren'Py. This thing works if an ordinarily defined transform is used rather than an anonymous one, unfortunately, even though it's passed by printing the contents of `properties`, the atl doesn't map itself using the `properties` UI statement. In a short note, anonymous atl doesn't get passed, defined atl, on the other hand, gets passed, but it just won't be mapped by the `properties` statement unless you explicitly tell it to by using conditionals like this...
```py
# the screen statement screen
screen my_statement(**properties):
    frame:
        properties properties

        if "at" in properties:
            at properties["at"]
```
This one works, as long as the atl is defined and not an anonymous one.
Another thing to note is that I observed that you can't do a direct anonymous atl inside the screen statement, so...
```py
# the screen statement screen
screen my_statement(**properties):
    frame:
        properties properties

        at transform:
            alpha 0.5
```
This one won't work, but if the transform specified is defined, then the transform will be recognized.

**Comment by Andykl** [comment]
Thank you for your response. I'll check it when I get a chance.

**Comment by Andykl** [comment]
This issue should be fixed in next nightly build.
