### ISSUE TITLE
Pass image tags to ImageDissolve

### ISSUE THREAD

**Issue by dogtopus** [renpy/renpy#2192]
It would be nice to have `ImageDissolve` resolving image tags defined by `image` statement automatically. Doing so will also provide more consistency since other features like the `add` statement in screen language happily accepts a string that contains image tags.

Currently I can do `ImageDissolve(renpy.get_registered_image('mask test'), ...)` but that's a lot messier than `ImageDissolve('mask test', ...)`.

**Comment by Andykl** [comment]
This is not possible at the moment because the "mask test" is not an image manipulator, but a ImageReference. 
But after a full transition to GL2, this can be changed to the use of general displayable.

**Comment by Gouvernathor** [comment]
Fixed by #2427
