### ISSUE TITLE
ConditionSwitch doesn't properly display some repeating animations

### ISSUE THREAD

**Issue by GiovanH** [renpy/renpy#2193]
I'm trying to display an animation with an option for a reduced-motion version. The animations work independently, and work if they're shown using `if` statements inline, but they don't properly work when using a ConditionSwitch object.

See this example code:
```renpy
transform psionicoverlay_flash_template(fadedur=1.0):
    contains:
        "#F20000"
        alpha 0.0
        linear fadedur alpha 0.22
        linear fadedur alpha 0.0
        repeat

    contains:
        "#003BFF"
        alpha 0.22
        linear fadedur alpha 0.0 
        linear fadedur alpha 0.22
        repeat

image psionicoverlay_flash:
    psionicoverlay_flash_template(fadedur=1.0)

image psionicoverlay_noflash:
    psionicoverlay_flash_template(fadedur=2.4)

image psionicoverlay = ConditionSwitch(
    "persistent.flash", "psionicoverlay_flash",
    "not persistent.flash", "psionicoverlay_noflash"
)
```

When shown, `psionicoverlay` should slowly strobe between red and blue, with a fade. Instead, it shows a transparent blue screen that does not repeat. `psionicoverlay_flash` and `psionicoverlay_noflash` both work fine independently.

**Comment by GiovanH** [comment]
This may be related to https://github.com/renpy/renpy/issues/1394, even though my code doesn't use transitions.

**Comment by Gouvernathor** [comment]
Cannot reproduce in last version of renpy.
