### ISSUE TITLE
Outlined dialogue text is glitchy when CPS is active

### ISSUE THREAD

**Issue by fullmontis** [renpy/renpy#2196]
Using Renpy 7.3.5.606

When the dialogue text is outlined and cps is active, parts of the lower lines show as the above line is being shown

This is indipendent from the line spacing, it seems.

![screenshot0050](https://user-images.githubusercontent.com/5768095/81992920-e3157c00-9644-11ea-9ddb-63c764ea5476.png)

The following is a script.rpy to replicate the bug

```
label main_menu:
    return

image bg = "#fff"

default preferences.text_cps = 20

style window:
    background None
    
style say_dialogue:
    outlines [(4, "#000")]
    line_spacing 30
    
label start:
    show bg
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    return
```

**Comment by renpytom** [comment]
Not a bug, exactly. Check out "Slow text concerns" here for details of what causes this and how to fix it. https://www.renpy.org/doc/html/text.html#slow-text-concerns
