### ISSUE TITLE
Android: Move keystore out of SDK directory and into project root

### ISSUE THREAD

**Issue by kdhunter** [renpy/renpy#2202]
Right now, because of the fact that Ren'py stores Android keystores inside the SDK area, instead of inside the project, it is more difficult than it should be to support multiple Android projects at the same time, or to update from one Ren'py SDK to a newer one.

Inside the Ren'py SDK `rapt/project/local.properties` file, there are two hard-coded paths:
```
key.store=<path to the key store inside the rapt directory>
sdk.dir=<path to the SDK directory inside the rapt directory>
```

Because the keystore is automatically created inside the Ren'py `rapt` directory (and always assumed to be located there) this means that if you are working on multiple projects with Android builds, effectively, you either need to use a different installation of Ren'py for each of your projects, or else you have to continually remember to go in and fiddle in the `rapt` directory when you switch projects.  This is a nuisance.  It's a particular pain when you want to update the Ren'py SDK, because you have to recover the original keystore, set up the new SDK, and then install the old keystore into the new SDK, and you have to do this separately on each SDK instance for each project if you've chosen the "separate SDK for each project" approach.

The main issue really appears to be the keystore, which, by definition, needs to be different for each project, yet which is being stored in a place common to all projects.  However, in addition, the `sdk.dir` option only seems to be set when you run `Configure` - if you move or rename the directory in which the (main) Ren'py SDK is located, the Android build will fail because the `sdk.dir` entry still points to the old location.  Everything else in Ren'py builds work without change after moving or renaming the main Ren'py directory - this should as well.  (This is a much less significant issue, since you normally run Configure for each build, but it stumped the heck out of me for a while when I reorganized my disk layout between builds.)

Suggestions for enhancement:

1. Separate out the "Create Keys" operation from the "Install SDK" options on the Android pane.  "Install SDK" should only need to be done once for a new Ren'py installation, while "Create Keystore" is a project-specific operation, and shouldn't be tied to setting up a new version of Ren'py.
2. Allow the "Create Keys" operation to create the keystore somewhere outside the SDK directory.  Ideally, it should be in the project root, just the way all the other project-specific files are.  In particular, if someone tries this operation and there's already one there, there should be dire warnings to make sure they know what they're doing.
3. If you can't just always assume the keystore is in the project root directory, then move the "memory" of where the keystore for a particular is into the .android.json file that's kept in the project root, and make specifying the keystore's location part of the "Configure" operation.
4. When you go to build an Android project, automatically set up the two paths in `local.properties` based on where the `rapt/SDK` directory is and where the keystore is without requiring any other user intervention.  If there's some hard technical reason that the keystore HAS to be in the SDK area, copy it in from whatever external place it's stored.

It seems to me that this will have the following advantages:

1. Putting the keystore in the project makes it way more likely that it will be saved.  Almost any operation (backup copies, git, whatever) that saves the project will save the keystore.
2. It will be far less likely for someone to overwrite their keystore.
3. You'll be able to share Ren'py SDK installations across Android projects the way you can with Mac and PC projects.
4. It'll be WAY easier to update to a new Ren'py SDK when you have Android projects, since all you'll have to do is (once) run the "Install SDK" operation.

To be perfectly frank, I would probably have designed it so that "Create Keys" was part of the "Configure" operation, since that's when you're setting up the information for a particular build.  Something along the lines of:
1. If the project already has a keystore in its root, just use it.
2. Otherwise, go through the "Create Key" portion, since you really DO need a key to do anything with an Android build.

This way, if someone really, REALLY needs to regenerate the keystore, they just delete the one in the project root.  Suppressing "Create Key" if there's already one there takes a foot gun out of the hands of developers.

Also, making it work this way might offer an opportunity to transition between "old system" and "new system" - if the keystore wasn't in the project, and if there was a keystore in the SDK area, the user could be offered the opportunity to either create a new project-specific one from scratch, or to copy the one from the SDK area into the project.  (Or, to skip the process entirely, I guess.)

Recognizing that this might take a while, in the interim, the https://www.renpy.org/doc/html/android.html page could be updated to document the location in which the keystore gets installed (so that it's easier for people to recover it and back it up) and the critical entries in the `local.properties` file so that more advanced users don't have to go grepping through all the files trying to figure out where things are stored.

**Comment by renpytom** [comment]
This has been finished in a series of commits.
