### ISSUE TITLE
Android: Provide a way to set the org.gradle.jvmargs value through the SDK

### ISSUE THREAD

**Issue by kdhunter** [renpy/renpy#2203]
There have been any number of posts on the forums of people who've had their Android builds fail due to an "out of memory" error.  The solution, of course, is to change the `org.gradle.jvmargs` setting in the `gradle.properties` file.

Unfortunately, this fact isn't documented anywhere.

1. In the longer term, it would be useful if one could set this value via the Ren'py Launcher.

2. In the short term, this fix could easily be documented on the https://www.renpy.org/doc/html/android.html page.  In particular, there are two copies of the `gradle.properties` file - one in `rapt/prototype` and one in `rapt/project`.  I'm guessing that one would want to set it in the `prototype` area, but since the internal process Ren'py uses to do an Android build isn't documented, I'm not sure.  It would be good to get "from the horse's mouth" documentation.

**Comment by renpytom** [comment]
The ability to set the memory usage has been in the launcher for a bit, so I'm closing this.
