### ISSUE TITLE
Nightly builds angle GLES fails on Windows.

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2206]
This fails on all angle, GLES, angle2, gles2 for both x32 and x64 variants with this log.
[log.txt](https://github.com/renpy/renpy/files/4653671/log.txt)
GL and GL2 runs fine.

**Comment by Andykl** [comment]
Still relevant for 6-13

**Comment by Andykl** [comment]
Still relevant for 6-27
[log.txt](https://github.com/renpy/renpy/files/4840861/log.txt)

**Comment by renpytom** [comment]
I believe that 043f7d0 fixes this.

**Comment by Andykl** [comment]
Now it starts the game, but always with the software renderer.
[log.txt](https://github.com/renpy/renpy/files/4847152/log.txt)

**Comment by renpytom** [comment]
Do you have working DirectX on your computer? Since this is a fallback,  I'm not including the DirectX redistributables with Ren'Py anymore. You'd have to install them to get it to work.

**Comment by Andykl** [comment]
Yes, I have DirectX and other applications are using it successfully. I can also successfully run 7.3.5 with Force DirectX.
I asked a colleague to run it, and he has the same error.

**Comment by Andykl** [comment]
Seems that fixed, library loading properly. As far I understand, #2349 is another bug.
