### ISSUE TITLE
Transition broken when given displayable w/ transform

### ISSUE THREAD

**Issue by SuperHatGuy** [renpy/renpy#2213]
I was planning to have an `AlphaTransition` that involved an **image displayable w/ transform** as control displayable. Said image displayable is supposed to simply move from right to left.

**The transition worked only once**; if used more than once, it simply got stuck in the new widget (due to the transform not _"resetting"_ every time the transition is used).
I decided to add a `repeat` statement in the transform, in hopes that it would fix it, and it mostly did, except for the fact that **after the transition ended, the old widget was showed for a split-second** (possibly due to the transform repeating a bit too early, despite it being supposed to finish at the same time as the transition does).

This is my transition definition:
```py
define feather_wipeleft_d0 = "images/transtest/0a.png"
transform feather_wipeleft_t:
    subpixel True
    xalign 0.0 yalign 0.5
    linear 2.0 xalign 1.0
    repeat # With or without this, it doesn't work properly.
define feather_wipeleft = AlphaDissolve(
    At(feather_wipeleft_d0, feather_wipeleft_t),
    2.0,
)
```

**Comment by renpytom** [comment]
Closing, since this has gone almost two years, and fell through the cracks. If this is still relevant, please re-open this issue.
