### ISSUE TITLE
OpenType CID fonts not displaying properly after fixing them through FontForge

### ISSUE THREAD

**Issue by Inui-senpai** [renpy/renpy#2217]
I'm using Ren'Py 7.3.5.606.

So, I'm trying to use some fonts of asian origin (in this issue I'll show only SkipStd, but this happens with any asian font). When I wrote original font file in character's string, it displaying properly, but cyrillic glyphs has abnormal spaces. After that I tried to fix these glyphs through FontForge, and this problem had disappeared, but spaces had changed on unknown glyph's symbol.

I also tried to use my fixed font file in game on another engine, and there this font was displayed correctly.

On this screenshot I'm using original SkipStd:
![Snap2768](https://user-images.githubusercontent.com/29918546/83328777-cf5a4e80-a2af-11ea-8a3d-a2a314972023.png)
On this screenshot is the same font, but with fixed cyrillic glyphs:
![Snap2769](https://user-images.githubusercontent.com/29918546/83328779-d08b7b80-a2af-11ea-99b4-815000b3ac06.png)
On this screenshot is the game on another engine, and there I was used a fixed font:
![unknown](https://user-images.githubusercontent.com/29918546/83328855-527ba480-a2b0-11ea-9ad6-f8e416aaf498.png)

As you can see, the fixed font is displayed normally on the KirikiriZ engine, but Ren'Py somehow does not display some glyphs, including spaces.

**Comment by uyjulian** [comment]
Did you also provide glyph for space symbol?

**Comment by uyjulian** [comment]
The reason why you are not seeing the missing glyph in Kirikiri Z is that Kirikiri Z has a font fallback system where if the font is not found in the loaded font, it will use the fallback font (usually `ＭＳ Ｐゴシック` or `メイリオ` depending on the result of `::GetStockObject(DEFAULT_GUI_FONT)`)

**Comment by Neko-Monika** [comment]
> Did you also provide glyph for space symbol?

Yeah, on all my screenshots have spaces between words. And yes, there's definitely a space glyph in the font. I also try write all symbols in Adobe Photoshop using fixed font and yes, the space glyph displaying properly even there.

I can write all the symbols from this font in PS and take a screenshot, if you want.

**Comment by Neko-Monika** [comment]
I changed all spaces on no-break spaces and it works. 🤔
![Snap2774](https://user-images.githubusercontent.com/29918546/83335501-70a8cb00-a2d7-11ea-9bef-ec21ce17a46c.png)

**Comment by Neko-Monika** [comment]
So, are there any other programs for editing fonts, which can work with fonts of OpenType CID type? FontForge, as I understood it, had created me fixed variants with broken glyphs, which can not be displayed even in the "Fonts" section of the Settings screen, so it falls away.
![Snap2799](https://user-images.githubusercontent.com/29918546/83400060-7106aa80-a42c-11ea-8456-1ee27ef1b227.png)
![Snap2800](https://user-images.githubusercontent.com/29918546/83400064-7237d780-a42c-11ea-938c-86361589b8eb.png)

**Comment by renpytom** [comment]
Closing, because this fell through the cracks. Please re-open this issue if it's still relevant,
