### ISSUE TITLE
Java Virtual Machine launcher error

### ISSUE THREAD

**Issue by whiteangel123** [renpy/renpy#2218]
Not sure if this is a Ren'py problem or a jEdit problem
But I recently installed a Java update on a DIFFERENT location than the previous version, and when I try to open Jedit from Ren'py it keeps trying to access the old Java folder, which no longer existed. 

It says "Error: could not open jvm.cfg". Like, jvm.cfg actually exists in my computer. Just not in THAT folder. I had to open jEdit.exe manually to get it work, and it's a pain because opening it manually only lets me open one file at a time apparently? Not multiple rpy files in multiple tabs like the Ren'py launcher does. 

![image](https://user-images.githubusercontent.com/36785520/83514427-d1b1e800-a4fd-11ea-9f9a-d8def32b8bb3.png)

This is not where my Java is. My actual Java location is "C:\Program Files (x86)\Java\jre1.8.0_251\lib\i386"

How do I tell Ren'py to stop trying to read Java from that folder?

**Comment by renpytom** [comment]
I don't know. This dialogue doesn't come from Ren'Py, it comes from something in the Java system. Ren'Py simply runs javaw.exe to run Java for jEdit, and doesn't do much beyond that.

**Comment by whiteangel123** [comment]
@renpytom I reinstalled my Java again and cleaned the registry. Now what it says is "Cannot find Java SE Runtime environment". If it's not Ren'py where can I get support/help for this :(

**Comment by 004307ec** [comment]
When it shows "Cannot find Java SE Runtime environment", you can try to set up JAVA_HOME environment to something like "C:\Program Files\jdk8.0.232" and add "C:\Program Files\jdk8.0.232\bin" (or "%JAVA_HOME%\bin" if you have already set it up) to PATH.

**Comment by whiteangel123** [comment]
@004307ec Tried that, and it doesn't seem to be working. 
I've set up Java home, and confirmed that the Path is correct 

![image](https://user-images.githubusercontent.com/36785520/83771356-64908500-a6ac-11ea-9be4-690a20f35043.png)
![image](https://user-images.githubusercontent.com/36785520/83771369-678b7580-a6ac-11ea-8b37-1bd48b5f7eae.png)


This is what I still see when I open jEdit from Ren'py

![image](https://user-images.githubusercontent.com/36785520/83771381-6b1efc80-a6ac-11ea-9e60-deb44eb9617d.png)

**Comment by whiteangel123** [comment]
I've also added both "C:\Program Files (x86)\Java\jre1.8.0_251\bin" and "C:\Program Files (x86)\Java\jre1.8.0_251" to PATH. Still seeing Could not find SE Runtime.

**Comment by whiteangel123** [comment]
I have found the solution. There's something wrong with the javaw.exe file in C:\Windows\SysWOW64. I replaced it with the updated javaw.exe from the newly-installed Java folder, and everything's back to normal.
