### ISSUE TITLE
Nested variable substitution

### ISSUE THREAD

**Issue by willhausman** [renpy/renpy#2219]
I noticed that I cannot have nested variable substitution.

```
default foo = "foo1"
default bar = "[foo] bar2"
image foobar = "[bar].png"
```

This tries to find the image `[foo] bar2.png` instead of `foo1 bar2.png`.  I see the #2094 exists, but when would I ever *not* want to recursively substitute when I have nested variables?  It seems like needing a switch to be explicit about the recursion is poor  for usability.

I considered a simple
```python
while "[" in s:
  s = formatter.vformat(s, (), kwargs)
```
instead of https://github.com/renpy/renpy/blob/d256d27e287ddfc7b66d65dab7f574069f57ae34/renpy/substitutions.py#L255

but this does not correctly account for `[[` escaping.  e.g. calling `renpy.substitutions.substitute("[bar].png")` might return the correct value with only 2 iterations of the while-loop, but `renpy.substitutions.substitute("[[ [foo] ]")` would be stuck in an infinite loop instead of returning `[ foo1 ]`.

Has an approach with automatic end-user participation been considered?  I suppose that could even be as simple as a configuration option that turns the #2094 flag on by default could work..

**Comment by Andykl** [comment]
Conversion flag is a pythonic way to do it (Explicit is better than implicit), but also don't forget about backwards compatibility. Recursive substitution is not so common, so !i is a reasonable price. So, for your example it's just `bar = "[foo!i] bar2"`

**Comment by willhausman** [comment]
That's a very developer-oriented answer for a tool that isn't necessarily used by developers.  I know *how* to use the conversion flag - I'm suggesting that it shouldn't be that way. I'm asking you to consider the end users.

I'm suggesting that the average Ren'Py user won't know what recursion is - let alone how to use it or search for how to do it.  However, if that same user at least understands `if I put "[variable]" in my string, it will be replaced by the value of variable`, I am willing to bet that they would be confused to discover that my example does not work.

With this in mind - where is the evidence that recursive substitution is not common?  Probably, it isn't sought because it isn't a known term. If it happened by default, it might be used more frequently.

As for backwards compatibility.. If recursion wasn't supported before, what functionality is protected? What issues can we expect if it is default behavior? Would the average users even notice?  Put another way, is there evidence that someone is using Ren'Py to write out variables and expects them not to render their value?  Furthermore, is there evidence that said individuals would update their Ren'Py launchers?

The Ren'Py users are not writing python - they're writing Ren'Py with some python-like syntax.

**Comment by willhausman** [comment]
**I propose the following compromise: a config variable which enables the `!i` conversion to always run on substitutions in a project.**

That gives users the ability to nest their variables throughout their project without keeping track of when they do or don't need to declare `!i` if they do it a lot, but it also keeps the explicitness of the conversion.

It can also maintain backwards compatibility, but I would still suggest it is enabled by default with a release note to change it to false for the people who relied on the previous behavior. I don't think it's something end users should have to think about if they aren't already thinking about it.

**Comment by Andykl** [comment]
I see that this has a very narrow use, mostly added by me as documentation.
It's not me who makes these language decisions, so I'll leave it to @renpytom to answer.
I'm good to change my PR if decision changes.

**Comment by renpytom** [comment]
I apologize for not getting to this sooner, but I think that recursive substitution by default is a bad idea. One place substitution can be used is to display things the player inputs, and having recursive substitution seems likely to cause crashes in that case. So I wouldn't want to enable it by default.
