### ISSUE TITLE
Request: re-allow downloading nightly builds via the Launcher

### ISSUE THREAD

**Issue by ladyisak** [renpy/renpy#2220]
In past Ren'Py versions, we could download the latest nightlies via the Launcher; that ceased to be the case some time ago — as I understand, because no stable nightly builds were available in the first place — but now that we're getting frequent nightly builds again, could that feature be restored, please?

**Comment by renpytom** [comment]
This should be done.

**Comment by ladyisak** [comment]
Thank you so much!
