### ISSUE TITLE
7.4 Launcher crashes when setting editor preferences

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2226]
When trying to set the 7.4 editor preference to System Editor, Ren'Py Launcher crashes. The contains the error messsage: LookupError: unknown encoding: cp1252.

This is on Windows with Ren'Py 7.4.0.426 (nightly build renpy-nightly-2020-06-09-0a3104af-sdk.zip)

[log.txt](https://github.com/renpy/renpy/files/4755767/log.txt)

**Comment by Andykl** [comment]
Starts fine in 6-13 build for me.

**Comment by rdurfee** [comment]
Yes, looks like it's fixed in 6-13. Thanks!
