### ISSUE TITLE
Enabling GL2 on 7.4 causes game to crash on startup

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2228]
When enabling GL2 support on Mac to test Live2D, the game crashes at startup.

Add the following line to options.rpy:
define config.gl2 = True

After launching the game, the window will open and then immediately close. Changing config.gl2 to False allows the game to run again.

This in on nightly build 7.4.0.426 for Mac.

Log.txt (attached) displays:
Exception: Shader ('renpy.ftl', u'renpy.geometry') has not been given uniform uTransform. 

[log.txt](https://github.com/renpy/renpy/files/4756278/log.txt)

**Comment by renpytom** [comment]
Were you able to get this working with today's build (ignoring the live2d part)?

**Comment by rdurfee** [comment]
Yes, the VN now launches when GL2 is enabled! Thanks.
