### ISSUE TITLE
ui improvement: 'auto' doesnt stay on when you go to the next text / dialogue 

### ISSUE THREAD

**Issue by SolveEverything** [renpy/renpy#2239]
'auto' should stay on

**Comment by renpytom** [comment]
This is by design. Once you take over manual control of the game, auto disables until such time as you re-enable auto. I don't believe that this is a behavior that needs to be changed, if I'm understanding your request correctly.

**Comment by Andykl** [comment]
If I understand correctly he asked about already implemented feature:
`Preference("auto-forward after click", "enable") - Remain in auto-forward mode after a click.`
https://renpy.org/doc/html/preferences.html#var-preferences.afm_after_click
