### ISSUE TITLE
Brightness with new matrixcolor alters transparent pixels

### ISSUE THREAD

**Issue by mal** [renpy/renpy#2255]
I dug into this a bit, and ultimately the both the matrix and shader seem fine. Debugging by duplicating the `renpy.matrixcolor` shader and having the final step be a check on `gl_FragColor.a > 0` and setting a solid red pixel if true resulted in the expected silhouette, suggesting that this is occurring outside of shader code?

This only appears to happen when setting brightness, I tried I few other convolutions but only brightness appeared to present this issue.

### Testcase

<details>
<summary>Visual result of testcase below</summary>

![matrixbug](https://user-images.githubusercontent.com/591257/85473482-374c3e00-b5ab-11ea-9162-56a7cd00bb72.png)
</details>

```rpy
define config.gl2 = True

label main_menu:
    $ _confirm_quit = False
    return

label start:
    scene
    show expression Placeholder('girl'):
        matrixcolor im.matrix.brightness(0.1)
    "Brightness affects transparent pixels, but it shouldn't."
    return
```

**Comment by renpytom** [comment]
The probably has to do with the fact that matrixcolor is doing alpha premultiplication. I need to think about what the right fix is.

**Comment by renpytom** [comment]
I think this is fixed by BrightnessMatrix and the new ColorMatrix stuff.
