### ISSUE TITLE
Requests integration issue

### ISSUE THREAD

**Issue by MatthewGoff** [renpy/renpy#2256]
Hi, I'm trying to use the python requests package with renpy. I have downloaded the "News" example provided on pytom's patreon (https://patreon.renpy.org/news.html). The example works on windows via the Renpy launcher but does not work when I build and install on my Android device.

In news.rpy function news_thread() the actual call to requests [news = requests.get(NEWS_URL, verify=ca_file).json()] raises this exception:
```
HTTPSConnectionPool(host='patreon.renpy.org', port=443): Max retries exceeded with url: /_static/news.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7264762050>: Failed to establish a new connection: [Errno 2] temporary failure in name resolution.',))
```

Seemingly the critical difference is that running on Windows via the renpy launcher uses python 2.7.10 while running on Android uses python 2.7.2

**Comment by kobaltcore** [comment]
There was a similar issue discussed in the Ren'Py Discord server some time ago.
While I can't guarantee that it will help in this case, there were two things affecting `requests` on Android at the time:
1. While configuring the Android build, `No Internet` was selected, effectively blocking all internet access for the app
2. The version of the application in `config.version` and in the Android configuration file are not the same

Maybe check these two things in case they help.
