### ISSUE TITLE
iOS IAPHelper uses deprecated UIAlertView

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2257]
The iOS IAPHelper uses the deprecated UIAlertView API. This API was deprecated way back in iOS 8.

To create and manage alerts in iOS 8 and later, instead use UIAlertController with a preferredStyle of UIAlertController.Style.alert.

https://developer.apple.com/documentation/uikit/uialertview

**Comment by renpytom** [comment]
I believe this has already been fixed in the renpy-build master branch.
