### ISSUE TITLE
Feature request: Drag'n'Drop overlap respects transparent pixels

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2259]

**Comment by Andykl** [comment]
My view to do so: https://github.com/Andykl/renpy/commit/4c36ba9b22243bd645d9d7451f3aed940cf6a990#diff-f64003e96e8ab179b22ae708b274b9343e99e70b83c039959db95b868b5b19c6R1091

**Comment by renpytom** [comment]
This feels too slow to ever implement, I think.
