### ISSUE TITLE
gl2: Frame is misaligned.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2260]
![image](https://user-images.githubusercontent.com/379804/85936273-0f205000-b8c7-11ea-8c1f-e968c7ccf327.png)

**Comment by dogtopus** [comment]
Also the whole game looks a lot blurrier than on gl to me. Some sort of rounding issue?

**Comment by dogtopus** [comment]
Can confirm that a6cfc52 fixed both the blurriness and misalignment for me.
