### ISSUE TITLE
Does RenPy use Pygame?

### ISSUE THREAD

**Issue by gitozify** [renpy/renpy#2265]
For 2D development in python, I'd think that they use pygame. However, if that's not the case, then what do you guys use? If it is the case, then how do you get it to work well with your custom scripting language?

**Comment by renpytom** [comment]
This isn't really suitable for the bug tracker, so I'll close this - feel free to email me at pytom@bishoujo.us if you want more. 

Ren'Py uses pygame_sdl2, which is a partial-rewrite of pygame (compatible with the portion of the API that Ren'Py uses) in cython, using SDL2. It's loaded like any other binary Python module. That being said, despite it being 2D, most of Ren'Py's graphics is done using OpenGL, as it accelerates drawing.
