### ISSUE TITLE
Arabic proper rendering support? 

### ISSUE THREAD

**Issue by trevortknguyen** [renpy/renpy#2266]
It seems as though Arabic text doesn't render properly. With default settings on everything and creating a simple Arabic dialog script, the words are rendered in isolated form from left-to-right instead of right-to-left.

Here's a sample Arabic string that doesn't work in RenPy: "السلام عليكم"

![](https://upload.wikimedia.org/wikipedia/commons/b/be/Arabicrender.png)

In RenPy, it looks like the first line, but it should look like the last line.

**Comment by renpytom** [comment]
Did you do:

```
define config.rtl = True
``` 

?

**Comment by trevortknguyen** [comment]
Oh wow. Okay that fixed it. Thank you so much and my apologies for not reading the docs carefully!

Regards,
Trevor
