### ISSUE TITLE
matrixcolor: TintMatrix() no longer allows color "addition"

### ISSUE THREAD

**Issue by dogtopus** [renpy/renpy#2269]
When we are still using `im.matrix` I can specify the RGB factor to be > 1.0 to "add" colors on specific channels and get a distinct "oversaturated" effect (like setting `<color> in <color> channel` to be above 1 in GIMP's channel mixer). It is no longer possible on TintMatrix due to `Color()` capping every channel above or equal to 1.0 and thus only allows color "subtraction", which makes things darker as a side effect.

**Comment by dogtopus** [comment]
Just found out that it's still possible to create a `Color()` object with `rgb` contains numbers above 1. Sounds a bit hacky to me though.

**Comment by renpytom** [comment]
I'd suggest if you want to do things like that, it probably makes sense to use Matrix directly, rather than trying to use TintMatrix to do this.
