### ISSUE TITLE
Feature request: Proper emoji rendering support

### ISSUE THREAD

**Issue by dogtopus** [renpy/renpy#2272]
Currently attempting to render emojis result in a lot of weird behaviors.

- Noto Color Emoji font fails to load properly with an error saying "loca" table not found.
- Noto Emoji loads, but rendering is broken (`heart emoji` (`U+2764 U+FE0F`) shows as `heart character` (`U+2764`) and a placeholder, `skull` shows as 2 placeholders. Both cases the characters are clearly present in the set but aren't rendered properly)

Since modern emojis provide a lot of useful symbols in a standard and self-documenting way (no more inserting some pictures as characters, what you see in script is what you get on-screen if the fonts are the same) and AFAIK newer freetype does handle emojis (even the colored ones) it makes sense to support them properly.

**Comment by renpytom** [comment]
Is this a feature request, or are you planning to submit a pull request at some point?

**Comment by dogtopus** [comment]
@renpytom I don't have plans to work on it at this point so it would be a feature request.

**Comment by dogtopus** [comment]
I found some time to look at the issue and it seems to be (partially) caused by the Python build that shipped with Ren'Py. In [Python docs](https://docs.python.org/2/c-api/unicode.html) there's a mention that `Py_UNICODE` depends on a build option to be 16 or 32-bit (i.e. either UCS2 or UCS4). It also mentioned that most Linux distros ships with UCS4 Python builds. So I did a quick test on the self-built master version and at least the UCS4 monochrome emojis got correctly rendered.

**Comment by dogtopus** [comment]
Variation sequences should now be handled with `FT_Face_GetCharVariantIndex` (docs [here](https://www.freetype.org/freetype2/docs/reference/ft2-glyph_variants.html)).

A screenshot shows it working:

![Screenshot from 2020-07-10 00-04-10](https://user-images.githubusercontent.com/3405234/87112265-bf844180-c241-11ea-830d-3c7fd32e8dc2.png)

Please review and don't close this issue yet on merge since the first case (loading NotoEmojiColor) is not yet resolved.

**Comment by dogtopus** [comment]
So the nightly no longer complains non-existing LOCA table when loading Noto Color Emoji. However it still stuck on `FT_Set_Char_Size()` in `setup()` with error `invalid pixel size`.

**Comment by dogtopus** [comment]
Since supporting for bitmap/vector color emojis seems to be more involved than I initially thought and me not having enough time and interest look into it further, I'll leave color emoji support as a feature request. Monochrome emojis should work however once the above PR and the Python Unicode encoding issue are resolved.

**Comment by renpytom** [comment]
It looks like UCS-4 breaks things on windows, which assumes that sizeof(Py_UNICODE) == sizeof(wchar_t). I'll leave this open and potentially look at just decoding the surrogate pairs myself.

**Comment by renpytom** [comment]
I believe this is done now.
