### ISSUE TITLE
Exception callback for monitoring software

### ISSUE THREAD

**Issue by Daniel-Gherard** [renpy/renpy#2274]
One of the few complaints I have with Renpy is it's really hard to know how your game is behaving when others are playing. That's specially true when an error/exception occurs. One of the ideas I got to fix that and get an idea of all the problems occurring was to use a monitoring software like Airbrake. But, the only way I found to send the exceptions back to Airbrake was by changing the /renpy-7.3.5-sdk/renpy/error.py file. Which by itself is terrible practice as just one update and it breaks. And, everytime the SDK gets update I'll have to introduce this code again.

So, my question is would it be possible to add a callback when an exception will be thrown? So that I can send it back to a monitoring software for fixes in future releases or updates? This would not be a way to prevent exceptions as to my understanding that would not be a good way to prevent errors. It's just a way to collect data on problems that are occuring.

Last, but not least, I'm offering to make a PR with a feature like that if you all agree with it.

**Comment by renpytom** [comment]
Could you take a look at c682e4f40606ee1e6b9f34afa8b35738a22bd207 , and see if it already does what you want?

**Comment by Daniel-Gherard** [comment]
@renpytom, sorry for the delay. Yes, that's exactly what I wanted. I apologize I wasn't aware this feature already existed.
Anyways... thank you for the quick reply!! I'll close this issue right now.
