### ISSUE TITLE
Hide Scrollbars on viewport until content overflows?

### ISSUE THREAD

**Issue by newbiemate** [renpy/renpy#2279]
Is there a way to hide scrollbars until the content within the viewport overflows?

Currently, I have a parent frame and a viewport which are locked at a ysize of 600:

                frame:
                    xsize 200
                    ysize 600
                    
                    viewport:
                        scrollbars "vertical"
                        mousewheel True
                        draggable True
                        ymaximum 600

                        for itm in my_list:
                            text itm.name size 20 

But this ends up showing scrollbars, even though the viewport content is less than ysize 600. I was hoping setting the `ymaximum 600` would achieve this, but it doesn't. Is there a way to hide the scrollbar until a defined maximum is hit?

**Comment by renpytom** [comment]
You'd do that with 

```
                viewport:
                    scrollbars "vertical"
                    mousewheel True
                    draggable True
                    ymaximum 600
                    vscrollbar_unscrollable "hide"

                    for itm in my_list:
                        text itm.name size 20 
```

Let's leave this open until I document it better.

**Comment by renpytom** [comment]
6efbba109660b51a1416e8e43a73b7c818d7840e is the documentation this was waiting for.
