### ISSUE TITLE
Renpy keeps deleting my project files

### ISSUE THREAD

**Issue by KarkatMufiin** [renpy/renpy#2288]
Twice now I have had Renpy be unable to connect to any files...I just have to make a new one. This would suck if I actually cared about what I was doing.

Basically I start up the launcher and under projects, it just has the basic downloaded content. Hours of work are still in the proper files but lost due to Renpy simply just not seeing them.

This time I just wanted to go in since I wanted to do a rewrite of my story but I wanted the stuff that I coded for fun since it was way better. Of course, I hadn't touched ANY of the files (moved them, deleted them, renamed them. I didn't do anything with the basic files or even use Renpy to edit them) When I went to open the file in Renpy to get the dialog it wasn't there...the files were simply gone. It is still in the folder, it still exists but Renpy can't find it, and of course, I can't open it without Renpy...So I'm just lost here.

I'm just an artist, not a coder so I don't know much. And this not like my job or anything so if this problem continues to be an issue, then I will just have to struggle using unity.
![-](https://user-images.githubusercontent.com/68494253/87869432-cdd30b80-c96d-11ea-9223-61d9ad5b3147.png)

**Comment by KarkatMufiin** [comment]
I had a lot of project files due to me messing around with the resolution size

**Comment by langbakk** [comment]
Check your project folder. 100% it's been reset to default. Renpy can't see your files because Renpy isn't looking where your files are.

**Comment by KarkatMufiin** [comment]
Ogm that worked thank you so much
