### ISSUE TITLE
Unable to choose sound device propertly

### ISSUE THREAD

**Issue by roxygen** [renpy/renpy#2291]
Hello.

One of our customers met a strange problem with sound device. Renpy refuse to work with their sound card and only play sound when customer turn it off. After that renpy direct sound to grafix card HDMI to play it with a TV monitor's speakers.

Windows sound manager also doesn't allow to change sound device for user. Customer also cheched their drivers and re-update it. Audiocard model is Soundblaster Audigy Platinum.

His [log.txt](https://github.com/renpy/renpy/files/4960482/log.txt) seems prefectly fine. I even build game with a new version of renpy and it also didn't help.
He has no problem with other games' sound.

My only guess is his problem my be with the SDL audio device selection.

**Comment by roxygen** [comment]
Well, I have and idea to choose sound device by pygame, but get lost. So I findout that renpy don't allow you to initialize sound device because it use legacy function https://wiki.libsdl.org/SDL_OpenAudio instead of new https://wiki.libsdl.org/SDL_OpenAudioDevice

https://github.com/renpy/renpy/blob/master/module/renpysound_core.c#L1150

**Comment by renpytom** [comment]
SDL will be updated in 7.5/8.0, and so hopefully that fixes this.
