### ISSUE TITLE
Live2D: When not looped, a motion resets to the first frame after playing

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2293]
If Loop=False is set when defining the Live2D model, after a motion has finished playing, the animation abruptly resets to the first frame of the animation.

It should stay on the last frame that was rendered. Or adding an option to not reset the animation. Either would be extremely helpful.

**Comment by renpytom** [comment]
Can you tell if it's resetting to the first frame, or the neutral position. (The one  that the model defaults to.) The neutral position is what's intended, as that's what live2d has in their documentation.

**Comment by renpytom** [comment]
I agree, this was closed with the fix for #2552. Let's discuss it there if it's still a problem.
