### ISSUE TITLE
can't change the font

### ISSUE THREAD

**Issue by denish07-a** [renpy/renpy#2296]
I have see the tutorial In your you tube
so I try it and it's error
yes it's error
[traceback.txt](https://github.com/renpy/renpy/files/4977121/traceback.txt)
here the prof
yeah I have try it several time and other tutorial to
and still not working

**Comment by YasPHP** [comment]
faced a similar font issue (for the main menu) previously but resolved with this tutorial: https://www.youtube.com/watch?v=DL6Cqn0G4F0
