### ISSUE TITLE
Having RTL enabled causes {w} tag to throw an exception

### ISSUE THREAD

**Issue by Hassohappa** [renpy/renpy#2298]
I [posted about this bug](https://lemmasoft.renai.us/forums/viewtopic.php?f=32&t=59663) on the Lemma Soft Forums and was advised to file a bug report here. 

Steps to reproduce:

1.  Set RTL as True (renpy.config.rtl = True)
2. Add {w} to a line of dialogue. 
3. Play the dialogue and observe that an exception has occurred (traceback attached). 
[traceback.txt](https://github.com/renpy/renpy/files/4985032/traceback.txt)

This happens on any language once rtl is true (regardless of if it's left-to-right or right-to-left).

**Comment by Hassohappa** [comment]
Since it's been a week and no one's responded, I came up with a [tedious workaround](https://lemmasoft.renai.us/forums/viewtopic.php?f=32&t=59663&p=532675#p532675) for anyone with the same issue. The bug is still unresolved and {w} will still not work in rtl languages, but at least the tag doesn't need to be deleted from every single language.

**Comment by renpytom** [comment]
I'll be working on this when I get a chance.

**Comment by Hassohappa** [comment]
Thank you Tom! Turns out using nvl and extend dialogue with RTL causes the same TypeError in rtl_paragraph, so until this is fixed I can't actually do much in terms of workarounds.

`I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tl/farsi/1_diya.rpy", line 4087, in script
    cAkarsha "دیا پرینگلز دوست داری دیگه، آره؟"
  File "renpy/common/00nvl_mode.rpy", line 380, in do_display
    **display_args)
TypeError: Argument 's' has incorrect type (expected unicode, got str)`
