### ISSUE TITLE
Checkerboard is visible through fully opaque image

### ISSUE THREAD

**Issue by Queex** [renpy/renpy#2299]
With this code:

```
image transparent=Solid("#0000")

screen billboard:
    modal True
    window:
        style "blank_window"
        background "#7b7b7b"
        null width 1280 height 720

label start:
    scene transparent with None
    call screen billboard()```

The checkerboard pattern is still visible (the difference is reduced to 1 bit in each rgb channel, though, so it's hard to see).

This occurs no matter what layer the screen is assigned to.

(Not sure how this would behave with developer mode turned off, but this is strange and undesirable in any case)

[image](https://user-images.githubusercontent.com/10655723/88967609-f6300380-d2a5-11ea-9cd1-901e4a08c863.png)

**Comment by renpytom** [comment]
I can't repeat this with:

```
define _confirm_quit = False

image transparent=Solid("#0000")

screen billboard:
    modal True
    window:
        style "empty"
        background "#7b7b7b"
        null width 1280 height 720

label start:
    scene transparent with None
    call screen billboard()

label main_menu:
    return
```

I don't know what blank_window is, as it's not a standard style. When I change it out for empty, things seem to work fine.

**Comment by Queex** [comment]
```style blank_window:
    xalign 0.0
    yalign 0.0
    ysize None
    xfill False
    padding (2,2)
    background None```

Which should be functionally equivalent to empty. The problem still persists for me with `style "empty"`. Have you verified by checking a screenshot in an image editor that there's no variation in background colour? For some other colours I couldn't tell by eye.

**Comment by renpytom** [comment]
Yes, I went ahead and increased the contrast fully to confirm that it was not leaking through.

**Comment by Queex** [comment]
Pasting it into a new project, I still see it, clear as day, so it can't be something weird in the original project. I've checked every system display option I can find and nothing seems relevant. Where is that checkerboard pattern actually stored?

**Comment by Queex** [comment]
I wondered if it might be related to #2300, but it still happens in an otherwise empty project under the old drivers.

**Comment by renpytom** [comment]
Could you please post that empty project? I've been unable to repeat it here.

**Comment by Queex** [comment]
I've pre-emptively turned off all the bells and whistles I could find in the Radeon software, and tried all 3 Renpy rendering modes with the same result.

[Checker.zip](https://github.com/renpy/renpy/files/5010315/Checker.zip)

![Clipboard01](https://user-images.githubusercontent.com/10655723/89101138-2afea080-d3f5-11ea-911a-47e91bacfef6.jpg)

**Comment by renpytom** [comment]
![foo](https://user-images.githubusercontent.com/379804/89143564-0865a800-d519-11ea-8a76-09f70b856ad9.png)

This is a crop of the gray part at the bottom of the screenshot you gave me. 

![image](https://user-images.githubusercontent.com/379804/89143669-64c8c780-d519-11ea-9380-f02941068956.png)

Is the histogram the GIMP gives me of the cropped image - with all the value in a single column. I guess my question is how did you determine that a 1-bit difference was present? Visually, or by analyzing the data with a program?

**Comment by Queex** [comment]
The colour-picker in GIMP shows me different hexcodes - although on my good monitor it's easy to see the difference once I knew it was there. 

![Clipboard02](https://user-images.githubusercontent.com/10655723/89175774-5235a900-d580-11ea-863e-491760e028f9.jpg)
![Clipboard03](https://user-images.githubusercontent.com/10655723/89175781-5792f380-d580-11ea-9b72-a9c42a7545a2.jpg)

**Comment by renpytom** [comment]
Can you use gimp to screenshot it, and render a png? Like I said, I took your screenshot, ran a histogram in GIMP, and it was all in one bin.

**Comment by Queex** [comment]
The area to the left in my last screenshots is actually the same area, top half one colour and the bottom half the other. If you can't find the difference by eye, you can use the eye-dropper tool with the colour picker open and click in a line down the image until the hexcode changes - that's how I confirmed it initially.
