### ISSUE TITLE
Awful loading time on huge game

### ISSUE THREAD

**Issue by dogtopus** [renpy/renpy#2302]
Not sure if anything can be done about this as I would definitely consider this as a rare case, but I'll drop an issue here anyway just in case something can be done for this.

So I made an "enhancement" port of an old commericial VN for fun and profit (as in being able to play it on a Windows or Android tablet. The original engine HATES tablets and will literally refuse to start if it can't detect a mouse). The game has quite a lot of text and character animations and the converted rpyc scenario files are over 30 MB (!). The direct result of this is VERY LONG loading time. It takes ~25 seconds to do a hot start (with all scripts pre-compiled and analysis completed) on a 3rd gen desktop i5 and could easily take MINUTES on lower power devices like an Atom-based tablet.

The whole loading process seems to be purely CPU-bound with 100% single core usage and tiny amount of I/O operations. So I suppose multiprocessing/true multithreading might help this a little. The scripts are splitted into 10kB-1MB blocks natually by the original scenario files.

Tested on the last available nightly, although stable does similar things (might actually be slightly faster IIRC).

Some performance metrics: (`config.profile_init` was set to 0.1 and seems that no init blocks actually took that long)

```
Bootstrap to the start of init.init took 1.11s
Early init took 0.01s
Loader init took 1.97s
Loading error handling took 2.05s
Loading script took 24.30s
Loading save slot metadata. took 0.08s
Loading persistent took 0.01s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 0.40s
Loading analysis data took 5.73s
Analyze and compile ATL took 0.29s
Index archives took 0.00s
Dump and make backups. took 0.42s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.58s
DPI scale factor: 1.000000
Creating interface object took 0.03s
Cleaning stores took 0.00s
Init translation took 0.06s
Build styles took 0.01s
Load screen analysis took 0.46s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.08s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.01s
Performance test:
Interface start took 0.65s
```

**Comment by kobaltcore** [comment]
We actually experience a similar behavior on our VN, where loading the script takes a long time. Last time I investigated this some months back, it came down to the pickle module being slow and thus being the main cause of this issue.
As soon as Renpy moves to Python 3 (and thus a newer protocol for pickling) I expect performance to somewhat improve.
Unfortunately pickle is kinda required due to the complexity of the stuff that's being saved, so moving to something like Json or msgpack would not be trivial.
I'd be interested in tips for improving script loading performance as well, if anyone else chimes in.

**Comment by renpytom** [comment]
I'd also check to make sure that your conversion is not terrible. Analysis is applied to screen and to transforms, so if you have a lot more than the usual number of screens and ATL animations, then that could cause this sort of problem.

**Comment by uyjulian** [comment]
Could using Protocol Buffers improve performance compared to using pickle?

**Comment by renpytom** [comment]
I don't think debating alternatives to pickle is important here. A more important question is why so much analysis data is being created in the first place, which is probably an issue with the conversion.

**Comment by kobaltcore** [comment]
That is definitely true.
Does the analysis data have an impact on the script loading time?
Otherwise the main item of `Loading script took 24.30s` would remain untouched, even though it is the main factor for startup time in this case.

I profiled my "script loading" step using cProfile and the time there is absolutely dominated by cPickle, so at least for that step it does have an impact that is non-negligible.

**Comment by dogtopus** [comment]
@renpytom due to he nature of the original engine unfortunately yes. All `show` statements for character images have an ATL block attached to it for setting the drawing position relative to the corner and there's little I can do about it if I only look at the scripts and not also the image dimensions in the converter.

**Comment by renpytom** [comment]
Why have an ATL block rather than something like:

```
transform abspos(x, y):
    xpos x ypos y
```

```
show eileen happy at abspos(x, y)
```

Fundamentally, before investing effort into optimizing pickle, I'd need to know that this is a sensible conversion.

**Comment by dogtopus** [comment]
@renpytom kinda because I don't really know that ATL blocks have more overhead than `at` statements and I just treated it as some sort of inline style.

**Comment by dogtopus** [comment]
So I tried to translate all the one line atl position block to a transform and the loading time did significantly improve. However the script loading is still painfully slow.

New performance metrics:

```
Bootstrap to the start of init.init took 1.14s
Early init took 0.00s
Loader init took 2.27s
Loading error handling took 2.11s
Loading script took 22.80s
Loading save slot metadata. took 0.09s
Loading persistent took 0.01s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 0.38s
Loading analysis data took 0.90s
Analyze and compile ATL took 0.13s
Index archives took 0.00s
Dump and make backups. took 0.42s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.39s
DPI scale factor: 1.000000
Creating interface object took 0.02s
Cleaning stores took 0.00s
Init translation took 0.06s
Build styles took 0.01s
Load screen analysis took 0.14s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.09s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.01s
Performance test:
Interface start took 0.40s
```

It might still make sense to switch to a faster serialization format for rpy{,m}cs if pickle is the bottleneck.

---

Also not really related but after I switched to `at` statement the animation behavior becomes a bit weird. Sometimes it teleports to the very left of the screen when I don't even specify it to start from there. The at transform is as follows:

```renpy
transform abspos(x, y):
    # Start from top left corner
    reset
    # Place the sprite
    pos (x, y)
```

and an invoke example is like:

```renpy
show fg G1_AA01S at abspos(1.0, -0.06666666666666667) zorder 0 as fg_i0:
    linear 0.5 xpos 0.73875
    linear 0.3 xpos 1.0
```

Any idea why this would happen?

**Comment by kobaltcore** [comment]
For what it's worth, I found that temporarily disabling the garbage collector for the script loading step netted me a consistent performance boost of about 30%.
I'm not entirely educated on whether this has any adverse effects on things later down the line, so I'd add a very large disclaimer that this is highly experimental and probably not recommended for anything other than playing around at the moment.

**Comment by dogtopus** [comment]
I noticed that Ren'Py seems to use Python `pickle` instead of the faster `cPickle` for saving/loading rpyc files. Any particular reason why this choice was made other than Python3 compatibility?

**Comment by kobaltcore** [comment]
It does actually use cPickle when available. This is governed by `config.use_cpickle`.

**Comment by dogtopus** [comment]
> It does actually use cPickle when available. This is governed by `config.use_cpickle`.

No. `renpy/script.py` is hardcoded to use `pickle` instead of `cPickle`. I was surprised when I found it out as well.

**Comment by kobaltcore** [comment]
That does appear to be the case in master, however for the latest actually released version, this is not the case. It uses cPickle and I assume the next release version will do so as well. If I were to hazard a guess, it's probably currently set to pickle to make debugging and porting to Python 3 easier.

**Comment by dogtopus** [comment]
> That does appear to be the case in master, however for the latest actually released version, this is not the case. It uses cPickle and I assume the next release version will do so as well. If I were to hazard a guess, it's probably currently set to pickle to make debugging and porting to Python 3 easier.

Hm that explains why master feels slower than 7.3.5. Good catch.

**Comment by uyjulian** [comment]
Yeah, cPickle is much faster than pickle.  

---

I looked into using other serializable formats. Python objects (such as those from global `renpy.ast`) are included when doing a pickle operation, so those use of Python objects would need to be converted into a generic structure type (such as `dict`).  
However, whichever method of serialization is done, if the Python objects are constructed at load time, the performance improvement compared to cPickle will be minimal.  
For there to be a sizable improvement, there would need to be a way to lazily construct the objects.

**Comment by dogtopus** [comment]
Since we have `renpy.compat`, I suggest to change all the hardcoded `from pickle import loads, dumps` to something like `loads, dumps = cPickle.loads, cPickle.dumps` since `cPickle` import will always exist and will always get the faster pickle implementation where possible.

**Comment by dogtopus** [comment]
Just an update: pausing gc during init also sped things up for me by another 50%:

```
Bootstrap to the start of init.init took 1.12s
Early init took 0.00s
Loader init took 1.98s
Loading error handling took 0.24s
Loading script took 5.36s
Loading save slot metadata. took 0.10s
Loading persistent took 0.01s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 0.37s
Loading analysis data took 0.07s
Analyze and compile ATL took 0.16s
Index archives took 0.00s
Dump and make backups. took 0.42s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.43s
DPI scale factor: 1.000000
Creating interface object took 0.02s
Cleaning stores took 0.00s
Init translation took 0.06s
Build styles took 0.01s
Load screen analysis took 0.04s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.08s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.01s
Performance test:
Interface start took 0.36s
```

**Comment by renpytom** [comment]
Has anyone checked this with the current nightlies? It now uses cPickle, which should be faster.

**Comment by dogtopus** [comment]
Yes it works well.

**Comment by kobaltcore** [comment]
It's certainly faster than before, though still a bit behind the latest 7.3.5 release.

I've tested 7.3.5.606 versus 7.4.0.684, and the 7.4 release is consistently about 40% slower still.
Granted, my system is fast and story files are comparatively small (about 8MB), so some of this may be chalked up to margin of error.
In general I am observing a very consistent speed of about 1.2 seconds to load the script (once compiled) on 7.3.5 versus 1.7 seconds on 7.4.0. These measurements stay consistent across multiple runs (I did five consecutive runs on each version).

I also noticed something only tangentially related, which is that the 7.3.5-strain of releases appends to `log.txt` as it runs, flushing the file in between. The 7.4.0 versions do not flush/write to the file until after the game is closed again. This is not bad per-se, but the previous behavior was more convenient.

**Comment by uyjulian** [comment]
Also see https://github.com/renpy/renpy/pull/2307

**Comment by dogtopus** [comment]
Anybody tested nightlies after ab8c1bb4? Any speed improvements?

**Comment by kobaltcore** [comment]
In my testing, speed has (roughly) returned to its initial state in 7.3.5. On my system, with my specific setup, there is almost no difference in speed between 7.3.5 and the 7.4 series anymore.

It's a bit of a bummer that we didn't get any actual speed gains out of it, but at least we're back to the previous, acceptably-speedy behavior.
