### ISSUE TITLE
Does not work with certain styles in Latte-dock of KDE

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [renpy/renpy#2303]
All games written with Ren'Py and the Ren'Py launcher force the dock style to be changed into ```plasma``` no matter what original style is used.

Without running Ren'Py games:

![without rpy](https://i.imgur.com/HvvmLW6.png)

With Ren'Py games:
![with rpy](https://i.imgur.com/M5X9bHq.png)

**Comment by renpytom** [comment]
I'd file an issue with KDE, as Ren'Py doesn't do anything special, as far as I know. I'd be happy to talk about changes if someone figures out what's going on, but fundamentally Ren'Py is just an SDL2 application.

**Comment by Ravenclaw-OIer** [comment]
I would suggest to file issues to lattedock because lattedock is not an official KDE application

**Comment by renpytom** [comment]
Sure, please do. I don't think there's an issue with Ren'Py here, is there?

**Comment by Ravenclaw-OIer** [comment]
Probably, but I haven't been able to reproduce this issue with any other app... Can you suggest an app that uses a similar architecture to Ren'Py?

**Comment by renpytom** [comment]
Ren'Py uses SDL2 for its video output, so I'd suggest any SDL2 game should be similar.

**Comment by lotaris-xx** [comment]
You can tell KDE not to allow blocking of the compositor. SDL2 does request desktop compositing to be blocked which is likely what is causing this issue.

**Comment by Ravenclaw-OIer** [comment]
I wonder if anyone has a GNOME at their disposal. I don't have one and I think it is needed to test `latte-dock` on GNOME to make sure it is not a KDE problem.

**Comment by lotaris-xx** [comment]
I think KDE is doing what is asked by SDL2 using  the _NET_WM_BYPASS_COMPOSITOR hint.

https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46035372472224 chats about the values. It seems like this is designed for things running full screen.

SDL appears to hint this with HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR.

Perhaps Renpy could toggle this hint when toggling between full screen and windowed mode.

If a user is running windowed mode and things look weird, try Alt-Shift-F12 to toggle this in Kwin.

**Comment by Ravenclaw-OIer** [comment]
> I think KDE is doing what is asked by SDL2 using  the _NET_WM_BYPASS_COMPOSITOR hint.
> 
> 
> 
> https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46035372472224 chats about the values. It seems like this is designed for things running full screen.
> 
> 
> 
> SDL appears to hint this with HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR.
> 
> 
> 
> Perhaps Renpy could toggle this hint when toggling between full screen and windowed mode.
> 
> 
> 
> If a user is running windowed mode and things look weird, try Alt-Shift-F12 to toggle this in Kwin.
> 
> 
> 
> 

I do not think it is the case as the problem arises as soon as Ren’Py launches

**Comment by renpytom** [comment]
I just landed a change that should prevent the BYPASS_COMPOSITOR hint from being set. 

Hopefully this will fix things.

**Comment by lotaris-xx** [comment]
This seems to work fine for me as long as the bundled SDL2 version is >= 2.0.8 where the hint was introduced. Thanks!

**Comment by lotaris-xx** [comment]
If you are using nvidia proprietary drivers, nvidia just fixed something related to this in their current long term drivers:

https://www.nvidia.com/Download/driverResults.aspx/162107/en-us

* Fixed a bug causing the Plasma desktop panel to freeze when compositing is disabled (https://bugs.kde.org/show_bug.cgi?id=353983) 

450.66 completely resolved the issue for me with older renpy games. (I did not test 450.57. but anything after .50 is supposed to have this fix).
