### ISSUE TITLE
Unable to import .py, .pyo, .pyd

### ISSUE THREAD

**Issue by PatrickBate** [renpy/renpy#2311]
Importing .py, .pyo or .pyd doesn't work and it's throwing a "weird" error when trying to import a .py script only containing a function returning a string. Writing "import test" in renpy launcher (test.py is in the launcher's renpy folder with other .py/.pyo scripts) throws and error "No module named test". Trying to import it with "import renpy.test" closes the launcher with error "'module' object has no attribute 'get_side_image'". When this test.py script is being imported in bootstrap or loader causes Renpy Launcher to not even start, without a traceback. It should be possible to import own modules with functions.

**Comment by kapilgain** [comment]
Hi Patrick,

There is already a test package inside the renpy folder. So when you are trying to import your test.py script using `import renpy.test`, it is importing the `renpy/test/__init__.py` script instead. I tried to import a custom script (mytest.py inside the renpy folder - at the same level as bootstrap.py) and I was able to import it successfully

```py
# renpy/mytest.py
def get_side_image():
    return "my side image"
```

```renpy
# inside a .rpy file
python:
    from renpy.mytest import get_side_image
```

**Comment by PatrickBate** [comment]
Well, I couldn't get this to work. I created a script called aabc.py in the same renpy folder with main.py and when I try to import it through console in the Renpy SDK I get the same error over and over whether I add this "def get_side__image()" function or not. I want to be able to import this module during the main.py runtime and not in the .rpy script when game is fully loaded. So yes typing "import renpy.aabc" in SDK console get's me this error "AttributeError: 'module' object has no attribute 'get_side_image'"every time.

**Comment by kapilgain** [comment]
I created a sample game called 'HelloRenpy' in my workspace, launched it and fired up its dev console. I printed out its `sys.path` to identify the possible locations where I could place my aabc.py script.

![image](https://user-images.githubusercontent.com/69730236/91149726-130afb80-e6d9-11ea-9ac1-60129d293884.png)

I picked the first entry and created the aabc.py script right next to the `game` directory.
```py
# /Users/kapilgain/workspace/HelloRenpy/aabc.py
def say_hello():
    return 'Hello'
```
![image](https://user-images.githubusercontent.com/69730236/91150509-1e125b80-e6da-11ea-980d-0beb96aca0fa.png)


I was able to `import aabc` and invoke the `aabc.say_hello()` function

![image](https://user-images.githubusercontent.com/69730236/91150326-df7ca100-e6d9-11ea-983f-c3e5ad39eaec.png)

You should be able to do something similar for your use-case.

**Comment by PatrickBate** [comment]
Yeah, putting it anywhere else, even into the lib/python2.7 works, thanks for that. I assumed that putting it with core engine scripts would work, but it doesn't which is weird and very unintuitive. I have a question that I cannot test.. will .pyd gonna get imported when running on a Mac build?

**Comment by kapilgain** [comment]
No, .pyd is a Windows binary and will not work on other OS (macOS, Linux). To support all platforms (windows-i686, mac-x86_64, linux-i686, linux-x86_64), you will need to compile and build the Cython code for each of them, and drop the generated shared library files in a `sys.path` location. Depending on the OS in which Ren'Py is running, the appropriate shared library (.pyd on Windows / .so on Linux / .dylib or .so on macOS) will get picked when you do an `import`

**Comment by renpytom** [comment]
Ren'Py is documented to load .py files under /game. Loading DLLs (.pyds, .so, .dylib), etc, isn't supported.
