### ISSUE TITLE
Custom Mouse Pointer is not working 

### ISSUE THREAD

**Issue by mess66** [renpy/renpy#2315]
The following code appears to be broken, "mouse.png" is non-existent in-game even though the file has been defined and is in the same path as the code states. As a result there is no cursor in the game.

`config.mouse = { 'default' : [ ('mouse.png', 0, 0)] }`

**Comment by lee-yunseok** [comment]
On stable 7.3.5.606 I have no problem with `config.mouse`.

Is the `mouse.png` file inside `game` directory?

**Comment by PatrickBate** [comment]
On Renpy 7.4.0.619 it works without a problem.

**Comment by mess66** [comment]
> On stable 7.3.5.606 I have no problem with `config.mouse`.
> 
> Is the `mouse.png` file inside `game` directory?

Yes, but the version I'm using is the nightly build 7.4.0.619

**Comment by mess66** [comment]
> On Renpy 7.4.0.619 it works without a problem.

I'm using the same version, after some thought I realized the bug could be related to a Live2D model being displayed on a screen or maybe just the Live2D model itself. I haven't tried deleting the Live2D model yet but the issue seems to be on the title screen.

**Comment by jsfehler** [comment]
I can reproduce this on a new project built with 7.4.0.924. It only occurs when GL2 is activated, ie: `define config.gl2 = True`

**Comment by jsfehler** [comment]
https://github.com/renpy/renpy/blob/c8e45d6ce196ba5573109ac4abb293e3f01d66f9/renpy/gl2/gl2draw.pyx#L1028
https://github.com/renpy/renpy/blob/c8e45d6ce196ba5573109ac4abb293e3f01d66f9/renpy/gl2/gl2draw.pyx#L1053

Don't ask me why, but I've got a hunch custom mouse support isn't implemented in GL2 yet.

**Comment by Andykl** [comment]
Fxied by https://github.com/renpy/renpy/commit/ac0dd6e361a386e72e56d0720ccc4454b7cc3cdf
