### ISSUE TITLE
7.4 GL2: Crop and Frames are now broken with current nightly build

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2321]
Since updating to the latest release of 7.4 (7.4.0648), images are no longer cropped correctly and Frames appear incorrectly.

This image shows a LayeredImageProxy side image where the image is cropped incorrectly. In the previous versions, his shoulder wasn't cut off. It also appears that the layers of the layered image are cropped differently in that you can see the base body image peeking out from the outfit image.

Though not apparent in this screenshot, cropped images extend further on the Y axis than they are supposed to.

You can also see the standard prompt frame is also corrupted.

(EDIT: This issue only appears when config.gl2 is enabled) 

![screenshot0004](https://user-images.githubusercontent.com/12246002/90289987-08d03e00-de4b-11ea-8191-7eda91e83d38.png)

**Comment by renpytom** [comment]
Sheesh, that's bad. Do you have something that exhibits the problem, and a log.txt running on your system? I don't see the issue here, but I did change serveral relevant things.

**Comment by rdurfee** [comment]
This happens with a new project and setting define config.gl2 = True. It also happens on both my iMac/Catalina and Surface Pro/Win10.

Here is a copy of log.txt:
[log.txt](https://github.com/renpy/renpy/files/5077552/log.txt)

**Comment by renpytom** [comment]
Interesting. It's failing on the nightly build, but not on my development setup. I'll figure it out and let you know what's wrong. Thank you for the report.

**Comment by dogtopus** [comment]
Can confirm this on Android as well. Thought it was an Android-specific problem but I guess it goes deeper...

**Comment by renpytom** [comment]
It was a problem with the build system for the nightly build, which should be fixed tomorrow. If you could test the 8-15 version, I'd appreciate it.

**Comment by rdurfee** [comment]
It appears to be fixed with the 8-15 build. Thanks!
