### ISSUE TITLE
Migration from Pickle module to Dill module? 

### ISSUE THREAD

**Issue by hell-oh-world** [renpy/renpy#2323]
This one is a standard question. I am curious whether it is possible for Ren'Py to migrate from `pickle` module to `dill` module so that the engine could support a lot more types of objects in the process of pickling such as `lambda`s etc.
https://github.com/uqfoundation/dill

**Comment by renpytom** [comment]
I've considered it. There are just way more important things on my plate at the moment.

**Comment by dogtopus** [comment]
One thing to take note is Pickle wasn't that fast to begin with and Dill might actually make it even slower. This might cause edge cases like #2302 to become worse.
