### ISSUE TITLE
pygame_sdl2/pygame_sdl2.h: No such file or directory error, when following the installation instructions

### ISSUE THREAD

**Issue by alevikpes** [renpy/renpy#2328]
Hi! I am trying to install renpy and getting this error `gen3/_renpy.c:613:10: fatal error: pygame_sdl2/pygame_sdl2.h: No such file or directory`, at the step of installing pygame_dsl2.

```
$ pushd module
$ python setup.py install
running install
running build
running build_ext
building '_renpy' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include -I/usr/include/SDL2 -I/usr/include/freetype2 -I/home/user/projects/venvs/renpy3/include -I/usr/include/python3.6m -c gen3/_renpy.c -o build/temp.linux-x86_64-3.6/gen3/_renpy.o -std=gnu99 -Wno-unused-function
gen3/_renpy.c:613:10: fatal error: pygame_sdl2/pygame_sdl2.h: No such file or directory
 #include "pygame_sdl2/pygame_sdl2.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Can somebody please help me?

**Comment by dogtopus** [comment]
1. Make sure you built and installed `pygame_sdl2` properly.
2. Seems that you are running Ren'Py under Python 3. Note that Python 3 support is still WIP and Ren'Py still won't start under Python 3 the last time I checked (not so long ago). So please switch to Python 2.7 for now.

**Comment by alevikpes** [comment]
>     1. Make sure you built and installed `pygame_sdl2` properly.
> 
>     2. Seems that you are running Ren'Py under Python 3. Note that Python 3 support is still WIP and Ren'Py still won't start under Python 3 the last time I checked (not so long ago). So please switch to Python 2.7 for now.

Thank you. Will try it
