### ISSUE TITLE
Autovoice doesn't work inside menus

### ISSUE THREAD

**Issue by artyrambles** [renpy/renpy#2337]
I got a menu with a spoken line inside it, and even though the dialogue line shows up in the dialogue.tab, and all the files are present and working, the line is silent in game.

My code looks like this:
```
menu:
        ja "Some spoken line."
        "Some option.":
            jump .option1
        "Some other option.":
            jump .option2
```

The "Some spoken line" doesn't get voiced.

**Comment by artyrambles** [comment]
I'm using Renpy 7.3.2.320, if it matters.

**Comment by sunrisesarsaparilla** [comment]
I could not duplicate this bug. I suggest closing it.

**Comment by artyrambles** [comment]
> I could not duplicate this bug. I suggest closing it.

Since I reported it more than four years ago, I assume it was fixed in the meantime.
