### ISSUE TITLE
Lint unable to find dynamic variables

### ISSUE THREAD

**Issue by mal** [renpy/renpy#2343]
This looks to be related but also separate from https://github.com/renpy/renpy/issues/1534 (which now appears fixed). While lint understand parameters, it seems it doesn't comprehend dynamic variables.

**File**
```rpy
label issue2343:
    $ renpy.dynamic(t=Transform(yzoom=-1))
    show text 'HELLO WORLD' at t              # lint error
    pause
    return

label issue1534(t=Transform(xzoom=-1)):
    show text 'HELLO WORLD' at t              # no lint error
    pause
    return
```

**Lint output**
```
Ren'Py 7.4.0.619 lint report, generated at: Wed Sep  2 17:37:13 2020

game/src/script.rpy:3 Could not evaluate 't', in the at list of a scene or show statment.
Perhaps you forgot to define or misspelled a transform.
```

**Comment by renpytom** [comment]
Not a bug. Lint is by definition not perfect, it's there to suggest possible errors rather than 100% definitive ones. In this case, it can't solve renpy.dynamic. The way to stop the warning is to create a global variable `t` that gets shadowed.

**Comment by mal** [comment]
Ahh fair enough, I thought perhaps it would be possible to capture the names of the variables defined by `dynamic` and add them to lint's understanding of local state or something along those lines, but upon reflection (and after some sleep) I realise there's no good way to extract dynamic definitions from python blocks.

The only way this could be reliable would be to have a separate statement, something like `dynamic var = value`, which would be of questionable use outside of this specific linting issue to the point of being a non-starter. Thanks for the response. 🙂
