### ISSUE TITLE
Android SDK 29 not work

### ISSUE THREAD

**Issue by pelatihan102** [renpy/renpy#2345]
Hi, tanks for this support.

I found problem when i build apk with new Android SDK 29 with latest nightly renpy, when i test apk in my phone there is auto close after splash. last week i build using SDK 28 there is ok and no error. and we cant choose where SDK default we can use. Any one can help? Thanks.

Regards.
Aan

**Comment by renpytom** [comment]
Please send a logcat with the error.

**Comment by pelatihan102** [comment]
I mean, we success build apk with Android SDK 29, but when i test the apk in my phone, there game auto close after splash screen. Different with Android SDK 28 no problem.

**Comment by renpytom** [comment]
Yes. The logcat output is required so I can see what's going wrong. I'm not going to drop back to targeting 28, as Google rejects it from the store.

**Comment by pelatihan102** [comment]
Ok. wait a minute.

**Comment by pelatihan102** [comment]
![image](https://user-images.githubusercontent.com/31663375/92070586-9feb3e80-edd6-11ea-8387-b44dae1d8441.png)

Hi, i think logcat not work in my laptop, its 20 minute stay without change. Any suggestion?

**Comment by renpytom** [comment]
You need to hook your phone up to your laptop via USB.

**Comment by pelatihan102** [comment]
hi, its difficult to get data, i fail to run logcat with device, i many try but nothing, iam sorry. Just info my phone are android 5 and android 6. Sorry about it.
