### ISSUE TITLE
[Feature/Q] Add VSCode (or VSCodium) to the Suggested Text Editors

### ISSUE THREAD

**Issue by manuth** [renpy/renpy#2348]
When editing a file, some text editors (such as Atom, Editra and jEdit) are suggested to install or open files in.
It'd be awesome to have VSCode (or VSCodium) as a choice here.
VSCode is quite similar to Atom, it brings capabilities to edit and execute python code as well.

Is there some way I can add VSCode as a choice by myself as a workaround?

**Comment by StudioErrilhl** [comment]
It would be nice if there was a general "browse to app/program" so you could pick any editor you choose. Not sure why it's not possible.

**Comment by kobaltcore** [comment]
It is already possible to add support for arbitrary, non-default editors, see the documentation here: https://renpy.org/doc/html/editor.html

**Comment by manuth** [comment]
Awesome, thank you so much 😄
I'll go test it and set up a PR when I get the chance

**Comment by kobaltcore** [comment]
Oh yeah, I just remembered that I made two small integrations for text editors some time ago. I'll paste them here for posterity, in case anybody else comes across this issue.

## Visual Studio Code
```python
import os
import subprocess

import renpy.editor

class Editor(renpy.editor.Editor):

    def open(self, filename, line=None, **kwargs):
        filename = renpy.exports.fsencode(filename)
        arg = filename if line is None else "%s:%d" % (filename, line)
        if renpy.windows:
            subprocess.call(["code.exe", "-r", "-g", arg])
        elif renpy.macintosh or renpy.linux:
            os.environ["PATH"] += ":/usr/local/bin"  # is not in PATH by default
            subprocess.call(["code", "-r", "-g", arg])
```

Put this in a file named `VisualStudioCode.edit.py` and save it in the root level directory of any Ren'Py project. The Launcher will pick it up and offer it as a choice in the editor selection screen under the name `VisualStudioCode`.

## SublimeText
```python
import os
import subprocess

import renpy.editor

class Editor(renpy.editor.Editor):

    def open(self, filename, line=None, **kwargs):
        filename = renpy.exports.fsencode(filename)
        arg = filename if line is None else "%s:%d" % (filename, line)
        if renpy.windows:
            subprocess.call(["subl.exe", arg])
        elif renpy.macintosh or renpy.linux:
            os.environ["PATH"] += ":/usr/local/bin"  # is not in PATH by default
            subprocess.call(["subl", arg])
```

Put this in a file named `SublimeText.edit.py` and save it in the root level directory of any Ren'Py project. The Launcher will pick it up and offer it as a choice in the editor selection screen under the name `SublimeText`.

In some cases the command-line executables for a text editor may not be sym-linked into a directory that's in the `PATH` upon installation, so sometimes you may have to do this manually. Notably I had this issue with SublimeText on macOS, but your mileage may vary.

**Comment by manuth** [comment]
Awesome! I'll create a PR containing these two editors ASAP
Thank you very much for providing your implementations! 🥳

**Comment by kobaltcore** [comment]
I do want to note that the default editors available in the Launcher use a less public-facing system, as can be seen [here](https://github.com/renpy/renpy/blob/master/launcher/game/editor.rpy#L138-L213). I assume Tom would prefer any editors in the default selection to be one of these FancyEditor objects with additional information, though I'd defer to his input on that.
As such I'm not sure a PR with the above would be sufficient.

**Comment by manuth** [comment]
Thank you so much for your help!
I had a look at the `Ren'Py` and also at your VSCode snippet - I simplified it to the following:

```py
import os
import subprocess

import renpy.editor

class Editor(renpy.editor.Editor):

    def open(self, filename, line=None, **kwargs):
        filename = renpy.exports.fsencode(filename)
        address = filename if line is None else "%s:%d" % (filename, line)
        subprocess.call(["code", "-g", address], shell=True)
```

I'll create a PR for adding SublimeText and VSCode to Ren'Py

Thanks again for your help :D

**Comment by renpytom** [comment]
This will be one of the major features of 7.5/8.0.

**Comment by manuth** [comment]
Awesome! Thank you so much for your great work 😄
