### ISSUE TITLE
Ren'Py slows down over time?

### ISSUE THREAD

**Issue by hell-oh-world** [renpy/renpy#2355]
Hello guys! Hope you're all doing alright.
I have an issue that I can't figure out whether it is related to my machine or related to Ren'Py.

Okay, so the gist of the issue is that whenever I'm using Ren'Py the engine always slows down over time especially when a screen has a `timer` and some displayables in the screen become unresponsive, meaning I can't achieve the hover effect etc. properly, restarting the computer fixes the issue but again, once I use it over time it slows down again. I'll provide video links of what it looks like.

This is how the game should normally work: [Working Good](https://streamable.com/wxuzq6)
This is how the game acts slowly due to an unknown reason: [Working Slowly](https://streamable.com/m8f4sf)

As you can see, in the first video, the game works smoothly I am able to achieve the things that I want the idle and hover effects, but in the second video the fps drops in that part, and displayables start to become unresponsive to the mouse events.

I've included in the video the current process being handled by my machine through the task manager assuming that I think it would be helpful. Also, in the second video (issue), I've enabled the performance diagnostic screens placed on the top left corner of the game. I also tried to include it in the first video (working), but unfortunately, I can't seem to achieve the hover effect when they're showing so I hid them in that video. You might think that it might be the issue (showing the performance screen) but no. I swear that even if the performance screens are hidden the game still acts like that.

Additionally, if this would be helpful, I'm using a `timer` in that screen to achieve the countdown effect, it has a ` delay (1 / 30.0)` with `repeat True`. I'm thinking that this has something to do with the `timer`? because I observe that whenever a `timer` has a very quick delay the screen would become unresponsive, especially when trying to hover over things. But then again it doesn't make sense to me as in the two videos the working and the slow one both are using the same code, and my code works normally in the first video. I did also observe that the fps seems right and normal when there's no `atl`s or `timer`s, so I'm not sure whether it slows down in all part of the game or just in those parts where `atl`s or `timer`s appear. But I can't really tell since the dialogues don't use cps.

I'll include the screenshots of my machine's specifications, maybe these would give you guys more idea about the issue.
![CPU](https://i.ibb.co/hm5nkzZ/cpu.jpg)
![Graphics](https://i.ibb.co/0Xd8c8D/graphics.jpg)
![Memory](https://i.ibb.co/Mng8Gb2/memory.jpg)

And lastly, I'm using Ren'Py 7.4.0.731 and Windows 10. To fix the issue I've tried to work with the stable release but still the same issue and I did also all the functionalities that the launcher can offer such as recompiling, deleting persistent etc., but sadly all of them didn't seem to work. Restarting fixes the issue, but not signing out.

Hope I provided the necessary information. Thank you for reading this.

**Comment by uyjulian** [comment]
Does the issue occur with a fresh install of Windows 10?

**Comment by hell-oh-world** [comment]
I just formatted my computer recently like 2 weeks ago. And I actually did it in hope of that it will fix the issue but still the same, once I use Ren'Py long enough, screens start to drop their fps and displayables start to become unresponsive to mouse events when a `timer` is present.

**Comment by uyjulian** [comment]
Did you use the following tool: https://www.microsoft.com/en-us/software-download/windows10startfresh

**Comment by hell-oh-world** [comment]
Not really sure whether that tool is the same as what I did, but I reformatted the machine from the settings through the reset option with the option of keeping my personal files, I then, later on, deleted the old windows installation after resetting.

**Comment by dogtopus** [comment]
I saw your CPU isn't turboing up as it should under load. That's probably the cause. Could be a firmware bug on turbo control. Did you get this computer recently or did you change anything recently like updating the firmware/BIOS? If not did you experience anything like this before?

BTW quick Google search shows this: https://community.amd.com/thread/235235. Not sure if related.

Anyway this doesn't seem to be Ren'Py related.
