### ISSUE TITLE
GL2 scaling artifact in Frame displayable

### ISSUE THREAD

**Issue by TropeCode** [renpy/renpy#2365]
When using a Frame displayable with an image that is bigger in one dimension (or both) than the area where the Frame is used, the sections of the Frame get downsampled in a way that creates a visual artifact.

To illustrate the problem, here is a box with a background Frame with 8 pixel borders, and its source image.

![dark_frame](https://user-images.githubusercontent.com/52769598/93718747-5e9cb200-fb7e-11ea-8c7a-70249176fabe.png)
![scaling_bug](https://user-images.githubusercontent.com/52769598/93718796-a0c5f380-fb7e-11ea-8db8-57f7091ee567.png)

For comparison, here is a box variation that uses a smaller source image (which I'm not using in practice because it lacks a vertical gradient, which is why the other image is so tall).

![light_frame](https://user-images.githubusercontent.com/52769598/93718750-6197a280-fb7e-11ea-876a-b467b6991d79.png)
![scaling_ok](https://user-images.githubusercontent.com/52769598/93718798-a28fb700-fb7e-11ea-8119-73de32190f8c.png)

This bug started occuring with GL2. My suspicion is that before, with GL (one), the image was linearly interpolated, but with GL2 it's also using mipmaps. Since the mipmaps maintain the aspect ratio, the smaller ones aren't suitable for the type of downscaling that might happen in a Frame.

**Comment by renpytom** [comment]
I decided to address this by turning on anisotropic filtering, which seems to handle this well.
