### ISSUE TITLE
[Request] Support auto-updating over https

### ISSUE THREAD

**Issue by GiovanH** [renpy/renpy#2377]
The renpy auto updater currently uses an old version of zsync to perform network syncs, which doesn't support SSL.

~~As-is it seems like a security issue, as ren'py games replace themselves with executable code downloaded over http and then executes it.~~

It'a also just a massive inconvenience for people who have secure-by-default web hosting, which is a growing population.

**Comment by renpytom** [comment]
It's the only version that supports windows, though. 

Ren'Py actually signs the updates, so it's not a problem. For other games, chances are they use the itch app and things like that, rather than the builtin updater.

**Comment by GiovanH** [comment]
Isn't zsync just a selective implementation of the rsync algorithm? In theory, it should be possible to bundle a cross-platform ssl-supporting sync with full backwards compatibility, even if it isn't actually zsync. 

I'm not saying it's *urgent*, just suggesting that it might be a good long-term goal.

**Comment by renpytom** [comment]
Oh, sure, and if you're looking to contribute, it would be a great place to do so. I'm just explaining why it's not done yet.

**Comment by renpytom** [comment]
I believe this is now supported, though zsync isn't used - it's just a full, automatic update.  I'll keep an eye out for a version of zsync that support https.

**Comment by mpldr** [comment]
It seems zsync development moved on to https://github.com/AppImage/zsync2
