### ISSUE TITLE
[Bug] Functions from Python objects are executed twice despite only being called once

### ISSUE THREAD

**Issue by melodicstream** [renpy/renpy#2378]
I managed to make a minimum reproducible example:

```py
init python:
    class World:
        def hello_world(self):
            print "hello world"

default w = World()

label start:

    $ w.hello_world()

    "end"

    return
```

If I run the game, when the game gets to the "end" line my expectation is that when I open the Console I'd only see the string "hello world" written once. However, it gets printed twice.

This behavior is breaking some of my code. Is this a genuine Ren'py bug? If so, is there a workaround I can use to prevent that from happening on version 7.3.5.606?

**Comment by daihaminkey** [comment]
Didn't test issue yet, but as a workaround you can use flag, that tracks execution of a function. 

Simple way to do it:
```python
class World:

    def __init__(self):
        self.__is_hello_world_executed = False

    def hello_world(self):
        if __is_hello_world_executed:
            return
        __is_hello_world_executed = True

        print "hello world"
```

Hard, but more clean way - do the same, but via decorators. I'm not writing decorator code here, but the result may be something like this:

```python
class World:

    @execute_once
    def hello_world(self):
        print "hello world"
```

**Comment by daihaminkey** [comment]
I think, good idea is to test this not onloy within renpy script (`.rpy`, `init python`), but also in pure python ('.py' with import to renpy scope). There is a chance, that result would be different.

**Comment by melodicstream** [comment]
Hm... Ok! I'll try the pure .py file first and if that doesn't work I'll go the decorator route. Writing one for that shouldn't be all that hard.

**Comment by renpytom** [comment]
This isn't really a bug - Ren'Py is doing a rollback upon console entry. Rollback gets a little weird when it comes to having side effects, but so long as you don't have side effects, it's fine. In general, Ren'Py doesn't play too well with scripts that produce side effects that aren't just Ren'Py interacting with the user - it's a visual novel engine, and not a general programming framework.

I'd advise against the pure python approach - classes written in pure python don't  participate in rollback, and hence that's a problem.

**Comment by melodicstream** [comment]
I see. So the reason why it's printing a second time is because of the fact that I opened the console. That already helps me on how to proceed with what I want. Thanks!
