### ISSUE TITLE
 The operation couldn’t be completed. (Mach error -308 - (ipc/mig) server died)

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2380]
![image](https://user-images.githubusercontent.com/60040734/94992547-ab907780-05c5-11eb-8c1b-061ef2895df4.png)

Whenever I try to test project with an emulator in Xcode, the sentence ' The operation couldn’t be completed. (Mach error -308 - (ipc/mig) server died)' appears.
This is a problem with Xcode version 12.0.0.1 and ren’py version of September 28, 2020(nightly). (With the latest version, I couldn't test it because there was an error in the installation stage of renios.)
Actually, I've reported on this problem before, but it hasn't been solved yet.
In the past, I tested it in Xcode 11, ren’py 7.3.5. But the same result came out then.
I'd like to know if there's a problem with settings of my Mac, and if it's not that, if it's problem of ren’py, I'd appreciate it if you could fix it.

**Comment by renpytom** [comment]
I don't believe this is a Ren'Py issue, but one with the iPhone simulator. You'll have to address this with Apple, as I don't believe that this is something I can do anything about.
