### ISSUE TITLE
Layeredimage does not display default attribute if attribute name is not unique

### ISSUE THREAD

**Issue by Euphemismus** [renpy/renpy#2387]
This behavior of layeredimage is not documented and I really can't tell if it is intended or not, so reporting as issue.

Code that reproduces issue (tested in 7.2.2.491):
```layeredimage testimage1:
    align (0.5, 0.5)
    group color1:
        pos (-60, 0)
        attribute red default:
            Solid("#f00", xysize=(100,100))
        attribute blue:
            Solid("#00f", xysize=(100,100))
    group color2:
        pos (60, 0)
        attribute red default:
            Solid("f00", xysize=(100,100))

layeredimage testimage2:
    align (0.5, 0.5)
    group color1:
        pos (-60, 0)
        attribute red1 default:
            Solid("#f00", xysize=(100,100))
        attribute blue1:
            Solid("#00f", xysize=(100,100))
    group color2:
        pos (60, 0)
        attribute red2 default:
            Solid("f00", xysize=(100,100))


label start:
    show testimage1 red
    "Expectation & actual: two red squares."
    show testimage1 blue
    "Expectation: blue square on left, red square on right. Actual: blue square on middle, no other square."
    hide testimage1
    show testimage2 red1 red2
    "Expectation & actual: two red squares."
    show testimage2 blue1
    "Expectation & actual: blue square on left, red square on right."
    hide testimage2
    return
```

Why this is relevant:
I stumbled upon this when I had a character who had an "angry" head and "angry" brows, but only "smile" head. I expected "mychar smile" to show "smile" head and "neutral" brows. Instead, since the "neutral" name was used several times, I got no brows whatsoever. Using only unique names will quickly get quite clunky, even if "if_any" and "if_not" help a bit.

Other notes:
Thanks for developing Ren'py!

**Comment by renpytom** [comment]
I don't think this is a bug. You're saying, in the first group, that red and blue conflict. So when you do "show testimage1 blue", that would mean that the 'red' attribute isn't allowed. 

I'd suggest that if you wanted this, you could have color1_default and color2_default attributes, in addition to the names you're using. You wouldn't actually be typing them in, so they can be as long as you need.
