### ISSUE TITLE
Browser launch error

### ISSUE THREAD

**Issue by tellts** [renpy/renpy#2389]
Hello. V. 7.3.5.606 in Lubuntu 20.04.

When in the dialog about the game I click on the Ren'py link, the browser does not start (a window pops up with an error message : Firefox had a problem and crashed.). In other programs, clicking on a link in the interface launches the browser normally.

**Comment by renpytom** [comment]
I believe this is fixed in Ren'Py 7.4. (At the very least, 7.4 uses a new approach to library management, and clicking through to launch chrome works here.)
