### ISSUE TITLE
Error starting code editor

### ISSUE THREAD

**Issue by tellts** [renpy/renpy#2390]
Hello. V. 7.3.5.606 in Lubuntu 20.04.

When I select Atom or jEdit, this setting is not saved. It only helps to select a globally installed code editor for files with the py extension. Or maybe it's not about the extension, I don't remember exactly. But you can see that something is not working correctly.

**Comment by renpytom** [comment]
Closing, as this was simply missed. I'm sorry. Please reopen this issue if you're still having problems.
