### ISSUE TITLE
In iOS, the screen size of the projects is very small.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2415]
![image](https://user-images.githubusercontent.com/60040734/96732508-5f319e00-13f3-11eb-9252-4f11ffcb5171.png)

In iOS, the screen size of the projects is very small.
I have the same problem in all projects.

- Ren'py Nightly Build(October 20, 2020) with Xcode 12.

**Comment by renpytom** [comment]
Can you tell me what size your game is configured to use, and what device you're testing on? (The former is at the top of gui.rpy, in the gui.init line.)

**Comment by ikusorae** [comment]
I don't think it's a problem with a specific project because the same problem occurs when I test it after I create a new project.
The project is using a size of 1280x720 specified by default. The device that tested the project was iPhone X.

**Comment by renpytom** [comment]
I've tried this on an iPhone X simulator, and an iPad Mini 2. I'm unable to repeat this problem with the current version of Ren'Py.

**Comment by ikusorae** [comment]
Well, did you test it at Nightly Build? The Stable version does not have this issue. It could be a problem with my test device, so I'll try it again and get back to you.

**Comment by renpytom** [comment]
I tested it with the master branch, which might be a little ahead of the nightly build. But I can't think of anything relevant that would have changed between then and now.

**Comment by ikusorae** [comment]
Okay, thank you. I will contact you after the test again.

**Comment by ikusorae** [comment]
Basically, I took the possibility that there was a problem with Xcode and tested it in two versions of Xcode (11, 12).
Another reason is that the Stable version of Ren'py has an error in Xcode 12.
All of the projects tested to rule out the possibility of problems with existing projects are newly created with the default settings for Ren'py.

![image](https://user-images.githubusercontent.com/60040734/97316889-9bf70c80-18ad-11eb-8b1c-508dfddeebd9.png)

1. Tested with Ren'py Nightly + Xcode 12.
The same problem as the first report occurs. As expected, the screen of the game appears small.

Also, I tested it after setting it to 1920x1080 size.
As the same result was obtained, I thought it was not a problem with the resolution size.

![image](https://user-images.githubusercontent.com/60040734/97316942-a9ac9200-18ad-11eb-9759-690b5ef9357e.png)

2. Tested with Ren'py Nightly + Xcode 11.
I thought there might be a problem with the latest Xcode, so I tested it with a different version of Xcode. But the same result came out as before.
In conclusion, I decided there was no problem with Xcode.

3. Tested with Ren'py Nightly(Windows) + Xcode 12.
I tested this just in case. I was wondering if there was a problem with my macOS environment, so I downloaded the Renpy nightly version from Windows and manually installed renios. And I created the Xcode project in a Windows environment, moved it to mac, and tested it. The result is the same problem as before.

![image](https://user-images.githubusercontent.com/60040734/97316817-8255c500-18ad-11eb-934e-520872cb2e31.png)

3. Tested with Ren'py Stable + Xcode 11.
Everything is fine. There is no problem except that there is an error with Xcode 12.

As a result, all problems occurred only in Ren'py nightly.
So I decided, more fundamentally, that I would look for where the problem came from.

![image](https://user-images.githubusercontent.com/60040734/97317058-c3e67000-18ad-11eb-9d4d-edc5713b0e83.png)


Then I found something while minimizing the screen.

I found out that the 16:9 ratio screen feels like it's trapped in a 'container' with a different resolution and a letterbox is created up and down.

![image](https://user-images.githubusercontent.com/60040734/97317101-d06ac880-18ad-11eb-8e5f-26a6f5ce6f09.png)


I've reconstructed it graphically. It feels like the picture right above it.
As expected, I got an idea here.

![image](https://user-images.githubusercontent.com/60040734/97317148-dd87b780-18ad-11eb-91d2-6901a551dd62.png)


I thought that if I make a project with a ratio (ex. 4:3) that is not restricted by the ‘container’ as above, the problem that the vertical is not full will not occur.
So I quickly created a project with a 4:3 ratio of 1024x768 resolution and tested it.

![image](https://user-images.githubusercontent.com/60040734/97317238-f001f100-18ad-11eb-89c6-66d0da3957ca.png)


Yes, it was as I expected. A project with a ratio that fits inside the 'container' is coming out on the screen with a full vertical ratio.
In conclusion, I concluded that the problem occurred because the ratio of this invisible 'container' was not 16:9.

That's why the other ratio, 'container', seems to be preventing the 16:9 screen from filling the vertical completely. Also, it seems that there is a letterbox on the top and bottom of the 'container'.

I haven't made any modifications to Ren'py, and the projects created are all new.
So, I think this is a problem that needs to be fixed.

My guess is that the ratio of invisible 'containers' is 16:9 or longer, which will solve the problem.

Thank you.

**Comment by rdurfee** [comment]
If your project does not use a launch storyboard, it will always be "letterboxed" into a safe zone because Xcode doesn't think it's compatible with devices that do not have a home button, so it constrains the app into the safe area, which makes it so the home bar is always visible outside the game area.

The stable version of RenPy uses the old launch images instead of a launch storyboard. The easiest way to fix this is to create a launch storyboard and set the Launch Screen File to that storyboard. Once you do that, the game will fit the entire screen, letterboxing as needed depending on the device's aspect ratio (e.g., on the sides on a phone, and top/bottom on an iPad).

**Comment by ikusorae** [comment]
Thank you, I'll try that way.

**Comment by ikusorae** [comment]
Thank you. I'll try that way and leave a comment again.

**Comment by ikusorae** [comment]
![P20201028_211004000_3AD10921-A8CE-4BFC-B739-0D5D28275183](https://user-images.githubusercontent.com/60040734/97434592-93acd900-1962-11eb-8e10-64b0dc80f0c8.PNG)

As a result, when I set the Launch Screen File to Launch Screen.storyboard, everything works fantastic.
Thank you so much to renpytom and rdurfee.
