### ISSUE TITLE
In macOS, an error message occurred when setting up the Xcode project directory.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2416]
![image](https://user-images.githubusercontent.com/60040734/96735397-8047be00-13f6-11eb-8f6b-79a0ded01733.png)

In macOS, an error message occurred when setting up the Xcode project directory.
I tried installing python3, but it didn't work.
This issue does not occur with the Stable version of Ren'py.

- Ren'py Nightly Build(October 20, 2020)

**Comment by renpytom** [comment]
Which version of macos are you using?

**Comment by ikusorae** [comment]
I'm using version 10.15.7 Catalina, the latest version of macOS.

**Comment by renpytom** [comment]
Thanks. This will be fixed in the next nightly.
