### ISSUE TITLE
music issue on android

### ISSUE THREAD

**Issue by weypro** [renpy/renpy#2419]
I built an android package successfully with a sample, but the music could not be played on my android devices. I decompressed the .apk package and found that the path of music(*.ogg) was renamed by adding "x_". Whether it causes this issue? Or how can I solve it?

**Comment by renpytom** [comment]
It's working for me. What version of Ren'Py are you using?

**Comment by weypro** [comment]
7.3.5, the latest. 
```
play music "./audio/bgm_1.ogg" fadein 1.0 fadeout 1.0
```
And this is my code. It works on my pc.

**Comment by renpytom** [comment]
Can you try it as:

```
play music "./audio/bgm_1.ogg" fadein 1.0 fadeout 1.0
```

? The ./ is not needed or allowed, and my guess is that is what is causing the problem.

**Comment by weypro** [comment]
You are right. Thank you very much.
