### ISSUE TITLE
Apk size error in Renpy Android Package

### ISSUE THREAD

**Issue by ChloeRaven** [renpy/renpy#2422]
I'm having a problem when I try to package a 600+ mb renpy game for android.
Whatever I try, it works perfectly and renpy creates the apk files and put them in a folder, but they decrease VERY in size and delete several game files. Is this because the game is too big or something? What should I do??

**Comment by renpytom** [comment]
Hm... Is it possible you're telling it to use an expansion APK, and hence it's creating an obb file?

**Comment by ChloeRaven** [comment]
Not really. I did it the same way as I did withmy old ports for android (without creating a obb), and they all worked, but this one, which is bigger than others, doesn't work. The build works perfectly, but most game files are removed and from 600+ mb goes to 200 mb, making the port don't work on phone.

**Comment by ChloeRaven** [comment]
> Hm... Is it possible you're telling it to use an expansion APK, and hence it's creating an obb file?

Not really. I did it the same way as I did with my old ports for android (without creating a obb), and they all worked, but this one, which is bigger than others, doesn't work. The build works perfectly, but most game files are removed and from 600+ mb goes to 200 mb, making the port don't work on phone.

**Comment by renpytom** [comment]
Could you post the APK somewhere, so I can pick it apart to see what's missing?

**Comment by ChloeRaven** [comment]
> Could you post the APK somewhere, so I can pick it apart to see what's missing?

Here: http://www.mediafire.com/file/8oqk8c5fxdrndzg/com.blueskies.ddlc-10005-universal-release.apk/file

Here is the original game folder (which I already tested and programmed to work on android): https://imgur.com/a/prXWoy6

And those are the only files that the renpy package within the apk... : https://imgur.com/a/cUlrt9A

**Comment by Lolimipsu** [comment]
have you tried checking the Build configuration? in my experience with ddlc modding .rpa and outside files  don't go well. Try using [rpa-tool](https://github.com/Shizmob/rpatool) and make sure you add your files in Build Configuration, It can be found in options.rpy.

**Comment by ChloeRaven** [comment]
> have you tried checking the Build configuration? in my experience with ddlc modding .rpa and outside files don't go well. Try using [rpa-tool](https://github.com/Shizmob/rpatool) and make sure you add your files in Build Configuration, It can be found in options.rpy.

I managed to solve the problem. It was like you said, I had forgotten to add important informations in opinion.rpy and many lines of build.package and build.archive were missing, and when I added them everything went well. Thank you ^^
