### ISSUE TITLE
Mac About menu is not very useful

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2424]
On a Mac, the About Menu only displays the build.name and a generic folder icon. It would be nice if it displayed the icon, the company name, copyright, version and also used the Display Name.
![Screen Shot 2020-10-27 at 4 54 24 PM](https://user-images.githubusercontent.com/12246002/97363216-9f23d580-1878-11eb-8262-634cf7609ef3.png)

The menus also use the build.name instead of the display name in all of the menu options.
![Screen Shot 2020-10-27 at 4 53 14 PM](https://user-images.githubusercontent.com/12246002/97363313-c4184880-1878-11eb-8072-dabd6955c0cb.png)

**Comment by renpytom** [comment]
Are you actually building your game, and supplying it an Icon.icns file? At least in Ren'Py 7.43, I'm seeing a more useful about screen - it has the icon, the game's name (build.display_name or config.name) and the version. I'm about to add config.mac_info_plist, which would let you add additional plist keys to customize things further.

**Comment by rdurfee** [comment]
I have supplied the icon, and it shows correctly as the app icon and in the dock. I haven’t tried it with 7.4 yet, so I will check that out. The additional plist keys will be helpful for some things.

**Comment by renpytom** [comment]
Closed in 8f9e072.
