### ISSUE TITLE
Google Play flags Ren'Py 7.3.5 as having IAP.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2429]
https://lemmasoft.renai.us/forums/viewtopic.php?p=535594#p535594

**Comment by ashl1** [comment]
I think this mark might confuse players and aware them to not install completly free applications

**Comment by Gouvernathor** [comment]
d06a6f3034b6c2c5facda731dc860a565d85ca9d is related

**Comment by mal** [comment]
I don't think it's really related to that commit besides them both touching on IAPs, is it?

Anyway, I believe this issue was duplicated and resolved by #3623 for 7.5/8.0.

**Comment by renpytom** [comment]
I concur, this can be closed.
