### ISSUE TITLE
Lint Check In Azure Pipeline

### ISSUE THREAD

**Issue by Lokanath-hue** [renpy/renpy#2436]
Hi All,

I am trying to set up a azure pipeline , The goal is to run the "lint" command and later check the output lint file.
I have setup the command like this 
"Source\renpy-7.3.5-sdk\lib\windows-i686\pythonw.exe" -EO "Source\renpy-7.3.5-sdk\renpy.py" "Source\<Project Name>" lint "lint.txt" 
When I run the pipeline I get the following error, Probably the azure server does not have a sound card.
I am not sure if this is an issue or not but I would love to have this automated instead of me running the lint everytime on my PC after every commit.
Please let me know if there is a workaround?

 File "D:\a\1\s\Source\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "D:\a\1\s\Source\renpy-7.3.5-sdk\renpy\main.py", line 565, in main
    renpy.display.core.Interface()
  File "D:\a\1\s\Source\renpy-7.3.5-sdk\renpy\display\core.py", line 1659, in __init__
    renpy.audio.audio.init()
  File "D:\a\1\s\Source\renpy-7.3.5-sdk\renpy\audio\audio.py", line 860, in init
    renpysound.init(renpy.config.sound_sample_rate, 2, bufsize, False, renpy.config.equal_mono)
  File "renpysound.pyx", line 383, in renpy.audio.renpysound.init
  File "renpysound.pyx", line 98, in renpy.audio.renpysound.check_error
Exception: DirectSoundCreate: No audio device found

After initialization, but before game start.
Exception: DirectSoundCreate: No audio device found

**Comment by renpytom** [comment]
I believe ``export SDL_AUDIODRIVER=dummy`` should disable sound intialization. That being said, I'm not sure why it's trying to start here in the first place, so let's leave this open.

**Comment by Lokanath-hue** [comment]
I merged delta changes to renpy 7.3.5 locally, Now Azure has no issues in running the lint.
Thanks for the quick support 👍
