### ISSUE TITLE
Bug - dialogue extraction tool does not grab sayer image attributes

### ISSUE THREAD

**Issue by Eliont** [renpy/renpy#2441]
Hello and good time of day.

Code:
`gg gg9 "Хм... Думаю, по-хорошему тут не выйдет..."`

dialogue.tab
`prologue_1ea407fe	gg	Хм... Думаю, по-хорошему тут не выйдет... game/_story/prologue.rpy	92`

**Comment by renpytom** [comment]
I don't think this is a bug. This is meant to extract dialogue, and it's not clear why we'd expect it to extract the sayer attributes, which aren't part of the dialogue.

**Comment by Eliont** [comment]
Sayer attribute is part of sayer character, in this case they define side image, and without attributes - there are no side image shown.
If this not a bug, can you please, make it a feature ? Is is possible fix engine code somewhere right away ? Version 7.3.5.606

We localizing game by exporting dialogue.tab to Google Tabs, translating it in additional column, and then converting to renpy tl code.

But omitting sayer attributes is huge issue.

**Comment by renpytom** [comment]
I've added this. What I did was add another column to dialogue.tab, that includes all of the source code surrounding the dialogue in its own  column. This should be easy-ish to backport to 7.3.5, and will be in the next 7.4 nightly.
