### ISSUE TITLE
Roll Forward doesn't apply SetVariable() or Play() inside action

### ISSUE THREAD

**Issue by TheUntamed** [renpy/renpy#2442]
I have a screen with an imagebutton which contains an action:
action [SetVariable("example_variable", False), Play("sound", "sfx/example_sound.mp3"), Jump("example_label")]

When the button is pressed normally, everything works fine, but If I use Roll-Forward only the jump is applied but neither the sound is played nor the Variable is changed. I don't really care about the sound, but the variable leads to inconsistency.

How to recreate the issue:
Create a screen with an imagebutton that contains an action like above. Play and press the imagebutton. Then rollback and afterwards roll forward. The variable should not be changed.

**Comment by renpytom** [comment]
I don't believe this is a bug. Roll Forward doesn't actually click the button, so the actions associated with the button don't run.

**Comment by TheUntamed** [comment]
But it should simulate a button click. Because that was the action that is rolled over. But I think rollback also doesn't do that.
In my case I have a variable that is changed twice. Once when the screen is entered by the player and once when the player leaves the screen.
The first change happens in a label just before it calls the screen. The second happens when a button is clicked that leaves the screen. The first change is always applied, even if rollback is used. The second change is not applied if it is rolled over by rollback or roll forward.

**Comment by renpytom** [comment]
I'll be honest and say I don't plan to make roll-forward simulate a button click. I don't see a good way of making this change, that doesn't add a ton of complexity . I'd suggest considering different ways to achieve what you're trying to do - my guess is that the end character callback is a better way to cause something to occur when dialogue is dismissed. 

https://www.renpy.org/doc/html/character_callbacks.html
