### ISSUE TITLE
Everytime I open the renpy launcher it errors and gives me a traceback (Renpy 7.4)

### ISSUE THREAD

**Issue by strawcup1** [renpy/renpy#2443]
I'm sorry, but an uncaught exception occurred.

After loading the script.
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 7: invalid continuation byte

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 461, in main
    game.persistent = renpy.persistent.init()
  File "renpy/persistent.py", line 223, in init
    filename = os.path.join(renpy.config.savedir, "persistent.new")
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/ntpath.py", line 85, in join
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 7: invalid continuation byte

this is the traceback, that I get I've no idea what it is, and why it's doing that.

**Comment by Andykl** [comment]
It seems it related to https://renpy.org/doc/html/problems.html#windows-encoding-problems

**Comment by renpytom** [comment]
I believe this should be fixed in the newest prereleases.
