### ISSUE TITLE
function statement interference in atl

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2444]
When supplying a `function` clause and an `xpan` clause or a transform including xpan manipulation to an atl-defined transform, the first written works but the second is ignored.
If it's another transform that alters the xpan, the other properties that inner transform is altering do perform nominally.
About the function, the glitch triggers whenever the returned value is other than None. Currified functions and even empty functions (returning 0 or another integer, as shown) trigger the bug all the same.

When the bug happenedto me the instructions were inside a `contains` block and the transform took a child, not sure if it changes anything about it, I didn't try it otherwise.

Test code :
```
init python:
    def transfunc(trans, st, at):
        return 1

transform testing(child):
    contains:
        child
        panning(1)
        function transfunc
    contains:
        child
        function transfunc
        panning(-1)

transform panning(direction):
    xpan 0
    linear 3 xpan 180*direction
    repeat

label start:
    show eileen happy at testing
```
One eileen will go right but the other won't go left.
If you add some actually useful stuff in `testfunc` they will work only on the still eileen but not the moving one.
If you add some other clauses in `panning` related to other properties than `xpan` or `ypan` they will be applied to both eileens.

I found a way around it (which doesn't change the fact that it's a glitch) : putting the pan-related stuff in a `parallel` block and the `function` clause in another works fine. To my big surprise, putting only one in a parallel block doesn't.

**Comment by renpytom** [comment]
I don't think this is supposed to work. From the documentation for ATL's function statement:


    If the function returns a number, it will be called again after that number of seconds has elapsed. (0 seconds means to call the function as soon as possible.) If the function returns None, control will pass to the next ATL statement.

https://www.renpy.org/doc/html/atl.html#function-statement

So what's happening is you're not actually getting down to the call to panning(-1), and it never runs.

**Comment by Gouvernathor** [comment]
Oh ! I hadn't seen that last clause.
But when the second transform (`panning` in my example) is altering two transform properties, like `alpha` and `xpan` for example, `alpha` will be altered and not `xpan`, that means panning(-1) does run at least partially, and isn't that a glitch ?
To reflect that case the `panning` transform can be modified like so
```
transform panning(direction):
    xpan 0
    alpha 1.0
    linear 3 xpan 180*direction
    linear 1 alpha 0.0
    repeat
```
If the `panning(-1)` statement weren't called, that eileen should remain visible at all times, but she doesn't.

**Comment by renpytom** [comment]
Trying out your example (in 7.4), she does say visible (and animated without movement) all the time.

**Comment by Gouvernathor** [comment]
Indeed, I can't replicate it now. I'm going to try again.

**Comment by Gouvernathor** [comment]
Wait but isn't it weird that when you put an effective clause in `transfunc`, like `trans.yoffset = at`, it only applies to the still eileen and not to the other ?

**Comment by renpytom** [comment]
No.

Basically, panning(1) traps execution with a repeat statement - your script is basically the same as:

```
init python:
    def transfunc(trans, st, at):
        return 1

transform testing(child):
    contains:
        child
        block:
            xpan 0
            linear 3 xpan 180
            repeat

        # execution never reaches this point.
       
        function transfunc
    contains:
        child
        function transfunc
 
       # execution never reaches this point.
 
       block:
            xpan 0
            linear 3 xpan -180
            repeat

label start:
    show eileen happy at testing
```

ATL is only running one statement per contains block, and so  the first block never leaves the "function" statement, and then second one never leaves the repeating block. Make sense?

**Comment by Gouvernathor** [comment]
I guess. I didn't think atl was working like that, for example the fact that the first `contains` has a `repeat` in it doesn't keep the second from happening. But I understand it in the way that a `parallel` statement should not be considered as implicit. It does make sense when you know that.
Thx a lot for your answers.
