### ISSUE TITLE
Request: Predict when Character will instantiate a new object

### ISSUE THREAD

**Issue by GiovanH** [renpy/renpy#2454]
In a game I'm working on I have a subclass of `Character` that conditionally transforms the text spoken by overriding the `__call__` method. This looks something like this:

```python
    class QuirkChar(ADVCharacter):
        def __call__(self, what, *args, **kwargs):
			what = transform(what)
            super(QuirkChar, self).__call__(what, *args, **kwargs)
```

This does not work for the following intuitive reason: the original `Character.__call__` implementation at `renpy/character.py` may conditionally instantiate a new object of Character, based on the passed `kwargs`:

```python
    def __call__(self, what, interact=True, _call_done=True, multiple=None, **kwargs):

        _mode = kwargs.pop("_mode", None)
        _with_none = kwargs.pop("_with_none", None)

		# If there are kwargs left over, after popping those and consuming other kwargs from the prototype:
        if kwargs:
            return Character(kind=self, **kwargs)(what, interact=interact, _call_done=_call_done, multiple=multiple, _mode=_mode, _with_none=_with_none)
```

If a new `Character` object is instantiated, `QuirkChar.__call__` gets called multiple times in the MRO, such that the `what` string gets transformed multiple times. The only way to prevent the multiple transformation is to predict whether or not a new `Character` object gets instantiated, which currently looks like this:

```python
    class QuirkChar(ADVCharacter):
        def __call__(self, what, *args, **kwargs):
            safe_kwarg_keys = ["interact", "_mode", "_call_done", "multiple", "_with_none"]
            if all(k in safe_kwarg_keys for k in kwargs.keys()):
				what = transform(what)

            super(QuirkChar, self).__call__(what, *args, **kwargs)
```
This works as a workaround, but it is obviously a very brittle solution. 

I suggest some sort of a method for `Character` objects that will report whether or not a call will mutate the MRO, so the prediction implementation and the logical implementation can stay in the same class. Subclasses, then, could use an abstract implementation such as

```python
    class QuirkChar(ADVCharacter):
        def __call__(self, what, *args, **kwargs):
            if not self.callWillMutateMRO(what, *args, **kwargs):
				what = transform(what)

            super(QuirkChar, self).__call__(what, *args, **kwargs)
```

**Comment by GiovanH** [comment]
Anticipating "you shouldn't conditionally transforms the text in the Character object, you should use custom text tags for that": I do, in fact, use custom text tags for this. In my implementation, the character __call__ transformation wraps the text body in custom text tags, based on the state of the character object. The tags themselves do as much of the heavy lifting as possible, but they don't obviate this problem.

**Comment by renpytom** [comment]
There's nothing involving the MRO here - you're confusing what's going wrong, as all that's happening is a second Character object is created, with the additonal arguments provided to it. That being said, I think a new method that can determine if any of the keyword arguments will create a second Character makes sense, and hence I've added ADVCharacter.has_character_arguments.

**Comment by GiovanH** [comment]
Oh, you're right, it's not technically the MRO, because there's a new object being created. I meant the function call chain, I guess.

Anyway, thanks!
