### ISSUE TITLE
Disco error screen on the last nightly build (7.4.0.978)

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2457]
I'm getting this instead of a normal error screen while triggering the glitch reported in #2456 (or others)
`config.gl2` is True, and I'm on Windows.
![Screenshot_96](https://user-images.githubusercontent.com/44340603/98459187-97c5cb80-2198-11eb-8863-5a860fce8708.png)
Maybe somehow related to #2342 ?

**Comment by renpytom** [comment]
Without some sort of replication, there's not much I can do here.

**Comment by Gouvernathor** [comment]
```
define config.gl2 = True

layeredimage whatever:
    # zoom .3
    always:
        "eileen happy"

label start:
    show whatever
    pause
```
Try opening the game, reaching the `pause`, uncommenting the `zoom` line then hitting Shift+R in the game. It triggers it for me.
If it doesn't I can maybe give you more information about my system, idk.

**Comment by renpytom** [comment]
That repeats for me.

**Comment by Gouvernathor** [comment]
You mean the bug does trigger ?
