### ISSUE TITLE
image attributes not predicted

### ISSUE THREAD

**Issue by Beuc** [renpy/renpy#2465]
Hi,

While testing a game with RenPyWeb, I noticed that some images were not predicted (pixelated preview).
Checking further with the latest nightly in desktop mode, I see that attribute prediction also fails according to the image log (F4).

To reproduce the issue, please find attached a version of The Question that uses image attributes rather than explicit 'show' statements.
[the_question-script.zip](https://github.com/renpy/renpy/files/5532683/the_question-script.zip)

Typically, after defining ```Character(_("Sylvie"), ..., image='sylvie')```,
'sylvie green smile' is not predicted for ```s smile "Hi there! How was class?"```, and
'sylvie blue giggle' is not predicted for ```s giggle "Will you marry me?"```
(but are otherwise displayed correctly).

I see this in both 7.3.5. and 7.4  nightly. I'm surprised nobody ever noticed so far (myself included).

**Comment by renpytom** [comment]
I believe this is fixed by 9d2ce440824377c161ba5fbbe392eca8d923f6b0 , 1ad6149e289a85201947573d6e4a96ba9b215c03 , and 2c1c1e7a452021428e986d86f1a9ff73cf264d1e .

**Comment by Beuc** [comment]
This works fine on my end, as far as I can test. Thanks!
