### ISSUE TITLE
main_menu_music not triggered

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2468]
The music I set using `define config.main_menu_music = audio.whatever` doesn't trigger when launching the gam and arriving to the main menu. However when I play the game then go back to the main menu, the music does trigger.
Happens with the last Nightly build, but not with the Prerelease nor with the Stable build.

**Comment by renpytom** [comment]
I've been unable to repeat this with renpy-nightly-2020-11-16-ac0dd6e36-sdk , and the script:

```
define _confirm_quit = False

define config.main_menu_music = audio.second_flight

label start:

    scene bg washington

    "..."

    return
```

Please let me know if you're having trouble with a clean game.

**Comment by Gouvernathor** [comment]
No, it doesn't happen in a clean game. I'll try to narrow down the issue to find out why it happens sometimes and sometimes not.

**Comment by Gouvernathor** [comment]
At the moment, i reached this (00start.rpy, line 240) :
```
    if config.main_menu_music:
        $ print(renpy.music.get_playing()) # returns None
        $ print(config.main_menu_music) # returns the right filename
        $ renpy.music.play(config.main_menu_music, if_changed=True)
        $ print(renpy.music.get_playing()) # returns None
    else:
        $ renpy.music.stop()
```
I'll update this comment if I get more info about what's happening.

**Comment by renpytom** [comment]
I'll note that Ren'Py may be starting the music a little later than it did before, which could plausibly change what happens with renpy.music.get_playing() before the first frame is displayed, which is now generally showing the main menu rather than a black screen for a few frames.

**Comment by Gouvernathor** [comment]
Ok so the issue lies in the compilation part. When I comment the `config.main_menu_music`, launch the game (recompiling options.rpy), then uncomment the line and launch it again, the music triggers as it should. I don't know how to reproduce the glitch as I didn't backup the old `options.rpyc`, but it probably will happen again to other developers.
The good news is, the fix is simple.
