### ISSUE TITLE
Weird console window spawning on restart-after-update

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2469]
Every time I use the update menu to update ren'py to a 7.4 version (including the prerelease and any of the Nightly builds so far), when the launcher restarts after the update, a cmd window whose name is the python path, pops along the launcher window.
Closing it closes the main window, and when I get in the console of the launcher (with Shift+O) and `print` something, it gets printed on the cmd window.
It looks like when launching a game with the "console output" preference checked, but this setting was not enabled any time the glitch triggered, and the black window doesn't show up when I start the launcher normally (when it's not after a restart).

It's not a serious issue at all whil this is the Nightly version, but it may cause some issues if released in the stable version.

**Comment by renpytom** [comment]
Fixed by renpy/renpy-build@a3c57e8bda77507dca4230d3ee6b0a590dabadb7 .
