### ISSUE TITLE
How can i add Visual Studio code as my text editor?

### ISSUE THREAD

**Issue by EmeraldWizardX** [renpy/renpy#2473]
I would like to use visual studio code as my text editor because it is faster and it has a ren'py extension.

**Comment by peachiestking** [comment]
Hiya! In the launcher preferences, you need to change your Text Editor from whatever it is now to System Preferences. Then, when trying to open a .rpy file, choose Visual Studio Code.
![image](https://user-images.githubusercontent.com/45401754/99903462-844c5180-2cbc-11eb-9424-89e3aed1da6f.png)
Like this, choosing Visual Studio Code.

Also, try and raise these on the Lemma Soft Forum or the Discord, not here. Thanks!
