### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by DinakiS** [renpy/renpy#2487]
There is a Pan class with a description
https://github.com/renpy/renpy/blob/master/renpy/display/motion.py#L218

But it can't be found via search
https://www.renpy.org/doc/html/search.html?q=Pan

Is it on purpose?

**Comment by Andykl** [comment]
If I remember correctly, it's depricated and exists for backward compability.

**Comment by DinakiS** [comment]
> If I remember correctly, it's depricated and exists for backward compability.

Oh, okay. Thanks for the reply/
