### ISSUE TITLE
Auto-update leaves game in broken state

### ISSUE THREAD

**Issue by GiovanH** [renpy/renpy#2488]
Using the built-in zsync updater to update the game isn't working. After the update, critical assets are missing, and the game gives a traceback screen.

Here are the results of my update `log.txt` file:

```
running ['C:\\Users\\[user]\\Projects\\Gamedev\\Renpy\\[game]-pc\\lib\\windows-i686\\zsync.exe', '-o', 'C:\\Users\\[user]\\Projects\\Gamedev\\Renpy\\[game]-pc\\update\\pc.update.new', '-k', 'C:\\Users\\[user]\\Projects\\Gamedev\\Renpy\\[game]-pc\\update\\pc.zsync', '-i', 'C:\\Users\\[user]\\Projects\\Gamedev\\Renpy\\[game]-pc\\update\\pc.update', 'http://[game]-autoupdater.sponsus.org/[game]-pc.zsync']
rename: Permission denied
Unable to back up old file C:\Users\[user]\Projects\Gamedev\Renpy\[game]-pc\update\pc.update.new - completed download left in C:\Users\[user]\Projects\Gamedev\Renpy\[game]-pc\update\pc.update.new.part
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
could not rename file \\?\C:\Users\[user]\Projects\Gamedev\Renpy\[game]-pc\game\archive.rpacould not rename file \\?\C:\Users\[user]\Projects\Gamedev\Renpy\[game]-pc\game\courbd.ttfcould not rename file \\?\C:\Users\[user]\Projects\Gamedev\Renpy\[game]-pc\renpy\common\DejaVuSans.ttfR \\?\C:\Users\[user]\Projects\Gamedev\Renpy\[game]-pc\renpy\common\DejaVuSans.ttfTraceback (most recent call last):
  File "renpy/common/00updater.rpy", line 108, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 74, in process_deferred_line
    os.unlink(fn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'\\\\?\\C:\\Users\\[user]\\Projects\\Gamedev\\Renpy\\[game]-pc\\renpy\\common\\DejaVuSans.ttf'
```

From what I can tell, the immediate problem is `could not rename file \\?\C:\Users\[user]\Projects\Gamedev\Renpy\[game]-pc\game\archive.rpa`: the main asset archive isn't getting updated due to a OS error of some sort, but ren'py doesn't detect this in any way. 

This leads to a state where the rpy files are updated, including behavior and versioning info, but the assets are *not*, which leaves the game in a broken, unfixable state.

**Comment by renpytom** [comment]
Which version is this? 

To me, it looks like there may be some sort of OS issue on your system. Unfortunately, by the time this is happening, the game is already in a broken state, so there isn't a way to recover. It may be that you have two copies of the game open at once.

**Comment by GiovanH** [comment]
Windows-8-6.2.9200
Ren'Py 7.3.5.606

There was only one instance of the game running. When the update process started, the game's state was correct, but yes, after this has happened, there's currently no way to recover besides redownloading the game.

It definitely seems like *some* kind of OS error, or a process (antivirus?) accessing the file, but I wasn't able to determine the exact conditions that caused this, only that it happened repeatedly. 

While ren'py obviously can't solve file access issues, some sort of fallback that detects errors from zsync and rolls back files if the update process fails would be enough to prevent the broken state, which is the biggest problem here.

**Comment by renpytom** [comment]
The zsync event is happening after the restart, which is long after rollback is possible. I'm not really sure what to do about it at this point, since it's not clear that this is a problem in Ren'Py. I haven't had reports about updating from Ren'Py users, who are the main users of the update system.

**Comment by uyjulian** [comment]
It may be possible that anti-virus or other resident process may be interfering with the file access.  

In that case, you can try disabling anti-virus.  
If that doesn't help, you can try the following: https://www.microsoft.com/en-us/software-download/windows10startfresh
