### ISSUE TITLE
In nightly, Ren'py does not launch on macOS.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2489]
Tested on macOS 11.0.1 Big Sur.

(Ren'py 7.3.5 and pre-released 7.4 work well.)

**Comment by renpytom** [comment]
Just to check, this is nightly-2020-12-06-98243a511 ?

**Comment by ikusorae** [comment]
Yes, I've tested it with a few recent builds nearby, but they don't work, so maybe there's a problem after a certain build.

**Comment by renpytom** [comment]
Thank you. I've updated my dtk, and can repeat the problem now.
