### ISSUE TITLE
Renpy .Sh file has wrong line encoding during deployment

### ISSUE THREAD

**Issue by Lokanath-hue** [renpy/renpy#2493]
Hi,

When I build my project for "PC" the ".sh" file is generated with the wrong line endings code.
When we try to run the same in Linux it we get an error saying " \r command not found"
Would it be possible to generate the sh file with proper encoding?

Thank you
Best Regards

**Comment by renpytom** [comment]
Is this in 7.4?

**Comment by Lokanath-hue** [comment]
> 
> 
> Is this in 7.4?

I'm sorry for not mentioning the version. The issue is seen with 7.3.5

**Comment by renpytom** [comment]
Can you explain how you had this happen? I've been playing 7.3.5 games for a year, and haven't seen this.

**Comment by Lokanath-hue** [comment]
> 
> 
> Can you explain how you had this happen? I've been playing 7.3.5 games for a year, and haven't seen this.

Standard workflow, Package generated on win 10 machine
1) Launch Renpy Launcher
2) Select "Build Distributions" (PC and Mac, i.e 1st and 3rd Options)
3) Start Build
4) Copy the PC zip to Ubuntu and extract
5) Start a terminal and run bash ./Game.sh 

Step 5 Gives the error

**Comment by Lokanath-hue** [comment]
Issue not seen in 7.4, It may have been fixed during development of 7.4 hence closing this issue
