### ISSUE TITLE
Unable to accept Android licenses when installing Android SDK

### ISSUE THREAD

**Issue by Sayo-Exo** [renpy/renpy#2495]
> Ren'Py 7.3.5.606

I'm compiling a short test program, to see if you have a working JDK on your system.

The JDK is present and working. Good!

I'm downloading the Android SDK. This might take a while.

I'm extracting the Android SDK.

I've finished unpacking the Android SDK.

I'm about to download and install the required Android packages. This might take a while.

I was unable to accept the Android licenses.
``
It pops up in notepad and Ren'py says this: 
![image](https://user-images.githubusercontent.com/75951527/102022522-6e7afb00-3d55-11eb-8fb5-1d6a4e7a5580.png)

**Comment by renpytom** [comment]
This is two years old, and hasn't been reported by other users, so this is local. (Hopefully, this has fixed itself.)

**Comment by theLMGN** [comment]
@renpytom It, sadly, has not fixed itself :'(

```
Ren'Py 7.4.11.2266

I'm compiling a short test program, to see if you have a working JDK on your system.







The JDK is present and working. Good!

The Android SDK has already been unpacked.

I'm about to download and install the required Android packages. This might take a while.
Error: Could not find or load main class to




I was unable to accept the Android licenses.

```
