### ISSUE TITLE
Using wait tag on Android fails

### ISSUE THREAD

**Issue by hackerncoder** [renpy/renpy#2501]
When trying to use text with the wait tag ({w}) it crashes. Apparently it expects unicode but is served "str".
If I remove the wait tag it suddenly works.

<details><summary>Log</summary><p>

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/1_diya.rpy", line 225, in script
>     Hayden "Uh, {w=0.35} I just meant that she's less violent."
> TypeError: Argument 's' has incorrect type (expected unicode, got str)
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/1_diya.rpy", line 225, in script
>     Hayden "Uh, {w=0.35} I just meant that she's less violent."
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/ast.py", line 708, in execute
>     renpy.exports.say(who, what, *args, **kwargs)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/exports.py", line 1345, in say
>     who(what, *args, **kwargs)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/character.py", line 1142, in __call__
>     self.do_display(who, what, cb_args=self.cb_args, **display_args)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/character.py", line 842, in do_display
>     **display_args)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/character.py", line 591, in display_say
>     rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/ui.py", line 297, in interact
>     rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/core.py", line 2702, in interact
>     repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/core.py", line 3194, in interact_core
>     self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/core.py", line 2094, in draw_screen
>     renpy.config.screen_height,
>   File "renpy/display/render.pyx", line 490, in renpy.display.render.render_screen (gen/renpy.display.render.c:6805)
>     rv = render(root, width, height, st, st)
>   File "renpy/display/render.pyx", line 259, in renpy.display.render.render (gen/renpy.display.render.c:3520)
>     rv = d.render(widtho, heighto, st, at)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/layout.py", line 722, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 166, in renpy.display.render.render (gen/renpy.display.render.c:4075)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 259, in renpy.display.render.render (gen/renpy.display.render.c:3520)
>     rv = d.render(widtho, heighto, st, at)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/layout.py", line 722, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 166, in renpy.display.render.render (gen/renpy.display.render.c:4075)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 259, in renpy.display.render.render (gen/renpy.display.render.c:3520)
>     rv = d.render(widtho, heighto, st, at)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/layout.py", line 722, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 166, in renpy.display.render.render (gen/renpy.display.render.c:4075)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 259, in renpy.display.render.render (gen/renpy.display.render.c:3520)
>     rv = d.render(widtho, heighto, st, at)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/screen.py", line 675, in render
>     child = renpy.display.render.render(self.child, w, h, st, at)
>   File "renpy/display/render.pyx", line 166, in renpy.display.render.render (gen/renpy.display.render.c:4075)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 259, in renpy.display.render.render (gen/renpy.display.render.c:3520)
>     rv = d.render(widtho, heighto, st, at)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/layout.py", line 722, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 166, in renpy.display.render.render (gen/renpy.display.render.c:4075)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 259, in renpy.display.render.render (gen/renpy.display.render.c:3520)
>     rv = d.render(widtho, heighto, st, at)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/layout.py", line 1127, in render
>     st, at)
>   File "renpy/display/render.pyx", line 166, in renpy.display.render.render (gen/renpy.display.render.c:4075)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 259, in renpy.display.render.render (gen/renpy.display.render.c:3520)
>     rv = d.render(widtho, heighto, st, at)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/display/layout.py", line 722, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 166, in renpy.display.render.render (gen/renpy.display.render.c:4075)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 259, in renpy.display.render.render (gen/renpy.display.render.c:3520)
>     rv = d.render(widtho, heighto, st, at)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/text/text.py", line 1996, in render
>     virtual_layout = Layout(self, width, height, renders, drawable_res=False, size_only=True)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/text/text.py", line 612, in __init__
>     p, rtl = self.rtl_paragraph(p)
>   File "/home/hackerncoder/renpy-7.3.5-sdk/renpy/text/text.py", line 1205, in rtl_paragraph
>     s, direction = log2vis(s, direction)
> TypeError: Argument 's' has incorrect type (expected unicode, got str)
> 
> Linux-5.9.14-arch1-1-x86_64-with-glibc2.2.5
> Ren'Py 7.3.5.606
> Butterfly Soup 2.19
> Thu Dec 17 21:44:40 2020

</p></details>

(Same on a real Android device)

**Comment by renpytom** [comment]
Can you try using 7.4 with this? My guess is that this is a problem with the backport of this from 7.4 to 7.3.5.

**Comment by hackerncoder** [comment]
It seems to working in emulation on 7.4.

**Comment by hackerncoder** [comment]
Yep. Works on my phone too. Thanks.
