### ISSUE TITLE
[7.4.0.1079(16 of December 2020)] Steam Lib Bug?

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#2502]
I'm testing the 7.4 update and when I run the renpy launcher, runs the steam library. I think this is fine, but is it normal that you can open the steam menu of a game that is published in steam without running the game code? If I run the game I can also open the steam menu.

![image](https://user-images.githubusercontent.com/36079551/102565768-e2eacc80-40bc-11eb-875a-2bb113f98e43.png)

**Comment by renpytom** [comment]
This should be fixed by 3fc95821b, which will be in the next nightly. 

Thank you for reporting it. If you can let me know if this fixes the problem, I'd appreciate it.
