### ISSUE TITLE
Upload releases to Github

### ISSUE THREAD

**Issue by darealshinji** [renpy/renpy#2503]
Can you upload the release packages found at https://renpy.org/release to Github's release section? The download speed I get from renpy.org is super slow and there don't seem to be any mirrors available.

**Comment by renpytom** [comment]
I've been uploading to https://renpytom.itch.io/renpy-mirror .

**Comment by darealshinji** [comment]
Yes, I've seen that and thanks for that! But I also want to be able to download them automatically with shell scripts to "patch" Ren'Py games to make them playable natively on Mac and Linux.
Another mirror I could find is on archive.org: https://archive.org/details/renpy-7.3.5-sdk
