### ISSUE TITLE
ZeroDivisionError when restoring mobile web window

### ISSUE THREAD

**Issue by Beuc** [renpy/renpy#2506]
Hi,

I got a report that RenPyWeb 7.4.x has an issue when run within itch.io on mobile.
This website handles the situation where you switch from the mobile browser to a different application, and go back to the browser: the game is hidden and a "Restore game" button is displayed. When clicking on it the game crashes.
I reproduced the issue with the latest prerelease:
https://beuc.itch.io/test?secret=k0gMxY5FvibbjtT9ErCaafZnbQ
[log.txt](https://github.com/renpy/renpy/files/5717959/log.txt)
```
Screen sizes: virtual=(1280, 720) physical=(360, 0) drawable=(1080, 0)
...
  File "gldraw.pyx", line 176, in renpy.gl.gldraw.GLDraw.on_resize
ZeroDivisionError: float division by zero
...
  File "gldraw.pyx", line 724, in renpy.gl.gldraw.GLDraw.draw_screen
ZeroDivisionError: float division by zero
```

Interestingly RenPyWeb 7.3.x is not affected.

This sounds like a tricky corner case (height==0) so I'd rather check with you first on how to fix this.

**Comment by renpytom** [comment]
Here's a shot at fixing it. I'll wait for the nightly, and then try uploading this to itch to see if the problem is solved.

**Comment by Beuc** [comment]
> Here's a shot at fixing it. I'll wait for the nightly, and then try uploading this to itch to see if the problem is solved.

I also tested today, Ren'Py now appears to handle the situation.
(I got a weird browser cache issue though, I thought itch.io would handle that, but I'd recommend clearing the cache before testing nonetheless)
