### ISSUE TITLE
Setting config.mouse on the fly crashes the engine on Prerelease/Nightly

### ISSUE THREAD

**Issue by outkats** [renpy/renpy#2509]
Not sure if this is a bug or if our current way of doing this is no longer supported.

In the Prerelease (7.4.0.1079) and Nightly (7.4.0.1091), we experience a crash when dynamically setting config.mouse to a dictionary containing custom crosshairs used in a minigame if the game is initialized using the default mouse cursor. This code does not crash in 7.3.X.  Here's the log of the crash:

```
While running game code:
  File "game/engine/arcade.rpy", line 214, in script
    show screen fpsmenu with dissolve
  File "game/engine/arcade.rpy", line 214, in script
    show screen fpsmenu with dissolve
  File "renpy/common/000statements.rpy", line 536, in execute_show_screen
    renpy.with_statement(eval(transition_expr))
TypeError: argument of type 'NoneType' is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 617, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "game/engine/arcade.rpy", line 214, in script
    show screen fpsmenu with dissolve
  File "game/engine/arcade.rpy", line 214, in script
    show screen fpsmenu with dissolve
  File "renpy/ast.py", line 1960, in execute
    self.call("execute")
  File "renpy/ast.py", line 1948, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 536, in execute_show_screen
    renpy.with_statement(eval(transition_expr))
  File "renpy/exports.py", line 1640, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2517, in do_with
    clear=clear)
  File "renpy/display/core.py", line 2977, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "renpy/display/core.py", line 3662, in interact_core
    self.update_mouse()
  File "renpy/display/core.py", line 2753, in update_mouse
    if mouse_kind in self.cursor_cache:
TypeError: argument of type 'NoneType' is not iterable
```

Enclosed below is the code/variables we're using which exhibits this crash

```python
default option_crosshairs = [
        "assets/images/crosshair1.png",
        "assets/images/crosshair2.png",
        "assets/images/crosshair3.png",
        "assets/images/crosshair4.png",
        "assets/images/crosshair5.png",
    ]
default option_crosshair = 1
```

Our game cycles between optional crosshairs using the menu code below:
```python
    menu:
        "Crosshair: #[option_crosshair]":
            play sound "assets/sfx/menu_select.mp3"
            if option_crosshair >= len(option_crosshairs):
                $ option_crosshair = 1
            else:
                $ option_crosshair += 1
            $ config.mouse = {'default': [(option_crosshairs[option_crosshair - 1], 25, 25)]}
```

When we comment out the cursor altering logic, the crash does not occur. It's worth noting that simply assigning config.mouse in the renpy console to a valid mouse cursor dictionary (as seen in this cookbook link: https://www.renpy.org/wiki/renpy/doc/cookbook/Adding_a_Custom_Mouse_Pointer) like below also produces the same crash:

```config.mouse={'default': [("assets/images/reload.png", 25, 25)]}```

Digging a bit, the crash appears to be a result of how the cursor_cache dictionary is initialized when config.mouse is not set at init time, but later set on the fly. 

In core.py, the cursor_cache is defaulted to None which is not iterable:
```
        # The cursor cache.
        self.cursor_cache = None
```

If config.mouse is set at init time in options.rpy, this does not produce a crash because the cursor_cache is iterable when it is an empty dict:
```
        if renpy.config.mouse:

            self.cursor_cache = { }
```

In our case, since we were using the default cursor (config.mouse=None) at init time and only introducing custom mouse cursors during the mini game, we exhibit the crash here. However, even if I initialize config.mouse in options.rpy at init time to a custom mouse cursor, the engine no longer crashes, but cycling/changing the mouse cursor on the fly no longer works as it used to and whichever cursor is indicated in config.mouse['default'] is simply ever present. Even explicitly changing config.mouse to None on the fly in the console does not bring back the old system cursor, so I suspect that perhaps that our way of performing dynamic cursor changes may be outmoded.

Thanks.

**Comment by Andykl** [comment]
Config variables are intended to be immutable, but this trick is relying on a side effect of the config.mouse. Look at https://github.com/renpy/renpy/commit/090ca5f8dc6b3b341100ba3a462b356c2cc06cf0.

**Comment by outkats** [comment]
I can respect that config variables are not meant to be changed, but surely you can understand that in older versions of Ren'Py, it was possible to dynamically change the cursor and have games use that to affect presentation to the players. I'd argue there might be legitimate reasons for a game to want an engine to support such dynamic behavior. 

While fixing whatever issue allowed this to work might be something that was long overdue and 7.4 is the release that finally does this, I think maybe it also does suggest that there may now be a functionality gap in Ren'Py for dynamically changing the mouse cursor. 

I guess whether or not that is something that can/should be potentially addressed in a future version is up to the team, but please feel free to close this issue as it sounds like it's not a bug and working as intended. 

We'll try to figure out something for our game on our end, whether that means patching the Ren'Py code base locally to support dynamic cursor change on 7.4 or sticking with 7.3 indefinitely.

Thanks

**Comment by renpytom** [comment]
There actually was a way to do this, but it wasn't documented. What you'll want to do (in the next nightly or prerelease) is to set ``default_mouse``, which gives a key that is looked up in config.mouse. That  should, I think, give you what you need to set custom mouse cursors.

**Comment by outkats** [comment]
Interesting! So assuming something like this:

```python
# options.rpy
init -1 python:
  config.mouse = {
      'default': [('assets/images/cursor.png', 48, 48)], # guessing we need this
      'crosshair1': [('assets/images/crosshair1.png', 25, 25)],
      'crosshair2': [('assets/images/crosshair2.png', 25, 25)],
      'crosshair3': [('assets/images/crosshair3.png', 25, 25)],
      'crosshair4': [('assets/images/crosshair4.png', 25, 25)],
      'crosshair5': [('assets/images/crosshair5.png', 25, 25)],
      'reload': [('assets/images/reload.png', 25, 25)]
  }

# dynamically
$ default_mouse = renpy.random.choice(['crosshair1', 'crosshair2', 'crosshair3', 'crosshair4', 'crosshair5'])

# reset the default cursor
$ default_mouse = 'default'
```

Yeah? Any easy way to provide the config.mouse dictionary and still have the 'default' key behave like a system cursor and not have to be a customized image like below:

![cursor](https://user-images.githubusercontent.com/56181352/102698743-a11d6b80-420d-11eb-9802-e89b1fb11e1a.png)

If not, not a huge deal. We don't particularly care if our MacOS/Linux users get a windows cursor in game.

 We can give this a go in the next nightly.

**Comment by renpytom** [comment]
Just looking at how I wrote it, it looks like if you don't have the default key, Ren'Py will use the system cursor.

**Comment by outkats** [comment]
Oh, that's actually perfect. Sounds like our mini game should be no different for the player between 7.3 and 7.4 and I'm glad we won't have to disable the custom cursors or hack up the engine code to move forward to the next version.

Thanks for the top notch support my dudes.

**Comment by renpytom** [comment]
Thanks, closing this now.
