### ISSUE TITLE
[Nightly] When first launching the game on Android, main_menu_music does not play.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2522]
When first launching the game on Android, main_menu_music does not play.
Unless return, this state persists.

Tested on nightly-2020-12-23-d43728801.

**Comment by Gouvernathor** [comment]
May be related to #2468

**Comment by ikusorae** [comment]
In my case, it also happens in clean project, and it only happens in Android.
But it could be suspected. Thank you.

**Comment by Beuc** [comment]
This appears to have fixed a similar issue with RenPyWeb.
