### ISSUE TITLE
[Feature Request] Cryptomatte support possibly with crptomatte meta data support

### ISSUE THREAD

**Issue by yourherobby** [renpy/renpy#2526]
Having a native cryptomatte support would open up many possibilities. Cryptomattes are a way to mask out objects and aid in compositing. Think of it as an alpha mask but every object in the image has assigned a unique mask color and this is done with only single file without need for several plain alpha masks.

Additionally blender supports storing the mask information in the meta data of the file, which renpy can extract and then from renpy i can simply specify by name which object i want to mask out. native support of this workflow would ensue that anyone can use it and open up many possibilities and overal improve usefulness by fair amount. i think it would be a great addition!

here are some references
https://developer.blender.org/D9553 (if you want to look into meta data aspect of cryptomattes i mentioned)
https://github.com/Psyop/Cryptomatte
https://www.sidefx.com/docs/houdini/render/cryptomatte.html
https://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2020/ENU/Flame-EffectsandToolsReference/files/GUID-0402116E-B47C-4E32-9010-DB8C334853E0-htm.html

**Comment by renpytom** [comment]
I think this can be done with shaders, at this point. Actually supporting Cryptomatte is probably outside the scope of Ren'Py, but it would make a decent cookbook entry.
