### ISSUE TITLE
7.4 Bug: libpng prints its warnings into stdout

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2534]
libpng may print in stdout things such as `libpng warning: iCCP: CRC error` or `libpng warning: iCCP: known incorrect sRGB profile`.
Moreover, the output occurs without checking that someone else is writing to the stream, so via predicting pictures, these outputs can interrupt debug prints.

The ideal solution is to move these warnings to the lint.

**Comment by renpytom** [comment]
Fixed in renpy/renpy-build@1df77ae .
