### ISSUE TITLE
Incomplete rollback when Python code runs can cause invariants to be violated

### ISSUE THREAD

**Issue by jackmcbarn** [renpy/renpy#2539]
When a player rolls back, Python code will sometimes run with some class variables rolled back but not others. Consider the following `script.rpy`:

```renpy
init python:
    class Foo:
        def __init__(self):
            self.myfield = []
            self.mylen = 0
        def append_and_remove_dups(self, thing):
            self.myfield.append(thing)
            self.myfield = list(set(self.myfield))
            self.mylen = len(self.myfield)

label start:

    $ foo = Foo()
    $ foo.append_and_remove_dups("abc")
    "Line one"
    if len(foo.myfield) != foo.mylen:
        $ raise Exception("Invariant violated! len(foo.myfield) is %d but foo.mylen is %d" % (len(foo.myfield), foo.mylen))
    "Line two"
    $ foo.append_and_remove_dups("def")
    "Line three"

    return
```

If, while on "Line three", you try to roll back to "Line two", you'll get `Exception: Invariant violated! len(foo.myfield) is 2 but foo.mylen is 1`. Oddly, I can reproduce this most of the time but not every time (to see both ways, try rolling forward then back again, and starting a new game without restarting Ren'Py). This occurs with both Ren'Py 7.3.5.606 and 7.4.0.1079.

**Comment by Andykl** [comment]
I'm pretty sure this doesn't happen when doing `self.myfield[;] = list(set(self.myfield))`.
And also this doesn't happen without such object wrapper.

**Comment by renpytom** [comment]
The issue is that since the original myfield list isn't reachable when rollback starts, it's not rolled back. I think I know what I need to do to fix this.
