### ISSUE TITLE
[7.4 Bug] Writing to open files raises exception

### ISSUE THREAD

**Issue by multimokia** [renpy/renpy#2543]
Reporting a bug on the 7.4 prerelease as we open and create our own log/json files in our project. Whenever we attempt to write to these files, renpy crashes as for some reason, the strings passed in aren't actually unicode.

See below a copy of the traceback:
![image](https://user-images.githubusercontent.com/22531674/103252393-af286600-494a-11eb-9343-f6a6c34dbff4.png)

**Comment by renpytom** [comment]
I don't think this is a bug in Ren'Py. You need to open the file in binary mode (with "wb" as the mode, not "w") if you plan to write binary strings to it.

**Comment by multimokia** [comment]
The code we have here is writing text instead of a binary string, and the same approach was used in other versions (6.99.14, 7.1.1, 7.3.5) in which, all do indeed work as intended, and strings are treated as `unicode`. It seems that only with the transition to 7.4.0, does this happen.

**Comment by renpytom** [comment]
How are you opening the file you're writing to?

**Comment by multimokia** [comment]
the exact code in question for this trace is:
```python
        with open(renpy.config.savedir + '/db.mcal', 'w') as fp:
            json.dump(calendar_database, fp, cls=encoder)
```
for another one we got too:
![image](https://user-images.githubusercontent.com/22531674/103261599-10aefb80-4970-11eb-8819-571cc71a41ee.png)

That code is:
```python
        with open(_ev_stats_fp, "w") as _ev_stats_file:

            _ev_stats_file.write(config.version + "\n\n")
            _ev_stats_file.write(mas_sessionDataDump())

            # gather data
            for ev in mas_all_ev_db.values():
                _seen = _stat(statcounters, ev)

                # print event stats
                _ev_stats_file.write(StatCounter._ev_statline.format(
                    ev.eventlabel,
                    ev.pool,
                    ev.random,
                    ev.unlocked,
                    _seen,
                    ev.shown_count
                ))

            # print final stats (including most seen)
            for _sc in statcounters:
                _ev_stats_file.write(str(_sc))
```

**Comment by multimokia** [comment]
Thank you!
