### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by teward** [renpy/renpy#2545]
When renpy is finished building a given game/executable/etc. do you need to ship the .rpy files if the .rpyc files exist?  In the Python world, the .pyc can be enough at times to ship without the actual source code files itself and operating simply with the compiled bytecode, especially if you ship the Python libs with it.

Is this by design?  Or is there an option during build/compile time to exclude the .rpy files and only keep the .rpyc files?  Or is this up to developer cleaning before building to do all that?

**Comment by renpytom** [comment]
You don't need to ship the .rpys if the .rpyc files exist. You can write:

```
init python:
     build.classify("**.rpy:", None) 
```

To exclude them.
