### ISSUE TITLE
Consider making an option to Encrypt assets

### ISSUE THREAD

**Issue by teward** [renpy/renpy#2546]
As it stands in RenPY, there is no mechanism to ship an encrypted .rpa file so that it is not easily decrypted by end users after publication of an application.

Consider making that a feature, it will make it more easy to secure assets and restrict modification of games after being produced.

**Comment by renpytom** [comment]
Unfortunately, this is impossible. All the information required to run a game has to be present in the game for the game to be run by the end user. So an unpacker tool would have everything it needs to unpack the game, while the presence of the obfuscation would just slow things down. 

It's a hard problem, and not one I know how to solve.

**Comment by uyjulian** [comment]
Even if the archive format itself is complicated, as long as the game process is running or you can see the screen, there will be a way to get assets out of the process. (See KrkrExtract or HDCP Strippers for such examples)

You can use this method to prevent `.rpa` opening programs from opening the archive files. https://lemmasoft.renai.us/forums/viewtopic.php?f=51&t=59725

However, this method will not help if an external program injects an extractor in your game. For that, consider kernel-level anti-cheat program.
