### ISSUE TITLE
Ren'Py windows increase in size with each subsequent launch

### ISSUE THREAD

**Issue by Belgerum** [renpy/renpy#2547]
So, I recently tried out Ren'Py 7.4.0, and one of the issues I immediately noticed was that my game in windowed mode would grow larger with every subsequent launch from the launcher, and i eventually noticed that even the launcher itself has the same issue. I'll upload a video of what I'm seeing, and it gets pretty annoying when a basic window like the Ren'Py launcher suddenly fills the screen, and I have to manually resize the thing smaller after every few times I open it.

I do think I've made a connection about how the problem is occuring, and I tried playing around with my monitor's display settings. It seems that the window scaling factor is the same factor by which the Ren'Py window increases in size with every launch. (When I have the scaling factor at 100%, the windows don't get larger. At 200%, it doubles in size every time it launches. In the video, the window gets 125% larger every launch to match my current setting.)

https://user-images.githubusercontent.com/6981764/103434003-c1afd300-4bc8-11eb-9776-c7a406963156.mp4

**Comment by renpytom** [comment]
Which version of windows are you on?

**Comment by Belgerum** [comment]
Windows 10 Pro

**Comment by renpytom** [comment]
Thanks. It looks like I can repeat it, so I'll look to get a  7.4.1 out this weekend.
