### ISSUE TITLE
Live2D motions overlap and cause a tuple error

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2552]
Two Live2D models that worked with previous nightly builds no longer work with the final build of 7.4.

The first model shows both motions, when it should show them exclusively.

The second model generates an error when it's displayed after the first model:
`TypeError: can only concatenate tuple (not "list") to tuple`

Sample project is attached.
[Live2DSample.zip](https://github.com/renpy/renpy/files/5759334/Live2DSample.zip)

**Comment by eristheapple** [comment]
I seem to have opened the same issue - I found that it could be corrected by changing line 657 in `/renpy-7.4.0-sdk/renpy/gl2/live2d.py` from `("_sustain" ,)` to `["_sustain"]` - you may wish to try that and see if it does the trick for you.

**Comment by Andykl** [comment]
Yes, fixed by 3cb6d38

**Comment by rdurfee** [comment]
The second issue with the tuple type exception is fixed, but the motion issue still exists.

**Comment by rdurfee** [comment]
Can this be re-opened since it's not actually fixed?

**Comment by renpytom** [comment]
This is actually us respecting Live2D a bit more closely. Live2D makes the default fadeout time for expressions and motions 1.0 seconds, unless you specify a different fade in or fade out time. In your transformation motion, you had it set up that when the motion was faded out, both the man and wolf were displayed, which lead to what you saw. 

I've made two changes to Ren'Py. The first is that Live2D now takes a new `default_fade` parameter, which you can set to 0.0 to disable the fading, using something like:

```renpy
image gabriel transformation = Live2D("resources/transformation/human_to_wolf.model3.json", base=0.9, loop=False, default_fade=0.0)
image gabriel werewolf = Live2D("resources/werewolf", base=0.9, loop=True, default_fade=1.0)
```

The second is that Ren'Py now holds the last frame of an animation when it stops, so it won't pop back to the start, if looping is not done. 

Together, I think these two will address your problem.

**Comment by Andykl** [comment]
I think the second change is also about #2293

**Comment by renpytom** [comment]
I think this is fixed.
