### ISSUE TITLE
Lag/slowed problem with the 7.4.0

### ISSUE THREAD

**Issue by NoiGS2015** [renpy/renpy#2559]
Hello there. I have a little inconvenient with the new version.

When the test launcher start, some functions present some lag :

- Beggining with the splashscreen, just a simple text with dissolve, and 
```
label splashscreen:
    scene black
    with Pause(1)

    show text "Una Cuerda de Subnormales Presenta..." with dissolve
    with Pause(2)

    hide text with dissolve
    with Pause(1)

    return
```

- Then when I start the game, The game asks for choosing an name, when you type the words, it takes too long to show what you're typing
`$ y = Character(_(renpy.input ("Decide tu nombre antes de comenzar.")), color="#804000", image = "prota")`

- It also happens when you try to close the game, the "Are you sure?" screen don't show inmediatly, and also when you pause the game (right click).

- The most frequent one is when the `**menu**` options appear, as the previous point, it takes a lot to show the hover effect (That I have as the default of Renpy), you can select anything, but it will show late the path you choose. This happens with all of the menu.

The other functions works perfectly (Like the skip button). I though it could be my pc, but I downloaded the 7.3.5 version again, it worked perfectly, as always did.
I work with Windows 10 Pro.

I hope this get better, because I'm very excited with the new functions of this new version. Meanwhile, I'll use the 7.3.5 version. Also, I'll let you a little video of the problems.

https://youtu.be/HGKshCy0z2g

Salutes.

**Comment by renpytom** [comment]
Can you send a log.txt ?

**Comment by NoiGS2015** [comment]
> Can you send a log.txt ?

Sure thing
[log.txt](https://github.com/renpy/renpy/files/5761023/log.txt)  -  This is from my game folder
[log.txt](https://github.com/renpy/renpy/files/5761024/log.txt)  - And this from the Renpy folder (I wasn't sure at all of which one so I send both XD)

**Comment by renpytom** [comment]
Hm... can you try: 

```
define config.gl2 = True
```

In your game?

**Comment by renpytom** [comment]
Can you send me your game? Either here, or email it to pytom@bishoujo.us, and let me know you did? I'd like to look into this, to see if it's likely to be hardware related.

**Comment by NoiGS2015** [comment]
> Hm... can you try:
> 
> ```
> define config.gl2 = True
> ```
> 
> In your game?

I putted it in the options.rpy but it do the same, I closed all about Renpy, reopened it, but still the same. Here's the  new log.

[log.txt](https://github.com/renpy/renpy/files/5761054/log.txt)

**Comment by NoiGS2015** [comment]
> Can you send me your game? Either here, or email it to [pytom@bishoujo.us](mailto:pytom@bishoujo.us), and let me know you did? I'd like to look into this, to see if it's likely to be hardware related.

ok, I'll do it

**Comment by NoiGS2015** [comment]
> Can you send me your game? Either here, or email it to [pytom@bishoujo.us](mailto:pytom@bishoujo.us), and let me know you did? I'd like to look into this, to see if it's likely to be hardware related.

Done, thank you so much man.

**Comment by renpytom** [comment]
I'm not seeing anything slow about this game, at least in my development version. 

Would you mind adding:

```
define config.profile = True
```

to your game, running it to cause the problem, and then sending me the log.txt? It should include profiling information that breaks down what's taking the time.

Thank you.

**Comment by NoiGS2015** [comment]
Sure thing, I did and still the same.

By the way, I noticed that in the game folder there is two launchers

![image](https://user-images.githubusercontent.com/74834511/104067615-d9dfad80-51d9-11eb-9672-35f8822aa5d4.png)

And also noticed that the one that I was running was the first one (which log is in the zip below like... log.txt)
So, I tried with the other one (that I suppose is a 32bit version), and the game runned almost perfectly, the slow thing is almost imperceptible, but still there. The log of that one is called "log (renpy-32).txt".

[Logs.zip](https://github.com/renpy/renpy/files/5789495/Logs.zip)

And Just for the record, I'll leave you a capture of my system properties, If you need anything else, let me know, thank you.

![image](https://user-images.githubusercontent.com/74834511/104069457-de0cca80-51db-11eb-8a97-38e1a0be573c.png)

**Comment by NoiGS2015** [comment]
Hello Tom. Just wanna say that with the new 4.1 version, this thingy doesn't happen anymore. Thank You a lot man, you're my hero.

**Comment by renpytom** [comment]
Thanks! I'll close this out.
