### ISSUE TITLE
Expose more transforms that renpy.geometry can already do

### ISSUE THREAD

**Issue by jackmcbarn** [renpy/renpy#2561]
The stock `renpy.geometry` shader supports arbitrary linear transformations of homogeneous coordinates through its `u_transform` matrix. We only expose a subset of what it can do, though. These 4 operations are possible (each independently in the `x` and `y` directions):
* Translate
* Zoom
* Skew
* Keystone

We fully expose translations and zooms. We only expose a subset of skews (in particular, all rotations are equivalent to a combination of zooms and skews, but not all combinations of zooms and skews correspond to a rotation), and we don't expose keystones at all. Can we add these things to ATL, so that (1) a custom shader isn't required to use them, and (2) inverting these transforms for mouse events would be automatic? I'm thinking we should either let users specify the full `u_transform` matrix directly somehow, add individual properties (`xskew, yskew, xkeystone, ykeystone`), or both.

**Comment by renpytom** [comment]
The 3D Stage - new in 7.4.5 - supports this, and lets the user specify a matrix. So I'll close this one out.
