### ISSUE TITLE
Bug: Style 'file_picker_entry' does not exist. with old RPA-1 application 

### ISSUE THREAD

**Issue by madeddy** [renpy/renpy#2569]
Sys/Vers Info: Kubuntu 18.04.5 / RenPy 7.4.0 release v.
**Important:** The fix from #2567 is applied to this.

```
Exception: Style 'file_picker_entry' does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/olli/Downloads/lager/GameEngine/renpy-7.4.0-sdk/renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "/home/olli/Downloads/lager/GameEngine/renpy-7.4.0-sdk/renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/wingse.rpy", line 32, in script
    $ style.file_picker_entry.idle_background = Solid((0, 0, 0, 255)) #black
  File "game/wingse.rpy", line 32, in script
    $ style.file_picker_entry.idle_background = Solid((0, 0, 0, 255)) #black
  File "/home/olli/Downloads/lager/GameEngine/renpy-7.4.0-sdk/renpy/ast.py", line 913, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/olli/Downloads/lager/GameEngine/renpy-7.4.0-sdk/renpy/python.py", line 2111, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/wingse.rpy", line 32, in <module>
    $ style.file_picker_entry.idle_background = Solid((0, 0, 0, 255)) #black
  File "style.pyx", line 216, in renpy.style.StyleManager.__getattr__
  File "style.pyx", line 98, in renpy.style.get_style
Exception: Style 'file_picker_entry' does not exist.
```

Used game for test is "Wings" from [games.renpy.org](https://games.renpy.org)

Edit: Perhaps the support for such "pre rpa3 age" apps should be discontinued. There are a lot of RenPy version available for this.

**Comment by renpytom** [comment]
Please don't flag this as 7.4.0, unless this wasn't present in 7.3.5.

**Comment by renpytom** [comment]
This has been fixed in 7.5/8.0, with a0ba72b82d24476b3a96069e043026e20f1e911b  and 16ba68a927604f9c4465c4ccfde2407fadb48c57 . Wings now runs again.

**Comment by madeddy** [comment]
Sorry. I should have mentioned.
I copy just the ../game directory in the SDK and run it there from the launcher. This worked so far with every other game i did this because i experienced some problem with.

**Comment by renpytom** [comment]
Ah, that won't work, since you're using the updated copy of Ren'Py. 

What will work is you drop the game into either the SDK directory or the projects directory, and launch it from the launcher. That will let the new copy of Ren'Py read the old copy, and it should work. (The problem with your method is not all old games use rpa/rpi, and even if they do, it'd be hard to decide the precise script version to use.)

**Comment by madeddy** [comment]
> ...not all old games use rpa/rpi, and even if they do, it'd be hard to decide the precise script version to use.
Argh! Dammit. The usual. It's never as easy as we hope. :) Anyway, thanks for all.
