### ISSUE TITLE
Ren'Py "Not Responding"/Slow to Load (both Launcher and games) in 7.4

### ISSUE THREAD

**Issue by mjmcguire** [renpy/renpy#2571]
Installed the 7.3.5 version of Ren'Py and then updated in-app to 7.4 release. After updating, the launcher takes minutes to load. My machine is still new-ish and there's no reason any part of it should be bottlenecking with the loading. I haven't had any issues with anything else that loads from the drive that Ren'Py is installed on/loads from. None of the other members of the team I'm working with have had any issues with loading times. I tried searching the LSF for similar reports, but the only thing that came back was an older post that suggested the problem was with a failing drive (which I'm really hoping is not the case here). I'm running Windows 10 64-bit on my system, and it's happening both during the initial Ren'Py Launcher startup as well as upon attempting to load the quickstart guide tutorial game. Per Tom's advice, I tried disconnecting my control prior to launch but it did not affect the loading issue. I also tried swapping to force different shaders, but these also did not affect the issue.

[log.txt](https://github.com/renpy/renpy/files/5767810/log.txt)

**Comment by uyjulian** [comment]
Your anti-virus or other resident software may be hooking system calls, causing slowness when loading a lot of files.

**Comment by mjmcguire** [comment]
Excluding the Ren'Py folder from Microsoft Defender Antivirus has had no noticeable effect on the time it's taking for the launcher to load. I'm hesitant to believe large amounts of files are the underlying issue, since the the launcher began displaying this behavior after updating a clean install of 7.3.5 to 7.4 (i.e., I've never worked with Ren'Py before and had no additional files beyond those that are installed by default).

**Comment by uyjulian** [comment]
Excluding the folder most likely will not disable the hooks since the hooked file open function still needs to check if the folder is excluded.

**Comment by renpytom** [comment]
Looking at the log.txt, this isn't the problem. It's happening at GUI start.

**Comment by Christian112358** [comment]
Hi,

I downloaded Renpy 7.4 today for the first time. Unfortunately it is very slow. 
When I click on "The Question" or "Tutorial" in the initial screen it takes up to 20 seconds to move the focus.
I turned off the MS Defender. My PC is an i7, 16Gig RAM, SSD.

Can you help ?
Thanks,
Christian

[log.txt](https://github.com/renpy/renpy/files/5851564/log.txt)

**Comment by renpytom** [comment]
Can you try 7.4.1, please? I believe it should be faster.

**Comment by Christian112358** [comment]
I download 7.4.1 - but it has the same problem - but I realized when I do the following:

- start renpy
- click on "The Question" 
- change to another window (explorer)
- and change immediately back to renpy 
- then the menu focus has changed

When I don't change to another windows the focus change takes 20 seconds. 
It looks to me like the screen refresh is not working properly

CU
Christian

**Comment by Christian112358** [comment]
Started "The Question" and the behaviour in the game is the same. When I click - nothing happens. When I change to another window and back then "the click works".

**Comment by Christian112358** [comment]
Now I tried 6.99.14.3 and its also the same behaviour. Can it be that some underlying library has a problem ?

**Comment by renpytom** [comment]
I'm going to have to say yess, especially since these versions are so very different from each other.

**Comment by Christian112358** [comment]
Do you have a suggestion how to fix this ? Can I help to identify the library ?

**Comment by uyjulian** [comment]
Try removing/disabling resident programs like anti-virus, overlays, download accelerators, etc.

If you are not sure which ones they are, you can try a clean installation of Windows 10: https://www.microsoft.com/en-us/software-download/windows10startfresh

**Comment by Christian112358** [comment]
I installed 7.4.1 on another PC - and there it works fine. 
On the "problem PC" I disabled MS Defender, I don't use overlays and I don't have a download accelerator.

So I am good with this solution - but If you ever want to investigate why renpy works on certain pc and others not - I can help you.

Thanks,
Christian
