### ISSUE TITLE
After install RAPT,I can't open renpy.

### ISSUE THREAD

**Issue by shelling4d** [renpy/renpy#2577]
When I download RAPT, I can't open reply.it shows following information.

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "renpy/common/00start.rpy", line 280, in script
>     python:
> ScriptError: could not find label 'start'.
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "renpy/bootstrap.py", line 326, in bootstrap
>     renpy.main.main()
>   File "renpy/main.py", line 617, in main
>     run(restart)
>   File "renpy/main.py", line 148, in run
>     renpy.execution.run_context(True)
>   File "renpy/execution.py", line 922, in run_context
>     context.run()
>   File "renpy/common/00start.rpy", line 280, in script
>     python:
>   File "renpy/script.py", line 900, in lookup
>     raise ScriptError("could not find label '%s'." % str(original))
> ScriptError: could not find label 'start'.

**Comment by renpytom** [comment]
Can you please post the version information ?

**Comment by shelling4d** [comment]
> Can you please post the version information ?

7.3.5 &7.4.0

**Comment by renpytom** [comment]
Hm... This has been working for years on 7.3.5. What platform are you on, and how are you unpacking Ren'Py from the archive?

**Comment by robotsheepboy** [comment]
Hi I'm having the exact same issue, literally identical to that described. Was all working fine, installed rapt, then it asked me to reboot, as soon as I did I got the error message described.

I'm using renpy 7.4.2, windows 10, used 7zip for unpacking the archive.

**Comment by renpytom** [comment]
Closing this. If this is still an issue in a clean install of 7.4.5, feel free re-open, or open a new issue.
