### ISSUE TITLE
Ren'Py resolution does not adjust for Display Scaling[7.4.1.1193 Nightly]

### ISSUE THREAD

**Issue by Belgerum** [renpy/renpy#2581]
While trying the latest nightly to see if the issue with windows resizing larger with every subsequent launch was fixed, I noticed that the Ren'Py window for projects does not adjust it's resolution output to fit the adjusted size of the window. This means that, if put to extremes, a Ren'Py game that launches full-screen on a 3840 x 2160 display with a scaling factor set to 350% will only render at 1096x617, and upscale that to fullscreen, rather than working at the appropriate resolution for the actual amount of space the Ren'Py window is taking up.

Here's a quick video showing the visible difference in quality when changing the scaling factor on my 4K display:
https://user-images.githubusercontent.com/6981764/103960837-231ff680-5121-11eb-8389-283c7cd5a0df.mp4

Another way I can see this happening is in screenshots taken by the engine. When pressing the "S" key in the tutorial game, the screenshot saved by Ren'Py will be at a lower resolution than the display window (assumingly before the upscaling to the true window size occurs.)

**Comment by renpytom** [comment]
Can you send the log.txt for this?

**Comment by Belgerum** [comment]
[log.txt](https://github.com/renpy/renpy/files/5785123/log.txt)

**Comment by Belgerum** [comment]
After doing some testing with Ren'Py version 8.0.0.22062402 , I've found this exact issue to be happening again.
