### ISSUE TITLE
[7.4.2+] Add "Force Recompile" option to Android, iOS and Web build pages.

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2582]
Differently from the PC build. So it causes incompatibility of saves between Android and PC when PC was built first.

**Comment by Andykl** [comment]
After further checking I realized it was my misunderstanding. The option in Build Distribution is also responsible for Force Recompile when building other builds.

It might make sense to add Force Recompile to the other build options (Android, iOS, Web) to clear up potential confusion, because now after a build with Force Recompile, before building Android I should open Build Distribution again and remove that option.

**Comment by Phalzyr** [comment]
I noticed that 7.3.5 being forced to recompile does not change script_version.txt to new version and when 7.4.5 reads it in it sees the version internally as 7.3.5 which causes issues when using the new 7.4.5 code and android as the hw_video gets set to true. Shouldn't that file be altered/no longer used at that point?

**Comment by renpytom** [comment]
@Phalzyr 

That last one is intentional. The goal of script_version.txt is to record the version of Ren'Py that the script is compatible with, and to change the defaults to match that older version. Otherwise, you'd have changes in game behavior when building an older game with a newer version. (It's possible we do have some, but they're unintentional.)

**Comment by Phalzyr** [comment]
Well then it needs altered slightly as any 7.3.5 android game converted to 7.4.5 crashes on start unless one manually changes that file so hw_video doesn't get set to true as the same code later bails out of the game if it is set to true... in 00compat.rpy
`        if version <= (7, 3, 5):
            config.side_image_requires_attributes = False
            config.window_functions_set_auto = False
            config.hw_video = True
            config.who_what_sub_compat = 0`
            
            then in video.rpy:
            `        if (self.channel == "movie") and (renpy.config.hw_video) and renpy.mobile:
            raise Exception("Movie(channel='movie') doesn't work on mobile when config.hw_video is true. (Use a different channel argument.)")
`
I tried setting config.hw_video myself to false but it still sees it as true thanks to that code... Didn't spend too much time trying to overwrite that setting once i saw changing said file worked for me...

**Comment by renpytom** [comment]
You should be able to do:

```
define config.hw_movie = False
```

Before you define your Movie image. Potentially, you might have to do:

```
init -10:
    define config.hw_video = False
```

**Comment by Phalzyr** [comment]
might be the later as a simple define didn't do it. I was thinking I might need to change init level but then found changing that text file did what I wanted... my upload speed is horrendous so stopped at that point :D
