### ISSUE TITLE
Unable to build for Android on Mac with RenPy 7.4

### ISSUE THREAD

**Issue by eristheapple** [renpy/renpy#2586]
I'm unable to build any releases for Android on macOS Big Sur.  7.3 doesn't even get past the "I'm compiling a short test program, to see if you have a working JDK on your system.". 7.4 actually errors complaining about the JDK not being installed, though it is, and I am manually able to compile the test program if I try to.  Error is:

`Traceback (most recent call last):
  File "game/mobilebuild.rpy", line 195, in call
  File "/home/tom/ab/renpy-build/tmp/install.android-x86_64/lib/python2.7/subprocess.py", line 325, in __init__
  File "/home/tom/ab/renpy-build/tmp/install.android-x86_64/lib/python2.7/subprocess.py", line 978, in _execute_child
OSError: [Errno 2] No such file or directory`

Java version is:
`java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)`

**Comment by renpytom** [comment]
Hm...

Can you run from the command line, 

/usr/libexec/java_home -v 1.8

And then if it prints out *path*, try:

*path*/bin/javac ?

**Comment by eristheapple** [comment]
Sure, can do.
`% /usr/libexec/java_home -v 1.8
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home`

Followup: 
`% ls "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/"
ControlPanel	javaws		keytool		policytool	servertool
_javaws		jcontrol	orbd		rmid		tnameserv
java		jjs		pack200		rmiregistry	unpack200`

and lastly, if this helps:

`% which javac
/usr/bin/javac
`
/usr/bin/javac is *not* a symlink.

**Comment by eristheapple** [comment]
Okay so a bit more info.  If I do:
`% sudo ln -s /usr/bin/javac /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/javac`

RenPy 7.4 will then not give the missing JDK error and instead says it is building the test program, but hangs, the same as 7.3.5 does.

**Comment by renpytom** [comment]
Hm...

My guess is that you have a JRE, but not a JDK. Could you try installing the 1.8 JDK from https://adoptopenjdk.net/ ?

**Comment by eristheapple** [comment]
I have from Java SE Development Kit 8u271 from https://www.oracle.com/ca-en/java/technologies/javase/javase-jdk8-downloads.html

Specifically: jdk-8u271-macosx-x64.dmg

**Comment by renpytom** [comment]
It doesn't seem to be in use, though, given that java_home is reporting the JavaAppletPlugin version. I think you'll have to switch your system version - the one java_home reports - to the 1.8.

**Comment by eristheapple** [comment]
I only had the one version of Java (Oracle JDK 1.8) installed, I'd previously removed all Java JDK/JRE and reinstalled to ensure that I didn't have a version mismatch issue.

However, at your advice, removing the Oracle JDK 1.8 and installing the one from https://adoptopenjdk.net/ has resolved the issue, the build is working now.

**Comment by renpytom** [comment]
I'm glad it's working! I'm going to close this out. Thanks for working with me to solve this.
