### ISSUE TITLE
Boxes do not work with relative positioning

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#2589]
In switching over to v7.4 from 7.3.5, I've noticed some of my vboxes and hboxes are no longer positioned properly. After some testing, I have come up with a test screen that showcases the problem in a fresh project:

```renpy
screen box_test():

    frame:
        padding (0,0)
        xysize (265, 235)
        vbox:
            xysize (265, 235)
            add Solid("#f0f") size (50, 50) align (0.5, 1.0)
    frame:
        padding (0, 0)
        xysize (400, 700)
        align (0.5, 1.0)
        has hbox
        xysize (300, 500)
        add Solid("#0ff") size (50, 50) pos (300, 500)

    frame:
        padding (0, 0)
        xysize (400, 700)
        align (1.0, 1.0)
        has hbox
        xysize (300, 500)
        add Solid("#0ff") size (50, 50) pos (1.0, 1.0)

    frame:
        padding (0, 0)
        xysize (150, 150)
        align (0.0, 1.0)
        has hbox
        xysize (150, 150)
        add Solid("#0ff") size (50, 50)
        add Solid("#0f0") size (50, 50)
```

In v7.3.5, this acts as I would expect -- the square inside the vbox is aligned to the middle and bottom of the vbox (and containing frame), and the square inside the hbox is found approximately at position (300, 500) relative to its container for both the second and third frame.

However, in v7.4 only the second frame displays as expected; the vbox appears to ignore its ysize property, and the hbox appears to ignore its xsize property when positioning the coloured square.

![image](https://user-images.githubusercontent.com/37048629/104114704-5905dc00-52d5-11eb-8ba6-6e842a9d6c0d.png)

(Top is v7.3.5, bottom is v7.4)

The fourth frame in my screen example (displayed in the bottom left) shows the difference in spacing between boxes which are given an explicit size and more than one child. For v7.3.5, the box seems to try to manually space the children out (though, not to the limit of the box; if the box were to manually space the items I would have expected it to produce a result more like

![image](https://user-images.githubusercontent.com/37048629/104114750-0678ef80-52d6-11eb-93b1-27d7ebb1cedb.png)

or not attempt to space its children at all. However, v7.4 just groups them together as a unit, which is also fine, except using relative positioning (`pos (1.0, 1.0)` or `align (1.0, 1.0)`, for example) does not position the box as expected in the bottom right corner of the box's defined area.

**Comment by m-from-space** [comment]
I can confirm problems with hbox alignment, I had to switch to a frame in my project too.
