### ISSUE TITLE
`on "show"` not firing on screen show

### ISSUE THREAD

**Issue by dossy** [renpy/renpy#2594]
* Version: Ren'Py 7.4.0

The [documentation](https://www.renpy.org/doc/html/screens.html#on) suggests that `on "show"` in a screen should work.

Here is a minimal reproducible example of it not working:

```
define config.developer = True

screen choice(items):
    on "show" action Function(print, "on show action print")
    on "hide" action Function(print, "on hide action print")
```

When the choices are displayed, I would expect `on show action print` to get printed to the console.  It doesn't.  When a choice is selected and the choice screen is hidden, `on hide action print` is printed to the console, as expected.

**Comment by AndriWilford** [comment]
This is due to an indentation problem in exports.py .  The following lines should be indented one level back (-1),  so that the show_screen function is  NOT  part of the for loop above.

https://github.com/renpy/renpy/blob/551aebb22bf02f5113f9eee6c5783a621fd7c33b/renpy/exports.py#L1260-L1267
