### ISSUE TITLE
Rollback breaks timers

### ISSUE THREAD

**Issue by jackmcbarn** [renpy/renpy#2596]
When a screen with a timer is showing, using rollback will sometimes result in it not firing. Minimal test case:
```rpy
screen a():
    text "Screen A" xalign 0.0 yalign 0.0
    timer 1.0 action [Show('b'), Hide('a')]

screen b():
    text "Screen B" xalign 1.0 yalign 0.0
    timer 1.0 action [Show('a'), Hide('b')]

label start:
    show screen a
    "One"
    "Two"
    "Three"
    "Four"
    "Five"
    "Six"
    "Seven"
    "Eight"
    "Nine"
    "Ten"
```

That's supposed to use timers to keep switching between screens A and B every second. But if you quickly roll back, roll forward, and click to advance, the timers will stop running, and it will get stuck on one of the two screens.

It looks like #1951 fixed another symptom of this bug, but not its root cause.

**Comment by Andykl** [comment]
To fix it ad hoc you can do `timer 1.0 repeat True`
