### ISSUE TITLE
It's impossible to ignore an image with a bad filename.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2598]
```
# Where test.png doesn't exist.
image test = "test.png"

label start:
     show test
     "A"
     "B"
     "C"
```

Potentially with config.developer = False. Anything would be better than a runtime exception.

**Comment by madeddy** [comment]
I would suggest to redirect in such cases to a placeholder image similar the 404 code in browsers. (`Error XYZ: Missing resource or wrong entry {name}` ) In most cases the app should at least still running with this and people have a optical pointer.

Perhaps someone in the community could design this for you/RenPy. A little contest...?
