### ISSUE TITLE
renpy i can't edit the script (english/français)

### ISSUE THREAD

**Issue by bbrunef** [renpy/renpy#2600]
English: Hi! I just installed renpy and I already have a problem. I created a new game, but when I click on script.rpy to modify it, nothing happens. And every fonctionnality under the editor title don't  work. Can you help me?

Français: Salut, alors je viens juste d'installer l'application renpy et j'ai déjà un problème... J'ai crée un nouvaeu jeu, mais lorsque je clique sur script.rpy pour modifier le script, rien ne se passe. Toutes les fonctionnalités en dessous du titre "éditer" ne marchent pas. Je ne peux donc pas éditer mon jeu. Pouvez vous m'aider s'il vous plait? Merci d'avance!

**Comment by renpytom** [comment]
Please make sure you unpack Ren'Py from the .zip file. You might also want to go into preferences, editor, and choose Atom.

**Comment by bbrunef** [comment]
the problem is solved!
