### ISSUE TITLE
Expand say_attribute_transition to regular image attribute changes

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#2604]
Ren'py has a config variable for what transition to apply to the image when you change its attribute in a say with image attribute command (config.say_attribute_transition), e.g:
```
define e = Character('Eileen',image="e")
label start:
    show e happy
    e "I'm happy!"
    e sad "I'm sad now."   # <- image changes with the transition we defined in config.say_attribute_transition
```
This is very convenient, but at the moment it's also very restricted, since it only works for say with image attribute commands. If you want to change the character's expression on a line where they're not talking, or if there's multiple characters changing expressions at once (,or if you simply prefer the syntax of separate show and say commands), you're forced to manually add the transition to the show command every time, which is quite cumbersome and fills the script with a bunch of unnecessary transition commands.

Since the feature already seems to be mostly there, and from what I've seen (and personal experience) it's very sought after, I'd like to request that it be extended to work with regular image attribute change commands, or have its own config variable.

**Comment by renpytom** [comment]
This isn't as easy as it sounds at first blush. We probably don't want:

```
scene bg whitehouse
show eileen happy at left
show lucy concerned at right
```

To trigger three separate transitions. It probably makes sense to leverage the statement-types to make this possible, similarly to the way window auto works.

**Comment by renpytom** [comment]
Implemented.

**Comment by Kuroonehalf** [comment]
> Implemented.

Tom, I love you. ❤
