### ISSUE TITLE
Ren'Py was unable to run python with tkinter to choose the directory

### ISSUE THREAD

**Issue by ElliotBath** [renpy/renpy#2607]
Fresh download of Ren'Py SDK. I have ensured that full disk access is enabled in System Preferences. When I try to change the Projects Directory, I don't get any options - it goes straight to this error:

![image](https://user-images.githubusercontent.com/13207554/104902740-fe285080-5976-11eb-92a4-77c9ceae7935.png)

**Comment by renpytom** [comment]
I believe this was fixed in Ren'Py 7.4.1, if you're on the mac.
