### ISSUE TITLE
Documentation - new ATL properties that require gl2 mode should mention

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2608]
The new ATL properties (blur, matrixcolor) that require gl2 to be Ana led do not specifically say so in the ATL documentation page. This would be very helpful for people looking to use these new transforms.

**Comment by jackmcbarn** [comment]
Looks like this was fixed by https://github.com/renpy/renpy/commit/a854b63b965c466e7264c9ed1cd31c6fd7e28da3#diff-d85831f8a6da9c8f020125c0d4147fa3143b98e21ac0a8356a0c91bcf54c97da
