### ISSUE TITLE
Android Samsung USB-C Headphone Adapter Crashes Apps Compiled With Ren'Py 7.4+

### ISSUE THREAD

**Issue by HMBM47** [renpy/renpy#2609]
Topic.
Device: Samsung Galaxy Tab S6
Android 10

If the Samsung USB-C headphone adapter is plugged in the game crashes. 
The sound can still be heard. The app disappears from the recent app menu. 
Android reports the app as still running in the background and advises that it be stopped. 

If the Samsung USB-C headphone adapter is unplugged the app works like it's supposed to.

Older versions of Ren'Py don't seem to have this issue.

**Comment by renpytom** [comment]
Have you tried this on 7.4.1, especially in the last day or so?

**Comment by HMBM47** [comment]
Yup. That's why I added the "+" in the title. 
After it didn't work with 7.4.0, I tried 7.4.1.
I then went backwards in releases, and only had to go a step down to 7.3.5 for it to work properly.

**Comment by renpytom** [comment]
Thank you. I guess my only question is how long ago did you you try this? The reason being is that there has been an update to 7.4.1 recently. 

The other data that would be useful would be the logcat output.

**Comment by HMBM47** [comment]
I believe this is the file you want to see? 
[logcat.txt](https://github.com/renpy/renpy/files/5837013/logcat.txt)

**Comment by HMBM47** [comment]
I made this using the latest nightly build.
I THINK this is the info you wanted? Clicked the "Logcat" button in the program. 
Hopefully there's enough info.
[logcat.txt](https://github.com/renpy/renpy/files/5837134/logcat.txt)
