### ISSUE TITLE
[Crash with No Log] Movie Sprites on Ren'Py 7.4.0.1167

### ISSUE THREAD

**Issue by DipeshAggarwal** [renpy/renpy#2610]
[Video Sprite Test.zip](https://github.com/renpy/renpy/files/5837299/Video.Sprite.Test.zip)

Just Click on Start and the game will freeze for a few seconds and then close without leaving any traceback/log/error.
OS: Windows 10
Ren'Py v7.4.0.1167

**Comment by renpytom** [comment]
Could you try it on 7.4.1, please? I

**Comment by DipeshAggarwal** [comment]
Works with 7.4.1. Closing.
