### ISSUE TITLE
$ renpy.input() problem with special characters (ñ, ç...)

### ISSUE THREAD

**Issue by xavi-mat** [renpy/renpy#2611]
Tested with 7.4.1.1241 and 7.4.1.1208. Both don't work. (Works OK in 7.3.5.606).
(Ubuntu 20.10 64-bit)
```
$ renpy.input("Write something")
```
and
```
screen test_input():
    input
```
Input accepted: `a á â ä`...
Input not accepted (just does nothing): `ñ, ç, ŀ`
Some key combinations causes a crash without error: `· `

Curiously, this works in 7.4.1, and not in 7.3.5: `ạ`

**Comment by renpytom** [comment]
I haven't been able to repeat this.
