### ISSUE TITLE
Allowing ImageDissolve transition to use Displayables as well

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#2617]
Currently the ImageDissolve transition uses an image manipulator for a matrixcolor. https://github.com/renpy/renpy/blob/a21b7a7dc88668058f505968d61df40ba1acac8f/renpy/display/transition.py#L508

We can now use the matrixcolor transform property to allow displayables in an ImageDissolve, eg:

```
            if not reverse:
                # Copies red -> alpha
                matrix = Matrix(
                    [
                        1, 0, 0, 0,
                        0, 0, 0, 0,
                        0, 0, 0, 0,
                        1, 0, 0, 0,
                    ]
                )

            else:
                # Copies 1-red -> alpha
                matrix = Matrix(
                    [
                        1, 0, 0, 0,
                        0, 0, 0, 0,
                        0, 0, 0, 0,
                        -1, 0, 0, 0,
                    ]
                )

            self.image = Transform(image, matrixcolor=matrix)
```

I can open a PR for this, I just need to know if I can gut the image manipulator or if versioning should be used for compatibility.

**Comment by Andykl** [comment]
See https://github.com/renpy/renpy/pull/2427

**Comment by jsfehler** [comment]
Awesome. My work here is done.
