### ISSUE TITLE
Unable to install RAPT on macOS with 7.4.1

### ISSUE THREAD

**Issue by eristheapple** [renpy/renpy#2618]
I am able to build Android versions of RenPy games with no issues on 7.4.0, but on 7.4.1 if I try to install RAPT, I get the error: `An error has occurred: OSError: [Errno 2] No such file or directory`

No further info is given, it just hangs with the error and I have to click Cancel to get out of the dialogue.

**Comment by auzbuzzard** [comment]
This is the same for targeting iOS builds. It will ask to download renios but then show the same Exception.

**Comment by renpytom** [comment]
Dangit. This is going to break updating to the next version, until I fix things.

**Comment by renpytom** [comment]
Can you try it now? I believe that I was able to fix this remotely.

**Comment by eristheapple** [comment]
Can confirm it's working now, I can build for Android and iOS.  Thanks renpytom!
