### ISSUE TITLE
Screen minimization issues in macOS.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2623]
<img width="77" alt="스크린샷 2021-01-25 오후 6 15 18" src="https://user-images.githubusercontent.com/60040734/105685599-999e6000-5f39-11eb-9e4d-a775d4d89b1e.png">

When I maximize the screen with the green button at the left top, it becomes impossible to minimize the screen.

**Comment by jackmcbarn** [comment]
Does pressing `F` to toggle fullscreen help?

**Comment by ikusorae** [comment]
It's not related to that. It shows strange minimization only in games maximized through the "green button".
