### ISSUE TITLE
After building Android the Java process remains alive even after the Launcher has been closed.

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2624]
On Windows with Ren'Py 7.4.1

**Comment by renpytom** [comment]
Note to self - The fix for this is to call ``gradlew --stop`` once the build is finished.

**Comment by Andykl** [comment]
Same with logcat (adb process).

**Comment by renpytom** [comment]
I'm not going to worry about adb, as it's small, and having the adb daemon provides actual benefit to users.
