### ISSUE TITLE
Renpy keeps resetting and loosing projects?

### ISSUE THREAD

**Issue by Adamsnowflake** [renpy/renpy#2629]
I've seen a few people say to reset the preferences but I'm unsure of as to what? When you go into preferences on renpy theirs a boat load of folders you can reset the preferences too and I'm unsure of as to where to set the preference folder to? (hence the weird folder location in the photos)
Sorry if I worded that weirdly.
Basically I'm working with renpy and I have a ton of games I'm working on, but it keeps resetting itself and I keep loosing my game folders in the options menu here are a few pictures. The games are still stored in the settings of renpy. The files are still saved on my computer and I believe the issue has to do with something on the preference setting in the settings of renpy. Major thanks to anyone who can help me out here ^^;
![image](https://user-images.githubusercontent.com/78120902/106071201-e9189380-60d3-11eb-8d43-0f3351b4cf20.png)
![image](https://user-images.githubusercontent.com/78120902/106071234-f46bbf00-60d3-11eb-967d-a8aa6f96e379.png)
![image](https://user-images.githubusercontent.com/78120902/106071252-0188ae00-60d4-11eb-9843-c6b690ec5613.png)

**Comment by renpytom** [comment]
I'd suggest not sticking games in the tmp directory that Ren'Py uses for its own purpose.

**Comment by Adamsnowflake** [comment]
Yeah I just don't know where renpy usually stores them ^^; I'm sorta lost.

**Comment by renpytom** [comment]
There's no place, it just asks you. You could put it in "My Documents".

**Comment by Adamsnowflake** [comment]
ah that fixed it! I just put the project on desktop and then put preferences on desktop. I think I just need to put the folder where the projects are stored! thanks!
