### ISSUE TITLE
Screens above modal screen don't show buttons as hovered

### ISSUE THREAD

**Issue by midgethetree** [renpy/renpy#2630]
If a modal screen is placed in between the quick menu and some normal screens (zorder 50), the quick menu buttons can be clicked on but they never actually get styled as hovered (imagebuttons don't change image, textbuttons don't change text color).

**Comment by renpytom** [comment]
I'm not able to repeat this. 

```
define _confirm_quit = False

define e = Character("Eileen", image="eileen")
define l = Character("Lucy", image="lucy")
define a = Character("Augustina", image="augustina")

label main_menu:
    return

screen test():
    modal True
    zorder 50

    frame:
        has fixed

        textbutton "Test" action Return(True)

screen test2():
    textbutton "Double Test" action Return(False)

label start:

    scene bg washington

    show screen test2()
    show screen test()

    "..."

    return
```

**Comment by midgethetree** [comment]
Tested some more things out and turns out this issue only happens when the button sets a variable on hover - possibly this happens with some other actions I haven't tested, but NullAction seems to not have this issue at least. Here's the quick menu code I used in the test project with your sample to demonstrate it, most of the buttons still work but Skip and Save change variables on hover and so have the issue I'm talking about:

```
default test_nonscreen = 0
screen quick_menu():

    zorder 100

    default test_screen = 0

    if quick_menu:

        hbox:
            style_prefix "quick"

            xalign 0.5
            yalign 1.0

            textbutton _("Back") action Rollback()
            textbutton _("History") action ShowMenu('history'):
                hovered NullAction()
            textbutton _("Skip") action Skip() alternate Skip(fast=True, confirm=True):
                hovered SetScreenVariable('test_screen', 1)
            textbutton _("Auto") action Preference("auto-forward", "toggle"):
                unhovered SetScreenVariable('test_screen', 1)
            textbutton _("Save") action ShowMenu('save'):
                hovered SetVariable('test_nonscreen', 1)
            textbutton _("Q.Save") action QuickSave():
                unhovered SetScreenVariable('test_nonscreen', 1)
            textbutton _("Q.Load") action QuickLoad()
            textbutton _("Prefs") action ShowMenu('preferences')
```

**Comment by renpytom** [comment]
Thanks. I'm retargeting this to 7.4.3.

**Comment by renpytom** [comment]
I haven't been able to repeat this, but I'm pretty sure that's because 3ee379438ea51a5e0cf7eac2c441e981f8aa3ea8 fixed the problem. Could you try this on the nightly and see if things are fixed?

**Comment by midgethetree** [comment]
Tried the nightly and yep, the buttons are being correctly styled now, thanks!
