### ISSUE TITLE
Zorder Enhancements

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2635]
It would be nice to have two new functions that affect the zorder of layers:

renpy.list_layer_zorders() - Returns a list of everything on a layer (or everything with a tag on the layer), and it's current zorder.
renpy.change_zorder() - Given a layer and tag, set the zorder of of the displayable on that layer with the tag.

**Comment by JellySnek** [comment]
Fantastic and much, MUCH appreciated, Tom.

**Comment by renpytom** [comment]
The final names are:

* renpy.get_zorder_list()
* renpy.change_zorder()

And they'll be in the next nightly.
