### ISSUE TITLE
Saving persistent falls on Windows with Yiddish username.

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2637]
![image](https://user-images.githubusercontent.com/27142420/106392177-61939300-63f9-11eb-8cd2-51ee71ceb5eb.png)
Where `??` is `שי`. I don't know why it replaced it with questions, since it successfully writes escaped unicode for Cyrillic.

**Comment by renpytom** [comment]
What is the user's encoding set to? We are very likely to have problems if the user's username is not representable in the system encoding. This might be something similar to #215, though not the same thing exactly.

**Comment by Andykl** [comment]
Yes. User encoding was English (USA).
Only weird thing is that a replacement was questions, instead of escaped unicode.
