### ISSUE TITLE
{done} tag does not send full dialogue string to renderer

### ISSUE THREAD

**Issue by AndriWilford** [renpy/renpy#2638]
It seems that the {done} tag, when encountered by the dialogue tag parsing in renpy/character.py  ~line 100, will stop processing the rest of the text, and not append the rest of the string.

If the intent is to let the text render for a subsequent line that extends the text (like, by using the {fast} tag), do so without visual artifacts, then only accumulating part of the string defeats that.

If that's not the intent in the first place, then this issue is not an issue.

As an example, a very 'hacky' way to fix this, that seems to work for me, is attached. {no alt} ensures that the hidden text is not spoken. Maybe only as an example.. like, realized that other things can come up. Also need a {cps=0}{/cps} there so hidden text doesn't take non-zero time to display...

[donetagHackFix.txt](https://github.com/renpy/renpy/files/5900449/donetagHackFix.txt)

**Comment by renpytom** [comment]
This should be fixed by d9163b5f49539b0bddf316169d0f0179316a3286 and d7afd56a94b6a6fec3d4acd6031d10c8e1decf17.
