### ISSUE TITLE
.ico file is causing launch issues for Windows 7 (Tested in 7.4.1 and 7.4.2)

### ISSUE THREAD

**Issue by SLimLUL** [renpy/renpy#2639]
Player on Windows 7 and older were reporting the error ".exe is not a valid Win32 application"
The issue is gone when removing the .ico file from the origin folder.

The game launches normally on Windows 10
The game launches normally on older renpy versions

[icon.zip](https://github.com/renpy/renpy/files/5905967/icon.zip)

**Comment by HizorGungine** [comment]
I can confirm. .ico files are causing Win7 to display ".exe is not a valid Win32 application".
[icons.zip](https://github.com/renpy/renpy/files/5937551/icons.zip)

**Comment by renpytom** [comment]
I'm pretty sure this has been fixed by the changes in 7.4.3.
