### ISSUE TITLE
Bug since ren'py 7.4.0 when displaying Emoji

### ISSUE THREAD

**Issue by ex-term** [renpy/renpy#2642]
One of my projects makes extensive use of Emojis embedded into normal text.
This did work quite well with 7.* versions up to 7.3.5
Since 7.4.0 it is not longer possible.

Please see the attached example  fragment. When extracted to a fresh project the supplied "script" will result in displaying a bunch of emoji using the font included in the .zip

Using ren'py 7.3.5 this works for any code point that actually is in the font. For 7.4.0 it does not work for most emoji and even on those sometimes gets the spacing wrong (look at the first two characters).

[script.txt](https://github.com/renpy/renpy/files/5908842/script.txt)

**Comment by ex-term** [comment]
Sorry - forgot to attach the font too ...
[example.zip](https://github.com/renpy/renpy/files/5916431/example.zip)

**Comment by dogtopus** [comment]
![aab](https://user-images.githubusercontent.com/3405234/106705240-f8ac4680-65c3-11eb-846c-6ba7b018b36f.png)

idk seems fine for me. Tested on Arch Linux system Ren'Py (7.4.0.1167, freetype version 2.10.4)

The heart being off center could be a font issue since heart the character is displayed properly but not heart the emoji. There was a font rendering fix a few month ago that specifically let Ren'Py differentiate between those 2 cases so it might work normally before but not anymore.

**Comment by dogtopus** [comment]
Still can't reproduce even with the example files.

![aac](https://user-images.githubusercontent.com/3405234/106705718-d961e900-65c4-11eb-9672-ffd5c3697ec9.png)

Could you please send a screenshot?

**Comment by dogtopus** [comment]
OK I know what's potentially going on. Seems to be the surrogate pair issue mentioned in #2272. Still waiting for a screenshot.

**Comment by ex-term** [comment]
Here's the result with ren'py 7.4.2.1292 (or any other officially released "stable" 7.4.x version before that):

![screenshot0001](https://user-images.githubusercontent.com/78401049/106753930-9dfb0500-662c-11eb-86f9-a4ff8a5d8af4.png)

And this is using 7.3.5.606
![screenshot0001](https://user-images.githubusercontent.com/78401049/106753976-af441180-662c-11eb-8473-a5c8f377f0e0.png)

I'm running OpenSuSE 15.2 with a copy of Symbola.ttf that I found on my system and copied to the game directory.
Freetype lib installed on system is libfreetype6-2.10.1-lp152.2.5.1.x86_64

**Comment by ex-term** [comment]
> OK I know what's potentially going on. Seems to be the surrogate pair issue mentioned in #2272. Still waiting for a screenshot.

Seems like it is related. As far as I can tell the "broken" symbols are all from beyond 0x10000 and thus > 65535.
(Note: both the python 2.7 and python 3 versions on the OS itself have sys.maxunicode = 1114111 by the way)

**Comment by dogtopus** [comment]
> Freetype lib installed on system is libfreetype6-2.10.1-lp152.2.5.1.x86_64

Official release has its own freetype version so it will be unrelated to system freetype version. Nevertheless it's not related to freetype but a Python build issue and how 7.4 handles unicode in general.

**Comment by renpytom** [comment]
Just going from memory here, I believe this stems from changing things so that all platforms use UCS-2, like Windows does. If I'm remembering correctly, and it'll be a bit until I can do some tests, emoji would work on Linux/Mac and fail on Windows, and with the change they now produce the same failures on every platform. 

Eventually, I'd like to implement something that can create glyphs from surrogate pairs, but I haven't had time to get to do that yet. Python 3 support will also fix this, and that may come first. As much as it's unfortunate that emoji rendering doesn't work on Linux, I think giving developers a consistent platform to work on takes priority, and we can add features to it.

**Comment by ex-term** [comment]
I realize that python3 support is way more important than this.

Is there any kind of workaround for now?

**Comment by ex-term** [comment]
Sorry, but I just tried the nightly build on my example code and it seems like there went something wrong with your fix.
[traceback.txt](https://github.com/renpy/renpy/files/6008238/traceback.txt)

(In case stuff had changed since the release of that nightly - this is line 758 and some context from ftfont.pyx right now)

            if i < len_s - 1:
                if i < len_s - 2 and is_ucs2_surrogate(s[i + 1]) == 2 and is_ucs2_surrogate(s[i + 2]) == 1:
>>                next_c = ((s[i + 1] & 0b1111111111) << 10) | (s[i + 2] & 0b1111111111)
                    vs_offset = 3
                else:
                    next_c = s[i + 1]
                    vs_offset = 2

**Comment by dogtopus** [comment]
> Sorry, but I just tried the nightly build on my example code and it seems like there went something wrong with your fix.
> [traceback.txt](https://github.com/renpy/renpy/files/6008238/traceback.txt)
> 
> (In case stuff had changed since the release of that nightly - this is line 758 and some context from ftfont.pyx right now)
> 
> ```
>         if i < len_s - 1:
>             if i < len_s - 2 and is_ucs2_surrogate(s[i + 1]) == 2 and is_ucs2_surrogate(s[i + 2]) == 1:
> ```
> 
> > > ```
> > >            next_c = ((s[i + 1] & 0b1111111111) << 10) | (s[i + 2] & 0b1111111111)
> > > ```
> 
> ```
>                 vs_offset = 3
>             else:
>                 next_c = s[i + 1]
>                 vs_offset = 2
> ```

Why? I mean I know why but why? :confused: 

Anyway I fixed it and I'll test it with a UCS-2 build of Python this time.

**Comment by ex-term** [comment]
> Why? I mean I know why but why? :confused:
;)

By the way: there's two lines with that kind of arithmetic as far as I can tell (you handled s[0] as a special case).

**Comment by dogtopus** [comment]
I wasted too much time tracking down a dumb bug lol. Anyway it's now working and I made sure to test it this time.

![finally](https://user-images.githubusercontent.com/3405234/108488005-412b5b80-7276-11eb-99ea-ab11425cb932.png)

script.rpy:

```renpy
﻿label start:

    "{font=Symbola.ttf}❤️❀✽❊💐📖🛒🛍️👗🎉👭👫🤦🌏💬🎮📺🎟️⚽🎲📿💍🤼😜\u2648\u2649\u264A\u264B\u264C\u264D\u264E\u264F\u2650\u2651\u2652\u2653{/font}\n[sys.maxunicode]"


    return
```
