### ISSUE TITLE
Using `mesh True` or `Flatten` produces visual artifacts when the screen size is different than what was passed to gui.init

### ISSUE THREAD

**Issue by NbpDev** [renpy/renpy#2644]
Steps to reproduce:
1. Create a new Ren'Py project with size 1920x1080
2. Replace the contents of `script.rpy` with the following:
```rpy
define config.gl2 = True

screen meshbug():
    vbox:
        xalign 0.5 yalign 0.5
        text "{b}{i}Lorem ipsum dolor sit amet{/i}{/b}" size 48 outlines [(5, "#ff0000")]:
            at transform:
                mesh True
        text "{b}{i}Lorem ipsum dolor sit amet{/i}{/b}" size 48 outlines [(5, "#ff0000")]

label start:
    show screen meshbug
    pause
```
3. Run the game in a window much smaller than 1920x1080

The result will be that the top line of text with `mesh True` is significantly fuzzier than the bottom line of text without it, and the outline on the last letter will get truncated.
![screenshot0005](https://user-images.githubusercontent.com/69883267/106703624-9c8ff500-65b8-11eb-8222-e346ae2af2b7.png)

**Comment by renpytom** [comment]
I don't believe this is a bug. By using Flatten/mesh , you're basically asking Ren'Py to take a picture of the full-sized text, and then shrink the picture down. I believe that - modulo some issue with not enough padding - you're basically getting the artifacts I'd expect from that process. 

I'm not sure what the motivation for making a picture out of text like this, would be. Something to do with shaders?

**Comment by NbpDev** [comment]
> I don't believe this is a bug.

On Discord last week, you said it was: ["File a bug report with a replication. meshT True shouldn't cause artifacts like that, unless you transform the text in size."](https://discord.com/channels/286633898581164032/286633898581164032/806396002826453002)

> I'm not sure what the motivation for making a picture out of text like this, would be.

Because otherwise, fading it in and out with `alpha` will result in the intermediate color of the text being pink instead of gray (and can cause other artifacts with slightly different font or outline size choices). For example, here's what each looks like at `alpha 0.5`:
![image](https://user-images.githubusercontent.com/69883267/107601456-cc607d80-6bf4-11eb-88ca-bfe78790cd79.png)

**Comment by NbpDev** [comment]
For completeness, here's the original example from Discord:
```renpy
screen test():
    grid 2 2:
        xalign 0.1 yalign 0.1
        text "Test" font "BradleyGratis.ttf" size 64 outlines [(3, "#000000")]:
            at transform:
                mesh True
                alpha 0.5
        text "Test" font "BradleyGratis.ttf" size 64 outlines [(3, "#000000")]:
            at transform:
                mesh False
                alpha 0.5
        text "Test" font "BradleyGratis.ttf" size 64 outlines [(3, "#000000")]:
            at transform:
                mesh True
                alpha 1.0
        text "Test" font "BradleyGratis.ttf" size 64 outlines [(3, "#000000")]:
            at transform:
                mesh False
                alpha 1.0
```
![image](https://user-images.githubusercontent.com/69883267/107601618-45f86b80-6bf5-11eb-8d96-51ad6b97b237.png)
![image](https://user-images.githubusercontent.com/69883267/107601630-4b55b600-6bf5-11eb-88dd-94a9bdf2e0b5.png)

**Comment by renpytom** [comment]
Ah, I remember now, though I'm not sure I understood what was going on when we spoke on discord. 

My current thinking is that while I get the motivation, I don't think there's a good way to combine both mesh/flatten and drawable resolution text. I'll think a bit more and see if there's a way to get this to work, but I'm not terribly hopeful.

**Comment by NbpDev** [comment]
> My current thinking is that while I get the motivation, I don't think there's a good way to combine both mesh/flatten and drawable resolution text. I'll think a bit more and see if there's a way to get this to work, but I'm not terribly hopeful.

If you don't see a way to get mesh/Flatten to work, what about a different approach entirely to making text with outlines fade correctly, such as if outlines were only opaque where the real characters (and "higher" outlines, if there's more than one) are transparent? For example, the top line in this mock-up would currently be drawn by Ren'Py as the two pieces in the middle line. If it were instead drawn as the two pieces in the bottom line, then I wouldn't need mesh/Flatten.
![image](https://user-images.githubusercontent.com/69883267/107603039-88bc4280-6bf9-11eb-9075-12ead4ca6dda.png)

**Comment by renpytom** [comment]
I'm not 100% sure I can do it, but I'm working on getting mesh working.
