### ISSUE TITLE
[Feature request] Stop all sounds & music if window is minimized

### ISSUE THREAD

**Issue by Vadim-Karpenko** [renpy/renpy#2645]
Hello everyone,
Is there a way to stop playing all the sounds from the game if the window is minimized and then continue from the same spot when game is maximized again?

Did try to find how this can be achieved, but no luck yet. Any help would be appreciated

**Comment by renpytom** [comment]
This should be controlled by a preference that defaults to False.

**Comment by renpytom** [comment]
@jsakaa asked to take this on as part of a university project.

**Comment by Andykl** [comment]
Fixed by #3431.
