### ISSUE TITLE
Different behaviour in  7.1.3 vs 7.4.2 Drag xmaximum

### ISSUE THREAD

**Issue by RubenGarcia** [renpy/renpy#2647]
This code:
```
image i = Fixed(Drag ("I.png", draggable=True, droppable=False, xpos=25, 
    xmaximum=200, ymaximum=200))
```
 - When run in Renpy 7.1.3 provides an image which can be dragged in a 200x200 square)
 - When run in Renpy 7.4.2 can be dragged outside of the 200x200 square.

In Renpy 7.4.2, the code
```
image i = Fixed(Drag ("I.png", draggable=True, droppable=False, xpos=25), 
    xmaximum=200, ymaximum=200)
```
provides an image which can be dragged in a 200x200 square.

Can a note indicating the change in behaviour be added to 
https://www.renpy.org/doc/html/drag_drop.html
?

**Comment by renpytom** [comment]
This was 115aae01dc93fcbf448edb6605ad57809e91808b , which was a pure bugfix - it doesn't make sense that xmaximum (which sets the size of the drag) would limit that it's moved. At the time, I considered it so minor, I don't think it even made the changelog, and I don't think that it needs to be documented going forwards. 

(I belive that the current behavior matches the documentation, so I don't think it makes sense to document when it didn't.)
