### ISSUE TITLE
How to access global objects 

### ISSUE THREAD

**Issue by oldhiccup** [renpy/renpy#2650]
I have the following situation, I am used to object-oriented programming, and renpy is sometimes completely structured.

Reusing the code is quite complex.
I am trying to develop a routine as follows.

My character has a side image, I would like to be able to define the text font according to the side image, without using auxiliary variables, of course at some point renpy passes to python which image it will load, I would like to do an if to check which image is being shown or something, and configure the source or anything according to that condition;
Like this

```
if Character().SideImage() == "happy":
    define gui.text_font = "ArchitectsDaughter.ttf"
elif Character().SideImage() == "sad":
     define gui.text_font = "ArchitectsDaughter2.ttf"
```

**Comment by renpytom** [comment]
You probably want:

```
$ side_image = renpy.get_side_image("side")
```

**Comment by oldhiccup** [comment]
No no friend, I think I was not clear on my doubts, I had even tried this method before, but it always returns None, no matter if I put the side configured on my character, or generically. 

Look.

The character


`
define main_character_name = Character(
                                "{b}[main_character]{/b}",
                                color="#007aff",
                                image="mc_side")
`

This character has two images different from the standard and when he is thinking.
When he is thinking I call `main_character_name think "Hi"`
and the side image appears, but I would like to change the font along with the image, without having to use it directly in the message, from automatic form.

As renpy knows that I'm past think, I should be able to access this image somehow.

example

`$ side_image = renpy.get_side_image (). getCurrent ()`

```
if side_image:
      define text_font = "ArchitectsDaughter.ttf"
else:
        define text_font = "ArchitectsDaughter2.ttf"
```

**Comment by oldhiccup** [comment]
Thanks 👍
