### ISSUE TITLE
[7.4] Distribution for macOS does not support HiDPI.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2658]
When a game is played through Ren'py, the screen does not appear blurry, but the distribution does not apply HiDPI, making the screen blurry.

**Comment by renpytom** [comment]
Do you have an example? Since there shouldn't be a relevant difference here.

**Comment by ikusorae** [comment]
<img width="170" alt="스크린샷 2021-02-09 오후 6 06 37" src="https://user-images.githubusercontent.com/60040734/107340968-c2aa1d80-6b01-11eb-9ac1-98f0fa043a4b.png">
The top is a game run through Ren'py, and the bottom is a distribution made by Ren'py.

<img width="271" alt="스크린샷 2021-02-09 오후 6 06 53" src="https://user-images.githubusercontent.com/60040734/107340971-c50c7780-6b01-11eb-9905-7f12bdf04cb0.png">
And also the left is executed through Ren'py, right is a distribution.

Tested on the iMac 5K with the latest nightly.

**Comment by renpytom** [comment]
Can you make a short game, build the distro, and post it somewhere? I want to look to see what's going wrong.
