### ISSUE TITLE
Environnement variable: 'RENPY_DRAWABLE_RESOLUTION_TEXT' not working when using new Model-Based rendering (gl2)

### ISSUE THREAD

**Issue by Bobyteal** [renpy/renpy#2659]
Doesn't seem to work with GL2
Wish it would work because it's kind of a deal when you are aiming at retro aesthetic. In those cases you want the text to scale with the rest of the image (and become a bit blurry along with the images, that's okay) and not have the text scale independently and be perfectly clean while the image alone become blurry.

Here with RENPY_DRAWABLE_RESOLUTION_TEXT set to 1 (it is by default)
![frametest](https://user-images.githubusercontent.com/78823063/107424320-cba8e800-6b1d-11eb-806f-d7d21f18ea7e.png)

Here with RENPY_DRAWABLE_RESOLUTION_TEXT set to 0 (environment variable)
![frametest2](https://user-images.githubusercontent.com/78823063/107424470-f5faa580-6b1d-11eb-9bb4-73d48033194c.png)

**Comment by renpytom** [comment]
Could you put together a short example of this? As far as I can tell, this environment variable works and is respected. (Though I would recommend using config.drawable_resolution_text over the environment variable.)

**Comment by Bobyteal** [comment]
I can set up a series of screenshots if necessary, but here the observed behaviour, I have the environment variable recognised while using the old render, as soon as I use the new render (gl2), the text becomes sharper, the environment variable seems to be ignored.
Thank you for recommending config.drawable_resolution_text, I didn't know there was another way but I couldn't find an example on how to use it though, how would you use this another method exactly?
Regards

**Comment by renpytom** [comment]
Sorry, it's:

```
define config.drawable_resolution_text = False
```

I'm looking at this, and I'm not actually seeing an issue in Ren'Py. If you could put together a replication, I'd appreciate it, otherwise I can't do anything else with this issue.

**Comment by Bobyteal** [comment]
Thank you, define config.drawable_resolution_text = False worked perfectly. It's also much more practical to use, I don't know why environment variable via environnement.txt stopped working with GL2 but it doesn't matter when this is just a superior way of using it. This is definitely resolved I think.
Just wanted to notify you, this isn't related to the issue but after messing around with GL2 this morning and running lot of test comparison between the two renders, I was surprised by how GL2 performs on my hardware. The performance and framerate takes a ~20% hit, which is noticeable when loading a new scene, or playing transform, the dips to lower framerate are more pronounced compared to the old render. So for now I'll be sticking to the old render because of the slight performance increase and not planning to use the new stuff that GL2 offer yet. 
I'll be revisiting it in the future. Thank you for the great work and good continuation.
