### ISSUE TITLE
Mouse cursor didn't change in runtime 7.4.x 

### ISSUE THREAD

**Issue by roxygen** [renpy/renpy#2663]
We have feature in the game wich allow player to change mouse cursor in preferences, but since 7.4.0 I noticed mouse cursor now only changed during game restart.  Is there any way to keep feature in next games? I know there is a way to change cursor in runtime in sdl.
Action sample
```py
class ADV_ChangeCursor(Action):
        def __init__(self,num):
            self.num = num
        def __call__(self):
            persistent.cur = self.num
            if cursors[self.num].data is None:
                config.mouse = None
            else:
                config.mouse = { 'default' : [ cursors[self.num].data ] }
            renpy.restart_interaction()
            renpy.save_persistent()
        def get_selected(self):
            return self.num == persistent.cur
```

**Comment by renpytom** [comment]
Changing config.mouse at runtime, like changing other config variables, isn't supported. 

Instead, you'll want to set the `default_mouse` variable to either 'default' or None.
