### ISSUE TITLE
[Nightly] Transform is laggy with nightly build.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2665]
https://user-images.githubusercontent.com/60040734/107877354-42275a80-6f0f-11eb-8a1d-d3484e1be770.mp4

( 00:00 to 00:07 Ren'Py 7.4.2 / 00:08 to 00:16 Ren'Py Nightly )

I think it is laggy when a large amount of Transform is performed.
Tested on SM-N971N(Galaxy Note10).

**Comment by renpytom** [comment]
I don't think this is something I can address with just a video. If you'd like, please refile the bug with an example game.

**Comment by ikusorae** [comment]
I sent you an email including an example project and an application file. Please check.
Thanks
