### ISSUE TITLE
[Possible feature] "Activable" property for buttons

### ISSUE THREAD

**Issue by Lezalith** [renpy/renpy#2667]
Right now, there are "selected" and "sensitive" properties for buttons (and imagebuttons, textbuttons and hotspots). 

I think it would be useful to have an "activable" property too. 

Selected takes an expression to evaluate whether the button is selected, which means using the "selected_idle" and "selected_hover" properties, if present.
Sensitive takes an expression to evaluate whether the button is sensitive, which means using the "insensitive" property and disabling the "action".
Activable would take an expression in the same way, to evaluate whether the button is activable, which would mean the button acts as normal (using "idle" and "hover" properties), only disabling the "action".

**Comment by renpytom** [comment]
Isn't this just:

```
action If(condition, DoSomething(), NullAction()) ?
```

**Comment by Lezalith** [comment]
Basically. Not worth making into a standalone property you think then?

**Comment by renpytom** [comment]
I don't think so. I think wanting to have a button that looks like it can be clicked, but can't really be clicked, isn't going to come up that often, and so I don't think it's worth adding syntax to support this.
