### ISSUE TITLE
[7.4.2] Windows security system detects x32 exe as if it were a Trojan horse

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#2676]
In my recent build of my game Windows detects the x32 exe as a trojan and blocks it.
virustotal: https://www.virustotal.com/gui/file/b2f6211d55cd5f3a66602dea2837d756a96f07a599d0fca4120ad39235548c88/detection

![image](https://user-images.githubusercontent.com/36079551/108440118-4ca86380-7231-11eb-8d9c-622fcb36560d.png)
![image](https://user-images.githubusercontent.com/36079551/108440164-5762f880-7231-11eb-91ab-d5b3e911bef7.png)
Message error in english:
```
Alert Level: Severe
Status: Active
Category: Trojan Horse
Details: This program is dangerous
```

**Comment by renpytom** [comment]
This is a duplicate of #2631  . Can you try the 7.4.3 nightly, to see if it fixes things?

**Comment by Neyunse** [comment]
Fixed 
https://www.virustotal.com/gui/file/71081d1815d1b20ff78485a4e2ec2dd512ef69ebcce08292bac2e1f33cf4aff6/detection
