### ISSUE TITLE
Unhovered and tooltip don't work on modal screens in 7.4.2

### ISSUE THREAD

**Issue by bobcgames** [renpy/renpy#2680]
In renpy 7.4.2, when you have a modal screen (Screen B) that is shown on top of another modal screen (Screen A), tooltips and unhovered actions don't work on Screen B. They do work on Screen A.

This is a regression from renpy 7.3.5, where such functionality did work on both screens.

See this script for repo examples: [https://drive.google.com/file/d/1xViADLGJm2xMnzYvma4UlXGLe4cq-SZv/view?usp=sharing](https://drive.google.com/file/d/1xViADLGJm2xMnzYvma4UlXGLe4cq-SZv/view?usp=sharing)

Click the "Show modal screen" button at the top left, and note that both tooltips work on the first screen (one is using "tooltip" while the other is hovered/unhovered). Click the "Show next screen" button and notice that the first tooltip doesn't work at all, while the second shows but doesn't hide.

Making the second screen non-modal also does not solve the problem. Click "Show next next screen" and see that the same problem occurs.

If the first screen is non-modal, all tooltips and hovers work properly. Close and click "Show non-modal screen" and repeat the steps and notice that all hovers and tooltips work on all screens when the first screen is non-modal.

**Comment by bobcgames** [comment]
Looks like it could be related to this issue: https://github.com/renpy/renpy/issues/2630

**Comment by renpytom** [comment]
Have you tried this in 7.4.3? I believe this might be fixed by 3ee379438ea51a5e0cf7eac2c441e981f8aa3ea8 .

**Comment by bobcgames** [comment]
Just did with the nightly (7.4.3.1336) and it is indeed fixed. Thank you!
