### ISSUE TITLE
Audio tracks do not start after load 

### ISSUE THREAD

**Issue by AndriWilford** [renpy/renpy#2681]
When a context switch (load) happens, audio is reverted to the previous context. The new tracks are started with  `synchro_start=True`  which will wait until all audio channels are cleared and ready to start a new track.

However, the chain of events for starting a new, upcoming track in a channel will not 'restart' audio when:
1) The channel is set to loop or the track in a channel is set to loop
2) The  "current"  track  (the audio track before the context switch)  is the same as that currently playing, or is in filelist of a set of files in the upcoming looping audio

When this happens, all other tracks are set in a paused state, waiting for that looping track to clear out  (queue depth in channel object in audio.py, not the renpysound queue becomes 0). This is typically after two loops of the track, since loops will usually have current + next queued. After those two loops complete, all channel queues are now  0 depth  and suddenly, all other channels begin playing.

I see options as:
1) Keep the notion of 'sync start'  on game load/context switch,  which then would presumably require stopping and restarting a track, even when the track is already playing in the channel
    1a)  Keep sync-start,  and  DO NOT  restart the looping track when it's the same,  but "pretend" like it was restarted and sync-start other things

2) Do not have tracks sync-start on context switch  (switch to   synchro_start=False )

3) Ignore the problem, since it's relatively minor

**Comment by AndriWilford** [comment]
For 1):
@ 1135
```
                if c.loop:
                    if not filenames or c.get_playing() not in filenames:
                        c.fadeout(renpy.config.context_fadeout_music or renpy.config.fade_music)
```
 .. to ..
```
                 if c.loop:
                    c.fadeout(renpy.config.context_fadeout_music or renpy.config.fade_music)
```



For 2):
@ 1140
`                    c.enqueue(filenames, loop=True, synchro_start=True, tight=tight, fadein=renpy.config.context_fadein_music)`
 .. to ..
`                     c.enqueue(filenames, loop=True, synchro_start=False, tight=tight, fadein=renpy.config.context_fadein_music)`

**Comment by renpytom** [comment]
I think 2 is right. I'll make the change.
