### ISSUE TITLE
Lint issues in 7.4.3

### ISSUE THREAD

**Issue by bobcgames** [renpy/renpy#2684]
1) Parameterized Text usage in 7.4.3 is reporting as a lint error (`testtext "[foo]" is not an image`.), while the same text does not cause problems in 7.3.5

```
image testtext = ParameterizedText(size=60, xalign=0.5, yalign=0.5)
default foo = "test"
label start:
show testtext "[foo]"
```

Note that using the variable directly is a lint error in both 7.4.3 and 7.3.5 (so **this** behavior isn't a regression, even if it's slightly odd)
`show testtext foo`

Note that in both above cases, the text does display properly when the game is run. So lint probably shouldn't be flagging these as errors.

2) Lint reports on Windows that open up in Notepad do not have proper line breaks in 7.4.3... all of the text shows up on a single line. This did not occur in 7.3.5.

This happens because the lint reports in 7.4.3 are being generated with only the line-feed character (LF), whereas in 7.3.5 it uses carrage-return plus line-feed (CR LF).

3) Renpy 7.4.3 seems to have a special character called `next`, as the code `next "Hello"` (where next was not defined as a character) is a lint error in 7.3.5 but not 7.4.3. However, attempting to run the game results in an error (`next() takes no keyword arguments`)

Attempting to use the statement by itself (`next`) is also an error (`excepted statement.`)

It seems like this wasn't intended to be used as a character in this manner, so lint should probably catch its misuse

**Comment by Gouvernathor** [comment]
`next` is either a renamed function defined in six.py or a built-in one (depending on python's version I guess).
In my case it's a built-in one, so I tried this
```rpy
label start:
    next "hello"
    print "hello"
    any "hello"
```
and Lint doesn't say a word about any of them (all three are built-in functions).
Maybe 7.3.5 detected functions (maybe built-ins only) being used as Characters, and it doesn't anymore ?

**Comment by bobcgames** [comment]
In 7.3.5, `next` and `any` are lint errors, but `print` is not

```
Could not evaluate 'next' in the who part of a say statement.
Perhaps you forgot to define a character?

Could not evaluate 'any' in the who part of a say statement.```

**Comment by renpytom** [comment]
Next became a builtin in Python 3, and Ren'Py is trying to emulate this. 

In general, Ren'Py is willing to accept any function as a character. The goal of lint is to check for things that are 100% errors, not things that could be correct. So when it sees a function, it's willing to let it slide and try it at runtime. I suspect any is similar, though I thought it had been in Python 2.7. 

I need to look into the other issues.

**Comment by bobcgames** [comment]
Thanks Tom; that makes sense
