### ISSUE TITLE
'NoneType' object has no attribute 'get_physical_size'

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#2688]
```
init python:
    def physical():
        w,h = renpy.get_physical_size()
        print w,h
    physical()
```
A question how can I get the physical size of the window? I am trying with `` renpy.get_physical_size()``, but it is giving me problems

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/window.rpy", line 1, in script
    init python:
  File "game/scripts/window.rpy", line 1, in script
    init python:
  File "game/scripts/window.rpy", line 5, in <module>
    print physical()
  File "game/scripts/window.rpy", line 3, in physical
    w,h = renpy.get_physical_size()
AttributeError: 'NoneType' object has no attribute 'get_physical_size'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/scripts/window.rpy", line 1, in script
    init python:
  File "game/scripts/window.rpy", line 1, in script
    init python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/window.rpy", line 5, in <module>
    print physical()
  File "game/scripts/window.rpy", line 3, in physical
    w,h = renpy.get_physical_size()
  File "renpy/exports.py", line 3240, in get_physical_size
    return renpy.display.draw.get_physical_size()
AttributeError: 'NoneType' object has no attribute 'get_physical_size'

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
Rosas de amor 0.1.5
Mon Feb 22 15:47:54 2021
```

**Comment by renpytom** [comment]
There is no window during the init python phase, so you can't get the size of it.

**Comment by Neyunse** [comment]
> There is no window during the init python phase, so you can't get the size of it.
does it work on a define or default?

**Comment by renpytom** [comment]
Unfortunately, no, or at least not reliably. This information only becomes available after the window has been displayed, which takes place when the window is being displayed. This happens during the first interaction. (Which varies a bit from platform to platform.) 

You can look at preferences.physical_size, which was the size of the window the last time it existed. It's None the first time the game starts (which means it will default to config.screen_width, config.screen_height). And there are a lot of things that can cause the game itself to change size. 

I think we're in an xy problem here - https://xyproblem.info/ . What are you actually trying to do?

**Comment by Neyunse** [comment]
I'm trying to get the images and screens to fit like this: https://cdn.discordapp.com/attachments/536270480932601859/813237914980057098/2021-02-21_23-36-02.mp4
I try to make the contents of the window fit the actual size of my window.
I don't know if there is any other way to do this.

**Comment by renpytom** [comment]
Ren'Py just does that automatically, unless I'm misunderstanding.

**Comment by Neyunse** [comment]
What I am trying to do is to adjust the scaling so that the black stripes are not visible.
ex:
![image](https://user-images.githubusercontent.com/36079551/108759579-4c5ae180-752b-11eb-8afe-70d842333696.png)

**Comment by renpytom** [comment]
Noted. That's somethign I plan to address soon-ish, but it's a hard problem.

**Comment by Neyunse** [comment]
Yes, I also realized how difficult it is, my idea was to put what I returned in an At with a size and see if it worked. But I ran into a lot of problems.
Thank you very much for replying Tom :D
