### ISSUE TITLE
Feature: Move gamedir calculation to renpy.py

### ISSUE THREAD

**Issue by fantesykikachu** [renpy/renpy#2689]
Moving the calculation of the gamedir, from boootstrap.py to the core renpy.py would give game developers more flexibility over their directories without modifying and potentially breaking the core bootstrapping code. This does add some complexity unless the basedir calculation is also moved or the ability to set basedir via an argument is removed in which case all use of basedir can be replaced with renpy_base.

**Comment by renpytom** [comment]
What do you think the benefit of this would be?

**Comment by fantesykikachu** [comment]
it would allow developers to name their gamedir something other than "game_name", game, data, or launcher/game. It would probably be fine with allowing gamedir to be taken as a launch argument, however this is a hassle when creating the executable for windows.
