### ISSUE TITLE
Android Setup JDK and JRE

### ISSUE THREAD

**Issue by QuantumCoder002** [renpy/renpy#2690]
Hey, I was looking recently on converting a pygame .py to an android apk, and from the many results that i found, renpy can do the work.
I have downloaded the Renpy GUI (exe), and i tried following [this](https://www.youtube.com/watch?v=ho8m8_CJpWM) tutorial on making android apps, but im stuck at the JDK and JRE download step :
I understand that it needs Java 8 , but i have to make an Oracle account for it, which needs personal informations such as adresses...
Also, i'm suspecting Oracle accounts to be used only for Oracle workers and might not be public

Now the question is can you give me a specific link to download the required JDK and JRE without having to make an account for it ?

**Comment by renpytom** [comment]
https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot is probably what you want. 

That being said, I wouldn't expect that tutorial to work anymore. Ren'Py and Pygame have diverged quite a bit at this point, and I only support packaging Ren'Py projects.

**Comment by QuantumCoder002** [comment]
Oh ok, thanks for your answer though
Now i want to be sure about something : can i package a pygame project using that Android section, i think i can because of the pygame snake in Ren'Py's logo, but i still need an answer from the creator ...

**Comment by renpytom** [comment]
No, you can't. Ren'Py's android support is intended for the use of Ren'Py games.

**Comment by QuantumCoder002** [comment]
Oh ok, thought i could use it for pygame, do you suggest any other methods to make a pygame apk

**Comment by renpytom** [comment]
I'd look into potentially look at https://kivy.org/doc/stable/guide/packaging-android.html , which used to work with pygame. I don't know if it still does.
