### ISSUE TITLE
Problem with accented letters

### ISSUE THREAD

**Issue by CavaleriOmar** [renpy/renpy#2693]
There is a way to write a VN and keep the display of the accents (I'm writing in italian), because despite having tried various solutions it continues to display the vowel without the accent and followed by a space.

I know python 3.4 should support UTF-8 encoding by default, but I don't know which one is using renpy.

**Comment by xavi-mat** [comment]
Probably there is a problem in the font you are using. Renpy displays special characters without problem. Try the default font "DejaVuSans.ttf" and see if the problem persists.

**Comment by CavaleriOmar** [comment]
It didn't depend on the fonts themselves ... but on the fact that it was a ".oft" file instead of ".ttf".

Without the font hint (in ".ttf") I wouldn't have noticed.

Thanks
