### ISSUE TITLE
Get duration of WEBM file or Movie displayable

### ISSUE THREAD

**Issue by Eliont** [renpy/renpy#2699]
Seen several get_duration functions in docs and code, but not a single helps with getting duration of video file in seconds.

Please, how to get it from valid video file inside Ren'Py script.

Thanks in advance.

**Comment by renpytom** [comment]
I'd suggest just determining it outside of Ren'Py, and then hardcoding it in. Ren'Py generally don't have ways of determining the lengths of things without loading them in, mostly because that encourages programming patterns that lead to very slow code.
