### ISSUE TITLE
improvements to Scroll action, new scrollbutton displayable?

### ISSUE THREAD

**Issue by midgethetree** [renpy/renpy#2702]
I've made a commit (midgethetree@bad8a85) which will cause the Scroll action to be insensitive when the given adjustment cannot be scrolled in the given direction. However this only really works if the associated displayable - presumably a kind of button - is modified to a) register itself with the adjustment so it'll be redrawn when the adjustment value changes and b) recheck the sensitivity of the Scroll action when rendered. As a bonus, this kind of displayable can be made to hide itself when the adjustment has no range, like scrollbars can. Here's an example code of what I mean:

`class ScrollButton(renpy.display.behavior.Button):

    def __init__(self, *args,**kwargs):
        super(ScrollButton, self).__init__(*args, **kwargs)
        self.hidden = False
        self.null = renpy.display.layout.Null()

        d = renpy.get_widget(None, self.action.id)

        if self.action.direction in [ 'increase', 'decrease' ]:
            self.adjustment = d.adjustment
        elif self.action.direction in [ 'horizontal increase', 'horizontal decrease' ]:
            self.adjustment = d.xadjustment
        elif self.action.direction in [ 'vertical increase', 'vertical decrease'] :
            self.adjustment = d.yadjustment

    def per_interact(self):

        self.focusable = self.adjustment.adjustable
        self.adjustment.register(self)

        super(ScrollButton, self).per_interact()

    def render(self, width, height, st, at):

        if self.adjustment.range <= 0:
            self.hidden = True
            return renpy.render(self.null, width, height, st, at)

        self.hidden = False

        if self.is_sensitive():
            self.clicked = self.action
        else:
            self.clicked = None

        if self.clicked is not None:
            self.set_style_prefix('' + 'idle_', True)
            self.focusable = True
        else:
            self.set_style_prefix('' + 'insensitive_', True)
            self.focusable = False

        return super(ScrollButton, self).render(width, height, st, at)

    def event(self, ev, x, y, st):

        if self.hidden:
            return None

        return super(ScrollButton, self).event(ev, x, y, st)`

I'm opening an issue on this because the commit isn't very useful without the displayable, and I thought it best to get feedback on the displayable and see if it would even be welcomed as an addition to Ren'Py. Perhaps it should be somehow combined with the existing Button displayable so all buttons will behave with these modifications IIF they have the Scroll action?

**Comment by renpytom** [comment]
This one sort of fell through the cracks, mostly because last year wasn't great for me. (This year has been great, but I've been catching up.) 

Are you still interested in this? 

I'm thinking it would make sense to have some way of having an action have its button register to be redrawn, and linking that with the scroll values.

**Comment by midgethetree** [comment]
Honestly this has been a low-priority thing for me as well, but I still think it's still worth working on and found some time today to look into your suggestion.

A register function on the Scroll action that passes the button to the adjustment's register function (also added get_delta and get_adjustment functions to Scroll to reduce duplicate code) removes the need to edit the button's per_interact function, and adding restart_interaction to the Adjustment class's change function before looking at its registered displayables removes the need for the button's render function to recheck the action's sensitivity.

I'm not sure if these are the sort of changes you had in mind? I've committed them to the branch I've been working on this stuff on: https://github.com/renpy/renpy/compare/master...midgethetree:renpy:improve-scroll-action.

With those edits the ScrollButton class from above can be simplified to:
```
class ScrollButton(renpy.display.behavior.Button):

    def __init__(self, *args, **kwargs):
        super(ScrollButton, self).__init__(*args, **kwargs)
        self.hidden = False
        self.null = renpy.display.layout.Null()

        self.action.register(self)
        self.adjustment = self.action.get_adjustment()

    def render(self, width, height, st, at):

        if self.adjustment.range <= 0:
            self.hidden = True
            return renpy.render(self.null, width, height, st, at)

        self.hidden = False

        return super(ScrollButton, self).render(width, height, st, at)

    def event(self, ev, x, y, st):

        if self.hidden:
            return None

        return super(ScrollButton, self).event(ev, x, y, st)
```

I was thinking it might also be nice to be able to register buttons to get updated with the adjustment's range so storing a reference to the adjustment in the button can be done away with completely, but my initial attempt isn't quite working yet (game menu scroll buttons aren't getting hidden when switching from one game menu to another with a smaller, unscrollable viewport).
