### ISSUE TITLE
Loading slot saved with different language skips transition

### ISSUE THREAD

**Issue by kostek00** [renpy/renpy#2711]
I have set transition after game load to "define config.after_load_transition = Fade(0.5, 0.0, 0.5)". However today I saw that this transiiton is skipped if I load save that has been saved in different language. For example I save my game into slot 1 in english language, then switch language to japanese and load save from slot 1 game skips this transition and instantly shows game from this save. However if I switch back to english and load from slot 1 game shows correctly transition.

This is example of my button to switch language:
`            button:
                action [Language('Japanese'), Return()]
                style 'menu_choice_button'
                text '{font=fonts/Adobe Heiti Std R.ttf}日本語{/font}' size 20 pos (250, 21) style 'lang_choice'`

**Comment by renpytom** [comment]
I don't consider this to be a bug in its own right - there are several behaviors that Ren'Py does when changing languages that it doesn't do otherwise. This also shouldn't happen in normal use, and doesn't affect playability.
