### ISSUE TITLE
Web problem.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2719]
I'm sorry, but an uncaught exception occurred. 
While running game code: File "game/web.rpy", line 363, in <module> File "game/web.rpy", line 243, in build_web File "game/web.rpy", line 199, in repack_for_progressive_download
 AttributeError: 'module' object has no attribute 'mktime' -- Full Traceback ------------------------------------------------------------ Full traceback: File "launcher/game/web.rpyc", line 363, in script File "renpy/ast.py", line 922, in execute renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store) File "renpy/python.py", line 2218, in py_exec_bytecode exec(bytecode, globals, locals) File "game/web.rpy", line 363, in <module> File "game/web.rpy", line 243, in build_web File "game/web.rpy", line 199, in repack_for_progressive_download

 AttributeError: 'module' object has no attribute 'mktime'

**Comment by Beuc** [comment]
This was reported to me by e-mail as well.

Windows builds appear to have lost [mktime](https://docs.python.org/2/library/time.html#time.mktime) in the built-in time module.
```
print(dir(time))

7.4.2
['__doc__', '__name__', '__package__', 'accept2dyear', 'altzone', 'asctime', 'clock', 'ctime', 'daylight', 'gmtime', 'localtime', 'mktime', 'sleep', 'strftime', 'strptime', 'struct_time', 'time', 'timezone', 'tzname']

7.4.3
['__doc__', '__name__', '__package__', 'accept2dyear', 'altzone', 'asctime', 'clock', 'ctime', 'daylight', 'gmtime', 'localtime', 'sleep', 'strftime', 'strptime', 'struct_time', 'time', 'timezone', 'tzname']
```

**Comment by renpytom** [comment]
That's... odd. I'll look into this later today to figure out why this is happening, and make a release in the next day or so. Thank you for investigating this.
