### ISSUE TITLE
Mouse tracking doesn't work if game window is resized

### ISSUE THREAD

**Issue by michael-conrad** [renpy/renpy#2722]
Ubuntu: 20.10
RenPy: 7.4.3.1414

Issue:

If I launch the game - windowed mode, mouse tracking works fine.

If I hit "maximize" - windowed mode, mouse tracking no longer works and is off by the maximized amount.

**Comment by renpytom** [comment]
It's working on 20.04. What sort of mouse tracking is this?

**Comment by michael-conrad** [comment]
When I launch the game, it works fine.

If I hit maximize, the mouse position is off for clicking on menu items and
other on screen controls.

The project is set to 1920x1080 if that makes a difference. I think it
starts off displaying at 1280x720.

**Comment by renpytom** [comment]
Can you post the log.txt file from a run in which you maximize the window?

**Comment by michael-conrad** [comment]
Just discovered additional condition.

Happens specifically when I hit "reload" key combo when maximized.

Like maybe a reinit on resize might need to be rerun on reload?

[log.txt](https://github.com/renpy/renpy/files/6136016/log.txt)

**Comment by renpytom** [comment]
I just fixed this, so the fix will be in the next nightly and 7.4.4.
