### ISSUE TITLE
Live2D: Read the artmesh blend mode from the model

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#2723]
This is about the thing called Artmesh https://docs.live2d.com/cubism-editor-manual/concept-of-artmesh/?locale=en_us

This is how it looks like in Cubism viewer.

https://user-images.githubusercontent.com/27142420/111055868-b4de1400-8482-11eb-91e9-a588130b2180.mp4

Ren'Py just ignore it and always use normal mode.

https://user-images.githubusercontent.com/27142420/111055869-b60f4100-8482-11eb-8cbb-2100f3d5e29d.mp4

Project with this model [test_l2d_blend_mode.zip](https://github.com/renpy/renpy/files/6135999/test_l2d_blend_mode.zip)

**Comment by Parasitius** [comment]
join the request. The renderer does not read the blending modes of the art meshes from model. This feature is very useful for creating light and shadow effects.

**Comment by renpytom** [comment]
This will probably come in after 7.4.4, which needs to get out ASAP. I'm not opposed to this, though I need to see how well Ren'Py can support this. It's probably just changing the GL blend function, which should be doable.

**Comment by Parasitius** [comment]
Thanks for the answer. Of course. I'll wait. Contact me if you need test models for any aspect related to Cubism. I am ready to help. You still have many unrealized l2d functions ahead and I will gladly help you with my modest skills, if it is useful to you.

**Comment by renpytom** [comment]
It would up easier to do than I thought, so it'll be in 7.4.4. 

Please let me know what's missing - there isn't a central place for Live2D features, that I know of, so it's a bit hard to even know what Ren'Py doesn't have.

**Comment by Parasitius** [comment]
Oh... Quick list is:
Mouse events in l2d (hitboxes and cursor position tracking)
Poses. (Sets of part visibility)
And main feature what i waiting - working physic in l2d model. This is most interesting thing in l2d. Maybe some guys know more features from cubism, but i use only this missed for now in Renpy options.
