### ISSUE TITLE
[7.4.x] Renpy and Renpy games closes when it is captured in OBS

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#2724]
I encountered this error in 7.4, renpy closes when capturing with OBS.
Video: https://drive.google.com/file/d/1WTI10L5uMpDN09QCHAqF2KBvMX_xAe31/view

**Comment by renpytom** [comment]
Can you try the 7.4.4 prerelease, and post your log.txt?

**Comment by Neyunse** [comment]
It still happens in 7.4.4
[RenPy-log.txt](https://github.com/renpy/renpy/files/6138510/RenPy-log.txt)
[RosesOfLove-log.txt](https://github.com/renpy/renpy/files/6138514/RosesOfLove-log.txt)

**Comment by renpytom** [comment]
Can you please update your Nvidia drivers? It looks like you're on 461.09, while the current version is 461.72.

**Comment by Neyunse** [comment]
Continues to close
[RosesOfLove-log.txt](https://github.com/renpy/renpy/files/6138642/RosesOfLove-log.txt)
[Renpy-log.txt](https://github.com/renpy/renpy/files/6138645/Renpy-log.txt)

**Comment by renpytom** [comment]
I'm not sure what to say. Does it work fine without OBS?

**Comment by Neyunse** [comment]
Yes, without capturing it with OBS it works.

**Comment by renpytom** [comment]
I'll see if I can re-create this, but you may need to change your OBS settings, if they cause Ren'Py to break.

**Comment by Neyunse** [comment]
I understand I will try several configurations, I also tested with mirillis action and it also closes.

**Comment by mavyxdawn** [comment]
Hi! A temporary workaround is to record the screen instead of the window. Mine works correctly using OBS.
Versions: 26.1.0 (64-bit)
Ren'Py: 7.4.4.1439

This video was recorded with OBS: https://www.youtube.com/watch?v=4O3uqLpvnKE&t=6s
