### ISSUE TITLE
String interpolation !c capitalization first letter issue

### ISSUE THREAD

**Issue by Tristimdorion** [renpy/renpy#2726]
When using with an interpolation string that uses tags, it does not uppercase the first printed character.

Looking in the codebase it uses something like:

str[0].upper() + str[1:]

But when the interpolation variable is like: 

myvar = "{color=#ff0000}my red text{/color}"

Using the following say command:
p "[myvar!c] looks pretty cool."

Is printed as:
p "my red text looks pretty cool."

Instead of:

p "My red text looks pretty cool."

**Comment by renpytom** [comment]
I don't consider this a bug in Ren'Py.

**Comment by Tristimdorion** [comment]
Why not? It is in the 'renpy/substitutions.py' line 209. A simple regex that ignores the non-printable part (the text between all {} tags) and then uppercase the first printable character should solve the problem.

**Comment by Tristimdorion** [comment]
You only need:
rc_strip_tags = re.compile(r"[\w]+(?![^{]*})", re.IGNORECASE)

And replace the conversion block with:
        if "c" in conversion and value:
            idx = rc_strip_tags.search(value).start(0)
            value = value[:idx] + value[idx].upper() + value[idx+1:]

**Comment by renpytom** [comment]
I don't believe the substitution code should be processing text tags like that. (For one thing, because !cq is a possible thing it can do.)
