### ISSUE TITLE
[7.4.3] Live2D models are broken

### ISSUE THREAD

**Issue by DipeshAggarwal** [renpy/renpy#2727]
Live2D version: 4.0.07

Works perfectly in v7.4.2 but breaks completely in 7.4.3 and 7.4.4.

Attaching a screenshot of how it looks in 7.4.3

![Screenshot 2021-03-16 193538](https://user-images.githubusercontent.com/1311129/111322323-d1e73280-868e-11eb-8906-117be78c217f.png)

**Comment by renpytom** [comment]
Can you try the nightly? I believe it should have a fix.

**Comment by DipeshAggarwal** [comment]
Fixed in the latest nightly.
