### ISSUE TITLE
AVI not playing

### ISSUE THREAD

**Issue by josh314151** [renpy/renpy#2728]
I'm adding a video using:
```python
image bandit battle = Movie(play='bandit_battle.avi', pos=(0,0), anchor=(0,0))
show bandit battle
```
and the video doesn't show at all but if I just change avi to webm and convert the video it works fine. This is on Ren'Py version 7.4.2.1292 on windows

**Comment by renpytom** [comment]
What video and audio codecs does the .avi use?

**Comment by josh314151** [comment]
No audio and video was made by combining a series of images together using opencv (it supports several codecs but I'm not sure what the default for avi is).

Code I'm using to create the videos is as follows:
```
import cv2
import os

image_folder = 'path_to_folder'
video_name = 'video.avi'

images = [img for img in os.listdir(image_folder) if img.endswith(".png")]
frame = cv2.imread(os.path.join(image_folder, images[0]))
height, width, layers = frame.shape

video = cv2.VideoWriter(video_name, 0, 15, (width, height))

for image in images:
    video.write(cv2.imread(is.path.join(image_folder, image)))

cv2.destroyAllWindows()
video.release()
```

**Comment by renpytom** [comment]
Chances are, it's not a codec Ren'Py supports. I think you found the fix, so I don't think this is a bug.
