### ISSUE TITLE
If the user uses an oversized cursor, cursor becomes invisible when going "FullScreen".

### ISSUE THREAD

**Issue by WingFoxie** [renpy/renpy#2729]
**How to reproduce the bug:**

1. In Windows, go to Settings -> Ease of Access -> Mouse pointer. Then set a larger pointer size.
2. Open any Renpy game, go to its settings.
3. As soon as you set the game to run at "FullScreen", the cursor becomes invisible, until you set the game to run "Windowed" again.

Basically every single Renpy game has this problem now. So it must come from the Renpy engine.

**Temporary walkaround:** 

Maximize the Windows instead of going full screen, so the cursor will still be visible.

**Extra Info:**

The Windows pointer size setting allows user to use a cursor with a size up to 256x256.
I personally used even larger cursors, 1024x1024, daily-drived, seriously. It seems that as long as an app works with 256x256 cursors, it works with even larger ones. (Did remember there was one example in which 256x256 works, but not above?? Can't recall which one.)

I didn't report this problem right away, it's been there for quite a few years. (>3 years maybe?) Didn't report because I don't think anyone else in the world cares about this. But at least now I can tell you **the bug does not come with a recent version of Renpy. Instead, it's been existing for a long time.**

**Comment by renpytom** [comment]
I'm unable to repeat this, under windows 10 with a cursor size of 15, which is the maximum the interface supports. If this happens in The Question, it's an OS issue, as that game doesn't change the mouse cursor. (I suspect it's an OS issue, and best taken up with Microsoft.)

**Comment by WingFoxie** [comment]
> 
> 
> I'm unable to repeat this, under windows 10 with a cursor size of 15, which is the maximum the interface supports. If this happens in The Question, it's an OS issue, as that game doesn't change the mouse cursor. (I suspect it's an OS issue, and best taken up with Microsoft.)

Ahh, my bad. Should have tested right before posting.
So the actual "problem" is, **the bug only happens with a "larger than 256x256" cursor!**, e.g. 257x257 and above.
In my main post I mentioned this: 

> (Did remember there was one example in which 256x256 works, but not above?? Can't recall which one.)

Now I remember, it's Renpy! 
So that's why I didn't report it ~3 years ago? Because it's sort of invalid for a bug report. Had to go beyond Windows setting's reach to trigger that bug.

**If you want to reproduce this "Bug" you need to do this:**
1. Better change the cursor size to 15 first. Otherwise the upscaled cursor will be too hard to use. And I suggest you also set the cursor color to "inverted" (the third option), so it's easier to use.
2. Edit registry. Go to "HKEY_CURRENT_USER\Control Panel\Cursors\CursorBaseSize" change the "CursorBaseSize" value to something larger than 256 (try 257, maybe don't try 1024 like I did, because the upscaled cursors will be very hard to use)
3. Reboot. (There must be a way to apply settings without reboot, but I don't know how.)
4. Now you should be able to reproduce the problem, as long as you go full screen, cursor disappears.

Note: To revert changes after you've done testing. Just go to that cursor size settings again, just drag the bar to the far left (If is already at far left, drag it to the right, and then back to left.). And the cursor setting will be back to default.

**Since I already created a new issue anyway, let me try to convince you to fix this bug:**

1. **It only happens with Renpy.** You can try with that 257 CursorBaseSize, and **see if any other app has the same "cursor disappearing" problem**, I couldn't find any. 
And **even with Renpy it works in windowed mode, only don't work when it's full screen.** So there must be something wrong with Renpy.
2. You see, to use large cursor, there's the Windows cursor size setting, and there's the "CursorBaseSize" registry entry. 
But there two things doesn't come at the same time! Back then when the cursor size setting was implemented, the "CursorBaseSize" registry entry isn't there at all! The "CursorBaseSize" registry entry appeared way later (Like 1 year later or so). So before that, 256x256 really was the limit, and you could not use cursors larger than that.
**Maybe back then when Renpy developers react to the Windows cursor size changes, they realized the 256x256 is a hard limit, and didn't program Renpy to completely work with even larger cursors?** (Because later on the "CursorBaseSize" registry option makes it **not a hard limit anymore**.)

Since there are quite a lot of great great Renpy games out there, this incompatibility is like a **timed bomb**. Later when Windows finally decide to support even larger cursors, suddenly all of Renpy games will have issues exposed. **Some of them already ended support long long ago. So they won't fix the problem by just updating their game with the latest Renpy engine.** It could be a mess. So better fix this "bug" before it becomes an actual problem?

**Comment by renpytom** [comment]
I can't find any documentation for CursorBaseSize on Microsoft's website. Can you point to any location where it's documented, and where values greater than 256 are allowed?

**Comment by WingFoxie** [comment]
Ehh there's probably no documentation for that at all. I can write one for you if you want to. Haha. But it won't really help with the bug.

BTW I tried to look at Renpy's source code and find what goes wrong. Tried a few hours with no luck. 

The only thing that's a bit suspicious to me is that...
**in renpy-master\module\include\sdl2.pxd ,line 1552:**
`SDL_Cursor *SDL_CreateCursor(const Uint8 *data, const Uint8 *mask, int w, int h, int hot_x, int hot_y)`
Well Uint8 looks like something that doesn't support values over 256, but that alone might not be the issue.

There's more.
When I go fullscreen, I noticed that the screen (or interface, or viewport, whatever) turns black for a fraction of a second. And then the cursor is invisible. If I don't exit fullscreen but alt-tab to another app, cursor is visible again. If I click on the Renpy app, switch to it again, the screen will flash black again and cursor is invisible again.

I tried to trace the code corresponding to this, but couldn't quite find it.

What I tried:
The click changes a variable called `"toggle_fullscreen"`, and some code makes sure (probably keeps checking) that another variable called `"renpy.game.preferences.fullscreen"` has the same value.  
Then some code in core.py monitors the change of the `"renpy.game.preferences.fullscreen"` value, and call a function called `"renpy.display.draw.resize()"` if the value has changed. 
But what next? Search the keyword `"renpy.display.draw.resize"` doesn't bring me anywhere else.

Then I tried to find codes which both cursor size and fullscreen are involved. But it's not easy to find this just by searching keywords. All I can find is this.
In "core.py", line2814, there's a function called `"update_mouse(self)"`. In which there's line 2822: `"visible = visible and self.show_mouse and not (renpy.display.video.fullscreen)"`
then the mouse cursor will be hidden if `"visible = False"`.
But this also doesn't seem to be where the problem is.

Then I realized the developers used word "mouse" for "cursor", so I searched the keyword "mouse" as well, still no luck.


**Can you give me some hints?** Which part of the source code is for this "full screen, flashing black" refresing thing? The thing that happens either when I go to full screen, or re-focus on the already full-screened Renpy app?

**Comment by renpytom** [comment]
I'm going to close this, unless there's a way of changing the cursor size to 257 through the interface, or at least through a registry key that Microsoft documents.
