### ISSUE TITLE
Latest release from 18 March just breaks my game

### ISSUE THREAD

**Issue by Bobyteal** [renpy/renpy#2733]
Transitions don't play, and it returns to the menu instead of continuing. The list will be too long, but I'm reverting for now, not sure why but this release is a no go.

**Comment by renpytom** [comment]
I'm closing this. If you can supply an example of the errors, I'd be happy to take a look, but "just breaks my game" isn't an actionable bug report.

**Comment by Bobyteal** [comment]
As I said transitions don't play, things for 7.4.1, past that point transitions don't play, screens don't show up and get skipped etc. List is too long but this should be easy to track given how big the problem is. I don't have any errors per say, just transitions and a bunch of code stopped working altogether, let me know what I could provide that I could help tracking the issues.

**Comment by renpytom** [comment]
I'dd need the latest version of

**Comment by renpytom** [comment]
I'd need at least a link to the game, something like that. My guess is it's likely a single use of something undocumented with wide repercussions, but I'd need to see it.

**Comment by Bobyteal** [comment]
You must be correct, I don't have the knowledge to know exactly what went wrong. But all the screens transitions I had stopped working and it goes back to the menu screen suddenly at one point, whereas in 7.4.1 I would be able to continue through the game. The game is in development and there exist no published version yet, but if there is something that can do let me know

**Comment by renpytom** [comment]
If you could email me a link to the development version, including full source code, I'd appreciate it. Again, without being able to see the errors, it's very hard to figure out what could be wrong.

**Comment by Bobyteal** [comment]
I totally understand, and I will apply. Thank you for the investigation, keep in mind this is a commercial project, so it must not leak at all costs, but I'm sure you know how to handle that. At which email I could send the ongoing project

**Comment by renpytom** [comment]
My email is pytom@bishoujo.us.

**Comment by Bobyteal** [comment]
Currently uploading

**Comment by Bobyteal** [comment]
Sent email.

**Comment by renpytom** [comment]
Do you have a more specific example of the problems? I'm not seeing an obvious skipped transition, but I don't know where to look.

**Comment by Bobyteal** [comment]
It appears only when skipping apparently, I have a tendency to always skip to test if things are working, the new github issue opened is a better representation of the problem as this actually seems to be a problem with calling screen while skipping, it made me realise. The transitions that I was using, were all calling screens that had the transitions inside them. 
Hope it helps

**Comment by Bobyteal** [comment]
I have tested 7.4.2, and the issue was not present there, the issue seems to appear from 7.4.3 onwards.
Open game in 7.4.2, open game in 7.4.3+
Start a new game, there should be a fade to black playing on the 7.4.2, and on the 7.4.3+ it will just display a black screen instantly. The second transition that is explained in the email (the lady with the clock), will also have different behaviour in 7.4.1, it will lock you from activating skip during the transition by pressing control. In 7.4.3+ you will be able to press control (skip), you will the button sound activating. Something is not properly being enforced as it should, on the second transition it's more random but I had a moment where it partially skipped it and sometimes it did play all the way, however, the buttons were never locked properly compared to 7.4.2.

On the second look, the first transition is skipped regardless of using skip or not though, same for the second the issue isn't tied to skipping only. 
But it does make you return to the main screen only if you are in skipping mode as soon as it will want to call a screen to enter point and click mode, again this behaviour is not existing in 7.4.2, the game will continue normally.

**Comment by renpytom** [comment]
Can you try the latest nightly, to see if it's fixed?

**Comment by Bobyteal** [comment]
I have to go out, but I tried it very quickly this morning, so this fixed a couple of issues the transition with the lady and the return to main menu screen were fixed. However the first transition has still a problem, the fade to black, it's not a big deal in itself but it shows that something is still not 1:1. And as I was able to continue past the moment where it returned to main menu screen before, I noticed a couple of new issues as well on the game part that was unreachable until then. 
Again things that seem related to modal screen not being enforced I would say but it's hard to be sure, I'll look at it again tonight.

**Comment by Bobyteal** [comment]
I'm sorry to report again but while it improved, there is things that are still broken compared to 7.4.3, transition doesn't play the same, they skip. If you launch the project I sent to you, in both versions, it's not the same. And 7.4.2 got lot of false reports regarding ren'py x32, anything I can do to get rid of false reports? I would like to stay on 7.4.2 until 7.4.3+ got some improvements. Anyway good luck, good day man.

**Comment by Bobyteal** [comment]
define build.include_i686 = False 
found it 

Well for me I can stay forever on 7.4.2, I just wish there was a solution that could be done for older versions to fix the antivirus false positive for x32 bits version, but outside of this it's really the best version. Maybe the problems I encountered are not a very common and bad practice, but that's really a shame for me to not be able to be 1:1 with 7.4.3+ but maybe in the future, with time it will come to parity. Thank you again, and best of luck with this awesome engine
