### ISSUE TITLE
[7.4.3 onwards] "Call"ed screens skipping issue

### ISSUE THREAD

**Issue by solarProtag** [renpy/renpy#2736]
Hello there! I've noticed an issue with screens and calling them ever since the 7.4.3 update, and have had to stay at 7.4.2 because of it while working on my project.

The issue lies with screens I've called into my game with call, like so:
`call screen screenname`
can be skipped through like seen dialogue - with both holding ctrl and with the skip button in the quick menu - which then shoots you out to the main menu screen.

This has been a big problem since all these screens I'm calling are for user interactions such as point-and-click adventure-type screens, and before 7.4.3, even if you've seen the text preceding it before, or you select "skip seen text" in the options menu, it would stay on the screen until the user gave some sort of input. (I also have my screens set to modal = True for reference).

I hope this gets fixed soon, since this will affect other point and click making devs like myself.
Thank you!

**Comment by TheArcadean** [comment]
Having the same issue myself - having "skip" on, using CTRL, TAB or via the quick menu skip button is causing the game to try to "skip" through scenes, although in my case it's taking users into "label"ed scenes instead of the main menu, which is causing events to happen out of order (and overlay them on top of the screen).

**Comment by renpytom** [comment]
Can someone put together a replication of this. It doesn't occur with:

```
define _confirm_quit = False

define e = Character("Eileen", image="eileen")
define l = Character("Lucy", image="lucy")
define a = Character("Augustina", image="augustina")

label main_menu:
    return


screen test():
    modal True
    textbutton "Test" action Return(True)
    

label start:

    scene bg washington

    "A"
    call screen test
    "B"


    jump start

```

Which makes me think there's something else at work here.

**Comment by solarProtag** [comment]
After playing around with the above code and adding bits from my own project to it I think the issue might be related to screens that are "shown" instead of "called" not being immune to skipping when modal is True.

For example:

```
screen testy:
    modal True
    textbutton "Test" action Return(True)

label start:
    
    scene bg washington

    "A"
    show screen test  # before 7.4.3 even if skipping was on, the modal True above would keep you here
    pause                   # but after 7.4.3 skipping ignores the modal True, making you skip ahead
    "B"

```

I realized this because for some of my screens I've been using
`$renpy.show_screen()`
because I wanted to use variables to lessen the amount of lines I'd have to write to call my screens over and over, and call screen doesn't allow for what I wanted it to do. (If such a method exists with call already, god help me I'll take it)

7.4.3 might have accidentally given skipping an exception when it comes to the modal variable, so that could also be the cause of TheArcadean's issues as well.

Thanks!

**Comment by Bobyteal** [comment]
This is the same issue I have in my project with 7.4.3+, so we could merge the problems

**Comment by solarProtag** [comment]
Not me realizing that I could've been doing $renpy.call_screen this whole time OTL.

Still though, I tested everything related to showing and calling screens, and it definitely seems like the modal variable isn't working properly after 7.4.3.

**Comment by renpytom** [comment]
I'm not sure this is modal not working - a pause is supposed to take priority over a shown screen, as things like click go on top. This was a bug fix, but it looks like a number of games are dependent on the bug. 

Let me see if I can figure out some  sort of compaitibility mode so that you don't have to make major changes.

**Comment by renpytom** [comment]
Can someone look at the latest nightly to see if this is fixed?

**Comment by solarProtag** [comment]
Just tested it, and it looks like that worked!

**Comment by renpytom** [comment]
I'm closing this issue, then. Thank you!
