### ISSUE TITLE
build: Including single file from directory fails non-obviously

### ISSUE THREAD

**Issue by mal** [renpy/renpy#2737]
```py
build.classify('game/dir/file.special', 'all')
build.classify('game/dir/**', None)
```

Does not behave as expected because `'game/dir/**', None` matches `game/dir/` as it is walked and before descending the tree, so `game/dir/file.special` is never reached or evaluated despite it's classification rule coming first and so expecting to take precedence.

Propose that the `*` and `**` wildcards should require at least one character. Entire directories may still be excluded via explicit exclusion of `'game/dir/'`.

An alternative option would be to not attempt to match directory names at all, always walking the full tree and evaluating files names only.

**Comment by renpytom** [comment]
Yep. Made the change.
