### ISSUE TITLE
[bug] Persistent field does not update for transform

### ISSUE THREAD

**Issue by fk1995** [renpy/renpy#2738]
buggy demo:
https://mega.nz/file/eFtw0LDI#YBIDmEu-0ym9D9SC9hzu_DciRdzGmInNn5mRiR3V6cQ

The textbox image's alpha value is not correctly updated with the persistent field unless the game restarts.

**Comment by renpytom** [comment]
The issue is that you used:

```
define persistent.window_alpha = 0.5
```

Instead of:

```
default persistent.window_alpha = 0.5
```

**Comment by fk1995** [comment]
> The issue is that you used:
> 
> ```
> define persistent.window_alpha = 0.5
> ```
> 
> Instead of:
> 
> ```
> default persistent.window_alpha = 0.5
> ```

Can you explain the difference between these two lines of code? Thanks

**Comment by renpytom** [comment]
The relevant difference is that define marks a variable or field as read-only. That means that Ren'Py can optimize screens by assuming it can't change.

**Comment by renpytom** [comment]
4ebf1d0df8478c57e1ce9d102d36bd4be86d1cce will prevent this from being an error, since I believe older documentation might recommend define in this case.
