### ISSUE TITLE
renpy.windows not working according to documentation

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#2739]
Hey!

First I want to say that Ren'py is an incredible tool because it makes creating a Visual Novel so easy, yet allows for more advanced users to take advantage of the Python language.

I found a little issue in the documentation of this function
![image](https://user-images.githubusercontent.com/4298411/112666869-61cd6f00-8e3b-11eb-8205-365311d6c1c3.png)
Source: https://www.renpy.org/doc/html/other.html#var-renpy.windows

But when I run this script in my game:
![image](https://user-images.githubusercontent.com/4298411/112666944-7873c600-8e3b-11eb-93c1-2d6e862d2d6b.png)

I get this result:
![image](https://user-images.githubusercontent.com/4298411/112666993-83c6f180-8e3b-11eb-8753-2f0c61447ec1.png)

which is not a False or True as I expected. Also, I don't know how to use this returned value.

**Comment by renpytom** [comment]
It's a phrasing thing - Python separates True/False from something being true and something being false. So 2 is true, but it's not True. 

In any case, you can just use renpy.windows as a true/false value:

```
if renpy.windows:
    "You're on windows."
else:
    "Not on windows."
```

You could also do:

```
define on_windows = bool(renpy.windows)
```

That being said, I should probably clarify the documentation here.

**Comment by renpytom** [comment]
If you don't mind, I'd like to leave this open until I can fix the documentation.

**Comment by SergioAlonsoJr** [comment]
Thanks. Your solution worked.
