### ISSUE TITLE
[7.4.4] L2d motions are not starting

### ISSUE THREAD

**Issue by Archy812** [renpy/renpy#2742]
Hi! I didn't find the cause of the problem but in some cases on version 7.4.4 L2D animations are not started until external manipulations such as code reload. 
Video of the bug:
https://monosnap.com/file/W4QA3ZiIjhZoqUdZbgl3KakrBag1wY

Note that I passed "say" line and only after the next reload animation is started. L2D image with motions is placed on the screen on a separate layer

Same script on version 7.4.3 is working as intended:
https://monosnap.com/file/jpvLo030LEL3Vwu7y6veK9EDw6Cs6T

I made a simple script and it works differently on 7.4.3 and 7.4.4:
```
init -100 python:
    config.gl2 = True

init:
    if renpy.has_live2d():
        image location home_01_base = Live2D("home_l2d", loop=True, seamless=True)
    else:
        image location home_01_base idle = Null()

label start:
    show location home_01_base idle

    "sdf"

    jump start
```
If I set `show location home_01_base still idle`, then it works in 7.4.4 too, after a short pause of the `still`, of course. 

I may assume some problems with the l2d model so this is the model used in the tests [home_l2d.zip](https://github.com/renpy/renpy/files/6218476/home_l2d.zip). But as I have similar behaviour with other our models and only in 7.4.4, I think there is some problem.

**Comment by renpytom** [comment]
Fixed by a5920b2200d0eca586817a5a0c4e591786db9abb and cee512ea618e6f5b1c8376ac2d125a1919a02f0a.
