### ISSUE TITLE
Korean translation of tutorial is not perfect.

### ISSUE THREAD

**Issue by CodePsy-2001** [renpy/renpy#2748]
Korean translation is not perfect, and sometimes words that are too far from our daily life are used. I want to improve the translation. Is there any precautions I should be aware of for this? For example, is it right for me to make a hasty decision on the translation of a particular programming word?

**Comment by renpytom** [comment]
I don't have any experience with Korean, so I'm limited here. @lee-yunseok , can you comment?

**Comment by CodePsy-2001** [comment]
And, http://baekansi.dothome.co.kr/doc/html/index.html Here is the Korean version of renpy documentation (but slightly not recent). Why don't you link this document to the official manual page?

**Comment by CodePsy-2001** [comment]
@lee-yunseok

**Comment by renpytom** [comment]
I'm going to close this now. I don't want to link an out of date version of the documentation, but I'd link one kept up to date.
