### ISSUE TITLE
Memory bloat with old cache files

### ISSUE THREAD

**Issue by Phalzyr** [renpy/renpy#2750]
Just thought I would mention this...

Granted most people prob won't be doing/encounter this, but I tend to copy one game to another and use that as template, delete all images etc, change options and gui as needed then rebuild... I don't recall ever having a problem with this untl 7.4 (now using 7.4.4). The "cache" directory under "game" seems to be causing an issue and I have to manually delete it to start a fresh instance otherwise I get major memory usage bloat. before deleting said cache dir, I got over 2GB of memory used at startup of a game that has less than 100MB of files... After deleting said directory it goes back to the normal around 400Mbish.

I thought the older versions didn't copy the cache files to a build just like it ignores saves?

**Comment by renpytom** [comment]
Can you look at the size of the files in cache? I have no idea what it's keeping. The cache files should prune themselves each time they're updated.

**Comment by Phalzyr** [comment]
That is what I was thinking that they should be pruning themselves, The file size is about the same as the newly created ones that just had the game open once, I can open the previous game with its file and get normal memory usage, it was complete surprise when users started saying hey it is loading with 2GB memory usage. Let me see if I can recreate it easily...

**Comment by renpytom** [comment]
Okay. I'll close this for now, feel free to re-open it if the issue repeats.
