### ISSUE TITLE
The "modal" flag for Frames does not prevent event propagation in case of erratic mouse movements

### ISSUE THREAD

**Issue by evitegames** [renpy/renpy#2751]
The new "modal" flag only prevents event propagation if the mouse is moved slowly. In case of fast and erratic movements, the behaviour does not seem to work as expected.

The issue persists on both the latest stable and nightly builds. 

Expected behavior: The modal flag should prevent the whole Frame from propagating events even with fast mouse movements. 

The issue is reproducable with the following screen:

```
screen chaptersummary():
    tag chapter_summary
    modal True
    
    add "chapter_summary_background"

    imagebutton: 
        focus_mask True
        idle "mal_norm"
        hover "mal_selected"
        action Return()

    imagebutton: 
        focus_mask True
        idle "jaye_norm"
        hover "jaye_selected"
        action Return()

    frame:
        modal True
        xsize 1540
        ysize 168
        xalign 0.5
        ypos 762
        background "chapter_summary_text_background"
```

Make sure to call it from script as `call screen chaptersummary with dissolve`

I've attached the necessary image resources to this ticket as well. 
[ChapterSummary.zip](https://github.com/renpy/renpy/files/6253045/ChapterSummary.zip)

**Comment by renpytom** [comment]
This isn't actually a bug in Ren'Py. 

What's happening is that the lower frame (the modal one) is 168 pixels high, but the background image is 293 pixels high - too big for it. When the mouse is inside those top 168 pixels, the window is modal. Below that, the image is never modal. My guess is when moving the mouse slowly, you naturally stay above the 168 pixel mark.

**Comment by evitegames** [comment]
Oh crap. You are absolutely right. I typed in the wrong value from the design handover tool.

I'm so sorry to drag you along for the ride Tom.
