### ISSUE TITLE
Exception "closes a text tag that isn't open", when it is.

### ISSUE THREAD

**Issue by silvialaurentino** [renpy/renpy#2752]
Hello, Tom! I hope you're doing well with your hard work.

Today, I was caught with this exception:
![image](https://user-images.githubusercontent.com/28473494/113485621-ebf18500-9484-11eb-9dbb-cf3e4143d78d.png)
I know the solution is to simply erase the close clause, but this exception makes me question my sanity, considering the text tag _is_ open... Right? Hehe

See ya!

**Comment by renpytom** [comment]
No, because {p} doesn't take a close tag.

**Comment by silvialaurentino** [comment]
I know it doesn't, but the way it is written makes it look like there is no tag in the first place, you know?

**Comment by renpytom** [comment]
Sure. I added a check.
