### ISSUE TITLE
Android skip crash on some event

### ISSUE THREAD

**Issue by AshyraStudio** [renpy/renpy#2758]
Some event don't work properly when skipping on Android version.
It look like the process is to speedy, nor conflict with other process on some occasion, even more, the game sent back to the main menu, as if there is a "security" system.

**Comment by renpytom** [comment]
Can you provide the apk, the files needed to build it, and the logcat data? I'd like to try it on my phones to see if I can repeat it here.

**Comment by renpytom** [comment]
Closing for now. Please re-open this if you can repeat it with Ren'Py 7.4.5.
