### ISSUE TITLE
ATL animation within layeredimage "resets" on attribute change

### ISSUE THREAD

**Issue by mal** [renpy/renpy#2760]
In the example below the expected/desired behaviour would be for `foo` to loop in the background while the `sally` attribute controls adding and removing the `girl` placeholder image between dialogue lines.

What currently happens is that each time the `sally` attribute is added or removed, the `foo` animation restarts.

```rpy
label main_menu:
    $ _confirm_quit = False
    return

image foo:
    '#f777' with dissolve
    .5
    '#7f77' with dissolve
    .5
    '#77f7' with dissolve
    .5
    repeat

layeredimage bar:
    attribute foo default 'foo'
    attribute sally Placeholder('girl')

define qux = Character('Qux', image='bar')

label start:
    scene
    show bar
    qux sally 'Hi!'
    qux -sally 'Each time I change an attribute ...'
    qux sally '... my animation resets.'
    qux -sally ':('
    show bar sally
    pause
    return
```

**Comment by renpytom** [comment]
I don't think this is a bug. You might be able to get this to work if you use the animation timebase on image foo:

```
image foo:
   animation
    '#f777' with dissolve
    .5
    '#7f77' with dissolve
    .5
    '#77f7' with dissolve
    .5
    repeat
```

But fundamentally, a layeredimage is intended to be something like an image loaded from disk, and so transform state doesn't propagate within it.

**Comment by mal** [comment]
Ahh, unfortunately while `animation` keyword definitely has an impact, it's not what I'd expect from using the tag's timebase - the animation flickers erratically on each click instead. I'm not sure if that's expected but given the tag isn't being hidden and reshown, I'd have expected it to pick up where it left off. :/

Is it possible that transform state being propagated in LIs would be considered in future?

**Comment by renpytom** [comment]
No, I don't think this is what layeredimages are for.
