### ISSUE TITLE
im.FactorScale and Transform() w/ zoom produce different results

### ISSUE THREAD

**Issue by omega-fallon** [renpy/renpy#2764]
From what I've seen in the documentation, the "zoom" property is meant to be the replacement for im.FactorScale(). However, using zoom with Transform() not only produces different results, but worse ones.

To verify this I set up an example with two variations on the same sprite. Both scale by 0.2 and use bilinear scaling. Additionally, I have gl2 enabled in configs. They should, by all means, be synonymous:
`image scarlet norm = Transform("Characters/Scarlet/AA_Scarlet_p1_01.png", nearest=False, zoom=0.2)`
`image scarlet norm = im.FactorScale("Characters/Scarlet/AA_Scarlet_p1_01.png", 0.2, bilinear=True)`

This isn't the case, though. Here's the two side by side, Transform on the left and FactorScale on the right.

![screenshot0278](https://user-images.githubusercontent.com/36779526/114461768-214a5100-9bb0-11eb-8aec-89326798b530.png)

The Transform version is noticeably more jagged and pixelated, while the FactorScale version is smoother.

**Comment by renpytom** [comment]
```
define config.gl2 = True
```

This is what mipmaps are meant to fix. At the same time, scaling down pas 0.5 is always going to have at least some problems, when done in one step like Transform does.

**Comment by omega-fallon** [comment]
> ```
> define config.gl2 = True
> ```
> 
> This is what mipmaps are meant to fix. At the same time, scaling down pas 0.5 is always going to have at least some problems, when done in one step like Transform does.

Yes, gl2 is enabled. Both of these functions scale in one step, by the same amount, using bilinear scaling. There is no reason for them to be so different.

**Comment by renpytom** [comment]
Can you post the file, please?

**Comment by omega-fallon** [comment]
![AA_Scarlet_p1_01](https://user-images.githubusercontent.com/36779526/114466939-21018400-9bb7-11eb-8c63-7e67a2813df1.png)
[images_characters.zip](https://github.com/renpy/renpy/files/6299990/images_characters.zip)

**Comment by omega-fallon** [comment]
Further messing around with my code, and I've found that this seems to be an ATL-specific issue, since the At() statement has this same mistake, as does simply showing the image with the zoom property, as in:
```
show image "Characters/Scarlet/AA_Scarlet_p1_01.png"
     zoom 0.2
```

**Comment by renpytom** [comment]
I don't understand what you mean by the last comment.

**Comment by omega-fallon** [comment]
Whether it's Transform(), At(), or just directly using "zoom", scaling the image has those ugly artifacts, which are not present in im.FactorScale().

**Comment by kobaltcore** [comment]
I am also running into this issue where the quality of the scaling is diminished. However, on my end this only happens on the nightlies, Ren'Py 7.4.4 is fine.
Upgrading to 7.4.5 and changing nothing else exhibits this behavior.
Our characters are scaled using `im.Scale`.

### Difference between two screenshots of the same scene on 7.4.4 and 7.4.5
The difference is not actually that pronounced, I just turned up the contrast for easier viewability.
![diff-enhanced](https://user-images.githubusercontent.com/39258182/114855211-fd705080-9de5-11eb-9a0e-adc269e821fa.jpg)

### Raw Screenshot on 7.4.4
![before](https://user-images.githubusercontent.com/39258182/114855225-019c6e00-9de6-11eb-8cea-e33002e74b2e.jpg)

### Raw Screenshot on 7.4.5
![after](https://user-images.githubusercontent.com/39258182/114855229-02350480-9de6-11eb-8de5-50b15b6c70e2.jpg)

### Side-by-Side Comparison of 7.4.4 vs 7.4.5
![a-b](https://user-images.githubusercontent.com/39258182/114855230-02350480-9de6-11eb-888f-b87f1180afbb.jpg)

**Comment by omega-fallon** [comment]
That's... really weird. So 7.4 FactorScale is good, but zoom and 7.5 FactorScale leaves artifacts?

**Comment by kobaltcore** [comment]
We are not using `FactorScale` in our game, we're just using the regular `Scale`. Looking at the code, however, it appears that both of these use the same surface scaling method internally, so they should behave the same way.

**Comment by omega-fallon** [comment]
I see. So what makes zoom different from those methods? As far as I can tell zoom produces worse results, even with gl2 and bilinear.

**Comment by kobaltcore** [comment]
The only thing I can think of that might've changed between 7.4.4 and 7.4.5 in its current state is Tom's work on perspective rendering, which did touch the accelerator file (which I think handles the `zoom` implementation). the FactorScale/Scale methods use the surface stuff directly and that might be why that still worked on your end.
Don't quote me on this though.

**Comment by omega-fallon** [comment]
I suppose I can try updating to 7.4.5 and see if that improves zooming.

**Comment by kobaltcore** [comment]
Judging by my example, it should make it worse.

**Comment by omega-fallon** [comment]
Well, probably not. Your example is using Scale, while mine is using zoom.

**Comment by omega-fallon** [comment]
Yeah it's worse. Both zoom and FactorScale look horrible now.
![screenshot0281](https://user-images.githubusercontent.com/36779526/114888332-1faea200-9dd7-11eb-9196-5471bd916fd9.png)

**Comment by omega-fallon** [comment]
For reference, here's the same screenshot in 7.4. Zoom on the left and FactorScale on the right.
![screenshot0282](https://user-images.githubusercontent.com/36779526/114889362-0eb26080-9dd8-11eb-9754-d63e08f022ba.png)

**Comment by omega-fallon** [comment]
After upgrading to today's (4-20's) Nightly, the situation seems to be the same as it is in 7.4. Transform() is jagged and im.FactorScale is smooth. So, that change made in #2770 seems to be unrelated/ineffective.

**Comment by renpytom** [comment]
I believe the change made in d0e4b33 address this. Ren'Py tries to use as much information as possible when drawing an image, by always scaling down, which combines the information from multiple pixels, rather than scaling up, which makes up pixel information. However, I think I got the parameter a bit wrong, and it can in some cases go up two levels, which means that Ren'Py will dropping some information during the interpolation. 

Here's the version with that commit. I think it's the same, at least to my eyes. Please let me know what you think. 

![image](https://user-images.githubusercontent.com/379804/115945206-98bd9180-a488-11eb-9319-275b7419d068.png)

**Comment by kobaltcore** [comment]
It's certainly very close now:
![diff](https://user-images.githubusercontent.com/39258182/115960131-ddd8d680-a50f-11eb-8eba-3994de4388e3.jpg)

There's minute differences in edges and fine lines, but overall it looks quite close. Unless somebody actually diffs the before and after, I don't think anybody will notice.

As far as I can tell, the scaling issues from my side are now resolved with this new commit.

**Comment by omega-fallon** [comment]
Agreed, both look good and about the same. Thanks! :)

**Comment by renpytom** [comment]
Closing, thanks for everyone's help.
