### ISSUE TITLE
[7.4.*] Big cursors are hidden on full screen mode

### ISSUE THREAD

**Issue by Archy812** [renpy/renpy#2769]
If the mouse cursor is translucent, it works fine in windowed mode, but fully hidden in full screen mode.

Sample cursors attached [cursors.zip](https://github.com/renpy/renpy/files/6330149/cursors.zip)

Test:
```
init -100 python:
    config.gl2 = True
    config.mouse = {
        "default" : [("gui/1.png", 4, 5)],
        "test1" : [("gui/hand_small.png", 1, 1)],
        "test2": [("gui/hand_idle.png", 16, 24)],
    }
    

label start:
    
    $ default_mouse = "default"
    
    "default"
    
    $ default_mouse = "test1"
    
    "test1"
    
    $ default_mouse = "test2"
    
    "test2"

    jump start
```

"default" and "test1" are fine, but "test2" is hidden in the fullscreen. Alt+Enter and it works fine. Alt+Enter and it's hidden again.
Maybe it's OS or GPU dependent? Windows 10, Nvidia with ~actual drivers

**Comment by renpytom** [comment]
How big are your cursors?

**Comment by Archy812** [comment]
308x227
You are right, this is not an alpha problem, but a cursor size problem. I removed alpha from `gui/hand_idle.png` but the problem persists

**Comment by renpytom** [comment]
Windows only supports 32x32 cursors, though larger sizes sometimes work - I'd expect 64x64 to work on most places. 

I don't think this is a bug in Ren'Py.

**Comment by renpytom** [comment]
To better support the "big cursor" case, there is a new config.mouse_displayable variable in Ren'Py 7.4.5. This uses the standard drawing methods to draw the mouse, which means that it can support mice larger than the OS does.

**Comment by Archy812** [comment]
Wow, thanks!

BTW, ~250x250 works fine, so I reduced the image size for now
