### ISSUE TITLE
Lint not working in nightlies

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#2772]
Lint works fine on 7.4.4, but since using the recent nightlies, the Ren'Py Launcher tells me that "Launching the project failed", even though it launches correctly on its own.

**Comment by renpytom** [comment]
Can you send your project to pytom@bishoujo.us, please? Lint is working for me, but it's likely your project is triggering some issue with lint.

**Comment by Andykl** [comment]
Even with lint startup, if the launch fails, traceback.txt is created. You may see the problem there.

**Comment by kigyo** [comment]
Sent my project. 
Unfortunately, using lint didn't create a traceback.txt in my case.

**Comment by renpytom** [comment]
I'm not able to repeat this on Linux. What platform are you working on?

**Comment by kigyo** [comment]
I’m using Windows 10
