### ISSUE TITLE
Using different self-voicing on Windows

### ISSUE THREAD

**Issue by m3M0ryHuN73R** [renpy/renpy#2773]
I am trying to use espeak-ng for a project I'm making and I'm trying to synthesize using Georgian language, which espeak-ng supports. How do I use integrate/use espeak-ng in Renpy?

**Comment by uyjulian** [comment]
You can set `os.environ["RENPY_TTS_COMMAND"]` to the path of espeak-ng

**Comment by m3M0ryHuN73R** [comment]
> You can set `os.environ["RENPY_TTS_COMMAND"]` to the path of espeak-ng

Would It be the same if i were to go to PATH and create RENPY_TTS_COMMAND line with the directory being of espeak-ng? Also, would it automatically call espeak-ng? Wouldn't I need to set things up?

**Comment by uyjulian** [comment]
You need to specify the path to the executable and any additional command line flags. The voice text will be appended to the end of the command

**Comment by m3M0ryHuN73R** [comment]
So, for example, I would like to add flags, "-v ka" as arguments of espeak-ng. Do I write that at the end? Could you show me an example?

**Comment by uyjulian** [comment]
```py
os.environ["RENPY_TTS_COMMAND"] = "C:/path/to/espeak.ng -v -ka "
```

**Comment by m3M0ryHuN73R** [comment]
Understood. Thank you a lot. Will give it a try and if it works, I'll close this down.

**Comment by renpytom** [comment]
You also have config.tts_function, which lets you change the TTS in any way you want. I'll close this, feel free to re-open it if you think there's something more here.
