### ISSUE TITLE
ATL resets zoom level

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#2774]
I show my characters at various zoom levels using `at` statements.
```
transform three:
    zoom 0.75 ypos 0.0
show character at r, three
```
This works great if they stay in place, but if I apply transforms such as
```
transform stomp:
    ease .04 xoffset 16
    ease .04 xoffset -16
    ease .02 xoffset 8
    ease .02 xoffset -8
    ease .01 xoffset 0
```
or `with move`
this tends to mess with the characters' zoom levels, reverting them back to 1.0.

Is this supposed to happen, even though the transforms contain nothing about zooming?

**Comment by renpytom** [comment]
I can't repeat this. 

```

label start:

    scene bg washington

    show eileen happy at right, three

    pause

    show eileen happy at center
    with move

    pause

    return
```

That being said, when you have multiple lists of transforms like this, they're matched - last to last, second to last to second to last, and so on. So things could get confusing if the number of transforms applied to a sprite changes.

**Comment by kigyo** [comment]
Okay, the fact that the order matters is definitely something I'll keep in mind! 

In a case like this, how can I make sure the last two transforms stay unchanged by `stomp`? (`three` is a zoom and `night` a blue tint)
```
show character at r,three,night with dissolve
"Look at them go."
show character at stomp
ch "I am angry!{w=0.3}{nw}"
show character at stomp
extend " Really angry!"
```
I thought since `r` and `stomp` are both first, they would go together, and since no further transforms are given, `three` and `night` should stay the same. But whenever `stomp` is used, the character goes back to a default 1.0 zoom. 
I tried to putting `r,three,night` in all different possible orders, but either the zoom or tint would go away in every case.

Even weirder, if I keep `r,three,night` in the first line and try to preserve the zoom by applying it along with stomp (`stomp,three`), then it instead applies the zoom twice. (So it's 0.75x0.75 rather than the 1.0x0.75 I would've expected.)

I'm really not sure if I'm failing to grasp some very obvious underlying pattern, or if this could be made more intuitive.

**Comment by renpytom** [comment]
I suspect it would work if you did stomp,r,three,night . Generally, you want to match the transforms up so they do the same thing, or else hide and show.

**Comment by kigyo** [comment]
That does work. Thank you for the clarification!
