### ISSUE TITLE
[Feature Request] Allow the size of layeredimages to be locked

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2783]
Problem :
The size of a layeredimage can change depending on which attribute is showing (if some non-always attributes exceed the bounding area of the always ones for example).
It causes a layim shown with a floating-point anchor (which includes aligns and therefore the `default` transform) to change position depending on which attribute is shown.
Having `fit_first` as a parameter for the underlying Fixed fixes that, but one of the numerous drawbacks is that the fitting is always made on the first showing attribute of the layeredimage.

Solution :
A new property for layeredimages with a new name not taken by any existing one (i.e. `fit_max`)
It would set the size of the layeredimage to be the shortest bounding box fitting each and every attribute.

Implementation :
During init time (if and when `fit_max` is set), a version of the layim with **ALL** attributes enabled is generated
(which can be triggered with the following code for testing purposes :
```renpy
init python:
    def _choose_attributes(self, *args, **kwargs):
        return tuple(a.attribute for a in self.attributes)
    LayeredImage._choose_attributes = _choose_attributes
```
)
Then either
- the size of the resulting image is saved and given to a Null() (lighter in memory and maybe in processing power)
- the exported image is wrapped in a transform with its opacity set to 0 (simpler to program, less low-level dependance)

which is turned into an Always attribute
which is set as the first attribute of the layeredimage
and the fixed of the layim is given the `fit_first` parameter, for the Null to define the size of the layim.

If issue #2782 gets fixed, `fit_max` could take "width" or "height" in addition to boolean values.

**Comment by renpytom** [comment]
Nope. 

Ren'Py isn't going to scan images at init time. Heck, it can't do that in the general case.
