### ISSUE TITLE
rolling text with {color}{/color} label in move() has unexpected line feed result

### ISSUE THREAD

**Issue by YuanlinLi** [renpy/renpy#2786]
$ rolling_info=“{color=#d60000}textextextextexte{/color}textextext{color=#d60000}textextextextexte{/color}textextext{color=#d60000}textextextextexte{/color}textextext{color=#d60000}textextextextexte{/color}textextext{color=#d60000}textextextextexte{/color}textextext{color=#d60000}textextextextexte{/color}textextext{color=#d60000}textextextextexte{/color}”
$ rolling_time=20
show text rolling_info at Move((1.2,0.05),(-1.0,0.05), rolling_time, repeat=True, bounce=False, xanchor="left", yanchor="top") zorder 991

**Comment by renpytom** [comment]
You'd want to do:

```
    show expression Text(rolling_info, layout="nobreak") at Move((1.2,0.0),(-1.0,0.0), rolling_time, repeat=True, bounce=False, xanchor="left", yanchor="top") zorder 991
```

Though that's still a 15 year old way of writing this. (Where did you find it?) A modern way of writing this would be:

```
    show expression Text(rolling_info, layout="nobreak") as text zorder 991:
         offscreenright
         linear 20.0 offscreenleft
         repeat
```
