### ISSUE TITLE
Texture Corruption on ANGLE (Nightly)

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#2787]
Recent Nightly builds seem to have issues with the Angle renderer. Tested on an empty project.

Logs:
[log.txt](https://github.com/renpy/renpy/files/6415899/log.txt)
[mini sysinfo dump.txt](https://github.com/renpy/renpy/files/6415999/mini.system.dump.txt)

Snapshot:
![image](https://user-images.githubusercontent.com/45672224/116897956-bda2c900-ac2d-11eb-94ad-32792367484f.png)

**Comment by renpytom** [comment]
Is there any chance you can go back through recent nightlies and see if you can figure out where it changed? Problems like this often only happen on one system.

**Comment by loafylemon** [comment]
I was able to trace it down to build from [Saturday, May 01, 2021](https://nightly.renpy.org/nightly-2021-05-01-1c0117d6b/index.html) 

After investigating a little, it would seem that the Depth Buffer change made in c32c9182bec3cae23bdef41bef22745290cb2a3e is what caused this on my end, and setting `depth_size=None` in `renpy/config.py` allowed me to run the project with no texture corruption.

If there's anything I can do to help, please let me know.

**Comment by renpytom** [comment]
Can you try setting it to 16 instead of 24?

**Comment by loafylemon** [comment]
I have tried setting it to values ranging from `16` to `2`, the result seems to be the same. 

Interface seems to be remaining functional throughout, and [I was able to enter the preferences menu](https://user-images.githubusercontent.com/45672224/116936821-420e3f80-ac60-11eb-9f67-0a886e9546c7.png).
