### ISSUE TITLE
Translation files are not generated for multiline strings using backslash at end of line.

### ISSUE THREAD

**Issue by RubenGarcia** [renpy/renpy#2791]
Translation files seem to be only generated for
animations.rpy   common.rpy   options.rpy   screens.rpy   script.rpy
but not for the rest of the files in the directory.

**Comment by renpytom** [comment]
I don't think that's true. Do the other files have dialogue in them?

**Comment by RubenGarcia** [comment]
Yes.
$renpy.say (None, "Example text")

**Comment by RubenGarcia** [comment]
I see only menu entries are added, not other strings. Closing.

**Comment by RubenGarcia** [comment]
I added
 $renpy.say (None, _("Example text"))
to my file, but it is still not being added to the translation files.
Reopening issue.

**Comment by RubenGarcia** [comment]
Ok, found the issue.
``` $renpy.say (None, _("Example text"))```
is detected, but
``` $renpy.say (None, _("Very long \
 text"))```
is not detected.
