### ISSUE TITLE
Gamepad (LogitechF310) causes Games not start anymore after prolonged sessions

### ISSUE THREAD

**Issue by supernap** [renpy/renpy#2798]
As the title exclaims, recently (the last 2 or so months) after longer sessions in RenPy games either the gamepad function or some conflict witht the drivers for my Logitech F310 cause subsequent RenPy games not to start properly and showing only whitescreens (or blackscreens when in DirectX mode) and freezing up after a few seconds. This only occures after at least one hour with in a game, shorter sessions seem to be not affected, and may be connected to repeated uses of said gamepad in those sessions (yeah i am strange i know, but i really like to lean back comfortably furing gaming, as well as snuggling  under blankets and the like). Not sure if thats an issue with other gamepads too, since the only other gamepads in my  posessions are various version of dualshocks, and those are a pain to be run on PC, if even possible.
Interestingly enough, a restart of the PC solves this issue (until the next longer session with repeasted gamepad usage), but there are also most of the times troubles while trying to close the OS (Win10-64Bit) making hard resets necessary, leading me to believe that the error occures within the RAM allocation for RenPy, and may by some function artifact that is not properly purged after closing the program.

**Comment by renpytom** [comment]
What version of Ren'Py are you on?  I'd think that if it's persisting past a single session, it's probably some sort of problem with the Logitech drivers, and you'll need to talk to them to fix there drivers. Fundamentally, once Ren'Py is closed, all of it's effects on your system end, and so if something is persisting past the end of a session, it would have to be Logitech related. 

(

**Comment by supernap** [comment]
I do not have a frikking Idea what versions it is, since i am not a developer, but a mere consumer, and i wanted to raise awareness of this issue. And i am also pretty sure it is more an issue with the drivers then RenPy itself, but this problem only occures in conbination of those two, so i am notifiing it here too, but not to blame you guys for said problem

**Comment by supernap** [comment]
small update.
I can say the error to be clearly with the F310, or at least was.
1. Updating the LT drivers, again, seemingly has fixed problem, so it was probably a driver deciding to go faulty for no eason, about 1 mounth or so ago ...
2. Using a DS3 with SCP-Drivers seems not to effect the function of the renpy player negatively.

I am sorry if I stirred up apparently unnecessary trouble about a problem that clearly seem to stem from my own system

**Comment by renpytom** [comment]
No problem. Thank you for letting me know, and I'm glad this is working for you.
