### ISSUE TITLE
Request: Remember game window position / monitor

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#2800]
(Do forgive me if I missed a setting for this but I found nothing in the documentation or the forums.)

Ren'py games will seemingly always launch on the main monitor (on Windows, at least). This is a problem for players who for one reason or another prefer to game in a monitor other than their main monitor - like me - and it forces them to move the window over every time they boot up the game.

This is extra cumbersome if you play in full screen, as the game will start full screened on the monitor you don't want, and you have to un-full screen, move the window over, and full screen again. With more and more games targeting 1080p resolution - and it apparently being the resolution everyone recommends for new devs - this is a problem.

Most games nowadays have this feature, so I think it's only natural that Ren'py have it too, and eliminate this unnecessary annoyance for players. It's not necessary that it remember exactly where on a screen the window was, just the monitor is fine and then you can center the window on that monitor, but remembering exact position would be preferable.

**Comment by renpytom** [comment]
This has been implemented by 534af32307152289f6f438f5f77e91cdd0429b39 .
