### ISSUE TITLE
Game flickering/blinking in visual novel ''Doki doki literature club''  (recording proof)

### ISSUE THREAD

**Issue by BuzzingBee** [renpy/renpy#2801]
https://user-images.githubusercontent.com/35054360/117554654-e6e89e00-b00d-11eb-9cdb-1e0fdebcf6c1.mp4

**Comment by BuzzingBee** [comment]
Wait what? its the normal vanilla ddlc from their website, also how do i know i have an unsopported version of renpy?

**Comment by GanstaKingofSA** [comment]
So a bit of information on this (after seeing the convo in Discord on DDFC and here.

1. This happens still on the latest version of Ren'Py with the Ren'Py SDK and other visual novels made in Ren'Py. 

2. DDLC at the time he ran this was the original version of the game. Not a mod.

While 6.99 is unsupported, from what I have seen and tested with the mod template, I have not encountered those flickers with different systems.

I hope that clarifies anything of this issue. I didn't send them here to report it, but I think the confusion is rather with the issue tag just being about DDLC and not other VNs. My assumption based off what I see is this isn't a engine or engine render bug but rather the system the issuer is running with Ren'Py itself.
