### ISSUE TITLE
Bug?: Save on Quit, does not save when returning to the main menu 

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#2802]
I have tested the save-when-exiting feature, following the Patreon tutorial:
[](https://www.patreon.com/posts/save-on-quit-19764358)
It works correctly when quiting the game, but there is a behavior that I think is not what I expected. When you return to the main menu the game is not saved.

The file assigned to _quit_slot should also be saved when you return to the main menu.

**Comment by Gouvernathor** [comment]
It still does in the 7.4.4 release, that's a regression.
