### ISSUE TITLE
Duplicate topic in documentation index 

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#2810]
In Nightly Build version 7.4.5.1608 Matrixcolor is found in the Text, Displayables, Transforms, and Transitions section and in the Other Functionality section. 

In addition to this, I looked for the documentation of the 3D scenario but could not find it. Or this functionality has not been released yet?

**Comment by renpytom** [comment]
The 3D stuff is in the "3D Stage" section under Text, Displayables, Transforms, and Transitions. I've removed the duplication.
