### ISSUE TITLE
Game closes on android when opening a game menu

### ISSUE THREAD

**Issue by hackerncoder** [renpy/renpy#2812]
Edit: Ok, so I cannot replicate this on a more normal phone/os. My guess is that renpy somehow trips GrapheneOS's hardening and so it kills it.

---

Ren'Py 7.4.5.1601 (Edit: And 7.4.5.1615)
Google Pixel 4 (Edit: Running GrapheneOS. Cannot replicate on Samsung A20e)

Somewhat log:
```
[just X took Ys]
Importing _renpystream: ImportError('No module name _renpystream',)
Set script version to: (7, 4, 5)
[more X took Ys]

Initializing gles2 renderer:
primary display bounds: (0, 0, 2280, 1080)
swap interval: 1 frames
Fullscreen mode.
Vendor: 'Qualcomm'
Renderer: 'Adreno (TM) 640'
Version: 'OpenGL ES 3.2 V@049.0 (GIT@85da404, I46ff5fc46f, 1606794520) (Date;11/30/20)'
Display Info: None
Screen sizes: virtual=(1366, 768) physical=(2280, 1080) drawable=(2280, 1080)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
Total time until interface ready: 8.88112998009s
Total time until interface ready: 8.88112998009s
Flip failed error('The specified window has not been made current',)
Screen sizes: virtual=(1366, 768) physical=(2280, 1080) drawable=(2280, 1080)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096

[end of log]
```

**Comment by renpytom** [comment]
Sounds like it. A more complere logcat might be helpful, but Ren'Py does expect to be able to read and write from all the standard places.

**Comment by hackerncoder** [comment]
[Here is the logcat](https://data.encryptionin.space/logcat.txt)

**Comment by renpytom** [comment]
It's segfaulting, which might be part of your operating system's protections. I'd also wonder about the specified window not being current - it's possible something is preventing the main window from gaining focus. 

Either way, I don't think this a Ren'Py issue, though if the GrapheneOS's developers had questions I'd be happy to work with them.

**Comment by hackerncoder** [comment]
> I don't think this a Ren'Py issue

Maybe not. It used to work.
