### ISSUE TITLE
Subclasses of ADVCharacter do not participate in rollback

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2813]
```rpy
init python:
    class A:
        def __init__(self):
            self.att = False

    class B(NoRollback):
        def __init__(self):
            self.att = False

    class C(ADVCharacter):
        def __init__(self):
            self.att = False

default a = A()
default b = B()
default c = C()

label start:
    e "You've created a new Ren'Py game."

    $ a.att += 1
    $ b.att += 1
    $ c.att += 1

    e "Heyo !"
```
Start a new game.
Open the console and typing `watch a.att, b.att, c.att`.
Go to the next dialogue line and roll back to the first one, several times.

You will see the behavior described [here](https://www.renpy.org/doc/html/save_load_rollback.html#norollback) occuring both to b and to c, despite C not being a subclass of NoRollback.
It may also happen with some other renpy-builtin classes apart from ADVCharacter, I didn't test further.

Surprisingly, having `class C(object, ADVCharacter)` solves it and makes it rollback-friendly again, while it does not in `class B(object, NoRollback)`'s case.
I suspect there is some of the py2 weird inheriting system where `class A:` is not the same as `class A(object):` meddling in the way. If so, this behavior would probably not be py3-compatible.

**Comment by renpytom** [comment]
This isn't a bug -  in general, you can't expect to subclass arbitrary parts of the Ren'Py implementation and expect it to work. What's happening here is that object (in the Ren'Py store) is a different class than Python's object - it's actually renpy.python.RollbackObject. 

That being said, Character is something that I can add new fields to at any time, so adding your own attributes to it is a really bad idea. It's also a bad idea to create your characters in default like this, as it means it's impossible to change a Character - things like the color of the text - once a game has been saved. 

What you *can* do is:

```
define character.a = Character("a")
default a = object()
```

And that will work in most cases. 

In general, though, you can't go poking into the Ren'Py implementation like this, without doing work on the engine itself.
