### ISSUE TITLE
Linux suspend/resume seems to invalidate textures

### ISSUE THREAD

**Issue by mal** [renpy/renpy#2823]
Observed with 7.4.4 on Ubuntu 18.04 with `config.gl2 = True`.

Leaving a game open, then suspending and resuming the PC leads to all displayed (or maybe cached?) textures being replaced with pure white filled with roughly (eyeballing it) 20x20px squares (typically full blue, but sometimes pink/magenta). These appear to be cached as new assets load correctly atop affected backgrounds and even heading back to the main menu and starting a new game doesn't change that.

Changing the window size, or entering/leaving full screen (forcing a texture reload) resolves the issue. Best guess would be stuff that's in volatile video memory and that's not captured during the suspend/resume cycle, leading to displaying either uninitialised or freshly initialised video memory in place of expected textures.

I'm not sure if this is detectable, or even if it's significant enough to warrant more investigation, but it might be worth acknowledging in the docs as a known issue/limitation.

**Comment by renpytom** [comment]
A quick look over the SDL2 source shows that the events that seem to be relevant, SDL_RENDER_DEVICE_RESET and SDL_RENDER_TARGETS_RESET, can only be triggered on Direct3D and Android, but not Linux. 

My understanding is that a suspend and resume on Linux should recover the OpenGL textures, and so if they're corrupted like this, it's an issue with the drivers not implementing suspend and resume correctly, as opposed to something normal software is expected to handle. (This is different from Direct3D, where it is.) 

I'll put some words about this into https://www.renpy.org/doc/html/problems.html , but this isn't fundamentally a Ren'Py problem.
