### ISSUE TITLE
[Feature request] Reverse-Frame

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2824]
The goal would be to have like a Frame, but with reversed deformation, aka it would keep the center part of itself as-is and deform the rest.
Taking [this picture](https://www.renpy.org/dev-doc/html/_images/frame_example.png) for example, the 5 are would be untouched (small), the 4 and 6 would be wider, the 2 and 8 taller, and 1, 3, 7 and 9 both wider and taller.
If implemented with a kwarg to the Frame object, like the `tile` argument, it would be handy.

**Comment by renpytom** [comment]
Can you explain where you think this would be handly? Frames/ninepatches are used elsewhere, but it's hard to think where somehting like this would be useful.

**Comment by Gouvernathor** [comment]
It's just another way of using frames.
Take the default choice button for example : opaque in the middle, gradient to transparent at the left and right. Suppose I were to put some arabesques just near the middle of the image (not too far on the left or right).
I want the image to be able to be stretched laterally, but the arabesques can't be deformed - it would be ugly.
So what I would want is to stretch (or tile) the left and right parts of the image, but while keeping the center part as-is.

**Comment by renpytom** [comment]
Do you have an example of this? I'm not 100% sure that:

```
Fixed(
    Frame("background.png"),
    Transform("decoration.png", xalign=0.5),
)
```

Wouldn't be a better way to do this. Historically, Frame has been a hard displayable to get right - it's very easy to have the patches overlap and cause rendering issues. So I'd want to make sure changes are useful before adding a variant.

**Comment by Gouvernathor** [comment]
That would be if the two pats of the image can be separated neatly, but it's not always the case - sometimes there are shadows, reflections and various effects between the parts of the image.
It's not that important, so if it's a big deal programmatically it may not be worth the shot - if only for the tiling option whose interactions with this would need to be adressed - but it would be cool to have another solution for this than passing each version of the sprite through a Transform-containg Fixed.

**Comment by renpytom** [comment]
I think stepping back, my question is if this was motivated by something you wanted to use for a game, or just something that happens to be omitted by Ren'Py. I'm trying to figure out if I implemented this, would you use it? (In any case, this won't go in until after 7.4.5 is out.)

**Comment by Gouvernathor** [comment]
It's something I wanted to do, tried to do it with transforms, `Fixed`s and `Crop`s and failed, so yes I would be using it. If I don't opt to separate that into two separate sprites in the short-term, that is.
I understand completely that it's not a priority.

**Comment by renpytom** [comment]
My feeling is something like this might be better off as part of a more general mesh system, that would let you specify this in general ways.

**Comment by renpytom** [comment]
Closing this, since we spoke on discord and a more generic version is probably better.
