### ISSUE TITLE
Official Ren'Py Splash?

### ISSUE THREAD

**Issue by Lezalith** [renpy/renpy#2826]
I thought about having a Splash Screen in every new Ren'Py project. Just something simple, like the Ren'Py Logo on a white background, fading in and fading out.

This would either mean that there would already be a present "splashscreen" label defined (probably in gui.rpy?), or that there would be another label for this purpose, called right before "splashscreen" is called. Former seems better to me, it brings more attention to the fact that Ren'Py has an easy way of creating splashscreens (Been commissioned for those before because people weren't aware).

Either way, this could be turned on/off through a config variable, just like quick menu can be.

The main issue I see with this is deciding whether the splashscreen should start turned on/off in created projects. 
On, users will probably turn it off soon because they won't want to pass the splashscreen every launch while testing.
Off, users might forget completely that this feature is present? Although if it was in gui.rpy, they should find it eventually, since that's a file most users are going through. 

Thoughts?

**Comment by Gouvernathor** [comment]
Adding it as a `splashscreen` label before the `start` label in script.rpy would be cool. That way, no config variable or custom screen is needed, and even newer users can understand how it works and how to custom/disable it.

However, the contents of that screen can cause a problem on its own. For the moment, no placeholder sprites are placed in a new project, except the debug Placeholder built-in. I mean, `bg` and `eileen happy` are called from the script but no such image file is included.
So, should the splash image be included in the gui folder ? Or should the splash be made of generated displayables only ? The latter would solve the image file issue, but either it's something basic and dull, or it's quickly too complex for new users...

**Comment by renpytom** [comment]
I don't think we need a Ren'Py splash screen between the player and the game.
