### ISSUE TITLE
[7.4.5] In Windows, if the date includes Korean, the sentence is broken.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2837]
<img width="500" alt="ss" src="https://user-images.githubusercontent.com/60040734/120113357-13c74580-c1b5-11eb-9b5c-7139a1c3856b.png">

- { ▲ Normal Example - macOS }

<img width="450" alt="ss" src="https://user-images.githubusercontent.com/60040734/120113484-9cde7c80-c1b5-11eb-9d9b-43a773be04e2.png">

- { ▲ Abnormal Example - Windows 10 }

<img width="450" alt="ss" src="https://user-images.githubusercontent.com/60040734/120113511-c8616700-c1b5-11eb-8fdf-b42defbe6db8.png">

- { ▲ Abnormal Example - Windows 7 }

Tested on Windows 10 and Windows 7.

In Windows, if the date includes Korean, the sentence is broken.
If English and numbers are included except for Korean, it works normally. I think similar problems will occur in such as Japanese and Chinese.

The source code below is the translation source code I used.

    translate None strings:
        # renpy/common/00action_file.rpy:47
        old "{#month}January"
        new "{#month}1월"

        # renpy/common/00action_file.rpy:47
        old "{#month}February"
        new "{#month}2월"

        # renpy/common/00action_file.rpy:47
        old "{#month}March"
        new "{#month}3월"

        # renpy/common/00action_file.rpy:47
        old "{#month}April"
        new "{#month}4월"

        # renpy/common/00action_file.rpy:47
        old "{#month}May"
        new "{#month}5월"

        # renpy/common/00action_file.rpy:47
        old "{#month}June"
        new "{#month}6월"

        # renpy/common/00action_file.rpy:47
        old "{#month}July"
        new "{#month}7월"

        # renpy/common/00action_file.rpy:47
        old "{#month}August"
        new "{#month}8월"

        # renpy/common/00action_file.rpy:47
        old "{#month}September"
        new "{#month}9월"

        # renpy/common/00action_file.rpy:47
        old "{#month}October"
        new "{#month}10월"

        # renpy/common/00action_file.rpy:47
        old "{#month}November"
        new "{#month}11월"

        # renpy/common/00action_file.rpy:47
        old "{#month}December"
        new "{#month}12월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Jan"
        new "{#month_short}1월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Feb"
        new "{#month_short}2월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Mar"
        new "{#month_short}3월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Apr"
        new "{#month_short}4월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}May"
        new "{#month_short}5월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Jun"
        new "{#month_short}6월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Jul"
        new "{#month_short}7월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Aug"
        new "{#month_short}8월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Sep"
        new "{#month_short}9월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Oct"
        new "{#month_short}10월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Nov"
        new "{#month_short}11월"

        # renpy/common/00action_file.rpy:63
        old "{#month_short}Dec"
        new "{#month_short}12월"
    
        # renpy/common/00action_file.rpy:142
        old "%b %d, %H:%M"
        new "%b %d일, %H:%M"

**Comment by renpytom** [comment]
Can you repeat this in The Question, or is this specific to a particular game?

**Comment by ikusorae** [comment]
I think the same problem occurs in other projects.
