### ISSUE TITLE
[7.4.5] Red-flashing issue on full screen in macOS

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2839]
When exit the game from the full screen via the green button in macOS, the entire window flashes red and then ends.

**Comment by renpytom** [comment]
I can't repeat this, 7.4.5 on my M1 Mac Mini. Does the log.txt say anything?

**Comment by ikusorae** [comment]
On my iMac, the problem occurs regardless of the project (even in The Question). And other macOS user who played my game said the same problem occurs.
However, after installing and testing a new macOS on VMware, the problem does not occur.

First of all, I am attaching the log.txt of my project.

[log.txt](https://github.com/renpy/renpy/files/6575704/log.txt)

**Comment by renpytom** [comment]
Can you try adding:

```
define config.gl2 = False
```

to your game?

**Comment by ikusorae** [comment]
Yes, I've been using that before. The problem seems to occur whether gl2 is active or not.

**Comment by ikusorae** [comment]
https://user-images.githubusercontent.com/60040734/120340094-ab04d800-c330-11eb-9771-96b8df2f03e9.mp4

In addition, I repeated this and recorded as a video.

**Comment by renpytom** [comment]
Can you start the game, and then quit, rather than quitting from the main menu? 

I want to make sure this is happening after the game is over. If it is, it's probably something we can live with, especially since it doesn't happen on either of my macs.

**Comment by ikusorae** [comment]
Unfortunately, it shows the same result. Have you tried maximizing through the green button?
There is a report of other mac showing this issue, but the problem cannot be reproduced in a virtual mac, so it may only occur in a particular macs. (I am currently using iMac 5K 2019 with i9, Radeon Pro 580X)

**Comment by renpytom** [comment]
Yes, I've tried this here, and Ren'Py is working fine. Can you take a screenshot of a quit through the confirm dialogue? Or does the confirm dialogue not show?

**Comment by ikusorae** [comment]
https://user-images.githubusercontent.com/60040734/121034272-dc295080-c7e7-11eb-9b35-fbff5dbb3821.mp4

Sorry, I'm late. Here it is.

**Comment by renpytom** [comment]
This looks like it's happening after Ren'Py quits, and isn't happening on my macs, so I don't think I can fix this.
