### ISSUE TITLE
Inconsistency with Yes/No Prompt

### ISSUE THREAD

**Issue by Keinart** [renpy/renpy#284]
When using a transparent png image for the Yes/No Prompt background, it will overlap the previous background when the prompt appears except when pressing the X button of the window to exit the game in a menu (it happens in all menus screens, but not when the game is running), creating an inconsistency.

Notes:
The user Crazy Li reported this issue didn't happen with Renpy 6.13, but will happen from the following version onward.

Images attached:
![bug yesno prompt 1](https://f.cloud.github.com/assets/6564457/2059221/e90b13d4-8b9e-11e3-8b22-82e344069456.png)
![bug yesno prompt 2](https://f.cloud.github.com/assets/6564457/2059227/0a050a40-8b9f-11e3-96b4-112cb4e998a8.png)
![bug yesno prompt 3](https://f.cloud.github.com/assets/6564457/2059228/0d3d7e22-8b9f-11e3-9ddf-a4dde23591e7.png)

A demo of a game for windows to reproduce the issue can be downloaded here: http://www.mediafire.com/download/djgf3puaymftvvi/Bug%20transparent.zip

Steps to reproduce:
1. In the main menu, press the "Quit" button to see how the gray.png image overlaps with the background when the yes/no prompt appears.
2. In the main menu again, press the "X" in the corner of the window to exit the game. Notice how when the yes/no prompt appears the menu background is removed.
3. Press "Start Game", and then press the "X" in the corner of the window to exit the game. Notice how the gray.png image overlaps correctly if the game have started.

**Comment by renpytom** [comment]
This is expected behavior that i don't want to change, as we want to support showing the background to the user. When at the main menu, use a different backround, using code like:

```
if main_menu:
     add "main_menu.jpg"
else:
     add "#0008"
```

Something like that.
