### ISSUE TITLE
Cookbook links are dead?

### ISSUE THREAD

**Issue by iwanPlays** [renpy/renpy#2840]
Google thinks that lots of documentation is on the wiki/cookbook

![image](https://user-images.githubusercontent.com/25465450/120200658-dbf7e680-c224-11eb-9958-e4c80353a3ee.png)

But https://www.renpy.org/wiki/renpy/doc/cookbook/Movie_Backgrounds

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

It'll be months and years until Google forgets. Is the content dead? Or did it just move? If it moved, can redirects be coded?

If dead, can some kind of statement be provided, or if there's search in the new documentation, can the title of the URL ( https://www.renpy.org/wiki/renpy/doc/cookbook/Movie_Backgrounds = "Movie Backgrounds") be put into search and the result given?

Cheers!

**Comment by renpytom** [comment]
This should be fixed now, it was an issue with an upgrade to the libraries the website depends on.
