### ISSUE TITLE
Mouse Cursor remains on-screen after gamepad input

### ISSUE THREAD

**Issue by Belgerum** [renpy/renpy#2843]
I recently submitted a game using the latest version of Ren'Py to Steam for approval. They gave me the following message within their notes:

> The following feedback is not strictly required for Steam's gaming support, but reflects some best-practices that we have discovered in the course of testing. While no follow up steps are required, addressing this issue will improve the game play experience.
> 
> - When the user is playing with a controller, the mouse cursor remains on-screen causing the user to have to move the mouse cursor off-screen for a better gaming experience. The mouse cursor will eventually disappear after 30 seconds during gameplay. Once the controller is used, if the mouse cursor were to disappear, that would eliminate this caution.
> 
> We recommend resolving this issue, but it will not prevent your game from releasing.

Would it be possible to change Ren'Py to make this behavior default?

**Comment by renpytom** [comment]
Yes, and I just did.
