### ISSUE TITLE
Importing _renpysteam outside of steam causes weird crashes

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#2844]
Was getting game crashes at weird points in the game which didn't produce an error, traceback or log.

Disabling the `_renpysteam` import no longer causes these crashes.

Skipping (CTRL or TAB) would work perfectly fine, but playing through normally either with SPACE or ENTER would cause a crash when it came up to a `call screen` or `jump` but a few lines back, I suspect that's due to prediction but I couldn't say.

Very weird crash and very little information about it.

**Comment by renpytom** [comment]
Huh. Are you forcing a steam import, or are you disabling Ren'Py's steam import?

**Comment by KiloOscarSix** [comment]
> Huh. Are you forcing a steam import, or are you disabling Ren'Py's steam import?

Yes. Before I was bought on board the previous programmer had a variable called "steam" so I'm importing `_renpysteam as steamAPI` so old saves don't throw a fit.

**Comment by renpytom** [comment]
I'm not sure there's a good way to solve this, as Ren'Py assumes that _renpysteam is imported as steam in a few places. Do you get the crashes in an unmodified Ren'Py?

**Comment by renpytom** [comment]
Weirdly, I don't understand the problem in the first place. Ren'Py imports steam as acheivement.steam - so it's not clear how that would conflict with your save games.

**Comment by KiloOscarSix** [comment]
> Weirdly, I don't understand the problem in the first place. Ren'Py imports steam as acheivement.steam - so it's not clear how that would conflict with your save games.

Ah, wasn't aware of that, I will remove the manual import and use `achievement.steam`

**Comment by KiloOscarSix** [comment]
> I'm not sure there's a good way to solve this, as Ren'Py assumes that _renpysteam is imported as steam in a few places. Do you get the crashes in an unmodified Ren'Py?

No, I only get the crash when I manually import `_renpysteam` and happened at irregular, almost random points. Using `achievement.steam` has fixed the problem

**Comment by renpytom** [comment]
Okay, I'll close this.
