### ISSUE TITLE
Android Notifications in Renpy

### ISSUE THREAD

**Issue by ChloeRaven** [renpy/renpy#2851]
I'm doing a Android port for a game and i want to know if there's a way to some parts of the game the player's phone receives a notification. For example, after a specific dialog the player receives a notification warning them about something.
Its this possible on renpy? What type of code i should use?

**Comment by renpytom** [comment]
This isn't something Ren'Py supports. We do have the pyjinus library, so you could maybe write something that called into the Android apis, but there isn't an easy way to do this. Would a Toast work? Those are easier than proper notifications.

**Comment by ChloeRaven** [comment]
> This isn't something Ren'Py supports. We do have the pyjinus library, so you could maybe write something that called into the Android apis, but there isn't an easy way to do this. Would a Toast work? Those are easier than proper notifications.

Thanks for the answer! I think maybe a toast notification would be the simplest way for my current port, I'll try to use that, thanks
