### ISSUE TITLE
Issues when compiling any renios project on XCode 12.0.1

### ISSUE THREAD

**Issue by Crafty-The-Fox** [renpy/renpy#2856]
I am getting:
```entry point (_main) undefined. for architecture x86_```

When compiling for IOS using XCode 12.0.1.
I think its x86 because I'm compiling for an iOS simulator, but it did the same thing when compiling for my iPad, but said arm64 instead.

I also tried on XCode 12.5, the same issue happened.

This happens with all projects made with renios, and the "open XCode project" button does not work for me either.

Using Mac OS X Catalina (10.15)

I have searched about this on google, but I cant seem to find this issue. (with anything related to renios/renpy)

**Comment by renpytom** [comment]
Is this on 7.4.6?

**Comment by Crafty-The-Fox** [comment]
> Is this on 7.4.6?

its on 7.4.4, il try again using 7.4.6

**Comment by Crafty-The-Fox** [comment]
> > Is this on 7.4.6?
> 
> its on 7.4.4, il try again using 7.4.6

Working on 7.4.6
