### ISSUE TITLE
[Feature request] Customized folder for screenshots

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#2857]
I don't know if it is included or not, but it would be nice to be able to customize the folder where the game screenshots are saved.
Example
`define config.screenshot_folder = "captures"`

If it is None the images would be saved in the root folder, and if it is not None they would be saved in the custom folder that would be created in the root of the game or in the `game` folder

**Comment by renpytom** [comment]
This actually already exists as config.screenshot_pattern, so I don't think a new variable is needed. I've improved the documentation of config.screenshot_pattern to make it clear that "mydir/screenshot-%d.png" will work. 

I've also added _screenshot_pattern, which is the same thing in the store, so the pattern could change as the game progresses.

**Comment by Neyunse** [comment]
> 
> 
> This actually already exists as config.screenshot_pattern, so I don't think a new variable is needed. I've improved the documentation of config.screenshot_pattern to make it clear that "mydir/screenshot-%d.png" will work.
> 
> I've also added _screenshot_pattern, which is the same thing in the store, so the pattern could change as the game progresses.

Thanks a lot Tom, I didn't know about this; One more question related to this screenshot thing, is it possible to specify the date the image was saved?

**Comment by renpytom** [comment]
Not directly. You could do something close by using the date to initialize config.screenshot_pattern when the game starts, but it would become wrong if the game is run past midnight.

**Comment by Neyunse** [comment]
> 
> 
> Not directly. You could do something close by using the date to initialize config.screenshot_pattern when the game starts, but it would become wrong if the game is run past midnight.

I'll see how I do, thanks Tom
