### ISSUE TITLE
Some transforms do not persist as expected

### ISSUE THREAD

**Issue by mal** [renpy/renpy#2858]
This issue over on the forums appears likely related: https://lemmasoft.renai.us/forums/viewtopic.php?t=62374.

The current (broken) behaviour can be observed at least as far back as 7.3.5, is still present in 7.4.6, and boils down to some valid transformations not carrying over when a tag's attributes and/or at_list are updated. This is especially problematic in the case of LayeredImages, but can be seen in simpler cases also, such as the test case below.

A second potential test case may be found in the forum thread referenced previously.

Test case:

```rpy
image r = Solid('f77', xysize=(320, 320))
image r b = Solid('7ff', xysize=(320, 320))

label start:
    scene
    show r at renpy.partial(AlphaMask, mask=Transform('black', align=(.5, .5), rotate=45)):
        truecenter
    "This isn't persistent."
    show r b
    "Blue rectangle no longer masked."

    scene
    show r at Transform(zoom=.5):
        truecenter
    "But this is."
    show r b
    "Blue rectangle still scaled."
    return
```

**Comment by renpytom** [comment]
So, this example is invalid. Transform properties are what's propagated, not the entire at_list, and so the AlphaMask isn't going to get propagated for you. (Plausibly the at_list could be, but that is too big a change to make to Ren'Py at this point.) 

I think the issue in the forum thread is valid, so I'm going to look into what's causing it now.

**Comment by renpytom** [comment]
It looks like the forum thread's example isn't failing in 7.4.7, either.

**Comment by mal** [comment]
Ahh, that's unfortunate about the `AlphaMask`, but I guess the way to do that since `gl2` is to put s shader inside a `Transform` anyway, so maybe not too unfortunate.

As to the forum thread, a slight modification to the example (where the original author conceivably forgot to replace their real character name, `xviii`, with the more generic `character`) would seem to surface an issue:

```rpy
define _confirm_quit = False

label main_menu:
    return

transform midright:
    xcenter .66 yalign 1.0

transform top:
    xalign 0.5 yalign 0.0

# Set sprite size to 50%
transform downscale:
    zoom 0.5

# Fade the sprite for when a character isn't talking
transform faded:
    matrixcolor BrightnessMatrix(0.0)
    linear 0.5 matrixcolor BrightnessMatrix(-0.1)

# Undo sprite fading
transform unfade:
    matrixcolor BrightnessMatrix(-0.1)
    linear 0.5 matrixcolor BrightnessMatrix(0.0)

define character = Placeholder('girl')

label start:
    scene bg washington

    "Some text"

    show character neutral at midright, downscale, faded with dissolve

    "Some more text"

    show character sad at top, unfade

    "Some more text"

    show character depressed at faded # HERE: character forgets size in 7.4.6

    "Some final text"
```

**Comment by mal** [comment]
Simplified this down and tested on `7.4.7` (`nightly-2021-07-11-65d719eca-sdk`). I'm not sure if `at` lists are meant to yield idempotent results, so perhaps this is expected? At the very least it can be extremely confusing, and it only gets worse when using more complex transforms. 😦 

```rpy
define _confirm_quit = False

label main_menu:
    return

transform lookright:
    xzoom -1

transform noop:
    pass

image girl = Placeholder('girl')

label start:
    scene
    "lookright - lookright - lookright"
    show girl at lookright
    'Looking right.'
    show girl at lookright
    'Still looking right.'
    show girl at lookright
    'Yup, still looking right.'

    scene
    "lookright - lookright, noop - lookright"
    show girl at lookright
    'Looking right.'
    show girl at lookright, noop
    'Erk! Looking left now.'
    show girl at lookright
    'And back to right.'

    scene
    "lookright, noop - lookright - lookright, noop"
    show girl at lookright, noop
    'Looking right.'
    show girl at lookright
    'Still looking right.'
    show girl at lookright, noop
    'Erk! Looking again left now.'

    return
```

**Comment by Gouvernathor** [comment]
This is really weird.
Whatever the (detailed) logic behind this is, I believe it should be documented.
I guess it makes sense that some transform stuff need to be kept and some others dropped when a new `show` happens, but there should be precise information about which is which.

**Comment by renpytom** [comment]
Fundamentally, properties are being propagated from the outermost transform to the outermost transform, the second outermost transform to the second outermost transform, and so on, until we reach something thaty isn't a transform .

I believe that Mal's example is a pathological case that is confusing because it's using xzoom twice to create the double reversal. That's a bit unfortunate, but I'd say that going from single transforms to lists of transforms is always going to be a bit confusing. I don't think there's an actual bug here, just at the end of the day, the engine is powerful enough you can do confusing things with it.

**Comment by mal** [comment]
The example is certainly pathological, but only in order to clearly show the issue - I have seen many far more subtle real world cases of this (for instance where the impact of an `at` list changes depending on another `at` list two labels prior in a different file, but only when on certain choice branches). It often becomes much simpler to use inline transformations, and update those (which works much more as expected as there's only ever one), however the volume at which this becomes necessary ends up hurting not only developer and code sanity but also at high enough volumes, start up times.

Would it be conceivable to have a config level setting that would cause `at` statements to first condense their list into a single transform, before following the current code path, such that transform properties would all be merged/propagated within a single "pool", rather than rely on the reverse positional matching which in my experience is very difficult to communicate to less technical team members in such a way that they're able to use it without surprises and bugs?
