### ISSUE TITLE
Transitions block/wipe/lose pygame events

### ISSUE THREAD

**Issue by mal** [renpy/renpy#2861]
When using `renpy.queue_event` or `pygame.event.post` just before a transition the event gets lost and is never delivered.

The testcase below shows how this plays out with a custom event type, however this problem was initially encountered with events of type `renpy.display.core.EVENTNAME` issued by `renpy.queue_event` not arriving. This seems to work as expected during rollback/rollforward, when the transition skipping preference is set, or when reloading (in some cases, see testcase).

Observed on both 7.3.5 and 7.4.6.

```rpy
label main_menu:
    $ _confirm_quit = False
    return


init python early:
    import pygame_sdl2 as pygame

    CUSTOMEVENT = pygame.event.register('CUSTOM')

    config.pygame_events += [CUSTOMEVENT]

    def emit(name, **kwargs):
        kwargs['name'] = name
        ev = pygame.event.Event(CUSTOMEVENT, kwargs)
        pygame.event.post(ev)


init python:
    from collections import deque


    class Example(Text):
        def __init__(self):
            header = 'Log started!'
            self.log = deque((header,), maxlen=15)
            return super(Example, self).__init__(header)

        def event(self, ev, x, y, st):
            if ev.type == CUSTOMEVENT:
                self.log.append(repr(ev).replace('{', '{{'))
                self.set_text('\n'.join(self.log))
            return super(Example, self).event(ev, x, y, st)


label start:
    scene black
    show expression Example() as log at reset
    "Logging events!"
    $ renpy.block_rollback() # prevent accidentally wiping log during rollback

    $ emit('custom', info='this event gets logged! :D')
    "Event logged."

    $ emit('custom', info='this event is lost! D:', trans='inline')
    "Event not logged. But reloading here logs it." with pixellate

    pause

    $ emit('custom', info='this event is lost! D:', trans='dict')
    with {'master': pixellate}
    "Event not logged. But reloading here logs it."

    pause

    $ emit('custom', info='this event is lost! D:', trans='global')
    with pixellate
    "Event not logged. Reloading here DOES NOT log it!"

    pause

    "Now rollback (and forward) will trigger lost events. Transitons skipped?"

    "Fin."

    return
```

**Comment by renpytom** [comment]
Transitions are supposed to block events. We're not going to let a user click on a button that isn't visible.

**Comment by mal** [comment]
Hmm, that makes sense.

The use case I'm interested in is being able to post an event that a CDD (if present) could listen for and react to, but it not be dependent on the CDD being present. It would be possible to build a completely out-of-band pub-sub type system to accomplish this, but using the existing event infrastructure with custom events felt more elegant. Is adding a list to the `config` namespace where custom events that should not be cancelled by transitions could be registered something you would consider accepting/adding?

**Comment by mal** [comment]
I took a naive pass at this to get an idea for how invasive it might be to pull off, turned out not too bad:
- Added `config.transition_events` as a `list`.
- Added `TIMEEVENT` to it in `config.init()`
- Replaced conditions in `Transition` and `MultiTransition`
  ```diff
  -ev.type == TIMEEVENT
  +ev.type in renpy.config.transition_events
  ```

Unfortunately however, even after this, for the use case to work as expected the event also needed to be dispatched to the `old_widget`, which is definitely the point at which I'm uncomfortably out of my depth about any potential ramifications. 😞

**Comment by renpytom** [comment]
The answer is no, that isn't something I want for Ren'Py, because I think it's a giant footgun, and I really don't want to have to deal with a world where creators are posting arbitrary events to the queue.  Doing something out of band is the way to go, since It's something you can support yourself, and not something that will need to be considered each time Ren'Py is changed. 

This feels like something that would be both hard to keep working, and little used, and that really feels like a dangerous combination.
