### ISSUE TITLE
Translation files generation problems.

### ISSUE THREAD

**Issue by H4M5TER** [renpy/renpy#2862]
The SDK doesn't mark say statement with speaker in menu block as translatable.

**Comment by renpytom** [comment]
Can you post what it looks like in your game?

**Comment by H4M5TER** [comment]
Code <https://github.com/ponytranz/FwBCN/blob/main/game/1prologue.rpy#L1218>
![QQ图片20210625224054](https://user-images.githubusercontent.com/21092951/123462624-2484a300-d61d-11eb-9fd2-8413f4cd05cb.png)

**Comment by renpytom** [comment]
I haven't been able to repeat this, using Ren'Py 7.4.7 nightly. I downloaded the game from github, translated it, and the line was generated for both piglatin and chinese.

**Comment by H4M5TER** [comment]
using Ren'Py 7.4.6 on the official website.
It's weird that I generated new strings on the 'main' branch but nothing on the 'empty' branch.
I had compared ‘/game/*.rpy’ files between two branches and the only difference is on 'y-screens.rpy' which I added a vbox to select language.

**Comment by H4M5TER** [comment]
Digression:

There are many blank strings on the file `artgallery.rpy` and Ren`Py decided to generate it. Is this expectable?
I read the document and it says:

> https://www.renpy.org/doc/html/translation.html#tips
> Adding labels can also confuse the translation process. To prevent this, labels that are given the hide clause are ignored when generating translations.:
> ```renpy
> label ignored_by_translation hide:
>     "..."
> ```

Is it required to have a label to mark the string hide? And how to mark a string hide anyway.

**Comment by renpytom** [comment]
> There are many blank strings on the file artgallery.rpy and Ren`Py decided to generate it. Is this expectable?

Yes, assuming it's dialogue.  If it's marked with ``_(*")``, then it should only be generated once. 

> Is it required to have a label to mark the string hide? And how to mark a string hide anyway.

No. The only time you'd have a label marked as hide is if it's added after translations are first created.

**Comment by renpytom** [comment]
Closing this, as I'm not sure what else there is to do.

**Comment by H4M5TER** [comment]
What's the meaning of `_(*“)`, I didn't see it on the [document](https://www.renpy.org/doc/html/translation.html?highlight=_#translation-actions-functions-and-variables).
It's very weird that I generated the missing string on the `empty` branch today since I can't generate it before and the Ren'Py version is not changed.

**Comment by H4M5TER** [comment]
It seems like when I do a clean generate those strings would no be generated.
For some information:
They are both menu dialog with speaker and there are additional `nointeract` generated which like `character "str" nointeract`.
There are no `nointeract` on the [code](https://github.com/ponytranz/FwBCN/blob/main/game/library.rpy#L1569) though there is on the comment.

```renpy
# game/library.rpy:1569
translate chinese lilystandingsex_95e96f19:

    # penelope "That you are. Anything you can tell me about Lily?" nointeract
    penelope "" nointeract
```

**Comment by H4M5TER** [comment]
@renpytom 
bump

**Comment by renpytom** [comment]
I don't know what the problem here is.

**Comment by H4M5TER** [comment]
I will make time to modify the Tutorial project and try to reproduce this.

Can you reproduce this on my repo?
For clean generation:
Delete `game/tl/` and generate. There will be only timestamp difference. And no difference with `node .\convert_paratranz.js && node .\reconvert_paratranz.js` done. (I use GitKraken to see difference)
And then generate again:
There will be new string on `1prologue.rpy`, `forest.rpy` and `library.rpy`.

> What's the meaning of `_(*“)`

And how about this question

**Comment by renpytom** [comment]
Closing, as I haven't been able to repeat this.

**Comment by marylloup** [comment]
I found a way to make it work if anyone is interested ! 
1) when you have a dialogue line in a menu it allows the line to be shown at the same time as the menu options.
2) when you generate translations for this particular line of dialogue inside a menu, it creates a line with the "nointeract" mention and just translating it like that could create some problems. 
3) to make it work like in the original language you have to write your translation line like this : 
```
# game/***
translate LANGUAGE IDENTIFIER:

        #"line of dialogue in the original language"
        character "line of dialogue ine the new language" nointeract
```
