### ISSUE TITLE
When gl2 is enabled on Android, FileScreenShot prints incorrect screenshots.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2863]
When gl2 is enabled on Android, FileScreenShot prints incorrect screenshots.
Tested with Ren'py 7.4.6 and Samsung Note10.

**Comment by renpytom** [comment]
I'm unable to get this to occur on my Pixel 5 and my Galaxy S10e. 

Does it happen with The Question, or is it something game-specific?

**Comment by renpytom** [comment]
Closing, since I can't repeat this on multiple devices.
