### ISSUE TITLE
Imagebutton does not work (directly) with animated image

### ISSUE THREAD

**Issue by tornsoul** [renpy/renpy#2864]
The following code does not work - And will simply show the last image of the animation (and not the first)

```
image picr = Fixed(Solid("F00", xysize=(60, 60)), xysize=(64,64))
image picw = Fixed(Solid("FFF", xysize=(60, 60)), xysize=(64,64))

image pic_animate:
    "picr"
    1.0
    "picw"

screen test_grid():
    imagebutton idle "pic_animate"
```

To make it work - one has to "wrap" the animated image in another image.
And then the animation is displayed.

```
image picr = Fixed(Solid("F00", xysize=(60, 60)), xysize=(64,64))
image picw = Fixed(Solid("FFF", xysize=(60, 60)), xysize=(64,64))

image pic_animate:
    "picr"
    1.0
    "picw"

image pic_animate_wrapper: #pic_animate won't work if used directly for some reason...???
    "pic_animate"
    
screen test_grid():
    imagebutton idle "pic_animate_wrapper"
```

Sure the workaround works - But it seems like a bug it doesn't work in the first place (without the wrapper)?

**Comment by tornsoul** [comment]
I'm using renpy-7.4.4-sdk

To show I do 

```
label test_it:
    "Ready to test"
    show screen test_grid
    "Grid should be visible now"
    return
```

**Comment by AndriWilford** [comment]
Hmm, this still seems to work for me.

To confirm, did you mean to have a 'repeat' statement in the image, or is it meant to only run through the two displays once?
```
image pic_animate:
    "picr"
    1.0
    "picw"
    repeat
```

**Comment by tornsoul** [comment]
No repeat.
Show run through just once (showing two pictures)

**Comment by AndriWilford** [comment]
Done in 7.4.4.  Full script ofd test.

Is this not what you see?
```
define e = Character("Eileen")

image picr = Fixed(Solid("F00", xysize=(60, 60)), xysize=(64,64))
image picw = Fixed(Solid("FFF", xysize=(60, 60)), xysize=(64,64))

image pic_animate:
    "picr"
    1.0
    "picw"

screen test_grid():
    imagebutton idle "pic_animate"

label test_it:
    "Ready to test"
    show screen test_grid
    "Grid should be visible now"
    return

label start:
    scene bg room
    e "You've created a new Ren'Py game."
    call test_it
    e "Once you add a story, pictures, and music, you can release it to the world!"
    hide screen test_grid
    e "hiding"
    call test_it
    e "final"
    return
 ```
 
 

https://user-images.githubusercontent.com/78317052/122788791-504e0480-d27c-11eb-8859-aff6e52cade0.mp4

**Comment by tornsoul** [comment]
I've created a completely blank project - and copied the code you've shown.
And it now works as expected.

Which leaves me baffled... 
My other sandbox (where it doesn't work) do have other simple test bits in it - But bits that really should not influence this.
Apparently I'm wrong - I'll try to dig in and let you know if I find out why (could be useful for bug finding - if this shows up again)

Thanks for the very prompt and thorough look at this.

I'm closing this - But will comment if I figure out why it doesn't work in my other sandbox.
You have to admit it's a weird behavior in the first place :-) (regardless what causes it)

**Comment by tornsoul** [comment]
New code - In a clean sandbox (7.4.4) with nothing else going on.
```

image picr = Fixed(Solid("F00", xysize=(60, 60)), xysize=(64,64))
image picg = Fixed(Solid("0F0", xysize=(60, 60)), xysize=(64,64))
image picb = Fixed(Solid("00F", xysize=(60, 60)), xysize=(64,64))
image picw = Fixed(Solid("FFF", xysize=(60, 60)), xysize=(64,64))
image picy = Fixed(Solid("F0F", xysize=(60, 60)), xysize=(64,64))

image pic_animate:
    "picr"
    1.0
    "picw"

image pic_animate2:
    "picr"
    1.0
    "picw"

image pic_animate_wrapper: #pic_animate won't work if used directly for some reason...???
    "pic_animate"

image pic_animate_wrapper2: #pic_animate won't work if used directly for some reason...???
    "pic_animate"

init python:
    pics = ['picr', 'picg', 'picb', 'picw', 'pic_animate', 'pic_animate2']
    #pics = ['picr', 'picg', 'picb', 'picw', 'pic_animate_wrapper', 'pic_animate_wrapper2']
    piclist = [
        [4,1],
        [1,1]
    ]
    dim = [len(piclist[0]), len(piclist)]

    def update_pics(x,y, button):
        global piclist
        if (button == "left"): #left click
            #asd = 1/0 #uncomment to verify that we actaully do get here (game will crash)
            #toggle between 4 and 5 (which actually do the same thing) to make renpy detect a change
            newValue = (((piclist[y][x] - 4) + 1) % 2) + 4 #the actual value will depend on gamestate - but hardcoded for this example
        else: #right click
            newValue = 2 #the actual value will depend on gamestate - but hardcoded for this example
        piclist[y][x] = newValue


screen test_grid():
    grid dim[0] dim[1]:
        for y, row in enumerate(piclist):
            for x, tile_index in enumerate(row):
                imagebutton:
                    idle pics[tile_index]
                    action Function(update_pics, x, y, "left")
                    alternate Function(update_pics, x, y, "right")

screen test_ib():
    imagebutton idle "pic_animate" action NullAction()

label test_it:
    "Ready to test ib"
    show screen test_ib
    "Ready to test"
    show screen test_grid
    "Grid should be visible now"
    return


label start:
    call test_it
    return

```

`show screen test_ib`:
- Expected behaviour: 
Animation runs.
- Result: 
As expected.

All is good (But I'm still baffled why this didn't work before - Can't figure it out. Ascribe to user error...)

`show screen test_grid`:
_Step1_
- Expected behavior:
Grid of 4 squares should show. First one should run the animation on load - The other 3 should be green
- Result
As expected.

_Step 2a_
- Expected behavior:
Left click a square, to have the animation run in that square (regardless of former content)
- Result
Only the last frame of the animation is shown.
Clicking white square - It stays white (no red showing)
Clicking green square - It simply changes to white (the last frame of the animation) (with no red showing)

Comment out/delete the existing `pics` list definition and uncomment the `pics` list definition containing the `pic_animate_wapper`s (line 24/25)

Step 2b
- Expected behavior:
Left click a square, to have the animation run in that square (regardless of former content)
- Result
It now works - Animation is run on left click, regardless of previous content of the square.
Use right-click to switch to a blue square, and it still works.
Some weird behaviors though - see below

Notes:
For the animation to work in scenario 2b - The image animation was wrapped in another image.
Otherwise only the last image of the animation is shown.

Also - Renpy needs to be "tricked" into registering a change, on running the animation - if the animation was the original content of the square (hence why pic_animate_wrapper is duplicated).
If the value (4) is not changed (to 5), and simply assigned (4) again -  Renpy will assume nothing has changed and not run the animation again (is what I'm guessing is going on)

_Weird behaviors_ (step 2b)
Left click - Keep the mouse over the square until end of animation.
Then move the mouse outside the square - And the animation runs again???
That is not supposed to happen.

Left click - Move mouse outside square and back again, before animation ends - and hold mouse there until animation ends.
Then move the mouse outside the square - And the animation does *not* run in this case.

**Comment by renpytom** [comment]
40fdecc0e fixes everything but the weird behavior, which I think I understand, and need to figure out how to fix.
