### ISSUE TITLE
Disable substitutions for any definite string

### ISSUE THREAD

**Issue by Eliont** [renpy/renpy#2867]
Hello and good time of day. I need to read many different files, some with square brackets in their names by absolute path outside of game folder. I have have no rights to change files names or location.

There are  **substitute False** text property, but it is not working in example for **add "path/to/image/file"** like statements.

Currently achieved goal by substituting substitute function, but maybe there are cleaner way that will persist through engine version updates ?

Thanks in advance.

```
  def substitute(s, scope=None, force=False, translate=True):
      if not isinstance(s, basestring):
          s = str(s)

      if translate:
          s = renpy.translation.translate_string(s)

      if not renpy.config.new_substitutions and not force:
          return s, False

      if "[" not in s:
          return s, False
          
      # String starts like "C:", "D:"
      if s[0].isupper() and s[1] == ':':
          scope = dict()
          for sub in re.findall(r"[^[]*\[([^]]*)\]", s):
              scope[sub] = sub
          
      old_s = s

      if scope is not None:
          kwargs = renpy.substitutions.MultipleDict(scope, renpy.store.__dict__)
      else:
          kwargs = renpy.store.__dict__
          
      try:
          s = renpy.substitutions.formatter.vformat(s, (), kwargs)
      except:
          if renpy.display.predict.predicting:
              return " ", True
          raise

      return s, (s != old_s)
      
  renpy.substitutions.substitute = substitute
```

**Comment by renpytom** [comment]
You can quote [ by writing [[. 

I'd strongly recommend against probing the player's system for random files like this.

**Comment by Eliont** [comment]
> You can quote [ by writing [[.
> 
> I'd strongly recommend against probing the player's system for random files like this.

Not working, still getting error.
basic filename: Exception: In DynamicImage u'...': NameError(u"Name '...' is not defined.",)
escaped ( [[ ): Exception: In DynamicImage u'...': Could not find substitution '...'.

Files not random, its like intergame mods system.

**Comment by renpytom** [comment]
Sorry, but without the actual errors, I don't think I can diagnose this. 

Ren'Py expects all files the game accesses to live under game/, so I'd suggest figuring out a way to enable mods that respects that.

**Comment by Eliont** [comment]
Is there any way to make **add "%s"%mod.iconfile align (0.01,0.5)  substitute False** works ?
Currently ity says  **u'substitute' is not a keyword argument or valid child for the add statement.**

**Comment by renpytom** [comment]
I'm not really planning on doing this, since add just takes a displayable, and displayables do substitutions like this. You can, if you want, quote special characters with something like mod.iconfile.replace("[", "[[").
