### ISSUE TITLE
arm64 libs

### ISSUE THREAD

**Issue by mizzunet** [renpy/renpy#2868]
I'm trying to play a renpy game on arm64 however the game doesn't come with libs for arm64, and it says missing lib/aarch64. And libs folder has libs for other architectures. How do I play this? Where can I get the files? So I could be able to put inside new folder called aarch64

**Comment by renpytom** [comment]
What system are you running on? Right now, Ren'Py only supports aarch64 for Android and iOS.

**Comment by mizzunet** [comment]
Ubuntu inside Android using termux

**Comment by renpytom** [comment]
Oh, that isn't a supported platform, and isn't likely to be. Aarch64 is likely to be a platform I support sooner rather than later, but it'll be targeted at Raspis and chromebooks.

**Comment by mizzunet** [comment]
Oh. But I wonder how renpy android work then? Don't they need these libs too?

**Comment by renpytom** [comment]
They have them, but android proper has a very different userspace than more mainstream Linux.

**Comment by mizzunet** [comment]
I see
