### ISSUE TITLE
Error when generating translation files

### ISSUE THREAD

**Issue by ChesterCheshireCat** [renpy/renpy#2874]
Here is my line of code in the original script:

`agathe "HAHAHA !" (490, 500, "lefttop", show_xmax=750) with hpunch`

![code-original](https://user-images.githubusercontent.com/40180356/123661108-92ef7e00-d834-11eb-94a2-7b48b61a23a0.PNG)

And here is the same line, generated by the translation file:

`# agathe "HAHAHA !" with hpunch (490, 500, "lefttop", show_xmax=750)
agathe "HAHAHA!" with hpunch (490, 500, "lefttop", show_xmax=750)`

![code-translation](https://user-images.githubusercontent.com/40180356/123661414-ccc08480-d834-11eb-93a7-814ba3492633.PNG)

As you can see, it automatically inverts the "with hpunch" position and the "(490, 500, "lefttop", show_xmax=750)" one, resulting in this error:

![error](https://user-images.githubusercontent.com/40180356/123661672-085b4e80-d835-11eb-903e-7ea0e2f84ad1.PNG)

`I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tl/english/custom scripts/chapters/01 Prologue.rpy", line 1029, in script
    agathe "HAHAHA!" with hpunch (490, 500, "lefttop", show_xmax=750)
  File "game/tl/english/custom scripts/chapters/01 Prologue.rpy", line 1029, in <module>
    agathe "HAHAHA!" with hpunch (490, 500, "lefttop", show_xmax=750)
TypeError: Move() got multiple values for keyword argument 'repeat'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/tl/english/custom scripts/chapters/01 Prologue.rpy", line 1029, in script
    agathe "HAHAHA!" with hpunch (490, 500, "lefttop", show_xmax=750)
  File "renpy/ast.py", line 714, in execute
    say_menu_with(self.with_, renpy.game.interface.set_transition)
  File "renpy/ast.py", line 538, in say_menu_with
    what = renpy.python.py_eval(expression)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/tl/english/custom scripts/chapters/01 Prologue.rpy", line 1029, in <module>
    agathe "HAHAHA!" with hpunch (490, 500, "lefttop", show_xmax=750)
  File "renpy/curry.py", line 48, in __call__
    return self.callable(*(self.args + args), **merged_kwargs)
TypeError: Move() got multiple values for keyword argument 'repeat'

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
La Faille 1.0
Mon Jun 28 17:13:36 2021`

I hope this will help to fix the issue. :)

**Comment by Gouvernathor** [comment]
The exception comes from the fact that renpy's code parsing (just like python) ignores spaces before parentheses and calls `hpunch` like a function.
So the only point of failure here would be the permutation of the args with the `with` clause on translation generation.
