### ISSUE TITLE
The Audio documentation does not take into account the audio folder and auto-import

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2875]
Since the audio folder was added, the Audio documentation at https://www.renpy.org/doc/html/audio.html was never updated.

The presence of the audio folder encourages users to place their audio files in there, but the examples on the Audio documentation page will not work because they do not include the "audio/" path.

The documentation should mention the auto-import feature of the audio folder and the examples should be updated accordingly.

`play music filename`
vs
`play music "audio/filename.ogg"`

**Comment by renpytom** [comment]
You're right. 

I've documented this a little better in the quickstart and the audio documentation.
