### ISSUE TITLE
ui.adjustments ranged function is called twice (instead of once)

### ISSUE THREAD

**Issue by tornsoul** [renpy/renpy#2876]
Renpy 7.4.4 - Sandbox with only the code below

`ui.adjustments` `ranged` function is called twice on range change.
Expected behavior would be just one call (after change)

A minimal code example below.

Each zoom leaves two entries in the `bucket` (inspect via shift+o)
Judging by the values in the `bucket` it looks as if `ranged` is called both before change and after change.

```

init python:
    adjx = ui.adjustment()
    adjy = ui.adjustment()
    zoomlvl = 1.0
    bucket = []

    def y_range_changed(adjy):
        bucket.append((adjy.value, adjy.range))

image testimg = Solid("0F0", xysize=(5000, 5000))

screen img_screen(zoomlvl):
    add "testimg":
        zoom zoomlvl
        xalign 0.5
        yalign 0.5

screen vp():
    $ zoomdelta = 0.02
    $ zoomdeltaplus = zoomlvl + zoomdelta
    $ zoomdeltaminus = max(zoomlvl - zoomdelta, zoomdelta)

    $ adjy.ranged = y_range_changed

    viewport:
        area (0, 0, 500 + gui.scrollbar_size, 500 + gui.scrollbar_size)
        scrollbars "both"
        child_size (5000 * zoomlvl, 5000 * zoomlvl)

        xadjustment adjx
        yadjustment adjy

        use img_screen(zoomlvl)

        key "mousedown_4" action [SetVariable("zoomlvl", zoomdeltaplus)]
        key "mousedown_5" action [SetVariable("zoomlvl", zoomdeltaminus)]

label start:
    call screen vp
```

**Comment by renpytom** [comment]
I don't consider this a bug.

**Comment by tornsoul** [comment]
If not a bug - It would be nice to have mentioned in the documentation that it happens.
It's definitely a nice capability to have (i.e. catching both before and after)

Personally I'd prefer two different "events to subscribe" to - before and after change.
Seems a bit messy to have both go to the same subscriber function  - and it add's extra code to differentiate between the two, which is an annoyance if you are only interested in one of them ymmw ofc.

**Comment by renpytom** [comment]
I've mentioned it. The way I see it, ranged is there to make it possible to find out the current value of range might have changed. It's not an "event" like you might be thinking.
