### ISSUE TITLE
[7.4.6] ATL is not working.

### ISSUE THREAD

**Issue by ikusorae** [renpy/renpy#2877]
In Ren'py 7.4.6, transform that using ATL does not work.
It works in the UI, but not in the image after starting the game.

**Comment by renpytom** [comment]
Can you elaborate? This isn't a useful report.

**Comment by ikusorae** [comment]
I used this source:

```
transform circlemove:
    on show:
        xpos 50
        ypos 50
        linear 2.0 xpos 200 ypos 300



label start:

    e "test1"
    show circle at circlemove
    e "test2"

    return
```

7.4.5:

https://user-images.githubusercontent.com/60040734/124123878-bde70580-dab2-11eb-9ea7-5cb9a01391f7.mp4



7.4.6:


https://user-images.githubusercontent.com/60040734/124123905-c4757d00-dab2-11eb-80db-cd54fad75707.mp4

In 7.4.6, it just stands still and doesn't move.

**Comment by AndriWilford** [comment]
I believe this is a duplicate of https://github.com/renpy/renpy/issues/2860

**Comment by renpytom** [comment]
I'm pretty sure this is fixed in the nightlies, so closing it.
