### ISSUE TITLE
[7.4.6] Atom won't open

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#2878]
Since the last update, I can't open files through the launcher anymore.

**Comment by renpytom** [comment]
Whay type of computer do you have? 32 or 64-bit?

**Comment by kigyo** [comment]
64-bit, Windows 10. 
And just to double-check, reverting to 7.4.5 fixed it for me.

**Comment by renpytom** [comment]
If you go into the atom folder and run the exe, does it work for you?

**Comment by kigyo** [comment]
The one in my 7.4.6 folder refuses to launch. 
I've also noticed it's missing a lot of the "api-ms-win-[stuff]" files that are present in the 7.4.5 folder.

**Comment by renpytom** [comment]
Hm... are you fully up to date on your Windows 10? It sounds like you're missing some of the microsoft libraries.

**Comment by kigyo** [comment]
I just checked, and my computer is fully updated. 
The same exact issue also occurs on my laptop (Windows 10 as well), so I'm not sure if my computer is the problem.
Atom works completely fine on 7.4.5, but updating to 7.4.6 breaks it every time.

**Comment by renpytom** [comment]
It started failing here.

**Comment by MiiNiPaa** [comment]
Had the same problem. Complete reinstall (delete atom folder, redownload through launcher) fixed it for me.

**Comment by renpytom** [comment]
I've updated Atom, so hopefully this will be fixed in 7.4.7. I'll leave this open until the release.
