### ISSUE TITLE
[7.x.x] Bug in the main menu music when reloading.

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#2880]
Note that when reloading the game with "Shift+R" in the main menu, there is a possibility that the same music will play twice on top of each other.

In game, I don't encounter this bug, but it is possible that it happens too.

**Comment by Gouvernathor** [comment]
Relatable, happens to me too. Thought it may be related to #2468, but maybe not.

**Comment by Neyunse** [comment]
I tried this, but it keeps happening, I think something is going on in the renpy reload part.
```
label before_main_menu:
    stop music
    play music config.main_menu_music
    return
```

**Comment by renpytom** [comment]
I haven't been able to repeat this - the story of tonight. Can someone put together a short example that exhibits this problem when reloading the main menu?

**Comment by Neyunse** [comment]
> 
> 
> I haven't been able to repeat this - the story of tonight. Can someone put together a short example that exhibits this problem when reloading the main menu?

It usually happens after an exception, and if you are using VScode with autosave while editing the file, there is a chance that it will appear.

I'will Try to recreate it

**Comment by Neyunse** [comment]
> 
> 
> I haven't been able to repeat this - the story of tonight. Can someone put together a short example that exhibits this problem when reloading the main menu?
@renpytom 
As I said, it usually comes up after an exception or when reloading the game in the main menu. 
I would say that it happens 6% or 9% of the time (if you are in the main menu), there are times that I don't often reload, and it usually happens.
Also, if the bug appeared, and you close the game, there is a small chance that it will appear when you run the game. (That's what happened to me, I had to make a second video because I couldn't hear the audio well).

Here is the video (piano plays twice)
https://drive.google.com/file/d/1jH_xThjfLufGxgVcclsrtXAILJNBiN6k/preview

**Comment by renpytom** [comment]
I don't have a good idea of what's going on here. 

I will stay that it's probably a bad idea to play the config music in label ``label before_main_menu:`` - I'd either play your own music there, or let Ren'Py play it, but reusing the config variable is a bad idea. 

Also, I don't have access to your example video.

**Comment by Neyunse** [comment]
> 
> 
> I don't have a good idea of what's going on here.
> 
> I will stay that it's probably a bad idea to play the config music in label `label before_main_menu:` - I'd either play your own music there, or let Ren'Py play it, but reusing the config variable is a bad idea.
> 
> Also, I don't have access to your example video.

new url https://drive.google.com/file/d/1jH_xThjfLufGxgVcclsrtXAILJNBiN6k/view?usp=sharing

**Comment by renpytom** [comment]
I've been unable to repeat this.
