### ISSUE TITLE
SIGBUS on Android 11

### ISSUE THREAD

**Issue by Poriy52863** [renpy/renpy#2883]
**Ren'Py 7.4.5.1602**

07-02 09:48:38.840 F/DEBUG   (11804): Softversion: PD1901EF_EX_A_6.12.7
07-02 09:48:38.840 F/DEBUG   (11804): Time: 2021-07-02 09:48:38
07-02 09:48:38.840 F/DEBUG   (11804): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-02 09:48:38.840 F/DEBUG   (11804): Build fingerprint: 'vivo/1904/1904:11/RP1A.200720.012/compiler0619205317:user/release-keys'
07-02 09:48:38.840 F/DEBUG   (11804): Revision: '0'
07-02 09:48:38.840 F/DEBUG   (11804): ABI: 'arm64'
07-02 09:48:38.840 F/DEBUG   (11804): Timestamp: 2021-07-02 09:48:38+0700
07-02 09:48:38.841 F/DEBUG   (11804): pid: 11356, tid: 11460, name: SDLThread  >>> package.name <<<
07-02 09:48:38.841 F/DEBUG   (11804): uid: 13734
07-02 09:48:38.841 F/DEBUG   (11804): signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x7159912000
07-02 09:48:38.841 F/DEBUG   (11804):     x0  000000704f542124  x1  0000007159912000  x2  000000000000004e  x3  0000000000000017
07-02 09:48:38.841 F/DEBUG   (11804):     x4  0000000000000004  x5  000000704f542024  x6  00000070639f78e8  x7  000000000000004e
07-02 09:48:38.841 F/DEBUG   (11804):     x8  0000000000000000  x9  000000000000004f  x10 0000000000000040  x11 000000000000009d
07-02 09:48:38.841 F/DEBUG   (11804):     x12 0000000000000000  x13 0000000000000000  x14 0000000000000005  x15 0000000000000000
07-02 09:48:38.841 F/DEBUG   (11804):     x16 0000000000000000  x17 0000000000000007  x18 000000706341a000  x19 0000000000000800
07-02 09:48:38.841 F/DEBUG   (11804):     x20 0000007159912000  x21 0000000000000000  x22 0000000000000000  x23 000000000000004e
07-02 09:48:38.841 F/DEBUG   (11804):     x24 000000704f542124  x25 0000007159912000  x26 0000000000000040  x27 000000000000004e
07-02 09:48:38.841 F/DEBUG   (11804):     x28 0000000000000400  x29 00000070639f7930
07-02 09:48:38.841 F/DEBUG   (11804):     lr  00000070b3f25b4c  sp  00000070639f7810  pc  00000070b3f2a79c  pst 0000000080000000
07-02 09:48:38.881 F/DEBUG   (11804): backtrace:
07-02 09:48:38.881 F/DEBUG   (11804):       #00 pc 00000000001a879c  /vendor/lib64/egl/libGLESv2_mtk.so (BuildId: 6a7692887300cd2044a9c6597dc6ea5e)
07-02 09:48:38.881 F/DEBUG   (11804):       #01 pc 00000000001a3b48  /vendor/lib64/egl/libGLESv2_mtk.so (BuildId: 6a7692887300cd2044a9c6597dc6ea5e)
07-02 09:48:38.881 F/DEBUG   (11804):       #02 pc 000000000012feac  /vendor/lib64/egl/libGLESv2_mtk.so (BuildId: 6a7692887300cd2044a9c6597dc6ea5e)
07-02 09:48:38.882 F/DEBUG   (11804):       #03 pc 000000000012e6f0  /vendor/lib64/egl/libGLESv2_mtk.so (glTexImage2D+320) (BuildId: 6a7692887300cd2044a9c6597dc6ea5e)
07-02 09:48:38.882 F/DEBUG   (11804):       #04 pc 0000000000092524  /vendor/lib64/egl/libGLES_meow.so (MEOW::meow_call_ddk_gl_2_glTexImage2D(unsigned int, int, int, int, int, int, unsigned int, unsigned int, void const*)+44) (BuildId: df003561794da3c12717b89f41ad59e0)
07-02 09:48:38.882 F/DEBUG   (11804):       #05 pc 00000000005cc1c0  /data/app/~~a0n3uMZNuCWfolfmaUgxQw==/package.name-DZf-YwFbhYuQs3EFdNiN1g==/lib/arm64/librenpython.so

**Comment by renpytom** [comment]
Can you please break this down into a small game that exhibits the problem?

**Comment by renpytom** [comment]
Also, could you please update to Ren'Py 7.4.6? Thanks.

**Comment by Poriy52863** [comment]
I'm sorry. Actually this is not own game.

Also I've tried some game that use Ren'Py 7.4.6.1693 and still got the same logcat output.

I've give the developer of the game my feedback about it and they still didn't give me an answer. So i thought maybe i can get an answer if post an issue in here! 

 When i play  the game that using Ren'Py 7.3.* i got no problem running the game on my phone.

Sorry for my bad English though.

Thanks for your reply.

**Comment by Poriy52863** [comment]
Hey, I'm sorry if I'm asking too much.

Did you by any chance have a test game that has been build the Ren'Py 7.4.*? 

I don't own a PC/Laptop with me.

I want to see if there's any different.

I'm using Android 11 BETA version btw. Does it could be the problem? 

Once again, I'm sorry if I'm asking too much.

**Comment by Poriy52863** [comment]
Here's one of the same game that I'm played that using different version of Ren'Py

> [Build with Ren'Py 7.3.5.606](https://mega.nz/file/P8w1AarT#CPzu8MCkQdwO9VfXAXn_-mJ_KuSEpERdv4MAAgR7lU8) this was the one that worked

> [Build with Ren'Py 7.4.6.1693](https://mega.nz/file/w4wmxD7A#KVgoKpVr0CelKqAx1Sd2GDhVDbk6duHXC8os9MzssgI) and this one is didn't work.

**Comment by renpytom** [comment]
At this point, I think we'd have to loop the game's developer in to work with you to figure out what's crashing. I'd love to help you, but without someone to narrow this down to a few lines of script, I'm kind of limited to what I can do.

**Comment by Poriy52863** [comment]
Oh that's alright, i think I'm just gonna wait for my Android version got an update of the final version of Android 11.

Thanks for your time :)
And have a good day .
