### ISSUE TITLE
Game crashes while playing

### ISSUE THREAD

**Issue by stranger54321** [renpy/renpy#2884]
Game : My Pleasure v0.14-elite
Attachments : log from Ren'Py and logcat from adb
Android : 11
Issues : Game crashes while playing, sometimes it also crashes while in the Main Menu.
Game:[Download ](https://mega.nz/file/w4wmxD7A#KVgoKpVr0CelKqAx1Sd2GDhVDbk6duHXC8os9MzssgI)  

[2021-07-02-10-45-01.txt](https://github.com/renpy/renpy/files/6752342/2021-07-02-10-45-01.txt)
[log-1.txt](https://github.com/renpy/renpy/files/6752343/log-1.txt)

**Comment by renpytom** [comment]
Works for me, on my Pixel 5.

Can you figure out which image it's causing the crash on?

**Comment by stranger54321** [comment]
> Works for me, on my Pixel 5.
> 
> Can you figure out which image it's causing the crash on?

No. There was no traceback

**Comment by renpytom** [comment]
You'll have to use process of elimination to figure it out, since if I can't repeat it here, there's not much I can do.
