### ISSUE TITLE
Update Renpy on Ubuntu

### ISSUE THREAD

**Issue by CanasDev** [renpy/renpy#2885]
Update renpy version to Ubuntu please 
It's still in an old version

**Comment by Evernow** [comment]
Why is it up to Renpy to update it? Renpy repository is up to date.

**Comment by renpytom** [comment]
Unfortunately, this isn't really something I can take care of. The good news is that I develop Ren'Py on ubuntu, and so the version from https://www.renpy.org/latest.html should run well.
