### ISSUE TITLE
Default Python function for Android notifications in Renpy

### ISSUE THREAD

**Issue by littlebird007199** [renpy/renpy#2889]
So we know that we can create Android notifications by calling JAVA functions via pyjinus library.
But we need to do some extra work in Android Studio which is a drawback.
If Ren'Py could generate files with the required JAVA classes and methods for Android notification system while exporting with RAPT, we could skip the whole process that otherwise has to be done in Android Studio.
If Ren'Py could do that, we can just import pyjinus and create Android notifications as easy as:
`$ PythonSDLActivity.myNotification(“Your notification text”, index, minutes)`

I am not an expert and this feature might be more complicated than my little brain can think of.
But if it was as easy as calling a Python function, I would be so happy and I bet many of the VN developers would be happy.
The article that I read about this whole thing : [[Tutorial] Expanding Mobile Functionality With Pyobjus/Pyjnius (Notifications)](https://lemmasoft.renai.us/forums/viewtopic.php?f=51&t=46091)

**Comment by renpytom** [comment]
I don't have any plans for this. 

A big problem is that Ren'Py game can have multiple saves, and when the game isn't running, it's not clear which save the gamer should go to if the notification is clicked.

**Comment by littlebird007199** [comment]
That makes sense. As for me, my game is based on persistent values so the player don't have to rely on save slots but if we consider multiple save slots, the notifications might get mixed up. Thank you for your response for this issue.
