### ISSUE TITLE
[Feature Request] size transform property should accept positions instead of ints

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2895]
Currently, `Transform(size=(100.0, 100.0))(Solid("#f00"))` amounts to a red 100x100px square.
There is no actual way of telling a displayable to take half or any fraction of the available room as height or width.
With a Solid `crop_relative` could be used but not for a proper image.
`xzoom=.5` would tell it to take half of its native size, not half of the maximum available size.

I think it could be a nice (retro-incompatible) addition to enable floats in `size`, `xsize` and `ysize` to mean a fraction of the screen instead of a number of pixels, thus paving the way for px and coordinates in a near future.
Except for `offset`, `size` is the only transform property to only allow numbers of pixels instead of any position value.
Furthermore, the corresponding `xsize`, `ysize` and `xysize` style properties support it (and have recently been fixed about it).

**Comment by renpytom** [comment]
It probably makes sense to rename the TransformProperty to xysize, and make the change then,.
