### ISSUE TITLE
Triple quote aren't showing single line breaks

### ISSUE THREAD

**Issue by midgethetree** [renpy/renpy#2900]
Triple-quotes aren't breaking as expected, making it impossible to get single line breaks. For example

```
_p("""
Line 1.\nLine 2.
Line 3.
""")
```

Gets displayed as

```
Line 1.Line 2. Line 3.
``` 

instead of

```
Line 1.
Line 2.
Line 3.
```

This can be easily seen in a new project by defining gui.about accordingly. Adding an additional blank line or \n to make it a double line break works fine.

**Comment by renpytom** [comment]
That's what _p does - it will merge together lines like that, and then break things into a paragraph when there is a blank line.

**Comment by midgethetree** [comment]
Ah whoops, you're right. Sorry for the trouble!
