### ISSUE TITLE
ConditionSwitch error on rollback

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2905]
```rpy
default var = False

image test_A:
    "#0f0"

image test_B:
    "#00f"

image testor = ConditionSwitch("var", "test_[var]", "True", Null())

label start:
    show testor
    e "You've created a new Ren'Py game."

    e "False"

    $ var = "A"
    # show testor
    e "A"

    $ var = "B"
    e "B"
```
Going to "False" displays nothing. Going to A or B display color, but rolling back to False or to "You created..." throws an exception as `could not find image (u'test_False')`.
Reloading (using the reload button on the exception screen) makes the error disappear and the False scene display normally.

Uncommenting the second "show testor" line makes the bug disappear.

**Comment by renpytom** [comment]
I'm getting "name var is not defined", which seems like the proper error for this example.

**Comment by Gouvernathor** [comment]
I forgot the first line, fixed.
