### ISSUE TITLE
anchor interferes with focus_mask in (image)buttons

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2908]
```rpy
screen scr:
    add Solid("#00f", xysize=(100, 100)):
        pos (.0, .5)
    imagebutton:
        pos (.0, .5)
        idle Solid("#f00", xysize=(100, 100))
        hover Solid("#0f0", xysize=(100, 100))
        focus_mask Solid("#f00", xysize=(100, 100))
        action NullAction()

    add Solid("#00f", xysize=(100, 100)):
        pos (.2, .5)
        anchor (.5, .5)
    imagebutton:
        pos (.2, .5)
        anchor (.5, .5)
        idle Solid("#f00", xysize=(100, 100))
        hover Solid("#0f0", xysize=(100, 100))
        focus_mask Solid("#f00", xysize=(100, 100))
        action NullAction()

    add Solid("#00f", xysize=(100, 100)):
        pos (.4, .5)
    imagebutton:
        pos (.4, .5)
        idle Null()
        hover Solid("#0f0", xysize=(100, 100))
        focus_mask Solid("#f00", xysize=(100, 100))
        action NullAction()

    add Solid("#000", xysize=(100, 100)):
        pos (.6, .5)
    add Solid("#00f", xysize=(100, 100)):
        pos (.6, .5)
        anchor (.5, .5)
    imagebutton:
        pos (.6, .5)
        anchor (.5, .5)
        idle Null()
        hover Solid("#0f0", xysize=(100, 100))
        focus_mask Solid("#f00", xysize=(100, 100))
        action NullAction()

label start:
    call screen scr
```
The blue squares are placed under the imagebuttons, allowing to locate the ones with no `idle` image.
The black square would be under the fourth imagebutton if it had not the `anchor (.5, .5)` property.
Notice no trouble for the first three buttons.
However, for the fourth one, if you put your mouse over the top-left corner of the blue square, where it doesn't overlap the black one, the hovering is not triggered. Worse, if you put your mouse on the black area, the hover flickers.

As far as I tested, it only happens when there's a reunion of these three ingredients : anchor, `idle Null()` and a focus_mask.
I only tested in imagebuttons with `hover`, maybe `hovered` doesn't suffer from the bug.

I hope I didn't forget a line this time...

**Comment by renpytom** [comment]
The confusion here is that you have a button that's changing size from (0, 0) to (100, 100). When the button changes size, it also changes position. The focus mask remains anchored to the upper-left corner of the button.
