### ISSUE TITLE
Text lines don't display past the initial limit of a viewport

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2910]
Very weird. It seems that the viewport listing the projects (or the vbox contained in it) is now limited to displayig 12 lines, aka 12 projects or less if some have a too long name.
I believe the limit is actually the size of the area the viexport is located in - every element after the first one to be wrapped under the lower border of the viewport, gets zapped.

Happens in the Nightly but not in the Stable.
Maybe 8de11ad0d126cb337b2928d7f5b36524a037fe3e, 6ec97b72fdcbaeba6cb05827b681ec042d34a258, ea977dcf4714e8dc99fa06516de60a8115c2737d, 65d719ecacd4143416dae6c8080b7bc4c39af38f or 77e7b6a9a5b50fa4d1aee8d3fa3244420c26141c ? I don't really see any other commit that could have caused it.
May also be a build error.

**Comment by Gouvernathor** [comment]
Having a viewport contain (or use) a vbox, itself containing text lines, only the text visible in the first """screen""" of the viewport (what you see of it before you start scrolling it) will be generated.

**Comment by renpytom** [comment]
It's one of 8de11ad0d126cb337b2928d7f5b36524a037fe3e or 9778498bf19cde43a4c056d751949ddc51d5d799 , according to git bisect.
