### ISSUE TITLE
With None statement failing on screens

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2913]
```rpy
screen scr:
    if var:
        add Solid("#f00", xsize=300, xalign=.0)
    add Solid("#0f0" if var else "#00f", xsize=300, xalign=.5)
# red and green if var, blue if not

image plain = ConditionSwitch("var", "#ff0", "True", "#0ff")
# yellow if var, blueish if not

default var = False

label start:
    show plain
    show screen scr
    "A"
    $ var = True # not blue
    with None
    # pause .0000001
    $ var = False # blue
    hide plain
    hide scr
    with dissolve
    "B"
```
What *should* happen is that all the blue suddenly turns red, yellow and green, then fade to grey. The almost-untimed pause should be irrelevent when following a `with None` statement.
What *does* happen is that without the pause statement, the red, yellow and green never appear.

This is not the same as the ConditionSwitch's behavior, which is supposed to (and does) remain blue at all times : as soon as the pause statement is added back, the screen and the image start behaving differently, and the screen actually does what it's supposed to.

The weirdest in this is that I have that code just after a label in my game, and whether or not I come from some call screen or from a dialogue before the jump, changes whether or not the bug triggers. I'm not able to identify what triggers the correct behaviour, yet, but it seems any dialogue, even `"{nw}"`, triggers the bug.

**Comment by renpytom** [comment]
What's going on here is that screens only update during an interaction, and with None doesn't cause an interaction to happen.  As a result, the change in var isn't going to be captured.

Assuming this is the case, this is fine. I'm pretty sure that screens are defined to be updated only when an interaction occurs, and updating the screens each time a with None occurs seems like it would be very expensive, to little benefit. 

The right answer to this is ``pause 0``, which displays the screen for one frame.
