### ISSUE TITLE
Images are now impervious to attribute change once shown

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#2926]
```rpy
image colr red = "#f00"
image colr blu = "#00f"

label start:
    show colr blu # blue
    pause
    show colr red # still blue
    pause
    hide colr
    show colr red # red
    pause
```

**Comment by midgethetree** [comment]
I noticed this issue too! It appears to have been introduced by the changes to renpy/display/core.py in #a3defaf and won't happen if those changes are reverted by using:
```define config.keep_running_transform = False```
Hopefully with that info this can be fixed more quickly.

**Comment by renpytom** [comment]
Thanks, I'll be working on this tonight.
