### ISSUE TITLE
Extending functionality, creating a plugin

### ISSUE THREAD

**Issue by GildedHonour** [renpy/renpy#2931]
Does the project support extending its functionality somehow, for instance, via plugins?

**Comment by Gouvernathor** [comment]
https://www.renpy.org/dev-doc/html/python.html#first-and-third-party-python-modules-and-packages

**Comment by renpytom** [comment]
While you can add in some external Python modules. (Mostly pure python ones that support Python 2.7), most of Ren'Py's extensibility comes from a lot of Ren'Py being written in the sort of Python that you can include in your game. For example, you can create creator-define dispayables to do what you want. 

In any case, this isn't really an issue, so I'm going to close this.
