### ISSUE TITLE
Could not evaluate 'CHARACTER' in the who part of a say statement.

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#2933]
**Describe the bug**
Using `default` and a custom `Character()` class causes lint to throw an error with every who part of a statement

Character code:
```
    class Character(ADVCharacter):
        def __init__(self, name, kind=None, **properties):
            ADVCharacter.__init__(self, name, kind, **properties)

            self.stats = {
                "Competitive": None,
                "Vindictive": [],
                "Talkative": None
            }

            self.points = 0
            self.opinion = None

        def kill(self):
            # Check Competitive stat
            if self.stats["Competitive"] == True and len(v12s7_killList) < 3:
                self.points -= 1
            elif self.stats["Competitive"] == False and len(v12s7_killList) < 3:
                self.points += 1

            # Check Vindictive stat
            for character in self.stats["Vindictive"]:
                if character in v12s7_killList:
                    self.points += 1
                else:
                    self.points -= 1

            # Check Talkative stat
            if self.stats["Talkative"] == True:
                self.points += 1
            elif self.stats["Talkative"] == False:
                self.points -= 1

            # Add character to kill list
            v12s7_killList.append(self)
```
`default u = Character("[name]", who_color="#53d769")`

**Expected behaviour**
Lint to return without error - game runs perfectly fine, without any problems
I believe the problem lies in the `eval_who()` function in the `ast.py` file.

**Screenshots**
![image](https://user-images.githubusercontent.com/26691547/126876796-26803c27-7c66-4edf-a459-d55964cd128a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 7.4.6

**Comment by Gouvernathor** [comment]
Renpy internal classes shouldn't be subclassed - see #2813

**Comment by renpytom** [comment]
Yep, this isn't a bug in Ren'Py. The characters aren't ``define``d, so lint can't find them. 

(It might make sense to run the default statements before linit, but even with that happening, subclassing ADVCharacter isn't allowed.)

**Comment by KiloOscarSix** [comment]
Cheers, seeing Tom's alternative will work for my case.
