### ISSUE TITLE
[Feature Request] Vector Primitives as Displayables

### ISSUE THREAD

**Issue by gnutrino** [renpy/renpy#2935]
Add Displyables for basic vector primitives (line, polyline, rect, polygon, circle, ellipse) and potentially more complex primitives (essentially something approaching what the svg [path](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path) element can do). There would also need to be some consideration of how things like styles, tranformations etc. would affect them.

Potentially related to #1641 as it would be nice to not only be able to render svgs to raster images but to be able to interact with the individual renderable elements as Displayables.

I'd be willing to have a go at a first pass at this but I think making something properly robust and performant probably requires more knowledge of the renpy engine than I have...

**Comment by renpytom** [comment]
It's probably not going to happen at this point - more likely is that I'll implement something that lets you create arbitrary meshes, which you could use to render vectors.
