### ISSUE TITLE
Drag and Drop performance is severely degraded with gl2 is enabled

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2940]
When define config.gl2 = True is used (either specifically or with the default in the latest version), drag and drop performance is severely degraded.

Dragging an image is very jerky and sluggish. The number of draggable items does not seem to make a difference. It happens if there is only 1 draggable item.

Adding define config.gl2 = False results in normal performance.

**Comment by renpytom** [comment]
It appears to be isolated to one computer for now. Closing unless the problem shows up elsewhere.
