### ISSUE TITLE
7.4.7.1862 - Lists do not get their appended data removed on rollback. Tested with new project & simple code.

### ISSUE THREAD

**Issue by henvu50** [renpy/renpy#2942]
Version: 7.4.7.1862 

To be thorough. I downloaded the latest 7.4.7.1862  from renpy website and put it into a new folder. I then ran the renpy.exe from that folder.  I created a new project with the code further below. 

How to reproduce problem:
1. Start a new game using the code below.
2. Keep playing until you see the say dialogue text "_rollback_".
3. Open console and type **_someList_**, to see the lists contents. You'll see **yo** & **nuts** in the list. 
4. Now rollback all the way to the first hello.
5. Open console and type someList again, and the contents of the list will still be there.

I tested this same code on 7.4.5.1648 and the list gets emptied properly when I roll all the way back.
```
default someList = [ ]
label some2:
    "yo"
    "hi"
    "rollback"
label some_label:
    menu:
        'how are things?':
            "good"
            jump some_label
        'im ready':
            "ok"
    "Hi, . "
    "One more ."
    "Okay,."
    $ someList.append("yo")
    $ someList.append("nuts")
    jump some2
init python:
    def doitman():
        renpy.call("some_label")
label start:
    "hello"
    "ya"
    $ doitman()
    return

**Comment by kobaltcore** [comment]
Seems to be caused by 62e4f3017bbd67261c063cef8983112ecca90360. Undoing this change makes lists behave properly again.
