### ISSUE TITLE
[Feature Request] Option for building universal apk only.

### ISSUE THREAD

**Issue by H4M5TER** [renpy/renpy#2944]
Since my application is big enough (and I'm not willing to upload it to Google Play Store) that making different ABI versions doesn't make sense.
This is a case for this feature.

**Comment by renpytom** [comment]
Closing this for now, as this is likely to happen once 7.4.9 moves to .aabs .

**Comment by H4M5TER** [comment]
7.4.9 prerelease is out now.
How's it going?

**Comment by renpytom** [comment]
7.4.9 only builds universal APKs.
