### ISSUE TITLE
[7.4.x] Presplash image is enlarged to full screen

### ISSUE THREAD

**Issue by drrouen** [renpy/renpy#2950]
In Android build by renpy version 7.4.x, the presplash image is simply enlarged to full screen, resulting in blurred image if the size of image is small. According to the documentation, 

> Preslash image should be surrounded by a monocolored border. That border is expanded to fill the screen.

I solved this issue by changing ` mPresplash.setScaleType(ImageView.ScaleType.FIT_CENTER)` to `mPresplash.setScaleType(ImageView.ScaleType.CENTER)`.

Also, I noticed that on presplash screen, the status bar won't hide (or a black bar is showed above the presplash image). Only when the game is loaded, it will be displayed full screen. I copy some of the old codes from 7.3.x (`setSystemUiVisibilityMode()`) and it will display correctly. 

However I am just an amateur so maybe someone can solve these issues properly?

**Comment by renpytom** [comment]
I'll change the documentation. 

IIRC, setSystemUiVisibilityMode had caused some compatibility problems (devices not responding to input), to the point that I thought living with controls during splash was preferable to dealing with them.
