### ISSUE TITLE
[Feature Req] Ability to apply transforms to already shown tag

### ISSUE THREAD

**Issue by mal** [renpy/renpy#2951]
From time to time it's necessary to show a duplicate of an asset on screen at the same time, or to show a somewhat complex dynamically constructed image; both of which cases are made easier with the `as` keyword, allowing them to be aliased for the duration of their display, and allowing a much easier way to `hide` them.

Sometimes it would be useful for these aliased/tagged assets to be manipulated via a transform, however while the `hide` statement will recognise tags, the `show tag at transform` statement will not, instead replacing the currently tagged image with a placeholder (as the tag does not exist as a real image.

The request is to be able to use the `show` statement or (if that's too breaking) a separate statement to be able to apply new transforms to currently displayed assets, such that things like the very simplistic example to follow would be possible without the placeholder being switched:

```rpy
label main_menu:
    $ _confirm_quit = False
    return

label start:
    show expression Placeholder('boy') as boy at left
    "Hello! I'm on the left side of the screen."
    show boy at right
    "Now I'm on the right of the screen, but my placeholder has changed!"
    return
```

**Comment by renpytom** [comment]
Is there any time you'd need to do this where: 

```
    $ boy = Placeholder('boy')
    show expression boy as boy at left
    "Hello! I'm on the left side of the screen."
    show expression boy as boy at right
    "Now I'm on the right of the screen, and my placeholder is the same."
    return
```

I'm reluctant to address a massively uncommon case.

**Comment by mal** [comment]
I don't believe so, indeed that's the approach we're currently taking, this would have been just a little syntactic sugar to help cut the repetition of  `expression boy as boy` and it's equivalents (which depending on prevalence can get a bit tiring), It'd be a nice to have, but nothing we can't live without, so if at least for now you don't believe it would be enough of a benefit to the broader creator base we can close this one. 🙂

**Comment by renpytom** [comment]
I don't think this is worth introducing new syntax for, so I'll close this.
