### ISSUE TITLE
Persistent not storing list of custom objects.

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#2963]
**Describe the bug**
A persistent variable defaulted to an empty list doesn't retain its data after a reload or restart.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download game zip and extract into a new project. [game.zip](https://github.com/renpy/renpy/files/6950191/game.zip)
2. Click on the "Create Playthrough" button or add `Playthrough` objects of your own.
3. Exit the game and relaunch and you will find no persistent data has been saved, including preference changes made. Everything has been set back to `default`

**Expected behaviour**
Persistent data to be stored and not reset.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 7.4.8

**Additional context**
Not including `__eq__` dunder method caused 
```py
raise Exception("To be persisted, %r must support equality comparison." % o)
```

**Comment by renpytom** [comment]
Not a bug, custom objects can't be in persistent. 

Per the documentation:

As persistent data is loaded before init python blocks are run, persistent data should only contain types that are native to Python or Ren'Py. Alternatively, classes that are defined in python early blocks can be used, provided those classes can be pickled and implement equality.

**Comment by KiloOscarSix** [comment]
Ah, was under the assumption persistent was similar to regular save data. Time to rethink the solution, thanks for the quick respone.
