### ISSUE TITLE
Hitching on loading zoomed images

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#2968]
Recently I changed my sprite pipeline from using multiple versions of images in different zooms to a single version of each image and using the built in zoom transform to do the scaling instead, in order to take advantage of the dynamic scaling functionality. Unfortunately, ever since then I've noticed these non negligible performance impacts. Whenever a zoomed image is shown for the first time Ren'py will hang for a few frames before displaying it. This has the effect of feeling unresponsive when playing, and makes skip mode quite clunky as Ren'py will quickly queue up a bunch of these hitches as it runs through all the different sprites.

The sprites I'm using aren't particularly large - they're 2000x3300 in webp format - so I wouldn't expect this to have such an impact to performance to resize. And also, this hitching only happens the first time an image is loaded. 

I can put together an example project to show this problem if you wish.

**Comment by renpytom** [comment]
Can you post your log.txt?

**Comment by Kuroonehalf** [comment]
I'm declaring composite images with renpy.image(...im.composite()), and then zooming with the zoom transform.

And here's my log.txt.
[log.txt](https://github.com/renpy/renpy/files/6955324/log.txt)

**Comment by renpytom** [comment]
Looks decent, but note that im.composite is legacy. Perhaps consider just Composite.

**Comment by Kuroonehalf** [comment]
Oh, huh, it seems that was it. Changing those declarations from im.Composite to just Composite has made this issue go away. Thank you! I'm closing this issue then. :>
