### ISSUE TITLE
[Feature Request] avif images support

### ISSUE THREAD

**Issue by suphamster** [renpy/renpy#2977]
Avif about 25% more effecient at the same size than webp (and about same amount slower).

**Comment by renpytom** [comment]
Do any web browsers support avif? I tend to use that as my proxy for a format becoming popular enough that tools exist to make it worth using?

**Comment by uyjulian** [comment]
https://caniuse.com/avif  

`sdl2_image` and `ffmpeg` do not support AVIF container format yet.

**Comment by PhiSYS** [comment]
The downside is that the encoding is hell of slow... but encoding is a one time process and it worth it. I can confirm in my tests that AVIF is far by superior from WebP, it retains much more fine details while it has practically no artifacts/ringing and it's.
It also supports Animations and Alpha althought I didn't tested them yet.

I definitely upvote AVIF

**Comment by renpytom** [comment]
I'll close this for now, as I probably won't do anything until it's SDL2_image,  at which point we'll get it by default. I don't think I need this to stay open until then.

**Comment by suphamster** [comment]
> I'll close this for now, as I probably won't do anything until it's SDL2_image, at which point we'll get it by default. I don't think I need this to stay open until then.
Hi, it looks like devs of this library finally added support by my request https://github.com/libsdl-org/SDL_image/commit/00b71a12a5b0ea376a890fbcdd22475ae9694a39
https://github.com/libsdl-org/SDL_image/issues/188

**Comment by thelordofcorruption** [comment]
AVIF support has been added to SDL_image, so I think this issue should be reopened. https://github.com/libsdl-org/SDL_image/commit/00b71a12a5b0ea376a890fbcdd22475ae9694a39

**Comment by renpytom** [comment]
Not sure which advanced format is best, as I need to investigate which dependencies these have.

**Comment by renpytom** [comment]
This should be done now.
