### ISSUE TITLE
Memory Leak with Texture Allocations in the GL1 renderer

### ISSUE THREAD

**Issue by SonicMastr** [renpy/renpy#2980]
While using the GL1 renderer with various games, I've noticed that when the texture cache gets full and textures are attempted to be freed, Renpy is under the impression that the texture is correctly freed while no memory is actually released. This causes a major memory leak with low memory systems (Such as the PSVita). 

I can't seem to find the source of the leak in the renderer itself, but one of my friends pointed out that a Yaoi VN forum also reported the same thing a while ago, but the post has since been deleted. I've been stumped on this for a few weeks now, so I'm resorting to opening this issue instead.

Games Tested: Doki Doki Literature Club, Syrup and the Ultimate Sweet, Spring Leaves No Flowers

**Comment by renpytom** [comment]
Ren'Py isn't supported on the PS Vita. Is there a problem on any supported platform?

**Comment by SonicMastr** [comment]
Unfortunately, I haven't had the opportunity to check. The only thing I know is that my initial vita port used Ren'Py 7.3.5.606 with no issue in the GL1 renderer, but when updating to master it seemed as though memory was never actually freed when textures were removed from the cache. 

I'm aware the GL1 renderer is no longer supported as well, so I may just seek other options instead, but I was just hoping maybe there was something that could've changed since then and now (which is a long time) that would have caused that issue.

**Comment by renpytom** [comment]
The move to uguu is a big change, and PS Vita isn't a platform that Ren'Py has ever supported. If you find the problem on a supported platform, it's appropriate for the tracker, but if not, it's not.
