### ISSUE TITLE
AlphaMask displayable causes low fps when receiving mouse events

### ISSUE THREAD

**Issue by AndriWilford** [renpy/renpy#2988]
IT seems that, when an AlphaMask displayable is on screen, swiping the mouse over the area it occupies can significantly lower the FPS of the renpy rendering. This does *not* seem to affect the CPU use to any great degree, only the renpy window's FPS. This occurs even when under a model object (wrong about this on first post).

This is a little specific, however it has affected some atl animations where an AlphaMask displayable was involved. When the ATL is playing, if the player moves the mouse over the alphamask displayable, the FPS of the game will tank,  causing the visual problems associated with low / inconsistent FPS.

I've noticed this in 7.4.6  and 7.4.8 .

This does NOT happen on all computers. This is the available testing I can show:
 * Windows 10 dell laptop with nvidia graphics - YES
 * Windows 10 dell laptop with intel graphics - YES
 * Windows 7 deskto with nvidia graphics - NO
 * iMac 27" retina 2019 with AMD graphics - YES

To recreate:

1) Provide an image of some reasonable % of the screen size  (like a 600x600 image) so that the mouse can be 'swiped' over it for testing

2) Create a test game, something like the following
```
image amtest = AlphaMask("amtest.png", Solid("#ffffffff"))
label start:
    scene bg room
    e "You've created a new Ren'Py game."
    show amtest
    e "alpha mask test showing"  #<---- Stop here
    return
```

3) Turn on the FPS meter  (F3)  and swap it to performance mode (not powersave) so that the full FPS of the game can be observed. 

4) Swipe the mouse over that alphamask displayable and watch the FPS of the game. One could also note the CPU use rises a little bit (as it always does when generating alot of mouse events), but does not max out core which would otherwise be an explanation for the FPS drop.

**Comment by Gouvernathor** [comment]
May be related to #2458
