### ISSUE TITLE
[Request] nightly build 8/21 .aab  targets API 29

### ISSUE THREAD

**Issue by sarahjiwoo** [renpy/renpy#2989]
Hi, the new nightly build uploaded on 8.21 targets API 29, and google play says the app bundle must target at least 30. 
Can this be fixed?

**Comment by renpytom** [comment]
Done, and it should be in the 2021-08-22 nightly.

I'm not 100% sure what the pack size limit for fast-follow packs are on Google Play, so I don't know if it will accept a full 2GB game.
