### ISSUE TITLE
renpy nightly build 8.22 .aab build error

### ISSUE THREAD

**Issue by sarahjiwoo** [renpy/renpy#2992]
Hi, I tried building an .aab file using renpy nightly build 8.22 but an error occured.
IOError: [Errno 2] No such file or directory: u'C:\\Users\\\uc11d\uc740\ud558\\Downloads\\renpy-nightly-2021-08-22-969cf58a3-sdk\\rapt\\project/renpyandroid/src/main/res/values/strings.xml'
this error occurs when I build the package.
Can this be fixed?

**Comment by renpytom** [comment]
This file should be automatically generated for you, if you have automatic generation of project files turned on.
