### ISSUE TITLE
camera statement breaks movement transitions

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#2995]
I was hoping the new `camera` statement would fix #2821 / #2560 , but unfortunately, it doesn't. 
I also think this made me find a new issue where effects disappear when they shouldn't.

If I understand this correctly:
```
renpy.show_layer_at(at_list, layer=u'master', reset=True, camera=False)
      The Python equivalent of the show layer layer at at_list statement. If camera is True, the equivalent of the camera statement.
```
Then
```
camera:
    perspective True
$renpy.show_layer_at(Chromatic(), reset=False)
```
should work as intended, no?

**Expectation:**
A chromatic aberration effect is applied to the master layer. It persists even after scene statements and does not break movement transitions.

**Result:**
1) Movement transitions are still broken.
2) While the breaking of movement transitions persists after scene statements, _the effect itself_ does not.

**Example:**
```
camera:
    perspective True
scene bg
show character at left
$renpy.show_layer_at(Chromatic(), reset=False)
#chromatic aberration is successfully applied to the master layer
"..."
show character at right with move
#this does not work
"..."
scene bg2
show character at easeinright
#chromatic aberration is no longer applied to the master layer, but movement remains broken
"..."
```

**Comment by renpytom** [comment]
There's a misunderstanding here. The ``scene`` statement clears the layer at list, and so when you do:

```
scene bg2
```

You'll be turning off the Chromatic() transform. You probably want:

```
camera at Chromatic():
    perspective True
```

Which will not clear the layer at list when the scene changes.

**Comment by kigyo** [comment]
Thank you for your explanation, that was indeed what I was looking for.

Unfortunately, doing it this way still breaks movement transitions, but at the very least the second issue took care of itself.

**Comment by renpytom** [comment]
I just landed a pair of commits that fixes this.
