### ISSUE TITLE
camera breaks various pre-defined transitions

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#2998]
Simply making use of
```
camera:
    perspective True
```
seems to break various pre-defined transitions, such as `wipeleft`, `slideleft`, `pushleft`, and `irisin`. 
(I may have overlooked some, so there could be more.)

`dissolve`, `fade`, `blinds`, `squares`, and `pixellate` are unaffected and work correctly.

**Comment by JackkelDragon** [comment]
I mentioned in the thread for 7.4.8 something potentially related to this, specifically about ease and move transitions. I suspect it has something to do with the 3D Stage, but I don't know if there's a way to disable the 3D Stage once it is turned on.
