### ISSUE TITLE
in-game visual editor

### ISSUE THREAD

**Issue by picobyte** [renpy/renpy#3005]
Several years back I wrote this in-game screen based visual editor, which in my opinion could with a bit more work be a nice addition to ren'py. It's not perfect but it used to be worse and is now I'm a bit back working on it slowly progressing. Do you think this could be a solution? License is GPL v3.

https://github.com/picobyte/EditButton
Also see the thread here:
https://lemmasoft.renai.us/forums/viewtopic.php?f=51&t=39968

Please note that pygments support for python2.7 stopped a while ago and therefore an old version of pygments is required. Hopefully when ren'py runs on python 3 this will be resolved as well.
![screen cast of editor in action](https://lemmasoft.renai.us/forums/download/file.php?id=60206&mode=view)

**Comment by renpytom** [comment]
I can see some projects that would find this useful, and I'm glad it exists. 

I don't thing something like this really belongs in Ren'Py. My current thinking is that maintaining a text editor is about the same amount of work as maintaining the rest of Ren'Py, and so I don't really want to add one to the project.  

Also, GPL3 isn't a license I could apply to Ren'Py.

**Comment by picobyte** [comment]
Thank you, also for taking the time to reply and the work in general. About the license, I figured as well it's a bit too restrictive, I'll change it to LGPL and may add MIT license under conditions.
