### ISSUE TITLE
Possible bug with hover animation on Imagebutton after 7.4.7?

### ISSUE THREAD

**Issue by Tapirismus** [renpy/renpy#3008]
I have encountered the following problem with the new renpy versions:

I'm using an Imagebutton on the navigation screen that looks like this:

```

	imagebutton:
        
        	action Start()
        	ypos 850
        	xpos 50
        	activate_sound "sounds/start sound3.wav"
        	idle "Start_button2" 
        	hover "start_hover"

```

Both the Idle and hover images are animated:

```
image start_hover:
    "start_button_animated/frame0000.png"
    0.05
    "start_button_animated/frame0001.png"
    0.05
    "start_button_animated/frame0002.png"
    0.05
    "start_button_animated/frame0003.png"
    0.05
    "start_button_animated/frame0004.png"
    0.05
    "start_button_animated/frame0005.png"
    0.05
    "start_button_animated/frame0006.png"
    0.05
    "start_button_animated/frame0007.png"
    0.05
    "start_button_animated/frame0008.png"
    0.05
    "start_button_animated/frame0009.png"
    0.05
    "start_button_animated/frame0010.png"
    0.05

    repeat

image Start_button2:
    "start_button_animated2/frame0000.png"
    0.05
    "start_button_animated2/frame0001.png"
    0.05
    "start_button_animated2/frame0002.png"
    0.05
    "start_button_animated2/frame0003.png"
    0.05
    "start_button_animated2/frame0004.png"
    0.05
    "start_button_animated2/frame0005.png"
    0.05
    "start_button_animated2/frame0006.png"
    0.05
    "start_button_animated2/frame0007.png"
    0.05

    repeat

```

Now the problem:
After 7.4.7 things don't work the same as they used to for me. The idle animation is fine and the hover animation is fine too if you hover over the button exactly once. 
After you hover over it again, the animation stops working properly. The animation freezes for a couple of seconds before it shows normally again. 
I tested this in a new project on 7.4.8 and 7.4.7 - Both times it didn't work. Then I tested it in 7.4.6, and the animation would show properly.

Thank you very much in advance. I appreciate the great work you do on this engine a lot.

**Comment by renpytom** [comment]
Can you try it on 7.4.9, from nightly.renpy.org? I think it might be fixed there.

**Comment by Tapirismus** [comment]
Thank you for your response.
I tried it on the latest nightly build and it still didn't work properly for me unfortunately

**Comment by renpytom** [comment]
I've been able to repeat this.
