### ISSUE TITLE
Save Location Screenshots are Black on Android

### ISSUE THREAD

**Issue by kobaltcore** [renpy/renpy#3009]
On Android, all screenshots taken for save slots end up completely black.
This was initially reported to me by a few players, but I can also reproduce this on my own phone (Huawei Mate 20 X, Android 10).
This happens with our game as well as with The Question, which I checked to make sure that this isn't a game-specific issue.

This was tested on Ren'Py 7.4.8. I would've tested 7.4.9, but the Android build menu seems to be broken in the launcher in that version.

**Comment by renpytom** [comment]
Can you send me the apk file for a game that has this problem? I've had this reported a few times, but I've been unable to repeat it on a device I have access to, on games I've had access to.

**Comment by kobaltcore** [comment]
Here's a fresh build of The Question which exhibits this issue on my phone:
https://mega.nz/file/A4YUQRJY#O4M3CYQ9O5jd7CkusIi1qoCw1D5xIWYkw_Yk8o2_2JY

This is a universal build straight from an unmodified project with a newly-installed launcher on 7.4.8.

**Comment by renpytom** [comment]
That apk works fine on my Pixel 5. 

Do you have a list of devices in which this is broken on? I can't really afford a Mate 20 X, but if there's something less expensive I could look at getting it in.

**Comment by kobaltcore** [comment]
With the help of some players I was able to come up with the list below.

Black Screenshot Issue:
- Samsung Galaxy S10e - Android 11 - Exynos 9820 - Mali G76
- Huawei Mate 20 X - Android 10 - Kirin 980 - Mali G76
- Xiaomi Redmi Note 7 - Android 11 - Snapdragon 660 - Adreno 512

Works Fine:
- Samsung Galaxy S20 FE - Android 11 - Snapdragon 865 - Adreno 650
- Xiaomi Mi 10 - Android 11 - Snapdragon 865 - Adreno 650
- Pixel 5 - Android 11 - Snapdragon 765G - Adreno 620
- Samsung Galaxy A12 - Android 11 - MediaTek Helio P35 - PowerVR

Up until the Note 7 came in I thought the Mali GPU's may have been a pattern, but that does not appear to be the case, unfortunately.
According to reports this may be intermittent. At least on the Note 7 this will randomly start happening and continue until the app is restarted, at which point screenshots will start working again. In this one case, the thumbnails will also exhibit artifacts instead of being entirely black, whereas all other users reported black thumbnails:
![corrupt](https://user-images.githubusercontent.com/39258182/131758404-ab516d2e-96a7-4f8c-9953-4082e6252163.png)

On the Mate 20 X and the S10e the screenshots are consistently black, even after restarting the app, and do not exhibit any artifacts.

**Comment by renpytom** [comment]
I just tried saving from The Question on my s10e, and it saved fine. So I'm not sure what could cause this.

**Comment by kobaltcore** [comment]
Those kinds of issues are indeed tough to address. If there's anything I can do to provide additional information from a device that does exhibit this issue consistently, let me know.
I could send you one of the affected saves, if that helps. If there are any "shot in the dark" things you want to try, I can also do that on my end. This has only started happening recently from what I can tell, so with one of the latest 7.4+ releases.

I will try this once more with GL2 mode disabled to see if that makes a difference as well.

**Comment by renpytom** [comment]
Can we get a save file off of a device having problems? I can pick it apart to see if the thumbnail inside is valid, which would at least distinguish between taking the screenshot and displaying it.

**Comment by kobaltcore** [comment]
Here you go:
[1-1-LT1.zip](https://github.com/renpy/renpy/files/7128095/1-1-LT1.zip)

This is a save file from a new build of The Question running on my Mate 20 X. I saved at a random point in the story.

**Comment by kobaltcore** [comment]
Can confirm this is now fixed on my Mate 20 X. Thanks for this!

**Comment by renpytom** [comment]
That was a shot in the dark, so glad this fixed it.
