### ISSUE TITLE
using the renpy Lexer for another project

### ISSUE THREAD

**Issue by erazor83** [renpy/renpy#301]
Hi there!

I'm currently writing some kind of a web based story engine, based on HTML5 websockets, javascript and cherrypy. The whole concept is to build something very similar to RAGS but on HTML/HTTP basis.

I'm now at a point where I need some text engine where stories can be described and gives me some text output. 

Personally I really like the format of renpy stories and would also like to use this for my project.

Is this even possible? Calling the lexer and binding commands to a custom class? Or is it so deep in the complete renpy that it does not make sense at all?

Where should I start?

Thanks for your response :-)

**Comment by jtenner** [comment]
If I may use this issue as a starter point, but is there any documentation on how the AST parser works?

If I were to convert the lexer and the parser to JS, is there a state machine that keeps track of sprite objects, that I can use, already coded?  I know that renpy is highly coupled, but I think it's possible to at least get the lexer + parser combination going.

**Comment by renpytom** [comment]
There isn't any documentation. It's a pretty straightforward recursive descent parser, of the sort you'd find in a compilers textbook. There isn't a state machine that keeps track of sprite objects. What the lexer+parser does is to create an AST, and then that AST executes to set up Python data structures describing objects.

I don't think the right way to port Ren'Py to the browser is to do it piecemeal, by trying to extract data structures. The right way is to wait for webasm to start working, and use that to port the whole thing at once.
