### ISSUE TITLE
[Request] renpy nightly build 9/2 aab file is not supported by google play store

### ISSUE THREAD

**Issue by sarahjiwoo** [renpy/renpy#3012]
Your Android App Bundle is signed with the wrong key. Ensure that your App Bundle is signed with the correct signing key and try again. Your App Bundle is expected to be signed with the certificate with fingerprint:
SHA1: D5:70:62:CB:7D:60:B9:88:B6:57:85:4E:F6:D6:1F:52:3B:A2:DE:64
but the certificate used to sign the App Bundle you uploaded has fingerprint:
SHA1: 16:58:41:60:F2:D7:43:35:18:05:09:D0:80:D0:7C:00:2E:4D:BD:23
This error message comes up when I tried uploading the aab file made with renpy nightly build 9/1. I was going to put it into beta testing but the file won't be uploaded. Can this be fixed?

**Comment by renpytom** [comment]
Please make sure you're using the same bundle.keystore.

**Comment by sarahjiwoo** [comment]
I made a bundle.keystore zip file and then uploaded it onto google play but it saids that there is no encrypted key file...I have no idea what the problem is...It happened when I used renpy nightly 9/6
