### ISSUE TITLE
Leaking textures from Movie images

### ISSUE THREAD

**Issue by multimokia** [renpy/renpy#3018]
I brought up a discussion [here](https://discord.com/channels/286633898581164032/286633898581164032/883184482688073768) in #renpy of the discord server, but forwarding to here as I believe this is a bug;

I've been dealing with Leaking textures recently, and noticed that if I disable the Movie sprites used in my game, the leaks completely disappear.

These leaks cause issues with other images used in game to disappear and leave a black square/rectangle where the image which was leaked *should* be. So it's pretty game-breaking.

I should note that these sprites are used as a sort of background (basically acting as weather for a background so the place feels a little more alive), which means they also take up the full screen (1280x720), and are shown for long periods of time because of that.

The formats we use are mp4 and mpg under the mpeg-4 part2 codecs (different types is due to filesize mainly as some were smaller in one container than the other, along with some detail loss in mp4 vs mpg)

Is there any way to make these no longer leak or is this just a bug with the move to Textures and such? (This never had issues prior to textures)

This is tested on Ren'Py renpy 7.4.6, 7.4.7 and 7.4.8, all of which experience this issue.

An example of some Ren'Py stdout which reports leaking textures is:
![image](https://user-images.githubusercontent.com/22531674/131949255-214c2368-3b89-4c71-a6af-da1704da9045.png)

**Comment by renpytom** [comment]
Do you have a small replication that repeats this? I can look at that.

**Comment by multimokia** [comment]
Pretty much just playing any `Movie` image in a renpy instance and resizing the window. The test for quick repetition was just
```renpy
image testmov = Movie(play="testmov.mp4")
label start:
  "GOing to test leaking textures"
  show testmov
  "Now playing, try resizing the window, then close the game and look at log.txt"
return
```

and `testmov.mp4` was just any mp4 file with that name.

**Comment by AndriWilford** [comment]
I think what's happening is that python's garbage collection is collecting the most-recently rendered frame of the video, AFTER the texture loader has already been  init'd .. this means that the GLTexture's deconstructor is running, putting that old texture into the list of items to be cleaned up on the next call to "interact", but that texture ID doesn't actually exist anymore in the list of allocated textures,  OR  it accidently deletes the wrong texture.. so "Black boxes"

I'm not really sure if this is just wild speculation, however a little but of evidence can be this:

1) In display/video.py,  create a global var , like  `texttex = []`

2) In the  "get_movie_texture" function, directly before the final return,  add a statement like  `testtex.append(tex)` to just hold a reference to all movie frame textures that are rendered out.

Now, with a permanent;y held reference to those textures, this problem does not appear...

**Comment by renpytom** [comment]
Fixed. The solution is a bit different - clearing the cache that was hanging on to the texture - but @AndriWilford's research pointed me in the right direction.

**Comment by multimokia** [comment]
Thanks so much!
