### ISSUE TITLE
error while building an .aab file using renpy nightly 9/4

### ISSUE THREAD

**Issue by sarahjiwoo** [renpy/renpy#3023]
While running game code:
  File "game/android.rpy", line 510, in <module>
  File "game/android.rpy", line 284, in android_build
TypeError: build() got an unexpected keyword argument 'permissions'
this errors occurs when I try to build the package. 
I'm sorry if I'm disturbing anyone that concerns. I really don't know anything about codes ㅠㅠ

**Comment by renpytom** [comment]
Forgot to push a change up. Thanks for letting me know. This should be fixed in the 9/5 nightly.
