### ISSUE TITLE
Displayable.is_pixel_opaque

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3035]
Using the latest version and `gl2` I'm having an issue I haven't had on older versions.

In my displayables I need access to `Render` objects, so I keep the last reference. I'm not pickling it (and if I do I have `__getstate__`) and I do a cleanup when I'm done showing my displayables. Everything worked fine until recently I saw the log with leaking textures, I figured it probably doesn't like my render references with the latest RenPy changes, so I commented those out and the leaks disappeared.

I'd really appreciate if something could be done to fix that. I'm using complex dispalyables that can't be replaced with screens, and having access to renders allows me to show better visuals/provide interactions I wouldn't be able otherwise.

One thing I tried instantly was trying to use weak references, but sadly `Render` objects don't support it. If it's impossible or hard to fix the leaks, I'd suggest to add support for weak refs. I believe it shouldn't add much overhead and it's a small change. Developers would be able to opt in to keep renders if they need to, yet GC would be able to clear the internal cache.

**Comment by renpytom** [comment]
You're not allowed to keep references to Renders, as Ren'Py will destroy and re-create them as needed to deal with things like the game being rescaled. Ren'Py does cache renders internally, so that render.render will return the same Render object when the underlying displayable has not changed.

You'll need to make sure your game does not keep Render references, as those references can become invalid at any time. (For example, a Render can refer to a texture that has been invalidated.)

**Comment by renpytom** [comment]
Fundamentally, you should never need to access a Render outside of the render method. 

This feels like an xyproblem - https://xyproblem.info/ . What are you trying to accomplish here?

**Comment by Booplicate** [comment]
My displayables utilise different methods. Stuff like `Render.get_size`, `Render.canvas`, `Render.is_pixel_opaque`, and `Render.is_opaque`.

**Comment by renpytom** [comment]
Render.is_pixel_opaque, and Render.is_opaque aren't documented methods, so you shouldn't be calling those. That being said, I can see that is_pixel_opaque might be worth adding a supported equivalent of, though probably something that takes a displayable and not a Render. 

Fundamentally, Render needs to be a very limited interface, as the Render class needs to be something I change to improve Ren'Py.

**Comment by Booplicate** [comment]
> Render.is_pixel_opaque, and Render.is_opaque aren't documented methods

I understand, but I find those to work much faster than the focus system when I have multiple objects on the screen. The methods may not be documented, but they are working perfectly, I used them in different cases and projects.

If we could get an alternative which would be used with displayable, it'd be great!
