### ISSUE TITLE
Safe mode is probably broken on Windows 11

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3044]
We were written to by a player with Windows 11 and bad AMD drivers. We advised him to try and switch the renderer to ANGLE via safe mode as usual, but he claims to have tried start with Shift several times and safe mode won't start. Maybe he did something wrong or maybe Microsoft changed something in windll.

**Comment by renpytom** [comment]
Just installed windows 11, and it seems to work fine. So the problem is likely with the user rather than Ren'Py. I'll add a command line flag to enable safe mode, so that you could give him a .bat file.

**Comment by renpytom** [comment]
d0572739fa05c7d3c769bd3d6a4ef4b22ed1efdd addresses this, and other than that I don't think it's a problem with Win11.

**Comment by Andykl** [comment]
Yeah, one of our testers had installed Win11 and said safe-mode works. But this CLI option will be helpfull.
