### ISSUE TITLE
Vertical glyphs are not shown in vertival texts.

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#3046]
When the vertical style property is set, vertical glyphs were shown in 7.3.5 or before. But in 7.4.0 or later only normal (horizontal) glyphs are shown.
I tested with MTLc3m.ttf (included in Ren'py 7.3.5 laucher) that contains Japanese vertical glyphs.

**Comment by renpytom** [comment]
Do you have an example I can test with?

**Comment by nyaatrap** [comment]
Create Japanese project with 7.3.5. to include MTLc3m.ttf (because 7.4.x uses SourceHanSansLite.ttf which doesn't include vertical glyph information), then chenge font to MTLc3m.ttf,  type this text:

`    "（）parenthesis 「」 brackets ー macron"`

These Japanese marks should be 90 % rotated in vertical texts. 

![screenshot0002](https://user-images.githubusercontent.com/3129985/134264031-a8cf4027-d118-4170-8275-fc90fae31350.png)


![screenshot0001](https://user-images.githubusercontent.com/3129985/134264011-d3683e02-c4ab-4c26-be24-3b501648ae6b.png)
