### ISSUE TITLE
Problem with paths on Linux

### ISSUE THREAD

**Issue by Dreamtale** [renpy/renpy#3059]
Hello. I have upgraded my game to 7.4.8 and now some of my users have tracebacks like this one. I believe I saw something similar on Debian. Works fine on Ubnuntu though.
![KJcoTMJwx7U](https://user-images.githubusercontent.com/127850/135156187-9d6a5f4d-4ac2-4a90-9fe0-135c923c0c74.jpg)
:

**Comment by renpytom** [comment]
Can you ask them to run 

echo $LANG 

from the command line? My guess is that they're using UTF-8 filenames on a system that is not configured for UTF-8.

**Comment by Dreamtale** [comment]
ru.RU.UTF-8

**Comment by Dreamtale** [comment]
Well. it doesn't seem to work even with english UTF-8.
![5aLW8NHDBpE](https://user-images.githubusercontent.com/127850/135293580-fccca268-4d77-4df0-9dc5-5ad30070d6e0.jpg)

**Comment by Andykl** [comment]
It looks like your game have some file or directory with a name that cannot be decoded properly.

**Comment by renpytom** [comment]
Is it possible for me to get this version from Steam and run it here? I'm not completely clear what's going on.

**Comment by Dreamtale** [comment]
> Is it possible for me to get this version from Steam and run it here? I'm not completely clear what's going on.

Yes. of course: https://store.steampowered.com/app/331470/Everlasting_Summer/

**Comment by renpytom** [comment]
Any idea what could create a non-ASCII filename in the Everlasting_Summer directory? Perhaps one of the mods? I'm getting the issue when LC_ALL is set to C, which it is what Steam seems to be setting it to. 

I am going to be fixing this regardless, but there has to be a file with, say, a Russian filename to trigger this issue.

**Comment by Dreamtale** [comment]
No, I don't think so. In fact, the file structure in my game hasn't changed since the previous version of Renpy. And on this previous version (7.3.5) no one had this bug.

**Comment by renpytom** [comment]
This is probably fixed in 7.4.9. I strongly believe there is a non-ascii file, but 7.4.9 should handle that. (It wasn't a problem in 7.3.5, though it might have been in other contexts.)

**Comment by renpytom** [comment]
This has been in the prereleases.
