### ISSUE TITLE
Allow "add" statement to take alt text

### ISSUE THREAD

**Issue by qirien** [renpy/renpy#3061]
The "add" statement is the main way to add images to a screen. For users using self-voicing, it would be nice if these images could have "alt" statements so that their contents could be described with text.

Right now I have:
 add "GUI/heart-normal.png"
 text "" alt "love: medium"

I would like to be able to have:
  add "GUI/heart-normal.png" alt "love: medium"

**Comment by renpytom** [comment]
I like the idea, but want to wait until after 7.4.9 is out to add this.
