### ISSUE TITLE
Channel corruption after reload in main_menu

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3065]
[test.zip](https://github.com/renpy/renpy/files/7268026/test.zip)
How to reproduce:
1. Start the game (only 7th channel will playing)
2. Play through the game
3. Press Shift+R In main_menu
4. Repeat 2nd and 3rd step until there is something like
![image](https://user-images.githubusercontent.com/27142420/135639764-2485f975-6788-45a0-8500-9dbf3151cd05.png)
If I understand correctly, this happens when number of Channel that was 7th on first load is assigned to different channel, and because there is no `audio.quit` during utter reload, the music starts to play in two channels.

**Comment by renpytom** [comment]
Good work tracking this one down, as I had no idea where to look. I think the right approach is to call audio.quit(), since a reload is meant to reset everything to the state when the game starts. 

Thank you!
