### ISSUE TITLE
Undocumented behaviour of "key" screen language statement

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#3066]
The key statement can accept a list or tuple of key names. However, the documentation at: https://www.renpy.org/doc/html/screens.html#key does not mention this. 

The change is fairly recent: https://github.com/renpy/renpy/commit/8b740e7e4baa18fcb9889637184a764a03b4d6c3

Should this behaviour be documented?

**Comment by renpytom** [comment]
Yes, that should be documented.
