### ISSUE TITLE
Repr of Displayable subclasses is ambiguous

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3069]
Repr of `im.Data("a" * 10, "test.png")` is `<'Data' u'aaaaaaaaaa' u'test.png'>` (this is most confusing as it really prints data field which is really long.
Repr of `im.Composite((300, 600), (0, 0), "girl_body.png")` is `<'Composite' (300, 600) (0, 0) u'girl_body.png'>`
Repr of `ImageReference(Image("test.png"))` is `<<ImageReference <'Image' u'test.png'> at 00000000>`
and so on.

Current implementation is
```py
class Displayable:

    def __unicode__(self):
        return self.__class__.__name__

    def __str__(self):
        return self.__class__.__name__

    def __repr__(self):
        return "<{} at {:x}>".format(str(self), id(self))
```
This is ambiguous with py3 compability, as unicode become str, and subclasses that redefine unicode to change repr should be changed anyway. But also, couple of times I was really confused to met just "Image" in string substitution when I was expecting path, which happened because substitution used im.Image.__unicode__. Get rid of `__unicde__` and `__str__` prevent this.

I propose to review repr of all Displayable subclasses and make them into the common form 
```py
f"<{type(self).__module__}.{type(self)} at 0x{hex(id(self))} {self.repr_info()}>
```
or something like that.

So, default implementation in class Displayable become something like
```py
class Displayable:
    # No __str__ or __unicode__. Subclasses that really need that should define it themselves.

    def repr_info(self):
        return None

    def __repr__(self):
        klass = type(self).__module__ + "." + type(self).__name__

        at = hex(id(self))
        at = "0x" + at.zfill(16 if renpy.exports.bits == 64 else 8)

        repr_info = self.repr_info()
        if repr_info is not None:
            repr_info = " " + repr_info

        return "<{} at {}{}>".format(klass, at, repr_info)
```

**Comment by renpytom** [comment]
I think this is a reasonable thing to do.

**Comment by Gouvernathor** [comment]
About the implementation, I think it would be simpler to use `object.__repr__` to obtain the type name (which will automatically be prepended with the module name in PY3 and will not in PY2) and the address.
Then if `self._repr_info()` is not None, it can be included like
```py
return object.__repr__(self)[:-1] + " " + repr_info + ">"
```
This would avoid the issue of re-implementing something Python already provides, so it would solve two inconsistencies : the missing `object` word before the `at`, and the module name, which is only supposed to be included in PY3.

Also I strongly agree about the need to renovate (all) the `__unicode__` methods in the code with `__repr__`, and using `__str__` only when relevant (which means never, in the case of Displayable subclasses ?). It would also mean checking and updating the places where instances are str'd and repr'd.
I volunteer to do that in a PR, but it will need a thorough overview of the situation and some time.

**Comment by Andykl** [comment]
@Gouvernathor If you do PR I would be glad to review.
