### ISSUE TITLE
[7.4.9] If an image that contains an animation (made of multiple frames) isn't preloaded, showing it some screen will make the loading extremely noticeable as blank images w

### ISSUE THREAD

**Issue by Bobyteal** [renpy/renpy#3082]
Hello
I was using 7.4.8 and all the versions before and it's the first time it does this issue so this seems to becoming of a change made for 7.4.9.
The project was loaded with the commands for incompatible changes added for 7.4.9:
define config.relative_transform_size = False
But it didn't help. 
It seems to be an issue with prediction. Preloading the animation seems to fix it but that's problematic as it used to load/work flawlessly before.

Example of an image animated:

```
    image boat_anim:
        "images/bg/1_ship/frame/1.png"
        0.11
        "images/bg/1_ship/frame/2.png"
        0.11
        "images/bg/1_ship/frame/3.png"
        0.11
        "images/bg/1_ship/frame/4.png"
        0.11
        "images/bg/1_ship/frame/5.png"
        0.11
        "images/bg/1_ship/frame/6.png"
        0.11
        "images/bg/1_ship/frame/7.png"
        0.11
        "images/bg/1_ship/frame/8.png"
        0.11
        "images/bg/1_ship/frame/9.png"
        0.11
        "images/bg/1_ship/frame/10.png"
        0.11
        "images/bg/1_ship/frame/11.png"
        0.11
        "images/bg/1_ship/frame/12.png"
        0.11
        "images/bg/1_ship/frame/13.png"
        0.11
        "images/bg/1_ship/frame/14.png"
        0.11
        "images/bg/1_ship/frame/15.png"
        0.11
        "images/bg/1_ship/frame/16.png"
        0.11
        "images/bg/1_ship/frame/17.png"
        0.11
        "images/bg/1_ship/frame/18.png"
        0.11
        "images/bg/1_ship/frame/19.png"
        0.11
        repeat

```

Here is a screenshot of the problem: https://imgur.com/a/Hx7RkY3
The load is very visible, and will create empty screen with white and black-box until the load is fully complete.
Except if the animation is preloaded but that would be a downgrade compared to before. 

Otherwise everything seems to work great so far, outside of this issue it seems to work perfect

**Comment by Andykl** [comment]
I have tested your test project on Win10 and can not reproduce it even with disabeled prediction. Maybe your project have some hidden differences from the test project. You may also check if with this nighly build problem is gone https://github.com/renpy/renpy/issues/3086#issuecomment-939401865. If not, you may also go back through the nightlies and find the one the prblem was introduced.
