### ISSUE TITLE
[Request] renpy.hide_all_screens()

### ISSUE THREAD

**Issue by neyunse** [renpy/renpy#3085]
I don't know if this would be a good idea, since renpy has its own screens running in the back, but maybe it could be adjusted to hide only user-created screens... Also, I don't know if this is already implemented.

`renpy.hide_all_screens()` Hide all open screens that were created by the user himself

**Comment by renpytom** [comment]
This sort of feels like something that could easily be implemented by a creator; and that would wind up being a footgun if implemented at the engine level. I'm also not completely sure how you'd wind up with screens you're out of control of to the point where this would be needed.

**Comment by PatrickBate** [comment]
Thing you're looking for is already implemented: renpy.scene(layer = "screens")
