### ISSUE TITLE
Make it possible to init Live2D without gl2 or with broken libs

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3093]
Live2D is the only thing which requires config.gl2 and make an error if it is not, when other gl2 things like matrixcolor, matrixtransform or camera silently ignore it and do nothing without gl2. The idea is to return a dummy thing, which could return `Text("Live2D is broken")` in its render, in case `live2d.init` results in error for some reason (which could be broken lib).
Right now to workaround it I have to do:
```py
init 500:
    if renpy.has_live2d():
        image a = Live2D(...)
        image b = Live2D(...)
    else:
        # Actually there is a CDD which ignore passed _duplicate args
        image a = Text("Live2D is broken")
        image b = Text("Live2D is broken")
```

**Comment by renpytom** [comment]
I'm not sure about this. 

My thinking is there are a few differences for Live2D. 

- Live2D doesn't support the same set of platforms as Ren'Py does, so dealing with the non-live2d case is going to be more common. (Ren'Py will be gl2-only after a few more releases, but this will be an ongoing issue.) 
- Detecting Live2D is not supported is easy to do at init time, whereas it's not easy to do with transforms and perspective.
- matrixcolor can often fall back to something useful, but that's not really true with Live2D. 

This is the sort of thing where I think it's probably better to leave the error handling to the creator. This can easily be done in a game using something like:

```renpy
init python:
    def MyLive2D(*args, **kwargs):
        if renpy.has_live2d():
             return Live2D(*args, **kwargs)
        else:
             return Placeholder("no live2d")
``` 

So it's not clear that doing this in the engine is good idea.

**Comment by Gouvernathor** [comment]
The example code you've give doesn't work, because fromthe second call on, `renpy.has_live2d()` returns True.
So, if you defind several live2d images in your game, only the first one will be defined as a placeholder, the others will all trigger some internal issue at some point (because live2d is actually missing/broken).

**Comment by renpytom** [comment]
I think this has been done since fe9d0fef1cbe5bc7316496daa81121b82248cd6d .
