### ISSUE TITLE
 [renpy/renpy] [7.4.9/7.4.10] If an image isn't preloaded, showing it some screen will make the loading extremely noticeable as blank images will fill the screen

### ISSUE THREAD

**Issue by Bobyteal** [renpy/renpy#3102]
https://github.com/renpy/renpy/issues/3082

Just a heads up but this issue still happens on 7.4.10.2178
So far, only reverting to renpy-nightly-2021-09-27-5b5127627-sdk fix the issues

**Comment by renpytom** [comment]
I'm closing this, as I think it  was fixed in the 7.4 series. Let me know if it's still showing up.

**Comment by Bobyteal** [comment]
The error was fixed in the most recent build!
(Sadly other problems appeared for my project using the most recent build (7.4.11) despite putting all the incompatibility commands that were added, at that point I have to accept the fact that I can't update the project anymore, I think it is to be expected past a certain number of versions)
