### ISSUE TITLE
Android cleanup

### ISSUE THREAD

**Issue by gimpyestrada** [renpy/renpy#3109]
More of a feature request than an issue.

Make a button in the Android screen that says "cleanup" or something similar.  And have this button empty out the \tmp directory as well as the \rapt\bin directories.  And anything else under the rapt directory you think could be safely cleaned.

**Comment by wbrambley** [comment]
Any chance to get this to re initialise the project folder? 
I'm not 100% sure but I think this is behind triggering the  "Install SDK & Create Keys" that pops up after running "Clean"

**Comment by gimpyestrada** [comment]
@renpytom would you need a new issue opened to deal with the above comment?

**Comment by Andykl** [comment]
Yeah, after removing those folders people need to "Install SDK & Create Keys" again but it runs like instantly because it only builds test project.

**Comment by renpytom** [comment]
Thanks for the catch, this should work better now.

**Comment by renpytom** [comment]
(In 69e6ffd09 .)

**Comment by wbrambley** [comment]
I'm getting this now after "Clean"
IOError: [Errno 2] No such file or directory: u'Z:\\renpy-7-nightly-2022-04-30-Alt_Saves-sdk\\rapt\\project/gradle.properties'
If I manually delete rapt\project and use "Install SDK & Create Keys" again it regenerates that file. (and possibly others needed)

**Comment by renpytom** [comment]
Can you send the traceback?

**Comment by wbrambley** [comment]
[traceback.txt](https://github.com/renpy/renpy/files/8598341/traceback.txt)
Sure.

**Comment by wbrambley** [comment]
This seems to fix the problem - when running configure before build anyway.
[launcher.zip](https://github.com/renpy/renpy/files/8598547/launcher.zip)
