### ISSUE TITLE
It is not possible to drag the grid or viewport when there are buttons with actions

### ISSUE THREAD

**Issue by maLikiz** [renpy/renpy#3110]
It is not possible to drag the grid or viewport when there are buttons with actions.

If you click in the space between the buttons, then only at this moment you will be able to drag the grid. But if you click on the button, then dragging does not work. I would like dragging to work if I hit the buttons. Is it possible?

Code example:
```py
# Code of documenation:
screen vpgrid_test():

    vpgrid:
        cols 2
        spacing 10 ## Modified by me
        draggable True
        mousewheel True

        scrollbars "vertical"

        # Since we have scrollbars, we have to position the side, rather
        # than the vpgrid proper.
        side_xalign 0.5

        for i in range(1, 100):

            textbutton "Button [i]":
                xysize (200, 50)
                action Return(i)
                ## Modified by me:
                background '#333'

label start:
    call screen vpgrid_test()
```

**Comment by renpytom** [comment]
At least for now, you will need to design around this.

**Comment by Andykl** [comment]
Duplicate of #1872.
The only solution for now is to define CDD like imagebutton which doesn't raise IgnoreEvent and CDSLS to this class.
