### ISSUE TITLE
Chromebook Touchpad Clicking, Keyboard, and Touchscreen

### ISSUE THREAD

**Issue by qirien** [renpy/renpy#3113]
I have a user who reported that using the touchpad to play the Android version of Our Personal Space 2 on a Chromebook mostly worked, but sometimes mouse clicks registered as two clicks, advancing text twice. The touchscreen works fine. I don't have a Chromebook to test on, but I wondered if this issue was with the Ren'py engine. 

I'm not sure if Chromebook users can use the keyboard, but that would be great if that worked, too.

Is there a way to include "Chromebook" as one of the emulation options for testing?

**Comment by renpytom** [comment]
I'm not able to replicate the "two clicks" problem on my Chromebook - I'd be curious if it occurs if an external mouse is plugged in. Just knowing how everything works, I don't see an obvious way that a click could be duplicated like this. 

The keyboard seems to work fine on ChromeOS. 

There are some mouse problems, though, that I'm tracking in #3118 .

**Comment by qirien** [comment]
You are right, it was with an external mouse. Maybe it is a compatibility issue with that mouse and the Chromebook? They did not give me any further information.
