### ISSUE TITLE
[Request] Counting words by characters in the Lint statistics.

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3114]
I was wondering if this might be interesting; the idea would be a separate stat count that shows per character total dialog blocks, words and characters.

I don't know how you could get the name; since I didn't look at the Launcher code thoroughly, but I think you could get it from the `Character()`. 

This could be useful for the developer to have an idea of how many words each character has, an example of use would be for voice actors. Each voice actor is charged for a certain amount of words, this could help to give an idea of how much would be the cost for each character.

Example:
```
Statistics:

The game contains 843 dialogue blocks, containing 9,245 words and 51,218
characters, for an average of 11.0 words and 61 characters per block.

The game contains 3 menus, 101 images, and 61 screens.

Characters statistics:

Eileen has: 400 dialogue blocks, containing 500 words

Aki has: 700 dialogue blocks, containing 1,000 words
```

**Comment by Gouvernathor** [comment]
A simple version could be to check what's written before the dialogue line, which would miss `extend` or treat it as one single character. Just putting a name between quotes, or defining a Character object in-place, or having a more complex expression returning a str or Character object, would be difficult if not impossible to scan properly.

A more complex version would require evaluating each of those expressions, which would obviously be complex, if not impossible in cases such as when a variable implicated in those expressions is not defined with a `define` nor `default` statement.

An arguable compromise could be to only consider stats about `define`d characters, plus the narrator, and ignoring all other dialogue lines.

**Comment by Neyunse** [comment]
@Gouvernathor It would be nice to add it using the simple form, so that it is not so complicated, as I said above, this feature would make it easier for the devs to have an approximate of how many words per character they have and use it as a reference for the voice actors.
