### ISSUE TITLE
[Android] .aab app crashes after downloading additional files from Google Play

### ISSUE THREAD

**Issue by npckc** [renpy/renpy#3115]
Hello, there seems to be an issue where when updating an app with the .aab format for Google Play, the app will crash on the "android-downloading" screen after downloading additional files from Google Play.

Unfortunately, I can't share a test project, since it seems to be an issue with Ren'Py and Google Play, but if you could share a Google account email with me, I can add it to the list of internal testers and provide a link to install an app where this issue is occurring. 

Notes:
- I am using Ren'Py version 7.4.10.2178.
- The crash occurred on a Pixel 3 running Android 11 but Google Play's pre-launch report also showed the same issue on all devices.
- No error message is displayed when the app crashes. It just closes and returns to the phone's home screen after displaying the "android-downloading" screen temporarily.
- This is for an app I am newly uploading to Google Play, hence only .aabs are accepted and I cannot use the old .apk format. (There doesn't seem to be any issue with updating old apps with .apks created using the same Ren'Py version. When I created an .apk and sideloaded it to my phone, it worked fine.)
- Using Build, Install, & Launch to try to install the app also caused the app to crash on the "android-downloading" screen.
- The app downloaded properly once, for the very first time I uploaded an internal testing build to Google Play, but when I uploaded a new version and updated through Google Play, the crashing began to occur. Uploading new versions causes the same issue.
- When updating the app, a notification will appear showing that the phone is downloading an additional file. The app will crash if it is opened before the download is finished as well as if it is opened after the download is finished.
- I do not use the Ren'Py-created android.keystore and bundle.keystore. Instead, I use a .jks file I created through Android Studio to act as both the android.keystore and the bundle.keystore. 
- Edit to add more info: I just tested this by trying to update an app currently on Google Play with an .apk and then updating it with an .aab, and the same issue occurs where after downloading the .aab and the additional file, the app crashes on the "android-downloading" screen.

I'm sorry I don't have any more specific information to provide, but I'm really not sure what could be causing this.

**Comment by renpytom** [comment]
You can add renpytom@gmail.com.

**Comment by npckc** [comment]
Thank you. I've added the email. If you are logged into the Google account, you should be able to download the internal test app here: https://play.google.com/apps/internaltest/4700486376229729463

**Comment by renpytom** [comment]
I see the crash. 

Can you upload two files for me, and send me the link? The first is the .aab you sent to google, and the second is rapt/blocklist.txt. 

If you need to send the link to renpytom@gmail.com, that would work. Thank you.

**Comment by npckc** [comment]
I've sent a download link to the files to the provided email.

**Comment by renpytom** [comment]
Can you send me the files you used to build the game? 

I've tracked the error down to:

```
Full traceback:
  File "game/tl/ja/splashscreen.rpyc", line 24, in script
  File "/home/tom/ab/renpy/renpy/ast.py", line 2519, in execute
    renpy.translation.add_string_translation(self.language, self.old, self.new, newloc)
  File "/home/tom/ab/renpy/renpy/translation/__init__.py", line 453, in add_string_translation
    stl.add(old, new, newloc)
  File "/home/tom/ab/renpy/renpy/translation/__init__.py", line 394, in add
    quote_unicode(old), fn, line))
Exception: A translation for "On" already exists at game/tl/ja/script.rpy:7116.

While running game code:
Exception: A translation for "On" already exists at game/tl/ja/script.rpy:7116.

Full traceback:
  File "/home/tom/ab/renpy/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/home/tom/ab/renpy/renpy/main.py", line 550, in main
    renpy.game.context().run(node)
  File "game/tl/ja/splashscreen.rpyc", line 24, in script
  File "game/tl/ja/splashscreen.rpyc", line 24, in script
  File "/home/tom/ab/renpy/renpy/ast.py", line 2519, in execute
    renpy.translation.add_string_translation(self.language, self.old, self.new, newloc)
  File "/home/tom/ab/renpy/renpy/translation/__init__.py", line 453, in add_string_translation
    stl.add(old, new, newloc)
  File "/home/tom/ab/renpy/renpy/translation/__init__.py", line 394, in add
    quote_unicode(old), fn, line))
Exception: A translation for "On" already exists at game/tl/ja/script.rpy:7116.

While running game code:
Exception: A translation for "On" already exists at game/tl/ja/script.rpy:7116.
```

Which is a sensible problem. What I don't get is why you're not seeing the error all the time, since the error should be occuring on the desktop, as well as Android.

**Comment by npckc** [comment]
I added the files I used to build the game as a zip to the Google Drive link I sent previously to your email. The source files don't seem to have a tl/ja/splashscreen.rpyc file though, and as you have surmised, the problem doesn't occur on PC. I tested creating an .apk file and the issue does not seem to occur there either.

**Comment by renpytom** [comment]
Question (me grasping a bit at straws here) - do you have other games you built this way? I'm wondering if things might not have been cleaned out, and we're seeing two games being built at the same time.

**Comment by npckc** [comment]
Ah, this should be it! I have a "splashscreen.rpy" used in other games and there is indeed an "On" which has a translation in the tl/ja/ folders in these games. As a note though, I made the .aab file on a freshly downloaded 7.4.10 where I downloaded RAPT anew, and on this installation of Ren'Py, I've only built two Android games, and neither of these games has the "splashscreen.rpy" or the translated .rpyc in their files (but both of them crashed on Android after downloading the update from Google Play).

**Comment by renpytom** [comment]
Hm... I found a bug where Ren'Py wasn't cleaning out the asset directories - so it really does feel like one of them had a translated .rpyc. 

Can you try tomorrow's nightly, the November 5 one, from https://nightly.renpy.org ? My feeling is this will fix it.

**Comment by npckc** [comment]
I built an .aab with the 11/5 nightly and that seems to have fixed the issue! Thank you so much for taking the time to look into it even when I didn't have much info to share about what could be going wrong.

**Comment by renpytom** [comment]
Thanks for working with me on this. I'll close the issue.
