### ISSUE TITLE
Matrix.ydy and zdz is wrong when a list of 4 numbers given

### ISSUE THREAD

**Issue by ruu2** [renpy/renpy#3121]
Hi. I'm sorry for reporting trivial bug.

Document said:

    Matrix([ 1, 2, 3, 4 ])

        would result in the Matrix::
            1.0, 2.0, 0.0, 0.0,
            3.0, 4.0, 0.0, 0.0,
            0.0, 0.0, 1.0, 0.0,
            0.0, 0.0, 0.0, 1.0,

but result is:

    Matrix([ 1.0000000,  2.0000000,  0.0000000,  0.0000000,
             3.0000000,  1.0000000,  0.0000000,  0.0000000,
             0.0000000,  0.0000000,  0.0000000,  0.0000000,
             0.0000000,  0.0000000,  0.0000000,  1.0000000,
     ])

Matrix([ 1, 2, 3, 4 ]).ydy is 1.0 not 4.0.

and source code(https://github.com/renpy/renpy/blob/master/renpy/display/matrix.pyx) is:

        if lenl == 4:
            (self.xdx, self.xdy,
             self.ydx, self.ydy) = l
            self.ydy = 1.0
            self.wdw = 1.0

I think self.ydy = 1.0 is wrong, self.zdz = 1.0 is correct, right?

**Comment by renpytom** [comment]
Yes, you're right.
