### ISSUE TITLE
Image location picker don't show the images in images folder

### ISSUE THREAD

**Issue by AnujaSL** [renpy/renpy#3122]
Hey
in the developer menu, the location picker  don't show the images I need... please help me

**Comment by renpytom** [comment]
Do you have an an example of the problem? It's working for me.

**Comment by AnujaSL** [comment]
@renpytom when I click on the image location picker it doesn't show any image in the game images folder.

(showing images are not in my game)

![Capture](https://user-images.githubusercontent.com/93642079/140690793-8a028db8-3296-41c3-9e7c-abea160203f1.PNG)

**Comment by renpytom** [comment]
Ah, not a bug. What you need to do is launch your game, then hit shift+D and go into the Image Location Picker. Since the Launcher is the wrong size (and this actually predates the launcher, if I recall correctly), the picker is in the game itself.

**Comment by AnujaSL** [comment]
It worked!, thanks for the support sier:)
