### ISSUE TITLE
[Feature req] Docstrings support

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3123]
Right now you have to use `#` for comments, it can be harder to read, and kind of a pain to write. I'd really like to be able to use Python docstrings for stuff like labels, screens, and transforms. Docstrings are also easier to parse than `#`-style comments.

```renpy
label do_stuff(amount, speed=5, callback_list=None):
    """
    This is a label that does stuff

    Available params:
        amount - int - amount of stuff
        speed - int - speed
        callback_list - list of callback labels, defaults to None

    Returns:
        boolean
    """
    $ success = func(amount, speed=speed)
    while callback_list:
        call expression callback_list[-1]
        $ callback_list.pop()
    return success
```

**Comment by Andykl** [comment]
Triplequote string in label flow is already taken as https://renpy.org/doc/html/dialogue.html#monologue-mode feature.

**Comment by Booplicate** [comment]
I'm not sure how many actually use that. Maybe there's some niche cases for that, but you get no exp control, no arguments. And imo it's harder to read, too. But if you think monologue mode is something necessary for the engine, you could start it after an empty line, so for labels it becomes:

```renpy
label mylabel:

    e """
This exists, for some reason.
    """
    return
```

And with docstrings:
```renpy
label mylabel:
    """This label is being used in X and Z flows"""

    e """
This exists, for some reason.
    """
    return
```

**Comment by renpytom** [comment]
Monologue mode is already part of Ren'Py, so we're not going to remove it for docstrings.

**Comment by renpytom** [comment]
Closing this, since I don't think this is going to happen. (It might work for screens, but it would be a semantics change for labels and transforms.)
