### ISSUE TITLE
[Ren'Py 7.4.11.2215] Variables displayed as text using brackets do not longer update their values

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3124]
In the latest prerelease 7.4.11.2215 this no longer works:

`bar value Preference("auto-forward time") `
`$ aft_bar_value = preferences.afm_time`
`text "[aft_bar_value]"`
                    
Which showed the value in real time as text when moving the bar or slider.
But it works again if the text is replaced by:

`text str(aft_bar_value)`

This happens to any updatable value not only sliders. For example I made an image gallery system that updates the unlocked images count each time the screen is showed and it's bugged now (sometimes it shows the real value and sometimes it shows "0"). It's solved by using `str(variable)` as text.

I traced this to the following commit (first present in nightly-2021-11-04-b457159e2): 
"sl2: Properly handle uses_scope with transcludes" [https://github.com/renpy/renpy/commit/43403e787e0ffe239841364e9f709e4bc4ed7061](url)

To be noted that  `text "[preferences.afm_time]"` still works.

Edit: I found out that the launcher does not show the current project title when selecting other projects in the list.

**Comment by renpytom** [comment]
Fixed by 3f7e65a.
