### ISSUE TITLE
Main images does not load in web above version 7.4.4

### ISSUE THREAD

**Issue by Neuropunker** [renpy/renpy#3125]
If you build the game with the web version and remove the images from the game.zip archive using progressive_download.txt, then the main images in the game are not loaded. Or it loads, but noticeably slower than, for example, in version 7.4.4 or 7.3.5. Only the image from the _placeholders folder is displayed.
this happens in all browsers.

**Comment by renpytom** [comment]
Can you please post your game files somewhere, so I can make builds of it? You can email a link to pytom@bishoujo.us.

**Comment by Neuropunker** [comment]
> Can you please post your game files somewhere, so I can make builds of it? You can email a link to [pytom@bishoujo.us](mailto:pytom@bishoujo.us).

Sent to you by mail

**Comment by renpytom** [comment]
I've asked for access for my google account. However, I'm unable to repeat this in using the_question with image preloading disabled.

**Comment by Neuropunker** [comment]
Gave you access


вс, 14 нояб. 2021 г., 2:04 Tom Rothamel ***@***.***>:

**Comment by renpytom** [comment]
I've emailed you a URL at which your files are hosted. They seem to work fine for me. I'm wondering if this might be a hosting or adblock-type issue.

**Comment by renpytom** [comment]
I  believe I've fixed this. Thanks for working with me to find the problem.
