### ISSUE TITLE
Error - Bad magic number for central directory

### ISSUE THREAD

**Issue by Neuropunker** [renpy/renpy#3129]
An error occurred when trying to build a game with a web collector, which has a large amount of data. For example 3gb. I suspect that the problem is not in your compiler, but in the library:  https://docs.python.org/2.7/library/zipfile.html

Is it possible to try to fix this?

https://drive.google.com/file/d/1T1JQeE-mJkTkO1mTWyIs9yHGv6CSGTLX/view?usp=sharing

**Comment by renpytom** [comment]
Can you please share me the files you're using to build the game? I might be able to fix this. 

That being said, I wouldn't expect a game that uses 3GB of data to be suitable for the web.

**Comment by Neuropunker** [comment]
Here are some download links for the game.

https://pixeldrain.com/l/uXe7c9i4#item=1  - for pc and mac
https://gofile.io/d/pxOSTg - for pc and mac
https://rpdl.net/misc/CollegeKings-14.0.1-mac-crunched.torrent  - torrent
file to mac
https://rpdl.net/misc/CollegeKings-14.0.1-pc-crunched.torrent - torrent
file to pc

ср, 17 нояб. 2021 г. в 04:54, Tom Rothamel ***@***.***>:

**Comment by KiloOscarSix** [comment]
@Neuropunker isn't apart of the CK Development Team and we ask this issue to be deleted

**Comment by renpytom** [comment]
I've deleted the post and blocked the user.
