### ISSUE TITLE
[Ren'Py 7.4.11.2228] Variables displayed as text using brackets STILL don't update their values

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3131]
In the newest pre-release 7.4.11.2228 the previously closed issue #3124 is still present although the launcher project name bug is resolved.

The text no longer reflects the bar value when moving the bar/slider:
`bar value Preference("auto-forward time")`
`$ x = preferences.afm_time`
`text "[x]"`

This fixes it:
`text str(x)`

**Comment by renpytom** [comment]
I believe this is fixed in the above commit. It should be in the 2012-11-18 nightly build.

**Comment by raspberry-soft** [comment]
It's fixed!

But I encounter new bugs due to this:

- `ScreenVariableInputValue()` no longer works. The traceback is:

I'm sorry, but an uncaught exception occurred.
  File "D:\Desktop\Otros\renpy-7.4.4-sdk/renpy/display/behavior.py", line 1221, in __init__
    default = value.get_text()
  File "renpy/common/00inputvalues.rpy", line 181, in get_text
    return cs.scope[self.variable]

- The launcher cannot create a new project pointing the error to the same line.

- Using `SetLocalVariable("page", 1)` to go through "pages" in a screen no longer works. Note: `default page = 0` is stated inside the screen.

**Comment by renpytom** [comment]
Okay, I'm pretty sure all of this is solved now. I had to back out quite a few changes and start over, but the end result is simpler, and I believe it should retain the same behavior as older versions of Ren'Py. I think tomorrow's nightly will be able to run all of the examples you gave correctly. 

Thanks for taking the time to work with me to deal with this, especially when I have "go fever".

**Comment by raspberry-soft** [comment]
Everything is fixed! Thank you!
