### ISSUE TITLE
persistent._seen_audio contains AudioData.data

### ISSUE THREAD

**Issue by ruu2** [renpy/renpy#3134]
Hi. I noticed that persistent._seen_audio contains instances of AudioData.
AudioData has binary data. So it is possible that size of persistent data becomes too big (and it does).

I'm not sure it is intentional or not. I mean I'm not sure whether persistent._seen_audio should contain whole AudioData or just contain filename part of AudioData only, but I think it's sufficient only filename part of AudioData is saved to persistent._seen_audio.

To be more concrete, I mean (for example):
    
https://github.com/renpy/renpy/blob/c5fe77dd5c9d3287e9f4e6158e3710a58f32a500/renpy/audio/audio.py#L654-L656

            for filename in filenames:
                filename, _, _ = self.split_filename(filename, False)
                if isinstance(filename, AudioData):
                    renpy.game.persistent._seen_audio[str(filename)] = True # @UndefinedVariable
                else:
                    renpy.game.persistent._seen_audio[filename] = True # @UndefinedVariable

How about this?

Sample code is here:

    label seen_audio_test:
        python:
            music = "audio/bgm/music.ogg"
            with renpy.file(music) as f:
                renpy.music.play(AudioData(f.read(), music))
        "AudioData is played."
        python:
            print(persistent._seen_audio)
            print([type(i) for i in persistent._seen_audio.keys()])
        "type of persistent._seen_audio.keys() are printed to console."
        return

**Comment by ruu2** [comment]
If there is some reason why whole AudioData is saved to persistent data, I'm sorry for that report.

**Comment by Andykl** [comment]
It is a bug for sure. This is what `filename` in AudioData stand for.

**Comment by Booplicate** [comment]
I fixed it like this in my project
![Capture](https://user-images.githubusercontent.com/53382877/142723482-22f1ac7d-affb-41da-89f7-82278fddea66.PNG)
