### ISSUE TITLE
Dissolve shows checkered background on screens that load large lists.

### ISSUE THREAD

**Issue by JiGSaWKilla89** [renpy/renpy#3135]

**Comment by JiGSaWKilla89** [comment]
A noticeable checkered background shows when using dissolve on buttons in screens that load data from relatively large lists.

First noticed it in the 7.4.9 update. The video below the first part of the clip is from 7.4.8 and the second part is from 7.4.10

The first part shows no issues with the dissolve works as intended. The second part gets haywired. Though this is only where large lists are involved. If I removed all the data from the list and having only say 2 galleries load then the issue isn't present

https://user-images.githubusercontent.com/93424001/142733599-b173d426-04e3-4bb2-93f2-5088fe56ee9a.mp4

**Comment by renpytom** [comment]
Can you put together a small demo of this, that's standalone? This seems more likely to be a programming error than a bug in Ren'Py - like the screen is going away, shown for a frame, and then replaced.

**Comment by JiGSaWKilla89** [comment]
On another note, if I use any other transition it transitions perfectly, and also when I don't use any transition there are no issues.

I will attempt to put together a small demo.

**Comment by JiGSaWKilla89** [comment]
https://drive.google.com/file/d/1MJJEJFyauJQXKAhRiXxCZMLYZIFu9P79/view?usp=sharing

Made a small demo with just this gallery. Works fine in 7.4.8 but still the same issue in 7.4.9 and upwards.

Excuse my mess of coding.

**Comment by renpytom** [comment]
Can you please grant renpytom@gmail.com access to that file?

**Comment by JiGSaWKilla89** [comment]
Granted

**Comment by renpytom** [comment]
Bisecting shows this was introduced by 372d6d026ee1c84b0acab72233fc70623bb389de .

**Comment by JiGSaWKilla89** [comment]
nightly-2021-11-24-30b851920 problem is solved. No more checkered background on Dissolve. Thanx PyTom
