### ISSUE TITLE
 [7.4.11.2228] Android Porting Error

### ISSUE THREAD

**Issue by Nek9-oxp** [renpy/renpy#3141]
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html
Process command line: C:\Program Files\Eclipse Adoptium\jdk-8.0.312.7-hotspot\bin\java.exe -Xmx3g -Dfile.encoding=windows-1252 -Duser.country=CO -Duser.language=es -Duser.variant -cp C:\Users\victo\.gradle\wrapper\dists\gradle-6.1.1-bin\4i3ntwqiazourd86epxcz427c\gradle-6.1.1\lib\gradle-launcher-6.1.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.1.1
Please read the following process output to find out more:
-----------------------
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by renpytom** [comment]
It strikes me that C:\Users\victo.gradle\ seems like a weird place to put gradle, so perhaps there's something going wrong there. What's the path to Ren'Py and rapt?

**Comment by Nek9-oxp** [comment]
I have ren'py on my desktop

**Comment by renpytom** [comment]
That's not your desktop. Perhaps create c:\renpy and put Ren'Py there. You'll need to re-do the install sdk step.

**Comment by Nek9-oxp** [comment]
Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 602, in main
    renpy.dump.dump(False)
  File "renpy/dump.py", line 260, in dump
    os.rename(new, filename)
WindowsError: [Error 3]

This is the new error I am getting when creating a project

**Comment by renpytom** [comment]
Hm... That's a problem with your system, Ren'Py doesn't have permissions to rename a file.

**Comment by Nek9-oxp** [comment]
I still have the same errors that I showed previously, but I followed the steps you told me to follow

**Comment by renpytom** [comment]
I don't know what to say. This is a permissions problem on your end, not a Ren'Py problem.

**Comment by Nek9-oxp** [comment]
Could you tell me what should I do to solve this permissions error?

**Comment by renpytom** [comment]
Unfortunately, I don't know. It's a problem with your computer.
