### ISSUE TITLE
No option to set music volume for main menu

### ISSUE THREAD

**Issue by Kazuo256** [renpy/renpy#3142]
There's only a `config.main_menu_music_fadein` variable, but nothing to set the volume. Setting the volume from the splash scene only works when the game opens - if you go back to the menu from inside the game, it uses de default music volume.

**Comment by renpytom** [comment]
Setting volume isn't really meant to be a substitute for equalizing your music in a tool meant for that purpose. That being said, you should be able to define a ``before_main_menu`` label and set the volume in there.

**Comment by Kazuo256** [comment]
> That being said, you should be able to define a before_main_menu label and set the volume in there.

That's very good to know! Thanks!

> Setting volume isn't really meant to be a substitute for equalizing your music in a tool meant for that purpose.

In this case, the music is already equalized. We just wanted to change the volume in the main menu specifically, because sometimes there are other sounds in the game so we need *more* equalizing during runtime. I imagined that's one of the purposes of being able to set the volume inside the game at all, right?

From what I read in the code, I imagine it's possible to add the feature [around here](https://github.com/renpy/renpy/blob/d3657005d84156c03f0ba97d7f5376d1bf7ee06f/renpy/common/00start.rpy#L243). I offer to open a PR for that feature if that is ok. If we can make devs life a little easier with ren'py, I'm glad to help =)
