### ISSUE TITLE
Dialogue renders part of the next line outlines when displayed.

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3143]
Tested on 7.4.10, latest nightly, 7.4.7, and 7.3.5

When the text is being displayed on the screen, the top part of the next line outline is rendered together with the current line.

![1](https://user-images.githubusercontent.com/87047775/143496070-767c83f7-2aa7-402d-8227-07915e16dc43.png)
![2](https://user-images.githubusercontent.com/87047775/143496103-35c80f3b-19dd-4179-8ee7-d802be5b75d6.png)

Replicate:
- Create new 1080p project.
- Put an outline on the dialogue text. I used a white 6p outline on a black text with `define gui.dialogue_text_outlines = [(6, '#ffffff', 0, 0)]` for it to be noticeable. (it can be noticed with less)
- It's independent of line spacing but with some size/font combination it may disappear.

**Comment by renpytom** [comment]
Documented.

https://www.renpy.org/doc/html/text.html#slow-text-concerns
