### ISSUE TITLE
Can't figure out how to build from the source code .bz2

### ISSUE THREAD

**Issue by DandelionSprout** [renpy/renpy#3154]
Hello. I've tried to download the 7.4.11 source code from https://www.renpy.org/dl/7.4.11/renpy-7.4.11-source.tar.bz2 and extracting it; but as someone with only intermediate Linux experience (Enough to handle command lines, disk resizing, ssh, and a few services; but lack experience with building from source), I can't seem to get `sudo ./configure` to work because the source code folder doesn't have such a file; `sudo make` gives me `make: *** No targets specified and no makefile found.  Stop.`; and I haven't had success at the time of writing with finding a Readme or build guide within the .bz2's source code (as opposed to on the seemingly pretty different source code here on GitHub) that could give me additional understanding of the building procedure.

Setup:
Distro: Fedora Workstation 35 stable
Distro architecture: aarch64
Hardware: Raspberry Pi 4 8GB

**Comment by renpytom** [comment]
https://github.com/renpy/renpy#compiling-the-modules

Shows how to do a basic build. Note that there already is a (32-bit) raspberry pi build.
