### ISSUE TITLE
blur documentation

### ISSUE THREAD

**Issue by SpaceLanesGame** [renpy/renpy#3157]
The docs list it as None or float, but it seems like it should be None or int? It's looking for a pixel value.

https://www.renpy.org/doc/html/atl.html#transform-property-blur

image test1 = Transform("test", blur = 1.0) #no visible effect
image test2 = Transform("test", blur = 10.0) #blurs as expected
image test3 = Transform("test", blur = 10) #also blurs as expected.

**Comment by renpytom** [comment]
1.0 turns one pixel into 1 pixel, so it's not blurring. 1.5 has a visible effect, and so do larger blurs.

**Comment by SpaceLanesGame** [comment]
Just my misunderstanding then, appreciate the clarification.
