### ISSUE TITLE
In music room stopping a paused track should not play a fadeout 

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3158]
In the latest nightly, if a track is stopped while paused it makes the track play the music again while making a fadeout (the one specified in  config.fade_music i think) independently of the music room fadeout time. Stopping a track should not replay the music.

This should fix it:

In music.py line 282 replace None with 0.0

`if get_pause(channel=channel):`
`fadeout = 0.0`

*Also I think it should be documented that renpy.music.get_duration() and AudioPositionValue() does not work on mp3 files. At least that's my experience.

**Comment by renpytom** [comment]
You're right on both counts. I've made the changes. Thank you.
