### ISSUE TITLE
' init python: ' command reads value changes in whole script

### ISSUE THREAD

**Issue by Atomic-44** [renpy/renpy#3159]
I am using the 

init python:

command to import 

random.randint(a, b)

functions, as well as keeping track of values like 

Passengers = int(100)

 According to the players choices, the value of num1 is subtracted or added to, such as 

init python:
    Passengers -= 3
"Passengers (stasis): [Passengers]"

However, when I display the passenger count several lines above subtracting the value, it has already subtracted it. I do not know why it seems to read value changes for the entire script before reaching those lines. I may just be doing it incorrectly. 
I know I've not done the best job explaining it, so I will attach a text file copy of my script. Please note this project is in its infancy, and I am a very new creator. If the problem is a result of my inexperience and not the program, I will be pleased to know how to fix it. 
[Script Copy.txt](https://github.com/renpy/renpy/files/7656777/Script.Copy.txt)

Thank you very much for your time,
    Atomic-44

**Comment by renpytom** [comment]
You don't want to be using init python here, at all. 

The initialization up top is best done with the default statement.

```
default Passengers = 100
default Redirectional = 100
```

and so on for the others. Later down in the game, you can change these with the python statement, which can be abbreviated to $ when it's a single line long. 

```renpy

python:
     Passengers -= 1

$ Redirectional += 1
```

I'd suggest looking at the quickstart:

https://www.renpy.org/doc/html/quickstart.html#supporting-flags-using-the-default-python-and-if-statements

And going from there. I don't think that this is a problem with Ren'Py proper - your best bet is to ask for help on the Ren'Py discord, or on the Lemma Soft Forums, as people there are better at explaining Ren'Py than I am. 

Thank you.

**Comment by Atomic-44** [comment]
@renpytom thank you so much, this is incredibly useful! It worked right away!
I will definitely dig through the quickstart and hop on the discord. 
You're a saint!

Thank you again, 
    Atomic-44.
