### ISSUE TITLE
[BUG] [7.4.10.2178] Some computers skip over animated splash-screen (happens instantly)

### ISSUE THREAD

**Issue by slobodaapl** [renpy/renpy#3164]
Some PCs seem to not properly show and animate the splash screen. I've investigated this issue with users on the RenPy Discord and Reddit but nothing seems to have worked to solve the issue.

It seems to work on about 50% of computers correctly and doesn't work (just skips the splash or it happens rapidly in like 2 frames) on others, so this is not a consistent issue. It works perfectly fine on mine and some of the tester's PCs in both development builds (launching the project through RenPy) and both production builds (built with RenPy for Windows and Linux).

More information is available in the Reddit post including videos: https://www.reddit.com/r/RenPy/comments/r9xqq5/splashcreen_speedup_bug/

I've arrived at the conclusion that this is likely a RenPy bug.

**Comment by uyjulian** [comment]
For the computers where the splash happens rapidly, I would recommend transferring the files to a spinning disk HDD or other slow storage device and run the game from there.

**Comment by renpytom** [comment]
Could the tester(s) have transitions disabled in their preferences?

**Comment by slobodaapl** [comment]
> Could the tester(s) have transitions disabled in their preferences?

The simplest solutions are typically the best. Yes that was the problem. It seems for some reason that the RenPy default is to have transitions skipped for some reason.

**Comment by renpytom** [comment]
No, that's not the default - it's something the player would have had to have selected.

**Comment by slobodaapl** [comment]
> No, that's not the default - it's something the player would have had to have selected.

That is odd then, because I just asked a few of my testers and they said they didn't turn it on themselves. It seems to have been on for about half my testers and off for the other half, without them ever even accessing the preferences. I'm thinking it's maybe something that transferred over when I built the game and distributed it, since maybe I could've had it on, but then I'd notice the same issue on my side which I never did, cause it always worked for me so it must've been off the whole time.
