### ISSUE TITLE
7.4.11 Generate Translations problem

### ISSUE THREAD

**Issue by shelling4d** [renpy/renpy#3167]
I generate translation files in 7.4.11 and 7.4.10 respectively, but the following code can be exported normally in 7.4.10, but not in 7.4.11.
Was there something has changed?

`screen word_cheat2:
    text _("{color=#000000}3 letter:SHE,SEE,REP,PER,PEE,HER\n4 letter:SEER,SEEP,REPS,PEER,HERS,HERE\n5 letter:SPREE,SHEER,SHEEP,PEERS 6 letter:HERPES,SPHERE {/color}")`

**Comment by Gouvernathor** [comment]
Can't reproduce.
![image](https://user-images.githubusercontent.com/44340603/145555625-c7611bb3-6be6-4aaa-95ce-aafa89a4b075.png)
This prints normally in-game, in both None and french (in my case) languages.

**Comment by Gouvernathor** [comment]
I added your code in a game with no french translation, and generated the translation from scratch. The 14 first lines of this file were generated at the same time as the others.

**Comment by shelling4d** [comment]
> I added your code in a game with no french translation, and generated the translation from scratch. The 14 first lines of this file (and the whole tl/french folder) were generated at the same time as the others. Do you mean the option "generate empty strings for translation" ?

yes ,Do you need whole rpy file?

**Comment by Gouvernathor** [comment]
After deleting the translation files and re-generating them with the empty string option enabled, no problem seem to arise
![image](https://user-images.githubusercontent.com/44340603/145580716-66187b4f-df9f-43ef-ad44-eff497a77df9.png)
You can send the whole .rpy file if you wan't but it doesn't seem like this is the problem.

**Comment by Gouvernathor** [comment]
What is the behavior happening to you in 7.4.11 ? Is there an exception being raised ? Does it generate a different string ?

**Comment by renpytom** [comment]
I'm also unable to repeat this.
