### ISSUE TITLE
For some unknown reason, the persistent file changed incorrectly and crashed the game.

### ISSUE THREAD

**Issue by maLikiz** [renpy/renpy#3168]
For some unknown reason, the persistent file changed incorrectly and crashed the game.

It was just loading the game and stopped loading without any errors. The log files and traceback did not report any error. Force recompile did not work, caused an error:
![image](https://user-images.githubusercontent.com/4878139/145496163-df20c41d-785f-4064-b1eb-3291305954b8.png)

Switching to another branch in the project's git also didn't help. I decided to try deleting the persistent file and it helped me. The only thing I'm worried about is that it won't happen again. Probably the best thing for me is to find out the reason why the persistent file has not changed correctly. Is it possible to read the persistent file in a different way?

**Comment by renpytom** [comment]
This is unlikely to be an issue in Ren'Py. The only thing I can think of would be that there's a problem in a game's init python code, which was causing an exception. That should have been logged to log.txt or traceback.txt. 

There isn't any way to read the contents of the persistent file.

**Comment by renpytom** [comment]
Not directly, but custom object can't go into persistent.

**Comment by maLikiz** [comment]
Since I still haven't been able to reproduce this issue again, I'm closing it.
