### ISSUE TITLE
Add a file into APPdata to disable powersaving globally (all game).

### ISSUE THREAD

**Issue by BirdInFire** [renpy/renpy#3169]
I actually Qcheck some game for dev (checking if the game don't have bug and so on) by launching them and many of them flicker (Intel Iris Xe, i have to manually Shift + G on each game at each start.
Can we have a way (master settings) to enforce ALL ren'py game to disable this powersave ?

I only have found out after many month of try error (debugging at start i have thinked it was my computer the culprit) and i only have found today in the doc this manual (shift at boot or shift + G when booted).

**Comment by raspberry-soft** [comment]
Maybe try:

`default preferences.gl_powersave = False`

**Comment by renpytom** [comment]
I think the request is to have a global settings file that overrides this and other preferences. Though it seems weird that the game is flickering in the first place - have you raised the issue with Intel?

**Comment by BirdInFire** [comment]
> I think the request is to have a global settings file that overrides this and other preferences. Though it seems weird that the game is flickering in the first place - have you raised the issue with Intel?

i have reported to intel and dell, but if it impact me it must impact other player as well who don't have enough knowledge to find the way to avoid it.
Because since i manually disable this on all game i try the flicker have disappear.

Maybe add to the doc (at least) in troubleshot this workaround.

**Comment by BirdInFire** [comment]
and maybe try to see if other user of intel Cpu with Iris Xe graphics on W11 have the same problem. (for the troubleshot)
Because since i don't have another pc with this kind of graphical unit, i cannot see if it's only my pc or windows the culprit.

**Comment by renpytom** [comment]
Has this been fixed in newer releases of the Xe drivers?

**Comment by BirdInFire** [comment]
> Has this been fixed in newer releases of the Xe drivers?

don't really know just have switched my dell to Linux (launch game with the launcher) and here the problem doesn't occur, will close this (if it append again or other user have the problem the surly will reopen one.
