### ISSUE TITLE
Saving nested classes

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#3171]
Hello! Is it possible to save a class with nested classes? Did not find any info about it.
When I create a 'Post' class it works fine but when I create a 'Comment' class using 'add_comment' function and then press save button the game raises PicklingError: Can't pickle <class 'store.Comment'>: attribute lookup store.Comment failed Windows-10-10.0.19041 Ren'Py 7.4.11.2266

Seems like that the type of the 'Comment' class just doesn't have a full path.

```
init python:

      class Comment:
      
          def __init__(self, name, text):
              self.name = name
              self.text = text
      
      def __init__(self, text):
          self.text = text
          self.comments = []
      
      def add_comment(self, *args, **kwargs):
          rv = self.Comment(*args, **kwargs)
          self.comments.append(rv)
          print(type(rv))
      
          return rv
```

**Comment by Andykl** [comment]
No, it is impossible by default to save closure functions or classes or lambdas as well as dynamically created classes. The good thing is that you always can move out such a class with a prefix (to avoid possible name conflict) and it will work.

However, it is possible to have such a thing and pickle it, but it is advanced stuff involving reduce. You may read about it in python pickle module docs.
