### ISSUE TITLE
Subpixel does not work with panning

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#3174]
Using subpixel with xpan/ypan in transforms doesn't smooth out movements. 
Panning is a really good feature. I hope it can be fixed somehow.

**Comment by renpytom** [comment]
Do you have an example of your transform? I believe that:

```
transform panning:
     xpan 0.0
     linear 10.0 xpan 360.0
```

Should work and be smooth - the .0 at the end is important, as it tells ATL to use floats rather than integers.

**Comment by via-my** [comment]
Well, I checked the code below on 7.3.5 and 7.4.0/7.4.11 with and without .0 and it seems to work properly in 7.3.x. Noticed that .0 at the end makes no difference when 'subpixel' makes it work fine.

```
transform panning:
     align (.5, .5) subpixel True
     linear 10.0 xpan 360.0
```
