### ISSUE TITLE
Request: Support for kerning for .ttf 

### ISSUE THREAD

**Issue by npckc** [renpy/renpy#3179]
Would it be possible for Ren'Py to support kerning for .ttf fonts? It doesn't seem to apply the kerning for .ttf files at all.

Example:
In Ren'Py: ![image](https://user-images.githubusercontent.com/50103058/145757416-e2a30710-a63c-48db-9167-7dae79a267db.png)
In a regular text editor: ![image](https://user-images.githubusercontent.com/50103058/145757478-455b5bff-db72-498c-9b34-76bd589964aa.png)

Note how the T and e have much more space between them in Ren'Py than in the text editor, and the other letters are spaced differently as well.

**Comment by uyjulian** [comment]
Ren'Py does not do text shaping.  

In order to do text shaping probably making use of the Harfbuzz library would need to be implemented.

**Comment by renpytom** [comment]
Ren'Py does do kerning and Arabic text shaping, so it's not clear why this isn't working for this font. Is the font open?

**Comment by npckc** [comment]
The font I'm using is a .ttf I made myself, but your comment got me curious so I tested with some other fonts too.

Ren'Py's default DejaVu Sans kerns properly in the game. However, Opendyslexic (from accessibility options), Pangolin and Yusei Magic (random .ttf fonts from Google Fonts) do not seem to - it seems to be taking only the character width into account, and not individual kern pairs.

Ren'Py: ![image](https://user-images.githubusercontent.com/50103058/146021556-6a4d322c-d9f3-457e-a7ba-be4a7595a023.png) ![image](https://user-images.githubusercontent.com/50103058/146021998-4d7ba49f-8619-4351-8c13-668bb7a7f20d.png) 
![image](https://user-images.githubusercontent.com/50103058/146022380-32d4b79f-48d6-403c-b37d-f284020b2e8b.png)

Text editor: ![image](https://user-images.githubusercontent.com/50103058/146021479-1c6673e4-a7db-4838-bbee-137958a2e3bc.png) ![image](https://user-images.githubusercontent.com/50103058/146022041-038e492a-a913-45f5-b3a4-b3fc31d51af3.png) 
![image](https://user-images.githubusercontent.com/50103058/146022439-154b90b5-900e-4262-b665-de682659ec85.png)

Here are download links for Pangolin and Yusei Magic for reference:
https://fonts.google.com/specimen/Pangolin
https://fonts.google.com/specimen/Yusei+Magic
