### ISSUE TITLE
Implement renpy.music.get_duration for mp3

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3192]
There is [apparently](https://stackoverflow.com/questions/6037826/finding-the-length-of-an-mp3-file) a number of ways to extract a mp3's duration from python.

A first possibility could be to adapt specific strips of the py3.6 [mutagen module](https://github.com/quodlibet/mutagen), just what's necessary, backport it to py2-3 compatibility and get it in renpy. They claim to only use the standard library, which is cool, but the GPL2 license might get in the way.
Another one would be to delegate calculation to ffmpeg, which may or may not be included in renpy (according to the [license](https://www.renpy.org/doc/html/license.html) page).
Either way, since this is a lengthy operation, there should be some sort of cache dictionary to memorize the duration of the files already computed.

**Comment by renpytom** [comment]
This probably isn't going to happen. There are way better formats that make this far easier, and games should prefer them to mp3. If you have to use mp3, just create a table of how long your files are.
