### ISSUE TITLE
Live2D expressions fade doesn't work in CDD + Screen

### ISSUE THREAD

**Issue by Archy812** [renpy/renpy#3193]
Hi!

I stumbled on a problem that I can't find a solution and this looks like a bug.

I use CDD for additional interactive logic in the live2d model until we need to not only play different motions by user input but also enable/disable a number of expressions at the same time.

Let's take example model "Epsilon" from Cubism site (test game with model and code attached [game.zip](https://github.com/renpy/renpy/files/7762867/game.zip))

```
image epsilon_test = Live2D(
    "epsilon",
    loop=True,
    seamless=True,
)

define anim1 = "epsilon_test shake_01"
define anim2 = "epsilon_test shake_01 angry"
```

While a change of expressions in common Ren`py flow works as indented:
```
label start_common:
    show epsilon_test shake_01 angry

    "1"

    show epsilon_test blushing
 
    "2"

    show epsilon_test sad

    "3"

    jump start_common
```

But if we try to work with CDD + Screen like:
```
screen epsilon_dynamic(ed):
    
    add ed
    
    vbox:
        align (.5, .5)
        
        textbutton "change state (Transform.set_child)"  action ed.change_image1
        textbutton "change state (new Transform)"  action ed.change_image2

init python:
    class Ed(renpy.Displayable):
        def __init__(self):
            super(Ed, self).__init__()
            
            self.img_obj = Transform(anim1)
            self.state = 0
            self.clock = 0
            
        def render(self, width, height, st, at):
            render = renpy.Render(width, height)
            
            self.clock = st
            
            render.place(self.img_obj, st=st, at=at)
        
            renpy.redraw(self, 0)
            return render
            
        def change_image1(self):
            if self.state == 0:
                self.img_obj.set_child(anim2)
                
                self.state = 1
            else:
                self.img_obj.set_child(anim1)
                
                self.state = 0
                
        def change_image2(self):
            if self.state == 0:
                self.img_obj = Transform(anim2)
                
                self.state = 1
            else:
                self.img_obj = Transform(anim1)
                
                self.state = 0
            

label start:

    $ ed = Ed()
    
    call screen epsilon_dynamic(ed)
    
    jump start
```

We got two behaviors, the animations reset on change in one or expressions lost fade in other.
Both variants are not satisfactory as expressions fading is very important in the given scene

I tried to find a workaround, like moving image rendering out of the screen, but can't get different results.

Is this a bug or is there a way to make it work?

P.S. Tested on Ren`Py 7.4.6 and 7.4.11

**Comment by renpytom** [comment]
I don't expect Live2D to work inside a CDD like this. It really does depend on how Ren'Py handles attributes, which you're not doing there.
