### ISSUE TITLE
Simulating a keypress event

### ISSUE THREAD

**Issue by altskop** [renpy/renpy#3205]
Hi!

Is it possible to simulate a keypress so that screens with configured keysyms would receive an event?
A usecase for this could be an accessibility option, so that some on-screen imagebutton could be used instead of the physical keyboard.

I tried replicating the method found in [00touchkeyboard.rpy](https://github.com/renpy/renpy/blob/master/renpy/common/00touchkeyboard.rpy), but while the events were generated properly, they were not received by the screen.

Here's the relevant code sample:

```
init python:

    # This is the method we'll be calling to simulate the keypress
    def simulate_keypress(unicode_key, pygame_key):
        pygame_sdl2.event.post(pygame_sdl2.event.Event(
                pygame_sdl2.KEYUP,
                key=pygame_key,
                scancode=pygame_key,
                unicode=unicode_key, mod=0, repeat=False,
            ))

# This is the screen that should respond to keypresses
screen controls:
	... # irrelevant code parts and graphics
	if controls_enabled:
                key "w" action Function(game_logic.go_up)
                key "s" action Function(game_logic.go_down)

# This is the "accessibility" screen, exposing on-screen controls that should simulate keypresses.
screen screen_controls:
    imagebutton:
        idle "arrow_up.png"
        action Function(simulate_keypress, unicode_key="w", pygame_key=pygame_sdl2.K_w)
    imagebutton:
        idle "arrow_down.png"
        action Function(simulate_keypress, unicode_key="s", pygame_key=pygame_sdl2.K_s)
```

Are there any built-in ways of simulating keypresses that could be used in this scenario? Is there something about how pygame events are processed by the screens that would prevent this from working?

Any pointers would be appreciated.

**Comment by renpytom** [comment]
That method should work. For a key with a proper binding, you can also use renpy.queue_event.

**Comment by altskop** [comment]
I've only tried simulating key up, so perhaps that's the catch. Thanks, Tom, I'll try that out and report the outcome as soon as I get a chance.

**Comment by altskop** [comment]
Simulating keypress down first, then up did the trick. Thanks again, Tom. Closing the issue.
