### ISSUE TITLE
7.5.0.242n nightly contains excess libs

### ISSUE THREAD

**Issue by wbrambley** [renpy/renpy#3208]
Hi, I noticed a slight size increase when building for Android. 
It appears there are excess unrequired lib files packaged in private.mp3.
Here's a comparison from what I was using until now. 
![private_mp3_size](https://user-images.githubusercontent.com/1310205/147844243-5d1b781a-d7bc-458f-95c1-510392c9c85f.jpg)

**Comment by renpytom** [comment]
Thanks for letting me know. A bunch of folders in lib/ changed names, and the list of patterns needed to be updated.
