### ISSUE TITLE
Ren'Py 7.4.11.22.66 - Auto-reload breaks every loop movie sprites.

### ISSUE THREAD

**Issue by rafi-hdw** [renpy/renpy#3209]
image misty_ancientcloth = Movie(play="movies/cg/misty_ancientcloth.webm", loop=True, size=(1920,1080))
image misty_first_encounter = Movie(play="movies/cg/misty_first_encounter.webm", loop=True, size=(1920,1080))
image misty_first_encounter spread = Movie(play="movies/cg/misty_first_encounter_spread.webm", loop=True, size=(1920,1080))

First boot it works fine, but as soon as I do Shift+R or Auto Reload, every loop will break and it will now loop every +- 0.5 seconds, no matter how long the video is

**Comment by renpytom** [comment]
Tentatively closing this, as I've tried this in 8.0, and it seems to be working now. Feel free to reopen this if it's broken in Ren'Py 7.5 or 8.0.
