### ISSUE TITLE
Default encoding in py3

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3212]
The way the `open()` function works seems to have changed (which is discussed [here](https://stackoverflow.com/questions/36303919/python-3-0-open-default-encoding) and in py 3.10's [PEP 597](https://www.python.org/dev/peps/pep-0597/)).
As a result, seemingly all `open()` done within renpy8 open files in ascii mode.

That's causing, as one side-effect instance, the fact that error reporting can't write to traceback.txt anymore, because of this : https://github.com/renpy/renpy/blob/33be897a081815c32d10fb08ae46148126f8a54c/renpy/error.py#L219
...and this in return causes the "Copy Markdown/BBCode" buttons to fail, since they open and read the traceback.txt file even though the very information they're seeking is displayed on-screen (which may deserve an issue in itself).

The canonical solution seems to be adding either `encoding="utf-8"` or `encoding=locale.getpreferredencoding()` (because it's ***not*** the default value, [this piece of doc](https://docs.python.org/3/library/functions.html#open) is lying, test it) to every open() in the code.
I'd advocate, instead, to add an open() wrapper in renpy.compat, which would have that value as a default. If the locale encoding is preferred, then this is simpler, since importing renpy.compat.open or locale will be necessary in any case.
Anyway, a choice probably has to be made between activating utf-8 everywhere or reading locale's default encoding.

Another solution could be to enable [Python's UTF-8 mode](https://docs.python.org/3/library/os.html#utf8-mode).

**Comment by renpytom** [comment]
We should be using utf-8 mode when run using the scripts. How are you starting Ren'Py?

**Comment by Gouvernathor** [comment]
Opening the .exe file.

**Comment by renpytom** [comment]
What does sys.getdefaultencoding say?

**Comment by Gouvernathor** [comment]
utf-8

**Comment by Gouvernathor** [comment]
seems fixed by renpy/renpy-build@91f511d82091053281a365c888fe00049faf4cbb
