### ISSUE TITLE
Feature Request: Include `offset` in bar::AnimatedValue()

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#3215]
Currently to my knowledge,
```py
bar value AnimatedValue(-10, 10, 2, 20)
```
`AnimatedValue` doesn't work with negative numbers. Would be ideal if we could use `offset` such as in `VariableValue` to shift the range of the bar value

**Comment by renpytom** [comment]
Having looked into implementing this, I think it's a bit confusing - if we do offset=10, should that get added into the range? 

I think the right way to do this is to just add the offset yourself, since the value is available. 

```renpy
bar value AnimatedValue(-10 + 10, 10, 2, 20)
```

or more likely:

```renpy
bar value AnimatedValue(x + 10, 10, 2, 20)
```
