### ISSUE TITLE
Rollback options in preferences are unintelligible and seemingly useless 

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#3216]
I wanted to bring up an issue I've had for a long time with one of the default naming conventions in the preferences menu - the rollback system. I've been working with renpy and entrenched in visual novels for the better part of a decade, and I still never have a clue what rollback left, right, or disabled do. I can't imagine the average player will know either.

The idea of clicking on the left half of the screen to go back in the script feels very unintuitive for a game interface on a desktop computer. And the option for it to be on the right makes it even harder to conceptualize cause why would anyone want it to be on the right? Is this meant for Japanese players who are used to reading right to left? Usually the left is associated with going back, not the right. It feels so confusing. 

Rollback is already part of the quickmenu UI through the "Back" button. Isn't this alone already the most clear and complete implementation of the tool? And it's also bound to scroll up as another relatively intuitive backup. The added options in the preferences just seem to take up space, being both unintelligible and seemingly useless.

I could see these *possibly* being useful for mobile, as it's a better interface than hitting tiny buttons, but I think it should still need better naming to explain what it does if so. Or have tooltips built into the default UI to explain what it does (though are those a thing in mobile?). As it is "Rollback: left | right | disabled" are totally cryptic.

Ideally this option wouldn't show up at all on desktop releases, in my opinion, unless otherwise set by the developer. It's an option that I imagine everyone ignores because they have no clue what it does, and even if they did, I don't see why anyone would use it.

**Comment by renpytom** [comment]
It's mean for use on tablets and convertible laptops, where an ebook-like interface works, and where tooltips do not in touch mode.

**Comment by Kuroonehalf** [comment]
Interesting, to mimic an ebook-like interface. Maybe that could be the new nomenclature? "Reading/Navigation mode: standard | ebook". It's still not super intuitive, but at least "ebook" may suggest the option of touching the edges of the screen for those who've used them, which is better than the current naming.

**Comment by raspberry-soft** [comment]
I agree that It was the most difficult one to figure out. I don't think is useful on Desktop but can be useful on mobile. Al least it should have a clearer name like "Rollback Touch Side" for mobile, "Rollback screen side", or "e-book Mode" with options: "left Rollback", "right Rollback" and "disable". That way players and developers will instantly know what It is.

**Comment by Kuroonehalf** [comment]
I actually think it's better to ditch the "rollback" term entirely for this outward facing UI, as it has widely come to mean something else in the videogame landscape (a type of netplay algorithm for online fighting games), and will more than likely lead to confusion for players to see it in a visual novel.

**Comment by raspberry-soft** [comment]
Some modern japanese visual novels have adopted the term "Backscene" to refer to "Rollback". However Ren'Py uses rollback and rollforward terminology internally so changing it may be confusing. That should be up to developers to how to name it in their games but the default GUI should be more clear to let the new users understand it better.

**Comment by Kuroonehalf** [comment]
What if selecting "Reading mode: ebook" has a confirmation prompt that explains what it does? This would work on all devices, and aid in the issue of informing the player of what it does. 

"In ebook mode, hitting the left side of the screen returns you to the previous line, and hitting the right side goes to the next line. Want to enable it? YES/ NO" Something like that. 

It's a little odd to add a confirmation prompt to a radial menu, but it's the most elegant solution I've thought of so far.

**Comment by KiloOscarSix** [comment]
If you find the default options not ideal, then go into the `preferences` screen and modify the text yourself?
The default creation doesn't need editing as anyone who has used the rollback side understands what it means. 

The benefit of renpy is almost every feature is customisable, it's up to individual developers to transform the engine into whatever game and goals they desire.

**Comment by Gouvernathor** [comment]
> anyone who has used the rollback side understands what it means

Sure, but how many didn't understand it, and couldn't use it ?
While not taking a position on the ebook formulation nor the confirm prompt solution, I agree with Kuroonehalf that the default interface is unclear and should be changed (even though it's not the upmost priority).
Yes, the engine is customizable, but there's a reason why roughly 1500 lines of code are shipped-in as the default screens.rpy. The default features and GUI should be clear and optimized, and I think in that instance it's clearly not the case. Not to mention the translations which make even less sense than the english version, by lack of room to explain the feature.

**Comment by geomat0101** [comment]
Summarizing in an attempt to drive implementation decisions

## Goal 
Reduce confusion around intent and behavior of the user pref 'Rollback Side' ( => ```[mobile|desktop]_rollback_side``` )

## Enhancement Proposals
1. **Rename Preference** (@Kuroonehalf, @raspberry-soft)
    - > Reading/Navigation mode: standard | ebook | ebook (flipped)
    - > clearer name like "Rollback Touch Side" for mobile, "Rollback screen side", or "e-book Mode" with options: "left Rollback", "right Rollback" and "disable"
    - abandon "rollback" in favor of "backscene"?
    - Everyone agrees this screen is all window dressing designed to be customized, yet what ships as default should not be arbitrarily unclear, difficult or confusing
2. **Confirmation Prompt** (@Kuroonehalf)
    - In general, even if it isn't a full confirmation dialog, would it be useful to have an option to provide a hover/unhover tooltip for preferences to obtain additional info?
3. **Documentation** [undiscussed]
    - Add a section to [Saving, Loading, and Rollback](https://www.renpy.org/doc/html/save_load_rollback.html) describing the various navigation styles and available options to control them

**Comment by renpytom** [comment]
Backscene is right out, rollback has a cleare meaning in the visual novel community distinct from its use in fighting games. 

Hover tooltips are a bad idea, as they don't work on mobile, which is what this is intended for. 

 Perhaps "Rollback Touch Side" (on mobile) and "Rollback Click Side" are good names. What do people think of that?

**Comment by JSearUK** [comment]
This issue has been raised in the past, and so I agree that clarification is needed.

Thoughts:
- Rollback makes more sense than Backscene - with a mousewheel, you literally rollback.
- Hover tooltips can be accessed by long-press on mobile. However, many people do not know this. *However*, if you are going to have a tooltip section/displayable, perhaps displaying text stating that "Hovertips can be accessed by long-pressing" solves that issue. Or simply add this to the Help page.
- Things relevant only to mobile need not even show up on non-mobile devices.

**Comment by mal** [comment]
If this is purely a UI impacting decision aiming to make this feature more understandable at a glance to players, then given the intent and behaviour of the feature, perhaps it makes sense to simply trade on the fairly well-established familiarity of consumers with ebooks and similarly controlled mobile apps, and label it along the lines of:
```
Ebook controls/mode/navigation/paging:
- Left-to-right
- Right-to-left
- Disabled
```

That it's triggering rollback or dismiss (advance) under-the-hood seems like it doesn't really to the player in this context, it's simply which direction do you want to be able to turn your virtual pages.

**Comment by Kuroonehalf** [comment]
> Backscene is right out, rollback has a cleare meaning in the visual novel community distinct from its use in fighting games.
> 
> Hover tooltips are a bad idea, as they don't work on mobile, which is what this is intended for.
> 
> Perhaps "Rollback Touch Side" (on mobile) and "Rollback Click Side" are good names. What do people think of that?

I continue to disagree that the layperson would have any clue what rollback means, and that even if they do, "Rollback touch side: left" still feels unclear that it's saying "touch the left part of the screen to rewind text". 
I also don't relate that it has a clear meaning in the visual novel community as a whole. To my knowledge no other visual novel engine has this term.

I think @mal's phrasing of the options would be ideal.

**Comment by renpytom** [comment]
More and more, I wonder if anyone actually uses this feature, compared to the button in the quick menu. I think I'll removbe it from the default preferences. 

I do think that Rollback has a clear definition in the VN community, especially since Ren'Py is clearly the majority engine at this point.

**Comment by Kuroonehalf** [comment]
Majority in raw numbers. But go on vndb and take the top 20 most popular visual novels and only 1 is made in Ren'py. 2 in the top 50. Aside from DDLC and Katawa Shoujo there's not many huge hits yet. Not Ren'py's fault, of course. But this is to say the average visual novel player will not have played many Ren'py games and be familiar with Ren'py specific terms.

But yeah, I'd be interested in knowing how many people use this. Maybe you could do a twitter poll.

**Comment by raspberry-soft** [comment]
My two cents: I played a lot of japanese visual novels when I discover the gnre. Then I discovered Ren'Py. But it was after I dug myself on the documentation (which I didn't even knew existed after months lol) I understood what that preference actually did.
