### ISSUE TITLE
dump_styles not implemented as documented

### ISSUE THREAD

**Issue by kdhunter** [renpy/renpy#3226]
https://www.renpy.org/doc/html/developer_tools.html#shift-y-style-dumping describes the "dump styles" feature as being triggered by Shift-Y when `config.developer` is `True`.

However, https://www.renpy.org/doc/html/keymap.html shows the default keymap as not having any key mapped to the `dump_styles` options.  In addition, if, in my game, I modify the keymap executing `config.keymap['dump_styles'].append('Y')` as described in https://www.renpy.org/doc/html/keymap.html#customizing-the-keymap, nothing seems to happen when I press Shift+Y.  

If the "dump styles" feature has been removed from Ren'py, then the documentation should be updated to remove it.  Otherwise, it should be configured into the keymap as described and functional.  

(Personally, I would REALLY like the feature to be there.)

**Comment by Gouvernathor** [comment]
The feature was removed in 2014 by dcd829931c4d5f1fe833fa0bddc8d5156eb116f3.

**Comment by kdhunter** [comment]
Then maybe, after 7+ years, it's time for the documentation to catch up with that fact?

It's actually a feature I would very much have liked to be able to use.  The current style inspector will tell you WHAT style is being used, but the "old feature" (was supposed to) include all the properties, which would sometimes be VERY useful.

**Comment by renpytom** [comment]
The current style inspector lets you see the properties - if you click on the style name, it will display the properties and where those properties come from. 

The  documentation is wrong. I'll remove the section from developer-tools.rst.

**Comment by kdhunter** [comment]
As so - thank you for that tidbit about clicking on the style name.  Didn't know that!
