### ISSUE TITLE
jump doesn't support 1a ,1b , etc

### ISSUE THREAD

**Issue by sum2012** [renpy/renpy#3230]
Example:

label start:
    menu:

        "As soon as she catches my eye, I decide..."

        "To ask her right away.":

            jump 1a

        "To ask her later.":

            jump 1b

label 1a:
    "1"
    jump 1c
label 1b:
    "2"
    jump 1c
label 1c:
    "3"

[code]
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

File "game/script.rpy", line 18: expected 'label_name' not found.
    jump 1a
        ^

File "game/script.rpy", line 22: expected 'label_name' not found.
    jump 1b
        ^

File "game/script.rpy", line 24: expected 'label_name_declare' not found.
    label 1a:
         ^

File "game/script.rpy", line 27: expected 'label_name_declare' not found.
    label 1b:
         ^

File "game/script.rpy", line 30: expected 'label_name_declare' not found.
    label 1c:
         ^

Ren'Py Version: Ren'Py 7.4.11.2266
Sun Jan  9 18:32:32 2022
[/code]

**Comment by KiloOscarSix** [comment]
names should start with a letter, same rules as python variable naming

**Comment by KiloOscarSix** [comment]
A variable name must start with a letter or the underscore character.
A variable name cannot start with a number.
A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ ).
Variable names are case-sensitive (name, Name and NAME are three different variables).
The reserved words(keywords) cannot be used naming the variable.

**Comment by sum2012** [comment]
ok,thanks.
I  surprise onscript supprt this.but renpy doesn't
