### ISSUE TITLE
[QUESTION] Why does 7x not have (Built in) editra support?

### ISSUE THREAD

**Issue by MoriMoriMorii** [renpy/renpy#3232]
Why'd editra get left in 6x? I understand it was an experimental editor but did it not work in newer versions? I know I can set editra as my system editor and use it that way but it fails to launch sometimes and I have to manually launch it before opening files. Did ATOM just replace editra as the preferred editor?

Thanks for reading :D

**Comment by renpytom** [comment]
The last release of editra was from 2013, and the editra.org domain name is down. 

The final reason for removing it was that when Ren'Py 7.4 changed the Ren'Py build process, the build of Editra broke. Rather than try to keep it going, I decided to remove it and the associated maintenance costs.
