### ISSUE TITLE
matrxtransform with RotateMatrix changes axis directions when I only use it for camera

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#3234]
x, y, z direction isn't rotated when I use matrixtransform with RotateMatrix for layer or image.
```
show layer master:
    matrixtransform RotateMatrix(0,0,45)
    xpos 600
```
![image](https://user-images.githubusercontent.com/1556311/149598973-31b65f82-3797-4d9e-9751-c7b22674cdb1.png)

But I use it for camera then x, y, z direction is also rotated.
```
camera:
    matrixtransform RotateMatrix(0,0,45)
    xpos 600
```
![image](https://user-images.githubusercontent.com/1556311/149598935-1d0fca53-bcca-4394-8ed3-7b6b69149a12.png)

Is this Intended behavior? I think it is not intuitive behavior as the behavior when moving the camera

Best Regard,

**Comment by renpytom** [comment]
That's documented and intended - the idea is that you're rotating the camera.

**Comment by kyouryuukunn** [comment]
OK Thank you
