### ISSUE TITLE
[Request] Dropdown button

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3235]
I was thinking that this could be interesting to include, a native Dropdown button. This can be done with several screens, but it is complicated in some cases. That's why I thought it would be a good idea to include a native Dropdown button.

This kind of buttons could be good to choose language etc.

The idea for this could be that depending on the amount of content, it could have a scroll or not.

**Comment by Neyunse** [comment]
Simple idea
```
dropdown:
     dropbutton "Hello" action NullAction()
```

Scroll dropdown:

```
dropdown:
     scroll 'vertical'
     dropbutton "Hello" action NullAction()
     dropbutton "Hello" action NullAction()
     dropbutton "Hello" action NullAction()
     dropbutton "Hello" action NullAction()
```



![mio-components_assets_1XhAXwplz2MXMIxPsBHDEz_GL1SaKbUAa_specs-menu-dropdown-2](https://user-images.githubusercontent.com/36079551/149954863-13497931-dd21-4aa6-bdd0-d05138f5bda7.png)

**Comment by Gouvernathor** [comment]
I saw a snippet of that some time ago, I can't find it now.
First, the inner buttons don't seem like they need to be `dropbutton`s instead of just `button`s.
Also, this seems like a typical use-case for the `use`/`transclude` screen statements. Like, a screen named "dropdown", taking a list of buttons, or taking a list of strings and a list of actions and making a list of textbuttons out of it ? So something that would be used and shared among creators, but I don't really see a need to include it in renpy.

**Comment by renpytom** [comment]
While this isn't a very high priority, my feeling is that we do need some sort of of engine support for this. Maybe not the entire dropdown, though figuring out focus issues might require a new displayable, but I do think that to do this properly we'll need something that can interrupt the flow of layuot, and then go on top of things that are laid out after it. 

So I'll tentatively accept this, to at least give better tools for creating displayables like this.

**Comment by Neyunse** [comment]
> I saw a snippet of that some time ago, I can't find it now. First, the inner buttons don't seem like they need to be `dropbutton`s instead of just `button`s or `textbutton`s. Also, this seems like a typical use-case for the `use`/`transclude` screen statements. Like, a screen named "dropdown", taking a list of buttons, or taking a list of strings and a list of actions and making a list of textbuttons out of it ? So something that would be used and shared among creators, but I don't really see a need to include it in renpy.

I put dropbutton as an example, as you said, a textbutton could be used, the issue with creating a Dropdown with screens is using two screens, I have tried a Dropdown code but if I had to change the position of the button I had to change the position of the other screen. 

This may not be ideal to include, but in some cases it can be good to include, for example if you have different window sizes, languages, fonts and that way you avoid having to adjust the layout of the settings window every time you want to add something new.

imagine generating a long list with different font designs, window sizes, or a long list of languages (there may be the case that the game receives several languages) In such a case it may happen that the entire container must be readjusted so that said content is look good.

But depending on who is looking at it, it can be good or bad to implement it, but it would facilitate some adjustments that could take up less space.

**Comment by Neyunse** [comment]
> 

Thank you Tom :D

**Comment by maLikiz** [comment]
@Neyunse I accidentally saw this problem, and I wanted to try to create something similar in ren'py, and this is what I got:
```rpy
init python:
    class Dropdown:
        def __init__(self, dropdown_list):
            self.dropdown_list = dropdown_list
            self.expanded = False
            self.selected_item = next((item for item in dropdown_list if item.selected == True), dropdown_list[0])

    class DropdownItem:
        def __init__(self, value, name, action = None, selected = False):
            self.value = value
            self.name = name
            self.action = action
            self.selected = selected


screen dropdown(dropdown_var):
    $ dropdown = getattr(store, dropdown_var)
    $ dropdown_list = dropdown.dropdown_list
    $ selected_item = dropdown.selected_item

    frame:
        xfill True
        xmaximum 200

        vbox:
            frame:
                xfill True

                hbox:
                    textbutton selected_item.name:
                        action SetVariable(dropdown_var + '.expanded', not dropdown.expanded)
                        xfill True

                    frame:
                        background None
                        padding (0, 0)
                        xpos -15
                        yalign 0.5

                        add Transform(
                            # change to your arrow:
                            im.Scale('image_1.jpg', 10, 10),
                            rotate = 180 if dropdown.expanded else 0,
                            yalign = 0.5,
                        )

            if dropdown.expanded:
                frame:
                    xfill True

                    vbox:
                        for item in dropdown_list:
                            $ actions = [
                                SetVariable(dropdown_var + '.selected_item', item),
                                SetVariable(dropdown_var + '.expanded', False)
                            ]

                            if item.action:
                                $ actions.append(item.action)

                            textbutton item.name:
                                action actions

label start:
    $ dropdown_1 = Dropdown([
        # Attributes: value (item id), name (textbutton), action(Jump and etc.) selected (is selected item by default)
        DropdownItem('item_1', 'Item 1'),
        DropdownItem('item_2', 'Item 2', Jump('test')),
        DropdownItem('item_3', 'Item 3', selected = True),
        DropdownItem('item_4', 'Item 4'),
    ])

    # In attr use your variable name
    call screen dropdown('dropdown_1')

label test:
    "test"

    return
```

All you have to do is add the styles you need and add an arrow to your drop-down list
