### ISSUE TITLE
Feature Request: Allow usage of functions as a menu choice

### ISSUE THREAD

**Issue by altskop** [renpy/renpy#3236]
Hi!

Currently, menus only allow strings as menu choices (as seen in renpy/renpy/parser.py).
```python
menu:
    "choice 1":
        ...
    "choice 2":
        ...
```

However, in certain usecases it would be useful if the choice label could be inferred from a function. it would grant a certain amount of flexibility to developers not having to create multiple choices if all that's changing is the label.
```python
def get_choice_1_label(arg):
    ...
    return arg+"[icon]"

menu:
    Function(get_choice_1_label, arg="choice1"):
        ...
    "choice 2":
        ...
```
Could this be implemented?

**Comment by Andykl** [comment]
If you really need only captions evaluation it can be easly achieved by
```
$captions = [get_choice_1_label(...), get_choice_2_label(...)]
menu:
    "[captions[0]!ti]":
        ...
    "[captions[1]!ti]":
        ...
```

**Comment by altskop** [comment]
That actually works great as a workaround, thank you!
I think knowing that, it might not actually be necessary for my idea to be implemented then.
