### ISSUE TITLE
Android 4.4 and some game emualtors cannot start the game or install it correctly

### ISSUE THREAD

**Issue by dewxin** [renpy/renpy#3240]

**Comment by dewxin** [comment]
If you dont mind, may I ask where I can find docs about these limitations

**Comment by renpytom** [comment]
If you look at https://www.renpy.org/ , it's right there under each of the platform logos.

**Comment by dewxin** [comment]
hahah , thanks

**Comment by dewxin** [comment]
I thought it may showed up in the documents.

**Comment by dewxin** [comment]
tutorial ,I mean .
