### ISSUE TITLE
RenPy 8 Nightly Builds on MacOS Crash - librenpython.dylib missing

### ISSUE THREAD

**Issue by Benlabscdk12** [renpy/renpy#3247]
Whenever I try running any of the RenPy 8 DMG and Zip Nightly builds on MacOS crash saying: 

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/librenpython.dylib
Referenced from: /Users/USER/Downloads/*/renpy.app/Contents/MacOS/renpy
Reason: tried: '/Users/beblackwell/Downloads/renpy-8-nightly-2022-01-06-5adb96543-sdk/renpy.app/Contents/MacOS/librenpython.dylib' (no such file), '/usr/lib/librenpython.dylib' (no such file)
(terminated at launch; ignore backtrace)

I never get to see any actual screens in the App.

**Comment by renpytom** [comment]
Does this happen with the Ren'Py 7.5 nightly?

**Comment by Benlabscdk12** [comment]
I am not sure. I will test it right now.

**Comment by Benlabscdk12** [comment]
It does indeed give the same error messag
<img width="994" alt="Screen Shot 2022-01-22 at 16 31 05" src="https://user-images.githubusercontent.com/15080825/150656097-a38c01c0-e7cf-4a7c-88bb-e555e9360a69.png">
e

**Comment by Benlabscdk12** [comment]
Is there anything I can do myself to fix this issue or am I doing anything wrong?

**Comment by renpytom** [comment]
It's almost certainly my fault. Let's keep this open and I'll try to fix this within the next few nightly builds.

**Comment by Benlabscdk12** [comment]
Thank you so much. I greatly appreciate it!

**Comment by Benlabscdk12** [comment]
I think I figured it out!
I am still experimenting to be sure. What I did was take the "renpy.app" file and extract the contents and then manually add all the files from the "lib/py3-mac-x86_64" directory to the MacOS directory in the App's Contents folder and then put everything back into an app (put into a folder, and add the .app extension) and when I clicked on it, the app launched. I am going to see if I can use a python 3 library (Flask, as I have been wanting to use that with RenPy forever) to work and I will post the results.

**Comment by Benlabscdk12** [comment]
Ok, I am having some issues. Whenever I try to launch any of my projects, none of them launch. I am not sure why that is... :(

**Comment by renpytom** [comment]
It's probably that the files aren't being signed correctly. (Or most likely, aren't being created correctly, and hence aren't being signed - something like that.)

**Comment by Benlabscdk12** [comment]
How do I sign it? Or is that something you will have to do on your end?

**Comment by renpytom** [comment]
I'll have to do it, or fix the automation to do it.

**Comment by Benlabscdk12** [comment]
Ok. Well hopefully that can be fixed soon. I appreciate all of your hard work. I really like RenPy. I am not the best at programming and RenPy has been so helpful for me to use to make quick graphical applications with Python. When I proposed to my fiancé, she and I both had never gone to prom, so I made a prom for just the two of us and I used RenPy to automate the evening (playing music, switching between special images, playing pre-recorded DJ clips, and working with asyncio and some other libraries to control the lighting). So RenPy holds a special place in my heart. Sorry if this is oversharing, but I just wanted to let you know that all your hard work impacts so many people and we thank you so much for it.

**Comment by renpytom** [comment]
That's incredible to hear. Honestly. Some of my best experiences are hearing about how Ren'Py has changed people's lives. Helping them become a creator, introducing themselves to program. You're not the first person to propose using Ren'Py. (At least, I think you're different from the first one.) It's really awesome to be part of this.

You can expect a fix in the next couple of days.

**Comment by Benlabscdk12** [comment]
Thank you so much! I look forward to it! I have notifications on so when it gets fixed in the nightly builds, I will know about it :)

**Comment by renpytom** [comment]
I've made a fix in how Ren'Py is built, and then I ran a second 'nightly' build. So from the newer/top January 23rd build on https://nightly.renpy.org/, this should be fixed.

**Comment by Benlabscdk12** [comment]
I tried running it and the GUI opens naturally now, but none of the programs will start when I click Launch Project (and this is not just my projects, even "Tutorial" and "The Question" do not start when I try to launch them).

**Comment by Benlabscdk12** [comment]
Also, I tried making a new project and when I do, it shows this message after the Background color selection screen:
<img width="792" alt="Screen Shot 2022-01-23 at 12 11 21" src="https://user-images.githubusercontent.com/15080825/150689749-062a6ddb-37e7-471d-bea6-b9e5144a2f32.png">

**Comment by renpytom** [comment]
I believe this is fixed in git, and should be fixed in the January 24 nightlies.

**Comment by Benlabscdk12** [comment]
It is working now! Thank you so much for all of your help! I will let you close this issue if would like :)
