### ISSUE TITLE
NVL mode paged rollforward

### ISSUE THREAD

**Issue by ZusYar** [renpy/renpy#3249]
Referring to this config option

    ## If true, NVL-mode rollback will occur a full page at a time
    config.nvl_paged_rollback = True

Assume, I have a block of 10 text lines between clearing nvl screen

1. I read several lines of text, let's say, 4 out of 10
2. I rollback, it shows the previous page.
3. To return to the place I've stopped reading, I roll forward and it shows the whole next page of text, including lines 5-10 which I haven't read yet. As well as every command until the next nvl clear gets executed, which is absolutely incorrect.

**Comment by geomat0101** [comment]
click to continue advances properly, but mouse wheel roll_forwards advance to the point prior to the next nvl clear

here's a repro using the nvl version of the_question

```python
# The game starts here.
label start:

    scene bg lecturehall

    window show

    "line 1"
    "line 2"

    nvl clear

    "line 3"
    "line 4"

    scene bg uni

    "line 5"
    "line 6"

    nvl clear
```

First rollback checkpoint is established after the first nvl clear.  Once the 'line 3' text pops up after the clear, a rollback and then rollforward flips the scene and displays all the text through 'line 6'
