### ISSUE TITLE
[Improvement] Improve the gl2 blur

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3252]
The new ATL blur has a big drop in quality compared to the one from im.Blur. I've seen a lot of creators move heaven and earth to make im.Blur work in their use cases, a lot of times dropping compatibility with higher-level tools taking transforms, just because of this.

If computing a better blurring is too expensive to be the default option, maybe having the property take a pair of values could be handy. Having an additional blur quality parameter instead of just the blur density could be an option, to let creators decide how much calculation they decide to put their game under, and in function of the size of the thing to blur.

**Comment by renpytom** [comment]
Unless there's a suggestion for how to make it work, I'm not sure this is a valid issue. If there is, we should probably implement the better algorithm.

**Comment by Andykl** [comment]
I tried this, but couldn't find a better single-pass shader.
