### ISSUE TITLE
[Question] Is it possible to buy back an item through Google play In-App Purchasing?

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3258]
I am creating a game where the player can buy an item that gives him more energy if it runs out, but the problem I ran into is that it doesn't let me buy that item again.

**Comment by renpytom** [comment]
That would be a consumable purchase, and that's not supported.

**Comment by Neyunse** [comment]
> 

And is there any other way to do it? I can't think of any other way, this kind of In-App Purchasing would be very useful to pay for my other projects.

I thought about including PayPal, but it gave me problems to integrate it (it was expected to happen), so I don't know what to do...

**Comment by renpytom** [comment]
Paypal is forbidden on google play, anyway. 

I'd be fine with a patch that  enables consumeables, but I don't have plans to work on that myself.

**Comment by Neyunse** [comment]
Ok, thank you tom for taking this doubt out of my mind. I think I will change the game structure, and see how to monetize the game.
