### ISSUE TITLE
side by side ndk not found

### ISSUE THREAD

**Issue by MichaelFenix** [renpy/renpy#3259]
using renpy 7.4.11.2266 and when building for android now I get WARNING Compatible side by side NDK version was not found for android ndk version 21.3.6528417. Previous builds have worked fine but all of a sudden on this build it comes up the build succeeds but will not install ANYWHERE! everything I have found for a soulution says go to tools SDK manager and so on but neither renpy or atom have this option. How do I fix this?

**Comment by renpytom** [comment]
Can you give a logcat from your phone during the installation process? The warning is unrelated to the actual problem.

**Comment by MichaelFenix** [comment]
where do I find that I have a galaxy note8 and nox player (Emulator) that I tried it on

**Comment by renpytom** [comment]
There should be a logcat command in the launcher. You want to keep it running while you do the install.

**Comment by MichaelFenix** [comment]
from the nox player:
[62025_logcat.txt](https://github.com/renpy/renpy/files/7962654/62025_logcat.txt)

**Comment by xOnlyFadi** [comment]
> using renpy 7.4.11.2266 and when building for android now I get WARNING Compatible side by side NDK version was not found for android ndk version 21.3.6528417. Previous builds have worked fine but all of a sudden on this build it comes up the build succeeds but will not install ANYWHERE! everything I have found for a soulution says go to tools SDK manager and so on but neither renpy or atom have this option. How do I fix this?

which version of renpy did you use for android that makes work without crashing?

**Comment by MichaelFenix** [comment]
same one. what I did was try to shrink the apk and split it into two games. I even went back and opened the project and packed the original again afterwords and it works fine.

**Comment by renpytom** [comment]
Is this game smaller than 2GB?

**Comment by MichaelFenix** [comment]
it is now. it originally got to about 3gb and quit compiling about 3 months ago. so I converted all .jpeg to .webp format at a quality reduction. and that is the current working one. But I want it at full quality so I cut the script in half at the chapter point. I'm currently on chap 2. so chapter 1 is cut down to where it was when I first made it and deleted all the chapter 2 stuff that has since been added. the chap 1 part is about 1.5GB and chap 2 is about 1GB. It makes zero sense to me why it won't work now just by doing that.

**Comment by luckykeeper** [comment]
我也遇到了这个问题，研究了几天终于解决了！
想要解决这个问题，关键在于日志的这里
> Compatible side by side NDK version was not found for android ndk version 21.3.6528417
说明它缺少了 android ndk version 21.3.6528417
这个问题会导致缺少 librenpython.so 导致无法运行
我们只需要补齐 Android NDK 就能解决这个问题
你可以下载一个 Android Studio ，然后用它下载 Android NDK ，再把它复制到 renpy-7.xx.x-sdk 的 rapt/Sdk/ndk/21.3.6528417下，再去编译就能解决这个问题
---------------------------------------------
Here is English Version
I also encountered this problem, and after a few days of research finally solved it!
To solve this problem, the key is here in the log
> Compatible side by side NDK version was not found for android ndk version 21.3.6528417
This means that it is missing android ndk version 21.3.6528417
This issue will cause librenpython.so to be missing, which will prevent it from running
We just need to copy the Android NDK to rapt folder to solve this problem
You can download Android Studio and use it to download the Android NDK, then copy it to renpy-7.xx.x-sdk under rapt/Sdk/ndk/21.3.6528417, and then compile it , you can solve this problem!
---------------------------------------------
下面附上两个文件夹的位置

**Comment by luckykeeper** [comment]
顺带问一下，有办法打包大于 2GB 的工程文件到安卓吗？我试过了但是会装不上
------------------------------------
By the way , is there a way to build project(to Android) larger than 2GB? I Have tried but found it can't install to my phone

**Comment by MichaelFenix** [comment]
> 我也遇到了这个问题，研究了几天终于解决了！ 想要解决这个问题，关键在于日志的这里
> 
> > Compatible side by side NDK version was not found for android ndk version 21.3.6528417
> 
> ## 说明它缺少了 android ndk version 21.3.6528417
> 这个问题会导致缺少 librenpython.so 导致无法运行
> 我们只需要补齐 Android NDK 就能解决这个问题
> 你可以下载一个 Android Studio ，然后用它下载 Android NDK ，再把它复制到 renpy-7.xx.x-sdk 的 rapt/Sdk/ndk/21.3.6528417下，再去编译就能解决这个问题
> Here is English Version I also encountered this problem, and after a few days of research finally solved it! To solve this problem, the key is here in the log
> 
> > Compatible side by side NDK version was not found for android ndk version 21.3.6528417
> 
> ## This means that it is missing android ndk version 21.3.6528417
> This issue will cause librenpython.so to be missing, which will prevent it from running
> We just need to copy the Android NDK to rapt folder to solve this problem
> You can download Android Studio and use it to download the Android NDK, then copy it to renpy-7.xx.x-sdk under rapt/Sdk/ndk/21.3.6528417, and then compile it , you can solve this problem!
> 下面附上两个文件夹的位置 Attached below are the locations of the two folders
> 
> here is ndk ![捕获](https://user-images.githubusercontent.com/34579433/157607584-775cf13c-4a2f-4e8a-8f84-6a0ee0bc0392.PNG)
> 
> and you should put ndk here ![捕获2](https://user-images.githubusercontent.com/34579433/157607773-80127459-00f4-4b5e-bfcc-b310a1dd4c40.PNG)

Ok downloaded and installed android studio and there is no option whatsoever for the NDK to download.
![Screenshot_2](https://user-images.githubusercontent.com/98531809/157674174-0639568e-faff-473f-a958-4f847e920b2d.jpg)

What am I missing?

**Comment by luckykeeper** [comment]
> Ok downloaded and installed android studio and there is no option whatsoever for the NDK to download.

才发现这还有一句，晚些时候我去截个图
2333

------

Just found your questions here , later I will give you a screenshot

**Comment by xOnlyFadi** [comment]
> > 我也遇到了这个问题，研究了几天终于解决了！ 想要解决这个问题，关键在于日志的这里
> > > Compatible side by side NDK version was not found for android ndk version 21.3.6528417
> > 
> > 
> > ## 说明它缺少了 android ndk version 21.3.6528417
> > 这个问题会导致缺少 librenpython.so 导致无法运行
> > 我们只需要补齐 Android NDK 就能解决这个问题
> > 你可以下载一个 Android Studio ，然后用它下载 Android NDK ，再把它复制到 renpy-7.xx.x-sdk 的 rapt/Sdk/ndk/21.3.6528417下，再去编译就能解决这个问题
> > Here is English Version I also encountered this problem, and after a few days of research finally solved it! To solve this problem, the key is here in the log
> > > Compatible side by side NDK version was not found for android ndk version 21.3.6528417
> > 
> > 
> > ## This means that it is missing android ndk version 21.3.6528417
> > This issue will cause librenpython.so to be missing, which will prevent it from running
> > We just need to copy the Android NDK to rapt folder to solve this problem
> > You can download Android Studio and use it to download the Android NDK, then copy it to renpy-7.xx.x-sdk under rapt/Sdk/ndk/21.3.6528417, and then compile it , you can solve this problem!
> > 下面附上两个文件夹的位置 Attached below are the locations of the two folders
> > here is ndk ![捕获](https://user-images.githubusercontent.com/34579433/157607584-775cf13c-4a2f-4e8a-8f84-6a0ee0bc0392.PNG)
> > and you should put ndk here ![捕获2](https://user-images.githubusercontent.com/34579433/157607773-80127459-00f4-4b5e-bfcc-b310a1dd4c40.PNG)
> 
> Ok downloaded and installed android studio and there is no option whatsoever for the NDK to download. ![Screenshot_2](https://user-images.githubusercontent.com/98531809/157674174-0639568e-faff-473f-a958-4f847e920b2d.jpg)
> 
> What am I missing?

u press on sdk tools and u would see ndk (side by side)
![image](https://user-images.githubusercontent.com/63213308/157802009-6e222abd-213e-445d-8c8e-4cf13b9a08d6.png)

**Comment by renpytom** [comment]
The side by side ndk thing is an unimportant warning. Please don't discuss it here. The maximum size of an Android APK is 2GB - beyond that, the phones do not support it.

**Comment by luckykeeper** [comment]
> The side by side ndk thing is an unimportant warning. Please don't discuss it here. The maximum size of an Android APK is 2GB - beyond that, the phones do not support it.

Got it,Thank you for the answer, But After I copy Android NDK to the rapt folder，I can install and run it smoothly ,but before that ,I can install but can't run it, when I open the app ,it shows presplash screen then just quit ,I think it's weird

This problem happen the this year, when I use the another computer last year with Ren'Py 7.4.6 ,it just fine. But when I changed to this computer this month with a new install Ren'Py 7.4.11 ,I find ndk warning and I can install it but can't run it,I solved the problem by copy the NDK as above.

the full warning is this 

> WARNING: Compatible side by side NDK version was not found for android.ndkVersion '21.3.6528147'
Compatible side by side NDK version was not found for android.ndkVersion '21.3.6528147'
Unable to strip the following libraries, packaging them as they are: librenpython.so.

I have no idea about this problem except the NDK, I can send you the apk with the problem above to you to further analyse If you need it.

**Comment by renpytom** [comment]
I don't think there's an actionable issue left here. The Side by Side NDK thing is a warning that can be ignores, and the rest seems to have been solved by shrinking the game.
