### ISSUE TITLE
[Question] Does renpy games have a unique identifier?

### ISSUE THREAD

**Issue by mensch272** [renpy/renpy#3263]
I would like to know if renpy games have an identifier that is unique to each game.

**Comment by Gouvernathor** [comment]
Yes, they have, but this is not the place for asking question such as these. See the [discord server](https://discord.gg/6ckxWYm) or on the [lemmasoft forums](lemmasoft.renai.us/).

**Comment by renpytom** [comment]
There's probably several things you could use as the identifier. Why do you want to know?

**Comment by mensch272** [comment]
> Why do you want to know?

I'm building a service that requires uniquely identifying games. I suppose you're not answering questions here though huh.

**Comment by renpytom** [comment]
I'll reopen this because I find it interesting. Can you describe the service a bit?

**Comment by mensch272** [comment]
> Can you describe the service a bit?

It is very early in development so I'd rather not go into specifics. We are currently collecting requirements. The service is concerned with games irrespective of the game engine.

Being able to identify a game by a unique id would be very helpful. If that is not possible we would have to fall back onto the name which might not be unique nor constant across installations.

Also, it seems I forgot to mention versions in the post, could you also describe how to identify the version of the game.

**Comment by Gouvernathor** [comment]
The answer to both, to me, would be the `config.save_directory` variable for the game identifier, and the `config.version` for the version.
Those variables (constants actually) are defined in the options.rpy file in a game by default, but the creator can move them around due to the freedom the engine allows, so no guarantees there.

**Comment by renpytom** [comment]
There isn't an easily accessible way to get anything about a Ren'Py game without running it - this information isn't really stored anyway except in the Ren'Py script files, which usually aren't distributed with a game. Your best bet is probably to hash the contents of the game directory (except game/cache and game/saves ).

**Comment by mensch272** [comment]
I've searched through a few games and indeed as you've said, options.rpy is the simplest way to do this. However, due to the freedom offered and the possibility of archiving it is not a reliable solution. Unfortunately, the same applies to hashing as well, since renpy games can be easily modded.

That being said, this is still useful. Thank you both for your replies.
