### ISSUE TITLE
Layeredimage with transform with default parameters does not pass the parameters, instead Image is received

### ISSUE THREAD

**Issue by RubenGarcia** [renpy/renpy#3264]
This is related to
https://github.com/renpy/renpy/issues/2990

I am using latest Release, version 7.4.11.2266, but the issue was found on 7.4.6.

This code (simplified):
```
python: 
    def x (trans, st, at, a, b=0, c=0, d=0):
      trans.rotate = c+d
      return 0

transform y (a, b, c=0, d=0):
  function renpy.curry(x)(a=a, b=b, c=c, d=d)
  repeat


layeredimage li:
  always:
    "a.png"
  always:
    "b.png"
    at y (1, 2, 3)

show li at y(1,2,3)
```

gives:
```
TypeError: unsupported operand type(s) for +: 'float' and 'Image'
```

Changing it to 
```
layeredimage li:
  always:
    "a.png"
  always:
    "b.png"
    at y (1, 2, 3, 0)
```
produces working code.
Can you confirm the issue?

**Comment by Gouvernathor** [comment]
There is indeed a discrepancy in how transforms are managed inside and outside of layeredimages.
To clarify, it should be noted that `show eileen at y(1, 2, 3)` does *not* produce the error triggered by `show li`.

Working on it.
