### ISSUE TITLE
Missing commands from renpy.exe (command line)

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#3270]
Hi,
Tried to build a distribution with the command line:
`"E:\renpy-sdk\renpy.exe" "E:\Projects\On-Going\Ren'Py\GAME_NAME" distribute --dest "E:\Projects\On-Going\Ren'Py\"

Which gave the following error:
```
Would you like to build the game? (Y/N): Y
usage: renpy.py [--savedir DIRECTORY] [--trace LEVEL] [--version] [--compile]
                [--keep-orphan-rpyc] [--errors-in-editor] [--safe-mode]
                [--json-dump FILE] [--json-dump-private] [--json-dump-common]
                [-h]
                basedir command
renpy.py: error: Command build is unknown.
```

Adding `sorted(commands.keys())` to the `ArgumentParser().error()` to return the commands expected produced:
```
[u'add_from', u'compile', u'dialogue', u'director', u'extract_strings', u'gui_images', u'lint', u'merge_strings', u'quit', u'rmpersistent', u'run', u'test', u'translate', u'update']
```

a different result than the help command:
```
The command to execute. Available commands are:
add_from, android_build, compile, dialogue, director,
distribute, extract_strings, generate_gui,
get_projects_directory, gui_images, ios_create,
ios_populate, lint, merge_strings, quit, rmpersistent,
run, set_projects_directory, test, translate, update.
Defaults to 'run'.
```

Doing a folder search for `register_command` it appears to be all the `launcher/game/**` commands aren't being registered for use but are being added to the help command.

Missing commands:
```
android_build
distribute
ios_create
ios_populate
set_projects_directory
get_projects_directory
generate_gui
```

Extra Infomation:
OS: Windows 10
Renpy version: 7.4.11.2266

**Comment by KiloOscarSix** [comment]
Supporting images:
![image](https://user-images.githubusercontent.com/26691547/152162545-0b6b95a5-dc71-455a-a4e8-21622d215a46.png)

![image](https://user-images.githubusercontent.com/26691547/152162686-81943161-fc0a-42e3-9159-bfd7639f349b.png)

![image](https://user-images.githubusercontent.com/26691547/152162782-be106940-fa86-464b-9e30-c5f50565ba51.png)

![image](https://user-images.githubusercontent.com/26691547/152162873-24c8dbeb-dd44-4809-9434-309660ca79af.png)

**Comment by morganwillcock** [comment]
How about if you try:
```bat
cd /d E:\renpy-sdk
renpy launcher distribute --dest "E:\Projects\On-Going\Ren'Py" "E:\Projects\On-Going\Ren'Py\GAME_NAME"
```

If you are scripting it from a batch file you might want to run it in a sub-shell (i.e. invoke a second cmd.exe) to avoid dealing with the return journey of the drive and directory changes.

**Comment by KiloOscarSix** [comment]
> ```batchfile
> renpy launcher distribute --dest "E:\Projects\On-Going\Ren'Py" "E:\Projects\On-Going\Ren'Py\GAME_NAME"
> ```

Yes. This works. I'll leave the issue open as I assume it isn't intentional behaviour, but I'll wait for confirmation on that. Thanks again :)

**Comment by renpytom** [comment]
This is intentional behavior - the launcher is what does distributions, not individual games.
