### ISSUE TITLE
[7.4.11] Bug launcher?

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3275]
Something strange has just happened to me, and that is that renpy failed out of the blue and closed. Also, it won't let me run it again, and I get the same message.
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  107
  Current serial number in output stream:  108
```

**Comment by renpytom** [comment]
Reboot your computer. I've had this happen, and it's always been caused by your OpenGL libraries and the X or Wayland server being out of sync.

**Comment by Neyunse** [comment]
> 

I thought that renpy had gone to a better life when I saw this error.... xd now if it happens to me I know what to do, thanks tom
