### ISSUE TITLE
Font scaling issue when "config.use_drawable_resolution = False" and "config.gl2 = True"

### ISSUE THREAD

**Issue by orobas0** [renpy/renpy#3276]
I had an old 800x600 renpy 7.4.3 project and after upgrading to 7.4.11, I noticed by chance that the fonts weren't looking as expected on full screen. Since the project is 800x600, it uses small images and has "config.use_drawable_resolution = False" to make fonts look pixellated if the window is bigger than 800x600, so everything looks cohesive.

I tested older releases and found out that this happens since 7.4.5, when the model based render was implemented. Turns out that setting "config.gl2 = False" makes renpy render the font as expected, but that obviously forces me to disable the model based renderer.

gl2 disabled (expected scaling):
![no_gl2](https://user-images.githubusercontent.com/86541456/152462353-8ca1a4f5-4274-41ee-a046-90bb93a15a86.png)

gl2 enabled:
![gl2](https://user-images.githubusercontent.com/86541456/152462330-f838f3d0-8b87-4332-a822-71865f0e11b2.png)

This behavior can be replicated in any project.

**Comment by renpytom** [comment]
Try:

```renpy
define config.drawable_resolution_text = False
```

Neither of these variables is currently supported, but that's the one that might be, as it applies to text.

**Comment by orobas0** [comment]
Thanks for the quick reply!

I can confirm that "config.drawable_resolution_text = False" makes the font scale as expected while maintaining the model based renderer enabled. Problem solved.

**Comment by renpytom** [comment]
This looks like it's fixed.
