### ISSUE TITLE
Document that renpy.reload_script() is not supported in mobile

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3283]
I created a clear progress button using the `persistent._clear()` function but it crashed the game after using it so I added `renpy.reload_script()` after it and it was fine. But when I used it in mobile it crashed. I think there should be a warning to devs.

**Comment by renpytom** [comment]
What are the errors you're getting? I'm not sure why renpy.reload_script doesn't work on mobile - I don't see anything in it that shouldn't work, though I haven't looked into it.

**Comment by raspberry-soft** [comment]
I pressed my clear progress button with prints to log and when it got to `renpy.reload_script()` it crashed.

The log file says: Reloading is not supported on mobile platforms.

Tested on Samsung model SM-J700F, vendor 'ARM', renderer 'Mali-T720', version 'OpenGL ES 3.1'
Renpy 7.4.11.2266

**Comment by raspberry-soft** [comment]
Found this:

![2022-02-08 19_29_23-__init__ py — C__Users_Roberto_Desktop_My Files_Software_renpy-7 4 11-sdk_renpy ](https://user-images.githubusercontent.com/87047775/153098922-594825d4-53e5-4cec-af8d-8f80e9d9be24.png)

**Comment by renpytom** [comment]
Huh. 

Try renpy.full_restart() instead.

**Comment by raspberry-soft** [comment]
I tried it but due to all the code I added it crash my game in certain cases due to some persistent variables being reseted. With `renpy.reload_script()` everything return to normal like a charm always. `renpy.full_restart()` does not reload the init phase and other stuff I guess.
