### ISSUE TITLE
JSON files cannot be read if archived

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3284]
Forgive if this is aclared somewhere but if you archive the .json files inside a .rpa file, you cannot access it from your script, for example using json.load etc. I use it as a database.

My solution for now is to archive everything BUT the json file, but it will be nice to archive it all.

I don't know if this is related but I also cannot access the .json file from an **android** build, no matter where I put it (game dir, game subdirectory), and if I use config.basedir or config.gamedir as part of the specified path it crashes saying the file is not found on 
` /data/data/com.company.mygame/files`. That works on desktop.

**Comment by renpytom** [comment]
You need to use renpy.file to access files. For example, renpy.file("database.json") accesses  /game/database.json .

**Comment by raspberry-soft** [comment]
Thanks! it works!
