### ISSUE TITLE
Menus may be shown incorrectly in alternate languages.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#3288]
https://lemmasoft.renai.us/forums/viewtopic.php?p=549856#p549856

**Comment by Gouvernathor** [comment]
Like the user said, this is because of the `nointeract` clause being added when generating translations, which was mistakenly removed. So, this is currently works-as-intended.
However, perhaps the menu translation could be made more intuitive ? By removing the need for the nointeract clause maybe ?

**Comment by renpytom** [comment]
I think that would requires more complexity in the translation system than I want to add at the moment. For now, the user reports this as fixed, so I'm closing this one.
