### ISSUE TITLE
[R8 BUG] - Unknown configuration variables when linting from CLI

### ISSUE THREAD

**Issue by multimokia** [renpy/renpy#3289]
We run a CI build system to handle automated regression testing and just general syntax linting for our project. After migrating the CI workflow to use the latest renpy 8 nightly, I'm noticing that config variables which worked normally before now show up as "not a known configuration variable." when running `lint`.

These are the erroring variables we have set, note they're set without an init level specified.
![image](https://user-images.githubusercontent.com/22531674/153899129-73daafc4-bbbf-482e-8c31-00d9076c1058.png)

Here are a couple instances from the CI output
![image](https://user-images.githubusercontent.com/22531674/153899738-a3d69a48-96dc-4acb-8023-6115d50682ac.png)
![image](https://user-images.githubusercontent.com/22531674/153899809-c1e3147e-cf3d-496c-b289-877f16bf6b6b.png)

Would really appreciate if this could be fixed, thanks!

**Comment by renpytom** [comment]
I just tried to repeat this, and I'm unable to do it. The script I used was:

```
define _confirm_quit = False

define e = Character("Eileen", image="eileen")
define l = Character("Lucy", image="lucy")
define a = Character("Augustina", image="augustina")

define config.report_extraneous_attributes = False
define config.keyword_after_python = True
define config.menu_showed_window = True
define config.window_auto_show = [ 'say' ]
define config.window_auto_hide = [ "scene", "call screen" ]
define config.replay_movie_sprites = False
define config.atl_one_frame = False


label main_menu:
    return


label start:

    scene bg washington

    "..."

    return

```

Does the error show up outside of your CI system?

**Comment by multimokia** [comment]
My bad, found the issue after trying that. Forgot we were caching the SDK so we were still on a significantly older build, hence why they didn't work. 

Sorry 'bout that!
