### ISSUE TITLE
[BUG] Transform doesn't update

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3292]
When using a transform with default parameters changing the transform's parameters outside of its function and using `update` doesn't update the transform. However, that works if the transform doesn't have default parameters.

```renpy
label test_transforms:
    python:
        transform_with_args = Transform("a", rotate=0.0, pos=(0.25, 0.5))

        transform_pure = Transform("b")
        transform_pure.rotate = 0.0
        transform_pure.pos = (0.75, 0.5)

    "Showing both transforms:"

    show expression transform_with_args zorder 15
    show expression transform_pure zorder 15

    "Trying to change the one with default args:"

    python:
        transform_with_args.rotate# 0.0
        transform_with_args.rotate = 45.0
        transform_with_args.update()# Nothing happens, why?
        transform_with_args.rotate# 0.0, why?
        # Obviously we also can't change pos since we passed in xpos and ypos:
        transform_with_args.pos = (0.25, 0.0)
        transform_with_args.update()# Nothing

    "The image on the left did not rotate nor moved. A bug?"
    "Trying to change the one without args:"

    python:
        transform_pure.rotate# 0.0
        transform_pure.rotate = 45.0
        transform_pure.update()# Worked!
        transform_pure.rotate# 45.0 as expected
        # And this, of course, works
        transform_pure.pos = (0.75, 0.0)
        transform_pure.update()# Moved

    "The image on the right rotated and moved. Works as expected."
    return
```

**Comment by renpytom** [comment]
The default parameters are given to the transform every frame if present.

**Comment by Booplicate** [comment]
I'm not sure if this is correct.
If I changed the code above a bit:
```renpy
    python:
        def _transform_func(transform, st, at):
            if st > 5.0:
                return None

            roto_speed = -10
            transform.rotate = at % 360 * roto_speed
            return 0.0

        transform_with_args = Transform("a", function=_transform_func, rotate=45.0, pos=(0.25, 0.5))
```
And this transform works as expected, the function updates it, even when it has default parameters. I understand *why* it happens, perhaps you're applying the default parameters and then the function? But that doesn't work with `update` because it just redraws the transforms and resets the parameters. This is very counter-intuitive, though, and probably should be documented (unless I missed it somewhere?). But I'd argue that `update` should *update* the transform. For example, my use case was:
```py
# I have multiple images defined like this
self.sprite= Transform(raw_img, rotate_pad=True, transform_anchor=True, subpixel=True, rotate=0.0, anchor=(0.5, 0.5), pos=(0.5, 0.5))
```
And to avoid this issue I had to
```py
# I have multiple images defined like this
self.sprite = Transform(raw_img)
self.sprite.rotate_pad = True
self.sprite.transform_anchor = True
self.sprite.subpixel = True
self.sprite.rotate = 0.0
self.sprite.anchor = (0.5, 0.5)
self.sprite.pos = (0.5, 0.5)
```
This is *very* messy and can only get worse. You could say that I should just wrap that in a function:
```py
def build_transform(raw_img, **kwargs):
    transform = Transform(raw_img)

    for key, value in kwargs.items():
        setattr(transform, key, value)

    return transform
```
But even then it'd be some kind of a crutch. Not to mention it's very unclear *why* we had to do that.

**Comment by renpytom** [comment]
Basically, if you include a property as part of the Transform, it's fixed for the life of the  transform. That's just how transforms are defined to work. 

This isn't a bug.

**Comment by Booplicate** [comment]
If it's not a bug, it should be mentioned somewhere. The doc of `update` doesn't mention it can't update default parameters. The doc of `Transform` doesn't say default parameters can't be changed.
If it's not a bug and "it's fixed for the life of the transform," then why an ATL transform of a transform with a function can change them?

That's undocumented inconsistency.

**Comment by renpytom** [comment]
I've updated the documentation. 

"an ATL transform of a transform" isn't a state that makes sense - you're discussing two separate transforms.

**Comment by Booplicate** [comment]
A typo, `or`*

Thanks! At least it's now clear what I should expect from transforms.
