### ISSUE TITLE
Android builds are sluggish after engine update

### ISSUE THREAD

**Issue by AviTheTiger108** [renpy/renpy#3299]
I test my games on an Alcatel OneTouch Pixi Glory running Android 5.  It's not crazy powerful but it still manages to get a lot done.

When I was using 7.3.5, all my games built with Ren'Py used to run smoothly on my device without any problem.  Then, after updating to 7.4.5 (after the build resources for 7.3.5 were disabled) my builds became extremely laggy and sluggish.  The text would stutter and transitions in between menu and scenes would be extremely delayed.  However, after I tested the game in a much weaker device running Android 17, the game ran fine.

Even if I update to the new versions, I'm still having this problem.  How can this be rectified?

**Comment by renpytom** [comment]
You could try: 

config.gl2 = False 

to see if that helps. That being said, given that it's about a 6 year old device running an 8 year old OS. It's possible that your device is emulating OpenGL ES 3, which would explain the slowness.

**Comment by AviTheTiger108** [comment]
> You could try: 
> 
> 
> 
> config.gl2 = False 
> 
> 
> 
> to see if that helps. That being said, given that it's about a 6 year old device running an 8 year old OS. It's possible that your device is emulating OpenGL ES 3, which would explain the slowness. 

I'll see if that helps anything and I'll get back to you

I still find it really weird that it would just not work all of a sudden

**Comment by AviTheTiger108** [comment]
> You could try: 
> 
> 
> 
> config.gl2 = False 
> 
> 
> 
> to see if that helps. That being said, given that it's about a 6 year old device running an 8 year old OS. It's possible that your device is emulating OpenGL ES 3, which would explain the slowness. 
IT WORKS THANK YOU SO MUCH
