### ISSUE TITLE
Unable to start game on Steam Deck

### ISSUE THREAD

**Issue by RStar8** [renpy/renpy#3307]
We have 2 games in Steam. We were testing the games on Steam Deck and this issue appeared.
![unknown](https://user-images.githubusercontent.com/26844209/156067478-95188516-384e-446b-9a0a-590bc5e2243a.png)
![unknown2](https://user-images.githubusercontent.com/26844209/156067489-7af36b1f-f679-4085-b304-192cadeef973.png)
Since the issue is showing up when Ren'Py is starting we couldn't figure anything out.

Some more info - This issue only occurs when we launch the game for the first time. After that the game will launch and run fine.
Then this issue reappears if we launch any other game and then try to launch the Ren'Py game again.

We don't know if it has something to do with the Steam OS or Ren'Py. So, we just wanted to make sure this issue is in your radar. Also now that you have the Steam Deck I am sure you will be able to figure out what is happening or at least suggest us something if we are doing anything wrong.

We were using the latest Ren'Py stable for the build and it was the Linux build running in Steam Deck.
Steam Deck software was updated to the latest version available as well.

Sorry for the blurry photos. We were unable to figure out a way to export screenshot or logs out of the Steam Deck.

**Comment by renpytom** [comment]
Could you send me a steam code so I can load this onto my device, and see if the problem repeats here? My email is pytom@bishoujo.us. That'll help me get the logs and see what's going wrong.

**Comment by RStar8** [comment]
We will mail them as soon as we can. Thank you so much for your fast response.

**Comment by renpytom** [comment]
Great. Also, if you could screenshot the Steam Input settings from Steamworks, that might help, too.

**Comment by RStar8** [comment]
I have mailed the Steam keys to you.

Also here is the screenshot -
![unknown.png](https://user-images.githubusercontent.com/26844209/156080149-bfc5b68d-bceb-41cb-8571-783e1965ad90.png)

Sorry if it is not what you meant.

**Comment by renpytom** [comment]
Can you select "Generic Gamepad" for the first choice?

**Comment by RStar8** [comment]
Doing what you said fixed the issue. Thank you so much for helping us out. I am marking this issue as resolved.
