### ISSUE TITLE
Zoomed side images look pixelated during transitions

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#3309]
I'm working on the side image implementation for my VN and I'm getting a problem with _config.side_image_same_transform_ and _config.side_image_change_transform_ where it seems to resolve the resizing/zooming of the new sprite too late (or something), which causes the new sprite to look pixelated during the transition. Here's a video example. https://drive.google.com/file/d/1gpCT78WeREtLMqE8HJ6uC4IwHUS5bdNk/view?usp=sharing

Notice it looks pixelated during the transition every time before becoming sharper.

The transforms are based on the documentation ones, but with change_transform also set to a dissolve:
```
transform same_transform(old, new):
    old
    new with Dissolve(0.2, alpha=True)
define config.side_image_same_transform = same_transform
define config.side_image_change_transform = Dissolve(1.0)
```
Perhaps relevant, the side image zoom atl is applied like:
```
transform side_image:
    zoom 0.35
    ...
screen say:
    ...
    add SideImage() at side_image
```
Nothing fancy. 

This problem does not occur when transitioning between regular sprites. Only on side image. 

I may be totally off base, but could it be an image prediction/caching problem?

**Comment by Andykl** [comment]
I think the solution for that is `Dissolve(0.2, mipmap=True)`

**Comment by Kuroonehalf** [comment]
Oh, that's it! That makes sense. You still notice a tiny difference in pixels, but you have to be looking super closely to notice anything. It works otherwise perfect. 

Is there something that can be done to avoid others hitting the same problem? Maybe have this be part of the documentation example?

**Comment by Booplicate** [comment]
There's also a [config var](https://www.renpy.org/doc/html/config.html#var-config.mipmap_dissolves), btw.
