### ISSUE TITLE
Outlines display at different widths on different platforms

### ISSUE THREAD

**Issue by npckc** [renpy/renpy#3315]
On Mac and Windows, outlines display at different widths. Tested on Ren'py 7.4.10.

Mac (MacBook Air 7,1, Monterey)
![2022-03-04_11 06 22](https://user-images.githubusercontent.com/50103058/156711238-6ee23276-5cb9-4da3-9f12-f9c4695f7212.png)

Windows (Microsoft Surface 7, Windows 10)
![screenshot0001](https://user-images.githubusercontent.com/50103058/156711376-638ff599-607b-4870-85ba-944ca8bb4afa.png)

The code is the same for both (text_outlines [ (12, "#fff") ]), but the Mac version appears much thicker.

**Comment by renpytom** [comment]
Can you try replacing 12 with absolute(12) ?

**Comment by npckc** [comment]
I just testsed and unfortunately this does not change anything. 

For further reference, on a MacBook Air 2020 (non-Retina display I believe), the outlines looked the same as on the Surface 7 machine. The MacBook Air 7,1 with the issues is non-Retina.

**Comment by mal** [comment]
Worth noting that the two screenshots are vastly different resolutions (1253x782 vs 2634x1481), but when viewing them side-by-side it's possible to see that the outline width in both instances is `12px`.

![outlines](https://user-images.githubusercontent.com/591257/156755415-dda1f1b3-6950-4b95-938f-badc1ee4a617.png)

Is it possible that `gui.init` or some other scaling-related gui value is being set differently depending on platform in your game?

**Comment by npckc** [comment]
I don't think I have anything that is platform dependent for gui.init - it is set to "gui.init(1920, 1080)". The same difference in display also occurs with both 12 and absolute(12), while it feels like having the outline size stay the same regardless of resolution feels like it should only happen in absolute (at least if I am reading the text in https://www.renpy.org/doc/html/style_properties.html about absolute type correctly, and the text about outlines which states "By default, size, xoffset and yoffset are scaled with the text").

**Comment by Kuroonehalf** [comment]
This sounds related to https://github.com/renpy/renpy/issues/1092 

I'd love to have an option to have outlines scale on window resize. It has always bugged me how you set the perfect outline for one resolution but it looks different (often worse) on other resolutions. Give Ren'py's focus on letting people play how they want, I think this is a good option to have. Should probably be the default.

**Comment by Gouvernathor** [comment]
@npckc could you try and add an `outline-scaling` style property to `"linear"`, and apply it to your text ? See what it does to the problem.

**Comment by npckc** [comment]
@Gouvernathor Assuming you mean "outline_scaling", I can confirm this fixes the issue and makes the outlines scale properly! Thank you. 

I'd like to suggest that "linear" is set to default so that this is the default behaviour, because everything else in Ren'Py scales properly when the window is shown at different resolutions. As-is, the documentation leads me to think that as long as I don't use absolute, the outlines should scale with the resolution by default, but it doesn't seem to be the case.
