### ISSUE TITLE
Possible audio issue on MacBook Air 2020 (M1) running macOS Monterey 12.2.1

### ISSUE THREAD

**Issue by npckc** [renpy/renpy#3316]
Music did not play on a Ren'Py game made in 7.4.10 on a MacBook Air 2020 (M1) running macOS Monterey 12.2.1. This was a report from a user and while I was not able to replicate the issue on a MacBook Air 7,1 dual core Intel Core i5 running the same OS, I confirmed through the user's submitted video and a traceback.txt that occurred when the game crashed from trying to read the name of a music file that wasn't playing that the bug does exist on their machine.  

I'm posting the bug here in case it is a problem with the engine, but please close it if it does not seem relevant.

**Comment by renpytom** [comment]
Do you have the traceback?

**Comment by npckc** [comment]
[traceback.txt](https://github.com/renpy/renpy/files/8183697/traceback.txt)

Here is the traceback. The game appears to play fine except for music not playing, but it crashes in the music room because when the game tries to read the current track, the track cannot be read. The strange thing is I have a fallback for if no music is playing (if renpy.music.get_playing() is None, it should show a text that says no music is playing), but this does not occur for the player whose device crashes.

**Comment by renpytom** [comment]
How do you set currentTrack? Is it inside some sort of Exception handler?

**Comment by npckc** [comment]
I set currentTrack using the following:
```if renpy.music.get_playing() is not None:
        $ currentTrack = musicList[renpy.music.get_playing()]```

musicList is where I list the names of the songs and the composers. Just in case, I also have this set:
```None:['NO MUSIC PLAYING','']```

**Comment by renpytom** [comment]
Can I suggest replacing this with:

```
$ currentTrack = musicList.get(renpy.music.get_playing(), [ "NO MUSIC PLAYING, "" ])
```

If renpy.music.get_playing()  returns None, currentTrack will never be set, and you'll get a crash. This also codes defensively around a missing key.

**Comment by npckc** [comment]
I will do this for the future, but this won't solve the issue of the music not playing at all throughout the game on the user's machine, which I unfortunately don't know the cause of.

**Comment by renpytom** [comment]
Yeah, that's hard to tell. I'll update my mac next week sometime, and see if I can repeat it.

**Comment by renpytom** [comment]
I've updated my M1 mac, and music plays fine on the tutorial game, on macOS 12.2.1 and Ren'Py 7.4.11. 

If you'd like me to test against a particular game, let me know. Otherwise, I'm not sure what else I can do here.

**Comment by npckc** [comment]
It sounds like it's probably an isolated incident specific to this user's enviroment then. Since it can't be reproduced, I'll close this.
