### ISSUE TITLE
Some translate mistake in Simplified Chinese Document

### ISSUE THREAD

**Issue by luckykeeper** [renpy/renpy#3318]
I didn't see feedback button in Doc site, So I open the issue here

1. https://www.renpy.cn/doc/config.html?highlight=channel#var-config.auto_channels
> define config.auto_channels = { “audio” : ( “sfx”, “”, “” ) }

should use "" instead of “”

2. https://www.renpy.cn/doc/config.html?highlight=channel#var-config.emphasize_audio_channels
> define config.emphasize_audio_channels = [ ‘voice’ ]

should use '' instead of ‘’

The problem above may get developer confused if directly copy it to the IDE without double check

3. https://www.renpy.cn/doc/audio.html?highlight=renpy%20music%20play#play
some English sentence is not translated
> Files placed into the audio namespace may automatically define variables that can be used like this.

I can give a translation：存放在音频命名空间的文件可以像这样自动创建变量

4. http://renpy.cn/doc/voice.html?highlight=play#ToggleVoiceMute
some English sentence is not translated
> This is selected if the given voice tag is muted, unless invert is true, in which case it’s selected if the voice is unmuted.

I can give a translation：当给定的 voice tag 被静音时将会被选中，除非 invert （反转）是 True 的时候，此时它将会在 voice 没有静音时被选中

at last, thanks to the Chinese translation team,they did awesome work and make Chinese Ren"Py developer learn easilier

**Comment by luckykeeper** [comment]
found another mistake
https://www.renpy.cn/doc/other.html?highlight=renpy%20is_seen#renpy.is_seen

> 如果 ever 为True，我们检查用户是否看过该行。如果 ever 为False，我们检查改行是否在当前游戏过程中被看过。

“改行” should change to “该行”

**Comment by renpytom** [comment]
This is probably a configuration problem in the Chinese documentation, rather than an issue with Ren'Py. I'm not 100% sure how to get in touch with them, and I can't really fix this.

**Comment by luckykeeper** [comment]
> This is probably a configuration problem in the Chinese documentation, rather than an issue with Ren'Py. I'm not 100% sure how to get in touch with them, and I can't really fix this.

Thanks for reply
Yes,It's definitely not an issue with Ren'Py,I thought you could get in touch with the maintainer of the Chinese documentation at that time I create the issue
I will try to see if there is another way to contact them
