### ISSUE TITLE
RangeError: Maximum call stack size exceeded on chrome 100

### ISSUE THREAD

**Issue by Rem-Py** [renpy/renpy#3333]
this is on chrome 100, not sure what is causing it.
it was working fine couple of days ago...
![image](https://cdn.discordapp.com/attachments/286633898581164032/952533307076263986/unknown.png)
![image](https://user-images.githubusercontent.com/66153474/158058942-99b84224-d85c-4cac-895e-66885852ac1e.png)

**Comment by Rem-Py** [comment]
![image](https://user-images.githubusercontent.com/66153474/158060642-bb90a5bf-e7a3-4356-96c8-0682b2b48f39.png)
chrome version details

**Comment by renpytom** [comment]
This looks like it's caused by a change in chrome, since Ren'Py hasn't changed. Have you tried reporting it there? There's not much I can do if they reduced their maximum call stack size.

**Comment by renpytom** [comment]
Actually, let me open the bug with google.

**Comment by renpytom** [comment]
This has been reported as:

https://bugs.chromium.org/p/chromium/issues/detail?id=130584

I'm also going to try updating emscripten soon, to see how that works.

**Comment by Rem-Py** [comment]
> This looks like it's caused by a change in chrome, since Ren'Py hasn't changed. Have you tried reporting it there? There's not much I can do if they reduced their maximum call stack size.

I did try to set the maximum call stack to infinity it didn't work...



> This has been reported as:
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=1305848
> 
> I'm also going to try updating emscripten soon, to see how that works.

will be waiting to get back to all the goodies out there, thx!

**Comment by Rem-Py** [comment]
I was looking at the bug reports and 
> if the dev console is open it doesn't crash

that's actually working, new beta was released so I will jump to that and check if anything changes
