### ISSUE TITLE
[internal] return-type change in the `round` builtin

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3335]
In py2 it returns a float (no matter what, it seems), while in py3 it returns an int as long as only one argument is provided.
This may induce bugs due to cascading type-changes, and does induce loss of processing time when round() calls are wrapped in int() calls (like in text/text.py).

It should be given a renpy.compat version, which in py2's case would mimic py3's version, and all uses of it in the code should be checked out (there are 23 (mostly repetitive), plus a shadowed version in glenviron_shader.pyx).

**Comment by mal** [comment]
Possible compat version based on few timings:
```py
from math import floor

def round(n):
    i = floor(n) # avoid looking up floor on math module, as it doubles call time
    return i if i == n else n
```

```py
# code A, convert = balanced
$ python2 -m timeit -s "from math import floor; n = 12.0" "a = floor(n); a if a == n else n"
10000000 loops, best of 3: 0.0648 usec per loop

# code A, no-op = balanced
$ python2 -m timeit -s "from math import floor; n = 12.5" "a = floor(n); a if a == n else n"
10000000 loops, best of 3: 0.0626 usec per loop

# code B, convert = disadvantaged
$ python2 -m timeit -s "from math import floor; n = 12.0" "floor(n) if n.is_integer() else n"
10000000 loops, best of 3: 0.0842 usec per loop

# code B, no-op = advantaged
$ python2 -m timeit -s "from math import floor; n = 12.5" "floor(n) if n.is_integer() else n"
10000000 loops, best of 3: 0.0563 usec per loop
```
