### ISSUE TITLE
[Request] Pass more object information to `focus_mask` callable.

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#3343]
Hi,
Would be ideal if additional information was passed to the callable that an object's `focus_mask` uses. Specifically the object's width and height.

My specific case:
I have a button that uses a `Frame()` background and the hover_background has a fading transparent effect however I don't want the button to remain focused when leaving the outline (into the hover effect) and would require the current height and width of the button to set the focus bounds.

**Comment by mal** [comment]
Could your case potentially be solved by passing the `idle` displayable to `focus_mask` directly instead of using a function? That way it would use the outline of the non-transparent pixels of the idle state for focus management, regardless of how the hover state may expand beyond that outline.

i.e. something like
```rpy
screen example():
    $ my_idle_frame = Frame(...)

    button:
        background my_idle_frame
        focus_mask my_idle_frame
        hover_background Frame(...)
```

**Comment by KiloOscarSix** [comment]
Unfortunately not, as the idle frame has a transparent centre so passing the idle image makes the thin outline the only interactive area

**Comment by KiloOscarSix** [comment]
![unknown](https://user-images.githubusercontent.com/26691547/159150254-f195a26c-78ee-4b50-b604-e4b33ad9bf1d.png)
![unknown](https://user-images.githubusercontent.com/26691547/159150263-3790b3f1-96ad-4899-add0-8c22977ab5a6.png)

For reference to the images

**Comment by Gouvernathor** [comment]
Changing this would break compatibility with the current version focus_mask callables work, with only two arguments.
Also, this seems like a bad idea to pass an almost-always constant information to a callable, as unless the button changes size (which in your case it seems it doesn't), this can be provided by other means, for example `focus_mask functools.partial(your_callable_here, size=constant_size_of_the_image)`. With this tweak, a three-argument callable can be used as the current two-argument focus_mask callable.
In your specific case, I'd recommand using a third image for the focus mask.

**Comment by renpytom** [comment]
I think this could be useful. Using a function for focus_mask is better than a displayable when render-to-texture can happen, so it makes sense to make it possible for those functions to be able to take the displayable size. 

The way I implement this is to allow a callable to take two arguments, and return a callable (such as itself) that's called with four. For example: 

```py
def edgy_button_mask(x, y, w=None, h=None):
     if w is None:
          return edgy_button_mask

     return (10 < x < w - 10) and (10 < y < h - 10)
```
