### ISSUE TITLE
"Couldn't find a place to stop rolling back..." If the OS does not have Python 2.7

### ISSUE THREAD

**Issue by maLikiz** [renpy/renpy#3345]
Error `Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way`
Renpy version: 7.4.11.2266

This error suddenly appeared after I reinstalled Windows 10 but **did not install Python 2.7** and after I started loading save that were created before reinstalling Windows 10.

My research:
This save file was saved on a dialog. I tried to load this save from an old build that was done with Python 2.7 installed and it worked. I tried to resave this save and run game from renpy launcher (my current game version), but loading this save file still caused the error. Then I tried again to load this save file from the old build and exit the dialog to the interactive screen and save the game. Then I tried to load the game from renpy launcher (my current game version), and loading this save stopped causing an error. But still it bothered me that when loading the save to the dialogs it caused an error.

I kept researching this. I decided to try installing Python 2.7, it didn't give any result. Then I installed Python 3.10, it didn't give any results either. Then I specified Python 2.7 in Windows environment variables, and fortunately this save worked.

Also at the time of the research, I used **unrpa** (https://github.com/Lattyware/unrpa) and **unrpyc** (https://github.com/CensoredUsername/unrpyc) to compare my code with the old build.

Guesses of the cause of this problem:
Perhaps not having Python 2.7 on the OS, files `.rpyc` are compiled in a different way, which is why the context on which dialog the file was saved is lost.

At the moment, of course, I have solved my problem. But still, some developers may get stuck on this and I want to inform you about a possible problem.

**Comment by renpytom** [comment]
I don't think this is an issue with Ren'Py, as it doesn't use the system install of Python. Those game modding tools can cause problems, so it's possible that was the cause.

**Comment by maLikiz** [comment]
I just did another research:
I found an `rpyc` file  (which was decompiled using `unrpyc`) that had a problem, I tried to copy it into my project and make a Force Recompile, the save file still worked. Then I deleted this file, and once again made a Force Recompile, the save file stopped working. It feels like the .rpyc file is not being generated again, but somehow changes the current one, which is why this problem causes.

**Comment by maLikiz** [comment]
I mean, I expected Force Recompile to actually force recompile this file regardless of how it was compiled earlier. That is, it will delete and create a new file.

**Comment by renpytom** [comment]
We don't support game modding like this, as it's an easy way to introduce issues like the one you did.

**Comment by maLikiz** [comment]
I don't do modding. I'm developing my game. I would never ask for such help. I myself do not understand how this happened to my project. Maybe I was stupid a long time ago and decompiled my own project and it turned out what happened. And it stretched from version to version of my game, until I just reinstalled the OS.

**Comment by Gouvernathor** [comment]
The error you're getting typically comes from situations where a rpyc has been deleted/regenerated (and when `from` clauses have not been added to `call` statements).
If you manage to reproduce the bug without interference from unrpyc and unrpa, it will likely come down to an issue of rpyc file(s) being regenerated or deleted between the game which saved and the game which loaded. And if so, that's a normal behavior.

In any case, the problem doesn't come from the lack of Python installed on your computer, so if you reproduce the problem in a situation where it shouldn't happen, please open a new issue.

**Comment by renpytom** [comment]
Ah, okay then. Those are modding tools, so they often cause problems. 

One problem they cause is that you basically need the .rpyc files to be updated each time the game is changed, since they contain information about the different lines in the game that's used to support loading. If you don't keep the .rpyc files around, that leads to errors like the one you have. 

There's a good discussion of this at: 

https://patreon.renpy.org/dev-2021-02.html#save-compatibility-through-repeated-releases

**Comment by maLikiz** [comment]
> (and when from clauses have not been added to call statements)

More like the truth

**Comment by maLikiz** [comment]
> Ah, okay then. Those are modding tools, so they often cause problems.
> 
> One problem they cause is that you basically need the .rpyc files to be updated each time the game is changed, since they contain information about the different lines in the game that's used to support loading. If you don't keep the .rpyc files around, that leads to errors like the one you have.
> 
> There's a good discussion of this at:
> 
> https://patreon.renpy.org/dev-2021-02.html#save-compatibility-through-repeated-releases

Thank you, I'll look into it. I'm glad you finally got me right :)

**Comment by maLikiz** [comment]
@renpytom 
I have read the contents that you sent me. I immediately had a questions:
I initially specified the `.rpyc` files in the `.gitignore` file. Should I commit`.rpyc` files to my git repository? Otherwise, how would pickle understand what I changed in my files after I reinstalled the OS and downloaded my repository without .rpyc files?

**Comment by renpytom** [comment]
You either need to do this, or place them into the old-game directory each time you release. 

https://www.renpy.org/doc/html/build.html#old-game

**Comment by maLikiz** [comment]
I tried to create the `old-game` directory and put there `.rpyc` files that I unpacked from `.rpa` using `unrpa` from my old build. It really works.
But: It would be great if I could put the `.rpa` files from my old build into the `old-game` directory, since I can't completely trust the `unrpa`. Or can this affect performance?
