### ISSUE TITLE
Automatically copy .rpyc/.rpymc files from game/ to old-game/

### ISSUE THREAD

**Issue by maLikiz** [renpy/renpy#3346]
I tried to create the `old-game` directory and put there `.rpyc` files that I unpacked from `.rpa` using `unrpa` from my old build. It really works.
But: It would be great if I could put the `.rpa` files from my old build into the `old-game` directory, since I can't completely trust the `unrpa`. Or can this affect performance?

_Originally posted by @maLikiz in https://github.com/renpy/renpy/issues/3345#issuecomment-1073748202_

**Comment by Andykl** [comment]
Implementing this would add unnesesary overhead and compexity to already complex Script class.
I think it is better to add an build option "Update old-game", so you do not need to unrpa your own game.

**Comment by renpytom** [comment]
I think @Andykl 's analysis makes sense, and that this could be implemented fairly easily with python tools that way - just copy the files over when the button is clicked.
