### ISSUE TITLE
Manual wrapping an ATLTransform in ATLTransform (or via `At`) is broken

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3349]
Manual wrapping an ATLTransform in ATLTransform (or via `At`) like:
```
label main_menu:
    return

define config.default_transform = None

image base = Solid("#0ff", xysize=(100, 100))

transform test_zoom:
    zoom 1.0
    linear 1.0 yzoom 0.5
    linear 1.0 yzoom 1.0
    repeat

transform test_alpha:
    alpha 1.0
    linear 1.0 alpha 0.25
    linear 1.0 alpha 1.0
    repeat

transform centr:
    align (0.5, 0.5)

image test = centr(test_zoom(test_alpha("base")))

label start:
    "{cps=0}Click to see the bug"
    show test
    "{cps=0}Auto-advance in 1 second{p=1.0}{nw}"
    hide test
    pause 0.0
    show test
    pause
    return
```
It starts with propertly animation on the first show. But after hide and show again the animation of the inner transform(s) freeze in state it was hidden.
This behaviour totally confusing and at odds with the only way that works:
```
image test:
    "base"
    parallel:
        test_zoom
    parallel:
        test_alpha
```

**Comment by renpytom** [comment]
I'm not able to repeat this. Can you try it in the latest nightlies and see if the problem still exists?

**Comment by Gouvernathor** [comment]
The behavior is different for both versions of the test image, the `centr(test_zoom(test_alpha("base")))` callable one and the atl one. (I added `centr` to the atl one just under "base")
When the test image is hidden, it's shrunk vertically. When the callable version is shown the second time, it is still shrunk, when it shouldn't be. It doesn't stay in that state indefinitely, but as it starts the test_zoom animation from the beginning, it interpolates between a zoom of .5 and a zoom of .5 during one second, where it appears to freeze.
