### ISSUE TITLE
Add an ability to load python code as init python module

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3352]
The idea is to add some function which behave like `renpy.load_string` (and probably just a wrapper around it) but skips RenPy's parse and just creates single PyCode with its content. The benefit of it is that such code may be developed with one less indent, which is big for classes (12 spaces in method bodies is annoying).
The only problem I see is to how cache it's content as compiled file.
Something like
```
def renpy.load_python_file(path_like_in_load_module, module_name="store"):
    content = open(path_like_in_load_module).read()
    code = f"""
init python in {module_name}:
    {content}
"""
    renpy.load_string(path_like_in_load_module, code)
```
This differs from the current `python-packages' in that it will apply the AST magic of RenPy.

**Comment by renpytom** [comment]
Hm... my current thinking on this is that we want a way of creating a .py file that's loaded with .rpy syntax . I have a pretty good idea of how I want it to work, using special strings to include Ren'Py code. 

```python

"ignore:"

import renpy.exports as renpy
from renpy.store import * 

"init python:"

class ThisIsTheAction(Action):
    ...
```

I want to tackle this myself, once 7.5/8.0 is out.

**Comment by renpytom** [comment]
This is done (the new _ren.py files.)
