### ISSUE TITLE
Warn about define with persistent in lint

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3354]
Related to #2166.
As said [here](https://www.renpy.org/doc/html/changelog6.html#define-improvements) in the changelog6 page, `define persistent.x = val` behaves exactly as `default persistent.x = val` would, which is especially different from the way the following code works :
```rpy
init python:
    persistent.x = value
```
The behavior of the define statement is usually equivalent (with minor differences mostly relative to substores) to the init python version.
Also, as the documentation for the define statement states :
**Variables that are defined using the define statement are treated as constant, are not saved or loaded, and should not be changed.**
Considering that the persistent store is meant to be changed by its very purpose, it is nonsensical to use define with the persistent store.
For these two reasons, it is most likely a mistake for the define statement to be used in cunjunction with the persistent store.

Of course, a compatibility config variable and/or a config.developer exception should be added in order not to break older games. However, such compat variable should not be documentedin the changelog, as creators should be encouraged to use `default` instead of `define` when it comes to persistent. Unless a difference is found in how default and define work with regard to the persistent store.

**Comment by renpytom** [comment]
The fix should be a lint warning, plus special casing in pyanalysis that persistent variables aren't constant.

**Comment by Andykl** [comment]
There is no need of pyanalysis thing because persistent namespace is already not constant.

The idea to forbid it is only based on the fact that other namespaces do not allow default or define, so it is about being consistent.
