### ISSUE TITLE
Japanese hanging punctuation

### ISSUE THREAD

**Issue by soos-peter-levente** [renpy/renpy#3356]
Is hanging punctuation supported in the Japanese text reflow/line breaking algorithms? If not, could it be?

### Description

In Japanese typesetting, hanging punctuation is used for lines ending with "。", "、", "」", "』" (and similar closing brackets) and I think the katakana chouon sign "ー", too. 

The _W3C Requirements for Japanese Text Layout_ explains it [here](https://www.w3.org/TR/jlreq/?lang=en#fig_ad1_7) (whew! in some detail, too) and the Wikipedia article on [_burasage-gumi_](https://ja.wikipedia.org/wiki/%E3%81%B6%E3%82%89%E4%B8%8B%E3%81%92%E7%B5%84%E3%81%BF) also has some self-explanatory images.

I'm guessing a single character slot beyond the end of the line is reserved in Japanese typesetting systems for this purpose? Can this be done in RenPy?

### Screenshot

The NVL mode layout can be made very aesthetic as it is, but the line-ending blanks are _frequent_ and glaring in Japanese long-form prose. 

In the screenshot below, the "**か、**" is thrown to the second line due to the comma line break rule. It should stay in the first line, with the "**、**"  _hanging_ outside the line end line. The same with the "**な、**" further down.

![hanging](https://user-images.githubusercontent.com/26578186/159978913-f01a040d-fd13-400e-af69-8ee1f9769bda.png)

**Comment by soos-peter-levente** [comment]
I don't think so, or at least, I'm not sure how to set it up, as you can see on the screenshot above. It was made with the "japanese-normal" property set, but the result is the same for the other modes. 

The line break happens alright, but the point is, it _shouldn't_ in this case - the commas/etc. should be rendered beyond the line end.

**Comment by renpytom** [comment]
Ah, gotcha. Yeah, this would have to be added. 

Can you post the example you use above - ideally the full version, including the fonts? I'd like to fix this, though this will probably wait until after 7.5/8.0 is out the door.

**Comment by soos-peter-levente** [comment]
Of course, here you go: [hanging_punctuation.zip](https://github.com/renpy/renpy/files/8344404/hanging_punctuation.zip)
