### ISSUE TITLE
Can't search japanese renpy-doc for keyword

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#336]
I tried to search the japanese renpy-doc in "http://ja.renpy.org/doc/html/" for a keyword with the search box.
But this searches english renpy-doc even if in japanese doc.

**Comment by renpytom** [comment]
I'll take a patch for this, but I'm not sure how to write a link to that page in Japanese.

**Comment by kyouryuukunn** [comment]
This was fixed. thank you.
