### ISSUE TITLE
Allow variable unpacking in `default` and `define` statements

### ISSUE THREAD

**Issue by jedestep** [renpy/renpy#3361]
Would be awesome to be able to do something like `default branch_a, branch_b, branch_c = create_dialogue_branches()`. Makes it easier to create objects that need to be saved as part of save files and also have mutual dependency on each other's state.

**Comment by renpytom** [comment]
I don't think this would likely get enough use to get the complexity. And I think you can already do this:

```
default template = create_dialogue_branches()
default branch_a = template[0]
default branch_b = template[1]
default branch_c = template[2]
```

So I don't see this as likely to be added to Ren'Py.

**Comment by jedestep** [comment]
Fair enough. Just thought I'd bring it up. Thanks for addressing.

**Comment by renpytom** [comment]
No problem, thank you for the suggestion. 

My main issue is that I think the default statement would be a bit confusing if branch_a and branch_b are defaulted, but branch_c doesn't have a value - then you'd have an invalid mutual dependency.

In any case, closing this.

**Comment by Andykl** [comment]
Another advice. For such probably complex cases there is https://renpy.org/doc/html/label.html?highlight=after_load#special-labels.
So, you can write something like
```
label after_load:
    python:
        if any(not hasattr(store, i) for i in ['branch_a', 'branch_b', 'branch_c']):
            branch_a, branch_b, branch_c = create_dialogue_branches()
```
