### ISSUE TITLE
[Question] Can you change Presplash directory path?

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#3367]
Hi,
It seems that presplash images only work when in the root `/game/` directory however would be ideal if I can direct the directory to `/game/gui/presplash/` or something

Thanks,
Oscar

**Comment by renpytom** [comment]
No, sorry. 

The problem with this is that the presplash is shown before anything else happens, and especially before any configuration is processed. So the files have to be in a fixed place for Ren'Py to find them.

**Comment by KiloOscarSix** [comment]
Not a worry, just a nice to have ;D
