### ISSUE TITLE
[Request] Possibility to add idle and hover images to regular buttons

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#3371]
Hello,
Would it be possible to add functionality to show idle_image and hover_image to regular button? I know there's already imagebutton for this, but button is more robust allowing for text, solid frames at the same time, but not alternating image. It supports "add", but that cannot alternate on it's own. So users can use button universally and then image and text buttons for faster and easier stuff when needed.

**Comment by renpytom** [comment]
I'm not sure what you want that button doesn't already have. There are a couple of style properties that probably should work for you, documented at: 

https://www.renpy.org/doc/html/style_properties.html#window-style-properties

background (which you can give as idle_background, hover_background) gives an image that goes behind the button, while foreground lets you put an image above it. You can't really give an image to a button, as it replaces the children... that's how imagebutton is implemented. 

What I'd suggest doing is:

```renpy
button:
    idle_background "button_idle.png"
    hover_background "hover_button.png"
    xysize (250, 50) # the size of the two image. 

    text "This goes inside the button." 

```

Something like that.
