### ISSUE TITLE
[Request] Re-enabling the font module in pygame_sdl2

### ISSUE THREAD

**Issue by the66F95** [renpy/renpy#3373]
![launcher](https://user-images.githubusercontent.com/54831834/160413492-c22325dc-fd6c-426c-a1fe-7587692d7fcb.png)
Due to missing of said module in v7.4.x  I'm no longer able to blit a proper percentage counter into the presplash images.

**Comment by renpytom** [comment]
Sorry, but I don't think this is a good idea. Ren'Py doesn't use the pygame_sdl2.font, and it depends on the SDL_ttf library. I don't think it's worth taking an additional dependency like this for something Ren'Py doesn't use.
