### ISSUE TITLE
Solve dialogue lines being cropped during typewriting

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3375]
The problem is that with tall glyphs or tall fonts, glyphs occasionally overflow on the previous line or get their tail cropped by the following line, while the last line or their own line (respectively) is being typewritten by the slow_cps feature.

Currently, the text area's whole texture is calculated once and blit(ted?) according to the scheme shown [here](https://github.com/renpy/renpy/blob/30962cab87a4fb6218618332ed8ea13a2a0c4a80/renpy/text/text.py#L79). What would actually be required is one single texture per line. The last texture would be cut (blitted) only horizontally during slow cps, with each piece of the texture taking the whole height of the textbox. All textures up to the one being typewritten would be displayed on the top of one another.
I don't really see a better way to do it.

An attempt to do this (or rather a method kind of similar) can be found [here](https://github.com/Gouvernathor/renpy/tree/typewriter-blits), use it as you will. It's a bit messy, a better version would require a more deep understanding than I have on all the things going on in text.py.

**Comment by renpytom** [comment]
I think the right way to fix this is probably to use a texture atlas for each character, and moving text rendering to the GPU. I don't think this is a big enough problem to be worth addressing before that.
