### ISSUE TITLE
It is interesting.

### ISSUE THREAD

**Issue by YukiiroRu** [renpy/renpy#3380]
If you use different double quotes in the code when it is necessary, then you do not need to escape them.
That's the (name of the character " „ His speech... “ ") The quotes are both lower and upper with a slope, so there is no need to escape, the code works fine.

**Comment by renpytom** [comment]
Sorry, is there an issue here (like something you'd like us to change about Ren'Py?)

**Comment by YukiiroRu** [comment]
No, I'm just saying there's no need to escape double quotes. You can use the lower case of quotation marks and the upper case with a slope, this does not cause errors.

**Comment by YukiiroRu** [comment]
I can give an example of the code for clarity from my mod for playing in this language.

**Comment by Andykl** [comment]
This is a U+201C symbol, i.e. not "that quote". There are many interesting characters like this among Unicode. The only problem with them is if your font does not support this character.

**Comment by YukiiroRu** [comment]
But they (i.e. quotes) can be copied.
