### ISSUE TITLE
Sound keeps playing when calling MainMenu()

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3383]
If a sound file is playing by using `play sound river_sound`, and then a button with the `action MainMenu()` is pressed, the sound keeps playing in the main menu screen.

A workaround I'm using is adding `renpy.sound.stop(fadeout=config.fade_music)` inside the MainMenu() class.

I don't know is this is as intended or I'm doing something wrong but gameplay audio should be stopped when exiting to the main menu.

Also audio related: FLAC files are not played (ren'py crashes) when called like this: `play sound flac_file_here`, with error: 'file is not defined'. This doesn't happen with the other formats.

**Comment by geomat0101** [comment]
confirmed via the tutorial: on action MainMenu(), the 'music' channel stops, but the 'sound' channel (others?) continue to play.

(is this by design?  should there be a preference?)

**Comment by renpytom** [comment]
Fixed, though if you want the fadeout you'll have to cancel this and do it yourself (probably in the before_main_menu label).
