### ISSUE TITLE
volume clause failed to set audio's volume on any channel now.

### ISSUE THREAD

**Issue by YuanlinLi** [renpy/renpy#3385]
you can hear sound even wrote ' volume 0.0'

**Comment by geomat0101** [comment]
can you help with a reproducible case / more details please?  seems to work ok in the tutorial project

**Comment by YuanlinLi** [comment]
> can you help with a reproducible case / more details please? seems to work ok in the tutorial project

find possible reason：
I wrote # define config.default_music_volume = 0.5
# define config.default_sfx_volume = 0.6
# define config.default_voice_volume = 1.0
in option.rpy,once removed them and the volume clause repaired,
however it 's necessary for me to use them to set default volume of channels,
is there anyway to fix this?

**Comment by renpytom** [comment]
I don't think this is a bug. The defaults only happen once, until you remove the persistent data. That means that it will happen the first time the player opens the game, but after that the player will be in control of the volume.
