### ISSUE TITLE
Unexpected screen prediction behaviour

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3398]
I'm showing a screen like this
```renpy
call screen MyScreen(*heavy_function(*func_args))
```

Apparently that calls `heavy_function` twice, I then remembered about screen prediction and disabled it by adding `predict False` to the screen. The screen doesn't seem to be predicted anymore, yet the function is still being called twice.

Is this intended? Can I disable it?

**Comment by renpytom** [comment]
Yes, it's intended.  Screens aren't allowed to have side effects.

**Comment by Booplicate** [comment]
Found a workaround, a bit inconvenient, but works.
```renpy
$ temp = heavy_function(*func_args)
call screen MyScreen(*temp)
$ del temp
```
