### ISSUE TITLE
Support AV1 codec movies on RenPy 7.x/8.x

### ISSUE THREAD

**Issue by iamtakingithard** [renpy/renpy#3400]
"​AV1 is an open source & royalty-free video codec developed by the Alliance for Open Media, a non-profit industry consortium. Depending on the use case, AV1 can achieve about 30% higher compression efficiency than VP9, and about 50% higher efficiency than H.264."

src: https://trac.ffmpeg.org/wiki/Encode/AV1

I think there should be no issues in adding AV1, since it's open source and royalty-free. Personally I would love to see that in RenPy 7.x/8.x

**Comment by renpytom** [comment]
I suspect this would require upgrading ffmpeg, and using its av1 decoder.

**Comment by suphamster** [comment]
Any news for this? AV1 is much better old VP9 at speed and compression efficiency (if encoding with svt-av1 codec aka libsvtav1 in ffmpeg).

**Comment by suphamster** [comment]
Since libaom comes with avif support now it's possible to add AV1 support just changing few lines in ffmpeg.py in renpy-build tasks https://github.com/renpy/renpy-build/commit/b8978eb654b0e841542335b702c5e84f1aca0aeb

**Comment by deepglugs** [comment]
> Since libaom comes with avif support now it's possible to add AV1 support just changing few lines in ffmpeg.py in renpy-build tasks [renpy/renpy-build@b8978eb](https://github.com/renpy/renpy-build/commit/b8978eb654b0e841542335b702c5e84f1aca0aeb) [oa4_launch.webm](https://user-images.githubusercontent.com/17669188/212892093-301e9308-e70a-4699-ade4-3d51fee3e5c9.webm) (file from tutorial encoded to AV1 for testing)

Is this a pull request or pending merge?

**Comment by deepglugs** [comment]
made a PR here using @suphamster 's patch https://github.com/renpy/renpy-build/pull/63

**Comment by suphamster** [comment]
Fastest **CPU** encoder for now is SVT-AV1 that included in recent ffmpeg builds by default. As far as I know quality for this encoder (comparing at same bitrate/crf and quality settings with VP9) is mostly depends on preset value (more info about params and presets [here](https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Parameters.md) and [there](https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/CommonQuestions.md#what-presets-do)) so if your AV1 video looks almost the same as VP9 than try to lower preset value. Here is a few (1 pass) examples using bitrate and [CRF](https://trac.ffmpeg.org/wiki/Encode/AV1#CRF).
```
ffmpeg.exe -y -i "C:\games\tutorial_7-7.4.10.2178-win\game\oa4_launch.webm" -c:v libsvtav1 -preset 8 -b:v 300k -g 240 -svtav1-params scd=1:fast-decode=1 -c:a libopus -b:a 40k -f webm "C:\games\tutorial_7-7.4.10.2178-win\game\oa4_launch.av1"
move /y "C:\games\tutorial_7-7.4.10.2178-win\game\oa4_launch.av1" "C:\games\tutorial_7-7.4.10.2178-win\game\oa4_launch.webm"
```
```
ffmpeg.exe -y -i "C:\games\tutorial_7-7.4.10.2178-win\game\oa4_launch.webm" -c:v libsvtav1 -preset 8 -crf 30 -g 240 -svtav1-params scd=1:fast-decode=1 -c:a libopus -b:a 40k -f webm "C:\games\tutorial_7-7.4.10.2178-win\game\oa4_launch.av1"
move /y "C:\games\tutorial_7-7.4.10.2178-win\game\oa4_launch.av1" "C:\games\tutorial_7-7.4.10.2178-win\game\oa4_launch.webm"
```
SVT-AV1 encoder preset=8 gives about same quality as VP9 (with good quality setting) but encodes much faster (especially on good CPU). Sadly there are not many GUI ffmpeg encoders that allows to set presets but I think [this tool](https://github.com/Alkl58/NotEnoughAV1Encodes) doest its job (don't forget to go to Video tab and enable svt-av1 there, speed=preset).
