### ISSUE TITLE
Cannot input non-alphabetic languages on Mobile because the inputtype is password

### ISSUE THREAD

**Issue by emz911** [renpy/renpy#3402]
Non-alphabetical keyboard languages are not compatible with the mobile builds (Android and iOS), attempting to switch Input Method Editors (IME) on the keyboard is not allowed because the inputtype is password.

Related issue/might be the bug: https://github.com/libsdl-org/SDL/issues/3377

Thanks for noting this issue! :)

**Comment by renpytom** [comment]
I'm backing this out, as it's causing too many problems on the latest SDL, as seen in #3608. 

I'm going to just document that this is a limitation of Android.
