### ISSUE TITLE
Using renpy.show() in post-execute function of creator-defined statement breaks rollback (a little)

### ISSUE THREAD

**Issue by dovedozen** [renpy/renpy#3405]
I wrote a CDS with a post-execute function that displays an image using renpy.show(), and it works pretty well for the most part, but when a transform which includes offset is included in the at-list of that show statement, the offset is repeated anytime I roll back to the statement associated with the show() (in practice, the line of dialogue directly following my CDS). This means that rolling back inevitably pushes my displayable out of the spot I intended it to be in. Rolling back to a line before my CDS call, then moving forward again, either by clicking or with the mouse wheel, resets it... sometimes.

My execute function clears the relevant layer with renpy.scene(), meaning that when a second instance of the CDS is reached, the first displayable is cleared. However, if I do this and then roll back to the first instance, it still behaves as described above (clearing the layer doesn't "reset" the displayable as far as rollback is concerned).
```
"The Beginning"
my_cds my_displayable
CHAR "Dialogue 1."
"Dialogue 2."
my_cds my_other_displayable
CHAR "Dialogue 3."
"Dialogue 4."
```
Reaching "Dialogue 1" displays `my_displayable` as intended. If the xoffset is 150, clicking through to Dialogue 2, then rolling back to 1 will display the image at an offset of 300. Reaching Dialogue 3 hides `my_displayable` and shows `my_other_displayable`. Rolling back to Dialogue 1 after that puts `my_displayable` at an offset of 450. Rolling all the way back to The Beginning resets `my_displayable` to its original offset of 150... but proceeding to Dialogue 4, then rolling back to Dialogue 2, _does not reset `my_other_displayable`_.

I'm still playing with workarounds, but is this something that could be fixed in the future? (Or: could there be something notably wrong with / missing from my approach?)

**Comment by renpytom** [comment]
I don't think there's enough information here to diagnose this. Can you please post the source code for your CDS?

**Comment by dovedozen** [comment]
Can do. I hope it's okay if I post it right in the comment? Super new to this whole scene; thanks for bearing with me!

First, here's the definition of the statement itself:
```
python early:

    def parse_fx(lex):
        obj = []
        check_point = lex.checkpoint()
        lex_piece = None
        lex.advance()

        if lex.match("extend"):
            lex.unadvance()
            lex.unadvance()
            lex.unadvance()
            lex.advance()
            lex_piece = 0

            while str(lex.word()).upper() != str(lex.word()) or not lex.match("\"") and lex_piece < 10:
                lex_piece += 1
                lex.unadvance()
                lex.unadvance()
                lex.advance()
            if lex_piece == 10:
                print("why do you have so many things btwn your say and your extend. stop that.")
                return ["mc", test, 0]
            elif lex.match("\""):
                obj.append("mc")
            else:
                lex_piece = lex.name()
                obj.append(lex_piece)

        elif lex.match("show"):
            lex_piece = lex.word()
            obj.append(lex_piece)
        elif lex.match("\""):
            obj.append("mc")
        else:
            lex_piece = lex.name()
            obj.append(lex_piece)

        lex.revert(check_point)
        next_word = 0

        while not lex.eol():
            next_word = lex.word()
            obj.append(next_word) # Always an image tag or Character object.
            next_word = lex.word()
            if next_word is None:
                obj.append(0)
                break
            elif isinstance(next_word, basestring) or str(next_word.upper() == str(next_word)):
                obj.append(0)
                obj.append(next_word)
            else:
                obj.append(next_word)
                next_word = lex.word()
                if next_word is None:
                    break
                else:
                    obj.append(next_word)

        return obj


    def clear_fx_layer(obj):
        renpy.scene(layer="effects")
        return


    def execute_fx(obj):
        x = 0
        while True:
            try:
                whos_emoting = obj[0+x]
                fx_type = obj[1+x]
                fx_pos = obj[2+x]
                fx_display(whos_emoting, fx_type, fx_pos)
                x = x+3
            except:
                break
        return


    renpy.register_statement("fx", parse=parse_fx, execute=clear_fx_layer, post_execute=execute_fx)
```

Here's the display function, which `post_execute` calls:
```
init python:

    def fx_display(whos_emoting, fx_type, fx_pos):
        hold_this = None
        if str(whos_emoting).upper() == str(whos_emoting):
            hold_this = eval(whos_emoting).image_tag
            whos_emoting = hold_this

        if fx_pos == 0:
            if whos_emoting == MC.image_tag:
                fx_pos = [mc_fx_pos]
            elif not renpy.showing(whos_emoting):
                fx_pos = [side_fx_pos]
            else:
                fx_pos = renpy.get_at_list(whos_emoting)
                fx_pos.append(fx_right)

        else:
            hold_this = fx_pos
            fx_pos = renpy.get_at_list(whos_emoting)
            fx_pos.append(hold_this)

        renpy.show(fx_type, at_list=fx_pos, layer="effects")
        return
```

The offending transform:
```
transform fx_right:
    yanchor 0.0
    ypos 100
    xoffset 150
```

The images I've been testing with are just static PNGs defined using their filepaths.

That should be all the context, but let me know if there's something else I can do that might help!

**Comment by renpytom** [comment]
Can you put together a small game that uses this? I'd probably need to run this and see what's happening to be able to understand what's going on. I don't see a glaring error here, so I'd like to see where the transform is getting its properties from.

**Comment by dovedozen** [comment]
If I managed to upload it right, this should work. Thank you for looking into it!
https://github.com/dovedozen/fx-test-game
