### ISSUE TITLE
[Feature Request] Resume playing music after load

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#3407]
Hello, would it be possible to implement music resuming after saving and loading from the exact point where we left it.

**Comment by renpytom** [comment]
Not easily. Do you have a use case for this?

**Comment by KatieCheerios** [comment]
Well the use case is that music just repeats from start over and over after every load. I tried doing this with tracking the name of the song, timer and then in after_load label play music with "from <>". The approach that I chose was very performance heavy and lable after_load still somehow played main menu music instead of that from scene. When I called the function in game after loading it worked, but rollback was braking it a little. That's why I ask if it possible to do implement internally.

**Comment by renpytom** [comment]
That's not really a use case. 

Basically, this would be a significant amount of work to pull off. I'm trying to figure out if there's some sort of gameplay purpose for this that I'm not seeing.

**Comment by KatieCheerios** [comment]
It's kind of annoying when music after every loading plays from the start over and over, but if it's too much time and effort then don't waste it on this. \It just wasn't working properly how I tried to do it.

**Comment by renpytom** [comment]
I don't think this is worth the amount of work, and I suspect that if I was to spend the time I'd have people who dislike having players brought into the middle of a song without hearing the start. I'll close this.
