### ISSUE TITLE
Issue found when using AlphaMask and Flatten on different than default resolutions

### ISSUE THREAD

**Issue by NNDanny** [renpy/renpy#3409]
To replicate this issue, start up any project with a different resolution than the default (used gui.init(1920, 1080) in this case). When using Flatten or AlphaMask, there's a small but noticeable loss in quality.

It looks as if the operations used are downscaling the image to work with it, and then returning the image upscaled again, which results in a loss of quality (also seems to use nearest neighbor, when project has it set on false?)

This seems to be related to a closed issue (https://github.com/renpy/renpy/issues/2644), but this time it also affects the normal intended use of both Flatten, and AlphaMask (which does the same exact thing) (as far as I've tested).

First image is a non-Flatten() image, second one has been Flatten(). Both are zoomed in images from The Question.

![image](https://user-images.githubusercontent.com/51226161/163020534-273b9268-d9f4-4c56-9c77-eb686a3f988d.png)
![image](https://user-images.githubusercontent.com/51226161/163020569-74002d69-8b69-4110-8919-985b2245cd27.png)

Sorry if this is a known thing and it's not going to be fixed. I tried searching for a solution that doesn't involve giving up on quality, but I can't seem to find one.

**Comment by NNDanny** [comment]
Okay, I tried that and it doesn't work for Flatten nor for AlphaMask.

Basically, what I'm doing is using Flatten or AlphaMask on an image, and that already lowers the quality of the image if the resolution of the game is 1920,1080. 

The image size does not matter, it happens while the game is 1920,1080, but it doesn't happen when the game is on the default resolution, using the exact same image (in this case, the image used was "sylvie green giggle.png", from the_question.

If needed, I can attack the code used to replicate.

**Comment by NNDanny** [comment]
```renpy
init python:
    #gui.init(1280, 720)
    gui.init(1920, 1080)

image sylvie = "sylvie green giggle"
image sylvie problem = Flatten("sylvie green giggle")

transform char(y=1.04, z=0.9):
    yanchor 1.0
    ypos y
    zoom z
    xcenter 0.5

label start:
    while True:
        #show sylvie at char(6.8,7.3) #Use this with project resolution set to (1280, 720).
        show sylvie at char(5.3,8.3)

        "This Sylvie should look \"normal\" (ignoring the blur from the zoom)"

        show sylvie problem 
        "Now, the image quality has dropped, ONLY if the resolution of the project is set to 1920x1080."

    return
```

This code uses the_question as a base, for the images to show. Thanks for your time.

**Comment by renpytom** [comment]
I've addded a new parameter to Flatten, drawable_resolution=False that handles this case. This turned out to be a fairly synthetic example - scaling up past 2x is going to be an artifacty mess in most cases, and the problem is that the artifacts different when scaling up in 1 vs 2 steps.
