### ISSUE TITLE
(documentation) renpy syntax formal reference

### ISSUE THREAD

**Issue by maathieu** [renpy/renpy#3410]
Hi, I like creating games on old portable game consoles (such as Game Boy Advance and Neo Geo Pocket) and I've been considering for a while a way to parse renpy files using a simple engine to generate an intermediate format that could then be interpreted by a C-based parser. I would like to do this with Renpy since I've made a few games with it and I am familiar with it.

I have two issues:

1. I am looking for a formal syntax reference that lists all the possible statements in a compact manner, is there such a document somewhere (or more generally speaking, a Renpy Engine Developer Documentation) or does the user documentation makes do as a reference?
2. I wonder what kind of strategy I could devise to deal with the bits of python code intertwined in Renpy game sources (statements starting with $), as my target systems won't run any python. For simple statements I could translate them to C (such as variable assignments) but more complex ones, idk.
Thoughts and comments welcome!

**Comment by renpytom** [comment]
(1) There isn't a formal syntax reference like this. The closest thing is parser.py, along with atl.py and sl2/slparser.py, but that's not formal.

(2) I don't think there's a good answer to this. Certainly, it's outside of the scope of the Ren'Py project.

**Comment by maathieu** [comment]
thanks for the pointers :-). I'll check how the parser works!
