### ISSUE TITLE
Choices with % generate wrong translation files

### ISSUE THREAD

**Issue by Victorius-Astral** [renpy/renpy#3417]
Hey,

This bug has been around for as long as I use Renpy (a year or so), I now use the latest stable (7.4.11.2266), and it's also there. When you have an % in your choice menu, you need to use \% or %% to make it not raise an error, in the text you also need to use /%, it won't raise an error, but LINT will show this as a problem. The thing is that for choice menu renpy will generate always %% (even if in choice it's /%), the bug lies in the fact that the translation system looks for just a single %.

Example:

```
menu:
   "Remove my corruption [[-50\% Sanity, -5\% Corruption]":
      pass
   "Restore my clarity [[+100\% Sanity, +5\% Corruption]":
      pass
```
It will generate:

```
translate spanish strings:

    # game/events/dreams/deal_with_the_devil.rpy:32
    old "Remove my corruption [[-50%% Sanity, -5%% Corruption]"
    new "Remove my corruption [[-50%% Sanity, -5%% Corruption]"

    # game/events/dreams/deal_with_the_devil.rpy:32
    old "Restore my clarity [[+100%% Sanity, +5%% Corruption]"
    new "Restore my clarity [[+100%% Sanity, +5%% Corruption]"
 ```
 
But translating this won't work at all. For the choice to get translated you need to make it a single %. Only this shows correctly in-game:

```
    old "Remove my corruption [[-50% Sanity, -5% Corruption]"
    new "Remueve mi corrupción [[-50% Cordura, -5% Corrupción]"

    # game/events/dreams/deal_with_the_devil.rpy:36
    old "Restore my clarity [[+100% Sanity, +5% Corruption]"
    new "Restaura mi claridad [[+100% Cordura, +5% Corrupción]"
``` 
   
But then again, when you generate translation files the next time, it's new %% translations, translators not knowing this will double translate it, if I try find-replace-all I'll get errors as translations are repeating ('Translation for this string exists already at:` errors). If the developer forgets to delete all in one language it will not be translated in-game amounting to a bug.

If you're reading it PyTom, please leave a comment if you're going to fix it anytime soon. I have a lot of new languages to generate, and I dunno if I should wait for it to work or generate them now and fix it for every language.

Dialogues also generate this %%, but it's not a problem as they work based on ID, so it doesn't matter, as it doesn't look for OLD string.

**Comment by renpytom** [comment]
I'll aim to fix this quickly.
