### ISSUE TITLE
Reload has bug.

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#342]
When config.save_directory is None, reloading game twice at the same position  causes game to return to main menu.

For example
1: Set config.save_directory to None.
2: Start tutorial.
3: Start game.
4: Reload game.
5: Reload game again

renpy v6.17.4.409

**Comment by renpytom** [comment]
I'm closing this for now. Could you check 6.99, and reopen if it's still a problem?

Note that in current Ren'Py, shift+R is a toggle - it changes autoreload mode. To do a manual reload, you have to hit it twice.
