### ISSUE TITLE
Android: Giving "Allow management of all files" permission

### ISSUE THREAD

**Issue by Bibifoc95** [renpy/renpy#3432]
Hello,
In my game, I made changes to:
1/ Store saves in a 2nd location (which won't be erased when the app will be removed)
2/ Store multipersistent file in a shareable location

It works well... if I manually give the **Allow management of all files** permission to the app.

The **android.permission.WRITE_EXTERNAL_STORAGE** persission isn't sufficient (it corresponds only to the **Allow access to media only** permission). It needs to be the "all files" thing.

It would be cool if Renpy could automatically prompt the player to allow this access. I know some people already managed to do that but I think it would be better if Renpy had a standard way of doing this.

Thx

**Comment by renpytom** [comment]
There are the renpy.check_permission and renpy.request_permission functions. 

Beyond that, I don't expect to do this. If I was to download a visual novel, and it was to prompt me to manage all files, then I'd assume it was up to no good - why does a visual novel need the same level of permissions that a file manager does. And so I think giving you the tools to request access is fine, but I don't see integrating any more of that into Ren'Py.

**Comment by Bibifoc95** [comment]
The 2 functions don't work for this specific permission. In fact, it's not really a "permission" because it implies **Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION**. But as you wish.

**Comment by renpytom** [comment]
Okay, closing this.
