### ISSUE TITLE
Allow config.side_image_tag to change in-game

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3434]
An use case would be switching the protagonist mid game and keep tracking its side image.

This could work by being a store vaiable just like `default_mouse` can change `config.mouse`

**Comment by renpytom** [comment]
This should be easy, though it'll work a bit differently.

**Comment by renpytom** [comment]
Implemented, and it probably works how you'd expect. Thanks for the idea.

**Comment by raspberry-soft** [comment]
It works great! thanks!
