### ISSUE TITLE
Bug at start of apk execution

### ISSUE THREAD

**Issue by Syrup007** [renpy/renpy#3441]
Hello team! I came to report a bad experience I had with not only this time about certain games that were made with Ren'py, as soon as I entered the game and its games loading screen was done, at the beginning of the prologue the game stopped working suddenly and without warning in that same part no matter the times.

I would like it fixed if it is a bug, or if it is not, tips on how to reverse it.
Thanks for reading!

**Comment by renpytom** [comment]
Do you have an adb logcat or other output? What device is this?

**Comment by Syrup007** [comment]
honestly i'm new to programming, i don't know about all the functions of my cell phone but i found only "adb shell...", are you referring to it?
It's on, besides I don't think I have another output, I currently use an Android 12 (Samsung Galaxy A12) 64GB of internal memory, and 4GB of RAM.

The game is a 3D animation, which currently reaches 1.21 GB I thought it was just storage but it doesn't seem like that from what I've tried.

**Comment by Syrup007** [comment]
If you want to take a look at the game I tested, it's called Corrupted Kingdom and it's on the Itch.io platform.
Another game I tested was deleted so I don't know its name anymore but it was lighter and the problem was the same, now it was a 2D animation and a little more complex controls.

**Comment by renpytom** [comment]
Please work with the game's developer to get that information to me. There's not much I can do for specific games without developer support.
