### ISSUE TITLE
Timers don't start until next event after calling screen with swing transition

### ISSUE THREAD

**Issue by kostek00** [renpy/renpy#3446]
I created myself a screen with **timer**. What I discovered is that if game is in window and mouse cursor is outside game when screen with timer is called with swing transition timer doesn't start, it's frozen. I have to move mouse into game window to start timer and then I can safely move cursor outside window and counter will still properly count.

I don't know and have no way to check if this bug appears in full screen when you use more than one monitor and your mouse is on different monitor when called screen with timer and swing transition appears.

Code for my screen affected:

```
define EyecatchRotate = Swing(2.0)

screen eyecatch(num):
    modal True

    timer 6.5 action [Return(), With(EyecatchRotate)]

    if persistent.seen_ending:
        key 'dismiss' action [Return(), With(EyecatchRotate)]

    add 'images/background/eyecatch[num].png'

label start:
    call screen eyecatch('01') with EyecatchRotate
```

I'm on Ren'Py version 7.4.11.2266.

Edit: I edited whole post and title as I managed to pinpoint exact issue with timer.

This bug only happens when you call screen with swing transition (showing screen doesn't bugs timer). I checked other transitions like fade, dissolve, etc. and they don't bug out timer, everything works correctly with them. So it seems timer is only affected with this new 3D transition.

**Comment by mal** [comment]
Cut down test case verified on `8-nightly-2022-04-23-9814d78e9`.

```rpy
label main_menu:
    $ _confirm_quit = False
    return

screen test():
    timer .5 action Return()

label start:
    "Before"
    call screen test() with swing
    "After"
    return
```

Observations:
- This doesn't occur if `swing` is replaced by `dissolve`.
- Rather than being to do with the cursor being inside the window, it seems that the timer doesn't activate until the next event. i.e. pressing an unbound key, moving the mouse, etc.

**Comment by kostek00** [comment]
That's probably the case as I tested it only with mouse.
