### ISSUE TITLE
Steam Functions

### ISSUE THREAD

**Issue by Xrisofor** [renpy/renpy#3449]
I usually don't write questions because I'm looking for solutions myself, but I have a request. RenpyTom can you add more Steam Api functions at once using RenPy, so as not to write them manually, for example SteamAPI.IsSteamRunning, SteamUserStats.GetAchievementIcon and other achievement functions, some SteamWorkshop functions. If it is not difficult for you to add at least a small part of the functions, especially SteamAPI.IsSteamRunning, I wanted to check whether the steam client is running or not, so that, depending on the data received, I could replace the username from steam or ask the user to enter it manually. It's possible that this function exists and I just didn't notice it. Perhaps the translation is inaccurate because Yandex Translate was used.

**Comment by renpytom** [comment]
This is already done, in 7.5/8.0

Assuming steam is present, the entire Steam API is available through ctypes bindings as achievements.steamapi. The best way to use this is to check if that object is not-None, which means Steam initialized. Then you can do:

```renpy
init python:
    if achievement.steamapi:
        steam_name = SteamFriends().GetPersonaName()
    else:
        steam_name = "Guy Shy"
```

Note that these are the nightly builds, not the release version.

**Comment by Xrisofor** [comment]
I forgot to ask how I can implement opening the steam overlay when clicking on the text (not the button)

**Comment by renpytom** [comment]
I'm not sure what you mean by thay.

**Comment by Xrisofor** [comment]
I meant something like this
![image](https://user-images.githubusercontent.com/60542735/165269596-18470eb9-d31a-4e15-b4d4-60953c409080.png)

**Comment by Xrisofor** [comment]
also, if it won't be difficult for you, update the RenPy documentation by inserting not only Steam Achievement functions there, but also others

**Comment by renpytom** [comment]
I  don't plan to support the Steam overlay like that, but you could write a custom hyperlink handler to do it - https://www.renpy.org/doc/html/config.html#var-config.hyperlink_handlers has the documentation for that. 

I don't plan to document the Steam API functions, as with the new module, the functions are the same ones supported by Steamworks, so you can use the documentation provided by valve, and the Python ctypes documentation.
