### ISSUE TITLE
Custom transition not working

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#3451]
As the title says I'm trying to make a custom transition that inverts the colors for 0.3s to then show the new scene
here's the code:

```
init python:
    def Invert(old_widget, new_widget):
        old_widget = Transform(
                        old_widget,
                        matrixcolor=InvertMatrix()
                    )

        return MultipleTransition(
                            [
                            False, Pause(0.3),
                            True
                            ],
                            old_widget=old_widget,
                            new_widget=new_widget
                )
```

but when i try to run the transition i get this error
`Exception: Expected transition to be a displayable, not a <curry <class 'renpy.display.transition.MultipleTransition'> ([False, <curry <class 'renpy.display.transition.NoTransition'> (0.3,) {}>, True],) {'new_widget': <Fixed at 5c8e950>, 'old_widget': <Transform at fbf13d0>}>`

which is weird since i've followed the exact principle as `Fade` does

**Comment by Andykl** [comment]
This is because in RenPy namespace `MultipleTransition` is a curry (kinda partially created instance) of real `MultipleTransition`.
To use `Invert` as other transitions your code should look something like
```py
init python:
    def Invert(old_widget, new_widget):
        old_widget = Transform(
                        old_widget,
                        matrixcolor=InvertMatrix()
                    )

        return MultipleTransition([
                       False, 
                       Pause(0.3),
                       True,
                   ])(old_widget=old_widget, new_widget=new_widget)
    Invert = renpy.curry(Invert)
```

**Comment by Gouvernathor** [comment]
[The doc](https://www.renpy.org/doc/html/trans_trans_python.html#transitions) showcases a function which calls a transition on the given arguments and returns the result of that call, which is a displayable. Your function instead defines a transition (while passing it undocumented and invalid arguments), and returns it.
Basically, the transition class returns a transition object, and a transition object returns a displayable.

**Comment by Elckarow** [comment]
this was the code that worked for me
```
init python:
    def Invert(old_widget, new_widget):
        old_widget = Transform(
                        old_widget,
                        matrixcolor=InvertMatrix()
                    )

        return MultipleTransition(
                                [
                        False, Pause(0.2),
                        False, Pause(0.0),
                        True,
                    ]
                )(old_widget=old_widget, new_widget=new_widget)
```
using `Invert = renpy.curry(Invert)` as Andykl told still gave me the error i previously said
