### ISSUE TITLE
renpy.known_languages() has a bug?

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3454]
I was trying to get the game to detect the translations that the game has, but there seems to be a bug.

```
> print(renpy.known_languages())

> set([u'jp', u'English'])
```
The problem here is that there is no 'jp' folder, the strange thing is that I can't find the folder for this translation and I have no way to remove it.

![imagen](https://user-images.githubusercontent.com/36079551/165422611-680a94f5-cea1-4037-ae0b-8119121c487f.png)

And the RenPy backup folder does not contain this translation either.

![imagen](https://user-images.githubusercontent.com/36079551/165422826-6de479a1-3291-4b88-aed6-a5f3f4b31e9b.png)
https://www.renpy.org/doc/html/translation.html#renpy.known_languages

**Comment by renpytom** [comment]
Could you have a translate jp block anywhere in your game? This uses the translation blocks, not the folders on disk. 

If not, please post the game and I'll dig through it.

**Comment by Neyunse** [comment]
> Could you have a translate jp block anywhere in your game? This uses the translation blocks, not the folders on disk.
> 
> If not, please post the game and I'll dig through it.

Oh, I get it. Yes, it had something that changed the styles of the Japanese texts. So it's not a bug, thanks for solving this. :D
