### ISSUE TITLE
Question: how to make changes to renpy files?

### ISSUE THREAD

**Issue by rvolgers** [renpy/renpy#3457]
I was thinking about implementing a custom lint, and for rapid prototyping I figured it would be smart to modify the existing lint functionality.

I would also like to avoid compiling the C / Cython modules if possible. The README seems to say that this exact use case should be possible by using a nightly build.

However, if I follow the instructions there, none of the Python files in the git checkout are used, it uses the python files from the nightly build, not just the binary modules. So if I make changes to `lint.py`, they are never used (obviously I don't want to edit the files in the downloaded nightly).

Could you clarify if I'm doing something wrong / misunderstood something? What is the right way to do development on this repo?

**Comment by renpytom** [comment]
What operating system are you on? 

In general, what's needed to make Ren'Py run are the renpy.exe/renpy.app/renpy.sh, and then the contents of the lib directory. 

Can you do me a favor and open the console, and type into it:

```python
import sys
sys.path
```

So we can see where Ren'Py is being imported from, relative to the git checkout?

**Comment by rvolgers** [comment]
I've managed to bypass the problem replacing the symlinked lib dir and shell script with copied versions. So it's not immediately blocking me anymore, but I'm still interested in investigating this further when I pick this up again just because I want to know what's going on. I won't be working on this next week though.

Feel free to close the ticket if you like, since I'm unblocked even though it's not totally resolved. If I end up finding the README could use an extra note to help future people I'll send a PR.

**Comment by renpytom** [comment]
Sounds good, thank you for working on it.
