### ISSUE TITLE
Make OpenDirectory() available.

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3458]
An usecase could be a button that opens the screenshot directory. The player could be clueless or bothered to search it.

I'm using the action from the launcher and it works fine.

**Comment by KiloOscarSix** [comment]
@raspberry-soft if you need an immediate solution for a project I've found
```
def open_folder(folder):
        import webbrowser
		import os

        path = os.path.join(config.basedir, folder)
        webbrowser.open('file:///' + path)
```
to be effective
