### ISSUE TITLE
Ren'Py 8: Add support for a Raspberry Pi platform.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#3459]
It probably makes sense to target the 64-bit version for Ren'Py 8.

**Comment by madeddy** [comment]
Question is how many people run RenPy on this. Maybe this should be polled. Could even be a chance to get a bigger overview what OS users run below RenPy.

**Comment by renpytom** [comment]
I wound up adding support for both 32-bit and 64-bit ARM.
