### ISSUE TITLE
Better import syntax request

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3460]
Would be cool if we could do `from store_module import x` like we can do with Python packages.

Say we have one module defined:
```renpy
init python in test_module_0:
    var0 = 0
```
Then we try to use constants/funcs/classes from it in another.
This works fine, but you'd have to prefix all your imports.
```renpy
init 10 python in test_module_1:
    from store import test_module_0
    var1 = test_module_0.var0 + 1
```
But this won't work, throwing `ModuleNotFoundError: No module named 'test_module_0'`. Almost like it doesn't recognise it's also a store module I can import from?
```renpy
init 10 python in test_module_1:
    from store import test_module_0
    from test_module_0 import var0
    var1 = var0 + 1
```

**Comment by Booplicate** [comment]
Ah I see.
I checked `sys.modules` and the module is still being imported as `"store.test_module_0"`. So `from store import test_module_0` effectively does nothing. I guess I'll have to prefix it with `renpy.store`.

**Comment by renpytom** [comment]
Sorry, I made a mistake with the syntax. You can do:

```
from store.mystore import myfunc
```

Or whichever.

**Comment by Booplicate** [comment]
Okay, I was just wondering if there's a way to make
```py
from mystore import myfunc
```
work too. But generally what you suggested is short enough to type, too. I'll close this as resolved.
