### ISSUE TITLE
Choice Menu Lag

### ISSUE THREAD

**Issue by yyou22** [renpy/renpy#3462]
Hello,

Whenever I use the built-in menu choice statement, my game skips a frame. This is especially noticeable when I have a looping ATL in the background. However, when I try to reproduce the problem in a newly created game, it does not happen. I tried to look up more information and noticed that there was one other person experiencing the same problem in the discord server, in which I have attached here as an additional reference. Any advice would be greatly appreciated. Thanks a lot in advance.

<img width="600" alt="Screen Shot 2022-04-29 at 11 18 07 PM" src="https://user-images.githubusercontent.com/33607623/166088700-4d5b80c4-e80c-490a-93fe-d94016884f80.png">

**Comment by renpytom** [comment]
Chances are, this is the autosave that occurs at each menu. Try 7.5/8.0, as that might fix things. Otherwise, I'll need a replication that makes this happen, so I can see what's going on.

**Comment by yyou22** [comment]
Hey renpytom, thank you for your response.

To provide some updates, I tried out multiple nightly builds and noticed that the issue still occurs in [Renpy-7.5-04-01](https://nightly.renpy.org/7-nightly-2022-04-01-7b217e59f/index.html) but is fixed in [Renpy-8-04-01](https://nightly.renpy.org/8-nightly-2022-04-01-7b217e59f/index.html).

However, on a different note, my game is completely unplayable in the more recent builds of 7.5/8.0 (I tried out [Renpy-7.5-04-28](https://nightly.renpy.org/7-nightly-2022-04-28-f97ba2f63/index.html), [Renpy-7.5-04-24](https://nightly.renpy.org/7-nightly-2022-04-24-d242babb2/index.html) & [Renpy-8.0-04-28](https://nightly.renpy.org/8-nightly-2022-04-28-f97ba2f63/index.html)). All audios become ear-tearing glitches, and some of the movies are completely messed up. I have absolutely no clue what's going on, and here's a screenshot of a movie being played at my main menu:
<img width="500" alt="Screen Shot 2022-04-30 at 12 09 16 AM" src="https://user-images.githubusercontent.com/33607623/166090056-08917840-c506-4a88-83d1-c98785136371.png">
Thanks again for your help, and let me know if you'd prefer me to open a new issue.

**Comment by renpytom** [comment]
Yikes. 

Let's close this, and you can open a new issue for the visual and audio problems.
