### ISSUE TITLE
Audio and Video Problems on macOS in Nightlies

### ISSUE THREAD

**Issue by yyou22** [renpy/renpy#3463]
Hello, 

As briefly mentioned in #3462, my game becomes completely unplayable in the more recent nighly builds (unplayable versions that I tried out: [Renpy-7.5-04-28](https://nightly.renpy.org/7-nightly-2022-04-28-f97ba2f63/index.html), [Renpy-7.5-04-24](https://nightly.renpy.org/7-nightly-2022-04-24-d242babb2/index.html) & [Renpy-8.0-04-28](https://nightly.renpy.org/8-nightly-2022-04-28-f97ba2f63/index.html)). 

All audios become ear-tearing glitches, and certain movies are completely messed up (see screenshot). However, the issue does not occur in [Renpy-7.5-04-01](https://nightly.renpy.org/7-nightly-2022-04-01-7b217e59f/index.html) or [Renpy-8-04-01](https://nightly.renpy.org/8-nightly-2022-04-01-7b217e59f/index.html). Let me know if you need more information, and thank you Tom again for looking into these issues.
<img width="500" alt="Screen Shot 2022-04-30 at 12 09 16 AM" src="https://user-images.githubusercontent.com/33607623/166090786-96a7bfbe-62eb-47ab-ae2c-0ebe6c403f29.png">

**Comment by renpytom** [comment]
Can I have access to the game, please?

**Comment by yyou22** [comment]
Sure. A while ago I have sent you a short demo regarding a different issue. I just tried it out and you should be able to reproduce this problem with the same build. I have responded to the same email for your convenience.

**Comment by renpytom** [comment]
Got the game. 

Two more questions: Does this only happen for with your game, or does it happen on all games? (Especially The Question and the Tutorial game.)  And what OS are you running on?

**Comment by yyou22** [comment]
Just tried running the tutorial with 7.5-04-28 and the issue also occurs. The music becomes complete glitches and the video displayable is unwatchable. I am on macOS Catalina with a 16-inch MacBook Pro. My processor is 2.4 GHz 8-Core Intel Core i9 and my GPU is intel UHD Graphics 630.
<img width="1281" alt="Screen Shot 2022-04-30 at 12 56 15 AM" src="https://user-images.githubusercontent.com/33607623/166091804-b7cd03a0-5276-424a-96ab-35005e638ba7.png">

**Comment by renpytom** [comment]
Can you run back through the nightlies to see if you can figure out where it started happening?

**Comment by yyou22** [comment]
For sure. I will get back to you when I pinpoint the exact build.

**Comment by yyou22** [comment]
Hey Tom, the issue starts occuring in exactly [Renpy-7.5-4-24](https://nightly.renpy.org/7-nightly-2022-04-24-d242babb2/index.html) and [Renpy-8-4-24](https://nightly.renpy.org/8-nightly-2022-04-24-d242babb2/index.html) on April 24th. 
Hope this helps.
