### ISSUE TITLE
Add QOI image format

### ISSUE THREAD

**Issue by Teashrock** [renpy/renpy#3467]
There's a new lossless image format on the Internet, which has been developed for using in videogames.

Benefits compared to stb_image and stb_image_write:
 - 20x-50x faster encoding
 - 3x-4x faster decoding
 - 20% better compression

The standard implementation also fits in 300 lines of C code.

Limitations:
The file format itself allows for huge images up to 18 exa-pixels, but the standard implementation is limited for images up to only 400 million pixels. If the image is larger than that, it will refuse to encode/decode, because it loads the whole image file into RAM and, according to the words of the author, is not extensively optimized for performance (but is still very fast).

QOI-files themselves are also significantly larger than PNG.

The implementation itself can be found here: https://github.com/phoboslab/qoi

**Comment by renpytom** [comment]
For image formats, we use SDL_image. I don't think we want to support new formats until they show up there.

**Comment by Teashrock** [comment]
@renpytom 
No particular reason actually, it's just a proposal. Closing this for now.

**Comment by Teashrock** [comment]
Reopening this due to SDL_image adding QOI support in version 2.6.0. Here it is: https://github.com/libsdl-org/SDL_image/releases/tag/release-2.6.0

**Comment by renpytom** [comment]
I actually looked this over, and I'm not sure I understand why someone would want to use a QOI image, given that it's 20% larger than the equivalent PNG. 

The new formats in 8.1 (AVIF and SVG) both have benefits that are worth taking the time to investigate. I'm not sure that's true of QOI. So I guess my question is - is there a reason why it would be rational to choose QOI over PNG?

**Comment by Teashrock** [comment]
@renpytom 
While QOI is larger than PNG, it also loads faster. I see it as something important to Ren'Py, also accounting that new Python versions are slower than previous. It can improve the speed of handling images at least in ATL, because the last time I tried to make a frame animation with pure ATL, it stuttered until it loaded every image into the memory. Maybe it would help?

**Comment by renpytom** [comment]
I think that a better way of handling this would be to make sure Ren'Py can predict the images. I wrote an article about that at: 

https://www.patreon.com/posts/avoiding-caused-17255706

I don't see QOI as something I want to include.
