### ISSUE TITLE
Inconsistent interpolation?

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3470]
Given this simple image and 2 transforms:
```renpy
image s = Solid("#fff", xysize=(200, 350))

transform t1:
    perspective True
    block:
        linear 1.0 matrixtransform RotateMatrix(0.0, 45.0, 0.0)
        pause 1.0
        linear 1.0 matrixtransform RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        repeat

transform t2:
    block:
        linear 1.0 xpos 50
        pause 1.0
        linear 1.0 xpos 0
        pause 1.0
        repeat
```
If I do `show s at t2` it works as expected, the image starts at `xpos 0` and moves to `xpos 50`, then back and repeats. That's how all the transform properties work as far as I'm aware.
But if I do `show s at t1`, I get different results. The image will be already rotated by 45 degrees when it's shown, as if it doesn't start from the identity matrix, but from the rotated matrix.

This can be fixed if I change the first transform to
```renpy
transform t1:
    perspective True
    matrixtransform RotateMatrix(0.0, 0.0, 0.0)
    block:
        linear 1.0 matrixtransform RotateMatrix(0.0, 45.0, 0.0)
        pause 1.0
        linear 1.0 matrixtransform RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        repeat
```
Looks like a bug to me.

**Comment by Booplicate** [comment]
Hmm, this is worse than I thought.
I added some time to interpolation so it's slower:
```renpy
transform t1:
    perspective True
    block:
        linear 4.0 matrixtransform RotateMatrix(0.0, 45.0, 0.0)
        pause 1.0
        linear 4.0 matrixtransform RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        repeat
```
I have to wait `5` seconds before the animation "begins." That means renpy evaluates the first interpolation which last 4 second, but doesn't actually change `matrixtransform`.

This is not a solution, but just to test some things I did this:
```py
def interpolate(t, a, b, type): # @ReservedAssignment
    """
    Linearly interpolate the arguments.
    """

    # Deal with booleans, nones, etc.
    if b is None or isinstance(b, (bool, basestring, renpy.display.matrix.Matrix)):
        if t >= 1.0:
            return b
        else:
            return a

    # Recurse into tuples.
    elif isinstance(b, tuple):
        if a is None:
            a = [ None ] * len(b)

        if not isinstance(type, tuple):
            type = (type,) * len(b)

        return tuple(interpolate(t, i, j, ty) for i, j, ty in zip(a, b, type))

    # If something is callable, call it and return the result.
    elif callable(b):
        # NOTE: This is the only difference, we return a rotatematrix instead of None
        a_origin = getattr(a, "origin", renpy.store.RotateMatrix(0, 0, 0))
        rv = b(a_origin, t)
        rv.origin = b
        # print(f"rv: {rv}", end="\n")
        return rv

    # Interpolate everything else.
    else:
        if a is None:
            a = 0

        return correct_type(a + t * (b - a), b, type)
```
And now it works as expected. Now the question is, how to fix this properly.

**Comment by Booplicate** [comment]
Another interesting example
```renpy
transform t1:
    perspective True
    block:
        linear 2.0 matrixtransform ScaleMatrix(1.5, 1.0, 1.0)
        pause 1.0
        linear 2.0 matrixtransform RotateMatrix(0.0, 45.0, 0.0)
        pause 1.0
        linear 2.0 matrixtransform RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        linear 2.0 matrixtransform ScaleMatrix(0.5, 1.0, 1.0)
        pause 1.0
        repeat
```
This is what's happening:
 - show scaled to 1.5 right away
 - show rotated by 45 right away (with scale being reverted?)
 - animate rotate to 0
 - show scaled to 0.5 right away
 - animate scaling to 1.5
 - now loop to step 2 and repeat

This is seems to be another issue where `matrixtransform` isn't being preserved, but I think both issues have the same (or close) root.

That's because `origin` has to be of the same type as the new interpolation. If it's `None` or a matrix transform of another type (in my example it was scale and rotate matrices), then we get no smooth interpolation.

**Comment by renpytom** [comment]
> That's because origin has to be of the same type as the new interpolation. If it's None or a matrix transform of another type (in my example it was scale and rotate matrices), then we get no smooth interpolation.

That's true, but also documented, IIRC. It doesn't make sense to interpolate between scale and rotate matrices.

**Comment by Booplicate** [comment]
I didn't see anything about it, must have missed? It kinda makes sense if I want to first scale, then rotate.
Apparently this:
```renpy
transform t1:
    perspective True
    block:
        linear 2.0 matrixtransform ScaleMatrix(1.5, 1.0, 1.0) * RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        linear 2.0 matrixtransform ScaleMatrix(1.5, 1.0, 1.0) * RotateMatrix(0.0, 45.0, 0.0)
        pause 1.0
        linear 2.0 matrixtransform ScaleMatrix(1.5, 1.0, 1.0) * RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        linear 2.0 matrixtransform ScaleMatrix(0.5, 1.0, 1.0) * RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        repeat
```
works, but the order is important, if I swap them, I get no smooth interpolation. Which is documented:
> Matrixes can be chained together with multiplication. It's easiest to think about them being applied right to left.

so I guess it's fine. Although, having to repeat code isn't ideal.

Anyway, can anything be done regarding the first problem (getting no interpolation over time)?

**Comment by renpytom** [comment]
> Anyway, can anything be done regarding the first problem (getting no interpolation over time)?

You have to start off with the multiplication of matrixes you want.  

```
transform t1:
    perspective True
    matrixtransform  ScaleMatrix(1.0, 1.0, 1.0) * RotateMatrix(0.0, 0.0, 0.0)
    block:
        linear 2.0 matrixtransform ScaleMatrix(1.5, 1.0, 1.0) * RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        linear 2.0 matrixtransform ScaleMatrix(1.5, 1.0, 1.0) * RotateMatrix(0.0, 45.0, 0.0)
        pause 1.0
        linear 2.0 matrixtransform ScaleMatrix(1.5, 1.0, 1.0) * RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        linear 2.0 matrixtransform ScaleMatrix(0.5, 1.0, 1.0) * RotateMatrix(0.0, 0.0, 0.0)
        pause 1.0
        repeat
```

**Comment by Booplicate** [comment]
Hmmm I see. So I just have to always add `ScaleMatrix(1.0, 1.0, 1.0) * RotateMatrix(0.0, 0.0, 0.0) * OffsetMatrix(0.0, 0.0, 0.0)` as "default" `matrixtransform` and then I can work with any or all of them later?
I think adding this as another example would be handy. Especially if you could mention we have to have this "default" as a starting point for transform.

Also I'm really enjoying `matrixtransform`/`matrixcolor`! They allow to create a lot of cool effects. Thanks for your help.

**Comment by renpytom** [comment]
Let's leave this open as a documentation issue.
