### ISSUE TITLE
VPGrid not completely full in web 7.5.0

### ISSUE THREAD

**Issue by AdamSmasher1** [renpy/renpy#3475]
![VPGrid](https://user-images.githubusercontent.com/104849745/166486872-64e1c291-8cff-4145-8176-8871ba278d6c.png)

The problem occurs in any game built by the web builder version 7.5.0

**Comment by Gouvernathor** [comment]
Can you try to reproduce it from a blank project ?
Your "loc_home/location_veranda.rpyc" file may contain a vpgrid that's underfull, triggering the error.

**Comment by AdamSmasher1** [comment]
> Can you try to reproduce it from a blank project ? Your "loc_home/location_veranda.rpyc" file may contain a vpgrid that's underfull, triggering the error.

If I compile with version 7.4.11 then there is no problem.

**Comment by Gouvernathor** [comment]
That's because that version allowed unfull vpgrids, which was corrected since. See the "incompatible" page from the doc shipped-in with the renpy nightly (in the doc/ subfolder where you installed the nightly), it will show you how to fix this.
VPGrids work like grids (now), so you need to set `config.allow_underfull_grids` to True to allow them to be underfull.

**Comment by AdamSmasher1** [comment]
> That's because that version allowed unfull vpgrids, which was corrected since. See the "incompatible" page from the doc shipped-in with the renpy nightly (in the doc/ subfolder where you installed the nightly), it will show you how to fix this. VPGrids work like grids (now), so you need to set `config.allow_underfull_grids` to True to allow them to be underfull.

Its work for me, ty

**Comment by renpytom** [comment]
Reopening this, as config.allow_underful_grids should be the default when config.developer is False.

**Comment by AdamSmasher1** [comment]
> Reopening this, as config.allow_underful_grids should be the default when config.developer is False.


Thanks for the info
