### ISSUE TITLE
Remove an added file in a Music Room

### ISSUE THREAD

**Issue by LucarioWaltz** [renpy/renpy#3478]
I am adding a music player to my game with "Music Room".
Players can edit the playlist, which means they can add and remove files in a Music Room. But I found that I can only add files to a Music Room and not delete them.
![1236](https://user-images.githubusercontent.com/104976310/166951536-6f06d253-0b31-424c-a1cd-a158a41e6fcf.png)
Need to know how to remove an added file in a Music Room, any help is highly appreciated.

**Comment by m-from-space** [comment]
This is not a bug. The music room is a special class, that has special uses. It's not a "music player" like you want it. Just write yourself a list of files your players can add and remove from a list, just use basic python stuff for it.

If you need help with stuff, please go to the forum and don't report stuff as bugs please, that are not.

**Comment by renpytom** [comment]
This isn't a use case that MusicRoom is meant to support. I think it's fine to make feature requests on the issue tracker, but in this case, I don't think it's a feature that I'd want to support. I'd suggest looking at the implementation of the music room (which is in renpy/common/00musicroom.rpy), and create something that supports what you need based on that.
