### ISSUE TITLE
Ren'py doesn't save a variable as expected.

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#3479]
I just copy the forum entry here, since user Ocelot suggested it.

Save the game at the moment the line says and then reload. The number will be different every time. Why isn't it saved? I understand, that Ren'py is repeating the python statement, but why is "number" None all of a sudden?

I also read the documentation (https://www.renpy.org/doc/html/save_load_rollback.html), but still don't get it. Since "number" is created using the default statement and number was changed, it should be saved, right?

```
default number = None

label start:
    "We will create a random number after this statement, but only if it is None."

    if number is None:
        $ number = renpy.random.randint(0, 1000)

    "The random number is [number]. Let's save the game here and reload. It will change after load."

    "Let's try it again here. Number is still [number] of course and saving and loading works here."
```

Link to forum entry: https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=64512

**Comment by MiiNiPaa** [comment]
Can confirm, behavior in 6.99.13 and before matches documentation, described problem appears in 6.99.14 and later versions.
