### ISSUE TITLE
Allow insensitive_hover on buttons

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3485]

**Comment by renpytom** [comment]
That's not something that makes sense.

**Comment by raspberry-soft** [comment]
Sorry for not explaining.

I know in sounds counter intuitive and defeats the purpose of being insensitive, but it occurs to me if it exists, it could be used to allow an insensitive_tooltip to display the unlock conditions of a button, also an insensitive_sound to play an error sound e.g. like windows.

**Comment by renpytom** [comment]
That's the use case NullAction is meant for. You can do: 

```renpy

if wanted:
     textbutton "Go to jail." action Jump("jail") tooltip "Turn yourself in."
else:
     textbutton "Go to jail." action NullAction() tooltip "You're not wanted for anything."
```

**Comment by raspberry-soft** [comment]
Thanks! The suggestion came from an organization angle, to avoid writing a complex button/imagebutton with multiple parameters twice and create a new style just for a tooltip. But I guess it will cause confusion.
