### ISSUE TITLE
The keyboard doesn't display on iPad devices. Is it possible to display it like on the mobile ones?

### ISSUE THREAD

**Issue by AlyonaBez** [renpy/renpy#3488]

**Comment by renpytom** [comment]
The keyboard does display on ipad ports, I believe. Do you have an example of a game where it doesn't?

**Comment by AlyonaBez** [comment]
Yes, here it is 
https://drive.google.com/file/d/13M79oGVGo_atvGooDbamlEJNenCkY1f6/view?usp=sharing

**Comment by renpytom** [comment]
This is the web port, not iOS. I'll look into the problem soon.

**Comment by AlyonaBez** [comment]
Works. Thank you!
