### ISSUE TITLE
Threaded optimization problems

### ISSUE THREAD

**Issue by ifucan17** [renpy/renpy#3489]
I have an Nvidia graphics card. And  after exiting a game I get two different states for Threaded optimization. It is either left off or it is turned on. And neither is the default. The default for Threaded optimization is Auto.

This constant changing of threaded optimization is causing for me a lot of issues with other games I play with low frame rates among other problems.

**Comment by renpytom** [comment]
Current versions of Ren'Py should restore the setting to how it found it when the game ended. 

Beyond that, please file this as a bug report with Nvidia. Threaded optimizations interact poorly with the Python GIL, and this really should be something that games can opt into or out of, but so far there isn't such an API that works without an installer.

**Comment by ifucan17** [comment]
Games actually can opt out of it that is why Nvidia uses Auto. As I stated
in my error report Renpy does not restore Threaded optimization to it's
default setting, it sets it to on. With it being on this in fact causes
issues with games that do not work well with Threaded optimization such as
Minecraft which killed my framerate and was part of the reason I started
investigating why it was being turned on when the default setting for
Threaded optimization is Auto.

It's not like I don't have any experience with this since I own an Nvidia
gpu and I have seen it multiple times so now I remove that code from the
core.py script and it still works fine. I have 100 or more Renpy games on
my system and everyone that is 7.4.3 or greater either turns it to on or
leaves it off after exiting the game. There is even a thread about Threaded
optimization being turned off or to on, on the Nvidia forum.

**Comment by Org-gith** [comment]
I have Nvidia GPU, so had opportunity to tested it:
- Put Nvidia Threaded Optimization to "Auto" (default), after launching a Ren'py game, it's set to Disabled in the GPU panel and remains that way until manually put back to "Auto".
- Put Nvidia Threaded Optimization to "On", after launching a Ren'py game, it's still set to "On".
- Put Nvidia Threaded Optimization to "Off", after launching a Ren'py game, it's still set to "Off".
