### ISSUE TITLE
[Feature Request] Allow passing arguments into menu statement label character.

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#3490]
If we define our character, and its side images, It's possible to use it as a speaker for the menu label, unfortunately, it's impossible to pass say, or image attributes into it.

Although display statements can be used to work around this limitation, it would be more natural and simpler if we could use Renpy syntax here. 

**Problem 1**

```renpy
image side eileen base = Null()
image side eileen smile = Null()

define e = Character("Eileen", image="eileen")

label start:
    menu:
        e smile "Which path should I take?" # Image attributes
        "Go left":
            pass
        "Go right":
            pass
    return
```
```
File "game/scripts.rpy", line 8: expected menuitem
    e smile "Which path should I take?"
    ^
```

**Problem 2**

```renpy
image side eileen base = Null()
image side eileen smile = Null()

define e = Character("Eileen", image="eileen")

label start:
    menu:
        e "Which path should I take?" (what_color="#f00") # Say attributes
        "Go left":
            pass
        "Go right":
            pass
    return
```
```
File "game/scripts.rpy", line 8: end of line expected.
    e "Which path should I take?" (what_color="#f00")
                                  ^
```

**Comment by renpytom** [comment]
I just fixed problem 1. Problem 2 didn't manifest for me, and looking at the source, it seems like say arguments should be processed normally. It's possible Problem 2 was fixed between the version you're working with and 7.5/8.0.

I believe both cases now work.

**Comment by loafylemon** [comment]
I tested both scenarios on the most recent stable release. I apologize for not mentioning it at the beginning, I'll make a note of it the next time.

Thank you very much for your time!

**Comment by renpytom** [comment]
No problem, just wanted to justify why I didn't do anything to fix Problem 2.
