### ISSUE TITLE
64bit Windows .exe doesn't work | Renpy 7.5, Windows 11

### ISSUE THREAD

**Issue by Victorius-Astral** [renpy/renpy#3497]
Hey,

This is my 'lucky' day I guess, the third thing I report here today. As In the title 64bit .exe in the current nightly branch doesn't work, at least on Windows 11. I tried on the stable branch and it launched without problems. 32-bit works on both stable and nightly branches.

TL: This app won't work on your PC ...

![Screenshot_4](https://user-images.githubusercontent.com/78815540/168106718-53775f57-1355-4d06-a727-105d2c169439.jpg)

**Comment by loafylemon** [comment]
Latest Windows 11 update (KB5013943) causes issues on some system configurations, breaking .NET Framework 3.5, and some DirectX 9 applications due to the newly added d3d9on12 translation layer. This is most likely the issue.

Microsoft suggests rolling back the update for now if your device is negatively affected by it.

https://support.microsoft.com/en-gb/topic/may-10-2022-kb5013943-os-build-22000-675-14aa767a-aa87-414e-8491-b6e845541755

**Comment by renpytom** [comment]
Is the log.txt file being created before the crash? If so, can we see what it contains?

Ren'Py shouldn't be using d3d9 unless the computer is rather misconfigured.

**Comment by loafylemon** [comment]
My idea was that if we enable Angle wrapper through accessibility menu, it would pass calls into D3D9, and that could potentially conflict with the newly added D3D9on12 translation layer, but I cannot be certain.

**Comment by renpytom** [comment]
That certainly could be the problem. I'm currently updating my win11 vm to see if that's the issue.

**Comment by renpytom** [comment]
Just tried it in a Win 11 vm that's up to date, and it's not producing any problems. 

@Victorius-Astral Can you get me the log.txt when you get a chance (delete it, and see if Ren'Py re-creates it). Also, could this be coming from your antivirus program rather than windows proper?

**Comment by Victorius-Astral** [comment]
@renpytom The log file is not generated on launching 64-bit.exe (in launcher game launches without problem). I tried running as an admin, and in Win8 and XP compatibility modes. The antivirus is Windows Defender, turning it off didn't fix it. I scanned with VirusTotal, no matches - [VirusTotal scan](https://www.virustotal.com/gui/file/1eead7e2b2e0522b2a80374d6dc8245e5fb8dc0be1210fc94e912ec7b7acbe5c/detection)

Launching 32-bit results in the log. It has one error `Faled to initialize steam: WindowsError(126, 'Nie mo\xbfna odnale\x9f\xe6 okre\x9clonego modu\xb3u')`, (TL: can't find the defined module) but I never used steam to begin with, so it's probably skippable. The whole log:
[log.txt](https://github.com/renpy/renpy/files/8683631/log.txt).

@loafylemon I tried it before installing KB5013943 yesterday, with it today, it also doesn't work. I tried forcing GL2 renderer in 32-bit, and Angle2 too. But the 64bit doesn't even try launching. 

I also tried moving to a different folder. 

Perhaps it's a problem with my launcher or system? I'll check on a fresh launcher and another system shortly. I'm going to install the latest nightly from yesterday.

**Comment by Victorius-Astral** [comment]
This is the link to the game I had problem with I tried unpacking a few times:

[https://mega.nz/file/wUtGiJAK#84h5U1ZdCS0kqQcAhf4mzGZTlMSivXq8OmUho3QFopI](https://mega.nz/file/wUtGiJAK#84h5U1ZdCS0kqQcAhf4mzGZTlMSivXq8OmUho3QFopI)

**Comment by renpytom** [comment]
Hm... it looks like the .exe file is corrupt. Do you have the .ico file you used to make it?

**Comment by Victorius-Astral** [comment]
@renpytom Yeah, here is both .ico and .icns. I used them for a year already.
[icon.zip](https://github.com/renpy/renpy/files/8684080/icon.zip)

I invited you to my Master repo, it has the whole project folder.

**Comment by Victorius-Astral** [comment]
I tried compiling release 5 times, so it's not a random bug. I'll also mention again that compiling on 7.4 makes working .exe, without any changes in my script or files.

**Comment by renpytom** [comment]
I'm not able to run the game, as the language_selector screen doesn't exist. Did you not check it in?

**Comment by Victorius-Astral** [comment]
@renpytom Sorry forgot to send you tl folder, I have it as separate public repo, while Master is private. Here's a .zip with translation files

[https://mega.nz/file/kZ9CCY6S#el2XvWYb5Smknct1zEOJ4mEBIFG8I1-w79qm1DnsL_Y](https://mega.nz/file/kZ9CCY6S#el2XvWYb5Smknct1zEOJ4mEBIFG8I1-w79qm1DnsL_Y)

**Comment by Victorius-Astral** [comment]
@renpytom Right, if you want to launch from launcher, you need to drop images folder from the 0.2.2b .zip I sent before, it's over what GitHub accepts, so I ignored images folder in my repo
