### ISSUE TITLE
archive not created in Web build

### ISSUE THREAD

**Issue by sarrowsmith** [renpy/renpy#3501]
Web build doesn't appear to be consolidating files into configured .rpa archive, which means that even the simplest game can't be played on itch.io because the work-around for the 1000 file limit given at https://itch.io/post/1110620 doesn't work.

(Desktop builds *are* generating archive correctly.)

(7.4.11.2266)

**Comment by renpytom** [comment]
RPAs aren't the solution for web builds. Instead, I'd suggest editing the progressive_download.txt file to include more of your game in the initial download, which is bundled into a single file.

**Comment by sarrowsmith** [comment]
OK, thank you, that's solved my immediate problem.

I'm not going to close the issue because it does report observed unexpected behaviour, but I'm not going to object if you declare it to be a "won't fix".

**Comment by renpytom** [comment]
I'm not sure this rises to the level of wontfix, so much as just a standard platform difference. (Android doesn't create archives, either.) 

I'll close this.
