### ISSUE TITLE
[Docs] renpy.map_event inaccuracy

### ISSUE THREAD

**Issue by Lezalith** [renpy/renpy#3506]
It's basically just one word, I think, but I am still scared of PRs, so would someone be so kind? 

Docs state the following about the **keysym** arg in **renpy.map_event** function:

```
keysym
    One of:
        The name of a keybinding in [config.keymap].
        A keysym, as documented in the [Customizing the Keymap] section.
        A list containing one or more keysyms.
```

Even though the last point says "a list", it can't actually be a list. Tuples work fine, not sure about others DSs.

At least I think this is still relevant. I was searching for something in DMs with Tom and stumbled upon this in messages from 2nd of May 2021. Long time, but I haven't seen anything about it in the Changelog.

![Snímek obrazovky 2022-05-15 094754](https://user-images.githubusercontent.com/56970124/168462756-65607eac-92aa-4652-bd05-4202db5378d6.png)

**Comment by renpytom** [comment]
This looks like it was fixed 15 months ago, by changing keysyms to accept lists.
