### ISSUE TITLE
Intermittent bug with cutscenes not displayed

### ISSUE THREAD

**Issue by chang-zhao** [renpy/renpy#3507]
Here in most cases the cutscene doesn't appear:

    label start:
        $ renpy.movie_cutscene("images/movie.webm")
        "done"
        jump start

You might think it's because `mouseup_1` happening during the movie playing (or, likewise, a signal from `Enter` key released) - which also might be regarded as something needed correction in Ren'Py...

But here's another script that I tested on my machine, and the movie there often wasn't displayed either, though there was no clicking mouse or pressing keys near the time of that cutscene:

https://www.reddit.com/r/RenPy/comments/upeiua/renpy_movie_not_working/

I'm puzzled what could be the case of the bug. Some key/mouse up signal in some queue? Or something quite different? It seems though that putting `window hide` directly before the cutscene statement prevents its skipping.

**Comment by renpytom** [comment]
I'm unable to repeat this in 7.5. 

I don't believe it's events - generally, things are triggered by mouseup_1 and keydown_enter, and so in both cases the button would have to be pressed and released to cause another cycle. 

Do you have an example of a small game that does this reliably? There are a lot of things that could potentially cause this, but it isn't happening here.

**Comment by chang-zhao** [comment]
Sorry, I tested it with 7.4.

After I deleted "cache" and "rpyc" and used Nightly, the skipping doesn't seem to happen.

Thank you.
