### ISSUE TITLE
crop_relative should default to False for integers

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#3508]
Version: 7.5.0.22051404n

In the following example, I'm making a square with four colours (RGBY), then attempting to crop it with corner properties such that just the yellow square is visible, however once corner properties are given, the entire displayable disappears.

```renpy
image sqr = Solid("#f00", xysize=(256, 256))
image sqg = Solid("#0f0", xysize=(512, 256))
image sqb = Solid("#00f", xysize=(256, 512))
image sqy = Solid("#ff0", xysize=(512, 512))

image square = Fixed("sqy", "sqb", "sqg", "sqr", xysize=(512, 512))

screen square():
    add "square":
        corner1 (256, 256)
        corner2 (512, 512)

    textbutton "Exit" action Return()

label start:
    call screen square
```

**Comment by Booplicate** [comment]
Apparently this:
```renpy
screen square():
    add "square":
        crop_relative False
        corner1 (256, 256)
        corner2 (512, 512)

    textbutton "Exit" action Return()
```
works.
And this:
```renpy
screen square():
    add "square":
        corner1 (0.5, 0.5)
        corner2 (512, 512)

    textbutton "Exit" action Return()
```
also works (although the documentation says `corner` must be `None` or `int`).

Since you didn't specify `crop_relative`, it takes the value from `config.crop_relative_default` which defaults to `True`, so it tries to do relative cropping.

**Comment by loafylemon** [comment]
I must have missed the change that defaulted `config.crop_relative_default` to `True`. Thank you!

**Comment by Booplicate** [comment]
Note, this might be a bug, unsure.

**Comment by renpytom** [comment]
This looks like an issue for me, as crop_relative_default really shouldn't come into play when everything appears to be an integer.
