### ISSUE TITLE
Steam Deck Keyboard not automatically appearing?

### ISSUE THREAD

**Issue by Belgerum** [renpy/renpy#3511]
One of my games on Steam uses text input to name the protagonist, and it's the only thing stopping the game from being "Verified" rather than "Playable" according to Valve's review. I've tried to upgrade the game (which runs on Ren'Py 7.4.11) as described in this guide (https://github.com/renpy/steam-deck-guide), but this doesn't seem to change anything when playing the game on my recently-acquired Steam Deck, no matter what I try.

I've tried upgrading the game distribution directly, as well as upgrading the Ren'Py launcher before making a new distribution, but neither work. I tried manually adding `define _renpysteam.keyboard_mode = "always"` to the code in case the variable wasn't that way by default, but no dice.

My personal Steam Deck has installed all software updates, and is freshy out of the box, so I am fairly certain it's not the problem.

Is there any specific way a game needs to call the input screen to trigger the keyboard, or a way the input needs to be placed in the input screen itself? My game uses the following code:
```
label start:
python:
        yuu_name = renpy.input(_("Enter the protagonist's first name:"), pixel_width=350, default=__(yuu_name))
```
```
screen input(prompt):
    frame:
        text _(prompt)
        input id 'input' value VariableInputValue('yuu_name', default=True, returnable=True)
```

Alternately, is there some code I could place in the script or input screen that would call the Steam Deck Keyboard without trying to rely on having Ren'Py automatically detect when it is needed?

**Comment by renpytom** [comment]
Not easily. It's basically just looking for the rectangle where it's shown. Can you make a short game that exhibits the problem with 7.5, and I can go from there?

**Comment by Belgerum** [comment]
I'm sorry, I don't understand. Are you trying to say that Ren'Py is looking for a rectangular input box before showing the keyboard?

Also, I don't know how I could make clear what the problem is, since I simply have found no way to get the keyboard to appear automatically on the Steam Deck, and the only real way to properly display the problem would be to have an app on Steam itself which shows the problem, and I don't want to experiment too much with my own app, since people are paying for a playable game, not a tech demo.

**Comment by renpytom** [comment]
Oh, are you not approved for Steam? That'd be the problem, then - you need a Steam App ID for this to work.

**Comment by Belgerum** [comment]
I am approved for Steam and I have several games on the platform, actually. If you don't mind viewing NSFW content, I am at https://store.steampowered.com/developer/Belgerum

The game in question that is having issues with text input is https://store.steampowered.com/app/562350/

**Comment by renpytom** [comment]
Is that the Steam Deck enabled build for it? If so, could you give me access to it so I can load it onto my deck here?

**Comment by Belgerum** [comment]
Note for future readers: After some private chatting with renpytom, giving him a steam key, and working things out, we found the problem to be with [update_renpy_steam.py](https://raw.githubusercontent.com/renpy/steam-deck-guide/main/update_renpy_steam.py) not correctly updating these files:
renpy/common/00achievement.py
renpy/common/00steam.rpy
lib/python2.7/steamapi.py
