### ISSUE TITLE
String u'[]' ends with an open format operation

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#3512]
I'm unable to print variables from dict to a screen. It doesn't work with format nor variable interpolate. There's a simple code to showcase the problem. How is someone supposed to do this?
`default a = {"list":[]}

screen test():
    text "{}".format(a["list"])`

**Comment by renpytom** [comment]
Please don't use the issue tracker for non-issue questions like this. 

I'd write that as:

```
screen test():
     $ a_list = a["list"]
     text "[a_list!rq]"
```

Where !rq first does repr on a_list, and the q then quotes the result.
