### ISSUE TITLE
Web build doesn't take account "variant" on brave (chromium based) android

### ISSUE THREAD

**Issue by Azephir** [renpy/renpy#3524]
Hi

I've tested Nightly renpy 7.5.0.22051602n for the web features.

I've only got one issue linked to renpy so far: the web build doesn't take account the variant "touch" I put on my gui (screen.rpy) when running on android browser brave.

It works perfectly with safary or with google integrated browser on android. But with brave (chromium based), I have the display that I should have only on PC normally. Same with variant "small", "android", "mobile" (I've made some test).

But, renpy.mobile is still True on brave android, though.

Hope it will be useful.

Thanks for your amazing job guys !
Azephir

**Comment by renpytom** [comment]
I've tried it on Brave on my cell phone, using Ren'Py 7.5, and it worked just fine. 

One thing I noticed is that Brave does seem to cache more aggressively than chrome or firefox.

**Comment by Azephir** [comment]
Weird, all the gui I have on my cell phone on brave is the PC gui...

Work well with chrome.

**Comment by renpytom** [comment]
Could you have your phone using a desktop user agent, something like that? That is checked.

**Comment by Azephir** [comment]
Hum not sure...

My user agent is: Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.61 Mobile Safari/537.36

Brave is up to date and the "PC version" of Brave is unchecked. (The proof of that, itch.io treat the browser as mobile since it doesn't launch the game at start, like it does on PC).

**Comment by renpytom** [comment]
I'm not sure what I can do, because running in a similar manner works for me. I'll close this for now, since I'm out of ideas as to why it's not working for you.
