### ISSUE TITLE
Vector classes in RenPy

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3527]
Pygame has powerful `Vector` classes, could we get those in RenPy? I had to reimplement `Vector2` myself, it works fine, but I think it'd be better for creators if they had it out of the box. Also while speed doesn't seem to be a problem, I think if it was implemented in C, it'd be faster.
I'm not sure if `Vector3` is as needed in 2D, but maybe could still be useful for moving in the Z axis.

**Comment by renpytom** [comment]
I'd be fine if you wanted to contribute this to pygame_sdl2, but I don't believe there's much of a need for this in Ren'Py.

**Comment by Gouvernathor** [comment]
@Booplicate A typical simple-and-fast implementation would be using namedtuples, I used it that way in another python project and it worked fine, especially with [some functions from the math module](https://docs.python.org/3/library/math.html#math.dist).
Contact me on discord ([Armise#6515](https://discord.com/users/308349275975188481)) if you want me to give you the code for a pygame_sdl2 addition.
