### ISSUE TITLE
Custom shader crashes when applied over solid color displayables

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#3531]
Hi. I made a custom shader and it's working great, however, when I try to apply it to the master layer during the pause menu, it errors out sometimes. Here's how I apply the shader.
```
screen pause(): 
    on "show" action Function(renpy.layer_at_list, [chromatic_aberration], layer="master")

transform chromatic_aberration (strength=0.05):
    shader "kuro.chromatic_aberration"
    u_strength (strength)
```

And the specific error is 
```
While running game code:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
Exception: Shader (u'kuro.chromatic_aberration', u'renpy.geometry', 'renpy.solid') has not been given mesh attribute a_tex_coord.
```
Sometimes it lists the error as this, which seems to be functionally the same.
```
While running game code:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
Exception: Shader (u'kuro.chromatic_aberration', 'renpy.alpha', u'renpy.geometry', 'renpy.solid') has not been given mesh attribute a_tex_coord.
```

It should be noted that it only errors out if I've displayed a solid color displayable (e.g. `image black = Color(hsv=(0.0, 0.0, 0.0))`). If it's just regular backgrounds and sprites this works fine. Does this seem like a bug?

**Comment by renpytom** [comment]
The problem is that you're trying to use a_tex_coord, but it's not being provided - Solids don't use textures, so there are no texture coordinates in play. 

What does your shader look like?

**Comment by Kuroonehalf** [comment]
Here's the exact code.
```
renpy.register_shader("kuro.chromatic_aberration", variables="""
        uniform float u_strength;
        uniform sampler2D tex0;
        attribute vec2 a_tex_coord;
        varying vec2 v_tex_coord;
    """, vertex_200="""
        v_tex_coord = a_tex_coord;
    """, fragment_200="""
        vec2 uv =  v_tex_coord;

        vec4 displace_left = texture2D(tex0, uv - vec2(u_strength, 0));
        vec4 displace_right = texture2D(tex0, uv + vec2(u_strength, 0));

        float alpha = displace_left.a * texture2D(tex0, uv).a * displace_right.a;

        gl_FragColor = vec4(displace_left.x, texture2D(tex0, uv).y, displace_right.z, alpha);
    """)
```

**Comment by renpytom** [comment]
That won't work, because there's no texture to sample. I'd suggest either flattening the solid, or using the gl_color_mask property, which does this without a shader. 

https://www.renpy.org/doc/html/model.html#gl-properties

**Comment by Kuroonehalf** [comment]
Isn't gl_color_mask just about disabling color channels? I want to displace them. :o 

The documentation for Flatten says it's an expensive operation. Is there no better approach (short of just making images for these solid colors, which seems inefficient too)?

**Comment by Kuroonehalf** [comment]
Gosh, I'm really having trouble parsing a workable solution from the documentation. And even then, I'd run into the problem again if I wanted to do another shader that wasn't just channel displacement. It might be best for me to just render some flat color jpegs, as clumsy as that is.

Since it seems like we've exhausted the possible solutions to this problem, I'll close this.
