### ISSUE TITLE
Split screens.rpy into smaller files in default project template

### ISSUE THREAD

**Issue by mikolajspy** [renpy/renpy#3539]
As someone who sometimes heavily modifies UI and adds additional elements based on Screen Language I find it useful to have each screen in separate file. Additionally it will help new users who might get lost hearing "Find choice menu in screens.rpy file".
Basically split it by categories and names as in current screens.rpy file, nothing fancy.

The structure I'm using in most projects:

- screens [folder in place of file]
    - styles.rpy
    - menu [folder]
        - about.rpy
        - game.rpy
        - help.rpy
        - history.rpy
        - loadsave.rpy
        - main.rpy
        - navigation.rpy
        - preferences.rpy 
    - ingame [folder]
        - choice.rpy
        - input.rpy
        - quick.rpy
        - say.rpy
    - additional [folder]
        - confirm.rpy
        - mobile.rpy
        - notify.rpy
        - NVL.rpy
        - skip.rpy
    - custom [folder where my own new screens end up]

**Comment by renpytom** [comment]
It's perfectly fine that you're doing it this way, but it's not the only way to organize a project, and I think for a new user, having so many files out of the box will be overwhelming. Plus, VSCode provides a nice outline now, making files easier to navigate.

**Comment by Numerlor** [comment]
Would the many files be overwhelming? 
To me it seems like it'd make it easier to navigate, and ignore the files they don't need to use. The current file is delimited by categories anyway, and at least to me it seems more overwhelming to have a single file you have to constantly search in, instead of a single file only containing the code for related functionality

**Comment by raspberry-soft** [comment]
It's an interesting debate. When I was newbie having only four files out of the box made it seemed easy. Once I opened the screen file I got so lost for a long time and I was afraid I would break the game if a moved the screens to other files.

**Comment by Booplicate** [comment]
The suggested structure is probably too much, but I agree having 1.5k lines of screens and styles in one file is messy and is hard to read/edit. I think that maybe not that many, but using 2 or 3 files instead 1 would help.
