### ISSUE TITLE
Ren'Py 8.0.0.22051902n doesn't render emojis

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#3540]
I have tested this emojis tutorial https://www.youtube.com/watch?v=XB_RQGsbftc in the nightly versions of Ren'Py 7 and Ren'Py 8. Ren'Py 8 does not render the emojis correctly, version. Ren'Py 7 works correctly

**Comment by renpytom** [comment]
I'm not able to get this to fail for me on Ren'Py 8. Do you have an example script that works on one and not the other? I'm testing with:


```renpy
    "... {font=static/NotoEmoji-Regular.ttf}😀😀{/font}"
```

And it seems to work.

**Comment by Moshibit** [comment]
What I have tried is similar.
`e "hola {font=fonts/NotoEmoji-Bold.ttf}😀{/font}"`
 Only unrecognized characters appear in Ren'Py 8. I will try the regular version of NotoEmoji

**Comment by renpytom** [comment]
Sure. If you have a small game with a problem, can you post it somewhere, and include the log.txt?

**Comment by Moshibit** [comment]
my log.txt
`Fri May 20 20:19:43 2022
Windows-10-10.0.19044
Ren'Py 8.0.0.22051902n


Bootstrap to the start of init.init took 0.08s
Early init took 0.00s
Loader init took 0.05s
Loading error handling took 0.04s
Loading script took 0.20s
Loading save slot metadata. took 0.01s
Loading persistent took 0.00s
Faled to initialize steam: Exception('Init returned false.')
Running init code took 0.22s
Loading analysis data took 0.02s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Backing up script files to 'C:\\Users\\ERIK\\AppData\\Roaming/RenPy/backups\\emoji':
Dump and make backups. took 0.08s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.02s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.91s
Cleaning stores took 0.00s
Init translation took 0.05s
Build styles took 0.00s
Load screen analysis took 0.00s
Analyze screens took 0.01s
Save screen analysis took 0.02s
Prepare screens took 0.07s
Save pyanalysis. took 0.00s
Save bytecode. took 0.08s
Running _start took 0.00s
Performance test:
Interface start took 0.12s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'GeForce GTX 970M/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 389.12'
Display Info: None
Screen sizes: virtual=(1280, 720) physical=(1280, 720) drawable=(1280, 720)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
`

**Comment by renpytom** [comment]
And the game?

**Comment by Moshibit** [comment]
I'll upload it in a moment

**Comment by Moshibit** [comment]
I sent it on Discord

**Comment by renpytom** [comment]
I don't think I got it. Can you try sending again?

**Comment by Moshibit** [comment]
https://github.com/Moshibit/renpy_projects
