### ISSUE TITLE
Movies out of sync

### ISSUE THREAD

**Issue by ksiadz** [renpy/renpy#3542]
When I create webm sprites I am getting out of the sync of alpha mask and the base image. 

What I figured out so far, is that it happens after the first loop. The only way to force animation to be in sync after each loop was to make the animation size full resolution of the game. Meaning 1920x1080. I am guessing RenPy is moving one of the layers after the first loop is finished which is causing out of the sync. Making all characters sprites full screen size, brings the issue that we cannot position them using xalign left or right, so we can only show one character at a time... 

images definitions:
```python
    image hime = Movie(play="images/characters/hime/emiko_test_1080.webm", mask="images/characters/hime/a-emiko_test_1080.webm")
    image aa = Movie(play="images/characters/hime/emiko_test_1080.webm", mask="images/characters/hime/a-emiko_test_1080.webm")
```

The way I am generating my webms:
```bash
ffmpeg -framerate 30 -i Scene1_%03d.png -filter_complex "alphaextract[a]" -map 0:v -c:v libvpx-vp9 -crf 0 -b:v 0 miyu-happy-pants.webm -map "[a]" -c:v libvpx-vp9 -crf 0 -b:v 0 a-miyu-happy-pants.webm
```

![Screenshot 2022-05-20 at 12 53 17](https://user-images.githubusercontent.com/20033156/169522818-d6e3ccb9-2dd4-4d5e-b020-272f3fc24f3b.png)

**Comment by renpytom** [comment]
side_mask is the way to go for this, as it combines two movies into one. A usable pair of ffmpeg commands are in the development version of the documentation, but the end result should work with any recent version of Ren'Py. 

https://www.renpy.org/dev-doc/html/movie.html

Actually keeping the movies in sync is something that I don't see happening - after a lot of trying, I was never able to get it 100% correct.
