### ISSUE TITLE
Rename the "Documentation" button to a more user-friendly name

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3549]
For example to "How to Use" or "Manual"

Although "Documentation" is the correct and elegant term, for newbies out-of-the-box (which is the vast majority of users) that words could mean another thing. When I first saw that button I thought it was some tech/legal stuff.

I always see comments of new users saying Ren'Py is very limited because they see the default template and think that's all (myself included, I even dropped the engine for that reason at first, how I was mistaken). I suggest promting the user to read what Ren'Py is capable of more aggressively. 

Maybe an user-friendly promt when creating their first project: "This default template barely scratchs the surface of what Ren'Py is capable of. See `link` and learn how to make your ideas come to live."

**Comment by renpytom** [comment]
I don't think this is a change I'm likely to make. It would require a ton of retranslation work for very little benefit.
