### ISSUE TITLE
AtomEditor WinError 2

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#3560]
Downloaded 7.5/8.0 from May 22 and installed Atom Editor from the launcher. When I try to open any .rpy file it shows Windows Error 2.
Copying "Atom.edit.py" from "renpy-x.x.x-sdk/launcher/" to "renpy-x.x.x-sdk/atom/" fixes this bug.

RENPY_ATOM is not in windows environment variables.

**Comment by Gouvernathor** [comment]
Most likely related to #3224 and/ or 554a11b065ae5ffa7932404f40b1304627bc03f2.
