### ISSUE TITLE
R8.0: renpy.movie.cutscene hangs in splashscreen label after transitions

### ISSUE THREAD

**Issue by Tom-Dowd** [renpy/renpy#3571]
**DEFECT**: In the splashscreen label, using renpy.movie.cutscene causes the application to hang if a transition or pause is used before it.

**STEPS TO REPRODUCE**:
- create new RenPy 8 project
- add splashscreen label
- place $ renpy.movie.custscene command in label, properly pointed at a valid movie file
- run project-  project runs
- place any scene command accompanied by a transition (such as with Dissolve (2.0)) or a pause before renpy.movie.cutscene
- run project - project hangs when attempting to execute renpy.movie.cutscene

**SAMPLE CODE:**
(runs)
label splashscreen:
     scene black
     $ renpy.movie.cutscene("yourmovie")

(hangs on renpy.movie.cutscene)
label splashscreen:
     scene black
     with dissolve
    $ renpy.movie.cutscene("yourmovie")

**NOTES**:
     Various transition and pause usage all cause the same effect in the splashscreen label
     Transitions or pauses do not affect execution of the splashscreen label itself
    Transitions and pause work properly outside the splashscreen label (limited testing)

**Comment by renpytom** [comment]
I believe this was fixed last night, by c608bb5c1cf5bdf852e0272c8572fceb7ff01d8b .
