### ISSUE TITLE
Other animation systems than Live2D? - Spine implementation

### ISSUE THREAD

**Issue by artoonu** [renpy/renpy#3572]
Live2D support is great, but I don't like SDK license terms.
I've seen there's Spine system and it has Python framework - [http://esotericsoftware.com/spine-runtimes](url)

I'm not that advanced programmer so I don't know where to go from there.

**Comment by renpytom** [comment]
I'll be honest that I haven't really seen a ton of demand for Spine - maybe 1 person asks for it every couple of years. I don't think that it's something that's likely to become part of Ren'Py any time soon, though if demand changes I can re-evaluate that. (I will count this towards that demand.) 

I do think that what is likely is that we'll improve the Model class to make it easier to implement things like Spine on your own, or to hire a programmer to do that.

**Comment by tarnos12** [comment]
@renpytom Since we need more people to say a word, then here I am.
I would like to see Spine support in Ren'Py.

There is a python script for spine from 5+ years ago, but I haven't tested it yet.

**Comment by Cullster** [comment]
adding in to this! u would love it as well

**Comment by bryanrieger** [comment]
+1 for Spine (or [Rive](https://rive.app) which also supports vector graphics and state machines) support.

**Comment by maLikiz** [comment]
Is there any documentation that would allow you to add your modules written in cython to the Ren'Py engine, which use modules from the C language in themselves. in the modules directory there is a setuplib file in which there is a cython function. But I don't quite understand how to use all this. Trying to somehow move forward by focusing on how Live2D is used in renpy, I can't achieve this success. After my changes in the code, the engine does not start and I do not see any lags, how could I prologue errors when trying to start Ren'Py?

I also tried to clone this engine from the repository and try to run it using run.sh hoping that I will be able to receive logs there. But alas, I couldn't even launch it, I get the following errors:
![image](https://github.com/renpy/renpy/assets/4878139/a5a66b04-e02a-4548-994f-6f0f75aa8e2c)

**Comment by Gouvernathor** [comment]
The cython parts of the engine are compiled once at the time each version is built, instead of each time you launch it like the py files. That's done by renpy-build, which you will have to run in a virtual machine.

**Comment by Soranokotachi** [comment]
I just noticed this thread, I'd love it if spine could be added in like with Live2D

**Comment by crimsonnight** [comment]
+1

**Comment by Lunagamer128** [comment]
+1

**Comment by Lobisomen** [comment]
Same. For me, Spine support Is one of the major features which Ren'Py lacks.

**Comment by LastE13** [comment]
+1

**Comment by IvanLiaskovski** [comment]
+1
