### ISSUE TITLE
Bring the show/call/hide screen up to date with their statement equivalents

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3577]
The [renpy.show_screen function](https://www.renpy.org/doc/html/screen_python.html?highlight=show_screen#renpy.show_screen) takes parameters to set the zorder and the layer the screen will be shown at, and some other properties (_tag, _widget_properties and _transient).
The renpy.call_screen function is documented not to pass the corresponding parameters to the screen (because they start with an underscore), but it's unsaid whether the parameters have the same effect as in show_screen.
renpy.hide_screen only takes a parameter for the layer - and it's consistent since the zorder doesn't matter when hiding a screen.

The show screen, call screen and hide screen don't include any of these controls. `show screen skreen(_layer="master")` works, but is undocumented (I guess it also works with zorder, but it's just as undocumented). There's no other way of then hiding skreen with hide screen. The only ways I found were `$ renpy.hide_screen("skreen", layer="master")`, and `hide skreen` but it probably shouldn't be documented as working that way.

There should be a `layer` clause for the hide screen statement (or rather an `onlayer` clause, to match the simple hide statement).
There should be the same and a `zorder` clause for the show screen and call screen statements.
There should be an `as` clause for the show screen and call screen statements, matching the `_tag` parameter of the renpy.show_screen function, ~~and arguably _widget_properties and _transient equivalents~~.

**Comment by mal** [comment]
I'd be tempted to view those `_`-prefixed args working as an implementation detail, with the preferred method being to set those values inside the screen itself with the appropriate keyword. I'm not sure that complicating the basic show/call/hide screen statements with them to support hypothetical(?) cases (has this ever come up in the wild?) would be all that advantageous. Meanwhile anyone requiring the additional power can still use things as they are with acceptable caveats.

**Comment by renpytom** [comment]
I can see a case for as/onlayer/zorder (the first for all three, the last two for just call/show screen.) 

_transient and _widget_properties seem very python-specific for me, and so I don't think those need clauses.

**Comment by Gouvernathor** [comment]
The Show, ShowTransient, ToggleScreen and Hide actions (which apply to screens) should also be part of this update.

The _layer kwarg is already taken into account by all four, but only documented for Hide,

Show and ShowTransient would pass any kwarg related to zorder or to `as`/_tag to the renpy.show_screen function, but the code doesn't explicitly support it, nor is it documented as such.
ToggleScreen and Hide don't support it, but ToggleScreen probably should.

**Comment by Gouvernathor** [comment]
In addition to this, could/should the `_implicit_with_none` weird keyword argument be given a prettier clause equivalent ? For example a `no_with_none` keyword, similar to the `nopredict` keyword, with no value passed ?
