### ISSUE TITLE
Say attributes only work on a tag's default layer

### ISSUE THREAD

**Issue by mal** [renpy/renpy#3578]
In the second half of the example below say attributes are not applied, and hide doesn't work. This is because the they're looking at the `master` layer for the `alice` tag and not finding it (as it's on the `another` layer).

As much as I'd like to see this work, my fear is it's too ingrained to make work intuitively without needlessly impacting the 99.9% of existing use cases that won't care about this, so I'm filing it more for posterity and the distant hope that there may be a sane way to offer this, but am equally prepared for a "that ship has sailed" type resolution.

```rpy
define character.alice = Character('Alice', image='alice')
define config.speaking_attribute = 'speak'
define config.layers += ['another']

image alice = Placeholder('girl')
image alice speak = Transform(Placeholder('girl'), matrixcolor=BrightnessMatrix(.3))


label start:
    scene black
    show text "master layer"
    show alice:
        xalign .75
    pause
    alice "Hello"
    pause
    alice "Goodbye"
    pause
    hide alice

    scene black
    show text "another layer"
    show alice onlayer another:
        xalign .75
    pause
    alice "Hello"
    pause
    alice "Goodbye"
    pause
    hide alice # "onlayer another" would make this work
    return
```

**Comment by renpytom** [comment]
I don't think there's a good way to offer this, as it's possible to show a tag on multiple layers at once. So it's not clear which layer you'd want to use for this. 

We should have config.tag_layer (IIRC, that's the name) to pick the default layer for a particular tag.

**Comment by mal** [comment]
That's pretty much what I feared. `config.tag_layer` does indeed exist and do just that, but it does limit a tag to a single layer, which isn't always ideal.
