### ISSUE TITLE
Some keys should be blocked during a splashscreen

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3582]
During the splashscreen label keyboard control is allowed. Specially if the keymap is reconfigured, it could lead to players opening menus during it. Games usually only allow dismiss and fullscreen during that. Toggling the save screen during the splashscreen looks like a bug to a player.

I understand that ideally it should be up to the dev. But if you show a screen that blocks the key input like:

```
screen key_block():
    key BLOCKED_KEYS action NullAction()

label splashscreen:
    show screen key_block
    return
```

The problem with this and any use case of this screens is when a transition occurs (e.g. fade) the screen also transitions and loses its blocking function (or any function).

I suggest at least warning this in the doc (It's been like a year and I just noticed it for some reason, it also caused unforeseen bugs because I didn't know this happened.) and provide an example of how to disable key input in this case in particular. For example I'm using:

```
define config.top_layers = [ "keyblock" ]

screen key_block():
    layer "keyblock"
    key BLOCKED_KEYS action NullAction()

label splashscreen:
    show screen key_block
    # splash/transitions
    hide screen key_block
    return
```

As a side note this is a downside to `config.overlay_screens` which is commonly used to append a screen to toggle key control during a game. Using a top layer loses the benefits of said function.

IMO this is important because the splashscreen is a staple in games and people expect them to behave a certain way and customizing this is kind of advanced.

**Comment by renpytom** [comment]
I don't believe this is something that Ren'Py should deal with. 

Ren'Py disables access to the game menu during the screen action. If you're customizing the keymap outside of the normal Ren'Py keymap, it's up to you to do that correctly - and I don't believe that the engine can be made smart enough to figure out what is and is not correct for your customized keymap. 

So I don't think that this is something we should pursue at the engine level.

**Comment by raspberry-soft** [comment]
I agree with that, but I still suggest documenting that screens lose function while transitioning.

**Comment by renpytom** [comment]
Fundamentally, I don't think keyblocking screens are something I want the documentation to touch. I don't know why you use one, but in general the right approach would be to have whatever screen is handling your custom keymap just be conditional.

**Comment by raspberry-soft** [comment]
I found out devs use `config.overlay_screens` to append toggling key functions mid-game. If they are already doing that, the expected function dissapear during a transition. As devs/players don't expect a screen to lose function during a transition. Maybe that particular point could be documented.

**Comment by renpytom** [comment]
I think the fundamental issue is that it should be possible to make a screen that is always active.

**Comment by raspberry-soft** [comment]
Agreed.
