### ISSUE TITLE
Include Language Action documentation in the screen actions page

### ISSUE THREAD

**Issue by morbil** [renpy/renpy#3586]
I've noticed that the [Language Action](https://www.renpy.org/doc/html/translation.html?highlight=language#Language) is not include in the [Screen Actions](https://www.renpy.org/doc/html/screen_actions.html?highlight=actions#screen-actions-values-and-functions) documentation page, which limits its discoverability. I think it is appropriate to include it in both locations as it's an important action to consider for localized games.

**Comment by Gouvernathor** [comment]
Actually the way shpinx works doesn't allow the Language action to be included in two different places at once.
So, we'll add a link ([this link](https://www.renpy.org/doc/html/translation.html#Language)) to the Actions page.
