### ISSUE TITLE
Ren'Py 8.0.0 pre-release fails to download VSCode (on Linux)

### ISSUE THREAD

**Issue by Szprinktrap** [renpy/renpy#3596]
As the title says.
When i went to my settings to select Visual Studio Code as my text editor, after accepting license terms a uncaught exception occurs.
If that changes anything, i'm on Linux. Arch Linux to be precise.
Traceback file: [traceback.txt](https://github.com/renpy/renpy/files/8792235/traceback.txt)
It's also worth mentioning that i have VSCode installed [from AUR](https://aur.archlinux.org/packages/visual-studio-code-bin), but Ren'Py doesn't seem to detect it.

Sorry in advance for my bad English, it's not my native language.

**Comment by renpytom** [comment]
I just fixed this, you should be able to install it. 

Are you using the "Visual Studio Code (System)" editor? If so, what's the command-line for running VS Code - I have it as "code", the default.

**Comment by renpytom** [comment]
This should be fixed by renpy/extensions@d1fcff9a2f6a7e22627131f65800af238e51a985 .

**Comment by Szprinktrap** [comment]
Seems to work fine now!
 
> Are you using the "Visual Studio Code (System)" editor? If so, what's the command-line for running VS Code - I have it as "code", the default.

It's also "code" for me.

**Comment by Szprinktrap** [comment]
Nevermind i'm dumb, i didn't notice that "Visual Studio Code (System)" option at the bottom. 🤦
