### ISSUE TITLE
Link  scattered configuration variables to the main list

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#3597]
Based on #3586 and #3589 I propose to including configuration variables that are not in the general list.

scattered configuration variables:
https://www.renpy.org/doc/html/nvl_mode.html#config-variables
https://www.renpy.org/doc/html/side_image.html
https://www.renpy.org/doc/html/self_voicing.html#var-config.descriptive_text_character
https://www.renpy.org/doc/html/preferences.html#audio-channel-defaults
https://www.renpy.org/doc/html/model.html
https://www.renpy.org/doc/html/achievement.html#var-config.steam_appid
https://www.renpy.org/doc/html/gesture.html
https://www.renpy.org/doc/html/live2d.html

**Comment by renpytom** [comment]
This is fine, if you want to do this.

**Comment by Moshibit** [comment]
I will do it.
