### ISSUE TITLE
im.FactorScale() bilinear filtering is slightly corrupted

### ISSUE THREAD

**Issue by davey3000** [renpy/renpy#36]
When using im.FactorScale() (or im.Scale()), the default "squares" background of RenPy is merged with the image being scaled.  The effect is subtle and is most noticeable with large blocks of a single bright color when viewed at an angle towards the edge of the view angle range on an LCD.

The effect only occurs when using bi-linear filtering.  Switching to nearest neighbor filtering avoids the effect.

Reproducible case: create a new project (e.g. theme: "TV", color scheme: "colorblind").  Default screen size for the project is set to 800x600.  Create a png file ("white.png") that is 800x600 pixels in size and consists of just a solid opaque block of white.  Put the file into the new project's "game" directory and alter "game/script.rpy" to read:

``` python
init:
  define e = Character('Eileen', color="#c8ffc8")
  image scaled_pic = im.FactorScale("white.png", 1.0, bilinear=True)

label start:
  show scaled_pic
  e "Hmmm..."
  return
```

Tested with the Linux (32-bit) version of RenPy 6.14.1.366.

**Comment by renpytom** [comment]
Closing, as I don't believe this is present in modern versions in Ren'Py. Also, im.FactorScale is now not recommended for use.
