### ISSUE TITLE
Config variables almost not documented

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3600]
The following configuration variables are referred to by the documentation in one way or another, but don't have a `.. var::` entry anywhere.

The following ones have a (broken) :var: reference :
config.default_language
config.editor
config.console
config.perspective

These ones are referred to in code blocks :
config.skipping
config.gamedir
config.pad_bindings

(fixed in d7d53a0)
And that last one does not exist, yet is referred to in a (even more broken) :var: reference :
config.history_list_length

**Comment by Moshibit** [comment]
Maybe config.history_list_length is referring to config.history_length, it was just misspelled.

**Comment by Gouvernathor** [comment]
I'd like to add to that list the various configuration variables (in a broad meaning, not only in the config namespace) from the default files for new projects, which not all are documented. (list TBD)
