### ISSUE TITLE
Renpy 8/7.5 crashes when toggling mute

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3603]
If a music track is playing and `mute all` is selected (`Preference("all mute", "toggle")`) the game crashes without logging an error.

It doesn't happen if any track slider is at "0".

The same projects work fine on Renpy 7.4.11

I'm using Windows 10.

**Comment by raspberry-soft** [comment]
The culprit is having a sound file playing while muting (clicking the mute button):

```
style button:
    properties gui.button_properties("button")
    activate_sound "click.ogg"
```

It doesn't happen when adding `activate_sound None` to "mute all" or having the sound slider off.

**Comment by renpytom** [comment]
Is it all sounds, or some particular sound file?

**Comment by raspberry-soft** [comment]
Any sound it seems.

**Comment by Gouvernathor** [comment]
```rpy
screen test():
    textbutton "PLAY":
        action Preference("all mute", "toggle")
        activate_sound "audio/bloup.mp3"
```
This does not reproduce any crash.

**Comment by raspberry-soft** [comment]
Writing it that way does crash the game for me. Although it require some tries. Tested with mp3 and ogg and different short sound files.

**Comment by via-my** [comment]
Well. Found out that it happens when a file is played with fadein.
It crashes only when you mute it within the fadein phase after pressing "Play" textbutton.

```
textbutton _("Play"):
            action Play(u'music', "audio/test.mp3", fadein=1.5)
            
textbutton _("Toggle All"):
    action Preference("all mute", "toggle")
    
textbutton _("Toggle Music"):
    action Function(preferences.set_mute, u'music', not preferences.get_mute(u'music'))
```

**Comment by renpytom** [comment]
This turned out to be a divide-by-zero error in a portion of Ren'Py that adjusts an ongoing fade when the volume is adjusted. Thank you to @via-my for doing the work to figure out the conditions under which this issue triggered.
