### ISSUE TITLE
Interpolated strings break in screens [7.5]

### ISSUE THREAD

**Issue by cisco-donovan** [renpy/renpy#3604]
Hi, I'm running Ren'Py 7.5.0.22052902 from the 7.5.0 prerelease build from 29th May.

In 7.3.5 I am using interpolation of local variables in my screens. Here's some really simplified code:
```
define test_names = ['bobbi']
screen sm_test_screen():
  frame:
    vbox:
      for name in test_names:
        add "images/[name].png"

label start:
  show screen sm_test_screen
  pause
```
In 7.5.0 the same code breaks with an error like:

![image](https://user-images.githubusercontent.com/101652800/171233263-0adba9bb-8f00-4e7e-ad90-148bc6a386ca.png)

I can use concatenation to show the images and everything works fine.
```
  add "images/" + name + ".png"
```

The screen does actually render, and if I ignore the error screen I see it. But it's like the interpolation runs out of context or something.

Not sure if this is a 7.5.0 bug or something up with my code, but I wanted to flag it.

**Comment by mal** [comment]
Reproduced on `8-nightly-2022-05-31-c83a90ab1`. Curiously if the image doesn't exist the error message provided performs the interpolation as expected.

Image file present:
```
Exception: In DynamicImage 'images/[name].png': Could not find substitution 'name'.
```

Image file missing:
```
Exception: DynamicImage 'images/[name].png': could not find image. ('images/bobbi.png')
```

This feels like a prediction issue to me, tweaking the start label to read as below appears to completely prevent the issue.

```rpy
label start:
  "pause"
  show screen sm_test_screen
  pause
```

**Comment by cisco-donovan** [comment]
> Curiously if the image doesn't exist the error message provided performs the interpolation as expected

Yes, I noticed this! One of the reasons I decided it was probably a bug.

Thanks for reproducing!
