### ISSUE TITLE
{alt} strings show up on history screen

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#3607]
I've been playing around with the {alt} text tag in order to get character names to be correctly pronounced.
For a character named "Saeva", the exact code I use is `{noalt}Saeva{/noalt}{alt}Sayva{/alt}`.

While this works nicely in-game:
![image](https://user-images.githubusercontent.com/91261760/171289368-28fcd60c-172c-4e6f-97a6-aa2155c9a7ec.png)

The alt text is repeated in the history screen:
![image](https://user-images.githubusercontent.com/91261760/171289450-5bcbf2b2-4be2-4e77-9905-7838e3d79a6b.png)

It seems to me that this would not be the intended behavior.

**Comment by renpytom** [comment]
I've added this to the documentation:

```rst
For the noalt text tag to work with history, you'll need to edit
screens.rpy to make sure that :var:`gui.history_allow_tags` contains
"noalt". The defaultfor this variable is::

    define gui.history_allow_tags = { "alt", "noalt" }

(This change was necessary in 7.4, but only documented now.)
```

You'll need to edit screens.rpy yourself to fix this, but  once you do that should resolve the issue.

**Comment by kigyo** [comment]
Thanks, that did indeed resolve it!
