### ISSUE TITLE
[WEB REQUEST] optional parameter to load the compressed file from url

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3610]
I was thinking, that you could include to the web version an optional parameter to load the compressed file of the game from a URL. This could be interesting to reuse files that are not in the index path.

Although it may be somewhat complicated to achieve, maybe

**Comment by renpytom** [comment]
What benefit does this have over a normal build?

**Comment by Neyunse** [comment]
> What benefit does this have over a normal build?

For example, if we upload a web version to a server, we can only zip files to the same path where the index.html file is located.

Now, with a parameter, we could upload the file that is located in another folder or url. Example: 

normal:
play.renpy.org/?game=demo.zip
idea:
play.renpy.org/?gameurl=play.renpy.org/demo/game.zip

and so, if we have more games we can use again the same files located in the example "play.renpy.org/"

and avoid this:

play.renpy.org/demo/index.html
play.renpy.org/demo2/index.html
play.renpy.org/demo3/index.html

Sorry if my example is not well understood

**Comment by Neyunse** [comment]
I found a way to accomplish this, and it works perfectly.

https://tranquil-kangaroo-ef25c8.netlify.app/?gameurl=https://tranquil-kangaroo-ef25c8.netlify.app/games/demo.zip
https://tranquil-kangaroo-ef25c8.netlify.app/?gameurl=https://tranquil-kangaroo-ef25c8.netlify.app/games/the_question.zip

![imagen](https://user-images.githubusercontent.com/36079551/171967237-ed7aecc9-192a-4b07-8541-15c2006521f9.png)
I leave a screenshot of how I implemented it in case someone wants to do this.



As far as I tested, it seems to work without problems, however, the folder "game" that is generated with the files has to have the game files and if or if to be located in the root with only the necessary, in this case, only the images and the audios.

I do not know to what extent this can work. As far as I have tested, it seems to work without problems

**Comment by Neyunse** [comment]
And here it is with two different links
https://play.kagarisoft.com/?gameurl=https://game.kagarisoft.com/games/demo.zip

https://play.kagarisoft.com/?gameurl=https://game.kagarisoft.com/games/the_question.zip

**Comment by renpytom** [comment]
This will likely work until you upgrade Ren'Py, at which point the older games may not work. 

I'm still not sure I see the benefit of doing it this way, rather than the way we've been doing it.

**Comment by Neyunse** [comment]
It might be beneficial for developers who want to create some embed system, and link only the zip file. But hey, this sounded good in my mind...

**Comment by Neyunse** [comment]
It might be beneficial for developers who want to create some embed system, and link only the zip file. But hey, this sounded good in my mind...
