### ISSUE TITLE
Make Variable vs Field SL behavior consistent

### ISSUE THREAD

**Issue by morbil** [renpy/renpy#3611]
Was having a discussion about how `SetVariable` (with "object.field") and `SetField` (object, "field") both work and the pros and cons of each. While I prefer `SetField`, I can see how `SetVariable` taking "object.field" form is still useful. That said, it's not implemented consistently across screen language, and that's likely to create confusion in people who are used to working that way from SetVariable/ToggleVariable. 

An example is `FieldInputValue` and `VarfiableInputValue` in which the latter *must* be a field in global scope, rather than `object.field`. Likewise `FieldValue` / `VariableValue`. In general, having a variable that can be passed as a string, should do the "split"->"resolve all objects" pattern to be consistent.

**Comment by renpytom** [comment]
This seems reasonable, but probably an 8.1/7.6 thing.
