### ISSUE TITLE
Imagemap noticeably slow with property alpha True and when config.gl2 is True

### ISSUE THREAD

**Issue by brimbel** [renpy/renpy#3612]
Tested on 7.4.10/7.5/8.0, although the lag may be different based on computer specs

**Comment by renpytom** [comment]
I'd need a demo to do anything with this.

**Comment by brimbel** [comment]
Here's some videos of me testing it.

https://user-images.githubusercontent.com/106859253/172017869-4a763b5a-badb-4baf-baf2-b357ed3262b9.mp4

https://user-images.githubusercontent.com/106859253/172017872-71b7ac42-89db-41c1-8986-0aa2c750894c.mp4

Here's what I was testing with on 7.5: [z75.zip](https://github.com/renpy/renpy/files/8838317/z75.zip)

**Comment by renpytom** [comment]
Can I see your log.txt ?

**Comment by brimbel** [comment]
A log.txt should have been included in the .zip I sent, unless you're referring to the one sitting in the renpy-7.5.0-sdk folder, in which case, here:

 Sat Jun  4 10:20:57 2022
Windows-10-10.0.19041
Ren'Py 7.5.0.22052902
 

Bootstrap to the start of init.init took 0.08s
Early init took 0.00s
Loader init took 0.02s
Loading error handling took 0.03s
Loading script took 0.33s
Loading save slot metadata. took 0.02s
Loading persistent took 0.00s
Set script version to: None (alternate path)
Running init code took 0.52s
Loading analysis data took 0.03s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.03s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: "Couldn't load nvlib." (can be ignored)
Creating interface object took 0.00s
Cleaning stores took 0.00s
Init translation took 0.03s
Build styles took 0.00s
Load screen analysis took 0.03s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.08s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.08s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'Intel'
Renderer: 'Intel(R) UHD Graphics'
Version: '4.6.0 - Build 30.0.101.1340'
Display Info: None
Screen sizes: virtual=(800, 600) physical=(800, 600) drawable=(800, 600)
Maximum texture size: 4096x4096

**Comment by renpytom** [comment]
I haven't been able to repeat this, on either my Nvidia GPU or my Intel laptop. I've gone so far as to look at the raw frame times and OpenGL actions, and I'm not seeing anything out of the ordinary. You might want to try the Ren'Py nightly or the next prerelease to see if that fixed it, as it does have some fixes to focus issues, which this could be. 

That being said, I wasn't able to repeat this on the current prerelease, either, so I'm not sure what the issue could be.

**Comment by Org-gith** [comment]
I have noticed a similar lag while using GL2 on not evenly matched hardware like Laptops usually have. 
Correct me if wrong but my theory would be that GL2 pushes the envelope on the GPU more than CPU now, and old model based render would mostly use the CPU. Since average specs laptops, and not gamer laptops and similar not gamer targetted devices usually pair a decent CPU with a low-end integrated GPU like Intel HD series, I think it's why old render might work better on such type of device. Overall that kind of issue might solve by itself as technology progresses if it's what I'm thinking.

**Comment by morbil** [comment]
@Org-gith In this case, no, because the hit test is still performed on the CPU.

**Comment by renpytom** [comment]
There have been two rounds of optimization for this use case. 

In 8.1, we moved to a 1x1 renderbuffer, so there will be a lot less work done rendering the pixel opacity test. Coming in 8.2, there's also an optimization where operations on pixels that are outside the bounding box of non-transparent pixels do not need to hit the GPU. 

I've never been able to see this slowdown, but hopefully this will fix things for people that can. 

I'm closing this, but feel free to re-open if there's a slowdown in 8.2 nightlies (after 2023-12-03).
