### ISSUE TITLE
LayeredImages and alpha transforms

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#3613]
I've noticed that when you're using a transform that makes use of "alpha" together with layered images, you get something like this:

![image](https://user-images.githubusercontent.com/76883792/172023233-082c866f-5b64-4dda-8b09-166dfd1dbc49.png)

It seems like each layer is faded in (or out) individually, which causes the opacities to stack on top of each other. Certain parts therefore look like they fade in quicker than others, which looks pretty weird. (Note the hand, eyes, and front part of the hair.)

Is this an intentional design choice, aka are there circumstances where this would be desired? Otherwise, I think it would be ideal if the behavior could be changed to look the same as when using a dissolve.

**Comment by Andykl** [comment]
Yes, this is intentional design choice. When you want to use `alpha` transform property with layered image, you want to use [https://renpy.org/doc/html/displayables.html?highlight=flatten#Flatten](Flatten) or `mesh True` transform property (gl2-only).

**Comment by kigyo** [comment]
Wow, that was fast! Thank you very much!
