### ISSUE TITLE
Build distribution for Steam - suggestions

### ISSUE THREAD

**Issue by artoonu** [renpy/renpy#3616]
Generally, when making *.zip place all files directly, without "ProjectName-Version-OS" folder. So that *.exe is directly in packaged *.zip .
Or basically what build for Web does, for developers to zip themselves or copy files to Steamworks SDK - that would be more universal.

This should add small quality of life for developers who make Steam builds often. If this is already included and I'm missing it, please point me where to go.

That's for the simplest basics.

For something more advanced, there could be Steamworks SDK implementation for automatic upload like the one for itch.io .
For depot, there could be added a new variable, for example config.steam_depot .
Or a button in Ren'Py Launcher would open SteamGUI from Steamworks SDK with predefined path to files.

**Comment by renpytom** [comment]
A good point, and fixed in 5a9efaa85 . I don't want to so directly integrate with Steam, but having market default to the bare-zip makes sense.
