### ISSUE TITLE
[7.4.11-7.5] Game seem to get laggy/unresponsive when running 'against' a pause, tooltips seem to cease working

### ISSUE THREAD

**Issue by Bobyteal** [renpy/renpy#3617]
Here is a video to showcase the behaviour, 7.5 seems to be lagging/unresponsive at these pause moments (but the game runs fine when it's running the regular VN moments without pause on 7.5):

https://streamable.com/6qa2dx

On the left, the game is recorded on 7.4.10, and on the right, it is recorded on 7.5 (but the same was observed on 7.4.11). 
The 7.5 on the right uses the "define config.always_unfocus = False" (incompatibility change command from 7.4.11).

**Comment by renpytom** [comment]
I don't know what "running against a pause" means. 

Videos don't really help in a situation like this, I kind of need to know what's actually going on in the game.

**Comment by renpytom** [comment]
Most notably, unhovered handlers may be triggered more often, so I'd like to figure out what's happening there.

**Comment by Bobyteal** [comment]
Gotcha, it's not very clear, let's see how to put it differently... it's showing screens with hotspots for navigation just before a pause statement, which was a method used to make the logic work for point and click:

    show screen hall
    $ inventory_active = True
    $ renpy.set_return_stack([])
    pause

So the problem only seem to appear when the pause statement is there, but when it's running the regular VN logic which would be let's say:

player "blablaba"
character "blablabla"
etc...

then on that type of code, the tooltips would be working, everything would be responsive and acting normally. It's only when the pause statement pops up that everything to not work anymore.

**Comment by renpytom** [comment]
What does the screen look like? Could you get me a small example, so that within a click or two I can see what's going on?

**Comment by Bobyteal** [comment]
Aight, here the screen for the room that we can see in the video:

screen hallsecond():
        modal True
        zorder 90

        button:
            xpos 302
            ypos 938
            if android_navigation:
                add "back_android"
            else:
                add "back"
            mouse "button"
            xysize (1324, 123)     # to do: adjust the size width and height to match the size of the image
            action audio_footstepsolid, Jump("hallfirst")
            at hover_navigation

        button:
            xpos 291   #move the smoke
            ypos 276    #move the smoke
            if android_navigation:
                add "hallsecond_leftdoor_android"
            else:
                add "hallsecond_leftdoor"
            mouse "button"
            xysize (88, 441)     # to do: adjust the size width and height to match the size of the image
            action audio_door, Jump("corridormc")
            at hover_navigation
        button:
            xpos 772
            ypos 320
            if android_navigation:
                add "hallsecond_middledoor_android"
            else:
                add "hallsecond_middledoor"
            mouse "button"
            xysize (176, 331)     # to do: adjust the size width and height to match the size of the image
            action Jump("check_dineeroom")
            at hover_navigation
        button:
            xpos 1393   #move the smoke
            ypos 309    #move the smoke
            if android_navigation:
                add "hallsecond_rightdoor_android"
            else:
                add "hallsecond_rightdoor"
            mouse "button"
            xysize (88, 375)     # to do: adjust the size width and height to match the size of the image
            action Jump("check_corridorsecondright")
            at hover_navigation
        button:
            xpos 1490
            ypos 430
            if android_navigation:
                add "hallsecond_stair_android"
            else:
                add "hallsecond_stair"
            mouse "button"
            xysize (331, 496)     # to do: adjust the size width and height to match the size of the image
            action Jump("hallsecondstair")
            at hover_navigation

image hallsecond_leftdoor:
    on idle:
        xalign 0.5
        yalign 0.5
        size (88, 552)
    on hover:
        xalign 0.5
        yalign 0.5
        "smoke_hover"
        size (88, 552)

image hallsecond_leftdoor_android:
    on idle:
        xalign 0.5
        yalign 0.5
        "empty_android"
        size (88, 552)
    on hover:
        xalign 0.5
        yalign 0.5
        "smoke_hover"
        size (88, 552)



image hallsecond_middledoor:
    on idle:
        xalign 0.5
        yalign 0.5
        size (220, 441)
    on hover:
        xalign 0.5
        yalign 0.5
        "smoke_hover"
        size (220, 441)

image hallsecond_middledoor_android:
    on idle:
        xalign 0.5
        yalign 0.5
        "empty_android"
        size (220, 441)
    on hover:
        xalign 0.5
        yalign 0.5
        "smoke_hover"
        size (220, 441)


image hallsecond_rightdoor:
    on idle:
        xalign 0.5
        yalign 0.5
        size (110, 496)
    on hover:
        xalign 0.5
        yalign 0.5
        "smoke_hover"
        size (110, 496)

image hallsecond_rightdoor_android:
    on idle:
        xalign 0.5
        yalign 0.5
        "empty_android"
        size (110, 496)
    on hover:
        xalign 0.5
        yalign 0.5
        "smoke_hover"
        size (110, 496)


image hallsecond_stair:
    on idle:
        xalign 0.5
        yalign 0.5
        size (441, 662)
    on hover:
        xalign 0.5
        yalign 0.5
        "smoke_hover"
        size (441, 662)

image hallsecond_stair_android:
    on idle:
        xalign 0.5
        yalign 0.5
        "empty_android"
        size (441, 662)
    on hover:
        xalign 0.5
        yalign 0.5
        "smoke_hover"
        size (441, 662)





Here the code for the tooltips:

screen tooltip_display_load(text_data,xpos_data,ypos_data):
    zorder 999
    layer "inventory"
    if persistent.tooltip == True:
        text text_data outlines [ (absolute(1.0), "#212121", absolute(0.0), absolute(1.0)) ] xpos xpos_data ypos ypos_data at tooltip_fade

**Comment by renpytom** [comment]
I need you to upload the game somewhere, including the full source code and images, so I can just run it. What you think is important may not be what's causing the problem, and so I need to recreate it here so I can determine what's going wrong.  I'd also like it if you could add a jump from start to just before the problem occurs, so I don't have to play through the game dozens of times to gain more information about the problem. 

You can email the link to python@bishoujo.us. 

I want to help, but I do need the actual game, not just a description of the problem.

**Comment by Bobyteal** [comment]
Understood, and appreciated, I'll upload the source package and send it then.

**Comment by Bobyteal** [comment]
Sorry, I got it ready and tried to send but got this warning and the mail didn't go through sent, first time I see this and not sure what to do:
550 5.1.1 <[python@bishoujo.us](mailto:python@bishoujo.us)>: Recipient address rejected: User unknown in virtual alias table

**Comment by renpytom** [comment]
Ah, sorry about that - it's pytom@bishoujo.us

**Comment by renpytom** [comment]
This is fixed. 

I will say that your tooltip system, which shows screens and then relies on unhover to hide them, seems to require a lot of resources. With this fix, it's behaving the same way it does in 7.4.10, but that still means that tha Ren'Py is re-evaluating screens once per frame when the mouse is over a tooltip-ed button. 

The problem is basically that the game repeatedly showing screens like tooltip_display_menu. That repeated showing stresses the focus system in a way that it wouldn't be stressed if the tooltips were part of the screen itself, shown and hidden with SetScreenVariable and the if or showif statement.

**Comment by Bobyteal** [comment]
Thanks a lot for taking a look at this and well understood for the tooltips (I will try to refactor this in the future as you explained here), I tried the compromise and it seems to work at first then unfortunately the fix stops working as soon as I grab the bottle in the scene, I recorded a very short video to be able to show this:

https://streamable.com/ju59pn


There is another probably unrelated change in behaviour that I noticed: when I enable the toggle skip in the top right, in older versions this will stay enabled until the user disables it. This offers great comfort in a point and clicks logic, since he doesn't have to reactivate the fast forward every time he goes to a new room or a new location. Currently, the change in behaviour forces the user to reactivate fast forward every time there is some of the text appears, whereas before it remained activated even though there was no text on the screen. If an user want to skip through a game that plays a bit like this, he would have to toggle skip a thousand times.

**Comment by Bobyteal** [comment]
For the fix supposedly not working it's totally possible that I messed up the commit, so I'll try again with the nighty in any case.

**Comment by renpytom** [comment]
Reopening, as I think it's still broken... not sure why I thought the fix worked.

**Comment by Bobyteal** [comment]
That's working perfectly. 👍
There are other small issues that I have noticed that were not present in 7.4.10 (not related at all to what has just been fixed), should I post them here, or open a new issue for each one (I spotted two for the time being). 
Thank you.

**Comment by renpytom** [comment]
Please file new issues for new issues. :)
