### ISSUE TITLE
Allow build.package generate rpa

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3625]
I don't know if I'm doing something wrong, or if it's a bug, but shouldn't it generate an rpa?
```
build.archive("DLC", "all")
build.classify('game/DLC/**.**','DLC')

build.package("DLC", "zip", "DLC", dlc=True)
```
Output zip: 
![imagen](https://user-images.githubusercontent.com/36079551/172497066-575de194-332c-4b5f-9e57-d45c089b2dda.png)

**Comment by raspberry-soft** [comment]
My guess is "DLC" is declared as an archive part of the "all" file list.
build.package takes a file list, not an archive. That is why it does nothing.

**Comment by renpytom** [comment]
This is just a mistake in how to do DLC in Ren'Py. 

The two parameters of build.archive are the name of the archive, and the file list to put it in. (The all list is included in all downloads.) 

You probably want: 

```renpy
init python:
     build.archive("DLC", "dlclist")
     build.classify('game/DLC/**.**','DLC')

build.package("DLC", "zip", "dlclist", dlc=True)
```

**Comment by Neyunse** [comment]
Oh, thanks Tom!
