### ISSUE TITLE
Document how to mantain code for R7 & R8 in the same project

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3635]
I think many devs will go back and forth between Ren'Py 7 and 8 for a while, adding and checking out the new features but still keeping the R7 project (e.g. for web builds).

I think an easy way to keep the same code working with the new features will need to be documented on the Py3 section of the doc and changelog.

I've been doing this, maybe there's a better way.

```
init python:
    if not PY2:
        config.preserve_volume_when_muted = True
```
I found out R8 new preferences variables do not crash on R7 but config variables will.

This may speed up the transition as people may fear going to R8 means crashing on R7 and for now R7 is still necessary at least for web. A counter argument could be this leads up to users staying in R7 too long.

**Comment by Booplicate** [comment]
> I found out R8 new preferences variables do not crash on R7 but config variables will.

I thought r7 and r8 share the same config vars? Are you sure it's not a bug?
`preserve_volume_when_muted` is mentioned under both 8.0 and 7.5, so I'd think it should work on either.

**Comment by raspberry-soft** [comment]
You are right, my bad. I was going back and forth with 7.4.11 and 8.0 for a while. But with 7.5 this won't be an issue.  I don't know if this is still a valid suggestion so I'm closing it.
