### ISSUE TITLE
[7.5] Change of behaviour that can lead to some crashes, using functions that used to work in the past

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#3636]
Not sure what has changed but here is a function that used to work on Renpy <7.5 and seems to lead to renpy crashing now:

```
init python:
    def _shake_function(trans, st, at, dt=.5, dist=256): #dt is duration timebase, dist is maximum shake distance in pixel
        if st <= dt:
            trans.xoffset = int((dt-st)*dist*(.5-renpy.random.random())*2)
            trans.yoffset = int((dt-st)*dist*(.5-renpy.random.random())*2)
            return .01
        else:
            return None

transform shake(dt=.4, dist=128):
    function renpy.curry(_shake_function)(dt=dt,dist=dist)
```

While used in that manner anywhere (the actual values fed to it don't matter):
```
    show layer master:
        shake(dt=1.0, dist=15)
        repeat
```
(the use is to shake the screen repetitively every *insertime* to add some dynamism to certain scenes)

https://streamable.com/04hbux
(left is 7.4.11, right 7.5)

**Comment by Org-gith** [comment]
I have tried:
```
                show layer master:
                    shake(dt=1.0, dist=15)
                    pause 1.0
                    repeat
```
It seems to work, so I think the change of behaviour is that before it would wait that the function is finished before repeating it again, and now it doesn't wait anymore, it will just repeat shake(dt=1.0, dist=15) without waiting, crashing the application.

**Comment by Gouvernathor** [comment]
Maybe related to #3428/#3514

**Comment by Andykl** [comment]
This is regression introduced in 0252718c1bf2ddacdac6b76d26538fe4d810a746
