### ISSUE TITLE
[Suggestion] Support Apple Silicon natively

### ISSUE THREAD

**Issue by gelvinp** [renpy/renpy#3637]
While ren'py games *do* run fine through Rosetta 2, I have noticed that ren'py games are the only thing that has managed to make my arm mac become hot to the touch and kill my battery, so it's definitely not optimal. Activity Monitor shows ren'py games regularly exceeding 100% CPU utilization and energy impact. With the move to a more modern python version, maybe it would be possible to build for AS natively.

**Comment by renpytom** [comment]
That's on my todo list. I'm going to close this now so I don't forget to close it later, but it's certainly in my plans - I have an M1 mac here.
