### ISSUE TITLE
Failed to execute 'stop' on 'AudioScheduledSourceNode error in Web version.

### ISSUE THREAD

**Issue by AdamSmasher1** [renpy/renpy#3652]
When building games with web version 7.5.0

index.js:1 Uncaught DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.
    at stop_playing (eval at _emscripten_run_script)

It happens when using  **$ renpy.music.play()**

The error is reproduced whether or not **$ renpy.music.stop()** 
or 
**stop sound
stop music**

**Comment by renpytom** [comment]
Which web browser is this?

**Comment by AdamSmasher1** [comment]
Google Chrome
