### ISSUE TITLE
ANGLE2 visual glitches

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#3654]
Windows 11
Ren'py 7.5.0.22061301n

When the Angle2 renderer is enabled, some UI components exhibit strange distortions.

Tested on AMD and Nvidia GPU, and both appear to be affected.

(Menu background has incorrect size)
![image](https://user-images.githubusercontent.com/45672224/173437331-fc18c392-e705-4541-af20-ed6aedae4827.png)

(Misaligned slider thumbs, and button backgrounds)
![image](https://user-images.githubusercontent.com/45672224/173437544-ba625204-16cb-4ed2-9506-e50acdb95953.png)

**Comment by renpytom** [comment]
This was introduced by yesterday's changes, though it's not clear how.
