### ISSUE TITLE
[7.5] Change of behaviour for rollback that can lead to some problems

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#3662]
Using rollback prior to 7.5 make you go back to the last bit of dialogue/text you have encountered. This means that in a hybrid VN, it jumps you from an important bit to another important bit and skips the part where you are 'moving' around and there is no text, which is great because these parts aren't that relevant since you could go back to them by simply using the hotspots/map to go back to where you came from and this wouldn't take more time than using the rollback button. 
Now, in 7.5 the rollback button makes you go back in time even though there was no text displayed at the time or anything important happening, it's not as 'smart' as it used to be in a way.

Here is a comparison video to showcase the change (left 7.4.10, right 7.5  |  the left top arrow triggers the rollback):
https://streamable.com/gyt3bk
At the very end of this video, the new rollback also freezes the screen and hotspots on the watermill scene, the only way to solve this here is to reload a save or restart the game.

Here is another instance of this problem captured specifically:
![gif6](https://user-images.githubusercontent.com/78823063/173693969-a9f441c3-bd36-469d-8f67-1364a13790f8.gif)
(it freezes on the notify screen with modal True)

**Comment by renpytom** [comment]
While I don't know what's wrong with your game in particular, there was a change to allow rollback pauses that don't have timeouts. That seems like a reasonable place to roll back to, and so you should adjust your game so that it works with such rollback points. 

(I don't know why a notify screen should be modal like this, but if you can't just click to dismiss it, that's a problem.)

**Comment by Org-gith** [comment]
I can adjust by putting new flags on every locations and micro manage the new behaviour but by default the old behaviour was superior in my opinion since it would rollback only from text to previous text which made it more effective and prevented the bugs reported here.
At the end of the video the new rollback freeze all the navigation hotspots on the screen (so you have to reload the game), and in the gif the modal notify screen is supposed to disappear after 2 secs automatically but it never does here, after the rollback you get yourself stuck because the notify screen just get stuck which isn't normal, all these issues don't happen with the old behaviour since in the past the rollback would only go from text to text and prevent all of this from potentially happening.

**Comment by renpytom** [comment]
Do you have a short example of this? I want to at least look.

**Comment by Org-gith** [comment]
With further testing, the common denominator is that it seems to happen when I rollback into a modal screen, the tricky part is that the issue doesn't always happen, but when it happens it will happen reliably at the same moment, the problem is always the modal screen getting 'frozen'. 
I have to be honest I don't think I would be able to actually create a brand new template project that mimics the issue reliably, since it seems to work fine most of the time and I'm able to pick out those individual moments where it stops working just because the game is actually long enough to have plenty of opportunities to stumble upon it...
I would be able to pick out and make individual saves for a bunch of those moments but I'm not sure if that's something you are okay with, please let me know what could work for you. In any case, somebody might have a simpler example at one point and we could dismiss the issue if that sounds better.
