### ISSUE TITLE
[Feature Request] Forward all matching keyword args in an ATL transform to the Transform

### ISSUE THREAD

**Issue by morbil** [renpy/renpy#3687]
So, I have a sort of "make this code look neater" bent brewing, and I'm running into a snag. Let's say I have a simple template ATL transform for a transition:

```renpy
transform ShaderTrans(shader, delay=1.0, warper="linear", old_widget, new_widget):
    delay delay
    Model().texture(old_widget).child(new_widget)
    shader shader
    warp warper delay u_time_position 1.0
```
Then I can just make instances like so:
```renpy
define water_dissolve = ShaderTrans(shader="3pood.water_dissolve")
define page_turn = ShaderTrans(shader="3pood.page_turn")
```
And if I want to override the interpolation function I can use:
```renpy
define burn_dissolve = ShaderTrans(shader="3pood.burn_dissolve", warper="easeout_quad")
```
Which works just fine. I can also override it when using it:

```renpy
scene the_image with water_dissolve(warper="easeout_cubic")
```
Which also works.

However, that's only good for uniforms that shaders of that class share, and does not extend in the general case. 

So if I wanted to do:

```renpy
define water_dissolve2 = ShaderTrans(shader="3pood.water_dissolve", u_warp_factor=4.0)
```
That wouldn't work. 

Likewise, I might want to set certain other transform properties that are *not* shader uniforms. 

My suggestion is then simply to take the arguments used to call the transform as the value of those properties in the initial state. I don't know if it would be better to restrict that only to the args not defined in the parameter before the ATL block, or any argument that is in the base Transform property set or those that match the "u_" or "gl_" pattern. 

Then I could write:
```renpy
transform ShaderTrans(shader, delay=1.0, warper="linear", old_widget, new_widget):
    Model().texture(old_widget).child(new_widget)
    warp warper delay u_time_position 1.0
    
define water_dissolve2 = ShaderTrans(shader="3pood.water_dissolve", u_warp_factor=4.0)
```
And everything would work. 

As an aside, being able to register default uniform values per registered shader name might be useful, though I'm not certain (definitely not in place of the setting the uniforms per Transform). 

Likewise just having a `uniforms {dictionary of uniform name:value pairs}` ATL statement might also obviate most of the usefulness of this request.

**Comment by Booplicate** [comment]
Passing in arguments that the transform hasn't been defined with (and doesn't even use within its body) looks like a mistake/bug to me. The last idea might be useful, though.

**Comment by morbil** [comment]
Internally, it's stuffing those properties into dicts/sets anyway, especially since Transform properties can be inherited by the Transforms they replace. In this case, it's just forwarding properties as though they were copied from a previous Transform in that state.

**Comment by Gouvernathor** [comment]
Transforms using arguments whose name match existing properties, like pos or offset for example, are supported and this (the first proposition) would introduce an uncertainty as to how transforms would resolve certain arguments.

**Comment by morbil** [comment]
```
I don't know if it would be better to restrict that only to the args not defined in the parameter before the ATL block, or any argument that is in the base Transform property set or those that match the "u_" or "gl_" pattern.
```
That would certainly be an argument for the former rather than the latter. In this case it would be taking arguments NOT defined in the parameter list and trying to match them as Transform properties. So:

```renpy
transform ShaderTrans(delay=1.0, warper="linear", old_widget, new_widget):
    delay delay
    Model().texture(old_widget).child(new_widget)
    warp warper delay u_time_position 1.0
define water_dissolve2 = ShaderTrans(shader="3pood.water_dissolve", u_warp_factor=4.0)
```
What would be the knock-on effect here?

**Comment by renpytom** [comment]
I don't plan to add this to Ren'Py. 

What probably will happen is:

```
transform mytransform(**properties):
     properties properties
```

But that's a feature for an eventual ATL redesign.

**Comment by morbil** [comment]
I'm fine with that. That's basically what I asked for, just opt-in rather than the default which I'm fine with.
