### ISSUE TITLE
Using the "wipeleft" transition leaves a line at the right of the screen [Renpy 8.0] [minor]

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#3696]
This happened to me in 7.4 and 8.0.

1) Resolution 1280 x 720
2) show a full screen background
3) show another full screen background with wipeleft transition
4) at the right side of the screen a line occurs (looks like some pixels of the first background that are left behind)
5) after the transition the line disappears

I assume cropping isn't properly calculated before wiping?

(wiperight doesn't produce an issue)

**Comment by Gouvernathor** [comment]
Can reproduce in a 1920x1080 game with :
```rpy
image red = "#f00"
image green = "#0f0"

label wipetest:
    show red
    pause
    show green
    with wipeleft
    pause
```
A small colon of red pixels are visible at the right border during the transition.
