### ISSUE TITLE
the result of os.path.abspath(__file__) is difference between Ren'Py 7 and 8

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#3700]
I typed "os.path.abspath('.')" on the console in Ren'Py.

Ren'Py 8 returns 'E:\\Soft\\renpy'
Ren'Py 7 returns 'D:\project_dir\test\game'

**Comment by Gouvernathor** [comment]
Can't reproduce your second example.
In my case, in both the launcher and a booted game, in both the latest 7.5 and 8.0, `os.path.abspath(".")` returns the same as `config.basedir`

**Comment by renpytom** [comment]
Ren'Py doesn't change the working directory it's given, and that working directory can be different from OS to OS, and it can vary based on how a particular game is launched. That being said, the only difference I'm seeing is that Ren'Py 7 use unicode strings, while Ren'Py 8 uses the str type (which is a unicode string, under a different name).

**Comment by kyouryuukunn** [comment]
Sorry, this is my miss understood.
