### ISSUE TITLE
Different property override behavior between renpy 7.5 and 8.0

### ISSUE THREAD

**Issue by GiannisPapadopoulos** [renpy/renpy#3702]
This (admittedly ambiguous) code:
 ```
screen test_screen():
    text "Hello World" pos (500, 200) align (0.5, 0.5)
```

Leads to `pos(500, 200) anchor(0.5, 0.5)` in the new renpy 7.5 and 
`pos(0.5, 0.5) anchor(0.5, 0.5)` in renpy 8.0

Not sure if that is intentional/expected

**Comment by Booplicate** [comment]
Idk if this is a bug or not, but using `pos` *and* `align` is wrong since `align` also sets `pos`.

**Comment by Gouvernathor** [comment]
https://www.renpy.org/dev-doc/html/atl.html#list-of-transform-properties
"Note that not all properties are independent. For example, [xalign](https://www.renpy.org/dev-doc/html/style_properties.html#style-property-xalign) and [xpos](https://www.renpy.org/dev-doc/html/style_properties.html#style-property-xpos) both update some of the same underlying data. In a parallel statement, only one block should adjust horizontal position, and one should adjust vertical positions. (These may be the same block.) The angle and radius properties set both horizontal and vertical positions."

This behavior wasn't and isn't documented, so if it changed between versions, we wouldn't fix it. However, differences between 7.5 and 8.0 are not supposed to happen, so it may cover a deeper problem.

**Comment by Gouvernathor** [comment]
Actually (contrary to the link in my last message), this concerns style properties and not transform properties. The Style object stores them in a dict called `properties`.
I assume that dict is iterated at some point, and given that the iteration order is documented in python 3 but not in python 2, that could explain the discrepancy.
So, unless a deeper analysis reveals that the problem doesn't come from the dict, I'd say this is fine.

**Comment by GiannisPapadopoulos** [comment]
Feel free to close, I just mentioned it because when this came up on the discord the person encountering it thought the behavior of `pos`  had changed due to python 3 being used (And rewrote it to use xpos, ypos, which coincidentally worked)

**Comment by renpytom** [comment]
This was never a defined behavior, and probably just depended on how Python arranged memory (in 2.7.)
