### ISSUE TITLE
7.5/8.0 discrepancies in screen actions

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3720]
I found a discrepancy, which is most likely linked to #3718 (I discovered it when testing it).
```rpy
screen testor():
    default liz = []
    vbox:
        textbutton "Append" action [Function(liz.append, 0), Function(print, "called")]
        if liz:
            text str(len(liz)) color "#f00"
        showif liz:
            text str(len(liz)) color "#0f0"
```
In the 7.5.0 Release and last nightly, the console prints each an every click, but the texts only appear at and after the *second* click. And, of course, it's offset : the second click shows a 1-length, the third shows 2...
In the 8.0 nightly, it works as I would have intended : each click is still printed, and the texts display the number of clicks.
(I wrote both to be certain : showif and if work seemlessly here, they're identical)

**Comment by renpytom** [comment]
This is fixed by 866bb6ce45ee55fb75215d8fd6e75dafd7bc2e8b and the commits following it.
