### ISSUE TITLE
[Doc] Inconsistent styling in screen_actions.html

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#3723]
![image](https://user-images.githubusercontent.com/26691547/176743271-9c0f2d6d-b7ff-4926-8284-4b595e7eccb8.png)
> This action takes the _layer, _zorder and _tag keyword arguments, which have the same meaning as in the [renpy.show_screen()](https://www.renpy.org/dev-doc/html/screen_python.html#renpy.show_screen) function.

is styled differently and I assume incorrectly for `ShowTransient` and `ToggleScreen`

**Comment by Gouvernathor** [comment]
Fixed by 545aae7a38087caf92e80ba2858e83158a0cb36a, it will show next time the doc is regenerated.
