### ISSUE TITLE
Extend statement doesn't correctly change language settings

### ISSUE THREAD

**Issue by kostek00** [renpy/renpy#3724]
Line to which another line is attached to via extend statement doesn't correctly assign different language settings. I will try to explain it with example.
`tom "It's peanut butter..."`
`extend "and it's delicious!"`

When you progress through the game and first line is extended with second line and you change game language for example from English to Japanese first line will be shown without translation applied while extended one will. It looks like Ren'Py don't apply properly backwords translation.

Edit: I checked multiple extends one after another and it seems like only the latest properly changes language.

I'm using Ren'Py version 7.5.

**Comment by Gouvernathor** [comment]
As far as I can see, this is expected. Unless some previous version of renpy included that feature (I very much doubt it), it won't be implemented.
We could possibly document this as a limitation of `extend` in the doc, but other than that it's unlikely this will be implemented.
