### ISSUE TITLE
[Idea 8.x / 9.x] Rescale images content

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3726]
Well, this is related to this #2688 issues, maybe this is more complicated to tackle, so this could be expected for Ren'Py 8.x or Ren'Py 9.x. And it's about rescaling the images without having stripes on the sides, more or less this would be a basic example of how it could be tackled.

tkinter Example
```
from tkinter import *

from PIL import Image, ImageTk

root = Tk()
root.title("Title")
root.geometry("1290x720")
root.minsize(width=600, height=600)

root.configure(background="black")


class Window(Frame):
    def __init__(self, master, *pargs):
        Frame.__init__(self, master, *pargs)

        self.image = Image.open("bedroom.png")
        self.img_copy = self.image.copy()

        self.background_image = ImageTk.PhotoImage(self.image)

        self.background = Label(self, image=self.background_image)
        self.background.pack(fill=BOTH, expand=YES)
        self.background.bind('<Configure>', self._resize_image)

    def _resize_image(self, event):

        new_width = event.width
        new_height = event.height

        self.image = self.img_copy.resize((new_width, new_height))

        self.background_image = ImageTk.PhotoImage(self.image)
        self.background.configure(image=self.background_image)


e = Window(root)
e.pack(fill=BOTH, expand=YES)


root.mainloop()
```
PyGame Example

```
import pygame
from pygame.locals import *
pygame.init()
screen = pygame.display.set_mode((500, 500), RESIZABLE)
pic = pygame.image.load("example.png")  # You need an example picture in the same folder as this file!
running = True
while running:
    pygame.event.pump()
    event = pygame.event.wait()
    if event.type == QUIT:
        running = False
    elif event.type == VIDEORESIZE:
        screen.blit(pygame.transform.scale(pic, event.dict['size']), (0, 0))
        pygame.display.update()
    elif event.type == VIDEOEXPOSE:  # handles window minimising/maximising
        screen.fill((0, 0, 0))
        screen.blit(pygame.transform.scale(pic, screen.get_size()), (0, 0))
        pygame.display.update()
``

Based on the width and height (gui.init) you could consume the base size of the image and then rescale the images inside the window.
Also, could define a configuration to include a minimum and maximum window size.
`config.max_window_size` => `define config.min_window_size = (600,600)` = root.minsize(width=600, height=600)
`config.min_window_size` => `define config.max_window_size = (1920,1080)` = root.maxsize(width=1920, height=1080)

**Comment by renpytom** [comment]
Could you explain what you're looking for in words?

**Comment by Neyunse** [comment]
> Could you explain what you're looking for in words?

I think explaining it would be a bit complex, so I recorded a video.  The idea is that the content of the images inside the window is scaled depending on the size of the window. As I said, this could be seen for a future version of 8.x or 9.x, because of the complexity I think it has.

https://user-images.githubusercontent.com/36079551/176800289-fe96a4f8-d218-4b12-b14d-b3b33fe6d976.mp4

Another thing, it is of this idea, is that the window minimum would avoid this, Since the window does not have a defined minimum size, I can scale the window down as much as I want.
![imagen](https://user-images.githubusercontent.com/36079551/176800575-84f711d2-d1af-48bb-b25a-ec99d711d4a5.png)

**Comment by Neyunse** [comment]
And here is the pygame version: https://www.pygame.org/wiki/WindowResizing?parent=CookBook#In%20Pygame%202

The code I put above is from tkinter

**Comment by renpytom** [comment]
I get what you want, which is a variable aspect ratio for games. This is one of those things that perennially on my TODO list, but has yet to get done. I suspect it will be a lot less drastic than what you propose her, probably consisting of a protected inner portion of the screen and then an area outside that that can be offscreen. 

(I'll probably close this in a bit, as I don't think these code examples define how I'd want the feature to work.)
