### ISSUE TITLE
Is Glyph.split needed to be not public?

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#3733]
I would like to allow the user to define his annotate function and register it.
This makes #2318 possible without merging annotate_janome to Ren'Py and also allow other language people to customize linebreaking.

But I can't access Glyph.split from outside of textsupport.pyx. It may be that split is not defined as public.
Is it needed to be not public?

**Comment by renpytom** [comment]
Sure, I've exposed split and ruby.
