### ISSUE TITLE
VPGrid not completely full...

### ISSUE THREAD

**Issue by Savage1969** [renpy/renpy#3737]
Ren'Py 8.0.0.22062402
Windows-10-10.0.19043 AMD64

VPgrid is throwing exception like the old Grid does when multiples of the columns are different. For instance if the VPgrid is set to "cols 3" and, for instance 2 or 4 children are in the grid currently it throws exception: "VPGrid not completely full, needs a multiple of 3 children."

This was never this way before and I can't find a similar issue reported. As noted in the documentation:

- A vpgrid must be given at least one of the cols and rows properties. If one is omitted or None, the other is automatically determined from the size, spacing, and number of children. **_If there are not enough children to fill all cells, any empty cells will not be rendered._**

Apologies if this is already known. Regards.

**Comment by Gouvernathor** [comment]
This is intended behavior that VPGrid behaves like Grid in that regard, as noted [in the changelog](https://www.renpy.org/dev-doc/html/changelog.html#boxes-grids-and-vpgrids). Look for the related [config property](https://www.renpy.org/doc/html/config.html?highlight=underfull#var-config.allow_underfull_grids) for an override. As the changelog says, the `allow_underfull` property can also be given ponctually.
Thanks for the documentation tip, it will be updated.

**Comment by Savage1969** [comment]
It was never like this before, right? So the default is to not allow underfull? Thank you for your prompt response.

**Comment by Gouvernathor** [comment]
That's right, the default is to be strict, like Grid always was (I think ?).

**Comment by Savage1969** [comment]
VPgrid's `allow_underfull` property doesn't seem to be working as expected. Can anyone confirm?

**Comment by Gouvernathor** [comment]
What does it give you ?

**Comment by Savage1969** [comment]
Same exception error: "VPGrid not completely full, needs a multiple of [X] children."

**Comment by Gouvernathor** [comment]
```rpy
screen vptest():
    vpgrid:
        cols 3
        allow_underfull True
        for k in range(5):
            add Solid(Color(hsv=(k/5, 1., 1.)), xysize=(200, 200))
```
This works for me in 8.0, and only yield the exception when commenting the allow_underfull line. Maybe you have several vpgrids you need to patch ?

**Comment by Savage1969** [comment]
Close the issue, I didn't note to assign the property to True `allow_underfull True`. My apologies. It's all good. Thank you for your time, sincerely.

**Comment by Gouvernathor** [comment]
It's fine.
