### ISSUE TITLE
intern known commonly reused strings

### ISSUE THREAD

**Issue by Numerlor** [renpy/renpy#3759]
Strings like the `who` attribute of a Say node may have tens of thousands of instances with the same content, interning them with `sys.intern`/`intern` would ensure there is only ever one string with the given content stored where the itern is applied

**Comment by Numerlor** [comment]
Are we thinking of the same thing?
```py
>>> node
<renpy.ast.Say object at 0x0000000005efbcc0>
>>> type(node.who)
<class 'str'>
```
https://github.com/renpy/renpy/blob/fab154eacea35c999941e65d4a976a83b8fdfb32/renpy/ast.py#L804-L809

From the script I can also think of With transitions and image names to be good candidates to be interned, at least for some case like `black` or `None` transition expression

**Comment by renpytom** [comment]
Huh. Let me check this out, then - the stripping might be removing the PyExpr-ness of it.

What are the statistics for your game's script?

**Comment by Andykl** [comment]
I've made that script to count what amount of RAM takes each kind of ast.Node
```
init python:
    def profile_script():
        from renpy.memory import write, memory_log
        import time
        import collections
        import types
        import gc

        write("=" * 78)
        write("")
        write("Memory profile at " + time.ctime() + ":")
        write("")

        roots = [ ]
        for o in renpy.game.script.namemap.values():
            key = f"{o.__class__.__module__}.{o.__class__.__name__}"
            if isinstance(o, renpy.ast.UserStatement):
                key += f" {o.get_name()}"

            roots.append((key, o))

        seen = set()

        # A list of (name, object) pairs.
        worklist = [ ]

        # A map from root_name to total_size.
        size = collections.defaultdict(int)

        ignore_types = (types.ModuleType, type, types.FunctionType)

        for name, o in roots:
            id_o = id(o)

            if id_o in seen:
                continue

            seen.add(id_o)

            if isinstance(o, ignore_types):
                continue

            worklist.append((name, o))

        # For speed, cache name lookups.
        getsizeof = sys.getsizeof
        get_referents = gc.get_referents
        worklist_append = worklist.append

        remaining = len(worklist)
        while worklist:
            name, o = worklist.pop(0)
            remaining -= 1

            size[name] += getsizeof(o)

            for v in get_referents(o):
                id_v = id(v)

                if id_v in seen:
                    continue

                seen.add(id_v)

                if isinstance(v, ignore_types):
                    continue

                worklist_append((name, v))
                remaining += 1

            renpy.renpy.log.real_stdout.write(f"\rRemaining {remaining} items.")

        renpy.renpy.log.real_stdout.write("\n")

        usage = sorted((v, k) for (k, v) in size.items())

        # The total number of bytes allocated.
        total = sum(i[0] for i in usage)

        for size, name in usage:
            write("{:13,d} {}".format(size, name))

        write("-" * 13)
        write("{:13,d} Total AST memory usage (in bytes).".format(total))
        write("")

        memory_log.file.flush()
```
You can use that to profile how much RAM Say nodes takes.

**Comment by Numerlor** [comment]
I don't have a game myself, but grabbing a random one that had a plaintext script, keeping track of all instantiated say nodes, there were 26500 of them with 84 unique who strings (excluding None). 
Counter through their `__sizeof__` method, together all the strings were 1_131_126 bytes. Only counting the size of each unique string gives 5_244 bytes

**Comment by Andykl** [comment]
I do have a game and top 5 Node kinds are
```
   10,900,059 renpy.ast.Python
   18,517,900 renpy.ast.EndTranslate
   38,052,957 renpy.ast.Translate
   40,596,096 renpy.ast.Say
  147,824,616 renpy.ast.Screen
```
I want to optimise it because of low-end Android devices, and as you can see, there are more important things to do (screens optimisations, lazy translations, etc.). Your optimisation will save 1 or 2 megabytes, which is good and probably will happen, but I think is less important.

Anyhow, thank you for your advice, it is possible that this optimisation will be used.

**Comment by Numerlor** [comment]
It is only a small memory optimization, but should also be trivial to implement in places where it would bring a benefit

**Comment by mal** [comment]
Are these numbers coming from Python 2 or 3? Python 3 does a fair amount of implicit interning automatically which may make such a change significantly less advantageous, at which point we may need to ask if it's worth it to benefit the 7.x branch with the clock on it already ticking.

src: https://stackabuse.com/guide-to-string-interning-in-python/#implicitinterning

This isn't intended to be for or against the suggestion, just highlighting something we should consider while considering it.

**Comment by Numerlor** [comment]
Afaik, for dynamically created strings, only single letter latin1 strings will be cached and won't be unique, other than that the optimatizations python applies is for attributes and constants

**Comment by renpytom** [comment]
Done, for simple cases (Say.who in many case, and names like image attributes).
