### ISSUE TITLE
[internal] fragment RawMultipurpose in several specialized classes

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3762]
Compiling (at runtime) an ATL line like `xpos 4 ypos 6` should not require figuring out each time whether the ATL statement changes the child, or includes another ATL transform, or warps something or other... That should ideally be determined at parse time, by converting the RawMultipurpose into a specialized class.
RawMultipurpose should still exist if only for pickling reasons, but I don't think we can afford to simplify its code without forcing older games to recompile (which isn't always possible).

**Comment by renpytom** [comment]
This is almost certainly not worth it before ATL2.
