### ISSUE TITLE
Composite function causes alpha seams at arbitrary display resolutions

### ISSUE THREAD

**Issue by MapAnon** [renpy/renpy#3767]
When using 2 images cut perfectly in half, and then using Composite() to put them together, the result is seamless in the project's internal resolution, like 1920x1080. At arbitrary display resolutions, there's a pixel thick alpha seam between the 2, and while it can be kinda fixed by fiddling the resolution to be at fixed sizes, it doesn't make it less annoying. Importantly, Flatten() doesn't help this issue.

Full screen
![Illustration](https://user-images.githubusercontent.com/52191957/179307855-2b902f4d-30dd-4f92-8501-4595667fb21a.png)

Windowed
![Capture](https://user-images.githubusercontent.com/52191957/179307867-e3c41b4d-5cf0-46a1-99a2-a735cfca5a6d.PNG)

**Comment by renpytom** [comment]
Can you grab the log.txt when this happens, as well as the window and the images? That will help track this down.

**Comment by MapAnon** [comment]
When you say window, did you mean a screenshot of the game's window?
Also, the test images in question have the dimensions of my game's sprites (why there's so much empty space), which work fine individually.
![Illustration](https://user-images.githubusercontent.com/52191957/179318728-ef8d674d-9995-461f-903f-832523b2475d.png)
[log.txt](https://github.com/renpy/renpy/files/9124439/log.txt)
![white1](https://user-images.githubusercontent.com/52191957/179318741-0cc562d2-29af-4c4b-9539-3e2ad054f9d9.png)
![white2](https://user-images.githubusercontent.com/52191957/179318747-4c7c4321-ef67-4518-9876-71cb6bedb8d3.png)

**Comment by MapAnon** [comment]
I realize now that it works perfectly fine if I were to cut the images in half resolution wise, since then the blending wouldn't try to blend with the surrounding alpha values.
But then I'm wondering why the Flatten() function doesn't work in this case. It works just fine when manipulating the alpha value, but that seam still exists like they're still separate images.

**Comment by renpytom** [comment]
Sorry it took a while, but this is what setting the new-ish drawable_resolution=False argument to flatten is for. 

What's happening is that in most cases, the displayables are scaled down, then drawn - and when scaled like that, you don't get perfect overlap. With drawable_resolution=False, the displayables are drawn, then scaled - and the artifact goes away.
