### ISSUE TITLE
Problem with the sound in the screens

### ISSUE THREAD

**Issue by REIDEUS** [renpy/renpy#3770]
Not sure if this is a problem or a feature. 
Trying to add music only for main menu screen via renpy.music.play and using SetLocalVariable/SetScreenVariable constantly restarts music. Also the renpy.music.play and renpy.music.stop commands work in other screens that are not called and in actions of buttons that are not pressed.

**Comment by renpytom** [comment]
This is probably a bug in your code, since you should be using Play rather than renpy.music.play. Do you have an example of what you're doing?

**Comment by REIDEUS** [comment]
> 
Tried Play, just like renpy.music.play restarts the music

```
screen main_menu():
    tag menu

    on "show" action Play("bgsfx", "audio/sounds/umilse_016.ogg")
    #on "show" action renpy.music.play("audio/sounds/umilse_016.ogg", "bgsfx", True, if_changed=True)
    #on "show" action renpy.music.play("audio/sounds/umilse_016.ogg", "bgsfx", True)

    default skip = False

    key ["dismiss", 'skip'] action SetLocalVariable("skip", True)
    ...
```

**Comment by REIDEUS** [comment]
It helped me like this.
```
on "show" action Play("bgsfx", "audio/sounds/umilse_016.ogg")
on "replace" action Play("bgsfx", "audio/sounds/umilse_016.ogg")
on "replaced" action PauseAudio("bgsfx", True)
```
Is it possible to use fadein and fadeout for Play and StopAudio, if not, is it planned to implement the future?

**Comment by Gouvernathor** [comment]
According to this https://www.renpy.org/doc/html/screen_actions.html#audio-actions it seems that you can pass fadeout kwargs to Play and that it will be passed to renpy.music.play afterwards.
It's not documented in the case of PauseAudio, and I don't think we could easily support it.

**Comment by REIDEUS** [comment]
Thank you all for help
