### ISSUE TITLE
Fixed "ctc" indicator is drawn behind the say screen / dialogue window [8.0.1]

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#3772]
How to reproduce:

* Create a Character using ctc_position="fixed" (instead of "nestled" or "nestled-close")
* Position the "ctc" image in the area of your dialogue window
* Give the dialogue window a background

Result: the "ctc" icon will be drawn behind the dialogue background, so it is never visible to the player.

**Comment by m-from-space** [comment]
Hey renpytom, are you sure this fixes this specific bug? Because this one is about the ctc drawn behind a dialogue window (meaning the z order is wrong). It sounds like a fix to this bug I reported though: https://github.com/renpy/renpy/issues/3774

Sorry if I am wrong about it, but the solution you linked doesn't sound like it refers to the bug above. :)

**Comment by renpytom** [comment]
That was the wrong issue. 

I've tried this in a newly created game, and I'm not seeing this problem. Here's my example:

```renpy
define e = Character(
    "Eileen",
    image="eileen",
    ctc=Solid("#f00", xysize=(200, 200), align=(0.5, 1.0)),
    ctc_position="fixed")

label start:

    scene bg washington

    e "This is a lot of text to demonstrate that the CTC indicator is on top of it."

    return
```

And the result:
![screenshot-2022-14](https://user-images.githubusercontent.com/379804/179657763-8b882e9b-a854-48b7-827d-5ec1be79af9e.png)

Is it possible your say screen is at a non-zero zorder? The default ctc screen is at zorder 0, and you'll need to define a custom ctc screen if you'd like something higher than that.

**Comment by m-from-space** [comment]
Yes, my say() screen is at non-zero zorder. Setting it to 0 removes the issue. But I am still confused, since the Renpy documentation doesn't state anything and also writes:

_If "fixed", the indicator is added to the screen, and its position is controlled by the position style properties._

To me this sounds like the ctc is added to the say screen and therefore should be visible. You talke about a "ctc" screen, but what screen is that?
