### ISSUE TITLE
Text keeps jumping around on {w=} and {p=} waits [8.0.1]

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#3774]
Text that is drawn using slow_cps (as part of the dialogue window most commonly) jumps around at the end of a text field after a {w} or {p}-tag occurs. The reason for this behavior is probably the ctc-pause indicator. But even if this indicator is set to ctc-pause = Null() as part of a Character() creation, this happens.
My assumption is that the ctc_pause image is not zero pixels wide, but it should be. So in some cases on wait times, the pixels are added to the text, which causes a line break to occur if the end of the maximum text width is reached. After the pause, the non-zero-width indicator is removed and the last words jumps back to the former line of the dialogue.

For me as a creator and player his is very annoying, since it interrupts the flow of the game.

Please don't add anything to the text if ctc-pause is Null(). :)

**Comment by Gouvernathor** [comment]
Would passing None instead of Null() work, in your case ?

**Comment by m-from-space** [comment]
Oh sorry, I'm actually referring to **ctc_timedpause** and {w=} and {p=}, not ctc_pause, since the documentation states:

_"When None, this takes its default from ctc_pause, use Null() when you want a ctc_pause but no ctc_timedpause."_

So None does not work, since then ctc_timedpause will be ctc_pause, which in my case is a visible ctc indicator image. On {w=} and {p=} I don't want an image though. It's just a little pause and then text resumes. Not need for the player to get distracted by a sudden ctc image.

(I use "nestled-close" by the way.)

**Comment by m-from-space** [comment]
Setting both ctc_pause and ctc_timedpause to None does not have the jumping effect. But that's the reason why I made this ticket: Null() should result in the same behavior, since nothing should be added to the text, right?

**Comment by Gouvernathor** [comment]
Yep, makes sense. We'll look into that.
