### ISSUE TITLE
Mute audio when the game window is not focused, not only minimized

### ISSUE THREAD

**Issue by Victorius-Astral** [renpy/renpy#3777]
The new feature to mute audio when the game is minimized is cool, truth be told I was already sick of having bgm on when someone sent me something with the audio or whatever. I think it's more useful to developers than players as the amount of time we spend with the game launched is usually a lot. 

It would be cool to expand this setting or add a second one - to mute audio while the game window is not focused. So when we or players click onto Discord, browser, desktop, or whatever, the game sound disappears, so we don't need to quit the game or at least mute/unmute it often.

**Comment by Org-gith** [comment]
I was interested in that functionality as well, it seems to work fine (been using it for a few days), in core.py, just added the extra condition that was mentioned in another post somewhere on the GitHub:
```
                    if not renpy.game.preferences.audio_when_minimized:
                        if (not pygame.key.get_focused() or not pygame.display.get_active()) and not self.audio_paused:
                            renpy.audio.audio.pause_all()
                            self.audio_paused = True
                            renpy.store._audioispaused = True
                        # If the window had not gone inactive or has regained activity
                        # unpause the audio
                        elif (pygame.key.get_focused() or pygame.display.get_active()) and self.audio_paused:
                            renpy.audio.audio.unpause_all()
                            self.audio_paused = False
                            renpy.store._audioispaused = False
```

It is still using "renpy.game.preferences.audio_when_minimized" as the trigger, so not really 'presentable'.
