### ISSUE TITLE
Some tutorial sample codes aren't shown correctly

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#3780]
Some tutorial sample code aren't shown correctly.

tutorial_quickstart.rpy:99, 159, 410
![image](https://user-images.githubusercontent.com/1556311/179705044-ba868090-5b55-48bf-b78a-d10b2322f679.png)

v8.0.1.22070801

**Comment by renpytom** [comment]
This is working for me here. 

Can you drop to the console (shift+O), and then try:

```
"characters" in examples
```

to see if the character was found? This works by scanning the file on disk for special comments.

**Comment by kyouryuukunn** [comment]
This doesn't happened when game was launched in English.

1. Launch Tutorial and change preference to not English language.
2. quit game
3. launch tutorial again

The result of "characters" in examples is False
