### ISSUE TITLE
Add `help expr` into avaliable console commands.

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#3783]
Right now `help something` is valid command but it just returns default help list. It would be useful if `help expr` would print `expr` signature and/or its \_\_doc\_\_.

**Comment by Andykl** [comment]
To make this work, we need to either include `sysconfig` module because `pydoc` is dependent on it, or patch `pydoc` to strip the only usage of `sysconfig` from the [pydoc source](https://github.com/python/cpython/blob/d348afa15d5a997e7a8e51c0f789f41cb15cc651/Lib/pydoc.py#L492).

After that `help expr` is just `print(pydoc.help(eval(expr)))`.

**Comment by Gouvernathor** [comment]
Done in #3890
