### ISSUE TITLE
IndexError: tuple index out of range, web version upper 7.3.5

### ISSUE THREAD

**Issue by RenpyOnly** [renpy/renpy#3786]
Link to the assembled game, screenshot and saving the moment of the error, reproduced if you click on the magnifying glass in the upper right corner. This problem manifested itself in the web builder, above version 7.3.5

https://drive.google.com/drive/folders/1AckFikpOxwU6tIHvz5jpFRlSyB7t53ev?usp=sharing

**Comment by renpytom** [comment]
This doesn't look like a bug in Ren'Py. It looks like at CustomScreens.rpy line 272, Ren'Py is being asked to display an index. Since that index doesn't exist, you're getting a crash.
