### ISSUE TITLE
[Suggestion] Make `renpy.image()` return the displayable or allow `{image=}` text tag to take displayables as arguments

### ISSUE THREAD

**Issue by Victorius-Astral** [renpy/renpy#3788]
My current problem is still solvable, but at the bottom, I described an unsolvable one (as far as I know by using normal means)

To explain what I want to do - I have displayables (composites of icon + frame) assigned in a dict, I want to use this very icon with an {image} tag for notifications - You got x buff {image}

Currently to do that I need to separately define the same composites with image and in my dict. I could also define them in the image, and use the corresponding name in the dict, but I would rather, if possible keep all things related to this dict in the dict, for ease of reading. I'll probably do a function that does what I suggested to implement.

This is my current problem, it has workaround methods, **but if I wanted to add {image} of auto-generated (random) displayable, I see no way if they're generated after init, like an icon of auto-generated loot with icon + frame, with frame changing on rarity which is RNG on acquiring the item.**

**Comment by renpytom** [comment]
The image tag takes the name of a displayable as an argument. You could always create the displayable, store it somewhere, and pass the store displayable to renpy.image. You could also use an image defined to be a DynamicDisplayable for this, a layered image, or several other approaches. 

I don't think this requires changes to Ren'Py to implement.
