### ISSUE TITLE
Issue with input fields and copy/paste in Renpy 8

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#3791]
The copypaste argument seems to not be functional in Renpy 8.  I created a brand new project, and added this to the label start and it errored out (I removed the commented out text for clarity, though it still fails with it):

```
label start:

    python:

        test_char = renpy.input("Test dialog.", copypaste=True)

    scene bg room

    show eileen happy

    e "You've created a new Ren'Py game."

    e "Once you add a story, pictures, and music, you can release it to the world!"

    return

```

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
    python:
  File "game/script.rpy", line 15, in <module>
    test_char = renpy.input("Test dialog.", copypaste=True)
TypeError: renpy.input() got unexpected keyword argument(s): copypaste

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script
    python:
  File "/Applications/renpy-8.0.0-sdk/renpy/ast.py", line 1111, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-8.0.0-sdk/renpy/python.py", line 1048, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 15, in <module>
    test_char = renpy.input("Test dialog.", copypaste=True)
  File "/Applications/renpy-8.0.0-sdk/renpy/exports.py", line 847, in input
    raise TypeError("renpy.input() got unexpected keyword argument(s): {}".format(", ".join(kwargs.keys())))
TypeError: renpy.input() got unexpected keyword argument(s): copypaste

macOS-10.16-x86_64-i386-64bit
Ren'Py 8.0.0.22061101
test_project_2 1.0
Thu Jul 21 00:32:35 2022
```

Script.rpy attached (after converted to txt):

[script.txt](https://github.com/renpy/renpy/files/9156161/script.txt)

**Comment by Neyunse** [comment]
From my side it works, I see you are using version 8.0.0. Try version 8.0.1

**Comment by Neyunse** [comment]
Another thing, the 'copypaste' argument is not necessary, as it defaults to True.

The correct use would be
```
label start:

    python:

        test_char = renpy.input("Test dialog.", copypaste=False)
```

**Comment by HorBro38** [comment]
I've updated to 8.0.1 as recommended and I no longer get a crash, but with the argument = True or without it at all I still can't paste into the field.

**Comment by Neyunse** [comment]
> I've updated to 8.0.1 as recommended and I no longer get a crash, but with the argument = True or without it at all I still can't paste into the field.

This sounds like a MacOS thing, when I implemented it I tested it on Linux and Windows, it worked correctly.

**Comment by renpytom** [comment]
Thanks for figuring out this was a mac thing.

**Comment by HorBro38** [comment]
I can confirm that as of the 7-28 nightly build this is fixed.  Thanks for the quick resolution!
