### ISSUE TITLE
Docs code example issues

### ISSUE THREAD

**Issue by JSearUK** [renpy/renpy#3797]
Any spelling errors I find that would cause the example to throw an exception, I'll put in here, as and when I find them.

https://www.renpy.org/dev-doc/html/config.html?highlight=config.python#var-config.save_json_callbacks
```py
init python:
    def jsoncallback(d):
        d["playername"] = player_name

    config.save_json_callback.append(jsoncallback)
```
Should be:
```py
    config.save_json_callbacks.append(jsoncallback)
```

**Comment by renpytom** [comment]
Thank you, this sort of thing is very valuable. This will be fixed in 8.0.2. If you can file one issue per problem (or related group of problems), I'd appreciate it, as it makes tracking the fixes easier.
