### ISSUE TITLE
Jump with arguments

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3800]
Allow `jump` to take arguments akin to `call`. I'm not sure why `jump` can't do that, I had about 5 cases where I needed that, but had to use some crutches instead.

This is generally useful when you want to have some local variables, but you don't want to increase call stack. I've seen a hack which allowed to jump with args, but a native solution provided by renpy would be better.

**Comment by renpytom** [comment]
Nope. It doesn't make sense to do this - you can just assign the arguments, then jump. Call's different, because the arguments become dynamic variables that are reset on a return.

**Comment by Booplicate** [comment]
> you can just assign the arguments, then jump

But that makes the whole thing janky.

```renpy
label some_dlg_here:
    "hello"

# I have jump to this label from a few other places, too
label define_vars_here:
    $ var_a = "a"

label actual_code_here:
    call screen test(var_a)
    if _return == "repeat":
        jump define_vars_here

    return
```

Except in my code there's much more variables, and having extra labels doesn't help readability or maintenance. I *could* use `call`:
```renpy
label some_dlg_here:
    "hello"

label actual_code_here(var_a="a"):
    call screen test(var_a)
    if _return == "repeat":
        call actual_code_here

    return
```
But technically it's useless for me, I don't care about returning, I don't want to increase call stack. I actually need *jump*.

So in the end we have a maze because we end up with 20 labels for a simple flow only because `jump` can't accept arguments.
Or we end up using the hack where you can use jump with args, but that's a pain to maintain in the long run.
