### ISSUE TITLE
Sphinx messing up quote marks

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3807]
Simple example : [config.rst](https://raw.githubusercontent.com/renpy/renpy/master/sphinx/source/config.rst) contains this : `.. var:: config.auto_channels = { "audio" : ( "sfx", "", ""  ) }`
Notice how the quotes are normal, all the same, healthy straight double-quote characters.
But go to the [distributed doc page](https://www.renpy.org/doc/html/config.html#var-config.auto_channels) : `define config.auto_channels = { “audio” : ( “sfx”, “”, “” ) }`
This time there are opening and closing quotes, which python will definitely spit out if this is copy-pasted in the game files.

I'm not sure how many roles do this besides `var` (if any).

**Comment by renpytom** [comment]
Fixed by 8b3e05d75ea66070aaa7e552821926df26539206 .
