### ISSUE TITLE
config.main_game_transition not working?

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3808]
Setting `define config.main_game_transition = pixellate` on a default game, does nothing.

Digging into Ren'Py code, I found it's usable with `config.main_menu`. Is there an scenario where this works with screens? Whatever the case is, it should be documented.

**Comment by renpytom** [comment]
Since these haven't been usable since screens came out, I've undocumented config.main_game_transition and config.game_main_transition, and documented that config.intra_transition should be used.
