### ISSUE TITLE
Android build failing, could not resolve all files for configuration

### ISSUE THREAD

**Issue by Winthiefow** [renpy/renpy#3811]
> Ren'Py 8.0.1.22070801
> 
> Updating project.
> 
> Creating assets directory.
> 
> Packaging internal data.
> 
> I'm using Gradle to build the package.
> :app:preBuild UP-TO-DATE
> :renpyandroid:preBuild UP-TO-DATE
> :renpyandroid:preReleaseBuild UP-TO-DATE
> :renpyandroid:checkReleaseManifest UP-TO-DATE
> :renpyandroid:processReleaseManifest UP-TO-DATE
> :app:preReleaseBuild FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> > Could not resolve com.danikula.expansion:expansion:1.3.4.
>   Required by:
>       project :app > project :renpyandroid
>    > Could not resolve com.danikula.expansion:expansion:1.3.4.
>       > Could not get resource 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/expansion/1.3.4/expansion-1.3.4.pom'.
>          > Could not GET 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/expansion/1.3.4/expansion-1.3.4.pom'.
>             > Remote host terminated the handshake
> > Could not resolve com.danikula.expansion:license:1.7.0.
>   Required by:
>       project :app > project :renpyandroid
>    > Could not resolve com.danikula.expansion:license:1.7.0.
>       > Could not get resource 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/license/1.7.0/license-1.7.0.pom'.
>          > Could not GET 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/license/1.7.0/license-1.7.0.pom'.
>             > Remote host terminated the handshake
> > Could not resolve com.danikula.expansion:zip:1.2.1.
>   Required by:
>       project :app > project :renpyandroid
>    > Could not resolve com.danikula.expansion:zip:1.2.1.
>       > Could not get resource 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/zip/1.2.1/zip-1.2.1.pom'.
>          > Could not GET 'https://dl.bintray.com/alexeydanilov/apk-expansion/com/danikula/expansion/zip/1.2.1/zip-1.2.1.pom'.
>             > Remote host terminated the handshake
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 3 actionable tasks: 1 executed, 2 up-to-date
> 
> The build seems to have failed.

This looks like the issue reported/fixed here [https://github.com/renpy/renpy/issues/2792](url) but I'm encountering it on the latest version of ren'py, both stable and nightly.
Also tried to redownload and install RAPT just in case, still facing the issue.

**Comment by renpytom** [comment]
This is an error that was resolved in 7.4. I'd suggest reconfiguring your game, and making sure Ren'Py is allowed to update the project.

**Comment by Winthiefow** [comment]
It worked thanks I wasn't allowing updates indeed !
