### ISSUE TITLE
Renpy 8.01 - Project won't launch

### ISSUE THREAD

**Issue by enokinoki1** [renpy/renpy#3812]
Project won't launch, and it don't show any kind of error.

I have an audio folder with 45k+ files, and if I remove this from the project folder, the project will launch.
I tried this with renpy 7 , and the project will still launch with the audio folder in there.

**Comment by renpytom** [comment]
Is there a traceback.txt or log.txt file created?

**Comment by enokinoki1** [comment]
[log.txt](https://github.com/renpy/renpy/files/9195595/log.txt)
only log created

**Comment by renpytom** [comment]
Could you post the game directory for you game somewhere? I don't see an obvious cause for that.

**Comment by enokinoki1** [comment]
![Capture1](https://user-images.githubusercontent.com/110056154/181457379-bc9fa685-4dd2-4bf2-afa7-08a160d7c7b0.PNG)

I had a folder full of label scripts. after I removed that ,the log become like this

![Capture2](https://user-images.githubusercontent.com/110056154/181457637-a519c9a6-e005-4e7b-8d42-bd7857627615.PNG)

It still cannot launch in renpy 8 unless i remove the audio folder, so I don't think the label folder matters. Also there are only .ogg files in audio folder.

But in renpy 7, it can launch perfectly even with the audio and label folder inside.

**Comment by renpytom** [comment]
Do you have a file without an ascii name in the audio folder? It's possible Ren'Py 8 could be the problem. 

What I'd really like is for you to email the game directory to pytom@bishoujo.us so I can see if I can figure out the problem here.
