### ISSUE TITLE
Cannot install via apt-get on Xubuntu 22.04

### ISSUE THREAD

**Issue by Ayutac** [renpy/renpy#3813]
This is the error I got. Looks like a typo?

![Renpy_error](https://user-images.githubusercontent.com/7873396/181123928-c9da292b-454f-4e9f-8278-24717d945b89.png)

**Comment by Gouvernathor** [comment]
You seem to have reached a version that's more than 3 years obsolete, I guess that apt-get toesn't reach an accurate source, and I don't think we distribute renpy that way (non-commital statement).
In any case, you should probably try the website, renpy.org.

**Comment by Ayutac** [comment]
Ah, I hoped to install it via apt-get, but I can take the website ofc
