### ISSUE TITLE
[Feature Request] Audio converter

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#3814]
Would it be possible to add an automatic audio converter somewhere in the future? Like an additional choice to compress everything down to 128kbps (ogg, mp3 seems like is used the most in games).

For now it seems messy to work with tons of audio files, separating (high quality and low quality) and editing them. It would save developers from this additional work and will also help to reduce game builds size for phones.

**Comment by Gouvernathor** [comment]
This would be an asset conversion tool, which I wouldn't consider to be within the scope of renpy.

**Comment by renpytom** [comment]
Correct, this isn't in the scope of Ren'Py. (More likely is some sort of pre-build script so that you can run your own scripts before a build.)
