### ISSUE TITLE
Why the removal of .pyc from python3

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#3815]
I don't really know if it's by purpose because of python 3 changes. But why aren't there .pyc scripts anymore. Why doesn't renpy recompiles .py scripts? I noticed there's a _pycache_ folder, but I don't want to distribute source .py files.

**Comment by renpytom** [comment]
The .pycs have moved into pycache.

**Comment by KatieCheerios** [comment]
I noticed, but when I remove the .py scripts the game doesn't work. I removed them through the 00build.rpy build patterns.

**Comment by renpytom** [comment]
Python 3 requires both of them, more or less. You could move things around so the .pyc is in the top directory, but Ren'Py sticks with the standard layout Python 3 uses. I can't see a reason to change that.

**Comment by KatieCheerios** [comment]
I wasn't able to move things around, didn't help.

**Comment by KatieCheerios** [comment]
Alright, I managed to do it after batch removing the ".cpython-39" or whatever that is and moving them from the pycache folders it worked. But this is so obscure compared to the way it was before.

**Comment by renpytom** [comment]
No, I don't think there's a need for that - having the Ren'Py source available as part of a game has proven handy in the past.

**Comment by KatieCheerios** [comment]
With so many options in renpy already I think it wouldn't hurt anyone. Game developers should decide when this was a thing not a long ago. It's not like it cannot be decompiled.

**Comment by renpytom** [comment]
I don't plan on changing this, so I'm going to close this issue.
