### ISSUE TITLE
Issue with the way the screen draws between multiple monitors and scaling in macOS

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#3816]
Another Mac specific issue/bug for you:

When running multiple monitor resolutions/scalings, moving the window from one screen to the other causes the screen to fail to draw at the correct scale/size.  For example, I have two monitors, a 5k and a 1440p monitor.  In macOS, it treats them as the same resolution despite the former being double the resolution.  Every other application when dragged from one to the other displays correctly; but Ren'py games (and the Ren'py launcher itself) scale incorrectly when moved between them.

I'm not positive, but it looks like the absolute scaling within the draw window is causing the issue (the actual borders of the window draw at the same relative size when moved across, it's just the content of the windows themselves).  I have attached screenshots for both for your review, using a simple test project:
<img width="2560" alt="5k monitor" src="https://user-images.githubusercontent.com/109490566/181149355-0fe55bf3-352b-4105-9f41-02db2202151d.png">
![1440p monitor](https://user-images.githubusercontent.com/109490566/181149367-5f93aaa2-4350-4119-8b84-bd3cf6bbc3f1.png)
.

**Comment by renpytom** [comment]
This may need an upgrade of SDL to fix.

**Comment by renpytom** [comment]
Can you try to resize the window while it's on the second monitor, and see if that fixes anything?

**Comment by HorBro38** [comment]
That does correct it.  As you may expect, moving it back then shows the content at 1/4 scale until you resize again.

**Comment by renpytom** [comment]
f7db1fb471c096ae097b203b394a9316267c900c should fix this. It'll be in the 2022-07-27 nightly build.

**Comment by HorBro38** [comment]
I can confirm that as of the 7-28 nightly build this is fixed.  Thanks for the quick resolution!
