### ISSUE TITLE
[idea] Create a new text box when the text reaches the maximum.

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3817]
The simple idea would be for renpy to create a new text box automatically when the text reaches the maximum of the text window.  It may happen that in some occasions the size of the text box is different, and it is required to create several lines of dialog, this would improve that by using only 1 line. Or perhaps to prevent the text from going out of bounds.

![imagen](https://user-images.githubusercontent.com/36079551/181385887-7f847336-517e-4791-9936-9d8d2ccfba5f.png)

**Comment by KiloOscarSix** [comment]
I think a better idea would be able to lint long dialogue lines. 
Something like `config.lint_max_dialogue_lines = 3` would then give you a lint warning on any dialogue lines that go over that limit

**Comment by renpytom** [comment]
Linting is an idea, though for many reasons it's complicated - I'll have to figure out how to make it work, as right now the rendering system isn't enabled during linting.

This idea is not something I'd want to do. The reason for that is that breaking the game up into text blocks is something that the creator should be doing, similar to how breaking a novel up into paragraphs is something the author does. I could imagine breaking text into blocks incorrectly could change the meaning. 

Then there's also the problems where it's hard to determine where a sentence ends, eg. "It's possible that E. E. Cummings could determine where this ends, but Robert Downey Jr. might have problems."

**Comment by Gouvernathor** [comment]
See #3076 for @KiloOscarSix's idea

**Comment by JSearUK** [comment]
Also worth noting that, regardless of whatever styling conditions could be calculated for, the *player* might have whacked the Accessibility Text Size slider up, and/or switched to Open Dyslexic...

What might make more sense is a config setting that, upon discovering that the rendered text - complete with Accessibility options applied, custom text tags/images, i.e. just before beginning to blit it into place - checks to see if the result will fit into the (presumably sized) target container and, if not, pops it into a zero-padded/margined viewport with a vertical scrollbar.  Even in the case of a self-sized container, this would be handy to make sure that said container still gets to respect properties such as xmaximum.

This way, *whatever* is going on, it will always be able display all of the content to the user without breaking the layout.

**Comment by renpytom** [comment]
I don't think this is something that will be implemented in Ren'Py. 

It's already possible to wrap the "what" text inside a viewport, if that's something a developer wants to do.
