### ISSUE TITLE
Screen action Function() executes before game starts

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#3818]
Hello,
I don't know if this is meant to work like it is. In the older Renpy 7.4 version this worked. I have a notify queue that queues every new notify message into a list and shows it through regular notify screen instead of replacing it with the last one. And it throws an error 'index out of range', well because the list in it's default state is empty.
this simple example doesn't work when the list is empty like in my case.
`define a = []

screen remove_list():
    vbox:
        text "[a]"
        textbutton "Remove" action Function(a.remove, a[0])`
Again I'm not sure if it's intended behavior. I know this would throw exact same error if tried clicking the textbutton during runtime, but not before the game even starts.

**Comment by Booplicate** [comment]
In your case you could (and probably should) replace it with `Function(a.pop, 0)` Although that's still unsafe - it will crash if you press it while the list is empty, but you will able to show the screen.

**Comment by renpytom** [comment]
This is correct behavior - the arguments are evaluated immediately.

The problem here is is that you're using define with a, and define implies that the variable and its contents are constant. This allows Ren'Py to optimize your game by running Function(a.remove, a[0]) before the game proper starts. I'd suggest replacing define with default here.

**Comment by KatieCheerios** [comment]
Thank you. Is this behavior documented? I looked at the screen actions and there was nothing.
I don't want to use default, because of if the list wouldn't accidentally empty out after quitting the game. Did you thought about adding this queue as a feature to notify itself?

**Comment by Gouvernathor** [comment]
"Screens must not cause side effects that are visible from outside the screen" - from the Screens doc page.
So, even when using default, I don't think we would _guarantee_ that the screen prediction wouldn't jam at this code. I believe any screen should be able to be read at any time, and yours depends on `a` not being empty.
I'd suggest either Booplicate's code, or putting the textbutton inside an `if a:`. Or both.

Also, note that while using `default` guarantee that the variable will be saved, using `define` _doesn't_ guarantee that it won't.
