### ISSUE TITLE
Transform child issues when using the at clause

### ISSUE THREAD

**Issue by Garro** [renpy/renpy#3819]
I'll start by saying that my understanding of Python and Ren'Py is pretty subpar if not worse, so there's a chance I just might have been doing things wrong. This is also an issue I managed to mitigate myself but was wondering if it was a bug in the SDK.

I recently updated to Ren'Py 8.0.1 from version 7.4. I work using mostly LayeredImage and I have built a crude function that adds or removes attributes inside an ATL block, thus allowing me to change a character expression in the middle of an animation. What the function basically does is that it retrieves the child of the transform, adds or removes attributes from` child.name` and call `transform.set_child` to set the LayeredImage with the updated attributes.

```
def unc_add_attributes(attr, trans):
        # Snipped code...
        child = trans.raw_child

        layer_tuple = child.__getattribute__('name')
        layer_list = list(layer_tuple)

        for item in attr:
            # Snipped code... 
            layer_list.append(item)

        final_tuple = tuple(layer_list)

        child.__setattr__('name', final_tuple)
        trans.set_child(child)
        trans.update()

        return None

add_attributes = renpy.curry(unc_add_attributes)
```

This was working fine until v8.0.1 when I noticed a few scenes were not updating a character's attributes. After meddling with the code I noticed only characters using the `show ... at ...` statement were not working. While if it was called in an ATL block it worked as usual.

After some testing I noticed the child provided by the transform when using the `at` keyword was not updating the displayable. Instead, I had to provide the child from the transform's child parameter `transform foo(child=None)` which the at keyword provides just fine, but the ATL block doesn't (resulting in `NoneType has no attrib 'name'` error). I managed to fix the function by checking whenever the child is defined (provided by the at clause) or not (run from an ATL block).

This new behaviour does seems odd to me, and this was working before updating to Ren'Py v8+ so I'm reporting this assuming this might be a bug in the SDK. I can provide more info and the complete function if needed.

**Comment by Gouvernathor** [comment]
The `raw_child`, `name` and possibly others are not documented, therefore it's expected to change or fail between versions.
`renpy.curry` also is, by the way, so you should use functools.partial instead for a reliable currying implementation - ours surely isn't until we document it.

You could get what you want to do by using a `Transform(function=...)` transform, or even a simpler function in a `function` ATL statement. The function you would pass it would be using a simple set_child, but there's no way to read and rely on the existing attributes of the image. Although, I'm not 100% sure changing the child is documented/supported in the ATL version, so perhaps the first one is better.
