### ISSUE TITLE
From __future__ import annotations

### ISSUE THREAD

**Issue by Quantumdit** [renpy/renpy#3822]
## Proposal

Add the annotations \_\_future\_\_ statement to Ren'Py 8:

`from __future__ import annotations`

## Background

With Ren'Py 8 now support type annotations (in pure Python code), I've been adding them to my game. Unfortunately, I've been unable to type hint several functions due to the type not being created yet. It would be possible to fix these issues by playing with load order, but that's a cumbersome solution.

Python 3 solved this issue a while back; changing the way annotations work (see PEP 563). The new behavior was added as a future statement in Python 3.7, meaning it could be enabled in Ren'Py 8.

## Addressing Counterarguments

Some might argue that there's no point in using future statements if that behavior will become the default anyway, but the annotations change has been postponed indefinitely due to competing proposals (see PEP 649). 

Others may instead argue that we shouldn't use future statements while the Python community is debating whether to use PEP 563, PEP 649 or something else entirely. I would counter that either proposal is far better than the current behavior. Additionally, the two proposals are more similar in behavior to each other than the current behavior; using the future statement now will lead to less work porting over code in the future, even if PEP 649 is adopted instead.

**Comment by Booplicate** [comment]
I'm already using that in my game and it works. The only downside is I have to repeat it in every `python` block.

**Comment by KiloOscarSix** [comment]
While this is being discussed you can put your type annotations in quotes (" ") to prevent errors and not having to fiddle with load order

**Comment by Gouvernathor** [comment]
Given the dubious future of the `annotations` \_\_future\_\_, I think we may come to regret having done this.
