### ISSUE TITLE
Web Build Distribution Documentation

### ISSUE THREAD

**Issue by thatwannabecat** [renpy/renpy#3831]
Currently there is no easy to find documentation for web builds on the ren'py documentation website. While there exists documentation for general [build distribution](https://github.com/renpy/renpy/blob/master/sphinx/source/build.rst), specific challenges of web builds like progressive-download are not discussed at all.

Many people use web builds as a primary means of distributing their game and it'd be very helpful to have better documentation for it so beginners can leverage the build tool that exists more effectively.

**Comment by renpytom** [comment]
This was landed recently, so I'm closing this issue.
