### ISSUE TITLE
Character namespace doesn't work on Narrator object.

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#3837]
As documented you can style the narrator with `narrator = Character(**properties)`

However, unlike other character objects using the character namespace:
`character.narrator = Character(**properties)`
won't style the narrator character as the `say()` function is using `renpy.store.narrator` 

Not sure if this is an oversight or intended

**Comment by renpytom** [comment]
This is intended. Narrator (and similar things like adv, nvl, and extend) should live in the namespace. The only reason for using the character namespace is for characters that would conflict.
