### ISSUE TITLE
Allow grids to accept properties as floating point numbers.

### ISSUE THREAD

**Issue by JSearUK** [renpy/renpy#3840]
Grid properties accept values as int, or None, in terms of pixels.
I'm hoping that they can also be made to accept a float, to support being a child of a self-sizing container, as so much else in Ren'Py does.

https://www.renpy.org/dev-doc/html/style_properties.html#grid-style-properties

**Comment by Gouvernathor** [comment]
I'm not sure this is feasible.
As a reminder for people who didn't click the link, the grid style properties are spacing properties which set the space between children. Also, all children are given an area of the size of the largest child.
What happens if you have a child of variable size, and a spacing of variable size ?
What happens if I have a 3x3 grid of identical children being .3 in width, relative to the containing area, and the spacing is .1 ? I'm not sure whether two or three spacings will be placed, but in any case the result will be either 1.1 or 1.2, so more than `1.0`.

**Comment by JSearUK** [comment]
> I'm not sure this is feasible. As a reminder for people who didn't click the link, the grid style properties are spacing properties which set the space between children. Also, all children are given an area of the size of the largest child. What happens if you have a child of variable size, and a spacing of variable size ? What happens if I have a 3x3 grid of identical children being .3 in width, relative to the containing area, and the spacing is .1 ? I'm not sure whether two or three spacings will be placed, but in any case the result will be either 1.1 or 1.2, so more than `1.0`.

Presumably, the exact same thing that happens if you set the pixel values too high:
```py
default self_sizing_parent = False
default child_scale = 1.0

screen controls():
    vbox:
        at top
        xsize 0.5
        yoffset 33
        hbox:
            text "Child size: "
            bar value VariableValue("child_scale", range=7.0, step=0.1)
        textbutton "Toggle Self-sizing parent ([self_sizing_parent])":
            action ToggleVariable("self_sizing_parent", True, False)
            xalign 0.5

screen example():
    frame:
        anchor (0.5, 0.5)
        pos (0.5, 0.55)
        if not self_sizing_parent:
            xysize (400, 225)
        grid 2 2:
            # spacing (16, 9)
                # Doesn't take a tuple ¯\_(ツ)_/¯
            xspacing 160
            yspacing 90
                # If the above properties took floats, devs could keep the
                # ratio between space and content consistent throughout scaling.
            frame xysize(.160 * child_scale, .090 * child_scale)
            frame xysize(int(160 * child_scale), int(90 * child_scale))
            frame xysize(int(160 * child_scale), int(90 * child_scale))
            frame xysize(int(160 * child_scale), int(90 * child_scale))

label start:
    $ quick_menu = False
    show screen example
    show screen controls
    pause
```
If the spacing scaled with the container, the layout would be preserved. It'd still be on the dev to wedge it all into the available space - just as it is now.

**Comment by Gouvernathor** [comment]
Yes, this isn't a new problem actually, and that's because it's relative to the area *available* to the grid, not the area of the grid. So it's valid.
