### ISSUE TITLE
[Idea] Ability to precache certain things forever (so that they don't get replaced)

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#3841]
This spurred from a conversation on the discord with another user, and I had a similar experience.

Sometimes after a long session of testing, you can tell Ren'py replaced some of the start_predict() stuff with something else and can end up having input lag on some essential images like UI images (that were precached initially) all over again.

I don't know if it's feasible, but having an extra argument that would set the start_predict() to have either a 'volatile' cache (like right now), or a cache that can't be replaced by new elements could be really useful.

**Comment by renpytom** [comment]
I don't believe that's true. renpy.start_predict() causes images to be predicted every frame, as one of the first things that's done. 

You can see what Ren'Py will predict each frame by displaying the _predict_set variable.

**Comment by Org-gith** [comment]
Understood, I used the variable you wrote to try to investigate what could be the cause and stumbled upon this, it seems odd but after running MainMenu() (for example launching the game and returning to the main menu), it seems like it empties the start_predict() list. Not sure why.


1) Started a new game, the _predict_set variable is full of stuff I precached as expected:
![dbbb0](https://user-images.githubusercontent.com/78823063/182801628-3045c786-5389-45de-8415-52d1195b2fc7.jpg)


2) Returning to the main menu through mainmenu() and then starting a new game again:
![untitled2](https://user-images.githubusercontent.com/78823063/182801777-47f0e125-6774-4cb8-aae9-730f07ef3866.jpg)
![untitled2](https://user-images.githubusercontent.com/78823063/182801847-85b1c071-2e9b-4c56-840f-052894dc2e85.jpg)
The list is empty now.

**Comment by Org-gith** [comment]
Made a template project that can replicate the behaviour above, downloadable here: https://mega.nz/file/LShmgSTS#a1ITMLVh51leFQt6DKvbuibbvPoYHG8KSElX75Ik2W8
(it has some images in it for the precaching but outside of that it's stock)
It seems also to happen when reaching the end of the game and it returns to the main menu automatically.

**Comment by renpytom** [comment]
You are calling start_predict in the splashscreen, so the second time through the game, it's not being run. You probably want to call it after label start.

**Comment by Org-gith** [comment]
Yes, the thing is I like it in the splashscreen because those are images that will be used during the whole game, like UI images etc. The problem is if I have to put it at the beginning, it that will make a big loading every time you start. Also those images are needed for the replay menu that is accessible through the menu. If a user come back to the main menu, it would remove this cache. 
If he chooses to start again, if let's say I switch the preloading at the start label, he would have to reload the same files over and over every time he starts, that's not good in my opinion. Also if he goes to the replay scene screen which is in the menu, I would need to make preload images again there because by returning to the menu, he would have lost them again.
I don't understand why this is not considered a problem, or at least I think an option would be very useful.
