### ISSUE TITLE
[Question] Ability to format RenPy's code?

### ISSUE THREAD

**Issue by iamtakingithard** [renpy/renpy#3845]
Greets, I am curious is there any feature for RenPy to be able to format it's game code easily?

Something like [Pylint](https://pypi.org/p/pylint/) or [YAPF](https://github.com/google/yapf)

**Comment by Gouvernathor** [comment]
No, because we don't enforce or publish official style guidelines. This is something for the creators community to decide and to create.
We only have the Linter included in the launcher.

**Comment by renpytom** [comment]
The answer is no - this would be a good third-party project, but isn't part of Ren'Py.
