### ISSUE TITLE
Linux: YAD directory selection not working properly

### ISSUE THREAD

**Issue by testes-tester** [renpy/renpy#3853]
I use EndeavourOS/Arch and when I want to start a new project and select a directory, I can't seem to be able to do that as the YAD directory picker isn't showing anything, it just appears with no options or anything so I can't choose where I want my project to be.

![image](https://user-images.githubusercontent.com/103084749/183736440-6962fa83-dd80-4bd5-8383-0c7f87cfc545.png)

**Comment by renpytom** [comment]
Can you try resizing the window to see if that helps? Beyond that, you might need to have to take this up with your distro's maintainers, as producing a tiny window like this seems wrong. (You can also install zenity, which looks like it takes precedence.)

**Comment by testes-tester** [comment]
> Can you try resizing the window to see if that helps? Beyond that, you might need to have to take this up with your distro's maintainers, as producing a tiny window like this seems wrong. (You can also install zenity, which looks like it takes precedence.) 

I've tried resizing before, that was the first thing I did, It really was just just empty window. But for some reason it just fixed itself? Not sure if it's because Zenity is installed (even though I don't remember installing it at all) or because of other reasons (like me installing Steam which I presume installed zenity), but thanks for the suggestions either way.
