### ISSUE TITLE
Does Transform() pixelate large images when resizing?

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3859]
I am trying to resize an image, but it is pixelated, before I used `im.Scale`, but it did not pixelate it if the image was normal. It only pixelated if I zoomed in, here it seems to be the other way around.

Is it some kind of bug? Or something wrong with my code?
### Code

`image test =  Transform("images/Sprites/01/Blazer Uniform/Aiko_Blazer_Smile.png", function=None, size=(561 , 1105))`

```
show test with dissolve:
        yoffset 81
```

> Native image size 2000x4127

### Screenshots

`Transform()`

**Zoom:**
![imagen](https://user-images.githubusercontent.com/36079551/184004713-fa9dce76-20cc-4e8f-8aeb-30671cbd9e2d.png)
**Normal:**
![imagen](https://user-images.githubusercontent.com/36079551/184004409-94ce3c99-8ea7-499f-a242-8049960ad07f.png)

 `im.Scale()`

**Normal:**
![imagen](https://user-images.githubusercontent.com/36079551/184004533-cccb47fb-c979-47c8-aee6-77b81e4270f3.png)

**Zoom:**
![imagen](https://user-images.githubusercontent.com/36079551/184004624-f6c9577e-a2ae-4898-8804-4dac458a28fe.png)

**Comment by renpytom** [comment]
Can you post the log.txt? 

The gl2, gles2, and angle2 renderers should all mipmap images, which should prevent these jaggies when scaling down.

**Comment by Neyunse** [comment]
With Transform() 
[log.txt](https://github.com/renpy/renpy/files/9303815/log.txt)
With im.Scale()
[log.txt](https://github.com/renpy/renpy/files/9303824/log.txt)

**Comment by Neyunse** [comment]
I didn't see anything strange in the log.txt, although I don't tend to know much about what it says...

**Comment by Neyunse** [comment]
here is a Example: https://github.com/Neyunse/game

**Comment by Neyunse** [comment]
After thinking about it, I resized the sprites to 740x1080 and they didn't pixelate, so I will close this...
