### ISSUE TITLE
[Idea] Ability for config.mouse to scale with the size taken by the game window compared to its native size

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#3863]
Just an idea and would be optional since the current behaviour can be wanted, but for example, I have a 2K monitor and the game's native resolution is 1920x1080, if I put it in fullscreen, the cursor becomes uncomfortably tiny compared to the rest (I suspect it becomes even more of an issue of readability at 4K or more). 
The opposite is true if the game is set at a much lower size compared to its native size, then the cursor becomes too big.

This would be similar to this feature: https://answers.unity.com/questions/1740970/cursor-resize.html

If anything I could see that working as an option in the preferences (do I want my cursor to scale or not) since in the edges case, the original behaviour might be prefered I think.

**Comment by renpytom** [comment]
Not possible. 

Hardware mouse sizes are limited by what the hardware supports, which is generally pretty small. 

If you want software mouse support (with the problems that entails), check out config.mouse_displayable.

**Comment by Org-gith** [comment]
That's too bad that it's not possible but it makes sense (and yeah config.mouse_displayable would not feel good as the main mouse cursor because of the input lag).

**Comment by Org-gith** [comment]
Was trying to find an alternative that doesn't involve too much complexity, an entirely different approach: there might be an okay compromise possible if it was possible to switch between two supported presets of config.mouse (32x32 and 64x64) on the fly.  Right now it's possible to offer an option that let's say uses a 64x64 variant if the player wants it in the options (and should cover 4K resolutions quite nicely as 64x64 perfectly filled is very big) but it requires a restart of the game. 
Is this something that could be possible? Feel free to not answer if it's also something impossible to do, I would understand, just leaving it there in case that could be something.
