### ISSUE TITLE
Warper example in documentation is incorrect

### ISSUE THREAD

**Issue by MiiNiPaa** [renpy/renpy#3872]
Documentation for the Interpolation statement in ATL ( https://www.renpy.org/doc/html/atl.html#interpolation-statement ) provides an example of registering custom warper, which doesn't work. Later in documentation there is section on warpers, which specifies that they should be defined in `python early` block in another file. 

But even with these modifications original example doesn't work (cannot store warper in a list, apparently, atl_warper decorator changes function name).

**Comment by Gouvernathor** [comment]
```rpy
init python early:
    @renpy.atl_warper
    def my_warper(t):
        return t**4.4
```
```rpy
define my_warpers = [my_warper]

transform builtin_warper:
    xpos 0
    my_warper 5 xpos 520

transform accessed_as_function:
    xpos 0
    warp my_warpers[0] 5 xpos 520
```
These, in successive files (in unicode order), work as intended. So, the first part you're describing was a mistake on my part, but the second part I can't reroduce.

**Comment by MiiNiPaa** [comment]
Welp, example in Warpers section is incorect too then. It is missing an `init` in `python early`. After adding it everything starts to work.

**Comment by Gouvernathor** [comment]
No, I find that to be working with `init python early` and `python early` all the same. However, if you have a `hide` in there, like the Warpers-section example shows, it's normal that things defined in it are hidden afterwards.

**Comment by Gouvernathor** [comment]
This one is fixed, GitHub didn't notice because of the weird merges between maint and master.
