### ISSUE TITLE
Steam achievements don't trigger in 7.5.2

### ISSUE THREAD

**Issue by perverteer** [renpy/renpy#3874]
This is a follow-up from [my question](https://discord.com/channels/286633898581164032/286633898581164032/1009175651120578640) on the Ren'Py Discord.

I've have two visual novels published on Steam which I recently upgraded from 7.4.* to 7.5 for better Steam Deck support. Unfortunately Steam achievements have stopped working after the upgrade.

The achievements are called using a function:
```python
 def set_achievement(name):
        if is_patreon() and renpy.has_label("extra_scene_01") and not achievement.has(name) and not _in_replay and not renpy.in_rollback():
            achievement.grant(name)
            achievement.sync()

            if gui.codex_notifications and not is_steam:
                renpy.notify(__("ACHIEVEMENT UNLOCKED"))
```
And registered in a separate file:
```python
# List of achievements, to be used in the Achievement screen and on Steam
init python:
    achievements = [
        {
            'title': __("My Shiny Achievement"),
            'description': __("This is achievement is so very shiny."),
            'name': "SHINY",
            'hidden': True,
        },
    ]

    # Register achievements
    for achievement_slot in achievements:
        achievement.register(achievement_slot['name'])

    # Sync registered achievements
    achievement.sync()
```
This setup worked in 7.4, but using 7.5 I can't even grant the achievements using the developer console (using `achievement.grant("SHINY")`).

I've reinstalled the Steam libraries from the Ren'Py launcher and did another build to no avail.  Both `_renpysteam.pyd` and `steam_api64.dll` are present in the game's install directory. The log of the game shows the following error however:
> Faled to initialize steam: AttributeError("function 'SteamAPI_SteamNetworkingIPAddr_GetFakeIPType' not found",)

Have I perhaps hit on a bug in the new Steam API implementation in 7.5?

**Comment by renpytom** [comment]
That's the problem. _renpysteam.pyd isn't needed, and there's a good chance steam_api64.dll is the wrong version. I'd suggest starting with a clean install of Ren'Py, then going to the preferences and having it install the steam libraries itself.

**Comment by perverteer** [comment]
Thanks for the quick follow-up. Turns out the lib directory of my steamcmd build directory had a mix of different files in Ren'Py's lib directory. Now it lists py2-* directories containing only the `steam_api64.dll` and not the `_renpysteam.pyd`. The AttributeError in the log is replaced with another error however:
> Faled to initialize steam: WindowsError(126, 'The specified module could not be found')

**Comment by renpytom** [comment]
Can you post more of the error? Especially, go to the console and and type "import steamapi".

**Comment by perverteer** [comment]
There's not much more I'm afraid. When I type `import steamapi` there is no output on the console, nor in the log. The entire log is as follows:

```
Wed Aug 17 10:53:08 2022
Windows-10-10.0.22000
Ren'Py 7.5.2.22081402
 

Bootstrap to the start of init.init took 0.11s
Early init took 0.01s
Loader init took 0.09s
Loading error handling took 0.28s
Loading script took 6.16s
Loading save slot metadata. took 0.02s
Loading persistent took 0.00s
Faled to initialize steam: WindowsError(126, 'The specified module could not be found')
Set script version to: (7, 5, 2)
Running init code took 0.35s
Loading analysis data took 0.03s
Analyze and compile ATL took 0.15s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.62s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.62s
Cleaning stores took 0.00s
Init translation took 0.63s
Build styles took 0.00s
Load screen analysis took 0.03s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.08s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.79s

Initializing gl2 renderer:
primary display bounds: (0, 0, 2560, 1440)
swap interval: 1 frames
Windowed mode.
Vendor: 'NVIDIA Corporation'
Renderer: 'NVIDIA GeForce RTX 3090/PCIe/SSE2'
Version: '4.6.0 NVIDIA 471.68'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1920, 1080) drawable=(1920, 1080)
Maximum texture size: 4096x4096
```

**Comment by perverteer** [comment]
I had an pass at this today. Removed the entire Ren'Py SDK I had and copied over the entire renpy-7.5.2 directory (instead of the files and folders inside). Moved my projects into the fresh Ren'Py directory and started building Steam releases. Everything seems to work now, no errors in log.txt.

Not sure how my old install of the SDK turned into some kind Frankenstein's monster though.
