### ISSUE TITLE
Alpha property in Transform class doesn't work

### ISSUE THREAD

**Issue by Waffle631** [renpy/renpy#3876]
Hello, I'm testing a module from this topic https://lemmasoft.renai.us/forums/viewtopic.php?t=59587 and it's seems that the alpha property of the Transform() class is broken, the thing is that if I set the variable `config.gl2` to False everything works, but if it is True alpha don't work. I'm testing this in 8.0.2 version
The code that doesn't work is this one
```
def slow_fade(st, gt, delay):
    t = Transform()
    
    t.alpha = 1.0
    
    if not gt == -1:
            
        if st < gt:
            t.alpha = 0.0
        
        elif gt == 0.0 or st > gt + delay:
            t.alpha = 1.0
        
        else:
            t.alpha = float(st - gt) / float(delay)
    
    return t
```
And here are the logs with `config.gl2=True` and `config.gl2=False
[log_gl2_true.txt](https://github.com/renpy/renpy/files/9363908/log_gl2_true.txt)
[log_gl2_false.txt](https://github.com/renpy/renpy/files/9363909/log_gl2_false.txt)

**Comment by Gouvernathor** [comment]
The [update method](https://www.renpy.org/dev-doc/html/trans_trans_python.html#Transform.update) should be called when the fields of a Transform object are updated outside the callback method.
Please check if it works when you do that.

**Comment by Waffle631** [comment]
I tried that and it's still not working.

**Comment by Gouvernathor** [comment]
The following code works as intended :
```rpy
init python:
    def alphathing(value):
        t = Transform()

        t.alpha = float(value)

        t.update()

        return t

label start:
show eileen at alphathing(.5)
```
So it seems to be an issue with FancyText rather than Ren'Py. The module likely uses an undocumented part of renpy that was changed between versions. Contact the creator as to ways of maintaining it.

**Comment by Waffle631** [comment]
Ok, thanks for answer.
