### ISSUE TITLE
[idea] Custom Template folder for new projects

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3877]
This just occurred to me, maybe it's a bad idea or a good idea. However, I will share it here.

The idea would be that renpy detects a folder in its root called `"template"` (that the developer should create) here would be files like script.rpy or screen.rpy and also folders needed for a project, these files would be used as custom templates for new projects and this way if the developer wants to use the styles of a previous game this would make it easier to program everything again and thus speed up the development.

However, there will be occasions where the developer does not want to use a template, for which the developer may be asked if it wants to use a template or a clean project.

**Comment by renpytom** [comment]
As a question, what do you see as the difference between this and just making a copy of the old game (and changing some of the config variables)?

**Comment by Neyunse** [comment]
> As a question, what do you see as the difference between this and just making a copy of the old game (and changing some of the config variables)?

That's an interesting question, since it would be the same thing to overwrite the files with the edits by changing the variables. The idea of this is to have a global template for renpy to generate it from there without having to be moving the files always, yesterday I also thought of another idea for this, and it would be that the folder can have inside sub folders and display it this way.

![imagen](https://user-images.githubusercontent.com/36079551/185532477-ae71f9f6-67ec-433e-90d8-27b902f7a8e9.png)

And thus allow the developer to choose a template based on an old game and streamline the editing of the GUI, as it is expected with this is to use the same GUI but with minor changes in the same or slightly larger changes but retaining the same style of the same. This is more to speed up the development of the games, reusing the existing, although it may not seem important, because it would only be enough to overwrite the files and edit some things, this could simplify it more.

Since the folder may or may not contain all the scripts from the old game and having a template to work on, renpy will only generate what is needed using those templates as a base or using all the files from the old game but with clean scripts ready to be used in a new project.

Of course, the developer would have to prepare the template by hand editing it, but this would only be done once for renpy to generate it in some next project (which is not expected to be the next one, only that he would already have a base to work with later).

There are some developers who use the same GUI in new projects, however, they have to overwrite and see what files work for them and in some cases it becomes a small delay for the game itself, this would benefit to only edit what is necessary and renpy works on it or directly working on a complete old project with the edits already done to have to write the dialogs and change the images.
