### ISSUE TITLE
Menu backgrounds hardcoded in screens.rpy by default

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#3879]
Line 388 and 500 of screens.rpy has the background image hardcoded to the following respectfully:

`background "gui/overlay/main_menu.png"`
`background "gui/overlay/game_menu.png"`

However, they should be allowed to be changed in gui.rpy (lines 90 and 91):

`define gui.main_menu_background = "gui/main_menu.webp"`
`define gui.game_menu_background = "gui/game_menu.png"`

Because of the hardcoding, they will break if they are changed.  Just need to update screens.rpy to be the actual variables.

**Comment by the66F95** [comment]
but you're aware that the frame background you're referring to has nothing to do with the screen background.
it was always coded that way.
if you want to have a gui variable assigned for the overlay then do so.

**Comment by HorBro38** [comment]
This is why I shouldn't be putting in issues at 3 AM.  I will close this one in shame.
