### ISSUE TITLE
No audio on the Music channel after playing a Movie

### ISSUE THREAD

**Issue by TuneEternal** [renpy/renpy#3891]
This is a weird issue I've never had before. No sounds will work out of the music channel after a movie plays. **However,** the music does play every time it is called before the movie scene. This is an issue even the best RenPy coders I know couldn't fix. I appreciate the help.

![Capture](https://user-images.githubusercontent.com/105620440/185817698-9d9872e9-e80f-4c3d-a537-da7a06eda240.PNG)
![Capture2](https://user-images.githubusercontent.com/105620440/185817700-9d70be1a-ebaf-4953-9534-bf89beefe22b.PNG)
![Capture3](https://user-images.githubusercontent.com/105620440/185817702-2c99719c-8269-45d2-84c9-ddcbe46b9003.PNG)

The first and second picture contains the workaround we have tried to fix this issue. We turned the video into a screen proxy and the audio issue persisted.
The third picture is the next occurring instance of Music after that movie.

**Comment by renpytom** [comment]
Can you put together a small demo? I don't see an obvious reason why a movie would prevent music from playing. (renpy.movie_cutscene does, but not normal movies).
