### ISSUE TITLE
Updating to renpy 8.0.2 [Errno 2]

### ISSUE THREAD

**Issue by clowns234** [renpy/renpy#3893]
Old renpy code that works in renpy 7:
        A = ["black.jpg"]
        e = renpy.file('images/S00/img.dat').read()
        e = e.split("\n")
        for img in e:
            A.append(img)
Error:
FileNotFoundError: [Errno 2] No such file or directory: 'images/S00/img.dat'

**Comment by renpytom** [comment]
Can you post the full error and the list of the files? Does the file actually exist in game?

**Comment by clowns234** [comment]
label start:
    python:
        A = ["black.jpg"]
        e = renpy.file('images/S00/img.txt').read()
        e = e.split("\n")
        for img in e:
            A.append(img)
           
[traceback.txt](https://github.com/renpy/renpy/files/9398801/traceback.txt)
 
[img.txt](https://github.com/renpy/renpy/files/9398803/img.txt)

**Comment by the66F95** [comment]
```
label start:
    python:
        A = [b'black.jpg']

        with renpy.file('images/S00/img.txt') as f:
            lines = f.readlines()
            for img in lines:
                img = renpy.re.sub(r'(\r|\n)', '', img.decode('utf-8')).encode()
                A.append(img)
```

**Comment by mal** [comment]
This doesn't appear to be an issue with Ren'Py.

You probably want to either be specifying the encoding in `renpy.file` (i.e. `renpy.file('images/S00/img.txt', encoding='utf8')`) or providing a bytes type value to `.split` (i.e. `e.split(b"\n")`), or as noted in the previous comment, manually calling `.decode` on the bytes object.

**Comment by clowns234** [comment]
> This doesn't appear to be an issue with Ren'Py.
> 
> You probably want to either be specifying the encoding in `renpy.file` (i.e. `renpy.file('images/S00/img.txt', encoding='utf8')`) or providing a bytes type value to `.split` (i.e. `e.split(b"\n")`), or as noted in the previous comment, manually calling `.decode` on the bytes object.

The decode made the existing data files work in the proper format.
