### ISSUE TITLE
Allow _side_image_tag to follow the speaker

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3896]
Setting `define config.side_image_tag = "protagonist"` and then mid-script using `$ _side_image_tag = None` does not allows the side image to switch between speaking characters.

I believe this is the line that causes it (00sideimage.rpy, line 60):

` side_image_tag = _side_image_tag if _side_image_tag is not None else config.side_image_tag`

According to the docs this works as intented, but, is there a way to make the side image follow the speaker once, and in the rest of the game follow a specific character?

My suggestion is to give the speaker-following function a value like `_side_image_tag = "follow"` so it could take precedence over `config.side_image_tag = "protagonist"`

 I guess you could use `config.side_image_tag = None` and then `_side_image_tag = "protagonist"` at the beggining, but that becomes a mess if the game uses labels in a complex manner and you only want to revert once. Ideally, one could use callbacks like `config.interact_callbacks` and create a system.

I know there are workarounds, but my proposal allows easy customization. I apologize if this solution creates more problems and it's not worth it.

**Comment by renpytom** [comment]
The right way to do this is to set ``_side_image_tag`` at the start of the game, and change it to None as appropriate. I don't see how having a "follow" mode adds anything over that.
