### ISSUE TITLE
How to change font on accessibility menu (A Key)?

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#3897]
Hi everyone,

The default font used on the the accessibility menu does not support Chinese characters, and 40% of my players are chinede, so the accessibility menu becomes full of tofu squares.

I want to manually set the font used on accessibility menu based on the current active language.

**Comment by renpytom** [comment]
You can set gui.interface_font to another font.

**Comment by SergioAlonsoJr** [comment]
@renpytom, setting gui.interface_font doesn't work.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/4298411/186922478-b7144a2a-2fba-478e-861d-9a8d6c507c91.png">

I change both gui.interface_font and gui.interface_text_font
