### ISSUE TITLE
How to delete DejaVu Sans from the "Font Override" on the accessibilities options?

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#3898]
DejaVu Sans does not support chinese characters, and 40% of my players are chinese. If they accidentally open the accessibility menu and click DejaVu Sans, their game text will become 100% tofu boxes.

**Comment by renpytom** [comment]
There isn't a way to do this. The contents of the accessibility options are part of Ren'Py, and aren't intended to be altered by the game developer. 

The accessibility menu allows people to ruin their game experience. That's by design.
