### ISSUE TITLE
[Feature Request] Dismiss Property

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#3903]
What do you think about adding keysym property to dismiss displayable?
It will save us from adding action duplicates like `key 'game_menu' action Hide()`.

```
dismiss:
    keysym 'game_menu'
    action Hide()
```

**Comment by JSearUK** [comment]
This could also help avoid issues such as `key` being finicky about where it is placed in a screen, or it actually being a displayable and potentially generating unwanted `fixed`s in a self-sizing frame, for example.

**Comment by renpytom** [comment]
Done.
