### ISSUE TITLE
Rollback screens bug?

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#3907]
Hello,

I'm having a problem with rollbacking screens. So, I think this worked sometimes back in a renpy 7.4. But now it doesn't. I've put up a sample code of what is happening. Basically if the flow is stopped at call screen, and before it there was shown another screen with a timer that hides it. After jumping from call screen to another label and rolling back, it doesn't register the timer has passed and the screen was hidden, but instead the screen is shown and stuck there. The timer doesn't get retriggered either. So, I want to rollback to the point of showing the primary screen just at the point of block_rollback(), and the secondary stays hidden. I think this worked some time in previous versions.

```
screen primary():
    zorder 5

    add "blue" align(0.5,0.5)

    textbutton "Jump" action Jump("test_label")

screen secondary():
    zorder 10

    add "red" align(0.5,0.5)

    timer 2.0 action Hide("secondary")

image red:
    Solid("#c00")
    size(500, 500)

image blue:
    Solid("#00c")
    size(800, 800)

label start:

    show screen secondary

    $ renpy.block_rollback()

    call screen primary
return

label test_label:
    "text1"

    "text2"
```

**Comment by renpytom** [comment]
I don't think this is something that should have ever worked.

**Comment by KatieCheerios** [comment]
Hm, I went over almost identical code from before the release of Renpy 7.5 and 8, and the code works there as I wanted it. My thought was that renpy.block_rollback() created a checkpoint that could not be rolled over. The problem is that in my original code the secondary screen is as big as the primary and modal. Which then prevents any interaction when it doesn't restarts the timer.

**Comment by renpytom** [comment]
Ther was a change in the newe versions so that modality now stops timers.

**Comment by KatieCheerios** [comment]
Is there any way to get that functionality back?

**Comment by renpytom** [comment]
As of 8.0.3/7.5.3, you can have modal True on timers, to allow them to expire when blocked by something that is modal.

**Comment by KatieCheerios** [comment]
I have 8.0.3.22083102 version and my modal overlay screen with timer is still stuck after rolling back, even though the timer expired. Otherwise I wouldn't be able to roll back. Or am I missing some newer version?
