### ISSUE TITLE
Unable to build for web on linux command line

### ISSUE THREAD

**Issue by EEsDoNotItNow** [renpy/renpy#3908]
Building on `Debian 5.10.120-1` , the resulting file has no web files what so ever. 

### Steps to reproduce

-  Download `renpy-7.5.2-sdk.tar.bz2` and `renpy-7.5.2-web.zip`
- `tar xf renpy-7.5.2-sdk.tar.bz2`
- `cd renpy-7.5.2-sdk`
- `unzip ../renpy-7.5.2-web.zip`
- `./renpy.sh launcher distribute --package web tutorial`

### Expected Behavior

The resulting `tutorial_7-7.5.2....` folder should have (among other things) an `index.html` file, a `game.zip` file, etc etc. 

### Actual Results

The directory after unzipping `./tutorial_7-7.5.2.22081402-dists/tutorial_7-7.5.2.22081402-web.zip` has the following files:

```
game
main.py
progressive_download.txt
renpy
tutorial_7-7.5.2.22081402-web.zip
tutorial_7.py
```

An exhausting search (`find | grep html`) doesn't find anything.

**Comment by renpytom** [comment]
To build for the web, please use the launcher, and click the "Web (Beta)" button. 

What you're doing isn't expected to work.

**Comment by EEsDoNotItNow** [comment]
@renpytom so the command line just flat out isn't supported? Thats... confusing.

**Comment by Andykl** [comment]
If you really want it, I have added separate build_web command in my project, place that code in separate `.rpy` file in `sdk/launcher/game` (separate to not broke sdk update):
```py
init python hide:
    def web_build():
        ap = renpy.arguments.ArgumentParser(description="Build web.")
        ap.add_argument("--destination", "--dest", default=None, action="store", help="The directory where the packaged files should be placed.")
        ap.add_argument("project", help="The path to the project directory.")
        args = ap.parse_args()

        def get_web_destination(ignore):
            return args.destination
        store.get_web_destination = get_web_destination

        p = project.Project(args.project)
        build_web(p, gui=False)
        return False
    renpy.arguments.register_command("web_build", web_build)
```
Note that this is hacky and you are on your own with it.

**Comment by EEsDoNotItNow** [comment]
@Andykl works like a charm! Very easy to integrate into a command line flow. Thanks!

**Comment by renpytom** [comment]
Note that this is likely to be a way to shoot yourself in the foot regarding .rpyc consistency, which is why building from the command line isn't supported.

**Comment by EEsDoNotItNow** [comment]
@renpytom There are no rpyc files in the distribution, and a CICD starts from a freshly installed environment every time you run it. So I don't understand how that could become a concern. 

Ideally this would just work. I cannot fathom how the GUI manages to do this when the actual code itself has a problem with it.
