### ISSUE TITLE
Inconsistent build behavior between Windows and Mac/Android

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#3909]
I was helping another developer on the discord today and we discovered an issue where a build would work for PC but would fail to launch on both my Mac as well as their own Android device.  We resolved the issue, but it looks like the fact it was working on the PC was an error/bug of some kind.  They were using the ability to swap between two different fonts in their game, by customizing both gui.rpy:

```
## The font used for in-game text.
define gui.text_font = gui.preference("font")

## The font used for character names.
define gui.name_text_font = gui.preference("font")

## The font used for out-of-game text.
define gui.interface_text_font = gui.preference("font")
```

Then they put this in their preference pane:

```
               vbox:
                    style_prefix "radio"
                    label _("Font")
                    textbutton _("Pixel Font!") action [gui.SetPreference("font", "pixxia.ttf", rebuild=False), gui.SetPreference("size", 4), gui.SetPreference("linespace", 1), gui.SetPreference("textcps", 25)]
                    textbutton _("Nonpixel Font!") action [gui.SetPreference("font", "ComicMono.ttf"), gui.SetPreference("size", 5), gui.SetPreference("linespace", -1), gui.SetPreference("textcps", 0)]
```

This would work on a Windows device, but would fail to a traceback on other platforms (I've attached the traceback.txt from my own computer):

[renpy-traceback.txt](https://github.com/renpy/renpy/files/9437197/renpy-traceback.txt)

We were able to resolve this on all platforms by changing it to the following:

```
## The font used for in-game text.
define gui.text_font = gui.preference("font", "pixxia.ttf")

## The font used for character names.
define gui.name_text_font = gui.preference("font", "pixxia.ttf")

## The font used for out-of-game text.
define gui.interface_text_font = gui.preference("font", "pixxia.ttf")
```

The issue here was the developer didn't even realize they had a problem (they knew Android was failing, but assumed it was another issue) as it worked on their Windows PC.  Let me know if you need sample projects/etc.

**Comment by renpytom** [comment]
The first one was just wrong. Chances are that gui.preference("font", "pixxia.ttf") had been used, then changed away from, but was still stored in persistent. I suspect this would manifest on Windows systems that have never run this game.
