### ISSUE TITLE
uncaught range error

### ISSUE THREAD

**Issue by roydaniel00** [renpy/renpy#3914]
hello guys browsers have reduced there call stack so you think that all renpy games work but for us no ren py game work please see it it shoes uncaught range error see javascript

**Comment by Gouvernathor** [comment]
This is supposed to be fixed in the latest 7.5, see [this](https://www.renpy.org/latest-7.html).

**Comment by Andykl** [comment]
Fixed in https://github.com/renpy/renpyweb/pull/28. 
Changelog note is [here](https://www.renpy.org/doc/html/changelog.html#web-and-chromeos).
