### ISSUE TITLE
Syntax errors all over the place on demo project opening

### ISSUE THREAD

**Issue by HappyUnknown** [renpy/renpy#3919]
I first downloaded Ren'py, but already had problems on the start. When opening any of the scripts, that belonged to demo projects, I have been seeing syntax errors on almost every keyword. I tried to search for something like "define is not defined ren py", but found nothing - seems there are no special forums for Ren'py, except its own Github. Python was updated yesterday - installation folder is default, same for Ren'py - I tried both 7.5.2 and 8.0.2. Ren'py cannot be installed wrong, because the app is being downloaded ready to launch.
What can be wrong about my installation process?
![image](https://user-images.githubusercontent.com/39666812/187176284-32231666-8998-48f8-a27b-ab69c1f7ef00.png)

**Comment by Numerlor** [comment]
Renpy is not Python, you have to run the projects through its sdk instead of directly from Python

**Comment by HappyUnknown** [comment]
@KiloOscarSix Much thanks! No tutorial mentions this thing.

**Comment by Andykl** [comment]
How to run RenPy projects is pretty well described in the [documentation quickstart](https://renpy.org/doc/html/quickstart.html#the-ren-py-launcher).

**Comment by Andykl** [comment]
If you have any questions you can always ask them in the official [discord community](https://discord.gg/6ckxWYm).
