### ISSUE TITLE
Modules shouldn't import through entrypoint

### ISSUE THREAD

**Issue by Numerlor** [renpy/renpy#3921]
It's currently impossible to run renpy through a different entrypoint, as `__main__` is assumed to be `renpy.py` and functions from it are used. This prevents renpy from being started by a different entrypoint. The functions should be moved to a module under the renpy package that will have a proper name

**Comment by renpytom** [comment]
renpy.py (or whatever it's named to) is the entrypoint of Ren'Py.

**Comment by Numerlor** [comment]
Yes, but the entrypoint should only be the entrypoint, it currently also serves as the source of some functions which are imported through `__main__` - making it impossible to use tools like profilers that run through `python -m` because they get assigned as the `__main__` module

**Comment by renpytom** [comment]
I'll consider this - at the very least, having the module register itself with renpy.main so that it runs. The current approach is that all of the functions that are expected to be customized by, say, a Linux distribution live in renpy.py.

**Comment by renpytom** [comment]
This was resolved by 351c97bf09c6c664fcba25a780f7ead49183cfc8 .
