### ISSUE TITLE
[Feature Request] ATL in screens

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#3925]
As far as I know, items placed in screens are also implicitly placed inside `fixed` area.
What about adding an ability to add ATL transform for the whole screen?

Like:
```
screen test:
   at transform

   text "..."
```

Instead:
```
screen test:
   fixed:
      at transform

       text "..."
```

**Comment by renpytom** [comment]
I think I'd rather you keep the fixed explicit, if you want to transform it. My thinking is that I might, at some point, want to replace the fixed that makes up the screen with something else (for example, a less complicated displayable meant just for this), and that would be hard to do if I documented that there was actually a real Fixed there. 

Make sense?

**Comment by via-my** [comment]
Well, you know best :)
