### ISSUE TITLE
Multiple text tag

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#3928]
`e "{b}{i}{outlinecolor=#00ff00}{color=red}{size=28}Hello{/size}{/color}{/outlinecolor}{/i}{/b}"` 

Idea: `e "{w=1, b, outlinecolor=#00ff00, color=red, size=30, i}Hello{/b, outlinecolor, color, size, i}"`

**Comment by Gouvernathor** [comment]
This would break custom text tags taking the `,` character as part of their parameter.
For cases like these I would suggest the use of one custom text tag applying all these ones.

**Comment by renpytom** [comment]
You're not actually saving all that much by this, either. Comma and space are the same length as }{, so you're only really saving the slashes in the closing tags. (And IIRC, you can actually omit the closing tag proper by writing {/} if you really want to.
