### ISSUE TITLE
Clear a tag's showing attributes

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3931]
A function similar to [get_attributes](https://www.renpy.org/doc/html/displaying_images.html#renpy.get_attributes), but which would clear the list of attributes of a given tag. Not equivalent to `hide tag` `show tag`, because it leaves placement as-is.
Preferably, a predicatable renpy-script version of that feature could be cool as well.

However, for a `layeredimage eileen old:`, the way of clearing the attributes of the layeredimage without showing the bare `eileen`, is `$ clear_attributes("eileen")` then `show eileen old`.
For layeredimages a hack is to request a non-existing attribute and then re-call the show instruction, but it would be cool to have a non-hack version of this as well as support for non-layeredimages.
There is also a way to do this using adjust_attributes, but if having a lot of adjust_attributes functions, patching them all is tedious.
There is also `$ renpy.show("tag" + "".join(" -" + att for att in renpy.get_attributes("tag")))`... but I said a non-hacky way.

**Comment by renpytom** [comment]
Seems reasonable. But please don't pseudo-tag things - especially when you can just tag it.
