### ISSUE TITLE
config.multiple_say_style_format

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#3932]
with a multiple character dialogue, instead of the style name needed being restricted to `"block{n}_multiple{m}_{style}"`, we could create a new config variable `config.multiple_say_style_format` (that would default that string), and use this variable to format what we need

**Comment by renpytom** [comment]
Please do not

**Comment by renpytom** [comment]
Please do not pseudo-tag issues. 

Can you give an example of why you'd want this? My feeling is that the multiple say is a rarely used feature as it is, and so making it more complicated by indirecting it through a config variable doesn't seem worth it. But I'm willing to be convinced by a compelling use case.

**Comment by Elckarow** [comment]
rarely used doesn't mean it can't be improved. i don't know anyone who has ever modified or even heard of the gc config variables, yet 4 of those exist.

the only use case i can think of is something like this
`define config.multiple_say_style_format = "something" if persistent.something else "something else"`
but generally it just allows more personalization which is something i am quite fond of, similar to `config.voice_filename_format`.

**Comment by renpytom** [comment]
I don't think this will be ever used, and so I don't think it justifies the additional complexity. 

A lot of the variables (like the gc ones) are there to allow errors to be fixed without a full release of Ren'Py.
