### ISSUE TITLE
Resize does not work with contains statement

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#3933]
I have an image with a simple blink animation:
```
image img_0:

    contains:
        "gui/001.webp"

    contains:
        "gui/002.webp"
        alpha .0
        block:
            pause 1.0
            linear .5 alpha 1.0
            pause .5
            linear .5 alpha .0
            repeat
```

But when I try to resize the image, it stays the same size:
```
screen sc_gallery:

   image 'img_0':
      ysize 216
      fit 'cover'
```

It only happens when I use `contains` statement.
Interesting thing that `zoom` statement works as it should.
Checked on Ren'Py 8.1.0.22083102n and 7.4.11.

**Comment by renpytom** [comment]
Please do not pseudo-tag issues titles. 

This is not a bug, but expected. When you use contains, what's happening is you're creating a Fixed to contain the  two images. The Fixed is what's being resized when you display the image, not the two transforms inside it.

**Comment by via-my** [comment]
Then I have in my mind one idea to make it work with such images.
One additional transform parameter like `sizezoom` that will change how `xysize` works. Like if ‘sizezoom‘ was enabled, xysize would work like `zoom`.

**Comment by via-my** [comment]
Let's say I have fixed area 1920x1080. 
Then I enable `sizezoom` and enter the xsize of 960. 
It should calculate the target width and the actual width and then apply xzoom of 0.5.

**Comment by Gouvernathor** [comment]
Why not just use `fit "fill"` or `fit "contain"` in the `contains:` blocks ? That way, the contained images would adapt to the size of the containing fixed, which itself gets its size set by the transform properties you give in the screen.

**Comment by via-my** [comment]
That's super genius! 
`fit 'contain'` worked for me. Thank you!
