### ISSUE TITLE
Audio files sometimes make a noticeable break 'noise' when they are interupted/replaced by a new sound before they end (on the same channel)

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#3934]
This is something that I have been noticing since I started Ren'py, it's so minor I have never bothered reporting it and I'm not sure how other engines avoid this noise to begin with, but this is happening on the spam of buttons or when skipping or when a blip sound made by a character talking is replaced by a new one before it ends. 
I think what causes this is when an audio file gets interrupted and replaced by a new sound on the same channel before it ends.
Here is a recording of the break 'noise': 
https://streamable.com/2igi25

**Comment by renpytom** [comment]
Can you record it as a .wav file at 48,000 samples per second? 

My guess is this is just what happens when you stop playing a file early without fading it out.

**Comment by renpytom** [comment]
Also, please do not pseudo-tag issues.

**Comment by Org-gith** [comment]
It was first thought too and remained that way for a long time, but here is a demonstration of the same test on rpgmaker using the same audio file compared to this:
https://streamable.com/1aih5s

Attached zip file with the recordings at 48khz wav (+ the audio files used in the testing).
(understood for the pseudo-tag)
[audiotest.zip](https://github.com/renpy/renpy/files/9476054/audiotest.zip)

**Comment by via-my** [comment]
As far as I know, there's one special channel for any GUI sounds. The `audio` channel creates additional channels on the fly to evade audio replacing. You can use it by simply writing `hover_sound "..."`.
So at least there's one quick workaround. And for me it sounds quite near to the one you showed with RPG Maker.

Indeed, `fadeout=0.01` removes that blip sound, but it does not make it sound any stranger. At least in my case.
[Test Video](https://www.dropbox.com/s/w2he5aw29w1t9ft/2022-09-02%2019-30-08.mkv?dl=0)

**Comment by Org-gith** [comment]
It seems great, may I ask which version are you running? Somehow my fadeout doesn't behave like that. Wasn't aware of the hover_sound/audio thing, though I like having my number of audio channel under control, the fadeout solution seems perfect but I can't make it work like you (still get the cracks):
renpy.play("audio/se/windowslideup.ogg", fadeout=0.01, channel="interface8")

**Comment by via-my** [comment]
I used nightly version `8.1.0.22082301n` on the video,
Also checked 7.4.11 and, as you said, `fadeout=0.01` didn't remove that blip sound.
On 8.0.3 and 7.5.3 everything works good.

**Comment by via-my** [comment]
I don't actually think that `fadeout` might be a good solution for this.
Better wait for the pytom's answer.

**Comment by Org-gith** [comment]
I upgraded and everything and this commit made it work for me I believe, thank you for your help: https://github.com/renpy/renpy/commit/44300d9a8c4e758409a762537d9353f383baea90

I think it's possible they use a negligible fade-out by default like this in rpgmaker or whatever library of audio is doing it for them automatically. 
A sort of 0.01 fade on every audio files, that is by default and only gets replaced by a bigger fadeout seems a pretty nice solution. We are talking about a fade that is just there to prevent the crack noise, it's not really something your ear should notice.

Basically was doing some research on that subject on google, and what is causing this is the sound being interrupted in the middle of high wave or low wave, then if the next sound starts on a very different wave, the crack will be noticeable. 
https://stackoverflow.com/questions/42192239/remove-control-clicking-sound-using-pyaudio-as-an-oscillator

Was reading on the possible solution for this and most of the library or the knowing guys talking about implementing a sort of unnoticeable fade which prevents the issue, I'm thinking most of the advanced libraries have that inbuilt or something that looks like that.
