### ISSUE TITLE
modal True on timer still shows timer in the end

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#3935]
My notify screen makes use of a 5 second timer. I noticed notifications would get stuck on-screen if you opened the menu while they were still being shown. 

After updating to 8.0.3 and using `modal True`, all it does is hide the notification after 5 seconds while the game menu is open, but when you close the game menu, the notification is still there and permanently stuck.

**Comment by KatieCheerios** [comment]
I have a similar issue, just with rollback. The answer as of right now is that modality disables timers. So, unless it's reverted back, there's no straightforward fix.
