### ISSUE TITLE
Issue with layeredimage's `at`

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#3942]
(tested in 7.5.3)
say you have something like this:
```
transform cg_dissolve:
    on show:
        alpha 0.0
        linear 0.5 alpha 1.0
    on hide:
        alpha 1.0
        linear 0.5 alpha 0.0 

layeredimage cg eileen:
    at Flatten, cg_dissolve
```

showing the image will result in the following error
![Capture](https://user-images.githubusercontent.com/101005497/188336054-56cb51ae-a606-4c2c-86cd-69465bd0bff6.PNG)

using a 1-element tuple also results in the same error
```
layeredimage cg eileen:
    at Flatten,
```

and only using a single `at` is fine
```
layeredimage cg eileen:
    at Flatten
```

**Comment by Gouvernathor** [comment]
Yes, that's because a lot of places accepting several transforms only accept _lists_ of transforms. That's the case here, as well as in the `at_list` parameter of `renpy.show`.

**Comment by Elckarow** [comment]
changing it to `at [Flatten, cg_dissolve]` did the trick

i do think converting the object to a `list` when passed as a `tuple` is worth looking into (especially for layeredimages, syntax is easier on the eye)
