### ISSUE TITLE
Google Play - unsupported version of Play billing

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#3950]
When uploading an .aab build to Google Play, they now display the error message: 

`We've detected this app uses an unsupported version of Play billing. Please upgrade to Billing Library version 4 or newer to publish this app. [Learn More.](https://developer.android.com/google/play/billing/deprecation-faq)`

Thanks for the fix from my previous issue, by the way!

**Comment by Gouvernathor** [comment]
Seems fixed by a renpy-build issue

**Comment by marchare555** [comment]
Hello, the app appears to be shipping to Google Play without errors now. Thanks for your help.
