### ISSUE TITLE
Layeredimage attribute if_ can override group if_

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3955]
When a group has a if_* property, and an attribute inside the group has another if_ property, the attribute will be shown if its own property is valided even if the group's property is not.
Example :
```rpy
layeredimage li:
    at top
    attribute a:
        Solid("#f00", xysize=(100, 100))
    attribute b:
        Solid("#ff0", xysize=(100, 100), xoffset=100)
    group c if_not "a":
        attribute d if_not "b":
            Solid("#0f0", xysize=(100, 100), xoffset=200)
        attribute e:
            Solid("#0ff", xysize=(100, 100), xoffset=300)
```
Calling `scene li d` shows a green square, that's normal.
Calling `scene li b d` shows a yellow square with no green square, because d's own properties are respected.
Calling `scene li a e` shows only a red square with no cyan square, because the c group's properties are respected.
But calling `scene li a d` shows the red and the green, which means d doesn't respect the c group's properties.

**Comment by renpytom** [comment]
This is documented. 

"The attribute statement takes the following properties:

if_all
 A string or list of strings giving the names of attributes. If this is present, this layer is only displayed if all of the named attributes are present.
if_any
 A string or list of strings giving the names of attributes. If this is present, this layer is only displayed if any of the named attributes are present.
if_not
 A string or list of strings giving the names of attributes. If this is present, this layer is only displayed if none of the named attributes are present.
"

"Properties supplied to the group are passed to the attributes inside the group, unless overridden by the same property of the attribute itself."

**Comment by Gouvernathor** [comment]
Ok, then I think it doesn't really make sense in this case, the conditions should add up instead of replacing one another. I think it makes more sense for a group condition to apply uniformly to all the attributes in a group.
You can always declare a second group with the same name and whatnot just under the first, without the group if_* properties, and put the more-permissive attribute there.

Although I realize that this is not and should not be the case for transform properties given to the group and others to the attributes : the latter should override the former and not merge with them. I think if_* are different, but consistency would be a factor to take into account.

**Comment by renpytom** [comment]
I don't think if_not is so special in this case it should be treated differently than every other property. Most notably, I don't see how we would merge if_all and if_any, and so I don't think that it makes sense to treat if_no differently than them.
