### ISSUE TITLE
Ability for transforms to be skippable or sped up by a certain amount when Renpy is skipping

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#3957]
Currently is possible to achieve this result by using some tricks, for example one of them would be:
```
transform zoom:
    linear 2.0*(not renpy.is_skipping()) zoom 2.0    
```
This will make it so that the transform is only applied when renpy is not skipping but it must be done on every transforms and every lines containing time, just an idea but it could be interesting to sort of remove or multiply the speed of ease/linear/etc. depending if ren'py is skipping or not, for all the transforms through a config.

**Comment by renpytom** [comment]
I've considered this in the past, but I don't think this is useful enough to justify the effort (and risk of error) that adjust this. 

This would also break down pretty hard if a repeat is involved.

**Comment by Org-gith** [comment]
Hmm hadn't considered that, and the transforms on the UI definitely nobody would want them to be affected by this.
Just formulating a rough idea that could work around it.  Maybe having a tag to apply on the transforms make it sensible, a very rough example:
```
transform zoom:
    [tag_that_makes_it_sensible_to_the_config.transformspeed]
    linear 2.0 zoom 2.0 
```   
config.transformspeed="None"  (default =1)
config.transformspeed="0"  (make the tagged transform skip when renpy is skipping)
config.transformspeed="2"  (make the tagged transform time/2 when renpy is skipping)

But I understand for the part where it's probably not worth the effort, I don't think the creators care that much about how renpy looks when it's skipping and probably it shouldn't be too hard to implement a solution for this for a given project (making it relevant to all the projects is the challenge), so trying to come with my own way of dealing with it is probably more appropriated.
