### ISSUE TITLE
Auto-advance and text wait tags issue

### ISSUE THREAD

**Issue by inismor** [renpy/renpy#3958]
(Ren'Py 8.0.2) I have an ATL background that executes over 6 seconds, zooming in on a portion of the image. I am trying to display a sequence of dialog text while the zoom is happening. It works fine in normal mode, but when you turn on auto-advance the waits disappear. For example:
```
python:
    waitLength = 3.0 # waitLength = 100.0
    strToSay = "This . . . {{w={}}}is how . . . {{w={}}}it works!".format(waitLength, waitLength)
    renpy.say(character.s, strToSay)

```
It doesn't matter what `waitLength` is; it could be 3 seconds or 100; the wait is over as soon as Ren'Py calculates how long it would take to read the preceding text, which in this case is fairly short. I was trying to get the dialog to stretch until the background zoom had completed. I would expect it to operate like this:

`This . . . `_(wait for 3 seconds)_`is how . . . `_(wait for 3 seconds)_`it works!`

**Comment by Gouvernathor** [comment]
At first view this doesn't look like a bug. Auto-advance is supposed to advance in lieu of the player, after a time estimated to be the reading time of the text, and that's what it does here apparently. If the user is capable of skipping, there's no reason for the auto-skip not to.

However, if the reading time is more than three seconds, and if the auto-skip forces the game to wait longer than three seconds, then that would be a bug. But I don't think that's what you're describing.

**Comment by inismor** [comment]
Then what is the purpose of the wait tag? If you’re allowed to specify a number of seconds to wait, I feel as though Ren’Py should honor that number. Of course, the player could physically click through if they desired to, just like with auto-skip off, but the delay ought to be maintained.

 

In every instance I can recall, creators only use the wait tag to add dramatic pauses to the dialog. IMHO that pause should persist even if auto-skip is turned on. This is especially important because I can’t think of another way to replicate this behavior using other calls.

 

--r

**Comment by Gouvernathor** [comment]
I'm not very familiar with hard pauses (which are user-unfriendly and therefore bad), but I think if you put a `$ renpy.pause(3, hard=True)` between the first part of the line, and another line said by the `extend` character, it would work like you want.

But in any case, auto-skip is just there to press the spacebar instead of the user : if the user can skip, so can the auto-skip. That most likely won't change (I think there's an exception for voicing or possibly only self-voicing, but not even sure).

**Comment by renpytom** [comment]
I think it makes sense to avoid auto-forward when a specified time is in effect. I'll address this in the next major release.

**Comment by inismor** [comment]
Doesn't work. The wait tags are used to stretch the dialog over an animation of the background image that takes 6 seconds to complete.

 

Using a hard pause causes future say statements to wait until the animation is done before continuing.

 

--r

 

Russ Wetmore

 ***@***.***> ***@***.***

+1 (470) 525-3830

**Comment by morganwillcock** [comment]
> This . . . (wait for 3 seconds)is how . . . (wait for 3 seconds)it works!

I found the same issue. If you want a workaround you can apply a text speed to the whitespace. This will allow the whole line to be dismissed or skipped.

```py
waitLength = 3.0
cps = 1 / waitLength
strToSay = "This . . .{{cps={}}} {{/cps}}is how . . .{{cps={}}} {{/cps}}it works!".format(cps, cps)
```

Not ideal, but it might be enough for your use case.

**Comment by inismor** [comment]
Hmm. I think I can make it more palatable...

```
def pause_tag(tag, argument):
    cps = 1 / eval(argument)
    return [
        (renpy.TEXT_TAG, "cps={}".format(cps)),
        (renpy.TEXT_TEXT, " "),
        (renpy.TEXT_TAG, "/cps"),
    ]

    config.self_closing_custom_text_tags["pp"] = pause_tag

. . .

eileen "This . . .{pp=3.0}is how . . .{pp=3.0}it works!"
```

I just have to remember that the `{pp}` tag will add that space.

This'll do for now, I guess. It has the virtue of being backwards compatible once PyTom's fix is released. Thanks for the suggestion!

**Comment by mal** [comment]
You could also use `(renpy.TEXT_TAG, "space=0"),` instead of the space character if you would find it easier to not need to remember it adds a space. I believe it would still impact word wrapping though if you used it mid-word, so keep that in mind. 🙂
