### ISSUE TITLE
Smart loading of renpy scripts

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#3960]
So, `renpy.load_module` exists, but it loads ASTs the moment it's being called. So if I execute it at init -10, all ASTs inside will be executed at -10, even if I had stuff inside for init 500.
I need something that would allow me to "plug in" a renpy script (read module) and then just let renpy load it as usual, along other scripts. Is it possible to achieve? Or can be considered as a possible feature?

**Comment by Gouvernathor** [comment]
Not likely, because it would only work for init priorities greater than the current one : if you load the module at init -10, what should we do if we find an init -20 blocks in the file ?
Only allowing module loading in `python early` would render the issue moot, but that would be a pretty bad solution in and of itself.

**Comment by Booplicate** [comment]
I'd be 100% fine with not being able to load code from earlier than when I added the module. Since that'd be a mistake/bad design from the developer (can raise an exception, log a warning and run asap, or log and ignore, at your choice). I'm willing to add those "modules" before loading the rest of the game.

**Comment by Booplicate** [comment]
I think, even just being able to run a hook before this code
https://github.com/renpy/renpy/blob/f9d1070da7115d0267629ead4bbf396b785310b6/renpy/main.py#L551-L567
would do.

**Comment by mal** [comment]
Curious as to what the use case would be, and why a simple `.rpy` rather than an `.rpym` wouldn't be more suitable for this?

**Comment by Booplicate** [comment]
Making a system to control extra content for our game. Since the said content can and will interfere with the main game, it should only be loaded (and loadable) in certain cases.

> why a simple .rpy rather than an .rpym wouldn't be more suitable for this?

I'm working with `rpym`s. The PR I added adds a new way to load them.
