### ISSUE TITLE
The game takes a long time to load using the presplash_foreground and presplash_foreground

### ISSUE THREAD

**Issue by maLikiz** [renpy/renpy#3962]
`presplash_background.png` has a size of 500 by 500 pixels has a weight of 197KB.
`presplash_foreground.png` has a size of 500 by 500 pixels has 1.16KB. Most of it is a transparent background with a loading bar.

When using these images, the game takes **14 seconds** to load.
If I start using `presplash_background.png` as just `presplash.png`, then the game will load for **4 seconds**.

Renpy Version 7.4.11.2266
OS: Windows 10

**Comment by renpytom** [comment]
Can you please post an example game with this problem? I'd like to profile and see what's going on.

**Comment by maLikiz** [comment]
I sent you a link to the game by email, the subject of the letter.
Email Subject: "Issue #3962 (Link to the game)"

**Comment by Oppai-Man** [comment]
I did a local test and my game with presplash progress bar takes 17 seconds to load.
Without the presplash progress bar it takes 9 seconds.

My presplash progress bar is 1280x720

**Comment by renpytom** [comment]
Check out 8.1 or 7.6.

**Comment by Oppai-Man** [comment]
In Renpy 7.6

presplash_background.jpg and presplash_foreground.jpg →  6.5 seconds
presplash.jpg → 6 seconds.

In Renpy 7.6 it's much faster. Fantastic Work, renpytom!
I'm using my phone's stopwatch to track the time, so it might be a little imprecise.
