### ISSUE TITLE
Allow a config to disable arbitrary rpy compilation in a distribution

### ISSUE THREAD

**Issue by multimokia** [renpy/renpy#3967]
In an exported game, Ren'Py will still compile stray `.rpy` files, allowing anyone with renpy knowledge to easily bypass parts of games by simply adding a file which sets `config.developer` to `True`. This can technically be a security issue too, as anyone can easily add executable python code to run. (Which can either be malicious, or just cause the game to crash potentially)

For a more specific use case, being able to arbitrarily drop files in that can run code would bypass a framework I'm building that allows loading modules during runtime for mods. The issue is, if rpy compilation is allowed, then this system can be bypassed and it may lead to issues in the main game I'm making. As such, I'd love to be able to disable it to enforce the single entrypoint system I'm building.

**Comment by renpytom** [comment]
I don't plan to implement this - if we disallow .rpys, then people will just drop in .pys. (Or a .rpy with a low number than loads before everything else.)
