### ISSUE TITLE
always_shown_screens screen variables re-evaluated when moving through the renpy UI

### ISSUE THREAD

**Issue by Numerlor** [renpy/renpy#3970]
With a screen like this that shows it:
```rpy
screen Test():
    default obj = object()
    $ print(f"{id(obj)=:#x}")
    text "shown" align (.5, .5)
define config.always_shown_screens += ["Test"]
label start:
    "0"
```
It can be seen that the `default obj` reevaluated when moving between renpy screens, like going from the game to the game menu, starting a new game, or when the UI is hidden. 
I'd expect the screen to keep its state from the moment it's shown until the game shutdown (or until it's hidden by being removed from the always shown list), instead of getting a new one after interactions

**Comment by Numerlor** [comment]
> I'd expect it to be revaluated so it can show how some variables changes. The GUI alters them: like renpy.context_nesting_level() changes.

I expect the screen to be re-evaluated on interactions, but not the variables inside of it being swapped to new ones from the default

**Comment by Gouvernathor** [comment]
> I expect the screen to be re-evaluated on interactions, but not the variables inside of it being swapped to new ones from the default

You're right about this, but the test with id may not be a valid one (due to how rollback works for example). You can try ton instanciate an object with a memorization or randomization in attribute generation in the init, or a print...

**Comment by renpytom** [comment]
That's an incorrect expectation. 

I'll make it clear that how this works is by re-showing the screen in cases where it is hidden.

**Comment by renpytom** [comment]
Documentation updated in 8d3cd5bb8595131ed0bd013bb1558fc762a7fcd3 .

**Comment by Numerlor** [comment]
So for each... scene for a lack of a better word, a new instance of the screen is created? I don't entirely understand the update to the documentation.

If I want state to be persistent across all the instances of the screen do I just have to use a plain python global variable?

**Comment by Gouvernathor** [comment]
I guess that if you want a value to have a "continuity" (for lack of a better word) for the duration of the game, there's no particular relevance to putting its declaration in a screen.

**Comment by renpytom** [comment]
Yes, you'd want to use a global for this.
