### ISSUE TITLE
Renpy 8 games won't start

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#3971]
I may be mistaken but for what I've seen, for some very small minority of users R8 games won't start (Using 64 bits computers). The same games and the question works fine if exported with R7. All of them last versions. No errors, no logs, just won't start when clicking the executable.

Sadly, I cannot give you more details because it doesn't happens to me. For now most games still use R7 so the pool of these users are very small but it might be something to look into.

**Comment by renpytom** [comment]
I'll leave this open for a few days, but there's not much I can do until someone with the problem reports it.

**Comment by renpytom** [comment]
I'd especially be interested if these uses are running a supported operating system, or are still on Windows XP or Vista.

**Comment by renpytom** [comment]
Huh. 

I'd need someone with the problem to work with to diagnose this.

**Comment by hirkir** [comment]
I have this same problem

**Comment by morbil** [comment]
I have observed R8 and R7 64-bit executables fail to initialize their window on Win 10 and Win 11 64-bit. Likewise, no logs. I can get it to happen on one of my machines if using Remote Desktop (though not another, which is odd) with 64-bit binary, where the 32-bit one works.

**Comment by Gouvernathor** [comment]
I have sort of the same behavior : starting from the 31 october nightly, the 7.5 renpy.exe won't start on my computer, but the renpy-32.exe works. Both 32 and 64 versions of renpy8 work fine.

**Comment by BlindVagabond** [comment]
Same problem with all r8 builds, but all the r7 builds work just fine. Trying to create a new project, trying to delete persistent, or recompile gives the error "Launching the project failed. Please ensure that your project launches normally before running this command"
win10 64bit

**Comment by renpytom** [comment]
Without any leads, not much I can do here. It doesn't seem to be widespread.
