### ISSUE TITLE
Issue with filter_alt_text in extras.py Ren'Py 7.5.3

### ISSUE THREAD

**Issue by wagleunagi** [renpy/renpy#3972]
So I had TTS on while I was reading this line in Ren'Py 7.5.3 using Wattson's Kinetic Text Tags.

```python
"He takes the {atl=0.3,drop_text~#~5.0,bounce_text~2}oologic{/atl} art out of the oven and cuts a few slices for us.  It smells purifying."
```
It like keeps trying to read the new letters being generated and saying "o o o o o o o o o o o o o o o o o".  When I put this line into his Text Tag Game Demo using Ren'Py 7.4.11 it works fine.

I spent a few hours trying to see if I could fix it myself.  I eventually I found that removing these two lines of code from the extras.py fixed it.
```python
    if renpy.config.custom_text_tags or renpy.config.self_closing_custom_text_tags or (renpy.config.replace_text is not None):
        tokens = renpy.text.text.Text.apply_custom_tags(tokens)
```
But I assume that those two lines are important and shouldn't be outright removed.

Is there anyway that this can made into in a boolean so I can disable it easily without me having to modify the extras.py?

**Comment by Gouvernathor** [comment]
The lines were added in 7453701 to fix #3313.

I think adding a config variable to toggle that back and forth could be considered, but I'm also not keen on adding kinda obscure features just for specific tools outside renpy. If the tools use undocumented aspects of renpy, as atl text tags generally are, they should adapt to new versions of renpy and not the other way around.
Also, for this specific question, I understand that one could want custom text tags in some cases to be applied before self-voicing and in other cases after, but I'm not sure the switch should be made for whole games at a time, as it would be if using a config variable.
I also think this could be superseded by some kind of rework of text in renpy, enabling atl things in some way or another.

**Comment by renpytom** [comment]
I think the change in 7453701 was something we want to have. The text displayable is really meant to display text, not to display something that isn't exactly text. So I don't plan on changing Ren'Py to address this issue.

**Comment by MineRobber9000** [comment]
For the record, as a workaround, you could monkey-patch renpy.text.extras.filter_alt_text to apply a `renpy.text.extras.filter_text_tags(s,deny={"atl"})` before doing what the base method does. Not exactly a fix that can be put in Ren'Py proper, but for a simple spot fix, it's not terrible.
