### ISSUE TITLE
Developer tool to explore persistent data

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#3973]
Persistent is a feature that's a bit hard to test and understand for new creators. Unlike normal defaulted variables, they can't be tested just by startin a new game after changing the code, and when you don't use the console it's hard to have any feedback on the stored values.

So, a new tool accessible in the dev menu (Shift+D is it ?) which would list every entry name, for starters ? And possibly a button to show the entry's content, or delete it ?

**Comment by Elckarow** [comment]
could be nice to also implement this for multi-persistent data, though one issue i see with this is that unlike persistent data, multi persistent aren't 100% sure to be loaded (if there's a `if` check for instance)
```
init python:
    if var:
        thing = MultiPersistent("thing") # depends on `var`
```

**Comment by renpytom** [comment]
Seems reasonable. This might be considered to be a sub-screen of the existing variable - which could probably also be updated to include variables in other namespaces.
