### ISSUE TITLE
Problem with the size of element with xfill inside hbox with multiple children

### ISSUE THREAD

**Issue by maxthyron** [renpy/renpy#3999]
# Problem

Example, where hbox has two children: one has xfill as xsize, the other has constant xsize.

```
screen dumb_main():
    frame:
        background Solid("#d42abeb7") # Pink
        align (0.5, 0.5)
        padding (15,15)

        xysize (1600, 1000)
        has hbox

        frame: 
            padding (0,0)
            background Solid("#18df398f") # Green
            
            xsize 100 # Takes 100px from hbox
            
        frame:
            padding (0,0)
            background Solid("#492ec5") # Blue
            
            xfill True # Gets remaining xsize = 1600 - 100 = 1500

```
In this case everything fits inside main frame and looks like what I expect.

![image](https://user-images.githubusercontent.com/25431453/192344498-4f35750c-88f9-4144-9b33-c0a4c80a05e3.png)

The second case is when the xfill child is placed before const sized child

```
screen dumb_main():
    frame:
        background Solid("#d42abeb7") # Pink
        align (0.5, 0.5)
        padding (15,15)
        
        xysize (1600, 1000)
        has hbox

        frame:
            padding (0,0)
            background Solid("#492ec5") # Blue
            
            xfill True # Hbox gives all of the xsize of frame (1600)

        frame:
            padding (0,0)
            background Solid("#18df398f") # Green
            
            xsize 100 # Isn't accounted for and gets pushed out of the main frame region resulting in overall 1700 frame
            
```

Which results in unexpected(for me) behavior:

![image](https://user-images.githubusercontent.com/25431453/192344772-bd4c7aa3-7a8f-4479-8d99-905da7817375.png)

# Expected result

I mentioned this in discord and got response from Feniks who checked engine code and said that currently hbox doesn't distribute space with all children in mind, just left to right in order. Since first child has xfill all remaining space gets allocated to it, while I expect second child be placed inside main frame without need to explicitly set the size of the first child, and get this:

![image](https://user-images.githubusercontent.com/25431453/192346810-4317144b-8bb9-4755-8225-8f4f130c9681.png)

**Comment by Gouvernathor** [comment]
In a HBox or VBox, the first child is given all the available room and takes what it wants. The second gets the remaininig room, et cetera.
The version you're proposing would be a massively breaking change for existing games, but in addition to that it would also cause behavior issues : what if I have several children with xfill ?

**Comment by maxthyron** [comment]
The first thing I thougt about was multiple children with xfill. This means that space should be equally distributed between them and other edge cases.

Maybe adding other keyword like "flex" in css which works like that? Or new primitive "FlexBox"? To prevent said breaking changes.

So, right now the solution to explicitly set the size of child instead of using xfill?

**Comment by shawna-p** [comment]
I'll second the idea of a FlexBox displayable to avoid running into problems with existing hbox/vbox code. The issue as I see it is that you can't solve this by `box_reverse` since it just reverses the list of the children and still doesn't take into account any explicitly given sizes of children that are technically in the box before the adaptable size child, which feels counterintuitive. While this look can be achieved with explicit item sizes, I think it would greatly benefit mobile functionality to have more flexibility with layouts rather than relying on programmers to do the math beforehand.

**Comment by MiiNiPaa** [comment]
Run into the same issue recently. Currently there simply no way to create a dynamically sized hbox where displayable with xfill True sits between two displayables without that property without a lot of extra code. 
Another kind of box which will give each displayable space for minimum requred size and then distribute the rest of space between ones who want to fill it would be great. 
Alternatively maybe allow integers to be passed to the *fill properties, which will enable new behavior: True means old behavior, greedy fill, integer means new fill with value specifying weight. Displayables with xfill 2 would be twice as large as ine with xfill 1 in the same container.

**Comment by renpytom** [comment]
This is working as designed. 

To have what you want, Ren'Py would need to move to two-pass layout, from it's current one-pass layout model. I don't want that - what it gains in flexibility we'd lose in complexity.

**Comment by renpytom** [comment]
In retrospect, I've decided to change this in 5505c01d0aa0cac9e5d3be2cff69d0936a4d8e46.
