### ISSUE TITLE
Android build not escaping app_name in strings.xml

### ISSUE THREAD

**Issue by KevinDHunter** [renpy/renpy#4000]
Ren'py 7.4.11.2266 (yes, a bit old)

I configured an Android build with a (long) app name that included an apostrophe.  (Well, technically, a "single quote character." "'")  

Ren'py accepted it, but when I ran the build I got an error:
```
The reference to entity "S" must end with the ';' delimiter
```
pointing to the `strings.xml` file.  Removing the apostrophe fixed it, with no problem, however I would have expected one of two things:

1. If you _can't_ include certain characters an an Android app name, don't let the configuration process accept them.

2. Alternately, "properly" escape any non-alphanumeric characters when generating the `strings.xml` file so that they work.

**Comment by renpytom** [comment]
I'm unable to repeat this with Ren'Py 8.0. Can you please post the .android.json from your project? At least for me, the apostrophe in "Ren'Py Test Game" worked.
