### ISSUE TITLE
Renpy error

### ISSUE THREAD

**Issue by Deluxe4arms** [renpy/renpy#4001]
I'm trying to port a game to ios but it says the selected project is not writable. How would I fix this?
<img width="767" alt="Screen Shot 2022-09-28 at 8 38 39 PM" src="https://user-images.githubusercontent.com/114636700/192933248-723d87a2-b5e0-411f-b04f-a68619a4b68b.png">

**Comment by renpytom** [comment]
You probably need to select a different directory for Ren'Py to write to.

**Comment by miyakopubl** [comment]
I have the same problem.
Details are as follows:

1-1. "Select Xcode project directory" in iOS build from launcher.
*In this case, for some reason, the directory is selected even after pressing "Cancel".
1-2. then rename or move the location of the directory folder selected in 1-1.
1-3. if I try to "Select Xcode project directory" from the launcher again, I always get an error message.
*Error message is the same as Deluxe4arms' post.

Perhaps there is something in the launcher or in renios that is robustly preventing you from specifying or changing directories.

I can solve this somewhat forcefully by either of the following methods.

2-1. Ignore "Select Xcode project directory" and select "Create Xcode directory". Then a folder with the same name as the folder created in 1-1 will be generated in the exact same location.
Or
2-2. manually revert to the same location with the same name as the file created in 1-1.

I'm just glad that Ren'Py works so accurately on the Mac and is so compatible with iOS.
So this is a somewhat extravagant problem report.
