### ISSUE TITLE
GL2 problem with large images in a viewport

### ISSUE THREAD

**Issue by rex-nihilo** [renpy/renpy#4009]
For a map, I need to use a large image (5120x2880) in a viewport. But the image has a problem from 1440 pixels vertical.

If I disable GL2, it's ok.
If I use Renpy 7.4.11 and previous version, it's ok.

Démo:
[BUG-viewport-GL2.zip](https://github.com/renpy/renpy/files/9708783/BUG-viewport-GL2.zip)

**Comment by renpytom** [comment]
Can you please post the log that Ren'Py creates when starting the game? 

I tried it here, both normally and with the maximum texture size overridden to 1024x1024, without problems. 

If you can also let me know what you mean by "a problem", that might help.

**Comment by rex-nihilo** [comment]
**LOG:**
```
Thu Oct  6 20:31:03 2022
Windows-7-6.1.7601-SP1
Ren'Py 7.5.3.22090809
 

Bootstrap to the start of init.init took 0.19s
Early init took 0.01s
Loader init took 0.01s
Loading error handling took 0.04s
Loading script took 0.34s
Loading save slot metadata. took 0.02s
Loading persistent took 0.00s
Faled to initialize steam: WindowsError(126, 'Le module sp\xe9cifi\xe9 est introuvable')
Set script version to: (7, 5, 3)
Running init code took 0.10s
Loading analysis data took 0.04s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.05s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: "Couldn't load nvlib." (can be ignored)
Creating interface object took 0.00s
Cleaning stores took 0.00s
Init translation took 0.08s
Build styles took 0.01s
Load screen analysis took 0.03s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.09s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.18s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'ATI Radeon HD 5570'
Version: '4.2.12002 Compatibility Profile Context 9.12.0.0'
Display Info: None
Screen sizes: virtual=(1280, 720) physical=(1280, 720) drawable=(1280, 720)
Maximum texture size: 4096x4096
```

I know, my OS is outdated, my computer is outdated, and especially my video card is outdated, even if the drivers are up to date. This is probably the origin of this problem, but for the moment I can't change that.

Here is a screenshot of the problem using a grid image (5120x2880) inside a viewport:

![screenshot](https://user-images.githubusercontent.com/60070641/194395666-16c94cf4-0a74-4c4f-b00b-cd4e072b41b4.png)

If the size of this image exceeds 2048px horizontally or vertically, then from 1440 pixels vertically (always 1440 vertically), there is a glitch. Same result with Renpy 7.5.3 or 8.0.3 version.

If I disable GL2, or if I use Renpy 7.4.11 or a previous version, the image is correct. So, my temporary solution is to develop with GL2 disabled.

**Comment by renpytom** [comment]
I don't see what I can do when there's a driver issue with a 10 year old GPU. I'm closing this issue.
