### ISSUE TITLE
Unrecognized Steam Controller

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#4010]
Recently I received a bug report from a player on my game as follows:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
error: Couldn't find mapping for device (0)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 4138, in interact_core
    ev = renpy.display.controller.event(ev)
  File "renpy/display/controller.py", line 230, in event
    start(ev.which)
  File "renpy/display/controller.py", line 156, in start
    c.init()
  File "src/pygame_sdl2/controller.pyx", line 160, in pygame_sdl2.controller.Controller.init
error: Couldn't find mapping for device (0)

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Our Life 1.6.0
Sat Oct  1 17:39:12 2022
```

The player tells me they have a Steam Controller attached which seems to be the cause of this issue. The error occurs occasionally when launching the game from Steam, but they can close it and try again to get past it. The player also noted:

> After the error, the game will start but I noticed I couldn't access Steam's overlay, but that the controller's bindings still worked in game. So maybe the error has to do with the overlay/controller interactions somehow since the controller does still work after the error fires off once.

I haven't updated to 7.5+ with this game as it was developed on 7.3.5 and had a kind of iffy update to 7.4+ with gl2 due to a custom legacy method of displaying sprites, so I have gl2 disabled for the game to function properly. The game is near completion so I've generally been planning to stick with 7.4.11 until it's completed, but I'd consider updating if it would help solve this problem.

**Comment by renpytom** [comment]
It looks like error handling was added to this case seven months ago, which means it was added in 8.0.0 and 7.5.0.
