### ISSUE TITLE
4K 60 fps video capped to 30 fps

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#4015]
Hi,

I'm capable of playing 1080p 60 fps video on Ren'py, but when it comes to 4K, not matter whether I use VP8 or VP8 with a very low bitrate, the 4K video is always limited to 30 fps.

I'm using this video for test because it has a lot of motion, but you can use any other.

[4k_60_gow.webm](https://user-images.githubusercontent.com/4298411/194766265-b336ace9-5507-44d8-be57-e38a944a52da.webm)

Can you play 4K 60 FPS videos on ren'py?

**Comment by renpytom** [comment]
This plays at 60fps for me. (There have been some relevant changes in 8.1.)
