### ISSUE TITLE
Long press on PC

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#4020]
Generally requiring to long press (or click & hold) can be annoying, but in some cases it's great to make sure users don't do an action that has some big consequences. Currently long press seems to be supported only for mobile platforms, would be cool to be able to use it for PC builds, too.

Some use cases:
- craft system
- cutscene skip
- story choices (because rollback doesn't fit all games)

What may be needed:
- perhaps it should be compatible with the existing long press for mobile platforms?
- some way to show a special image when the long press is in progress (like how renpy has idle/hover/etc variants)?
- maybe a separate action for long press? `alternate` uses RMB on desktop

**Comment by via-my** [comment]
Maybe it would be a good idea to also implement a double click action?
In case like "double click the image to open it".

**Comment by Gouvernathor** [comment]
If I'm not mistaken, the long press is a mobile equivalent of the right-click. So, if we add the long press on PC, either we make it generate a right-click event, and I don't see it being very useful on PC, or we make it seperate thing which makes it inaccessible on mobile.

The double-click would be considered, but probably deserves a separate issue.

**Comment by HorBro38** [comment]
> If I'm not mistaken, the long press is a mobile equivalent of the right-click. So, if we add the long press on PC, either we make it generate a right-click event, and I don't see it being very useful on PC, or we make it separate thing which makes it inaccessible on mobile.

Long press as an alternative to right click could be useful in a few fringe cases (specifically on the Mac platform) that it may be a good idea to have.

**Comment by Booplicate** [comment]
> if we add the long press on PC, either we make it generate a right-click event, and I don't see it being very useful on PC, or we make it seperate thing which makes it inaccessible on mobile.

Ideally right click/double click/long press should be separate (at least for desktop platforms).

**Comment by Gouvernathor** [comment]
Yes, but that's the issue : we can't separate them for desktop platforms and merge them on mobile.
It would either mean that a long press would unpredictably trigger one behavior or the other on mobile, or that the desktop-long-press behavior is unavailable on mobile. Both would be bad options, in my opinion.

@HorBro38 I think having a long press resulting in a right-click on (some) desktop platform(s) can make more sense, but it's contradictory in purpose with Boop's poposition.

**Comment by Org-gith** [comment]
It's already possible to have long click, double click and so on using listener screens. Though it's very annoying to do, and involve having 2-3 screens communicating with each other. Having it under shortcut function would definitely make it much easier to use.

**Comment by renpytom** [comment]
I'm closing this, as #4099 covers it.
