### ISSUE TITLE
MouseMove does not work after maximizing the window through the green button in macOS.

### ISSUE THREAD

**Issue by stunnings** [renpy/renpy#4023]
MouseMove does not work after maximizing the window through the green button in macOS.

The full screen in Windows does not cause problems, it only occurs in macOS.
It is estimated that it does not occur in Ren'py 7.4.x.

**Comment by renpytom** [comment]
I've been unable to solve this, as it looks like it's coming from a level below Ren'Py. I'm going to document this as working "if possible."
