### ISSUE TITLE
The Home, End, Insert, Delete keys on the numpad keyboard do not work in console

### ISSUE THREAD

**Issue by maLikiz** [renpy/renpy#4030]

**Comment by Gouvernathor** [comment]
That's true for the console, but also for any renpy input.

**Comment by Gouvernathor** [comment]
So, after an in-depth analysis on my part, it comes from pygame, because we check for `"K_HOME"` and it specifically matches the home key located on the right of the "insert" key (on my keyboard at least), but doesn't match the one from the keypad, be it with or without the NumLock.
