### ISSUE TITLE
Error when trying to port

### ISSUE THREAD

**Issue by Soukly** [renpy/renpy#4033]
//hello, I have this error when making a port and I really don't know how to solve it since I'm a newbie in this field.

Ren'Py 8.0.3.22090809

Updating project

Creating resource directory.

Packaging internal data.

I am using Gradle to build the package.
To honor the JVM configuration for this build, a new JVM will be created. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
The daemon will stop at the end of the build after processing

FAIL: The compilation has failed with an exception.

* What failed:
A problem occurred while setting up the ':app' project.
Could not create the ':app:assembleRelease' task.
The ':app:lintVitalRelease' task could not be created.
The SDK location was not found. Set the location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file to 'C:\renpy-8.0.3-sdk\rapt\project\local.properties'.

* Test:
Run with the --stacktrace option to get the stack trace. Run with the --info or --debug option to get more logs. Run with the --scan option to get complete information.

* Get more help at https://help.gradle.org/

BUILD FAILED in 14s

**Comment by renpytom** [comment]
Is this the same error reported in #4034 ?

**Comment by senpai1940** [comment]
> ¿Es este el mismo error informado en #4034 ?

No, that mistake is another. It happened to me in one of the attempts I made to fix the problem.

**Comment by renpytom** [comment]
Do you have the rest of the output from gradle, before this error?

**Comment by senpai1940** [comment]
> 



> ¿Tiene el resto de la salida de gradle, antes de este error?
No sorry I only have #4034 and this one.

**Comment by RuolinZheng08** [comment]
I'm getting the same error on mac. This is the entirety of the output file.
```
Ren'Py 8.0.3.22090809

Updating project.

Creating assets directory.

Packaging internal data.

I'm using Gradle to build the package.
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:bundleReleaseResources'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Applications/RenPy/renpy-8.0.2-sdk/rapt/project/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s




The build seems to have failed.
```
