### ISSUE TITLE
[Request] Better text substitutions

### ISSUE THREAD

**Issue by morbil** [renpy/renpy#4035]
So, we have `say_menu_text_filter` in order to check and replace lines of text in `say` or `menu` statements. This works alright, except that it runs into a similar issue as translations where if you want to change some text, you need to also update the replacement value or it will no longer function.

I have two suggestions, the first is probably easier, the latter more powerful. 

1. Pass the text id into `say_menu_text_filter`. This way, much like translations, the id could be the same and the edits could go through without breaking the substitution. 
As an aside, having a command in the launcher to automatically append the `id` clause for those statements the same way it can append `from` clause for the `call` statement would be super useful

2. This suggestion is for a new statement, `substitute`. `substitute` would work like `translate` allowing you to edit the AST rather than simply replace strings. This would look like this:

Given this
```renpy
"The rain in Spain falls mainly in the plain" id start_12783876
```

You could sub with this
```renpy
substitute start_12783876:
    "The walls in the mall"
    "Are totally, totally tall"
```

You could also add conditions for the substitution

```renpy
substitute start_12783876 if b_is_valley_girl:
    "The walls in the mall"
    "Are totally, totally tall"
```
Which would act like

```renpy
if b_is_valley_girl:
    "The walls in the mall"
    "Are totally, totally tall"
else:
    "The rain in Spain falls mainly in the plain"
```
As for why not just using the conditions like the example, it's mostly for modding. Also, menus look awkward with a lot of ifs.

**Comment by renpytom** [comment]
I don't think this is something I'm likely to add to Ren'Py. I don't see this as useful enough to be worth including in the engine.
