### ISSUE TITLE
config.enter_transition causing issues with Character Callbacks when not 'None'

### ISSUE THREAD

**Issue by RanaStrange** [renpy/renpy#4036]
Unsure how solvable this is, but calling the game_menu with a transition seems to cause issues with Character Callbacks. Specifically, when a game_menu with a transition is called, it seems to call either (at least) a `"show"` or `"show_done"` event even after `"slow_done"` has already been called, which is a problem when it comes to looping audio.

[This has been noted by someone else on the forums.](https://lemmasoft.renai.us/forums/viewtopic.php?p=336186#p336186)

**Comment by renpytom** [comment]
I can't repeat this, which probably means it's been fixed by  17c9c6f62c81b723c0866ac6c42b64f97b8d327e .
