### ISSUE TITLE
Ability to set coordinate position of ren'py window or auto center ren'py window after each rezise

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#4062]
https://www.renpy.org/doc/html/other.html?highlight=physical_size#renpy.set_physical_size
Just a minor idea to make it slightly better because currently, it will use the previous position coordinate to resize the renpy window.
For example, if the game is started at 800x600 resolution, it will be correctly centered in the center of the monitor, but then if you resize it to, for example, 2560x1440, it will start resizing at the top left edge of the previous size and expand from there. So the screen will be not centered anymore (and most likely go out of the monitor, so you have to drag it back manually in the center).

**Comment by renpytom** [comment]
I don't think this is something I'm likely to do. Every other program that I know resizes by expanding based on the side or corner that's being dragged. That's something people expect, and so I wouldn't want Ren'Py to do something different.

**Comment by Org-gith** [comment]
It's no problem, just to be clear this was refering to a change of resolution using "Preference("display", x.x)" or "set_physical_size", the drag option it makes sense that it should remain the same. In any case, it's nothing important.
