### ISSUE TITLE
Prefix for saves

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4067]
I just thought of this and I don't know if it already exists in renpy, but I wanted to share it. it would be to add a prefix to the saved games. For example: `prefix_[page]_[name] or prefix-[page]-[name]`.

In this way, it would be possible to make a filtering system for saves, for example. If we have some DLC that adds extra content to the game, but we don't want those saves to be shown next to the existing saves of the base game, this would make it easier to differentiate the saves.

`renpy.save(filename, extra_info='', prefix_name=None)` /` FileSave(name, prefix_name="dlc_1")`

"If it is None, the save items will be saved in the same way as by default, but if it is a string, a prefix will be appended to the file name. Saved games with prefixes will not be visible and can only be accessed with `renpy.filter_list_saves(prefixname)`."

`renpy.filter_list_saves(prefixname)` (the "filter_list_saves" name is as an example)

"Returns a list of non-empty save slots. Only slots have prefixname are returned. “
 
[(page,name),(page,name)]

Load Example:
```
screen extra_dlc_one_load_save_list():
    for (page, name) in renpy.filter_list_saves("dlc_1"):
        frame:
            background "gui/Saves/save_load_frame.png"
            xsize 330
            ypos 50
            left_padding 10
            right_padding 10
            bottom_padding 20

            button:
                xpos 60
                ypos -19
                xsize 230
                ysize 610
                action FileLoad(name, confirm=False, page=page)
                activate_sound audio
                add Transform(FileScreenshot(name), crop=(190, -8, 200, 500))
                add Transform("gui/Saves/slot_frame.png", crop=(0,0,200,700))
                text FileSaveName(name) size 16 xalign 0.5 ypos 373 font "gui/fonts/AlteHaasGroteskBold.ttf" color "#fff" outlines [(2,"#67a2c7",0,0)]
                text file_text size 16 xalign 0.5 ypos 420 font "gui/fonts/AlteHaasGroteskBold.ttf" color "#fff" outlines [(2,"#67a2c7",0,0)]
                key "save_delete" action FileDelete(name)
                mouse "hover"
```

Save Example:

```
screen extra_dlc_one_save():
    for i in range(gui.file_slot_cols * gui.file_slot_rows):

        $ slot = i + 1
        $ file_text = "\n%s: %s" % (
            FileSlotName(slot, 4),
            FileTime(slot, format='%B %d, %Y \n(%I:%M%p)', empty=__("empty"))
            )

        frame:
            background "gui/Saves/save_load_frame.png"
            xsize 330
            ypos 50
            left_padding 10
            right_padding 10
            bottom_padding 20

            button:
                xpos 60
                ypos -19
                xsize 230
                ysize 610
                action FileSave(slot, confirm=False, prefix="dlc_1")
                activate_sound audio
                add Transform(FileScreenshot(slot), crop=(190, -8, 200, 500))
                add Transform("gui/Saves/slot_frame.png", crop=(0,0,200,700))
                text FileSaveName(slot) size 16 xalign 0.5 ypos 373 font "gui/fonts/AlteHaasGroteskBold.ttf" color "#fff" outlines [(2,"#67a2c7",0,0)]
                text file_text size 16 xalign 0.5 ypos 420 font "gui/fonts/AlteHaasGroteskBold.ttf" color "#fff" outlines [(2,"#67a2c7",0,0)]
                key "save_delete" action FileDelete(slot)
      
                mouse "hover"
```

Maybe this is not interesting, but a filtering system would be a good idea, since it would be possible to catalog the saved games to differentiate them from the rest if necessary.

**Comment by Neyunse** [comment]
> Using the [json attached data](https://www.renpy.org/doc/html/config.html#var-config.save_json_callbacks) makes probably more sense to filter saves than having to parse a string. Especially if the filtering has to be the same for every game, if we include it a a renpy function.

but config.save_json_callbacks.append does not apply to all save files? From what I saw from the example and as I understand it, this is added to all files, not to some specific ones. 🤔

**Comment by Neyunse** [comment]
and I don't know if it would be a good idea to add several of these, since it would load the games with unnecessary things.🤔 ```
init python:
    
    def jsoncallback(d):
        d["dlc_1"] = false
        d["dlc_2"] = false
        d["dlc_3"] = false
        #...

    config.save_json_callbacks.append(jsoncallback)
```

**Comment by Gouvernathor** [comment]
The functions are called on any and all saves made after the said functions are added to the game. Which enables each creators to add their specific data without being limited by what the engine builds in or be bothered with data not useful to them. And since it's dicts being handled, there's a lot of easy mechanisms to allow for previous save which haven't been treated with the json data.

> it would load the game with unnecessary things
If you don't want to include them, then don't, but why would it be better to include them in strings rather than in json dicts ?

**Comment by morbil** [comment]
@Gouvernathor File names are faster to filter by, indeed there's even renpy.list_slots which takes a regex to filter used slots by name. But of course, that doesn't scale well, so I would agree JSON is better place for it. I would suggest, though, including some formal json attribute filtering with the "built in" actions would be more generally useful for people, as you more or less need to remake the file_slots screens completely if you want to do any sort of filtering in the pagination, including versions or multiple start points. 

Not sure how practical that would be with the page names sort of "enforcing" a slot structure that's more difficult to work around. But an "official" filtered view might be a nice-to-have

**Comment by Gouvernathor** [comment]
> But an "official" filtered view might be a nice-to-have

I don't think so, for one main reason : most creators (by far) don't need it at all, and complicating the screen would make it more difficult for new creators to learn how renpy works.
But even if we wanted to include a filtering behavior in the default screen, what data would we look for ? The name of the main character, as in my game ? The dlc being toggled, as in Neyunse's ? Even among the creators who use save informations, there is no single data which would be interesting for most of them.
That's typically the kind of thing or framework you should share in a gist or in a post on lemmasoft, but not include in the engine.

**Comment by morbil** [comment]
> and I don't know if it would be a good idea to add several of these, since it would load the games with unnecessary things.🤔
> 
> ```
> init python:
>     
>     def jsoncallback(d):
>         d["dlc_1"] = false
>         d["dlc_2"] = false
>         d["dlc_3"] = false
>         #...
> 
>     config.save_json_callbacks.append(jsoncallback)
> ```

I would say, rather than one per DLC, you could simply have 

```python
d['active_dlc'] = ['dlc_1', 'dlc_3']
```

Then one simple change you can make is, rather than filtering saves, you can disable them from loading (which is something I do for un-supported versions). 
Add this to file_slots:
```python
                    python:
                        saved_active_dlc = FileJson(slot, key='active_dlc') or ''
                        valid_file = title == 'Save' or not saved_active_dlc or [dlc in installed_dlc for dlc in save_active_dlc]
                        
                    button:
                        if valid_file:
                            action FileAction(slot)
                        else:
                            action None
```
And you can style a bit more for the inactive slots. Also, in this case, installed_dlc is a global with all of the dlc that are playable.

**Comment by morbil** [comment]
> > But an "official" filtered view might be a nice-to-have
> 
> But even if we wanted to include a filtering behavior in the default screen, what data would we look for ? 

Pass a callable that receives the slotname and json and returns if the file should be included, which is more or less what every filtering function in python does. 

I mean, in a sense `FilePage` action is adding a filter, just filtering by "page". In a sense, it's just generalizing that concept.
