### ISSUE TITLE
about the `renpy.seen_...` and `renpy.mark_..._seen` functions

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#4069]
the functions `renpy.seen_` use the `in` operator to check whether something has already been seen
`return filename in renpy.game.persistent._seen_audio` renpy.seen_audio for instance

and to "mark" something as "seen", a dictionnary is used
`renpy.game.persistent._seen_audio[filename] = True` renpy.mark_audio_seen

the values of the dict aren't being used anywhere...
wouldn't it make more sense to use a `set` for that or is it because of backwards comptability that a dict is used?

**Comment by renpytom** [comment]
These predate the addition of sets to the Python language. 

Changing it isn't really worth breaking old saves.
