### ISSUE TITLE
Worse movie playback performance when going from python 2.7 to python 3.9

### ISSUE THREAD

**Issue by Elrath12** [renpy/renpy#4070]
Upgrading from Renpy 7.4.4 or 7.5.3 to Renpy 8.0.0 or Renpy 8.0.3 seems to decrease performance of movies with an fps reduction of around half and a twice as big cpu utilization increase.

It might have something to do with python 3.9 or the libraries that Renpy uses as replacing the entire renpy folder of  8.0.3 with 7.5.3 still gives the same result.

The movie in question has the following properties:
Frame rate: 60
Resolution: 1920 x 1080 (HD)
Codex: Vp9
Bitrate: 18625 kb/s (is high, but renpy 7.5.3 handles it just fine)
Sampling: yuf444p (yuf420 did not seem to have this issue)
SAR 1:1
DAR 16:9

**Comment by renpytom** [comment]
Do you have the movie file in question?

**Comment by PastryIRL** [comment]
I'm facing the same issue after upgrading to RenPy 8.0.3 from 7.4.11.

I put together a sample project, showcasing playback of the same video in VP9 and VP8 formats.
https://github.com/PastryIRL/vp9_test

The project is runnable in both RenPy 7.4.11 and 8.0.3, so you can compare the results.

Additionally, I'm attaching the VP9 video in question, if you'd like to work with it separately.

[vp9test_1.webm](https://user-images.githubusercontent.com/100724468/201281202-b2715f4d-80da-4bf6-a6f0-1236b6019ee9.webm)

**Comment by renpytom** [comment]
I believe this is fixed in 8.1. (It was likely due to a problem with files being treated as python file-like objects, which take a slower path.)
