### ISSUE TITLE
register_channel requires an identifier ?

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4071]
Some issues related to queueing audio files were suddenly solved when the creator removed the spaces in the channel name, registered using register_channel. Are there constraints requiring the channel name not to contain spaces, or to be a valid identifier ?
If so, it should either be documented (I can do it), or be fixed to allow any string.

**Comment by renpytom** [comment]
It should be documented, for register_channel only. Channels with spaces are used internally.
