### ISSUE TITLE
renpy 7.4.11 build large android project 

### ISSUE THREAD

**Issue by Rreniel0909** [renpy/renpy#4073]
Ren'Py 7.4.11.2266

Updating project.

Creating assets directory.

Packaging internal data.

I'm using Gradle to build the package.
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :renpyandroid:preBuild UP-TO-DATE
> Task :renpyandroid:preReleaseBuild UP-TO-DATE
> Task :renpyandroid:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :renpyandroid:packageReleaseRenderscript NO-SOURCE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:generateReleaseBuildConfig
> Task :app:javaPreCompileRelease UP-TO-DATE
> Task :app:generateReleaseResValues UP-TO-DATE
> Task :app:generateReleaseResources UP-TO-DATE
> Task :renpyandroid:compileReleaseRenderscript NO-SOURCE
> Task :renpyandroid:generateReleaseResValues UP-TO-DATE
> Task :renpyandroid:generateReleaseResources UP-TO-DATE
> Task :renpyandroid:packageReleaseResources UP-TO-DATE
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease UP-TO-DATE
> Task :renpyandroid:extractDeepLinksRelease UP-TO-DATE
> Task :renpyandroid:processReleaseManifest UP-TO-DATE
> Task :app:processReleaseManifest
> Task :renpyandroid:compileReleaseLibraryResources UP-TO-DATE
> Task :renpyandroid:parseReleaseLocalResources UP-TO-DATE
> Task :renpyandroid:generateReleaseRFile UP-TO-DATE
> Task :renpyandroid:generateReleaseBuildConfig UP-TO-DATE
> Task :renpyandroid:javaPreCompileRelease UP-TO-DATE
> Task :renpyandroid:compileReleaseJavaWithJavac UP-TO-DATE
> Task :renpyandroid:bundleLibCompileToJarRelease UP-TO-DATE
> Task :app:mergeReleaseResources
> Task :app:processReleaseResources
> Task :app:compileReleaseJavaWithJavac
> Task :app:compileReleaseSources
> Task :app:prepareLintJar UP-TO-DATE
> Task :renpyandroid:prepareLintJarForPublish UP-TO-DATE
> Task :app:lintVitalRelease
> Task :renpyandroid:bundleLibRuntimeToJarRelease UP-TO-DATE
> Task :app:dexBuilderRelease
> Task :app:checkReleaseDuplicateClasses UP-TO-DATE
> Task :app:mergeExtDexRelease UP-TO-DATE
> Task :app:mergeReleaseShaders UP-TO-DATE
> Task :app:compileReleaseShaders NO-SOURCE
> Task :app:generateReleaseAssets UP-TO-DATE
> Task :renpyandroid:mergeReleaseShaders UP-TO-DATE
> Task :renpyandroid:compileReleaseShaders NO-SOURCE
> Task :renpyandroid:generateReleaseAssets UP-TO-DATE
> Task :renpyandroid:packageReleaseAssets UP-TO-DATE
> Task :app:mergeDexRelease
> Task :app:mergeReleaseAssets
> Task :app:processReleaseJavaRes NO-SOURCE
> Task :renpyandroid:processReleaseJavaRes NO-SOURCE
> Task :renpyandroid:bundleLibResRelease NO-SOURCE
> Task :app:mergeReleaseJavaResource UP-TO-DATE
> Task :app:collectReleaseDependencies UP-TO-DATE
> Task :app:sdkReleaseDependencyData UP-TO-DATE
> Task :app:mergeReleaseJniLibFolders UP-TO-DATE
> Task :renpyandroid:mergeReleaseJniLibFolders UP-TO-DATE
> Task :renpyandroid:mergeReleaseNativeLibs UP-TO-DATE

> Task :renpyandroid:stripReleaseDebugSymbols UP-TO-DATE
WARNING: Compatible side by side NDK version was not found for android.ndkVersion '21.3.6528147'
Compatible side by side NDK version was not found for android.ndkVersion '21.3.6528147'

> Task :renpyandroid:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :app:mergeReleaseNativeLibs UP-TO-DATE

> Task :app:stripReleaseDebugSymbols UP-TO-DATE
WARNING: Compatible side by side NDK version was not found for android.ndkVersion '21.3.6528147'
Compatible side by side NDK version was not found for android.ndkVersion '21.3.6528147'

> Task :app:validateSigningRelease UP-TO-DATE
> Task :app:packageRelease
> Task :app:packageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > value (4296219855) > 0x00000000ffffffffL

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13m 17s
44 actionable tasks: 11 executed, 33 up-to-date

The build seems to have failed.

**Comment by renpytom** [comment]
7.4.11 isn't supported - please try 7.5 or 8.0. That being said, there are limits to how big your project can be on Android - IIRC, there's a natural 2GB limit to the size of an APK that can be installed.
