### ISSUE TITLE
f-string issue

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#4084]
Take this code for example

```renpy
python early:
    __TEST = "test"
    print(f"{__TEST}")
```

It throws `NameError: name '__TEST' is not defined`. Perhaps this happens because of how renpy mangles names. Can something be done about it?

**Comment by Gouvernathor** [comment]
This can be circumvented using the .format method.
The name-mangling could be patched to include interpolations inside f-strings, but tbh the system is a bit archaic, rarely used and barely documented, and it would be simpler to just say in the doc that it doesn't work with f-strings and that .format should be used instead.

**Comment by Gouvernathor** [comment]
You can look there https://github.com/renpy/renpy/blob/91ecbb8719843b9af7a8e7d69df370c69e64b5a5/renpy/lexer.py#L175
I wouldn't say it's the f-strings that don't work, but rather the name-mangling that's not covering the latest language evolutions.

**Comment by Gouvernathor** [comment]
So, I looked more into it. The name-munging arrives very early in renpy parsing, really even before what we actually call parse time, aka "python early". It works upon a very basic syntaxic analysis, not based upon any third-party module, which considers all that's inside quotes as priviledged. It does not differenciate a prepending f, r, b or u before a string with any other possible word found in script.
To enable this for f-string, we would need to enhance this analysis to allow parsing the insides of f-strings, and that is a big nest of vipers - consider the possibly protected (doubled) braces, and the : and ! modifiers for example, that quickly becomes a mess. not to mention that it would imply python parsing _within_ string parsing _within_ python parsing, which is very far from the way it's currently implemented.
Not very likely to happen.
