### ISSUE TITLE
Two sounds on two different channels/mixers with a fadeout of 0.1 playing at the same time may generate a >200 db blast noise

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#4088]
If two sounds on two different channels/mixers with a fadeout of 0.1 play at the same time, it will generate a very loud blast noise under the condition that one of the audio mixers involved is set below 100% (below 1.0 value). If the mixers involved are set at 100% value, the problem will not occur.
It happened randomly on my project, I had a good fright, and the project is not using the new way of calculating mixer sound that Tom introduced recently, so this has nothing to do with a recent commit I think. I replicated the issue on a template project made on 8.0.3.

Here is a video showcasing the problem (I lowered the audio of the video so that it's safe to hear, needs to be put quite high to hear anything). In the first part of the video, I lower one of the mixers involved, and then play the two sounds together which creates the issue, then on the later part I change back the mixer to the 100% value and try again, and under this condition, the problem doesn't occur.
https://streamable.com/h6bb7s

Template project made on 8.0.3, **make sure to have the audio coming out of the speaker/headphone set to no more than 5% to avoid enduring the sound blast**. The code added in the template is on the screens.rpy, line 261
[testaudio2.zip](https://github.com/renpy/renpy/files/9983994/testaudio2.zip)

**Comment by Org-gith** [comment]
Another problem found and I think directly linked to this:
- any fadeout below 0.28 have their pan untreated/unreliable once one or two mixers are lowered, and that two sounds with fadeout <0.28 play close to each other (same condition as above, basically except it's concerning the pan and the threshold for this specific problem is below 0.28 and not 0.16).
For example, a sound that should play on the right ( pan set to 1), will play on the left instead (pan -1). Or a sound with a pan 0 (center), will play on the left instead. Somehow it always ends up changing the pan to the left side.
The problem seems to be related to the mixer, I've tried to look in the source code and try different things, like trying different sizes of buffer but it didn't help. 
I had to conclude I'm too unqualified to solve this, just hoping this information might help track the issue.

**Comment by Org-gith** [comment]
The problem that I'm facing is there seems to be no good solution right now to solve the clicking noise problem because if you apply a very small fadeout you run into the issues I reported on this thread, and a 0.28 fadeout which solves the aforementioned problems (on my computer at least) enter the territory of being too noticeable, it basically acts like a buffer with a massive delay. From my testing, only a fadeout of =< 0.1 would be acceptable to solve the clicking issues without creating other problems at the same time.

Was wondering if it's possible to compile a librenpython.dll containing the latest SDL2 version or something relative to the latest audio changes to test it out, it's because I noticed a lot of issues that are in the same family as theses issues have been reported on their GitHub, and they don't actually post their bugfixes in the changelog, but they actually fixed a lot of things. There is a very small chance that this problem could have been fixed in the past 3 years, I don't know if a new SDL2 compile on the latest version breaks things though, just an idea if it's easy enough to try.

**Comment by renpytom** [comment]
Fixed by a rewrite of how audio fading works.

**Comment by Org-gith** [comment]
Big thanks for this boss, it works perfectly!

**Comment by Org-gith** [comment]
I have to report that it triggered this bug once for me after this patch while working on the project, but it's impossible to really replicate it reliably compared to before, it seems so much harder to do it right now and it fixed the pan bug, so definitely a big improvement.
But I think to totally eradicate the bug, there might still need a slightly higher value to the fadeout to hit the ballpark where it doesn't trigger it on any computers? I have set the fadeout to 0.05 for now as it is still unnoticeable to the ears but much higher than the previous value, given the difficulty to replicate the bug right now, it may take a while before I can report back. Just wanted to let you know because I thought this could be important.

**Comment by Org-gith** [comment]
It would be probably better to try it also on the latest Renpy 8.0, as I'm still running ren'py 7.5. Maybe this kind of thing can play on the timings a bit.

**Comment by renpytom** [comment]
If there is a bug, it's not this one - the rewrite is so complete, the old problem seems impossible. (Also, Ren'Py can't make a 200dB sound - the loudest possible sound is 194 dB.)

**Comment by Org-gith** [comment]
Understood, that's reassuring then, I must have applied the commit partially wrong, I'll try on the new version in near future... (the db was based on a scale image defining noise level after I heard the noise, might have overestimated it a bit but it's not too far.)

**Comment by renpytom** [comment]
Note that it's not just a commit - there are a lot of changes behind the scenes to enable it. If you're not compiling Ren'Py, you'll need to use the nightly builds.
