### ISSUE TITLE
Project does not run on launcher screen

### ISSUE THREAD

**Issue by icannotopen** [renpy/renpy#4089]
When I click the launch project button, the launching screen appears for a while and then returns to the original screen. 

When I click on other areas, such as actions, the warning message "ERROR-launching the project failed. Please sense that your project runs normally before running this command." 

There is nothing wrong with running other games made with Renpy. It's just that the project in Launcher doesn't start. 

Is it just a problem with my computer?

**Comment by renpytom** [comment]
Check out the game's directory for traceback.txt, errors.txt, and log.txt.
