### ISSUE TITLE
Add continue and break statements in SL-for loops

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#4094]
I have some screens where I would want to use "for" loops like in Python.
What about adding "continue" and "break" statements for screens?

Before:
```
screen test:
   
   for i in items:
      
      if i:

         if ...:
            use screen1

         else:
            use screen2
```

After:
```
screen test:
   
   for i in items:
      
      if not i:
         continue

      if ...:
         use screen1

      else:
         use screen2
```

**Comment by KiloOscarSix** [comment]
For this specific example you could create a variable that filters out values before looping,

`default values = [i for i in items if i]`

**Comment by Gouvernathor** [comment]
This can't be done with showif I think, so implementing this would risk breaking the symmetry between if and showif.
What's more, screen language is not an imperative language, it's a language to construct things. It's kind of the same as in comprehensions vs classic for loops, break and continue make sense when you're writing successive and conditional instructions, but not in a statement specifically made for building a custom list (or iterable).

**Comment by MiiNiPaa** [comment]
You can `filter` your list and operate only on elements you want.

Example code can be written as:
```
screen test:
   for i in filter(None, items):
      if ...:
         use screen1
      else:
         use screen2
```

 I firmly believe, that screens should only be responsible for displaying data, and any complex manipulations should be done by external controller code.

**Comment by via-my** [comment]
Then it won't hurt to update this documentation:
[The for statement is similar to the Python for statement, except that it does not support the else clause.](https://www.renpy.org/doc/html/screens.html#for)

**Comment by via-my** [comment]
In any case, it's pretty strange that this old method will have that cool Python features, even though it's not recommended to use it.

```
init python:

    def screen(**kwargs):
        ui.vbox(id="say_vbox")

        for line in ["line_1", "line_2", None, "line_3"]:

            if line is None:
                continue

            ui.text(line)

        ui.close()

    renpy.define_screen("test", screen)
   ```

**Comment by Gouvernathor** [comment]
Clarified in 8fc417b5e93b4afac802d77e1ab9264da341bcbb.
That's the point of the transition from the ui.functions way to the current screen language : moving from imperative programming to generative and predictable code.

**Comment by renpytom** [comment]
This isn't ridiculous. I don't think break and continue make sense in script language, where you can jump to any statement (at least in theory). But you can't do that in SL, and especially the continue example makes sense. 

What's a bit worrying to me is optimization, but I'm not clear it's worse than what we have with the Python statement - so I'll look into this.
