### ISSUE TITLE
gui.preference() can not get default value.

### ISSUE THREAD

**Issue by YuanlinLi** [renpy/renpy#4098]
While running game code:
  File "game/gui.rpy", line 97, in script
    define gui.text_font = gui.preference("text_font", "GenSenMaruGothicTW-Medium.ttf")
  File "game/gui.rpy", line 97, in script
    define gui.text_font = gui.preference("text_font", "GenSenMaruGothicTW-Medium.ttf")
  File "game/gui.rpy", line 97, in <module>
    define gui.text_font = gui.preference("text_font", "GenSenMaruGothicTW-Medium.ttf")
  File "renpy/common/00gui.rpy", line 164, in preference
    if (name not in defaults) or (defaults[name] != default):
TypeError: argument of type 'NoneType' is not iterable

**Comment by qTich** [comment]
Did you call `gui.init`?

**Comment by YuanlinLi** [comment]
> Did you call `gui.init`?

not worked,still the same error

**Comment by YuanlinLi** [comment]
> > > Did you call `gui.init`?
> > 
> > 
> > not worked,still the same error
> 
> You need to call it before using `gui.preference`:
> 
> ```renpy
> init offset = -2
> 
> init python:
>     gui.init(width, height)  # screen width, screen height
> 
> define gui.text_font = gui.preference("text_font", "GenSenMaruGothicTW-Medium.ttf") 
> ```

I see,gui. init () should be written IN FRONT OF gui. preference (). Years ago I wriote gui. init () into options. rpy by mistake.
Sorry for disturbing and thanks for your kind reply.
Wish you have a nice day.
