### ISSUE TITLE
[oversampling] Issues with im functions

### ISSUE THREAD

**Issue by DinakiS** [renpy/renpy#4100]
Looks like all `im.` functions are ignoring oversampling.

I've tried Blur, MatrixColor, Flip and FactorScale.

For example:

```renpy
image orig = im.Blur("images/CG/bg.webp", 1.05)
image oversample = im.Blur("images_x2/CG/bg@2.webp", 1.05)

label start:
    scene orig
    "Original"

    scene oversample
    "Oversample"

    return
```

![Original](https://i.ibb.co/t4G5Xsy/screenshot0001.png)
![Ovesampled](https://i.ibb.co/1JfRBmM/screenshot0003.png)

**Comment by Andykl** [comment]
IMO, all functions in `im`, are obsolete and should not be used in modern RenPy games. `Transform` is a way to do so.

**Comment by DinakiS** [comment]
I think that many will use oversampling as simple upscaling tool for an old games.
If there will be a need to rewrite some code, it's not that simple anymore.

Also I tried to use `Transform("images_x2/CG/bg@2.webp", blur=10)`, why it's so messed up comparing to `im.Blur`?
![Original](https://i.ibb.co/YPm273c/screenshot0002.jpg)

**Comment by qTich** [comment]
> I think that many will use oversampling as simple upscaling tool for an old games. If there will be a need to rewrite some code, it's not that simple anymore.
> 
> Also I tried to use `Transform("images_x2/CG/bg@2.webp", blur=10)`, why it's so messed up comparing to `im.Blur`? ![Original](https://camo.githubusercontent.com/7b6cc4169c634995483e5f70d0e32a3a9de0e48f2b2a778f0e50ba151b4c4f66/68747470733a2f2f692e6962622e636f2f59506d323733632f73637265656e73686f74303030322e6a7067)

Because they are two different implementations. 

Using `Transform` is an addition of a shader.
Using `im.Blur` is a call to a `C` implementation.

**Comment by mal** [comment]
> why it's so messed up comparing to `im.Blur`?

As [qTich](https://github.com/qTich) notes, `im.Blur` is implemented in C as a 6-pass (three vertical, three horizontal) box blur with approximate gaussian values producing a relatively high-quality gaussian-like blur reasonably fast, while the `Transform` approach is using a single-pass shader designed to be extremely quick (especially on larger images) and of a quality that is "good enough".

At present if you need a higher quality shader blur (i.e. with a Transform) then it's necessary to implement your own shader, but doing so effectively is hampered by the current single-pass model.

**Comment by Gouvernathor** [comment]
8784250 seems to throw this out, but I think the base problem, im with oversampling, is a necessary or at least very handy thing when remastering old VNs at a low reingeneering cost. Which the oversampling syntax was all about.
