### ISSUE TITLE
Outlines move by one pixel then return

### ISSUE THREAD

**Issue by Charmareian** [renpy/renpy#4103]
Outlines randomly move during certain lines of dialogue. 

Here is my style for dialogue:
style default:
    outlines [ ( 4, "#181840", 0, 0) ]
    outline_scaling "linear"

https://user-images.githubusercontent.com/24770185/202921588-0924c384-8312-4d17-8359-bb405d214c8d.mp4

(Sorry for closing the old issue and opening a new one. I just thought I wasn't clear enough in my original post. I also noticed another person with a similar issue, but it was closed for not being clear enough)

**Comment by renpytom** [comment]
I've finally gotten to this, but I've been unable to repeat this in the 8.1 nightly build. Do you have a game that repeats this?

**Comment by Charmareian** [comment]
I do. Would you like me to send the game via email?

**Comment by renpytom** [comment]
Yes, please. The account is renpytom at gmail.com.
