### ISSUE TITLE
Dissolve can sometimes slowly play backward after a rollback

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#4105]
ATL doesn't do that and others transition don't I think, it might be an edge case.
During a dissolve at a certain time, if you rollback at a certain moment while it's playing (at the end of the dissolve it seems like, ~90%+ into completion), the dissolve will slowly play in reverse, instead of instantaneously returning to its previous position as it does almost all the time.

Assuming it was not intended, here is a rough idea to fix it (seems to work but not sure if it has any other side effects or if it is the optimal way):

in transition.py, line 365:
```

   def render(self, width, height, st, at):

        if renpy.game.less_updates or renpy.exports.in_rollback():
            return null_render(self, width, height, st, at)

        instead of the previous:
        if renpy.game.less_updates:
            return null_render(self, width, height, st, at)
```

**Comment by renpytom** [comment]
Can you come up with a technique for repeat this? I can't see an obvious way for this to happen, but there is always the possibility that some complex time-adjustment setup could cause it. I'm not sure a blunt fix like the one above is the right way to deal with this.

**Comment by Org-gith** [comment]
Exactly, I actually didn't know the exact conditions to make it happen but after making the template project, I can say it seems to involve having two pauses following each other during a transition, here is a template that replicates the issue consistently:
[testdissolve.zip](https://github.com/renpy/renpy/files/10086286/testdissolve.zip)

The rollback button is also configured to key 'r' in the project (this makes it easier to reproduce), also the bug happens if you rollback towards the later end of the transition, but not at the beginning, basically once it reaches the second pause I think.
The blunt solution is bad and has a side effect too which I discovered later on, even though it's a bit of a lesser evil than this issue itself, it's really not good.
