### ISSUE TITLE
[ 7.5 / 8.0+ ] MetalAngle framework causes Asset validation failure in Xcode, making it impossible to release the game in the App Store.

### ISSUE THREAD

**Issue by stunnings** [renpy/renpy#4106]
<img width="727" alt="batch_screenshot12" src="https://user-images.githubusercontent.com/109571458/203344520-435c3f8e-b9fe-4e2d-a4b4-d4b6362873e0.png">
<img width="726" alt="batch_screenshot13" src="https://user-images.githubusercontent.com/109571458/203344532-d6a6e829-18ab-462f-9e5c-5dee68db0afc.png">

MetalAngle framework causes Asset validation failure in Xcode, making it impossible to release the game in the App Store.
The following is as a detailed description of the reproduction process, including the process of deploying the app to the App Store via Xcode.

---------------------------------------

<img width="283" alt="batch_screenshot1" src="https://user-images.githubusercontent.com/109571458/203344724-48b1f65f-d77e-4b80-b224-e99e3c949a0c.png">
1. Open a project in Xcode and create an archive through Product > Archive. This will display a window containing a list of deployable archives.

---------------------------------------

<img width="1136" alt="batch_screenshot2_1" src="https://user-images.githubusercontent.com/109571458/203346028-775f109b-ed24-482d-b52e-92ae50f5fb4a.png">
<img width="726" alt="batch_screenshot3_1" src="https://user-images.githubusercontent.com/109571458/203346064-3c080c4d-7ae5-4eb2-8f12-8eeaca7e5da7.png">
2. Select a deployable archive, click 'Distribute App' to deploy the app, and select App Store Connect as the deployment method.

---------------------------------------

<img width="723" alt="batch_screenshot6" src="https://user-images.githubusercontent.com/109571458/203346670-3b8ab9df-a50f-4283-b263-750e85732a74.png">
(The window that selects Distribution certificate in Xcode displays three MetalAngle.frameworks)

---------------------------------------

<img width="728" alt="batch_screenshot7" src="https://user-images.githubusercontent.com/109571458/203347021-c914e977-d206-49b5-bdb6-bc6552f73f00.png">
3. Xcode displays a window asking you to review the content contained in the game.
Three MetalAngle.frameworks are included as content.

Until Ren'py 7.4.10, only app titles were displayed, with no content included.

---------------------------------------

<img width="724" alt="batch_screenshot8" src="https://user-images.githubusercontent.com/109571458/203347820-6919d438-eac3-4cba-a016-66b557d05ac5.png">
<img width="718" alt="batch_screenshot9" src="https://user-images.githubusercontent.com/109571458/203347833-eb1da55e-0d10-439f-9448-70168fb9516f.png">
<img width="722" alt="batch_screenshot10" src="https://user-images.githubusercontent.com/109571458/203347848-56b402b3-3804-41e7-bb3b-cb353af29eac.png">

(I'm attaching screenshots of the review information of each framework to help you solve the problem.)

---------------------------------------

<img width="732" alt="batch_screenshot11" src="https://user-images.githubusercontent.com/109571458/203348156-c7ea947b-3bf9-420f-8bec-90e188fcbf80.png">
4. Xcode uploads the archive.

---------------------------------------

<img width="727" alt="batch_screenshot12" src="https://user-images.githubusercontent.com/109571458/203344520-435c3f8e-b9fe-4e2d-a4b4-d4b6362873e0.png">
<img width="726" alt="batch_screenshot13" src="https://user-images.githubusercontent.com/109571458/203344532-d6a6e829-18ab-462f-9e5c-5dee68db0afc.png">

5. Xcode returns a total of 3 errors during the upload process.
Those are the errors that I attached at the top.

When repeating the same procedure with Ren'py 7.4.10, Xcode did not return those errors.

---------------------------------------

This is a very serious issue because games cannot be distributed to the App Store via Ren'py 8.X (or 7.5.X).
I would appreciate it if you could review this matter.

I masked some of the project name, app package name, certificate code, etc.
If you need an unmasked screenshot, please leave a comment. I'll send it to you via email.

Thank you for your hard work.

**Comment by renpytom** [comment]
How is MetalANGLEgetting into your project in the first place? At the moment, MetalANGLE is only used on iOS, not macOS, and I just did a build mac build and MetalANGLE was not part of it.

**Comment by stunnings** [comment]
@renpytom Yes, what I tried is to build the app for iOS through Xcode and then upload it to the App Store (iOS platform). If you read the process I explained, you can see what it means. In other words, I am currently faced with a problem that I cannot deploy or update my app to the iOS App Store. Retry Renpy 7.4.10 to complete the entire process without any problems. Of course, there is no problem with macOS.

**Comment by stunnings** [comment]
@renpytom (* Perhaps you misunderstood it as a problem of notarization in macOS. This is a problem that occurs when deploying iOS apps through the App Store in Xcode.)

**Comment by Stormsinger-Frostclaw** [comment]
Can confirm that I am also facing this issue. The only way I can get around it is to use Ren'Py 7.4 and an older version of Xcode, which isn't ideal.

**Comment by renpytom** [comment]
Finally figured this one out. The problem is that the Frameworks directory is listed in the "Copy Bundle Resources" step, which causes the problems. To fix this, remove Frameworks from the Copy Bundle Resources list. It's hard to explain how to get to this, so here's a screenshot.

<img width="1049" alt="xcode" src="https://user-images.githubusercontent.com/379804/206632873-2879fa95-ae68-43da-aaaf-d27fee7ae8b7.png">

Thank you for clarifying this, and I apologize for letting this linger so long.

**Comment by stunnings** [comment]
I tried your solution, and the problem was fixed perfectly.
Thanks for your help in solving this problem.
