### ISSUE TITLE
Why the newer renpy version doesn't anymore skim the folders for fonts like the elder ones ?

### ISSUE THREAD

**Issue by Nafraju** [renpy/renpy#4115]
Hi,

Why in renpy-7.3.5-sdk version - renpy - finds my fonts in `game/fonts/example.ttf`
and in renpy-7.5.2-sdk version (the newer one) renpy finds the fonts ONLY if they are in `game/example.ttf`  ❓

**Comment by renpytom** [comment]
I checked 7.3.5, and it doesn't behave as you describe by default. I don't see a change here.
