### ISSUE TITLE
Renpy 7.3.5+dfsg-2: Fails to configure

### ISSUE THREAD

**Issue by MBfromOK** [renpy/renpy#4120]
I installed renpy from the Linux Mint application manager. 

It gave me the launch and remove button but then reported it failed to install and offered a message.  I removed the install then went to the Terminal where I ran `sudo apt-get install renpy`

it completed with the following status:
```
Setting up renpy (7.3.5+dfsg-2) ...
  File "/usr/share/games/renpy/launcher/game/gui7/code.py", line 283
    l = re.sub(ur'_\((\".*?\")\)', replace, l)
                 ^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
dpkg: error processing package renpy (--configure):
 installed renpy package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 renpy
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The section of code in that part of the file reads:
```
281        for l in self.lines:
282
283            l = re.sub(ur'_\((\".*?\")\)', replace, l)
284            l = re.sub(ur'_\((\'.*?\')\)', replace, l)
285
286            lines.append(l)
287
288        self.lines = lines
```

Edited that file so lines 283-284 read like this (to match Renpy 7.5.2):
```
283            l = re.sub(r'_\((\".*?\")\)', replace, l)
284            l = re.sub(r'_\((\'.*?\')\)', replace, l)
```
Then ran `sudo apt-get upgrade` which then offers the following for renpy:
```
Setting up renpy (7.3.5+dfsg-2) ...
  File "/usr/share/games/renpy/launcher/game/pefile.py", line 88
    IMAGE_ORDINAL_FLAG              = 0x80000000L
                                               ^
SyntaxError: invalid hexadecimal literal
dpkg: error processing package renpy (--configure):
 installed renpy package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 renpy
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
"pefile.py" - Line 88 reads: 
```
IMAGE_ORDINAL_FLAG              = 0x80000000L
IMAGE_ORDINAL_FLAG64            = 0x8000000000000000L
```

**Comment by renpytom** [comment]
7.3.5 is an old version of Ren'Py at this point, and it sounds like you might be trying to run that version under Python 3. I;'d suggest downloading the official version from https://www.renpy.org .

**Comment by renpytom** [comment]
Closing, as this is about an obsolete version of Ren'Py.

**Comment by MBfromOK** [comment]
Figures, that is the "newest" version available in the repository.

Is there a .Deb package available for the new version?
