### ISSUE TITLE
Documentation doesn't mention Android minimum and maximum version

### ISSUE THREAD

**Issue by brunoais** [renpy/renpy#4124]
When looking at android documentation: https://www.renpy.org/doc/html/android.html

There's no mention on what are the minimum and maximum android versions that Renpy supports.
I believe there should be a mention about the versions or a link sending the reader to a page which specifies that information.

I had to ask on reddit to get the answer I needed: https://www.reddit.com/r/RenPy/comments/y93p0z/comment/it446xn/?context=3

**Comment by renpytom** [comment]
Fair enough, though it is mentioned on https://www.renpy.org. I'll update the documentation to make this clearer.

**Comment by brunoais** [comment]
Thank you
