### ISSUE TITLE
[Request] renpy.show take displayable

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#4125]
Would it be possible to make renpy.show to also take displayable string argument instead of just predefined image name? I'd like to show images without unnecessary image variable definitions similar to how add statement works in screens.

**Comment by Gouvernathor** [comment]
You can look at the `what` parameter of [the function](https://www.renpy.org/doc/html/statement_equivalents.html#renpy.show) for an equivalent of the show expression statement.
