### ISSUE TITLE
Ren'py trying to save at the wrong location

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#4130]
It's a bug reported by a user on a game, it's the first time I encounter this problem, here is the exception error he got when trying to save:
![image](https://user-images.githubusercontent.com/78823063/205467380-60a808bc-ae8a-4af6-9eaa-6ec00badac65.png)

I asked him to look for his ren'py folder, and he made that print screen of his save folder location;
![image2](https://user-images.githubusercontent.com/78823063/205467410-f1a036a7-f8a4-46c6-aa0e-8ee1d592eaa3.png)

His accent seems to mess up the path, otherwise, I'm not sure what else could cause it

**Comment by renpytom** [comment]
Can you try with 7.5? There have been a lot of changes in this area.

**Comment by Org-gith** [comment]
I tried to test it with 7.5 and created a Windows account with the same accent but my windows converted it automatically into:
"usuario" without accent in the path, despite showing it with an accent during creation. I wasn't able to test it, I think someone with a Spanish version of windows may be able to test it? I'm not sure how they end up with accents...

This  7.4.10 build that this user tried is a very old public demo version, the build on 7.5 is not yet public but once it came out I'll ask him if he can save it without problems on it and report back.

**Comment by Org-gith** [comment]
Weirdly enough, while deleting the test account with an accent, I realized it ended up with two user paths, one with the accent for windows stuff. So it seems to have been able to create a path with an accent after all. 
But it also created another entirely new path just for ren'py where there was no accent on the username, so another roaming folder within another username path just for the save, it duplicated the username but without accent.

**Comment by Org-gith** [comment]
I think 7.5 fixed it, since it seems to create another username path with no accent, which makes the save work but it has a side effect of creating two username paths, from there I don't know if it's good or not, but definitely no more problem on 7.5 I would say.

**Comment by renpytom** [comment]
I suspect this is a windows encoding mismatch issue. I'm going to close this - it's a hard issue to solve on Ren'Py 7 in all cases, and Ren'Py 8 should take care of this problem.
