### ISSUE TITLE
Name 'emscripten' is not defined

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#4133]
I tried out the latest nighlty R8 Web. I used the new documented function `emscripten.run_script` and it throws the error `name 'emscripten' is not defined`

For context, I used the following script for testing:

```
<script type="text/javascript" src="https://static.itch.io/api.js"></script>
<script type="text/javascript">
  Itch.attachBuyButton(document.getElementById("buy_button"), {
    user: "user",
    game: "my game"
  });
</script>
```

This worked if I call the function inside the index.html file, but I want to call this by a button inside renpy.

Is there a specific way to implement this? I guess the module is missing.

**Comment by renpytom** [comment]
Did you import emscripten first?
