### ISSUE TITLE
Transitions disable screen keybindings

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#4139]
In some screens I override the 'game_menu' key for different custom actions. But when a transition occurs, those key statements do not catch the mouse events and the game menu opens instead.

```
screen test():

    text "test screen" align (.5, .5)

    key 'mousedown_1' action With(Dissolve(1.0))
    key 'game_menu' action Notify("RMB pressed")
```

**Comment by renpytom** [comment]
If you want to override the game menu, use config.game_menu_action.

I think it might also make sense to have config.bottom_layers, similar to config.top_layers, to allow a place for screens like these to go - thought keymap blocking screens are a bad idea. 

#4181 is the new bug.
