### ISSUE TITLE
Web issues

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#4158]
1. This message is reported as an error by a certain percentage of users. I think it makes sense to remove or improve it, and also to write in the documentation what the server owner needs to do to prevent it from occurring.
![image](https://user-images.githubusercontent.com/27142420/207997909-215d2d8d-b037-435d-83dd-3dd59fb124d2.png)
2. When game exists there should be prompt explaining what user need to do. They are:
a. Normal quit -> The game quits. You may close the tab.
b. Error quit -> The game has crashed. You can download the log file and send it to the developers.
c. Game requested reload (currently `renpy.quit(reload=True)` is broken due to subproccess call) -> The game asks for a restart. You need to manually reload the tab.

**Comment by qinlili23333** [comment]
maybe we can use refresh to do the reload in web, just simply call `location.reload()` when request `renpy.quit(reload=True)`

**Comment by renpytom** [comment]
I'll add here, so we don't forget it, that aec68a96a4e856bcd801d261279caed976dc4b11 seems that it breaks loading in games from renpyweb-7. When you go to a game on itch.io, and download the savefiles, it includes the saves for every game, not just the one you were playing. 

I think it makes sense to keep the change, but also look for files of the format:

f'{config.save_directory }/whatever-LT1.save'

And strip config.save_directory before unpacking, so we can unpack saves exported by Ren'Py 7.

**Comment by renpytom** [comment]
renpy.quit(reload=True) doesn't make sense in the web environment.

**Comment by MiiNiPaa** [comment]
I believe renpy.quit(reload=True) is the only documented way to ensure that init statements are re-run and the game is properly restarted, e.g. conditionally loaded modules would be unloaded if conditions are no longer true. (There is utter_restart, but it is not documented).

**Comment by RenpyOnly** [comment]
Links not wokring in web. Do not redirect

**Comment by RenpyOnly** [comment]
Why are you complicating the web version? If you want to kill her just develop

**Comment by renpytom** [comment]
I believe that everything in here has been resolved.
