### ISSUE TITLE
Self-voicing system: NO control over TTS volume

### ISSUE THREAD

**Issue by zersiax** [renpy/renpy#4161]
In Renpy games that allow for the toggling of self-voicing mode using the V key, it is unfortunately impossible to influence the volume of the text to speech voice in relation to other things such as music and sound effects.
The documentation on the website points out that to modify properties for the voice used, one should use controls provided by the platform. And this is true for selecting voice and speech rate, however, volume cannot be set by the user on Windows; has to be done programmatically.
Particularly with quieter games the contrast can be quite jarring and it'd be awesome if there was some kind of way for users to tell the TTS to pipe down some.

**Comment by renpytom** [comment]
I'm not sure what I can do here, but I'll look into it.

**Comment by zersiax** [comment]
Thanks. I believe volume can be adjusted once a connection to the COM object has been made but I'm honestly not sure about the low level implementation there. Good luck :)

**Comment by fartcoin-project** [comment]
Install eartrumpet (from windows store) as it can change the volume for tts
