### ISSUE TITLE
Enforcing virtual resolution for GPU scaling

### ISSUE THREAD

**Issue by morganwillcock** [renpy/renpy#4162]
I have asked about this before (#793) and at that time it didn't seem feasible, but with the GL2 based renderer is there now the possibility to preserve the pixel size when down-scaling and `config.use_drawable_resolution` is set to `False`?

I am asking again after seeing there is a renderer property named `gl_drawable_resolution` although I can't see it has any effect on a scaling transform that uses a mesh.

**Comment by renpytom** [comment]
Are you talking about making sure pixels are an integer multiple of the originals, or am I confused about this.

**Comment by morganwillcock** [comment]
I mean that the result should be rendered with the smallest visible pixel size being determined by the virtual/game resolution and not the display resolution, when the game configuration says not to use the display resolution.

e.g. an image like this:
![square](https://user-images.githubusercontent.com/14958747/208201361-c55e1f4f-4271-4004-9977-44543e96505a.png)
...should visibly loses half of its pixels when scaled at 50% and the virtual resolution is enforced (`config.use_drawable_resolution` set to False):
![square_0 5](https://user-images.githubusercontent.com/14958747/208201363-d11ec637-2533-4730-9ec2-76a10ed2a16b.png)

Here are upscaled versions to help see the change:
![square_upscaled](https://user-images.githubusercontent.com/14958747/208202100-ff00f554-30b2-4eb1-898d-df3d3bbc693c.png)
![square_0 5_upscaled](https://user-images.githubusercontent.com/14958747/208202097-5f2578dc-5b4f-4e70-a7c8-b5594d277c68.png)

**Comment by renpytom** [comment]
You can use Flatten with the drawable_resolution=False parameter to capture a displayable at its virtual size into a texture. 

For example:

```renpy
image mesh = Flatten(Transform("mesh.png", zoom=.5, nearest=True), drawable_resolution=False)

label start:

    show mesh:
        align(.5, .5)
        nearest True
        zoom 10


    "..."
```

Where mesh.png is your original image.

**Comment by morganwillcock** [comment]
Thanks, I wasn't looking to generate a new displayable to ensure that the drawable resolution is not used, but using a shader that pixellates based on a grid size that matches the virtual resolution is something which should implement a similar result.

I did already give it a try with a shader:

```py
renpy.register_shader(
    "scale.virtualres",
    variables="""
    uniform sampler2D tex0;
    uniform mat4 u_transform;
    """,
    vertex_300="""
    v_tex_coord = a_tex_coord;
    """,
    fragment_300="""
    float dx = u_transform[0].x;
    float dy = u_transform[1].y;
    vec2 sample_coord = vec2(dx * floor(v_tex_coord.x / dx),
                             dy * floor(v_tex_coord.y / dy));
    gl_FragColor = texture2D(tex0, sample_coord);
    """)
````

...I don't think this is entirely correct and I'm struggling to get a sense of the numbers which are involved, but it seems feasible. But this also sounds a lot like the description of `gl_drawable_resolution` when set to `False`:

> gl_drawable_resolution
    If true or not set, the texture is rendered at the same resolution as the window displaying the game. If false, it's rendered at the virtual resolution of the displayable.

Is the "virtual resolution of the displayable" different to the virtual resolution of the game?

**Comment by renpytom** [comment]
gl_drawable_resolution only matters when rendering to a texture. It's how the drawable_resolution argument to Flatten is implemented. 

I don't have a great idea of how to do this in a shader.

**Comment by morganwillcock** [comment]
OK, so it sounds as though the situation is the same as before: `config.use_drawable_resolution = False` still uses the drawable resolution for scaled textures and that isn't going to change.

As a workaround, I do now have a working shader but the shader operation is aligned with the physical window rather than the rendered viewport. I think the viewport information that is available to the shader might be able to work around that.
