### ISSUE TITLE
Mouse Click stops to update on screen update.

### ISSUE THREAD

**Issue by GoldenCrowInf** [renpy/renpy#4172]
Hello Mr. Renpytom!

I hope everything is going well! I'm GoldenCrow and I'm working on a game called Influencing.
I want to report a bug that happened after I update the Ren'py version (7.5.3 and 8.0.3). I made a video about that and you can watch in [HERE](https://youtu.be/g4-oB99k_eY?t=45)! I'll explain it anyways...

When you hold any bar in the game and updates a screen at the same time, the mouse holds this bar forever, and after that you can't click on anything. It's like the game 'freezes'.

I hope this feedback helps you to improve our beloved Ren'py.
I really want to thank you for create such a tool! Thank you!

Kind regards.

GoldenCrow.

**Comment by GoldenCrowInf** [comment]
I've created a small Ren'py project with instructions to cause this bug. This is really important! Run this project in Renpy 7.5.3 or 8.0.3 and mouse click will freeze inside Ren'py. The older Ren'py versions have no this problem.

[Bug Test.zip](https://github.com/renpy/renpy/files/10292069/Bug.Test.zip)

Thank you!

**Comment by GoldenCrowInf** [comment]
I just want to let you know that the solution proposed does not solve the problem.

**Comment by renpytom** [comment]
Can you try your bug test? It seems fixed to me in the nightly. At least, I can't repeat it there.

**Comment by GoldenCrowInf** [comment]
Maybe I missed something in the solution. But I did the change proposed by thececc134, wich is add set_grab(None) in line 540 of the file focus.py and the problem persist in here.

**Comment by renpytom** [comment]
Have you downloaded 8.1 from nightly.renpy.org and tried it there?

**Comment by GoldenCrowInf** [comment]
Oh! I just tested it. It's working. Not just in the bug test project, but in my own game as well! Thank you!!!
