### ISSUE TITLE
Severe thread leaks when playing lossless audio files

### ISSUE THREAD

**Issue by ghost** [renpy/renpy#4174]
Playing a WAV or FLAC encoded audio file appears to create a new thread that tries to use 100% of a CPU core, and which persists after playback (until the game is quit). This also happens with looped playback — each loop creates a new persisting thread.

A minimal example:

```renpy
label start:
    $ renpy.sound.play('se_test.wav', loop = True)
    "Test"
    return
```

Running this script (along with the default files from the game template, and a short wav file `se_test.wav` in the game directory) and leaving it running while it waits for input on the "Test" line makes Ren'Py more and more CPU cores as the audio file loops, eventually going up to 100% of all cores.

This does not happen with Opus, Vorbis, MP3 or MP2 encoded audio.

I was able to reproduce this issue on Ren'Py 8.0.1 (from the Arch repos) and 8.0.3 (SDK downloaded from the website). I was unable to run the latest nightly build. My Python version is 3.10.8; I am on Arch Linux `Linux-6.0.12-arch1-1-x86_64-with-glibc2.36`. I have not tried any other environments.

**Comment by renpytom** [comment]
I'm not seeing this behavior, on Ubuntu 22.04, using 8.0.3 download from the website. Do you have your se_test.wav file? I'd like to see if it's something file specific, but barring that I can't reproduce this.

**Comment by Neurochitin** [comment]
Here it is: [se_test.zip](https://github.com/renpy/renpy/files/10346733/se_test.zip)
Although for me it happens with every file I've tried.

**Comment by renpytom** [comment]
I'm not able to repeat it the thread leak. 

I'll note the file in there isn't actually playable in Ren'Py - it's using IEEE Floating point in the wav files, which Ren'Py doesn't support. 

I've verified using GDB that each thread created to play the audio exits, so if there's a problem, it's unlikely to be with Ren'Py.
