### ISSUE TITLE
Labels that start with `_` are not used in creating translation id

### ISSUE THREAD

**Issue by via-my** [renpy/renpy#4180]
I have some labels that I visually separate from others by adding prefix.
```
label _lb_whisper:

    mc "*whisper*"
    return
```

When I generate a translation I receive this.
```
translate english 5fdf5835:

    # mc "*whisper*"
    ma ""
```
When I was expecting this.
```
translate english _lb_whisper_5fdf5835:

    # mc "*whisper*"
    ma ""
```

Is that an intended behavior? Can't see anything about this in the documentation.

**Comment by mal** [comment]
I believe this is intentional and falls under the catch-all warning in the second paragraph of the [Reserved Names](https://www.renpy.org/doc/html/reserved.html) page of the docs.

**Comment by renpytom** [comment]
This is correct, names beginning with _  are reserved for Ren'Py.
