### ISSUE TITLE
Question about save location

### ISSUE THREAD

**Issue by bober-gith** [renpy/renpy#4186]
It's not really a straight up issue, more like a quirk, I was wondering why Ren'py generates two saves folders by default.

https://www.renpy.org/doc/html/config.html#var-config.save_directory

Supposedly Ren'py should use the AppData folder to save under default circumstances, which it does but at the same time it always also creates a saves folder inside the game folder (even when config.save_directory is not set to "None"). 
I was wondering if there was a way to tell it to not do that.
Because for the users, from what I noticed is that it often creates confusion, their first instinct is to look into the game folder (not Appdata), they see there is a save folder full of saves, and assume this is their save folder. Try to do manipulation like deleting saves or whatnot, but nothing happens since it's actually not the saves that are being used. Come to me, file a bug report and I have to explain that there is two saves folder and redirect them to the right folder which is located in the Appdata. Just a way to remove this folder would remove their confusion, as the lack of a saves folder inside the game folder would ultimately lead them to find the 'right' saves folder by themselves I think, or if anything they would understand that they can't find the save folder and ask a question or use google, but not see it as a bug.
Outside of that, it also creates a minor issue where if an issue is trying to delete all the saves of his Ren'py game, he has to delete it at two locations at the same time, because if the AppData folder is still there, it will copy the saves to the game folder. And vice versa I think.
There might be a reason I'm not aware of why it is, but in the documentation, it's not explained.

**Comment by Numerlor** [comment]
The appdata folder should sync across systems so there's some value there, but I'm thinking the game local folder could be dropped and replaced with a shortcut/symlink

**Comment by Org-gith** [comment]
The appdata folder is also a must I believe for mac build, and android (could be wrong about that). 
+ it makes it so that the user is carried to a new version without needing manipulation, so it's the better solution between the two among the door. It's really that local folder still being generated when you don't want it, that is a bit confusing for the users.
But having something like a link to the appdata folder instead, would be pretty amazing, Not sure how difficult that is though, but yeah theoretically seems like the best outcome.

**Comment by nearlystardust** [comment]
> The appdata folder is also a must I believe for mac build, and android (could be wrong about that). And it makes it so that the user's saves are carried to a new version without needing manipulation, so it's the better solution between the two I think. It's really that local save folder still being generated when you don't want it, which is a bit confusing for the users. But having something like a link to the appdata folder instead would be pretty amazing. Not sure how difficult that is, but yeah theoretically seems like the best outcome.

You might need to use an additional library or two to create shortcuts on Windows, but it should work. You're also right about an equivalent off the `AppData` folder being necessary for macOS applications -- most apps can't write to other directories without user confirmation.

**Comment by renpytom** [comment]
The reason for the local folder is so if you're running off a USB stick, that works. (It also works really well with things like Steam's save sync.)
