### ISSUE TITLE
Question: Is there any way to change font for Developer Screen?

### ISSUE THREAD

**Issue by Longtianmu** [renpy/renpy#4187]
As the title, I create a translation, apply default style font but there are still block on the Dev Screen.
Is there any varibles relating to it?
![image](https://user-images.githubusercontent.com/60567448/209680095-8169585d-33a9-4b27-a63f-88b3e1cba34a.png)

**Comment by renpytom** [comment]
Yes, gui.interface_font.

**Comment by renpytom** [comment]
Correction, gui.system_font .
