### ISSUE TITLE
Web's hamburger feature for saves on mobile.

### ISSUE THREAD

**Issue by feltcute** [renpy/renpy#4198]
Newer versions of Android has tightened access to app data, which makes it no longer possible for users to move saves to and from desktop, as instructed in the [docs.](https://nightly.renpy.org/doc/android.html#transferring-files-to-and-from-android)

iOS has already been without this from what I understand.

This is useful for more than just developers. This has proven useful for users moving their saves of the game from desktop to mobile and back again depending on their life situation, many have asked for the android and desktop file paths to do exactly this, the community discord has a pin in the beginner channel just for it. 

But in the recent months, I've seen more than a couple users bring up in issues that they no longer are capable of doing this on newer versions of Android.

The new web build's recent introduction of the hamburger for importing and exporting saves would be very handy for addressing this. I understand it isn't a practical 1-1 technically and visually, with underlying platform permissions that'd have to be tackled.

This would prove useful for more than just platform switching. It would also be useful for backing up saves on naturally more at-risk devices given their portable nature, and transferring saves when switching mobile devices.

**Comment by renpytom** [comment]
I'm vaguely wondering if a web-based sync service might be a more convenient solution for this.

**Comment by feltcute** [comment]
On the user side, the nsfw games community is generally wary of network features. On the game developers side, if this is a service they have to host and maintain, it's generally not as appealing as a manual solution the user can turn to.

The act of switching/transferring/backing up saves for mobile wouldn't be so often that automation through a bespoke syncing solution would be a necessity, I imagine. 

I could see web-based syncing being handy for web builds if networking features become possible for it, albeit out of scope of the issue.

**Comment by morbil** [comment]
Anyone wary of networking will be (or should be) wary of an application that asks for general access to the device's storage which is what would be required otherwise. 

You also don't need a developer to host, I believe what he means is cloud storage integration like dropbox/google drive/onedrive etc. There are python libraries that offer multi-service support which could be integrated (individual developers would still need to set up app keys for any service they want to add). At the very least, ensuring that the renpy python distro has the needed dependencies (since the distributed libraries are cherry-picked) would be handy.

**Comment by Kassy2048** [comment]
@Gouvernathor The goal here is to add on the Android/iOS platforms the same menu as on the Web platform, so the "platform-web" label should probably be replaced with the "platform-android" and "platform-ios" labels.

This feature request might be of less importance now that there is a way to sync saves using Ren'Py web server though.

**Comment by renpytom** [comment]
Ren'Py Sync is the solution to this.
