### ISSUE TITLE
Error web version

### ISSUE THREAD

**Issue by Dante00035** [renpy/renpy#4223]
Compiled Web version of the game, engine version 8.1.0. When loading scripts, it gives error, please tell me how to solve it.

![Безымянный](https://user-images.githubusercontent.com/54725253/210960079-8d2ac05a-4da9-4125-ad6d-69bae923440b.png)

**Comment by renpytom** [comment]
Can you please screenshot the browser console? You can access it with f12.

**Comment by Dante00035** [comment]
> Не могли бы вы сделать скриншот консоли? Вы можете получить к нему доступ с помощью F12.

![Безымянный](https://user-images.githubusercontent.com/54725253/211052876-ff51d175-2329-4bfc-b272-f2d320e10257.png)

**Comment by renpytom** [comment]
This is likely based on something your game is doing that isn't supported. (Perhaps using live2d or ctypes.)

**Comment by Dante00035** [comment]
> This is likely based on something your game is doing that isn't supported. (Perhaps using live2d or ctypes.)

Yes, I have live2d connected, will this be fixed in future versions?

**Comment by Gouvernathor** [comment]
Our [live2d doc page](https://nightly.renpy.org/doc/live2d.html) warns how it's not supported on the web platform.
#2347 requests it for a long time, but it would need a lot of work, so it's not likely to work soon.

**Comment by renpytom** [comment]
There's now a better error for this case, so I'm closing this.
