### ISSUE TITLE
[SOLVED - IGNORE THIS] Ren'Py console crashes the game when "renpy" is imported into a third-party Python module.

### ISSUE THREAD

**Issue by CharlieFuu69** [renpy/renpy#4233]
Hello PyTom!
I'm opening this issue because I discovered this bug recently _(not sure if this happens in older versions as well)_.
I'm trying to make a Python module that can be imported into a game, and I make use of some of Ren'Py's built-in features, such as the `renpy.file()` function that I get through `renpy.exports`.

The problem is the following. When I use the module elements, the game runs smoothly. The problem appears when I try to **open the console (Shift + O)**, because when I do it after importing my module, the entire game breaks, without any error record in `log.txt` or `traceback.txt` that specifically shows failure.

A similar bug was reported in [this issue](https://github.com/renpy/renpy/issues/2331), but I didn't find anything that could fully satisfy my concern.

---
### How to check for the existence of this error?
Let's say we have a file called `my_module.py` in the path `/game/python-packages`, and into the game it is imported as:
```renpy
## In RPY script
python:
    import my_module
```
This works fine, and all the classes, functions, and other elements of the module can be used.
Now suppose we have the following code in that Python script:

```python
## my_module.py

import renpy

with renpy.exports.file("text_file.txt") as f:
    file_content = f.read()
```
This causes the indicated error. Importing or using a built-in Ren'Py function within the Python script makes it difficult to use the console if you want to use it. Basically the game window is left with the text "not responding".
I have tested without using the Ren'Py functions and everything works fine. I can open the console just fine if the python script doesn't include Ren'Py elements.

Is this behavior natural in the engine? Is there a possibility to use Ren'Py's built-in features in one module, without the console crashing along with the game?
I don't want to give up the idea of creating the python module I want to do :(

**Comment by Gouvernathor** [comment]
The issue you linked isn't the same problem. Importing renpy in the console scope is terrible, but importing it in a third-party module is a very different thing.

**Comment by CharlieFuu69** [comment]
> The issue you linked isn't the same problem. Importing renpy in the console scope is terrible, but importing it in a third-party module is a very different thing.

Sorry about that, but at the time it was the only thing I found to be "similar" to the error I've been getting :(
Do you know anything about what may be happening? Any incompatibility or an instruction that Ren'Py can't execute?

I really want to know what's going on, because I haven't found any answers related to this, other than the error attached to the URL :"(

**Comment by Gouvernathor** [comment]
We'll look into it. In the meantime you can try to put your code in an `init python` block in a rpy file, and try it from there without the need for imports. You can use a named python block too, so variables are in a named store.

**Comment by CharlieFuu69** [comment]
It's okay. The code works correctly in `init python` blocks, although the original idea was to use it as an importable Python module. In the same way, I can use it at least temporarily.

(Should I close the issue, or leave it open for a bit longer?

**Comment by Gouvernathor** [comment]
You can leave it open, we'll see what to make of it

**Comment by Gouvernathor** [comment]
I can't reproduce the bug with the following code
```rpy
e = None

try:
    import renpy
except Exception as e:
    pass
```
In the console, `import modul` (because the file is modul.py) then `modul.e` returns None, so no problem occurred.

I don't think we support importing renpy in pure-python modules. If you need to take an existing third-party module and import it in your game, it should work, but if you're developing something for renpy, you should use [named stores](https://www.renpy.org/doc/html/python.html#other-named-stores), whose variables _can_ be imported using `import`.
I suggest prepending your store's name with your own, so that people downloading your code don't have name collisions.

When using pure-python modules, you need to rely on undocumented parts of renpy, which may be broken in the next version (i.e renpy.exports.file instead of renpy.file), and your objects break rollback. What would be your use-case for that ?
Let's leave this open until Tom looks into it, but I don't think there's many chances we support that.

**Comment by CharlieFuu69** [comment]
I have discovered that the error does not occur when importing `renpy`, but rather when executing a function present in `renpy.exports` or in some path nearby.

I'll explain what I was trying to do.
My module was an attempt to integrate a rhythm action system into Ren'Py as an importable module from `python-packages`.  This module provides both the processing of the beatmap files (use `renpy.file()` to open the file in case it is inside an RPA package), as well as the player's ticks and tap recognition, so that only just integrate the module and implement the UI and other minimal additions.

In the hypothetical case that there is no going back, would it help me to put my module code in an RPYM file? 
It is my understanding that RPYM files could accept RenPy code without needing to import `renpy` as was the case with pure Python modules. Will this be feasible as a last option?

**Comment by Gouvernathor** [comment]
There's a difference between renpy _code_ and renpy functions as part of the API. Pure-python will never support the former, and the latter is not guaranteed.
Rpym files are renpy files, you write in them in renpy code. That's very similar with writing it in rpy files. So, yes, you can do that, but it's up to you to find out if you need to, as it will make accessing your functions less easy - people will have to use [`renpy.load_module`](https://www.renpy.org/doc/html/other.html#renpy.load_module) instead or before of just `from renpy.store.charlie_rythmsystem import main`.

**Comment by CharlieFuu69** [comment]
> There's a difference between renpy _code_ and renpy functions as part of the API. Pure-python will never support the former, and the latter is not guaranteed.
> Rpym files are renpy files, you write in them in renpy code. That's very similar with writing it in rpy files. So, yes, you can do that, but it's up to you to find out if you need to, as it will make accessing your functions less easy - people will have to use [`renpy.load_module`](https://www.renpy.org/doc/html/other.html#renpy.load_module) instead or before of just `from renpy.store.charlie_rythmsystem import main`.

Interesting point of view.  So basically the most viable way would be to use the RPYMs instead of pure Python scripts.  This would definitely save the trouble of Ren'Py's built-in functions.
This may help more than I thought, and I said about the RPYM because I just read about it in the documentation.

I'll close this issue as it seems I've found what's necessary for my problem.

Thanks for your time!

**Comment by Gouvernathor** [comment]
Please don't, we need to find out if there's something we consider a but or not in here.

**Comment by CharlieFuu69** [comment]
It's okay. I will leave it open until any other eventuality related to this.

To summarize, this would be the sequence to get to the error:
- Import `renpy` into a Python script [Works].
- Use functions exposed in `renpy.exports` [It works].
- Open Ren'Py console after using `renpy.exports` functions [Here is the error].

If this can be fixed, or if it's not worth poking around in, I'll still be on the lookout =D

**Comment by Booplicate** [comment]
> Open Ren'Py console after using renpy.exports functions [Here is the error].

Works for me, maybe something is wrong with console on your end. It won't be able to render large file content, for example.

**Comment by CharlieFuu69** [comment]
> > Open Ren'Py console after using renpy.exports functions [Here is the error].
> 
> Works for me, maybe something is wrong with console on your end. It won't be able to render large file content, for example.

Look again at my last comment. I have posted a screen recording of the incident.

**Comment by Booplicate** [comment]
So if you comment out `rhythm.load()` it works?

**Comment by CharlieFuu69** [comment]
> So if you comment out `rhythm.load()` it works?

@Booplicate Yes, since the `load()` method uses `renpy.exports.file` to open the file. By commenting out that line, nothing related to Ren'Py's built-in functions is executed, and it lets the console open as normal.

It definitely occurs when using Ren'Py functions. The rest of the module works flawlessly.

_Note: I use this function to open Beatmap files even inside RPA packages. You would use the conventional Python `open()` form, but this will look in a physical filesystem path, not inside RPA packages._

**Comment by Booplicate** [comment]
```py
import renpy

print(renpy)

print("reading")
with renpy.exports.file("text_file.txt") as f:
    file_content = f.read()
print("done")
```
```renpy
label start:
    python:
        import test_module
    "test"
    return
```
Works on r8.

**Comment by CharlieFuu69** [comment]
@Booplicate BRO WHAT THE F... 👀
So I'm definitely cursed. I try to remove and redownload Ren'Py? I'm working with v8.0.3...

**Comment by CharlieFuu69** [comment]
OH SH**. Gentlemen, I truly apologize a million times for wasting your time like this.
The focus of the problem was long before calling a Ren'Py built-in function, rather the module works correctly when imported in an `init python` block.

Oh my god, what a shame.
I'll close this thread with what little dignity I had left after this haha
