### ISSUE TITLE
Problems in executing items.action on "show" event.

### ISSUE THREAD

**Issue by RaXorX** [renpy/renpy#4234]
Is there a reason ``on "show"`` is unable to execute items.action while ``timer 0.1`` works just fine to execute it?

```
screen dummy_menu(items, *args, **kwargs):
    on "show" action items[0].action

label start:
    scene expression ("#000000")
    menu (screen="dummy_menu"):
        "Yes":
            "I am yes"
        "No":
            "I am no"
```

```
screen dummy_menu(items, *args, **kwargs):
    timer 0.1 action items[0].action
```
Changing the screen to that successfully prints "I am yes" otherwise it would just be stuck at the black screen.

**Comment by RaXorX** [comment]
```
default choice_items = []

screen dummy_menu(items=None, label=None, *args, **kwargs):
    on "show" action [ SetVariable("choice_items", items), Call(label) ]

screen choice_menu(items, *args, **kwargs):

    hbox:

        for i, btn in enumerate(items):
            textbutton btn.caption:

                action btn.action
                idle_background "#AAAAAA"
                hover_background "#000000"

# items[x].action cannot be resolved/executed with the on show event apparently for the same reason
# hence I have to resort to a label to jump to
# if it could be resolved the first choice could simply have a "pass" as an action
# screen dummy_menu(items, *args, **kwargs):
#     on "show" action [ SetVariable("choice_items", items), items[0].action ]

label start:
    scene expression ("#000000")
    menu (screen="dummy_menu", label="continue"):
# This doesn't run with on "show" event in the screen.
# If it did I wouldn't need a label to jump/call to in the screen.
#        "Default":
#            pass
        "Yes":
            "I am yes"
        "No":
            "I am no"

label continue:
    show screen expression "choice_menu" pass (items=choice_items)
```

This is the entire thing I was trying to do. I'll put this in a new comment just in case I can have explanations for both portions. Though they might be one and the same thing.

1) Problems in executing items.action on "show" event.
 items[x].action doesn't execute or gets resolved with the on "show" event.

2) The captured/stored menu entries from a menu statement, if used through the show/call screen statements do not resolve the entry actions. So even though it'll show the 
Yes and No as choice buttons, the respective actions from these buttons do not executes.

I also noted something. The entry actions are passed on as a reference (or a node?) to an object. My question was this reference should be a static reference or would it be dynamic?
Because if it were static, no matter how I call the menu entries it should point to the same return object and if not show, then at least call should be able to show the result of the return?

On that note also, 

`ShowTransient("choice_menu", items=choice_items)`

This action successfully give the results.

**Comment by renpytom** [comment]
The second example is expected to work. The menu items become invalid when the menu ends.

**Comment by RaXorX** [comment]
> The second example is not expected to work. The menu items become invalid when the menu ends.

Um... by 2nd example do you mean the entire snippet from my 2nd post or just the second point of my 2nd post? Because if that's the case then how about the first, where 

`on "show" action [ SetVariable("choice_items", items), items[0].action ]`
I can't execute this?

And secondly. When you say menu items become invalid.... I'm going to ask whether do you mean
The entire list of entries/items become invalid or the action returns which is what becomes invalid?

Because items do not become invalid at all. And I am using a literal workaround to achieve what I wanted. But because of that I know, items are still there and its data intact, totally valid to be used.

Menu shows up and menu works as intended, just as I said, through a workaround.
