### ISSUE TITLE
None is a true value for screen displayable properties

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4235]
```rpy
screen sense():
    # sensitive None
    hbox:
        imagebutton:
            idle Solid("#00f", xysize=(100, 100))
            hover Solid("#f00", xysize=(100, 100))
            sensitive None
            action NullAction()
        imagebutton:
            idle Solid("#f0f", xysize=(100, 100))
            hover Solid("#ff0", xysize=(100, 100))
            sensitive False
            action NullAction()
```
The first one is sensitive, and the second is not. If the second line is uncommented, the whole thing is insensitive, which means None _is_ a false value for screens.
This behavior dates from the introduction of button sensitiveness, so it's not a bug, but it should be documented more clearly.
This is the same for the selected property, and possibly others.

If possible, but the implementation cost may not be worth it, I would prefer an implementation allowing None to be false.
In the case of screens, that works by making the behind-the-scenes attribute to store not the value itself, but the unevaluated expression, so we can differenciate a None meaning it's not set, and a "None" or "none_returning_function()" meaning the creator means it to be false if the expression evaluates to None.
With a compat, of course.

**Comment by Gouvernathor** [comment]
As for a practical rationale, I have a game where `events.intro` is None by default. `screen a: sensitive events.intro` disables it, `if events.intro:`, in a screen, disables what's inside, but `sensitive events.intro` in a button leaves it on. It lead to sneaky bugs I did not foresee.

**Comment by renpytom** [comment]
We have a lot of places where None means "Take the default", and I think this is a reasonable place to keep that tri-state behavior.  I've gone ahead and documented it. Eliminating the tri-state seems like it would be bad - there would be no way for a use-invoked screen to emulate the default behavior, which I don't like.
