### ISSUE TITLE
Don't notify quicksaves when done on the menus

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#4236]
When you use a key (like  "q") to perform a quicksave, if you press it on the main menu, the default notification appears but it doesn't really saves anything (which is good). I suggest the QuickSave function to be modified to avoid this notification when on the menus because it's confusing.

The issue is here, because calling `FileSave()` in the menus doesn't save, but it stills notifies because it's calling `Notify()`
```
        rv = [
            FileSave(1, page="quick", confirm=False, cycle=True, newest=newest),
            Notify(message),
            ]
```

* As a side note, if you quicksave when the game menu is open in the middle of the game, the screenshot is of the menu. I guess that's expected because of the way the screenshot is made. Maybe don't quicksave when the game menu is open to avoid it?

**Comment by MiiNiPaa** [comment]
A lot of people still use ShowMenu (which displays a screen as game menu) for in-game purposes, because it behaves similarly to call screen or showing modal screen.
Disabling quicksave for game menus will disable it in those cases too which will be surprising for players.

**Comment by Gouvernathor** [comment]
As far as I understand, *saving* (not quickly) from the game menu takes a screenshot of the game, and not of the menu. Maybe making the quicksave work as a regular save when inside a game menu, would be good ? While not disabling anything

**Comment by Gouvernathor** [comment]
I did what I think is a solution to the notify issue, but at the same time I think the way you enabled q as the quicksave key may not be good in the first place. See, if you do this in the quick_menu screen : `textbutton _("Q.Save") action QuickSave() keysym "K_q"`
Then the key is associated with it only when the screen is showing, aka during gameplay, and not during the main menu or the game menu. To test this, I had to add a quicksave keysym to the navigation screen, which is definitely a pointless thing to do.

**Comment by mal** [comment]
Coming in the next version of Ren'Py (8.1) is a new `bottom` layer that is designed for holding keymaps like this, and by default is only active while in-game (rather than menus). I believe you would use it like this:

```rpy
screen customkeymap():
    layer 'bottom'
    key "K_q" action QuickSave()

label start:
    show screen customkeymap()

    ...
```

ref: https://nightly.renpy.org/doc/changelog.html#new-features
> Two new layers are now part of Ren'Py. The "top" layer is displayed above all other layers, and does not participate in transitions. This makes it useful for display information that is always shown. The "bottom" layer is displayed below all other layers. The bottom layer is useful for handling keys in a way that is always active.

**Comment by mal** [comment]
> you need to pass through the start label

Attaching the screen in the start label was just for the example, it can be attached in plenty of other ways, at least one of which is likely to be suitable.

> what if you want it to be active even on the menus?

That's a completely different use-case than the one you presented which was specifically about something that shouldn't occur in menus (quick save)? 😕

**Comment by Gouvernathor** [comment]
I think there are two different issues here : whether and how to allow creators to define keysyms (including or excluding menus, the bottom layer, the always shown screens, the Keymap and so on) and the Quicksave thing.
Whatever we choose about the former, which in my opinion deserves a separate issue, the latter would benefit by being solved. There are people who enable it during menus, I find it ill-advised but adding the security on the notify thing doesn't hurt.
