### ISSUE TITLE
Ren'py on the web

### ISSUE THREAD

**Issue by marimeireles** [renpy/renpy#4241]
Hello!

Super cool project! I've just learned about it.

I'm currently working at [github.com/pyscript/pyscript/](github.com/pyscript/pyscript/) which brings python to the HTML and I thought it'd be super cool to have ren'py running on a webpage!

But I see that's very reliant of POSIX and depends on a bunch of libraries that won't really translate well for the web I guess?

I'm wondering if the maintainers would have any opinions around how to go about this? Is it possible, is it worth it to try to create a fork and work on it to make it web compatible?

Thanks for the work!

**Comment by MiiNiPaa** [comment]
You mean like [RenpyWeb](https://github.com/renpy/renpyweb)?
Web distribution already exist for 7.5 branch and work is going to bring it to 8.x

**Comment by marimeireles** [comment]
Oh wow!
That's awesome! :)
Sorry I didn't see it.
I think we can close this one as it's a solution.
Cheers!
