### ISSUE TITLE
[Feature Request] Apply transforms to layeredimage attributes in show statement

### ISSUE THREAD

**Issue by negatwo** [renpy/renpy#4242]
Would it be possible to add a feature that lets you apply transforms this way?

code line: show layeredimage_character mouth_1 eyes_1 At(effects_1, effects_animation_1)

It would be useful for single-case scenarios where defining a new attribute would've been required otherwise.

**Comment by renpytom** [comment]
No, this is out of the scope of layeredimage.

**Comment by renpytom** [comment]
Specifically, this would require the show statement to take things that aren't strings or words as parameters. That's not a change I think can be made.
