### ISSUE TITLE
None translation "Line with id %s appeared twice"

### ISSUE THREAD

**Issue by Selenyhr** [renpy/renpy#4243]
Hello,

This behavior is present in both 8.0.3 and nightly 8.1.0.23011101n.

When translating a string using the None translation language, if the new string is the same as the old one, Ren'Py raises the `"Line with id %s appeared twice"` exception, although one of the strings is part of a translation block. Using the same trick with a non-None language does not raise any exception.

The following code raises the issue:
```renpy
define e = Character("Eileen")

label start:

    e "You've created a new Ren'Py game." id start_a170b500

    return

# game/script.rpy:5
translate None start_a170b500:

    # e "You've created a new Ren'Py game."
    e "You've created a new Ren'Py game."
```

```
I'm sorry, but an uncaught exception occurred.

While loading the script.
Exception: Line with id start_a170b500 appeared twice, at game/script.rpy:5 and game/script.rpy:10.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/selenyhr/downloads/renpy-8.0.3-sdk/renpy/bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "/home/selenyhr/downloads/renpy-8.0.3-sdk/renpy/main.py", line 489, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "/home/selenyhr/downloads/renpy-8.0.3-sdk/renpy/script.py", line 308, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "/home/selenyhr/downloads/renpy-8.0.3-sdk/renpy/script.py", line 842, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "/home/selenyhr/downloads/renpy-8.0.3-sdk/renpy/script.py", line 438, in finish_load
    self.translator.take_translates(all_stmts)
  File "/home/selenyhr/downloads/renpy-8.0.3-sdk/renpy/translation/__init__.py", line 166, in take_translates
    raise Exception("Line with id %s appeared twice, at %s:%d and %s:%d." %
Exception: Line with id start_a170b500 appeared twice, at game/script.rpy:5 and game/script.rpy:10.

Linux-6.1.4-arch1-1-x86_64-with-glibc2.36 x86_64
Ren'Py 8.1.0.23011101n
bugtl 1.0
Thu Jan 12 14:19:31 2023
```

Shouldn't this exception only be triggered when assigning the same id to two script lines?
```renpy
    e "You've created a new Ren'Py game." id start_a170b500
    e "What are you doing?!" id start_a170b500
```

Thank you for the time spent investigating this issue.
Selenyhr

**Comment by Gouvernathor** [comment]
Having translation nodes for the None language makes no sense : the dialogue lines associated with the None language are the ones present in the script. None translations only make sense for string translations (the `translate strings` block).
What would be the intended behavior ? If we took None-translated dialogue into account, what would become of the original dialogue lines, and under what conditions would it be shown on screen ? Why not write the None-translated strings directly in the game ?

**Comment by Selenyhr** [comment]
Using a None translation block allows to correct potential script mistakes, while not changing the automatic ID generated by Ren'Py, which in turn allows for game translations not to become messed up just because of some typo in the original text.
Plus, another unwanted side effect of changing the original dialogue line directly is that the new line is not flagged in the persistent data for already seen dialogue lines, which can lead to players being annoyed while skipping through the dialogue without the "skip unseen" parameter enabled.

When correcting a dialogue line through the None translation, the issue does not arise because the original line and the translated line are usually different. However this issue can be quite annoying when working with generated translations through the Ren'Py launcher ; you can not generate the None language without the entire game bugging out due to this. And changing the dialogue line id is also something that would not work, because it would invalidate all of the work done on regular translations of the game.

> What would be the intended behavior ?
The intended behavior would be for the translation to work the same way any other translation would. When Ren'Py reaches the dialogue line, it will look up into the None translation and display whatever is inside of it, regardless of whether it is the same as the original line or not.

> If we took None-translated dialogue into account, what would become of the original dialogue lines, and under what conditions would it be shown on screen ?
The original dialogue line would not be shown on the screen. Just show the contents of the translation block like the engine already does.

> Why not write the None-translated strings directly in the game ?
The main issue is for the translation issue mentioned above. In most projects, it is an undesirable thing to translate the same lines again and again just because of some slight typo in the original language. Combined with the fact that Ren'Py dialogue line ids are not easily guessable, it becomes even harder to do the right changes in the right places just to fix a typo.

**Comment by MiiNiPaa** [comment]
The documentation does not agree with None translation not making sense, in fact, it encourages it:
https://www.renpy.org/doc/html/translation.html#tips

**Comment by Gouvernathor** [comment]
Sorry @miinipaa I had your comment displayed three times and I only tried to delete the duplicates, my mistake.

**Comment by Gouvernathor** [comment]
> The original dialogue line would not be shown on screen.

So you have a line written in script, that doesn't really mean anything and whose dialogue is never displayed ? That's what doesn't make sense to me. Maybe in a line-by-line basis, as a way to fix typos which is now obsoleted by the `id` clause, but in large scale it's only wasteful and prone to errors.
And we're only talking about *concept* issues, to which, no doubt, consequent *implementation* issues add up.

The solution for typos is to use the `id` clause. I.e :
```rpy
label start:
    e "Scrambled egs wit chese !"

translate french start_a:
    e "Omelette du fromage !"
```
turns into :
```rpy
label start:
    e "Scrambled eggs with cheese !" id start_a
```
and the translation file remains unchanged.
That's the canonical intended way, specifically to avoid having to change the id of the line and to update the translations.

I'm not sure why None translation blocks are allowed, and used in examples as Mii points out, maybe it was the former way of adressing typos. @renpytom ?
Anyway I think we should prevent the launcher from generating (dialogue) translations for the None language, or at least add a warning that it will break things, and remove that example from the doc.

**Comment by Andykl** [comment]
`translate None id` does not work actually, it messes up the AST and lead to undefined behavior, only `translate None strings` works. I don't remeber in which issue, but I shared my script to auto generate id clases to say statements, so after that script run you can change original line and do not lose translated lines.
