### ISSUE TITLE
Images on the GL2 renderer get cut in half and skewed

### ISSUE THREAD

**Issue by thelordofcorruption** [renpy/renpy#4245]
Hello, a small number of people that play the game that I work on have reported getting some of their images cut in half and skewed.
I believe this happens on the GL2 Renderer. Changing the renderer from GL2 to ANGLE2 seems to fix the issue for these people.
![screenshot0001](https://user-images.githubusercontent.com/111158601/212471635-ce524885-4b18-4a38-94f5-454741facca5.png)
Some people have said that this is due to large resolution images (I do have some 4000x5000 images that also have this issue) but I believe this to not be true as the menu image is 2880 x 1800 yet it has the same issue and the ANGLE2 renderer does not have the issue either.

**Comment by loafylemon** [comment]
This might be a driver issue. https://github.com/renpy/renpy/issues/4009

**Comment by renpytom** [comment]
We'd certainly need the log.txt from a computer with the problems to see if there is anything that can be done - but given this hasn't changed in a while, driver issues are a very likely culprit.

**Comment by renpytom** [comment]
Thinking about this, this is almost certainly a driver issue. The stream of commands that Ren'Py issues in GL2 and ANGLE2 is the same - the UGUU translation layer sends them to one or the other systems, but Ren'Py should be doing the same thing. 

If it's being rendered differently, it means that GL and Angle/DirectX are doing different things for same commands. But that's not a Ren'Py issue.

**Comment by thelordofcorruption** [comment]
I see thanks for the response. I would have posted more data but it's been very hard trying to get in contact with these people. As soon as I told them how to fix it by changing the renderer they stopped responding and never sent any info. I do know that one of these people have a AMD Radeon HD 7450 so yeah it seems old gpus with ancient drivers are likely the culprit.

**Comment by shawna-p** [comment]
I was able to obtain a log.txt from a player experiencing a similar issue:
[log - visual bug.txt](https://github.com/renpy/renpy/files/10636526/log.-.visual.bug.txt)


It should be noted that the images which cause this range from 4000x2250 to 2500x3500 in my game. I don't use this size for all sprites, just the two main characters whose sprites are often zoomed in on, and they are the only images I've seen anyone report issues with.

**Comment by renpytom** [comment]
@shawna-p I still believe this is a driver issue, not a Ren'Py issue. The user appears to be using version 15.201.1301.0, of the AMD drivers, which came out in early 2015. There does appear to be a newer driver available at https://www.amd.com/en/support/graphics/amd-radeon-hd/amd-radeon-hd-7000m-series/amd-radeon-hd-7570m . 

I'm probably not going to change Ren'Py to deal with issues in the drivers for 11 year old GPUs.

**Comment by shawna-p** [comment]
I wouldn't be surprised if it was; I did tell the user to update their drivers and try one of the other renderers. After I sent this file they told me they hadn't yet taken my advice to update the drivers so I'll see if I can report back that it fixes the problem or not.
