### ISSUE TITLE
Text in center of "side" UI Container can overflow due to word wrap

### ISSUE THREAD

**Issue by PhanesDionysos** [renpy/renpy#4253]
I'm not sure if this is a bug or a feature request.

When a text child of a `side` container is placed in the "c" position and something else is placed in "r" (or another width-affecting position), the total height is calculated based on the height of the text when rendered according to the _total_ width.

This means that if the remaining width after the "r" child is sized causes the text to word-wrap, the text height will end up larger than the height of the container and overflow.

For instance, the following container:

```
button:
    fixed:
        fit_first True
        
        expandside("r c"):
            xfill True

            text right_text color "#555" xalign 1.0 text_align 1.0 layout "nobreak" xoffset -10

            text left_text
```
...will overflow downward if `right_text` is long enough that `left_text` will word wrap.

I'm not sure what the solution should be; I've subclassed `renpy.display.layout.Side` to add a line in the middle of the render() method where `cwidth` and `cheight` get their final calculations:

```
            cwidth = min(cwidth, width - left - lefts - right - rights)

            _, cheight = sizeit('c', cwidth, height, 0, 0)

            cheight = min(cheight, height - top - tops - bottom - bottoms)
```
...but that's probably not gonna be a general-purpose fix, since it generally assumes that we want the width of the "c" child to remain the same, but the height to expand.

Maybe this is a feature request to add an extra parameter to `side` called `expand_down` that defaults `False` for this situation.

**Comment by renpytom** [comment]
I think I have a general fix, which is to render the center displayable before all the others, and then expand cwidth and cheight if it becomes bigger. 

I don't think there's a need for a parameter to invoke this - I think it makes sense to deal with this expansion whenever the expansion occurs. (Which is really only in the case of text wrapping.)
