### ISSUE TITLE
Android Build Failed (8.0.3)(8.1.0.23011403n)

### ISSUE THREAD

**Issue by Codes301** [renpy/renpy#4254]
OS: Linux Mint 21.1 Cinnamon
Linux Kernel: 5.15.0-58-generic
Cinnamon Version: 5.6.6
Renpy version: **8.0.3.22090809**  and tested on **8.1.0.23011403n**

For some reason it worked on a newly created blank project with nothing added to it.

I've attached some files to look at for this.
[android.txt](https://github.com/renpy/renpy/files/10421570/android.txt)
[android2.txt](https://github.com/renpy/renpy/files/10421572/android2.txt)
[build.gradle.txt](https://github.com/renpy/renpy/files/10421573/build.gradle.txt)
[build.gradle2.txt](https://github.com/renpy/renpy/files/10421574/build.gradle2.txt)

I've tried adding the NDK version to the location of:  /renpy-8.0.3-sdk/rapt/Sdk/ndk/21.3.6528147
Which did not work either.

I have tried several things as well which did not work either such as:
    Clean - to remove android temporary files
    Force Recompile (android)
    Delete Rapt folder and re-download it
    Clean temporary files
    Re-configure from configure in android menu section of Renpy
    Delete persistent
    Force Recompile (Main menu renpy)

Another thing I've noticed with creating Android builds is that is also slows my desktop pc significantly during the process.

**Comment by renpytom** [comment]
Is your game under the 2GB limit?

**Comment by Codes301** [comment]
> Is your game under the 2GB limit?

No. But one of my other ones were above the 2GB limit for android phones and that worked some time ago before the 8.0.3 version

**Comment by renpytom** [comment]
It looks like you're going over 4GB, which is a hard limit for the APK format. 2GB is the supported maximum size. 

You'll need to shrink your game until it fits inside a package.

**Comment by Codes301** [comment]
> It looks like you're going over 4GB, which is a hard limit for the APK format. 2GB is the supported maximum size.
> 
> You'll need to shrink your game until it fits inside a package.

If this is not listed in Ren'py documentation can you please add that bit of info? Also thanks for answering this question. I downsized the game until it was under that 4GB hard limit. And yes that worked.

**Comment by mal** [comment]
It is documented [here](https://www.renpy.org/doc/html/android.html#step-4-build-and-install-the-package) section about packaging in the page about [Android](https://www.renpy.org/doc/html/android.html).
