### ISSUE TITLE
Add support for building distributions in CI/CD pipelines

### ISSUE THREAD

**Issue by micka190** [renpy/renpy#4257]
In the past, I've seen people ask about being able to build in a CI environment here and on the forums. 

The usual answer was "that's not supported", and it was because of the difficulties of handling `.rpyc` files in those environment.

Since then, though, the [`old-game/` directory and "Update old game" feature](https://www.renpy.org/doc/html/build.html#the-old-game-directory) have been added to Ren'Py.

While the docs don't mention whether the launcher automatically uses the `.rpyc` files found in the `old-game/` directory as a base, manually copying those files over to the `game/` directory in a CI environment is trivial (it's just using the `rm` and `cp` commands to get a "clean build slate").

Digging around in the `renpy.sh` and `launcher/game/distribute.rpy` files, we can see that there are `distribute` and `update_old_game` subcommands available to the launcher (but not to the user through the CLI).

There was a previously unsupported way to call those commands through `renpy.sh launcher [directory] [subcommand]`, but it seems an update got rid of the `launcher` command, since `renpy.sh launcher [directory] [subcommand]` now tries to find the `launcher/` directory, and using the new proposed `renpy.sh [directory] [command]` yields an unexpected command error when using `distribute` or `update_old_game`.

If those subcommands were exposed in a way that's callable from the CLI, it should make building distributions in a CI/CD environment possible while providing a system to properly handle `.rpyc` files:

- Optional*: Manually remove all `.rpyc` files from the `game/` directory
- Optional*: Copy the `.rpyc` files from the `old-game/` directory over to the `game/` directory
- Run the `distribute` command
- Run the `update_old_game` command
- Save the distribution and updated `old-game/` directory as release artifacts

\* Only needed if the `distribute` command doesn't automatically use the `old-game/` directory as a base for its `.rpyc` files.

**Comment by Tapiiri** [comment]
Hey @micka190,

I'm currently able to run `renpy.sh launcher distribute [Game Directory] `, with both 7.5.3 and 8.0.3. I couldn't quite make clear from your comment if this was the command format you were calling with?

**Comment by micka190** [comment]
I'm curious about what your environment looks like (OS, distro, etc.), if you're using a clean install of Ren'Py or whether updating doesn't properly replaces the `renpy.sh` file (that would be unexpected, though).

Because I'm using Ren'Py 8.0.3, and running `renpy.sh launcher distribute [Game Directory]` in my CI and in a Docker image both return this:

> Base directory '[some path]/launcher' does not exist. Giving up.

`renpy.sh --version` yields the following output:

> Ren'Py 8.0.3.22083102

Here's an example screenshot from my Drone CI environment with the demo project I was messing with at the time of writing the issue:
![renpy-ci-cd](https://user-images.githubusercontent.com/63615275/220502602-f2d3829c-7892-42b9-a9fb-b37b6ec95dce.PNG)

Plus, running `renpy.sh --help` shows that the "correct" way to run these scripts now is to use `renpy.sh [basedir] [command]`, so `renpy.sh launcher [command] [basedir]` shouldn't work anymore (according to the `--help` output, at least). Which is part of what this issue is for: having a supported way to build in pipelines.

![renpy-help](https://user-images.githubusercontent.com/63615275/220503198-7ca6c95a-a484-4899-a029-e6c7c0a074b7.PNG)

**Comment by mal** [comment]
The second argument `launcher` should point to the `launcher` directory inside the Ren'Py SDK. i.e. `???/renpy-8.0.3-sdk-ci/launcher`.

**Comment by micka190** [comment]
> The first argument `launcher` should point to the `launcher` directory inside the Ren'Py SDK.

Well today I learned!

Seems like `renpy.sh /[sdk path]/launcher update_old_game [game path]` and `renpy.sh /[sdk path]/launcher distribute [game path]` work when using the launcher path.

While that does address the whole "what command do we use in a CI environment" point, the rest of the issue still stands, though:

It'd be nice to have an officially documented (and supported) way of doing it. As it stands, this seems to be an unofficial way of doing it, and is subject to change. *Technically*, the `launcher` thing isn't even listed under `renpy.sh`'s `--help` output, and you just kind of have to know that it's possible to do it (I initially learned about it by digging around on the forums).

Additionally, documenting things like how `update_old_game` (and its GUI version) work in more depth would be nice. We don't know if we need to manually delete the current `.rpyc` files in `game/` or if the command/button does it for us, or if we need to manually copy the contents of `old-game/` over or not to have the `distribute` command use its `.rpyc` files.
