### ISSUE TITLE
Read only issue when executing inside a Flatpak application 

### ISSUE THREAD

**Issue by Steinhagen** [renpy/renpy#4258]
When running renpy inside a flatpak (which mounts the /app directory as read-only at runtime) will result in the following exceptions:
```
  File "/app/share/renpy/renpy/script.py", line 650, in load_file
    with open(rpycfn, "wb") as f:
```
This doesn't have any affect on the game executed, except the walls of exceptions raised for all rpyc files. Is there a way to fix this issue when executing inside a flatpak application?

Flatpak application example: https://github.com/flathub/com.katawa_shoujo.KatawaShoujo

**Comment by renpytom** [comment]
You want to make sure to include a correct version of the .rpyc files with the flatpak. What's happening is that Ren'Py is trying to recompile the .rpycs, and failing to save the results. You're then getting the error you see.

**Comment by Steinhagen** [comment]
May be a dumb question, but is there a way to recompile the files without running the game?

**Comment by Steinhagen** [comment]
renpy.py /path/to/game/ compile
