### ISSUE TITLE
Hard crash in nightly when using audio keywords

### ISSUE THREAD

**Issue by mal** [renpy/renpy#4259]
**Steps to reproduce**
1. Open Tutorial
2. Start game
3. Open console
4. Enter
    ```rpy
    play music "<from 1>renpyallstars.ogg"
    ```
5. Game ends without warning or logs

**Versions**
Last known good: `8-nightly-2023-01-08-8.1.0.23010802n`
First known bad: `8-nightly-2023-01-10-8.1.0.23011001n`

**Environment**
Platform: Linux x86_64

**Notes**
Best guess would be the build process changes in `renpy-build`.

**Comment by mal** [comment]
This still presents in `8-nightly-2023-01-18-8.1.0.23011701n`.

**Comment by renpytom** [comment]
This is probably a build issue, try it again in the 2023-01-19 nightly.

**Comment by mal** [comment]
Confirmed good in `8-nightly-2023-01-19-8.1.0.23011901n`.
