### ISSUE TITLE
Ren'Py 8.0.3 releases does not includes #4008.

### ISSUE THREAD

**Issue by yi-yunseok** [renpy/renpy#4260]
`ctx.translate_identifier = tid` #4008 is gone. The translation problem is reproduced with the nointeract menu statement.

**Comment by mal** [comment]
The patch landed a month and a half after 8.0.3 shipped, so I believe this is expected. It will ship as part of 8.1/7.6.

**Comment by yi-yunseok** [comment]
Oh I don't think its release date.
