### ISSUE TITLE
Allow details tag to Character()

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4262]
After proposing this #4248 it occurred to me to include this type of tag `Character("Name" details={})`, this could return any data you want to add to the character.

For example:
 ```

define n = Character("Name" details={
    surname : "Surname",
    love: 0,
    friends: ["Sam,", "Eli"]
})

label start:
    
   "[n.details.surname]"
   $ n.details.love +=1
   "[n.details.love]"
```
Of course, this expects an object and any type of information inside, it does not necessarily have to have the same data as the example. Since it is expected to be a field that allows to add details of that particular character and in case of not receiving anything this would be "None". Or an empty object, however, I suppose that "None" would be the most correct.

and this could also be complemented by what I commented in #4248, that callback could access this tag and consume what is here, for example if there is "name" it would be used by callback, however, this idea may contain the problems mentioned here https://github.com/renpy/renpy/issues/4248#issuecomment-1383568451. 

Now, by proposing this I feel that we can extend Character() a bit more, for example: you can create character stats, extra details or any other kind of character information that can be used anywhere in the game. It could also serve as an alternative to creating several variables on a character.

**Comment by Gouvernathor** [comment]
The problem is that Character objects do not work with rollback, and in the example you use (as in most uses of such a feature), the values get to change along the game.
The solution for this is a named store, and the use of the `character` special named store.
```rpy
define character.n = Character("Namo")
default namo.surname = "Surname"
default namo.love = 0

label start:
    n "Hellu" # works because of the character store
    "[namo.surname]"
    $ namo.love += 1
```

**Comment by MiiNiPaa** [comment]
> Now, by proposing this I feel that we can extend Character() a bit more, for example: you can create character stats, extra details or any other kind of character information that can be used anywhere in the game. It could also serve as an alternative to creating several variables on a character.

I feel that it does things wrong way: it makes more sense to have a reference to `Character` (which defines display properties) object in greater structure describing your VN character as a whole, not to bring gameplay related data in class made to print words on screen.
