### ISSUE TITLE
Ren'Py 8.0.3 Project Launch issues

### ISSUE THREAD

**Issue by exvilness** [renpy/renpy#4269]
The Project Launch button does not seem to work in Ren'Py 8.0.3 for me. It doesn't work for tutorials, doesn't work for created projects, doesn't create a log/traceback file, uninstalling and reinstalling it hasn't solved the problem.
I'm on Windows.

**Comment by exvilness** [comment]
A log.txt file was created but still no traceback or error files visible in the game directory:

Sat Jan 21 19:26:28 2023
Windows-10-10.0.19045
Ren'Py 8.0.3.22090809
 

Bootstrap to the start of init.init took 0.03s
Early init took 0.00s
Loader init took 0.03s
Loading error handling took 0.14s
Loading script took 0.29s
Loading save slot metadata. took 0.00s
Loading persistent took 0.00s
Set script version to: None (alternate path)
Running init code took 0.32s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.02s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.24s
Cleaning stores took 0.00s
Init translation took 0.04s
Build styles took 0.00s
Load screen analysis took 0.03s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.06s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.08s

Initializing angle2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'Google Inc.'"
Renderer: b'ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)'
Version: b'OpenGL ES 3.0.0 (ANGLE 2.1.0.a4b21cf26074)'
Display Info: None
Screen sizes: virtual=(800, 600) physical=(800, 600) drawable=(800, 600)
Maximum texture size: 4096x4096

**Comment by renpytom** [comment]
I'd suggest looking into your project, and potentially looking at the names of the directories containing your game. (There could be a problem if they're not representable in your system's encoding - your best bet is to go with c:\renpy-8.0.3 and c:\myprojects , if you're having these problems.) 

Other than that, I don't have a great idea what could be wrong. Ren'Py 8.0.3 has been used by many people without problems, so whatever is happening is specific to your install.

**Comment by danac78** [comment]
What version of Windows? If it is Windows 10, is it 32 or 64bit? If I am reading it right, Windows 32bit would cause a problem since 8.0.3 is 64-bit @renpytom?

**Comment by exvilness** [comment]
Thank you @renpytom, apparently the directory was all messed up and I never even realized!
