### ISSUE TITLE
Renaming the text_align property

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#4271]
I've noticed that the `text_align` property is an extremely common source of confusion in screen language, particularly as it relates to the `align` property and the `text_` prefix for the text portion of labels and textbuttons. For example:

```renpy
text "Hello" text_align 0.5 # <- Actually center-justifies the text

textbutton "Hello" text_align 0.5 # <- Error

label "Hello" text_align 0.5 # <- Error

textbutton "Hello" text_align (0.5, 0.5) # <- No error, but adjusts the x/y align of the text, not the text_align

label "Hello" text_align (0.5, 0.5) # <- No error, but adjusts the x/y align of the text, not the text_align

textbutton "Hello" text_text_align 0.5 # <- Actually center-justifies the text

label "Hello" text_text_align 0.5 # <- Actually center-justifies the text
```

In particular it's the combination of the `align` property existing + the `text_` prefix assigning a property to the text of the label/textbutton that leads to `text_align` meaning two different things depending on whether you're using it in a text style or directly as a property for a label or textbutton.

`text_align` can still remain a property in modern Ren'Py, but I suggest having it as an alias to a name with fewer conflicts, such as `alignment` or potentially `justification`, eliminating the confusion.

At minimum, if renaming isn't an option, having clearer error messages for the two errors I showed above would help people understand what the issue is.

**Comment by renpytom** [comment]
This is a reasonable ask, though I'm not sure about the names. ``justification`` is too close to justify. ``alignment`` might work, if nobody has any other ideas.

**Comment by Gouvernathor** [comment]
Maybe textalign, no underscore, which would facilitate the transition and yet break the confusion with the text_ prefix (I know we will maintain compatibility).

Or laterality. It has the advantage to not resemble existing properties like alignment and justification do, but I would prefer textalign better. Maybe talign ? Hopefully nobody will think we're aligning along the time dimension...

**Comment by shawna-p** [comment]
`textalign` could be all right in that it eliminates the underscore in a similar fashion to `xalign` but it doesn't follow the same rule as properties like `left_padding` where an underscore separates words. It also still means you're doing `text_textalign` which, while less confusing, still isn't ideal in my opinion. My preference is probably `alignment` despite the similarity to `align` since that's what most word processors call this feature, though it does allow for the potential of someone mixing it up with `align`. I'd be glad to hear more suggestions though if we can come up with a more distinct name that still makes the purpose clear.

**Comment by Booplicate** [comment]
I'd prefer it without any `text` prefix. `justification` looks better because there's many `align` and only one `justify`, which while named similarly, also does something *similar* and also with text. But generally `alignment` could also work.

**Comment by Gouvernathor** [comment]
I don't like `paragraph_align` because even if you have a `/n` in the middle of a text, the property will apply before and after it so it dosn't apply to one paragraph.

How about `justifalign`, since it's a mix of the two ? `justification_alignment` is too long anyway. I like to keep the ð`align` pattern, without space, because the property is really similar to a `xalign` in how it infers placement of the lines of the text. So, `justifalign` or `textalign` make sense to me.

**Comment by renpytom** [comment]
It was ``textalign`` in the past, and I think it got switched to ``text_align`` for some reason. Switching it back might be the right way to go.

**Comment by Gouvernathor** [comment]
Apparently it's the opposite. In generate_styles.py, textalign is the proxy and text_align is the actual datapoint. bcd95d937ced98a7b00e045a1cb29f79effc0abe added them in that fashion, and both seemingly at the same time.

**Comment by GohoDigitals** [comment]
It's working like in my project like that:

text_align (0.5,0.5)

**Comment by GohoDigitals** [comment]
It's working like that in my project :

text_align (0.5,0.5)
