### ISSUE TITLE
Add the ability to build a game as a Flatpak

### ISSUE THREAD

**Issue by thelordofcorruption** [renpy/renpy#4274]
As the title says, I think it would be awesome if Ren'py had the ability when building a game for Linux to be able to build it as a Flatpak so developers could easily submit their game on Flathub or just to provide the Flatpak package itself. Having a game on Flathub / as a Flatpak package means Steam Deck (and Linux users in general) can easily access these games.

Someone did already open a issue in regard to Flatpak (#3290) but the person was asking for Ren'py itself to be provided as a Flatpak which I think is unnecessary but being able to build a Ren'py game as a Flatpak would make things easier for users in general to try out the game.

**Comment by thelordofcorruption** [comment]
Also I feel like a game in a Flatpak might also make Ren'py games work even on more weird Linux setups where the game wouldn't normally work maybe.

**Comment by renpytom** [comment]
I'll be honest that this is fairly unlikely. Of this sort of format, AppImage would be my choice, but I'm not sure how easy it is to create one outside of Linux.

**Comment by thelordofcorruption** [comment]
Thinking about it, AppImage would be a better option if it can be done.

**Comment by thelordofcorruption** [comment]
Looking more in to it, it seems using a docker might be the best option to make the appimage. As for how to make the appimage there are multiple options https://docs.appimage.org/packaging-guide/index.html but using https://appimage-builder.readthedocs.io/en/latest/index.html might be the most sensible way to go about it. They also offer a prebuilt docker image with appimage-builder already in it.

**Comment by renpytom** [comment]
If docker is needed, this is out of the scope of Ren'Py proper.
