### ISSUE TITLE
Regression introduced with sync

### ISSUE THREAD

**Issue by Booplicate** [renpy/renpy#4282]
[This commit](https://github.com/renpy/renpy/commit/b42b24be756a0a20d909bf6b7e9dcb16f11bf004) introduced a change that made older persistent incompatible.

### Issue
I have a persistent made in a game built with renpy 7. When I load it in a build made with nightly, renpy replaces it with a newly generated persistent. If I close the game and open again, renpy doesn't nuke the persistent. I dig into the code and added some debug prints to see what's going on.

This is `renpy.persistent.load`
![Capture](https://user-images.githubusercontent.com/53382877/214929317-7f3d6485-2a69-46ba-96bd-c4d4d07bb221.PNG)

and I indeed can see the "token doesn't match" line printed in the log.

### Proposal
- need some compatibility level to be able to load persistent from old games in the new renpy
- when a persistent cannot be loaded due to failed verification, renpy should throw a clear error about what's going on. Otherwise people are going to lose their data without even knowing when or why

**Comment by renpytom** [comment]
First off, which editor/extension is that, that's adding in the type information like that? 

This should only happen if the game has not been upgraded to use save tokens. The first time - per game - a player moves from the old version to the new version, the persistent file will be upgraded. After that, save token security will be enforced.

Are you moving information into a game after the first time it's run?

**Comment by KiloOscarSix** [comment]
@renpytom It's a VSCode setting - `InlayHint`
```json
    "editor.inlayHints.padding": true,
    "python.analysis.inlayHints.functionReturnTypes": true,
    "python.analysis.inlayHints.variableTypes": true,
```

You can also use the following to add colour customisation to the Inlay hints
```json
    "workbench.colorCustomizations": {
        "editorInlayHint.background": "#00000000",
    },
    "workbench.colorCustomizations": {
        "editorInlayHint.foreground": "#868686f0",
    },
```

**Comment by Booplicate** [comment]
Yes, those are the setting within VSC I use, I think it's provided by pylance, but might be wrong.
```json
"python.analysis.inlayHints.functionReturnTypes": true,
"python.analysis.inlayHints.variableTypes": true,
"editor.inlayHints.padding": true,
```

> only happen if the game has not been upgraded to use save tokens

Can you explain, how I should upgrade the game? My actions were:
- making a build using nightly renpy (latest at the moment)
- creating the save dir
- moving persistent to the save dir

It was a one way transition pre 8.0 into 8.1 nightly

**Comment by renpytom** [comment]
I believe this is save security working as designed, making sure that you can't load a persistent file after the transition has happened.

**Comment by Booplicate** [comment]
The problem was caused by a sum of changes. I have global saves disabled, so building making a save file wasn't an issue. But with the new changes renpy initialises saves multiple times, and now forces saves to be saved globally. I think it indeed used tokens generated from building with the persistent I added manually, which caused the conflict. So works as intended.
