### ISSUE TITLE
Delayed and/or compated syntax errors

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4284]
For #3738 and #3821.
We need some currently accepted but faulty behaviors to lodge a syntax/parsing error, but that error be ignored if we're in compat mode for before the error started being raised.

Either the compat version is known early enough, in which case it's just a conditional raise, or it's not and we need to store the error and delay it for when the compat version is known.

In #3821's case, we need to check for a config variable too, not just the compat version - that is unless we drop the opt-out, but I think it's better with it.

**Comment by Gouvernathor** [comment]
It is possible to require certain compat config variables to be placed in [0-9]-starting files, same as cds, so it's available during the parsing of subsequent files.
If doing that, it doesn't look like there is a need for any kind of delay, and any other compat mechanism than `if renpy.config.enable_obsolete_behavior:`.

**Comment by Booplicate** [comment]
@Gouvernathor could it be possible to allow defining config vars via a config file? That way it could be read first before parsing scripts.

**Comment by Gouvernathor** [comment]
I don't think adding a separate kind of file format, or special-casing `config.rpy` to be parsed first (depending on what you meant) would be a great idea.
But if `behav` is defined internally as an early config, putting `define config.behav` in 01config.rpy will be enough. That's the case for config.allow_duplicate_labels for example. The list is in ast.py, as EARLY_CONFIG.

**Comment by Booplicate** [comment]
I meant some `config.json` (or `yaml`, or anything else depending on your needs). It could be read and parsed after this line:
https://github.com/renpy/renpy/blob/3e0a84ee8c2b1016f310ff9696a21f91a58bb7fd/renpy/main.py#L357
allowing you to load config variables easily. So you wouldn't need to think how to make sure your config var will be loaded in time or maintain extra list of config vars.

**Comment by Gouvernathor** [comment]
I don't think we need this. There is a landed habit of defining config variables in the script files, using normal define statements, and there is even a special syntax of augmented define statement that's specifically dedicated for iterable config variables.
Some config variable need to be defined alongside a computed value, for example arjust_attributes alongside the definition of the functions put inside it (or at least after the definition took place).

If you put all the config variables in a json file, you break this.
If you arbitrarily put only some of them in json, you start applying a double standard which I think is not a good thing for code clarity.
If you only put the early configs in there, I don't think it makes things simpler than putting them in 01compat.rpy. At least implementation-wise it certainly wouldn't, since we need to keep the current behavior for compatibility, and for code clarity and simplicity I think it's not any better.

**Comment by renpytom** [comment]
I just committed what I think is the basis of the solution - a system that will let errors be queued up, and be unlocked or ignored by config variables.
