### ISSUE TITLE
The sync could not be decrypted (custom save cloud)

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4285]
using a custom server I managed to upload the hash to a server, and also retrieve it. Apparently renpy is having trouble decrypting the hash. I guess the problem is in this line.
https://github.com/renpy/renpy/blob/ea4e9bc1443949a6975eaf43f91868d2d52aaf42/renpy/common/00sync.rpy#L434

now according to download_content() if it returns false it is correct, and according to a print I made in the function it returns false and takes the hash as correct/valid.

https://github.com/renpy/renpy/blob/ea4e9bc1443949a6975eaf43f91868d2d52aaf42/renpy/common/00sync.rpy#L284

![imagen](https://user-images.githubusercontent.com/36079551/215309508-30278b5e-6a60-46f2-b6ab-533826750dbf.png)

I don't think it is the server, but just in case I share it here: https://github.com/Neyunse/Custom-RenPy-sync-server

**Comment by renpytom** [comment]
This doesn't appear to be an issue with Ren'Py.

**Comment by Neyunse** [comment]
Oh @renpytom that's right! But my api can't access to content. In express 'req' the save doesn't appear. 🤔
req.body it's empty

**Comment by renpytom** [comment]
I'm not sure how to answer that, other than (with the change in 0c0b824be), this seems to work in Ren'Py, with the official sync server, which is the one I support.

**Comment by Neyunse** [comment]
I Noted that my problem is that my express server is not able to get "content" that is sent here. I see what it sends is `b' '`, but I can't get "content" from the server side.
https://github.com/renpy/renpy/blob/0c0b824be67c1c9f2b84404e6bc4ca9e68f029a3/renpy/common/00sync.rpy#L261

now I am experimenting to see if I can solve it by sending it as a param in the url in base64 format and have the server decrypt the base64 and store b' '. And then return that in renpy. but it seems like a dead end, I guess I will use the official server until I see a way to receive this data.
