### ISSUE TITLE
Game freezes on a black screen when minimizing and re-opening while playing on Android

### ISSUE THREAD

**Issue by Tymedust** [renpy/renpy#4286]
Hi!

I recently exported my Ren'Py game to Android and currently my testers are having a go at it over at Google Play Store via internal testing. Things seem well in general, except for the fact that all of them get the same recurring error, i.e. the game freezing on a black screen when minimizing and re-opening. This issue has never been reported in the computer (PC/Mac/Linux) version of the game despite over 5000 players having tried it, which leads me to believe that this must be an engine related Android issue.

My Ren'Py is updated to the newest version, 8.0.3.

My playtesters are all running the latest version of Android (13) and are either on a S20 FE model or a Pixel 8 Pro. The oldest phone used in the playtest is 3 years of age and the newest one is bought recently, so I doubt that's the issue either.

When scrolling through errors on Google Play I found something about a "defective version of OpenSSL"; no idea if that's related to the issue? I'm not the best programmer so I don't even know what that means unfortunately.

Thankful for any help in solving this! Have a great day. :)

![error](https://user-images.githubusercontent.com/123891561/215345480-a40dc505-159c-4ce3-a440-c092e119d498.jpg)

**Comment by renpytom** [comment]
The pixel 8 pro doesn't exist. 

I have a pixel 7, and if you'd like I can try your game on it so that I can see if I can figure out what's going wrong. 

My account is renpytom@gmail.com.

**Comment by Vulcan-Coder** [comment]
> The pixel 8 pro doesn't exist. 
> 
> I have a pixel 7, and if you'd like I can try your game on it so that I can see if I can figure out what's going wrong. 
> 
> My account is renpytom@gmail.com. 

The pixel 7/Pro only support x64 apks. Maybe that could be the problem.

**Comment by Tymedust** [comment]
> The pixel 8 pro doesn't exist.
> 
> I have a pixel 7, and if you'd like I can try your game on it so that I can see if I can figure out what's going wrong.
> 
> My account is [renpytom@gmail.com](mailto:renpytom@gmail.com).

Ah! That's what the tester said, I suppose he must have gotten it wrong. :)

Thank you so much for helping out, that's so kind of you! I've e-mailed you the link.

Thanks again and have an awesome day!

**Comment by wbrambley** [comment]
TBH it's been a problem for a while (for me at least)
7.5.3 seems affected as well. 
Making the same Android port on 7.5.0.242 the black screen after app switching doesn't happen as often if at all. 
My thoughts were it was something to do with SDL.

**Comment by renpytom** [comment]
Can you try out tomorrow's nightly? It will have a pair of changes meat to improve Android 12.

**Comment by wbrambley** [comment]
> Can you try out tomorrow's nightly? It will have a pair of changes meat to improve Android 12.

I will try it out, thanks.
I have attempted to introduce those changes into RenPy 7.5.3 release but didn't seem to change anything however I may be missing something.
Where can I find a reference for the default of "renpy.config.quit_on_mobile_background" ? I didn't find much in a quick search.
I did try 'define config.quit_on_mobile_background = False' in a late init and I haven't had the "black screen of doom" after switching multiple apps, return to home screen, screen off/on etc etc.

**Comment by renpytom** [comment]
It's a reasonable fix for this, though the game will shut down and reload each time you switch away. I'm not sure it's documented, but it's meant for this purpose. 

There's a second change in renpy-build the does a lot of the heavy lifting, and it requires patching SDL.

**Comment by Tymedust** [comment]
> Can you try out tomorrow's nightly? It will have a pair of changes meat to improve Android 12.

Thank you, I'll try it out asap and report back after my testers have tried the new Android build. Appreciate the help. :)

**Comment by Tymedust** [comment]
> Can you try out tomorrow's nightly? It will have a pair of changes meat to improve Android 12.

My testers report zero black screens since the latest export! This seems to have solved it. Thank you so much for your time and assistance! :)

**Comment by renpytom** [comment]
Thanks for testing. I'm closing this out.

**Comment by wbrambley** [comment]
Hi, sorry I'm late. I just ran a test on 7.6.0.23013001n and it's doing the same.  
I omitted define `config.quit_on_mobile_background = False` 
It seems to miss the fact the app has entered background the second time.
Tested on Android 10 Huawei mate 30 pro.
 ```
Screen sizes: virtual=(1920, 1080) physical=(2328, 1128) drawable=(2328, 1128)
Root FBO is: 0
FBO Maximum Texture Size: 2048
Total time until interface ready: 5.20904588699s.
Hid presplash.
Entered background. --------------------------------------------
Entering foreground. -------------------------------------------
Screen sizes: virtual=(1920, 1080) physical=(2328, 1128) drawable=(2328, 1128)
Root FBO is: 0
FBO Maximum Texture Size: 2048
```
![Screenshot_20230201_183831_my best deal](https://user-images.githubusercontent.com/1310205/215962299-e5b005b6-ea18-4295-85cc-19abb6c02a4e.jpg)
