### ISSUE TITLE
Distribution build using....way off time in 8.0.3

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#4291]
I could be missing something here, but...

When I taking some of the files and putting it into Steam, it is showing different times. For example, it was 1:02PM Arizona Time when I did a build, and it is saying 8:02 PM as a time it was created.

**Comment by danac78** [comment]
Tried with PC and it is compiling as 1/30/2023 at 8:24 when it was 1:24 where I am. What clock is the build basing it on?

**Comment by MiiNiPaa** [comment]
Seems to be UTC time.

**Comment by renpytom** [comment]
I don't think this is a real issue, just UTC vs Local.

**Comment by danac78** [comment]
@renpytom is it mentioned in the Documentation or will it be mentioned in the documentation that it uses UTC time? Because looking at build.html, it is not mentioned at all. If there is a reason for it to be arbitrarily UTC time rather than system clock time, it would be helpful.
