### ISSUE TITLE
What kind of encrypted data is sent in 00sync.rpy

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4293]
I am setting up a mini server apart from the one supported by renpy to store the saved games, my question is: What kind of data does the server receive? A file, a text type or some kind of byte array? 

From my server it seems to connect perfectly, but it is difficult to find what is being sent here: 
https://github.com/renpy/renpy/blob/a49bd0133c8c869272109cb98f0f661d0300c52b/renpy/common/00sync.rpy#L271

I thought it was sent in the body, but my `nodejs express server` tells me that the `request.body` is empty (undefined).

Here is the log of the server request, the server is receiving something because in the header you can see the weight of the data, but I can't reach it.

[req.txt](https://github.com/renpy/renpy/files/10541778/req.txt)

**Comment by renpytom** [comment]
It's application/octet-string binary data. 

Please don't ask questions about your implementation here - I don't know anything about your node.js server. I'm only supporting the official server for this feature - I don't plan to document the configuration variable to change it.
