### ISSUE TITLE
config.missing_image_callback is called in strange situations

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4303]
Not sure if it's intentional but after clicking on a button with config.missing_image_callback defined 
Ren'Py is trying to search for `"gui/button/selected_[hover and idle]_background.png"` that do not exist in newly created projects.

```
init python hide:

    def missing_image_callback(filename):
        renpy.notify(filename)
        return Image("gui/window_icon.png")

    config.missing_image_callback = missing_image_callback


screen test():

    default item = 0

    add Solid("#333")

    hbox:
        align (.5, .5)
        spacing 25

        textbutton "I'm a textbutton!":
            action SetScreenVariable('item', 1)

        button:
            text "I'm a button!"
            action SetScreenVariable('item', 2)
```

**Comment by qTich** [comment]
The entire interface is generated by default using the `prefix_` keyword,
which in turn is subsumed by `renpy.display.image.Image.find_target`,
which in turn calls `renpy.easy.dynamic_image`, and if no suitable image is found,
all tags will be searched, which will result in either `idle_` or `hover_`.

https://github.com/renpy/renpy/blob/9e02cf20f40a7020c27521fe334e91eaa334800a/renpy/easy.py#L179-L195

So this is deliberate behaviour.
