### ISSUE TITLE
Backslashes in renpy.gamedir

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4308]
It was recently documented as a good thing to pass to renpy.file and related functions, but on Windows it contains backslashes which renpy will reject. It's easily fixed when you know about it, but it can easily lead to platform-specific errors which are difficult to test for.
It would be simpler to convert it ourself internally - which probably won't cause any problem, considering everything accepts slashes as separators.

**Comment by Gouvernathor** [comment]
c7c7733

**Comment by mal** [comment]
I'm not sure why this was made direct to master, but it can break non-Windows systems that allow `\` as part of path names without treating it as a directory separator.

**Comment by Gouvernathor** [comment]
A misclick, that was reverted afterwards for that reason.

**Comment by mal** [comment]
Ahh, apologies, I was looking over changes chronologically and hadn't made it that far. 😓
