### ISSUE TITLE
Addition to Monologue Mode to allow all text to display at once.

### ISSUE THREAD

**Issue by Jeneara** [renpy/renpy#4312]
Hello,
I've been looking into ways to allow Monologue Mode to better be used for Interactive Fiction games or instances where the game requires all the text to display on the screen at once. Like a Letter or Codex page for example. An example of this in other engines would be the ChoiceScript or Twine.

Currently, in Monologue Mode, the below code will display each line separately, one after the other after requiring the player to click or use auto forward to show the whole section of dialogue 
```
"""
This is the first line of dialogue. It's longer than the other two
lines, so it has to wrap.

This is the second line of dialogue.

This is the third line of dialogue.
"""
```

I would like to be able to show the entire block of text at once on the page. I have managed to hack it a little and format the text like this while setting Text forward to 100%
```
"""
This is the first line of dialogue. It's longer than the other two lines, so it has to wrap.\n\n
This is the second line of dialogue.\n\n
This is the third line of dialogue.\n\n
"""
```
But adding `\n\n` or `{p}{p}` to the end of every line is very verbose. 

Not only that but I run into a text alignment issue as well.
The above code creates the below image and as you can see the first letter of each section is not aligned but rather a step forward in indentation
![Screenshot 2023-02-03 135000](https://user-images.githubusercontent.com/50791356/216502985-c7b7bc21-aabd-4898-a879-c6103833ddaa.png)

Doing the below code fixes this problem, but as you can imagine I find this code hard to read and debug.
```
"""
This is the first line of dialogue. It's longer than the other two lines, so it has to wrap.\n\nThis is the second line of dialogue.\n\nThis is the third line of dialogue.\n\n
"""    
```
![Screenshot 2023-02-03 134940](https://user-images.githubusercontent.com/50791356/216503234-b4996396-e637-48b8-8623-e4d554e62e33.png)

I'm hoping to figure out a developer-friendly way of implementing this function in Monologue blocks but I am not sure where exactly I would look in the codebase.

I was hoping something at the start of the `"""` to indicate the difference so that both standard Monologue mode and this mode could be used. `full """` for example. Thou I am not sold on the word `full`. 

I have previously looked into a CDS and while this did work it's not super beginner friendly to set up. 

Is this something that could be added or looked into?

**Comment by Gouvernathor** [comment]
Maybe `rpy monologue none` could disable monologue mode in a specified file - just like `rpy monologue single` changes its rules.
The `full` solution would collide with the character name, so it's unlikely we could go that way.

**Comment by Jeneara** [comment]
That makes sense! Yea it's why I wasn't sold on it because I don't like it being where that character name is but I still would like the function to use both modes in the same file. 

So having a way to disable or enable it within the script section.

**Comment by mal** [comment]
The splitting occurs when the file is parsed, and so @Gouvernathor's proposal seems like a good option if we want it as a feature.

However, if you really want to do it all in one file, then you could _maybe_ manage it by adding `{nw}` tags to the end of all but the penultimate line, that way I think you'll still be able to format it nicely in your script, display it all at once, and use normal monologue in the same file, but it's only slightly better than the approach you're already taking with `\n`. That said I've not used NVL mode much, so that's more speculating on something you could try, more than an outright solution.

**Comment by Jeneara** [comment]
Maybe @Gouvernathor's proposal is the way to go for now? And you just need to jump to a new script file to switch back if you really need to. Is that how it would work? is it contained too that script file?

**Comment by renpytom** [comment]
Can't you just do this with single quoted strings, not monologue mode? 

e "This is line 1.

Line 2.

Line 3."

Should work.

**Comment by Jeneara** [comment]
> Can't you just do this with single quoted strings, not monologue mode?
> 
> e "This is line 1.
> 
> Line 2.
> 
> Line 3."
> 
> Should work.

I tried that but it displays like below - Where I want them on separate lines
![Screenshot 2023-02-03 155448](https://user-images.githubusercontent.com/50791356/216515699-249d4248-4d10-46d8-a176-ddfbbeb1d43a.png)
![Screenshot 2023-02-03 085408](https://user-images.githubusercontent.com/50791356/216515704-4eab4e79-2088-42f8-a8e9-55838dbe58fd.png)

**Comment by Gouvernathor** [comment]
Yep, the linebreaks are replaced with spaces because of the spaces-collapsing mechanism (which integrates \n). In my trial I had to exclude \n from that regex : https://github.com/renpy/renpy/commit/9e0e85bc8667fdb3ee4ba1fb275027b406cc6769#diff-9390db80553a00f3c076c7d1bacf471db1cae239ea1eeac81da21ea0de1b912eR986
