### ISSUE TITLE
xycenter can't be used as a style property

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#4323]
I'd like to note that though #3945 adds the xycenter property to ATL, it is not included as a style property. Thus, the following is fine:

```renpy
text "Hello":
    at transform:
        xycenter (0.5, 0.25)
``` 
but the below is not:
```renpy
text "Hello" xycenter (0.5, 0.25)
```

I'm not sure if this was intentional seeing as it's documented only in the ATL doc pages rather than also in the style properties one, but it feels unintuitive to have it only in ATL and not as a style property.

**Comment by Gouvernathor** [comment]
Notwithstanding whether it works or doesn't, xycenter *is* listed in the [styles properties page](https://nightly.renpy.org/doc/style_properties.html#style-property-xycenter).

**Comment by Gouvernathor** [comment]
I can't reproduce this in the latest nightly. Your code works on my end.

**Comment by shawna-p** [comment]
Ah my apologies if it's fixed on the nightly then, I had only tested on the release build/looked through the release docs. Thank you!
