### ISSUE TITLE
Request for Steam deck variant build

### ISSUE THREAD

**Issue by Jeneara** [renpy/renpy#4325]
Hello,

I was wondering if there are any plans to have a variant build for the Steam deck similar to the mobile build?

I have heard some concerns that sometimes the standard PC build of a game doesn't translate as well to Steam deck due to the size of the screen.  Like too small text boxes and buttons etc. So I think having a variant build for the Steam deck would be really useful to avoid this issue.

Is this something that could be an option in the future?

**Comment by renpytom** [comment]
I believe this already exists. When you're running on the steam deck, the "steam_deck" variant is set.

**Comment by Jeneara** [comment]
OH, That's Awesome! Thank you ❤️
