### ISSUE TITLE
Ensure assets in the prototype project exist in the final game.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#4328]
To provide a way for the game to be customized to support third-party libraries.

**Comment by AircGroupStudio** [comment]
Okay. Strange you not give answer as i can do it's. But okay.
![Скриншот 06-02-2023 17 20 24](https://user-images.githubusercontent.com/93317344/216900341-8d46f86a-e846-4ac0-b3a5-7691e321b734.png)

![Скриншот 06-02-2023 17 15 42](https://user-images.githubusercontent.com/93317344/216900321-882b456f-2fea-4fb2-9b38-9b58e7615ca9.png)
