### ISSUE TITLE
Improving get_game_runtime() to include time spent in new contexts

### ISSUE THREAD

**Issue by altskop** [renpy/renpy#4335]
A feature discussion. 
I want to make sure I'm not missing anything before opening a PR for this.

Currently, the way `get_game_runtime()` works is it pulls `runtime` from top-level context only. See the snippet below:
```py
def get_game_runtime():
    """
    :doc: other

    Returns the game runtime counter.

    The game runtime counter counts the number of seconds that have
    elapsed while waiting for user input in the top-level context.
    (It does not count time spent in the main or game menus.)
    """

    return renpy.game.contexts[0].runtime
```

Therefore, any time spent in any new context is lost, rendering the counter inaccurate. 

My proposed solution: whenever we return to parent context, transfer the new runtime variable to it.
This works because whenever we create a new context (be it via `renpy.call_in_new_context` or `renpy.invoke_in_new_context`), we pass the top-level context as an argument, and the new context inherits its runtime.

The change could be as simple as that:
```py
def jump_out_of_context(label):
    """
    :doc: label

    Causes control to leave the current context, and then to be
    transferred in the parent context to the given label.
    """

    # Transfer the runtime to the parent context.
    try:
        renpy.game.contexts[-2].runtime = renpy.game.contexts[-1].runtime
    except:
        print("Failed to transfer runtime to parent context.")

    raise renpy.game.JumpOutException(label)
```

Additionally, `get_game_runtime()` method could be adjusted to always return runtime of the current context:
```py
def get_game_runtime():
    """
    :doc: other

    Returns the game runtime counter.

    The game runtime counter counts the number of seconds that have
    elapsed while waiting for user input in the top-level context.
    (It does not count time spent in the main or game menus.)
    """

    return renpy.game.contexts[-1].runtime
```

I think having support for this is good, particularly for games utilizing contexts a lot (for minigames for instance). 

This seems like a simple change to me, but I might be unaware of something important.
Let me know if I'm missing anything. If this is all good, I'll open a PR.

**Comment by renpytom** [comment]
This is intentional - new contexts are meant for things like the game and main menus, where the clock should not run. 

In general, games shouldn't be using non-top-level contexts outside of the menuing system (and special features like replay).

**Comment by altskop** [comment]
I figured it was something like that. Thanks for clarifying!
