### ISSUE TITLE
Rollback to "soft" checkpoint

### ISSUE THREAD

**Issue by valery-iwanofu** [renpy/renpy#4342]
I'm trying to create migration system compatible with loop style game.
In later versions of the game content of the labels can be changed, which can be cause problems with saves.
My idea is use rollback system in order to jump to the "safe identifier" which created at the start of the loop.
In code it look like this:
```renpy
label after_load:
    if is_version_mismatched() and safe_identifier:
        $ renpy.rollback(checkpoints=renpy.get_identifier_checkpoints(safe_identifier))
    return

label loop:
    $ renpy.checkpoint(hard=False) # soft checkpoint
    $ safe_identifier = renpy.game.log.current.identifier

    call scene1

    jump loop
```
But sadly, `renpy.get_identifier_checkpoints(safe_identifier)` returns None for "soft" checkpoints. 
Is it possible to somehow solve this problem?

**Comment by renpytom** [comment]
No, sorry. renpy.game.log.current.identifier is not documented.

I'd suggest doing this with labels, rather than rollback identifiers.

**Comment by valery-iwanofu** [comment]
Okay. Thanks for response. I thought I finally found a suitable solution, but it looks like I'll have to think about this problem again.
