### ISSUE TITLE
Ren'Py nightly not opening on Mac

### ISSUE THREAD

**Issue by GamesByKinmoku** [renpy/renpy#4346]
I'm having issues with 7.5.3 (button hovers and displayables using timer) so I thought I would try the nightlies... However, I'm using Mac (OS 11.7) and Ren'Py won't launch until I try a nightly all the way back from Monday, November 7 2022. When I try Monday, November 14, 2022 and beyond, it won't launch at all.

Not sure if this has been noted already but I thought I'd mention it.

**Comment by renpytom** [comment]
What kind of mac are you running on?

I just checked the the February 12 nightly (the February 13 version has a bad dmg for some reason), and it ran on my x86 mac running 11.7, and my M1 Mac Mini running 13.0.1.

**Comment by GamesByKinmoku** [comment]
MacOS Big Sur 11.7

MacBook Pro (Retina, 15-inch, Mid 2014), 2,5 GHz Quad-Core Intel Core i7, 16 GB 1600 MHz DDR3, NVIDIA GeForce GT 750M 2 GB

I tried that dmg too but it doesn't work launch for me.

**Comment by renpytom** [comment]
Can you give me a description of what you're doing to launch it? I'm trying to figure out what the difference between our procedures is.

**Comment by GamesByKinmoku** [comment]
Double click DMG -->  drag the folder to 'Applications' --> right click and 'open' the .app file --> click 'open' on prompt --> icon will bounce for a second before disappearing

**Comment by renpytom** [comment]
Hm... that's basically  what I did, and it worked. 

Could you check to see if there are any logs produced (log.txt, traceback.txt, errors.txt) and more.

**Comment by GamesByKinmoku** [comment]
Okay... This is very strange but I went to get the log.txt and thought I'd try launching it one more time...and it worked! I hadn't restarted my computer or done anything different, so I really don't know what happened. Anyway, it seems to work now. I will be back if it happens again.

**Comment by GamesByKinmoku** [comment]
Deleted previous comment, I was mistaken. There are no logs, tracebacks or errors being produced. It still fails to launch.

**Comment by renpytom** [comment]
Is there any chance I could get ssh access to the computer in question? I really have no idea how to diagnose this remotely when it works on two computers that bracket the version in question.

**Comment by Kassy2048** [comment]
@renpytom Maybe you tried Ren'Py 8 nightly and OP is trying Ren'Py 7 nightly instead?

**Comment by GamesByKinmoku** [comment]
@Kassy2048 I _am_ using Ren'Py 7 as I am near the end of my project.

**Comment by renpytom** [comment]
I've been able to repeat the problem on Ren'Py 7, so I'll work to fix this tonight. 

@Kassy2048 Thank you for getting me past my fixation.

@GamesByKinmoku I won't need the ssh access, but thank you for setting it up.

**Comment by renpytom** [comment]
Can you take a look at the Wednesday, February 15, 2023 nightly? I believe this fixes the issue.

**Comment by GamesByKinmoku** [comment]
@renpytom This now works for me! :) The other issues I was having have also been fixed in this latest version. Thanks so much for the help!

**Comment by renpytom** [comment]
Thanks for putting up with me.
