### ISSUE TITLE
Is there a function to switch to screen renpy after the current screen points to another window created with PyGame?

### ISSUE THREAD

**Issue by DonRP** [renpy/renpy#4347]
Hi I am developing a tool to be able to insert PyGame games into Renpy.

I am only missing one piece to get it working:

To allow this transition I set the screen from the one initially set by renpy to the one of my game in pygame. like this:
```py
    bestdepth = pygame.display.mode_ok(SCREENRECT.size, 0, 32)
    screen = pygame.display.set_mode(SCREENRECT.size, 0, bestdepth)  
```
But then I have a problem because after my game is finished I would like to go back to renpy screen, but I don't know how to do it.
I looked a little bit in the renpy repo and I noticed that at the beginning of the game something like this is done: https://github.com/renpy/renpy/blob/9ac23face8449a9cd6558828def49f9c41f60649/renpy/gl2/gl2draw.pyx#L367

I was wondering if there is a similar function within renpy to be able to transit on the renpy screen. or something like that.

**Comment by renpytom** [comment]
renpy.display_reset() does this, but it's undocumented, unsupported, and may not work in your case. 

Note that changing game modes isn't supported and is probably a bad idea - at the very least, you'll run into the problem that the game won't scale like Ren'Py games are expected to do. 

Your best bet would be to run the pygame(_sdl2) game in a second thread, and then use a creator-defined displayable to display a Surface, and to proxy the data into the main thread - then to process events and hand them back to the second thread, somehow. 

It's a tough problem. Good luck.
