### ISSUE TITLE
being able to get the size of the gui

### ISSUE THREAD

**Issue by DonRP** [renpy/renpy#4350]
you can transform the gui.rpy file from so:

```renpy
## Calling gui.init resets the styles to sensible default values, and sets the
## width and height of the game.
init python:
    gui.init(1920, 1080)
```
like this:
```renpy
## Calling gui.init resets the styles to sensible default values, and sets the
## width and height of the game.
define gui.width = 1920
define gui.height = 1080
init python:
    gui.init(gui.width, gui.height)
```

I would do it but I don't know what to modify.

the reason is that very useful to be able to know the size of the screen for various reasons

**Comment by Gouvernathor** [comment]
These are available as [config.screen_width/height](https://www.renpy.org/doc/html/config.html#var-config.screen_height). gui.init sets the values to those variables, apparently.
