### ISSUE TITLE
Screens do not allow recursion

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#4351]
I was implementing a tree system and wanted to use recursion to display it, but was blocked from doing so via the following exception:

```
I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
Exception: The following screens use each other in a loop: display_node_and_children. This is not allowed.
```

A simplified example with the same issue looks like the following:

```renpy
init python:
    class Node():
        def __init__(self, children=None):
            self.children = children or [ ]

default start_node = Node([
    Node([Node(), Node()]), Node(), Node([Node()])
])

screen display_node(start):
    fixed:
        xalign 0.5
        use display_node_and_children(start)

screen display_node_and_children(node):

    add "#f0f" xysize (50, 50) xalign 0.5 # The node
    if node.children:
        hbox:
            spacing 10 xalign 0.5
            for child in node.children:
                use display_node_and_children(child)
```

The idea is, of course, to re-use the same screen to display the node and any of its children until there are no children left to display. I understand this sort of use case does not seem to have been built into Ren'Py.

My workaround is to simply construct the displayable using recursion and add that to the screen instead, which works perfectly fine, leading me to believe it may be possible to allow screen language itself to do this as well:

```renpy
init python:
    class Node():
        def __init__(self, children=None):
            self.children = children or [ ]

        def display_node_and_children(self):
            result = [ ]
            result.append(Transform("#f0f", xysize=(50, 50), xalign=0.5)) # The node
            if self.children:
                children = [ ]
                for child in self.children:
                    children.append(child.display_node_and_children())
                result.append(HBox(*children, spacing=10, xalign=0.5))
            return VBox(*result, spacing=20, xalign=0.5)

default start_node = Node([
    Node([Node(), Node()]), Node(), Node([Node()])
])

screen display_node(start):
    fixed:
        xalign 0.5
        add start.display_node_and_children()
```

This has the following result:
![image](https://user-images.githubusercontent.com/37048629/218548629-dde3ac5b-896a-497c-b681-c8efce977cf6.png)

I'd prefer to be able to write this code using screen language rather than Python, if it's possible to add such functionality to Ren'Py.

**Comment by renpytom** [comment]
I'll note that you're breaking a lot of Screen Language's optimizations when you do things this way, so "working fine" is relative here. 

Optimizations are the reason for disallowing recursion in screens. It's hard enough to properly analyze one screen - having to do two at the same time (or even one and itself) would increase the challenge immensely. Given this and the relative lack of demand, I don't see this changing any time soon. 

Do you have a non-synthetic example of why you'd want this? I've been able to make similar things (the shift+I image picker) without using recursive screens. The key is to use a Python function to linearize the data into a list, and then iterate over the list to do the display, using null to indent things as required.

**Comment by shawna-p** [comment]
Yes, understandably the engine is not set up in a way for this to be optimal. If it's a lot of work to include this in the engine, I can concede it isn't the best use of time to add it. 
The actual use case is for a flow chart. In particular, both a dev tool which allows the user to click on nodes to add connections between nodes and new children, and a player-end display of the result. The most important part is the end result displaying properly, but the dev tool to build it means the user won't have to be proficient in Python to create functional flow charts to track the player's progress in their game. So, turning this class structure into a list to iterate over might solve the issue of how to display the end result, but would still require constant recalculation for a dev tool to create the flow chart, particularly when considering connectors between each node.

**Comment by renpytom** [comment]
Hm... I don't have a great example - the style inspector is what comes to mind. But the style inspector is broken up over several Ren'Py files. 

I'd probably take the underlying data, and break it up in to rows, each of which is stored in a list and drawn from that. 

(Really, I'd probably just use the drag and drop systems to let the creator move nodes around, and then store the node positions.) 

I'm going to close this, as I don't think there are going to be recursive screens any time soon - it would break way too much.
