### ISSUE TITLE
NVL rollback rollforward and translations

### ISSUE THREAD

**Issue by ZusYar** [renpy/renpy#4352]
Bringing back the issue with NVL style paging.
Here's the quick basic setup
```
define narrator = nvl_narrator
define config.nvl_paged_rollback = True
define config.rollback_enabled = True

label start:

    "Page 1. Line 1"
    "Page 1. Line 2"
    "Page 1. Line 3"
    "Page 1. Line 4"

    nvl clear

    "Page 2. Line 1"
    "Page 2. Line 2"
    "Page 2. Line 3"
    "Page 2. Line 4"

    nvl clear


    "Page 3. Line 1"
    "Page 3. Line 2"
    "Page 3. Line 3"
    "Page 3. Line 4"

    nvl clear

    "The end"

    return

```
then there's translation generated 'test'
with script being like
```
# game/script.rpy:5
translate test start_73de7446:

    # "Page 1. Line 1"
    "Page 1. Line 1 translated"

# game/script.rpy:6
translate test start_eb28d2d8:

    # "Page 1. Line 2"
    "Page 1. Line 2 translated"
```
so on
and a button added to preferences to swap languages between None and test
This results in something i don't even know how to describe

Section A: rolling back/forward
made it as one picture illustrating various attempts to roll back / forward from different spots
![изображение](https://user-images.githubusercontent.com/66777147/218800875-94490cc0-09b3-421a-b9f7-10f0e14a908a.png)

Section B: applying translation
when i swap translations, rolling back stops (which is maybe intended)
but when 1 try to roll back it shows the untranslated copy of the last seen line
![изображение](https://user-images.githubusercontent.com/66777147/218802281-f5ce3fe3-d971-4152-bf0c-c9528a4cee75.png)

Tested in both 7.5.3, 8.0.3, same result

**Comment by renpytom** [comment]
I believe this is fixed, well enough. The interaction between nvl_mode and rollback and language changes isn't going to be perfect (at least not without giving up some of the advantages of Ren'Py's translation system), but the obvious failures seem fixed, and the game behaves reasonably.
