### ISSUE TITLE
Projects not launching in versions 8.0.3 and 7.5.3 (windows 10)

### ISSUE THREAD

**Issue by teodorburlacu** [renpy/renpy#4356]
The renpy launcher is displayed but when i try to launch any project (including the default Tutorial) nothing happens and no error is thrown. 

I tried various things (moving the sdk folder on a different partition or Program Files, clearing the App Data, changing the version via Update) but nothing works.

This is the log:

```
Wed Feb 15 16:37:36 2023
Windows-10-10.0.19045
Ren'Py 8.0.3.22090809
 

Bootstrap to the start of init.init took 0.05s
Early init took 0.00s
Loader init took 0.04s
Loading error handling took 0.21s
Loading script took 4.13s
Loading save slot metadata. took 0.01s
Loading persistent took 0.00s
Set script version to: None (alternate path)
 - Init at launcher/game/android.rpyc:24 took 0.68689 s.
 - Init at launcher/game/installer.rpyc:6 took 0.89489 s.
 - Init at launcher/game/web.rpyc:26 took 0.30943 s.
Running init code took 2.59s
Loading analysis data took 0.02s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.03s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.31s
Cleaning stores took 0.00s
Init translation took 0.04s
Build styles took 0.00s
Load screen analysis took 0.04s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.07s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.21s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1600, 900)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce GTX 1060/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 528.49'
Display Info: None
Screen sizes: virtual=(800, 600) physical=(800, 600) drawable=(800, 600)
Maximum texture size: 4096x4096
```

**Comment by renpytom** [comment]
Are there any special character (non-ascii characters) in the path to your game or the path to Ren'Py?

**Comment by teodorburlacu** [comment]
> non-ascii characters

no, it's clean. could it have something to do with python? i enabled console output and i noticed the console closes immediately after trying to run the project.

**Comment by teodorburlacu** [comment]
i also have version 7.3.5 (which i normally used) and it works fine except for Android compiling

**Comment by danac78** [comment]
Have you tried running it under a different user name in Windows 10 (which creates a blank profile) to determine if it is Profile related? The fact that Python console closes immediately could be a sign that it is system-wide or profile-wide. Have you tried turning off Internet Security (even Defender) to see if it is getting spooked into a False positive? The only two other things I can think of at the moment that might cause that kind of reaction. If it is Internet Security related, you might have to add it to allow.

**Comment by teodorburlacu** [comment]
I found the issue and I'll lay it here case anyone else has it.

I was having both python 3.9 x32 and x64 installed on the system. uninstalling 32 bits version of python fixed the issue

**Comment by renpytom** [comment]
That's very odd. Ren'Py shouldn't use the system Python at all - though it's possible an environment variable was in play. 

I'm going to close this.
