### ISSUE TITLE
Ren'Py pause causing label to not continue

### ISSUE THREAD

**Issue by GamesByKinmoku** [renpy/renpy#4361]
Hello, I'm using Renpy 7.5.3 (also nightly Renpy 7 from 15th February). I have a label that will start but then not continue. Here is the code under the label:

`label .second:
        show glitch-smallvivi onlayer screens
        $ queue_sound([silence05, glitchsmall])

        $ renpy.pause(1.5, hard=True)

        hide glitch-smallvivi onlayer screens

        call screen clicktocontinue

        t grimace "Oh no..."
        $ animate_textbox = ""

        show glitch-vivi onlayer screens
        $ queue_sound([silence05, glitch])

        $ renpy.pause(3.0, hard=True)

        hide glitch-vivi onlayer screens
        show blackbg onlayer screens

        call screen clicktocontinue

        t shout "Argh!"
        #etc`

It reaches the first renpy pause then stops. I tried switching it to just "pause 1.5" but it still stops. When I completely remove it though, it works and continues playing the label.

If I save the game, load the save and return, it will work until the **next** pause. However, pause is working for me throughout the rest of the game...

The label I'm using here appears above a screen (friend_page_vivi). Code is as follows:

`label shark_vivi_friend_master:
    label .init_label:
        $ notifications.unread = False
        show screen friend_page_vivi

    label .controller:
        if game_session == 3 and story_notification == "vivi_now_friends":
            jump shark_vivi_friend_master.intro

        elif game_session == 14:
            jump shark_vivi_friend_master.second

    label .show_screen:
        while True:
            pause
            
    label .second:
        show glitch-smallvivi onlayer screens
        $ queue_sound([silence05, glitchsmall])

        $ renpy.pause(1.5, hard=True)

        hide glitch-smallvivi

        call screen clicktocontinue

        t grimace "Oh no..."
# etc`

And code for the screen:

`screen friend_page_vivi():
    zorder 0
    modal True
    tag sharkmenu
    use shark_interface

    text _("Vivi's Page") color get_secondary() style "header_text"

    add theme_image("profile-frame") xpos 330 ypos 374
    imagebutton idle theme_image("back-button off") hover theme_image("back-button on") action Show("friends_list") activate_sound "sounds/cancel.ogg" xpos 40 ypos 960

    imagebutton:
        xpos 1610 ypos 373
        idle theme_image("drawing friends off")
        hover theme_image("drawing friends on")
        action Show("vivi_collection")
        activate_sound "sounds/click.ogg"

    vbox:
        xpos 546
        ypos 390
        xmaximum 400
        ymaximum 200
        spacing -2

        text _("[violet.nick]") color get_secondary()
        add Frame(theme_image("underline"), left=1, top=1, right=1, bottom=1, xysize=(106, 4)):
            xalign 0.0
            ypos -6

        text _("Small Fry\nJoined: 04.09.03\nLocation: - \nLast Seen: [viviseen]") color get_secondary() style "small_text"

    fixed:
        xpos 920
        ypos 402
        xmaximum 600
        ymaximum 140

        imagebutton:
            idle theme_image("box-quote")
            action NullAction()

        text _("[violet.quote]") color get_primary() xpos 28 ypos 16

    vbox:
        xpos 330
        ypos 144
        spacing 20

        add "advert-wide"

        hbox:
            spacing 20

            vbox:
                spacing 20

                hbox:
                    xpos 20
                    ypos 20
                    spacing 20
                    xmaximum 1220
                    ymaximum 184
                    
                    add theme_image("avatars chat")

                text _("[violet.nick]'s Recently Played Games") color get_secondary() ypos 8 xpos 20

                hbox:
                    ypos -6
                    xpos 20
                    spacing 20
                    xmaximum 1220

                    imagebutton:
                        idle theme_image("game ff")
                        hovered Show("tooltip_screen", txt="Feudal Fantasy")
                        unhovered Hide("tooltip_screen")
                        action [Hide("tooltip_screen"), Show("game_description"), SetVariable("gamedesc", "ff")]

                    imagebutton:
                        idle theme_image("game shindig")
                        hovered Show("tooltip_screen", txt="Shindig")
                        unhovered Hide("tooltip_screen")
                        action [Hide("tooltip_screen"), Show("game_description"), SetVariable("gamedesc", "shindig")]
`

I'm sticking with Renpy 7 for my project as I am near the end... but when I updated recently to 7.5.3, I found this error. Unsure if it's been reported.

**Comment by renpytom** [comment]
Can you check this out in Ren'Py 7.6? IIRC, there are some fixes to this.

If that doesn't improve things, then I'll need a demo of the problem, that jumps right to the appropriate screen.

**Comment by GamesByKinmoku** [comment]
@renpytom I did, unfortunately it still behaves the same way. Let me get a demo for you ready...

**Comment by MiiNiPaa** [comment]
Wait, is your screen modal? In 7.5 modal screens prevent pauses from ending while they are shown. I would consider pause ending or reload to be a true bug here...

**Comment by renpytom** [comment]
The screen is modal. 

In modern versions of Ren'Py, modal screens block renpy.pause. 

You can try to revert this change with:

define config.modal_blocks_pause = False

if you prefer the old behavior. (However, I'm not sure the reversion will work - I just fixed an issue with the compatibility logic. renpy.pause(2.0, modal=False) will always work.

**Comment by GamesByKinmoku** [comment]
Ah sorry, my bad! I've changed it to model=False and it works now :) Thank you for taking the time to help me.

**Comment by renpytom** [comment]
@MiiNiPaa Gets the credit for this one. 

Closing the issue out.
