### ISSUE TITLE
config.keymap causing crash on launch (Renpy 7 nightly)

### ISSUE THREAD

**Issue by GamesByKinmoku** [renpy/renpy#4362]
I was testing with Renpy 7 nightly on February 15th and received a crash for the following lines:

`    #$ config.keymap['rollback'].remove('K_PAGEUP')
    #$ config.keymap['rollback'].remove('repeat_K_PAGEUP')
    #$ config.keymap['rollforward'].remove('K_PAGEDOWN')
    #$ config.keymap['rollforward'].remove('repeat_K_PAGEDOWN')
    #$ config.keymap['hide_windows'].remove('h')
    #$ config.keymap['hide_windows'].remove('noshift_K_h')
    #$ config.keymap['hide_windows'].remove('mouseup_2')
    #$ config.keymap['self_voicing'].remove('v')`

I've muted them for now and it loads fine without the crash, but I thought it was worth mentioning. Unsure if keymaps have changed much in the nightlies.

**Comment by renpytom** [comment]
The keymap has changed, so some of this is no longer valid, giving new keymap handling that factors in repeats. 

I'm going to leave this open to compat this, so at least their won't be crash errors.
