### ISSUE TITLE
Change order of execution for Character()

### ISSUE THREAD

**Issue by RaXorX** [renpy/renpy#4364]
Recently I was testing something out, more so in my laziness. Instead of using different characters, I tried to make a dynamic character, which would have different names for different portions of the game. Just 2 different portions.

```
init python:
    def who_say(event, interact=True, **kwargs):
        global comic
        
        if kwargs.get("comic"):
            comic = True
        else:
            comic = False
            
default comic = False
define em = Character('"Emily" if comic == False else "Kitty"', dynamic=True, callback=who_say)
default cb = { "cb_comic": True }

em "Hello hello. - 01" (**cb)
em "Hello hello. - 02" (**cb)
em "Hello hello. - 03" (**cb)
em "Hello hello. - 04"
em "Hello hello. - 05"
em "Hello hello. - 06" (**cb)
```

This was my code apparently. So what I had wanted to do was change the character's name to Kitty in the comic portions and keep it as Emily outside the comic portions. Apparently the Character() function's execution goes somewhat like

Character __call__ -> evaluate who -> pass that off to display_say -> then do the callbacks

So in the above example. The output is like:

Emily: Hello hello - 01    # Should display Kitty as the name, not Emily
Kitty: Hello hello - 02
Kitty: Hello hello - 03
Kitty: Hello hello - 04    # Emily, not Kitty
Emily: Hello hello - 05
Emily: Hello hello - 06    # Kitty, not Emily

I was wondering if it wouldn't be more optimal if it could do the callbacks earlier on, that way it would have much more proper control on the dialogue window's appearance.

**Comment by renpytom** [comment]
There are a lot of other ways to do this - I don't think that we need to change how the character callback works.
