### ISSUE TITLE
Crash parsing invalid UTF-8 in .rpy files.

### ISSUE THREAD

**Issue by SpikyCaterpillar** [renpy/renpy#4366]
On Debian with a UTF-8 locale (in this case, LANG=fi_FI.UTF-8), if I try to load a file containing invalid UTF-8 characters, I get "LookupError: unknown error handler name 'python_strict'". I haven't tested this in other locale configurations or OSes, but I assume it should just be 'strict'.

(This was exposed by feeding an ISO-8859-1 text file my writer supplied into a .rpy without noticing that there was a soirée invitation that should have been converted to UTF-8)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/renpy7/renpy-8.0.3-sdk/renpy/bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "/home/renpy7/renpy-8.0.3-sdk/renpy/main.py", line 490, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  F f = open('tmp/encoding','rb')ile "/home/renpy7/renpy-8.0.3-sdk/renpy/script.py", line 297, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/home/renpy7/renpy-8.0.3-sdk/renpy/script.py", line 781, in load_appropriate_file
    data, stmts = self.load_file(dir, fn + source)
  File "/home/renpy7/renpy-8.0.3-sdk/renpy/script.py", line 608, in load_file
    stmts = renpy.parser.parse(fullfn)
  File "/home/renpy7/renpy-8.0.3-sdk/renpy/parser.py", line 3047, in parse
    lines = list_logical_lines(fn, filedata, linenumber)
  File "/home/renpy7/renpy-8.0.3-sdk/renpy/parser.py", line 249, in list_logical_lines
    data = f.read().decode("utf-8", "python_strict")
LookupError: unknown error handler name 'python_strict'

Linux-5.15.0-2-amd64-x86_64-with-glibc2.31 x86_64
Ren'Py 8.0.3.22090809
 
Thu Feb  9 23:36:59 2023

-------

**Comment by Gouvernathor** [comment]
You're using 8.0.3. This seems to be fixed in the nightly releases, since the line the traceback points to isn't part of the source code anymore.

**Comment by renpytom** [comment]
I concur - this was fixed a while back.
