### ISSUE TITLE
doc: side_yfill is not documented

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#4374]
The screens.rpy file that is generated by default when a new project is created mentions the side_yfill property of the vpgrid displayable, this property is not documented, I imagine that side_xfill also exists, and that it is not the only displayable that takes these properties.

**Comment by Gouvernathor** [comment]
It is documented.
From the Screens page, in the VPgrid section : "In addition, a vpgrid takes all properties a [viewport](https://nightly.renpy.org/doc/screens.html#sl-viewport) can, and the following (...)"
In the Viewport section : "When scrollbars is not None, the viewport takes prefixed properties: (...) Properties beginning with side_ are passed to the side."
In the Side section : "A side takes the following property groups: (...) Position style properties"
From the Style Properties page, the yfill property is listed among the position properties.

**Comment by Moshibit** [comment]
my mistake, I thought it was not there since I searched for it with ctrl + F.
