### ISSUE TITLE
The example of configuration variables  seems outdated.

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#4375]
The example at the top of the configuration variables documentation seems outdated.
config.screen_width and config.screen_height are now set using gui.init(), I propose to change the example and also mention the use of define.

```
init python:
     # disable rollback
     config.rollback_enabled = False
```

is equivalent to:

```
# disable rollback
deafult config.rollback_enabled = False
```

**Comment by Gouvernathor** [comment]
I think just adding a one-line define example (not default) is fine for single-value configs. Possibly another showing a dict config and another for list-configs.
