### ISSUE TITLE
screens tool

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#4377]
Sometimes if something goes wrong the game closes and you have to run the game again to go back to test, I have created a game script to make this easier:

```
label main_menu:
    return

label start:

    python:
        _autosave = False
        _confirm_quit = False
        quick_menu = False

    scene reference_grid

    show screen test # call screen test

    $ renpy.pause(delay=None, hard=True, predict=False, modal=True)

    $ renpy.quit(relaunch=True, status=0, save=False)
    return
```

I would like to remove some more interactions, so that it can only interact with the screens. and remove features that are not important for displaying the screens. any suggestions to improve this and the experience of creating screens? is there any intention to create a tool to facilitate this in addition to the already useful style inspector? It does not need to be a graphical tool for editing screens, like those that exist for other programming languages.

**Comment by renpytom** [comment]
I don't know what your question is here.

**Comment by Moshibit** [comment]
Well, the request is to develop a tool to be included in the launcher that would make it easier to view screens during the creation process, without having to load a whole project/game. I'm not requesting something like Glade for Python, I want to save time if I close the application or an exception occurs. It doesn't matter if there are no plans to do something like that. At the moment the script I wrote allows me to load the screens without going through the main menu, it is already a significant time saver.

**Comment by renpytom** [comment]
Ah, I think I get what you want. I'm not sure it's something we can provide, though - most screens require at least some data to be given to them, and wouldn't work without it. Couldn't you just hit shift+R to enable autoreload, and then edit the screen?

**Comment by m-from-space** [comment]
I suggest creating a file named <testing.rpy> and put everything you test inside there. Then create a main menu link to a label there instead of putting your stuff inside label "start". Done. You then don't have to worry about the original game. And after developing just remove the link from the main menu.

**Comment by renpytom** [comment]
I don't think this is specific enough to leave open as an enhancement request.
