### ISSUE TITLE
music callback request

### ISSUE THREAD

**Issue by Moshibit** [renpy/renpy#4378]
I have a screen that indicates the name of the current track, every time the tack is changed it has to be invoked again, an alternative is not to hide it, the tracks are always shown on screen and change but I consider that it is not the correct way to solve it. I think it is necessary to create a callback that allows to show the screen every time the music starts or changes. maybe this should not happen during the main menu and game menus.

this is the screen i have, maybe it could be an example to be part of Ren'Py's features, if someone finds it useful, you can take it.

```
init python:
    def strip_file_name(file):
        file = file.rsplit("/", 1)[-1]
        file = file.rsplit(".", 1)[0]
        file = file.replace('_', ' ')
        file = file.replace('-', ' ')
        file = file.title()
        return file


    def show_music_notify:
        renpy.show_screen('music_notify')


define gui.music_notify_ypos = 121


screen music_notify():
    zorder 100

    style_prefix "music_notify"

    python:
        music_name = renpy.music.get_playing(channel='music')
        if music_name:
            music_name = strip_file_name(music_name)

    if music_name:
        frame at notify_appear:
            text "♫ [music_name]" 

    timer 3.25 action Hide('music_notify') 
    # TODO preferencias de tiempo: nunca, 3.25, 5, 7.50


style music_notify_frame is notify_frame
style music_notify_text is gui_text

style music_notify_frame:
    ypos gui.music_notify_ypos

style music_notify_text:
    properties gui.text_properties("notify")

```

**Comment by renpytom** [comment]
This should probably be a per-frame callback, rather than something music specific.

**Comment by mal** [comment]
Would per-frame offer any noticeable advantage over using the existing `config.periodic_callback` for cases like this?

**Comment by renpytom** [comment]
Actually, config.periodic_callback is probably the right answer for this.

**Comment by Moshibit** [comment]
Doesn't it affect performance if a function is invoked every 0.05s? it seems excessive just to check if the music changed track. even though there are probably things going on behind the scenes that affect performance more than a string comparison. thanks.

**Comment by renpytom** [comment]
Not really. Ren'Py redraws the screen every 0.016s, and calling, say, renpy.music.get_playing is a lot less intensive than that. 

The important thing is to make sure your game only calls renpy.restart_interaction() if an actual change occurs, rather than just doing it on every frame.
