### ISSUE TITLE
Building the web distribution through CLI yields a non-built archive

### ISSUE THREAD

**Issue by Tapiiri** [renpy/renpy#4380]
On both 8.0.3 and 7.5.3, it seems to be possible to build distributions of the game with `renpy.sh launcher [Game Folder]`.

It builds all packages succesfully except for the `web` package, which if instructed by appending `--package web` it accepts as a package name but only zips the build folder without building anything. If the package isn't explicitly defined with the --package parameter, it is not built alongside all the other distributions (that are built if no parameter is given).

Usage of the command can be seen for ex. in [ this Docker code ](https://github.com/ProjectAliceDev/renpy-build-action/blob/master/build.sh) for a Github Action meant for building the distributions as part of CI/CD pipeline.

I'm attempting to build a pipeline that would automatically build and publish the web distribution of the game to Itch.io, but so far it seems that the only way to do that currently is manually through RenPy.

**Comment by renpytom** [comment]
There isn't a supported CLI, yet.

**Comment by quillcraftsman** [comment]
@renpytom , I have the same issue today using 8.1.3 SDK. 

Could you tell me please, is web package still not supported? If not, is there any plan to add this feature in the future (may be some feature request or pull request)?
