### ISSUE TITLE
renpy.showing thinks tagged screens are still showing even after they're hidden.

### ISSUE THREAD

**Issue by SpikyCaterpillar** [renpy/renpy#4384]
Example code to demonstrate:

```
screen tagged():
    tag maincontrol
    null

screen test2():
    null

screen showing_status():
    vbox align (.5,.5):
        for s in ('tagged','maincontrol','showing_status','test2','test3'):
            text "Showing: "+s+" "+str(renpy.showing(s,layer='screens'))

label start:
    show screen showing_status
    "Testing."
    show screen tagged
    "Tagged is showing."
    hide screen tagged
    "Tagged is hidden... or is it?"
    show screen test2
    "Test2 showing."
    hide screen test2
    "Test2 hidden"
    # This ends the game.

    return
```
This shows up in 8.0.3 and 8-nightly-2023-02-22-8.1.0.23022201n.

AFAICT this is caused by it trying to remove the tag from image prediction instead of the original screen.

I've got a poorly tested fix against the nightly, but since I don't actually understand the image prediction code it's quite likely wrong in interesting and subtle ways.

[renpy8-hiding.txt](https://github.com/renpy/renpy/files/10804779/renpy8-hiding.txt)

**Comment by renpytom** [comment]
I've made some improvements here, but the best way to tell if a screen is showing is renpy.get_screen: 

http://nightly.renpy.org/doc/screen_python.html#renpy.get_screen
