### ISSUE TITLE
let renpy support multiple voice

### ISSUE THREAD

**Issue by fastfading** [renpy/renpy#4390]
they are so many good quality tts out side  , such as microsoft edge tts
and those tts support multiple voice selection

so why not give different role a different voice

please give a solution to configure it .

**Comment by fastfading** [comment]
and there is also  different  Speaking style 
we can add that too
reference 
https://azure.microsoft.com/en-us/products/cognitive-services/text-to-speech/#features

**Comment by renpytom** [comment]
The config.tts_voice variable lets you set the voice in use.
