### ISSUE TITLE
Wait tag closes game menu if interrupted

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#4392]
My game uses a lot of wait tags, and I've noticed they frequently mess with the use of the game menu.

From my experiments, if you are using slow text and right click right before a {w=} tag is about to kick in, the game menu stays open for the time specified in the tag, and then closes again.

Managed to get this pretty reliably with the following line and a speed of 70 characters per second:
`"We're going{w=1} to quickly run{w=1} an example."`

1. Open the game menu right as the line starts.
2. Quickly right-click twice, to close and immediately open it again.
3. The game menu closes by itself after one second.
4. The line is stuck at "We're going to quickly run", requiring you to click to advance.

The end of a line does not cause any issues from what I could tell.

**Comment by renpytom** [comment]
How are you showing the game menu? Have you set config.game_menu_action to something non-standard (for example, Show rather than ShowMenu?)

**Comment by kigyo** [comment]
Nope, nothing special. This happens even on a completely fresh Ren'py game with nothing added except the `"We're going{w=1} to quickly run{w=1} an example."` line.

**Comment by renpytom** [comment]
Note to myself: This triggered more reliably with 

```renpy
define config.enter_transition = Dissolve(2.0)
```
