### ISSUE TITLE
Doc update for renpy.pause

### ISSUE THREAD

**Issue by graterleg1990** [renpy/renpy#4396]
Hi guys,

Would it be possible to update documentation for renpy.pause with hard flag. Below is the screenshot one of the player posted before he wrote a harsh message directed towards an old game of mine.
Millions of people are using renpy and it would be nice to not have rebellious words and statements in the docs. Maybe subtle words would do the trick?
Please consider, thanks :)

![image](https://user-images.githubusercontent.com/122201140/221358937-f83c6a05-b376-47b5-9d1d-f4998dc66acf.png)

**Comment by mal** [comment]
The potential for players to react poorly to hard pauses (and view them as "rude") is what the docs are communicating. Effectively warning developers in advance that some players won't like it and why; however, the documentation of this fact is not the _reason_ players don't like it.

**Comment by renpytom** [comment]
I'm fine with the current wording.
