### ISSUE TITLE
In-app review feature for Google Play games?

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#4397]
One element that greatly helps when releasing an app on Google Play is a prompt that asks the player to rate it.

I know Google Play has an official API with such a feature, but it's only available for C and Java-based games: [https://developer.android.com/guide/playcore/in-app-review](https://developer.android.com/guide/playcore/in-app-review)

There is a popular but old library on github that can do this too: [https://developer.android.com/guide/playcore/in-app-review](https://developer.android.com/guide/playcore/in-app-review)

Would implementing such a feature be possible alongside Ren'py's in-app-purchase functionality?

**Comment by renpytom** [comment]
Just landed a series of changes that implemented this, targeted at 8.1.
