### ISSUE TITLE
Composite() function doesn't apply positional transform statements

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#4399]
I'm not sure if this is a bug or a feature or something that depends on what users want.

Consider the following ("background" and "item" are Displayables):

```
transform atl_item:
    xcenter 200
    ycenter 200

image myimage = Composite((1280, 720), (0, 0), "background", (0, 0), At("item", atl_item))
```

The "item" will be at position (0, 0), xcenter and ycenter not applied.

Now I know that (0, 0) defines the position of the following child. But I would expect that the transform statements will still be applied to the base size of (1280, 720). Not sure if this makes sense. Positioning the "item" at (20, 20) should then create an additional offset in my opinion. But that's probably up for discussion.

On the other hand: Is there already a "true" way to create a composite image with ATL transforms applied?

**Comment by shawna-p** [comment]
Historically I've occasionally used the Fixed container to solve this problem. It lays its children out like you would expect so long as you specify the size. I'd be interested to hear if there's a preferred solution to this or if Fixed is fine.

For reference, that would look like:

```renpy
image myimage = Fixed(
  "background", 
  At("item", atl_item), 
  xysize=(1280, 720)
)
```

You might also consider the Window displayable given how you described the background.

**Comment by m-from-space** [comment]
I guess that Fixed() is just the better solution here, thank you.

**Comment by renpytom** [comment]
Fixed is the way to go here, and it has several options (like fit_first, xfit, and yfit) that are designed for this use case.
