### ISSUE TITLE
"Translation nodes cannot be run directly"

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#4406]
We received a bug report from an user playing their game on Mac:
![image](https://user-images.githubusercontent.com/34620611/222073096-0accf09b-ff3a-408f-b22b-4d0bfb842593.png)
They further reported that:
- some of their saves can load, some cannot
- if they click "ignore", they still get that error at every line
- the problem does not happen when they make a new game

This report arose after I published a minor update; which I exported from a new Ren'py installation (7.5.3 in both old and new install), not sure if that's related.

**Comment by Gouvernathor** [comment]
The screenshot you show is 7.5.3, not 7.3.5, that's very different support-wise. Did you jump from 7.3.5 to 7.5.3 between your installs ? That wouldn't explain the error though.
Do you have an after_load label ? Do you use translate blocks outside of the tl/ folder, or wrote normal script inside that folder ? Do you have translations at all, in your game ?

**Comment by marchare555** [comment]
> The screenshot you show is 7.5.3, not 7.3.5, that's very different support-wise. Did you jump from 7.3.5 to 7.5.3 between your installs ? That wouldn't explain the error though. Do you have an after_load label ? Do you use translate blocks outside of the tl/ folder, or wrote normal script inside that folder ? Do you have translations at all, in your game ?

Whoops, my mistake; I was using 7.5.3 for both builds.

> Do you have an after_load label ?
Nope, I didn't know I could do that.

> Do you use translate blocks outside of the tl/ folder
Yes. For various reason I'm manually assigning every game line something like `translate None scene_01_001`. I also "translated" a lot of text styles inside screen.rpy.

> Do you have translations at all, in your game ?
The game is translated in 11 languages. This person was experiencing issues in French.

**Comment by Gouvernathor** [comment]
`translate None` blocks are not supported, except for `translate None strings`. Discussed in #4243.

**Comment by marchare555** [comment]
> `translate None` blocks are not supported, except for `translate None strings`. Discussed in #4243. You should use the say statement's id clause.

Do you mean I should do something like:
```
label scene_01:
    "I like bread." id scene_01_001
```

Instead of:
```
label scene_01:
    translate None scene_01_001:
        "I like bread."
```

**Comment by Gouvernathor** [comment]
Exactly.

**Comment by marchare555** [comment]
Thanks!

The `translate None` thing is still present inside the official Renpy documentation : https://www.renpy.org/doc/html/translation.html#tips

Perhaps some clarification in the documentation could be useful to differentiate the two methods and when to use them.

**Comment by Gouvernathor** [comment]
That example was removed following issue 4243, the doc pages will be brought up to date at the next release. I think if you download a nightly, the new version will be found in the doc/ directory inside the renpy install, though I'm not positive about that.

**Comment by mal** [comment]
For reference, here's the equivalent section in the current nightly docs: <https://nightly.renpy.org/doc/translation.html#tips>
