### ISSUE TITLE
Unknown chunk type 200 when building Android

### ISSUE THREAD

**Issue by gimpyestrada** [renpy/renpy#4413]
I've been seeing this message come up when I build for Android (currently using 7.5.3) and I am not sure if it is something that should be checked out. I'm also not sure if it is something that should be addressed by renpy or by the android build-tools folks.

I've checked and I can't seem to find the textual output of the build process anywhere, so I grabbed a screen shot so you can kind of see where it is occurring.

Any idea what this might be?

![Screenshot 2023-03-03 091415](https://user-images.githubusercontent.com/63172558/222756799-4f45fff9-e1d7-4a1f-8e95-41aa4657a3ca.png)

**Comment by renpytom** [comment]
It's spurious - a bug in the older android tools we use to build. I'll upgrade to newer tooling soon, but for now I'm just filtering the message. It's also harmless - the android packages are built correctly despite the warning.
