### ISSUE TITLE
Renpy 8.0.3 Build failing to launch on windows

### ISSUE THREAD

**Issue by emmabh** [renpy/renpy#4421]
My build is just showing the splash screen, stalling, and then finally just closing. Then, this log.txt file shows up:

```
Sun Mar  5 22:03:02 2023
Windows-10-10.0.19044
Ren'Py 8.0.3.22090809
 

Bootstrap to the start of init.init took 0.11s
Early init took 0.05s
Loader init took 0.10s
Loading error handling took 0.19s
Loading script took 2.48s
Loading save slot metadata. took 0.01s
Loading persistent took 0.00s
 - Init at renpy/common/00updater.rpy:23 took 0.25760 s.
Faled to initialize steam: FileNotFoundError("Could not find module 'C:\\Users\\emmab\\windowz\\lib\\py3-windows-x86_64\\steam_api64.dll' (or one of its dependencies). Try using the full path with constructor syntax.")
Set script version to: (8, 0, 3)
```

Any ideas what's going wrong here? I saw [this](https://github.com/renpy/renpy/issues/3812) issue and it seems similar, like Ren'Py is running out of memory! @renpytom is there any advice you can give here? Thank you in advance!

**Comment by emmabh** [comment]
@renpytom makes sense to me! Thank you for responding. I can’t post them publicly at the moment but can I possibly send them directly to you somewhere? And do you want the source and/or the compiled game files that are failing?

**Comment by emmabh** [comment]
Awesome, just sent that over to you @renpytom thank you so much again!

**Comment by renpytom** [comment]
This isn't a crash in Ren'Py, but a crash attempting to load a third-party Python package in Ren'Py.
