### ISSUE TITLE
The timer doesn't trigger an action when the screen is reshown with rollback

### ISSUE THREAD

**Issue by ticlock** [renpy/renpy#4422]
Replication:
```
screen timer_test():
    label "TEST" text_size 100 xalign 0.5 yalign 0.5
    timer 1.0 action Hide('timer_test')

label start:
    show screen  timer_test()
    "Line 1{nw}"
    "Line 2"
    "Line 3"
```
At `Line 2` wait for the screen to hide, then click to continue to `Line 3`, and rollback to `Line 2`.

As a result, screen `timer_test` is shown again due to rollback, but the `timer` doesn't trigger the action `Hide`.

This can be solved by adding `repeat True` to the timer

Not sure if it is a bug or a limitation of the `timer` use.

Related to the post: https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=66240&p=558844#p558840

**Comment by renpytom** [comment]
Have you tested with the latest nightlies? I believe this was fixed a couple days ago.

**Comment by ticlock** [comment]
Right. I missed it. Sorry for the trouble.
