### ISSUE TITLE
Deffective OpenSSL version detected on Google Play Console

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#4426]
![image](https://user-images.githubusercontent.com/34620611/223542352-029713fe-e68b-4442-aabe-e87498d28b99.png)

```
Your app uses a defective version of the OpenSSL library, which can cause your app to crash. Update to a fixed version of OpenSSL.

Defective versions:
    OpenSSL 1.1.1g in lib/armeabi-v7a/librenpython.so
```

You guys may have resolved it already for the next major update, but I figured I'd post it in case it hasn't been reported yet.

**Comment by renpytom** [comment]
8.1 (and 7.6) will be linked against OpenSSL 1.1.1s.
