### ISSUE TITLE
Android and the Quit button

### ISSUE THREAD

**Issue by gimpyestrada** [renpy/renpy#4431]
I'd like to make the argument to stop doing this in screen navigation():

if renpy.variant("pc"):

        textbutton _("Quit") action Quit(confirm=not main_menu)

Every time I port a game to android I remove this if statement.  The Quit button is just nice to have.

Lately I've noticed that if I don't actually Quit out of a game on my Android 13 phone, and then I come back to it later, it is just a black screen because something stopped working while it was in the background (likely some memory got freed or something similar).  In this case I have to force quit the game from the task list and then start it up again.  Pretty please remove this pointless exception.  If you must keep it in place for apple phones, then make the if statement be:

if renpy.variant("pc") or renpy.variant("android"):

**Comment by renpytom** [comment]
It's against the platform guidelines, and I believe 8.1 has fixes for the issues with Android 13. 

I don't plan to make this change.

**Comment by gimpyestrada** [comment]
> It's against the platform guidelines, and I believe 8.1 has fixes for the issues with Android 13.
> 
> I don't plan to make this change.

Platform guidelines or not, it's still a less than desirable experience.  I'll continue to comment that line every time, guidelines be damned!
