### ISSUE TITLE
Is it possible to get the screen/window used by renpy?

### ISSUE THREAD

**Issue by DonRP** [renpy/renpy#4433]
Is it possible to get the screen/window used by renpy?    

since the [set_mode](https://www.pygame.org/docs/ref/display.html#pygame.display.set_mode) function must be used to be created (as in pygame_sdl2), I looked it up in the code:

https://github.com/search?q=repo%3Arenpy%2Frenpy%20set_mode&type=code

I found only 3 places where it is used. in the SWDraw, GL2Draw and GLDraw  classes     

the problem is that I do not understand where they sell instantiated these classes and whether it is possible to source them from outside

**Comment by renpytom** [comment]
You can use pygame_sdl2.display.get_window() to get the window. 

Note that the window is likely to be in OpenGL mode. (Or might be in DirectX mode, on windows with the ANGLE renderer.) You're unlikely to be able to draw directly to it.

**Comment by DonRP** [comment]
mmm... unfortunately I think class Window was not what I was looking for.

I think screen is what I was looking for to be able to effect screen.blit

**Comment by renpytom** [comment]
You can't do that - even if you were to get it, Ren'Py keeps the window in a 3d mode.

Your best bet is to use a creator-defined displayable. You should be able to blit a pygame surface into a render and then display that.

**Comment by DonRP** [comment]
@renpytom I'm sorry to answer you like this later.
se intendi nel secondo mod:
```py
    bestdepth = pygame.display.mode_ok(SCREENRECT.size, winstyle, 32)
    screen = pygame.display.set_mode(SCREENRECT.size, winstyle, bestdepth)
```
yes this works, but then I don't see how I can get back to renpy's screen.

**Comment by DonRP** [comment]
(I noticed now that part of my previous comment was not translated so I have now corrected it)

Sorry but I'm not sure I understand what you mean by:

`Your best bet is to use a creator-defined displayable. You should be able to blit a pygame surface into a render and then display that.`

Did you mean in the following way?
```py
    bestdepth = pygame.display.mode_ok(SCREENRECT.size, winstyle, 32)
    screen = pygame.display.set_mode(SCREENRECT.size, winstyle, bestdepth)
```

**Comment by DonRP** [comment]
(I noticed now that part of my previous comment was not translated so I have now corrected it)

Sorry but I'm not sure I understand what you mean by:

`Your best bet is to use a creator-defined displayable. You should be able to blit a pygame surface into a render and then display that.`

Did you mean in the following way?
```py
    bestdepth = pygame.display.mode_ok(SCREENRECT.size, winstyle, 32)
    screen = pygame.display.set_mode(SCREENRECT.size, winstyle, bestdepth)
```

**Comment by DonRP** [comment]
@renpytom 

(I noticed now that part of my previous comment was not translated so I have now corrected it)

Sorry but I'm not sure I understand what you mean by:

`Your best bet is to use a creator-defined displayable. You should be able to blit a pygame surface into a render and then display that.`

Did you mean in the following way?
```py
    bestdepth = pygame.display.mode_ok(SCREENRECT.size, winstyle, 32)
    screen = pygame.display.set_mode(SCREENRECT.size, winstyle, bestdepth)
```

**Comment by DonRP** [comment]
@renpytom   

Could you answer the previous question?    

I don't think I understand the following solution you gave    

`Your best bet is to use a creator-defined displayable. You should be able to blit a pygame surface into a render and then display that.`

**Comment by renpytom** [comment]
https://www.renpy.org/doc/html/cdd.html
