### ISSUE TITLE
Cannot use controller/arrow keys to navigate buttons if a button has default_focus and hovered action

### ISSUE THREAD

**Issue by npckc** [renpy/renpy#4436]
On 7.5.3, you cannot use controller or arrow keys to navigate buttons if a button has default_focus and a hovered action.

I've attached a test project where the main menu makes it clear. "Start" button has "default_focus True" as well as a hovered action, and all the other buttons also have hovered actions. When using a mouse, the buttons work fine, but when you try to navigate, only the "Start" button can be selected. The hovered actions also seem to occur in a strange way.
[defaultfocushovered.zip](https://github.com/renpy/renpy/files/10952444/defaultfocushovered.zip)

In the test project, it will show the hovered button in the bottom right corner. If you navigate with controller or arrow keys, you'll see that by default, the hovered button is "None". Pressing down will change the hovered button text to "Start", even though by default_focus Start is already selected. Pressing down again will change the hovered button text to "Load", but Start remains focussed, and pressing Enter will select Start, not Load.

I think it may be related to the change with mouse/keyboard and default_focus in 7.5.2 https://www.renpy.org/doc/html/changelog.html#default-focus-changes

**Comment by renpytom** [comment]
Can you try this on the 8.1 (or 7.6) nightlies, from https://nightly.renpy.org ? I believe there have been fixes to this.

**Comment by npckc** [comment]
Ah, thank you! It works fine, my bad for missing the nightly. I'll close the issue.
