### ISSUE TITLE
Improve Android save data resiliency

### ISSUE THREAD

**Issue by Selenyhr** [renpy/renpy#4448]
Hello,

When making an Android version of the game, save data are by default located within the game folder itself `/Android/data/com.developer.project/files/saves`.
However, when the player uninstalls the game, this folder is deleted along the app. This makes it so that players who want to reinstall a game at a later point in time will need to restart a fresh game.

From [the Android data storage overview](https://developer.android.com/training/data-storage), there are two ways of storing data that will not be erased from storage: Media and Documents.
I gathered from #3432 that Media storage would not be chosen, because it requires to ask for extra write/read rights, which may lead to users being more easily infected from viruses contained within scam games using the engine.

Would it be possible to see if it is possible to implement Documents storage using the Storage Access Framework, so that saves could be located in a folder that would not be erased from uninstalling the game please? It does not need to be the default option, but having resilient save data on one of the most popular platforms would be highly appreciated :)

Thank you for your time.
Selenyhr

**Comment by renpytom** [comment]
Unless I'm wrong, Storage Access Framework prompts the user each time they  save. I don't plan to do that.
