### ISSUE TITLE
Interacting with the real world.via MQTT or websockets

### ISSUE THREAD

**Issue by esranonff** [renpy/renpy#4450]
Hi,

I'm working on an interactive novel and I'd like it to trigger or react to certain events in the real world.

Is this something that Ren'py can do?

In my head it's "as simple as" subscribing to an MQTT topic or connecting to a websocket and firing an event when something happens in the game or responding in the story when something happens in the real world, but I've no idea how to go about that because I'm brand new to Ren'py!

**Comment by renpytom** [comment]
In general, you can integrate Ren'Py with pure python libraries. I'd suggest looking at paho.mqtt and websocket-client. I'd also consider using requests to talk to a http or https server - requests is built into Ren'Py, so it should be easy to use. 

The precise details of how to do this are beyond the scope of the Ren'Py issue tracker.
