### ISSUE TITLE
Not able to Play Videos in Nightly Build without images/

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#4452]
So I went to try to test AV1 video to see if it would be acceptable performance, but..no videos are playing. First noticed when it didn't play sparks in my main menu. Code is:

image mm_Fire = Movie(play="ui/bg_sparks_mainmenu.webm",channel=u"movie",side_mask=True)

Plays fine in the public build of 8.0.3, but will not in Nightly mentioned. I checked the Traceback, but the only thing in that file dates back to February. 
Video will play if I write it as:

image mm_Fire = Movie(play="images/ui/bg_sparks_mainmenu.webm",channel=u"movie",side_mask=True)

Is it intended that we need to includes images when linking to video?

**Comment by danac78** [comment]
I had erased some information to be a little more concise, but the nightly build in question is 8.1.0.23031701.

**Comment by renpytom** [comment]
This is a documented change. 

http://nightly.renpy.org/doc/incompatible.html#incompatible-7-6-0

Under "File Search".
