### ISSUE TITLE
add the ability to use the `at` clause alongside `at transform`

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#4455]
it's a bit annoying to have to create a new transform whenever i want to pass multiple values to the `at` clause in a screen
```
frame:
    at (Flatten, my_atl_transform)
    ...
```
especially when `my_atl_transform` is a very simple atl transform that looks like `easein 0.5 alpha 1.0`

would be nice if we could have both `at transform` and `at`
```
frame:
    at Flatten
    at transform:
        easein 0.5 alpha 1.0
```
could work also long as the two are given in a row. though it creates another problem where if i were to have more that two values to give and that my atl transform wasn't my 1st / last one

**Comment by renpytom** [comment]
You sort of lucked  out - I was in that earlier today, so this was easy to implement.

**Comment by mal** [comment]
Does this end up behaving differently from:
```rpy
frame:
    at transform:
        Flatten # mesh True?
        easein 0.5 alpha 1.0
```

**Comment by renpytom** [comment]
Yes, since Flatten isn't applied to anything there. (mesh True would be another way of doing this.)
