### ISSUE TITLE
Cannot import 3rd party module "openai"

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#4457]
Following the [Renpy documentation](https://www.renpy.org/doc/html/python.html#first-and-third-party-python-modules-and-packages), third-party modules can be installed into the python-packages directory.

I installed it using:

`pip install --target "mygame/game/python-packages" -U openai`

which works flawlessly.

But trying to import the module inside Renpy like:

```
init python:
    import openai
```
creates the following error:

`ModuleNotFoundError: no module named 'netrc'`

`Netrc` seems to be a standard python module, that for some reason Renpy does not ship with. Can anybody explain this?

When I manually add netrc.py to the python-packages directory, suddenly the module `_multibytecodec` is missing, which is also considered a standard Python module.

**Comment by renpytom** [comment]
Not every third party module works with Ren'Py. We ship a limited subset of Python, for game size reasons.

**Comment by renpytom** [comment]
I've gone ahead and included the full Python standard library, less the modules that require third party libraries (like the dbm wrappers, uuid, sqlite, etc). I also left out the modules that will be removed in Python 3.12. 

Multiprocessing is there, as is _multibytecodec, netrc. 

I haven't included numpy, but it might get included in the future.

**Comment by metanoder** [comment]
@renpytom 

I am very interested in including numpy in my game in Ren'py.  I am hoping this isn't a big ask, but can you provide some general steps to include numpy, if we build ren'py from source ourselves?  That would greatly help me until numpy is added in the future.

> I've gone ahead and included the full Python standard library, less the modules that require third party libraries (like the dbm wrappers, uuid, sqlite, etc). I also left out the modules that will be removed in Python 3.12.
> 
> Multiprocessing is there, as is _multibytecodec, netrc.
> 
> I haven't included numpy, but it might get included in the future.

**Comment by Gouvernathor** [comment]
You can do that : https://www.renpy.org/dev-doc/html/python.html#first-and-third-party-python-modules-and-packages
The example featuring "requests" is a bit obsolete since requests has been included in mainline renpy for some versions now. Maywe we should write numpy instead.

**Comment by mal** [comment]
`numpy` isn't pure Python, so those docs won't help. Any docs there might be on the subject are likely in the `renpy-build` repo.

**Comment by metanoder** [comment]
Thanks @Gouvernathor @mal 

Tried to implement processes from the link Gouvernathor mentioned, but no dice.  Had the impression I needed to compile Renpy with Numpy.  Will look at the renpy-build repo next.  

Looking at the output, numpy needs C to be compiled with it?  ...yea, would love to know how to do that...  Appreciate any guidance.

![Screenshot 2023-08-03 165124](https://github.com/renpy/renpy/assets/117393840/a943a282-40b7-4bf8-8141-f38d03aa0ae6)

**Comment by m-from-space** [comment]
@metanoder 

> Looking at the output, numpy needs C-extensions with it? ...yea, would love to know how to do that... I'd have to compile C-extensions with numpy to renpy? Appreciate any guidance.

Since I also want to include `sqlite3`, which is not shipped with Renpy (although part of the Python standard library), I am looking for answers. This might be the one I guess: https://github.com/renpy/renpy-build/tree/master/extensions - Meaning, prepare those extensions as documented and then build Renpy yourself.

**Comment by metanoder** [comment]
Thank you for sharing this!  I'm gonna give it a try. 🙏🏼🥂
