### ISSUE TITLE
Anroid crash on startup when using 1920x1080

### ISSUE THREAD

**Issue by EngJoos** [renpy/renpy#4458]
My Ren'Py builds for android don't get past splash-screen after which they crash (even the default projects). I discovered there's one game that does work which is "The Question". After doing some comparing back and forth, it seems the culprit for me here is:

init python:
    gui.init(1920, 1080)

Cause whenever I change the aspect ratio to:

init python:
    gui.init(1280, 720)

... every android build suddenly works again.

Are more people experiencing this issue? Does anyone know a solution to this?

I've added the logcat crash report below.

[logcat.txt](https://github.com/renpy/renpy/files/11017323/logcat.txt)

**Comment by qinlili23333** [comment]
According to logcat, u r testing on an actual phone. Log file is a bit complex since tons of logs from other apps.
Can u test it on Android emulators such as AVD or WSA?

**Comment by EngJoos** [comment]
I'm unable to use AVD or WSA with my current setup. I did just try the android apk with BlueStacks android emulator and the exact same crash occurred. 

I've added the log below. Hope it's useful!
[Player.log](https://github.com/renpy/renpy/files/11018021/Player.log)

**Comment by renpytom** [comment]
I can't reproduce this with the nightly build of Ren'Py 8.1, on my Pixel 7. Can you try this with the nightly build from https://nightly.renpy.org ?

**Comment by EngJoos** [comment]
I can build a package for android with the latest release (which causes a crash when I try to launch the game later) but when I try it on the latest nightly, I get renpy :app:validatesigningrelease error.

I've reinstalled Ren'Py, but still the issue persists.

**Comment by EngJoos** [comment]
I still can't get it to work...

I deleted all keys from the game folder, removed Ren'Py, reinstalled the nightly of 20 March, downloaded RAPT from the Ren'Py Launcher, Installed SDK & Created Keys, Configured Package, but I keep getting the same error when building the package.

Am I missing something?

**Comment by renpytom** [comment]
Have you released the game yet?

**Comment by EngJoos** [comment]
Yes, but not in the Play Store. Only as a download link. Is there something else I need to delete to reset the android key?

**Comment by renpytom** [comment]
So, you'll need to grab the android.keystore from the rapt directory of your older Ren'Py build, and copy it into the game's basedir. That will allow you to build a version that installs on your phone. (You might also want to move over bundle.keystore, if it exists.)

**Comment by marchare555** [comment]
I have the exact same error as EngJoos when using yesterday's 7.x nightly, and I put the android.keystore and bundle.keystore files in the game's basedir as well. I also get this issue if I generate new keys for The Question and try exporting.

**Comment by renpytom** [comment]
There was an issue with, IIRC, bundle.keystore that was causing problems. That's been fixed for a while. Please let me know if you can't build with 8.1.
