### ISSUE TITLE
label_overrides doesn't play nice with local labels

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#4459]
I can't tell if this intended behavior or not, but in working on my project I discovered that label_overrides will not work with a local label.  Here's a quick test project that shows that:

```
define config.label_overrides["old_label.sub1"] = "new_label" 

label start:

  "Lets jump to the next label!"
  
  jump old_label
  
label old_label:

  "This is the old label"
  
label old_label.sub1:

  "This is still the old label"
  
  "Sad :("
  
  return
  
label new_label:

  "This is the new label"
  
  "Yay! :)"
  
  return
```

If you change both instances of `old_label.sub1` to simply `old_label_sub1` it will work.

**Comment by Gouvernathor** [comment]
Where is the `jump old_label.sub1` or `jump .sub1` at which the label override is supposed to trigger ?

**Comment by HorBro38** [comment]
*sigh*

You can close this.  It looks like it got eaten during a cut and paste and neither myself nor any of the folks I asked saw that.

Whoops!
