### ISSUE TITLE
map_event(ev, "mousedown_1") is False when click with ctrl

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#4461]
map_event(ev, "mousedown_1") is True when click with shift. But, map_event(ev, "mousedown_1") is False when click with ctrl.
This occurred with renpy-8-nightly-2022-12-12-8.1.0.22121201n-sdk.zip.
This didn't occur with renpy-8-nightly-2022-12-05-8.1.0.22120502n-sdk.zip.

For example, I wrote below code.
Click with shift cause the exception, but click with ctrl didn't cause it.

```
init python:
    class test(renpy.Displayable):

        def __init__(self, **properties):
            super(test, self).__init__(**properties)

        def event(self, ev, x, y, st):

            if renpy.map_event(ev, "mousedown_1"):
                raise Exception("clicked")

        def render(self, width, height, st, at):
            d = Null()
            render = d.render(width, height, st, at)
            return render
```

```
label start:
    show expression test()
    "test"
```

**Comment by renpytom** [comment]
This is an intended change. You need to use "ctrl_mousedown_1" as the keysym for when ctrl is pressed.

**Comment by danilnetrebskij6-rgb** [comment]
Can't you help me?

                if not mouse_clicked and renpy.map_event(evt="mouseup_1", focus="screen"):
                    $ mouse_clicked = True
                    if aim_start == (0, 0):
                        $ aim_start = (cue_ball.x, cue_ball.y)
This line is needed to make a hit in a mine game, but it gives an error.
Tell me the solution
