### ISSUE TITLE
Failed to give a name to the character.

### ISSUE THREAD

**Issue by KOPBYC** [renpy/renpy#4462]
﻿ I write the code:

   $ persistent.player_name = renpy.input("I think my name was....", default="Lucius.").strip()
    call update_objectives from _call_update_objectives
    $ renpy.save_persistent()
    Luc "Only the name! [persistent.player_name]."
__________________________________________________________________________________________________
This causes the code....:
    call update_objectives from _call_update_objectives
.... to generate the error shown below. When I remove this line of code, then the game goes on without errors. But with other characters does not give errors. I don't understand what the problem is.

______________________________________

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/day_1.rpy", line 142, in script call
    call update_objectives from _call_update_objectives_4
  File "game/script/day_1.rpy", line 142, in script call
    call update_objectives from _call_update_objectives_4
ScriptError: could not find label 'update_objectives'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/day_1.rpy", line 142, in script call
    call update_objectives from _call_update_objectives_4
  File "renpy/ast.py", line 1719, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script/day_1.rpy", line 142, in script call
    call update_objectives from _call_update_objectives_4
  File "renpy/script.py", line 957, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'update_objectives'.

Windows-10-10.0.19041 AMD64
Ren'Py 7.6.0.22111002n
Ancient Time 0.1a
Tue Mar 21 18:14:48 2023

**Comment by renpytom** [comment]
It looks like update_objectives isn't defined in the game. 

Do you think there is a problem with Ren'Py here?

**Comment by KOPBYC** [comment]
I do not know, I did not give any problems before, do you think if you remove this line, it will be worse?)

**Comment by renpytom** [comment]
I'm closing this, since it involves modding games.
