### ISSUE TITLE
Launcher fails to create new projects

### ISSUE THREAD

**Issue by KOPBYC** [renpy/renpy#4463]
Launcher fails to create new work projects and does not start a "learning project"

Just downloaded and re-installed "renpy", installed for it: Atom, visual code.
But the "training renpy project" does not start, and a new project is not created, writes that there was an "error".
![Безымянsный](https://user-images.githubusercontent.com/62189540/226707105-3d627330-bf25-4be9-99db-1cc7bed48293.png)

**Comment by KOPBYC** [comment]
Can anyone give me an idea how to solve the problem?

**Comment by renpytom** [comment]
Can you look for log.txt, error.txt, or traceback.txt in the new project?

**Comment by shawna-p** [comment]
I suggest you install 8.0.3, the stable version of Ren'Py, rather than the nightly if you are new to Ren'Py, as well.

**Comment by KOPBYC** [comment]
> I suggest you install 8.0.3, the stable version of Ren'Py, rather than the nightly if you are new to Ren'Py, as well.
The thing is, I tried to run both versions, but the result is the same: Error.



> Can you look for log.txt, error.txt, or traceback.txt in the new project?

there is no file with errors. :) It does not appear.

**Comment by renpytom** [comment]
You can sometimes have that happen if the encodings are set wrong on your system - Mixing Japanese and Cyrillic characters has done it. I'd suggest creating c:\vns , and moving Ren'Py and your game there. 

Can the Tutorial launch properly?

**Comment by KOPBYC** [comment]
> You can sometimes have that happen if the encodings are set wrong on your system - Mixing Japanese and Cyrillic characters has done it. I'd suggest creating c:\vns , and moving Ren'Py and your game there.
> 
> Can the Tutorial launch properly?


Thank you. It's up and running. 
But my curiosity got even more piqued.) After all, the old "renpy 8.0.3" I deleted an hour ago was installed/unpacked in the Cyrillic folder and had no problems. And now...
Thanks anyway))
