### ISSUE TITLE
About the translation feature

### ISSUE THREAD

**Issue by indescribableQB** [renpy/renpy#4465]
I generated the translation file and also added the language selection feature to screens.rpy. But entering the game cannot choose another language, what is the reason?
The environment system is Renpy 8.0.3, Win11, Python 3.11
![QQ截图20230322143346](https://user-images.githubusercontent.com/42056610/226821400-9718aabf-0b00-42cb-aec4-5b72a734143a.png)

![QQ截图20230322143107](https://user-images.githubusercontent.com/42056610/226821205-6def7899-9137-4aa7-b722-097508ea0da3.png)
![QQ截图20230322135657](https://user-images.githubusercontent.com/42056610/226821273-5cb1582c-2da2-4b06-8c67-88b079e8fe68.png)

**Comment by renpytom** [comment]
It's case sensitive - schinese and SChinese are different.

**Comment by indescribableQB** [comment]
I changed the file name to lowercase and still can't choose.
![QQ截图20230322212716](https://user-images.githubusercontent.com/42056610/226919331-3272b2a7-36ac-4a2a-ab7a-af0fdb907cda.png)
![QQ截图20230322212857](https://user-images.githubusercontent.com/42056610/226919342-ac664123-c3ea-44af-97df-bc3ec30eb871.png)

**Comment by Gouvernathor** [comment]
What do your `translate` blocks look like inside the tl/schinese folder ? If it's still with caps it won't work, the folder name is not enough

**Comment by indescribableQB** [comment]
This code? I didn't move.
![QQ截图20230322213217](https://user-images.githubusercontent.com/42056610/226920730-3622858b-eb5a-4fd0-bf64-92c5046d55cd.png)

**Comment by Gouvernathor** [comment]
No, I said the code inside the tl/schinese folder.

**Comment by indescribableQB** [comment]
![QQ截图20230322213728](https://user-images.githubusercontent.com/42056610/226922072-57460280-7ff3-4121-9a25-502fa77cbe1f.png)

**Comment by Gouvernathor** [comment]
Yes, those ones. You can see that they are still `SChinese` and not `schinese` as they should.

**Comment by indescribableQB** [comment]
I see, thank you very much for taking the time to answer my questions.

**Comment by indescribableQB** [comment]
> Why not use `Language("SChinese")` instead? You do not have to use all-lowercase.

In that case, I didn't know that the naming in the translated document would also cause this problem.：）

**Comment by renpytom** [comment]
I believe this is solved now.
