### ISSUE TITLE
Video sprites highlights don't work anymore on 8.1

### ISSUE THREAD

**Issue by GGAdams3D** [renpy/renpy#4469]
Hi I'm working on a pretty advanced animated sprite system which heavily use videos. I read recently that the 8.0 renpy version had some performance troubles with videos. My sprites use a highlight system (you know the free one) that changes the colors and brightness and a zoom, but now it doesn't work anymore. The zoom still work but the other effects don't. It's only on the video sprites, I also use image sprites that work fine.

**Comment by renpytom** [comment]
Can you put together a demo? I can't think of anything that changed here.

**Comment by GGAdams3D** [comment]
Actually I found that it didn't work anymore with the image sprites and when going back to 8.0 it still didn't work. So maybe something happened which is weird. I will invest more time to figure it out. So good news it maybe not related to videos after all....

**Comment by GGAdams3D** [comment]
It was a mistake. I turned off config.gl2 to False... I only noticed it when compared to a previous version. I didn't know it has this effect. Good news then, I'll edit the post as it was a mistake.

**Comment by Gouvernathor** [comment]
I don't think we support `config.gl2` being False in 7.5+, as True is now the default and the config is not documented anymore.

**Comment by GGAdams3D** [comment]
> I don't think we support `config.gl2` being False in 7.5+, as True is now the default and the config is not documented anymore.

Indeed it worked without the define of the variable so I guess it is now native. I got back into Ren'Py just recently.

**Comment by GGAdams3D** [comment]
I don't know how to delete the issue. If you can do something about this please do.

**Comment by Gouvernathor** [comment]
We can just close it, it's fine.
