### ISSUE TITLE
Accessibility: light theme default UI colors have bad text color contrast for non-hovered choices

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4470]
When creating a new project with the light theme (and any main color), the non-hovered choices have greyish text on white making it hard to read.

![RenPy 8 0 3 - Light theme UI has bad contrast for non-hovered choices](https://user-images.githubusercontent.com/1067772/226983062-164c7f1a-b5c5-4ec0-8b16-6897feca0614.png)

I'll customize it anyway, but it would be nice to have a good contrast by default, namely AA or even AAA:
https://webaim.org/resources/contrastchecker/

Currently, contrast is around 1.49:1 and we'd need at least 4.5:1 for normal text.

**Comment by renpytom** [comment]
I agree, I'll be looking at this shortly.
