### ISSUE TITLE
Ren'Py Launcher - Create new project: Resolution choice gives no feedback on click

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4471]
Below, I'm clicking on various resolutions to startup my project, but there is no feedback confirming my choice.

![RenPy Launcher - Create new project - Resolution choice gives no feedback on click](https://user-images.githubusercontent.com/1067772/226983827-e3ff412e-322d-44dd-8c97-ecf827615069.gif)

I don't remember having this issue in Ren'Py 7. Maybe it's a regression.

**Comment by Gouvernathor** [comment]
I can't reproduce that. It seems all your text appears in bold, are you using a custom theme ?

**Comment by hsandt** [comment]
No, it's the default theme (set in preferences > Theme).
You mean the text _should_ appear in bold, but it doesn't in my app?

**Comment by Gouvernathor** [comment]
Kind of the opposite, the selected option should appear in bold and the rest in thin, but on your screenshot everything appears in bold.
Are you using the english language in the launcher ?

**Comment by renpytom** [comment]
It looks like this is a problem when high contrast text is enabled.

**Comment by hsandt** [comment]
OK, I haven't enabled anything special, is there a way I can disable high contrast text to test, or is it something OS-related?

About bold, it seems to be the default font weight, but I do see thinner text on all language names containing some accents or unicode, so I suppose this is the actual normal weight, and all the rest is bold indeed.

![image](https://user-images.githubusercontent.com/1067772/227203731-7e1790ba-b9f1-42b4-b3c7-0cc0474bd8ca.png)

I don't have too much time to test fixing commit at the moment, but I can try it on next release (or after the Nanoreno 2023 is over...)
