### ISSUE TITLE
Video sprite don't dissolve with each other

### ISSUE THREAD

**Issue by GGAdams3D** [renpy/renpy#4472]
It's an issue that I had since the beginning I started making animated sprites with videos. Basically when changing a character expression using video sprites the dissolve function don't work, instead it does a little pause and switch.

Preview: https://user-images.githubusercontent.com/128613924/227004633-268fe5c1-ba27-43af-b2eb-79c1e427a13d.mp4

As you can see from the video, Natsu don't dissolve while Yin who uses image sprites does.

**Comment by renpytom** [comment]
Can you post how you declare Natsu's movies? Do they share a single channel?

**Comment by GGAdams3D** [comment]
> Can you post how you declare Natsu's movies? Do they share a single channel?

Sure I'll try:

Here is natsu's code for her non-talking sprites:
`image natsu_neutral_1 = At(Movie(channel="natsu", play= "sprites_natsu/natsu_neutral1_sidemask.webm", side_mask=True, framedrop=False), sprite_highlight('natsu'))
image natsu_neutral_2 = At(Movie(channel="natsu", play= "sprites_natsu/natsu_neutral2_sidemask.webm", side_mask=True, framedrop=False), sprite_highlight('natsu'))
image natsu_happy_1 = At(Movie(channel="natsu", play= "sprites_natsu/natsu_happy1_sidemask.webm", side_mask=True, framedrop=False), sprite_highlight('natsu'))
image natsu_happy_2 = At(Movie(channel="natsu", play= "sprites_natsu/natsu_happy2_sidemask.webm", side_mask=True, framedrop=False), sprite_highlight('natsu'))`

And here is Yin one:
`image yin happy = At('sprites/yin_happy[yin_costume].webp', sprite_highlight('yin'))
image yin angry = At('sprites/yin_angry[yin_costume].webp', sprite_highlight('yin'))
image yin sad = At('sprites/yin_sad[yin_costume].webp', sprite_highlight('yin'))
image yin horny = At('sprites/yin_horny[yin_costume].webp', sprite_highlight('yin'))
image yin shock = At('sprites/yin_shock[yin_costume].webp', sprite_highlight('yin'))
image yin fight = At('sprites/yin_fight[yin_costume].webp', sprite_highlight('yin'))
image yin neutral = At('sprites/yin_neutral[yin_costume].webp', sprite_highlight('yin'))`

**Comment by renpytom** [comment]
The issue here is the ``channel="natsu"``. All the movies are playing on the same channel, which shares resources, but doesn't allow two movies to play at once. 

Remove all of the ``channel="natsu",``. That will give each movie file its own channel, which Ren'Py will manage, and  things should just work.

**Comment by GGAdams3D** [comment]
> The issue here is the `channel="natsu"`. All the movies are playing on the same channel, which shares resources, but doesn't allow two movies to play at once.
> 
> Remove all of the `channel="natsu",`. That will give each movie file its own channel, which Ren'Py will manage, and things should just work.

okay thanks, indeed now it dissolve! But there is a new issue. The talking sprites now "flashes". I'll share a video.

**Comment by GGAdams3D** [comment]
> The issue here is the `channel="natsu"`. All the movies are playing on the same channel, which shares resources, but doesn't allow two movies to play at once.
> 
> Remove all of the `channel="natsu",`. That will give each movie file its own channel, which Ren'Py will manage, and things should just work.

Here is the video: https://user-images.githubusercontent.com/128613924/227219819-1f260f78-0c51-47cd-ba21-ef10d89def49.mp4

As you can see the sprites do dissolve now but are glitchy.
