### ISSUE TITLE
Problem: IME choosing box for Chinese broke on Windows, in Ren'py 8.0.3

### ISSUE THREAD

**Issue by Longtianmu** [renpy/renpy#4474]
I have known that the problem has been solved in version 7 by patching SDL2.
Howevere, I meet the problem again, with these environment:
Windows 11
Chinese,Microsoft IME
Ren'py 8.0.3
I had test this problem on several computers, and the results are the same.

**Comment by renpytom** [comment]
Do you have a description of how it's broken?

**Comment by Longtianmu** [comment]
Sorry, I forget.
The choosing box doesnt appear when attempt to input characters.
