### ISSUE TITLE
Video sprites flickering when conditionswitch

### ISSUE THREAD

**Issue by GGAdams3D** [renpy/renpy#4475]
Here is the video: https://user-images.githubusercontent.com/128613924/227219819-1f260f78-0c51-47cd-ba21-ef10d89def49.mp4

As you can see the sprites do dissolve now but are glitchy. They glitch when the sprite is speaking which is the same sprite with the mouth moving, it works as a condition switch. So it's pretty basic, the callback change a variable that show the right sprite when speaking.

Here is natsu's code for her non-talking sprites:
`image natsu_neutral_1 = At(play= "sprites_natsu/natsu_neutral1_sidemask.webm", side_mask=True, framedrop=False), sprite_highlight('natsu'))
image natsu_happy_1 = At(Movie(play= "sprites_natsu/natsu_happy1_sidemask.webm", side_mask=True, framedrop=False), sprite_highlight('natsu'))

**Comment by renpytom** [comment]
The issue with this is that it takes a small amount of time between when a movie is shown, and when the first frame is decoded. This is what the start_image parameter to Movie is for - it lets you put that first frame into an image file that can be predicted before the image is shown. 

https://www.renpy.org/doc/html/movie.html#Movie

**Comment by renpytom** [comment]
Can you send that as a small demo to renpytom@gmail.com? I have an idea for an optional behavior that might make this work better, though I'm not sure if the semantics will work out for everyone.

**Comment by GGAdams3D** [comment]
> Can you send that as a small demo to [renpytom@gmail.com](mailto:renpytom@gmail.com)? I have an idea for an optional behavior that might make this work better, though I'm not sure if the semantics will work out for everyone.

Sure, if that can help. I'll edit the demo so that it will be easy to navigate then. Thanks.

**Comment by GGAdams3D** [comment]
missclick lol

**Comment by renpytom** [comment]
Fixed this. Basically, you can now declare Movie(group="natsu", play="...") and when switching between natsu movies, things will work the way you want. 

Probably.

**Comment by GGAdams3D** [comment]
> Fixed this. Basically, you can now declare Movie(group="natsu", play="...") and when switching between natsu movies, things will work the way you want.
> 
> Probably.

It works! You're a god! I don't know how coding works but I'm happy to have help push Ren'Py a little more with my specific issue. Thanks.
