### ISSUE TITLE
Function to replace the current context with a new context.

### ISSUE THREAD

**Issue by valery-iwanofu** [renpy/renpy#4476]
The title of issue speaks for itself, but just in case, I will give an implementation of "unsafe" code that does what I would like to achieve using a documented API:
```renpy
label real_after_load:
    # maybe do some data migrations here
    python hide:
        for store_name, old_store_dict in renpy.session['stores'].items():
            renpy.python.store_dicts[store_name].update(old_store_dict)
        renpy.session.pop('stores')
    call set_vars
    jump loop
    return

label after_load:
    # persistent.game_version used for testing purposes
    # in real game it should be replaced with config.version
    if persistent.game_version != game_version:
        python hide:
            # we save changed store variables to renpy.session and restore them in "real_after_load" label
            changed = {}
            for store_name, store_dict in renpy.python.store_dicts.items():
                store_dict_copy = python_dict()
                for key, value in store_dict.items():
                    if key in store_dict.ever_been_changed:
                        store_dict_copy[key] = store_dict[key]
                changed[store_name] = store_dict_copy
            renpy.session['stores'] = changed
            renpy.full_restart(False, 'real_after_load')
    return
```

<details>
  <summary>The whole code</summary>
  
  ```renpy
default persistent.game_version = 1

screen debug_overlay:
    textbutton 'Toggle version([persistent.game_version])' action ToggleField(persistent, 'game_version', 1, 0) selected False

init python:
    config.always_shown_screens.append('debug_overlay')

screen test:
    text 'Shown'

default my_var = 0

label my_scene:
    scene expression '#610561' with dissolve
    show screen test
    'Inner scene.'
    $ my_var = True
    return

label loop:
    '[my_var]'
    call my_scene

    jump loop

label set_vars:
    $ game_version = persistent.game_version
    return

label start:
    call set_vars
    jump loop

label real_after_load:
    # maybe do some data migrations here
    python hide:
        for store_name, old_store_dict in renpy.session['stores'].items():
            renpy.python.store_dicts[store_name].update(old_store_dict)
        renpy.session.pop('stores')
    call set_vars
    jump loop
    return

label after_load:
    # persistent.game_version used for testing purposes
    # in real game it should be replaced with config.version
    if persistent.game_version != game_version:
        python hide:
            # we save changed store variables to renpy.session and restore them in "real_after_load" label
            changed = {}
            for store_name, store_dict in renpy.python.store_dicts.items():
                store_dict_copy = python_dict()
                for key, value in store_dict.items():
                    if key in store_dict.ever_been_changed:
                        store_dict_copy[key] = store_dict[key]
                changed[store_name] = store_dict_copy
            renpy.session['stores'] = changed
            renpy.full_restart(False, 'real_after_load')
    return
  ```
</details>

**Comment by renpytom** [comment]
Right now, what you want to do it's supported, except through saving and then loading again. What are you actually trying to accomplish by restaring the game. It seems like this is a really complicated version of "jump".

**Comment by renpytom** [comment]
Specifically, if what you're trying to do is jump to a different place after load, you want to do:

```renpy
label after_load:
    python:
         while renpy.call_stack_depth():
              renpy.pop_call()
    
    jump loop
```

Something like that.

**Comment by valery-iwanofu** [comment]
> Specifically, if what you're trying to do is jump to a different place after load, you want to do:
> 
> ```renpy
> label after_load:
>     python:
>          while renpy.call_stack_depth():
>               renpy.pop_call()
>     
>     jump loop
> ```
> 
> Something like that.

There is still a problem with showed screens and displayed images by labels called from `loop` label. Restarting the game is exactly what solves this problem. 

I want to accomplish that after loading a new version of the game, regardless of whether I changed the content of the labels or the game logic, I would be able to sort of "start the game all over again", but keep the storage variables at the same time. In that case, no matter where the player saves, he would still be able to use the save from the previous version of the game.

**Comment by renpytom** [comment]
Abusing the load/save mechanism isn't the right way to do this. 

I think the right way would be a function that replaced the top-level context with a new context at a given label.

**Comment by valery-iwanofu** [comment]
> I think the right way would be a function that replaced the top-level context with a new context at a given label.

I already tried to replace the context, but probably I somehow created it wrong or misunderstood the concept of context in general. With this code:
```python
context = renpy.execution.Context(False)
context.init_phase = False
renpy.game.contexts.append(context)

renpy.exports.block_rollback()

renpy.game.context().goto_label('real_after_load')
raise renpy.game.RestartContext()
```

i got the following error:
```
While running game code:
  File "game/script.rpy", line 22, in script
    '[my_var]'
  File "renpy/common/00gamemenu.rpy", line 117, in _invoke_game_menu
    if renpy.context()._menu:
AttributeError: 'RevertableObject' object has no attribute '_menu'
```

But even if I succeeded, I don't really want to use undocumented solutions, so I'll wait for the next release of Ren'Py, where the function to replace the context will already be there (hopefully).

**Comment by mal** [comment]
Out of curiosity, what is it that you gain from a new context that you wouldn't achieve from expanding Tom's snippet to block rollback and clear the screens and master layers?

<details><summary>Expanded snippet.</summary>

```rpy
label after_load:
    if persistent.game_version != game_version:

        python:
            while renpy.call_stack_depth():
                renpy.pop_call()

            renpy.block_rollback()

        scene onlayer screens
        scene black

        jump loop

    return
```
</details>

**Comment by valery-iwanofu** [comment]
`scene onlayer screens` - this is cheating! 
Apparently, I should read the documentation better before getting into the depths of the engine. 
This is exactly the solution I was looking for. Thank you.

Should this issue be closed or not?

**Comment by Gouvernathor** [comment]
I think `scene onlayer screens` is not documented as removing the screens, nor should it probably. But then, the other things you were using before weren't documented either, so if you think it's enough then good for you.
Documenting what a context is would be useful anyway.

**Comment by renpytom** [comment]
I'd like to do something here - I think the ability to reset everything that isn't variables and control flow will be valuable to add.
