### ISSUE TITLE
Live2D Properties! (Maybe just a question, maybe a request.)

### ISSUE THREAD

**Issue by GoldenCrowInf** [renpy/renpy#4487]
Hello!
I will try to be as succinct as possible.
I'm trying to migrate my game to use Live2D. I'm trying to add visual personalization to my chars. I need to be able to edit internal Live2D model parameters using Ren'py. So I can recolor something, or change a hair model, eye tracking, etc. 
My question is:
Is it possible to change a model parameter from a Live2D model using Ren'py? If not, will that be possible in any near future?

 >>The question ends in here. Now I'll describe what I've been trying to do to make it possible.<<

Why do I need to be able to edit it from renpy?! Because it's not viable for me to have expression files of every single configuration of char.

From what I could read on documentation, it's only possible to edit >renpy parameters< of a live2d object using update_function (such as 'top', 'base', etc). 
I'm using expression files to achieve what I need.
I've tried to edit my expression files using renpy codes, but the game loads it at the start. So the changes only apply if the game reloads.
I tried as well create expression file from the game and apply it using a dynamic name. But once more, the list of exressions are defined on game load, so I receive the error message saying the expression do not exists. On game reload after error message, it works.
I hope I'm not asking a dumb question in here, and if I'm missing something, I'm sorry. But I've really tried reading everything I could and watching every single tutorial I could find. Asking here really is my last resort.
Thanks in advance!

**Btw, I want to know if it will be possible to add Live2D elements in screens using add or something like this?

Edit: I'm sorry, I posted as an Issue instead of a Pull request. I don't know how to move/delete it.

**Comment by renpytom** [comment]
Just to understand this - you're interested in updating the properties directly, rather than going through motions or expressions?

**Comment by GoldenCrowInf** [comment]
Yes. Because I can't have one file for every single configuration of live2D properties sliders. Imagine that you want to do the live2D char follow the mouse with the eyes. Using motions and expressions it's impossible. I need to be able to change the properties sending from ren'py to the model.

**Comment by renpytom** [comment]
I'm thinking of a callback that is called each time an Live2D object is rendered, that returns a dictionary of properties and values, and a time to update them.

**Comment by GoldenCrowInf** [comment]
This solves my problem for sure! Thank you so much! I'm looking forward to it!

**Comment by renpytom** [comment]
I'm going to be touching Live2D between the first 8.1 prerelease and the actual release, so I expect this to happen there.

**Comment by renpytom** [comment]
This callback was there, and it's the update_function argument to Live2D. It's called with two arguments. 

* The Live2D object.
* st, the time since the object was first shown. 

The function then gets the Live2D object, and can set its parameters. 

For example: 

```renpy
init python:

     def always_open_eyes(live2d, st):
           live2d.blend_parameter("ParamEyeLOpen, "Overwrite", 1.0)
           live2d.blend_parameter("ParamEyeROpen, "Overwrite", 1.0)
           return None

image Hiyori = Live2D("Hiyori", update_function=always_open_eyes)
```
