### ISSUE TITLE
Have renpy versions of builtin containers rollback the attributes

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4498]
Since they don't have an empty `__slots__` anyway.
Helps having renpy-friendly versions of defaultdict, OrderedDict, [sortedcontainers](https://github.com/grantjenks/python-sortedcontainers/), and creator-defined dict subclasses.
To avoid overhead, maybe adding the methods in `__init_subclass__` could be good if we only want to allow that for subclasses wor performance worry.

Maybe we could also hook into the AST magic that for a class **indirectly** inheriting python_dict and not renpy_dict, renpy_dict is inserted in the mro. That would make `class defaultdict(collections.defaultdict)` work with rollback natively by default, and have an opt-out as `class defaultdict(collections.defaultdict, python_dict)`.

**Comment by mal** [comment]
It's already fairly trivial for creators to do some of this themselves as revertible subclasses are already possible:
```rpy
init python:
    # Creator-defined RevertableDict with defaults
    class listdict(dict):
        def __missing__(self, name):
            rv = self[name] = list() # or whatever default you like
            return rv
```

OrderedDict doesn't offer much over regular dicts (in Python3) now that keys are specified to be in insertion order, and sortedcontainers seems like a considerable amount of overhead to maintain in RenPy core for something that the vast majority of creators will never need or use - the data volumes at which sortedcontainers show real benefit is crazy high, in most reasonable cases using list.sort post-insert is going to be cheaper.

**Comment by Gouvernathor** [comment]
My first use case was a defaultdict with a factory_function changing through time, so a simple `__missing__` isn't enough.
The other is a more down-to-earth dict subclass supporting an ability with sub-abilities, where you have to put a certain amount of point in general before being allowed to improve sub-abilities. Having a .general attribute was buggy because not revertable, so I had to use a "general" key and escape it manually every time I iterate through the dict, which is a bit of a chore.
Having revertable attributes would be a simpler solution to both cases - especially since we already allow setting attributes on our dicts.

**Comment by renpytom** [comment]
00ad151a23ed22a75fea68dea60615b1b3aacbbe and 96e6975e9f7a6c5836bf5e25427d0ad54ab14540 address this issue, at least as much as I think I want to.
