### ISSUE TITLE
(Question) Live2D motion fading between show statements

### ISSUE THREAD

**Issue by PrincessNene** [renpy/renpy#4500]
This a question rather than a request, I'm trying to change some code myself but I can't figure out how. Sorry if this is not the right place to ask this! 

So basically, I want to have motion fading between each show statement and each individual motion. By motion fading, I mean what happens when you set fade = True, then click in the middle of a motion - it interpolates between the current pose and the first pose of the next motion. 

I know it shouldn't normally need to happen because when a motion ends, it transitions to the default pose, and then the next motion transitions from that pose but...The live2D models I'm using all have the default/neutral/nullmotion pose set to a T-Pose, and that means before, after and in between every motion, the character just T-Poses and it looks terrible :') 

I know the devs want to keep it consistent with Live2D by having it go to the default pose each time so I just want to modify the behaviour myself for my own project. But I'm still a beginner to programming so I'm really struggling to figure out how to do it... 

I figured out that the transition to default pose can be stopped by either setting do_fade_in and do_fade_out to False in live2d.py or setting fadein and fadeout to 0.0 in live2dmotion.py, but that also stops the interpolation that I want. I also have no idea how to replicate the mid-click interpolation so it also happens when a motion finishes and interpolates between two poses instead of either T-Posing or just cutting to the next one. 

Any tips or guidance would be much appreciated!

**Comment by renpytom** [comment]
You probably want to use an expression to set the neutral pose.

I'm not sure what to do here, because Live2D is pretty clear about how they expect this to work, and I really don't want to come up withour own live2d semantics. 

I don't believe this is an issue with Ren'Py.

**Comment by PrincessNene** [comment]
I totally understand that the current behaviour is best for Ren'py, I was just hoping to figure out how to change it for just my project. I want the next motion/pose to transition from the previous one rather than a default in-between pose, just like how it works in the Cubism Viewer. If you have time to help me understand the code a bit more, I would be very grateful!

I think I understand this much: When the user interacts, it calls update_states() and that updates the new and old states, which then lets the old_redraw and new_redraw in render() interpolate between the two poses? But is there a way that I can get update_states to be called in between motions? Also, is the default/nullmotion pose state in the states array, and can it be removed so there's no inbetween pose at all?

Thank you for your time!

**Comment by renpytom** [comment]
https://github.com/renpy/renpy/blob/master/renpy/gl2/live2d.py#L782

Fundamentally, the fade in and fade out are controlled by do_fade_in and do_fade_out, in the update method of Live2D. You can probably do something there. You might also want to look at other places Ren'Py checks to see if an animation is seamless - a few lines above, it will check for seamlessness to ensure an animation loops even if it's fading out. 

IIRC, nullmotion is just a motion that does nothing - the return to the default is due to a motion fading so much its contribution ends.

**Comment by PrincessNene** [comment]
I figured it out! I subtracted half the default fade time from motion.duration in update() and set do_fade_in to false when state.old_base_time is none and it works perfectly now! Thank you so much for your help!!

**Comment by kraytstudios** [comment]
@PrincessNene  don't know if this is at all the appropriate place to ask, but I am new to Live2D and have a very small understanding of code. Is there any way you would be willing to share/explain how you go it working in a bit more detail for a newby like me?
