### ISSUE TITLE
Updating from 8.0 to 8.1

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4503]
It's been some months that every time I downgrade from the nightly to the release, things are fine, but when I upgrade back to the future there are breaks in persistent data.
The launcher appears in the clear theme and prompts me for language every time after I upgrade, and what's weirder is that when I go to the Preferences/Theme tab, the Dark option is checked, and clicking it activates it.
There are other issues I think when I launch games in different versions, I think they get their persistent flushed too, but I'm not too keen on testing that on my precious games and console entries - and the launcher being itself a game itself should be enough for a testing ground.

**Comment by renpytom** [comment]
This is probably the new save security stuff kicking in. The upgrade works once per project, but upgrade/downgrade/upgrade isn't supported.
