### ISSUE TITLE
Show on-screen pygame graphical elements such as Rect

### ISSUE THREAD

**Issue by DonRP** [renpy/renpy#4507]
Hi I am developing a library that allows to convert pygame games to renpy: https://github.com/DRincs-Productions/Renpygame/tree/6-implement-my-pygame-library
a while back I already asked for something similar https://github.com/renpy/renpy/issues/4433 and was told to use Creator-Defined Displayables https://www.renpy.org/doc/html/cdd.html

-----

But I have a big problem: I noticed that if I show from python a renpy.Displayable and after that I effect some operations and also enter a timeout. this will be shown only after the timeout is over. this is a problem.

Also if there is a better way to draw graphical elements of pygame please tell me.

Es:

```renpy
label start:
    $ aliens.main()

screen rect(
    left = 0,
    top = 0,
    width = 0,
    height = 0,
    img = None,
):
    add Rect(left = left, top = top, width = width, height = height, image = img)

```
```py
def main(winstyle=0):
    renpy.show_screen(
            "rect", left=dest[0], top=dest[1], width=self.size[0], height=self.size[1], img="background.gif")

    pygame.time.wait(1000)

```

```py
class Rect(renpy.Displayable, pygame.rect.Rect):
    """https://www.pygame.org/docs/ref/rect.html"""

    def __init__(
        self,
        # pygame.rect.Rect
        left: int = 0,
        top: int = 0,
        width: int = 0,
        height: int = 0,
        # my params
        image: Optional[str] = None,
        **kwargs
    ):

        # renpy.Displayable init
        super(Rect, self).__init__(**kwargs)

        # pygame.rect.Rect init
        pygame.rect.Rect.__init__(self, left, top, width, height)
 
        # The width and height of us, and our child.
        self.width = width
        self.height = height
        self.left = left
        self.top = top
        self.image = image

    @property
    def image(self):
        return self._image

    @image.setter
    def image(self, value: str):
        if value:
            self._image = renpy.displayable(value)
        else:
            self._image = None

    def render(self, width: int, height: int, st: DOUBLE, at: DOUBLE):
        # Create the render we will return.
        render = renpy.Render(self.width, self.height)

        if self.image:
            # Create a render from the child.
            child_render = renpy.render(self.image, width, height, st, at)

            # Get the size of the child.
            self.width, self.height = child_render.get_size()

            # Blit (draw) the child's render to our render.
            render.blit(child_render, (self.left, self.top))

        # Return the render.
        return render

```

**Comment by Booplicate** [comment]
> `class Rect(renpy.Displayable, pygame.rect.Rect)`

Probably unrelated, but looks like super incorrect usage of inheritance.

**Comment by Booplicate** [comment]
Dependency injection, pass your rect to your displayable to avoid conflicts with renpy.

Iirc `pygame.time.wait` pauses the execution, so that's why nothing happens for you. If you need a timeout, you could use renpy tools for that.

**Comment by DonRP** [comment]
@Booplicate 

`Dependency injection, pass your rect to your displayable to avoid conflicts with renpy.`

It's not good because one of the two extended classes is saved as a variable (if I understand correctly). and that's not what I want.

`Iirc pygame.time.wait pauses the execution, so that's why nothing happens for you. If you need a timeout, you could use renpy tools for that.`
How do you start a timer with the renpy library?

**Comment by renpytom** [comment]
I don't think this is an issue with Ren'Py, is it? It looks like your pygame wrapper is not working properly.

**Comment by Booplicate** [comment]
> extended classes is saved as a variable

Don't save it in a variable if you don't want it. Dependency injection doesn't require you to use variables.

> How do you start a timer with the renpy library?

There's various ways to implement a timer, all depends on your use case. There's a `timer` displayable for screens, `renpy.timeout` function for displayables, and a few others way to make a "timer".

> request to add a way to draw pygame_sdl2 elements on renpy

You just used the wrong function, I don't think it has anything to do with drawing stuff on screen.

**Comment by DonRP** [comment]
@Booplicate 
> There's various ways to implement a timer, all depends on your use case. There's a timer displayable for screens, renpy.timeout function for displayables, and a few others way to make a "timer".

I tried with renpy.timeout(1000), but it gives the exact same problem

> You just used the wrong function, I don't think it has anything to do with drawing stuff on screen.

I followed https://www.renpy.org/doc/html/cdd.html, and I can show the screen, the problem is the timer.
but no I am an expert on renpy library, if there is a solution please tell me 

@renpytom 
(I am not sure) Renpy relying on pygame_sdl2 to make the main screen must do something like this 

```py
    bestdepth = pygame.display.mode_ok(SCREENRECT.size, winstyle, 32)
    screen = pygame.display.set_mode(SCREENRECT.size, winstyle, bestdepth)
```
there is a way to make the element returned by this function public : pygame.display.set_mode(SCREENRECT.size, winstyle, bestdepth)
if you can do it give this type of development a chance (although this could create instability)

More than anything else, I don't see the reason for not giving the opportunity to develop with pygame_sdl2

**Comment by renpytom** [comment]
Fundamentally, pygame has a very different display model than Ren'Py has, especially now that Ren'Py moves basically everything to the GPU. Ren'Py is event driven, while pygame uses a blocking call to retrieve the next event (pygame.event.wait()). 

You might be able to get it working, somehow - perhaps run the game in a second thread, pass the surfaces around from your thread to the displayable that will render them, and maybe pass events the other way. I suspect it would take me a bit of time to make this work - and the results wouldn't be as good as what CDDs allow. 

You basically will have to reimplement all of pygame.display and pygame.event yourself. The normal versions just aren't suitable for use inside Ren'Py. (This is why I discontinued the original renpygame.) You can't simply go around changing the mode of the main window and expect Ren'Py to continue working - you'll have to emulate that sort of thing.

**Comment by DonRP** [comment]
@renpytom 

> Ren'Py is event driven, while pygame uses a blocking call to retrieve the next event (pygame.event.wait()).

(I'm not sure) the sense is that I'm not affetuating the timeout in the right place? I should put it in the event function of renpy.Displayable, and use a pygame.event.wait() to start it 


> You should be able to blit a pygame.Surface into a Render

I don't think I understand, with CDD is there an option to draw pygame.Surface? or do you mean I have to create a renpy.Displayable similar to pygame.Surface in order to draw it?


> You basically will have to reimplement all of pygame.display and pygame.event yourself. The normal versions just aren't suitable for use inside Ren'Py. (This is why I discontinued the original renpygame.) You can't simply go around changing the mode of the main window and expect Ren'Py to continue working - you'll have to emulate that sort of thing.

I'm currently doing something like this: class Rect is an example. the goal is to replace blit() and draw() so that they use CDD. i know this might be a long shot, but is this feasible for you? 




in addition there is a way to not have to create a screen ex:
```renpy

screen rect(
    left = 0,
    top = 0,
    width = 0,
    height = 0,
    img = None,
):
    add Rect(left = left, top = top, width = width, height = height, image = img)

```
to draw a renpy.Displayable?

**Comment by renpytom** [comment]
> (I'm not sure) the sense is that I'm not affetuating the timeout in the right place? I should put it in the event function of renpy.Displayable, and use a pygame.event.wait() to start it

No, you need to make things event-driven. Timeouts are not the way to do that. 

> I don't think I understand, with CDD is there an option to draw pygame.Surface? or do you mean I have to create a renpy.Displayable similar to pygame.Surface in order to draw it?

Yes, you can pass a pygame_sdl2.Surface to the blit function. 

> class Rect is an example. the goal is to replace blit() and draw() so that they use CDD. i know this might be a long shot, but is this feasible for you?

I don't understand what you mean by this. Rect isn't a graphical element in pygame - it's a data structure. It's not something that's drawable. You can call Render.canvas to get an object that supports drawing, as described at https://www.pygame.org/docs/ref/draw.html - though it's closer to pygame 1.8 rather than 2.1. 


I'm not sure how much more discussion is appropriate for this issue tracker. You need to learn Ren'Py and how CDDs work, before tackling a renpygame-style project.
