### ISSUE TITLE
Movie resetting on interaction

### ISSUE THREAD

**Issue by deepglugs** [renpy/renpy#4508]
Not sure if this is the right place for issues with the nightly builds but...

I'm seeing animations/movies reset to the starting frame on every interaction "click".  The last version that was working for me was the March 3 nightly, but I didn't try anything in between that and maybe March 28.

**Comment by renpytom** [comment]
Do you have some examples of what does this?

**Comment by deepglugs** [comment]
I define my video like this:
```python
image ch10_forest_rain = Movie(start_image='images/ch10_forest_rain.webp', play='videos/ch10_forest_rain_swing.webm')
```
and play it like this:
```python
scene ch10_forest_rain
pause
# video resets after interaction
c "Why is it raining"
# video resets
d "Idk. It's always raining"
# video resets again
```

**Comment by via-my** [comment]
I don't think that it's a good idea to reset Movie channels on 'hide' because now webms resets before the end of any transition.

```
label start:

    scene black
    show webm_animation with Dissolve(1.0)
    "Showed with Dissolve(1.0)"

    hide webm_animation with Dissolve(1.0)
    "Hidden with Dissolve(1.0)"

    jump start
```

**Comment by lauwurence** [comment]
Just in case.
Notice me, @renpytom😅

**Comment by renpytom** [comment]
I think the current behavior (to trigger on show) makes sense - can anyone try it to see if there's an obvious problem?

**Comment by lauwurence** [comment]
All good for me!
