### ISSUE TITLE
Implement RollForward like Rollback

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4513]
From what I gather, rollforward is not implemented like rollback is, jumping the objects and the context from memory state to memory state. This causes some issues in called screens notably, which lead to rollforward being recently disabled in called screen by default, as that could lead to corrupted history where actions aren't triggered.

**Comment by renpytom** [comment]
For a bunch of reasons, this isn't something I want. 

One example, of many: 

```renpy
label test:
    "A"
    pause .1
    "B"
    pause .1
    "C"
    return
```

Go to C, then roll back to A. Roll forward, you'll get to the pause statement. If you do nothing for .1 seconds, it will advance (as it does normally) to B. 

If we implemented roll forward the way you propose above, the natural expiration of the pause .1 timer would terminate the roll-forward state. But then you wouldn't be able to roll forward to "C", which we'd like to be able to do. 

This was an idea I considered and rejected fairly early in the implementation of rollback.
