### ISSUE TITLE
StylePreference() calls cannot be stacked inside one action

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#4514]
When StylePreference() or renpy.set_style_preference() is called multiple times in one action, only the last call is respected.

In the following example script, only the colour of the text is changed:

```
init +10 python:
    renpy.register_style_preference(
        preference='foo_preference',
        alternative='Regular Font',
        style=style.say_dialogue,
        property='font',
        value='DejaVuSans.ttf',
    )

    renpy.register_style_preference(
        preference='foo_preference',
        alternative='Other Font',
        style=style.say_dialogue,
        property='font',
        value='_OpenDyslexic3-Regular.ttf',
    )

    renpy.register_style_preference(
        preference='foo_preference',
        alternative='Regular Colour',
        style=style.say_dialogue,
        property='color',
        value='#FFF',
    )

    renpy.register_style_preference(
        preference='foo_preference',
        alternative='Other Colour',
        style=style.say_dialogue,
        property='color',
        value='#f00',
    )

default persistent.text_font = 'Regular Font'
default persistent.text_colour = 'Regular Colour'

screen foo():
    vbox:
        textbutton "Regular Font" action SetField(persistent, 'text_font', 'Regular Font')
        textbutton "Regular Colour" action SetField(persistent, 'text_colour', 'Regular Colour')

        textbutton "Other Font" action SetField(persistent, 'text_font', 'Other Font')
        textbutton "Other Colour" action SetField(persistent, 'text_colour', 'Other Colour')

        textbutton "Save" action [
            StylePreference('foo_preference', persistent.text_font),
            StylePreference('foo_preference', persistent.text_colour),
        ]

label start:

    show screen buttons

    "Foo"

    "Bar"

    "Bin"

    return

```

**Comment by renpytom** [comment]
Without looking to closely into this, Ren'Py is behaving correctly here, I think. You only have one preference (foo_preference) defined, and so only one of the four alternatives given can be selected. You're selecting first one alternative, then another, but only the second alternative will take effect.

**Comment by jsfehler** [comment]
Maybe I'm misunderstand the style preference system. If I want to change multiple properties on a style, I was under the impression one preference would be suitable for multiple properties. Should I be creating a separate preference for every property on a style I want to change?

**Comment by Gouvernathor** [comment]
It depends on the alternatives you want. If you define 4 alternatives to 1 style preference, then all four will be mutually exclusive.
In your example, it looks like you want a color preference with two alternatioves, and a font preference with two other alternatives.

**Comment by jsfehler** [comment]
In this example, "foo_preference" has 4 alternatives, of which each modifies a different property. 
In the docs, "text" has 2 alternatives, of which each modifies the same properties. 

Perhaps my misunderstanding here is that alternatives are exclusive with each other. However, using my example, if there are 4 buttons instead of 1, they behave as I expected. Text and colour can be mixed and matched.

**Comment by jsfehler** [comment]
It might be an unintended side-effect:

```
textbutton "Other Font" action StylePreference("foo_preference", "Other Font")

textbutton "Other Colour" action StylePreference("foo_preference", "Other Colour")
```

When separated, both can be applied. Since "Other Font" does not touch the color property, "Other Colour" won't undo what's already there.

**Comment by Gouvernathor** [comment]
Yes, it is an unintended side-effect that is warned against in the doc :
> One should ensure that every alternative for a given style preference updates the same set of styles and properties.

**Comment by jsfehler** [comment]
I see. I misunderstood what that meant. I assumed it was about a style preference always updating the same style, my brain must have blanked out the "properties" bit.
