### ISSUE TITLE
April 05 Nightly, Perspective Camera doesn't work

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#4518]
Just FYI, In the April 05 Nightly, all my perspective cameras don't work.

**Comment by renpytom** [comment]
Do you have an example of this?

**Comment by colinharvie** [comment]
I just opened up The question and threw this statement in.

    camera:
        perspective True zpos 200 
        xpos 100 ypos 100

    show sylvie:
        zpos -200
        
 When the perspective True is set, the camera does not move at all (even the xpos and ypos aren't applied). It just looks like the default camera position.
 
When the perspective True line is commented out, it works as expected, with the X and Y position set.

At no point does the zpos on show sylvie seem to do anything at all, whether or not Perspective is enabled on the camera. 
(In the stable 8,0.3 build, setting Zpos on silvie to anything greater than 1 or less than -1 would case the sprite to vanish, if perspective was turned off. If turned on, it acted as expected).

This same code works fine (with perspective) in the stable release.
