### ISSUE TITLE
Screen defaults leak between instances from "use"

### ISSUE THREAD

**Issue by mal** [renpy/renpy#4519]
Forgive the somewhat contrived example but it demonstrates `c` bleeding between instances while `x` works as expected. Calling `test_inner` directly seems to behave, I've only seen the issue with `use`.

```rpy
label main_menu:
    $ _confirm_quit = False
    return

label start:
    call screen test('a')
    call screen test('b')
    call screen test('c')
    'END'
    return

screen test(x):
    use test_inner(x)
    dismiss action Return()

screen test_inner(x):
    default c = x
    text 'interp x: [x]\ninterp c: [c]\n\nliteral x: ' + x + '\nliteral c: ' + c align (.5, .5)
```

Seen in `8-nightly-2023-04-03-8.1.0.23040302+nightly`.

**Comment by renpytom** [comment]
This is one of the ones where what's happening (the scope is getting reused after being predicted differenty) is obvious, and so I have no idea how this wasn't caught before now.
