### ISSUE TITLE
Maybe an unintended behaviour in _in_replay mode?

### ISSUE THREAD

**Issue by RaXorX** [renpy/renpy#4522]
I disabled auto-reload for my game and instead manually reload it using Shift+R using the var `config.auto_reload = False`

This works normally in-game, except when in replay mode, either using the Replay() function or manually triggering it by setting `_in_replay = True` from console.

While `_in_replay` is True it stops using that variable and starts doing auto reloads. Shift+R would just toggle the auto reloading like before.

Just wondering if that is the intended behaviour or not? Otherwise, the expected behaviour should be for it to just reload manually.

**Comment by renpytom** [comment]
Reloading the script should be fully disabled during replay mode, due to bad interactions with other parts of Ren'Py. As far as I can tell, this is what's happening - hitting shift+R during replay does nothing.
