### ISSUE TITLE
Another kerning issue

### ISSUE THREAD

**Issue by Envi2023** [renpy/renpy#4524]
My font doesn't seem to kern properly in Ren'py. I've read this report:
https://github.com/renpy/renpy/issues/3179
And I want to report some new issues.

It seems that only the "default" font's kerning can work in ren'py. Even if I download the same font (DejaVuSans.ttf) and have the program use it, it won't make kerning work properly.

```
define e = Character("Default Font")
define f = Character("Another DejaVuSans", what_font="fonts/DejaVuSans.ttf")
label start:
    scene bg room
    show eileen happy
    e "ToTeTu"
    f "ToTeTu"
    e "AVAWATA"
    f "AVAWATA"
    return
```
Then it turns out:
![d1](https://user-images.githubusercontent.com/130234013/230728895-b485f67c-bb4e-4cb0-bf02-15980c57ef8b.png)
![a1](https://user-images.githubusercontent.com/130234013/230728908-9f427268-74fa-47a3-ba53-141cec024ed0.png)
![d2](https://user-images.githubusercontent.com/130234013/230728941-6e9bcb39-8a63-44b1-89bb-ead0f921ada6.png)
![a2](https://user-images.githubusercontent.com/130234013/230728952-61f0a714-b990-4c87-b785-4f9d416c8c81.png)
I want to know if the Ren'py supports the kerning feature now, as I am unable to kerning my font in ren'py.

**Comment by renpytom** [comment]
Where did you get the font you're using? It's possible there is some kerning information Ren'Py doesn't understand, or that there is not proper kerning information Ren'Py needs.

**Comment by Envi2023** [comment]
> 

Thank you for your reply! I downloaded another DejaVuSans from https://www.fontsquirrel.com/fonts/dejavu-sans for testing Ren'Py's kerning feature.
However, my goal is to use the font called Imperator from https://www.1001freefonts.com/imperator.font which also doesn't kern properly in Ren'Py.
I've opened both fonts in font editing software and confirmed that they contain kerning information, so I'm not sure where the problem lies.

**Comment by renpytom** [comment]
Can you try the nightly? I did, and I'm seeing the exact same kerning using the DejaVuSans you gave as the one that ships with Ren'Py. 

![image](https://user-images.githubusercontent.com/379804/232338007-bbc844aa-79d9-498e-994a-c916f4d0e711.png)
