### ISSUE TITLE
Steam: ActivateGameOverlayToWebPage and eMode

### ISSUE THREAD

**Issue by Xrisofor** [renpy/renpy#4526]
Hello, I tried to add the steam overlay opening by the link, but after trying to execute RenPy, it gives an error with eMode or with the fact that the argument is incorrectly set

I added the k_EActivateGameOverlayToWebPageMode_Default type to it from steamapi.py , but because of this, it says that the argument type is set incorrectly

``textbutton _("Open Google") action steamapi.SteamFriends().ActivateGameOverlayToWebPage("https://www.google.com/", steamapi.k_EActivateGameOverlayToWebPageMode_Default)`` error ``ArgumentError: argument 2: <class 'TypeError'>: wrong type``

What could be the problem? I tried to do it via _renpysteam.activate_overlay_to_web_page, but it already asks for a mode that is not initially set in 00steam.rpy

I am using the 8 renpy nightly build from April 6th

**Comment by renpytom** [comment]
The problem is with the url - the underlying call takes bytes, not string.
