### ISSUE TITLE
About Python 3.9 - 3.11....

### ISSUE THREAD

**Issue by Senyu** [renpy/renpy#4528]
> [renpytom](https://github.com/renpytom)
> Fundamentally, yes.
> 
> Moving to Python 3.11 will mean dropping support for Window 7, so I'm keeping an eye on statistics for Windows 7 usage to help inform when we switch.

_Originally posted by @renpytom in https://github.com/renpy/renpy/issues/4521#issuecomment-1500311443_

![wefwf](https://user-images.githubusercontent.com/75548744/231028654-1166cf58-bc3e-427c-a3f4-93cb22a49497.png)

Actually Python 3.9 to 3.11 can be run without problems on Windows 7, as long as have "api-ms-win-core-path-l1-1-0.dll":
https://github.com/nalexandru/api-ms-win-core-path-HACK

The problem is that the python developers, added a lock on the Python 3.9 to 3.11 installer so it won't install on windows 7 and don't want to add the api-ms-win-core-path-l1-1-0-0.dll and don't want to support Win7 it anymore... Even if Python 3.9 or above is still supported.
https://discuss.python.org/t/windows-7-support-for-python-3-9-or-3-10-without-a-fork/13842

Same thing with OBS Studio 29 in which you just have to add some missing code (I will not say here) in the *.dll to run on Win7. The funny thing is when I saw some random guy on the internet modify Chrome 112 which doesn't support Win7 and getting it to work in Win7 was funny. 😂

Some software/game developers have been blocking the executable (.exe) or the code script, from running on win7 which is sad, but if it is removed by someone it works again.

It's strange this crazy logic that the devs have been following based on microsoft... What I mean is that as long as DirectX 11/OpenGL/Vulkan is still used for many programs and games the win7 support will not end, it's only going to end for those who want to live in the illusion that it's over even if it isn't... even more after microsoft did this:
https://github.com/microsoft/DirectX-Specs/blob/master/d3d/D3D12onWin7.md

Blame or thank blizzard for that, after all it was blizzard that managed to convince Microsoft to create a version of DirectX 12 for Windows 7 for its World of Warcraft player base, and in doing so opened doors for modder/programmers/devs... etc.

Of course I am not saying that Renpytom has to continue Win7 support, but it is undeniable from what I have seen on internet forums that some people will modify the X program/game and return Win7 support (I think Microsoft's biggest fear is that Win7 will be haunting the MS like WinXP was for a few more years, because of its compatibility...)

And we've already lost WinXP support in Ren'Py, it would be sad to lose Win7 support for something forced and it is still compatible with newer versions of Python.

Well, that's for renpytom to decide whether to continue to support it or not bye. 👋

**Comment by renpytom** [comment]
I'm more worried about cpython-mingw, which is what we use for Python on windows, dropping support for Windows 7. (They've said they plan to do that.) 

I'm perfectly fine if people modify things to re-add support for windows 7 - while I'm likely to add a version check, those should be easily bypassable. 

In any case, don't plan to do this until 8.2 at the earliest.
