### ISSUE TITLE
Ctrl and Alt block mouse clicks

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4529]
In the latest (10 April) nightly build if the Ctrl or Alt button is pressed, then buttons and viewports do not respond to clicks and so do mousewheel's rollback/rollforward. Seems like that those two buttons block all mouse events.

**Comment by lauwurence** [comment]
Can't speak for other players and developers but I constantly use Ctrl to skip dialogues and I find it annoying to always unpress Ctrl when I want to make a choice or interact with UI. Using Caps Lock is slower and is not as intuitive as Ctrl.

Is there any possibility that a new config variable that disables mouse modifiers could be added?

**Comment by mal** [comment]
Try using tab to toggle skip on/off rather than having to hold ctrl the whole time, it'll save your fingers and not interfere with clicks.

**Comment by lauwurence** [comment]
@mal, oh sure, I mean Tab instead Caps Lock... Thank you for the example!

But there's another question. Why Shift modifier works in not that strict way? 
If Shift is held then any other key can be detected, while Ctrl and Alt block everything until the exact key is pressed.

```renpy
screen sc_key():
    key 'K_w' action Notify("'W' pressed!")
    key 'mousedown_1' action Notify("Clicked!")

label start:
    call screen sc_key
```

**Comment by renpytom** [comment]
Shift traditionally works differently than other modifiers. It interacts with caps-lock, and only applies to some keys.

**Comment by lauwurence** [comment]
Thanks, @mal! Adding alt and ctrl to mouse inputs is a good idea! https://github.com/renpy/renpy/issues/4529#issuecomment-1504164717

**Comment by renpytom** [comment]
It's a pretty terrible idea, but if you want to do it for your games, that's fine. It's not going to be the default.
