### ISSUE TITLE
Abnormal behaviour after renpy.suspend_rollback()

### ISSUE THREAD

**Issue by Kthunda** [renpy/renpy#4534]
Here my code :

```
label start:
    "" "Start text 1"

    call label_to_call

    "" "Start Text 2"

    return

label label_to_call:
    "" "label Text 1"
    "" "label Text 2"

    $ renpy.suspend_rollback(True)

    "" "label Text 3"

    jump label2


label label2:

    $ renpy.suspend_rollback(False)

    "" "Text 4"

    return
```

If we go until "Text 4" and rollback, it brings us to "label Text 2".
But if we continue until "Start Text 2" and rollback, it brings us to "label Text 3".

Is it a bug or something I missed ?

**Comment by Kthunda** [comment]
Thanks, the bug is now fixed for this case, but not in my code, so I searched a little more and found out that if we just add a label in our label_to_call, after renpy.suspend_rollback(True), the bug reappear ^^'

```
label start:
    "" "Start text 1"

    call label_to_call

    "" "Start Text 2"

    return


label label_to_call:
    "" "label Text 1"
    "" "label Text 2"

    $ renpy.suspend_rollback(True)

    label huh:
        "" "label Text 3"

        jump label2


label label2:

    $ renpy.suspend_rollback(False)

    "" "Text 4"

    return
```

**Comment by renpytom** [comment]
I believe fb803ea solves this one.

**Comment by Kthunda** [comment]
Works like a charm, thank you :)
