### ISSUE TITLE
Expected statement for a dialogue line in Nightly builds

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#4535]
I'm using yesterday's nightly (Ren'Py 7.6.0.23041402+nightly ) and I'm encountering an error I can't explain:

```
File "game/scenes/scene_26.rpy", line 200: expected statement.
    u "... Danya?" id s26_023a
```

Here's the original code:
```
    voice "b26_10"

    u "... Danya?" id s26_023a

    show danya ec pose1 faceleft
    with dissolve

    voice "d26_20"

    d "Yeah, it's me. Who am I speaking to?" id s26_024
```

And here's the "u" character definition:
```
define u =  Character("???", \
            show_namebox_type="unknownname", \
            show_namebox_touch="t_unknownname", \
            ctc="ctc_pic", \
            ctc_position="nestled-close")

define d =  Character(_("Danya"), \
            show_namebox_type="danyaname", \
            show_namebox_touch="t_danyaname", \
            ctc="ctc_pic", \
            ctc_position="nestled-close", \
            voice_tag= "danya")

define r =  Character(_("Riemphea"), \
            show_namebox_type="riempheaname", \
            show_namebox_touch="t_riempheaname", \
            ctc="ctc_pic", \
            ctc_position="nestled-close", \
            voice_tag= "riemphea")

```

I tried various things:
- removing the line ID: still same error
- removing the voice statement: still same error
- removing the entire line: no more error
- changing the "u" character to another defined character: works for "d" and a few others, but not "r" for some reason (see character definition above).

Is it a Ren'py bug or something I can fix on my side?

**Comment by Gouvernathor** [comment]
It's because `u"Hello"` is a thing in python. u tells the string is unicode, r or R that it's raw, and b that it's a bytestring. The renpy parser now reads the u as well as the quoted part following it as one python expression (the name of the speaking character), instead of one being the speaker and the other a renpy-string (yes, strings in renpy are parsed slightly differently than in pure python).
This is likely due to dffbe3521cd9fcab8df774571dd7b686fd2cd01d.

**Comment by marchare555** [comment]
> It's because `u"Hello"` is a thing in python. u tells the string is unicode, r or R that it's raw, and b that it's a bytestring. The renpy parser now reads the u as well as the quoted part following it as one python expression (the name of the speaking character), instead of one being the speaker and the other a renpy-string (yes, strings in renpy are parsed slightly differently than in pure python). This is likely due to [dffbe35](https://github.com/renpy/renpy/commit/dffbe3521cd9fcab8df774571dd7b686fd2cd01d).

I changed the "u" character to "un" and the "r" character to "rem" and now the error no longer appears. Thanks!

I actually have a "b" character and that one didn't cause any bug.

**Comment by renpytom** [comment]
That wasn't intended, obviously. Let me fix it.
