### ISSUE TITLE
Save Profile

### ISSUE THREAD

**Issue by N0lla** [renpy/renpy#4539]
This is more of a suggestion than a bug.

Is it possible to have as a top level a profile - so all the saves go under that. Doing this would allow the player to go after certain other character and get all the events covered. Also, it would be easier to track progress - when major decisions need to be made.

I believe this would be pretty easy to impliment, as you could assign the save profile name at the begining of the file name. The only thing would have to be changing the engine and UI to accommodate.

**Comment by N0lla** [comment]
This is in addition to the save name that you can add.

**Comment by mal** [comment]
This sounds like it would be satisfied by the new `config.file_slotname_callback` forthcoming in 7.6/8.1, which allows save files to be given creator (and by extension, player) controlled prefixes, allowing them to be grouped into something akin to the profiles outlined here.

> The new [config.file_slotname_callback](https://nightly.renpy.org/doc/config.html#var-config.file_slotname_callback) variable allows the developer to customize how file slot names are generated. One application of this is allow the developer to apply a prefix to save slots (for example, to select between dlc and non-dlc saves). The new autosave_prefix_callback allows a similar prefix to be given to autosaves.
**~** https://nightly.renpy.org/doc/changelog.html#new-features

**Comment by renpytom** [comment]
@mal Is right - config.file_slotname_callback is meant to solve this.
