### ISSUE TITLE
Dual Monitor Issue

### ISSUE THREAD

**Issue by N0lla** [renpy/renpy#4540]
I have a dual monitor and when I leave them and the monitors switch off after 5 minutes. When I return and the monitors switch back on the game doesnt seem to know what monitor to display to. It will switch between each monitor and makes saving the game really difficult. The only way to rectify the problem is to exit the game and restart - but if you havent been able to save your game this causes an issue.

**Comment by Gouvernathor** [comment]
I'm on Win10 with a double screen since a long time and never had that problem. What OS are you on ?

**Comment by N0lla** [comment]
windows 10.

Also, running displayfusion - so might be an issue with that software?

**Comment by N0lla** [comment]
It only happens when the screens go into sleep mode. Otherwise its fine

**Comment by danac78** [comment]
You might also want to check your video drivers as well. If they are acting in bizarre manner, it will affect how the system behaves when it wakes up (including Renpy if it is using either OpenGL or GL2).

**Comment by renpytom** [comment]
I don't think this is likely to be a Ren'Py problem, given the non-os software in use.
