### ISSUE TITLE
Android 12 Game Crashing

### ISSUE THREAD

**Issue by LordOfTurk** [renpy/renpy#4542]
Hello, my phone is android 12 and unfortunately the games are constantly crashing, I have been trying to solve the problem for almost 1 week but I could not solve it unfortunately. How can I solve this problem or should I just wait for the new version of Renpy? I checked the log file of the game but I can't say that I understand much, I didn't see any errors in the log but still the game crashes.
[log.txt](https://github.com/renpy/renpy/files/11271314/log.txt)

**Comment by Org-gith** [comment]
The soc in the log is 9 years old, hhave you an android 12 phone more recent that you can borrow to someone to test if it still crashes on it.

**Comment by LordOfTurk** [comment]
> Günlükteki gpu 9 yaşında, hala üzerinde çöküp çökmediğini test etmek için birinden ödünç alabileceğiniz daha güçlü bir android 12 telefonunuz var.
> 
> Edit: İşte bu gpu'da çöken birlik oyunları hakkında alakalı olabilecek bazı bilgiler, https://stackoverflow.com/questions/74413455/unity-android-a-lot-of-crashes-on-devices-with-powervr-gpu

Unfortunately not, so is there no other solution? I just bought the phone and I never thought I would have such a problem. I wish I had saved my money and bought a better phone. :/

**Comment by Org-gith** [comment]
I'm just interested in this issue and it's kind of baffling they would use a 9 years old gpu (that has problems) in a 2022 device. I was suggesting to test on another android 12 phone that is a bit better to see if the problem was still there, because this can be good information.
As for possible solutions and going indepth, only Tom can tell, so wait and see.

**Comment by LordOfTurk** [comment]
> I'm just an user interested in this issue and it's kind of baffling they would use a 9 years old gpu (that has problems) in a 2022 device. I was suggesting to test on another android 12 phone that is a bit better to see if the problem was still there, because this can be good information. As for possible solutions and going indepth, only Tom can tell, so wait and see.

It did not occur to me that they could use such an old gpu in a new model phone, the price was affordable and the features were not bad, so I chose it for this reason, but now I am not a little regretful. I wish I had another Android 12 phone to try, but unfortunately I don't. :(

**Comment by renpytom** [comment]
I would try 8.1, which has a number of android fixes, though it's hard know if one of them fixed the problem.

**Comment by LordOfTurk** [comment]
> I would try 8.1, which has a number of android fixes, though it's hard know if one of them fixed the problem.

Thank you, I hope the problem will be solved.
