### ISSUE TITLE
config.quadratic_volume is not a known configuration variable.

### ISSUE THREAD

**Issue by Belgerum** [renpy/renpy#4554]
Looking at the Incompatible changes list for prerelease 8.1.0 ( [https://www.renpy.org/dev-doc/html/incompatible.html](https://www.renpy.org/dev-doc/html/incompatible.html) ) I saw the mixer section mention that the new mixer volume behavior can be reverted with `define config.quadratic_volume = True` .

Attempting to put this line of code in any renpy game I have immediately results in a traceback on launching the game:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/options.rpy", line 57, in script
    define config.quadratic_volume = True
  File "game/script/options.rpy", line 57, in script
    define config.quadratic_volume = True
  File "renpy/common/000namespaces.rpy", line 33, in set
    setattr(self.nso, name, value)
Exception: config.quadratic_volume is not a known configuration variable.
```

A quick search through the files in renpy/common reveals two very similar variables being used, `config.quadratic_volume` in 00voice.rpy and `config.quadratic_volumes` in 00defaults.rpy and 00compat.rpy , with the only difference being an 's' on the end. Is this a typo?

**Comment by renpytom** [comment]
Fixed. 

Offhand, why would you want to set this? I think the new behavior is strictly better.

**Comment by mal** [comment]
Still needs to be updated here I believe:
https://github.com/renpy/renpy/blob/4613ee1fa49f5853c9bcecc9b1ec6589d58366e1/renpy/common/00voice.rpy#L186

**Comment by Belgerum** [comment]
> Offhand, why would you want to set this? I think the new behavior is strictly better.

I've coded my settings UI to have numeric values next to the sliders. The new behavior causes the values to be exponential rather than linear, which does not feel right at all. 50% volume is now on the far right side of the bar, and the entire left side is less than 2%. This contrasts the linear values of the Text speed and Auto-forward time sliders, too.
![image](https://user-images.githubusercontent.com/6981764/233903485-7c2b297e-d20f-4917-a221-654ecf61109a.png)

**Comment by lauwurence** [comment]
I talked about almost the same issue here: https://github.com/renpy/renpy/pull/4165#issuecomment-1399554657
I checked such games as Cyberpunk 2077, Civilization and I didn't notice them using decibels over the linear values.

**Comment by Belgerum** [comment]
You'll probably also want to update the Incompatible changes list to use `config.quadratic_volumes` rather than `config.quadratic_volume` if that's the name you're going with.

**Comment by Org-gith** [comment]
I think both options are respectable/good, it's probably a taste thing, I did notice when launching Ren'py for the first time, that the sound slider did almost nothing unless you were really reaching the extremities of the slider. This was an 'innocent' reaction, so I probably had encountered games that had logarithmic sliders if that's something that I sort of noticed right away. Overall it seems like someone might prefer or not depending on his own taste and habit.
