### ISSUE TITLE
Request: Automatic way to add identifiers to dialogue

### ISSUE THREAD

**Issue by Belgerum** [renpy/renpy#4558]
For context, I'm currently going through the process of preparing a game for release, which has me polishing the game's script while organizing translations into a number of languages beyond English. I am simultaneously playtesting to fix typos and grammar issues in my English script while also being sent files of translated versions of lines, and the ability to manually add an ID to a dialogue line has been a godsend, since it allows me to preserve all of the translated versions of a line while still being able to edit the original text to fix issues, or add additional elements like bold, italics, or other tags.

If possible, I'd love if Ren'Py could add some kind of option to add manual identifiers to all dialogue in the game, similar to the function which adds `from` clauses to calls. This would be useful for managing translations, and probably also for other things like auto-voicing, which uses the same identifiers.

For clarity, I'm hoping to have the option to automatically turn this...
```
label storyscene:
Fred "How do you turn soup into gold?"
Joe "I don't know."
Fred "You just add 24 carrots!"
```

...into this.
```
label storyscene:
Fred "How do you turn soup into gold?" id storyscene_a55204a8
Joe "I don't know." id storyscene_0e9e6351
Fred "You just add 24 carrots!" id storyscene_233c57c0
```

**Comment by Gouvernathor** [comment]
Already asked in #4156, which mentions a way to do it yourself I think.

**Comment by renpytom** [comment]
Closing as duplicate.
