### ISSUE TITLE
Default Layer/Camera Transforms / Full Screen Transforms

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#4562]
I've implemented this in my own game, but I think many people would find it useful.
Being able to set a "default" transform for a layer is very useful, OR a transform that is applied to every layer, regardless of other transforms. As the game currently is, I would need to re-set the default transform every time the scene reset, or run the risk of accidentally replacing the transform on the layer. 

Why do I want to do this? I have a custom transform that makes uses of shaders that I want to be able to toggle on and off in the settings, meaning that I ALWAYS want the transform applied:

I've probably not implemented it the best way, because I was just futzing around until I got it to work, but here's how I did it:

    default_at_list = {
        "screens":[FullScreenTransform]
        }

    always_at_list = {
        "master":[FullScreenTransform]
    }

    def screenshader_set_layer_at_list(self, layer, at_list, reset=True, camera=False):
        global always_at_list
        layer_at_list = list(at_list)
        if (layer in always_at_list):
            layer_at_list.append(*list(always_at_list[layer]))
            
        if camera:
            self.camera_list[layer] = (None, list(layer_at_list))
        else:
            self.layer_at_list[layer] = (None, list(layer_at_list))

        if reset:
            self.layer_transform[layer] = None

    renpy.display.core.SceneLists.set_layer_at_list = screenshader_set_layer_at_list

    

    def screenshader_clear(self, layer, hide=False):
            global default_at_list
            if layer not in self.layers:
                return

            if not hide:
                self.layers[layer][:] = [ ]

            else:

                # Have to iterate in reverse order, since otherwise
                # the indexes might change.
                for i in range(len(self.layers[layer]) - 1, -1, -1):
                    self.hide_or_replace(layer, i, hide)

            self.at_list[layer].clear()
            self.sticky_tags = {k: v for k, v in self.sticky_tags.items() if v != layer}

            self.shown.predict_scene(layer)

            if renpy.config.scene_clears_layer_at_list:
                layer_at_list = []
                if layer in renpy.store.default_at_list:
                    layer_at_list = renpy.store.default_at_list[layer]
                self.layer_at_list[layer] = (None, layer_at_list)

    renpy.display.core.SceneLists.clear = screenshader_clear

Also for applying a full screen transform to everything:

    renpy.store.screen_transform = FullScreenShader

    def draw_screen(self, root_widget, fullscreen_video, draw):
        try:
            renpy.display.render.per_frame = True
            renpy.display.screen.per_frame()
        finally:
            renpy.display.render.per_frame = False
        
        surftree = renpy.display.render.render_screen(
            root_widget,
            renpy.config.screen_width,
            renpy.config.screen_height,
            )

        if draw:
            renpy.display.draw.draw_screen(surftree)

        if renpy.emscripten:
            emscripten.sleep(0)

        now = time.time()

        self.frame_times.append(now)

        while (now - self.frame_times[0]) > renpy.config.performance_window:
            self.frame_times.pop(0)

        renpy.display.render.mark_sweep()
        renpy.display.focus.take_focuses()

        self.surftree = surftree
        self.fullscreen_video = fullscreen_video

        if self.first_frame:
            self.after_first_frame()
            self.first_frame = False

    def shader_draw_screen(self, root_widget, fullscreen_video, draw):
        if renpy.store.screen_transform:
            root_widget = renpy.store.screen_transform(root_widget)
        return draw_screen(self,root_widget, fullscreen_video, draw)
    renpy.display.core.Interface.draw_screen = shader_draw_screen 

I'm certain the implementation I did will definitely break because I don't fully understand the engines flow.

Figured this would be a nice feature to have in Ren'py, implemented correctly.

**Comment by mal** [comment]
Have you tried using the `camera` statement? It works very similarly to `show layer at` however it is not reset by `scene` statements.

**Comment by colinharvie** [comment]
I have. I am almost exclusively using the camera statement since I'm using the 3d stage for my VN, however I ran into 2 issues:

1. If I provided some custom transforms like so:
```
camera at FullscreenTransform
    "Stuff"
    camera:
        xpos 0.5 ypos 0.25 
```
The FullscreenTransform would be removed upon the second camera statement. I'm not sure if this is intended behavior or not, I got a little confused by the documentation in this area.

2. If I ever wrote:
`camera at reset`
Or something similar, the initial FullscreenTransform would be replaced, and I'd always have to reapply it.

**Comment by renpytom** [comment]
I don't really understand what semantics you want. The way Ren'Py works, if you give a specific transform, you'd have to apply it every time the camera changes.

**Comment by colinharvie** [comment]
Here's my use case:
I have a shader (apply's some bloom, vignette, and light gradient) to the entire screen (or, in this case, to the entire "master" layer.) I want this shader to ALWAYS be applied. Since it's a screen shader, to be applied to the whole layer, I want it always applied. If I have to re-apply it every single camera statement (I have a camera statement roughly every 5 lines), it be comes a real pain.

What I've done is created a variable What I want to do is have a variable defined `default_at_list` and `always_at_list`, which defines a list of transforms to be applied when layers are cleared of their at_list, or appended when they are adding a new at list

I then altered altering the following 2 methods to apply those transforms when they are called (see first post):
`renpy.display.core.SceneLists.set_layer_at_list`
`renpy.display.core.SceneLists.clear`

This way, the transforms I've set are always applied, even when cleared.

Additionally, I altered `renpy.display.core.Interface.draw_screen` to wrap the `root_widget` with a displayable set in the variable `screen_transform`.

My specific use case here is that I have a VHS screen shader that creates a Fast Forward effect, which is applied over the entire rendered image, whenever `renpy.is_skipping()` is true.

Does my explanation make sense?

**Comment by renpytom** [comment]
Do you ever need to not set the shader on a layer? I'm wondering if it might make sense to simply have config.layer_transforms, that just applies an at_list to each layer after the usual at_list and camera.

**Comment by colinharvie** [comment]
That's exactly the sort of thing I was thinking!

I'm currently applying the shader with a custom displayable, so when I need to turn it off, I just set the variable and when it goes to render, it just doesn't apply the shader, but I imagine it'd be much easier to just change `config.layer_transforms` to remove it. 

Additionally, having something like `config.root_transform` which applies ot the `root_widget` in `renpy.display.core.Interface.draw_screen` before rendering would be nice as well, for things that need to be applied to the entire screen, not just specific layers.

**Comment by Gouvernathor** [comment]
You can't change config variables at runtime, they are supposed to be constants. That is, it may or may not work in practice concerning various config variables, and it may get broken without warning.
If you want the transforms to be togglable, Tom's idea is probably not the solution for you.

**Comment by colinharvie** [comment]
In that case, perhaps it would be better to have a store variable then? Or a store variable that is used in lieu of the config variable if it exists? Or make the config either a dict or a Callable that returns a dict?

At this point it really gets down to what's the most versatile for people to use. My use case is a custom displayable:

    class ScreenShader(renpy.display.transform.Transform):
        def __init__(self,child,**kwargs):
            super(ScreenShader,self).__init__(child,**kwargs)
            self.child = child;

        def visit(self):
            return [self.child]
        
        def event(self,ev,x,y,st):
            return self.child.event(ev,x,y,st)

        def _render(self,width,height,st,at):
            return self.child.render(width,height,st,at)

        def _modify_render(self,rv):
            return rv 

        def render(self,width,height,st,at):
            rv = self._render(width,height,st,at)
            rv = self._modify_render(rv)
            return rv

    class VCRScreenShader(ScreenShader):

        def _render(self,width,height,st,at):
            child = self.child
            if (renpy.is_skipping() and store._skipping and renpy.config.skipping and store._menu is False):
                child = Transform(child,matrixcolor=SaturationMatrix(0.2),shader="vhs", mesh=True,perspective=True)
            rv = child.render(width,height,st,at)#renpy.render(self.child, width, height, st, at)
            return rv
            
    renpy.store.screen_transform = VCRScreenShader

It handles whether or not it displays inside it's render method, so I personally don't NEED to change or disable the transforms that are being applied, but I can see where other users might, either because they don't want to use around with custom displayable, or what to do something fancy that hasn't occurred to me yet.

**Comment by Gouvernathor** [comment]
I think there's a clear choice to be made : either you want the transform to be toggleable, that is, to be applied and taken away at arbitrary time. In that case, the `camera` statement is just what you need : yes, you need to reapply your transform every time you use the camera statement for another transform, but if it didn't flush the former transform, how would you ever stop applying it ?

Or, you want something constant, and in that case the way of a config variable is probably what we should do. But in that case, you can't change your mind during game execution, it is that transform, always.

Trying to find a middle ground between these two would yield a complex system where all the transforms you apply to a layer are subject to change, but they are spread into classes with different rules about how that change is made and under which circumstances it is permitted. That seems very counter-intuitive to me.

**Comment by renpytom** [comment]
What are you doing that has a camera statement every 5 lines or so?

**Comment by colinharvie** [comment]
Here, this video shows it better than I can explain it with words:
https://www.dropbox.com/s/s8zamrnak1ugws1/vaygren_draft_sample.mp4?dl=0

I've got a camera statement every 5 lines because my whole visual novel has different visuals and camera angles every 5 lines, created out of sprites and various background elements. 

On top of everything, I have a Transform I apply that contains shades (vignette, bloom, lighting, etc), which I can toggle on and off in the settings, so setting the "default" transforms (or a transform applied on top of everything every time) in a config would work just fine for my purposes (the class I have handles whether or not it applies the shader based on the preferences, I don't need to add and remove the transform).

**Comment by birctreel** [comment]
Hello colinharvie, thank you for sharing your code and preview of your game, it looks so fascinating and gorgerous!
May I ask for some help, if you are willing to listen?
I have a similar ambition to apply a crt shader to my master layer (in fact it would be perfect it I can apply to all the layer), and I want to try your code for that. However, there is a problem that always come:
`    renpy.display.draw.draw_screen(surftree)
Exception: Shader ('renpy.geometry', 'renpy.solid', 'shader.background') has not been given uniform tex0.`

the shader.background is the shader I defined.
I wonder if you've ever came with the same problem, and maybe you would know how to avoid this?

Thank you so much for reading this! Your idea is really helpful!

**Comment by Gouvernathor** [comment]
Your issue is unrelated to this issue's subject, and also, Github is there for bugs or improvements to bring to the engine itself.
If you need help using it, or creating your game, use the help channel of the official discord server at https://discord.gg/6dkxWYm or the LemmaSoft forums.
