### ISSUE TITLE
Text never updates after screen replace?

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4563]
![image](https://user-images.githubusercontent.com/46109734/233867608-d945a642-c4ea-4365-8af4-8fed48d59d06.png)
![image](https://user-images.githubusercontent.com/46109734/233867625-78ad8d27-bb18-4b94-8fd1-593af33b69e9.png)

1. Open the launcher.
2. Click the "preferences" button and then "Return".
3. Try to select any project.

The selected project's name remains the same.

**Comment by Gouvernathor** [comment]
df524315a8e281be385cbbb12ef9bac5951ce354 is the culprit
