### ISSUE TITLE
new style property `sizeof` for boxes?

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#4566]
_that or a more general `width_of` / `height_of` for containers, idk_

the idea would be to have a way of setting the width (vbox) or height (hbox) to one of its children's.
it would enable properly placing displayables relative to this displayable's width (or height).

take a look at this:
![image](https://user-images.githubusercontent.com/101005497/233881447-484787a6-2e70-4e33-82d6-c4d629ca4206.png)
_yes this is a ddlc mod please don't hit me_

it works, but the code is kinda spaghetti.
not precise enough and if the `UNDERCURRENTS` text changes, the layout would break.

with what im proposing, one would be able to use `xalign 1.0` for the text `01/16` and `xsize 1.0` for the underline (it's a `Solid`), cause if i try doing that... well
![screenshot0004](https://user-images.githubusercontent.com/101005497/233881751-2a7cc5d4-4f71-4859-8fb9-5b8dc8a08e2f.png)
i get this absolute hell

**Comment by renpytom** [comment]
I think you're basically looking for fixed with fit_first True.

**Comment by Elckarow** [comment]
doesn't work at all
```rpy
screen test():
    add "#fdfdfd"

    fixed fit_first True:
        text "DOKI DOKI" style "under_light"
        text "01/16" style "under_light" xalign 1.0

        frame ypos 20:
            background Solid("#121212", ysize=2, xsize=1.0, yalign=1.0)
            text "UNDERCURRENTS" style "under_text"
```
_this is the closest i got to something working_

a few problems. first of all... well
![image](https://user-images.githubusercontent.com/101005497/234000547-6751c0d0-dba7-4200-ac93-41552ffe3e16.png)
_right?_
using a `frame style "empty"` as you said breaks it even more (the `"01/16"` text doesn't care about the `fixed` and goes to the right side of the screen).

secondly, even if it did work, i don't like having to manually position the `frame` containing the text `"UNDERCURRENTS"`. so i put everything inside a `vbox`, _which fucks things up even more_: no way (from what i tested) of having the two texts `"DOKI DOKI"` and `"01/16"` at the same height and properly placed. removing the `"01/16"` text is an option to make it work but... yknow? it's not something i wanna do

**Comment by mal** [comment]
This seems to do what you're looking for using the `fit_first` approach suggested:
```rpy
    frame:
        align (.5, .5)
        background "#fdfdfd"

        has fixed
        fit_first True

        vbox:
            text "DOKI DOKI" color "000" size 20
            text "UNDERCURRENTS" color "000" size 60

        add Solid("#121212", ysize=2, xfill=True, yalign=1.0)
        text "01/16" color "000" size 20 xalign 1.0
```
Obviously you may need to play around a little with spacing a margins, but it should hold up.

**Comment by renpytom** [comment]
@mal Has it. 

I'm pretty sure this is exactly what is wanted.

**Comment by Elckarow** [comment]
yep. seems to be working good 👍 
thank you
