### ISSUE TITLE
`radius` atl property not working properly with `int`s and `absolute`s

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#4574]
```rpy
label main_menu:
    return

screen test():
    add "#fdfdfd"

    add "#000":
        at transform:
            subpixel True xysize (50, 50)
            around (0.5, 0.5) angle 45 radius 100

label start:
    call screen test
```
the square does not show up.
using a float does work

**Comment by mal** [comment]
Code appears to always expect and treat radius values as floats. Unclear, but possibly by design. One for Tom.
https://github.com/renpy/renpy/blob/f65c1a1af3300a9f9af3876ef034f0c0d200f62d/renpy/display/transform.py#L1114
