### ISSUE TITLE
SVG image doesn't render

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#4577]
Hi,
I was attempting to utilize the new SVG support feature, but unfortunately, I'm unable to view the rendered image.

Code (testing in The Question):
```py
image pink_idle = Transform("images/pink_idle.svg", size=(100, 100))

# The game starts here.
label start:

    # Start by playing some music.
    play music "illurock.opus"

    scene bg lecturehall
    with fade

    "It's only when I hear the sounds of shuffling feet and supplies being put away that I realize that the lecture's over."

    show pink_idle
```

SVG:
![pink_idle](https://user-images.githubusercontent.com/26691547/234437790-0eeefd38-9213-4fc6-a298-0bf65ef66be3.svg)

Additional Info:
- Image name shows up in "Image Attributes" and the file shows up in "Filename List" (Developer Menu)
- No error shows up in game or lint
- SVG was exported from Figma - not sure if that makes a difference
- I have tried the image definition without a Transform() method: `image pink_idle = "images/pink_idle.svg"`

**Comment by renpytom** [comment]
It looks like you're using an SVG that contains features that nanosvg does not support. SVG 1.0 features, that aren't supported. 

You can check out https://core.tcl-lang.org/tips/doc/trunk/tip/507.md , which uses the same library, and has a list of the features that _are_ supported.
