### ISSUE TITLE
Children of Buttons having Individual Transforms on Them

### ISSUE THREAD

**Issue by negatwo** [renpy/renpy#4578]
When writing logic that requires the children of a button to behave in a way different than the transform on the button itself, is there any way to 'transmit' the hover and idle events to its children? 

I've tried different implementations involving a variable that's used as an argument in the transforms that's set by the hovered and unhovered actions (i.e. SetScreenVariable) but that ends up resetting all animations because of something to do with the timebase.

Below is some example code I wrote up trying to explain what I mean:
```
transform main_trans:
    on hover:
        alpha 1.0
    on idle:
        alpha 0.0

transform child_trans:
    on hover:
        xoffset 50
    on idle:
        xoffset 0

transform child_trans2:
    on hover:
        xoffset -50
    on idle:
        xoffset 0

button at main_trans:
    text "hello"
    vbox:
        add "image.png" at child_trans
        add "image2.png" at child_trans2
    action ActionHere()
```

**Comment by Elckarow** [comment]
may be related to #4571 ?

**Comment by renpytom** [comment]
This isn't a bug at the moment. Right now, transforms only work if they are on the outside or directly inside the button. They don't propagate through displayables. 

It might make sense to change that going forwards, just for hover and idle, but this is going to be an 8.2 thing.
