### ISSUE TITLE
[8.1/7.6] The need for a new approach to 'secure save files' in Steam Cloud

### ISSUE THREAD

**Issue by stunnings** [renpy/renpy#4579]
Steam supports Steam Cloud. Steam Cloud is a feature that saves your game's save file on Steam each time you exit the game, allowing you to uninstall and reinstall the game and keep your save file intact, or provide a synchronized save file experience on any PC.

Traditionally, my games have utilized Steam Cloud by specifying the save path as the Steam Cloud path (e.g. Windows: `%APPDATA%/RenPy/game_directory`, macOS:`~/Library/RenPy/game_directory`, Linux:`~/.renpy/game_directory`). This is known as the Steam Auto-Cloud method.

However, with Ren'py 8.1/7.6 and later enforcing tokens that are tied to the PC, I think this method can get a little tricky.
This means we need a new way to support Steam Cloud without sacrificing security.

One possible way is for Ren'py to directly support the Steam Cloud API. For more information, please refer to the following documentation This document also includes a description of the Steam Auto-Cloud method, which we've traditionally used by manually specifying a path.
https://partner.steamgames.com/doc/features/cloud#5

Another possible solution is to use a "game-specific token".
This method may not be as secure as using a unique token for each computer, but it’s still reasonably safe. A truly malicious person could reverse-engineer the game’s source code, find out the game-specific token, and craft a harmful save file. But that would require a lot of effort and skill for each game. If someone is that malicious and capable, they would probably target user's PC directly instead of messing with save files.

This issue is important, and I'd be happy to see it fixed before Ren'py 8.1 is released. I hope you will consider my suggestions, or any other alternatives, to address this problem. Thank you for your hard work and dedication.

**Comment by renpytom** [comment]
How is this different than the 8.1 token method? The user will get the warning the first time they load a game from the older computer, and then can choose to accept that computer.
