### ISSUE TITLE
"this file contains unreachable statements" when using ''' comments while sing lint

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#4587]
I'm using Ren'Py 7.6.0.23042213.

When checking the script with lint, it appears that all code that is commented between two ''' will earn me a warning message such as this one:
```
game/sprites.rpy : this file contains unreachable statements at lines 1, 9, 14, 227, 674, 897, 1248, 1251, 1324, and others.
```

Example of code that gives this warning:
```
""" 
NOTES
k = knee up - the smallest sprite size
w = waist up - mid size
b = bust up - biggest size, can only show 1 character

pose1s, pose2s = sick variant for Brahve
"""
```

These warnings aren't particularly useful, so I guess these could be excluded from link checking.

**Comment by mal** [comment]
Assuming the line is meant to be a comment, then starting the line with `#` character should resolve this. The warning probably does make sense to keep as it could conceivably be a narrator say statement that has been accidentality left out of a label.

**Comment by marchare555** [comment]
> Loose strings are [not comments](https://www.renpy.org/doc/html/language_basics.html#comments) in RPY files. Starting the line with a `#` character to denote it as an actual comment should resolve this. The warning probably does make sense to keep as it could conceivably be a narrator say statement that has been accidentality left out of a label.
Placing triple quotes before and after a piece of code comments it, but unlike # you can do it across multiple lines. I updated my example to better convey this.

Here's some quick documentation about it: [https://www.w3schools.com/python/python_comments.asp](https://www.w3schools.com/python/python_comments.asp)

**Comment by Booplicate** [comment]
Python doesn't have multiline comments, you're actually creating a string and using it as a comment. Furthermore, RenPy has its own syntax, it's not Python, so you can't apply that logic to RenPy script.

**Comment by Gouvernathor** [comment]
Yep, this is intended behavior. I had that in the script when I tested an earlier version of reachability analysis.
Even in python it's not a multiline comment, it has effects on AST and at execution time. And as Boop said, it's even more true in renpy code.

**Comment by marchare555** [comment]
My mistake then! I'll close this case.
