### ISSUE TITLE
RenPy 8.0.3 deployment won't launch on Steam Deck

### ISSUE THREAD

**Issue by shenyi216** [renpy/renpy#4588]
Hello,
I developed and deployed my game with RenPy 8.0.3, and uploaded it to Steam. It can launch on Windows and Mac with no issues, but not Steam Deck. When I tried to play it on Steam Deck, it only shown the Steam logo splash screen for 1-2 seconds and crashed without even showing any errors. I uninstalled and reinstalled the game a few times, but didn't get any luck. I searched here and found [a similar issue](https://github.com/renpy/renpy/issues/4270), but the solution didn't work for me.

I switched to the Desktop mode, but still can't play it via the Steam app.

**Comment by renpytom** [comment]
Can you try with the 8.1 prerelease, to see if there is a fix there already? 

Otherwise, please send a steam code to renpytom@gmail.com, I'll install it on my deck, and see what the cause is.

**Comment by shenyi216** [comment]
Thanks so much for your prompt reply! Just sent the key to your email.
I created a sample game and deployed it via 8.1, but it still won't launch on Steam Deck.

**Comment by renpytom** [comment]
It looks like either there isn't a Linux launch configuration, or it's set wrong. I'm showing that when I launch the game on Linux, it runs: 

/home/tom/.local/share/Steam/steamapps/common/Thesis of Love/Test.exe

You almost certainly want to change that to Test.sh for the Linux version. 

There's a good guide here: https://docs.google.com/document/d/1La4Pg72Wzpo1cPFFPk_g8Wjkl-MwLG2Qunwu65Ovl5w/edit . Check the "Build configurations" section, and it will tell you how to make things work on Mac and Linux + Steam OS.

**Comment by shenyi216** [comment]
Thanks so much for digging into this!! I changed the Linux executable to Test.sh and it runs perfectly now!!

The doc is extremely helpful to me! I'll go through these steps. Closing this issue now.
