### ISSUE TITLE
`if` statement doesn't work until `restart_interaction`

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4591]
Everything that is inside `if` statement in screens is not updated/triggered until a manual `renpy.restart_interaction` is performed.
Might be related to https://github.com/renpy/renpy/issues/4559 because window resizing does restart interaction.

~~Here's an example of the code where image is supposed to be changing depending on the mouse position:~~ _(See the comment next to **Mr. mal**)_

<details>
  <summary>Example Code</summary>

```renpy
screen sc_test():

    python:
        x, y = renpy.get_mouse_pos()

        if x < (1920 / 2):
            img = 'bubble'
        else:
            img = 'window_icon'

    if img == 'bubble':
        image "gui/bubble.png":
            align (.5, .5)
    else:
        image "gui/window_icon.png":
            align (.5, .5)

    key 'dismiss' action Function(renpy.restart_interaction)


label start:
    call screen sc_test
    return
 ```
 
 Timers like these also do not work until restart interaction:
```renpy
if img == 'bubble':
    timer .1 action Notify("Is bubble image!")
else:
    timer .1 action Notify("Is window_icon image!")
```
</details>

~~Is this a new intended behavior where every change have to be done through restarting interaction?~~

**Ren'Py 8.1 Prerelease May 2**

**Comment by mal** [comment]
This works the same way as in 8.0.3 and prior, and so isn't a regression.

The correct way to implement the behaviour in your example would be to use the `mousearea` widget with actions:
```rpy
screen sc_test():
    default img = "window_icon"

    mousearea:
        area (0.5, 0.0, 1.0, 1.0)
        hovered SetScreenVariable("img", "bubble")
        unhovered SetScreenVariable("img", "window_icon")

    if img == "bubble":
        image "gui/bubble.png":
            align (.5, .5)
    else:
        image "gui/window_icon.png":
            align (.5, .5)
```

**Comment by lauwurence** [comment]
Oh, sure it doesn't work! My bad! I was too confident about the example code.

Here's another one with the screen added to `config.per_frame_screens`. Try following these steps:
1. Scroll down until the "Scroll Down" buttons disappear.
2. Scroll up until the buttons appear.
3. Try to click on the "Scroll Down (if)" button.
4. As a result it can't be triggered even though it's shown.
5. Click the `W` key to trigger `renpy.renstart_interaction` and then try again clicking the "Scroll Down (if)" button.
6. Now it works.

<details>
  <summary>Example Code 2.0</summary>
  
```renpy
init python:
    config.per_frame_screens.append('sc_messenger')

screen sc_messenger():

    frame:
        background Solid("#fffb")
        align (.5, .5)

        viewport id 'viewport_messages':
            xsize 400
            ysize 600

            draggable True
            mousewheel True

            has vbox
            xfill True
            spacing 10

            for i in range(20):
                text "Message [i]"

    # Detect when we hit the bottom of the viewport and then show or hide the "Scroll Down" button:
    python:
        d = renpy.get_widget(None, 'viewport_messages')
        if d is not None:
            show_the_button = d.yadjustment.value < d.yadjustment.range
        else:
            show_the_button = True

    text "show_the_button: [show_the_button]":
        align (.5, .9)
        size 18

    if show_the_button:
        button:
            at tr_scroll_down()
            pos (800, 890)
            action Scroll('viewport_messages', 'vertical increase', 1000)
            text "Scroll Down (if)"

    showif show_the_button:
        button:
            at tr_scroll_down()
            pos (1220, 890)
            action Scroll('viewport_messages', 'vertical increase', 1000)
            text "Scroll Down (showif)"

    key 'K_w' action Notify("renpy.restart_interaction()")


transform tr_scroll_down():
    subpixel True
    anchor (.5, .5)
    on show:
        alpha .0
        yoffset 10
        pause .5
        linear .15 alpha .75 yoffset 0
    on hover:
        easein .15 yoffset 10 alpha 1.0
    on idle:
        easeout .1 yoffset 0 alpha .75

label start:
    call screen sc_messenger
    return

```
</details>

. . .

One more goal that I'm trying to achieve here is to trigger the `on show:` block in the ATL transform. It doesn't work with the `showif` statement.


But when I remove the `on show:` line like in the code below, it works with the `if` statement but still the button can't be triggered.
```renpy
transform tr_scroll_down():
    subpixel True
    anchor (.5, .5)
    alpha .0
    yoffset 10
    pause .5
    linear .15 alpha .75 yoffset 0
    on hover:
        easein .15 yoffset 10 alpha 1.0
    on idle:
        easeout .1 yoffset 0 alpha .75
```

**Comment by Booplicate** [comment]
I might be wrong, but I don't see `Scroll` to restart interaction, so the screen won't be updated. `Notify` on the other hand, does restart interaction and causes the screen to get updated.

**Comment by mal** [comment]
> I don't see `Scroll` to restart interaction

I think that may be intended, the restart interaction would only be needed if something else was watching the scroll (as in [lauwurence](https://github.com/lauwurence)'s example) in which case it is probably the watcher that needs to call it.

> Here's another one with the screen added to config.per_frame_screens.

Fairly sure that it's expected that you need to call restart interaction yourself after updating `show_the_button` there. Really it ought to be using the `changed` callback on the adjustment rather than trying to test every frame, and then, as with any other action that updates variables, that callback would need to call restart interaction.

**Comment by lauwurence** [comment]
Okay, here's the a small code that is supposed to work for sure, but it doesn't:

<details>
  <summary>Example Code 4.0</summary>
  
```renpy
screen sc_test():

    default show_the_button = False

    text ("""show_the_button: [show_the_button]"""):
        align (.5, .75)
        size 18

    if show_the_button:
        button:
            at tr_scroll_down()
            xpos 800
            action NullAction()
            text "Button (if)"

    showif show_the_button:
        button:
            at tr_scroll_down()
            xpos 1220
            action NullAction()
            text "Button (showif)"

    timer 1.0 action SetScreenVariable('show_the_button', not show_the_button) repeat True


transform tr_scroll_down():
    subpixel True
    anchor (.5, .5)
    yalign .5
    on show:
        alpha .0
        yoffset 10
        linear .15 alpha 1.0 yoffset 0
    on hide:
        linear .15 alpha .0 yoffset 10
    on hover:
        easein .15 yoffset 10 alpha 1.0
    on idle:
        easeout .1 yoffset 0 alpha 1.0

label start:
    call screen sc_test
    return

```

</details>

The timer triggers the buttons showing each 1 second. The `on show:` and `on hide:` block still do not work with the `showif` button.

At this point I don't know what else I can do.

**Comment by lauwurence** [comment]
### As a result:
1. Adding a screen to `config.per_frame_screens.append` doesn't make the buttons shown with the `if` statement available for triggering, even though they're visible (can be fixed with manual restarting interaction) 
2. Buttons shown with the `showif` statement do not trigger the `on show:` and `on hide:` ATL blocks.
### Alternative result:
1. Maybe I'm just dumb?

**Comment by renpytom** [comment]
Can you state what you think the screen should do? 

config.per_frame_screens are a bit weird, as the screen is being re-shown far more often than a normal screen is. It's intended for debugging, rather than actual use. (The main use is the fps counter.)

**Comment by renpytom** [comment]
Also, having show, hide, hover, and idle transforms in the same transform doesn't make sense.

**Comment by lauwurence** [comment]
I want the "Scroll Down" button that is inside `showif` block to be animated on show, hide, hover and idle.

### No way...

```renpy
transform tr_scroll_down():
    parallel:
        on show:
            alpha .0
            yoffset 10
            linear .15 alpha 1.0 yoffset 0
        on hide:
            linear .15 alpha .0 yoffset 10

    parallel:
        on hover:
            easein .15 yoffset 10 alpha 1.0
        on idle:
            easeout .1 yoffset 0 alpha 1.0
```
Using the `parallel:` block helped!

**I see that right now to make it work I have to:**
1. Do not use `config.per_frame_screens`.
2. Instead use a listener that shows/hides the buttons and then runs `renpy.restart_interaction()`.
3. Use `parallel:` blocks in the ATLs to split `on show`/`on hide` and `on hover`/`on idle` because they block each other.

But is using `parallel:` blocks the right way to deal with this?

**Comment by renpytom** [comment]
So, what you want here is a bit confused. Say you have a show event and a hover event that happen an instant apart. Show will be trying to set yoffset to 0, while hover will be trying to set it to 10. 

Ren'Py will do _something_ there, but what it will do is undefined. That's not an issue with Ren'Py, it's more just that when you tell it to do two things at once, there's no great way to resolve that.

**Comment by Booplicate** [comment]
> Also, having show, hide, hover, and idle events handled in the same transform doesn't make sense.

What is the correct way to use multiple events (like hover/show/hide)? Assuming the transform changes different properties.

**Comment by lauwurence** [comment]
It sounds like a "tug of war" in ATL events, but for me it's not a problem as long as the animation with the longest duration wins.
Anyway, my main issue here has been solved. Thanks, @mal and @renpytom!

And I was thinking... Is it possible to temporarily block `on hover` and `on idle` events while `on show` and `on hide` take place?

**Comment by renpytom** [comment]
parallel is fine if the properties are genuinely different. 

And right now, there isn't a way to temporarily block things. ATL2 will likely rethink a lot of things, but I haven't really started on that yet. (And I might want to refactor how displayables work before I do.)

**Comment by lauwurence** [comment]
ATL2.0?? No way! 
Thank you for your work, @renpytom!

**Comment by renpytom** [comment]
> ATL2.0?? No way!

Could be years before it's actually a thing.
