### ISSUE TITLE
Video playback problem in web version.

### ISSUE THREAD

**Issue by AdamSmasher1** [renpy/renpy#4594]
Renpy version - 8.1.023050201
Browser - Chrome 112.0.5615.138

Video playback is looping. Can't continue game

There was a playback error before.
https://github.com/renpy/renpy/issues/4488

**Comment by Kassy2048** [comment]
Try with `config.fadeout_audio` set to 0.

[Fadeout is not implemented for movies on Web](https://github.com/renpy/renpy/blob/ca3b98672f0815ff301eebb8a71e16cf365b09ac/renpy/common/_audio.js#L548), so now that the default value for `config.fade_music`/`config.fadeout_audio` is [not 0.0 anymore](https://github.com/renpy/renpy/commit/eb89a9bafb0a06e7096bf45292bbbe91e4353a8c), the movie does not stop on first interaction, but the movie audio does fade out. If a dialog is following the cutscene, the movie will stop playing on a second interaction though (but the dialogue won't show), and the "movie" channel will be muted forever afterwards.

I'm working on a fix.
