### ISSUE TITLE
`config.linear_fades` breaks secondary volume

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4597]
When `config.linear_fades` is enabled, setting secondary volume with `renpy.music.set_volume()` is broken as long as the `delay` argument is None.

<details>
  <summary>Video</summary>
  
https://user-images.githubusercontent.com/46109734/236054341-7aed9573-a876-49d0-9ae6-4bd041cf41cf.mp4

</details>

Here's the project: https://mega.nz/file/a8kSiADb#HDrQBDPIEPIvj-TD35UL1eZK9ZBGoKakqZIDquWAntg

**Comment by lauwurence** [comment]
I did an empirical experiment relied on FL Studio 20 to compare the linear fadings.

Ren'Py 8.0.3 was much more closer to the FL Studio's result, while Ren'Py 8.1 was fading much closer to this function https://easings.net/#easeInExpo. This means that the fade curve in the latest Ren'Py is heavily modified because of decibels.

But then https://github.com/renpy/renpy/issues/3746 _"the use of decibels should be in the interface only"_ - Does this mean that `config.linear_fades` should be enabled by default? 

https://user-images.githubusercontent.com/46109734/236060700-d71d6112-b0b6-4b27-98c6-9b9eb772d1a0.mp4

**Comment by lauwurence** [comment]
I think the best solution would be adding a `warper` argument, if it's possible: 
`renpy.music.set_volume(delay=1.0, warper=_warper.ease)` to let the devs decide what fade they want to use, because right now this one is used.

![image](https://user-images.githubusercontent.com/46109734/236071435-5fc202a4-275c-4e08-a2b2-5bb47daa07f9.png)

**Comment by renpytom** [comment]
A warper is a non-starter, for performance reasons. 

The new behavior sounds better to me, since the old one... basically nothing happens for most of the fade, and then everything happens all at once. 

Opening the soundtrack for your demo in Audacity, the Ren'Py 8.1 version looks closer in basic shape than the Ren'Py 8.0 version, though the peak is down slightly. 

![image](https://user-images.githubusercontent.com/379804/236078476-029eb62b-fdc6-4eb7-844f-d5a7532b329e.png)

**Comment by renpytom** [comment]
I do think the 60 dB range might be too high, Wikipedia recommends 30-40 dB.

**Comment by lauwurence** [comment]
@renpytom, reducing the fadeout range makes a lot of sense! Now secondary volume sounds much closer to the FL Studio's result. But speaking of mixer volume, it still has that 60dB range. So basically they extremely mismatch at 50%.

<details>
  <summary>Video</summary>
  
https://user-images.githubusercontent.com/46109734/236432725-d80647ae-a0f1-4142-aeb8-e4bded324ee0.mp4
</details>

Here's the waveform (upper - secondary volume change, lower - mixer volume change):
<details>
  <summary>Waveform</summary>
  
![image](https://user-images.githubusercontent.com/46109734/236431444-288ae617-0089-47aa-8bd2-946b3a211e43.png)
</details>

<details>
  <summary>Code</summary>

```renpy

define config.volume_db_range = 10

init python:

    version = renpy.version()

    try:
        latest_renpy = renpy.version(True).commit > 23010203 # Ren'Py May 3, 2023
    except:
        latest_renpy = False

    # if latest_renpy:
    config.quadratic_volumes = False
    config.linear_fades = False


    def get_secondary_volume(channel):
        """
        Get the secondary volume that is controlled by `renpy.music.set_volume`.
        """
        c = renpy.audio.audio.get_channel(channel)
        return c.get_context().secondary_volume

    def set_mixer_volume(*args, **kwargs):
        renpy.invoke_in_thread(_set_mixer_volume, *args, **kwargs)

    def _set_mixer_volume(mixer, volume, delay=0):
        from time import sleep
        STEPS = 30

        vol0 = preferences.get_volume(mixer)
        vol1 = volume
        prog = 0

        for i in range(int(delay * STEPS)):
            prog = (i + 1) / (delay * STEPS)

            new_volume = vol0 + (vol1 - vol0) * prog
            print(new_volume)
            MixerValue(mixer).set_mixer(new_volume * config.volume_db_range)
            # preferences.set_volume(mixer, )

            sleep(1 / STEPS)


screen sc_decibels:
    if latest_renpy:
        text "New behavior (decibels)\n{size=18}Version: [version]" align (.5, .1)
    else:
        text "Old behavior (linear)\n{size=18}Version: [version]" align (.5, .1)

    default volume = 1.0
    default show_animated_bar = False
    default delay = 4.0

    $ current_volume = get_secondary_volume('music')

    vbox:
        align (.5, .5)
        spacing 10

        # Mixer volume:
        text "Mixer volume: {:.2f}%".format(MixerValue('music').get_volume() * 100 if latest_renpy else preferences.get_volume('music') * 100):
            xalign .5

        bar:
            xalign .5
            xysize (600, 40)
            value Preference("music volume")

        # Set Mixer Volume with delay:
        hbox:
            spacing 50
            xalign .5

            textbutton "Set to 0% (delay: [delay])":
                action [ Function(set_mixer_volume, 'music', 0.0, delay=delay),
                         SetScreenVariable('show_animated_bar', True) ]

            textbutton "Set to 100% (delay: [delay])":
                action [ Function(set_mixer_volume, 'music', 1.0, delay=delay),
                         SetScreenVariable('show_animated_bar', True) ]

        null height 120

        # Secondary volume:
        text "Secondary volume: {:.2f}%".format(current_volume * 100):
            xalign .5

        bar:
            xalign .5
            xysize (600, 40)
            value ScreenVariableValue('volume', range=1.0, step=0.001, force_step=True,
                                      action=Function(renpy.music.set_volume, volume, channel='music'))
            released Function(renpy.music.set_volume, volume, channel='music')

        null height 50

        # Set Secondary Volume with delay:
        hbox:
            spacing 50
            xalign .5

            textbutton "Set to 0% (delay: [delay])":
                action [ Function(renpy.music.set_volume, 0.0, channel='music', delay=delay),
                         SetScreenVariable('show_animated_bar', True) ]

            textbutton "Set to 100% (delay: [delay])":
                action [ Function(renpy.music.set_volume, 1.0, channel='music', delay=delay),
                         SetScreenVariable('show_animated_bar', True) ]


    if show_animated_bar:

        vbox:
            align (.5, .5)
            spacing 5

            text "Applying progress..." xalign .5 size 22

            bar:
                xalign .5
                xysize (400, 10)
                value AnimatedValue(value=1.0, range=1.0, delay=delay, old_value=.0)

        timer delay action SetScreenVariable('show_animated_bar', False)


label start:
    $ renpy.unwatch('all')
    $ renpy.watch('config.quadratic_volumes')
    $ renpy.watch('config.linear_fades')
    $ renpy.watch('config.volume_db_range')
    play music "audio/low_frequency_noise_60hz.ogg" fadein 1.0
    call screen sc_decibels
```
</details>

Changing `config.volume_db_range` to something lower than 60 breaks the mixer slider.
