### ISSUE TITLE
Why Live2d attribute_filter is now sorted?

### ISSUE THREAD

**Issue by ParadoxalDeviant** [renpy/renpy#4599]
https://github.com/renpy/renpy/blob/ca3b98672f0815ff301eebb8a71e16cf365b09ac/renpy/gl2/live2d.py#L682

Hi,
I was wondering why this change was made?

I recently switch from 8.0.3 to 8.1.0 to anticipate the change and I have to admit that I really didn't see this one coming. We switch from an attribute list where new attributes come first to a sorted attribute list where you have to find which are the new one.
I don't know if there's any reason behind this change but is it really necessary?

I have a method that I use as a Live2d attribute_filter to manage attributes and correctly switch between the various eyes/mouth/etc. of my animated character.
It looks like that:
```py
def character_attr_filter(attrs):
    all_motions = ["idle", "move"]
    all_eyes = ["open", "close"]
    all_mouths = ["smile", "surprised"]

    attr_motion = []
    attr_eyes = []
    attr_mouths = []

    for attr in attrs:
        if attr in all_motions:
            attr_motion.append(attr)
        elif attr in all_eyes:
            attr_eyes.append(attr)
        elif attr in all_mouths:
            attr_mouth.append(attr)

    motion = attr_motion[0] if attr_motion else all_motions[0]
    eyes = attr_eyes[0] if attr_eyes else all_eyes[0]
    mouth = attr_mouth[0] if attr_mouth else all_mouths[0]

    attrs = tuple([motion] + [eyes] + [mouth])
    return attrs
```
So if you only use `show character` it's like you're typing `show character idle open smile`. Then, when you have to change an attribute afterwards by typing `show character close` it will just replace `open` by `close`, as if you've typed `show character idle close smile`.

So let's assume you display the character and then you need to change the mouth expression:
```py
show character
"Pretty nice weather today."
show character surprised
"Oh no, the clouds are coming!"
```
- In 8.0.3, when you enter the method with the second `show` statement the attribute list you get is `('surprised', 'idle', 'open', 'smile')` so the `attr_mouth` list will be equal to `['surprised', 'smile']`. The first item of this list **is** the attribute given.
- In 8.1.0, when you enter the method with the second `show` statement, the attribute list you get is `('idle', 'open', 'smile', 'surprised')` so the `attr_mouth` list will be equal to `['smile', 'surprised']`. The first item of this list **is not** the attribute given.

I have now to find a way to know if there is a change in the attributes given (like if one of the `attr_` list I create is bigger than 1, to find in this list what is the new attribute so I can use it when I return my `attrs` tuple.
But why?
Why this change was made when it's so simple to know what are the new attributes when they're the first returned in the attribute list?

**Comment by renpytom** [comment]
The thinking was to have a stable order in the case where two expressions manipulated the same property - to make that deterministic. 

4221cd1e8 is another take at that - making sure all the new attributes are before all the old ones, and sorting within a group.
