### ISSUE TITLE
Issues with Speech Bubbles

### ISSUE THREAD

**Issue by rabbitwithworms** [renpy/renpy#4605]
Note: This issue occurs in the Prerelease builds. I'm not sure if bugs in the Prerelease are covered and the developers are aware of these in particular. But they should be noted nonetheless.
Note 2: I tested this on Linux, but maybe you should test it on Windows as well?

### Bug 1 - Bubbles not working properly with "extend"

How to reproduce:

In a coding software of choice, Define a character with speech bubble mode using **kind=bubble**. Write their dialogue as you would with them and use the **extend** special character after them.
```
e "Sometimes, I feel sad. "
extend "But I usually quickly get over it!"
```
Expected behavior:
Since I used the **extend** special character, the bubble should display the next text as it normally would with extend.
Actual behavior:
The bubble cuts to a split second to the say screen, before reappearing and displaying the rest of the text.

This behavior can be avoided by using the {p} text tag, but it's not ideal for text sentences.

### Bug 2 - Bubbles do not get saved.

If I use the Speech Bubble Editor I can position and change the style of bubbles. However if I change the text after editing the bubble position or look, it resets.

**Comment by renpytom** [comment]
Your second issue is know, and accepted - when you change the text, it becomes a different line of dialogue. (Unless you preserve the translation id.)

**Comment by rabbitwithworms** [comment]
Thank you for taking notice to the second issue! Also, i know its not related to this discussion, but if the speech bubble mode is eventually completed, will it support multiple speech bubbles on screen at once, as seen in games like Please Be Happy? 
![Please-Be-Happy-Screenshot-006-1280x720](https://user-images.githubusercontent.com/132721101/236641550-ecb8cccd-bbe3-428b-ab27-68627c37396d.jpg)

**Comment by rabbitwithworms** [comment]
Ah dang it, I accidentally closed it.

**Comment by renpytom** [comment]
I just added 8048386b4 , which fixes the first issue. 

Multiple always was supported, using the usual (multiple=2) syntax. There's a fix to a problem that prevented the editor from working properly with multiple, but display was always there. 

```renpy
define e = Character("Eileen", kind=bubble, image="eileen")
define l = Character("Lucy", kind=bubble, image="lucy")

label start:
     l "If you set the multiple..." (multiple=2)
     e "Multiple lets you have multiple speech bubbles up at the same time." (multiple=2)

    l "Do you have to talk at the same time as me?"
```

**Comment by rabbitwithworms** [comment]
Ah, thank you! Now this can be closed.

**Comment by rabbitwithworms** [comment]
I know about multiple mode, but I wonder if it's possible for bubbles to stay on screen and then clear once dialogue is completed? Adding one bubble per each line, kind of like how NVL mode uses its lines of dialogue.

**Comment by renpytom** [comment]
This is something I'll add, but since the changes will be fairly large, it's going to wait for 8.2

**Comment by Gouvernathor** [comment]
In the meantime, you can probably do this more easily using `extend "{nw}" (multiple=2)`.
And I suggest opening a new issue for this feature request and closing this one, for clarity.
