### ISSUE TITLE
Live2D Bug - Animation ends with A-Pose (neutral pose)

### ISSUE THREAD

**Issue by CodedRubyChan** [renpy/renpy#4608]
My Problem is that after a Live2D Animation is played, it reverts to the neutral position. (neutral pose = A-Pose)
I tried setting the Loop Attribute to True and False but both don't work.
The Loop Attribute is set to True = The Animation plays, reverts to the neutral pose, and it does the same thing again and again.
The Loop Attribute is set to False = The Animation plays, reverts to the neutral pose and stays in the last frame with the neutral pose.

I looked at the Model in the Cubism Viewer and there it works like i wanted to do it. 
So i don't whats the problem and how to fix it

**Comment by renpytom** [comment]
You probably have fades set. The documentation says that if you have fades set at the end of the loop, then it'll fade out t the neutral pose before the loop is over. 

https://docs.live2d.com/en/cubism-editor-manual/about-fade/

That being said, this is a common enough request that I'd be willing to make a loop_fade option in Ren'Py. Do you have an example that makes the problem obvious?

**Comment by CodedRubyChan** [comment]
To reproduce the problem easy is what i did.

First i just wanted to test how it works so i downloaded a Live2D Model from https://sekai.best/l2d which has everything the Rhythm Game "Hatsune Miku: Colorful Stage!" has, Models, Music, Artworks etc.

And thats where this problem occurs.
If its really a problem with set fade options, then i could fix it manually, but it would be awesome to have a option directly in Ren'Py

**Comment by renpytom** [comment]
Turns out that option existed already. You can uses the seamless option to declare seamless motions, or set seamless=True to declare all motions seamless.

**Comment by CodedRubyChan** [comment]
I'll try that tomorrow, thanks :D
