### ISSUE TITLE
Restart interaction only for particular screens

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4609]
What do you think about `renpy.restart_interaction()` having an argument to which can be passed a screen name or a list of screens? So it could be possible to update the particular screens, instead every shown ones. 
It might increase performance of `Show`, `Hide`, `-ScreenVariable` actions in cases where many complex screens are displayed.

**Comment by renpytom** [comment]
This doesn't make a lot of sense, given the way Ren'Py works. Either you continue the interaction, or you don't. It might be possible to have restart_interaction take a list of screens _not_ to update, but even there... 

I'll be honest that it seems like the right solution would be to optimize the screens better, rather than to request that Ren'Py not update them. 

How much work have you done to profile the screens in question to figure out why they're slow?

**Comment by lauwurence** [comment]
They're not actually slow, but l see ~15fps drop on actions with `renpy.restart_interaction()`, even though such actions do not affect other shown screens. For example, a custom notification screen that shows a list of notifications and hides them in a few seconds. 

I think I optimized my screens as much as possible... But when there're more than 3 screens shown, it doesn't matter how optimized they are, because `renpy.restart_interaction()` affects them all.

A list of screens not to update? Maybe It could be possible to use the list of currently shown `ScreenDisplayable`:
`renpy.game.context(-1).scene_lists.layers['screens']`
Subtract the user input list and then tell Ren'Py to not to update the screens from this list?

**Comment by Org-gith** [comment]
Do those screens contain a lot of text rendered by Ren'py (like the screen history)? I have noticed text being rendered (not image text) can murder performance if you have a certain number of screens running at once.

**Comment by lauwurence** [comment]
No, @Org-gith, I combined as many separate displayables as possible into single displayables, like here:

<details>
  <summary>Example</summary>
  
```renpy
python:
    tt = "%s%s%s" % (
        ("{color=#d6d6d6}%s %s{/color} %s%s %s\n" % (
            "{image=_social_birthday}",
            __("Birthday:{#social}"),
            renpy.translate_string(PAGE['birthday']),
            "," if preferences.language == 'english' else "",
            current_year - character.age,
            )
        ) if 'birthday' in PAGE else "",

        ("{color=#d6d6d6}%s %s{/color} %s\n" % (
            "{image=_social_heart}",
            __("Relationships:{#social}"),
            renpy.translate_string(PAGE['relationship'][page.relationship]),
            )
        ) if PAGE['relationship'][page.relationship] else "",

        ("{color=#d6d6d6}%s %s{/color} %s" % (
            "{image=_social_location}",
            __("City:{#social}"),
            renpy.translate_string(PAGE['city']),
            )
        ) if 'city' in PAGE else "",
    )

text tt:
    style 'st_smartphone_text_h4'
    text_align .0
    xalign .0
    
```
![image](https://user-images.githubusercontent.com/46109734/236637987-48924b6d-afc0-4b7e-969b-379c6cde4bd1.png)

</details>

**Comment by Andykl** [comment]
I've tried that and it did not work good because it goes out of sync very quickly, and you're wondering "where exactly did I forget to specify this screen". 
What hurts performance in my case is a python code, eg. `if` conditions, and I have found a pretty good solution to that. You write a label wrapper around the screen update, i.e.
```
label show_myscreen:
    $state = {
        'var': complex python expression,
    }
    show screen myscreen(**state)

screen myscreen(var):
    if var:
        ...
```
So, when `restart_interaction` occur it is fast bool lookup, not a reevaluation. And you call that label only when you know you alter `complex python expression`.

**Comment by lauwurence** [comment]
Hmm... @Andykl, why don't you just use `default' in your screen instead? This looks like a simpler solution to me:

```renpy
init python:
    def complex_function():
        from time import sleep
        sleep(1.0)
        
screen myscreen(page, baction=None):
    default var = complex_function()
```

**Comment by Andykl** [comment]
`default` is `NOT_CONST` when screen parameter is a `LOCAL_CONST` if you know what it mean.

**Comment by lauwurence** [comment]
So, basically screen parameters are faster because of being `LOCAL_CONST`? This makes sense in terms of getting data more efficiently.
Thanks for sharing your solution, @Andykl!

**Comment by Gouvernathor** [comment]
Simply putting them as the default values in the parentheses is presumably simpler as those are evaluated at call time rather than at definition time (like the python functions). It may be more readable, but it depends on what your expression looks like.
