### ISSUE TITLE
New Launcher Bug

### ISSUE THREAD

**Issue by avarisclari** [renpy/renpy#462]
The latest release features a weird bug. If you have no project selected in the tree and click launch a new launcher appears. I tested on a previous build I had downloaded and it didn't exist.
To reproduce:
1. Select update.
2. Click Proceed.
3. No project should be selected now.
4. Click Launch.

Also, on the second launcher, update doesn't exist. I don't know what causes this. 

Edit: Attempted to reproduce in a new launcher and it wouldn't. It must only appear in the restarted version of Ren'Py when updated. I don't know, sorry.

Edit 2: I looked into it more and it seems to go with the option of "Open Launcher Project". I still don't know what caused this in the first place though.

**Comment by renpytom** [comment]
It's there to allow for testing of the launcher, for development purposes. It's reasonably hidden, and useful for me and people developing launcher themes. So I don't think this is really a bug.
