### ISSUE TITLE
renpy-8.1.0-sdk Startup issue

### ISSUE THREAD

**Issue by SamGamerYT** [renpy/renpy#4622]
Hello there, Quick proper information issue report, 
renpy-7.4.11-sdk & renpy-8.0.3-sdk - Boots up as expected however renpy-8.1.0-sdk does not boot up as expected but when I unplug my https://www.razer.com/gaming-keypads/Razer-Tartarus-Pro/RZ07-03110100-R3U1 it works as expected.

**Comment by renpytom** [comment]
Do you have the log.txt? I can blocklist that hardware.

**Comment by SamGamerYT** [comment]
Thu May 11 18:44:47 2023
Windows-10-10.0.19044
Ren'Py 8.1.0.23050902
 

Bootstrap to the start of init.init. took 0.06s
Early init. took 0.00s
Loader init. took 0.06s
Loading error handling. took 0.33s
Loading script. took 0.72s
Loading save slot metadata. took 0.04s
Loading persistent. took 0.00s
Set script version to: None (alternate path)
Running init code. took 0.53s
Loading analysis data. took 0.02s
Analyze and compile ATL. took 0.01s
Reloading save slot metadata. took 0.00s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache. took 0.00s
Making clean stores. took 0.00s
Initial gc. took 0.04s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object. took 0.51s
Cleaning stores took 0.00s
Init translation took 0.05s
Build styles took 0.00s
Load screen analysis took 0.05s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.13s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start. took 0.37s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 531.79'
Display Info: None
Screen sizes: virtual=(800, 600) physical=(800, 600) drawable=(800, 600)
Maximum texture size: 4096x4096
controller: '030000006d0400000000000000007200' '(Razer Xbox 360 Controller)' 1

**Comment by renpytom** [comment]
I've blocklisted the controller.
