### ISSUE TITLE
Is it possible to force a 60 fps movie to run as 30 fps?

### ISSUE THREAD

**Issue by Oppai-Man** [renpy/renpy#4624]
Most computers can run 60 fps movies, but some can’t. These computers would benefit of limiting a video framerate to 30 fps.

Is it possible to force a 60 fps video run at 30 fps, by droping every second frame?

**Comment by renpytom** [comment]
You can hit shift+G, and limit the framerate. You can also encode the movie at 30 fps. Other than that, no.
