### ISSUE TITLE
I can't install the SDK and create keys, RenPy

### ISSUE THREAD

**Issue by xeoonx** [renpy/renpy#4625]
![image](https://github.com/renpy/renpy/assets/133381997/c56b5092-ab07-44fb-bfe6-bd4553327b63)
I can't install the SDK and create keys, what should I do?

**Comment by renpytom** [comment]
You need Java 8.

**Comment by xeoonx** [comment]
installed, it turned out to install the sdk, but another problem arose, after processing the use of Grandle, an error occurred, and the assembly writes with an error
![image](https://github.com/renpy/renpy/assets/133381997/55169c01-4ae2-4c03-b36b-f43dacae3faa)
![image](https://github.com/renpy/renpy/assets/133381997/7f65a3ea-20e6-4853-803e-c03269812e5f)

**Comment by renpytom** [comment]
The error isn't a Ren'Py one. The gradle plugin has a problem with non-ascii characters. So you need to install a new copy of Ren'Py in, say, C:\RenPy.
