### ISSUE TITLE
Ability to skip new history entries if the previous entry displayed was the same

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#4626]
Minor stuff, but for games that have repetitive bits, let's say for example asking a repetitive question with a repetitive answer, the history message can end up looking like this:
![wise](https://github.com/renpy/renpy/assets/78823063/89ddd8f8-bd53-436f-9de8-41494f4c0847)
The idea would be just to avoid that repetition in extreme cases, by not repeating the entry in history if it's the same as the previous one (it wouldn't deal with all cases, but only the most obvious one which is what matters the most I think). Could be just an option in the way history is working, because I assume the regular method could be wanted too.

**Comment by renpytom** [comment]
Ren'Py shouldn't produce these itself. Apart from that, _history_list should be a normal list you can pop from.
