### ISSUE TITLE
Save created on another device screen

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#4632]
Hello,
1.Under what section can I find how to properly set up the key in documentation?
2. Where is the screen that shows this element so it can be further styled. The default screen breaks some of my other screen functions and stretches on almost whole width of screen. Is there a way to move this screen to project screens.rpy or is it just a regular confirm screen?

**Comment by KatieCheerios** [comment]
Thank you. Can I get my key as a project creator?

**Comment by renpytom** [comment]
Are you talking about the key used for "official saves"?
