### ISSUE TITLE
Volume slider

### ISSUE THREAD

**Issue by KatieCheerios** [renpy/renpy#4635]
Hello,
I know that the game changed to db, but can we get a bar that when set at 50% is actually half the volume? Setting the volume through _preference at 0.5 shows the slider what would before be something like 80%+. This is even a case in newly created projects.

Edit:
Tried the default bar value Preference("mixer") that ships with every project and also the bar value MixerValue("mixer") and both are the same. If the MixerValue() is intended for volume then change it to logarithmic fashion internally. Or something like that to make it work intuitively.

**Comment by renpytom** [comment]
preferences.set_mixer("music", 0.5)  sets a mixer to 50%.

**Comment by Gouvernathor** [comment]
It is, you won't find it in the documentation anymore.

**Comment by KatieCheerios** [comment]
Ok, thanks.
