### ISSUE TITLE
Still worse movie playback: Now for 8.1 and 7.6 + no partial playback anymore

### ISSUE THREAD

**Issue by Elrath12** [renpy/renpy#4646]
This is a continuation of the issue: https://github.com/renpy/renpy/issues/4070

The performance of videos is still worse when going from 7.4.4. to 8.1 or 7.6. There also doesn't seem to be partial playback support for movies anymore, e.g. <from 1.0>, <loop 1.4> and so on.

I made a small sample project for this that works on 8.1 and 7.6. Some context: 
The video does not seem to be able to reach 60 fps on my pc and takes twice the amount of cpu and gpu utilization compared to 7.4.4. Furthermore using partial playback just shows a static image. In 7.4.4. The frames were a stable 60 fps with partial playback working as intended. The same movie as in the previous issue has been used.

Link: https://drive.google.com/file/d/1IUgEgAGlLtLMSxe7_RnfPqFVojS3Hq3A/view?usp=share_link

**Comment by lauwurence** [comment]
Found out that in my case performance drops when I manually create channels for movies like here:
```renpy
init python:
    renpy.music.register_channel('custom_webm_channel', mixer='sfx', loop=True, stop_on_mute=False, movie=True)
```

Using movies with non-existing channels assigned do not decrease performance:
```renpy
image webm_test1 = Movie(play="images/test.webm", channel='custom_webm_channel')
```

**Comment by renpytom** [comment]
Can you please make that drive link readable to the world?

**Comment by Elrath12** [comment]
> Can you please make that drive link readable to the world?

Sorry, thought I did. It should be accessible for everyone now.
