### ISSUE TITLE
Play audio in ATL

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4647]
I faced with the need to create an animation with synchronized audio but there's no play statement. 
Is there any chance that something like this could be implemented?

```renpy
image anim_blink_icon:
    'gui/blink_icon_0.png'
    pause 5.0
    'gui/blink_icon_1.png'
    play sound "audio/blink.ogg"
    pause .5
    repeat
```

Using `function` is one way to play sound, but it looks too cumbersome: 
`function renpy.curry(play_sound)(filename="audio/blink.ogg")`

```renpy
def play_sound(trans, st, at, filename):
    renpy.music.play(filename, channel='sound')
    return None
 ```

**Comment by Booplicate** [comment]
Also had to do the exact same, was worried the function will be called during prediction, but seemed to work.

While technically it can look weird to combine visuals and audio (why not show and play both?), there's a more interesting use case. Imagine if you're using `choice`s and you want to play the sound only for one of them:
```renpy
block:
    choice 0.5:
        "some_image"
        pause 0.1
        function play_sfx
    choice 0.5:
        pass
```
There's no way of doing it w/o this hack since you cannot know the image state outside of it.

**Comment by Gouvernathor** [comment]
> This function should not have side effects other than changing the Transform object in the first argument, and may be called at any time with any value to enable prediction.

https://www.renpy.org/doc/html/atl.html#function-statement

This is not a feature and will likely be broken in a future version.

**Comment by Gouvernathor** [comment]
Aside `function` misuse, the idea could be good. It could be considered to only `play` things on the audio channel for starters, so no queue, no stop, also no interference between displayed ATLs.
I'm still not sure about it fitting in ATL, but I was also against break and continue in screen language so...

**Comment by renpytom** [comment]
This isn't likely to happen before ATL2 comes out, whenever that is. Right now, ATL is intended for use with displayables, and I don't think that's likely to change without a major rethink.
