### ISSUE TITLE
Layeredimage if_any doesn't raise errors on bad syntax

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#4649]
Currently, in Ren'py 8.1 stable, `if_any` allows lists containing syntax errors without triggering an error, resulting in a False evaluation.

Example (Note the missing comma inside the list):
```renpy
layeredimage myimage:
    group outfit prefix "outfit":
        attribute casual default
        attribute formal
        attribute pyjamas

    attribute hair_fringe default if_any ["outfit_casual" "outfit_formal"]
```

**Comment by Gouvernathor** [comment]
That's not a syntax error, that's normal Python parsing of strings. Your example results in `["outfit_casualoutfit_formal"]`, you can try it in any python console. So, it looks like intended behavior.

**Comment by renpytom** [comment]
That's weirdness inherited from Python, but I don't think we'll change it.

**Comment by loafylemon** [comment]
I never thought it could be valid syntax, but I was wrong. Thanks!
