### ISSUE TITLE
Can't decode Shift-jis

### ISSUE THREAD

**Issue by azulika** [renpy/renpy#4650]
```python
init python:
...
            title = title.encode("iso-8859-1").decode("shift-jis")

```

```
title = title.encode("iso-8859-1").decode("shift-jis")
LookupError: unknown encoding: shift-jis

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
TheFoolsJourney 1.0
Sat May 20 09:53:18 2023
```

It seems that Renpy doesn't currently support the Python built-in encode/decode in several encodings, such as shift-jis.
Although I can use `cp932` instead and have no problems so far, it would be better if shift-jis support was added.

**Comment by renpytom** [comment]
The full set of Python encodings was added to Ren'Py in the new release.
