### ISSUE TITLE
How can the following problem be resolved?

### ISSUE THREAD

**Issue by xyzsarkanyagyu** [renpy/renpy#4653]
Despite the change in the variable's value, the appearance of the image button does not update unless the screen has been opened once, closed, and then reopened.

$ minolock = True
screen gallery():
            imagebutton: 
                    if (minolock == False):
                        idle "gui/UI/podcast_lock.png" 
                    elif (minolock == True):
                        idle "images/galleryui/mino_idle.png"
                        hover "images/galleryui/mino_hover.png"
                        action [ToggleScreen ("gallery"), ShowMenu("minogallery")]

**Comment by mal** [comment]
You likely need to call `renpy.restart_interaction()` after changing the value of minolock, wherever you are doing that, so that the screen gets updated with the new value.

**Comment by renpytom** [comment]
Closed for no, pending a response.
