### ISSUE TITLE
utter_restart() does not work as intended on Android

### ISSUE THREAD

**Issue by treirouxel88** [renpy/renpy#4654]
on Android, renpy.utter_restart() close the game and after that i am unable to open it again (the game closes instantly whenever i try to launch it)

tested on physical phone (honor 8X android 10) as well on Bluestacks.
renpy version 8.1 stable

**Comment by renpytom** [comment]
renpy.utter_restart is not supported on Android, iOS, and the Web. (You can probably kill the process or restart your phone, and it will then start working again.) 

I'm not sure we say this, so I'll make a doc issue.

**Comment by Gouvernathor** [comment]
It's actually [undocumented](https://github.com/renpy/renpy/blob/master/renpy/exports.py#L1910)... though it's referenced in the doc, [here](https://nightly.renpy.org/doc/other.html#renpy.set_autoreload) for instance. 🤷

**Comment by treirouxel88** [comment]
i implemented a resource downloader which downloads scripts, screens, live2d models, cutscenes, and much more, the thing is i am implementing a system which donwloads "on-demand", instead of downloading the whole game in one time, it downloads parts of the story only when needed, it would save bandwidth on my side.

**Comment by renpytom** [comment]
renpy.utter_restart now works on Android.
