### ISSUE TITLE
Self-voicing not working in Renpy 7.6 release? Volume Bars...

### ISSUE THREAD

**Issue by GamesByKinmoku** [renpy/renpy#4656]
Hello, I was play-testing my game last week with the 7.6 pre-release and self-voicing was working...but I updated today to build my demo and self-voicing doesn't appear to be working anymore. Pressing V or the button I added to preferences shows the popup but doesn't make any noise.

Also, I know this has been changed recently, but the audio volume bars are all almost silent for the first half of the bar. Do I need to change my code or something? I just use:

bar value Preference("music volume")

Thanks.

**Comment by renpytom** [comment]
Hm... Can you go into the voice debug mode, (from the shift+A menu), and see if it says anything? 

What platform are you on?

**Comment by GamesByKinmoku** [comment]
Sorry, Shift+A voice debug doesn't seem to be doing anything for me. I'm on Mac.

**Comment by renpytom** [comment]
That's odd. Are you at least getting the shift+A accessibility menu?

**Comment by GamesByKinmoku** [comment]
No, pressing shift+A does nothing for me. To clarify, this is on Renpy 7.6.0.23051307. My Mac is on Big Sur 11.7.4.

**Comment by GamesByKinmoku** [comment]
Update:

"I was play-testing my game last week with the 7.6 pre-release and self-voicing was working"

Actually, I forgot to test this with the 7.6 pre-release and the last time it was working for me was on nightly 7.6.0.23031904

**Comment by renpytom** [comment]
Can you try a new game? It's working for me with a new game on macOS 13.3.1.

**Comment by GamesByKinmoku** [comment]
Okay. It works in a new game.

I went and checked my project and forgot I had:

`$ config.keymap['accessibility'].remove('K_a')`

As I already made my own accessibility menu a while ago. Commenting this out seemed to fix the self-voicing, but now that I've added it again, self-voicing still works! I've no idea why but it's a relief :)

**Comment by renpytom** [comment]
I'd suggest not removing Ren'Py's accessibility menu like that. Doing so can harm accessibility - as I add features to new versions of the engine, people have the ability to load older games in newer Ren'Pys, and the new accessibility features will be accessible through that menu. 

In any case, looks like this has been resolved.

**Comment by ORyanNova** [comment]
I have same issue, only I use windows 11.
