### ISSUE TITLE
Bubbles pop up per line of Dialouge/Thought

### ISSUE THREAD

**Issue by rabbitwithworms** [renpy/renpy#4658]
I just made a new post for this specific feature request i mentioned on a now closed issue: #4605 

the gist of it is that I wonder if it's possible for bubbles to appear one by one per line of dialogue or thought, and clearing them with a statement Ala NVL mode? Like an animated web comic or a flash game:

![demonstration](https://github.com/renpy/renpy/assets/132721101/3392e302-e543-4677-93dc-3d26ea6b31dc)

A workaround [Gouvernathor](https://github.com/Gouvernathor) mentioned is by using `extend "{nw}" (multiple=2).` But I would like to see a full fledged implementation in the future.

**Comment by renpytom** [comment]
This is retained bubbles, coming in 8.2.

https://nightly.renpy.org/current-8/doc/bubble.html#retained-bubbles
