### ISSUE TITLE
Ren'Py - Live2D Feature Request

### ISSUE THREAD

**Issue by CodedRubyChan** [renpy/renpy#4662]
Hey there! 
I have some ideas for Features i would love and maybe other people could need it too.
First look at the Video where i showcase the Live2D Model "Kanade" from the Game "HATSUNE MIKU feat. Colorful Stage!" 
~_(AND PLEASE IGNORE THE SOUNDS IN THE VIDEO I WAS WATCHING A YT VIDEO XD)_~

https://github.com/renpy/renpy/assets/40892993/585e4677-e8d8-4932-82e3-00cfa2aff940

The First Feature i would love to have is to Rewind Motions. As you can see the second motion does not have a animation to go to its first frame so the motion loops abruptly.
The Second Feature i would like (in combination with Feature 1) - Setting Loop Points.
It would play the motion at first time complete and then if the motion is completed, rewind (with feature 1) to Loop Point A play until the end or Loop Point B, rewind, LP-A -> LP-B and so on.

I hope its understandable what i mean, english is not my first language, its german.
And if its not going to be accepted, which i can understand if not, maybe someone here has an idea on how i can fix my problems.
Because i use downloaded Assets i don't have the Source Files for the Character and i only have the .moc3, .model3.json and the .motion3.json files

(All Assets used in the Video are just downloaded/ripped for the Purpose of Learning Ren'Py & Live2D Implementation!)

**Comment by renpytom** [comment]
I don't see these as particularly likely to happen in-engine. Both should be doable by designing your motions correctly. The looping repeat of the motion should certainly be possible in live2d - and you could hire a programmer to write a tool to reverse live2d motions.

The start and then loop is best done by listing out two motions, not trying to force them into one. 

I don't really want to go past what's documented in Live2D, so you'd want to bring these features up with them.
