### ISSUE TITLE
`bar`'s size behave the same way for `float`s and `absolute`s

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#4666]
```rpy
label main_menu:
    return

screen test():
    default alpha = 0.0
    add "#fdfdfd"

    add "#000":
        at transform:
            alpha alpha
    
    frame style "empty":
        background "#000000d0"
        xysize (100, 300) align (0.5, 0.5)

        vbar style "empty":
            bar_vertical True
            value ScreenVariableValue("alpha", 0.8, style="empty")
            bottom_bar "#bdbdbd"

label start:
    call screen test
```
works fine
![image](https://github.com/renpy/renpy/assets/101005497/dfad1f97-4279-4ea2-af38-cabd2af35df5)

but using `xysize (absolute(100), absolute(300))` for the `frame`'s size we get
![image](https://github.com/renpy/renpy/assets/101005497/8eb2e21d-5235-4adf-b012-cbc79ac03224)
as if we used `xysize (100.0, 300.0)`

doesn't matter if it's the parent's size or the bar's size, it happens in both cases

**Comment by renpytom** [comment]
Fixed by 3396feff333be35bcea6a3269860edafda4b4ddc and 360dc4fdbbcd58c341d9414caf1d1d839b2c4cc5 (and their main-branch equivalents).
