### ISSUE TITLE
renpy does not write every text to the translation

### ISSUE THREAD

**Issue by am1guard** [renpy/renpy#4668]
When I translate a game from Ren'py, there is almost never an interface translation. There is always something missing. Let's say a sandbox game shows you how to do a task from your phone. This part is never translated. How can I do this?

**Comment by Dobby233Liu** [comment]
Sounds like you need to mark the related strings as translatable manually. It's explained in the docs here: https://renpy.org/doc/html/translation.html#menu-and-string-translations

**Comment by m-from-space** [comment]
TL;DR: Whenever you want some string to appear inside the translation files and that string is not already a dialogue or menu option, put it inside the function `_("my text")`. Next time you could have asked within the [forum](https://lemmasoft.renai.us/forums/viewforum.php?f=8) for that matter or RTFM (which is mostly great actually)! :)
