### ISSUE TITLE
Custom RPA extension

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4669]
https://github.com/renpy/renpy/blob/fe2d76bdd34738e6603789e7d41b2c67490f0643/renpy/loader.py#L114

https://github.com/renpy/renpy/blob/fe2d76bdd34738e6603789e7d41b2c67490f0643/launcher/game/distribute.rpy#L885

Looking a little bit at Ren'Py's code I found the class that is in charge of loading the RPA and what I understand is what generates the rpa. Thinking a little I thought about the possibility of allowing custom .rpa extensions, for example: .data, .package, .dlc. Basically the only thing that changes is the name of the extension, I suppose that to implement this you could call some function that adds to the list of allowed extensions the custom extension. And to change the value of "archive_extension" for the change to take effect.

on the configuration side on the developer's side I think it could be like this:

define config.rpa_extension = "data" // By default "rpa" 

This I propose would be to add a little support to this, it may not make sense to some developers and I agree, it's a crazy idea. But it would add a touch more customization to the engine.

**Comment by renpytom** [comment]
I think that this would cause too many problems. A big one is that scripts can be contained in archives, but the list of extensions won't be changed until script loading occurs. So you can very easily get into a state where the game isn't loaded properly - and that seems like it could lead to hard to diagnose errors. 

Couple this with the lack of a decent case for this, and I can't see putting any effort into this.
