### ISSUE TITLE
Transforms containing event handler don't respect "animation" timebase

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#4671]
(So I was trying to solve [this forum issue](https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=66663).)

I'm really not sure if I am doing this right, but when I create a transform that handles events using the `event` and `on` statements and showing those transforms as part of `showif` statements, the animation keyword is not respected. That means that the animation starts from the beginning instead of using the animation timebase.

Also could we have `animation` statements for blocks, not just the whole transform?

Example below. I expect that the rotating animation (anim_A) will use the animation timebase when the player clicks the button. Instead it starts from the beginning. Doesn't matter where I put the animation keywords, I already put them everywhere. ^^

```
transform anim_A:
    rotate 0
    linear 3.0 rotate 360

transform anim_A_loop:
    animation
    anim_A
    repeat

transform anim_B:
    animation
    on appear:
        anim_A
        event anim_A_done
    on show:
        anim_A
        event anim_A_done
    on anim_A_done:
        linear 3.0 xpos 500

screen myscreen():
    default clicked = False
    vbox:
        showif clicked:
            add "eileen" at anim_B
        else:
            textbutton "Click Me!" action SetScreenVariable("clicked", True)
            add "eileen" at anim_A_loop

label start:
    show screen myscreen
    "Fin."
```

**Comment by m-from-space** [comment]
(By the way, I actually don't want statements after events use the animation timebase, if not explicitely stated after the event or as part of the whole transform. Otherwise this whole thing won't work.)

So my dream would be:

```
transform anim_B:
    on appear:
        animation
        anim_A
        event anim_A_done
    on show:
        animation
        anim_A
        event anim_A_done
    on anim_A_done:
        linear 3.0 xpos 500
```

Also why doesn't this enforce using the animation timebase everytime I include it in another transform?

```
transform anim_A:
    animation
    rotate 0
    linear 3.0 rotate 360
```

**Comment by m-from-space** [comment]
My biggest dream would not using events at all, but make sure that `animation` keywords can be used inside blocks.

```
transform anim_B:
    block:
        animation
        anim_A
    block:
        linear 3.0 xpos 500
``` 

(The second block should NOT use the animation timebase.)

**Comment by renpytom** [comment]
I think you're misunderstanding how animation and on interact. The on statement takes precedence here, and so time inside its block resets when the block is reached. This is unlikely to change before ATL2, and I'm not sure it's going to change there.
