### ISSUE TITLE
"Auto" being turned on after Reload

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#4672]
Whenever I reload, auto is turned on whether I want it or not. This can create an issue if I am correcting an issue in Code and go back to see that it has automatically gone past that point. Is this intended?

Using 8.1.1.23052601+nightly.

**Comment by renpytom** [comment]
Yes, since most people want that. 

You can disable it with: 

```renpy
define config.autoreload = False
```

**Comment by danac78** [comment]
@renpytom Umm.. that will disable auto-reload, which is not what I was talking about. It is turning on auto-forward, which was not an issue before I updated to this fix.

**Comment by danac78** [comment]
Case in point:

8.1.1.23052201+nightlyupdate

I hit shift-r, Auto-forward is not activated and the "Auto" in the quick menu is not highlighted. 

@renpytom

**Comment by danac78** [comment]
@renpytom Furthermore, that didn't fix the issue. Auto-Reload is off, but Auto-forward is still turned on when I do clt-R. Unless I am missing a config variable to set to False.
