### ISSUE TITLE
'Launch Project' doesn't work.

### ISSUE THREAD

**Issue by koorsy** [renpy/renpy#4678]
Hi! First of all, i’m so sorry for my english, i’m not even close to be fluent.

Well, i need some help because i don’t know what else to do. When i click on “Launch Project” on the launcher it just don’t open, nothing happens. I’ve tried some things like update the app, download some programs that could help, restart the notebook but nothing makes it work. 

If someone could help me with this i would be so grateful. Thank you so much and sorry again.

**Comment by mal** [comment]
Take a look at the `log.txt`, `error.txt`, and potentially `traceback.txt` in your project directory. They may give you a hint as to what's going wrong.

**Comment by koorsy** [comment]
Hi! I found this.
![image](https://github.com/renpy/renpy/assets/134976049/18bbbc97-8f3c-4a2b-bc10-9935006960b9)

**Comment by Gouvernathor** [comment]
This should be solved in the last Nightly or Nightly Fix.

**Comment by koorsy** [comment]
Ooh, okay! I will try it! Thank you!!

**Comment by koorsy** [comment]
Ok, it didn't work too. I think it might be my notebook :/

**Comment by renpytom** [comment]
Could you try creating a new project with the nightly fix?

**Comment by koorsy** [comment]
Hi! Sorry for not answering before. I remember that i tried this too, but it got error and doesnt even create the project

**Comment by renpytom** [comment]
Just to check, what language are you using?

**Comment by koorsy** [comment]
portuguese
