### ISSUE TITLE
Search bar is less user friendly in new documentation layout

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#4682]
I am largely neutral about the new documentation layout, but one thing that seems like a clear downgrade is that you have to scroll all the way up the navigation in order to access the search bar. What used to be a simple task now always takes at least a few seconds. Considering how often I use the search bar, that wasted time really adds up.

Is there any chance you will restore the search bar’s old place, i.e. that it’s always accessible at the top, regardless of scroll position?

**Comment by the66F95** [comment]
i would also add a positive z-index attribute to keep the search box on top of the other scroll list elements.

**Comment by Gouvernathor** [comment]
The search bar is unusable when scrolled, in the current state of things.

**Comment by the66F95** [comment]
> The search bar is unusable when scrolled, in the current state of things.

adding `z-index: 1;` or any positive value solves exactly that issue.

**Comment by renpytom** [comment]
This has been fixed, I believe.

**Comment by Gouvernathor** [comment]
![image](https://github.com/renpy/renpy/assets/44340603/942961ee-4372-451d-b5c4-cb7d94b03da2)
Seems the search bar would benefit from a z-index greater than 1, so it's not behind the "other functions and variables", and from being completely opaque so that "model-based rendering" doesn't appear behind.

**Comment by renpytom** [comment]
![image](https://github.com/renpy/renpy/assets/379804/e3b9dd1e-a27d-430a-b050-d19fd7028a88)

The current version has a z-index of 1.

At least, https://www.renpy.org/doc/html/other.html#other-functions-and-variables seems to work.

**Comment by Gouvernathor** [comment]
Yup, I didn't pull before regenerating the doc. My mistake !
