### ISSUE TITLE
Renpy8.1: When using build.include_i686 = False

### ISSUE THREAD

**Issue by Tristimdorion** [renpy/renpy#4685]
There are two 64-bit exe files in the zip file when building "PC: Windows and Linux" package.

Haven't check the other build types.

**Comment by renpytom** [comment]
I'm not able to repeat this on a clean new game.

Do you have an exe file in the base directory that could be copied over?

**Comment by Tristimdorion** [comment]
Yeah, that's the problem, I've added a build.classify to exclude the .exe in the root and now its gone ;)
Thanks.
