### ISSUE TITLE
"focus_mask" does not work with drag objects

### ISSUE THREAD

**Issue by jagogames** [renpy/renpy#4686]
drag:
            drag_name "TV"
            pos(634,238)
            idle_child "tvbutton_red"
            selected_idle_child "tvbutton_green"
            focus_mask True
            draggable False
            droppable True
            
    Will provide a result where the entire image is sensitive to hover, regardless of alpha values.

**Comment by renpytom** [comment]
I don't 100% understand your example, as droppables should be sensitive to hover at all. However, the dropping algorithm only considers the rectangular size of the drag and the drop - it  doesn't consider the focus mask of either the drag or the drop. 

I'm not going to change that last par, but I will document it.
