### ISSUE TITLE
game version with compilation id or compilation date

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4689]
For example, if the version is 1.0.0 it could have a renpy generated compile id (1.0.0.[numeric id]) or maybe the date the game was compiled for distribution.

taking build_version as an example, this could get the version from config.version during compilation and apply the id to it. 
"[build_version]" //1.0.0.54234354 or 1.0.0.230610

idea based on https://www.renpy.org/doc/html/changelog.html#versioning

**Comment by renpytom** [comment]
https://nightly.renpy.org/current-8/doc/build.html#build-info

This has been done for a little while.
