### ISSUE TITLE
Preferences dictionaries are not persistent

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#4698]
So I recently set up a new preference variable that makes use of a dictionary:
```
default preferences.content_warnings = {
    "extreme violence": False,
    "death": False,
    "suicide": False,
    ...
}
```
On my settings screen, I then use: `ToggleDict(preferences.content_warnings, "extreme violence")`

While these settings work nicely across different saves, as well as when returning to the main menu, I've noticed they are **reset** whenever I **quit** or **reload** the game.

**Comment by the66F95** [comment]
that's the expected behavior. probably you might want to use the `_preferences` object.

**Comment by kigyo** [comment]
> No, you should use the persistent object directly. Preferences and the preferences and _preferences objects/modules are for builtin preferences, not for user-defined preferences.

Oh wow, I never knew that! Are there any "dangers" to using preferences instead of persistent? If yes, I feel like there should be some kind of warning - I've been doing it this way for 2 years and had no idea. (Mainly because I... well, _could_, and it felt cleaner to separate settings and progression-related variables.)

And thanks for the advice to separate them! I first thought it would be more tidy to have them all in a dictionary, but knowing myself, I will make changes to them down the line. Separate persistent entries is definitely wiser.
