### ISSUE TITLE
Some webm videos show a blackscreen and get skipped

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#4711]
Some webm videos are displaying as usual, but some others show a black screen before skipping (they have been used and functioned correctly from version 7.4 to 7.5).
At least on my comp, this one skips now:
[think.webm](https://github.com/renpy/renpy/assets/78823063/0166df5e-3c15-4eff-a058-bed6115b3fb9)
I have another one that plays fine, not sure what's wrong.

**Comment by renpytom** [comment]
Can you put together a short game that exhibits the problem? At least for me, the movie plays.

**Comment by Org-gith** [comment]
This worked inside a template project and made it work on the project, I found the 'issue', the two videos were defined like this:

image video1= Movie(play="bg/special_effect/think.webm")
image video2 = Movie(play="images/redikal.webm")

This used to work, video1 full path is actually "images/bg/special_effect/think.webm", and was cut to just bg/etc/, but this doesn't work anymore. 

This seems linked to this change:
```
File Search Ren'Py will now only look for image files in game/images, rather than all files. To look for all files in game/images, use:
define config.search_prefixes += [ "images/" ]

```
My bad, I'll be more cautious in the future.
