### ISSUE TITLE
renpy.loadable Ducomentation updates

### ISSUE THREAD

**Issue by lokanathshankar** [renpy/renpy#4712]
Hi Team, 
After latest renpy upgrade "renpy.loadable" no longer without adding appropriate search prefixes i.e"define config.search_prefixes += [ "images/" ]"
I think this is a breaking change in 8.1.1, it would be great to update the documentation on https://www.renpy.org/doc/html/file_python.html#renpy.loadable to indicate this change?

Thanks

**Comment by Gouvernathor** [comment]
This is not due to renpy.loadable itself but to a more broad change, I think. It is documented in the "File Search" section of the [incompatible changes](https://www.renpy.org/doc/html/incompatible.html#incompatible-7-6-0).

**Comment by Gouvernathor** [comment]
Possibly. We will look into it.
