### ISSUE TITLE
Parser bug that causes an uncaught exception.

### ISSUE THREAD

**Issue by duckdoom4** [renpy/renpy#4713]
I was going through the [parser source](https://github.com/renpy/renpy/blob/a33f891d65d3fd2b59a533c365800a59f8e15f0c/renpy/parser.py#L1167) and found this bug. See my comment [here](https://github.com/LuqueDaniel/vscode-language-renpy/issues/335#issuecomment-1583139711)

The parser will accept any statement to start with `init`, even `init` itself.
Leading to this possible error:
```
label start:
    init init offset = 0
```

```
I'm sorry, but an uncaught exception occurred.

While parsing .\the_question\game/script.rpy.
AttributeError: 'list' object has no attribute 'get_children'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.2.23060801+nightly
The Question 7.0
Thu Jun  8 20:39:16 2023
```

Just confirmed that this is valid and will parse without exceptions:
`init init init default testy = False`

**Comment by Gouvernathor** [comment]
First, the init block and statement is not documented (anymore), so we're sort-of covered on that end.
The issue is that the following is allowed, even though it's not very pretty:
```rpy
init:
    init:
        $ vale = "emerald"
```
It does parse and execute as intended, even with priorities being set.
I guess it's the specific case of the inline "init" that's a problem, not the block one. We could blacklist it with something like this:
```py
if l.match(":"):
    ...
else:
    if l.match("init"):
        raise ParseError
```
But perhaps a more comprehensive solution would be better.

**Comment by Gouvernathor** [comment]
The inline init was intended as a generalization of the `init python` logic to `define`, `image` and `style` statements (and `default`, though they didn't exist at the time) by this little guy : bb2a80f5e8e58add25ae125d32d8ca0865a78542.
I'm not sure what to make of it. Maybe the inline syntax should be restricted to a whitelist only, or be shelved in favor of the block and `init offset` version ? With a deferred error and an early config to go with it ?

**Comment by renpytom** [comment]
The inline init is meant to provide a way of adjusting the priority of various statements, as well as allowing things that won't normally run at init time to run at init time. 

While it doesn't make sense with every statement (I don't know what ``init play music`` would do before the music system is initialized), I think it's easier to write an ``init [ priority ] <statement>`` rule than try to allow specific things - especially when creator-defined statements are allowed.
