### ISSUE TITLE
Unexpected Transform Behaviour: x/y/zrotate

### ISSUE THREAD

**Issue by negatwo** [renpy/renpy#4715]
https://github.com/renpy/renpy/assets/84490762/78fa2b2f-6a3b-4c3f-8a79-7013601bcf93

Hi! In the first case I'm using the transform property:
`xrotate (30.0 if not phase else 0.0)`
And in the second case, I'm using this:
`xrotate (0.0 if not phase else 30.0)`

These should yield the same results (I think) but instead I get different behaviours between the syntaxes. I tested this behaviour for x, y, and zrotate and they all seem to follow the same pattern.

(Tested on Renpy 8.1.0)

**Comment by renpytom** [comment]
Can you post a more full example? I don't know what you're trying to do here, or what else is different.

**Comment by negatwo** [comment]
I have a toggle for a screen variable that controls the state of a displayable's rotation. So in its full context the code looks like this:
`
    frame xysize (1280, 1280):
        at transform:
            add "children"
            easein_quint 0.5:
            
                #CASE 1
                #xrotate (30.0 if not phase else 0.0)
                
                #CASE 2
                xrotate (0.0 if phase else 30.0)
`
There should be no functional difference between the two cases since it should just be interpolating between xrotate 0.0 and 30.0 or 0.0 and 30.0. Both should yield visually the same results. However, when I switch between the two cases it seems like xrotate transforms the image in an entirely differently way.

 I'll send a recording with less stuff moving parts to make it more clear in a bit, but I was just mostly wondering about that specific behaviour and what makes them so different.

**Comment by negatwo** [comment]
Sorry for the earlier confusion but upon more investigation it seems like its an issue with the order in which the transforms are applied. zrotate is supposed to be applied first according to documentation but goes last instead. Here's the code for my test along with a video:

https://github.com/renpy/renpy/assets/84490762/809e1d8f-ee6a-461b-9b9e-8419ecdb0580


```
screen ntwo():
    tag menu

    default rot = 0.0


    add Solid("#FDFDFD")
    frame at Transform(perspective=True, xrotate=30):
        background Transform("#000", alpha=0.3)
        xysize (1280,1280)


        #frame at Transform(xrotate=75, zrotate=rot):
        frame at Transform(matrixtransform=Matrix.rotate(75,0,0) * Matrix.rotate(0,0,rot)):
            background Solid("#00000030")
            for i in range(36):
                add RoundedFrame("#000", xysize=(25,25), radius=14):
                    at transform:
                        anchor (.5,.5) pos (.5,.5) around (.5,.5)
                        clockwise
                        radius 0.2
                        angle i*10

    key "mousedown_4" action SetScreenVariable("rot", rot+10)
    key "mousedown_5" action SetScreenVariable("rot", rot-10)
```

The Transform(xrotate=75, zrotate=rot) seems to cause the rotation on the z to be applied after the x rotation, while the manual multiplication with Transform(matrixtransform=Matrix.rotate(75,0,0) * Matrix.rotate(0,0,rot)) seems to yield the expected results.

**Comment by negatwo** [comment]
Reading over the docs that definitely does make a lot of sense. Thanks! Though it's not an issue anymore, do you happen to know why transforms on the displayable vs. the camera are applied in a different order? And if it'd be worth making them the same?

**Comment by Gouvernathor** [comment]
I think that's @kyouryuukunn's design, that's who you'll need to ask.

**Comment by kyouryuukunn** [comment]
In Ren'Py, camera rotation is actually displayable rotation; Ren'Py's rotation system is x, y, z. Rotating the stage in x, y, z order is the same as rotating the camera in z, y, x order.
 Rotating the camera in the order x, y, z is inconvenient because the z rotation does not rotate around the center of the screen. I thought it best to change the rotation scheme from x, y, z order to z, y, x order and rotate both the displayable and the camera in z, y, x order, but this was an incompatible change. This is why we rotate the camera in z, y, x order.

**Comment by negatwo** [comment]
If it's incompatible I guess that's too bad but thanks for clearing things up!
