### ISSUE TITLE
Exception: Audio channel is unknown

### ISSUE THREAD

**Issue by RaXorX** [renpy/renpy#4723]
Similar to [this](https://github.com/renpy/renpy/issues/4402#issuecomment-1585862749) was unsure if I the closed issue would be reopened or not.

This error still occurs when rollback is used.
Ah welps, it also happens when you reload in the middle of the playback as well...

**Comment by renpytom** [comment]
Question - does it happen during rollback from a new save, or only in older saves?

**Comment by the66F95** [comment]
i had similar problems once, was able to fix it with:
```
--- D:/renpy-sdks/renpy-7.6.2.23060902+nightly-sdk/renpy-7.6.2.23060902+nightly-sdk/renpy/display/video.py	Fri Jun  9 11:27:35 2023
+++ D:/renpy-sdks/renpy-7.6-sdk/renpy/display/video.py	Thu Jun  1 14:36:48 2023
@@ -439,2 +439,5 @@
 
+            self.ensure_channel(self.channel)
+            self.ensure_channel(self.mask_channel)
+
     def ensure_channel(self, name):
```

**Comment by RaXorX** [comment]
> Question - does it happen during rollback from a new save, or only in older saves?

Happens in new saves or new game as well (if I didn't save at all even) so it's not just a problem of loading a save game. And it also happens if I use Shift+R to reload the game
