### ISSUE TITLE
Ren'Py 7.6.0 deleting persistent data

### ISSUE THREAD

**Issue by RStar8** [renpy/renpy#4725]
We have 3 games in Steam, 2 of them made with Ren'Py 7.4.11 and a newly released one made with Ren'Py 7.5.3

We updated the first 2 game to Ren'Py 7.6.0 to make sure the olders games have Steam Deck support now. But now we got 2 issues.

1. Everyone of our players are loosing their persistent data after launching the updated game. I am not sure if it is an intended behaviour or not. So, I asked it here because I don't remeber seeing anything related to this in the changelog.

   Edit:- I also realized that my persistent data gets deleted if I launch a project (That was previously launched using Ren'Py 7.5.3 or 7.4.11 launcher) from Ren'Py 7.6.0 launcher.

2. After updating the games some of the players having the game .exe file and python.exe detected by their antivirus as trojan. When I tested I realized that none of the 64 bit .exe files were detected in VirusTotal but all of the 32 bit .exe were being detected as Trojan by 7 engines. And it was true for all the builds I made with Ren'Py 7.6.0 and 7.6.1, even a build of newly generated project.
Ren'Py 7.5.3 and 8.1.0 (I guess because it doesn't have 32 bit files anyway) doesn't have this issue.

This is a screen of the dectecton of 32 bit python.exe file - 
![image](https://github.com/renpy/renpy/assets/26844209/0a545d64-f1a0-4d4f-b480-8a1cc15af852)

I know it's a flase positive, but this doesn't help the players thinking our computers were breached by some malware or we are doing something shady behind their back. As far as I understand it is probably because Ren'Py 7.6.0 is relatively new? But is there any way we can prevent this from happenning or is there anyhting else we can do to prevent this except submitting false positive reports to the antivirus vendors?

**Comment by renpytom** [comment]
1. Sounds like it may be one of two things. The first is that loading persistent files for a particular game is a one-way thing - Ren'Py will upgrade the game to use secure persistent files once, and after that it won't allow insecure persistence files for a particular game. It should migrate the file once, but we don't support toggling back and forth between old and the new versions.

One test you can do to make sure this is working right would be to create a  brand new game in 7.5.3 and then load it in 7.6.1. It should retain any persistent data you set. 

The other possible problem is you put something in Persistent that doesn't belong there, and that is no longer in the current Ren'Py. (Like an internal class.) That can cause a problem loading persistent files, which are limited to basic types (int, string, bool, dict, tuple, list). 

2. Is not something I can handle. If the antivirus software is operating incorrectly, it's up to the creators of that software to fix their problems.

**Comment by RStar8** [comment]
Okay. So, I did what you suggested and yes making a new project in 7.5.3 and  then loading it in 7.6.1 does retain the persistent data.
So, I think the problen for our case is the other possiblity you meantioned as we use a modified version of Ren'Py's Multipersistent save system. Our save system allows players to save and load specific playthroughs between different games because it is a 3 part game.
Anyway thanks a lot for your fast response and guidence. Appriciate the help

**Comment by RStar8** [comment]
Now our players are having a similar but new issue. Every time they launch the games their persistent data saved during last session (window size, preferences, gallery etc.) are getting reset. A lot of reports has been appearing from our Steam players recently. One of them sent this log to me and ho[pefully someone caNn help me understand what is going wrong here -
`Thu Nov 30 21:45:44 2023
Windows-10-10.0.19041
Ren'Py 7.6.0.23051307
 
Bootstrap to the start of init.init. took 0.03s
Early init. took 0.00s
Loader init. took 0.01s
Loading error handling. took 0.03s
Loading script. took 1.27s
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading save slot metadata. took 0.01s
Loading persistent. took 0.00s
Faled to initialize steam: Exception(u'Init returned false.',)
Set script version to: (7, 6, 0)
Running init code. took 0.12s
Loading analysis data. took 0.02s
Analyze and compile ATL. took 0.03s
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Reloading save slot metadata. took 0.03s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache. took 0.00s
Making clean stores. took 0.00s
Initial gc. took 0.08s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object. took 0.11s
Cleaning stores took 0.00s
Init translation took 0.09s
Build styles took 0.00s
Load screen analysis took 0.01s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.04s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start. took 0.17s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'NVIDIA Corporation'
Renderer: 'NVIDIA GeForce RTX 4090/PCIe/SSE2'
Version: '4.6.0 NVIDIA 546.17'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1739, 978) drawable=(1739, 978)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
controller: u'030000005e0400008e02000000007200' u'Xbox 360 Controller' 1L
controller: u'030000005e0400008e02000000007200' u'Xbox 360 Controller' 1L
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
`
I don't understand why this incorrect header check might be happening. Hopefully someone from here might be able to help because I asked in Ren'Py Discord and no one was able to help unfortunately.
Any way only one thing worth mentionning is that the games are using the mutipersistent feature of Ren'Py, I don't know if it has anything to do with it.
