### ISSUE TITLE
Speed up renpy reload at expense of potentially delayed images

### ISSUE THREAD

**Issue by brunoais** [renpy/renpy#4726]
# Introduction

I'm currently working on a VN and I'm having `layeredimage`s made of many images.

In scenes where 3-4 characters are present, if I request a reload, the reload is causing renpy to **take 7-10s**. This is after I changed the images into webp. When I tried avif, it was slower possibly due to a mix of `image_load_lock` lock and the difficulty in decoding `AVIF`.

# The most annoying

The most annoying part is that, usually, the image files are very often unchanged. I'm just changing the script and checking if the result is to my satisfaction. 
I'm either editing the text or I'm even just editing styles or transitions to make sure the characters are moving or being placed where I want them to. I'm using `renpy-ActionEditor3` which is a huge time-saver but I still need to tweak and make sure of what I'm setting. It also doesn't have everything.

# My intent as a question

Is there a way to speed up reloading at the expense of not dumping the currently showing sprites from memory when reloading?

# The solution in theory

In theory, this would be just, when `UtterRestartException` is raised, move the loaded sprite images to a class that isn't reloaded (or keep them in the stack) and place them back to their correct placement when reload finishes. To make it better, a prediction thread would start for the current displaying image which would replace the images with the correct ones if they changed.
I believe the reality isn't as easy as that.

More memory wasteful but something potentially considerable could possibly be also just be keeping `im.cache` intact during a reload... But the data is dumped elsewhere already, so keeping that instance wouldn't be enough. Additionally, it would be much harder to then replace with the new image, after the image finishes loading.

# The ideal way it would work

Ideally, I'd like an optional fast reload composed of:

1. Dumps all "memory" and optionally images. (currently it's not optional)
2. Saves the game (very fast)
3. Loads the scripts (screen just shows `Reloading script...`)
4. Displays the VN as currently is (`Reloading game...` would appear front and center)
4.1. Reuses images that were loaded previously
5. Loads gui images (I.e. textbox, buttons, etc...)
6. Loads background (I.e. What is showing due to a `scene` statement and equivalent)
7. Loads sprites (I.e. What is showing due to a `show` statement and equivalent)
8. `Reloading game...` disappears

I'd make the `Reloading game...` removable too.

# Possible middle-ground alternative.

Similar to above but images aren't shown until the modification time as recorded by the filesystem is checked. If the image was modified according to that, keep the same behavior as now but just for those images. (showing `Reloading game...` until the images are reloaded).

# I tried to record how long the reload takes

I set `define config.profile_reload = True`.
It says it took ~1.3s to reload. I think it doesn't take into account the time it takes to load the images for the `Reloading game...` part. It's definitely taking ~7s until `reloading game` disappears from the screen where there's 3 simultaneous characters.

# Final note/clarification

Whatever is done according to this issue, it only affects if `renpy.config.developer` is `True` or ends up being `True`.

# My setup

I'm using renpy 8.1.1.
I'm using linux.
I'm using an M.2 NVMe SSD.

**Comment by renpytom** [comment]
Can you make a small game that  exhibits the problem in a click or two? I'd like to see the problem myself, and then I can determine an ideal way to fix it.

**Comment by brunoais** [comment]
> Can you make a small game that exhibits the problem in a click or two? I'd like to see the problem myself, and then I can determine an ideal way to fix it.

I'm under an agreement to not share this VN publicly. If I can send you privately, I can get that for you.

**Comment by brunoais** [comment]
@renpytom Another option would be me trying to replicate using images I make myself in a new project. That way I can share publicly.

**Comment by renpytom** [comment]
Either one would work, provided it's the sort of game that can exhibit the problem in 1-2 clicks. I don't want to have to diagnose this on a large game with gigabytes of data files and half a minute of splashscreens. 

My email address is pytom@bishoujo.us. For google drive related files, use renpytom@gmail.com.

**Comment by brunoais** [comment]
That's very reasonable. I'll put together an example where I remove all the fluf at start the start sends directly to one of the dialogues with the issue. I'll also remove all the images that are not part of this to try compacting it.
Thank you. I'll give news when I can.

**Comment by brunoais** [comment]
@renpytom Were you able to check out the e-mail I sent on tuesday (13th June)? It was sent at around 2PM PST.

Without any hurry. Is there any sort of ETA you can provide? Is it sometime within this month or maybe next month?

**Comment by renpytom** [comment]
I did get the email. I'll look at it when I get to it - possibly this weekend.

**Comment by brunoais** [comment]
Awesome! So I'll organize myself for some sort of answer (even if asking for more time) sometime this weekend or next weekend. Thank you!

**Comment by renpytom** [comment]
The answer to this one is a 'no' - because of the way Ren'Py stores images, I don't think it's going to be possible to speed up the cache like this. Ren'Py doesn't store the image files in the cache, it stores textures, and right now it makes the assumption that images can be reloaded fairly quickly. (You'll also see a slowdown when you resize the window.) 

Your game is loading something like 25 images in the 8-9 megapixel range, and that's just a bit much. You can look to see if you can use a lower png compression setting - that can speed things up. But your real improvement would be to crop the images, and tell layeredimage to display them as an offset. 

Fundamentaly, I don't think this is something I can address anytime soon. I can leave this open as an enhancement requests, but it's going to be something long-term, as it would require massive changes to Ren'Py to pull off.

**Comment by Org-gith** [comment]
If you are willing to use GL1 to develop the game (just for the editor for example), I know a trick to keep textures beyond reloading on that renderer. That trick doesn't work on GL2. Could be something until a long-term solution is found in your case (is not meant to be an issue or anything).

**Comment by brunoais** [comment]
@renpytom In that case, is there a way to make a different approach for now?

Maybe as a plugin to renpy. Detect new and modified files. Create a cache directory (or make use of the cache directory) with smaller or lower quality versions of those files. If renpy is in dev mode, the config is active and not predicting, load the lowres, faster to load version of the file. If the file was updated, load the new version.

I think I'd be able to do such code but I'm not sure where it's safe to apply the changes.
If the images could be scaled down and then bloated in renpy, that would help a lot too. I tried doing that but it didn't work. I can make `layeredimage`s smaller using a transform but I can't find a way to make them bigger.

E.g. 

```
layeredimage eileen:
    xsize 2000
    ysize 4000
    attribute a
    attribute b default if_not "a"
    attribute c default if_not "b"
```

If the images are 1500x2000 (to make numbers easier), they the layeredimage isn't getting larger to fit the size.
I think both together would help a lot for an alternative approach using lower res and lower quality caching for fast reloads.

**Comment by brunoais** [comment]
> If you are willing to use GL1 to develop the game (just for the editor for example, not the actual game published), I know a trick to keep textures beyond reloading on that renderer. That trick doesn't work on GL2 (is not meant to be a github issue or anything). Could be a stop gap until a long-term solution is found in your case.

I'm not choosing which GL, so whichever I think it will work for the purpose. In this case, it's just to have fast reloads, at least, when the images aren't updated.

**Comment by Org-gith** [comment]
Never mind, spent one hour on this and it doesn't seem actually possible in the case of reload. I was using it for keeping the textures between loading and saving saves, returning to the menu, and resizing windows (this only works on GL1). The thing is that reload_script calls utter_restart and that's it, there seems to be no way to tell him to keep the textures in that case (not in my limited knowledge at least).
I think one possible solution would be to use low-resolution images for development and then scale the code with a multiplier for release maybe through a variable (if you really want to keep the very high resolutions images). Or use oversampling but not sure how it works.

**Comment by brunoais** [comment]
> I think one possible solution would be to use low-resolution images for development and then scale the whole image code with a multiplier for release maybe through a variable and to put the high resolutions pictures then (if you really want to keep the very high resolutions images). Or use oversampling but not sure how it works.

I've seen that `Image` has [oversample option](https://www.renpy.org/doc/html/displayables.html#Image) but I'm still unable to correlate how can I make use of it for this purpose. But then 

> (Actually, the user documentation is a bit misleading, as
     this tries for compatibility with several older forms of
     image specification.)

oversampling appears to be done like this:
```
                rv = renpy.display.render.Render(ce.width * inv_oversample, ce.height * inv_oversample)
                rv.forward = renpy.display.matrix.Matrix2D(oversample, 0, 0, oversample)
                rv.reverse = renpy.display.matrix.Matrix2D(inv_oversample, 0, 0, inv_oversample)
```
Renders and then moves the image, apparently. I guess I can only try by testing if my proposal for changing the image and caching the changed image works for this purpose...
