### ISSUE TITLE
Old project launch issues on 7.6.1 + editor troubles

### ISSUE THREAD

**Issue by Redorianin** [renpy/renpy#4727]
Newly created projects work fine, but when I try an older one, made on a different version, I get different errors during game start up. Not even getting to the main menu. It feels like the game displays the last error I had for the project when I worked on it in 7.6.0

My main project I tested gave me an error for a missing image scene, even though it was there. It was like the file wasn't detected. Another issue is why was that giving an error at all? Normally a missing scene would simply display a gray background once u get to it. But this somehow prevented the game from launching at all. I think the missing scene was from the last event I was working on. So it would be the last displayed and edited scene.

Another project gave me an error for a line in a custom made screen. Basically a name of the location. The error said that unicode does not have an attribute. I think this was an error I had during initial testing of the screen, but managed to fix it eventually. Why it shows up now and during load up instead when loading a save? Idk.

Furthermore, I tried changing the code in the last project, to make it load, and discovered that I cannot save my old projects in atom. Any changes I made are not saved. CTRL + S or file- save do not save the files. I made a new project and it worked 100% fine.
I have reverted to 7.6.0 and things work fine again.

**Comment by renpytom** [comment]
Please post the errors your'e getting in individual issues, so we can work on them one at a time. I can't accept multiple issues like this, as it'll be impossible to discuss them. 

Atom is no longer supported by it's creators. I'd suggest switching to VS Code. (There may also be a permissions issue with your project - like if some of the files are read only - which would explain the different errors you're getting.)
