### ISSUE TITLE
[Renpy 8] Problem with a Cyrillic characters

### ISSUE THREAD

**Issue by linakima** [renpy/renpy#4728]
For Renpy v8. If the path to the SDK contains Cyrillic characters, you will not be able to start or create a new project.

This was not an issue in version 7.
Cyrillic characters for test: ывалоцукнгш

**Comment by renpytom** [comment]
What encoding is your system set to? What platform are you on?

**Comment by linakima** [comment]
> What encoding is your system set to? What platform are you on?

Windows 10 / Pro 22H2 / build 19045.3086
I opened the regional standards and enabled the unicode support (utf-8). Now everything works fine :)

![1](https://github.com/renpy/renpy/assets/34077156/621238b3-4a64-4634-ad70-4190df0640ab)
