### ISSUE TITLE
Security message for unofficial game files

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4729]
I suggest adding a security message for files that are not official game files. Like game saves, it is possible that rpy or rpa files created by third parties for a particular game are malicious, this warning is not intended to prevent piracy. But be aware that you may be accessing PC resources without the user's consent, for example the IP address or data of the PC itself that Python can access and then send to the attacker with a request.

Currently renpy loads any rpy or rpa file that is in the `/game` directory, so it could be used for malicious purposes. for example, a basic script that can be loaded without the need for any extra packages: 

```
init python:
  import requests
  import json
  try:
    print(json.loads(requests.get("https://ipapi.co/json").text)) 
  except Exception as e:
    raise e
```

This script returns exactly the user's location, and also the IP address. This information can be used for malicious purposes, besides making a request there are Python actions that can breach the user's security.

That's why I come with this suggestion to add a small warning when trying to load a file that is not the game's own, how could the files be validated? Well, the game could keep a persistent list of created files and then commit it or maybe renpy could sign the files and then confirm if one or more files do not belong to the game.

**Comment by HorBro38** [comment]
This would ruin my project, so if implemented I would need a way to disable it.

**Comment by Neyunse** [comment]
> This would ruin my project, so if implemented I would need a way to disable it.
I understand it can happen, but it's better than some person stealing data from players and then trying to blame the developer.

**Comment by mal** [comment]
At the point that there are malicious files in a distribution, you've already lost. Any detection system would be trivial to circumvent and so at best it would give a false sense of security.

As with any software acquired from the internet, if you don't trust it, don't run it. Promoting that message alongside the official distribution channels of your project is probably the best approach you can take.

**Comment by Org-gith** [comment]
I think it's too much, even token security was a bit borderline for me. Don't turn Ren'py into an annoying av and let the users take responsibility for their actions like it is the case for most engines, especially this one that is only single-player games or let creators opt out of it if he wants, this would avoid a lot of problems/bugs within the software in general.
I don't think anyone trusting someone that sends him malicious files and gets something bad of it will ever blame a creator or Ren'py, that sounds absurd to me.

**Comment by AdultVisualNovels** [comment]
You want to warn users that your own distribution might contain malicious files? Tell them the only safe place(s) to download trusted distributions and leave it to the end user not to obtain your work elsewhere. Who else are we warning here, software pirates who deserve to have malware packaged in the distribution?

**Comment by Booplicate** [comment]
I don't think people are getting this right. Even if your distribution is valid, nothing will stop a malicious script that got added to game directory afterward from running.

**Comment by AdultVisualNovels** [comment]
> I don't think people are getting this right. Even if your distribution is valid, nothing will stop a malicious script that got added to game directory afterward from running.

Think about that for a minute. Someone has to obtain the distribution, unpack it, unarchive it, add malicious content, rearchive it, repackage it, and redistribute it. The only way anyone obtains that distribution is from an unauthorized source. If that's how someone is obtaining my work, I want them to get what they deserve. I need to warn them that stealing my work from third party sources is not only illegal and unethical but might also contain malware not added by me?

**Comment by Booplicate** [comment]
Best part: you don't need to unpack, put, repackage, or whatever. You just put any malicious python code in `breaksystem.rpy`, put the script in a directory of any renpy game and voila!

**Comment by Org-gith** [comment]
And how do you access their computer to do that against their own will?

**Comment by brunoais** [comment]
The only way to do this kind of thing is with immutable packaging or immutable disk images (E.g. flatpak, snap or android' apk).
For all I know, doing this on windows in a way that isn't easily bypassable except if the player installs a ring0 driver is pretty much impossible. It will always be easily bypassable.

**Comment by renpytom** [comment]
I don't think this is something that I'm likely to address, at least directly. 

By the time someone puts a .rpy file in the game, they can just as easily put a .py file into the renpy/ directory. Or they could put a .exe file in the base directory. So I don't think that there's a ton of security benefits to warning against the player modifying the game in one particular way. 

The token security is different, as the save files don't really convey that they're executable - it's something of a surprise that modified game files can run code. That's why I made the change. I don't think it's surprising to anyone that a mod can change how the game runs, even in malicious ways - that's the point.

This doesn't mean we shouldn't, long term, pursue a code-signing solution that covers all the game's files, perhaps using some sort of root-of-trust baked into a signed executable. But what this issue presents doesn't seem likely to solve real problems.
