### ISSUE TITLE
Do not hide movie after playback ends

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4732]
Right now, every movie with a disabled loop hides after it finishes playing. Is it possible to add an argument that changes this behavior, or add another one - `end_image`?

**Comment by HorBro38** [comment]
The `image` argument does just this, has the image appear after the video is ended.

**Comment by lauwurence** [comment]
Hmm, yes... But it seems a little bit strange for me. I would expect that `image` is an alternative displayable for the movie, like if the movie file doesn't exist or it's too performance costy. But not as the final frame.
It leads to the issue when we have an ATL animated image as alternative for Movie. And then when Movie ends, the ATL one is shown.

**Comment by Gouvernathor** [comment]
I think it makes sense to add an image specifically fir the end and that would override that image parameter

**Comment by HorBro38** [comment]
@Gouvernathor I'm not sure if this is possible, but if there could be an attribute to just have it hold the last frame at the end of a video I think that would be used a lot.  Most people looking for help on the discord on how to add a custom image just want it to be the last frame of the movie.

**Comment by Gouvernathor** [comment]
Yes, but that may not be a simple thing to do and generalize to every platform and backend out there. Consider that it's the reason why we can't have the runtime of mp3 files...
But if it can be done easily it may replace the need for a specific end image. I think the best thing API-wise would be to replace the loop parameter with something that sets what happens at the end of the movie: either show the movie again, show the last frame, show the replacement image, show another image, show transparency...

**Comment by renpytom** [comment]
I've added keep_last_frame, but you can get this in Ren'Py 8.1 by giving the movie a unique value for its group parameter.

**Comment by lauwurence** [comment]
Wooow, thank you! 🤗

**Comment by HorBro38** [comment]
Oh wow, thanks Tom! (gets ready to remove a bunch of code they had to emulate this behavior)

**Comment by HorBro38** [comment]
I was testing this in the latest nightly (8.2.0.23062307+nightly) and it's not functioning - plays to the last frame, then disappears.

**Comment by HorBro38** [comment]
This issue is resolved and working as of 8.2.1; it can be closed.

**Comment by lokanathshankar** [comment]
Hi, Just a quick observation. When you use keep_last_frame and let the clip/movie play to the end, advance couple of images or interactions and then upon rollback the last frame from the video is not getting retained. I hope this isn't a intended feature, atleast from the player perspective we have to treat the last frame as an displayable and load it back upon rollback is what I feel. 
This observation is with Renpy 8.2.1.24030407.
**PS : oh btw this is an amazing enhancement.**

**Comment by renpytom** [comment]
@lokanathshankar's issue is now #5564.
