### ISSUE TITLE
Documenting _last_say variables.

### ISSUE THREAD

**Issue by Lezalith** [renpy/renpy#4733]
There are four variables in question:
- **_last_say_who**
- **_last_say_what**
- **_last_say_args**
- **_last_say_kwargs**

All are undocumented because of their internal use (I'm guessing), but are being used fairly commonly by programmers. The only harm I see in documenting them is that people could decide to set them directly and cause a mess, but hey, they can already do that with plenty of variables.

If you agree, I'll write (Or have @Gouvernathor do so :P) them onto the Store Variables page.

**Comment by Gouvernathor** [comment]
I don't think that's a good idea, for several reasons.
First, the data is just wrong. `_last_say_who` is a string of code that _evaluates_ to the last speaking character. The others look right-ish in that regard (though kwargs is unexpectedly not-empty), but this one leads people towards using `eval`, which is wrong. It could be used as a black-box character identifier, at best.
Second, you can and probably should implement all that cleanly, using a character callback, or a [say arguments callback](https://nightly.renpy.org/doc/config.html#var-config.say_arguments_callback). The latter enables you access to the speaking character (the actual one, not some string), the args and the kwargs, which you can choose to save in a variable you created and manage so as to access them later. And that can enable you access to a larger history than just the last entry.
That doesn't give you access to the spoken text though, so maybe there isn't a workaround for `_last_say_what`. But that doesn't mean they should.

**Comment by renpytom** [comment]
Hm... how about a function renpy.last_say(), that returns an object with who, what, args, and kwargs fields on it. The who field could be a property that evaluates when called, and return the Character object.
