### ISSUE TITLE
My backgrounds, buttons and characters appear grayish

### ISSUE THREAD

**Issue by Lilyops** [renpy/renpy#4734]
Hello,
When i creat my project and start adding image, I noticed that it appears greyish. I looked for where it came from, without finding. I create a new project and the same problem appears (i do some project in another version where i have no problem). I would like to know if anyone has the same problem or where it comes from. ( i have the version 8.1.1)

Tanks :)

**Comment by renpytom** [comment]
Can you post the images? 

There are several causes for this, but it's possible that some of your equipment is doing color correction, which Ren'Py doesn't do. (It assumes you got things right.)

**Comment by Org-gith** [comment]
This looks like a problem I ran into in the past, basically what Tom said, if you, for example, save your image with the extended color or a color profile within the file that can only be loaded by Photoshop or whatever app you are using to make the image, it could create such issues. Also... if your monitor has a color profile, maybe it's only implied in certain apps but not everything, it's a pretty complicated topic and it's hard to understand every detail about it. 
Maybe try to make sure your app is running the default which should be:
![medieval-blacksmith-clothing-belt-shoe](https://github.com/renpy/renpy/assets/78823063/984a83bb-6e2b-46d2-8c66-b2ae1cda5f73)

**Comment by Lilyops** [comment]
That works !! thanks you two ! (i was in rec.2020 on krita)
