### ISSUE TITLE
Bubble boxes don't take transitions like dissolve

### ISSUE THREAD

**Issue by fablackstar** [renpy/renpy#4735]
I've been using the new bubble boxes (greatly anticipating 8.2), but it doesn't seem like box transitions like dissolve work when using window show/hide statements, while still working with regular textbox.

**Comment by renpytom** [comment]
Correct, but I don't think this is an error. With the bubbles, unlike ADV dialogue, there isn't a text box that can be displayed empty while the dissolve occurs. 

For bubbles, if you want something transition-like, your best bet would probably to be a transition with an "on show" clause. I'll add that to the documentation.

**Comment by fablackstar** [comment]
![image](https://github.com/renpy/renpy/assets/48921192/7d9aa7a4-59a7-4fed-af9c-64805e6f5854)
![image](https://github.com/renpy/renpy/assets/48921192/12177c66-fbe2-4f47-8655-fd42aa1483d5)


while adding a transform directly to the screen works great, it does cause the transform to play every time there is a wait tag in the line, making the transform apply multiple times within a single line. I'm sure it also might act that way with some other text tags.
Any suggestions to make this better?
