### ISSUE TITLE
Document the `play movie` statement

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4737]
Apparently it's an equivalent as a statement of the `renpy.movie_cutscene` function. It's very counterintuitive to have a `play` statement have a consequence, if and when that is not documented as its own statement (as the special case that it seems to be).
Either that or, if it's unintended behavior (but it really doesn't look like it is), it should be disabled.

**Comment by renpytom** [comment]
This is intentionally undocumented. It was useful in the past, now it's not, but it's retained for compatibility with older games.

**Comment by Gouvernathor** [comment]
Then we should probably warn not to use the play statement or the play function on a channel called movie or on which movie=True was passed to register_channel
