### ISSUE TITLE
Renpy cannot detect System-wide Installed VS Code

### ISSUE THREAD

**Issue by RaXorX** [renpy/renpy#4739]
![image_144](https://github.com/renpy/renpy/assets/44987810/1f54a4d8-0dfd-44b8-b9d6-ee64b06968cc)
My VisualCode editor is installed systemwide (not per user, but for all users - [link](https://go.microsoft.com/fwlink/?linkid=852157)

I haven't tried with the per user install. 

![image](https://github.com/renpy/renpy/assets/44987810/09dfb397-93bb-4f2a-9bd7-40265e47d822)

**Comment by renpytom** [comment]
RENPY_VSCODE needs to be set to the path to code.exe, not to a directory.
