### ISSUE TITLE
Renpy Can't recompile project

### ISSUE THREAD

**Issue by RaXorX** [renpy/renpy#4740]
Renpy out of nowhere stopped recompiling my projects at all. 

`Launch failed. command=['E:\\Renpy_Work\\renpy-8-sdk\\lib\\py3-windows-x86_64\\pythonw.exe', 'E:\\Renpy_Work\\renpy-8-sdk\\renpy.py', 'E:\\Renpy_Work\\Projects_8\\Test', 'compile', '--json-dump', 'E:\\Renpy_Work\\Projects_8\\Test\\game\\saves\\navigation.json', '--errors-in-editor'], returncode=1`

Tried updating Renpy to no avail. Delete Persistent still works, which, from what I noticed also recompiles the project back again. Yes, the project launches just fine without any errors at all. 
It happened with 1 project then the other 2 started doing the same.

**Comment by renpytom** [comment]
On discord, this was tracked down to errors in the game script that hadn't been detected in the past, but are now.
