### ISSUE TITLE
Feature Request - Optional Save Security

### ISSUE THREAD

**Issue by multimokia** [renpy/renpy#4742]
I'm opening a request to make the save security introduced in renpy 8.1 *optional*.
I work on a larger project that often invovles saving/restoring multiple persistents not only in testing (literal tens of different circumstances based on persistent data collected over months of playtime) but in practice in case the user (again long-form [endless] game) may need to restore from backup persistents due to the nature of it.

The save security has completely tossed the backups and save system we have out the window and there doesn't seem to be a clear way to disable it, nor was it listed on API changes. As such I'm making a request to allow disabling of the system.

If not, would it be possible to point me to what I might have to change to disable this myself? This has quite literally been game breaking for us

**Comment by renpytom** [comment]
I don't plan to disable save security. It's genuinely important, despite the problems it causes.

**Comment by multimokia** [comment]
Nevermind, I looked more into it, potential ACE via pickle. Okay fair enough there
