### ISSUE TITLE
bubble.json never removes bubble positions for old line identifiers

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4743]
The [doc on speech bubbles](https://www.renpy.org/doc/html/bubble.html) says that lines are identified the same way as the translation system. I could verify that indeed, local changes modify line identifiers, causing edited bubble positions to break. Adding something like `id start_d220198f` after a line will freeze it and protect the bubble position, as suggested in translation tips.

However, I also noticed in my VCS diff that if you don't freeze the identifier and redefine bubble position, a new bubble position is added, and the old one never removed. This can stack up a lot of unused data in bubble.json.

Is it intended for retro-compatibility with older versions of the text? In case dev undoes some changes in text while keeping latest bubble.json? Or is it something inherited from the translation system, that was simply not changed for bubbles?

Is there a way to force cleanup of old ids? I don't see such a button in the Ren'Py launcher.

**Comment by renpytom** [comment]
I's more just that it's not a big deal to have old information in the JSON, and I prefer not to have Ren'Py automatically delete data.

**Comment by hsandt** [comment]
OK, so any way for us to identify if an ID is used or not, even if we have to write a custom script? Then someone could write a 3rd party tool at least.

**Comment by Gouvernathor** [comment]
Unofficially, you can do it like this
```py
def does_identifier_exist(id):
    for nod in renpy.game.script.all_stmts:
        if isinstance(nod, renpy.ast.Translate) and (nod.language is None) and (nod.identifier == id):
            return True
    return False
```
This code must never end up being used in a distributed game, you should only use it while testing your own project. It relies on undocumented aspects of Ren'Py and may break in any future version. Also it's pretty unoptimized.

Maybe we could make a function like that public ?

Also, since we lint orphan translations (#4314), we could lint orphan bubble data too.
