### ISSUE TITLE
Ctrl key skipping anomaly in 8.1

### ISSUE THREAD

**Issue by ZusYar** [renpy/renpy#4748]
It's impossible to interact with anything while holding the "ctrl" key.
Easily noticeable when you reach, for example, choice menu screen.
You can't choose unless you release the "ctrl" key.
This behaviour appeared in renpy 8.1 only and it's inconsistent with "tab" skipping.
(tab enables the skipping mode and you can click anything in this mode)

**Comment by lauwurence** [comment]
Here https://github.com/renpy/renpy/issues/4529

**Comment by renpytom** [comment]
This is an intentional change, as discussed in #4529. The fix is to let go of ctrl before you click.
