### ISSUE TITLE
Using ComposeTransition with a MoveTransition as primary requires MoveTransitions as secondaries

### ISSUE THREAD

**Issue by jedestep** [renpy/renpy#4750]
When using a `ComposeTransition`, if you supply an instance of `MoveTransition` for the first argument (`trans`), you must also supply instances of `MoveTransition` for the `before` and `after` arguments (if supplied). This requirement is triggered by [this line](https://github.com/renpy/renpy/blob/06d6d4b1ef1854a154c49bdfdce9bf308f87847c/renpy/display/movetransition.py#L520), which expects transitions merged with a `MoveTransition` to have a `layers` attribute. `layers` is not defined on any other transition type.

If this behaviour is intentional, it should be mentioned in the documentation.

**Comment by jedestep** [comment]
Functioning example:

```
init python:
    define.move_transitions("exit", 0.25, in_time_warp=_warper.easein, out_time_warp=_warper.easeout, old=True, layers=['main'])

define leave = Dissolve(0.25, time_warp=_warper.easeout)

define exit_left = ComposeTransition(exitoutleft, before=leave, after=None)
```

Calling `exit_left` will trigger an `AttributeError`.

**Comment by Gouvernathor** [comment]
22a1e0525b498444bd6b0b92b2d83d79391acff2 changed this from raw_layers to just layers, but reverting that to raw_layers doesn't solve the bug.

**Comment by jedestep** [comment]
Yeah, this bug was present in 8.0.3 as well, giving the attribute error for `raw_layers`.

**Comment by Gouvernathor** [comment]
What's the intended behavior ? Are you sure you're not confusing ComposeTransition with MultipleTransition ?

I'm actually surprised putting a move as the *main* transition in a ComposeTransition works at all when providing accessory transitions (i.e : when those are other moves). MoveTransition needs to access the sprites inside what it accesses, and if you flatten the input or output scene, it can't access it.
It actually makes sense to document this as a limitation of move transitions, I think. I also don't know how those would behave when used in ATL's [`with` feature](https://www.renpy.org/dev-doc/html/atl.html#expression-statement), it's likely to lead into problems too.

**Comment by jedestep** [comment]
The intended behaviour was to do a move and a dissolve simultaneously. Using the move as the secondary transition and the dissolve as the primary transition works fine.

It's fine if this is the expected behaviour, or if changing this wouldn't be worth it. However, I do think it's worth it to document this limitation, either as part of `ComposeTransition` or `MoveTransition`. It wasn't clear that this use case was unsupported, and it didn't produce an error that clearly indicated the issue.

**Comment by Gouvernathor** [comment]
As I see it, there are two solutions : either coming up with how composing such transitions is supposed to work (and in that case, figuring if there's a reasonable use-case for that behavior), or documenting that move transitions are limited and should only be used in `with` statements in renpy scripts excluding any form of composition or use in ATL (unless proven that it works).
In the latter case, I think it may be worth it to add a try/catch, or a type check, to raise a more appropriate and understandable exception in that case (such as in your code).

**Comment by renpytom** [comment]
Movetransitions are intended to be quite limited.

**Comment by renpytom** [comment]
1a62894650ab834c452f5e8f35ee75bf6fad4417 adds a check for this.
