### ISSUE TITLE
Reload application (SHIFT + R) crashing the application

### ISSUE THREAD

**Issue by manuelifeno** [renpy/renpy#4754]
When reloading the game using SHIFT + R the game crashes without an error message after 1 to 2 seconds. I have done a decent amount of debugging to see if I could fix this, and the issue seems to be that Renpy doesn't like my main monitor anymore. It used to work just fine. My main monitor is a 165Hz monitor, 1440p resolution. Changing the resolution or refresh rate doesn't fix this, I have to fully disconnect it to prevent the crash. I am using Renpy 7.4.11, but this happens on the newest version as well. There is no crash log or traceback. The only thing I can see is this in the log:

Sun Jun 18 12:48:24 2023
Windows-10-10.0.22621
Ren'Py 7.4.11.2266
 

**Bootstrap to the start of init.init took 0.05s
Early init took 0.00s
Loader init took 0.01s
Loading error handling took 0.08s
Loading script took 0.33s
Loading save slot metadata. took 0.00s
Loading persistent took 0.00s
Imported steam.
Set script version to: None (alternate path)
Running init code took 0.27s
Loading analysis data took 0.04s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.03s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.24s
Cleaning stores took 0.00s
Init translation took 0.03s
Build styles took 0.00s
Load screen analysis took 0.02s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.05s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.03s

Initializing gl2 renderer:
primary display bounds: (0, 0, 2560, 1440)
swap interval: 2 frames
Windowed mode.
Vendor: 'NVIDIA Corporation'
Renderer: 'NVIDIA GeForce RTX 3090/PCIe/SSE2'
Version: '4.6.0 NVIDIA 536.23'
Display Info: None
Screen sizes: virtual=(800, 600) physical=(805, 604) drawable=(805, 604)
Maximum texture size: 4096x4096**

Things I have tried:
Changing Nvidia control panel settings
Changing monitor settings
Changing render mode of renpy
Locking renpy's refresh rate to 60
Uninstalling the latest windows update
Updating nvidia drivers 
Changing monitor connections on the graphics card
updating to latest version of renpy
giving admin rights to renpy
Compatibility mode for renpy

**Comment by renpytom** [comment]
I don't have any idea. You might want to file an issue with Nvidia, to see if there might be some sort of unknown issue with their drivers. 

I don't see anything I could do to resolve this here.

**Comment by manuelifeno** [comment]
> I don't have any idea. You might want to file an issue with Nvidia, to see if there might be some sort of unknown issue with their drivers.
> 
> I don't see anything I could do to resolve this here.

It is definitively not a nvidia drivers issue, as I haven't updated the drivers in between when it was working and it stopped working

**Comment by Gouvernathor** [comment]
It still may be an issue that the drivers are working with the previous configuration (whatever that is) but fail with the current one. If the new versions of renpy are working with all other monitors, then the difference is the driver talking to those monitors. Maybe not updating them is in fact the problem.

**Comment by manuelifeno** [comment]
> I don't have any idea. You might want to file an issue with Nvidia, to see if there might be some sort of unknown issue with their drivers.
> 
> I don't see anything I could do to resolve this here.

Looking around there has been another bug with the same issue coming up a week ago: https://github.com/renpy/renpy/issues/4693 
This is very recent. Have you tried running renpy on a dual monitor with different resolutions and refresh rates?

**Comment by manuelifeno** [comment]
> It still may be an issue that the drivers are working with the previous configuration (whatever that is) but fail with the current one. If the new versions of renpy are working with all other monitors, then the difference is the driver talking to those monitors. Maybe not updating them is in fact the problem.

I have tried updating the drivers and not updating the drivers. It is definitively not nvidia drivers. I have even tried rolling back to an older version.

**Comment by Gouvernathor** [comment]
Just because several versions of the drivers have the issue doesn't mean it's not a bug present in both versions. I have that with another bug visible in renpy (but not leading to a crash), and it is definitely the driver's fault in that case (I'm sparing you the details).
I am running renpy on a dual monitor with different resolutions, I never had that issue. I will do some tests regarding framerate.

**Comment by manuelifeno** [comment]
> 

What I am trying to say is that the issue started happening out of nowhere, with no changes on my drivers. The only thing that has changed since then is windows updates, and checking around there is no drivers updates. I rolled back the latest windows update, but that didn't fix it.

**Comment by renpytom** [comment]
Ren'Py shouldn't have code paths that vary  based on monitor framerate, and so I can't see how it could be a Ren'Py problem. I wish I could help you, but I don't have any way of telling what's going wrong. If you can get more information, perhaps we can try something, but I wouldn't know where to start. 

(Is there a log.txt file from a crash, rather than a normal start? Perhaps that will have more information.)

**Comment by manuelifeno** [comment]
> Ren'Py shouldn't have code paths that vary based on monitor framerate, and so I can't see how it could be a Ren'Py problem. I wish I could help you, but I don't have any way of telling what's going wrong. If you can get more information, perhaps we can try something, but I wouldn't know where to start.
> 
> (Is there a log.txt file from a crash, rather than a normal start? Perhaps that will have more information.)

So renpy is generating no crashing logs, so I went to the event viewer, and this is what I got:
![image](https://github.com/renpy/renpy/assets/4889781/118a84fb-dfe8-4d35-b5de-e2c525273cf7)

**Comment by Gouvernathor** [comment]
For anyone's information, I tested on my end with one screen 16:10 60Hz and another 16:9 which I put from 60Hz to 50Hz : no crash when reloading renpy in either case.
I don't have a higher-end monitor to test high refresh rates on.

**Comment by manuelifeno** [comment]
> For anyone's information, I tested on my end with one screen 16:10 60Hz and another 16:9 which I put from 60Hz to 50Hz : no crash when reloading renpy in either case. I don't have a higher-end monitor to test high refresh rates on.

Sadly changing the refresh rate doesn't change anything on my end. I have to fully disconnect the monitor :(  
Maybe it is something else to do with the monitor, but it was working fine a week ago with the same monitor. So weird. It is pythonw.exe that is crashing, more precissely.

**Comment by manuelifeno** [comment]
I found the same error I am having a few more times: https://lemmasoft.renai.us/forums/viewtopic.php?t=63835. I am still very lost on this. I am going to try to rollback the windows DLL that is crashing. Wish me luck, that might nuke my windows installation.

**Comment by HorBro38** [comment]
I have an LG Ultragear running at 1440p @ 144hz and see no issues in 8.1.x with Auto-reload.

**Comment by manuelifeno** [comment]
> LG Ultragea

We have the same monitor! Exactly the same monitor. Where do we set auto-reload? Maybe it is something to do with the auto-reload settings.

**Comment by manuelifeno** [comment]
Update on this: I tried another monitor, and it crashes too. So the problem is not with the monitor or the different resolutions or refresh rate. Any second monitor will cause the crash.

**Comment by HorBro38** [comment]
I have 3 monitors on my Windows 11 install (The Ultragear, a 4k TV and a headless/fake screen) - still no issues.  Seems like it may be a odd driver issue with your particular machine.

**Comment by manuelifeno** [comment]
So looking into it in more detail, windows decided to update my display drivers 10 days ago. I am trying to get rid of them, but they keep reinstalling them when I delete them. It might be something windows update related.

**Comment by manuelifeno** [comment]
Okay, I tried rolling back those drivers, and even the main drivers, and nothing. It is still crashing. I give up.

**Comment by manuelifeno** [comment]
Okay, so it works now, and I didn't do anything to make it work. No updates, same version of everything... thanks everyone for trying to help me on this. I really don't know what happened there.
