### ISSUE TITLE
Have logs log the links for dependencies

### ISSUE THREAD

**Issue by RaXorX** [renpy/renpy#4757]
Allow the logs to log links for dependencies and respective directories to put/extract them in for various libraries.
For ex. a lot of the times downloading the android sdk failed over and over event though my internet connection is fully stable.
android.txt under ``tmp/GameName/android.txt`` only had one single line stating "Preparing to install Android SDK."
and that was it. I had no links to download manually or know where to put them in. Worst, on the part for 
Android Emulator, it keeps failing and if you stop that part, your sdk directory is just messed and it needs to repeat all those steps once again.

Please allow manual downloads and setups of these dependencies if Renpy is unable to handle this properly. Yes, I'm aware you can download the sdk and set it up globally, but that's not what I am intending to do when Renpy can do it locally, it just needs better handling for the downloads.

**Comment by renpytom** [comment]
I can do this for the small number of dependencies Ren'Py downloads directly, and probably  will. Most of the dependencies are downloaded indirectly, using the android tools.

Your best bet is to make sure your system isn't blocking the downloads. If it keeps failing, then you should figure out what's going wrong with your computer to prevent the download from happening.

**Comment by renpytom** [comment]
On second thought, this isn't worth it. Most of the downloads are done through the android tools or gradle, so it's not worth adding support for adding manual download - but not installation - of the parts that are not supported.
