### ISSUE TITLE
Release builds VP9 video

### ISSUE THREAD

**Issue by HRelease** [renpy/renpy#4761]
I've been receiving reports that videos in the Distribution versions of my game don't work on some machines. It shows a black screen only.
I use the VP9 video codec and run it on Win10.
I've bought a new computer and now have the same issue. At the same time, my old computers still have no problem running it.
Everything works fine in debug but not in distribution.

**Comment by renpytom** [comment]
Can you send me the built game? I can take a look.

**Comment by HRelease** [comment]
Game build:
https://mega.nz/file/NLsFVLIb#Rn_NdFJau_Heyytu1uxTo6GKFRApHHQtCm8GN-rYCR4
Save game:
https://mega.nz/file/a0kFxZIK#osycjTSdkCXAIms4KAVfEJjCC3DdwFHrjnYnCUcFWKE
If you click on a woman in the scene her animation should appear

**Comment by HRelease** [comment]
I think I've got my answer.
I had turned off all sound devices. When I turned them on, the videos appeared again.
I'm not sure how it's connected, but it worked in my case.

**Comment by renpytom** [comment]
Ren'Py uses sound to synchronize video and audio, so if sound is off, that won't work. Makes sense to me.
