### ISSUE TITLE
Sometimes, after one Shift+R reload, Ren'Py keeps reloading again and again even if I don't change anything

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4762]
It's a tricky one as it just happens sometimes and I have no reliable repro. I still open the issue so at least other people can say if they have the same bug and hopefully give more precise repro conditions. It happened on my previous Renpy version (7.1.3) and now it happens with v8.1.1.

Repro (when it happens):
- change something in the script
- focus game and Shift+R to enable auto-reload

Actual:
- after first reload, Renpy keeps reloading 5-6 times every second, sometimes it even prevents you from saving or quitting because it's super fast and will interrupt the exit popups

Expected:
- there should be only one reload

**Comment by Org-gith** [comment]
Did you update the sdk or made a clean install? Never encountered this bug in 4 years, but I noticed updating the sdk (through the update system) from older versions can sometimes create unexpected issues (just in case it could be something).

**Comment by Gouvernathor** [comment]
Updating the sdk should/can cause one reload, if the game is set to autoreload, because the renpy/common rpy files are checked for updates.
But in this example the spurious reloads happen when *activating* autoreload so I don't think it's related.

Does it happen in one game or did you see it appear in at least several ? Did you try to turn off your antivirus, in case it's meddling with the files behind your back ?

**Comment by hsandt** [comment]
- Doing incremental updates each time
- Happened a lost on my last project, and the current one, so at least 2. Possibly in some test project too (could try the tutorial or question to see if even standard projects have it; or a brand new project I suppose).
- I have no antivirus running at the moment and my code editor (Sublime Text) should not save and format the file without user action. I can check the modified date for unwanted modifications caused by other sources, although I don't have an idea what it could be

**Comment by Org-gith** [comment]
Should try on a fresh sdk install, and see if it happens again imo.

**Comment by renpytom** [comment]
You can also disable autoreload with:

```renpy
define config.autoreload = False
```

You might also look to see if you have some code generation in your game, since that could cause this. It's very unlikely to be cause by Ren'Py itself.
