### ISSUE TITLE
Suggestion: add history entry vertical spacing `gui.history_spacing` to gui configuration variables

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4766]
Currently, history entries can only have fixed height, or dynamic height with 0 margin / vertical spacing.

Fixed height:

```rpy
# gui.rpy

## The height of a history screen entry, or None to make the height variable at
## the cost of performance.
define gui.history_height = 100
```

![image](https://github.com/renpy/renpy/assets/1067772/3fe837ec-a65d-44d4-98fe-f54cb6fdb57b)

Note how the single line has more space around.

Dynamic height:

```rpy
define gui.history_height = None
```

![image](https://github.com/renpy/renpy/assets/1067772/5997a972-18bc-4ff5-878c-b33eaceccfd8)

I need a hybrid: dynamic height to match number of lines + fixed margin / vertical spacing between each entry.

This is, in fact, how NVL text works already in the main game:

```rpy
## The height of an NVL-mode entry. Set this to None to have the entries
## dynamically adjust height.
define gui.nvl_height = None

## The spacing between NVL-mode entries when gui.nvl_height is None, and between
## NVL-mode entries and an NVL-mode menu.
define gui.nvl_spacing = 20
```

![image](https://github.com/renpy/renpy/assets/1067772/17825744-b43d-40d7-b790-3c4892f53d2a)

I just need an equivalent variable: `gui.history_spacing`

**Comment by hsandt** [comment]
Cool! It doesn't work on nightly 8.1.4.23112006+nightly, although the commit is based on 8.1.3. A quick text search shows no occurrence of the new `history_spacing` parameter in my nightly folder.

Is it wrong to assume that a higher nightly version always have all the latest commits from previous versions onwards?

I'll clone renpy repo and try to target that specific commit myself, but I admit it's easier if I can do it directly from the installer selecting nightly as it would be harder for me to explain how to install a specific version from repo to my team of non-programmers if they want to all align on the same version (fortunately history spacing is not a critical feature that affects normal runs).

**Comment by mal** [comment]
It's a new feature, and as such can be found in the nightly of 8.2, not the 8,1.x fix nightly.

**Comment by hsandt** [comment]
Thanks, I kept using the Nightly Fix instead of Nightly. However, I still cannot make it work:

Version: 8.2.0.23112603+nightlyupdate
![image](https://github.com/renpy/renpy/assets/1067772/484417ff-b7b0-4365-82a6-4ccb2e56caac)

Code:
```rpy
gui.rpy

## The height of a history screen entry, or None to make the height variable at
## the cost of performance.
define gui.history_height = None
define gui.history_spacing = 40
```

History:

![2023-11-27 8 2 0 nightly still doesnt implement history_spacing](https://github.com/renpy/renpy/assets/1067772/cf7d1cdf-c6d5-4b3c-8627-106fbf182868)

P.S.: any way to easily copy the version number from Renpy Launcher? In Godot they added a one-click version copy as it's done very often in bug reports.

**Comment by mal** [comment]
Have you updated your `screens.rpy` as appropriate to make use of the new setting?
[gui/game/screens.rpy](https://github.com/renpy/renpy/commit/d309f3fb93d4ff249ad2250a5ee693fa2a805a98#diff-f5d9828288ad4c33283547ada46bf16c0d8ad5ee3eb1559763be146c25aaef7c)

**Comment by hsandt** [comment]
That was it, thanks! I forgot that existing project screens are not auto-updated!

I don't know if other things are changing in 8.2 screens but I don't see other visible issues so I just did the minimal changes from that commit to make `history_spacing` work.
