### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' (/lib/python3.11/collections/__init__.pyc)

### ISSUE THREAD

**Issue by MarkovaVV** [renpy/renpy#4768]
![image](https://github.com/renpy/renpy/assets/102507603/34d0a24e-2a19-4109-aeb9-657eda098949)

Building the web version of the visual novel in Ren'Py gives this error.  Can you please tell me what the problem might be?

**Comment by renpytom** [comment]
Requests isn't supported on the web platform, for security reasons. (There may be a secondary problem here, but that's the first issue.)

**Comment by MarkovaVV** [comment]
@renpytom, thank you for your answer! Can you please tell me if there is an alternative way to send an http request from the web version of the visual novel?

**Comment by renpytom** [comment]
There isn't a great way at the moment. What you need to do is to use emscripten.run_script and the other documented functions to invoke the HTML fetch api, and other APIs as required to get the data ready and send it across. (Generally, what I do is to create a promise in one function, and then have a second function wait for it to complete and send the data. This is made hard for a bunch of reasons, like CORS.) 

https://www.renpy.org/doc/html/web.html#emscripten.run_script

It's used in Ren'Py Sync: 

https://github.com/renpy/renpy/blob/master/renpy/common/00sync.rpy#L196
https://github.com/renpy/renpy-build/blob/master/runtime/web/renpy-pre.js#L789

**Comment by renpytom** [comment]
Unless I'm missing something, Mapping isn't even a documented member of collections. https://docs.python.org/3/library/collections.html

Anyway, I think this is resolved.

**Comment by mal** [comment]
`Mapping` was moved from `collections` to `collections.abc` during py3 development. The deprecation was completed in 3.10 when it was removed from its original home in `collections`. Since web runs on 3.11, it makes sense that it would flag there and not on other distributions.

**Comment by renpytom** [comment]
This probably means we need to update the version of requests included with Ren'Py.
