### ISSUE TITLE
issue with interactive director sorting image tags

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#4769]
defining an image by a name that starts with any number causes the `show` statement to crash
`image 0 = Null()`, opening the director and pressing `show` gives us this traceback

[traceback.txt](https://github.com/renpy/renpy/files/11840391/traceback.txt)

it's related to the `component_key` function. sorting a list with this func as key can cause said problem.

**Comment by Gouvernathor** [comment]
Identifiers in python can't start with 0, I'm not sure if doing so in image names is explicitly forbidden but it probably should not be supported.

**Comment by Elckarow** [comment]
the `0` isn't the problem here. use `76849644365` as name and you get the same problem

**Comment by Gouvernathor** [comment]
I meant starting with any digit. Python identifiers can start with a letter or underscore and continue with letters, digits and underscores.

**Comment by renpytom** [comment]
I might fix this for the director, but @Gouvernathor is right - tags and attributes need to begin with a letter (or _, but that's reserved for Ren'Py.)

**Comment by Elckarow** [comment]
right. might wanna specify that somewhere then.
i still think it's worth fixing though. i know a lot of people that use the `image` directory _not_ for automatically defining images, but simply for having a place to put those images. take DDLC for example, 
```rpy
image sayori 1a = im.Composite((960, 960), (0, 0), "sayori/1l.png", (0, 0), "sayori/1r.png", (0, 0), "sayori/a.png")
```
here, `sayori/1l.png` represents her _right_ arm and which outfit she's in (1 is her school uniform), and automatic image definition would define `1l` as an image, even though it's not what was expected. seeing this problem while using the director and _not_ having defined any image starting with a digit will create confusion

**Comment by Gouvernathor** [comment]
That's not the same, slashes and dots are authorized in file paths, yet you can't expect `image 1.f = Null()` to work.
There are a lot of file names that either result to the same automatic defined name (when the subdirectory, case or extension is different for example) or have no valid automatically defined name (dashes, dots...). That's normal behavior to me.

**Comment by Elckarow** [comment]
well that's a page of doc i didn't know existed (probably came in with the 8.1.0).

time to do some reading

**Comment by renpytom** [comment]
It also explicitly says image components can begin with numbers, so we should support that.
