### ISSUE TITLE
default_focus and other UI Statement properties are difficult to search

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#4774]
The properties under the sub-header "User Interface Statements" (https://www.renpy.org/dev-doc/html/screens.html#user-interface-statements) are not easily searchable in the docs as-is, and are extremely easy to miss even if you know what you're looking for. I knew there was a focus property for displayables (`default_focus` in fact), but I could not find it by searching "focus" because it is not a linkable subheader.

I also suggest this property be linked in other places where a user might look for it, for example in https://www.renpy.org/dev-doc/html/screen_python.html#renpy.set_focus

**Comment by hsandt** [comment]
I also often search my whole project for an occurrence of a word of interest, here `focus`, so the more commented lines giving examples of things to do in the default project template there are, the easier it is for me to find how to do X. However, I get it that you don't want to fill the project template with too many commented lines. (I had the same idea for options.rpy which doesn't show that many config vars to customize, but it's the same issue; I currently search through renpy-sdk's config.py file directly to get the list of config vars now...)

Alternatives are adding examples in the demo projects, e.g. with a chapter "auto-focus" making it easy to find by playing the feature demo itself, or by searching text inside the demo.

Last resort, I do search text in renpy-sdk itself but it also gives me a bunch of results in low-level code that I may not be interested in.
