### ISSUE TITLE
Reload game after launching it via command line with option `--warp` will always restart from warp position instead of last position

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4780]
I use `renpy.sh --warp scene.rpy:line` to quickly debug a certain sub-scene. But it causes all reloads to restart from the warp position instead of the last position, which makes me waste during after each small edit.

Shouldn't it preserve the last position in script as usual?

**Comment by Andykl** [comment]
In par with that issue. If the game was launched with `--compile` flag, that flag does nor resets when I hit Shift+R sometimes leading to unloadable `_reload.save`. I think that flag also should be reset once the game fully loaded.
