### ISSUE TITLE
Ren'Py is not working.

### ISSUE THREAD

**Issue by swornvi** [renpy/renpy#4781]
"When I click the "Launch Project" button in Ren'Py's main menu tab, nothing happens. This issue is also present in the tutorial and occurs only in version 8.1.1.

**Comment by renpytom** [comment]
Can you look in your project's directory to see if there is any output, like a log.txt, traceback.txt, or errors.txt file?

**Comment by swornvi** [comment]
[log.txt](https://github.com/renpy/renpy/files/11881531/log.txt)

**Comment by renpytom** [comment]
It seems like your game is crashing during video driver initalization. 

* Make sure you don't have any "game enhancement" programs installed, as those can interfere with the correct operation of your computer. 
* Potentially, hold down left shift as the game starts, to enable safe mode, and try the angle2 renderer.

**Comment by swornvi** [comment]
There is no such program as you mentioned in the first suggestion, and I tried the second suggestion but it didn't work.

**Comment by renpytom** [comment]
Hm... If you drag the tutorial directory onto renpy.exe, what happens?

**Comment by swornvi** [comment]
It worked as you suggested.

**Comment by renpytom** [comment]
I'm honestly not sure what could change between a hand launch and launching from the launcher. This is the workaround, but given that the problem happens when Ren'Py starts graphics, it might have something to do with drivers?

**Comment by swornvi** [comment]
If you're referring to the graphics card drivers, they are all up to date.

**Comment by renpytom** [comment]
I don't have any leads on this one, so I'm closing it.
