### ISSUE TITLE
Player-definable save folders

### ISSUE THREAD

**Issue by GetOutOfMyLab** [renpy/renpy#4783]
There are Ren'Py games out there that have variety of different routes/paths players can make. Because of this, players will often have many save files. 

It would be handy for the Save\Load screens to have a place for players to manage save folders so they can keep their saves more organized. From this screen, they could create/modify/delete save folders and then use a dropdown to tell Ren'Py which folder to display saves from. 

I've been looking into a way to do this myself, but doesn't seem to be a simple thing.

**Comment by AdultVisualNovels** [comment]
The ability to add a description to the save files would also go a long way here. A screenshot rarely tells the user the difference between one save and another. Having to load every save to determine which to keep or discard is defeatist by design.

**Comment by Gouvernathor** [comment]
Adding info to saves can be done using [json](https://nightly.renpy.org/doc/config.html#var-config.save_json_callbacks). You can add descriptions, make a virtual save folder system, or whetever your heart desires.
I think a system involving actual folders would be a hard and bad thing to do if you intend to support web or mobile platforms.

**Comment by GetOutOfMyLab** [comment]
I'm actually playing around with simply appending a string to the slot variable in the file_slots screen. Looks promising for now, but we'll see. 

Regardless of how its done, virtual or not, I still feel this should be core functionality in Ren'Py.

**Comment by rdurfee** [comment]
There is a built-in variable, save_name, that will show up on the save/load screen UI automatically.

Players can also change the name of the save pages by clicking on the title, allowing them to organize their saves how they want.

**Comment by GetOutOfMyLab** [comment]
Yeah, I already use save_name to name the save file. I did just notice that you can click on "Page 1" for example and rename it. Not very noticeable/intuitive IMO, though.

**Comment by Gouvernathor** [comment]
> Regardless of how its done, virtual or not, I still feel this should be core functionality in Ren'Py.

I don't. It's not useful for simple VNs which barely need saves to begin with, so it would pollute their GUI, and (as opposed to Sync) it can be done with the current API as shareable code. I mean, the backend part doesn't look more complex than adding a "folder" field to the json.

As for the UI, if you don't find some parts of the default GUI intuitive for things you want in your game, then you should change it, but that doesn't mean your change should become the default. I don't think it should, in this case. Ren'Py is more about giving you the tools to make your own game, than giving you an expansive starter pack.

**Comment by GetOutOfMyLab** [comment]
> I don't. It's not useful for simple VNs which barely need saves to begin with

Are simple VNs the standard used for what is decided to be core functionality? I rarely come across simple VNs these days. 

> so it would pollute their GUI

It could be a config option that would have to be enabled, like almost everything else.

> As for the UI, if you don't find some parts of the default GUI intuitive for things you want in your game, then you should change it, but that doesn't mean your change should become the default. I don't think it should, in this case. Ren'Py is more about giving you the tools to make your own game, than giving you an expansive starter pack.

That seems to be a short-sighted view. For example, I've seen many occasions where folks (playing various VNs) have no clue they can hover over file slot and press their delete key to delete the save. Such simple functionality that could be made more aware to others by having a better UI. Who wouldn't benefit from that? And in the case I showed above... I had no idea I could click the Page name and change it. Why would I know based on the default UI? Why is the functionality there if no one knows about it?

I see you actually commit to code repo here so may have taken insult or offense to what I suggested and that was not my intent. You say its more about giving the tools we need to make your own game... and it does that. That doesn't mean that things can't be improved. Imagine if web browsers never created bookmarks back in the 90's because they were met with the same resistance.

**Comment by Gouvernathor** [comment]
I spoke a bit too harsh, I apologize.

I'm not saying your idea is bad, or that the current UI is perfect (the examples you give are good ones), just whether it should be the default or not. Mostly because I imagine it would take too much room on the GUI, but I may be shown wrong depending on how you see it implemented. But as an example, we offer a splashscreen feature, but it's not shown in the default project (it's been proposed, and we chose not to).

In any case, things which can be done in the current API have lower priority for us to focus on than expanding the API (or other things like performance, platform support and whatnot). But it may still blossom into a good addition to Ren'Py.

**Comment by GetOutOfMyLab** [comment]
No harm done.  I just think that the landscape of VNs has changed quite a bit since Ren'Py started out and things that used to be unique to a certain VN, players are now expecting to be default. So all I ask is that an open mind is kept. As for this particular thing, I may have found my solution and there may be unexpected consequences, but we'll see.

**Comment by mal** [comment]
It may be worth reading up on the configuration options listed below which further facilitate partitioning/organising of saves:
https://www.renpy.org/doc/html/config.html#var-config.autosave_prefix_callback
https://www.renpy.org/doc/html/config.html#var-config.file_slotname_callback

> Are simple VNs the standard used for what is decided to be core functionality?

Within the sample project generated as part of a new project, generally yes. It's intended to be a low bar for new creators to get right into building their game/story without having to worry about lots and lots of overwhelming options. That isn't to say the engine doesn't or won't support more complex cases, but making use of them is generally an exercise for more seasoned creators who have decided they need to search for a leverage that more complex functionality.

**Comment by renpytom** [comment]
I don't currently think this is on the roadmap, and I think that the prefix functionality provides a way for people to add this sort of thing to their games. 

I also think that the right system for organizing saves for large games might vary from games to game - one might organize it based on dating partner, another may organize based on if your'e a banker from Boston or a carpenter from Ohio. 

So I don't think this is something that should be done at the engine level.

**Comment by GetOutOfMyLab** [comment]
> I don't currently think this is on the roadmap, and I think that the prefix functionality provides a way for people to add this sort of thing to their games.
> 
> I also think that the right system for organizing saves for large games might vary from games to game - one might organize it based on dating partner, another may organize based on if your'e a banker from Boston or a carpenter from Ohio.
> 
> So I don't think this is something that should be done at the engine level.

Well that's a shame. I know of many players with 40+ save pages. And I feel that allowing custom save folders would cover all games. You mentioned saves based on dating partner or specific route... that's exactly what a folder structure could provide. Create a folder named "Kate Romance". Or by choosing the character's profession, a folder named "Banker Route" or "Carpenter Route". 

Oh well.
