### ISSUE TITLE
Documentation: hpunch, vpunch and other transitions have no explanation on what class they are instantiated from, making customization difficult

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4786]
In https://www.renpy.org/doc/html/transitions.html many transitions like hpunch, vpunch, zoomin, zoomout, zoominout do not have explanations of the class used to instantiate them, unlike wipeleft, slideleft, etc.

This makes it harder to customize transition durations and other parameters as the class name is not trivial: you cannot just titlecase the transition name to get the class, for instance, `hpunch` uses `Move`:

```rpy
# renpy-sdk/renpy/common/00definitions.rpy
    # Zoom-based transitions. Legacy - nowadays, these are probably best done with ATL.
    define zoomin = OldMoveTransition(0.5, enter_factory=ZoomInOut(0.01, 1.0))
    define zoomout = OldMoveTransition(0.5, leave_factory=ZoomInOut(1.0, 0.01))
    define zoominout = OldMoveTransition(0.5, enter_factory=ZoomInOut(0.01, 1.0), leave_factory=ZoomInOut(1.0, 0.01))

    # These shake the screen up and down for a quarter second.
    # The delay needs to be an integer multiple of the period.
    define vpunch = Move((0, 10), (0, -10), .10, bounce=True, repeat=True, delay=.275)
    define hpunch = Move((15, 0), (-15, 0), .10, bounce=True, repeat=True, delay=.275)
```

While zoom may be depracated, at least the others should be properly documented (and for zoom, we should point to preferred method in the documentation).

We should add the instance definition of each transition that doesn't have it yet.

**Comment by Gouvernathor** [comment]
Note for everyone's information that Move, which is not documented and is the type of vpunch, is not the same as MoveTransition, which is documented and is the type of move, moveinleft, ease and many others.

Also, Move is not a class but a function, even though it just reforms the parameters to pass them to the Motion class. The Motion class doesn't seem to have other documented instances. It is currently used within the MoveTransition implementation.

**Comment by Gouvernathor** [comment]
In my view it seems easier to make a simple ATL transition to do the equivalent of Move, it will even be more readable.
```rpy
transform diagpunch(t):
    delay t
    new_widget
    ease t/2 offset (10, 10)
    ease t/2 offset (0, 0)
```

**Comment by renpytom** [comment]
That's correct. Atl (or just Transform directly) is now the documented way to create custom moves, zooms, etc. 

I don't think there need to be further changes.

**Comment by hsandt** [comment]
ATL equivalent looks great too! C++ doc itself uses code equivalents a lot to explain behavior without all the templating fuss.

So, are we adding this to the description of hpunch, vpunch, etc. ? So they can customize those preset animations with minimum tweaks, while using the recommended ATL.

Bonus question: if hpunch is used as simple motion transform and not transition, we can get rid of new_widget/old_widget, right? Or is it better to always write generic, reusable transforms this way so they are compatible with transitions, but when new_widget is None, the sprite simply doesn't change?

**Comment by Gouvernathor** [comment]
Actually, I don't think there's an easy ATL equivalent for the zoomin/zoomout/zoominout transitions mentioned in the OP, as like the move transition they apply to the separate images and not to the display as a whole. We should probably provide a way to at least customize their duration, it doesn't look very hard to do.
[Relevant code](https://github.com/renpy/renpy/blob/master/renpy/common/00definitions.rpy#L366-369), which mentions "Legacy - nowadays, these are probably best done with ATL." but if they are, I don't know how.

I don't think it's worth putting an example of ATL for the punches (because imitating the movement perfectly would make it documented and approximating it could make people complain), although adding a link to the ATL transition API wouldn't hurt.

**Comment by Gouvernathor** [comment]
So, fcaa02f, otherwise it seems it's a no.
