### ISSUE TITLE
Renpy 7.6.1 Steam deck variant shows as 'PC', 'large'

### ISSUE THREAD

**Issue by redfox2605** [renpy/renpy#4789]
On Previous versions of renpy (7.4) after following the steps on this [Steam deck guide](https://github.com/renpy/steam-deck-guide#renpy-750-or-later) the keyboard was shown automatically on steam deck when calling `renpy.input()`

Now after re-building the game with renpy 7.6.1 & renpy 8.1.1 keyboard doesn't show automatically anymore. I have set up the variables 

- define _renpysteam.keyboard_mode = "always"
- define _renpysteam.keyboard_shift = True
- define _renpysteam.keyboard_baseline = 0.7

But still the keyboard is not appearing automatically, it only appears with `steam + x` and in gaming mode. While on desktop mode no chance to make it appear.

We're using the following screen for input
```
screen input(prompt):
    style_prefix "input"

    window:

        vbox:
            xalign gui.dialogue_text_xalign
            xpos gui.dialogue_xpos
            xsize gui.dialogue_width
            ypos gui.dialogue_ypos

            text prompt style "input_prompt"
            input id "input"

style input_prompt is default

style input_prompt:
    xalign gui.dialogue_text_xalign
    properties gui.text_properties("input_prompt")

style input:
    xalign gui.dialogue_text_xalign
    xmaximum gui.dialogue_width

```

Can you suggest how can we trigger the keyboard to be shown in steam deck when using `renpy.input()`?

**Comment by renpytom** [comment]
Can you grab the log.txt from your build running on the Steam Deck? It sounds like the game isn't being launched through Steam, and so it's not making the connection to Steam that's required to start the keyboard. 

(I'll take a look at the output, but Steam Deck support is meant for the default mode, not the desktop mode.)

**Comment by redfox2605** [comment]
Here is the requested logs
```
Thu Jun 29 23:56:53 2023
Linux-5.13.0-valve36-1-neptune-x86_64-with-glibc2.2.5
Ren'Py 7.6.1.23060707
 

Bootstrap to the start of init.init. took 0.11s
Early init. took 0.00s
Loader init. took 0.04s
Loading error handling. took 0.32s
Loading script. took 5.38s
Loading save slot metadata. took 0.21s
Loading persistent. took 0.01s
Faled to initialize steam: Exception(u'Init returned false.',)
Set script version to: (7, 6, 1)
Running init code. took 0.31s
Loading analysis data. took 0.04s
Analyze and compile ATL. took 0.12s
Reloading save slot metadata. took 0.11s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache. took 0.00s
Making clean stores. took 0.00s
Initial gc. took 0.50s
DPI scale factor: 1.000000
Creating interface object. took 0.00s
Cleaning stores took 0.00s
Init translation took 0.52s
Build styles took 0.00s
Load screen analysis took 0.03s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.13s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start. took 0.64s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1280, 800)
swap interval: 1 frames
Fullscreen mode.
Vendor: 'AMD'
Renderer: 'AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve36-1-neptune)'
Version: '4.6 (Compatibility Profile) Mesa 22.2.0 (git-17e5312102)'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1280, 800) drawable=(1280, 800)
Maximum texture size: 4096x4096
controller: u'03000000de280000ff11000001000000' u'Steam Virtual Gamepad' 1
controller: u'03000000de280000ff11000001000000' u'Steam Virtual Gamepad' 1

```

1. As you suggested making the release from steam, as beta-test branch and installing it directly from the steam it works fine.
2. So the only way to test with  steam_deck  variant and have keyboard appearing is to through steam release? Before I was just making the build and adding the .sh of the build as external steam library and then executing it from steam in gaming mode, but this was not working.
3. Is there a way to test on a steam deck without having to go through the process to release it from a beta-test branch?

**Comment by renpytom** [comment]
So, Ren'Py needs to connect to steam in order to display the keyboard. The line: 

```
Faled to initialize steam: Exception(u'Init returned false.',)
```

Implies that Ren'Py was unable to connect to Steam. It should be possible to launch a .sh file through steam and have it run that way. At least, it works on the Linux desktop. I don't know what's happening here. 


You can use the SteamOS Devkit Client to upload games directly to Steam Deck:

https://partner.steamgames.com/doc/steamdeck/loadgames


I don't know if launching in windowed mode on Steam Deck will enable the steam deck functionality. It depends on what IsSteamRunningOnSteamDeck returns - Ren'Py uses that function to determine where it's running.

**Comment by redfox2605** [comment]
Thanks for your help, I will have a look
