### ISSUE TITLE
No external events are triggered for a screen shown via the use statement.

### ISSUE THREAD

**Issue by DipeshAggarwal** [renpy/renpy#4795]
I'm not sure if this is expected behaviour or not but when showing a screen via the `use` statement, no external events are triggered . While it makes sense that other external events are not triggered , but intuitively I feel like atleast `update` event should be triggered.

Though personally, I feel like other events should also be triggered because we are showing a new screen, which could do it's own things.

```
screen test_message(txt):
    on "show":
        action Function(print, "show event")
    on "replace":
        action Function(print, "replace event")
    on "replace":
        action Function(print, "replaced event")
    on "update":
        action Function(print, "update event")
    text txt

screen main_test_screen():
    use test_message(_("Test"))
```

**Comment by Gouvernathor** [comment]
Not the point here, but `_(txt)` does absolutely nothing in this context. If it contains a variable instead of an actual string, nothing is marked for translation, and the `text` element does the translation itself at the time of display.

**Comment by DipeshAggarwal** [comment]
I know. I just simplified my actual code, forgot to remove the unneeded bit of code.

**Comment by renpytom** [comment]
I tested this, and the show, hide, and replaced events are all occurring as I'd expect. The update event is causing problems, as it's not expected to cause an interaction restart like it's doing here - I'll go ahead and fix that, but the fundamental issue here seems invalid. 

Note that screen events are only delivered to the top level of the screen that is actually  shown, and not deep into screens that aren't being shown.
