### ISSUE TITLE
Feature request - When clicking on callstack hyperlink on Exception screen, jump to specific line

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4800]
The runtime exception screen has a cool feature where it shows clickable hyperlinks to faulty file and line:

![image](https://github.com/renpy/renpy/assets/1067772/c80a4b06-7931-4901-8f3c-d41685f5be6f)

Clicking on the links opens the .rpy script with the editor set for Renpy (or system one if not set). However, it doesn't jump to the corresponding line. It would be nice if it did.

Jumping to line requires a certain command line option and format that depends on editors. In fact, Unity had exactly this issue where jumping at line was very bad for many editors. Eventually, they solved this by supporting a few common editors (at least for C#) and adding an extra field where user can add an arbitrary command-line option to format how to pass the file and line information, such as `-g "$(File):$(Line)"`

I know this is more work, so maybe we could start by supporting VS Code, which is the first one in the list of suggested editors. The format `file:line` should also work Atom, the second suggested editor. And even Sublime Text, which is not in the list (however, we'd need an option to enable/disable jump to line with compatible editors; otherwise the extra `:line` may cause issues with editors unaware of this convention).

From there we could see how the feature is appreciated and extend it to other editors, possibly allowing user to pass custom file-line format so we don't have to take care about a bunch of them.

To be honest, I didn't request this for exceptions, which are not so common in my project. I made this request to prepare another related request to jump to current statement during debug. I will open it soon.

**Comment by Gouvernathor** [comment]
This already works on my end (system VSCode).

**Comment by renpytom** [comment]
Works for me, with the supported editors. You want to make sure RENPY_EDIT_PY is set correctly (by default, the launcher sets it, so if you're launching the game some other way, it can be wrong).

**Comment by hsandt** [comment]
OK, so I made VS Code work as you said:
- do not rely on Not Set / System Editor + VS Code set as system editor, since Renpy will just think it's a generic editor and not recognize system editor is VS Code
- Visual Studio Code (System) makes it recognized, and I suspect the embedded Visual Studio Code would work too. However, you need to play the game from the launcher as @renpytom said.
- When playing from a custom command running `renpy.sh`, as @renpytom said, you should set RENPY_EDIT_PY environment variable. However, I had to write a global path that only works on my computer:

```json
"env": {
	"RENPY_EDIT_PY": "$HOME/Applications/Game Engines/renpy-sdk/launcher/Visual Studio Code (System).edit.py",
},
```

I suppose I could set some RENPY_SDK_PATH and tell my fellow devs to do the same so I can write a path relative to it that works on all computers, but there doesn't seem to be a native way to support it.

If there was a way to use the launcher settings when using renpy.sh, I suppose this could help avoiding platform-specific settings.

---

Now back to the second part of the feature request: supporting other code editors via custom file:line format string.

Well, while inspecting `Visual Studio Code (System).edit.py` I understood how it worked, esp. the `open` method that handles line:file format. So I just wrote my own edit.py. Here is an example for Sublime Text (I picked some parts from Atom.edit.py which is simpler and doesn't have some options that don't apply to Sublime Text):

```py
# Sublime Text.edit.py
import os
import subprocess
import sys

import renpy

class Editor(renpy.editor.Editor):

    has_projects = True

    def get_subl(self):
        """
        Returns the path to the subl executable.
        """

        if "RENPY_SUBLIME_TEXT" in os.environ:
            return os.environ["RENPY_SUBLIME_TEXT"]

        # Make sure to add subl executable to PATH
        # (generally C:\Program Files\Sublime Text\ on Windows, /Applications/Sublime Text.app/Contents/SharedSupport/bin on macOS,
        # /usr/bin/subl or /usr/local/bin/subl on Linux)

        if renpy.windows:
            return "subl.exe"

        return "subl"

    def open(self, filename, line=None, **kwargs):
        if line:
            filename = "{}:{}".format(filename, line)
        self.args.append(filename)

    def open_project(self, project):
        self.args.append(project)

    def begin(self, new_window=False, **kwargs):
        self.args = [ ]

    def end(self, **kwargs):
        self.args.reverse()

        subl = self.get_subl()
        args = [ subl ] + self.args
        args = [ renpy.exports.fsencode(i) for i in args ]

        subprocess.Popen(args)



def main():
    e = Editor()
    e.begin()

    for i in sys.argv[1:]:
        e.open(i)

    e.end()

if __name__ == "__main__":
    main()
```

If `subl` is in path, or you customize `RENPY_SUBLIME_TEXT`, you can run the app from any location. Heck, you could even set RENPY_SUBLIME_TEXT to a different code editor as long as it uses the same `file:line` format!

From here, it's easy to use via command-line: just set `RENPY_EDIT_PY` to the path to that file (again, it will probably be computer-specific... but again, you can decide some convention with your team, using env vars).

But ff you want it to be recognized by the Renpy Launcher, you should put it in a specific place. https://www.renpy.org/doc/html/editor.html notes that sub-folders of renpy-sdk is scanned, but a look at `renpy-sdk/launcher/game/editor.rpy` shows that sub-folders of `persistent.projects_directory` are also scanned. So, if you don't fancy putting stuff in your renpy-sdk (e.g. because you clone the repo directly and that messes up your Git diff), you can use that folder instead.

For instance, I put mine in `{persistent.projects_directory}/Custom Editors`. It now appears in the list of editors in Renpy Launcher...

![image](https://github.com/renpy/renpy/assets/1067772/1b37058d-f8b4-46cd-9e51-39ec965a75c4)

... and it opens the file at the correct line with both methods (running renpy.sh and playing via the Renpy Launcher).

This should completely close this issue, as users now have a way to add whatever file:line opening format they need.

I don't know if you're interested in adding more code editors this way to the official Renpy repository, so I didn't send a PR containing my Sublime Text.edit.py. If your intention is to let each user add their own files this way, it is fine, but consider completing https://www.renpy.org/doc/html/editor.html which the extra information I mentioned (namely, that {persistent.projects_directory} sub-folders are scanned too, and that renpy-sdk/launcher/*.edit.py are good examples to start with).

Also, if you find a good way to make the `RENPY_EDIT_PY` var easier to share (relative to renpy-sdk or persistent.projects_directory?), I'll be glad to hear it.

But at least I got a way to make this run on my computer consistently, and more hope to make #4801 work too!
