### ISSUE TITLE
Feature Request - Quickly open text/code editor at current script statement at any time (possibly via Interactive Director)

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4801]
**Context**

I generally iterate like this:
- run scene until I spot an issue
- fix typos, character expressions, etc. in script
- reload, continue testing

However, when the next issue is far after the previous one, I need to find the line containing the issue in the script. To find the right line in code, I can:
- search by text: read dialogue line, switch to script editor, Ctrl+F to find text by typing the start of the line (works well when the line is pretty unique)
- search by line: open the Interactive Director (D) and read the line, switch to script editor, Ctrl+G to go to line

**Proposal**

It would be nice to automate with a single action:
a. Using the Interactive Director: click on any statement line to jump at the corresponding line in that file
b. Global shortcut (e.g. G): press it to quick jump to last executed statement in appropriate file (if screens are running background animations, just focus on the last statement in the main script; basically the one you'd see at the end of the Interactive Director panel)

Once https://github.com/renpy/renpy/issues/4800 is implemented, we will have a way to jump to a certain file at a certain line. Then it is a matter of adding the hyperlink to the Interactive Director statements, or the global shortcut.

This would make the workflow much faster, and seems in line with Interactive Director's purpose. In fact, if you wanted a full Interactive Director solution, you would add a feature to allow live editing of statements instead of just adding statements. But I understand that can be difficult, so allowing quick switch to the dev's script editor is a good compromise!

**Comment by Gouvernathor** [comment]
Shift+E already does that, if I understand what you say correctly

**Comment by hsandt** [comment]
Excellent! Combined with my custom Editor integration file (see #4800) it works perfectly! I can't believe I didn't find the shortcut during my initial search!
