### ISSUE TITLE
Call from_current breaks roll-forward on pause statements

### ISSUE THREAD

**Issue by mal** [renpy/renpy#4807]
**Update**: Turned out to be an underlying issue with how the `pause` statement was dealing with roll-forward info, rather than anything specific to `from_current`, see supplied PR for details.

---

The `from_current` parameter is useful for allowing the player to diverge temporarily from a main dialogue, perhaps because they clicked a secret, or some other optional thing the creator makes available during dialogue.

It works great for this purpose and is friendly with both rollback and roll-forward except, it seems, in the case that it is activated while the main dialogue is on a pause statement. When used in a such a scenario it still _mostly_ works, but that point becomes impossible to roll-forward over.

<details><summary>Testcase</summary>

- Clicking the "Extra" button on dialogue lines works as intended and functions perfectly with rollback and roll-forward.
- Clicking the "Extra" button on a pause statement works as intended and functions perfectly with rollback **but not** roll-forward.

```rpy
label main_menu:
    $ _confirm_quit = False
    return

label start:
    show screen example()
    "A"
    "B"
    pause
    "C"
    return

label sidebar:
    hide screen example
    "extra: This is outside the main label."
    show screen example()
    return

screen example():
    textbutton 'Extra':
        action Call('sidebar', from_current=True)
        align (.5, .5)
```
</details>

Ren'Py: `8.1.1.23060707`, `8.1.2.23063001+nightly` (`fix`), and `8.2.0.23070203+nightly` (`'master`).

**Comment by Gouvernathor** [comment]
Can it be a side-effect of [roll-forward being disabled by default in call screen](https://www.renpy.org/dev-doc/html/changelog.html#call-screen-and-roll-forward) ?
Even if so the difference between pause and dialogue is weird.

**Comment by mal** [comment]
It doesn't appear so, or at least using `define config.call_screen_roll_forward = True` doesn't alleviate the issue.

**Comment by Gouvernathor** [comment]
My theory was that from_current would somehow rely on some common code with ``call screen`` so that behavior would have been contaminated from it, but it doesn't appear so.

**Comment by mal** [comment]
After some more digging around, I _think_ it's because `say` statements (via `Character`) trap control exceptions and write them into the rollback log (making it work on dialogue lines), but I suspect `pause` statements do not. They probably should, but Tom is probably best placed to know where such code belongs, and whether it should be broader in scope that just `pause`.
