### ISSUE TITLE
Steam not able to launch the build on Mac

### ISSUE THREAD

**Issue by investigat** [renpy/renpy#4816]
I'm not sure if this is steam problem or a Ren'py problem, but some players are unable to launch the game on steam. It launch and then closes. They can launch it with the folder but not by steam. It says it might not run as 32 bit but it works otherwise.
<img width="989" alt="Screenshot_2023-07-03_at_9 57 29_PM" src="https://github.com/renpy/renpy/assets/92343272/37c1ee05-565d-4e48-af83-75c15da3623e">

https://github.com/renpy/renpy/assets/92343272/3bc7752c-6595-4a5b-a911-205136a12903

**Comment by HorBro38** [comment]
It looks like steam throw's this warning if the application isn't explicitly flagged for 64 bit, I'm not sure if this is something done during the build generation or not.

**Comment by renpytom** [comment]
This does look like the steam settings are wrong. 

I'm closing this out for now, feel free to re-open if Ren'Py is implicated.
