### ISSUE TITLE
Using Viewport on PC causes hover_background image; which exceeds button size, to become cut off.

### ISSUE THREAD

**Issue by henvu50** [renpy/renpy#4825]
**Ren'py Version:** 8.1.1.23060707

**Issue:** Using Viewport on PC causes hover_background image; of which the hover_background image exceeds button size, to become cut off.

**Image of problem:** 
![image](https://github.com/renpy/renpy/assets/82792098/f5e8633c-fa29-40e5-9473-aac008b70872)

**How to reproduce:**
1. Create new Ren'py Project.
2. Copy these two images to gui folder: [https://i.ibb.co/998MyXr/button-hover-biggerthanbutton.webp](url) [https://i.ibb.co/gV2tVTS/button-idle.webp](url)
2. Use this code to reproduce problem:
```
screen test():
    
    viewport:
        xalign 0.5
        xfill True
        yfill True
        xsize 1920
        ysize 1080
        has vbox:
            xfill True
            yfill True
            xalign 0.5
            yalign 0.5
        imagebutton:
            xalign 0.5
            yalign 0.5
            idle Transform("gui/button_idle.webp", xalign=0.5, yalign=0.5)
            hover_background Transform("gui/button_hover_biggerthanbutton.webp", xalign=0.5, yalign=0.5)
            action NullAction()

label start:
    show screen test
    pause
```
Image of problem: 
![image](https://github.com/renpy/renpy/assets/82792098/f5e8633c-fa29-40e5-9473-aac008b70872)

3. Use the following code adjustment to get rid of the problem, note the viewport has been removed:
```
screen test():
    imagebutton:
        xalign 0.5
        yalign 0.5
        idle Transform("gui/button_idle.webp", xalign=0.5, yalign=0.5)
        hover_background Transform("gui/button_hover_biggerthanbutton.webp", xalign=0.5, yalign=0.5)
        action NullAction()
```
Image of solution, the problem goes away when not using viewport, no cut off.
![image](https://github.com/renpy/renpy/assets/82792098/573fb949-55cb-48e7-8498-7f03a70458c1)

**Summary**
Being able to use a hover image that's far bigger than the button size is rather convenient. However, if a rule needs to be made: in which hover_background images must be the same size as the button size, so be it. 

I'll defer to your judgement of which solution is best:

a) Either the issue is fixed, and using a viewport no longer results in hover_background image cut off, despite the hover_background image exceeding the button size. **_Note: I've noticed cut off with other things too, like labels where the text size is dynamic, if the text size increases, the text gets cut off, but if the viewport is removed, then the text is no longer cut off._**

b) Mandatory: when making images for a button, all images used in idle, hover, selected, hover_background, or whatever must all be the exact same size.  Note: this means that if you have a label with a dynamic text size, the text will still get cut off. Ideally, it would be better if viewport just never causes displayables to ever get cut off, no matter what.

c) Another solution I didn't think of?

**Comment by renpytom** [comment]
I don't think this is a valid issue. 

The purpose of a viewport is in its name - it provides a viewport into a displayable that's larger than the viewport itself. (At least for the non-trivial case.) What seems to be happening here is that you've come up with a combination of a button and background that extends past the left boundary of the viewport - and hence, it's getting cut off. 

I don't think this is a problem with Ren'Py. If you want to use a viewport, make sure everything inside it fits within the displayable (the vbox, in this case) that's the child of the viewport.

**Comment by henvu50** [comment]
For anyone who finds this, you have to go with solution B in my original post:

```
b) Mandatory: when making images for a button, all images used in idle, hover, selected, hover_background, or whatever must all be the exact same size. 
```

Renpytom basically said he won't fix it; _which is np, I respect his decision, although I don't understand it_, so that means you have to ensure all images used in that button have the exact same size, but if you don't use the viewport, then your button sizes for idle and hover can be different without causing the cut off issue.

Here are the specifics:

```
screen test():
    viewport:
        xalign 0.5
        xfill True
        yfill True
        xsize 1920
        ysize 1080
        frame:
            background "#fd3"
            padding (20,20,20,20)
            vbox:
                xfill True
                yfill True
                xalign 0.5
                yalign 0.5
                xsize 1720
                ysize 950
                frame:
                    background "#ad4"
                    xalign 0.5
                    yalign 0.5
                    xfill True
                    yfill True
                    padding (20,20,20,20)
                    imagebutton:
                        xalign 0.5
                        yalign 0.5
                        xsize 300
                        ysize 120
                        idle Transform("gui/button_idle.webp", xalign=0.5, yalign=0.5)
                        hover_background Transform("gui/button_hover_big.webp", xalign=0.5, yalign=0.5)
                        action NullAction()
```
Note the following dimensions.
- button_idle.webp dimensions: 80x80
- button_hover_big.webp dimensions: 300x120

If not using a viewport, you don't have to hardcode the button size to the size of the biggest image used in the button.

If using a viewport, you have to hardcore the button size to the size of the biggest image, in this case the _hover_; since it's bigger than the _idle_.

Leaving it as is doesn't make sense, if only one button can ever gain focus at a time, it's okay for the hover image to be bigger than the idle image, without having to hardcore the button size to be the size of the biggest image; in this case the hover, because the hover images would never risk overlapping; since only one button can gain focus at at time.

Ideally, if using a viewport, the behavior of the buttons should behave the same whether using a viewport or not.

**Comment by renpytom** [comment]
> Renpytom basically said he won't fix it

No, I said the issue was invalid, and explained what you were doing wrong. Please re-read my post.

**Comment by henvu50** [comment]
> > Renpytom basically said he won't fix it
> 
> No, I said the issue was invalid, and explained what you were doing wrong. Please re-read my post.

np.

> The purpose of a viewport is in its name - it provides a viewport into a displayable that's larger than the viewport itself. 

In the new example I provided, I explicitly made sure the viewport is far bigger than the displayable; in this case a button.

![image](https://github.com/renpy/renpy/assets/82792098/ede02f1e-1845-44db-8978-164a4ab374df)

```
screen test():
    # ensure viewport is bigger than displayable button inside it
    viewport:
        xalign 0.5
        xfill True
        yfill True
        xsize 1920
        ysize 1080
        frame:
            background "#fd3"
            padding (20,20,20,20)
            vbox:
                xfill True
                yfill True
                xalign 0.5
                yalign 0.5
                xsize 1720
                ysize 950
                frame:
                    background "#ad4"
                    xalign 0.5
                    yalign 0.5
                    xfill True
                    yfill True
                    padding (20,20,20,20)
                    frame:
                        background "#dda233"
                        xalign 0.5
                        yalign 0.5
                        #padding (50,50,50,50)
                        imagebutton:
                            #idle_background "#dda233"
                            xalign 0.5
                            yalign 0.5
                            #xsize 300
                            #ysize 120
                            idle Transform("gui/button_idle.webp", xalign=0.5, yalign=0.5)
                            hover_background Transform("gui/button_hover_big.webp", xalign=0.5, yalign=0.5)
                            action NullAction()
```

> (At > least for the non-trivial case.) What seems to be happening here is that you've come up with a combination of a button and background that extends past the left boundary of the viewport - and hence, it's getting cut off

But the viewport has a size of 1920x1080, how can it possibly cut off a centered button with a dimension of 80x80?

I get what you're saying. You're saying that the very nature of a viewport is to cut off displayables inside it that exceed the viewports size. I understand that. But in my case, the displayable is much much smaller than the viewport.

Look what happens when I disable the viewport:

![image](https://github.com/renpy/renpy/assets/82792098/6e8f7820-6ed0-4bab-b086-8bba39057019)

```
screen test():
    # viewport:
    #     xalign 0.5
    #     xfill True
    #     yfill True
    #     xsize 1920
    #     ysize 1080
    frame:
        background "#fd3"
        padding (20,20,20,20)
        vbox:
            xfill True
            yfill True
            xalign 0.5
            yalign 0.5
            xsize 1720
            ysize 950
            frame:
                background "#ad4"
                xalign 0.5
                yalign 0.5
                xfill True
                yfill True
                padding (20,20,20,20)
                frame:
                    background "#dda233"
                    xalign 0.5
                    yalign 0.5
                    #padding (50,50,50,50)
                    imagebutton:
                        #idle_background "#dda233"
                        xalign 0.5
                        yalign 0.5
                        #xsize 300
                        #ysize 120
                        idle Transform("gui/button_idle.webp", xalign=0.5, yalign=0.5)
                        hover_background Transform("gui/button_hover_big.webp", xalign=0.5, yalign=0.5)
                        action NullAction()
```

Maybe i'm being really stupid with my code, and somehow the super huge viewport which is much bigger than the displayable button, is somehow cutting it off, and I don't see or understand it?

**Comment by henvu50** [comment]
Seronis in discord confirm that the viewport is indeed not cutting off the button displayable:

![image](https://github.com/renpy/renpy/assets/82792098/26934cbf-7dca-49d6-98cc-73100220b6d9)

**Comment by renpytom** [comment]
In your first example, the button was off the left side of the viewport.

**Comment by henvu50** [comment]
> In your first example, the button was off the left side of the viewport.

I'm sorry, we're on a completely different page.

Fen (Feniks) in Discord confirmed what I mentioned in my original post, that when using a viewport, you have to create an extra rule: When using viewport, button size must be the same size as the biggest image size used for that button; e.g, if the hover image is 300x120, yet the button size is 80x80, you have to set the button to be 300x120.  However, if you don't use a viewport, then you can ignore this rule.  

My argument is that the more rules that exist for different displayable states can confuse things when doing a lot of multi-platform stuff, I have to do extra coding, but it's fine, if that's the way it is, so be it, I'll manage, thank you for your time.
