### ISSUE TITLE
when rolling back after a load, rollback is not restoring the correct transform state for some displayables

### ISSUE THREAD

**Issue by NaughtyRoad** [renpy/renpy#4827]
I've recently upgraded from ren'py 7.3.5 to ren'py 7.6.1 for my existing project, and noticed different behavior in the rollback functionality after a load has occurred.

The gist of it is: in many cases, with an active transform applying to a displayable, when rolling back after a load, rollback is not restoring the correct transform state for that displayable, but instead immediately forwards to the end value of the property that is the subject of the transform.

**In more detail:**

I layer several images over each other and zoom them in/out with different zoom levels to create a parallax effect, like this:

> scene image background:
>  &emsp;   zoom 1.0
>  &emsp;  ease 30.0 zoom 1.15
> show image foreground variant1:
>  &emsp;  zoom 1.0
>  &emsp;  ease 30.0 zoom 1.3
> with dissolve.
> char "Hello, line 1"

Then each dialog line I explicitly call "show" for each image, even if they don't change in content, so the transform state is saved for all of them in the rollback queue on that line of dialog, and when you do roll back, they all revert their zoom to a state that is correct in relation to the other displayables for that line of dialog.

So, each next line of dialog looks something like this:

> show image background
> show image foreground variant2
> with dissolve
> char "Hello, line 2."

Possibly of interest: the foreground image in this example is running it's own transform. It's defined something like:

> image foreground variant1:
> &emsp;  "images/char1 variant1 wings_up.png"
> &emsp;  1.2
> &emsp;  "images/char1 variant1 wings_down.png"
> &emsp;  0.5
> &emsp;  repeat

The background image in this example is simple: 

> image background = "images/bckgr.png"

**Now for the issue:**

Rollback works completely as expected still in 7.6.1 during regular playthrough.

But, after loading a save, then immediately rolling back, it seems the rollback queue is not restored entirely correctly, and when rolling back, the zoom transform of some images immediately forwards to the end value, while  others would correctly jump back a little in zoom. Which image it is varies, but most of the time, it's the image or images in the foreground.

The rollback does work entirely fine if you roll back all the way to the "scene" statement, then go forward again, then roll back. It also works fine with whatever transform is applied later on in the script, it's just the bit of the rollback queue that is restored by the load that is off.

The above example is a bit simplified, and most of my scenes will have more than just two displayables layered on top of each other, with a mix of simple still images, and displayables running their own transforms. I tried several scenarios to see if I could make more sense of when it would cause a displayable to exhibit this behavior, but I can't quite pin down what the deciding factor is to have this happen, only that it happens a lot. 

I have a very small test project that demonstrates this issue, and I would be happy to share it (but I'd prefer not to post it in public).

**Comment by HorBro38** [comment]
I would highly recommend adding `$ renpy.block_rollback()` to your after_load() label, otherwise anything you do in that label can be ignored if the user rolls back before it (possibly breaking any updates required by the label).

**Comment by NaughtyRoad** [comment]
> u

Currently, I'm not doing anything on after_load(), so from that perspective, it shouldn't be needed. If at all possible, I'd prefer not to block users from using the rollback function at any moment. As a player, I love that feature and I do roll back after loads all the time in ren'py games I play. 

Still, cheers for the tip, I might include it in my impending release if this issue is still present, but I'd very much prefer the rollback after a load to work correctly again at some point.

**Comment by HorBro38** [comment]
Sure thing, you're just going to run into issues with future version releases if you need to update older save games so I wanted to give you a heads up. :)

**Comment by renpytom** [comment]
Can you send me the test project? I'm ready to look at this, but can't repeat the problem. (Sorry for the delay, this got buried.)

**Comment by NaughtyRoad** [comment]
> Can you send me the test project? I'm ready to look at this, but can't repeat the problem. (Sorry for the delay, this got buried.)

Cheers and no worries. I don't think github does direct messages so I've messaged you through Patreon with a reproduction project and some additional info.

**Comment by mal** [comment]
Suspect this may have been the real issue targeted by the fix in https://github.com/renpy/renpy/commit/05e72cbe274a6bce76521ca5f13e70a4cb606e3f.

**Comment by renpytom** [comment]
Correct.
