### ISSUE TITLE
Render SVGs at arbitrary (large) sizes

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4832]
There should be a way to have "small" svg files (in their inner coordinate system, that is), but to show them at arbitrary large sizes, since in vector images, size isn't supposed to matter.
I found a way by adding another multiplying factor, for example 10, at this line : https://github.com/renpy/renpy/blob/bdec32fa5bd92af48f900d56a0a4b54d96ee1009/renpy/display/im.py#L780
I suggest there should be an additional parameter to Image, or another behavior for the oversampling parameter in the case of SVG files, and a config default value of the oversampling factor in the case of SVG so that auto-defined images can have it.

**Comment by mal** [comment]
The correct render size for an SVG feels like something that belongs in the SVG itself, ensuring that its display in Ren'Py is consistent with other viewers/editors and remains spec-friendly. Conveniently, this is also easy to do, for example:

A basic 100x100 SVG containing a centred rectangle:
```svg
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <rect width="70" height="70" x="15" y="15" fill="#733" />
</svg>
```

The same image that will render at five times the resolution:
```svg
<svg viewBox="0 0 100 100" width="500" height="500" xmlns="http://www.w3.org/2000/svg">
  <rect width="70" height="70" x="15" y="15" fill="#733" />
</svg>
```

Adding `width` and `height` attributes to the top level `<svg>` will allows it to scale (pre-raster) which Ren'Py respects when loading and results in a larger texture, which if I've understood correctly is the goal outlined.

**Comment by Gouvernathor** [comment]
That's a good workaround, but I feel there should be an option to do that in renpy. You can expect a common creator to rename all their file with an @, if piggybacking the oversample system, or to set a config, but although svg is simpler than binary bitmap format like png, that's placing the bar a bit high for someone who just wants to use images (and who may have no idea how SVG works internally).

Also, you may want to keep the image files just as you found them, so as not to have to convert them again if you update them from the place you found them : in my case wikimedia, but it could be your typical artist or image software which may have their settled way of doing things.

**Comment by mal** [comment]
I'm not sure I agree about that being easier. Needing to specify a size when creating an `Image` object wouldn't work with existing features designed to make creators lives easier, such as automatic image definitions and string file paths automatically being turned into `ImageReference` instances.

Just like a jpeg sourced from elsewhere, it doesn't seem unreasonable to think a creator might need to resize an SVG asset to fit correctly in their game. I understand that some creators may not be well versed with the SVG format, but in such cases I'm not sure requiring them to know they need to explicitly define the image and specify the desired render size in their codebase is significantly better, especially when they would see seemingly arbitrary differences between `show my_svg` and `show expression 'my_svg.svg'`.

My own suggestion would probably be documentation around utilising SVGs that gives a brief summary of how to resize such assets (perhaps including a link to a reputable free editor) and a link to a more comprehensive guide to the format for those interested in diving deeper (MDN perhaps?).

**Comment by renpytom** [comment]
I think it's reasonable to let the user to override the dpi of an SVG. The current default (96, IIRC) is pretty arbitrary anyway, and so I don't think it's crazy to let users change that to get the file in a higher or lower resolution when rasterized.

**Comment by Gouvernathor** [comment]
My propositions are trying to help with these use cases : if you're piggybacking the @-oversample system, then you will have no problem with automatic image definition (although changing that behavior may be backwards-incompatible) ; if there is instead a dedicated parameter for SVGs in Image, and which is defaulted using a config, setting that config will apply to all automatically defined SVG images since Image will (I think ?) be called at that time. That parameter could be a factor to increase the rasterization by, or a dpi value which would have that default of 96 (yep).

I agree that a dedicated arg for SVGs in Image, itself, is not great, mostly for the reasons you give and also because it only applies to some images.
My ideal would be a dedicated class for vector images, a subclass of Image for example, which would first support that additional parameter defaulted in config, but if some of us have insomnia it could be further expanded to render the image at arbitrary resolutions, depending on the width and height passed to the render method. Making that arg/config couple obsolete, I guess. But it may reveal to be too expensive to be generalized, and would be a nice opt-in, as a special value for the arg/config for example 🤷 
And renpy.image (used in automatic image definition) would create objects of that class of course.

**Comment by renpytom** [comment]
A new argument to Image is better than a new class. 

I think it will be hard to justify saying that Image works with all image files, except for SVGs. (Especially when it already works with SVGs.) 

I think it's perfectly fine to have an argument that only works with some file types.

**Comment by Gouvernathor** [comment]
I think we could keep the existing Image as-is, and have a specialized class which does the above, at the same time. That way, if you want to customize the dpi or enjoy the potential arbitrary-dpi feature, you may use the new callable (and it's the case for auto-defined images), but if you don't and use Image(".svg"), it still works like your typical vanilla bitmap image.
The API would be cleaner that way in my view, but it probably doesn't make a lot of difference behavior-wise (the ifs of a single-class approach would have a minor performance consequence).
