### ISSUE TITLE
Use window icon to generate a .ico/.icns on deploy the game

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4833]
Using the Pillow library, it could be used to generate the icons of the game without resorting to external tools. A basic use would be the following.
```py
from PIL import Image
filename = r'gui/window_icon.png'
img = Image.open(filename)
img.save('icon.ico') # or icon.icns

# Custom sizes
icon_sizes = [(16,16), (32, 32), (48, 48), (64,64)]
img.save('icon.ico', sizes=icon_sizes)
```

[Pillow doc](https://pillow.readthedocs.io/en/stable/index.html)

**Comment by renpytom** [comment]
I don't want to take on Pillow as a dependency, just for this. 

It might make sense to host a web service on renpy.org that can do the conversion, though.

**Comment by Neyunse** [comment]
> I don't want to take on Pillow as a dependency, just for this. 
> 
> It might make sense to host a web service on renpy.org that can do the conversion, though.

But, if the dev doesn't have internet connection and need the icon probably 
renpy.org don't work. 🤔 And depending on the conversion site, in some cases the icons generated are not well optimized and their quality is low. 

Perhaps during the compilation the icon will be generated on the renpy server and downloaded, that may be an idea. But the problem of generating the .ico file offline would persist. Maybe using some other method to generate the icons could help.

**Comment by JamiesonC** [comment]
Note that GIMP (free, open-source image editor) supports export to ICO. It also supports export to ICNS as of 2.99.16, which was released 7 July 2023.
