### ISSUE TITLE
Incorrect behavior of Angle and Radius ATL

### ISSUE THREAD

**Issue by brimbel** [renpy/renpy#4835]
I was testing out ATL transforms where I can supply an angle offset to the transform so I can reuse animations, but noticed that the angle and radius properties didn't work as I expected them to.

```
transform rotate_animation_1(i=0):
    anchor (0.5,0.5) around (0.5,0.5) angle i radius 200

    matrixcolor InvertMatrix(0.0)
    linear 2.5 angle i+360

    matrixcolor InvertMatrix(1.0)
    linear 2.5 angle i+360
    repeat

transform rotate_animation_2(i=0):
    anchor (0.5,0.5) around (0.5,0.5) angle i radius 200

    matrixcolor InvertMatrix(0.0)
    linear 2.5 angle i+360 radius 0

    matrixcolor InvertMatrix(1.0)
    linear 2.5 angle i+360 radius 200
    repeat

transform rotate_animation_3(i=0):
    anchor (0.5,0.5) around (0.5,0.5) angle i radius 200

    matrixcolor InvertMatrix(0.0)
    linear 2.5 angle i+360 radius 1

    matrixcolor InvertMatrix(1.0)
    linear 2.5 angle i+360 radius 200
    repeat

label start:
    "START"

    scene image_0 at rotate_animation_1(0)
    show image_90 at rotate_animation_1(90)
    show image_180 at rotate_animation_1(180)
    show image_270 at rotate_animation_1(270)

    "EXAMPLE 1"

    scene image_0 at rotate_animation_2(0)
    show image_90 at rotate_animation_2(90)
    show image_180 at rotate_animation_2(180)
    show image_270 at rotate_animation_2(270)

    "EXAMPLE 2"

    scene image_0 at rotate_animation_3(0)
    show image_90 at rotate_animation_3(90)
    show image_180 at rotate_animation_3(180)
    show image_270 at rotate_animation_3(270)

    "EXAMPLE 3"

    "EOL"

    return
```

https://github.com/renpy/renpy/assets/106859253/2543da92-ed1b-42d8-9076-62b97f296491

The expected behavior of all transforms here is that an interpolation from angle i+360 to angle i+360 shouldn't result in any angular movement. Furthermore, rotate_animation_2 and _3 only differ by going to radius 0 and radius 1 respectively, and somehow result in different angular movement.

Here's the exact project I used to test on 8.1.1, along with its log.txt
[Angle and Radius.zip](https://github.com/renpy/renpy/files/12010731/Angle.and.Radius.zip)

**Comment by renpytom** [comment]
Fixed in cb80aea90 . Because this is a fairly intrusive change, I'm holding it back for 8.2, and not 8.1.2.
