### ISSUE TITLE
Launcher project folder

### ISSUE THREAD

**Issue by Demon11** [renpy/renpy#4836]
The launcher preferences for selecting the project folder doesn't work using nightly build: 8.1.2.23071003

**Comment by renpytom** [comment]
Do you have the error message? There was a problem in 8.1.2.23071001, but 8.1.2.23071003 should have the fix in it.

**Comment by Demon11** [comment]
It doesn't show any error message, but when i select the folder, the continue button doesn't appear anymore and it doesn't select the folder. It still happens in the latest nightly build.
