### ISSUE TITLE
Absolute does not work in screens / as size

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4840]
I'm not sure of the extent of the presence of the bug, but here is one reliable summoning:
```rpy
screen absoluter():
    fixed:
        xysize (absolute(100), absolute(100))
        add Solid("#00f", xysize=(50, 50)) align (1., 1.)
```
If you use `(100, 100)`, the blue square's bottom right corner shows the coordinates (100, 100), as it should. But for some reason, if you use absolute(100) instead of 100, which shouldn't change anything, the blue square disappears.
If you write `absolute(.5)` instead, the blue square appears at the center of the screen, confirming the data is interpreted as a relative position.

**Comment by renpytom** [comment]
Merging #4709 seems to have fixed this.
