### ISSUE TITLE
A VN that is updated to 8.1.x will make all save files have current date/time of first run

### ISSUE THREAD

**Issue by bkats** [renpy/renpy#4845]
A update on a vn that uses the new 8.1.x version causes to all save files to get current date/time, because of updating them with a signature.
Now it is harder to find the correct save file. (I don't keep them in an exact order and there is not always a save name option)

This can be fixed by using the date/time not from the file it self, but from a file inside the zip (e.g. screenshot)

You could make it even more robust by adding date/time to the json information, but you still need the fallback option when it is not there.

**Comment by HorBro38** [comment]
This should have been fixed in https://github.com/renpy/renpy/commit/d72de4ab686f0e1eb1a308f78a0274af8dbfde6d by issue https://github.com/renpy/renpy/issues/4736

**Comment by bkats** [comment]
Sorry I overlooked that issue, but still it would be nice if a future update would display correct date/time for already converted files that no longer have correct date/time.

**Comment by bkats** [comment]
Is this for real @MiiNiPaa? Already give that solution in my first comment! Get the date/time from a file inside the zip file!

**Comment by renpytom** [comment]
I don't plan to do any further work on this. (Just too many other things to work on.)
