### ISSUE TITLE
Occasional visual artifacts scaling Frame()s in OpenGL

### ISSUE THREAD

**Issue by SpikyCaterpillar** [renpy/renpy#485]
I'm seeing occasional glitches where the corners of a Frame are rendered at a slightly different size than the body at some window sizes.  Screenshots:
![screenshot0001](https://cloud.githubusercontent.com/assets/4422093/4749928/d93e7196-5a8b-11e4-9c4d-48cfec5d2130.png)
![screenshot0002](https://cloud.githubusercontent.com/assets/4422093/4749931/eb33a2fe-5a8b-11e4-927c-40cc248e33e4.png)
![screenshot0002-quitbugged](https://cloud.githubusercontent.com/assets/4422093/4749936/f2c6a6a6-5a8b-11e4-9b5e-1e14ce3d6b53.png)
![screenshot0003](https://cloud.githubusercontent.com/assets/4422093/4749940/fbcc8252-5a8b-11e4-8f60-92359529aab9.png)
![screenshot0004](https://cloud.githubusercontent.com/assets/4422093/4749942/02fb436a-5a8c-11e4-8a7a-531685f3af07.png)

![screenshot0005-prefsbugged](https://cloud.githubusercontent.com/assets/4422093/4749947/0e6b9c5e-5a8c-11e4-994a-632c5db5fc20.png)

Log.txt (Note: most of the screenshots are from an earlier invocation of the tutorial):
Thu Oct 23 01:12:52 2014
Linux-3.2.0-4-amd64-x86_64-with-debian-7.7
Ren'Py 6.18.3.761
Ren'Py Tutorial 6.18 "... through shared popular culture."

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(800, 600)
Vendor: 'VMware, Inc.'
Renderer: 'Gallium 0.4 on llvmpipe (LLVM 0x209)'
Version: '2.1 Mesa 8.0.5'
Display Info: <VideoInfo(hw = 0, wm = 1,video_mem = 0
	     blit_hw = 0, blit_hw_CC = 0, blit_hw_A = 0,
	     blit_sw = 0, blit_sw_CC = 0, blit_sw_A = 0,
	     bitsize  = 32, bytesize = 4,
	     masks =  (16711680, 65280, 255, 0),
	     shifts = (16, 8, 0, 0),
	     losses =  (0, 0, 0, 8),
	     current_w = 1920, current_h = 1080
>

Extensions:
    
    GL_AMD_draw_buffers_blend
    GL_APPLE_packed_pixels
    GL_APPLE_vertex_array_object
    GL_ARB_ES2_compatibility
    GL_ARB_copy_buffer
    GL_ARB_depth_texture
    GL_ARB_draw_buffers
    GL_ARB_draw_buffers_blend
    GL_ARB_draw_elements_base_vertex
    GL_ARB_draw_instanced
    GL_ARB_explicit_attrib_location
    GL_ARB_fragment_coord_conventions
    GL_ARB_fragment_program
    GL_ARB_fragment_program_shadow
    GL_ARB_fragment_shader
    GL_ARB_framebuffer_object
    GL_ARB_half_float_pixel
    GL_ARB_half_float_vertex
    GL_ARB_instanced_arrays
    GL_ARB_map_buffer_range
    GL_ARB_multisample
    GL_ARB_multitexture
    GL_ARB_occlusion_query
    GL_ARB_occlusion_query2
    GL_ARB_pixel_buffer_object
    GL_ARB_point_parameters
    GL_ARB_point_sprite
    GL_ARB_provoking_vertex
    GL_ARB_robustness
    GL_ARB_sampler_objects
    GL_ARB_shader_objects
    GL_ARB_shader_texture_lod
    GL_ARB_shading_language_100
    GL_ARB_shadow
    GL_ARB_sync
    GL_ARB_texture_border_clamp
    GL_ARB_texture_compression
    GL_ARB_texture_compression_rgtc
    GL_ARB_texture_cube_map
    GL_ARB_texture_env_add
    GL_ARB_texture_env_combine
    GL_ARB_texture_env_crossbar
    GL_ARB_texture_env_dot3
    GL_ARB_texture_float
    GL_ARB_texture_mirrored_repeat
    GL_ARB_texture_non_power_of_two
    GL_ARB_texture_rectangle
    GL_ARB_texture_rg
    GL_ARB_texture_storage
    GL_ARB_texture_swizzle
    GL_ARB_transpose_matrix
    GL_ARB_vertex_array_bgra
    GL_ARB_vertex_array_object
    GL_ARB_vertex_buffer_object
    GL_ARB_vertex_program
    GL_ARB_vertex_shader
    GL_ARB_vertex_type_2_10_10_10_rev
    GL_ARB_window_pos
    GL_ATI_blend_equation_separate
    GL_ATI_draw_buffers
    GL_ATI_separate_stencil
    GL_ATI_texture_compression_3dc
    GL_ATI_texture_env_combine3
    GL_ATI_texture_float
    GL_ATI_texture_mirror_once
    GL_EXT_abgr
    GL_EXT_bgra
    GL_EXT_blend_color
    GL_EXT_blend_equation_separate
    GL_EXT_blend_func_separate
    GL_EXT_blend_minmax
    GL_EXT_blend_subtract
    GL_EXT_compiled_vertex_array
    GL_EXT_copy_texture
    GL_EXT_draw_buffers2
    GL_EXT_draw_instanced
    GL_EXT_draw_range_elements
    GL_EXT_fog_coord
    GL_EXT_framebuffer_blit
    GL_EXT_framebuffer_multisample
    GL_EXT_framebuffer_object
    GL_EXT_gpu_program_parameters
    GL_EXT_multi_draw_arrays
    GL_EXT_packed_depth_stencil
    GL_EXT_packed_float
    GL_EXT_packed_pixels
    GL_EXT_pixel_buffer_object
    GL_EXT_point_parameters
    GL_EXT_polygon_offset
    GL_EXT_provoking_vertex
    GL_EXT_rescale_normal
    GL_EXT_secondary_color
    GL_EXT_separate_shader_objects
    GL_EXT_separate_specular_color
    GL_EXT_shadow_funcs
    GL_EXT_stencil_two_side
    GL_EXT_stencil_wrap
    GL_EXT_subtexture
    GL_EXT_texture
    GL_EXT_texture3D
    GL_EXT_texture_compression_latc
    GL_EXT_texture_compression_rgtc
    GL_EXT_texture_cube_map
    GL_EXT_texture_edge_clamp
    GL_EXT_texture_env_add
    GL_EXT_texture_env_combine
    GL_EXT_texture_env_dot3
    GL_EXT_texture_lod_bias
    GL_EXT_texture_mirror_clamp
    GL_EXT_texture_object
    GL_EXT_texture_rectangle
    GL_EXT_texture_sRGB
    GL_EXT_texture_sRGB_decode
    GL_EXT_texture_shared_exponent
    GL_EXT_texture_snorm
    GL_EXT_texture_swizzle
    GL_EXT_vertex_array
    GL_EXT_vertex_array_bgra
    GL_IBM_multimode_draw_arrays
    GL_IBM_rasterpos_clip
    GL_IBM_texture_mirrored_repeat
    GL_INGR_blend_func_separate
    GL_MESA_pack_invert
    GL_MESA_texture_signed_rgba
    GL_MESA_window_pos
    GL_MESA_ycbcr_texture
    GL_NV_blend_square
    GL_NV_conditional_render
    GL_NV_fog_distance
    GL_NV_light_max_exponent
    GL_NV_packed_depth_stencil
    GL_NV_primitive_restart
    GL_NV_texgen_reflection
    GL_NV_texture_env_combine4
    GL_NV_texture_rectangle
    GL_OES_EGL_image
    GL_OES_read_format
    GL_SGIS_generate_mipmap
    GL_SGIS_texture_border_clamp
    GL_SGIS_texture_edge_clamp
    GL_SGIS_texture_lod
    GL_SUN_multi_draw_arrays
Number of texture units: 8
Using shader environment.
Using copy RTT.
Using gl renderer.
Texture testing:
- Hardware max texture size: 4096
- 64px textures work.
- 128px textures work.
- 256px textures work.
- 512px textures work.
- 1024px textures work.
- 2048px textures work.
Performance test:
- Target is 5 frames in 0.333333333333 seconds.
- Frame drawn at 0.000000 seconds.
- Frame drawn at 0.171523 seconds.
- Frame drawn at 0.187502 seconds.
- Frame drawn at 0.202100 seconds.
- Frame drawn at 0.216637 seconds.
- 0.216637 seconds to render 5 frames.

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(400, 300)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(400, 300)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(400, 300)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(404, 302)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(400, 300)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(402, 300)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(403, 300)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(591, 467)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(400, 300)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(626, 529)

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(400, 300)

**Comment by renpytom** [comment]
Since I don't think this is a Ren'Py bug, I'm closing it to clean up the tracker.
