### ISSUE TITLE
dissolve transition completes immediately, from one Movie displayable to another.

### ISSUE THREAD

**Issue by Saltome** [renpy/renpy#4850]
The issue is easy to recreate, I have a simple label which shows Movies defined as images, as background. With some text in between.
When transitioning between the two Movie displayables with a dissolve the transition is completed immediately.

It persists on renpy 8.0.3 through 7.5.1.
I've narrowed the problem down to me using "movie_dp" as the movie channel. 
When using the default "movie" channel the issue doesn't occur.
I attempted to register the "movie_dp" channel but it would still not transition correctly.

This doesn't happen with the pixellate transition, which might suggest an issue with dissolve itself.

**Comment by renpytom** [comment]
If you're using the same channel for the two Movie displayables, than this isn't a bug. You'll need to use multiple movie channels if you want to movies to play at once, which is needed to dissolve between them.

**Comment by Saltome** [comment]
Fair enough, you're spot on. However the options this leaves me with don't seem ideal.
I have to either be stuck using the default movie channel, and suffer the game crashing every time I reload the project because the automatically generated serialized channels disappear after reload. 
Or define unique channels for every single animation to ensure the dissolve works.
Or figure out a way to determine which channel to use on the fly, so I can only have the minimum number of channels required.

**Comment by renpytom** [comment]
Are you on an old version of Ren'Py? At least in the nightly fix builds, the issue with undefined channels should be fixed.

**Comment by Saltome** [comment]
Yes, the specific project uses. 7.5.1.

Another thing that surfaced during my exploration of this issue is that when I was looking through the code I found that user registered movie channels do not behave as the default one. Because a number of code blocks only execute if the channel name is 'movie' as opposed to when the movie variable is true. Is there a specific reason to have this separation?

**Comment by renpytom** [comment]
Yes, the reason is compatibility with older games that used the movie channel for fullscreen movies.

**Comment by Saltome** [comment]
Ah, yes backwards compatibility.
This doesn't necessarily exclude the possibility of making user defined movie channels behave like the default one, it would just require adding on to the existing logic.
This is rather tangential to the dissolve issue though. Should we end the discussion here, or is it worth further attention?

At this point I can work around the issue by using the default movie channel and disabling automatic channel generation in developer mode to avoid the missing channels error.
Might still need the ability to dissolve multiple movie displayables further down the line though, so the movie channel won't be enough.
