### ISSUE TITLE
Ability to change the font per character for the history screen 

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#4851]
This is a strange feature request but something I ran into recently and don't really have a solution for it...
 I have a special character who speaks in weird symbols, using an unorthodox font that makes only symbols, for example:
Bober: "*:･ﾟ✧*:･ﾟ" 

Current problem: in the history screen, it would be using a general standard font so it wouldn't actually show Bober's message, but only ▯▯▯▯ for nonrepresentable characters every time he speaks.

Hmm, is there already a solution for this? 
If not, I was thinking if it was possible for certain characters, to be displayed in the history screen with a different font attached to them.

**Comment by Elckarow** [comment]
you can use `config.history_callbacks` [https://www.renpy.org/doc/html/config.html#var-config.history_callbacks](https://www.renpy.org/doc/html/config.html#var-config.history_callbacks):

```rpy
init python:
    def save_font(h):
        if h.who == "my_character":
            h.font = "special_font.ttf"
        else:
            h.font = "normal_font.ttf"

    config.history_callbacks.append(save_font)
```

**Comment by mal** [comment]
Have you added `font h.font` to your `history` screen?

```diff
                 text what:
+                    font h.font
                     substitute False
```

**Comment by Org-gith** [comment]
I didn't had it, this must be it, but I get this error telling me there is no attribute font:
![image](https://github.com/renpy/renpy/assets/78823063/175b6370-f199-4b96-8956-c1b32690cfca)

**Comment by mal** [comment]
If you have pre-existing history (i.e. from loading a save) then older entries wouldn't have the new attribute you're now adding, so you'd need to compensate for that. i.e.
```diff
                 text what:
                     substitute False
+
+                    if hasattr(h, 'font'):
+                        font h.font
```
If you're still in development and don't need to retain save compatibility then you should be able to use the original with the need to check (assuming you always set it in your callback).

**Comment by Org-gith** [comment]
This worked! Really thank you for helping me mr, and thanks Elckarow.
I will close since it was always possible, maybe if someone runs into this, he could find the solution there.
