### ISSUE TITLE
Apply Transforms to screenshot when making a save

### ISSUE THREAD

**Issue by KiloOscarSix** [renpy/renpy#4860]
This may not be possible, however, we've built a custom `fileslot` screen using `AlphaMask` and `Crop` to create a unique design. 
![image](https://github.com/renpy/renpy/assets/26691547/7691ee82-95e4-4ce9-9d98-d09d690d1c51)
 

However, I suspect this is somewhat computationally expensive. Instead of running these functions multiple times every screen draw, having a callback that saves the screenshot with these Transforms already applied might be more efficient, allowing the fileslot screen to just display the static images.

**Comment by Gouvernathor** [comment]
If you crop the screenshot at the saving stage, you can't change the layout of the saves screens depending on another way to crop them, old saves would not play well with that despite being potentially perfectly compatible. I don't think that's an idea that should end up in the engine for that reason (though it may be fine in specific games which pledge never to change the saves layout in future releases or to always break saves compatibility), too many beginners would screw their own screenshot data.

I also suspect the same implementation difficulties would arise as the idea to hide the interface before the screenshot.

**Comment by mal** [comment]
Likely requires the same functionality discussed in #4852 - the ability to "draw the screen and not show it".

**Comment by renpytom** [comment]
I don't  think this is something that I'm likely to add to Ren'Py, as I think presentation of screenshots is better done after the screenshot is loaded.
