### ISSUE TITLE
Music loop property doesn't appear to work as advertised

### ISSUE THREAD

**Issue by inismor** [renpy/renpy#4864]
According to the docs, if a value is given in the loop property, the music should loop starting from the given value after reaching the end of the file. It doesn't appear to accept any value. It just loops all the way from the beginning of the file.

`play music "<loop 5.0>audio/test_music.mp3" # does not loop from 5 seconds, but from the start of the file`

**Comment by JamiesonC** [comment]
Does it work correctly if the MP3 is converted to OGG? I'm just curious if this is yet one more feature that doesn't work for certain formats (MP3 in particular).

**Comment by inismor** [comment]
Converted to OGG, same behavior.

**Comment by Vulcan-Coder** [comment]
> Converted to OGG, same behavior.

You might want to check the actual audio file. Someone in the discord server had a similar problem and it turned out to be a problem with the audio file.

**Comment by inismor** [comment]
I've tried with a couple of different files. I edited them myself with Audacity--had to, so that loop starts and ends would line up.

**Comment by inismor** [comment]
Weird. I loaded up my Audacity project and exported the audio again. Now it works. Not sure what side of the alternate universe I landed on, but this happened with a couple of different files before it started working.
