### ISSUE TITLE
Add CopyToClipboard action

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#4868]
A helpful action for devs could be the CopyToClipboard() action:

```
    def CopyToClipboard(s):
        s = str(s)
        return Function(pygame_sdl2.scrap.put, pygame_sdl2.scrap.SCRAP_TEXT, s.encode("utf8"))
```

I found it on a cookbook years ago and it's a life-saver. I found it again on the translation id screen.

**Comment by Gouvernathor** [comment]
To be fully supported, it would need to work on the web and on mobile platforms. Or to be documented just as a dev tool, but that would be a bit limited.

**Comment by Gouvernathor** [comment]
Actually I think there would be uses for that outside of a dev tool, to use renpy to make things whose end purpose is not strictly gaming, for example a RPG character generator, or a school test of some sorts, if you can copy your result formatted however you want and share it it would be a great feature.
Seen on that side, I think in addition to making it part of the API we should try and make it available on other platforms, but we should probably not wait until we manage that before publishing it.
