### ISSUE TITLE
Game crash in Samsung Galaxy S21 Ultra 

### ISSUE THREAD

**Issue by pineapple010108** [renpy/renpy#4869]
Hello, I was uploaded my project with android version to an app store. They reported that the game crashed in Samsung Galaxy S21 Ultra.Is there any solution to fix this bug？

**Comment by renpytom** [comment]
There isn't close to enough information here to diagnose the problem. Please make sure you're on the latest Ren'Py, and if it still crashes there, please post a logcat showing what happened when the crash occurred.

**Comment by pineapple010108** [comment]
Here is the logcat file.
https://drive.google.com/file/d/1zLCT821U8WqepMN9grHup8-vKDgF_CN_/view?usp=drivesdk

**Comment by pineapple010108** [comment]
Thanks for the responding. I did not modify renpy.py and I use clean Ren'Py. But the app store "Tap Tap" had to add their own api to my original apk automatically once I uploaded my game to the store.

**Comment by renpytom** [comment]
I'm closing this, as this is likely an issue with Tap Tap launching Ren'Py incorrectly, that should be taken up with their support.
