### ISSUE TITLE
Renpy Game brings the Windowmanager to crash

### ISSUE THREAD

**Issue by Severus157** [renpy/renpy#487]
The Renpy Game Loren the Amazon Princess, won't work in Fullscreen on Kubuntu 14.10. It just kills the Windowmanager several Times. Here is the Crash Report, if it helps to fix the problem.

Application: kwin_x11 (5.1.0)
 (Compiled from sources)
Qt Version: 5.3.0
Operating System: Linux 3.16.0-24-generic x86_64
Distribution: Ubuntu 14.10

-- Information about the crash:
- What I was doing when the application crashed: 
  I was trying to play a Game on Steam, which uses Ren'py Framework. Loren the Amazon.
- Unusual behavior I noticed:
  It crashes multiple times. And with every Start of the Game.
- Custom settings of the application: 
  None.

The crash can be reproduced every time.

-- Backtrace:
Application: KWin (kwin_x11), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fbcf0704800 (LWP 11923))]

Thread 4 (Thread 0x7fbcd1d03700 (LWP 11931)):
#0  0x00007fbcf00601c3 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fbcee1403c1 in qt_safe_select (nfds=14, fdread=fdread@entry=0x7fbcc4000a78, fdwrite=fdwrite@entry=0x7fbcc4000d08, fdexcept=fdexcept@entry=0x7fbcc4000f98, orig_timeout=orig_timeout@entry=0x0) at kernel/qcore_unix.cpp:83
#2  0x00007fbcee140b93 in QEventDispatcherUNIX::select (this=this@entry=0x7fbcc40008c0, nfds=<optimized out>, readfds=readfds@entry=0x7fbcc4000a78, writefds=writefds@entry=0x7fbcc4000d08, exceptfds=exceptfds@entry=0x7fbcc4000f98, timeout=timeout@entry=0x0) at kernel/qeventdispatcher_unix.cpp:328
#3  0x00007fbcee142012 in QEventDispatcherUNIXPrivate::doSelect (this=this@entry=0x7fbcc40008e0, flags=..., flags@entry=..., timeout=timeout@entry=0x0) at kernel/qeventdispatcher_unix.cpp:204
#4  0x00007fbcee142585 in QEventDispatcherUNIX::processEvents (this=0x7fbcc40008c0, flags=...) at kernel/qeventdispatcher_unix.cpp:615
#5  0x00007fbcee0eb042 in QEventLoop::exec (this=this@entry=0x7fbcd1d02dc0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#6  0x00007fbcedeaf4a4 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:511
#7  0x00007fbcedeb42ee in QThreadPrivate::start (arg=0x100a610) at thread/qthread_unix.cpp:345
#8  0x00007fbce692b0a5 in start_thread (arg=0x7fbcd1d03700) at pthread_create.c:309
#9  0x00007fbcf006884d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7fbcc97bd700 (LWP 11936)):
#0  0x00007fbcf00601c3 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fbcee1403c1 in qt_safe_select (nfds=17, fdread=fdread@entry=0x7fbcc0000a78, fdwrite=fdwrite@entry=0x7fbcc0000d08, fdexcept=fdexcept@entry=0x7fbcc0000f98, orig_timeout=orig_timeout@entry=0x0) at kernel/qcore_unix.cpp:83
#2  0x00007fbcee140b93 in QEventDispatcherUNIX::select (this=this@entry=0x7fbcc00008c0, nfds=<optimized out>, readfds=readfds@entry=0x7fbcc0000a78, writefds=writefds@entry=0x7fbcc0000d08, exceptfds=exceptfds@entry=0x7fbcc0000f98, timeout=timeout@entry=0x0) at kernel/qeventdispatcher_unix.cpp:328
#3  0x00007fbcee142012 in QEventDispatcherUNIXPrivate::doSelect (this=this@entry=0x7fbcc00008e0, flags=..., flags@entry=..., timeout=timeout@entry=0x0) at kernel/qeventdispatcher_unix.cpp:204
#4  0x00007fbcee142585 in QEventDispatcherUNIX::processEvents (this=0x7fbcc00008c0, flags=...) at kernel/qeventdispatcher_unix.cpp:615
#5  0x00007fbcee0eb042 in QEventLoop::exec (this=this@entry=0x7fbcc97bcdc0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#6  0x00007fbcedeaf4a4 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:511
#7  0x00007fbcedeb42ee in QThreadPrivate::start (arg=0x1a9a810) at thread/qthread_unix.cpp:345
#8  0x00007fbce692b0a5 in start_thread (arg=0x7fbcc97bd700) at pthread_create.c:309
#9  0x00007fbcf006884d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7fbcbcd94700 (LWP 11939)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbcec451b34 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Script.so.5
#2  0x00007fbcec451b79 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Script.so.5
#3  0x00007fbce692b0a5 in start_thread (arg=0x7fbcbcd94700) at pthread_create.c:309
#4  0x00007fbcf006884d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7fbcf0704800 (LWP 11923)):
[KCrash Handler]
#5  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#6  0x00007fbcee677d33 in memcpy (__len=262144, __src=0x7fbcc80f3030, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:51
#7  QImage::copy (this=this@entry=0x7fffae543330, r=...) at image/qimage.cpp:1124
#8  0x00007fbcee67882c in QImage::detach (this=this@entry=0x7fffae543330) at image/qimage.cpp:1070
#9  0x00007fbcee678977 in QImage::scanLine (this=this@entry=0x7fffae543330, i=i@entry=0) at image/qimage.cpp:1514
#10 0x00007fbcee6a49df in QPixmap::setMask (this=this@entry=0x7fffae5433f0, mask=...) at image/qpixmap.cpp:636
#11 0x00007fbcef6f80ec in KXUtils::createPixmapFromHandle (pixmap=<optimized out>, pixmap_mask=<optimized out>) at ../../src/kxutils.cpp:173
#12 0x00007fbcef6fe409 in KWindowSystemPrivateX11::icon (this=0x7fbcc80f3030, win=119537686, width=16, height=-1, scale=184, flags=3) at ../../src/kwindowsystem_x11.cpp:686
#13 0x00007fbcef6f4bd8 in KWindowSystem::icon (win=119537686, width=width@entry=16, height=height@entry=16, scale=scale@entry=true, flags=flags@entry=3) at ../../src/kwindowsystem.cpp:466
#14 0x00007fbcefbc05de in operator() (scale=true, size=16, __closure=<synthetic pointer>) at ../client.cpp:2083
#15 KWin::Client::getIcons (this=this@entry=0x245de50) at ../client.cpp:2088
#16 0x00007fbcefbf9329 in KWin::Client::manage (this=this@entry=0x245de50, w=w@entry=119537686, isMapped=isMapped@entry=false) at ../manage.cpp:137
#17 0x00007fbcefba946d in KWin::Workspace::createClient (this=0x1000a20, w=119537686, is_mapped=<optimized out>) at ../workspace.cpp:467
#18 0x00007fbcefbe98bf in KWin::Workspace::workspaceEvent (this=0x1000a20, e=0x7fbcd4012bf0) at ../events.cpp:430
#19 0x00007fbcee0ea420 in QAbstractEventDispatcher::filterNativeEvent (this=<optimized out>, eventType=..., message=message@entry=0x7fbcd4012bf0, result=result@entry=0x7fffae5439d8) at kernel/qabstracteventdispatcher.cpp:468
#20 0x00007fbcda240aa8 in QXcbConnection::handleXcbEvent (this=this@entry=0xf41a00, event=event@entry=0x7fbcd4012bf0) at qxcbconnection.cpp:823
#21 0x00007fbcda241f1b in QXcbConnection::processXcbEvents (this=0xf41a00) at qxcbconnection.cpp:1232
#22 0x00007fbcee11d12a in QObject::event (this=0xf41a00, e=<optimized out>) at kernel/qobject.cpp:1241
#23 0x00007fbceedbf16c in QApplicationPrivate::notify_helper (this=0xf34670, receiver=0xf41a00, e=0x7fbcd4001660) at kernel/qapplication.cpp:3504
#24 0x00007fbceedc441e in QApplication::notify (this=0x7fffae5440a0, receiver=0xf41a00, e=0x7fbcd4001660) at kernel/qapplication.cpp:3287
#25 0x00007fbcee0ed81b in QCoreApplication::notifyInternal (this=0x7fffae5440a0, receiver=0xf41a00, event=event@entry=0x7fbcd4001660) at kernel/qcoreapplication.cpp:935
#26 0x00007fbcee0ef7e3 in sendEvent (event=0x7fbcd4001660, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:237
#27 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0xf252c0) at kernel/qcoreapplication.cpp:1539
#28 0x00007fbcee142422 in QEventDispatcherUNIX::processEvents (this=0xf6a810, flags=flags@entry=...) at kernel/qeventdispatcher_unix.cpp:587
#29 0x00007fbcda2927dd in QUnixEventDispatcherQPA::processEvents (this=<optimized out>, flags=...) at eventdispatchers/qunixeventdispatcher.cpp:70
#30 0x00007fbcee0eb042 in QEventLoop::exec (this=this@entry=0x7fffae543fc0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#31 0x00007fbcee0f2acc in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1188
#32 0x00007fbcee62a1dc in QGuiApplication::exec () at kernel/qguiapplication.cpp:1436
#33 0x00007fbceedbd795 in QApplication::exec () at kernel/qapplication.cpp:2749
#34 0x00007fbcf0337923 in kdemain (argc=3, argv=0x7fffae5441f8) at ../main_x11.cpp:294
#35 0x00007fbceff8fec5 in __libc_start_main (main=0x4007d0 <main(int, char**)>, argc=3, argv=0x7fffae5441f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffae5441e8) at libc-start.c:287
#36 0x00000000004007fe in _start ()

**Comment by nok-ko** [comment]
This issue is referencing older issues and confusing things a bit. Not sure if you can edit other people's issue posts, but putting the error message in code tags might be helpful here.
