### ISSUE TITLE
Inertia warp crash.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#4870]
![image](https://github.com/renpy/renpy/assets/379804/78aaee90-e1b8-4dd8-8517-d2aa758f9f59)

**Comment by mal** [comment]
Additional info: Triggering this appears to require a `done` value less than `-118`.

**Comment by renpytom** [comment]
This was reported in 8.1.1.

**Comment by mal** [comment]
I think @qTich is suggesting that because it was reported against 8.1.1, which doesn't include the fix in #4752, this issue may already be resolved in git.
