### ISSUE TITLE
New `if_changed`/`loop_only` behaviour in `music.play()` incorrectly restarts looping music tracks (8.1.1/Nightly)

### ISSUE THREAD

**Issue by mithost** [renpy/renpy#4872]
**AUGUST 14th UPDATE.** Please read the comments and TL;DR for updates on this issue. I'll provide a new TL;DR below and update the title with a better one to match. The existing reproducible example is still a relevant example of the issue.

TL;DR: Calling `play` on a track that is already looping with `if_changed` set to `True` will queue the same track as what is currently playing due to the removal of `loop_only` in commit `b0b096b`. This track will play from the **very beginning once** the current track reaches it's end, **ignoring any loop points defined in the track**. This leads to an abrupt interruption and restart to the track if it was made with a specific `loop` loop point in mind, even if that loop point is included in the track's file name.

Comments in code as well as documentation mention that this will "queue up an additional loop" to the currently playing music. If you have a set `loop` loop point that you are expecting the track to jump back to, this is ignored and the track will abruptly start again at the beginning (due to it being queued a second time).

----- 

Original body, describes discovery and recreating the issue:

After updating Ren'Py to 8.1.1 from 8.0.3, we noticed that our main menu theme (`config.main_menu_music`) would loop correctly for a few minutes, loop incorrectly once, then resume looping correctly afterwards. On this incorrect loop, the song starts again from the very beginning once reaching the end of the track as opposed to jumping directly to the loop point roughly 22 seconds into the track as it would on a successful loop. This issue does not occur on 8.0.3 or any other previously tested versions of Ren'Py (as far back as 6.99). We have observed this issue on Windows 10 and Mac.

When trying to recreate this issue, we discovered that the incorrect loop would only occur in situations where the main menu was entered from `splashscreen`, which in our project includes a call to start the main menu music during the game's intro sequence using `$ renpy.music.play(config.main_menu_music)`. The incorrect loop would not occur when entering the main menu from other parts of the game such as the pause menu or the ending of a scene.

To isolate and confirm the issue, we created a blank project on Ren'Py 8.1.1 where the only additions were our existing main menu theme file and a splashscreen label that contains `$ renpy.music.play(config.main_menu_music)` (value assigned in options.rpy). We were able to recreate the issue in this blank project, and I've included it as a .zip below.

[mainmenumusictest.zip](https://github.com/renpy/renpy/files/12175915/mainmenumusictest.zip)

Recreation steps: 

1. Unzip provided project
2. Start project in Ren'Py 8.1.1
3. Idle on main menu until track loops
4. Observe the music jumping back to the beginning of the track, not the loop point
5. Continue to idle, observing that it loops correctly forever after the one incorrect loop has occurred.
6. (Optional) Start a new game, exit to main menu, observe that the incorrect loop never occurs.

Additional investigation showed that reverting the files included in commit `b0b096b` to their previous revisions causes the incorrect loop to not occur, both in the test blank project and in our full game. This lines up with us not encountering this issue before updating to Ren'Py 8.1.1.

**Comment by mithost** [comment]
August 14th update: In any situation where a looping track is queued on top of itself with `if_changed`, the track will begin at the very beginning after reaching it's end point (either the end of file, or the user defined `to` point) ignoring any user set `loop` parameters for the audio track. 

In `b0b096b` (included in release 8.1.1) the `loop_only` parameter was removed from `enqueue()`. This made it so even in situations where a song was already playing on loop, trying to play it again would add it to the queue. When the currently playing track reaches it's end of file, it looks like it decides to play the next song in the queue from the very beginning as opposed to continuing it's current loop. 

If a track is not designed with a loop point in mind (loops back to the very beginning of the intro naturally) this will not be noticed, but if a track is designed with a `loop` point in mind (i.e. `play music "<loop 6.333>song.opus"`) this behaviour will be ignored and the track will abruptly end before the next track in the queue (itself) begins from the very beginning.

This can be observed in the above situation (playing `config.main_menu_music` before `00start`), but is also reproducible using the example provided in documentation for `if_changed` [here](https://www.renpy.org/doc/html/audio.html) (provided the track has a `loop` point defined):

![image](https://github.com/renpy/renpy/assets/55294388/8e18d214-9e01-4aa2-8f00-de61cdde8580)

I'm not sure what the best solution would be, but a few suggestions would be either to:

1. Ensure that newly queued tracks start at the loop point if they are queued directly behind the same track, or...
2. Prevent a track from queuing itself directly behind itself (restore previous functionality, allow track to continue looping without interruption).

**Comment by Gouvernathor** [comment]
So I guess this one shouldn't be closed

**Comment by mithost** [comment]
> So I guess this one shouldn't be closed

It looks like this issue was referenced by mistake/typo, as the issue that better fits [05e72cb](https://github.com/renpy/renpy/commit/05e72cbe274a6bce76521ca5f13e70a4cb606e3f) is #4827 (the 2 and 7 are flipped).

**Comment by mithost** [comment]
Additional context for @Gouvernathor 

This issue had already been closed with a fix (#4914) on August 20th. While @renpytom 's August 26th commit referenced this issue by mistake instead of the correct one, this issue was already properly resolved and closed before that mistake occurred. This should be re-closed (unless the music loop bug this issue references has popped back up, of course).

**Comment by Gouvernathor** [comment]
Oh, right.
