### ISSUE TITLE
Feature proposal: store total playtime since game start in save info so developers can show it on save slot

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#4873]
I'm coming from https://lemmasoft.renai.us/forums/viewtopic.php?t=40407 where we are looking at a way to track game time. Currently we cumulate `renpy.get_game_runtime()`.

Ultimately, it would be nice to have this feature as standard in Renpy: save total game playtime on save, and display it on save info. This helps checking which save is more advanced without comparing dates (assuming player doesn't backtrack), compare to game average playtime to see how advanced they are without looking at Shift+Alt+P debug progress, etc.

And this can be useful in any game, so it's better if the feature is integrated in Renpy, enabled by default. Developers could disable it if they need a more custom way to indicate progress (for instance, they could use a tag "Chapter X" that they set at the beginning of each chapter - or even a progress "X%" if they don't mind preparing the player to the end, as done in some RPG and adventure games). They can always customize the save slot screen anyway.

**Comment by renpytom** [comment]
This probably isn't something that we should have as part of the default interface - I think it might be inaccurate in many games. But it might make sense to include the data in the default json, so if someone wants to include it, it's already there in all their saves.

**Comment by mal** [comment]
I've tried this before and it ended up super confusing for players. Leaving the game open, saves for different branches, and skipping seen text were all things that contributed to wildly different times played even when saves were for the same point in the same route, and were a terrible indication of progress.

I agree with Gouvernathor that it should probably be a creator decision, rather than dumping it into all saves. It doesn't feel overly burdensome to do, and the creator in question already needs to be sufficiently advanced to modify the slots screen to make any use of it.

**Comment by hsandt** [comment]
**About making it faster to add**

> I'ts easy enough to add a dozen line of code that calculates that value and put it in a json slot, and show that how you want it shown in the saves screen. If creators can customize the save screen anyway, it should be a decision on their individual part.

I thought so looking at the forum thread, but also find someone who couldn't make it work at once: https://www.reddit.com/r/RenPy/comments/o6vrxw/playtime_is_not_working_anymore/

It seems they either solved it or don't need it anymore, but I still think a solution out-of-the-box (one or two lines) would reduce friction. If it doesn't fit every time, there could at least be an API or variable that does the job and can be plugged in one line. Which comes back to renpytom's suggestion:

>  it might make sense to include the data in the default json, so if someone wants to include it, it's already there in all their saves.

**About making it default or well documented**

I'm fine with not having it as default, but this should, however, be well documented and explained in tutorials (website or interactive), or added as part of project startup parameters, so as many developers as possible are aware of it. This is because it's a feature that works well with simple, kinetic/linear games, for which we expect to have many developers who tweak *fewer* things in their project. Whereas the developers who use advanced features, a lot of branching, want to display progress based on exploration of all blocks, etc. are the one who are also the best at tweaking the save slot screen. In fact, I feel mal's last remark

> creator in question already needs to be sufficiently advanced to modify the slots screen to make any use of it

goes in the same direction.

But really, if you advertise it as well as you did with speech bubbles, I wouldn't worry that much: anybody upgrading Renpy will see if it fits their project, more and more projects will use it, and therefore new developers joining will know that the feature exists because they played games using it before. From here, they can search doc, find this issue or the doc/tutorials we would have created in the meantime.

**About using it or not in your game**

> I've tried this before and it ended up super confusing for players. Leaving the game open, saves for different branches, and skipping seen text were all things that contributed to wildly different times played even when saves were for the same point in the same route, and were a terrible indication of progress.

I see different points here:
- time due to leaving the game open or reading slowly: this is true for every RPG time counter as well. This can be fixed by replacing time with percentage progress, as suggested above. But I wouldn't use it as default either because
1. there is no good default value for any project. blocks seen / total blocks is only relevant for kinetic novels, on first play (there is no "blocks seen in this particular game save"
2. some devs don't want to "spoil" approaching end game. Whereas play time is never giving more information than what a player could measure checking the clock.
3. devs need to define what "progress" is for each game, by adding flags at the beginning of each section, chapter, etc. But why not, it may be a nice "feature" to have. However, all Renpy could do is provide an API to easily flag advancement: most of the work would still be on game dev side to actually flag the game events. And that would be another feature, outside the scope of this issue.
- backtracking via loading (instead of backtracking inside game via Page Up/Mouse Scroll Up) and playing again causes time to be rewound: this is no different from any adventure game, it's just that it happens more often in VN. Players can still use the absolute date time to check what save slot they saved last. I don't see how it is more confusing than showing Chapter 1 or Chapter 2: if you go back in a previous save, the chapter number may also decrease.
- skipping things already seen makes the game go faster: it's no different from adventure games... The playtime makes the most sense for the first run. Afterwards, on second run and further, you'll skip tutorials, read dialogues faster, beat monsters faster thanks to your improved skills... so of course you'll finish the game faster. Some RPGs (e.g. Tales of Symphonia) allow New Game+ that keeps track of the play time of your last session and adds further time spent on top of it, that's how I reached 300h... It became so crazy after two runs I just decided to reset the counter anyway. BUT it may be relevant if your game is about exploring branches, which leads to the next point:
- games entirely based around the concept of time branch explorations: I totally get this. In Radiant Historia (which is an RPG, not a VN, but embraces the same concept), the character is actually travelling through time and your game time is the actual time spent by player going through the various time branches. It's great if we can track this. But unless you want to implement that system inside your game, you're better off letting the player load save slots directly (Radiant Historia *needs* the system to be integrated because the character keeps Level and Key Items across time). In which case you lose that information of total playtime, and there is not much doing against it. The only workaround I see is to use some permanent variable that would track the total play time (very similar to Steam's play time, except it would not advance in the main menu). If you reach that level of complexity though, you're probably good enough to tweak save slot to show whatever you want.

Anyway, you'll have to see with your specific case.

**About player circumventing the system to find out session time anyway**

Finally, for advanced _players_ who just need the info, we could add `get_game_runtime()` to the Shift+Alt+P progress debug screen. Just so they know how much time they spent in the current session (and they can sum it up with previous sessions manually if they need to). But that would be another feature request.

I also noticed you could just run `renpy.get_game_runtime()` in the console (Shift+O), which is great, but the console is a debug feature and seems deactivated in the game I've installed and played. Whereas Shift+Alt+P is not.

Otherwise, they can use OS system monitor to check renpy process time running, assuming they didn't spend to much time in the menus!

**Conclusion**

I'm good with renpytom's suggestion: presave play time data in save data. It seems that devs will still need to do some time formatting, but this part could be covered in tutorials or with some helper functions.

I will wait and see if the feature becomes popular once it gets implemented.

For personal use as a player, I'll check Shift+Alt+P progress in terms of blocks seen/total blocks, it will work for first run on kinetic novels, good enough for me.

As a developer, I can use Shift+O -> `renpy.get_game_runtime()` to check my session time, useful when playtesting my own game and measuring the current duration of a certain chapter, or the full game.
