### ISSUE TITLE
Image displaying in wrong order in show statement

### ISSUE THREAD

**Issue by Mondprinzessin** [renpy/renpy#4877]
Hi, 
with the latest RenPy 3 build (and also the latest nightly build) I am facing an issue that some images aren't showing up. 
Investigating this issue with the "image attribute" dev-tool I came to the conclusion that the image is indeed loaded, but not on the topmost layer.

This is the code:
```
define slowdissolve = Dissolve(0.5)
label start:
    show ns 107
    with slowdissolve
    ev "Test 1"
    scene black
    with slowdissolve
    ev "Test 2"
    show ns 108
    with slowdissolve
    ev "Test 3"
    show fix 55
    with slowdissolve
    ev "Test 4"
    show fix 54
    with slowdissolve
    ev "Test 5"
    show ns 114
    with slowdissolve
    ev "Test 6"
    show ns 115
    with slowdissolve
    ev "Test 7"
```
After the last show the image "fix 54" is still shown, but I would expect image "ns 115".

The dev-tool  "image attribute" shows me this output:
```
fix 54
ns 115
black
```

The image files are png format "fix 54.png", "ns 115.png" ...
Already tried deleting rpyc files and forcing recompile.

Is this expected behavior, am I doing something wrong? I never faced this issue before.
Help is very much appreciated :)

**Comment by renpytom** [comment]
This looks like correct behavior to me. Removing everything but scene and show statements, and everything before the last scene statement, we get:

```renpy
    scene black
    show ns 108
    show fix 55
    show fix 54
    show ns 114
    show ns 115
```

When you show something that's already showing, it keeps its place in the order. So black is at the bottom, ns is above it, and fix is on top - and that doesn't change.
