### ISSUE TITLE
High-contrast text is not very readable

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4880]
![image](https://github.com/renpy/renpy/assets/44340603/1cabbd42-fb7f-4622-b404-0ff6d09289ff)
Notice the white pixel artefacts around the letters which make the small font parts harder to read
Still potential deep-fried meme material.

**Comment by mal** [comment]
Feature behaves normally for me (looks completely fine and very readable) using `8.1.2.23072301+nightly` on Ubuntu. Do you have more reproduction info?

**Comment by Gouvernathor** [comment]
It happens on any game I test, but only on the 8.2 nightlies. Maybe related to the emoji-related font changes ?

**Comment by mal** [comment]
Could be related to the premultiplication stuff being touched as part of the emoji work. Worth waiting until that work is considered complete before digging into it IMO.
