### ISSUE TITLE
Labels with `hide` clause can break the game flow

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4881]
Documentation says that _"Adding labels can also confuse the translation process. To prevent this, labels that are given the `hide` clause are ignored when generating translations."_

But the thing is that adding labels can also break the game flow. Let's say there's a choice menu, and at the end of its choices the menu should be shown again. At some point I added "hidden" labels to the choices so I could jump to them, but at the end I get an error: "could not find label 'new_hidden_label_1.fridge'.

```renpy
label start:

    "Let's open the fridge!"

    menu .fridge:

        "Drink":
            label new_hidden_label_1 hide:
            "Tea..."
            jump .fridge

        "Eat":
            label new_hidden_label_2 hide:
            "Salad..."
            jump .fridge
```

I know that there's a simple workaround for this particular example, but is it possible to make labels with `hide` clause more "invisible" for the `jump` statement?

**Comment by Gouvernathor** [comment]
The knowledge of the current global label is not "for the `jump` statement", it also applies to other things, for example if you declare a `.loca` local label in your menu option, under your hide label, it will be called `new_hidden_label_1.loca` and not `start.loca`.
For that reason, we can't simply change `hide` to do what you say from one opdate to another, as it would rename a bunch of innocent local labels. `hide` is a fairly old feature, even though it's not very often used.

Now, we could, maybe, add another keyword to the label statement to do what you say, i.e not change the global label name. Assuming the implementation works (I have no idea), I would rather see `hide` become deprecated in favor of a new keyword that would do both. Maybe `hidden`.

**Comment by mal** [comment]
If I'm understanding what you want correctly, then can't you simply make your new `hide` labels local to achieve this? i.e.
```rpy
label .new_hidden_label_1 hide:
```
That way they don't change the global label, and your jump works as intended. Sure when you use them else where you'd need to prefix them with `start.` but since you're already using full label names, that doesn't seem like it should be an obstacle - it may even make your script more readable as it would also tell you where you could find them.

**Comment by lauwurence** [comment]
Yep, I have considered that solution. But I plan to scatter a lot of such labels around my project, and searching for each root label can be difficult, especially when they can contain 1000+ dialogue lines.

**Comment by renpytom** [comment]
I'd suggest that the right approach is to make the labels local, and then use: 

```renpy
jump start.new_hidden_label_1
```

To jump to them. I don't really see a need for a change in syntax or semantics to support this use case.
