### ISSUE TITLE
Duplicate attributes on displayables now prevent it from showing, lint warning?

### ISSUE THREAD

**Issue by NaughtyRoad** [renpy/renpy#4886]
After upgrading my project from ren'py 7.3.5 to 7.6.1, I discovered that ren'py will now display "image 'x' not found" when that displayable had duplicated attributes, whereas it would display the intended displayable just fine in 7.3.5.

e.g. 
with an image declared as
`image person1 sitoncouch eatapple:`
`    "something"`

this will now not display an image, whereas before it would work just fine
`show person1 eatapple sitoncouch eatapple`

So first off, I think it's absolutely desirable or at least acceptable behavior for ren'py to not display the image with the duplicate attribute. It's just wrong, and the only good solution here is testing. 

But in this case I feel it would be really helpful if lint could help out and warn about those. I'll admit to being a bit biased as I've got a several dozen hours of gameplay implemented already with many, many splitting and converging story branches, and retesting all of those will be it's own special kind of torture. 

So, not a bug as much as a request.

**Comment by Gouvernathor** [comment]
I think this comes from Live2D, where duplicate attributes have a meaning that it doesn't have in normal images. So, and assuming I'm right about that, I don't think we can revert that thing without breaking that Live2D feature, and it's not trivial for Lint to know that a particular show statement (containing a duplicate attribute) leads to a live2D or not, i.e is safe or should be flagged as meaningless.

**Comment by Gouvernathor** [comment]
For example :
```rpy
label a:
    if some_condition:
        show eileen live # eileen live is a Live2D
    else:
        show eileen layer # eileen layer is a layeredimage, for example
    pause
    show eileen happy happy
```
Depending on the preceding if, the last show statement can be either a normal live2D order or meaningless. In that situation, I don't know what Lint could do.

**Comment by NaughtyRoad** [comment]
Cheers, hm, yeah, I appreciate that conundrum. Speaking from my very biased perspective, I'd prefer a false positive over a false negative in this case. :)

I have to admit I'm very, very unaware of lint implementation or best practices, but is there a way to work with directives to suppress or enable warnings, either globally or locally?

I'm aware I'm wheedling here and perhaps the use case I'm presenting is not really common enough to support an effort there.

**Comment by mal** [comment]
Gouv already laid out why this is a bit problematic in the general case, however for your specific case, you could temporarily add a bit of code to flag the issue for yourself, then remove it after you've fixed the problems. It's not ideal, but it'll at least save you having to hunt them all down manually.

```rpy
init python hide:
    def flag_dupes(name):
        if len(name) > len(set(name)):
            # add a bogus attribute to ensure lint finds it
            return name + ('_dupe_lint',)

        return name

    # assumes you're not already using adjust_attributes
    config.adjust_attributes[None] = flag_dupes
```

**Comment by NaughtyRoad** [comment]
Oh wow, I hadn't realized lint would run displayables through adjust_attributes like that. That is beautiful! 

It works a charm, found five of those duplicates in all on a project with ~30k images, or so Lint claims, those would have been a needle in a haystack indeed. Thanks so much for handing me a metal detector.
