### ISSUE TITLE
About the problem of random words after translation

### ISSUE THREAD

**Issue by indescribableQB** [renpy/renpy#4888]
I encountered a problem, using the translation function, in the game after loading the translation language, there is gibberish. I checked the font and the file encoding is all right. Could you tell me what else could have caused this.
![QQ截图20230803102119](https://github.com/renpy/renpy/assets/42056610/35aad8a9-72de-4677-9445-0ef1d452299b)
![QQ截图20230803103335](https://github.com/renpy/renpy/assets/42056610/a55c4dc4-5e51-4f59-9dfd-40f332ec7d8c)
![QQ截图20230803102036](https://github.com/renpy/renpy/assets/42056610/22e2c2a6-645d-43f6-a3e4-622815a67287)

**Comment by Gouvernathor** [comment]
The font you're using doesn't support kanji. I suggest you use the font style property on that translation button specifically, to tell it to use the chinese font, since it's not enabled when your game is in english language mode.

**Comment by renpytom** [comment]
You probably need to set the font for the game itsellf. Something like: 

```renpy
translate schinese python:
     gui.text_font = "simsun.ttc"
     gui.interface_text_font = "simsun.ttc"
```

**Comment by indescribableQB** [comment]
> The font you're using doesn't support kanji. I suggest you use the font style property on that translation button specifically, to tell it to use the chinese font, since it's not enabled when your game is in english language mode.

I use my own sourcehansanlite. TTF, also can not display properly.

**Comment by indescribableQB** [comment]
> ```renpy
> translate schinese python:
>      gui.text_font = "simsun.ttc"
>      gui.interface_text_font = "simsun.ttc"
> ```

I got it. Modified the GUI. RPY file on the TTF code, can be normal display, thank you!
