### ISSUE TITLE
Call screen in a new context

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#4894]
A question often asked is how you can call a screen from another screen, or even more specifically how to call a screen from a `call screen` itself, a.k.a from an interaction.
An interaction within an interaction, that's a Context. So, one way of doing that (because as itself a call screen from a screen is a no-go) is to open a new context to show that screen, and return from that context afterwards.
An existing action does almost that : ShowMenu. The trouble is, it's specifically tailored for calling the game menu, or calling an arbitrary screen "as part of the game menu". It's not just some documentation phrasing or suggestion : the default screen being called, the transition being invoked and the overall implementation are tied to the game menu.

There should be an action to do that, but generalized for any screen and not specific to the game menu. Given the implementation of ShowMenu it doesn't look like it should be very hard to do.

**Comment by mal** [comment]
The very first thing that'll happen is someone will include a `Jump` action in the second screen and accidentally run their entire game in a secondary, unsavable, unrollbackable context.

I can't help but feel that creators finding themselves desiring this are pursuing a bad solution. The `Show` and `Hide` actions exist to manage screens and work within the `call screen` statement to add, remove, and swap screens. It's even possible to leave the first screen in the background by making your new screen modal so it's possible to drop back into it state unchanged.

Ultimately a `call screen` is a `show screen` + await player input, the input is already being awaited, so all that should be needed is to show/hide screens, not try and nest contexts/interactions.

Even across LSF the number of cases that would legitimately need this functionality is miniscule.

**Comment by Gouvernathor** [comment]
What you say about jump also applies to call_in_new_context. Maybe we shouldn't document this upfront as a "call screen in call screen", and maybe it's a very niche use, but I think there are valid use cases, very similar to ones using ShowMenu with a specified arbitrary screen. I do that in a game of mine, not specifically to be called during a call screen, but there is a button part of the quick menu by which you can look at your watch, and that's supposed to be accessible whatever happens on the screen : a dialogue, a menu, an input, a called screen... And yet it's really not a game menu : it has not at all the same look, does not contain links to the save and other menus, and should not receive the same enter and out transitions for instances. So, specialized ShowMenu with no menu.

We have a function to call a label in a new context, and a function to call a function in a new context (which suspiciously looks like the ui. equivalent to what I'm proposing by the way), there should be a function and/or an action to call a screen in a new context.

**Comment by renpytom** [comment]
I think @mal is analyzing this one right - call screen is show screen and waiting. I'll also add that a modal screen with a high zorder is part of this solution, as showing such a screen will prevent the underlying screen from running. I don't see why your watch can't just be a modal screen? 

(To some extent, new contexts are an artifact from the pre-modal screen days.)
