### ISSUE TITLE
Error when running renpy

### ISSUE THREAD

**Issue by boatsky** [renpy/renpy#4897]
I build the latest ```pygame_sdl2``` and ```renpy/module```,
but when I run a, it reports an error and displays this sentence

``
ValueError: renpy.text.textsupport.Glyph size changed, may indicate binary incompatibility. Expected 88 from C header, got 72 from PyObject
ValueError: renpy.text.textsupport.Glyph size changed, may indicate binary incompatibility. Expected 88 from C header, got 72 from PyObject
``

**Comment by renpytom** [comment]
Delete module/gen3/renpy.text.* and module/gen/renpy.text.* , and you'll get going. 

Please leave this open, as this really needs to be done automatically.

**Comment by boatsky** [comment]
> 删除 module/gen3/renpy.text.* 和 module/gen/renpy.text.* ，你就可以开始了。
> 
> 请保持打开状态，因为这确实需要自动完成。

It has been resolved and I will keep the issue open.

**Comment by renpytom** [comment]
This was fixed a little while ago, so I'm closing this issue.
