### ISSUE TITLE
'renpy.movie_cutscene' freezes the game on Android.

### ISSUE THREAD

**Issue by ChrisTheGrizz** [renpy/renpy#4898]
For starters, the game was originally being developed in RenPy 7.3.5, updated to 7.5.2 at some point in the past few years _(had its own share of bugs caused by the update that were promptly fixed)_.
And recently the developer updated the SDK to RenPy 8.1.1.

The largest, and currently unfixable problem found was that the game completely freezes on Android whenever a video is played using `$ renpy.movie_cutscene()`.
Music remains playing but the visuals freeze right before the video is played and nothing can be interacted with.

Other forms of video playback, like defining them as images with `image videoName = Movie(play="videoPath")` work fine.
Haven't found a way to make `movie_cutscene` work, nor of an alternative way to display videos that play only once.

---

The video files are all VP8 in a webm container with no audio track.
Have tried various other formats and containers _(VP9, MPEG, H.264)_, even tried adding a silent track to them with ffmpeg.
But nothing worked so far. 

The only solution found is to have the player use a file manager to go into the game's private folder (`Android/data/com.domain.package/files`), to then create a folder called `game` and have them put the video files in there like they would be on PC _(folder structure and everything)_.

Doing so, makes the game load the cutscenes as they should which works as a temporary fix for the problem, but as expected it is very inconvenient for the end user, specially for ones on Android 11+ where you need specific file managers to access the app's private folder.

It is rather odd that the game refuses to load those videos unless they're manually added to the private folder location.
I tried extracting the files from inside the APK and the video files are the exact same as the ones in the SDK. _(minus the 'x-' in the filename)_

Open to suggestions on how to "replace" the `movie_cutscene()` functionality.

 ---
 
 ## ADDENDUM
 
 I also observed the behaviour described in [this issue](https://github.com/renpy/renpy/issues/4329). 
 Where video files played with `movie_cutscene()` are being stretched to match the aspect ratio of the device's screen.
 
 In my case, the videos are **16:9** but on my phone the cutscene videos are stretched horizontally to fit **20:9**.
 
 Relatively minor issue, but thought it was worth mentioning.

**Comment by renpytom** [comment]
This seems to be working (on the nightly build of Ren'Py), using a clean game that just uses renpy.movie_cutscene. 

My guess is that for some reason, you might be using config.hw_video, or that could have been set to True by compatibility. This has been removed in the nightlies, and wasn't useful before then. Please try: 

```renpy
define config.hw_video = False
```

**Comment by ChrisTheGrizz** [comment]
Huh, the one thing I didn't think of trying.
Considering how docs and forums posts talk about `hw_video` I assumed it would've been set to False by default, apparently it wasn't.
And as far as I can tell, no line in the code was explicitly setting it to True.

---

But yes, setting it to False fixes the problem of playback freezing on **8.1.1.23060707**.
It also fixes the other issue I mentioned about the video being stretched to fit the screen's aspect ratio.

Thanks for your help.
