### ISSUE TITLE
Add action Continue()

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#4901]
I was thinking that renpy could natively have a resume button where it was last left off, for example. If the player saved a game manually, or if it was saved automatically the game would allow to show in the main menu a continue button.

an example would be:
```
screen navigation ():

    vbox:
        style_prefix "navigation"

        xpos gui.navigation_xpos
        yalign 0.5

        spacing gui.navigation_spacing

       if renpy.can_continue():
             textbutton _ ("continue") action Continue()

        if main_menu:

            textbutton _ ("Start Game") action Jump ("restart")

        else:

           textbutton _ ("History") action ShowMenu ("history")

           textbutton _ ("Save") action ShowMenu ("save")

        
        textbutton _ ("Load game") action ShowMenu ("load")

        textbutton _ ("Options") action ShowMenu ("preferences")
```
Examples: 

Action Continue(save="auto")
   save: determines where the last save will be loaded from. by default it will take the automatic game saves (although it can take the manual saves, I thought it would be better to take the automatic ones).

renpy.can_continue() Check if there are saves that can be continued.

**Comment by m-from-space** [comment]
Not sure this is really necessary, the only thing you have to do right now is something like this:

```
$ newest_game = renpy.newest_slot(regexp='\d|quick')
if newest_game:
    textbutton _("Continue") action FileLoad(newest_game, newest=False, slot=True)
```
