### ISSUE TITLE
transform doesn't work with volatile variables anymore

### ISSUE THREAD

**Issue by HRelease** [renpy/renpy#4903]
I don't know if it's intentional, but 

```
transform rot_param_transform(rot, rot_function, t_mark):
    parallel:
        block:
            rotate Roulette.BallTmpRot[0]
            linear Roulette.BallTmpRot[2] rotate Roulette.BallTmpRot[1]
            repeat
    parallel:
        block:
            function rot_function
            repeat
```

rot_function changes Roulette.BallTmpRot, but the game use only the first value. If I restart the screen it uses the first new value

I tested on 7.6.1 and 8.1.1
In my previous renpy (I think it was 7.1) version it worked

**Comment by Gouvernathor** [comment]
How do you first define Roulette.BallTmpRot ? using default, define or something else ?

**Comment by HRelease** [comment]
Thanks, your link helped. I changed the approach and put the transformation inside the function. Everything works fine now

**Comment by Gouvernathor** [comment]
Yes, and the mention of the ui functions is outdated. I'll clean that up.
