### ISSUE TITLE
Building project is difficult in mostly non graphical environment

### ISSUE THREAD

**Issue by Yarn** [renpy/renpy#4907]
As far as I can tell the only way to build a project is through the launcher gui. It's not very clear how to work with your project in the launcher, it just shows the two default projects and an option to create a new project. The results when trying to google the problem indicate confusion about the intended usage in common.

Using the preferences in the gui to change the projects directory allows entering a file path on the command line, I entered `..` which did allow it to find the project but the path appears to be 0 width in the gui and is thus no longer clickable so the path can't be changed again.

Any documentation I could find about it indicates the settings are stored in ~/.renpy but deleting this directory doesn't reset the settings so it's still not editable.

After doing a web build the docs indicate there should be a web.zip file but I don't see that file. There does appear to be a web folder that was created.

**Comment by renpytom** [comment]
I'm confused by what you're asking here. The  GUI environment is the supported way of building projects. Are you having trouble with the GUI?

**Comment by Yarn** [comment]
Sorry this is kinda a jumble of things that all contributed to a specific workflow being difficult.

### There seems to be ~~one~~ actual bug.
When projects directory is set to `..` it seems to just not be interactable and can't be changed again.

While writing this ticket I realized creating a new project also seems to be broken, I'm not sure if this is a result of having the projects directory set to `..` and I can't change it to check.
```
FileNotFoundError: [Errno 2] No such file or directory: '../test/game/../test/game/script.rpy'
```

### A few documentation/UX complaints

The intended way to get your project to show up in the UI isn't very clear. Adding a button to change the directory it searches in on the main page next to the header or under create project would be a lot more discoverable.

It's not clear where settings for the launcher are stored so I can't delete them to work around the bug above.

It's not immediately clear where the output of the build went. I found the -dist folder in `..` after writing the previous message. A note in the docs or the success message for the build could make this easier.

If you aren't looking at the terminal that renpy was launched from (or didn't launch it from a terminal) there isn't any feedback that file selection is occurring. It just has a prompt for text entry in the terminal. I have no graphical file selection options installed in this environment.

### A feature request

It would be nice to be able to set the projects directory as a command line flag, it would allow tab completion, scripting and environment variables to be used and, for the rare primarily command line user, work around most of the issues mentioned above (if the help string mentioned that it was the location that builds are placed as well, all of the issues mentioned above).

**Comment by renpytom** [comment]
How did you change the projects directory to .. ? 

There already is an undocumented command line to change the projects directory: 

./renpy.sh launcher set_projects_directory /path/to/projects 

(or renpy.exe on windows.) 

Also, what OS are you using? There shouldn't be command line path entry unless you have a massively misconfigured OS.

**Comment by Yarn** [comment]
I click on the directory in projects directory, there is a prompt in the terminal

```
missing software! (we will try basic console input)

 ___________
/           \
| tiny file |
|  dialogs  |
\_____  ____/
      \|
tiny file dialogs on UNIX needs:
   applescript or kdialog or yad or Xdialog
or zenity (or matedialog or shellementary or qarma)
or python (2 or 3) + tkinter + python-dbus (optional)
or dialog (opens console if needed)
or xterm + bash (opens console for basic input)
or existing console for basic input

press enter to continue



Select Projects Directory

Select folder from <path>
(esc+enter to cancel): ..
```

it's an arch linux container, there isn't a graphical file chooser available

**Comment by renpytom** [comment]
Ah, you'll have to fix that, then.
