### ISSUE TITLE
Trouble with Bengali Translation

### ISSUE THREAD

**Issue by stranger54321** [renpy/renpy#4908]
Hello! The highlighted translated words in the script
appear to be correct, but on the game screen, they're
not displaying accurately. I've even tried different fonts,
but the problem persists. Any suggestions on how I can
resolve this?
I've been also tried different fonts
![Screenshot 2023-08-12 191845](https://github.com/renpy/renpy/assets/71636301/1b4dfa19-7c2f-43e1-815a-7345281565a7)

**Comment by renpytom** [comment]
Can you try the nightly build (not nightly fix, the full nightly build), from https://nightly.renpy.org ? There were recent changes to improve support for Indic text shaping, and I want to see if those worked.

**Comment by stranger54321** [comment]
> Can you try the nightly build (not nightly fix, the full nightly build), from https://nightly.renpy.org ? There were recent changes to improve support for Indic text shaping, and I want to see if those worked.

Same. Nothing has changed. I've also tried it with a similar language (Hindi), and the Hindi language displayed correctly.

**Comment by renpytom** [comment]
Okay. Can you  please copy some of the text you need to display into this issue, and also point me to the font you're using?

**Comment by stranger54321** [comment]
Sure
"অধ্যাপক আইলিনের বক্‌তৃতাগুলি সাধারণত আকর্ষণীয়, তবে আজ আমি কেবল এটিতে মনোনিবেশ করতে পারিনি।"

font list :
Bengali-Regular.ttf
Noto Sans Bengali Regular.ttf
kalpurush.ttf

Noto Serif Bengali Varible & static all fonts

**Comment by stranger54321** [comment]
> Okay. Can you please copy some of the text you need to display into this issue, and also point me to the font you're using?

Sure
"অধ্যাপক আইলিনের বক্‌তৃতাগুলি সাধারণত আকর্ষণীয়, তবে আজ আমি কেবল এটিতে মনোনিবেশ করতে পারিনি।"

font list :
Bengali-Regular.ttf
Noto Sans Bengali Regular.ttf
kalpurush.ttf

Noto Serif Bengali Varible & static all fonts

**Comment by renpytom** [comment]
Here's the line you gave rendered with the current build of Ren'Py 8.2. 

![image](https://github.com/renpy/renpy/assets/379804/1a7c898a-dd13-4353-8278-d1b77e3ee7c7)

It seems to match how my web browser renders the text you gave - do you see any issue. (I should have mentioned that these changes are going into Ren'Py 8 only.)

**Comment by stranger54321** [comment]
> Here's the line you gave rendered with the current build of Ren'Py 8.2.
> 
> ![image](https://user-images.githubusercontent.com/379804/260334280-1a7c898a-dd13-4353-8278-d1b77e3ee7c7.png)
> 
> It seems to match how my web browser renders the text you gave - do you see any issue. (I should have mentioned that these changes are going into Ren'Py 8 only.)

It seems correct

**Comment by renpytom** [comment]
Question - when you tested, did you use an 8.2 nightly? Or 7.7?

**Comment by stranger54321** [comment]
> Question - when you tested, did you use an 8.2 nightly? Or 7.7?

![Uploading SmartSelect_20230813_194619_Chrome.jpg…]()

**Comment by stranger54321** [comment]
> Question - when you tested, did you use an 8.2 nightly? Or 7.7?

![SmartSelect_20230813_194619_Chrome](https://github.com/renpy/renpy/assets/71636301/d32ca350-5400-43b5-9106-1a2697240f97)

**Comment by renpytom** [comment]
I'm not sure what the issue is. Can you try a new project? I just tried the Linux and Windows versions of 8.2.0.23081301+nightly, and it seemed to render the text correctly.

**Comment by stranger54321** [comment]
![Screenshot 2023-08-13 195647](https://github.com/renpy/renpy/assets/71636301/b0a74053-fedb-4ce1-b09d-cefc54ba11be)
Sadly nothing seems different 😕

**Comment by renpytom** [comment]
Can you post that project so I can test it here?

**Comment by stranger54321** [comment]
> Can you post that project so I can test it here?

[Translated project link](https://mega.nz/folder/JGsS2ZLB#PfG84tEN_f-AzWyinM-nzw) 

I'm used a live translation tool which work online to translate . Added that tool file with project file .  Also tried Ren'Py translation both throwing same issue. 


Translated languages save location "game\_Paloslios_ZLZK\mtl"

**Comment by renpytom** [comment]
I wasn't able to get the files you had working. Can you please create a new project containing just the Bengali text and font, make sure it doesn't work, and post that? I don't want to have to deal with an entire custom translation framework to debug a text rendering issue.

**Comment by stranger54321** [comment]
Okay done again a test with my current sdk (8.0.2) & latest  nightly build you pointed me. It seems problem old sdk . With nightly build bengali texts rendering perfectly with & without live translator tool.
[https://mega.nz/folder/JGsS2ZLB#PfG84tEN_f-AzWyinM-nzw](here)  is both builds.


Could you please provide me a patch that I can apply on my previous  8.0.0 + sdks

**Comment by renpytom** [comment]
No, sorry - the changes are too intrusive with older versions.

**Comment by stranger54321** [comment]
So when will we get latest stable release !? I really don't want to work with nightly version for my project

**Comment by Gouvernathor** [comment]
It will take the time it needs to be stable enough for a Release, which is the case every time but especially in this case since it's a big change of the internals which may generate a lot of nifty hidden bugs.
You should not distribute games built from a Nightly but you can very well develop them on it. If your reluctance to use Nightlies is that they can be buggy and unstable, well the font reform in itself *is* unstable and probably buggy, and the bugsweep and review process is the way by which we're able to correct that.
