### ISSUE TITLE
The project directory is not changeable on Linux

### ISSUE THREAD

**Issue by AXWTV** [renpy/renpy#4910]
I went into preferences>general and clicked on the Project directory, and I always get "Ren'py has set the project directory to: "
![image](https://github.com/renpy/renpy/assets/88997488/7fcdad99-f783-4430-bd83-1ccccea21b52)

I also tried the nightly version, and I get the same prompt.

**Comment by AXWTV** [comment]
I am on Fedora Linux btw.

**Comment by renpytom** [comment]
Weird. It should be creating a dialogue if you have zenity, kdialog, or python2/3+tikinter present.
