### ISSUE TITLE
renpy.notify is not picked up by self-voicing, and interrupts self-voicing

### ISSUE THREAD

**Issue by JenivereSH** [renpy/renpy#4912]
I've had a couple of issues with renpy.notify. 

First, which has been resolved for now, I'm including here in case it might have any effect on the problem behavious. The default notify screen was not picking up the defined character names, which has been resolved by altering screens.rpy for notify so it is now:

```
screen notify(message):

    zorder 100
    style_prefix "notify"

    frame at notify_appear:
        text message

    timer 3.25 action Hide('notify')
```
    
However, neither the default version nor this one are being read by self-voicing. Currently with this version, notify is interrupting self-voicing. It is reading half a line of dialogue then returning to the beginning of the dialogue and reading the entire thing. I was going to use a section of alt to read something for the notify, but that won't be a working solution if notify is still interrupting the behaviour of self-voicing with the dialogue.

**Comment by renpytom** [comment]
This is fixed by 936363d243a9c8987850e07227146446b39e1262 .
