### ISSUE TITLE
[Feature Request?] Presplash Image Transparency

### ISSUE THREAD

**Issue by WindChimesGames** [renpy/renpy#4913]
Hi! 

Is it possible for the presplash.png image to have transparency rather than be fully opaque? I noticed that the documentation mentioned that presplash_foreground.png can have transparency, but presplash_background.png must be fully opaque, and it looks like that's the case for presplash.png as well, as my current presplash.png has a transparent background but it shows up as black background instead when the game is loading.

I'm not sure if there's limitations to making the presplash image work with full transparency and if it'd be complicated to add that, but it'd be wonderful if it could be done! I understand it's a small not-exactly-important thing though so it might not be looked into.

Thank you so much regardless!

**Comment by renpytom** [comment]
I don't think this is likely to happen. The presplash is meant to be a small thing that's shown while waiting for Ren'Py to load, and so I don't want to invest a ton into it - especially to accomplish weird results, like non-rectangular windows.
