### ISSUE TITLE
Can't run a Renpy based game on Windows XP

### ISSUE THREAD

**Issue by Caas111** [renpy/renpy#492]
Hello. I can't runa Renpy created game on my system. I know that other ppl tried it and the game works for them. When i try to run it the game just open the window and freezes. The log looks like that:

Wed Nov 12 23:58:19 2014
Windows-XP-5.1.2600-SP3
Ren'Py 6.15.1.275
A Ren'Py Game 0.0

Couldn't import angle renderer:
Traceback (most recent call last):
  File "F:\Ryanshow World of Vore-1.3.1-win\Ryanshow World of Vore-1.3.1-win\renpy\display\core.py", line 1279, in make_draw
    __import__(mod)
ImportError: DLL load failed: Nie mo¿na odnaleæ okrelonego modu³u.
Unknown renderer: angle

Windowed mode.
Screen sizes: virtual=(800, 600) physical=(800, 600)
Vendor: 'Intel'
Renderer: 'Intel 965/963 Graphics Media Accelerator'
Version: '2.0.0 - Build 7.15.10.5218'
Display Info: <VideoInfo(hw = 0, wm = 1,video_mem = 0
	     blit_hw = 0, blit_hw_CC = 0, blit_hw_A = 0,
	     blit_sw = 0, blit_sw_CC = 0, blit_sw_A = 0,
	     bitsize  = 32, bytesize = 4,
	     masks =  (16711680, 65280, 255, 0),
	     shifts = (16, 8, 0, 0),
	     losses =  (0, 0, 0, 8),
	     current_w = 1440, current_h = 900
>

Extensions:
    
    GL_3DFX_texture_compression_FXT1
    GL_ARB_depth_texture
    GL_ARB_draw_buffers
    GL_ARB_fragment_program
    GL_ARB_fragment_shader
    GL_ARB_multitexture
    GL_ARB_occlusion_query
    GL_ARB_pixel_buffer_object
    GL_ARB_point_parameters
    GL_ARB_point_sprite
    GL_ARB_shader_objects
    GL_ARB_shading_language_100
    GL_ARB_shadow
    GL_ARB_texture_border_clamp
    GL_ARB_texture_compression
    GL_ARB_texture_cube_map
    GL_ARB_texture_env_add
    GL_ARB_texture_env_combine
    GL_ARB_texture_env_crossbar
    GL_ARB_texture_env_dot3
    GL_ARB_texture_non_power_of_two
    GL_ARB_texture_rectangle
    GL_ARB_transpose_matrix
    GL_ARB_vertex_buffer_object
    GL_ARB_vertex_program
    GL_ARB_vertex_shader
    GL_ARB_window_pos
    GL_ATI_separate_stencil
    GL_EXT_abgr
    GL_EXT_bgra
    GL_EXT_blend_color
    GL_EXT_blend_equation_separate
    GL_EXT_blend_func_separate
    GL_EXT_blend_minmax
    GL_EXT_blend_subtract
    GL_EXT_clip_volume_hint
    GL_EXT_compiled_vertex_array
    GL_EXT_draw_range_elements
    GL_EXT_fog_coord
    GL_EXT_framebuffer_object
    GL_EXT_multi_draw_arrays
    GL_EXT_packed_pixels
    GL_EXT_rescale_normal
    GL_EXT_secondary_color
    GL_EXT_separate_specular_color
    GL_EXT_shadow_funcs
    GL_EXT_stencil_two_side
    GL_EXT_stencil_wrap
    GL_EXT_texture3D
    GL_EXT_texture_compression_s3tc
    GL_EXT_texture_env_add
    GL_EXT_texture_env_combine
    GL_EXT_texture_filter_anisotropic
    GL_EXT_texture_lod_bias
    GL_EXT_texture_rectangle
    GL_IBM_texture_mirrored_repeat
    GL_NV_blend_square
    GL_NV_texgen_reflection
    GL_SGIS_generate_mipmap
    GL_SGIS_texture_edge_clamp
    GL_SGIS_texture_lod
    GL_WIN_swap_hint
Number of texture units: 8
Using shader environment.
Using copy RTT.
Using gl renderer.
Texture testing:
- Hardware max texture size: 2048
- 64px textures work.
- 128px textures work.
- 256px textures work.

**Comment by renpytom** [comment]
I don't think this is a Ren'Py problem -  I'd suggest upgrading your video drivers.
