### ISSUE TITLE
Add Interactive choice features (buttongroup)

### ISSUE THREAD

**Issue by Wendy-Nam** [renpy/renpy#4932]
Hello,

I propose enhancing the Ren'Py framework by introducing `button groups` and `multi-choice capabilities` to foster interactive game development.

### Context:
While using Ren'Py, I encountered scenarios where multiple choices on one screen were essential. However, the current `menu` syntax only supports one choice per screen, limiting complex decision-making.
<img width="292" alt="스크린샷 2023-08-24 오후 8 24 17" src="https://github.com/renpy/renpy/assets/142412339/8fc0d52f-8798-4bd1-9480-ea411b319cf4">

### Features:

`Multi-Choice Screens`: Enable multiple choices on a single screen, enhancing decision dynamics and gameplay.

`Grouped Selections`: Allow selection of one or more items from divided layouts using image/text button groups.

### Solution:
I've developed a plugin for image and text button groups, enabling seamless selections without screen transitions.

🔗 Plugin: [GitHub Link](https://github.com/Wendy-Nam/RenPy-RadioButtonGroup)

By integrating these features into Ren'Py, we simplify interactive game design and ensure compatibility with modern industry trends, including combat systems.

I'm keen on contributing to the integration of these features directly into the Ren'Py framework. If you would kindly consider allowing me to collaborate on this development, I would greatly appreciate the opportunity.

Best regards,
Wendy Nam

**Comment by qTich** [comment]
Menus can take a screen parameter, which in turn can be responsible for customizing what the buttons will do - [doc](https://www.renpy.org/doc/html/menus.html#menu-arguments)

**Comment by Wendy-Nam** [comment]
I sincerely appreciate your guidance.

By using the screen transfer to my menu, I have successfully resolved the issue related to the 'Image Button Group' on the second screen.

Is there a feature within the Ren'Py framework itself that allows for 'multiple groups of choices' on a single screen?

As shown in the upper part of the attached screen, I need to enable users to select choices from various groups, such as gender and race, all on one screen, before transitioning to the next. Currently, I have implemented this functionality using the plugin I created. However, if there is an approach within Ren'Py itself, I would prefer to make the adjustments accordingly. Your insights on this matter would be highly valuable.

Thank you for your consideration.

**Comment by renpytom** [comment]
Correct, this is exactly why screen language exists. 

Multiple groups of choices is done by SetVariable. If you were to have: 

```renpy
default mascot = "Eileen"

vbox:
     label "Select a mascot." 
     textbutton "Eileen" action SetVariable("mascot", "Eileen")
     textbutton "Lucy" action SetVariable("mascot", "Lucy")
     textbutton "Shiro" action SetVariable("mascot", "Shiro")
```

Since the mascot variable can only take on one value, the choices are by necessity alternatives.
