### ISSUE TITLE
SystemError: unknown opcode

### ISSUE THREAD

**Issue by Org-gith** [renpy/renpy#4933]
I ran into this issue today, everything was working normally, reloaded the script multiple times prior to it without problems, but this time when reloading something broke and the traceback was:
![xx1](https://github.com/renpy/renpy/assets/78823063/6136ffd3-f2b1-4c33-af41-d3f1b83c96c5)

Restarting the SDK didn't fix it, I had to re-download the SDK and make a new install to make it work again. 
I had another problem like this last week during a reload, where something broke, and had to delete a .rpyc to make it work again but I don't remember the traceback. It was an easy fix compared to that one.
I'm not sure if the problem is hardware-related because I changed my whole system to AMD Ryzen last month, and it was at about the same time when I started to use Renpy 8.1 and 7.6 intensively and ran into issues I have never encountered with the SDK in the past 4 years with my previous system.

**Comment by renpytom** [comment]
I can't think of anything that would cause this other than a corrupt file. I'm not sure what to say here - check your ram and storage, I guess.

**Comment by Org-gith** [comment]
If this error means nothing, then it has to be hardware problem, thank you for the confirmation and pff, sorry for the trouble.
Why I get weird issue like this... I'll try to enforce higher voltage than default on the ram and set manual timing to increase stability, seems like I could have gotten a bad kit and I also just read online that amd platform is very sensitive to memory timing in general.

**Comment by renpytom** [comment]
For the record, what it means is that the compiled Python contains a byte the Python interpreter doesn't expect.
