### ISSUE TITLE
UploadSync results in 413: Request Entity Too Large

### ISSUE THREAD

**Issue by PhanesDionysos** [renpy/renpy#4938]
When trying out Ren'Py Sync on my in-progress game, triggering the UploadSync action displays a confirmation dialog, as expected, but when I click "Yes," the game hangs for around ten seconds before displaying an nginx server error (413).

It looks like the code tries to keep the total payload size below a limit by excluding files, but if it helps with diagnosis: my `persistent` file is 342 KB and my saves are between 140 and 267 KB each. The total size of my save directory, excluding `auto`, `_`, and the like, is 11.6 MB (not zipped).

I'm happy to provide my game hash in private if it would be useful.

**Comment by qTich** [comment]
> When trying out Ren'Py Sync on my in-progress game, triggering the UploadSync action displays a confirmation dialog, as expected, but when I click "Yes," the game hangs for around ten seconds before displaying an nginx server error (413).
> 
> It looks like the code tries to keep the total payload size below a limit by excluding files, but if it helps with diagnosis: my `persistent` file is 342 KB and my saves are between 140 and 267 KB each. The total size of my save directory, excluding `auto`, `_`, and the like, is 11.6 MB (not zipped).
> 
> I'm happy to provide my game hash in private if it would be useful.

The limit on total file size is 10MB.
Although, I think the server sometimes limits uploads.

**Comment by renpytom** [comment]
Can you try it now? I've made a change on the server-side. If you're still getting errors, send your game to  pytom@bishoujo.us. (If you're using google drive, please add renpytom as the user.)

**Comment by PhanesDionysos** [comment]
> Can you try it now? I've made a change on the server-side.

That seemed to resolve the issue! Thank you. Is there anything developers should be doing to limit the total payload size?

**Comment by renpytom** [comment]
No, other than keeping your save files as small as practical.
