### ISSUE TITLE
Main Menu Video Background

### ISSUE THREAD

**Issue by andrewngn13** [renpy/renpy#494]
I added a video to my main screen as a background, but when using "X" to exit, the menu will disappear. Clicking "X" again will exit ren'py. I have found that if you don't double click, but click "X" once and then right click, you can make the menu reappear.

I found out how to put in the video using this thread, where the issue was mentioned.
http://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=23365

**Comment by renpytom** [comment]
Sorry about the delay in getting back, I mostly use the bug tracker for development.

I believe this could be fixed by adding to the yesno_prompt screen either:

```
    add Movie() # To display the movie
```

or 

```
    on "show" action Stop("movie")
````

to stop it from playing.
