### ISSUE TITLE
GamepadExists() ignores config.developer

### ISSUE THREAD

**Issue by micka190** [renpy/renpy#4940]
[`GamepadExists()`'s documentation states the following:](https://www.renpy.org/doc/html/screen_actions.html#GamepadExists)

> `GamepadExists(developer=True)`
> A function that returns true if a gamepad is present, and false otherwise.
>
> **developer**
>       Forces this function to always return true while [config.developer](https://www.renpy.org/doc/html/config.html#var-config.developer) is true.

I was trying to test the help screen on a project, and couldn't get the Gamepad button to appear, even with `define config.developer = True`. It seems like this check was removed from Ren'Py.

Currently, [`GamepadExists()`'s definition](https://github.com/renpy/renpy/blob/18d3f48686381c0617774ffc509ea2687bf97723/renpy/common/00gamepad.rpy#L249) seems to simply be a call to `renpy.display.controller.exists()`.

[`renpy.display.controller.exists()`](https://github.com/renpy/renpy/blob/18d3f48686381c0617774ffc509ea2687bf97723/renpy/display/controller.py#L125) doesn't seem to check if `config.developer` is enabled or not.

Unless I'm missing something with how `config.developer` works internally, shouldn't one of these be checking to see if `config.developer` is enabled?

**Comment by Elckarow** [comment]
recent fix completely disregards the `developer` parameter
```
if developer and config.developer:
    return True
```
does what's intended

**Comment by renpytom** [comment]
What I get for coding while tired.

**Comment by Elckarow** [comment]
can be closed now, btw
