### ISSUE TITLE
Bytecoded Hinted vs Autohinted Text

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#4941]
I may be wrong or the issue may be on my side because I recently reinstalled my system, but I see a huge difference between the old Ren'Py version and the latest. Text now looks more blurry and spaces between characters seem to have decreased.

<details>
  <summary>In the Launcher</summary>

Old Ren'Py:
![image](https://github.com/renpy/renpy/assets/46109734/1d8c649c-7ce9-421e-87a7-4d050f2df3f1)
Latest Ren'Py:
![image](https://github.com/renpy/renpy/assets/46109734/f09e3c06-cd96-4a98-b145-fb9cc36086a0)
</details>

<details>
  <summary>In Game</summary>

Old Ren'Py:
![image](https://github.com/renpy/renpy/assets/46109734/f6278635-16c1-45ce-95ae-5f71c10664b9)
Latest Ren'Py:
![image](https://github.com/renpy/renpy/assets/46109734/218f25d3-6b8d-4c2f-9139-65fbae3c8ec4)
</details>

Ren'Py 8.2.0.23082803+nightly
Win 11

**Comment by renpytom** [comment]
Can you try: 

```renpy
style default:
     shaper "freetype"
     hinting True
```

And see what you think about the changes. Fundamentally, the new changes aim to respect the hinting and placement information in the font, over the autohinting used by previous versions of Ren'Py. IMO, the letter placement is much more pleasing in the new version. (I do agree there's more aliasing, but I need to figure out if that's just the way Roboto renders with proper hints.)

**Comment by renpytom** [comment]
Here's how a test program on Linux renders the first three languages in the launcher. I think this is closer to your second set of screenshots.

![image](https://github.com/renpy/renpy/assets/379804/7eb502b3-3162-4364-93f4-ed6f942671f1)

**Comment by lauwurence** [comment]
I just did some research and I believe there is no good or bad characters placement, it's a matter of taste and the method used.
In my case, the small letters are now placed noticeably closer to each other so they almost blend. Adding `kerning 1` fixes that but it adds pixels, and it's too much for small texts. I wish there was something different that behaves like "tracking" in Photoshop.

I also checked how Blender Devs handled their text rendering:
<details>
  <summary>Blender Screenshots</summary>

Hinting is off. Looks close to the new Ren'Py:
![image](https://github.com/renpy/renpy/assets/46109734/41b0882e-0bc4-411d-a5d5-fa851bdc7c8e)

Full hinting. Closer to the old Ren'Py:
![image](https://github.com/renpy/renpy/assets/46109734/a862cc96-048f-4136-8674-59028592b997)

Slight hinting. Maybe something that should be added to Ren'Py? 
![image](https://github.com/renpy/renpy/assets/46109734/6f621360-d658-445e-828a-5822807e458b)

</details>

I think that hinting should be added as an optional button in the Launcher. My eyes hurt when I work with blurry text...

**Comment by renpytom** [comment]
I'll note that in both cases, the text is being hinted - one using bytecode hinting, and the other by the autohinter.

**Comment by Org-gith** [comment]
I think the text was overly sharpened in the past too, which can look nice in some fonts and not so good in some others.
For example in a project I was on recently, I added the minimum value of blur to a text because the base result was too pixelated (sharpened) imo. This can be a bit distracting since sometimes you want your next to not stand out too much, and blend with the image.
Default:
![xx2](https://github.com/renpy/renpy/assets/78823063/c97bbb67-e18a-4bf0-9b3c-30213d438835)
Blurred it blend better:
![xx1](https://github.com/renpy/renpy/assets/78823063/220426c1-7157-4111-a9e8-94554a113ee8)

I wasn't super happy either with the slightly blurred text, but still preferred it over the sharpened one. At any rate, maybe the ability to pick between the two would be the best if it's possible because I can see a world where you would prefer one or the other but it would depend on each individual font's properties.

**Comment by renpytom** [comment]
A recent series of changes backs out some of this, in favor of using harfbuzz and freetype to produce better autohints.

**Comment by lauwurence** [comment]
Awesome! I like the new changes, it removed strange spaces between characters so small text now looks more consistent, but there's one little thing I noticed. "f" and "i" are now connected at the top so the dot is not visible:

![image](https://github.com/renpy/renpy/assets/46109734/a47869af-2026-4071-bc52-3940e98b8d60)
![image](https://github.com/renpy/renpy/assets/46109734/12f8faf6-db83-4979-b256-9f826b91d37f)

Probably, not a big issue. Just seemed strange to me.

**Comment by Gouvernathor** [comment]
Discussed in #4952, that's something which is intended by the font creators and which renpy didn't respect until now.

**Comment by lauwurence** [comment]
I see. Than it's just that the DejaVu Sans font used by Ren'Py is being different from the latest DejaVu Sans from here https://dejavu-fonts.github.io/

![image](https://github.com/renpy/renpy/assets/46109734/232ef800-7c21-458a-93a4-88534952d79c)

**Comment by lauwurence** [comment]
Roboto? I thought it was some sort of modified Deja Vu. Now everything makes sense.
At this point, I have nothing to complain about.

**Comment by renpytom** [comment]
Closing, since I think this has run its course.
