### ISSUE TITLE
Build archive and classify unintended behaviour

### ISSUE THREAD

**Issue by graterleg1990** [renpy/renpy#4944]
Hi,

I am trying to structure my game in chapters, I am trying to build 2 distributions based on below code.
Expectation: The output zip must **not contain** 'images/cp1/' or 'images/cp2' folder and cp1 and cp2 rpa files are created.
Actual : The output zip  **contains** 'images/cp1/' or 'images/cp2' folder and cp1 and cp2 rpa files are created.
Can anyone let me know if the usage is wrong or the behavior?

>     $build.archive("cp1", "cp1")
>     $build.classify("game/images/cp1/**", "cp1")
>     $build.classify("game/movies/cp1/**", "cp1")
> 
>     $build.archive("cp2", "cp2")
>     $build.classify("game/images/cp2/**", "cp2")
>     $build.classify("game/movies/cp2/**", "cp2")
>     $build.package("all-chapters", "bare-zip", "windows linux mac renpy all cp1 cp2", "All The Chapters for Market")
>     $build.package("demo-chapters", "bare-zip", "windows linux mac renpy all cp1", "Chapters All but 1 for Market")

**Comment by Gouvernathor** [comment]
Those need to be in an init python, otherwise the build process will not execute them. Dollar-lines outside of a label are unreachable (obviously), and labels are not called in the build process.

**Comment by renpytom** [comment]
There's also the issue that having the archive list and the file list the archive goes into be the same isn't going to work. Something like: 

[code]

Hi,

I am trying to structure my game in chapters, I am trying to build 2 distributions based on below code.
Expectation: The output zip must not contain 'images/cp1/' or 'images/cp2' folder and cp1 and cp2 rpa files are created.
Actual : The output zip contains 'images/cp1/' or 'images/cp2' folder and cp1 and cp2 rpa files are created.
Can anyone let me know if the usage is wrong or the behavior?

```renpy
init python:

    build.archive("cp1_archive", "cp1")
    build.classify("game/images/cp1/**", "cp1_archive")
    build.classify("game/movies/cp1/**", "cp1_archive")

    build.archive("cp2_archive", "cp2")
    build.classify("game/images/cp2/**", "cp2_archive")
    build.classify("game/movies/cp2/**", "cp2_archive")

    build.package("all-chapters", "bare-zip", "windows linux mac renpy all cp1 cp2", "All The Chapters for Market")
    build.package("demo-chapters", "bare-zip", "windows linux mac renpy all cp1", "Chapters All but 1 for Market")
```
Is probably close to what you want.

**Comment by graterleg1990** [comment]
Works perfectly, thanks a lot for the support :)
