### ISSUE TITLE
Android package invalid problem please help thank you

### ISSUE THREAD

**Issue by Githubfrienduser** [renpy/renpy#4947]
First, I installed JDK and SDK 8.0, and I successfully completed the steps for generating keys and configuring them. Then, I was able to build the package without any issues, and it resulted in an APK file.

However, when I tried to install the file, I encountered an issue stating "Invalid package," and I couldn't install the game. I attempted to reduce the game size from 3GB to 2.20GB, but I still couldn't install the APK. I also tried disabling "Force recompile," but it didn't resolve the installation problem.

I noticed that there was a warning that appeared briefly during the package building process. Could this be the reason why I'm unable to install the game? This is my first time attempting to create an Android file, and I would greatly appreciate any assistance. Thank you very much.

Warning show in attach files thank you.

![warning](https://github.com/renpy/renpy/assets/142469177/f9ece6bd-f3ff-499e-959b-0adfab49e96f)

**Comment by renpytom** [comment]
This is not the problem, you likely need to get below 2GB.
