### ISSUE TITLE
Ren'py not launching Projects

### ISSUE THREAD

**Issue by DesDiv6** [renpy/renpy#4949]
Hi, to me it looks like I'm affected by the same issue as #4781 
Projects do not launch from main menu (no error, it just returns to the start screen). Dragging the folder to renpy.exe opens the Tutorial and The Question.

Log.txt:

Sat Sep  2 18:29:54 2023
Windows-10-10.0.22621
Ren'Py 8.1.1.23060707
 

Bootstrap to the start of init.init. took 0.03s
Early init. took 0.00s
Loader init. took 0.02s
Loading error handling. took 0.18s
Loading script. took 0.38s
Loading save slot metadata. took 0.13s
Loading persistent. took 0.00s
Set script version to: None (alternate path)
Running init code. took 0.31s
Loading analysis data. took 0.01s
Analyze and compile ATL. took 0.00s
Reloading save slot metadata. took 0.01s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache. took 0.00s
Making clean stores. took 0.00s
Initial gc. took 0.03s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object. took 0.26s
Cleaning stores took 0.00s
Init translation took 0.03s
Build styles took 0.00s
Load screen analysis took 0.03s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.07s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start. took 0.09s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 537.13'
Display Info: None
Screen sizes: virtual=(800, 600) physical=(1000, 750) drawable=(1000, 750)
Maximum texture size: 4096x4096

I'm new to Ren'py and just downloaded the zip and followed the Quickstart instructions. No changes done.

Your help is very much appreciated.

Kind regards

**Comment by mal** [comment]
Suggest trying one of the nightlies to see if you still have this issue with them, at least two issues that could cause this have been addressed since the release of 8.1.1 (#4878 and #4759).

**Comment by DesDiv6** [comment]
Hi Mal,
Thanks for the heads-up.
The nightly build solved it.
