### ISSUE TITLE
Possible issue with ruby text?

### ISSUE THREAD

**Issue by noellenoe** [renpy/renpy#4951]
I began translating my game and I've encountered a problem with ruby text?? 
![image](https://github.com/renpy/renpy/assets/53459848/fe76e19e-7e4a-4fda-8202-88b40691b4e7)
I did the style thing like so:

```ren'py
style ruby_style:
    size 8
    yoffset -20

style say_dialogue:
    line_leading 12
    ruby_style style.ruby_style

style history_text:
    line_leading 12
    ruby_style style.ruby_style
```

**Comment by renpytom** [comment]
I've been unable to reproduce this.
