### ISSUE TITLE
android build package problem: Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by lucas-watteuw** [renpy/renpy#4960]
I am on windows 10 and I try to build the project on android.

> Ren'Py 8.1.2.23090503

>Updating project.

>Creating assets directory.

>Packaging internal data.

>I'm using Gradle to build the package.
>To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: >https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
>Daemon will be stopped at the end of the build stopping after processing
>Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns >http://schemas.android.com/repository/android/common/01
>Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns >http://schemas.android.com/repository/android/generic/01
>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns >http://schemas.android.com/sdk/android/repo/addon2/01
>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns >http://schemas.android.com/sdk/android/repo/repository2/01
>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns >http://schemas.android.com/sdk/android/repo/sys-img2/01
>Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns >http://schemas.android.com/repository/android/common/01
>Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns >http://schemas.android.com/repository/android/generic/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns >http://schemas.android.com/sdk/android/repo/addon2/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns >http://schemas.android.com/sdk/android/repo/repository2/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns >http://schemas.android.com/sdk/android/repo/sys-img2/01
>Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns >http://schemas.android.com/repository/android/common/01
>Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns >http://schemas.android.com/repository/android/generic/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns >http://schemas.android.com/sdk/android/repo/addon2/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns >http://schemas.android.com/sdk/android/repo/repository2/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns >http://schemas.android.com/sdk/android/repo/sys-img2/01
>Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns >http://schemas.android.com/repository/android/common/01
>Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns >http://schemas.android.com/repository/android/generic/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns >http://schemas.android.com/sdk/android/repo/addon2/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns >http://schemas.android.com/sdk/android/repo/repository2/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns >http://schemas.android.com/sdk/android/repo/sys-img2/01
>Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns >http://schemas.android.com/repository/android/common/01
>Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns >http://schemas.android.com/repository/android/generic/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns >http://schemas.android.com/sdk/android/repo/addon2/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns >http://schemas.android.com/sdk/android/repo/repository2/01
>Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns >http://schemas.android.com/sdk/android/repo/sys-img2/01
>Warning: Dependant package with key emulator not found!

>FAILURE: Build failed with an exception.

>* What went wrong:
>Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
>> Failed to install the following SDK components:
 >     build-tools;29.0.2 Android SDK Build-Tools 29.0.2
  >Install the missing components using the SDK manager in Android Studio.

>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get >full insights.

>* Get more help at https://help.gradle.org

>BUILD FAILED in 15s

>The build seems to have failed.

I have on Android Studio, in the SDK Tools, the version 29.0.2 installed.

**Comment by renpytom** [comment]
Do you have access to Google's repository? Are you trying to install on a device that isn't connected?

**Comment by lucas-watteuw** [comment]
I just click on build package to create the apk file on my computer and then send it on my phone.
The part I don't understand is having access to Google's repository.

![Capture](https://github.com/renpy/renpy/assets/81231194/84535752-5752-4643-ab33-0a8a058a01ad)

I just install the Google API because of the API Level of 29.
Maybe there something really obvious that I don't know.

**Comment by renpytom** [comment]
Can you take a screenshot of what you're doing? The build should take place entirely within Ren'Py.

**Comment by lucas-watteuw** [comment]
I have made more than one mistake.
I thought than API level 29 have a link with the Android SDK Build-Tools 29.0.2.
My second mistake was to select Play Bundle instead of Universal APK.

![Capture](https://github.com/renpy/renpy/assets/81231194/0a938969-4d10-4fff-8868-fb5e9a5b95ad)

I just use Android Studio to install the Android SDK Build-Tools 29.0.2.

The build only take place in Renpy.

**Comment by renpytom** [comment]
I've been unable to repeat this. I don't need to install anything with Android Studio, so perhaps that is your problem.
