### ISSUE TITLE
Using default_focus in a Preferences screen locks up input in bars

### ISSUE THREAD

**Issue by nkrapivin** [renpy/renpy#4970]
Repro steps:
1) Create a fresh project with default settings (just press next next next)
2) In `screens.rpy` add `default_focus True` to the text speed bar in the preferences screen:
```rpy
bar value Preference("text speed") default_focus True
```
3) Run the project, DON'T TOUCH THE MOUSE, open Preferences using the keyboard (down down down enter),
4) Text speed should be highlighted, scroll down to a different bar, press enter to select it, press the right arrow a few times.
5) Observe that all input is essentially locked up, same thing happens when using a game controller.

**Comment by renpytom** [comment]
What version of Ren'Py are you using? I can't repeat this with the current nightly.

**Comment by nkrapivin** [comment]
I am using 7.5.3 but there weren't any changes related to default_focus, if you can tell me which commits to cherrypick that would be awesome because I am maintaining a Nintendo Switch port and upgrading to 8 right now is not an option.

**Comment by renpytom** [comment]
Can you try it on Ren'Py 7.6.2, and see if the problem repeats there?

**Comment by nkrapivin** [comment]
Hmm, no, doesn't happen. But what commit fixed the issue then...
Thanks anyway!
