### ISSUE TITLE
"preferences.gl_powersave = False" breaks Web version preloading prediction

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#4979]
The web version tries to load images and music a few moments before they are necessary. But this feature is disabled in a game with the following line

`default preferences.gl_powersave = False`

I think this behavior is a buggy because preferences.gl_powersave shouldn't interfere with preloading prediction in the web version.

Version: Renpy 8.1.3

**Comment by renpytom** [comment]
I don't believe this is fixable, as the web platform only supports a single thread, which will get starved. I'd suggest not setting preferences.gl_powersave to False on the web platform.
