### ISSUE TITLE
Android: App not installed as package appears to be invalid

### ISSUE THREAD

**Issue by tedbc** [renpy/renpy#4980]
Users get this error when trying to install the game on Android devices: App not installed as package appears to be invalid.

I have rebuilt the game multiple times (also reinstalled Renpy) but none of the generated packages works. 

Can anyone suggest a fix?

**Comment by teodorburlacu** [comment]
> Do you have the package file? Is it < 2GB, and an apk and not an ADB?

Yes, the apk is greater than 2GB. Is that the reason? And is there any fix to it?

**Comment by teodorburlacu** [comment]
> Do you have the package file? Is it < 2GB, and an apk and not an ADB?

Yes, the apk is greater than 2GB. Is that the reason? And is there any fix to it?

**Comment by renpytom** [comment]
That's likely the reason. It's a limit on Android. I'm working on ways around this, but for now your best bet is to get the game under 2GB.

**Comment by renpytom** [comment]
This isn't an issue with Ren'Py, so I'm closing the issue.
