### ISSUE TITLE
How to manually load videos into RAM?

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#4981]
I know Renpy has a predictive loading feature for Images and audio, but this feature is missing for videos. My game has extensive use of videos, and it’s for Web and PC. 
On the Web version, downloading a video at the exact moment it’s needed makes the play experience slow.
If I could have a script to manually request a video file, to load it into RAM I would be capable of solving my problem.

Another alternative, is if I had a script to check if a specific video is already cached on disk or in RAM.

**Comment by Kassy2048** [comment]
It should be possible to implement the caching of video files in advance on the Web platform as well, although they must not be put in the MEMFS after downloading contrary to what we do for image/audio files. I'll have a look at it when I'll find some time.

Alternatively, you can use the [web_cache_preload](https://www.renpy.org/doc/html/preferences.html#var-preferences.web_cache_preload) preference to load the full content of your game in the browser cache (including video files) and make it playable offline. Of course, if the content is big, it will take time to download and cache it.

**Comment by SergioAlonsoJr** [comment]
I'll use web_cache_preload, but it might take 10 minutes until all the game files are downloaded. Also, I don't have control over the order that files are being downloaded with web_cache_preload. I wish I could prioritize all the video files before images and audio.

**Comment by Kassy2048** [comment]
You should be able to prioritize video files with this preference by manually editing the file "pwa_catalog.json" and putting video files at the beginning of the list. You could also only keep video files in that file if you're okay with image/audio files not being preloaded when the game starts (so it will not be playable offline).

The file "pwa_catalog.json" is re-generated each time you build the game though, so better keep a copy of its modified version somewhere to erase the re-generated version after each build.

**Comment by SergioAlonsoJr** [comment]
Editing "pwa_catalog.json" will certainly help a lot to prioritize video files over images and audio.

Would it be possible to check whether a specific video file is already in cache or not?

**Comment by renpytom** [comment]
No. 

There doesn't seem to be a way to see it something is in cache on the web platform, at least that I know of.

**Comment by Kassy2048** [comment]
The service worker has access to its own browser cache, so that should be possible by interacting with it. I'm thinking about asking the SW to pre-fetch the video files when RenPy predicts they will be needed.
