### ISSUE TITLE
GL2 render stuttering on Android 5.1

### ISSUE THREAD

**Issue by AviTheTiger108** [renpy/renpy#4982]
If I don't set gl2 to false, my games tend to stutter and lag on my Android device.

Model: Alcatel OneTouch Pixi Glory
SoC: Qualcomm Snaodragon 210 MSM8909
CPU: ARM Cortex A-7, 1100 MHz, Quad Core 32-bit, 1mb L2
GPU: Qualcomm Adreno 304, 400 MHz
RAM: 1GB, 533 MHz, Single Channel
Year of Manufacture: 2016

More info on the phone https://www.devicespecifications.com/en/model/ac093f87

**Comment by renpytom** [comment]
What sort of resolution would you expect here? That's a budget phone from 7 years ago.

**Comment by AviTheTiger108** [comment]
Would the depreciation of the current/old OpenGL Render apply only to RenPy 8, or would gl2=false not work anymore on RenPy 7 as well?

Or am I misreading the 8.1.3 announcement?  It just says that the original OpenGL renderer will be removed and that gl2 should be set to true

**Comment by renpytom** [comment]
Ren'Py 7 support will end at the same time gl support is removed. 

Fundamentally, I think this is just an old phone. It it supported by its manufacturer? Android 5.1 hasn't been supported since 2016.

**Comment by AviTheTiger108** [comment]
The phone doesn't update so I don't think so?  

What will happen when support for 7 is lost?  Will I no longer be able to build to android with it?

**Comment by HorBro38** [comment]
> The phone doesn't update so I don't think so?
> 
> What will happen when support for 7 is lost? Will I no longer be able to build to android with it?

You are free to stay on 7 for as long as you want, you just won't see any further updates.

**Comment by renpytom** [comment]
And that's that. I'd suggest getting a new phone at some point, for security and compatibility with newer software. Not just Ren'Py - you're at the point where websites will start breaking.

**Comment by AviTheTiger108** [comment]
Thank you!
