### ISSUE TITLE
In Renpy 8.1.3 Web, video displayables become transparent when they are still being downloaded

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#4983]
I'm using Renpy 8.1.3 Web, and I define my [Movie ](https://www.renpy.org/doc/html/movie.html#Movie) Displayable using both:

start_image
> An image that is displayed when playback has started, but the first frame has not yet been decoded.

and

image
> An image that is displayed when play has been given, but the file it refers to does not exist. (For example, this can be used to create a slimmed-down mobile version that does not use movie sprites.) Users can also choose to fall back to this image as a preference if video is too taxing for their system. The image will also be used if the video plays, and then the movie ends.

But neither of these are displayed when a movie file is not in cache and is being downloaded. Instead, the Movie Displayable becomes transparent.

I wish that either start_image or image are displayed while the video is still being downloaded.

**Comment by renpytom** [comment]
As best as I can tell, this is invalid, or else the first frame of your movie is transparent. I did substantial experimentation, and on both chrome and firefox, start_image is displayed before the movie begins.

**Comment by SergioAlonsoJr** [comment]
@renpytom 
I spent 2 more hours testing, and I think I found the real culpirit. It's the **size parameter**


   ```
 image video artlist = Movie(play="images/video artlist.webm",
        start_image="first_frame",
        size =(1920, 1080) # size breaks the start_image
        )
```

When I remove the size =(1920, 1080) parameter, the start_image loads. But when I add it, the start_image breaks.

Please test it on your end.
