### ISSUE TITLE
Renpy 8.1.3 Web on Android or iOS: dragging a scrollable interface hits the refresh action

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#4991]
On any website, on Android or iOS, if you drag your finger down being near the top of the page, will cause it to refresh.

The problem happens when a game has a scrollable viewport that can be navigated with the same gesture, but this gesture will cause the page to refresh, which will restart the game from the preloading screen.

It can be tested with the “The Question” project, on the settings screen.

Desired behavior: Inspired on m.youtube.com. If I drag my finger down inside the video player, m.youtube.com will not refresh and restart my video.

**Comment by renpytom** [comment]
overscroll-behavior: none

Is the magic word to disable refresh.
