### ISSUE TITLE
Flashing Image not working from update v8.1.2

### ISSUE THREAD

**Issue by BlackGrimReaper** [renpy/renpy#4994]
![Screenshot 2023-09-23 001337](https://github.com/renpy/renpy/assets/26975750/36bcba7a-4068-4ec0-bf86-8fa7ea7c4944)

I've employed the code above to overlay a white screen on my renders and images. However, starting from v8.1.2, this code no longer functions. Surprisingly, even in v8.1.3, it remains ineffective. Consequently, I had to revert back to v8.1.1., where it operates flawlessly. Is there anyone who can offer assistance with this issue?

**Comment by Gouvernathor** [comment]
It may possibly (though I doubt it) be related to #4867, which relates to using Dissolve in ATL.

**Comment by Gouvernathor** [comment]
I can't reproduce this in the latest Nightly, but it does trigger in Nightly Fix. So, I suggest waiting for the next full release, 8.2, which will have this fix (whatever the actual problem may be).

**Comment by BlackGrimReaper** [comment]
Tried the code again in v8.2.1.24030407 and 8.3.0.24051701+nightly but its not working... again working flawlessly in 8.1.1. I thought since it's completed, it's fixed. Am I missing something?
