### ISSUE TITLE
Linting each character word count

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5001]
At the moment lint gives this: 

`h has 4,326 blocks of dialogue.`

It will awesome to do this:

```
h has 4,326 blocks of dialogue, containing 34,951 words and 75,975
characters.
```

That way you can quickly have an idea of your budget for voice actors.

**Comment by Gouvernathor** [comment]
Tha would not be a good idea for games with lots of characters, as it would bloat the lint report. It would also break the current shortening we have with "a, b and c have 5 blocks of dialogue".
However, as an opt-in I think it would be a good option. And if we add lint opt-ins, I would throw in #3878 as well.
