### ISSUE TITLE
Renpy 8.1.3 Web: icons should be replaced like web-presplash.jpg

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5003]
![image](https://github.com/renpy/renpy/assets/4298411/9a4a76de-2eb5-4b18-a9d9-f4bc48f047f4)

I wish I could replace these icons by putting them into my renpy project.

**Comment by renpytom** [comment]
This is supported by pwa_icon.png, which doesn't appear to be documented.

**Comment by Kassy2048** [comment]
The file name should be "web-icon.png" actually and put in the project root folder (not the game subfolder). Its resolution must be at least 512x512 and be a square. I'll send a PR about that later on.

**Comment by SergioAlonsoJr** [comment]
I can confirm that "web-icon.png" outside the "game" subfolder does the trick.
