### ISSUE TITLE
Request for Web: allow video web-presplash.mp4 or other formats

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5004]
Preloading the web version easily takes 20–30 seconds, which is a long time to watch a static image.

I wish I could replace the web-presplash.jpg with a video file.

OR

A sequence of images that are each shown for 3 seconds before going to the next one.

This can solve the boredom problem while the web version loads.

**Comment by bober-gith** [comment]
If it works like ren'py 7 web, you can do that with a web-presplash.webp. Because webp can contain sort of gif animation too.
Here is one I used for the web if want to try:
https://i.ibb.co/cQnwKZb/web-presplash.webp

**Comment by SergioAlonsoJr** [comment]
@bober-gith, it works!

It works on the 3 platforms: Desktop, Android and iOS.

The only drawback is that the animated .webp is about 4x bigger than a regular .mp4 h264 file.

**Comment by bober-gith** [comment]
There should be some kind of compression tools available for webp, for example, a setting to not change the pixels that don't change between the frames, quality setting etc., but it might be that .mp4 does all of it a bit better. The anim that I was using is below 200kb, for around 6 frames at 720P I believe, I think that's not too bad, as long as there aren't too many things going on you can have something that could load quite fast.

**Comment by renpytom** [comment]
I think webp is a good solution here, so I don't plan to add support for other formats.
