### ISSUE TITLE
Renpy 8.1.3 Web: in Movies, image parameter is being loaded before start_image

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5005]
The [Movie](https://www.renpy.org/doc/html/movie.html#Movie) objet has two parameters that I'm using:

**_start_image_**

> An image that is displayed when playback has started, but the first frame has not yet been decoded.

**_image_**

> An image that is displayed when play has been given, but the file it refers to does not exist. (For example, this can be used to create a slimmed-down mobile version that does not use movie sprites.) Users can also choose to fall back to this image as a preference if video is too taxing for their system. The image will also be used if the video plays, and then the movie ends.

I'm using both parameters, but with different images.
I'm using **_start_image_** as the first frame of non-loopable video; and **_image_** as the last frame of the video.

The problem is: Renpy Web is showing me **_image_** while the video is loading, but I want to see **_start_image_**.
I would like to see **_image_** only after the video is done playing.

**Comment by SergioAlonsoJr** [comment]
@raspberry-soft, how can I use that?

**Comment by renpytom** [comment]
I'm unable to repeat this, with the script:

```renpy
label main_menu:
    return

image oa4 = Movie(play="oa4_launch.webm", start_image="#00f", image="#f00", loop=False)

label start:
    scene bg washington

    "..."

    show oa4 at truecenter

    "..."

    return
```

And the relevant assets from the tutorial game. I'm testing against the test server, with chrome configured to include a 250ms delay, and cache disabled. 

Blue shows up for 250ms, the movie plays, and then red replaces it.

It's possible other changes fixed this, but I'm going to mark this as can't reproduce.
