### ISSUE TITLE
Interpolation functions

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#5009]
When interpolating, the object returned should be checked to see if it's callable. If it is, then the function should be called, and the result of the call should be formatted and interpolated.

**Comment by mal** [comment]
Interpolating the result of `__call__` rather than the result of `__str__` would be surprising and break games that already expect/rely on it, so if pursued this feature would need to differentiate such cases. Perhaps a new `[custom_func!f]` suffix.
