### ISSUE TITLE
Mixed relative + absolute position type

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#5013]
Add a new position type, representing the sum of an absolute position (a current int or absolute) and a relative position (a current float).
- It would first be added internally only, for test purposes and to add a new aside feature (mixed-type interpolation). It would work as a lingua franca to which you would convert positions of different types for means of summing them or interpolating them - a bit like absolute.compute, except that you don't need to know what the available room is.
- Then we can document it as a callable, like absolute() but with two parameters.
- Then, there is an idea of adding a `px` object and to allow syntaxes such as `a+b*px` to ease use of this feature for the general public. It poses consequent API questions which I believe are best left for later.

Update : points 1 and 2 can't be split because of renpy.get_placement, which leaks the internal values of some transform/style properties to the creator, so we can't add new possible values of said properties without documenting them.

---

### TODO :

- [/] Study implementing the mixed position type as a subclass of complex instead of a namedtuple, in terms of code complexity and performance.

Pros :

- the `-`, `+` (unary and binary), `*`, `/`, and `**` operators are already implemented the way it makes the most intuitive sense. To interpolate mixed coordinates a and b, over x between 0 and 1, it's `x*a + (1-x)*b` or `a + x * (b-a)`. Tuple multiplication is awful in our use-case. Being implemented in C rather than in Python by ourselves, these calculations are also faster.
- weighs half as much in memory (complex subclass is 48 bytes, 2-long namedtuple containing one int and one float is 108 bytes).

Cons :

- No easy way of telling `0*px` from `px` from `.0+0*px`. `px` may need to be a singleton and relative-less coordinates be of a different class, or we may need to add a flag slot. There are ways around that with a tuple implem by playing with the type of the two elements, when with a complex, they are always floats. Maybe `a*px` may return an `absolute` ? But if an absolute being summed with a float returns a mixed coordinate, that's a breaking change.

Neither :

- both attribute accesses are of equal time.

---

- [x] Replace the position variable in renpy.atl with an actual type (or static/class method) taking any kind of supporting position and returning a mixed coordinate. Also make an "or None" version, if only local to the atl module.

---

- [x] Implement addition/interpolation of position transform properties of any type. First because it's a nice useful feature, second because it will eventually be covered by the conjunction of a) interpolation of mixed coordinates and b) conversion of any position type to mixed coordinate.

**Comment by mal** [comment]
Closed by #5123 (see commit referencing this issue above).
