### ISSUE TITLE
renpy.exports.can_rollback() seems unreliable

### ISSUE THREAD

**Issue by bober-gith** [renpy/renpy#5014]
I use it as a condition to display a notification message warning the players that they have reached how far they can rollback when they try to use rollback but it cannot go back further than that.

Something like this:
```
if not renpy.exports.can_rollback():
   key "K_r" action Function(limitrollbacknotify)
else:
   key "K_r" action Rollback() 


def limitrollbacknotify():
   renpy.display_notify(rollbackexhaustedalert)
```

This works on the first playtest perfectly, but at one point it stops working, from what I've noticed it tends to go wrong when you start making saves/loading saves and reloading in dev mode, but I'm not sure what exactly is the trigger, because it doesn't always go wrong. Is there by any chance another method that can give more consistent results?

**Comment by bober-gith** [comment]
Upon further testing, while it doesn't always happen, and seems to start getting a thing only after some dev reloads and load/save, it seems to be always linked to the following statement:

$ renpy.suspend_rollback(True)
_something here_
$ renpy.suspend_rollback(False)
n "Cannot rollback before this line but the renpy.exports.can_rollback() still reports True"

**Comment by bober-gith** [comment]
Last post about it, here is a template project made on 8.1.3 that can replicate the issue with a bit of luck:
[TestRollback.zip](https://github.com/renpy/renpy/files/12750193/TestRollback.zip)
It has just this piece of code to make it obvious when the can_rollback() is working and when it's not:
![image](https://github.com/renpy/renpy/assets/78823063/b3a77e5d-2889-4f25-84d4-52db6456ed5c)
It contains some saves, the save 2-5-LT1.save has the issue. To trigger the issue I just tried everything blind, I'm not sure what caused it but after some load/save, quit, restart the game, I was able to replicate it once. It doesn't even to be related to $ renpy.suspend_rollback() but I'm not sure.

**Comment by Booplicate** [comment]
Your code seems to be incorrect:
```renpy
if not renpy.exports.can_rollback():
   key "K_r" action Function(limitrollbacknotify)
else:
   key "K_r" action Rollback() 
```
That `if` statement will be evaluated when the screen is rendered. If at first rollback was possible, your screen will have the `Rollback` action, then if when the player presses the key it's not, your screen will still use the other action attempting to rollback.

I might be wrong and it might update itself on key press, but I wouldn't rely on that.

**Comment by bober-gith** [comment]
Hmm I see what you mean, the thing that is strange is that it s working correctly 99% of the time but breaks at one point after load/save or something breaks it, but on a first playtest there will be no problem. 
Do you have another method that I could test to eliminate this possibility? Thank you.

**Comment by mal** [comment]
The `suspend_rollback` function doesn't prevent rolling back (that would be `block_rollback`), so `can_rollback` returning `True` after it being called makes sense. Suspending rollback can be thought of a bit like a "stop recording" action on a camera - you can still rewind, there's just no new footage until you resume - so rolling back would still work, it would just rollback all the the way to the last interaction before the suspension. Hopefully the example below will help to clarify that a little.

<details><summary>The following example behaves as expected on 8.1.3.</summary>

```rpy
label main_menu:
    $ _confirm_quit = False
    return

label start:
    show screen rollback_control()
    "First line - cannot rollback before start of game."
    "Second line - can rollback here."
    $ renpy.suspend_rollback(True)
    "Third line - can rollback from this line, but not back to it."
    "Fourth line - can rollback from this line to before suspension."
    $ renpy.suspend_rollback(False)
    "Fifth line - can rollback to the second line, skipping the 'suspended' lines."
    $ renpy.block_rollback()
    "Sixth line - cannot rollback as it's been blocked."
    "Seventh line - can rollback here."
    "End."
    return

screen rollback_control():
    layer 'bottom'
    if not renpy.exports.can_rollback():
       key "K_r" action Function(renpy.notify, "Unable to rollback before this point.")
    else:
       key "K_r" action Rollback() 
```
</details>

**Comment by bober-gith** [comment]
All good Mal, I get that, it's hard to explain it correctly... I think the best is to download the template and see the issue live. I'm still thinking it might be what booplicate said, and if there is another method I would love to test it.
I'm aware renpy.suspend_rollback(True) will 'jump' the segment inbetween the flags, I was mainly speculating if it was not creating an issue with renpy.can_rollback() where it ends up blocking it in a state where it's forever returning True when it shouldn't, even though it can't rollback anymore. I hope that makes sense, it's a bit hard to explain, and I can't pinpoint what is triggering the issue right now.

**Comment by mal** [comment]
Are you simply exhausting your `config.rollback_length`? Try bumping it up and see if you still see this issue.

**Comment by mal** [comment]
I've only done some cursory poking around, but it seems like perhaps the internal count of how many steps can be rolled back is no longer being tracked accurately (possibly due to various changes to rollback behaviour over the years), so the list of places you can rollback to is (effectively) exhausted before the counter hits zero, which is why you're seeing `can_rollback` return `True`.

Tom will probably need to look at this when he has a moment.

---

To speed that secondary investigation, it's possible to reproduce the problem reliably by:
1. Skip all the way up to the high 90s.
2. Rollback as much as possible.
3. Run out at around 7/8.
4. At this point `renpy.game.log.rollback_limit` is significantly higher than `len(renpy.game.log.log)` and the remaining entries aren't suitable for rollback.

**Comment by bober-gith** [comment]
Just a reaction to your update Mal, first of all, I understand it now better thanks to your explaination so I'll definitely raise the config.rollback_length on the main project. 
I just want to specify that when I raised the config.rollback_length when you asked me to, I did it on the template project, putting it at 200, not on my project. So I think the default config.rollback_length seems to not handle well a base project with only dialogue lines, a base project will run into this problem I think. The second thing is how do we know how much we need, is there something we can take a look at to determine what works the best for a project that plans to use can_rollback()? Thanks again for your help, and at any rate in the meantime, I'll just try different values until the problem seems to be gone on the original project so even if there is no way to know it's fine.

**Comment by mal** [comment]
The commit https://github.com/renpy/renpy/commit/2a62b88aeb83f538cce64b55ea9aad13b0d3fa4d targeted this issue using a fix that took the same approach as I did above. It makes things behave in a more expected manner but is still unable to correctly account for blocked rollback, but that maybe sufficient for now.

**Comment by bober-gith** [comment]
👍

**Comment by mal** [comment]
As explained in my last message, this is not fixed, and can currently break rollback.
