### ISSUE TITLE
Renpy 8.1.4.23092301+nightly Web: can't use renpy.movie_cutscene()

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5015]
`$ renpy.movie_cutscene('video.mp4')`

crashes the game on Renpy 8.1.4.23092301+nightly Web

Crash Message
![image](https://github.com/renpy/renpy/assets/4298411/5a7be1d0-3225-4e9f-baba-9772e08f7c33)

**Comment by Kassy2048** [comment]
Yep, cutscenes are broken on all platforms since 03fdf2801ea8c18f8ff2d091031f2d9b2ea517de. It's easy to reproduce using the video section in the tutorial. The `render_movie()` method should probably be added back for cutscene movies only.
