### ISSUE TITLE
Renpy 8.1.4.23092301+nightly Web iOS: Audio stops working after you lock and unlock the screen

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5017]
1) The audio starts working when the game starts.
2) I lock the screen of my iPhone.
3) I unlock the screen of my iPhone.
4) There is no audio anymore.

I believe this issue also happens in 8.1.3

**Comment by renpytom** [comment]
Closed by 5db965a7093333a5ae0ea4e434af908483a801c4
