### ISSUE TITLE
Quick return to game when using controller

### ISSUE THREAD

**Issue by tezf** [renpy/renpy#5019]
Hi team, I've been reading a bunch of VNs lately on my steam deck and a minor enhancement I'd like to suggest is for the controller B button when in the menu to act more idiomatically to how video games use it, as well as for users that play on both keyboard and mouse and controllers to have a more consistent experience.

B in video game usually binds to exiting menus, escaping 1 level of the menu, etc. I've also mentally linked A to mouse 1 and B to mouse 2 in my brain (sample size of 1 though).

B in renpy currently is bound to the alternate action, which (usually?) doesn't get used in the game menu screen so it's slightly jarring for users that are used to the idiomatic B. 

There are a couple of proposals along with some musings I'll leave here:
1. changing the behaviour of B when in menu screens to exit the menu
    * this is the least harmful to users as this doesn't change the default behaviour of renpy outside of the menu context
    * unknown if authors will use alternate actions in the menu screen 
    * unknown to me how renpy deals with keymapping and if context aware keymaps are a thing
2. changing the behaviour of B universally to toggle the menu
   * this brings it more in line with how keyboard and mouse users experience renpy vns
   * this is a breaking change to the behavioural contract renpy has with users
   * will need to find another suitable key for alternate actions, X perhaps?
3. mapping long press B to toggle the menu
   * this is ok I guess, some games will map long press B to exit the menu fully so there is precedence for this
   * how can functionality like this be surfaced to the users intuitively?
   * sub musings: I just remembered that I stumbled on the skip to next choice option by accident, it's B when the skip option is highlighted

I was also thinking that a truly idiomatic B button should mean that it should return users out 1 level of the menu, but most games I've play do not employ submenus so I don't think this is necessary.

**Comment by renpytom** [comment]
Makes sense, I've made the change.
