### ISSUE TITLE
Renpy 8.1.3: Movie class, providing channel prevents transitions.

### ISSUE THREAD

**Issue by Paraxdq** [renpy/renpy#5021]
The following code will produce the error. The images vid_a and vid_b will just appear without the transition compared to a and b which will have transitions.

```
image vid_a = Movie(play="videos/a.webm", channel="vid")
image vid_b = Movie(play="videos/b.webm", channel="vid")

image a = Movie(play="videos/a.webm")
image b = Movie(play="videos/b.webm")

[...]

"" "Test1"
show vid_a with Dissolve(2.0)
"" "Test2"
show b with Dissolve(2.0)

"" "Test1"
show a with Dissolve(2.0)
"" "Test2"
show b with Dissolve(2.0)
```

**Comment by renpytom** [comment]
The error is in sharing the same channel between two movies. I'd suggest not using the channel argument here. (It's not that useful.)

**Comment by Paraxdq** [comment]
Thanks for the reply, I just used it because I wanted to reduce the audio volume of the movies and there is no specific channel if I don't use the channel argument. Is there a better way to reduce the volume without setting the channel?

**Comment by mal** [comment]
I think you should be able to use [`config.movie_mixer`](https://www.renpy.org/doc/html/config.html#var-config.movie_mixer) to set the default mixer for movie displayables to something other than `music`, and then use the volume controls on that mixer to affect your movie displayables.

**Comment by Paraxdq** [comment]
@mal it works kind of. But that leads me to the problem I started the issue with (no transitions between the videos).

This works but prevents the transitions:
```
define config.movie_mixer = "video"

renpy.music.register_channel("vidChannel", mixer="video", loop=False, stop_on_mute=False, tight=False, buffer_queue=True, movie=True)

image vid_a = Movie(play="videos/a.webm", channel="vidChannel")
image vid_b = Movie(play="videos/b.webm", channel="vidChannel")

"" "Test1"
show vid_a with Dissolve(2.0)
$ renpy.music.set_volume(0.0, channel="vidChannel")
$ SetMixer("video", 0.0)
$ Preference("video volume", 0.0)
"" "Test2"
show vid_b with Dissolve(2.0)
```

Without setting the channel of the video, I can create a preference volume slider which changes the volume of the videos but I can't (or at least don't know) how to change the volume during the game like "renpy.music.set_volume" is only for channels and won't work if I don't set the channel for the videos. 

"SetMixer("video", 0.0)" or "Preference("video volume", 0.0)" don't work either.

**Comment by bober-gith** [comment]
You could remove/extract the audio track of the movie file with a program like audacity, and play it in parallel as the video file on a regular audio channel. It's not pretty but it works.

**Comment by Paraxdq** [comment]
Yes , that is possible and I also tried that but the audio gets desynced after some loops. The clips is just some seconds long and repeats itself over and over again, so that won't work unfortunately. :/ I manage to reduce the volume in the preference menu if I won't set the Movie() channel, but that should also be possible with renpy commands during the game flow, right?

**Comment by Paraxdq** [comment]
I found some code snippets online and the following piece does give me the desired result 👍 

```
$ _preferences.set_volume("video", 0.0)
```

**Comment by bober-gith** [comment]
Nice. If the original error was in sharing the same channel between the two movies, could have tried to set two different channels, each movie a channel then use renpy.music.set_volume, for testing at least, but I assumed you had tried that too.

**Comment by Paraxdq** [comment]
Thank you! It's a big workaround, but at least I don't have to manually edit more than 50 video files to reduce the volume in each of them...
I didn't think of using the same channel would prevent the transitions from occurring to be honest, I thought I could provide a playback channel for the sound in the video, why should I make 50 channels, didn't make much sense to me, but it's solved now.

**Comment by bober-gith** [comment]
It seems there is something clunky here for sure, there is probably a reason for that though, I don't know the technicity. The answer was given by tom when he closed the post. I ran into similar things with video in the past and extracting the tracks made it easier but I was not dealing with loops, I learned something here too.

**Comment by Paraxdq** [comment]
I think so too... when I have two videos playing on the same channel they start to "lag", just slightly but I still noticed it. It would be perfect if you could give the movie class a relative_volume or volume setting.

Since my last post I started from scratch again because when I use the _preference setting to adjust the volume of the sound, it wouldn't be adjustable by the user at all, which made me realize that I should do it in another way. I don't use voices in my novel so I renamed the voice slider to video and set the default movie mixer to voices. Now I just need to make sure that the videos have an equivalent level of volume. I think that's a good workaround, for now.

**Comment by bober-gith** [comment]
Aren't you able to do something like:

**Comment by bober-gith** [comment]
Aren't you able to do something like:

image vid_a = Movie(play="videos/a.webm", channel="audiovid1")
image vid_a = Movie(play="videos/b.webm", channel="audiovid2")

$ renpy.music.set_volume(0.3, 0, channel='audiovid1')
$ renpy.music.set_volume(0.5, 0, channel='audiovid2')

then for the mixer:
define config.movie_mixer = "movie"

and in your audio interface part where the player adjusts the volume:
bar value MixerValue('movie')

**Comment by Paraxdq** [comment]
I tried that! But that's when I found out that the movies start to lag at the point where they start over and over again, it looked really clunky. I need to put more work in unfortunately, and edit the movies to have an equal volume. But it works now, so yeah. Still bothers me that we can't do what you also suggested, that would be handy.

**Comment by mal** [comment]
As an experiment, does this fit the bill?

```rpy
init python:
    def play_movie_at(volume):
        def play_callback(old, new):
            renpy.music.play(new._play, channel=new.channel, loop=new.loop, synchro_start=True, relative_volume=volume)

            if new.mask:
                renpy.music.play(new.mask, channel=new.mask_channel, loop=new.loop, synchro_start=True, relative_volume=volume)

        return play_callback

image vid_a = Movie(play="videos/a.webm", play_callback=play_movie_at(.3))
image vid_b = Movie(play="videos/b.webm", play_callback=play_movie_at(.5))

define config.movie_mixer = "movie"

# and in your audio interface part where the player adjusts the volume:
bar value MixerValue('movie')
```

The idea is that the tertiary volume (the one you provide to `play_movie_at`) would be set each time the displayable starts playing, while the primary (overall volume) and secondary (the `movie` mixer`) would be controlled by the player as Bober outlined, The result (I think) should be that you're able to specify the relative volume for each video when you define them.

**Comment by Paraxdq** [comment]
That works perfectly, thank you very much!

**Comment by Paraxdq** [comment]
@mal Your solution works pretty well but unfortunately you can't save the game anymore if any of these changed Movies are in the Stack / Cache, I don't know exactly but after I played the first Movie, I am unable to reload the game nor save it in the published version.
The following error occurs every time when reloading or saving:

[traceback.txt](https://github.com/renpy/renpy/files/12848485/traceback.txt)

I would be very happy if you could provide a solution for the problem! Thanks in advance!

**Comment by Gouvernathor** [comment]
```py
init python:
    import functools
    def play_callback(volume, old, new):
            renpy.music.play(new._play, channel=new.channel, loop=new.loop, synchro_start=True, relative_volume=volume)

            if new.mask:
                renpy.music.play(new.mask, channel=new.mask_channel, loop=new.loop, synchro_start=True, relative_volume=volume)

image vid_a = Movie(play="videos/a.webm", play_callback=functools.partial(play_callback, .3)
image vid_b = Movie(play="videos/b.webm", play_callback=functools.partial(play_callback, .5)

define config.movie_mixer = "movie"

# and in your audio interface part where the player adjusts the volume:
bar value MixerValue('movie')
```
That should do the trick.

**Comment by Paraxdq** [comment]
Works perfectly, thank you very much!
