### ISSUE TITLE
Enable Duplicating master layer (adding effect on partical area of master)

### ISSUE THREAD

**Issue by Wendy-Nam** [renpy/renpy#5026]
Hello. I've encountered an issue while implementing the GUI with a semi-transparent background. I needed to create a blurred effect in the area behind it to make the textbox more prominent. However, I could only apply the blur to the entire master layer, not just a portion of it. So, I applied the blur to the entire master area and then cropped it to match the textbox area.

Now, all I need to do is display the original master layer screen behind that cropped piece. However, I can't seem to find a way to display two master layers at the same time or duplicate the current master layer, including all its transition statuses, images, and so on, into another layer.
<img width="1196" alt="스크린샷 2023-10-01 오후 8 05 01" src="https://github.com/renpy/renpy/assets/142412339/e1ba07eb-d82b-4c20-af3b-e6c0c1e7ebda">

If there is a solution for this, I would greatly appreciate it. Thank you in advance.

**Comment by mal** [comment]
You can try this which seems to work in my brief testing (vary the blur number to your liking):
```rpy
style say_window:
    background Transform(Layer('master'), blur=15)
```

<details><summary>Extra bits and pieces that might be useful</summary>

```rpy
# in case you already have a background, you can combine them like so:
style say_window:
    background Fixed(Transform(Layer('master'), blur=15), previous-background-value)
```

```rpy
# You can also add other effects such as reducing the brightness to create a better contrast:
style say_window:
    background Transform(Layer('master'), blur=15, matrixcolor=BrightnessMatrix(-.1))
```
</details>
