### ISSUE TITLE
RenPy 8.1.423092801+nightly Problems with "frozen" SideImage only after loading a savegame.

### ISSUE THREAD

**Issue by Deschain1975** [renpy/renpy#5027]
No problems while playing from the beginning to the end.
Problems with "frozen" SideImage only after loading a savegame!

1.) Start a new game.
2.) Save game.
3.) back to the main menu.
4.) load save.

The avatar from the first picture of the loaded savefile stays somehow "frozen in the background"?!
You can see it (briefly) at every transition.
and at the end (pause)

PS
(just for info, not built in the demo.)
It also happens to me with "multiple-say-windows" (then the SideImage even gets X times overlaid). Wanted to keep the code as "vanilla" and small as possible. X=number of multiplesaywindows, 4 times in my case.
[Seitenbild-1.0-win.zip](https://github.com/renpy/renpy/files/12777411/Seitenbild-1.0-win.zip)

**Comment by zarg0n** [comment]
I've been experiencing this same issue since yesterday (Using Renpy 8.1.3) and the way I was able to fix it was by going back to Renpy 8.1.1.

- My previous saves created in Renpy 8.1.3 still had the problem in Renpy 8.1.1.

- New saves created in Renpy 8.1.1 do not seem to experience the problem of stuck/frozen sideimages.

**Comment by bober-gith** [comment]
I would check out the last nightly fix, it has some sweet fixes for things related to greedy_rollback, which made a big difference for me, and what you are describing looks a bit like the problem encountered earlier last month with rollback that was fixed. Wouldn't hurt to give it a try.

**Comment by renpytom** [comment]
Closed by mistake by the fix for #5017
