### ISSUE TITLE
When declaring a Character, the image attribute isn't take in account, dynamic also

### ISSUE THREAD

**Issue by Quarior** [renpy/renpy#5031]
Hi.
I have a problem, and I think it is a bug.

When I am in the scene "acte0_scene5.rpy":
```renpy
label acte0_scene5:
    luin "{b}Emprunte le chemin indiqué Vivanas pour se rendre à la salle de recrutement.{/b}"
    "Près de la salle de recrutement, au niveau d'une porte."
    luin "{b}En marchant.{/b} {i}J'entends du bruit, ça doit être par là.{/i}"
    "Boom." with vpunch
    luin "Aïe."
    $ maecenas_name = "Femme qui a ouvert la porte"
    show character_maecenas
    "{i}Test pour voir si l'image s'affiche. C'est le cas."
    maecenas surprise "Ah. Vraiment désolé, je ne vous avais pas vu Monsieur."
    luin "Cela n'est pas grave Mademoiselle, ça sera juste une bosse et un bleu. Et je ne m'attendais pas à ce que cette porte s'ouvre 
    dans ce sens-là."
```

I have this error:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 7, in script call
    call acte0
  File "game/scripts/acte0/acte0.rpy", line 15, in script call
    call acte0_scene5
  File "game/scripts/acte0/acte0_scene5.rpy", line 10, in script
    maecenas surprise "Ah. Vraiment désolé, je ne vous avais pas vu Monsieur."
Exception: Say has image attributes ('surprise',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 7, in script call
    call acte0
  File "game/scripts/acte0/acte0.rpy", line 15, in script call
    call acte0_scene5
  File "game/scripts/acte0/acte0_scene5.rpy", line 10, in script
    maecenas surprise "Ah. Vraiment désolé, je ne vous avais pas vu Monsieur."
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\character.py", line 1290, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\character.py", line 1109, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\character.py", line 1035, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('surprise',), but there's no image tag associated with the speaking character.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Les aventures de Luin 1.0
Mon Oct  2 10:21:34 2023
```

However, I defined my character "maecenas.rpy" as follows:
```renpy
define maecenas_name = "???"
define maecenas = Character("maecenas_name", color="#fd0202", image="character_maecenas", dynamic=True)
```

So, I decide to investigate in the console to show what it is put in my maecenas character, and I discover this:
![image](https://github.com/renpy/renpy/assets/27765452/7b2736ed-4a9c-4b1b-b699-2c292c92dfef)
![image](https://github.com/renpy/renpy/assets/27765452/ddd3aec9-df82-427c-ab90-443a63cae756)

And if I put in the console `maecenas.image_tag = "character_maecenas"`, it is worked.

I precise my images are in a sub-folder of images with of course images, like this:
![image](https://github.com/renpy/renpy/assets/27765452/e6331436-8f77-46d2-99cd-6c5e6ac3e33a)

Hope it is help.
If isn't a bug, sorry, but I don't know how to fix.

**Comment by Gouvernathor** [comment]
You're probably erasing the `maecenas` variable in some way.
To see when it may happen, you can open the console, type `watch maecenas` and/or `watch maecenas.dynamic`, and see when it changes.

**Comment by m-from-space** [comment]
`define maecenas_name = "???"`

Sidenote: If you want your character name change to actually be saved, you should use "default" here.

**Comment by Quarior** [comment]
> You're probably erasing/replacing the `maecenas` variable in some way. To see when it may happen, you can open the console, type `watch maecenas` and/or `watch maecenas.dynamic`, and see when it changes.
Oh my gosh. They was a old compiled file (rpyc) of a file (rpy) I deleted, but he stayed with the project. In the Visual Studio Code view, it wasn't displayed.

I look like a idiot. Very thanks you.



> `define maecenas_name = "???"`
> 
> Sidenote: If you want your character name change to actually be saved, you should use "default" here.

Thanks you. I change to default.
