### ISSUE TITLE
New keymap not taken account by renpy.input, issue or intended?

### ISSUE THREAD

**Issue by bober-gith** [renpy/renpy#5032]
Previously, I was using things for example key 'l' and key 'L' to open the load menu, at one point there was a change where those things stopped working and I changed them to key 'K_l', this was actually a welcome change because it reduced the need to use one uppercase and lowercase version of the key. I believe that was reverted, but I kept the change since it seemed a bit better. 
However, "K_l" (and other keys like that) are not being blocked during renpy.input, if you try to enter a name with a 'L' in it it will open the load menu whereas key 'L'/key 'l' will not.

Edit: if that's an issue, maybe a way to specify what to block, certain specific keymap during renpy.input could be the way, because there is a world where you want certain keymaps to still be usable during ren'py input (probably not gonna be letters ones though).

**Comment by renpytom** [comment]
This is probably intended. As long as the keymap is above the input, then it'll take priority over the input. If you want it not to be blocked, put the keymap underneath the input.

**Comment by bober-gith** [comment]
Thanks. For some reason, the previous keymap didn't need to be placed above the input screen which threw me off but that makes more sense actually.
