### ISSUE TITLE
_greedy_rollback variable does not seem to work

### ISSUE THREAD

**Issue by bober-gith** [renpy/renpy#5035]
Wanted to bring back the old rollback on load because the greedy rollback creates some visual glitch on a project but putting 
using _greedy_rollback = False does not change it back (https://www.renpy.org/doc/html/store_variables.html#var-_greedy_rollback).

**Comment by renpytom** [comment]
What version are you on. I recall that it didn't work, but I fixed it recently. (But I could be wrong.)

**Comment by bober-gith** [comment]
On this version: ![image](https://github.com/renpy/renpy/assets/78823063/3eaf4a8d-a8e2-4ae2-a1bf-297b0229bcd1)
Reverted the commit shortly in Ren'py after this github post, I think it puts it always True regardless of the variable but maybe something is off with my project or my ren'py version, no idea.
in rollback.py right now:
```
        # Now, rollback to an acceptable point.

        greedy = renpy.session.pop("_greedy_rollback", True)
        self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
```
Then changed it to greedy = renpy.session.pop("_greedy_rollback", False) to fix it. If it's working for you, then please dismiss it, I thought it was still an issue.

Have to say, the previous behavior seems more proper and corresponds to the screenshot in the save slot (especially during autosave), the new behavior can awkwardly throw you back a bit in time, in the middle of a transition that is already finished and doesn't correspond to the screenshot of the save, it also creates visual issues sometimes.
