### ISSUE TITLE
Renpy 8.1.4.23092301+nightly: Web on MacBook Air M1: Problems with fullscreen

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5038]
Hi, I'm testing my Web game on a MacBook Air M1 and I noticed 3 problems with fullscreen.

I recorded my screen and shared it here: https://mega.nz/file/AahzXC7I#XV8UIFEDsQ6ZKgJ1H8HTt2lmnq-QmHRsKPTgSpLjf74

Problem 1:
1) Safari is in window mode.
2) I enter fullscreen and the game exists fullscreen immediately.
3) I have to enter fullscreen again to finally enter fullscreen.

Problem 2:
1) Safari is in fullscreen mode
2) I click the fullscreen button.
3) My view is moved to the desktop.
4) I click Safari Icon and the fullscreen button is not enabled.

Problem 3 (not on video):

The input name box does not work correctly when the game is in fullscreen
```
$ persistent.name = renpy.input(
                                _("What is your name?"),
                                length=32)
```
The game exits fullscreen, but the input text box doesn't show up.

The game works correctly in window mode.

Workaround: Would it be possible to detect if the web version is running on a Mac so I can hide the fullscreen button?

**Comment by renpytom** [comment]
1 and 2 seem fixed.

**Comment by Kassy2048** [comment]
For 3, it would probably be better to put the canvas and input div inside a same div and set this parent div as the fullscreen element instead of just the canvas, so that we won't have to leave fullscreen mode to show the input div.

Nice catch on visibilitychange btw 👍

**Comment by renpytom** [comment]
I've disabled fullscreen on Safari, as I simply can't get it working reliably on macOS.
