### ISSUE TITLE
Greedy rollback on load causes saves with suspended rollback to step backwards

### ISSUE THREAD

**Issue by mal** [renpy/renpy#5040]
Possible regression related to greedy rollback on load changes. Might also be intentional, but player experience wise it doesn't _feel_ right. 🤷

May be related to #5035.

<details><summary>Reproduction</summary>

```rpy
label main_menu:
    $ _confirm_quit = False
    return

label start:
    "1"
    "2"
    $ renpy.suspend_rollback(True)
    "3"
    "4 - Save, then load.\nOn 8.1.1 this works as expected, in 8.1.3 the load takes you back to line 3."
    $ renpy.suspend_rollback(False)
    "5"
    "End."
    return
```
</details>

Issue still exists as of `8.2.0.23100601+nightly`.

**Comment by bober-gith** [comment]
This is I think the exact scenario where it happened for me too (with renpy.suspend_rollback()).

$ renpy.suspend_rollback(True)
/long transition that introduces a new day
/autosave
$ renpy.suspend_rollback(False)
show sunshine_image
n "A new day has come."

autosave screenshot is showing: sunshine_image

Click on it before greedy rollback on load, end up at:
n "A new day has come."

Click on it after greedy rollback on load, end up at:
In the middle of the long transition that introduces the new day + UI is showing and bugged (it should be hidden during this transition). Doesn't correspond to the screenshot.
