### ISSUE TITLE
Can't include Itch App Manifest (or other hidden files) in Build

### ISSUE THREAD

**Issue by lunarcloud** [renpy/renpy#5041]
This doesn't work:
```py
    build.classify('.itch.toml', 'all')
```
But this works:
```py
    build.classify('anythingelse.toml', 'all')
```

Makes me thing there's an issue with including files that start with a dot?

**Comment by the66F95** [comment]
that's the expected behavior if the default entry in options.rpy `build.classify('**/.**', None)` is still executed before your line.

**Comment by renpytom** [comment]
I'm going to fix this, at least having a way of putting your stuff before the default entries.

**Comment by mal** [comment]
Isn't the section in the [`gui/game/options.rpy`](https://github.com/renpy/renpy/blob/master/gui/game/options.rpy#L185) template (the one meant for creators to customize) already that?

**Comment by the66F95** [comment]
he just have to move the default entry to exclude dotfiles behind his custom entry. 🤷
as @mal said, isn't that part of options.rpy meant to be the place to configure your build process or a template to create your own section/script.

**Comment by renpytom** [comment]
Specifically, you want to change, in options.rpy:

```renpy
    build.classify('**~', None)
    build.classify('**.bak', None)
    build.classify('**/.**', None)
    build.classify('**/#**', None)
    build.classify('**/thumbs.db', None)
```
to

```renpy
   
    build.classify('.itch.toml', 'all')
    build.classify('**~', None)
    build.classify('**.bak', None)
    build.classify('**/.**', None)
    build.classify('**/#**', None)
    build.classify('**/thumbs.db', None)
```

This should work in all recent versions of Ren'Py.

**Comment by renpytom** [comment]
Closing this as resolved.
