### ISSUE TITLE
Renpy 8.1.4.23092301+nightly WEB:  action OpenURL() on iPad, Mac, iPhone is blocked by browser

### ISSUE THREAD

**Issue by SergioAlonsoJr** [renpy/renpy#5042]
[OpenURL](https://www.renpy.org/doc/html/screen_actions.html#OpenURL) opens URLs correctly on Windows and Android, but on iPad, iPhone and Mac, these URLs are blocked by Safari and Chrome as unwanted popups 

How to work around this situation?

**Comment by renpytom** [comment]
Convince the user to accept the popup.
