### ISSUE TITLE
Allow `Layer`s to be rendered at full size-

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#5044]
-(the size given by config.layer_clipping), and not at its parent's size.

say you have the following:
```rpy
fixed:
    xysize (803, 389) # totally random numbers :clueless:

    add Layer("some_detached_layer", clipping=False):
        at transform:
            ysize 1.0 fit "contain" xalign 0.5
```
you want the layer to fit the container vertically and it to be centered. currently this is only possible through creating a subclass of `Layer` that calls its render method with `config.screen_width` and `config.screen_height` as available sizes.

**Comment by mal** [comment]
Looking into this, but in the mean time be aware that the values in `config.layer_clipping` and clipping as it pertains to displayables (which is the keyword argument on the `Layer` displayable) are not the same thing. A layer with an entry in `config.layer_clipping` will always be clipped, irrespective of the argument given to a `Layer` displayable presenting it - it's clipped long before it arrives. Meanwhile a layer without such an entry is not clipped by default, and so a `Layer` displayable can choose whether or not to clip it within its (the displayables) bounds.

**Comment by mal** [comment]
This already appears to work as you want when a `layer_clipping` entry is provided? i.e.
```rpy
define config.layer_clipping['some_detached_layer'] = (0, 0, renpy.config.screen_width, renpy.config.screen_height)
```

**Comment by mal** [comment]
That was written long before detached layers and the Layer displayable were introduced and hasn't been updated. I'll see if we can improve the docs there, but essentially:

By default (and intentionally) layers displayed by a Layer displayable are not bounded by the screen like normal layers, their default "layer clipping" effectively comes from the bounds of the Layer displayable containing them, allowing things on that layer to be laid out at normal resolution but relative to those bounds.

The behaviour you're seeking is to have a detached layer behave as if it had set bounds, then scale/resize to fit the bounds of the Layer displayable, for which concrete bounds are required. The `config.layer_clipping` map is the way to achieve this.
