### ISSUE TITLE
Documentation Update for Image Manipulators

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#5047]
On the IM page ( https://www.renpy.org/doc/html/im.html ) there is the following text:

> With the few exceptions listed below, the use of image manipulators is historic. A number of image manipulators that had been documented in the past should no longer be used, as they suffer from inherent problems. In any case except for im.Data, the [Transform()](https://www.renpy.org/doc/html/trans_trans_python.html#Transform) displayable provides similar functionality in a more general manner, while fixing the problems.

Is there any chance we could have this put into a similar style as the orange warning text seen here ( https://www.renpy.org/doc/html/statement_equivalents.html#dialogue) so as to draw one's eye to it more?

**Comment by Gouvernathor** [comment]
Yes using `.. warning:` or red using `.. error:`, I'll see that tonight.
