### ISSUE TITLE
Mipmap as a Transform property arg

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5048]
One of the biggest problems with resizing images is that it doesn't look near as good as to the image manipulador counterpart. Everything looks jagged when its too small. However, using im has many problems because it's depreciated. I've seen this issue raised by several people. I suggest using the same solution as with Movie or Text where this is not an issue. You can use a movie as a thumbnail and it looks good when setting mipmap to true, the same with text. Great additions!

Imo a depreciated function should not be more visually pleasing than the recommended. I still use it whenever I can just for that reason.

**Comment by Gouvernathor** [comment]
mipmap is a position style property, which means it can be taken by any displayable. Transform is a displayable.
So, I didn't test it but you should be able to pass it as a kwarg and it should work.

**Comment by renpytom** [comment]
Do you have some examples of this? Mipmapping should be used by images by default. 

Can you hit shift+G, and make sure you're using the gl2 renderer? Mipmapping was added there.

**Comment by renpytom** [comment]
Closing this, but feel free to re-open if there's still a problem.
