### ISSUE TITLE
Name not displaying like it should

### ISSUE THREAD

**Issue by ifitmakesyoushush** [renpy/renpy#5049]
Here's my code:

show text "Welcome, NEW USER"
        pause 2.0
        label f:
            show text "Please enter the first letter of your first name."
            $ persistent.f = renpy.input("", allow="ABCDEFGHIJKLMNOPQRSTUVWXYZ", length=1)
            if persistent.f == "":
                show text "Invalid input. Please retry."
                pause 2.0
                jump f
        label l:
            show text "Please enter the first letter of your last name."
            $ persistent.l = renpy.input("", allow="ABCDEFGHIJKLMNOPQRSTUVWXYZ", length=1)
            if persistent.l == "":
                show text "Invalid input. Please retry."
                pause 2.0
                jump l
        $ persistent.a = renpy.random.randint(0, 9)
        $ persistent.b = renpy.random.randint(0, 9)
        $ persistent.c = renpy.random.randint(0, 9)
        $ persistent.u = "[persistent.f][persistent.l]-[persistent.a][persistent.b][persistent.c]"
        show text "Your username is: [persistent.u].\nDo not lose this information."

When I try to run it, it shows up as "Your username is: [persistent.f][persistent.l]-[persistent.a][persistent.b][persistent.c].\nDo not lose this information."

Am I doing it wrong? Is there a way to make it say (for example) "HW-926" instead of the labels?
(I would also like to add that the indents are correct but Github isn't showing them.)

**Comment by Gouvernathor** [comment]
See the [related documentation](https://nightly.renpy.org/doc/text.html#interpolating-data), and in particular the `!i` flag, which enables interpolation inside the interpolated string itself. Otherwise the interpolation is done just once and the result is displayed even if it contains square brackets. It's intended behavior.

**Comment by renpytom** [comment]
Most notably, it's very weird to put interpolation in the data that goes into persistent. You might want to rethink what's going on here.

**Comment by ifitmakesyoushush** [comment]
Good point
