### ISSUE TITLE
Expanding capabilities for alt text.

### ISSUE THREAD

**Issue by feltcute** [renpy/renpy#5054]
I am currently trying to expand the accessibility of a project with text to speech support, though I've found some rather difficult challenges to surpass, either incredibly arduous conditional screen variables everywhere prior to every `alt` with interpolation, or just not possible from what I could find.

Three particular topics of expansion of the typical `alt` stood out to me.

## Alt property variances, `hover_alt`, `selected_alt`, etc.

Currently, you have to use lots of conditionals to decide the exact alt text for something. This is rather time consuming and error prone to do with conditional checks via screen variables and interpolation, and in some edge cases, impossible to properly do. Trying to make good use of [Action classes](https://www.renpy.org/doc/html/screen_python.html#Action) stand out.

What I see as the most important feature I'd like to mention in this issue is being able to specify alt variances based on the UI element's state, particularly to use in styles where the `alt` isn't replaced, but added to through the critical use of new `prepend` and `append` modifiers:

```renpy
style equipment_radio_button:
    hover_alt "equip" prepend # would the syntax for a modifier need to be a string?
    selected_hover_alt "unequip" prepend
style visual_settings_check_button:
    selected_alt "on" append
    unselected_alt "off" append
```

```renpy
   # Equipment text button or other alt-able element:
       style equipment_radio_button # Prepended with "equip/unequip" through `hover_alt` and `selected_hover_alt`
       alt "Shiny Helmet"
```

Whereas alt would have no use for `prepend` and `append` modifiers.

Worthy of note, specifying `selected_alt` would have to override the default use of "selected", which is what started me on this journey after finding no way to manually adjust it, as in some cases isn't quite accurate to what a button is doing. Notably, I'd like to adjust the check button for the project I'm working on to say "enabled" or "on" instead for things like VFX preference `ToggleVariable()`s, and to explicitly state whether it is "disabled" or "off" through `unselected_alt`.

An overview of alt variances I'd see as useful:
- hover_alt
- selected_hover_alt
- selected_alt
- unselected_alt (unselected would be a new term, I don't see any existing terms for properties that fit?)

Sensitivity related properties seems irrelevant as it typically automatically blocks keyboard input. 

## entered_alt

I'd like to be able to state `entered_alt` on any UI element capable of taking children that activates once, and can only be activated again when leaving the UI element and its children, or through a child ui element with its own `entered_alt`, taking first-served order priority over any other `alt`s.
Example:
```renpy
    vbox:
        label _("Purchase Weapon")
        grid _ _:
            entered_alt "Purchase weapon. " prepend
            # etc...
        label _("Purchase Protection")
        grid _ _:
            entered_alt "Purchase protection. " prepend
            # etc...
```

This is useful for an easy-to-implement communication of switching context from one group of ui elements to another.

There is an argument for something like this being redesigned on separate screens through tabs to help better enable text to speech, though the project I am working on already has a large portion of its UI set in stone, and the UI artist long gone. It's no small feat to redo and risk whether it will still be overall as good as before for users not using text to speech, whereas `entered_alt` would be applicable to many existing interfaces and have general usefulness.

## controls_alt keysym

While exploring [this article](https://www.readspeaker.com/blog/video-game-accessibility/), I came across a video where an inventory menu explains the behavior and button, directly on the item hovered.

This general concept seemed immediately useful to me to enable discovery-centric methods of explaining controls, if for simplicity sake as something binded to a keysym rather than complex 'remembering' behavior per the video.

```renpy
style inventory_weapon_button:
        controls_alt "Press space to view weapon passive description. Press c to compare to your equipped weapon. Press enter to toggle equip."
```

By default, perhaps `K_QUESTION` as the keysym? [It doesn't seem to be in use.](https://www.renpy.org/doc/html/keymap.html)

This seems very complementary to any explanation on a game's help/controls menu, particularly when a game starts implementing more complex interfaces with various points of information available to communicate, such as often found in RPGs.

**Comment by mal** [comment]
I'd suggest looking into the `alt` property of `Action` classes, and the special `[text]` interpolation value. They may not solve all the cases you've listed here, but they definitely make a dent.

**Comment by feltcute** [comment]
> I'd suggest looking into the `alt` property of `Action` classes, and the special `[text]` interpolation value. They may not solve all the cases you've listed here, but they definitely make a dent.

Is that something to research via the Ren'Py source code? I saw no mention of alt on the [Action class documentation](https://www.renpy.org/doc/html/screen_python.html#Action).

**Comment by MiiNiPaa** [comment]
There is a mention of this in [self-voicing](https://www.renpy.org/doc/html/self_voicing.html)

> **Alternative text**
>
>    Alternative text is supplied by a displayable's [alt](https://www.renpy.org/doc/html/style_properties.html#style-property-alt) style property. _It can also be supplied by actions supplied to buttons and values supplied to bars._ Explicitly supplied alternative takes precedence over text supplied by actions or values, and both take precedence over text extracted from Text displayables.

Not very useful, since it does not explain how to use it, nor it provides an example.

**Comment by renpytom** [comment]
I've spent some time looking at this today. 

I don't think entered_alt can happen. The portions of Ren'Py that deal with focus don't really understand the hierarchy of displayables, and I don't think that's something that can change any time soon - and so that one is out. 

The hover_alt property doesn't make any sense - the only time when alt text will be read out is when the displayable is in the hovered state. Right now, every time Ren'Py reads alt text, it's really reading the hover_alt property - it's just that since it's always there, there's no point in making it obvious. 

The selected_alt property works now. However, selected_alt on a button will say "selected" after the text. I've changed that so that it will no longer say "selected" if the selected_alt text is different from the normal/hover alt text. 

I am leaning towards an "extra_alt" property - perhaps bound to ? - that will cause the tts system to read extra text associated with the current displayable, if it exists. (This would be a renamed version of controls_alt.)

**Comment by renpytom** [comment]
I've also added documentation for the alt property of Bar and Button.

**Comment by feltcute** [comment]
Thanks for giving this a look.

> I don't think entered_alt can happen. The portions of Ren'Py that deal with focus don't really understand the hierarchy of displayables, and I don't think that's something that can change any time soon - and so that one is out.

Understandable. Perhaps something can be explored with a manual tagging feature for general keyboard/gamepad behavior independent of mouse/touch focus, but that is well beyond the scope of this issue.

> The hover_alt property doesn't make any sense - the only time when alt text will be read out is when the displayable is in the hovered state. Right now, every time Ren'Py reads alt text, it's really reading the hover_alt property - it's just that since it's always there, there's no point in making it obvious.

In hindsight, I didn't do a good job thinking the properties out. What I really wanted out of it was prepending and appending properties for `alt` and and `alt_selected` that could be cleanly controlled through styles, though I understand it may be considered rather extra.

> The selected_alt property works now. However, selected_alt on a button will say "selected" after the text. I've changed that so that it will no longer say "selected" if the selected_alt text is different from the normal/hover alt text.

Ah, it does, perfect. And thanks for addressing its behavior limit, that and the lack of documentation were major roadblocks in learning that. In the recent commits you did, I don't see `selected_alt` as [documented](https://github.com/renpy/renpy/blob/master/sphinx/source/style_properties.rst) so that it can be found by search? Would a documentation PR from me be a good idea to get my feet wet to address this?

> I am leaning towards an "extra_alt" property - perhaps bound to ? - that will cause the tts system to read extra text associated with the current displayable, if it exists. (This would be a renamed version of controls_alt.)

This would be most desired, it'd streamline a lot of difficulties with explaining the controls if various elements for the project I am working on. `extra_alt` sounds good to me as a more flexible name for its potential uses.

**Comment by feltcute** [comment]
> In the recent commits you did, I don't see selected_alt as [documented](https://github.com/renpy/renpy/blob/master/sphinx/source/style_properties.rst) so that it can be found by search? Would a documentation PR from me be a good idea to get my feet wet to address this?

... Ah, this seems to be from the assumption that people know [this section](https://www.renpy.org/doc/html/style_properties.html#style-property-prefixes) applies to everything on the page, including alt?

I had difficulty proving this through SensitiveIf() and `insensitive_alt`, but `selected_alt` went fine.

**Comment by renpytom** [comment]
Correct. 

insensitive_alt doesn't make sense. Insensitive text can't be focused, and so the self voicing will never read it out.

**Comment by renpytom** [comment]
I've added group_alt (your entered_alt), and extra_alt (your controls_alt). 

Both are implemented in such a way that they can be set in a displayable, and will be shared by all children. 

```renpy
screen test():
     vbox:
           group_alt "Test choices"
           extra_alt "You can pick any one of these, it doesn't matter." 
           
           textbutton "A" action Return("A")
           textbutton "B" action Return("B")
           textbutton "C" action Return("C")
```

If you focus A, it will say "Test choices: A". If you then move to B, self-voicing will say "B". And when ? is pressed, "You can pick any one..." will be spoken. 

The prepend is possible using [text] inside the alt property of the button, so I think this one is done.

**Comment by feltcute** [comment]
Ooo, glad you found a solution for making `group_alt` a thing. Thank you for adding these!
