### ISSUE TITLE
Possible to start renios manually

### ISSUE THREAD

**Issue by Longtianmu** [renpy/renpy#5056]
I saw a method in official SDL that:
```SDL_SetMainReady();
SDL_iOSSetEventPump(SDL_TRUE);
SDL_main(argc, argv);
SDL_iOSSetEventPump(SDL_FALSE);
```
Could I use these functions by using renios default build?
Or should I build it by myself?

**Comment by renpytom** [comment]
I'm not sure what you're asking here. You should be able to use Ren'Py to create an iOS project, that you can then use Xcode to build and run on your device. The built project should contain a call to SDL_main.

**Comment by Longtianmu** [comment]
Well I'm just trying to write an app which could run any renpy game by adding games directory into it manually.
That requires a manually setup step.

**Comment by wbrambley** [comment]
Good luck with that, if you can get it published in the istore it's a good work around for people unable to play the games they want on iPhone.
I played around with something similar for Android some time back, the problems I encountered were RenPy versions compatibility and vast differences in game formats i.e. when start labels are RPA file. I should get back to it when I have time.

**Comment by renpytom** [comment]
You can probably have Ren'Py start normally, and replace path_to_game in renpy.py with something that finds the game. I can't really support something like this, however, at least in terms of answering how to make it work. You'll need to figure it out yourself if you want to make the project.

**Comment by HorBro38** [comment]
> Good luck with that, if you can get it published in the istore it's a good work around for people unable to play the games they want on iPhone.
> I played around with something similar for Android some time back, the problems I encountered were RenPy versions compatibility and vast differences in game formats i.e. when start labels are RPA file. I should get back to it when I have time.

Apple wouldn't allow this in the store, they don't allow you to compile applications at run time like this.  And as Tom alluded too, it has questionable legality when it comes to redistributing other's projects.

**Comment by wbrambley** [comment]
> > Good luck with that, if you can get it published in the istore it's a good work around for people unable to play the games they want on iPhone.
> > I played around with something similar for Android some time back, the problems I encountered were RenPy versions compatibility and vast differences in game formats i.e. when start labels are RPA file. I should get back to it when I have time.
> 
> Apple wouldn't allow this in the store, they don't allow you to compile applications at run time like this. And as Tom alluded too, it has questionable legality when it comes to redistributing other's projects.
There would be no distribution, only a more or less blank project. Game files would be acquired by the user.
Now legality depends on the licencing structure. If the user purchased a game on pc and said licence for use covers other platforms I can't see the problem with copying the game folder  into a mobile app's search path and run it from there?
There's a lot of reasonably popular NSFW games created in RenPy and no way they'd be allowed in the respective platform's store.

**Comment by Longtianmu** [comment]
Anyway I have done it.
By hooking into SDL, the app could work without ReCompile or something else magic.
Sideload is an effective way to install it.
