### ISSUE TITLE
How to handle names in dialogue when using the character store?

### ISSUE THREAD

**Issue by micka190** [renpy/renpy#5060]
When using the [character store](https://www.renpy.org/doc/html/dialogue.html#the-character-store), what is the intended approach to using names in the `say` screen?

Assuming I have the following code:

```rpy
define character.bob = Character("Bob")

default bob = StatTracker()

label demo:
    # Uses store for speaker
    bob "The speaker/who's name will correctly show 'Bob', because the character store is used."

    # Uses tracker class for properties
    bob "Here's some arbitrary bit of data: [bob.arbitrary_data]."

    # Does NOT use the store first when stringifying it, though
    "Unfortunately, using [bob] does not show Bob's name, because it will __str__() the tracker class."

    # Will work, but is kind of long
    "Using [character.bob] works, but it seems weird since the speaker/who is handled automatically for us."
```

Is there a way to make the `say` screen use the `character` store by default when interpolating variables that appear in the actual dialogue itself? The speaker's name seems to be handled by Ren'Py itself via the "who" id.

I've found that one way to handle this is to provide a `__str__()` implementation to the `StatTracker` class, but then I lose out on other features like dynamic characters. Or rather, I haven't gotten those to work yet. I'm guessing I'd need to do some weird string tag wrapper inside the `__str__()` method to spit-out something the `say` screen could properly interpolate.

Is the only solution to not use the `character` store and just use different variable names to disambiguate them when interpolating? If so, the feature seems a bit pointless beyond the simplest of usecases. Maybe I'm just using Ren'Py wrong and people just use the full `[character.bob]` in their dialogue to get around it?

**Comment by Gouvernathor** [comment]
> in the `say` label

There is no `say` [label](https://renpy.org/doc/html/label.html).

Your code works as intended : you access the character object using `character.bob` and the StatTracker object using `bob`. If we were to have `[bob]` be resolved as `[character.bob]`, there would be no way for you to access the StatTracker object, as it would be shadowed by the `character` store.
A good example of this is found [here](https://nightly.renpy.org/doc/dialogue.html#the-character-store).

> Maybe people just use the full [character.bob] in their dialogue to get around it?

Yes. Which allows you to use both dynamic characters, and whatever you want to store besides it. If typing `character.` is too verbose for you, then yes, use different variable names. That's how the `character` store is meant to work, if it doesn't fit your use case for some reason, that's all right.

**Comment by micka190** [comment]
> There is no say [label](https://renpy.org/doc/html/label.html).

Ah yeah, my bad. I meant the `say` screen. Edited the main post.

> If we were to have [bob] be resolved as [character.bob], there would be no way for you to access the StatTracker object, as it would be shadowed by the character store.

I'll admit I'm a bit confused about how it works for the speaker, then. Because, using my example in the OP, the following code is able to automatically distinguish between the `character` store and the tracker class:

```rpy
label demo_speaker:
    bob "This uses the character store for the speaker."
    bob.arbitrary_data "This uses the tracker instance's property for the speaker."
```

So there seems to be *something* the checks the store first, and then checks the global scope afterwards.

Would've been nice if the actual dialogue itself did the same thing, since I'm pretty sure the use case for the `character` store was so that we could re-use variable names for the `Character` classes and their corresponding state-tracking object.

I'd be pretty surprised if someone using `[bob]` inside their dialogue would *want* it to call `__str__()` on the tracker class over showing the name of the `Character` instance, since that's different than using `[bob.property]` (especially since the speaker code seems to do just that).

**Comment by Gouvernathor** [comment]
> So there seems to be something the checks the store first, and then checks the global scope afterwards.

Yes, that's specific for the speaker part of the say statement (the "who", if you will). What it does is trying to find what you wrote inside the `character` store, and _if_ it fails, to try again in the general store. But it does so specifically because the `character` substore is made to contain speakers (Character objects), and the purpose of a speaker is to speak, not to be mentioned in a dialogue.
Using `[char]` to display a character's name in dialogue on the other hand, that's not what characters are _for_ and it's not even documented, so there's no reason to facilitate that use case - especially if it hampers other uses of interpolation.

Also, interpolation is not only for dialogue but also for text in screens in general (that's even how it's implemented, I think). Wouldn't it seem very weird to you that `text "[pop]"` in a random screen would seek the character substore in priority ?

**Comment by micka190** [comment]
> that's not what characters are for and it's not even documented

Are you referring to the `character` store here, or the `Character` class? Because I was under the impression that using instances of `Character`s directly in dialogue was intended (but I may be wrong). Not disagreeing on the fact it's undocumented if you meant the store, though.

> Also, interpolation is not only for dialogue but also for text in screens in general (that's even how it's implemented, I think). 

Yeah, I just figured since it's implemented differently for "who", it might be possible to make it work for "what" as well.

> Wouldn't it seem very weird to you that text "[pop]" in a random screen would seek the character substore in priority ?

Personally? If `[pop]` was a variable inside the `character` store, I wouldn't *really* find it weird (especially if it was documented). Though I'm not really annoyed by having to specify `character.pop` in screens. Just in the `say` screen's dialogue.

**Comment by MiiNiPaa** [comment]
> > that's not what characters are for and it's not even documented
> 
> Are you referring to the `character` store here, or the `Character` class? Because I was under the impression that using instances of `Character`s directly in dialogue was intended (but I may be wrong). Not disagreeing on the fact it's undocumented if you meant the store, though.

`Character` class. I am pretty sure it has `__str__` (which is used by interpolation) only for debug reasons (so it would show nicely in console)

> > Also, interpolation is not only for dialogue but also for text in screens in general (that's even how it's implemented, I think).
> 
> Yeah, I just figured since it's implemented differently for "who", it might be possible to make it work for "what" as well.

`who` is produced by character class itself. It does not need to know in which store (or stores) it is stored, because everything is kept within object itself,
 
> > Wouldn't it seem very weird to you that text "[pop]" in a random screen would seek the character substore in priority ?
> 
> Personally? If `[pop]` was a variable inside the `character` store, I wouldn't _really_ find it weird (especially if the behavior was documented). Though I'm not really annoyed by having to specify `character.pop` in screens. Just in the `say` screen's dialogue.

Just for fun: according to #5008 we will have an `interpolation` store which would be checked before global store when interpolating variables, like `character` store is checked for characters.

**Comment by micka190** [comment]
> Character class. I am pretty sure it has __str__ (which is used by interpolation) only for debug reasons (so it would show nicely in console)

Uh. I guess I just kind of discovered that it works and just forgot it wasn't the official way of doing it.

This changes a lot 😅

> Just for fun: according to #5008 we will have an interpolation store which would be checked before global store when interpolating variables, like character store is checked for characters.

Ooh, that looks like exactly like what I wanted. I'll keep an eye on it. Thanks!

Gonna close the issue, since my question has been answered at this point.
