### ISSUE TITLE
Seemingly random AVIF files fail to display

### ISSUE THREAD

**Issue by juniorthejunior** [renpy/renpy#5061]
I am experimenting with encoding my images to AV1, and I am running into an error when displaying some of the encoded AVIF files in Ren'Py.

I am using pretty much the same FFmpeg command on a series of files; some of them display fine in Ren'Py, while other, seemingly random ones, throw the following error when displayed:
```
Exception: Could not load image 'corrupt.avif': error("Couldn't get AVIF image: 11")
```

I am using av1_nvenc, and the following command:
```
ffmpeg -i "input.jpg" -c:v av1_nvenc -preset slow -cq 20 -multipass 2 -vf "smartblur=lr=1.0:ls=0.0:lt=0:cr=1.0:cs=0.0:ct=0,hwupload_cuda,scale_cuda=3840:2160:format=yuv420p" "output.avif"
```
(This is the same command used for all images except for the `scale_cuda` argument, as I was running into some errors with FFmpeg and had to manually specify the dimensions here to fix them; you might have to do so as well during your testing.)

I have used FFprobe and MediaInfo to compare the files that do and do not display, both before the encoding and after, and (to my untrained eyes) they seemed identical save for the dimensions and sizes. The erroneous files also display fine elsewhere (Windows, Photoshop, and OperaGX). The erroneous files also seem to vary in dimensions and file size - I couldn't spot any obvious pattern going on there.

Full traceback:
[traceback.txt](https://github.com/renpy/renpy/files/12938704/traceback.txt)

File that works (`scale_cuda=3840:2160`):
![works](https://github.com/renpy/renpy/assets/144063178/343750ce-2b5c-4ff3-b3cf-831424dc4274)

File that does not work (`scale_cuda=1920:775`):
![corrupt](https://github.com/renpy/renpy/assets/144063178/050f50ab-b546-4245-b394-8a775a651495)

Another file that does not work (`scale_cuda=1209:678`):
![corrupt_2](https://github.com/renpy/renpy/assets/144063178/3feaad70-7a60-4274-9fbd-e0a507ac1f14)

**Comment by mal** [comment]
The error seems to originate from the AVIF library itself, where error code 11 (as seen in the exception message) maps to the message "Decoding of color planes failed". Based on that it seems likely to either be a bad encoding or a bug in the core AVIF library. I don't think this is (directly) a Ren'Py issue.

A separate issue is the poor error message, but I believe that's down to the version of SDL we use. The issue appears to have been addressed by https://github.com/libsdl-org/SDL_image/commit/45f2a322110cacd0a546291e08a15f108a302f10 but it's not clear to me if we can take advantage of that change without upgrading. A question for Tom.

**Comment by juniorthejunior** [comment]
> The error seems to originate from the AVIF library itself, where error code 11 (as seen in the exception message) maps to the message "Decoding of color planes failed". Based on that it seems likely to either be a bad encoding or a bug in the core AVIF library. I don't think this is (directly) a Ren'Py issue.
> 
> A separate issue is the poor error message, but I believe that's down to the version of SDL we use. The issue appears to have been addressed by [libsdl-org/SDL_image@45f2a32](https://github.com/libsdl-org/SDL_image/commit/45f2a322110cacd0a546291e08a15f108a302f10) but it's not clear to me if we can take advantage of that change without upgrading. A question for Tom.

I see. Thank you Mal. I actually ran some more experiments, and it seems to have something to do with the dimensions provided to `scale_cuda`; changing the "corrupt" images' output dimensions to something else allows them to be decoded successfully in Ren'Py; while changing the dimensions of the _working images to those of the corrupt ones,_ seems to result in error 11 as well. No idea what exactly may be going on there.

Should I open an issue with the AVIF library that you guys use, then? And if so, could you please point me to the correct repo? I took a look but I'm unsure which one it is the correct one! Much appreciated.

**Comment by renpytom** [comment]
Can you upload the actual AVIF files? Github has them as pngs or jpgs.

**Comment by juniorthejunior** [comment]
Sure (GitHub doesn't support uploading AVIF files, so here's a ZIP file):
[AVIF_images.zip](https://github.com/renpy/renpy/files/13063200/AVIF_images.zip)

As a bonus, I've also included the files that had their `scale_cuda` values swapped, which allows the corrupt one to now be displayed correctly, and the working one to throw error 11.

**Comment by renpytom** [comment]
So, turned out that the issue was that libyuv wasn't compiled in. It was used when certain kinds of scaling is going on - although I didn't actually run this one all the way down, my guess is that the compressed image and the output image can be of different sizes, and when that's the case, libyuv is used to scale them. 

The fix should be in tomorrow's nightly.
