### ISSUE TITLE
MusicRoom doesn't let you unpause on web

### ISSUE THREAD

**Issue by nomnomnami** [renpy/renpy#5065]
i made a music player intended for in-browser use, but if i use `mr.TogglePause()` it will pause the song but not resume playback when pressed a second time. it works normally on all other platforms.

my guess is that it doesn't want to look at the file or something, since i also noticed `renpy.music.get_duration(channel='music')` would freeze the game on web. maybe these bugs are related...? this happened using firefox btw!

**Comment by renpytom** [comment]
Just landed a fix for the get_duration problem. Not sure if it will fix musicroom - could you grab tomorrow's nightly fix build (October 31st's) and see if it solves it for you?
