### ISSUE TITLE
Quickload button crashing players to desktop

### ISSUE THREAD

**Issue by fishghost42** [renpy/renpy#5068]
I haven't been able to replicate this issue on my end, but I've been receiving several reports from players that pressing the quickload button crashes them to desktop without providing an error log. I've turned off the feature for the time being, but maybe worth investigating.

Build compiled in Ren'py 8.0.3

**Comment by fishghost42** [comment]
<img width="639" alt="Screenshot 2023-10-24 at 5 46 57 PM" src="https://github.com/renpy/renpy/assets/113782110/5a98fb5f-ca85-4e05-bb51-20419f22408c">
Hi Tom,

It looks like this wasn't an issue with quick load, but rather with the way the Steam overlay was interacting with the game. Attached a screengrab from our bug report thread. (And there's a link to that thread here: ([https://steamcommunity.com/app/1989270/discussions/0/3873717982252458009/?tscn=1698183837]))

**Comment by renpytom** [comment]
Ah. You probably need to contact valve on this one.
