### ISSUE TITLE
Unhovered event not being called

### ISSUE THREAD

**Issue by JeremyMiller** [renpy/renpy#507]
We have a map screen that shows different options when you hover over a location. These options appear in a modal to keep from conflicting with the map background, and we use a mousearea with a focus mask to tell when the user moves their mouse outside of the location. When they do, we hide the options so they can hover over other locations.

This works perfectly when mouse movement is slow, however when mouse movement is quick, the unhovered event is often not called, forcing the options menu to remain open until the user re-enters and re-exits the mousearea.

A commit where this problem can be viewed is here: https://github.com/Dischan/Dysfunctional-Systems-Ep2/tree/map_debug. To test, just start the game, go to New Story, test, and Show Map. There's no real way to reliably reproduce the bug, however if you move your mouse around the map rapidly you should notice it. It might be easier to trigger if the resolution is set to 576p.

The relevant code is located in game/ui_script/map/map_ui.rpy. Please let me know if you need any explanation of the code.

Thank you for your time.

**Comment by evilantishad0w** [comment]
404 on the example link.  Note that, if the background or hovered graphic has any full transparency (alpha = 255), hover and unhover may not trip properly.  I can't examine your graphics to check for that though.

**Comment by evilantishad0w** [comment]
Should probably be closed (though it'd be nice if the transparency problem were fixed).
