### ISSUE TITLE
Add check for non-self-closing text tags in Lint Options

### ISSUE THREAD

**Issue by brainos233** [renpy/renpy#5075]
As of https://github.com/renpy/renpy/commit/68e2cfb42054d78e250a31cd6cbf69cd6e01871f and #3926 , non-self-closing text tags are not considered an error in Lint. But since Lint options are now available, it might be possible to add checking non-self-closing in lint options so that type of error
```ren'py
"Plain {b}Bold {i}Bold-Italic should-be-Bold should-be-Plain"
```
can be recognized by Lint.

**Comment by renpytom** [comment]
That's not an error nowadays.

**Comment by brainos233** [comment]
> That's not an error nowadays.

I already know this, but I wish it would be added as a lint option, because sometimes I forget close text tags, and I can only find them with Ren'Py 8.0.3 Lint.
