### ISSUE TITLE
Movie: 'group' argument prevents 'image' from being used

### ISSUE THREAD

**Issue by PaulLl5** [renpy/renpy#5088]
When using the new 'group' argument for a Movie, image set for the Movie is ignored.

For example, a non-looped Movie:
`image kr_a11 = Movie(size=(2560, 1440), play="images/videos/kr_a11.webm", loop=False, group="anim", image="kr_130a")`

The expected behavior is that 'image' is shown after the Movie ends. When 'group' argument is present, that doesn't happen. Without it, it's shown as expected.

This doesn't seem obvious and either requires a fix or at least a notation in the documentation.

Ren'Py 8.1.3

Thank you!

**Comment by Gouvernathor** [comment]
Try the Nightly Fix version, 8.1.4 to have the last fixes and see if the bug is still there

**Comment by renpytom** [comment]
Fundamentally, the point of group is to prevent this behavior, and keep the last frame showing until the next movie in the group is ready. 

So don't use group.

**Comment by PaulLl5** [comment]
> Fundamentally, the point of group is to prevent this behavior, and keep the last frame showing until the next movie in the group is ready.
> 
> So don't use group.

Yeah, it's not an issue to not use group when image is used. But I think it'd be good to add a note to the documentation to avoid possible confusion on why this happens.

Thank you :)
