### ISSUE TITLE
NVL choice menu with nvl_menu: unwanted fading before and after choice

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5089]
This is the same issue as this one from 2020: https://lemmasoft.renai.us/forums/viewtopic.php?p=527890

On a new project, I use the NVL narrator with `define narrator = nvl_narrator` in script.rpy.

If I add a choice menu, it will appear alone on the screen, with the NVL box hidden. There, the fading defined in the default `config.window_hide_transition` and `config.window_show_transition` does make sense because we switch from the NVL box to this fullscreen, dramatic choice.

If, however, I follow https://www.renpy.org/doc/html/nvl_mode.html and set define menu = nvl_menu so I can display the choice menu right below the last piece of text (Choose-Your-Own-Adventure / IF-style), the NVL box will *still* try to disappear, before reappearing right away, together with the choice.

![Renpy 8 1 3 - NLV preserved text with menu causes fading](https://github.com/renpy/renpy/assets/1067772/86c54369-bdc7-4ea1-a23d-4bdb86630d5b)

I can avoid this by using

```rpy
init python:
    config.window_hide_transition = None
    config.window_show_transition = None
```

but then I will lose transitions I may want outside choice menus. A cleaner solution would be to remove the hide+show again NVL box entirely (and after the choice, the unnecessary re-show NVL box).

Repro code: add this to script.rpy

```rpy
# Use NVL narrator by default
define narrator = nvl_narrator

# Display the menus immediately after the current page of NVL-mode text (IF-style)
define menu = nvl_menu
```

**Comment by MiiNiPaa** [comment]
Either make window to not go away before menu by using `window show` statement (and `windows auto` afterwards if you need to restore auto-hiding functionality for other reasons), or remove menu statement from list of statements which cause window to hide:
```
init python:
    config.window_auto_hide.remove("menu")
```
