### ISSUE TITLE
keyboard_focus True error

### ISSUE THREAD

**Issue by benhamill** [renpy/renpy#509]
I'm running Arch Linux and was hoping to play around with Ren'Py. There's [a package for it in the Arch User Repository](https://aur.archlinux.org/packages/renpy-aio/) that seems to have the latest version. However, I can't get the editor to fire up. Behold:

```
● ~ ❱ renpy --version
Ren'Py 6.18.3.761
● ~ ❱ renpy

File "renpy/common/_errorhandling.rpym", line 99: style property keyboard_focus is not known.
    keyboard_focus True
                  ^
START /usr/bin/gvim -f "errors.txt"
● ~ 255❱ 
```

That `255` at the end is the exit code. I went trolling around in the source as installed on my machine and found several references to `keyboard_focus`. They looked to be the same as what's on Github and the release notes mention that this was added in 6.18.2. I'm not sure what else to check to see why it won't work on my machine.

Any advice?

**Comment by evilantishad0w** [comment]
Friend also stumbled on this problem, but for him it only seems to pop up when performing "force recompile".  The game appears to launch normally.

**Comment by renpytom** [comment]
It seems like the Ren'Py binary python modules may be out of date. Keyboard focus is a fairly new style property - if you were using old modules, you'd probably get this problem. I don't think this a bug in Ren'Py (or at least, I can't repeat it here).
