### ISSUE TITLE
Physical Images vs. coded image calls

### ISSUE THREAD

**Issue by N0lla** [renpy/renpy#5091]
Possbile development tool addition:
Is it possible to devise an extract from the coded ren'py program, which will call various images, etc. Then put that against the directory where the images are stored. That way a comparison can be done on either additional images that are in the directory or just named incorrectly and those that the program has called. As I noted that a number of problems that can either cause a rollback due to a missing image (or corrupted image - maybe add a checksum in the code so the code will skip over a corrupted image and not cause the program to break).

**Comment by renpytom** [comment]
I don't know what you're asking for here.

**Comment by Elckarow** [comment]
i think they wanna be able to turn a displayable render into an actual image and save it on the disk

**Comment by Elckarow** [comment]
which is already possible btw? it's just a lot of dark magic

**Comment by Gouvernathor** [comment]
IIRC this is about when a show statement calls an image which doesn't actually exist. That's checked in Lint, so satisfied.

**Comment by renpytom** [comment]
Closing this, as I don't see anything to do here.
