### ISSUE TITLE
Issue updating to Nightly from Launcher

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#5095]
The Nightly Fix (Ren’Py 8, Python3) build gets an error when attempting to update:
KeyError: ‘sums_url’

**Comment by lustfarmer** [comment]
I got same error when try to update me game on renpy 8.0.3 to renpy 8.2.0 
![image](https://github.com/renpy/renpy/assets/115584535/84a03dcf-46e8-49fa-a0bc-7ca49ad1618b)
