### ISSUE TITLE
About multithreading and context problems

### ISSUE THREAD

**Issue by ZYKsslm** [renpy/renpy#5105]
I'm a new developer of renpy so I don't use renpy expertly. And I met a serious problem that an error was occurred when I tried to use multithreading functions in renpy.

Here's my code:
```renpy
init python:

    import threading

    def func():
        # do any renpy functions
        renpy.say(e, "sub_thread_func")

    def subthread_func():
        # create a new thread to operate the func
        thread = threading.Thread(target=func)
        global thread
        thread.start()


define e = Character("艾琳")


label start:

    e "start"

    $ subthread_func()

    e "end"

    return
```

Here's the error:
```
Full traceback:
  File "game/script.rpy", line 25, in script
    e "end"
  File "F:\renpy-8.0.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "F:\renpy-8.0.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "F:\renpy-8.0.3-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "F:\renpy-8.0.3-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "F:\renpy-8.0.3-sdk\renpy\character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "F:\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "F:\renpy-8.0.3-sdk\renpy\display\core.py", line 3551, in interact
    raise Exception("Cannot start an interaction in the middle of an interaction, without creating a new context.")
Exception: Cannot start an interaction in the middle of an interaction, without creating a new context.
```

It seems that I need to create a new context, so how can I deal with that?

**Comment by renpytom** [comment]
In general, Ren'Py functions can only be run on the main thread. (The one exception is renpy.restart_interaction() ).

**Comment by ZYKsslm** [comment]
> In general, Ren'Py functions can only be run on the main thread. (The one exception is renpy.restart_interaction() ).

So whether there is a way to call renpy functions in the subthread but in the current context such as calling a screen?

**Comment by ZYKsslm** [comment]
I mean that I want not to block the main thread that renpy uses so I do some blocking operations in the subthread.

**Comment by renpytom** [comment]
So, you can certainly do that with things that you write (take a look at renpy.invoke_in_thread), but the functions that Ren'Py provides all assume that they will run on the main thread. There isn't a way around that - something like renpy.say assumes it's in the main thread, which (like in most gui environments) is the only one that can display things on the screen and process events. 

What are you trying to do? There are often equivalents that should work on properly - instead of time.sleep(), use renpy.pause(), which updates the interface as it 'sleeps'.

**Comment by ZYKsslm** [comment]
Thanks a lot, you have inspired me!
But how can I update the GUI after I update some data in the subthread?
And I thought a solution thanks to your tips.If there is a better way?

Here's my code:
```renpy
init python:

    import threading
    import time

    def func():
        # do some blocking functions
        state = False
        global state
        for i in range(5):
            print(i)
            time.sleep(1)

        state = True

    def subthread_func():
        # create a new thread to execute the func
        thread = threading.Thread(target=func)
        thread.daemon = True
        global thread
        thread.start()


define e = Character("艾琳")


label start:

    e "start"

    python:
        # prevent user to rollback because the func should be executed only once
        config.rollback_enabled = False
        subthread_func()
        while True:
            if state:
                renpy.block_rollback()
                break
            # don't make the renpy look stuck
            renpy.pause()

        config.rollback_enabled = True
        renpy.notify("received data")

    e "end"

    return
```

And how can I prevent user to save it while the subthread is running?

**Comment by ZYKsslm** [comment]
And it often happens in a screen, can I update the screen in the screen?

**Comment by renpytom** [comment]
Ren'Py will

**Comment by renpytom** [comment]
Hm... perhaps there needs to be renpy.run_on_main_thread, that  would let a subthread send information back to the main thread.

**Comment by renpytom** [comment]
I've added the new function (renpy.invoke_in_main_thread.)

**Comment by ZYKsslm** [comment]
> I've added the new function (renpy.invoke_in_main_thread.)

so when will the new version be released?

**Comment by ZYKsslm** [comment]
What's more, I found that the function `renpy.notify` can be used normally in the subthread.

```renpy
init python:
    
    import time

    def func():
        state = False
        global state
        for i in range(5):
            print(i)
            time.sleep(1)
        renpy.notify("done")
        state = True


define e = Character("艾琳")

label start:

    e "start"

    python:
        renpy.invoke_in_thread(func)
        while not state:
            renpy.say(e, "waiting......")

    e "end"

    return
```

So what else functions can do it?

**Comment by Gouvernathor** [comment]
The fact that you used it once and it worked, doesn't mean the function is safe to use in threads, or if it is now, that it will keep being safe in future versions.
The three safe functions are `restart_interaction`, `invoke_in_main_thread`, and `queue_event`, as says c9c9a149573bed9e50b133e7f737ebb11786c38c.

**Comment by ZYKsslm** [comment]
Fine, the new function seems that it can return to the main thread in the subthread and do sth. But what can it do in practice?
