### ISSUE TITLE
Meshing/Flattening a layered image makes them blurry at low resolutions

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#5108]
Hello, we noticed that our sprites looked blurry on lower resolutions (Notoriously playing in windowed mode in a laptop). We managed to track this down to the fact that we have mesh set to True inside out layered images. If you want to see it for youself I highly recomend downloading the MRE and trying it for yourself, just put it in windowed mode and down-scale the window, the difference is noticable. Either way, here are some screenshots (I recommend downloading them and trying it with an image comparison website)

![screenshot0011](https://github.com/renpy/renpy/assets/46462621/5123494e-b1ec-489b-a250-74c089c4db61)
![screenshot0012](https://github.com/renpy/renpy/assets/46462621/36273fdb-cfc8-49e0-baeb-ee4e8e0032eb)

And this is the reason we have mesh set to True in the first place

![screenshot0013](https://github.com/renpy/renpy/assets/46462621/0cc9c74a-8136-4293-a4e2-bb1af7dc3acc)
![screenshot0014](https://github.com/renpy/renpy/assets/46462621/2f3d26ba-b843-49b5-816d-ae51ec19ad76)

Below I have attached a Minimal Reproducible Example, please check it out.

[MeshBlurMRE.zip](https://github.com/renpy/renpy/files/13311168/MeshBlurMRE.zip)

**Comment by bober-gith** [comment]
Why not use Flatten instead, since it does the same but without this happening. 
It looks like Mesh would be something more suited for 3D, and might handle scaling a bit differently than a 2D image if it's like in Unity (without it being necessarily an issue).

**Comment by Galo223344** [comment]
Try the MRE out, I cover both mesh and flatten. And both provide the same blurry result.

**Comment by Elckarow** [comment]
use `gl_drawable_resolution False` (or `at renpy.partial(Flatten, drawable_resolution=False)`)

**Comment by bober-gith** [comment]
This seems to be a real thing, it does happen when the window is downscaled but also when it's upscaled. If ultimately there is no easy fix, I would say a good compromise would be to apply Flatten to the sprite only when you want to play with the alpha and not before or after, because when the alpha is low this kind of thing is not noticeable (that's why I never noticed it).

**Comment by Galo223344** [comment]
> use `gl_drawable_resolution False` (or `at renpy.partial(Flatten, drawable_resolution=False)`)

Based, thank you, this worked.
