### ISSUE TITLE
Music loop lag

### ISSUE THREAD

**Issue by Doedelzak** [renpy/renpy#511]
I'm not sure if it's my computer fault or the new version of Renpy, but the music doesn't loop smoothly anymore in my game. This was not a problem before. Now there is a small latency before the music starts again. It's really small but audible. I use the loop fonction to loop very small music files (such as drum loops), so I clearly hear it and it ruins the rythmic loops. 

I have verified that my files are real loops, and they are. They loop perfectly in Audacity, for exemple. So the latency comes from Renpy. The problem didn't exist in previous versions of Renpy. Any ideas ?

Sorry for my bad english, I'm french.

**Comment by renpytom** [comment]
Can I get access to these files? I've been trying it with perfect loops I've made in Audacity, and I haven't been able to repeat the problem.

**Comment by Doedelzak** [comment]
I'm so sorry : I checked my files again and the problem wasn't from Renpy. Althrough I was pretty sure I checked the right files, I mistook my backup folder for my actual folder... This is so lame.

I apologize for the time you wasted because of me. Next time I will make sure to check twice or more. Thanks for your replies.

**Comment by renpytom** [comment]
No problem. I'm closing this.
