### ISSUE TITLE
Auto-line break cuts fail to cut lines made of dots `.`, cuts narrow letters/words too early

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5111]
I was experimenting line-break by chaining only dots `.` to detect the actual right edge of my text area with maximum precision, and noticed the line was never broken.

So I used `i` letters instead, which can also narrow to give maximum precision. This time, the line was broken, but very early. I continued with `l`, `m`, and finally actual 4-letter `word` and it finally reached the normal length I see with actual sentences.

![2023-11-11 - Line break is odd with short words](https://github.com/renpy/renpy/assets/1067772/521998ac-314e-4af0-88be-73e67bd29df3)

The results for narrow letters and short words made of few letters is still odd, and I don't understand why `. . ` is not broken at all. While `i i i ` is unlikely text, a game could totally use dots for dramatic silence or something.

Here is the sample text to repro:

```rpy
    ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . "

    "i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i "

    "l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l "

    "m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m "

    "word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word word "

    "long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word long-word "
```

Note: I'm using NVL mode here which makes the issue obvious thanks to line comparison, but it works just as well on a standard dialogue (it will still be obvious with `...`, less obvious with `i i i ` but you can still see the text breaks too early.

**Comment by renpytom** [comment]
![screenshot-2023-28](https://github.com/renpy/renpy/assets/379804/f163fb3e-74dd-48d6-b88e-350e1e54d643)

With the development version of Ren'Py,  I don't see the issue with i and l, see the screenshot above. This may be an issue with the font you're using - is it a problem with DejaVuSans? 

As best as I can tell, the first line, with the periods, is right. Ren'Py follows an older version of Unicode TR 14. https://unicode.org/reports/tr14, the Unicode Line Breaking Algorithm. What you're seeing is a combination of Rule LB7 "Do not break before spaces or zero width space." and rule  LB13, which forbids breaking before a period or semicolon (both have type IS). 

The first line is the unicode algorithm, which is designed for meaningful text, breaking down when you feed it nonsense, and I think that's fine.

**Comment by hsandt** [comment]
I used the Inter font, but i tried again and could not repro:

![screenshot0001](https://github.com/renpy/renpy/assets/1067772/a872beb4-b4c4-4c4a-b5ff-d09cbbceadb5)

I suppose I should have sent an MWE of the exact snapshot of the game. For now it's fixed at least.
