### ISSUE TITLE
Allow project.txt to EXCLUDE projects from listing

### ISSUE THREAD

**Issue by Eliont** [renpy/renpy#5113]
Hello and good time of day.

This, or something alike, needed to split Renpy 7 and Renpy 8 projects, as they are not compatible, but all launchers still open same folder.

Thanks in advance.

**Comment by renpytom** [comment]
Why not just split your projects into two folders?

**Comment by Eliont** [comment]
Well, i wanted to do this, but when i launch renpy 8, it still show renpy 7 projects folder.
And if i chanege directory, when i launch renpy 7 - it show renpy 8 projects folder.

**Comment by renpytom** [comment]
Ah, right... makes sense. 

At the same time, I don't think I'm going to implement this. Ren'Py 7 vs Ren'Py 8 is a temporary things. (And you'd be sharing a projects.txt in this case, anyway)
