### ISSUE TITLE
[enhance]  add the movie pause/fastforward/backward/seek fucntion 

### ISSUE THREAD

**Issue by fastfading** [renpy/renpy#5120]
as the video visual novel game<love is all around>
https://store.steampowered.com/app/2322560/_/
became so popular, 
it is essential to enhance the move api 
add the movie pause/fastforward/backward/seek/skip fucntion 
and provide a demo to use  it 

and add a default way to make the  Play Movie unskipable

**Comment by renpytom** [comment]
This duplicates #2854

**Comment by fastfading** [comment]
> This duplicates #2854

any plan ? it is 2 years ago
