### ISSUE TITLE
Detecting iPad and iPhone

### ISSUE THREAD

**Issue by thelastsecret** [renpy/renpy#5124]
Safari on iPad presents itself as a Mac by default, so the “touch” variant isn’t active. This makes it hard to know that you are on an iPad. (We've discussed this in LemmaSoft Forum.)

**Comment by Kassy2048** [comment]
For the Web platform, this should have been fixed by PR #5024.  Did you try with a [nightly build](https://nightly.renpy.org/current-8/)?

**Comment by renpytom** [comment]
I've cherry-picked the change into the fix branch. Please try that (starting with the first build on or after November 20), and re-open this if there's still a problem.
