### ISSUE TITLE
Have an optimized version of Transform(alpha=0)

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#5125]
There is a lot of times where you need an empty version of a given image or displayable.
One example would be for sizing a fixed containing transformed version(s) of the image, but where the size of the fixed must be the one of the initial displayable.
Another would be for imagebuttons you put on a large background image, and where you only cut the hover image. In that case, you want to set a transparent version of the hover image as the idle image, to have the correct size.
A common way of doing that is `Transform(child, alpha=0)`, but the texturing and rendering still follows the usual image pipeline. I would see a version of Null() which would only compute the size of its child in the most optimized way possible, then entirely skip the following operations (the shaders for one).

**Comment by renpytom** [comment]
Could we optimize Transform(..., alpha=0), to skip the portions of the rendering process that occur after computing the size and position of the render?

**Comment by renpytom** [comment]
My suggestion went in as 332dfb510b0edcb89c1640d95aecb4b64413cebd.
