### ISSUE TITLE
Dynamically loaded image

### ISSUE THREAD

**Issue by ZYKsslm** [renpy/renpy#5126]
Can I show an image that didn't be defined in initialization phase?

**Comment by ZYKsslm** [comment]
I tried to write this way but it didn't work.

```renpy
define e = Character("艾琳")

label start:

    $ im = Image("images/Markima.jpg")
    show im:
        xysize(1920, 1080)
    pause

    return
```

**Comment by Elckarow** [comment]
```rpy
show expression "images/Markima.jpg"
```

**Comment by Gouvernathor** [comment]
You're confusing the images namespace and the variables namespace. In your example, `im` is a variable, not a defined image. See [defining images](https://www.renpy.org/doc/html/displaying_images.html#defining-images), [displayables](https://nightly.renpy.org/doc/displayables.html), and the [show expression statement](https://www.renpy.org/doc/html/displaying_images.html#show-expression).

**Comment by ZYKsslm** [comment]
> ```python
> show expression "images/Markima.jpg"
> ```

Oh, it does work!

**Comment by ZYKsslm** [comment]
> ```python
> show expression "images/Markima.jpg"
> ```

How can I use it in python statement?

**Comment by Gouvernathor** [comment]
https://www.renpy.org/doc/html/statement_equivalents.html#displaying-images

**Comment by ZYKsslm** [comment]
> https://www.renpy.org/doc/html/statement_equivalents.html#displaying-images

it requests me to define an image in initialization phase.

**Comment by ZYKsslm** [comment]
I mean that the show statement needs a param `name` which is a string of an image that need to be defined in initialization phase.
