### ISSUE TITLE
Cannot hide image shown on layer screens

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5133]
# Setup

You can either download the MWE: [Repro bug Show image on layer screens cannot hide.zip](https://github.com/renpy/renpy/files/13403621/Repro.bug.Show.image.on.layer.screens.cannot.hide.zip)

or recreate the project yourself:

1. Create a new project

2. Fill script.rpy with this:

```rpy
image disc = "images/disc_100x100.png"

label start:

    show disc

    "After show disc"

    hide disc

    "After hide disc: OK"

    show disc onlayer screens zorder 1

    "After show disc onlayer screens zorder 1"

    hide disc

    "After hide disc: disc is sticky!"

    return
```

3. Download this sample picture:

![disc_100x100](https://github.com/renpy/renpy/assets/1067772/5397ca96-3ef4-451f-8f56-51d0b34a6694)

and place it in project/images//disc_100x100.png

# Repro

Run the game and observe how the first disc is hidden, but the second one on screens layer is not.

This seems to occur on other premade layers (not custom layers though, but in my case I needed the `screens` layer to place my character right between the NVL text box and the exit popup, on a custom layer above `screens`, it would show over the exit confirmation popup...)

![screenshot0003](https://github.com/renpy/renpy/assets/1067772/d43d8986-9019-4e2a-a577-6ce8e30863f0)

**Comment by bober-gith** [comment]
I think that's intended, hide alone autotarget master, then if you want to hide something that is on another layer:

hide disc onlayer screens

**Comment by renpytom** [comment]
@bober-gith is correct.

**Comment by hsandt** [comment]
Odd, I'm sure I had tried `hide ... onlayer ...` before too, but I suppose I used it in a different context where it didn't work. The MWE helped me reduce the code to the most simple lines anyway, and now `hide ... onlayer ...` works! Thanks!
