### ISSUE TITLE
renpy.get_sdl_dll() always returns None

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#5138]
SDK: Ren'Py 8.1.3
OS: Windows 10

When following the example at https://www.renpy.org/doc/html/other.html#sdl
`renpy.get_sdl_dll()` always returns None. Using ctypes directly to load `librenpython.dll` resulted in `SDL_GetError` and other SDL functions not being found.

**Comment by renpytom** [comment]
Fixed by renpy/renpy-build@a7faf7c .

**Comment by CharlieFuu69** [comment]
In v8.1.3, the `renpy.get_sdl_dll()` function keeps returning `None`. Does this happen in newer versions?
![Image](https://github.com/user-attachments/assets/d04e1c18-671b-473d-8bdd-2d0e74504fee)
