### ISSUE TITLE
Add function: Run Ren'Py script in Python statement

### ISSUE THREAD

**Issue by ZYKsslm** [renpy/renpy#5139]
# Add a new function: Run Ren'Py script in Python statement

## Description

We can use `python` statement or `$` to run python code in renpy.
But it seems that there isn't a function that support to run renpy script in python statement.
Some equivalent python functions don't do well and it will be more convenient to code so I think we need it.

So can a new function be added?

## Example

```renpy

$ renpy.run_in_renpy("scene bg")

```

**Comment by renpytom** [comment]
Generally, if a python equivalent doesn't do well, it's because the statement is benefiting from being a permanent part of the script. 

I don't plan to add something like this. (Beyond renpy.load_string.)
