### ISSUE TITLE
Ren'Py should save to the "Saved Games" directory on Vista and newer.

### ISSUE THREAD

**Issue by SaberUK** [renpy/renpy#514]
Since Windows Vista there has been a "Saved Games" directory (which defaults to `~/Saved Games`). It would be nice if Ren'Py could use this directory for saving its game data as the `%APPDATA%` folder which Ren'Py currently uses is not something which is normally visible to users which makes it hard for backing up saves when migrating between systems.

Reference: http://msdn.microsoft.com/en-us/library/windows/desktop/dd378457.aspx#FOLDERID_SavedGames

**Comment by renpytom** [comment]
I'm not sure if there's a good way to change this. Ren'Py games that support multipersistent data need to use the data stored in %APPDATA%. XP is also still in widespread use. So I don't think I can change this anytime soon.

**Comment by bbs3223474** [comment]
In my opinon, because almost every ADV games saved at their own game folder, only a little of them saved at %SysDir%\Users\%Username%\AppData\, it's no need to change this.

**Comment by vollschauer** [comment]
I think this issue can be closed by now :D 

## Save directory ##############################################################
##
## Controls the platform-specific place Ren'Py will place the save files for
## this game. The save files will be placed in:
##
## Windows: %APPDATA\RenPy\<config.save_directory>
##
## Macintosh: $HOME/Library/RenPy/<config.save_directory>
##
## Linux: $HOME/.renpy/<config.save_directory>

**Comment by renpytom** [comment]
I don't plan to change this, for the same logic expressed in #1377 .
