### ISSUE TITLE
Imagemap flickers with mouse over transparent areas within a hotspot rectangle

### ISSUE THREAD

**Issue by h3llra1ser** [renpy/renpy#5142]
I was experimenting with Imagemap using two images: idle and hover
Reading the docs, the hotspot rectangle only should get focus when the cursor is over an **opaque area of the hover image** inside the hotspot rectangle.
This basically works, but if I move the mouse inside the transparent area, the hover rectangle "flickers" on and of for each pixel the mouse gets moved...

I've put a test case here:
https://www.mediafire.com/file/hksk58s3zldy8zl/imagemap_alpha_flicker.zip/file

The vials, the two flasks on the left and the microscope have hotspot rectangles and a red hover overlay.
Try the transparent area around of the microscope (same issue on the other hotspots, but there are smaller rectangles).

**Comment by h3llra1ser** [comment]
Forgot to mention: Windows platform, tested ren'py 8.1.1 and 8.1.3

**Comment by the66F95** [comment]
[imagemap.zip](https://github.com/renpy/renpy/files/13445550/imagemap.zip)
use proper ground, idle and hover images.
but i'd advise to use imagebuttons, it's way more flexible.

**Comment by h3llra1ser** [comment]
Hello and thanks for the clarification.
After re-reading the documentation I think this should be clear in the text for "alpha". idle and hover mention this, but alpha only talks about opaque areas in the hover image, which is a bit confusing.

`If true, the default, a hotspot only gains focus when the mouse is in an area of the hover image that is opaque.`

On the other hand, after investigating the imagemap code, it's only one line to change so that imagemaps can use alpha hover mask using idle and hover images only:
renpy/ui.py, line 1325:
```
    if imagemap.alpha:
        # focus_mask = True
        focus_mask = hover
    else:
        focus_mask = None
```
Both the Ren'py documentation and I don't see any reason why it should be neccessary to provide three separate base,  idle and hover images where the idle AND hover image both have to be transparent to get this 'feature' working correctly?

**Comment by renpytom** [comment]
Thanks for the report and the fix. I've committed it into Ren'Py.
