### ISSUE TITLE
libjpeg-turbo license wrong in documentation?

### ISSUE THREAD

**Issue by AGraber** [renpy/renpy#5147]
Hi,
on the documentation about licenses, this is stated:

https://github.com/renpy/renpy/blob/02fa5ad2bf68db43d201105b9f1b34192c33eb8d/sphinx/source/license.rst?plain=1#L46

However, I've checked [libjpeg-turbo's License file](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/LICENSE.md) and it makes no mention of it. Is it just wrong in the docs or is it stated somewhere else I'm not aware of?

**Comment by renpytom** [comment]
It's possible it's wrong, or it's possible it's changed in the interim. I'll take a look.
