### ISSUE TITLE
Crash in glTexImage2D

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#5152]
From #3643

May be because of an unexpected alignment.

```
  #00  pc 0x00000000001a8144  /vendor/lib64/egl/libGLESv2_mtk.so
  #01  pc 0x00000000001a3294  /vendor/lib64/egl/libGLESv2_mtk.so
  #02  pc 0x000000000012ee98  /vendor/lib64/egl/libGLESv2_mtk.so
  #03  pc 0x000000000012d650  /vendor/lib64/egl/libGLESv2_mtk.so (glTexImage2D+320)
  #04  pc 0x0000000000bbad04  /data/app/~~LoH3m9_RLw6YYQD3GOg3Ow==/com.npckc.tavern-ClknixmbQuiRZkdV85BSUA==/split_config.arm64_v8a.apk
  #05  pc 0x0000000000d98a8c  /data/app/~~LoH3m9_RLw6YYQD3GOg3Ow==/com.npckc.tavern-ClknixmbQuiRZkdV85BSUA==/split_config.arm64_v8a.apk
  #06  pc 0x0000000000b93018  /data/app/~~LoH3m9_RLw6YYQD3GOg3Ow==/com.npckc.tavern-ClknixmbQuiRZkdV85BSUA==/split_config.arm64_v8a.apk
  #07  pc 0x0000000000b949e4  /data/app/~~LoH3m9_RLw6YYQD3GOg3Ow==/com.npckc.tavern-ClknixmbQuiRZkdV85BSUA==/split_config.arm64_v8a.apk
  #08  pc 0x0000000000b9ba78  /data/app/~~LoH3m9_RLw6YYQD3GOg3Ow==/com.npckc.tavern-ClknixmbQuiRZkdV85BSUA==/split_config.arm64_v8a.apk
  #09  pc 0x0000000000b33694  /data/app/~~LoH3m9_RLw6YYQD3GOg3Ow==/com.npckc.tavern-ClknixmbQuiRZkdV85BSUA==/split_config.arm64_v8a.apk
  #10  pc 0x0000000000b49200  /data/app/~~LoH3m9_RLw6YYQD3GOg3Ow==/com.npckc.tavern-Clkn
```

**Comment by renpytom** [comment]
More stacktraces at:

https://github.com/renpy/renpy/issues/3643#issuecomment-1836957732

[samsung gta7litewifi (Galaxy Tab A7 Lite) Android 13 (SDK 33).txt](https://github.com/renpy/renpy/files/13532806/samsung.gta7litewifi.Galaxy.Tab.A7.Lite.Android.13.SDK.33.txt)
[google hana_cheats (Mediatek MT8173 Chromebook) Android 9 (SDK 28).txt](https://github.com/renpy/renpy/files/13532807/google.hana_cheats.Mediatek.MT8173.Chromebook.Android.9.SDK.28.txt)
[ZTE P963F07 (ZTE A7030) Android 11 (SDK 30).txt](https://github.com/renpy/renpy/files/13532808/ZTE.P963F07.ZTE.A7030.Android.11.SDK.30.txt)
[Redmi water (Redmi A2+) Android 13 (SDK 33).txt](https://github.com/renpy/renpy/files/13532809/Redmi.water.Redmi.A2%2B.Android.13.SDK.33.txt)
[Vortex HD65 (HD65) Android 13 (SDK 33).txt](https://github.com/renpy/renpy/files/13532810/Vortex.HD65.HD65.Android.13.SDK.33.txt)
[samsung a10s (Galaxy A10s) Android 11 (SDK 30).txt](https://github.com/renpy/renpy/files/13532811/samsung.a10s.Galaxy.A10s.Android.11.SDK.30.txt)
[samsung a03s (Galaxy A03s) Android 13 (SDK 33).txt](https://github.com/renpy/renpy/files/13532812/samsung.a03s.Galaxy.A03s.Android.13.SDK.33.txt)
[samsung a3core (Galaxy A03 Core) Android 11 (SDK 30).txt](https://github.com/renpy/renpy/files/13532813/samsung.a3core.Galaxy.A03.Core.Android.11.SDK.30.txt)

**Comment by renpytom** [comment]
I have a Galaxy Tab A7 Lite, so I'll use that to try and address this. 

@npckc , can I get access to the game with  the problem? I first want to repeat it, and then I'll try to fix it.

**Comment by npckc** [comment]
@renpytom The game in question is https://play.google.com/store/apps/details?id=com.npckc.tavern (.aab) and should be able to be played for free through the Play Store.

**Comment by renpytom** [comment]
Okay, I'm able to reliably reproduce the crash on my Tab A7 Lite. Can you send the game files to renpytom@gmail.com, and I'll see what I can do to fix things. 

A problem is that this isn't a bug in Ren'Py - the problem is in libGLESv2_mtk.so, which is the driver for the gpu on the tablet. Hopefully I can find a way to work around the problem.

**Comment by npckc** [comment]
I've sent the game files along with the .aab file through email. Hopefully there is something that can be done for the driver.

**Comment by renpytom** [comment]
Okay, the issue is with the old gl renderer. You seem to be setting config.gl2 to False, and that's activating an older code path that's causing the problem.

**Comment by npckc** [comment]
Good to know the issue! I have it set to False because of lag caused if it is True (reference issue https://github.com/renpy/renpy/issues/3612) but as a stop-gap measure I can set it to True for Android.

According to this text, the old gl renderer will be removed in 8.1 (https://renpy.org/doc/html/incompatible.html) so perhaps this is not an urgent issue.

**Comment by renpytom** [comment]
I've disabled config.gl2. This isn't the first problem that's been caused by a creator setting it to False, and given that there's little point in fixing the gl renderer when it'll be going away in 2024, it seems reasonable to disable.
