### ISSUE TITLE
Regarding the volume set by Preference("xxx volume", xxx)

### ISSUE THREAD

**Issue by caqingtgas** [renpy/renpy#5158]
I've noticed that prior to Ren'Py 8.0.3, using "Preference("xxx volume", xxx)" and "define config.default_xxx_volume = xxx" to set the volume resulted in the same behavior. However, in the latest version, I've observed that they behave differently.

For example, I have the following settings:
`Preference("music volume", 0.5)`
`define config.default_music_volume = 0.5`

While I'm aware that they set different volumes in practical use, I prefer using "Preference" to directly set the global volume. Could you please advise on how to adjust the configuration in the new version to restore the previous behavior, ensuring that the volume set by "Preference" and "define" is consistent?

**Comment by renpytom** [comment]
Correct, this was a change in how volumes work. You can still use preference, but you now need to use the decibel scaling.

**Comment by caqingtgas** [comment]
> Correct, this was a change in how volumes work. You can still use preference, but you now need to use the decibel scaling.


Thank you very much. I would like to set the default volume for the game, but after the update, the volumes no longer match. Is there a way to add decibel scaling to 'Preference' to address this issue? Or can I use percentage volume entirely? In any case, is there a way to ensure that the volumes set are the same?

**Comment by renpytom** [comment]
Looking at it, the config.default_music_volume should work the same way as other volumes works, with 0.0 being -40dB and 1.0 being full-scale.
