### ISSUE TITLE
Joystick Events are not sent to displayables

### ISSUE THREAD

**Issue by jsfehler** [renpy/renpy#5161]
Joystick and Controller events such as  pygame.JOYAXISMOTION and pygame.CONTROLLERAXISMOTION are not sent to displayables. An event with the number `32771` is sent for gamepad button down and axis motion events.

Hardware: 8-BitDo SN30 Pro (Detected as XBox 360 Gamepad)

In the example below, an Exception is never triggered, but one should be.

```
    class JoystickTracker(renpy.Displayable):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            
            self.axis = False
            
            self.joystick = pygame.joystick.Joystick(0)
            self.joystick.init()

        def render(self, width, height, st, at):
            render = renpy.Render(width, height)
            
            self.axis = self.joystick.get_axis(0)
            
            return render

        def event(self, ev, x, y, st):
            if ev.type == 32771:
                renpy.redraw(self, 0)
                renpy.restart_interaction()
                
            elif ev.type in [pygame.JOYAXISMOTION, pygame.CONTROLLERAXISMOTION]:
                raise Exception(ev.type)
```

```
screen show_axis():
    default jt = JoystickTracker()
    
    add jt
    
    vbox:
        hbox:
            text "Axis:"
            text "[jt.axis]"
    
```

```
label start:
    call screen show_axis
```

**Comment by mal** [comment]
This is currently by design as they're very spammy events and the vast majority of VN games only need impulse mappings (for example being able to recognise a joystick being twitched to the right so it can be mapped similarly to a right arrow key press).

Can what you're seeking to do be accomplished by observing MOUSEMOTION events, and if not could you give more details on what you're trying to achieve?

**Comment by jsfehler** [comment]
I'd like to use the motion amount to control the velocity of sliders.

Technically, I can fetch the axis from updating on any gamepad event, but I find that too broad and it relies on undocumented behaviour.

As a related issue, Pygame's event types are well documented but `32771` is not. At least so far, this is the only case where event types do not match pygame. The pygame_sdl2 repo has some documentation for which pygame modules are not implemented but we should have docs for where Ren'Py's Pygame API implementation diverges on purpose.

**Comment by renpytom** [comment]
I've added config.pass_joystick_events and config.pass_controller_events , which pass the respective events to Ren'Py when true. That should let you process them how you want.
