### ISSUE TITLE
Broken ATL & Transform

### ISSUE THREAD

**Issue by qTich** [renpy/renpy#5162]
16e50a978ee1f58735158c11f5ad5bbedb1e7aba - Broke some operations at the Transform and ATL level:

```py
File "PP\renpy\atl.py", line 684, in execute
action, arg, pause = block.execute(trans, timebase, self.atl_state, events)
File "game/modules/ATL.rpym", line 166, in execute
File "PP\renpy\atl.py", line 1415, in execute
startanchorangle = trans.state.anchorangle
File "PP\renpy\display\transform.py", line 392, in get_anchorangle
angle, radius = self.cartesian_to_polar_anchor(xanchor, yanchor)
File "PP\renpy\display\transform.py", line 292, in cartesian_to_polar_anchor
dx = x - xaround
File "PP\renpy\atl.py", line 109, in __sub__
return self + -other
TypeError: unsupported operand type(s) for +: 'position' and 'float'
```
If we uncomment isinstance (int, float) in `__add__`, we will get a different error:

```py
File "PP/renpy/atl.py", line 1415, in execute
startanchorangle = trans.state.anchorangle
File "PP/renpy/display/transform.py", line 392, in get_anchorangle
angle, radius = self.cartesian_to_polar_anchor(xanchor, yanchor)
File "PP/renpy/display/transform.py", line 295, in cartesian_to_polar_anchor
radius = math.hypot(dx, dy)
TypeError: must be real number, not position
```
Likewise, when entering a name in the tutorial:

```py
File "PP/renpy/display/transform.py", line 926, in render
return RenderTransform(self).render(width, height, st, at)
File "accelerator.pyx", line 989, in renpy.display.accelerator.RenderTransform.render
File "accelerator.pyx", line 328, in renpy.display.accelerator.RenderTransform.cropping
File "accelerator.pyx", line 125, in renpy.display.accelerator.relative
TypeError: int() argument must be a string, a bytes-like object or a number, not 'position'

While running game code:
File "game/script.rpy", line 186, in script call
call expression tutorial.label from _call_expression
File "game/tutorial_quickstart.rpy", line 599, in script
e "That's done with Python, and especially the renpy.input function. The first line of this example prompts the player for some texts, and sticks it in the name variable."
TypeError: int() argument must be a string, a bytes-like object or a number, not 'position'

```

**Comment by Gouvernathor** [comment]
I likely fixed the last one in 874e72e (I need to rebuild renpy to be certain but I'm fairly confident, it was a missed place where absolute.compute should have been used).

Can you give me a sample code to reproduce the first part ? In `cartesian_to_polar_anchor`, both parameter should be converted to a native type before that substraction occurs 🤔

**Comment by qTich** [comment]
> I likely fixed the last one in [874e72e](https://github.com/renpy/renpy/commit/874e72e740f2c378a4029bae504f0b3efb61fc7b) (I need to rebuild renpy to be certain but I'm fairly confident, it was a missed place where absolute.compute should have been used). Also, it was't triggered by clicking on just any name in the tutorial, it was a specific part of the Input path. That sort of things is useful.
> 
> Can you give me a sample code to reproduce the first part ? In `cartesian_to_polar_anchor`, both parameter should be converted to a native type before that substraction occurs 🤔

```renpy
image ...:
    ....
    zoom 0.2
    rotate 0
    pos (2000, 1000)
    linear 0.06 pos (1800, 1000)
    linear 0.09 pos (1600, 1010) rotate 51
    linear 0.12 pos (1400, 1015) rotate 102
    linear 0.15 pos (1200, 1020) rotate 154
    linear 0.18 pos (1000, 1000) rotate 205
    linear 0.21 pos (800, 960) rotate 257
    linear 0.24 pos (600, 920) rotate 308
    linear 0.33 pos (340, 850) rotate 360
    align (0.179, 0.785)
    alignaround (0.185, 0.715)
    linear 0.9 clockwise align (0.179, 0.785) rotate 720  # error line
    pos (340, 850)
    linear 0.02 pos (300, 860)
    linear 0.05 pos (200, 900)
    linear 0.04 pos (100, 925)
    linear 0.03 pos (0, 950)
    linear 0.02 pos (-100, 975)
    repeat
```

**Comment by Gouvernathor** [comment]
Got it, I got it mixed up with cartesian_to_polar_pos for some reason.

**Comment by Gouvernathor** [comment]
The top part is a bigger can of worm because a set of properties was understood to only work properly if they were all passed the same type of data, sort of (but not exactly) like how align can only pass a float value to both pos and anchor.
Since they are now all converted to the position type all may seem fine, but actually not since a lot of the calculations were made supposing all the data was of numeric types, and it's not the case anymore.
The fix is not straightforward.
