### ISSUE TITLE
Accessibility: accessibility panel key binding is `K_a` instead of `shift_K_a`

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5177]
I noticed in 00keymap.rpy and https://www.renpy.org/doc/html/keymap.html this binding:

```py
accessibility = [ 'K_a' ]
```

which corresponds to A, although it also coincidentally binds to Shift+A (generally speaking, all "pure" bindings map to the Shift variant; which btw is not clearly explained in the doc, HB38 explained it on Discord).

But looking at the changelog and Help, it should really be Shift+A i.e. `shift_K_a`.

Is it intended to allow devs to just press A when they're in a hurry?

In my case I created a custom accessibility panel I wanted to bind to A, so I had to make sure to remove the native accessibility panel's `K_a` binding and replace it with `shift_K_a`, then add my custom binding `noshift_K_a` to my custom accessibility panel to avoid conflict between the custom and native accessibility panels.

**Comment by renpytom** [comment]
it was meant to be shift+A.
