### ISSUE TITLE
Random crashes on Android with Ren'Py 8.1.1

### ISSUE THREAD

**Issue by perverteer** [renpy/renpy#5178]
I've had some reports from players who experience random crashes on Android. Only one of them responded in detail, so I'm a little hesitant about opening a report for this. According to this user the game either closes without warning or displays a black screen. This is on Android 12 on a Samsung Galaxy Tab S6 with a stock OS.

The problems don't occur with earlier versions of Ren'Py 8 (8.0.3 and lower), it's 8.1 that somehow trips Android up. When testing the exact same game using 8.0.3 there were no crashes. According to the player, this behavior is consistent with all games using 8.1.1. Setting a different renderer doesn't resolve the issue.

I've attached [a log](https://github.com/renpy/renpy/files/13671004/log.txt) provided by the user who contacted me. The game is using an alternate save game location, but the crashes happen with or without the default save game path. The only error I see in the log is this one:

`Flip failed error(b'The specified window has not been made current')`

Suggesting a dialog window in the background interfering with the game. I found [this issue](https://github.com/renpy/renpy/issues/2812), but I'm not sure if it's applicable as the crashes mentioned in the report are consistent and in my case they happen randomly.

[log.txt](https://github.com/renpy/renpy/files/13671004/log.txt)

**Comment by renpytom** [comment]
I've made a small fix, but since the app runs for quite a bit after that error, it's likely not the crash. 

If you can repeat it, I need the android logcat when it happens, to see if I can pick something else out of it.

**Comment by perverteer** [comment]
Sorry for the lack of follow-up on my side. I've asked the player who reported the problem to me to provide me with logcat output, but I've yet to hear back. Hopefully the fix mentioned above will resolve things either way.
