### ISSUE TITLE
[Crash] Game doesn't start with Razer Tartarus Pro Sequel

### ISSUE THREAD

**Issue by SamGamerYT** [renpy/renpy#5181]
> Do you have any sort of traceback or other output?
Sorry, Was inactive and no, However, it does create "log.txt" file but that's it.

[log.txt](https://github.com/renpy/renpy/files/13678008/log.txt)

I don't see any crashes in the Event Viewer Application but I do see some error reports

```
Faulting application name: App.19.exe, version: 0.0.0.0, time stamp: 0x650907b0
Faulting module name: ntdll.dll, version: 10.0.22621.2506, time stamp: 0xbced4b82
Exception code: 0xc0000374
Fault offset: 0x000000000010c7a9
Faulting process id: 0x0x8E4C
Faulting application start time: 0x0x1DA2ECB6CB4915A
Faulting application path: D:\Sam\Games\App\App.19.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 52ad33dd-c46e-491a-8fd3-9985239254fa
Faulting package full name: 
Faulting package-relative application ID: 
```

```[tasklist]
### Tasks
- [ ] https://github.com/renpy/renpy/issues/5176
```

**Comment by renpytom** [comment]
If you uninstall the Razer software, does Ren'Py work?

**Comment by SamGamerYT** [comment]
> If you uninstall the Razer software, does Ren'Py work?

Can't uninstall it sadly however if I unplug my controller, yes it starts - This issue was reported and fixed previously but it happened again sadly.

**Comment by renpytom** [comment]
Did you report it to me, or to Razer?

**Comment by SamGamerYT** [comment]
> Did you report it to me, or to Razer?

To you #4622

**Comment by renpytom** [comment]
I think you're going to have to contact Razer's support department here. The crash is happening before the controller fully enumerates, which means it's not likely happening in Ren'Py but in something that Razer is doing.

**Comment by renpytom** [comment]
(Closing, as this seems to be a problem best handled by Razer.)
