### ISSUE TITLE
Having trouble trying to randomize a music list

### ISSUE THREAD

**Issue by SchaakaKon** [renpy/renpy#5182]
I was looking to add music to my Renpy game and found some good tutorials online, which works great.
Then I wanted to randomize the playlist so the same song isnt playing every time, the only problem I ran into is that I can only randomize the playlist once.
For example if i have song_1, song_2, song_3 and Renpy will randomize to lets say to play song_2, song_3 and then song_1. Renpy will always start the same order from song_2 every time you load in the game. How can I make it so that Renpy randomizes every time a player loads their save? Ive gone to discords and reddit but no one can figure why its not working as it should.

The only code I have that has anything to do with music, sounds or randomize is only 3 lines of code, which are placed above label start:

define main_menu_music_tracks = ['song_1.mp3', 'song_2.mp3', 'song_3.mp3', 'ect..' ]

$ renpy.music.queue(main_menu_music_tracks)

init python:
    renpy.random.shuffle(main_menu_music_tracks)

Any help on this is most appreciated, thanks!

**Comment by Gouvernathor** [comment]
Several problems.
- You seem to have a dollar-line outside of a label. That code will not get executed, period.
- You use define on a value, then mutate (change) that value using shuffle (which changes the list in-place). That may be fine-ish in this particular case but it's not a good practice because it breaks prediction. Values defined with the define statement are constants.
- You shuffle the list exactly once, when the game boots, since you do so in an init python block. I don't know when you trigger your music to be played, but the order of the list will remain the same from the moment you open the game until the moment you close the window. I'm not sure that's what you wanted to do.

I think you should clarify what you want and ask that on the discord help channels again ; not about how you can fix your code, but how you can implement what you want.

**Comment by SchaakaKon** [comment]
> Several problems.
> 
>     * You seem to have a dollar-line outside of a label. That code will not get executed, period.
> 
>     * You use define on a value, then mutate (change) that value using shuffle (which changes the list in-place). That may be fine-ish in this particular case but it's not a good practice because it breaks prediction. Values defined with the define statement are constants.
> 
>     * You shuffle the list exactly once, when the game boots, since you do so in an init python block. I don't know when you trigger your music to be played, but the order of the list will remain the same from the moment you open the game until the moment you close the window. I'm not sure that's what you wanted to do.
> 
> 
> I think you should clarify what you want and ask that on the discord help channels again ; not about how you can fix your code, but how you can implement what you want.

I do apologize if I am not understanding you correctly, but yes I am asking here how I can implement a code to randomize a music list when a player loads their game. 
I am by no means married to any code I written, I've tried a bunch of variations and that just happens to be the last one I tried.

**Comment by Gouvernathor** [comment]
What do you mean by "load their game" ? do you mean booting the game, or loading a save file ?
When is the music supposed to be played ?
You should clarify the answers to these questions and specify that when asking for help on discord about how to make something. This is not Discord, this is GitHub, where we track and solve bugs on the renpy engine, which this doesn't seem to be.
I also suggest looking at [the audio in renpy documentation](https://www.renpy.org/doc/html/audio.html), in particular the queue statement, and [the random module's documentation](https://docs.python.org/3/library/random.html), in particular the sample function.

**Comment by SchaakaKon** [comment]
Ah thats my bad, Im not too familiar with github but that makes sense. Usually when the other sites cant figure it out they mention asking here.

Yes to answer your question, whenever the player loads their save file Renpy will always play the same order of songs. It will randomize the initial or first time but then play in that same order every time. If you play, save, load, save, load ect it will always be the same order of music.

I guess this is a lot tougher cookie to beat than I thought it was, I do appreciate your time though. My quest continues haha.
