### ISSUE TITLE
screen timer cannot perform data operations

### ISSUE THREAD

**Issue by ZYKsslm** [renpy/renpy#5183]
# screen timer cannot perform data operations

## Description

When I use a timer in a screen, I tried all of the data actions but they didn't work, didn't report error, either.

## Code

There is an example. The var won't be changed to `True`.

```renpy
screen t:
    $ var = False

    timer 1 action SetScreenVariable("var", True)
    timer 2 action Notify(str(var))

label start:
    call screen t
    pause
    return

**Comment by shawna-p** [comment]
Running Python like that in the screen causes it to run every time the screen is refreshed, ergo your action runs, the screen refreshes, and your variable is set back to False. This is known as a side effect, and its advised you do not run Python in screens which cause side effects. You need to use `default` not `$` to set up the screen variable.
