### ISSUE TITLE
Alt+tab to switch app sometimes accidentally triggers Toggle Skip, messing up with iterative debugging

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5187]
I often switch between my Renpy game and VS Code with Alt+tab, and realised the tab was sometimes registered by Renpy after switch (esp. when pressing Alt+tab quickly), causing Toggle Skip, causing the game to advance on its own (default setting is to skip text already read), which advances too much in the story while I was just testing the current text block after my change.

**Repro**

1. Run Renpy game to a certain text block (not a menu choice, but rather linear text, if possible before a block already read, or enable Skip Unseen Text in preferences)
2. Switch to code editor (or any other app)
2b. In real life, we modify script at this step, but it's not needed for repro
3. Switch to Renpy project with Alt+tab, pressed and released quickly
3b. In real life, you would usually reload with Shift+R the first time, or the project would auto-related further times (this may help repro the bug)

There is no 100% repro so repeat 2-3 many times to trigger the bug.

I found it hard to repro on default project (one out of 20, and I had to press Tab and release it super fast), whereas on my real project (where I also auto-reload changes), it seems to happen very often (maybe it's my perception because it's much more annoying in a real project).

**Video capture on default project**

[2023-12-20 Renpy repeated Alt+tab toggle skip.webm](https://github.com/renpy/renpy/assets/1067772/87a45509-b399-46fb-8d8e-5e2a7d0c653c)

(here the script is short for Skip will immediately end the game)

**Comment by renpytom** [comment]
I've made a small change to try to fix this. If you get a chance, please try the 2023-12-21 nightly, to see if the fixed worked. 

(Feel free to re-open the issue if it didn't.)
