### ISSUE TITLE
Is there *any way* to make the import of llama-cpp-python possible?

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5190]
So I am able to import [ctransformers](https://github.com/marella/ctransformers) into Renpy as extra python-packages using the suggested method. This is a module for handling transformer large language models. As you can expect, it can be a lot of fun and opens up many interesting VN possibilities. (There is an issue on saving that I have to solve, but oh well).

Sadly, `ctransformers` is way slower and less potent than [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) which binds to `llama.cpp`.

The main problem right now is that importing `llama-cpp-python` does not work, since `sqlite3` is not included in Renpy's python packages. Maybe other errors will occur even if `sqlite3` is available, but I cannot get that far. And I am not able to build Renpy myself with included `sqlite3` (I tried really hard!).

Can anybody help me out here? I think it's time that Renpy has official support for those important LLM modules - at least as extra packages.

**Comment by renpytom** [comment]
This is out of the scope of Ren'Py, at least for the moment. 

One suggestion would be a second install of Python, which you can run and communicate with using subprocess. 

You can also use renpy-build to make your own builds, though the documentation there is sparse - check in extensions for how to build your own submodule.

**Comment by m-from-space** [comment]
> You can also use renpy-build to make your own builds, though the documentation there is sparse - check in extensions for how to build your own submodule.

I did that already, and was able to build `renpy-build` with `sqlite3` (using the amalgamation version) only. But building the distrubution failed with error:

`./python: symbol lookup error: /home/rb/renpy-build/renpy/lib/py3-linux-x86_64/librenpython.so: undefined symbol: PyInit_sqlite3`

**Comment by m-from-space** [comment]
> One suggestion would be a second install of Python, which you can run and communicate with using subprocess.

That was a fantastic suggestion, I was able to pull it off. Thank you very much. <3
Now I have to figure out how make Renpy not to throw a pickle error when trying to save.
