### ISSUE TITLE
[Documentation] screens.rpy uses button_text_properties which is undocumented, but alias for text_properties which is documented

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5197]
I was looking at screens.rpy navigation styles:

```rpy
style navigation_button:
    size_group "navigation"
    properties gui.button_properties("navigation_button")

style navigation_button_text:
    properties gui.button_text_properties("navigation_button")
```

and searched for button_text_properties, found no result in doc. Then I inspected source code and found that it was an alias for text_properties, which is documented in https://renpy.org/doc/html/gui_advanced.html#gui.text_properties

What is the reason for the dual names? One makes it obvious that it should be used for text on _buttons_, the other is more about the implementation, agnostic of where text comes from maybe?

If we intend to keep both, at least there should be some indication that one is an alias for the other (possibly on https://renpy.org/doc/html/gui_advanced.html itself, since people may have looked for the similar `button_properties` earlier and so already be on that page) to allow users to search for either string and still find the documentation for it.

**Comment by renpytom** [comment]
Dunno. I'll change the default gui to remove the use of the alias.

**Comment by Gouvernathor** [comment]
That's because it's the former name of text_properties which was documented under that name at the time, see f7a64793c3383291c529607c40285e4204013c6d
