### ISSUE TITLE
Feature request: add Restart option to Exception screen to allow testing after change in main menu (which cannot rollback)

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5199]
**Context**

I am currently working on the main menu and after an exception due to e.g. a missing main_menu.png because I was just updating it and Renpy auto-reloaded before I had time to put the new one, I want to keep testing the game's main menu.

However, on error I get an Exception screen, which features different options like Rollback and Reload - two commands which are meant for in-game script running.

Thus, after fixing the issue (e.g. placing the new main_menu.png), whether I choose Rollback or Reload, I will get a second Exception:

> Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Indeed, I am in the main menu so there is nothing to rollback. Even Reload is considered like a rollback apparently.

So I must Quit, and restart the game manually each time.

**Request**

Add a Restart button besides Rollback and Reload so I can restart the game at the main menu, so I can immediately test my changes.

**Comment by mal** [comment]
This seems expected when removing an image that is in use while auto-reload is enabled. If you don't want it to reload then turn off auto-reload before attempting to replace assets that are being used.

**Comment by HorBro38** [comment]
You can just click "ignore" and it will reload the main menu without issue @hsandt .

**Comment by hsandt** [comment]
Ignore worked, thanks!
