### ISSUE TITLE
Script parsing error on Renpy 7 when commenting a line

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5200]
In Renpy 7 only, leaving a blank space between a script line and a comment is reported as an error.

`"Hello"  # Comment` gives an error.

It usually appear when building the project (but not always). Not during testing.

Erasing the white space fixes it:

`"Hello"#Comment`

**Comment by Gouvernathor** [comment]
Can you show the error message ?

**Comment by renpytom** [comment]
I'm not able to reproduce with. Can I see what the error is?

**Comment by Gouvernathor** [comment]
Yeah, I don't think this would be worth fixing even if it was also present on 8. It's probably due to a change in how str.strip works, though I don't recall reading about such a change.
