### ISSUE TITLE
RenPy doesn't load the translated common.rpy files when switching language

### ISSUE THREAD

**Issue by Konayachi** [renpy/renpy#5203]
### Problem:
Translated strings in common.rpy file doesn't load when the language is switched

### What I did:
I generated new translation files to implement a new language in my project.
After all files were translated by a translator, I put them on the tl folder.
The translated strings were loaded properly except the ones in the common.rpy, shown as following:
![commonrpy doesn't translate](https://github.com/renpy/renpy/assets/65081458/df90f493-50ad-4c7e-9329-3ae761cb02d4)
![commonrpy doesn't translate 2](https://github.com/renpy/renpy/assets/65081458/fb7953ae-4b52-443a-857d-41b5165b4335)
![commonrpy doesn't translate 3](https://github.com/renpy/renpy/assets/65081458/a0503e50-e32e-4b2d-9115-cf8cfe765b06)

This happened to me a few months ago with different language, but I was able to solve it by following the solution in [this forum post](https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=59503&p=531797&hilit=menu+is+translated#p531797).
This time, however, the same solution no longer works.

I'm unable to figure out how to fix this. Is this a bug?

**Comment by Gouvernathor** [comment]
Can you show the code that's in that file ? Also, what language are you using as None language (in the script), and is the language of the translation you're trying to activate Portuguese ?

**Comment by Konayachi** [comment]
Yes, here is the file which translations don't load in game:
[common.rpy.zip](https://github.com/renpy/renpy/files/13766141/common.rpy.zip)
I also need to comment line 943 and 944 because of this error:
![image](https://github.com/renpy/renpy/assets/65081458/ce5e96e9-0a1d-41e8-813f-d9ef81a6112a)

The None language is english, and I'm trying to implement portuguese, yes.

I generated the translation files through the Generate Translations menu in the launcher, typed the language (in this case, portuguese) and pressed the Generate Translations button.
I gave the generated files to the translator, then when I received it, I just overwrote the files that RenPy generated with the files that the translator sent me over.
I don't see any button to import.

The other files such as script.rpy has the translated strings applied correctly without a problem. I only have problem with common.rpy translations that are not reflected while I'm trying to switch the language (as shown in the screenshots).

This happened when I tried to implement french language a few months ago, but I just used common.rpy from RenPy's launcher instead and it solved it ([this aforementioned solution](https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=59503&p=531797&hilit=menu+is+translated#p531797)).
This time, however, using the RenPy's portuguese's common.rpy doesn't solve this.

**Comment by renpytom** [comment]
Can you please send an entire game - not single files?

**Comment by Konayachi** [comment]
Yes I can. May I send it to you in private, @renpytom ?

**Comment by renpytom** [comment]
Sure, please send to renpytom@gmail.com

**Comment by renpytom** [comment]
Looking at your game, tl/brazilianportuguese/common.rpy has: 

```renpy
translate brpt strings:
```

while the rest of the translation has, for example: 

```renpy
translate brazilianportuguese start_b6ffa404:
```

Since "brpt" is not the same thing as "brazilianportuguese", those are two languages. I'd suggest modifying the first file to replace "translate brpt strings:" with "translate brazilianportuguese strings:".

**Comment by Konayachi** [comment]
This works perfectly! It appears that I was careless about this...
I confirm that this is not Ren'Py's problem. This issue may be closed now. Thank you very much!
