### ISSUE TITLE
Menu To Clipboard

### ISSUE THREAD

**Issue by Leowolf93** [renpy/renpy#5204]
Ladies and gentlemen, does anyone have an rpy script that can directly capture menu items from ongoing dialogues in the game? Actually, just obtaining them is enough, as I know how to copy them to the clipboard. I've been working on a translation tool, but currently, I'm unable to access the menu items. Thank you very much.

**Comment by Leowolf93** [comment]
I write this, but can't work.
`init python:
    import pygame.scrap
    import renpy.exports as renpy

    def handle_menu_items(items, *args, **kwargs):
        # Assumption: 'items' is the first positional argument expected by Ren'Py's menu function

        # Convert menu items to string and copy to clipboard
        menu_text = '\n'.join([str(item[0]) for item in items])
        pygame.scrap.init()
        pygame.scrap.put(pygame.scrap.SCRAP_TEXT, menu_text.encode("utf-8"))

        # Return the modified items and other arguments
        return (items,) + args, kwargs

    config.menu_arguments_callback = handle_menu_items
`

**Comment by Gouvernathor** [comment]
The translation for the menu items is managed as string translations, and generated when generating the translation files from the launcher.
You should read the documentation page about [in-game menus](https://www.renpy.org/doc/html/menus.html#menu-arguments) to understand what menu arguments are and why "items" aren't a part of it.

**Comment by Gouvernathor** [comment]
If you still want to copy menu items for some reason, you can add the recently added action to copy something to the clipboard (I don't recall the name but it can be found in the shipped-in doc of the nightly builds at least), pass it the .caption element of the menu item in the "choice" screen (as explained in the menu page of the doc), and put it as the action or alternate action of the menu item's button.

**Comment by Leowolf93** [comment]
> If you still want to copy menu items for some reason, you can add the recently added action to copy something to the clipboard (I don't recall the name but it can be found in the shipped-in doc of the nightly builds at least), pass it the .caption element of the menu item in the "choice" screen (as explained in the menu page of the doc), and put it as the action or alternate action of the menu item's button.

Sorry, but I really read the documentation carefully and tried a lot, but it still doesn't work....

**Comment by Gouvernathor** [comment]
This is the [action](https://nightly.renpy.org/doc/screen_actions.html#CopyToClipboard). You should ask your question in the discord help channels and provide what you made of the choice screen. Questions like this aren't really for github.

**Comment by Leowolf93** [comment]
> This is the [action](https://nightly.renpy.org/doc/screen_actions.html#CopyToClipboard). You should ask your question in the discord help channels and provide what you made of the choice screen. Questions like this aren't really for github.

You are truly a kind-hearted person, and I sincerely thank you for that. I wish you a Merry Christmas. Sorry, I'm new here and not quite familiar with the rules. Going forward, I will discuss any questions I have with everyone on Discord. I've read the link you provided about the CopyToClipboard feature, but maybe I'm a bit slow to understand it. This is a script I wrote earlier, which I placed in the game's directory. When I open the game, it automatically copies the content to the clipboard, and then I can paste the content into a translation tool to translate it.
`init python:
    import inspect
    import pygame.scrap

    def to_clipboard(event, **kwargs):
        if event == "show":
            d = inspect.currentframe().f_back.f_locals
            line = str(d)
            pygame.scrap.put(pygame.scrap.SCRAP_TEXT, line.encode("utf-8"))

    config.all_character_callbacks.append(to_clipboard)`

If this is a menu, one that offers options to choose from, how should I go about it? This issue has troubled me for a long time, keeping me up at night. I hope to receive your assistance with it.

**Comment by renpytom** [comment]
You can enable clipboard voicing using the shift+A accessibility menu. 

Apart from that, you're not asking for something we support, and this isn't really a feature request. So I'm closing it.
