### ISSUE TITLE
Renpy not starting 

### ISSUE THREAD

**Issue by Blastum1** [renpy/renpy#5206]
After running the renpy executable on windows.  The application is monitored in the task manager, does not load the central processor at all, but loads the memory by about 100 MB.  I reinstalled both the old and new versions several times.  downloaded new drivers for the video card.  everything is missing and doesn’t work.  windows 10

**Comment by renpytom** [comment]
Do you have a log.txt from the start attempt?

**Comment by renpytom** [comment]
Closing due to a lack of response.
