### ISSUE TITLE
4K AV1 webm movie files performance

### ISSUE THREAD

**Issue by DebatingPanda** [renpy/renpy#5207]
Hello!
I haven't found any information on this topic yet. I've implemented two 4K AV1 webm videos into my game, and both videos play fine when I play them outside of Ren'Py. However, in-game, they lag horribly. I usually have my CPU limited to 99% so it doesn't overclock itself, if I remove this restriction, the video still lags very badly but not as bad as before. 

Any plans on this topic or should I go back to the VP9 codec? I can provide the video if necessary.

Thanks in advance!

**Comment by renpytom** [comment]
Please provide the video. The color space matters a lot here.

**Comment by DebatingPanda** [comment]
Sorry, I'm a little late, I attached the video to the comment.
It was created with ffmpeg using the av1_nvenc codec and yuv420p pixel format.

[xmas.webm](https://github.com/renpy/renpy/assets/5851011/b9fae33e-5165-483e-819f-50bd959d35d5)

**Comment by renpytom** [comment]
So the issue is that your video is encoded using the tv/limited color range, which required conversion compared to the usual pc/limited color range. Ren'Py doesn't accelerate that conversion, so it's slow, causing the slowdown you see. 

Using the command: 

```
ffmpeg -i test.webm -vf scale=in_range=limited:out_range=full -color_range 2  -c:a copy test2.webm
```

I was able to reduce CPU usage by about 2/3rds.  I'm not sure how great the quality is, though - I'd suggest setting whatever tool you're using to make these videos to compress for pc rather than TV. 

You can see the problem by looking at the output of the ffplay command that ships with ffmpeg. Here's the video you uploaded: 

```
Input #0, matroska,webm, from 'cg/test.webm':
  Metadata:
    ENCODER         : Lavf60.16.100
  Duration: 00:00:03.12, start: 0.000000, bitrate: 18137 kb/s
  Stream #0:0: Video: av1 (Main), yuv420p(tv, progressive), 3840x2160, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn
    Metadata:
      ENCODER         : Lavc60.31.102 av1_nvenc
      DURATION        : 00:00:03.117000000
```

And here's it recompressed: 

```
Input #0, matroska,webm, from 'cg/test2.webm':0KB sq=    0B f=0/0   
  Metadata:
    ENCODER         : Lavf60.3.100
  Duration: 00:00:03.12, start: 0.000000, bitrate: 10036 kb/s
  Stream #0:0: Video: vp9 (Profile 0), yuv420p(pc, progressive), 3840x2160, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn
    Metadata:
      ENCODER         : Lavc60.3.100 libvpx-vp9
      DURATION        : 00:00:03.117000000
```

I'm guessing you may need to tweak the quality settings as well, given the different bitrates. I'm not an ffmpeg expert, though.

**Comment by DebatingPanda** [comment]
I did some tests the last couple hours and it is indeed a little confusing with ffmpeg. During the creation it clearly states that it is not yuv420p (see the code block down below), but whenever I use the command you mentioned, it states yuv420p(tv, ....). 

Your recompressed version isn't av1 anymore unfortunately, but vp9, which I wanted to switch out with av1 since av1 has a better compression rate. I compressed a 80 mb vp9 video file down to 50 mb av1 without loosing any quality at all.

Since I create my videos from frames, I can't use anything beside ffmpeg (I haven't found a good alternative, yet)

Need to go back to vp9 I guess.

```
Output #0, webm, to 'output-AV1-UHD.webm':
  Metadata:
    encoder         : Lavf60.16.100
  Stream #0:0: Video: av1 (Main), rgba(pc, bt709, progressive), 3840x2160, q=2-31, 60 fps, 1k tbn
    Metadata:
      encoder         : Lavc60.31.102 av1_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
```

**Comment by renpytom** [comment]
Ah, I didn't see that. Are you still having the problems with the pc/bt709 avi1 video? That _should_ hit a fast path.

**Comment by DebatingPanda** [comment]
Thanks for the fast reply!

It isn't much better unfortunately. I created the video with the following command:
`ffmpeg.exe -framerate 60 -i %%d.png -c:v av1_nvenc -color_primaries bt709 -color_trc bt709 -colorspace bt709 -cq 25 xmas.webm`

If you want to test it for yourself, here is the video:

[xmas.webm](https://github.com/renpy/renpy/assets/5851011/291347ac-6d7d-4bde-b5f4-b79cc0ac050b)

**Comment by DebatingPanda** [comment]
With some help I managed to have a video with yuv420p(pc, progressive), it still lags the same as a before, also it's about 10-20% bigger in size.

ffplay output:
`Stream #0:0: Video: av1 (Main), yuv420p(pc, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn
    Metadata:
      ENCODER         : Lavc60.31.102 av1_nvenc
      DURATION        : 00:00:03.117000000`

[xmas.webm](https://github.com/renpy/renpy/assets/5851011/9055d889-5a7f-45d1-8c8a-17b7d2074fd3)

**Comment by renpytom** [comment]
I tracked this down to an issue that was causing the movie to reach the end, and then keep trying to read data - even as the next movie in line started up. Each loop would take up a core's worth of CPU... which is probably the reason for the problem. 

Check out the next nightly, it should work better.

**Comment by DebatingPanda** [comment]
Hey there! 
Thanks for the reply and the good work, unfortunately it doesn't seem to do anything for me. I tried it out with both nightly builds (8.2.0.X and 8.1.4.X). I downloaded my latest xmas clip from the last post and used it to have the same basic requirements. Here is a video of the actual in-game main menu:

https://github.com/renpy/renpy/assets/5851011/23f86440-6e9e-4cda-9e2b-b8e96272dc24

The bitrate of the video is, as you already pointed out earlier, quite high with "18137 kb/s". Reducing the quality of the clip, resulting in a 2mb video file for a mere 3 seconds runtime, seems to work, resulting in 7000 kb/s bitrate. It might be just the cheer amount of data which makes Ren'Py struggle. FFplay doesn't want to play a clip with > 10000 kb/s as well. So it might not be a Ren'Py issue per se.

**Comment by renpytom** [comment]
Did you try the 23122804 versions? 

Either way, too high a bitrate could prevent your computer from being able to handle it - it is something you need to consider.

**Comment by DebatingPanda** [comment]
Thanks for the reply! Yes, that's the version shown in the short clip, as well, so that's not the problem. I also checked the ffmedia.c file, the changes are inside. The video clips work fine in vlc-player / win11 movie player. I have also very good hardware, I can assure you that this would be the last problem. 
Does it work on your side with my clip? Maybe it's something I'm doing wrong in Ren'Py?

```
config.screen_width = 3840
config.screen_height = 2160

...

video = f"{backgroundPath}xmas.webm"
gui.main_menu_video = Movie(play=video, size=(config.screen_width, config.screen_height))

...

screen main_menu():
    ## This ensures that any other menu screen is replaced.
    tag menu

    add gui.main_menu_video
    ...
```
