### ISSUE TITLE
`config.replace_text` before substitutions

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5208]
Hello! I use `config.replace_text` to add fancy text formatting to dialogue, which lessens the need for editing. Today I tried to implement similar toil-reduction to some text tags that I normally use, namely with use of `{w}`.

Code for this would look like this:

```python
def replace_text(s: str):
    # replace periods between sentances but not at the end of a sentence
    s = re.sub(r'(?!\s)\.(?<!$)', '.{w}', s)

    # replace commas between words but not at the end of a sentence
    s = re.sub(r'(?!\s),(?<!$)', ',{w=0.25}', s)

    return s

config.replace_text = replace_text
```

My use case here is that I want to add pauses into my dialogue in a standard way. So for example, periods between words get translated to `.{w}` and commas get translated to `,{w=0.25}`. However, this does not work how you might expect since [the documentation states that](https://www.renpy.org/doc/html/config.html#var-config.replace_text):

> The function is called after substitutions have been performed and after the text has been split on tags, so its argument contains nothing but actual text.

Meaning that `.{w}` will be printed as actual dialogue text. This is not what I wanted here, and it would be great if there was a way to add such text transformations _before_ substitutions have been performed. 

There might be some other way to do this that I've overlooked, so please let me know if that's the case.

**Comment by shawna-p** [comment]
I think you probably want [config.say_menu_text_filter](https://www.renpy.org/doc/html/config.html#var-config.say_menu_text_filter) instead

**Comment by furudean** [comment]
Yep, that totally is what I want! Maybe we could improve the documentation so that these reference each other?

**Comment by renpytom** [comment]
I've made the changes.
