### ISSUE TITLE
Viewport animation when manually scrolling

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5217]
I suggest doing animated scrolling the same way the Scroll(delay) action works, but when clicking the scrollbar. This could be enable by writing:

```
viewport:
    scrollbars "vertical"
    delay 0.1  # the same way the Scroll() action
```

![2023-12-27 22_39_46-Window](https://github.com/renpy/renpy/assets/87047775/276524e2-d83f-4fb9-888f-b932c1cd4675)

That way is consistent with the Scroll action, and up to date with modern GUIs, for example, check Discord for reference. Also note that the scrollbar should be animated to.

**Comment by renpytom** [comment]
I don't like this behavior, so I'm not going to add this to Ren'Py.
