### ISSUE TITLE
gui.unscrollable should be included by default

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5218]
According to the docs and the gui.rpy file, gui.unscrollable is implied to have a built-in functionality for all scrollbars.

![2023-12-27 23_51_39-Window](https://github.com/renpy/renpy/assets/87047775/0beecfa6-360a-4ea9-a283-ef9ea275311a)

But on new projects it does not work because it's not included on the basic style on screens.rpy, but on the game menu style instead. 

![2023-12-28 00_00_27-Window](https://github.com/renpy/renpy/assets/87047775/849429e6-1358-4d38-b212-5d4177d67919)

So this isn't applied to any new viewport by default, contradicting what is implied. Sure, you can add it, but it creates confusion, at least it did for me when I started using Ren'Py because I thought it was a built-in variable instead of a custom/manual one.

By adding it to all defaults projects it should work.

![2023-12-28 00_06_07-Window](https://github.com/renpy/renpy/assets/87047775/09ee134a-e3f9-466f-ba63-6e8037924601)

** Also , it should be documented that "insensitive" is also a valid option due to it being the same as the unscrollable style property. For future maintenance of the code, I suggest editing it to point to that property documentation, or to remove the variable all together.

**Comment by renpytom** [comment]
I'll take a look at the documentation, but the change to scrollbar and vscrollbar is too much - I don't plan to do this. I this case, "the GUI" refers to the game menu, main menu, etc - not to the game proper.
