### ISSUE TITLE
Renpy crashes when trying to render NotoColorEmoji font

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5220]
I wanted to use Google's popular NotoColorEmoji when replacing emoji textcode, and did this:

`"{font=NotoColorEmoji.ttf}😏{/font}"`

But an exception occurs:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 100, in script
    "{font=NotoColorEmoji.ttf}😏{/font}"
FreetypeError: 23: b'invalid pixel size'
```

Now I read [here](https://github.com/python-pillow/Pillow/issues/6166), that you have to use size 109 for that font. 

`"{size=109}{font=NotoColorEmoji.ttf}😏{/font}{/size}"`

But doing that just makes Renpy crash without even throwing an error, but leaving this inside `log.txt`:

```
renpy.text.ftfont.FreetypeError: 7: b'unimplemented feature'
Exception ignored in: 'renpy.text.ftfont.FTFont.get_glyph'
Traceback (most recent call last):
  File "/home/cosmos/Programs/renpy-stable/renpy/text/text.py", line 258, in glyphs
    rv = fo.glyphs(s)
renpy.text.ftfont.FreetypeError: 7: b'unimplemented feature'
```

**Comment by renpytom** [comment]
Not a bug, it's not supported.

**Comment by renpytom** [comment]
(Specifically, noto use SVG, while Ren'Py will be supporting the COLRv2 standard.)

**Comment by m-from-space** [comment]
> Not a bug, it's not supported.

Well, thank you, Tom. Is there any colored emoji font, that is supported by Renpy as of now?

**Comment by renpytom** [comment]
8.2 will ship with TwemojiCOLRv0.ttf .
