### ISSUE TITLE
Certain "grounds" in imagemap make hotspots not working.

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5225]
I'm not sure this is a bug, or isn't supposed to work in the first place.

So I wanted to create an imagemap, with a transparent "ground" (meaning, that I only want the hotspots to work).

So I tried this:

```
imagemap:
    ground Null(width=1920, height=1080)
    hotspot ...
```
This doesn't throw an error, but the hotspots are not working. Same problem applies to:

`ground Solid("#000")` (make it transparent or not, doesn't matter)

I would expect that this should be possible, since both `Null()` and `Solid()` return a Displayable.

**Comment by shawna-p** [comment]
`ground` is not considered for hotspots and can simply be omitted from an imagemap declaration if not needed. I suspect the issue is elsewhere with your hotspots. Make sure they have an action, for example, and your **idle** image must either have non-transparent areas inside the hotspots, or you need to set `alpha False` for the imagemap.

**Comment by m-from-space** [comment]
> `ground` is not considered for hotspots and can simply be omitted from an imagemap declaration if not needed. I suspect the issue is elsewhere with your hotspots. Make sure they have an action, for example, and your **idle** image must either have non-transparent areas inside the hotspots, or you need to set `alpha False` for the imagemap.

Ground is definitely needed, because it will throw an exception when not using it and then hovering over any hotspot. But you are totally right about the `alpha False` property, I didn't know about that one before. So thanks, this makes the empty Null() Displayable work. :)

**Comment by m-from-space** [comment]
> and your **idle** image must either have non-transparent areas inside the hotspots, or you need to set `alpha False` for the imagemap.

By the way, an "idle" image is not needed, I never use one in my imagemaps. Only using ground.
