### ISSUE TITLE
Maybe an idea to improve cache

### ISSUE THREAD

**Issue by bober-gith** [renpy/renpy#5226]
This is based on profiling one of my project, I hope the observations are correct.

For now, if you set let's say have 700mb of cache for ren'py, you press new game, you start playing for a while, the cache fills up slowly until it reaches 700mb.
At this point it will never decrease on its own unless you quit the game or go back to the main menu, or clear it manually.

Problem encountered: 
Performance is excellent until the cache reaches 700 MB and stays there. After that, it seems that every new piece of data from the moment it reaches the limit is slower, I notice spikes start appearing when it gets into this state. 
In these 700mbs, there are some textures that are no longer needed and it seems that the action of replacing the existing cache is slow.

As for the idea, I'm not very bright but was thinking maybe something like having a small configurable buffer cache that's not part of the 700mb limit and only serves to take new data while the old one is flushed. Something that allows preloading to behave as well as before reaching the 700mb limit as long as you don't need those 700mb at the same time.

**Comment by renpytom** [comment]
Do you have numbers from your profiling? Removing something from cache should be fast.

**Comment by bober-gith** [comment]
Okay. I'm not sure either what's going on then but something with the cache I think because when it spikes the cache resets to 0 mb and this occured when the cache was hitting my limit set but I'm not sure if it's because of the limit or something else, and it stranges that it resets the cache to 0mb during the spike, I have recorded one of the spikes with the profiler running, I'll send the details by email to keep the project anonymous if that's not a problem.

**Comment by bober-gith** [comment]
Here is a repro on a template project:
[Cache_test2.zip](https://github.com/renpy/renpy/files/13801684/Cache_test2.zip)

The template preloads a lot of images at the beginning of the script, then when you start moving in the script forward and when new images are being loaded and the cache is close to the limit, spikes start appearing. The spikes are less important here than on a real project with other things running, but I'm thinking it's the same thing happening.

Normal:
![image](https://github.com/renpy/renpy/assets/78823063/6b7a7c78-037a-4b68-b977-5abe71c93c05)

Spike:
![image](https://github.com/renpy/renpy/assets/78823063/54bcf8d5-8b31-4db0-88a6-098729995b0a)

**Comment by renpytom** [comment]
Your demo seems like it's filling up the image cache with hard preload images, then continuing to fill it by displaying many images on top of each other. Performance is going to drop once the cache fills up - but given that everything is either forced to be there, or shown in the current frame, I don't think anything can be done. 

The script:

```renpy
    show 1
    e "1"
    show 2
    e "2"
    show 3
    e "3"
    show 4
    e "4"
    show 5
    e "5"
    show 6
    e "6"
    show 7
   e "7"
```

nerver hides an image, so everything will stay in the cache.

**Comment by bober-gith** [comment]
Ah, my bad sorry, I totally forgot about clearing scene/hide images in the template. In the original project, I do clear scenes and it's happening, but maybe it's a different problem. I'll keep looking if I can repro it one way or another.

**Comment by renpytom** [comment]
Sure. 

I'm thinking this isn't the right place for that new issue. I think there can be improvements in prediction - right now, Ren'Py will only predict  images if there is a 200ms pause in drawing the screen. That's something I'm going to look into addressing.

**Comment by bober-gith** [comment]
I have to find the solution for it but I have no clues, the difference with the template is that it's not even hitting 100% usage when it happens so it seems different, and I think it equals a crash on android if it happens so I'm really looking into it. Any rough ideas of what could cause spikes like this by any chance?
Awesome and looking forward to it for what is planned.

**Comment by renpytom** [comment]
My guess is you might be blowing out the cache, causing your game to do unpredicted image loads, consume too much memory, and then crash on limited android systems.
