### ISSUE TITLE
[Doc]Question for Document expression

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#5227]
I have some question about doc

1. My interpretation is that alt property can be set to a string in that class, a string in that class's constructor and Python property which returns a string. But what does "it" in '"it" or it can be ...' means? 
https://github.com/renpy/renpy/blob/2f38077f67830573dae4e2b1e8f9ca668708d095/sphinx/source/screen_python.rst?plain=1#L91-L97

2 I couldn't understand the below document.
"with the specificity that in that case, a multiple group's name _is_ part if the pattern, and that the format_function passed to the layeredimage is ignored."
This means that format_function is ignored when the group has multiple keyword?
What does "\_is\_" in "name \_is\_ part if the pattern" mean?

https://github.com/renpy/renpy/blob/2f38077f67830573dae4e2b1e8f9ca668708d095/sphinx/source/layeredimage.rst?plain=1#L285-L293

**Comment by KiloOscarSix** [comment]
1. My understanding any of these definitions are permitted:
```py
class Action:
    alt = "My Action"
    
    def __init__(self):
        alt = "My Action"
        
    @property
    def alt(self):
        return "My Action"
```

**Comment by Gouvernathor** [comment]
1. yeah there's a typo
2. using \_underscores\_ was supposed to create _italics_, somehow it didn't work. I'll fix that too.
You have to take the sentence in full :
> ...scan its list of images for those that match the group's pattern (see [below](https://www.renpy.org/doc/html/layeredimage.html#layeredimage-pattern)), with the specificity that in that case, a multiple group's name _is_ part if the pattern, and that the format_function passed to the layeredimage is ignored.
- The format_function is normally used to customize the pattern a given layeredimage will use for attributes declared explicitly (non-`auto`) with no explicit displayable. But in the `auto` mechanism, the default pattern will be used regardless of the format_function you may have passed to the layeredimage.
- The name of a group that is `multiple` is normally not included in the pattern, but again in the specific case of the `auto` mechanism, the name of the group _is_ included as if it were a normal group. This discrepancy I adressed in my [layeredimage2](https://github.com/Gouvernathor/layeredimage2) project.
