### ISSUE TITLE
position type can't be used in atl block

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#5234]
In doc, xsize position(10, 0.5) is acceptable, but actually it cause "NameError: name 'position' is not defined".
"xsize renpy.atl.position(10, 0.5)" works
This was tested by Ren'Py 8.2.0.24010103+nightly.

https://github.com/renpy/renpy/blob/9c272b9d45fb15644b486357b1541472774246c1/sphinx/source/changelog.rst?plain=1#L136-L141

**Comment by Gouvernathor** [comment]
Yeah, I forgot to add it in the default namespace, fixing it.
