### ISSUE TITLE
[Issue] Problems reading files in binary mode with `renpy.open_file()`

### ISSUE THREAD

**Issue by CharlieFuu69** [renpy/renpy#5239]
Greetings to all.

Today, I come to report a bug that has me a little upset. When trying to open a file in binary mode using `renpy.open_file()` (in Ren'Py 8) it seems to keep reading it in text mode.

First, the problematic code snippet is this:

![image](https://github.com/renpy/renpy/assets/77955772/521e5835-13e2-4534-8e6e-8d506d340377)

As you can see, I have made a kind of condition to open the files with one function or another, in case the code I made is running on Ren'Py 8 or Ren'Py 7. Consider the `self.fn` attribute as a string containing the path of the file to open, relative to the project's `/game` folder.

The problem is that `renpy.file()` works without problems in Ren'Py 7 (exactly using v7.4.11), opening the file as binary. Now if we execute exactly this code in Ren'Py 8, the problems begin, returning the following error:
```
TypeError("a bytes-like object is required, not 'str'")
```
Of course, this code expects to receive bytes, and is instead receiving a string, giving me the impression that the file is still being opened in text mode ("r"), instead of "rb".

Now, why did I put `False` in the `encoding` parameter? Well, I proceed to cite the [Ren'Py Documentation: renpy.open_file()](https://www.renpy.org/doc/html/file_python.html#renpy.open_file):

> **encoding**
> *If given, the file is open in text mode with the given encoding. If None, the default, the encoding is taken from [config.open_file_encoding](https://www.renpy.org/doc/html/config.html#var-config.open_file_encoding). If False, the file is opened in binary mode.*

According to this, passing `encoding=False` to the function should open the file in binary mode, but I think it still opens it in text mode, otherwise that exception would not occur.

Due to internal code issues, this file must be read as binary and not as text, in addition to having the ability to be read from an RPA, which this function allows.

If you didn't need to read it from an RPA, then you would just use the standard function:
```python
open("....", "rb")
```
But is not the case.

**Comment by CharlieFuu69** [comment]
Full code:
```renpy
def load(self):
            """
            Este método carga y procesa las secuencias de un archivo beatmap de
            una canción en específico. El archivo `.beat` debe ser señalado en el
            momento en que se crea una instancia de la clase.

            Esto se llama automáticamente cuando la clase es instanciada. No recibe
            ningún argumento ni tampoco retorna datos.
            """

            try:
                if renpy.version_tuple > (8, ):
                    print("Opening as Ren'Py 8")
                    with renpy.open_file(self.fn, encoding=False) as beatmap:
                        bmpdata = beatmap.readlines()
                else:
                    with renpy.file(self.fn) as beatmap:
                        bmpdata = beatmap.readlines()

                for keypad in bmpdata[1:]:
                    keypad = keypad.replace("\n", "").replace("\r", "").split("|")

                    if len(keypad) > 1:
                        left = keypad[0]
                        right = keypad[1]

                        if not "End" in left:
                            self.lane_L.append(eval(left) + self.offset)

                        if not "End" in right:
                            self.lane_R.append(eval(right) + self.offset)


                self.lane_L = tuple(self.lane_L)
                self.lane_R = tuple(self.lane_R)

                beatmap.close()

                self.sprite_creator()

            except Exception as open_error:
                raise RhythmBeatsException("Beatmap read error: %s" % repr(open_error))
```

Maybe it's my mistake, but I leave this code for your analysis.

**Comment by qTich** [comment]
In which version 8 specifically does this happen? Because in 8.1.3 and nightly - everything works correctly.

**Comment by qTich** [comment]
> ```py
>keypad = keypad.replace("\n", "").replace("\r", "").split("|")
> ```

You open the file in binary, but append replace for the string without doing the encode.

**Comment by CharlieFuu69** [comment]
Curse. I knew it was my mistake, but... why did this work well in old versions?
I will mark this Issue as closed, but I have that question, because the code as it is, worked in v7.4.11

**Comment by qTich** [comment]
> Curse. I knew it was my mistake, but... why did this work well in old versions? I will mark this Issue as closed, but I have that question, because the code as it is, worked in v7.4.11

That's right, the approach has changed since then:
https://github.com/renpy/renpy/commit/084b01745ef82624b13811ff1af6f2365a4a97c9

The default `config.open_file_encoding` is exactly `False`.
