### ISSUE TITLE
Windowed fullscreen (Borderless Windowed) mode on Windows

### ISSUE THREAD

**Issue by rakleed** [renpy/renpy#5241]
Could you please add Windowed fullscreen (Borderless Windowed) mode on Windows? In this case, you can quickly minimize the game or quickly switch to another application, but the game will occupy the entire screen.

https://www.renpy.org/doc/html/preferences.html#var-preferences.fullscreen

**Comment by renpytom** [comment]
That's the mode Ren'Py has used for years.

**Comment by Gouvernathor** [comment]
In typical borderless window mode, you can show anything in front of the window. With renpy, switching windows while renpy is in the process of showing itself in fullscreen (when it's reloading for example) will most of the time cause renpy to pmget displayed above the window that is focused. When switching from renpy to something else there is often the screen flicker when it adapts to the fullscreen.
That doesn't happen in normal borderless windows.

**Comment by renpytom** [comment]
When I run on 8.1 on windows, it doesn't cause the screen to flicker at all. And if you look at gl2, initially starting in fullscreen is handled by: 

https://github.com/renpy/renpy/blob/master/renpy/gl/gldraw.pyx#L433

While changing to fullscreen is ultimately handled by: 

https://github.com/renpy/pygame_sdl2/blob/master/src/pygame_sdl2/display.pyx#L302

Both use FULLSCREEN_DESKTOP. So I don't know why you get the flicker.

**Comment by rakleed** [comment]
@renpytom can you then rename Fullscreen to Windowed fullscreen or Borderless Windowed?

But I, like @Gouvernathor, doubt that the current Fullscreen mode is still Borderless Windowed. Since in Apex Legends (or any other non-Renpy game) in Borderless Windowed mode there is no blinking when switching to another window, but in A Date with Death (or any other Renpy game) there is blinking of the game window itself. And usually this blinking occurs in games that run in Fullscreen mode. Here's a screen recording (poor quality since GitHub doesn't allow uploads larger than 10MB):

https://github.com/renpy/renpy/assets/19418601/80570a56-ac97-4978-b651-01e5c76198cb

Can you check in the current version of Windows 10/11? Otherwise, [Windows 8.1 has already reached the end of its life cycle](https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93).

And unfortunately I don’t have enough Python knowledge to understand the examples you gave, I’m describing the experience from the point of view of an end user.

**Comment by wavebeem** [comment]
I'm playing a Ren'Py game from late 2025 and every time I alt-tab out of it I get black flickering. Also, the window is "reluctant" to give up its place. I often have to press Win+1 _three times_ in order to switch to my Firefox window. alt-tab is similarly challenged at effecting its change. but once i successfully switch windows, the switching problem goes away for a while. the flickering stays no matter what. i did try Shift+G, disabling powersave, and restarting the game. But the problem persists

**Comment by izarii-dev** [comment]
Ren'Py's "Fullscreen" has the same behavior as exclusive fullscreen in other game engines for me too, I'm pretty sure it's not borderless/windowed fullscreen. I think this issue should be reopened
