### ISSUE TITLE
Side Image Loading Glitch - Change Transform Causes issues

### ISSUE THREAD

**Issue by spirevn** [renpy/renpy#5242]
Hi,

If I make a save while a side image is on screen, once I re-load this save from the main menu or when restarting the game, the side-image I saved on will randomly flicker on the screen -- usually between narrator lines, or during window transitions.

From then on, that save will forever have that first side image flicker, very quickly on and off screen, most commonly on window transitions, but also in-between other side images at times.

The issue seems to be linked to having "Change Transform" enabled, as it goes away when I remove this code. Interestingly, "Same Transform" works fine. 

Strangely, the save glitch doesn't occur from loading within the game, only if you go back to the title menu and load from there. Also strangely, the "Change Transform" coding will work fine within the game and when loading within the game, the glitch is only associated with the save file when loaded from the main menu.

I have tried the fix listed on #5151 from the66F95 , as well as tried installing 8.1.4.23112903+nightly which said to have fixed similar the issues, but neither makes a difference to this glitch.

So weather the latest version of nightly, or 8.1.3, the issue persists. 

As an extra test, I ran my game as-is through Renpy 7.4.2 -- and here I had no issues whatsoever, the glitch did not occur using all the exact same code that I built using 8.1.3. This seems to confirm all my testing, that it's likely not my code but something in the engine, as the "change_transform" coding I'm using works fine in Renpy 7.4

It's not the end of the world if I have to remove the change transform transitions from my side images, but given the glitch, and given my code all works fine in Renpy 7.4, I thought it was worth raising to see if there is a fix.

EDIT: Turns out change transform was not the culprit. See the video below for a run-down of the issue.
EDIT: See my post below for important new information.

Any help would be appreciated.

**Comment by spirevn** [comment]
Some extra context -- it seems to be specifically like to the "old" part of change_transform. 

So, this will not trigger the glitch:

```
transform change_transform(old, new):
    contains:
        new
        yalign 1.0
        alpha 0.0 xpos 0.0 xanchor 0.1 
        linear 0.15 alpha 1.0 xanchor 0.0 

define config.side_image_change_transform = change_transform
```

While this will:

```
transform change_transform(old, new):
    contains:
        old
        yalign 1.0
        alpha 1.0 xpos 0.0 xanchor 0.0
        linear 0.15 alpha 0.0 xanchor 1.0
    contains:
        new
        yalign 1.0
        alpha 0.0 xpos 0.0 xanchor 0.1 
        linear 0.15 alpha 1.0 xanchor 0.0 

define config.side_image_change_transform = change_transform
```

The type of transform has no bearing, weather a Dissolve etc.

Somehow the "old" is getting saved and causing a glitch when loaded from the main menu?

**Comment by renpytom** [comment]
Any chance you can put together a small demo of this?

**Comment by spirevn** [comment]
> Any chance you can put together a small demo of this?

Thanks for the response! It's great to meet you (I recently saw you in the Visual Novel Design Youtube interview, that was great btw)

Okay, I've put together a video below. Enable audio while you watch - I explain through all the issues as I go and make it very clear, I go through the code and do a bunch of testing, it's quite thorough so hopefully watching it all will give you a good insight into the issue.

It also turns out that the Change Transform is _NOT_ the cause as I believed, as the glitch returned even when I deleted it out. In fact, the issue happens even when I go back to base code and remove all custom transitions. I go through all that in my video, as well as talk through additional testing I've done.

Here is a video that demos the issue and my code / explains my testing:

https://drive.google.com/file/d/1eoDwGvckKkxoDd19FnyRBSLALQkFvm8x/view?usp=sharing

It's just a google video so you can watch without downloading at the above link^^

Thanks for your help.

**Comment by renpytom** [comment]
Can I have the game and your savefiles, so I can try to repeat it. 

Ideally, a save file that was created in 8.2, so I can be sure this isn't being baked in the savefile by an old version.

**Comment by Rotzumey** [comment]
Incredible timing with this post because I am coincidentally running into the same issue and seeking a solution as well. This fixed the problem for me based on what [the66F95](https://github.com/the66F95) had done:

Step 1: Go to renpy file directory in renpy/common/00gamemenu
![image](https://github.com/renpy/renpy/assets/90002042/f5915394-9ea2-4500-8ed0-94840128be03)
Step 2: Add two lines of code at line 107:
        store._side_image_attributes = None
        store._side_image_attributes_reset = False        
![image](https://github.com/renpy/renpy/assets/90002042/f09d3442-72b7-4774-bb83-2579457703d8)

And that's it. That worked for me.

**Comment by spirevn** [comment]
> Incredible timing with this post because I was coincidentally running into the same issue and seeking a solution as well. I had done what [the66F95](https://github.com/the66F95) suggested and it worked for me:
> 
> Step 1: Go to renpy file directory in renpy/common/00gamemenu ![image](https://private-user-images.githubusercontent.com/90002042/294645471-f5915394-9ea2-4500-8ed0-94840128be03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MTIzOTIsIm5iZiI6MTcwNDUxMjA5MiwicGF0aCI6Ii85MDAwMjA0Mi8yOTQ2NDU0NzEtZjU5MTUzOTQtOWVhMi00NTAwLThlZDAtOTQ4NDAxMjhiZTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDAzMzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MDIzNzBjMmMxYjc2MzdmYjk2YmYyZWNjNTZjNDQ0ZWYzZThiZjBlMDAxZDFhZWUyNWI4M2RmMjM3ZDJlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dSBhFYmJDyhRNvyATevkJWmd-U2IPwA5Wa1B4zWj8Lk)
> 
> Step 2: Add two lines of code at line 107: store._side_image_attributes = None store._side_image_attributes_reset = False ![image](https://private-user-images.githubusercontent.com/90002042/294645507-f09d3442-72b7-4774-bb83-2579457703d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MTIzOTIsIm5iZiI6MTcwNDUxMjA5MiwicGF0aCI6Ii85MDAwMjA0Mi8yOTQ2NDU1MDctZjA5ZDM0NDItNzJiNy00Nzc0LWJiODMtMjU3OTQ1NzcwM2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDAzMzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZGY1OTY0ZTBmOTRhYzkwOTAwOGU4OWQ2ZGM1YTg2Y2ZmMTdhN2IyYjE4MDg2MmQzYTZmZGU4NmIzYjg3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gnaHuZDVnRT1XbdBkbBcydRem9GU52puha_VQjS2f2g)
> 
> I know you said you already tried this fix, but I just wanted to share that this worked for me.

Thanks, I have done this as you've said, and I also tried running it through the latest nightly version with has this fix, but unfortunately neither worked. Thanks for sharing it though -- it does feel like the issue I'm having is related?

**Comment by spirevn** [comment]
> Can I have the files needed to build game and your savefiles, so I can try to repeat it.
> 
> Ideally, a save file that was created in 8.2, so I can be sure this isn't being baked in the savefile by an old version.
> 
> You can share it with [renpytom@gmail.com](mailto:renpytom@gmail.com)

Thanks, I'll do that -- my game folder is quite bloated, so I might duplicate it and cut it down a bit, then share it with the save files as you've suggested. It might take me a day or so but I'll email it as soon as I can. Thanks again for the help!

**Comment by Rotzumey** [comment]
Nevermind, the bug is back. Let me know if you figure anything out. 😅

**Comment by mal** [comment]
@Rotzumey your case as presented does not appear to be valid.

Condensed bug history:
- Present in 8.0.3.
- A fix landed in 8.1.3 (but contained a typo, which is why some creators are still seeing this issue).
- Typo fixed in as yet unreleased 8.1.4/8.2.

The change you made to your local copy of 8.0.3 is based only on the typo fix and does not include the original fix from the 8.1.3 cycle, which is why I wouldn't expect it to resolve your issue. I'd suggest instead downloading a nightly release and testing with that.

**Comment by the66F95** [comment]
even if you use a build containing the fix, affected save files still produce the "ghost" sideimage.
add `$ _side_image_attributes = None` to `label after_load:`, and no, you don't need to block rollback here.

**Comment by spirevn** [comment]
> even if you use a build containing the fix, affected save files still produce the "ghost" sideimage. add `$ _side_image_attributes = None` to `label after_load:`, and no, you don't need to block rollback here.

Even with the latest builds, when I create new saves they also trigger the glitch. I even deleted all old saves, persistant data, recompiled, only used the latest nightly build - and the glitch still occurred with new save files?

I will try what you've suggest. Which rpy file contains the "after_load" label? Just to make sure I'm understanding you, you're saying to add the `$ _side_image_attributes = None` anywhere in the block under the `label after_load:` - correct? Thanks for the help!

**Comment by danac78** [comment]
@spirevn If you have not used it before, it after_load isn't there. It is a special label you can use to tell Renpy want to do after you load a save file. So, you need to create the label in any rpy file in the game folder.

**Comment by spirevn** [comment]
> @spirevn If you have not used it before, after_load isn't there. It is a special label you can use to tell Renpy what to do after you load a save file. So, you need to create the label in any rpy file in the game folder.

Got it, I'll look it up and try it. Thanks -- I just thought it might be in one of the rpy files in the common folder, but that makes sense. I haven't used it before but I'll see if adding this fixes the issue.
