### ISSUE TITLE
cache the old translations id before generating a new id

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#5244]
I was thinking that the id of the dialog string could be saved before a new id is generated, and in this way allow both ids to coexist. This would solve the problem of having to translate the game from 0 because the ids do not match the new ones.

Maybe this is not in the plans at the moment, but I think it should be taken into account to adjust how Ren'Py generates translations or id. One idea to address this issue is to have both the old id and the new id coexist and allow the translation to not break. For example: If the translation of the new id does not exist renpy can search with the old id and compare the strings looking for a match, otherwise search in the new id.

one form of storage could be a json with these characteristics:

/renpy/projects/test/game/cache/translations.json
```json
[
      {
          "id": "start_b",
          "old_id": "start_a",
          "character": "e",
          "old_dialogue": "Helle world",
          "new_dialogue": "Hello world",
          "line": 8
      }
]
```

being a renpy array it could traverse and search for matches in both dialogs and ids. Of course, this json must exist inside the game so that renpy can map it and search for matches. Whenever a dialog is updated renpy would look for the translations.json file and update or create `old_dialogue`, `id`,`old_id`,`character`, `new_dialogue` and `line`.

line` could be used to compare and search if that line exists with the content (suppose line 8 is deleted and the dialog does not match, then renpy will remove that translation from the cache).

this is just one way of approaching the subject, but I think that some alternatives should be considered to keep the translations working without breaking them.

On the other hand, inside the file in `tl/[lang]/script.rpy` could contain a `old_id` tag to link that translation with the json.

```rpy

translate lang start_b:

    old_id "start_a"
    e ""

```

in the dialog extraction (.tab)

```
Old_Identifier	Identifier	Character	Dialogue	Filename	Line Number	Ren'Py Script
start_a	start_b	e	Has creado un nuevo juego Ren'Py.	game/script.rpy	8	e "[what]"
```

and this would basically be my proposal and idea.

**Comment by renpytom** [comment]
I'm confused, since regenerating translations shouldn't change the IDs.  What are you doing that is causing translation IDs to change? The only thing that factors into translation IDs are: 

* The source code of the line of dialogue. (Not including any 
* The label before the text.
* The count of how many times the same code has appeared inside the dialogue.

The translation system is designed so that you should get the same TLids if you retranslate from scratch. Do you have an example of where that's not the case?

**Comment by Neyunse** [comment]
> I'm confused, since regenerating translations shouldn't change the IDs. What are you doing that is causing translation IDs to change? The only thing that factors into translation IDs are:
> 
> * The source code of the line of dialogue. (Not including any
> * The label before the text.
> * The count of how many times the same code has appeared inside the dialogue.
> 
> The translation system is designed so that you should get the same TLids if you retranslate from scratch. Do you have an example of where that's not the case?

Yes, it sounds confusing. I mean if the content of the dialog changes because of some correction. I understand that there is `e "hello world" id {id}`, but this idea would be profitable in case there are several changes (like corrections) in different dialogs or are moved to another label. it is a bit annoying to have to send the translation to translate everything again, this would be an extra layer to prevent that if several dialog lines (src) that are changed or moved can still exist and be valid. (it can also serve if for some reason the id generation fails, renpy will already have where to look) I understand that it may not be a priority this proposal (or valid) but I wanted to share this idea so that translations that have significant changes are not broken.

for example: suppose there is a recently released game and it has a translation, but the original dialogs turn out to have text errors in several lines (more than one) and you correct the dialogs, generate the translation and forget that they changed the ids. The game that was updated lost lines of dialog or they are not translated, the most common would be to fix it manually or add the id to the dialog but in games with many lines of dialog it can be a tedious thing to fix. And this alternative can help a little in those cases.

on the other hand, if for some unknown reason renpy got confused and broke the connection with the translation, this could be used to solve that.


I don't know if you understand what I'm getting at, sorry.

**Comment by renpytom** [comment]
I don't think that this additional layer is needed. 

You either want the translators to re-translate the line, so you just change it. Or you want to keep the same translations, so you update the line to include the id. I don't see how having a second file to change helps anything. 

Rejected.

**Comment by renpytom** [comment]
I'll point out that Ren'Py puts new translations at the bottom of the translation files, to make it easy to figure out what's changed. It also flags the translations with TODO comments, making it easy to find them.
