### ISSUE TITLE
Chromebook SDK for RenPy major issues

### ISSUE THREAD

**Issue by Syansyaru** [renpy/renpy#5253]
- Projects directory unable to be generated automatically (Fix: Make New folder called "projects" and then attach the directory path to it
- Upon creating a project, many files are missing [script.rpy, audio and images must be added manually]
- Upon testing a project, there are many, many errors. Attached one as part of files.
[Test.zip](https://github.com/renpy/renpy/files/13868898/Test.zip)
[Test_Project_4PyTest.zip](https://github.com/renpy/renpy/files/13868903/Test_Project_4PyTest.zip)

**Comment by HorBro38** [comment]
I assisted this user on the Discord to try and sort this out.  They reported issues with their project, did some testing with them and after a reinstall of the SDK they are still seeing an issue with the majority of files don't generate on new project creation (Test_Project_4PyTest.zip is a brand new project after SDK reinstall, no changes by user).

It looks like it's not generating most of the correct files/dependencies; I'm not familiar enough with Chromebooks to advise further.  Figured we should open up a git issue for assistance on this, thanks.

**Comment by renpytom** [comment]
My guess: Your chromebook ran out of ram trying to run 2 copies of Ren'Py at the same time, which it needs to do to generate a game.  You might want to try closing everything that isn't Ren'Py - including Chrome. 

Which chomebook model is it?
