### ISSUE TITLE
Problem about using #4562 code about applying transform on whole layer

### ISSUE THREAD

**Issue by birctreel** [renpy/renpy#5255]
Apology for my last reply on #4562 . I should post it here.
First, thanks for @colinharvie 's code and idea. It is fascinating and very useful!! I have the very same need as the author of #4562 , that is, to apply a shader to a whole layer, and keep it that way. So I tried the code there.
Here are some problems I faced. Hope someone would have any idea to fix that!

Basically, my goal is to apply a vintage shader effect to my master layer. Here are those problems:

1. when I tried the first part code of #4562, it mute my camera moving.
Detailed:
The first part code of #4562  is about applying a whole transform to the master layer. It did work without error! However, when I write about:
`    camera:
        perspective True
        subpixel True xpos -423 
        ypos -252 
        easein 20.00 ypos -639 ` 
every camera moving is gone and it just keep it there without moving.

2. When I tried the second part code of #4562 , it mute all the interaction even the quit button.
Detailed:
The second part code is applying the shader to all the showing screen of renpy game, though I don't intend to apply the shader on layers other than master. I'm so desperate to try every possibility :)
And it works too! Every display part is added the shader and it looks beautiful! However new problem comes, it seems my interaction is all muted and I can't play the game anymore.

Is there anyway we can fix the two problems, to apply a shader to the whole layer, while using perspective True camera, with moving and interaction?

Thank you for reading! I hope we can work this out :D
```[tasklist]
### Tasks
```

**Comment by renpytom** [comment]
What you're replying to isn't part of Ren'Py, so it isn't supported in the tracker. I'm probably going to address #4562, though.
