### ISSUE TITLE
Can't find the namespace of objects defined by the image statement

### ISSUE THREAD

**Issue by ZYKsslm** [renpy/renpy#5257]
# Can't find the namespace of objects defined by the `image` statement

For some reasons, I need to run codes just slimilar to the following, but it occurred an error.

## codes:

```renpy
image tm:
    "images/tm.jpg"
    zoom 0.7

label start:
    $ img = eval("tm")
    show expression img
    return
```

## error:

```
NameError: name 'tm' is not defined
```

---

However, it can successfully run if changing it like this:
```renpy
define tm = Image("images/tm.jpg", oversample=2)
```

And this one can't.

```renpy
image tm = Image("images/tm.jpg, oversample=2)
```

---

I have used the builtin function `globals` to check all of variables. Obviously, python can't find the namespace of objects defined by the `image` statement .

So I guess there is some problems about the namespace or the `image` statement doesn't create a new object at all.

**Comment by renpytom** [comment]
The image statement doesn't define a Python variable. You can generally access images by providing a string to something that expects a displayable - for example:

```renpy
show expression "tm"
```

This is because images can have spaces: 

```renpy
image eileen happy = "images/eileen_happy.jpg"
```

is legal.

**Comment by ZYKsslm** [comment]
> The image statement doesn't define a Python variable. You can generally access images by providing a string to something that expects a displayable - for example:
> 
> ```renpy
> show expression "tm"
> ```
> 
> This is because images can have spaces:
> 
> ```renpy
> image eileen happy = "images/eileen_happy.jpg"
> ```
> 
> is legal.

Thanks, it does work!
