### ISSUE TITLE
How to add a variable number of options to a menu

### ISSUE THREAD

**Issue by ZYKsslm** [renpy/renpy#5260]
# How to add a variable number of options to a menu

I want to realize a more flexible feature that the number of menu options can be variable.

## For example

I have a list:

```renpy
default choices = ["c1", "c2", "c3"]
```

How can I add them to a menu?

```renpy
label start:
    menu:
        "the number of options is variable"

    return
```

**Comment by renpytom** [comment]
You need to use the renpy.display_menu function.

**Comment by ZYKsslm** [comment]
Thanks very mush! However, can I add the say statement to it?

just like this

```renpy
menu:
    e "which one?"
    
    "c1":
        "1"
     "c2":
        "2"
```

**Comment by MiiNiPaa** [comment]
These kind of questions are better suited to the [RenPy Forums](https://lemmasoft.renai.us/forums/viewforum.php?f=8) or [RenPy Discored server](https://discord.gg/fBJ3WWfY). Github issues are mainly for reporting bugs within RenPy.

**Comment by mal** [comment]
> can I add the say statement to it?
```rpy
e 'Which one?' (interact=False)
$ renpy.display_menu(...)
```

**Comment by ZYKsslm** [comment]
Got it.
