### ISSUE TITLE
Proxied side image does not update using say image attributes unless sprite is also being shown, Possible ShowingSwitch() issue?

### ISSUE THREAD

**Issue by SpaceLanesGame** [renpy/renpy#5262]
I have been messing with mixing side images and normal sprites, and discovered that the side image does not update via say attributes unless the main sprite is also being shown. 

It seems to be some issue with ShowingSwitch(), which I have been using in order to make LipFlap work.
(I suppose it could be some issue with the lipflap code, it is quite old, but I don't understand enough about how it works to tell)

I updated to the nightly just to make sure it wasn't something already fixed.

[Side Image Bug Test.zip](https://github.com/renpy/renpy/files/13926574/Side.Image.Bug.Test.zip)

**Comment by renpytom** [comment]
I think you're misunderstanding how ShowingSwitch works. It's only true if an image is actually showing, so it's always going to return the default when the main sprite isn't being shown. 

I'd suggest rather than using the ShowingSwitch, you embed things into the LayeredImage directly. 

```renpy
layeredimage theo:
    always:
        "theo_bodybase"

    always:
        "theo_earrings"

    group eyes auto:
        attribute neutral default

    group mouth:
        attribute angry WhileSpeaking("theo", "theo_speaking", "theo_mouth_angry")
        attribute closed WhileSpeaking("theo", "theo_speaking", "theo_mouth_neutral")
        attribute embarrassed WhileSpeaking("theo", "theo_speaking", "theo_mouth_embarrassed")
        attribute happy WhileSpeaking("theo", "theo_speaking", "theo_mouth_happy")
        attribute neutral default WhileSpeaking("theo", "theo_speaking", "theo_mouth_neutral")
    
    group blushing:
        attribute blush "theo_blush"
```

You could also use renpy.get_attributes() along with ConditionSwitch.

**Comment by SpaceLanesGame** [comment]
Ah, I see, sorry to bother you then, and thanks for the suggestions.
