### ISSUE TITLE
Clipbord functions

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#527]
I want to use clipboard functions in Ren'Py. For example, paste strings on console, pass strings
by viewer like this(https://www.youtube.com/watch?v=fZ2o2iVaZ0Q).
I wrote function like below.
https://github.com/kyouryuukunn/renpy/commit/068373878a0badb2b870029becc8b57d2a57e365
But, where should I init pygame.scrap? Can you help me?

**Comment by renpytom** [comment]
pygame.scrap isn't included in 6.18.

In 6.99, pygame.scrap will be present, and you won't have to do anything to initialize it.

**Comment by kyouryuukunn** [comment]
Thank you
