### ISSUE TITLE
Web builds freezes on mobile browsers on audio functions calls.

### ISSUE THREAD

**Issue by zerofluence** [renpy/renpy#5276]
I have implemented VAST ads on the renpy web player.

When a VAST ad loads, I call `renpy_exec('renpy.audio.audio.pause_all()')` to mute the game audio
and when the ad stops, I call `renpy_exec('renpy.audio.audio.unpause_all()')` to unmute the game audio.

This works well on desktop browsers. But on mobile browsers, the game freezes without any error or crash.

I am using 8.1.2.

**Comment by renpytom** [comment]
Those are undocumented functions.
