### ISSUE TITLE
config.enable_language_autodetect does not work for Chinese

### ISSUE THREAD

**Issue by Noriverwater** [renpy/renpy#5282]
Because no matter which region’s Chinese (zh-CN zh-SG zh-HK zh-TW etc.), their locale is 'zh', so they are currently being incorrectly identified as traditional Chinese. Maybe this kind of problem could also happen in other languages.

**Comment by renpytom** [comment]
Just landed a fix that takes the region into account, so zh_cn and zh_sg should map to simplified Chinese.
