### ISSUE TITLE
Live2D renders textures at a lower resolution than the texture atlas permits

### ISSUE THREAD

**Issue by ronchonbon** [renpy/renpy#5293]
I can provide examples if needed, but the effect is simple: Live2D displayables are presented at a much lower resolution than the original model, regardless of zoom factors applied. This can be easily confirmed by showing the raw texture atlas and lining up the Live2D displayable to compare relevant textures.

Effect is present on 8.1.3 and the nightly. I've tested both a large Live2D model with several hundred textures and a 4096 x 4096 texture atlas as well as a model with a single texture at 512 x 512.

I can compensate for the lower resolution by increasing the texture atlas size, but this is not optimal - to obtain the desired in-game resolution, I'm forced to initialize the model's texture atlas at 8192 x 8192.

**Comment by renpytom** [comment]
Can you provide that demo? Ren'Py uses mipmaps, so if you're displaying that on a normal-sized screen, you may be getting that effect, depending on how things are being scaled.

**Comment by ronchonbon** [comment]
Interesting - I'm displaying on a 4K laptop screen with an RTX 4070 mobile, but I just tested on a 4090 and had the same issue. If the issue is that the image is bigger than the maximum texture supported by my GPU, wouldn't I see the same effect on the raw texture atlas?

However, in trying to generate a minimum example, I've found that the effect is heavily dependent on the drawable count of the Live2D model: if I make a minimum Live2D model with a single texture at the desired scaling, the Live2D displayable is presented at an (almost) indistinguishable quality from the texture atlas itself - even if I make the texture atlas 8192 x 8192. If, however, I use the full model, which has more than 300 parts, initialize the texture atlas at 8192 x 8192, and show the Live2D displayable, it is presented at a much lower quality than simply showing the raw texture atlas.

I wonder if the solution is for me to split up my texture atlas into smaller ones so that the blit calls don't have to use the full texture atlas for every drawable...

I'm more than happy to provide you with the Live2D model file and .rpy with image definitions that show the effect - would it be possible for me to e-mail them to you?

**Comment by renpytom** [comment]
Sure, renpytom@gmail.com is my address. Making a small game that exhibits the problems is generally the best.

**Comment by ronchonbon** [comment]
Sent! Thanks!

**Comment by renpytom** [comment]
Ren'Py will load live2d in at it's native resolution, but I do suspect that 8192x8192 is just too big for most systems. You may want to scale your texture down. (That's over 8x the size of a 4k screen.)
