### ISSUE TITLE
Ren'Py doesn't use the RPYC files in old-game on Windows

### ISSUE THREAD

**Issue by doorknob22** [renpy/renpy#5294]
When using Force Recompile on a Windows OS installation, Ren'py ignores the RPYC files in old-game folder. Enclosing a log file.
[log.txt](https://github.com/renpy/renpy/files/13990961/log.txt)

**Comment by qTich** [comment]
I guess that should have been fixed: 59dbb7ac50f5bcacd4a9c6bbedd1439f8251b353
