### ISSUE TITLE
Ability to keep/hold certain textures

### ISSUE THREAD

**Issue by bober-gith** [renpy/renpy#5295]
Spent a lot of time on this, stumbled upon something I think is interesting...
First of all, you were right about the cache problem. Was able to keep it much lower, which made a difference but some spikes still happen at about 1500mb (which is still high but going down more is a lot of sacrifice).

Start_predict/image cache has a lot of overhead as you said, it runs every interaction or something. This is what creates the spike when it's quite high, without it, the game runs well.

Interesting finding:
Textures seem to not have this problem, if for example we start_predict a whole lot of images, then we stop_predict all of it once it's done. All we have left is the textures which don't create spikes or anything, I tested it a bunch of times, it's smooth, no more issues, behave the same.
The problem is that textures eventually get replaced one by one and so it only works well for a short period of time, if there was a way to tell it to keep certain textures in memory and not have them replaced by anything, it would work well I think, better than the image cache. I don't want to bother, if it's impossible or ridiculous, after that 'm gonna go to plan B and add loading screen between each section of the game.

**Comment by renpytom** [comment]
Why is predicting expensive for you? It shouldn't be expensive once the images are loaded into the cache. Do you have an example of where it's causing spikes?
