### ISSUE TITLE
Infinite Loop Detection

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5296]
So I noticed that the infinite loop detection system likes to show itself in my current project quite a lot. I am not sure why it's still doing it sometimes, because I use a lot of `renpy.not_infinite_loop(0)` statements in all the parts that may stay in a loop for a while. One of my assumptions is that the detection cannot really surpressed within a side thread. Because I use `renpy.invoke_in_thread(fn)` sometimes and those functions wait for answers from a local LLM. Everything works flawlessly, but the loop detection comes up every now and then at random places - despite the timer resets. Maybe those timer resets don't work outside of the main thread?

So I was wondering if it would be possible to disable the detection system via a config variable alltogether or what other suggestions you might have.

**Comment by m-from-space** [comment]
Wait a second, am I missing something here? I assumed `renpy.not_infinite_loop(0)` would reset an internal timer to 0, but then again, this still throws an infinite loop error after a while:

```
while True:
        $ renpy.not_infinite_loop(0)
        $ time.sleep(0.1)
```

Setting it to something greater, seems not to throw an error. (I am wondering why a "reset" would need an integer to begin with.) Is the documentation about this a bit misleading?

**Comment by mal** [comment]
The argument to `renpy.not_infinite_loop` is the time in seconds to delay reporting a possible infinite loop warning. For example `renpy.not_infinite_loop(15)` would disable the warning for the next 15 seconds. For the most part Ren'Py manages this internally, and it should only be needed just before executing code that you expect to block for more than 10 seconds (or 60 during the init phase).

**Comment by m-from-space** [comment]
> The argument to `renpy.not_infinite_loop` is the time in seconds to delay reporting a possible infinite loop warning. For example `renpy.not_infinite_loop(15)` would disable the warning for the next 15 seconds. For the most part Ren'Py manages this internally, and it should only be needed just before executing code that you expect to block for more than 10 seconds (or 60 during the init phase).

Thank you, that means I really got it wrong and I just can deal with it properly. :)
