### ISSUE TITLE
ZeroDivisionError: Float Division when Orientation X or Z component set to itself (and not 0)

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5305]
Game crashes and I get the following error when setting the orientation's X  or Z component to a value it already is with ATL. Happens both on images and on camera statements.

Sample code:

```
scene bg
"Time to test this junk!"
show bg:
    orientation (0.0,0.0,0.0)
"Setting orientation to (0.0,0.0,0.0). This works fine!"
show bg:
    orientation (0.0,0.0,0.0)
"Setting orientation to (0.0,0.0,0.0) once again. Still working!"
show bg:
    orientation (10.0,0.0,0.0)
"Setting orientation to (10.0,0.0,0.0) once again. Cool! It rotate!"
show bg:
    orientation (10.0,0.0,0.0)
"Setting orientation to (10.0,0.0,0.0) once again.  Uh oh, it crashed!"
show bg:
    orientation (10.0,0.0,2.0)
"It also would have crashed if I'd set it to (10,0, 0.0, 2.0)"
return
```

The log says the error is in quaternion.pyx, line 158, in renpy.display.quaternion.euler_slerp

Generally this error only happens when I set the X or Z component to itself, when it is already set. The Y component seems to handle it fine, when X and Z are at 0.

Why am I setting it to itself? In case people are rapidly clicking through lines, I need the transform to jump to it's set orientation that it would have slowly eased to if the player hadn't been rapidly clicking! But also if I wanted an orientation that has an X or Z component that was the same as the old one. 

Help!
I tried in 8.2.0.24012306+nightly (and previously in 8.2.0.24012202+nightly)

**Comment by renpytom** [comment]
Can you send me a demo? I'm unable to repeat this. (I'm reading through the code now, to see if there's an obvious cause._) 

My test is: 

```renpy
define _confirm_quit = False

define e = Character("Eileen", image="eileen")
define l = Character("Lucy", image="lucy")
define a = Character("Augustina", image="augustina")

label main_menu:
    return


label start:

    camera:
        perspective True

    scene bg washington

    "Time to test this junk!"
    show bg:
        orientation (0.0,0.0,0.0)
    "Setting orientation to (0.0,0.0,0.0). This works fine!"
    show bg:
        orientation (0.0,0.0,0.0)
    "Setting orientation to (0.0,0.0,0.0) once again. Still working!"
    show bg:
        orientation (10.0,0.0,0.0)
    "Setting orientation to (10.0,0.0,0.0) once again. Cool! It rotate!"
    show bg:
        orientation (10.0,0.0,0.0)
    "Setting orientation to (10.0,0.0,0.0) once again.  Uh oh, it crashed!"
    show bg:
        orientation (10.0,0.0,2.0)
    "It also would have crashed if I'd set it to (10,0, 0.0, 2.0)"

    return
```

**Comment by renpytom** [comment]
I see the issue, I think.

**Comment by colinharvie** [comment]
So my old sample,, which broke at the time I made it, now works... I don't know why.
I just made a brand new project, used your code, and used specific values that seem to always cause it to break now. Hopefully this works (or rather, hopefully it doesn't work).

```
define _confirm_quit = False

define e = Character("Eileen", image="eileen")
define l = Character("Lucy", image="lucy")
define a = Character("Augustina", image="augustina")

label main_menu:
    return


label start:

    camera:
        perspective True

    scene bg washington

    "Time to test this junk!"
    show bg:
        orientation (0.0,0.0,0.0)
    "Setting orientation to (0.0,0.0,0.0). This works fine!"
    show bg:
        orientation (0.0,0.0,0.0)
    "Setting orientation to (0.0,0.0,0.0) once again. Still working!"
    show bg:
        orientation (-270.0,0.0,0.0)
    "Setting orientation to (-270.0,0.0,0.0) once again. Cool! It rotate!"
    show bg:
        orientation (-270.0,0.0,0.0)
    "Setting orientation to (-270.0,0.0,0.0) once again.  Uh oh, it crashed!"

    return
```

**Comment by renpytom** [comment]
I was able to repeat the issue. 

I just uploaded 8.2.0.24012501, which has the fix.

**Comment by renpytom** [comment]
Assuming the heart is confirmation of this fix, I'm closing the issue.

**Comment by colinharvie** [comment]
Yes, it works perfectly now!
