### ISSUE TITLE
Transform that uses "yzoom" behaves differently when called multiple times

### ISSUE THREAD

**Issue by chrisachiu** [renpy/renpy#5308]
The following transform will sometimes invert, seemingly at random.
I am unable to narrow down the exact conditions which make this happen.

- It can happen to images and layeredimages.
- It can happen after an image appears onscreen via dissolve, or via easeinright / easeinleft / easeinbottom / easeintop

```
transform jumper:
    ease .01 yzoom 1.02
    ease .02 yzoom 1.04
    ease .03 yzoom 1.06
    ease .03 yzoom 1.06
    ease .02 yzoom 1.04
    ease .01 yzoom 1.02
    ease .01 yzoom 1
    ease .01 yzoom .98
    ease .02 yzoom .96
    ease .03 yzoom .94
    ease .03 yzoom .94
    ease .02 yzoom .96
    ease .01 yzoom .98
    ease .01 yzoom 1
```
    
In this scene (video below), the character in the **"center"** is anchored to the bottom of the screen, while the character on the **"midleft"** becomes detached from the bottom of the screen, despite both of them using the same transform. (I expected both of them to be anchored to the bottom of the screen during the transform.)

```
   #Scene loads. Inside a ferry.

   scene bg ferry
   show player neutral at midleft
   show grant tired at center
   with dissolve

   thinks "I woke up to..."
   show player neutral at jumper
   player "Hm?"
   show grant neutral at jumper
   grant "Next stop is ours."
```

https://github.com/renpy/renpy/assets/49689047/9a40a27d-2d50-4147-acfb-9c276f158ad5

In this example, both "player" and "grant" are layeredimages.

I observed this behavior on RenPy 8.1.3 and RenPy 8.2.0

**Comment by shawna-p** [comment]
Does `midleft` have `yanchor 1.0`? It seems to me that it does not, which would be consistent with the animation you are seeing - the zoom is happening towards the top of the screen, where it is anchored. Meanwhile, built-in transforms like `center` have `yalign 1.0`.

**Comment by chrisachiu** [comment]
That worked!
Thank you so much!

I added yalign 1.0 to the "midleft" transform:

```
    transform midleft:
        xalign 0.33
        yalign 1.0
```
