### ISSUE TITLE
config.transition_use_child_placement MIA

### ISSUE THREAD

**Issue by bober-gith** [renpy/renpy#5309]
![image](https://github.com/renpy/renpy/assets/78823063/52b2cd61-f697-47ea-bddd-efc4f9dc0cbd)

Maybe it's not something that is used anymore, but it was in the incompatible change for 8.2, just in case that's something.
(I'm not sure what it does)

**Comment by mal** [comment]
This was a typo in the doc (should have been "transitions" plural), but it also surfaced that the automatic compat value was incorrect, so that's been addressed too.
