### ISSUE TITLE
Having transparent pixels on presplash_background.png prevents the game from starting up.

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#5313]
I am trying out Ren'py 8.2.0 with it's new feature that supports transparency for presplashes, I tried adding rounded corners to our pre-splash but that makes the game crash, the game crashes so early that no log generates, so I cannot provide you with an actual error code. This happens only when presplash_background has transparency. If I remove the "_background" sufix the game no longer crashes and the transparency does show, but of course now I no longer have a presplash foreground (our loading bar), this kind of seems like an oversight since the changelog doesn't mention that this is not supported on the foreground and it straight up crashes the game.

**Comment by renpytom** [comment]
Can you tell me what platform you're on, and post the images?

**Comment by Galo223344** [comment]
I'm on windows 10 64 bits (From the logs: Windows-10-10.0.19041)
(File is censored but bug still presists)

![presplash_foreground](https://github.com/renpy/renpy/assets/46462621/aae15fc1-24ba-42b7-b38e-e3dde44e38b9)

![presplash_background](https://github.com/renpy/renpy/assets/46462621/738d1786-ac30-4c5e-ab14-b9f7af3efb99)
