### ISSUE TITLE
Windows defender classifies the renpy 8.2.0 sdk exe as a trojan

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#5314]
On windows 10 64 bits.

The virus is clasified as a `Trojan:Script/Wacatac.B!ml`
![image](https://github.com/renpy/renpy/assets/46462621/1c0cab36-541e-49aa-9158-1c9fd0624572)

**Comment by renpytom** [comment]
This is a faulty detection.  Please report it. I'm going to be making a new build shortly, but you should let microsoft know their antivirus is faulty. 

(How do I know? Ren'Py builds don't use windows.)

**Comment by Galo223344** [comment]
I marked it as a false positive

**Comment by renpytom** [comment]
I've also uploaded a new version, and scanned that on my windows box, and it came out clean. It also came out clean on virustotal, save for one spurious detection by a no-name company.

**Comment by KiloOscarSix** [comment]
So you're aware, updating to 8.2 resulted in Windows Defender blocking and quarantining renpy. 
All threats detected `Trojan:Win32/Wacatac.B!ml` same as OP

**Comment by renpytom** [comment]
That certainly isn't happening with me, with Windows Defender, with "Security Intelligence Version 1.403.2818.0, created on 1/27/2024." I scanned the file, and it was clear.

**Comment by KiloOscarSix** [comment]
My defender versions: 
![image](https://github.com/renpy/renpy/assets/26691547/26e2001f-6297-4621-97c9-1718ed91d386)

Running latest Windows 11 pro

**Comment by Galo223344** [comment]
> That certainly isn't happening with me, with Windows Defender, with "Security Intelligence Version 1.403.2818.0, created on 1/27/2024." I scanned the file, and it was clear.

Could it be that you're scanning the direct build instead of a downloaded/extracted one? I know that windows defender is harsher on downloaded files, so it could be that.

**Comment by mal** [comment]
I just downloaded and scanned with Windows (10 x64, same as reported in OP) Defender the self-extracting exe (`renpy-8.2.0-sdk.7z.exe`), the zip archive (`renpy-8.2.0-sdk.zip`), and for good measure then extracted the zip and scanned the resulting directory. All came up clean.

**Comment by renpytom** [comment]
I've had two peop scan it on the Ren'Py discord, and both found it clean. I'm going to close this - feel free to comment, but this seems more likely to be an issue with your computer than a problem with Ren'Py.

**Comment by renpytom** [comment]
From Microsoft:

![image](https://github.com/renpy/renpy/assets/379804/7b689238-9663-462b-8c0a-ddbb2b0bd8cd)
