### ISSUE TITLE
Images with transparency are rendered too dark sometimes

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5324]
Hello,

so I just encountered this problem while making an imagemap and I thought it's about the imagemap:

![imagemap_bug](https://github.com/renpy/renpy/assets/76992439/61f8ef59-4476-4bdf-b01b-1b05e8cdba0f)

But then I looked at the hover image inside the "image location picker" and the whole image is too dark. **Using the hover image as the "idle" image or the "ground" image inside the imagemap somehow shows it correctly.**

I then tested a render against black background in general:

![render_bug](https://github.com/renpy/renpy/assets/76992439/d1943e56-5926-4219-9523-201e1b2dbf33)

This one uses this "test.png": 
![test](https://github.com/renpy/renpy/assets/76992439/890af32c-1e19-431a-b612-ce04b46b0b35)

And I render it using:

```
screen myscreen():
    add Solid("#000")
    add "test"
```

What is going on?

**Comment by renpytom** [comment]
Please do not put tags in your issue - there's nothing 8.2-specific about this issue.

**Comment by m-from-space** [comment]
> It might be that in the absence of a defined hover image, it will autodefine hover to be the same as idle or ground (giving that stacking effect), I don't know however, just a wild guess. It's weird that gimp would double layers, but it seems to be what it did yeah.

(I'm not hovering anything within the image by the way.)

I filed a bug report with GIMP, let's see what they will say about those different blend mode types I never actually noticed before. Thanks for pointing out that it appears as it was stacked.

**Comment by renpytom** [comment]
I believe (and I'm not an expert in this) is that the difference seems to be that Ren'Py doesn't perform gamma compensation as part of the blending process, and GIMP does, producing different results. Web browsers seem to do this the same way Ren'Py does. 

Right now, I'm not convinced this is an issue with Ren'Py.

**Comment by renpytom** [comment]
I'm closing this, as I don't expect Ren'Py to require changes.
