### ISSUE TITLE
semantic auto increment game version 

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#5326]
This could be useful for games that receive several updates or patches. For example, if the game starts with version 1.0.0 Ren'Py will increment the version to 1.0.1, it could also increment to 1.1.0 or 2.0.0 depending on the type of version being made. Maybe the type can be defined like this:

```
config.version_type = "patch" # minor / major
```

and if you don't want a version auto increment you could set it like this:

```
config.auto_increment_version = False # maybe by default False
```

semantic version info https://semver.org

**Comment by renpytom** [comment]
I don't think this belongs in Ren'Py. It's fine as something a third-party tool can implement, but it's too opinionated about how versions should work to be sensible for a game engine. 

For example, under semver, what changing the major version means ("when you make incompatible API changes") is well defined, but it's not clear what that means for a narrative game.
