### ISSUE TITLE
Shader-based text effects.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#5330]
TBD.

**Comment by furudean** [comment]
This is sort of possible by putting all of your text on a layer and then setting a shader for that layer. But if you want to use a shader on a specific set of text (like text tags), that is not possible. Assuming this issue is about the latter, this would be useful for me personally.

**Comment by renpytom** [comment]
This is something I'm planning to add.

**Comment by Malavos** [comment]
Hey, isn't this what has just been added to 8.3.0? 
https://www.renpy.org/dev-doc/html/textshaders.html

**Comment by renpytom** [comment]
Yes, so I can close it.
