### ISSUE TITLE
Text Underline is segmented in Renpy 8.2

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5332]
In text hyperlinks with `hover_underline True`

This is how it looks in 8.1 and before:

![2024-02-02 12_59_47-Indecent Wife Hana Ver 0 37 0](https://github.com/renpy/renpy/assets/87047775/b40340a3-4276-40fa-b0eb-06f046ef535d)
![2024-02-02 12_59_50-Indecent Wife Hana Ver 0 37 0](https://github.com/renpy/renpy/assets/87047775/345674d1-2b4e-4a75-927f-7dc28cb9e379)

This is how it looks in 8.2:

![2024-02-02 12_58_32-Indecent Wife Hana Ver 0 37 0](https://github.com/renpy/renpy/assets/87047775/397faccf-8500-423c-9295-2e80389b653b)
![2024-02-02 12_58_36-Indecent Wife Hana Ver 0 37 0](https://github.com/renpy/renpy/assets/87047775/bad255d1-169d-4b15-ab94-51fbc495f8cc)

Notice how the underline is segmented. If you change the window size, the segments vary.

**Comment by renpytom** [comment]
I've been unable to repeat this with the default font and game. 

Can you please make a small sample game that  shows the problem, and send it to me?

**Comment by renpytom** [comment]
Any update on this? I'm getting close to a release.

**Comment by renpytom** [comment]
I'm closing this, as I've been unable to repeat it. Please-reopen if there's a font for which this is broken.

**Comment by stunnings** [comment]
I also have the same issue.
