### ISSUE TITLE
Ren'Py 8.2.0 fails to initialize new project in ukrainian language

### ISSUE THREAD

**Issue by ivxvm** [renpy/renpy#5333]
English projects initilialize well, but when I select ukrainian, I get the following error during project creation:

```
Під час виконання створення нового проєкту сталася помилка:

Exception: Comment translation doesn't start with '## ': Якщо є бічне зображення,
показуйте його над текстом. Не виводьте на мобільний варіант - немає місця.
```

**Comment by ivxvm** [comment]
As a temporary workaround, I manually installed 8.1.3, it creates ukrainian language projects without any problems.

**Comment by renpytom** [comment]
I'll take a look at this today.
