### ISSUE TITLE
Archive file access denied

### ISSUE THREAD

**Issue by ZYKsslm** [renpy/renpy#5337]
# Archive file access denied

I'm want to open a writable archive file in game by using `open` function but it often occurs an PermissonError.

```renpy
arc = open(abs_path("archive.rpa"), "rb+")
```

```
PermissionError: [Errno 13] Permission denied: "E:/Ren'py/ba-1.0-dists/ba-1.0-pc/ba-1.0-pc/game/archive.rpa"
```

Sometimes it can run but sometimes it can't.

The archive seems to be occupied by renpy. I want to know how renpy process the archive.

**Comment by renpytom** [comment]
I'm not sure what you're trying to do there, but this isn't an issue with Ren'Py, but something you've written.

**Comment by ZYKsslm** [comment]
Fine. I've read the source code. It seems that Ren'Py will create an unclosed read-only file object when it loads rpa files. When I try to access the file, it occurs an error. 

Maybe some developers have requirements to edit rpa files such as encrypting resources. So I think developers can be allowed to edit the rpa files in code and they just need to ensure the alteration is safe.

**Comment by renpytom** [comment]
I don't plan to change how Ren'Py accesses archive files to support this use case.

**Comment by ZYKsslm** [comment]
That's OK.  
But Ren'Py should have a more advanced encryption system to ensure the safety of resources like other engines, perhaps.

**Comment by renpytom** [comment]
I don't think that's possible while keeping the goal of being open source. (And even closed source would just be obfuscation.)

**Comment by ZYKsslm** [comment]
Yes, the fact is as you said.

However, I think it is necessary to increase the cost of cracking. Because it is **too easy** to decrypt rpa files now even if the cracker don't know anything of reversing tech *(by using some tools)*. 

The copyright needs urgent preservation especially for commercial products.

Maybe developers can be offered some *api* to rewrite the implementation of handle of resources just like *AssetBundle* or something else.
