### ISSUE TITLE
Can't import tkinter

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#5338]
I'm trying to summon a file dialogue window so the user can choose where to save some files. But doing `import tkinter.filedialog` yields me the error `ModuleNotFoundError: No module named 'tkinter'` which makes no sense since tkinter is included in the standard Python libary. I'm on windows 10 64 bits, running ren'py 8.2.0

**Comment by madeddy** [comment]
> the error ModuleNotFoundError: No module named 'tkinter' makes no sense since tkinter is included in the standard Python libary

But it makes sense.

1. Ren'Py comes with his own custom Python(3.9) and AFAIK there is no tkinter included.
2. A module being in the standard lib doesn't mean your py-install has it included. I'am on Kubuntu with py3.10 as the py needed by the OS and tkinter **is not** there. I world need to install it by hand.

Greets

**Comment by renpytom** [comment]
Correcty, tkinter isn't supported on Ren'Py.
