### ISSUE TITLE
Set variable at build time (specifically `config.version`)

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5340]
You may want to generate `config.version` (or some other variable) dynamically at build time so that it can be static to that build.

Consider this example:

```renpy
init 1 python:
    # override the version with the build date
    config.version = "BUILD-" + datetime.today().strftime('%Y-%m-%d')
```

Currently, this would evaluate whenever the game is started, meaning that `config.version` would just represent the date that the end user runs the game.

You may also want to tag the game version with a git hash or something, so just providing the date isn't comprehensive. Allowing the user to specify a function to run at build-time that can mutate such variables would be useful.

**Comment by danac78** [comment]
If you upgrade to 8.2/7.7, build.time takes care of this. 

For example, I use this:

`init 999 python:
    from datetime import datetime
    if build.time == None: #for developing, will come up with a date in 1970
        build.time = 100000
    tsutc = datetime.utcfromtimestamp(build.time).strftime('%Y%m%d')
    #tsutc = datetime.utcfromtimestamp(10000).strftime('%Y%m%d')
    setattr(folbuild,"foltimestamp",tsutc)`

This will go based on the build.time, which sets on build (thus for the if build.time == None because that is what it will default when running from the Launcher.

**Comment by danac78** [comment]
Can't you use build.time to do that? It is basically UTC time.

**Comment by micka190** [comment]
It'd be nice to see this added to the [command line interface](https://www.renpy.org/doc/html/cli.html) as well. Currently, we're using a shell script that uses `sed` to replace a specific string (`CI_VERSION`) with the release number:

```sh
sed -i "s/CI_VERSION/$BUILD_VERSION/" "$OPTIONS_RPY_PATH"
```

**Comment by renpytom** [comment]
Check out the build.info and bulld.time variables added in 8.2, which should let you be able to create what you want. If you need information from the environment, like CI_VERSION, you can initialize keys in build.info from the environment if the key doesn't exist. 

I don't think any changes are needed to support these, as Ren'Py 8.2 should give you the building blocks to do what you need.

**Comment by danac78** [comment]
@furudean here is how I got mine to work

```
from datetime import datetime
    
    if build.time == None: #when running from Launcher, it will be None.
        tsd = datetime.utcnow()
        build.time = tsd.timestamp()
    config.version = "{}.{}".format("47a",datetime.utcfromtimestamp(build.time).strftime('%Y%m%d'))
```
So if build.time is None (default), I am having it capture the time (first by UTC, and then making a timestamp out of it in seconds). 
Then regardless if build.time was none or not, config.version will get assigned it. So, when you got to build it, it will attach the current date to it. But when end-users play it, it will go based on the build.time set into the json (because build.time will go from None to the timestamp that the building occured in.)
