### ISSUE TITLE
Template project gui & screens requirements

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#5342]
Currently, template projects require the presence of **gui.rpy** and **screens.rpy** to work. I believe this is unnecessary. I have a project I would like to use as a template (https://github.com/shawna-p/EasyRenPyGui) which reduces the contents of gui.rpy significantly and distributes screens.rpy into several different files. This template does not include gui.rpy or screens.rpy as a result.

I was able to turn this project into a template by including "dummy" gui.rpy and screens.rpy files with nothing in them, but in such a case it seems unnecessary to require them at all. Is there anything I'm missing by removing these files? Can this requirement be removed so different template structures can be used?

**Comment by renpytom** [comment]
Makes sense, and so I've modified things such that if a file doesn't exist, the generation of it doesn't happen.
