### ISSUE TITLE
Way to download web-extension before web-build in CLI (question or feature request) 8.2.0

### ISSUE THREAD

**Issue by quillcraftsman** [renpy/renpy#5343]
Hello,

 `web_build` CLI command was added in `8.2.0` version, thanks a lot for this.

But I'm still can not to use it automatically in `GitHub` actions. Because in GUI we can download web-extension first but in CLI we can't do it.

Question: Can I download web-extension using CLI only?

If the answer is no then is feature request - to make it possible.

I took a look on code... And I think we can do something like this:

```python
def install_web_dlc():
        add_dlc("web")
        return Falseonly

def web_build_command():
        ap = renpy.arguments.ArgumentParser()
        ap.add_argument("web_project", help="The path to the project directory.")
        ap.add_argument("--launch", action="store_true", help="Launches the app after build and install complete. Implies --install.")
        ap.add_argument("--destination", "--dest", default=None, action="store", help="The directory where the packaged files should be placed.")
        
        reporter = distribute.TextReporter()
        if WEB_PATH is None:
            reporter.info("Before packaging web apps, you'll need to download RenPyWeb")
            reporter.info("To Install RenPyWeb from CLI you can run: ./renpy.sh launcher install_web_dlc")
            return False

        args = ap.parse_args()

        p = project.Project(args.web_project)

        build_web(p=p, gui=False, launch=args.launch, destination=args.destination)

        return False

    renpy.arguments.register_command("web_build", web_build_command)
    renpy.arguments.register_command("install_web_dlc", install_web_dlc)
```

Just add new command to install web-extension, but it's not so easy because `add_dlc` function call `renpy.call_screen` inside and the program crashed in CLI 

As minimum we can add this block to show why user can't run `web_build` in CLI:
```python
reporter = distribute.TextReporter()
if WEB_PATH is None:
        reporter.info("Before packaging web apps, you'll need to download RenPyWeb")
        reporter.info("To Install RenPyWeb from CLI you can run: ./renpy.sh launcher install_web_dlc")
        return False
```

Without this output program crushes with python exception in other place

**Comment by quillcraftsman** [comment]
![web_build](https://github.com/renpy/renpy/assets/135632271/37b89e5f-e5b8-4129-8285-be7ebd3a462c)

Output for command "./renpy/renpy.sh ./renpy/launcher web_build ." without `web-extension`.

**Comment by renpytom** [comment]
I don't support github actions, but you can download the web extensions from https://www.renpy.org/latest.html , look for "web platform support". 

In general, you should be using a cached environment for your builds, rather than downloading from renpy.org.

**Comment by renpytom** [comment]
Closing this, since it's not really a Ren'Py issue.

**Comment by quillcraftsman** [comment]
> I don't support github actions, but you can download the web extensions from https://www.renpy.org/latest.html , look for "web platform support".
> 
> In general, you should be using a cached environment for your builds, rather than downloading from renpy.org.

Okay, thanks a lot. Not perfect, but it's the way. I need to copy `web` folder to `renpy` folder before run `web_build` command in CLI.
