### ISSUE TITLE
crash: `:` in path

### ISSUE THREAD

**Issue by qTich** [renpy/renpy#5345]
If the path contains `:`, a crash will occur.

Details:
```py
Python path configuration:
  PYTHONHOME = '/home/tichq/Downloads/:/lib/py3-linux-x86_64/../..'
  PYTHONPATH = (not set)
  program name = '/home/tichq/Downloads/:/lib/py3-linux-x86_64/renpy'
  isolated = 1
  environment = 0
  user site = 0
  import site = 1
  sys._base_executable = '/home/tichq/Downloads/:/lib/py3-linux-x86_64/renpy'
  sys.base_prefix = '/home/tichq/Downloads'
  sys.base_exec_prefix = '/lib/py3-linux-x86_64/../..'
  sys.platlibdir = 'lib'
  sys.executable = '/home/tichq/Downloads/:/lib/py3-linux-x86_64/renpy'
  sys.prefix = '/home/tichq/Downloads'
  sys.exec_prefix = '/lib/py3-linux-x86_64/../..'
  sys.path = [
    '/home/tichq/Downloads/lib/python39.zip',
    '/home/tichq/Downloads/lib/python3.9',
    '/lib/py3-linux-x86_64/../../lib/python3.9/lib-dynload',
  ]
Failed checking if argv[0] is an import path entry
ModuleNotFoundError: No module named 'encodings'
Traceback (most recent call last):
  File "/home/tichq/Downloads/:/lib/py3-linux-x86_64/../../renpy.py", line 27, in <module>
ModuleNotFoundError: No module named '__future__'
```

**Comment by renpytom** [comment]
Fixed, for Ren'Py 8. 

I'm not going to bother fixing this for Ren'Py 7. This is the first time this has been reported in quite some time, so it's not a big issue. And the changes required would probably need a patch to Python 2, which isn't worth developing for one release.

**Comment by madeddy** [comment]
> If the path contains `:`

Is this only in your linux paths used or in general?
And is there a chance the colon will from Python passed through to the OS? Particularly on Windows?

**Comment by MiiNiPaa** [comment]
> > If the path contains `:`
> 
> Is this only in your linux paths used or in general? And is there a chance the colon will from Python passed through to the OS? Particularly on Windows?

Technically colon is illegal character in windows filenames. If you create a path containing illegal name on Linux and then access it on Windows, RenPy will be the least of your problems.
