### ISSUE TITLE
Remove or ignore orphaned translations

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#5348]
Hello, I'm having a minor annoyance but I would like to know if it was possible to fix in an easy way. I generated the translations for my game and then translated them, but then the writers made minor changes to some lines like fixing typos and such, so I had to re-generate the translation since the translation code changes when the line changes, this puts the changed lines at the bottom, I translate them again and done. But now whenever I lint the project I get these huge blocks of text telling me about orphaned translation lines, and sure, I could go and remove them, but going back and forth Ctrl+F-ing looking for the lines and removing them would be more trouble than it's worth, especially when it's like 50 lines spanned across 4 files and there's no actual downside to having them there that I know of.

So is there a way to automatically remove them? (Since Renpy knows about those lines) or to at least make the linter ignore them through a configuration?

**Comment by danac78** [comment]
Preferences>Lint>Check for Orphan/obsolete translation (first checkbox)
