### ISSUE TITLE
default_focus True is working infrequently in Renpy 8.2.0

### ISSUE THREAD

**Issue by Charmareian** [renpy/renpy#5358]
I recently updated from Renpy 8.0.2 to Renpy 8.2.0 and I noticed some of my menus aren't focusing on the correct item anymore. 

https://github.com/renpy/renpy/assets/24770185/d4ca37a4-5d88-445f-8b20-6e83ca54e36e

In this video, my first button bar defaults to FIGHT as it should, but my move and target selection menus aren't focusing on anything anymore(As they did previously). 

![choice menu](https://github.com/renpy/renpy/assets/24770185/a0f7df0b-d21e-445c-8a25-7aaa9cbc637a)

The above screenshot is how the first menu is coded, which works flawlessly.

![move menu](https://github.com/renpy/renpy/assets/24770185/b0f8dfda-7e22-4ff5-8316-035cd460aab0)

This second screenshot is from my move menu, which no longer works with default_focus True in Renpy 8.2.0

If you need a test build, let me know.

**Comment by renpytom** [comment]
If I could get a test build, that would be helpful.

**Comment by Charmareian** [comment]
Email sent

**Comment by renpytom** [comment]
I don't see the email, please sent it to renpytom@gmail.com

**Comment by Charmareian** [comment]
Ah, I used the one linked on your github page. Sent again.

**Comment by renpytom** [comment]
(Sorry, closed by mistake.)

**Comment by renpytom** [comment]
Should work with the fix I just added, but note that default_focus only happens when the keyboard or gamepad are used. (Since it's silly to have a button focus only for it to lose focus when the player clicks the mouse.)

**Comment by Charmareian** [comment]
Yeah, this was 100% intended for controller support. I'll be happy to see it fixed in a future release, thanks.
