### ISSUE TITLE
Multiple dialogue broken in 8.2

### ISSUE THREAD

**Issue by DinakiS** [renpy/renpy#5361]
Created new project.
Edited script.rpy to this
```
    "Some other character" "First line" (multiple=2)
    e "Second line" (multiple=2)
```

In the screens.rpy I've added this styles under the "say_dialogue" style.
```
style multiple2_say_window:
    xsize config.screen_width / 2
    xfill False

style block1_multiple2_say_window:
    xalign 0.0
style block2_multiple2_say_window:
    xalign 1.0
```

Ren'Py 7.6.3
![renpy_7 6 3](https://github.com/renpy/renpy/assets/30759655/8e2f12ae-297c-49ac-90f5-cbbeb0c5226c)

Ren'Py 8.2.0
![renpy_8 2 0](https://github.com/renpy/renpy/assets/30759655/ac4f3050-03a6-4544-ae46-4338c10d6349)

**Comment by renpytom** [comment]
This is a Python 2 to Python 3 issue. 

In Python 2,  xsize config.screen_width / 2 is an integer - for a 1280 width screen, this is 640. 

In Python 3, it's a float - 640.0 - which is way bigger than the screen. You want to change it to: 

```renpy
style multiple2_say_window:
    xsize config.screen_width // 2
    xfill False
```

And things will work properly.
