### ISSUE TITLE
Simple say window show/hide transforms

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#5364]
What I'm looking for is to apply a transform to the say window once when it appears on-screen, and once when it's hidden. This would be far more restrictive than the way `show` and `hide` currently work with the say screen. 

Ideally, when using the transform below, the behavior would be that the text window slides out when a transition occurs, or a screen is called, etc. It then slides back in when the dialogue continues. Between two lines of dialogue, nothing should happen.
```
transform say_window_animation:
    on show:
        yoffset 330 alpha 0
        linear 0.3 yoffset 0 alpha 1.0
    on hide:
        yoffset 0 alpha 1
        linear 0.3 yoffset 330 alpha 0
```
_(As a side note, I was also thinking about an event / transform whenever the speaking character changes, but I want to keep this request as simple as possible for now.)_

One thing that would already help is that all pauses inside a say statement should be considered `replace`s, including the first one. (Thereby removing `i != 0 and` from line 677 in `character.py`.)

Is there a way to achieve this effect? Or could this be a feature that will be added in the future?

**Comment by mal** [comment]
This seems to sound like `config.window_hide_transition` and `config.window_show_transition`.
https://www.renpy.org/doc/html/config.html#var-config.window_hide_transition
