### ISSUE TITLE
PicklingError shows when saving game after "re-show" custom screen

### ISSUE THREAD

**Issue by COPtimer** [renpy/renpy#5365]
The issue can be reproduced by the following code. `PicklingError` shows when saving after putting the red block into the green block.

```renpy
image red = Solid("#ff0000")
image green = Solid("#00ff00")


screen board():
    modal True

    draggroup:
        drag:
            drag_name "rubbish"
            droppable False
            dragged item_dragged
            pos (200, 200)
            xysize (100, 100)

            add "red"

        drag:
            drag_name "bin"
            draggable False
            pos (860, 440)
            xysize (200, 200)

            add "green"


default dropped_times = 0


init python:
    def item_dragged(drags, drop):
        if not drop:
            return

        store.dropped_times += 1

        return True


label start:
    show screen board

    "[dropped_times]"

    jump start
```

![image](https://github.com/renpy/renpy/assets/8299251/5ec66603-f6b8-4330-8a4c-42068ac3b109)
![image](https://github.com/renpy/renpy/assets/8299251/e8b53f06-b559-43f2-9a38-a37e6d26d9b5)

**Comment by shawna-p** [comment]
I'd just like to add that I have experienced this problem also and it may be related to `draggroup` - in my specific case I was able to remove the draggroup to get rid of the error but this is obviously unideal.

**Comment by COPtimer** [comment]
Additional note: I found that everything works fine if I run the example with Ren'Py 7.6.3.
