### ISSUE TITLE
Extract Dialogue output IDs are not stable: they can change even when line content is exactly the same 

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5373]
I was using auto-voice and noticed that one of my text blocks was not voiced. So I re-Extracted Dialogues to make sure I had the latest IDs, and noticed it had changed. Yet the VCS shows no line content change (only line number change due to offset - but if it was causing the ID change, then all other paragraphs below should have changed ID too, but they didn't).

Below, my diff: only the ID of the first sentence changed. Lines content were the same, except the line number.

![VCS diff start](https://github.com/renpy/renpy/assets/1067772/530fe92f-80f9-4db6-94f1-21bd5469eeec)

![VCS diff end](https://github.com/renpy/renpy/assets/1067772/f8483057-ec62-484e-88f7-3b7b34451ba4)

I assumed that line content was used for hashing ~~(apparently ignoring tags based on my previous testing)~~, but it seems that it's not. Or maybe it somewhat hit a super rare conflict but then again I don't see any other line that hit the same ID.

EDIT: I tested changing tags again and they seem to affect the ID even when stripping tags, which seems to defeat the purpose of stripping tags in order to avoid ID changing when the write is simply changing text format and wait timing but not the text itself.

This makes me pretty worried about starting any VA until definitive text format and timing is done (even if sentences don't change), as I'd have to re-assign all IDs properly. Unless someone knows of a full pipeline to auto-assign IDs to audio files with a single script run.

**Comment by renpytom** [comment]
At least right now, the voice ids are the translation IDs, which change when the strings (including the text tags) change. Stripping tags is just for proofreading and so on - it doesn't change the IDs Ren'Py generates. 

One thing you might want to do to support this model - I'm not sure this is a good idea, but it's possible - would be to use the translation system to generate an english transation, which defaults to the text in the game. When that exists, you can changes the text of the translation how you want, while leaving the game script intact. 

Alternatively, I could define a function that takes the information that goes into generating a voice identifier, and lets you generate your own identifiers (say, by stripping tags and doing the hashing yourself).

**Comment by PasixTheValkyrie** [comment]
This problem is still persistent and as someone who followed the documentation both for translation and auto voice-lines, I'm now stuck in a debacle where multiple of my lines somehow were given a different ID and i'm now to figure out which ones changed and add a "id x" to the line, which is absolutely less than ideal.

For most lines I have not even made any changes, which is quite confusing. They've remained on the same line, had no changes in the content, etc.

It'd be great if there was an option to just auto-add the id after the line so you don't have to do that tedious work yourself, and ensures you're still using the same id henceforth.

**Comment by hsandt** [comment]
OK, so what I understand is that with the current design, the IDs should *not* change and what's happening is a bug, esp. since @PasixTheValkyrie also reported it, and I also found this [thread](https://www.reddit.com/r/RenPy/comments/vo2xed/question_about_voice_line_identifiers_for_auto/).

> It's still not optimal, because it would seem that the voice id for any voice line can change in a whim and I don't know why that is.

Although I'm surprised there wouldn't be _more_ reports as I imagine it would be a hassle for big projects - do many projects use this system? The last one I worked on used manual `voice` statements with `[character]_[scene][line number].ogg` convention e.g. `king_204.ogg` for scene 2, line 4 of the King.

I'm sorry we couldn't find a 100% repro but I think it might be worth keeping this issue open to keep an eye on it. Although I myself also switched to `[character]_[scene][line number].ogg` naming in my own project so I can't tell if the bug happens frequently in the new Renpy (v8.4.1).

Slightly out of scope: If you're really bothered by having an issue with no MWE, but know a lot of developers adding voice acting to their games, an idea could be to survey them to know what system they use (id or manual `voice` statement), which one they prefer and which issues they encountered - they will probably reveal such an issue in the process, and either way the survey's results would surely be interesting. If you're busy with dev, maybe I could actually run it myself on DevTalk since we're in the middle of Raise your Voice jam.

**Comment by renpytom** [comment]
@hsandt There are certainly things you can do to break translation ids. (My guess in that thread is some sort of issue with a duplicate file.) 

Without the use of  version control to show what you did, I can't really do anything to fix this. 

I don't suspect a survey would be helpful here.
