### ISSUE TITLE
Text: no-wait tag with argument {nw=duration} doesn't work, duration is ignored as if passing {nw) or {nw=0}

### ISSUE THREAD

**Issue by hsandt** [renpy/renpy#5374]
I just tried `{nw=duration}` shortcut for `{w=duration}{nw}` which was suggested in https://github.com/renpy/renpy/issues/4763 and implemented.

However, the text just goes on immediately. I created a MWE to compare with the behavior of {w=duration} + {nw}, which works:

```rpy
label start:

    e "Ready?"
    e "w(2) + nw (lasts 2 seconds){w=2}{nw}"
    e "nw + w(2) (lasts 2 seconds){nw}{w=2}"
    e "nw(2) (SO FAST YOU CAN'T SEE IT){nw=2}"

    e "END"

    return
```

**Comment by renpytom** [comment]
I'm unable to repeat this in 8.2.0. 

What version of Ren'Py are you using. If you're on a version before the feature, you'd get what you see.

**Comment by renpytom** [comment]
Closing this. Feel free to re-open if this repeats on the current version.

**Comment by hsandt** [comment]
I was on Renpy 8.1.3 which was released after said commit, but I suppose it only took patches at that point, hence the lacking feature.

I tested again on 8.2.1 and it works, thanks!
