### ISSUE TITLE
SideImage() not retrieving a side image when using multiple character dialogue

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5378]
As described, if you use a multiple dialogue, the side images are not visible inside the say or the multiple_say screen using Renpy's `SideImage()` function.

**Comment by renpytom** [comment]
Yes, though I don't think this is something that is fixable, at least without totally redoing how Ren'Py manages the side image, which probably isn't worth it. I'd suggest passing the side images in using a say argument.

**Comment by m-from-space** [comment]
Thanks Tom, at least I know now. :)

**Comment by thuccynguyen** [comment]
How should one pass in a side image using a say argument?
