### ISSUE TITLE
Ren'py slow as a turtle when using package from ubuntu repos

### ISSUE THREAD

**Issue by score100** [renpy/renpy#538]
Hello,
when using the 6.15.7 packages from Ubuntu, renpy is incredibly slow. The animations are skippy, and music does not play back at all. On top of that, I can not start the demo from the launcher but have to do so from my ubuntu menu.
 I'm using an Asus x550cc with lubuntu Trusty 14.04 on it. When I download the newer version (6.18) and just execute it from there everything works fine. I read about earlier ubuntu packages of ren'py being corrupt, maybe those are as well?

**Comment by renpytom** [comment]
Can you resize the window? If not, it means OpenGL is broken.

You'll have to take this up with the ubuntu maintainers. 6.15 is ancient, and I do not handle packaging for distros, so there isn't anything I can do.
