### ISSUE TITLE
Development Idea: Random Image Selection

### ISSUE THREAD

**Issue by N0lla** [renpy/renpy#5381]
Whilst playing a renpy game the author used the same image for a number of waiting breaks. However, I thought maybe it would be better if within renpy you could actually pick a random image that would display like "A little while later" image, but the author could put a number of these images together and renpy could pick a random image with the syntax of:

pick_random_time_filler<1-3>

So, you would have 3 images that you would have and when renpy would hit this it would pick a random image that the author had already produced. But each time you played it would still pick a new image, thus giving a different image to look at. 

Now each time_filler image could be stored in a seperate directory or pointed to with global variables.

**Comment by MiiNiPaa** [comment]
You can already do that with ATL and choice statement:
```
image waiting:
    choice:
        "waiting_color.png"
    choice:
        "waiting_bw.png"
    choice:
        "please_standby.png"
```

**Comment by N0lla** [comment]
Just it just apply to png files or any?

**Comment by MiiNiPaa** [comment]
> Just it just apply to png files or any?

It requres a displayable. Any displayable. Displayable stored in variable. Name of predefined image. Path to the image file. Anything you can pass to the `add` statement in screens or to `show expression`
Displayables: https://www.renpy.org/doc/html/displayables.html

**Comment by Gouvernathor** [comment]
DynamicDisplayable would also do the job. But ATL is probably the simplest.

**Comment by renpytom** [comment]
Since this is something that can be done already, I'm closing this.
