### ISSUE TITLE
Check for Ongoing Transitions

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#5385]
I have a special Dynamic Displayable for blinks which I don't want animating during transitions (since having a half-faded in eye blink while transitioning to the next expression looks bad). However, I am unable to find any reliable ways of checking for ongoing transitions. Ideally, I would like to check on a per-layer basis (including None).

Of my efforts, the following yielded incomplete results:

- Checking for `renpy.game.interface.ongoing_transition` works well up until you use config variables like `config.say_attribute_transition` and `_scene_show_hide_transition` with dict transitions. These transitions won't trigger the `end_transitions` method and thus sit around in the ongoing_transition dictionary long after they're done animating.
- `renpy.game.interface.transition_delay` has very inconsistent information and almost never seems to read out the actual transition times per-layer. 
- `renpy.get_transition()` seems to always return `None` even when transitions are actively happening

I would like an official way of checking for this so I can have my DynamicDisplayable account for transitions when determining which image to show, though I imagine this check may be useful for other circumstances as well especially when it comes to animations.

**Comment by renpytom** [comment]
I'll look into this, but it may not be possible to get this information.
