### ISSUE TITLE
preferences.gl_powersave "auto" defaulting to power save 5hz on desktop for shaders

### ISSUE THREAD

**Issue by ZeikJT** [renpy/renpy#5387]
On my desktop computer with power directly from the wall with the default `preferences.gl_powersave = "auto"` is still limiting shader render to 5hz. On Ren'Py 8.2.0.

If I forcibly change it to `preferences.gl_powersave = False` then it runs at the full framerate. Normally not noticeable, but very noticeable when rendering a shader on a background that relies on `u_time`.

**Comment by mal** [comment]
I suspect you're not managing the frame rate with the `pause` and `repeat` ATL statements, per the documentation on animated shaders.
https://www.renpy.org/doc/html/model.html#animated-shaders

**Comment by renpytom** [comment]
My guess is the power detection isn't working - but honestly, 5hz is fine as a base thing. 

To go full speed, you need ATL like: 

```
transform full_framerate:
     pause 0
     repeat
```
