### ISSUE TITLE
Add verbose tip upon opening the console view

### ISSUE THREAD

**Issue by Luisjesch** [renpy/renpy#5388]
Explicitly write the tip "use the command long to disable truncating of logs" upon opening of the console so devs wouldn't have a difficult time trying to get past the (...) ellipsis. While the current implementation allows console messages to be neat, it defeats the purpose of using the console to check variable values. The current implementation introduces unnecessary grief and cruel and unusual punishment to devs who do not know the command "long". It's time to put an end to this evil and malicious practice by equipping our devs with knowledge.

**Comment by renpytom** [comment]
The drama isn't necessary, but it's a good idea.
