### ISSUE TITLE
Issue with `persistent` store starting from v8.2.0 when enabling auto-reload

### ISSUE THREAD

**Issue by kobaltcore** [renpy/renpy#5389]
This is reproducible on our game which works perfectly fine on 8.1.3 but fails to start on 8.2.0 with the following traceback when attempting to enable auto-reload during development:
```
Full traceback:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "/Users/cobaltcore/.renutil/8.2.0/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/cobaltcore/.renutil/8.2.0/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "/Users/cobaltcore/.renutil/8.2.0/renpy/exports.py", line 4090, in execute_default_statement
    i.execute_default(start)
  File "renpy/common/00director.rpy", line 28, in new_set_default
    default persistent._director_bottom = False
KeyError: 'store.persistent'

While running game code:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "renpy/common/00director.rpy", line 28, in new_set_default
    default persistent._director_bottom = False
KeyError: 'store.persistent'
```

What's puzzling here is that the entire traceback is contained within Ren'Py itself, no calls to actual game code are shown. I tested The Question just to double check, and it does **not** exhibit this behavior, so I'm unsure of what could be causing this.
Commenting out the affected lined in `00directory.rpy` simply moves it to another `default` statement somewhere in the Ren'Py codebase, so this doesn't appear to be a one-off issue.

I tested this with fresh installs of both `8.1.3` and `8.2.0`, clearing `rpyc` files, `cache` directory and the `saves` directory between runs to ensure a clean slate. However, this behavior is consistent even if those preparatory steps are not taken.

**Comment by renpytom** [comment]
Can I see your game's source code, so I can reproduce this? There's something else to this issue.

**Comment by kobaltcore** [comment]
Yeah, I suspect so as well, though the weird version-specific behavior made me doubt its actual origin. In any case, the current code may be viewed [here](https://git.student-transfer.com/st/student-transfer). Do note that this is a NSFW game, though on the lighter side of things. The code on `master` is representative of what I've been testing with.
Be aware that the game is very large and comes with a bunch of custom stuff, which is also the reason it's so difficult for me to figure out what could cause something like this, especially with no hints to go off of in the traceback.

**Comment by qTich** [comment]
> Yeah, I suspect so as well, though the weird version-specific behavior made me doubt its actual origin. In any case, the current code may be viewed [here](https://git.student-transfer.com/st/student-transfer). Do note that this is a NSFW game, though on the lighter side of things. The code on `master` is representative of what I've been testing with. Be aware that the game is very large and comes with a bunch of custom stuff, which is also the reason it's so difficult for me to figure out what could cause something like this, especially with no hints to go off of in the traceback.

You override `ast.Default.execute_default`.
So I guess you should look at what has been changed and make the changes.

**Comment by qTich** [comment]
> > Yeah, I suspect so as well, though the weird version-specific behavior made me doubt its actual origin. In any case, the current code may be viewed [here](https://git.student-transfer.com/st/student-transfer). Do note that this is a NSFW game, though on the lighter side of things. The code on `master` is representative of what I've been testing with. Be aware that the game is very large and comes with a bunch of custom stuff, which is also the reason it's so difficult for me to figure out what could cause something like this, especially with no hints to go off of in the traceback.
> 
> You override `ast.Default.execute_default`. So I guess you should look at what has been changed and make the changes.

You can try this:
```py
# From:
old_set_default = renpy.ast.Default.execute_default
def new_set_default(self, start):
    try:
        old_set_default(self, start)
    except:
        d = renpy.python.store_dicts[self.store]
        defaults_set = d.get("_defaults_set", set())
        if start or (self.varname not in d.ever_been_changed):
            d[self.varname] = renpy.python.py_eval_bytecode(self.code.bytecode)
        if d.ever_been_changed is None:
            d.ever_been_changed = set()
        d.ever_been_changed.add(self.varname)
        defaults_set.add(self.varname)
renpy.ast.Default.execute_default = new_set_default

# To:
def new_set_default(self, start, old_set_default=renpy.ast.Default.execute_default):
    try:
        old_set_default(self, start)
    except:
        d = renpy.python.store_dicts[self.store]
        defaults_set = d.get("_defaults_set", set())
        if start or (self.varname not in d.ever_been_changed):
            d[self.varname] = renpy.python.py_eval_bytecode(self.code.bytecode)
        if d.ever_been_changed is None:
            d.ever_been_changed = set()
        d.ever_been_changed.add(self.varname)
        defaults_set.add(self.varname)
renpy.ast.Default.execute_default = new_set_default
```

**Comment by renpytom** [comment]
It's almost certainly the used of undocumented internals that is causing the problem, and probably has to do with patching this twice. In any case, this isn't an issue with Ren'Py.

**Comment by kobaltcore** [comment]
Yeah, excellent catch, thank you guys for sanity checking me. That was indeed it and the auto-reload now appears to work properly. Sorry for creating some churn in the issue tracker.
