### ISSUE TITLE
Variables bug

### ISSUE THREAD

**Issue by mirdisk** [renpy/renpy#5391]
Sorry if the translation isn't very good.
I don't speak English and I used Google Translate.

I'm now learning how to create with renpy and I wanted to make a battle system with 10 options but it's giving an error that I realized was a system bug because at one point the script is working and then it gives an error.

At one point I thought it was my lack of experience but it's not because everything works fine when implementing the project.
And then when running again, the error occurs.

Then I will put all my codes for you to reproduce.
I divided it into several folders and scripts because I think it's easier that way.
Everything is inside the game folder

I'll do it like this in mine:
folder name
script name
I will try to be as understanding as possible.

>>> folder name/folder name/script name

>>> game/script.rpy:
defines p = Character("Protagonist")
defines a = Character("Nim")
#image s = "images/s/park.jpg"
#image c = "images/s/cafe.jpg"
#image a1 = "images/p/m (1).png"

label start:
    $ jumpCafe = False
    $ howManyCafe = 0
    scene s
    "Do you want to go to the variables test or continue the story?"
    menu:
        "variable test":
            jump variables
        "continue the story":
            jump continue
        "game menu":
            jump games
label continue:
#Here I continue the story but as this part was not a problem I will not put the script here.

>>>game/games/menuGames.rpy

label games:
    "choose the game"
    menu:
        "rock paper scissors without points":
            jump jok
        "rock paper scissors with dots":
            jump d
        "point test":
            jump point
        "battle test":
            jump simulator
            #"if this appeared, it's because it happened (this sentence was a test)
            # the jump below was a test to see if the label was working
            # jump games

>>>game/testScript/ponit.rpy
$ t = 5
label point:

    menu:
        "One more point":
            $ t += 1
        "Minus one point":
            $ t -= 1
    "Your score is %(t)d points"
    if t == 10:
        jump count
    elif t == 0:
        jump count
    else:
        jump point
label count:
    if t == 10:
        "you came"
        $ t = 0
        "Where do you want to go?"
        menu:
            "count points again":
                $ t = 5
                jump point
            "variable test":
                jump variables
            "test the story":
                jump continue
            "insert":
#This option may not be clear but this is where the game ends.
                return
    elif t == 0:
        "you lost"
        $ t = 5
        "Where do you want to go?"
        menu:
            "variable test":
                jump variables
            "test the story":
                jump continue
            "insert":
                return
    else:
        jump point

>>> game/games/simulator.rpy
################
As is my custom, I just put a test there at the end.

I just tested and chose the battle test option again.

sometimes the phrases:
 b "test"
 i "worked"
show up and go to the menu.

However, after testing a few times, I get this error:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/jogos/simulador.rpy", line 25, in script
    $ atakA += 1
  File "game/jogos/simulador.rpy", line 25, in <module>
    $ atakA += 1
NameError: name 'atakeA' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/jogos/simulador.rpy", line 25, in script
    $ atakeA += 1
  File "D:\z+++\renpy\renpy\renpy-8.1.3-sdk\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\z+++\renpy\renpy\renpy-8.1.3-sdk\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/jogos/simulador.rpy", line 25, in <module>
    $ atakA += 1
NameError: name 'atakeA' is not defined

Windows-7-6.1.7601-SP1 AMD64
Ren'Py 8.1.3.23091805
tutorial 1 VagaData 1.0
Tue Mar  5 17:24:56 2024
```

The same error appears in label point:
Honestly, I'm learning so I don't know much.
But if at one moment it works normally and at another there is an error, I assume it is a bug.
##########################

init python:
    from random import randint
    letterAdivesario = ""
    letterI = ""

defines i = Character("I")
defines b = Character("Adivessary")
$vA = 10
$ vI = 10
$energyE = 0
$energyA = ​​0
$atakA = 0
$atakE = 0
$defenseA = 0
$defenseE = 0
label simulator:

label attackFromAdivessary:

    python:
        draw = randint(1,10)
    if draw == 1:
        $atakA += 1
        $ energyA += 1
    elif draw == 2:
        $atakA += 1
        $ energyA += 1
    elif draw == 3:
        $atakA += 1
        $ energyA += 1
    elif draw == 4:
        if energyA == 3:
            $ atakA += 3
            $ energyA -= 3
        else:
            jump attackDoAdivessario

label test:
    b "test"
    I "worked"
    jump games
#################
I hope I helped and was as clear as possible.
If you want to contact me for further clarification my email is
juniorseier@gmail.com

**Comment by shawna-p** [comment]
This isn't an engine bug; you haven't declared `atakeA` anywhere. For one you're misspelling `atakA` earlier I think, and secondly you aren't setting up your variables properly. I have a few articles on proper variable setup in Ren'Py you can find here: https://feniksdev.com/a-quick-primer-on-variables-in-renpy/

**Comment by mirdisk** [comment]
> Est



> Este não é um bug do motor; você não declarou `atakeA`em lugar nenhum. Por um lado, acho que você digitou incorretamente `atakA`antes e, em segundo lugar, não está configurando suas variáveis​​corretamente. Tenho alguns artigos sobre configuração adequada de variáveis ​​​​​​no Ren'Py que você pode encontrar aqui: https://feniksdev.com/a-quick-primer-on-variables-in-renpy/

It must have been an error in the translation.
It's there, atakA and not atakeA
I'll try to edit better
And the same error also happens in label dot

**Comment by mirdisk** [comment]
> > Husa
> 
> > Este não é um bug do motor; você não declarou `atakeA`em lugar nenhum. Por um lado, acho que você digitou incorretamente `atakA`antes e, em segundo lugar, não está configurando suas variáveis​​corretamente. Tenho alguns artigos sobre configuração adequada de variáveis ​​​​​​​​no Ren'Py que você pode encontrar aqui: https://feniksdev.com/a-quick-primer-on-variables-in-renpy/
> 
> Deve ter sido um erro na tradução. Está aí, atakA e não atakeA vou tentar editar melhor E o mesmo erro também acontece no label dot

And thank you very much for the link.
I'm going to study right now

**Comment by mirdisk** [comment]
Good. It's not just in this part but in another that I only tested game
over conditions.
As for the file, I think it was a translation error.

The problem is that in the test everything works correctly about 3 to 9
times but then in an instant an error appears.
If I'm the one who doesn't know how to program, it shouldn't even work.

I'll send you the game and you can see it for yourself.

I'm really new to this and I don't know how to program with rempy.

Em ter., 5 de mar. de 2024 às 17:50, shawna-p ***@***.***>
escreveu:

**Comment by mirdisk** [comment]
I closed the issue.
But like I said, the problem isn't that I don't know how to program.
If that were the case, I would try to find out where I'm going wrong until
it works.
The problem is that I test it 3 to 9 times and it works fine and if I test
+ 1 it gives me an error.

I made this just to research and learn Renpy.
Thank you and I hope I helped.

If you need a version with the menus etc in English, just ask.

Em qua., 6 de mar. de 2024 às 21:05, juniorseier juniorseier <
***@***.***> escreveu:

**Comment by shawna-p** [comment]
If you think it isn't a problem with your code, it would help if you could post your exact code (do **not** translate your code) which is causing the error so someone can reproduce it.
