### ISSUE TITLE
Issue with a persistent dictionary value requiring a full game reboot before it can be added to

### ISSUE THREAD

**Issue by Janus-Bifrons** [renpy/renpy#5395]
So the issue I'm having is 2-fold: if I have no persistent file or I manually set a persistent dictionary list to empty, the game will not append to that dictionary until the game is launched a second time. But for the first launch, it doesn't just not append... The function sees the list as None and throws an error

Here is the error I get.
```
While running game code:
  File "game/script.rpy", line 42, in script
    $ repadd("Test1", "1", "creates the key")
  File "game/script.rpy", line 42, in <module>
    $ repadd("Test1", "1", "creates the key")
  File "game/screens.rpy", line 97, in repadd
    if place not in l:
TypeError: argument of type 'NoneType' is not iterable
```

However, if you launch a second copy of the game, whether it be after closing the original window or even while the first window stays open, it appends perfectly fine, but only in the new instance of the game, not the original. The top window is the original launch, and the second window is the second instance I loaded with the first one, as in, I launched the game, then launched it again before doing anything in the game.
![dictionary issue](https://github.com/renpy/renpy/assets/133758431/ead7902b-541a-4063-9152-a7a94cc6d7d3)

This is the original defaulting
`default persistent.masterreplist = {}`

This is the function
```
    def repadd(place, upd, desc, l = persistent.masterreplist):
        v = "{}_{}_{}".format(place, upd, desc)
        if place not in l:
            print("if")
            l[place] = [v]
        elif v not in l.get(place):
            print("elif")
            l[place].append(v)
        else:
            print("else")
        return
```

And this is the function call in the script that adds to the dictionary.
```
    $ repadd("Test1", "1", "creates the key")
    $ repadd("Test2", "1", "creates a second key")
    $ repadd("Test1", "1", "added to the first key")
```

Of note is the fact that this is only happening for the persistent version. A regular dictionary does not have this issue. Unfortunately, I need a persistent version for what I'm creating.

So far, the only fix I've found is to tie it to another persistent variable defaulted to False and if that one is False, then it get's set to True and the game is rebooted.

**Comment by Gouvernathor** [comment]
When and where do you call the repadd function ?
As stated in the [lifecycle page](https://nightly.renpy.org/doc/lifecycle.html), if you do so during the init phase, it's normal not to work since defaults kick in after init. Though persistent values kick in _before_ init.

**Comment by Janus-Bifrons** [comment]
It's called in the script itself. Those were sitting a few lines after label start

**Comment by renpytom** [comment]
The problem is with: 

```python
    def repadd(place, upd, desc, l = persistent.masterreplist):
        ...
```

In python, variables like `l` are bound when the function is defined. At that time, persistent.masterreplist is None, and so you get the error. 

You probably want:

```python

    def repadd(place, upd, desc, l = None):
        if l is None:
            l = persistent.masterreplist

        v = "{}_{}_{}".format(place, upd, desc)
        if place not in l:
            print("if")
            l[place] = [v]
        elif v not in l.get(place):
            print("elif")
            l[place].append(v)
        else:
            print("else")
        return
```

Which will use the value of masterreplist when the function is called. 

Not an issue in Ren'Py, though.

**Comment by Janus-Bifrons** [comment]
> The problem is with:
> 
> ```python
>     def repadd(place, upd, desc, l = persistent.masterreplist):
>         ...
> ```
> 
> In python, variables like `l` are bound when the function is defined. At that time, persistent.masterreplist is None, and so you get the error.
> 
> You probably want:
> 
> ```python
>     def repadd(place, upd, desc, l = None):
>         if l is None:
>             l = persistent.masterreplist
> 
>         v = "{}_{}_{}".format(place, upd, desc)
>         if place not in l:
>             print("if")
>             l[place] = [v]
>         elif v not in l.get(place):
>             print("elif")
>             l[place].append(v)
>         else:
>             print("else")
>         return
> ```
> 
> Which will use the value of masterreplist when the function is called.
> 
> Not an issue in Ren'Py, though.

Yep... that did it. Thanks.
