### ISSUE TITLE
 L2d issue in v8.2.1, When showing xxx, {motion file }is not a known attribute

### ISSUE THREAD

**Issue by sine1212** [renpy/renpy#5405]
Once I updated to 8.2(and 8.2.1) all the new motion files that I exported cannot be found in Renpy.

I tried using Cubism Editor v5.0.04, v5.0.00 and v4.2.04 to export motion files and they all have the same issue in 8.2(and 8.2.1).
The weird thing is the old files(which export using v5.0.00 Cubism Editor and put into 8.1 before I updated renpy to 8.2) have no issue loading, only the new added one.

I tried to use "define config.log_live2d_loading = True" and the newly added motion files are not shown in the log but the old ones dose.

Error message:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/script.rpy", line 5, in script call
    call startGame from _call_startGame_4
  File "game/script/deck.rpy", line 221, in script
    show noel_cg normal with dissolve
Exception: When showing noel_cg, normal is not a known attribute.
```

`image lyn_cg = Live2D("cg/lyn/lyn_cg3",default_fade=1.0,loop=False, seamless=True,attribute_function=None,update_function=None,nonexclusive=['drink1','drink2','book_on','m_worried','m_happy','m_upset','m_smile','lyn_worried2','lyn_worried','lyn_hands_up','lyn_happy','cam1','cam2'])
`

**Comment by renpytom** [comment]
Can you please upload a sample gamer somewhere and email renpytom@gmal.com, so I can take a look at what's wrong here?

**Comment by sine1212** [comment]
> Can you please upload a sample gamer somewhere and email [renpytom@gmal.com](mailto:renpytom@gmal.com), so I can take a look at what's wrong here?

I sent you an email the day before, thank you very much, much applicated.

**Comment by renpytom** [comment]
Sorry for taking very long, but I've finally gotten a chance to diagnose this. 

The issue is that there is no Motions section in lyn_cg3.model3.json. Ren'Py only uses the motions that are present in the model3.json file.

**Comment by sine1212** [comment]
OMG thank you for your reply, I also found this post that helped me

https://f95zone.to/threads/renpy-doesnt-display-live-2d-motions.204774/

Thanks a lot!!
