### ISSUE TITLE
Config audio Channel Defaults not working

### ISSUE THREAD

**Issue by LaytaLoiselle** [renpy/renpy#5408]
https://www.renpy.org/doc/html/preferences.html#audio-channel-defaults

These 3 configs don't work:

define config.default_music_volume = 1.0
define config.default_sfx_volume = 1.0
define config.default_voice_volume = 1.

**Comment by shawna-p** [comment]
Remember they are *defaults* - they only work the first time you start your game. After that, it remembers what the player set the volume levels to. You will need to delete persistent from the launcher in order to see them take effect.
