### ISSUE TITLE
local labels in testcase label statement

### ISSUE THREAD

**Issue by adrianmgg** [renpy/renpy#5410]
the `label` statement in a `testcase` currently only works with global labels, since it doesn't accept a dotted `foo.bar` label.

afaict, the fix should be as simple as[^1] changing `l.name` to e.g. `l.label_name` here:

https://github.com/renpy/renpy/blob/b7f4812beec6e47e62216d03f9286ee138c65624/renpy/test/testparser.py#L117-L120

, but I'm opening an issue rather than a PR since I realize there's a bit of a design choice here -- parsing a `label_name` there would make it work with taking an implicit global label from above, and i'm not entirely sure if that behavior would be preferable or if it should only accept fully qualified labels

```renpy
label foo:
    "hello world"
    "aaaaaaa"
label .bar:
    "abcdefg"

# this one already works
testcase with_global_label:
    click until label foo
    # = Until(left=..., right=Label(name="foo"))

# this one doesn't currently work but definitely seems like it should
testcase with_qualified_local_label:
    click until label foo.bar
    # = Until(left=..., right=Label(name="foo.bar"))

# should this one work?
testcase with_unqualified_local_label:
    click until label .bar
    # = Until(left=..., right=Label(name="foo.bar"))
```

[^1]: based on some quick print debugging it looks like `renpy.test.testexecution.labels` already contains strings for local labels (e.g. `"foo.bar"`) too, and that's the only place `renpy.test.testast.Label` checks, so `testast.Label(name="foo.bar")` should just work

**Comment by renpytom** [comment]
This is done. 

An unqualified label is resolved with the name of the testcase - the idea is that testcase foo would be used to test label foo.
