### ISSUE TITLE
Generating zsync updates in 8.2.0 / Advice

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5412]
Let's say I have a game that was created with an older version of Renpy. How can I create an update which supports both zsync and RPU? I don't see an option to create zsync updates in the launcher, nor anywhere in the documentation.

What is the supported path to bring a pre-8.2.0 game to 8.2.0?

**Comment by renpytom** [comment]
```
define build.update_formats += [ 'zsync' ]
```
