### ISSUE TITLE
Tooling: Show the say statement in the original language while in another language

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5414]
Just like the translation identifier screen, will be very helpful to have a screen that shows the original language say statement when playing in the translated language.

Example: showing the original english line when the language is in spanish.

This way, having both lines on screen at the same time, at a glance, you can confirm there are no mistakes or mix ups.

**Comment by Gouvernathor** [comment]
I'm not sure I understand what you want. Is this about a dev tool, that would be used during the translation (checking) process ?

In any case, there are one-off things that execute when you change language, including style changes and `translate python` statements. Two versions of the same style can't exist at once, same as two values for the same variable.
One of the two displayed dialogue entries would lack support of that, and (for one example) you wouldn't be able to display english and chinese/japanese/korean script simultaneously as both are not supported by a single font (well not the default ones at least, but if you need to have the same font for all languages in order for this feature to work that's still a serious hole in the feature).

**Comment by Noriverwater** [comment]
This will be more useful if it is possible to return say statement text in any language, rather than being limited to the original language.
