### ISSUE TITLE
Unable to start 7.7.x SDK when there is a special character in the install folder

### ISSUE THREAD

**Issue by Bibifoc95** [renpy/renpy#5419]
Tested with 7.7.0, 7.7.1 and last nightly fix.
No problem with 8.2.x

When there is a special character in the Renpy SDK install folder, you can't run the SDK. In my case, the character ž (\u017e).
[traceback.txt](https://github.com/renpy/renpy/files/14620356/traceback.txt)

**Comment by renpytom** [comment]
This is fixed in Ren'Py 8, and unfixable (except by you) in Ren'Py 7.
