### ISSUE TITLE
Both the background and the character do the same transition when I only want to apply it to the character

### ISSUE THREAD

**Issue by bobhob314** [renpy/renpy#5425]
I have code like this:

```
transform smaller:
    zoom 0.55

label start:
    scene bg background

    show chara at left:
        smaller
    show chara at left
    with moveinleft
    [...]
```

For some reason, the moveinleft moves in both the bg background image and the chara image at the same time. I didn't want the background to transition in too, I just wanted the character to transition in.

The reason why I think this is a bug or unintentional behavior, is because I can fix it with a simple workaround: Add some text between the `scene` and the `show`.

```
transform smaller:
    zoom 0.55

label start:
    scene bg background

    "text"

    show chara at left:
        smaller
    show chara at left
    with moveinleft
    [...]
```

And now only the character chara transitions with moveinleft.

**Comment by HorBro38** [comment]
This is intentional behavior, it allows you to do a cross dissolve for example:

```py
    hide image_1
    show image_2
    with dissolve
```

It looks like you copied the same code in twice; do you want to share the one without your `"text"`?

**Comment by Gouvernathor** [comment]
Yes, that's intended behavior explained on eother the transitions page or the displaying images page (of the documentation), look into `with None`.

**Comment by bobhob314** [comment]
@HorBro38 
> This is intentional behavior, it allows you to do a cross dissolve for example:
> 
> ```python
>     hide image_1
>     show image_2
>     with dissolve
> ```
> 
> It looks like you copied the same code in twice; do you want to share the one without your `"text"`?

Sure, here

```
transform smaller:
    zoom 0.55

label start:
    scene bg background

    show chara at left:
        smaller
    show chara at left
    with moveinleft
    [...]
```


@Gouvernathor 
> Yes, that's intended behavior explained on eother the transitions page or the displaying images page (of the documentation), look into `with None`.

Ah, thank you very much, using `with None` solved the issue.
