### ISSUE TITLE
Ren'Py constantly sends sound data even when silent

### ISSUE THREAD

**Issue by mal** [renpy/renpy#5429]
Discovered this while forwarding sound from one PC to another. For each instance of Ren'Py ~1.6Mbps is sent from pulse audio forwarding client to the second PC. As each instance of Ren'Py is closed it drops by 1.6 and starting a new instance increases the transmission by the same amount. This behaviour is present in both the launcher and games.

This is in contrast to the observed behaviour of most other applications, where audio data flat lines until audible sounds are triggered, spiking and then returning to zero.

While odd I doubt most PC users would ever notice, but it probably costs mobile users battery life for no benefit, so if it's possible to investigate during the on-going audio filter work, it seems like it might be worth addressing.

Observed on Ren'Py 8.2.1.

**Comment by renpytom** [comment]
This is as designed. 

Cutting off the sound and starting it up again often leads to transients on, for example, bluetooth headsets. Couple that with most games keeping music playing all the time, and this doesn't make sense in the game case - starting and stopping audio will lead to problems.

It probably makes sense to disable sound entirely in the launcher. I'll leave this open until I do that.

**Comment by Gouvernathor** [comment]
Maybe it shouldn't be the case if and when music, sounds and voices are all turned off. Which should be the case of the launcher.

**Comment by renpytom** [comment]
I agree that the launcher should be silent, see above.

**Comment by HorBro38** [comment]
Would it be possible to flag a project as silent somehow so it will function like the launcher will after that update?

**Comment by Gouvernathor** [comment]
My idea is to use `config.has_sound and config.has_music and config.has_voice` as the flag.

**Comment by renpytom** [comment]
Fixed for the launcher. 

Not changed elswhere, as we use the sound stream as a good time reference for video, and without it we'd have problems.
