### ISSUE TITLE
loadsve.py shutil.copy permission bit issue

### ISSUE THREAD

**Issue by rdissertori** [renpy/renpy#543]
I'd like to point out an issue when playing renpy based games on nfs mounts:

>File "/media/nfs/Spiele/SteamLibraryLinux/steamapps/common/Sunrider/renpy/loadsave.py", line 219, in write_file
shutil.copy(self.first_filename, filename_new)
File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/shutil.py", line 118, in copy
File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/shutil.py", line 91, in copymode
OSError: [Errno 1] Operation not permitted: '/media/nfs/Spiele/SteamLibraryLinux/steamapps/common/Sunrider/game/saves/1-4-LT1.save.new'

As you can see I've mounted the data via nfs - my server restricted the permissions so that you cannot change userrights/permissions.

shutil.copy is specified to copy permission bits

So the easy fix is to juse use "shutil.copyfile" instead of "shutil.copy".
I confirm it working changing that.

**Comment by renpytom** [comment]
Makes sense.
