### ISSUE TITLE
Generate a translation reference based on another

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#5434]
* this problem was seen on the spanish discord Ren'Py server, where a dev asked if it was possible to generate a reference based on a language other than the game's native **language.**

I was thinking this idea similar of a system similar to the "Extract dialog" feature, but integrated into the translation generation option.

For instance, suppose our game is in Spanish, and we aim to create a Japanese translation, yet we already possess an English translation. In such a scenario, leveraging the existing English translation as a reference for generating the Japanese version could prove beneficial.

Presently, Ren'Py only allows translation generation based on the game's native language. However, it might be worth considering the addition of a feature similar to the "Extract dialog" option, tailored for translation generation.

By doing so, we could facilitate the generation of translations based on languages other than the game's native one.

example (from es to en): 

```
translate en [ID]:
      "Hola"
      "hello"

translate en strings:
      old "Comenzar"
      new "Start"

``` 
example (from en to ja):
```
translate ja [ID]:
      "hello"
      "こんにちは"

translate ja strings:
      old "Start"
      new "スタート"
```

Visual Example:

![image](https://github.com/renpy/renpy/assets/36079551/f4cf60fc-34b4-40a9-bbd3-4f512405da1b)

This may not be a great idea, but it could make it easier to generate translations for other languages.

**Comment by Gouvernathor** [comment]
The practice of translating text that has already been translated is prone to cascading approximations and to drifting off the original meaning, that's not something we should make the engine support - your idea may not include the None language at all in the translation files, I don't think that's a good idea.
Not to mention the fact that strings that may be different in None may be translated to the same french version, and then for translation from french to italian there's no way to separate them again.

I suggest using the translation-tools, in a repo of mine, which adds commented-out versions of the other languages under the commented-out None version of each translation. That way the None version keeps being authoritative, but you have a better idea of how the line should be translated based off examples. I don't remember if I included translate strings tho.
