### ISSUE TITLE
Ren'Py 8.2.1 Works Natively on FreeBSD 14.0 with Some Hacking

### ISSUE THREAD

**Issue by bedwardly-down** [renpy/renpy#5435]
Hey there. I'm not much of a programmer at all but have been dabbling in programming and doing port work on and off again for years. I need to properly document it and do some heavy testing, but I was able to get Ren'Py 8.2.1 natively working on FreeBSD 14.0 and was able to get Katawa Shoujo Re-Engineered (a fan remake of a cult classic VN) to run natively without too many issues so far.
![1711328140](https://github.com/renpy/renpy/assets/59133880/9842be0f-5658-49e7-b9ac-f4d607413545)
![1711328529](https://github.com/renpy/renpy/assets/59133880/388eff95-fd71-4f1b-95b9-632e546c47d3)

I'm working on getting a PR setup as we speak

**Comment by renpytom** [comment]
I'd certainly be interested, but I do need to make sure the changes are things I can support.

**Comment by bedwardly-down** [comment]
Already on it for that part. Getting the engine to run and compile locally was the easy part; the problem was how I originally did my local port. It would break your official build system due to differences in the operating systems if I were to add. There are ways to run and build from Linux jails on FreeBSD but they’re not viable or easy for the average user or developer. Your build system is beautiful and flexible.
