### ISSUE TITLE
Shift+E when starting game with `renpy.sh`

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5439]
1. When you launch your game with the launcher, hitting <kbd>Shift</kbd>+<kbd>E</kbd> will open the current line in the editor specified in the launcher preferences.
2. When using [`renpy.sh <path_to_game>`](https://www.renpy.org/doc/html/cli.html) the <kbd>Shift</kbd>+<kbd>E</kbd> shortcut will open using the system's default text editor, and not the one specified in the launcher. While this makes sense as the launcher is never touched, it presents a potentially missing feature, or I simply do not understand how to get this behavior.

Can the editor be specified in some other way outside the launcher prefs, or is this a missing feature currently? If it's missing, consider this a feature request.

**Comment by renpytom** [comment]
Check out https://www.renpy.org/doc/html/editor.html. Tl;dr - you need to set the RENPY_EDIT_PY variable.

**Comment by furudean** [comment]
Since the `.edit.py` files are a part of the launcher, this won't work, right? I'd have to specify my own `.edit.py` in the project in question. I was hoping I would be able to reuse the editors defined by the launcher in some way 🤔

**Comment by furudean** [comment]
OK, `RENPY_EDIT_PY` is path to the editor to use. So that could be any path, including one inside the launcher. So I could simply plug the editor I want there.
