### ISSUE TITLE
nvl hide transition doesn't work in some cases

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#5443]
following #5426 and is what i believe #5362 was trying to fix

```rpy
define config.adv_nvl_transition = dissolve
define config.nvl_adv_transition = dissolve
```

say you have this
```rpy
some_adv_character "talking"

show bg 1

some_nvl_character "talking"
```
it works as expected. the adv textbox fades out while `bg 1` and the nvl textbox fade in

but if you do the opposite
```rpy
some_nvl_character "talking"

show bg 1

some_adv_character "talking"
```
`bg 1` appears instantly

**Comment by renpytom** [comment]
I belive this has been fixed.
