### ISSUE TITLE
Will the new version of Android renpy pause due to loss of focus?

### ISSUE THREAD

**Issue by aneame01** [renpy/renpy#5448]
I have a problem playing Renpy game on Android. English is not my native language so I used the screen translator app and then there is a floating button, but as soon as I click on it the game in the background pauses and the status bar pops up at the top.
![Screenshot_2024-04-02-13-05-14-426_com caribdis eternum](https://github.com/renpy/renpy/assets/88713502/0b592b84-fd93-4929-93d2-f820b1a9c67c)
The status bar removes part of the screen, and clicking it resumes the game. Doing this repeatedly is very annoying. 
Old versions of renpy games do not have this problem. I would like to know if this problem can be solved?

**Comment by erikacheyenne** [comment]
I am having the same issue on android but not sure how to resolve it. Commenting to hopefully have it get looked at!
