### ISSUE TITLE
Building a "Google Play" downloader game builds the wrong game?

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#5449]
I'm using Ren'py 8.2.1 and  trying to build a "Downloader" and "Main game" combo by following this page: https://www.renpy.org/doc/html/downloader.html

I have my remote server set up with the right files, and I was able to successfully build an APK "downloader" that's around 20MB that imports the rest of the game at first launch. However, when I build a "Google Play" bundle file for a different game with a different bundle key, the resulting AAB file is 660MB, similar to the filesize of the first game I built.

I'm able to replicate the same behavior with "The Question". Just in case, I used different bundle keys.

In other word, here's what happened:
- build an APK build for game A
- after game A has been successfully built, tried building an AAB build for game B
- When selecting "Google Play bundle", Ren'py builds an AAB file for game A instead of game B.
- when selecting "Universal APK" for game B, Ren'py successfully builds an APK file for game B.

How to possibly reproduce the bug:
1. From Ren'py launcher, build an Android game by selecting either "Universal APK" or "Google Play bundle"
2. From Ren'py launcher, build a "Google Play bundle" for a different game

EDIT: I deleted the RAPT folder and downloaded it again from Ren'py launcher. Now it built game B properly.

**Comment by renpytom** [comment]
Should be fixed in tomorrow's nightly fix build.
