### ISSUE TITLE
I want to make API call with renpy.fetch and pass bearer token in authorization. Help me with that

### ISSUE THREAD

**Issue by prajyot1708** [renpy/renpy#5452]
<img width="1088" alt="image" src="https://github.com/renpy/renpy/assets/26087423/e6dedf8e-bab8-4dc2-b073-dc8fbd9237a0">

**Comment by renpytom** [comment]
Right now, there's no way - but I'll add a field for headers. It's a really bad idea to access a service that requires authentication from a game, however - people can take your token and use it to construct malicious requests.

**Comment by renpytom** [comment]
I'm about to add it. It should be in the April 5 Nightly (non-fix) build.

**Comment by prajyot1708** [comment]
I have downloaded the renpy-8.2.2.24040603+nightly-sdk, but still facing the same issue of headers is not present.
