### ISSUE TITLE
Replace your keyboard style to regular keyboard style when entering text on Android.

### ISSUE THREAD

**Issue by vadimk1337** [renpy/renpy#5453]
When entering text on Android, the gboard keyboard loses the suggestion strip. Instead, a keyboard with a number strip appears instead of the suggestion strip, ignoring the Gboard settings. The keyboard loses functionality; you can't translate text, switch floating mode, and there's no suggestion strip.

**Comment by renpytom** [comment]
This is a known issue, but so far I haven't found a good way of fixing it. For now, you'll just have to make do.
