### ISSUE TITLE
Allow evaluating code from `renpy.sh` via stdin

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5455]
I'm working on a VSCode extension where I would like to dynamically warp to a specific line in a open game. Currently I do a rudimentary version of this by running `renpy.sh` with the `--warp` parameter. The game starts at the right place. Cool! But now warping elsewhere after the fact, it's not strictly possible without restarting the game, which is subject to overhead and intrusive window openings and closings.

My proposed enhancement is as thus: take stdin from `renpy.sh` to allow arbitrary renpy code to be executed, like the `ctrl+o` menu in-game. This will allow developers to call `renpy.warp_to_line()`, or any other function that they desire in context of the game, enabling more powerful integrations.

Related issue in my extension's repo: https://github.com/furudean/vscode-renpy-warp/issues/2

Happy to take a stab at this myself, as I realize this might be a sort of niche use-case

**Comment by renpytom** [comment]
I don't think stdin is the right place for this - it's been my experience that it's a problem. A file on disk is probably a better choice - let me give a shot at implementing this myself.

**Comment by furudean** [comment]
Just to be clear, I'm asking for a feature that allows you to warp dynamically in an already open game, via an external signal. So I'm not sure a file on disk is going to be able to get that on-demand feature. It's possible I'm just misunderstanding something here

**Comment by furudean** [comment]
Maybe stdin is the wrong terminology here. More in line with the REPL pattern or I guess more aptly an equivalent to the developer console in Ren'Py as described in the OP

**Comment by renpytom** [comment]
You should be able to do this with the nightlies, by creating an exec.py file with: 

```
renpy.warp_to_line("script.py:123")
```

Ren'Py looks in the base directory for exec.py about every 100ms, and will run it if it exists.

**Comment by furudean** [comment]
I've tried it out and it works great. Thanks!
