### ISSUE TITLE
Style property interpolation

### ISSUE THREAD

**Issue by WladekProd** [renpy/renpy#5456]
It would be great if you could seamlessly change different style parameters, like the CSS transition property.

For example:
```
style navigation_button_text:
    idle_color "#ffffffff" ease 0.8
    hover_color "#eb2842ff" ease 0.8
```

And get something like this:
![Recording 2024-04-06 at 00 23 20](https://github.com/renpy/renpy/assets/71282508/276aff57-7ba9-48bb-9fec-6d0140c4814c)

**Comment by renpytom** [comment]
I don't expect this to ever be added to Ren'Py. If you want animation, use ATL.
