### ISSUE TITLE
ui.timer seems to bug while trying to instantiate multiple classes?

### ISSUE THREAD

**Issue by BariumBlue** [renpy/renpy#546]
I've boiled the example code here:

script.rpy:
http://pastebin.com/pTV0rEK2

This is a script that calls two functions from `ui.timer`, who each print to console, then calls two classes from ui.timer, who should each print to console.

What should be printed (as you go along in the script), is
```
Function One!
Function Two!
Class One!
Class Two!
```
What i get instead is
```
Function One!
Function Two!
Class One!
```
This is when I run it using Ren'Py 6.18.3.761.

More specifically, it seems that after the first class is instantiated, other calls to `ui.timer` seem to bug out, as calling
```
test_classes()
test_functions()
```
 (see pastebin for functions)
only prints
`Class One!`
and apparently causes ui.timer to only instantiate the very first class

**Comment by renpytom** [comment]
Not a bug, as discussed on IRC.
