### ISSUE TITLE
Describe which OS the different SDK downloads are for.

### ISSUE THREAD

**Issue by SpaceLanesGame** [renpy/renpy#5460]
While probably not a super common issue, we do occasionally get people on the discord asking which one they should be downloading. Adding a Mac, Windows, Linux label/description with each button would help those who are not as tech literate.

https://www.renpy.org/latest.html

**Comment by renpytom** [comment]
The website already does that - the one you download is in green, the others are outline buttons.

**Comment by SpaceLanesGame** [comment]
While that is a nice bit of design, there's no indication it's checking anything for you, rather than just having one button be green for unknown reasons. Again, not a big deal, just a suggestion to make things clearer.

**Comment by renpytom** [comment]
I think the current design is fine - the problem is, each of the versions works on all platforms. So I don't think a change is needed here.
