### ISSUE TITLE
Problem with Renpy 7.8.0 saves

### ISSUE THREAD

**Issue by gofa4a** [renpy/renpy#5462]
Good afternoon. I wrote in [this thread](https://github.com/renpy/renpy/issues/5446) and you solved part of the problem, but not completely. Now in our game, if you save AFTER a battle (have completed several quests and saved) then when loading this save is rolled back to the end of the first battle. That is, part of the saved progress is lost. Tested on version **7.8.0.24040902+nightly**.

To clarify. If you pass after the battle a lot of quests and save - then when loading this save will be rolled back to the first battle. As a result, all progress on completed quests after the first battle - will be lost.

**Comment by gofa4a** [comment]
> Behaviour as described sounds like what you might see if `call_in_new_context` was being used incorrectly.

Everything works fine on 7.6.3. But with the new version these problems began.

**Comment by qTich** [comment]
> > Behaviour as described sounds like what you might see if `call_in_new_context` was being used incorrectly.
> 
> Everything works fine on 7.6.3. But with the new version these problems began.

I don't rule out that `call_in_new_context` might have been used incorrectly if you are only using different versions of `Ren'Py`.

However, if the content of the game has been changed, I believe you should look into the following:
https://www.renpy.org/doc/html/build.html#the-old-game-directory
https://patreon.renpy.org/dev-2021-02.html#save-compatibility-through-repeated-releases
https://patreon.renpy.org/rpyc.html#implications-for-save-compatibility

**Comment by renpytom** [comment]
Is there something that can be done to repeat this reliably, with the same game script?

**Comment by gofa4a** [comment]
> Is there something that can be done to repeat this reliably, with the same game script?

I sent you the game in the mail a while ago. Let me know if you need to duplicate it and I'll send it again.

In order to replicate what we're seeing, it's necessary:
1. Go through the battle (it does not matter to win, or run away from the battlefield)
2. Then run around the map, you can do a quest.
3. Survive. 
4. When loading a save - the game throws back to the end of point 1 (the end of the battle). That is, all progress as if rolled back when loading a save. And everything that passed after the first battle, all progress is lost, because there was some kind of rollback.

**Comment by gofa4a** [comment]
> Is there something that can be done to repeat this reliably, with the same game script?

I can send a video if that would help.

**Comment by renpytom** [comment]
Send me the game again, please - just so I don't have to hunt around to find it.

**Comment by gofa4a** [comment]
> Send me the game again, please - just so I don't have to hunt around to find it.

I have resent the game to your email with detailed instructions attached in the email.

**Comment by gofa4a** [comment]
Tell me, will the problem be solved?

**Comment by renpytom** [comment]
I believe this problem has been solved. At least, with the nightly fix build, and the instructions provided in your email, I wasn't able to repeat the problem in 3 tests.
