### ISSUE TITLE
start_screen_predcit (and screen prediction in general) not predicting displayables in screen

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5465]
For context, my main menu has a few screens, including a "play_menu". Both the base "main_menu" and the "play_menu" have a bunch of displayables that are essentially transforms displaying repeating image sequences. They aren't huge, but they are big enough so that if they aren't predicted, there is noticeable lag.  

The first time I navigate to the "play_menu", there is is a noticeable lag spike. Further navigation between the two menus is smooth as butter (unless I've started the game and then return to the menu, then the spike returns for the first navigation). Pressing F4 and watching image prediction seems to confirm that the problem is that the images on the screen (which are just `add` statements in screen language) are not being predicted. Pressing F4 on game load, before the main_menu appears, also shows me that the main menu images aren't being predicted either, nor are any other images on any screens.

I tried to have it manually predict the screen using `start_screen_predict` in `label before_main_menu`, but that did not change anything. Afterwards, I added `on "show" action function(predict_screen,"play_menu")` to the main_menu screen, (where `predict_screen` was a quick function that just runs `start_screen_predict`), but still no effect.

What eventually worked was, in my `predict_screen` function, was running `renpy.start_predict` and then listing all the images that appeared in "play_menu".

I'm not sure if I just misunderstand how `start_screen_predict` or screen prediction in general, is supposed to work, but from the documentation it sounds like the point is to prevent this sort of lag by having all the displayables in the screen predicted and ready to go.

**Comment by renpytom** [comment]
Do you have an animation or movie running under your main menu? In general, Ren'Py has trouble predicting things while animations are in progress, such that constant animations can starve the predictor. (That's something I need to fix at some point.)

**Comment by colinharvie** [comment]
I did indeed! I had both a movie playing, and an transform that was causing the opacity of an element to oscillate. 

Turning both of those off caused screen prediction to happen normally, and everything worked smoothly.
