### ISSUE TITLE
Displayables with changing children jitter when physical size is less than ~75% screen size 

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5466]
I have quite a few animated sprites in my game. Some of them use a custom displayable I made which just changes which image to render every 1/8 of a second, and some I've implemented with something like:

```
image phylla_title:
    "cg/title/phylla_title_00.png"
    1/8
    "cg/title/phylla_title_01.png"
    1/8
    "cg/title/phylla_title_02.png"
    1/8
    "cg/title/phylla_title_03.png"
    1/8
    "cg/title/phylla_title_04.png"
    1/8
    "cg/title/phylla_title_05.png"
    1/8
    "cg/title/phylla_title_06.png"
    1/8
    "cg/title/phylla_title_07.png"
    1/8
    repeat
```

In both instances, if the user has scaled the window to less than roughly 75% of the games screen_size (at least in my testing), the image starts jittering up and down about 1 pixel or so. If made very small, it also starts jittering left and right. 

It becomes more obvious the more frames there are. Some of my sprites with only 3 frames do not jitter, with the offsets only appearing on the 4th child to be swapped out. 

The jittering repeats, with the offsets tied to the the specific child image being displayed. 
All images have the exact same dimensions. 

This happens both with images added to a screen with `add`, or images in the game using `show`. 

Example: (Recorded with very small screen so the jittering will be more obvious)
https://github.com/renpy/renpy/assets/4917213/0e8dcf8e-06e5-4790-96f2-01ef99203faf

**Comment by colinharvie** [comment]
More information after some additional testing:

if I only use 3 different images in the transform, like so:

```
image phylla_title:
    "cg/title/phylla_title_00.png"
    1/8
    "cg/title/phylla_title_01.png"
    1/8
    "cg/title/phylla_title_02.png"
    1/8
    "cg/title/phylla_title_00.png"
    1/8
    "cg/title/phylla_title_01.png"
    1/8
    "cg/title/phylla_title_02.png"
    1/8
    "cg/title/phylla_title_03.png"
    1/8
    "cg/title/phylla_title_02.png"
    1/8
    repeat
```

Regardless of hte order and how many times, it doesn't seem to jitter (the jittering offset seems tied to the specific image/frame)

Additionally, if I duplicate one frame 8 times and name them all differently, again, no jittering. (in this example, #s 08-14 are exactly the same as 00, but separate files)

```
image phylla_title:
    "cg/title/phylla_title_00.png"
    1/8
    "cg/title/phylla_title_08.png"
    1/8
    "cg/title/phylla_title_09.png"
    1/8
    "cg/title/phylla_title_10.png"
    1/8
    "cg/title/phylla_title_11.png"
    1/8
    "cg/title/phylla_title_12.png"
    1/8
    "cg/title/phylla_title_13.png"
    1/8
    "cg/title/phylla_title_14.png"
    1/8
    repeat
```

Lastly, if I ONLY use frames I know have a jittered offset, the offset IS there. I assume this means it's something about the actual data of the images causing this?

Again, this only happens when the window is scaled down smaller than about 75% of virtual size..

**Comment by renpytom** [comment]
Do you have an example game? Simply postying code isn't going help, as I'd need to see if it's an issue with the images.

**Comment by colinharvie** [comment]
I will make up a small example.

**Comment by colinharvie** [comment]
Here you go. 
https://www.dropbox.com/scl/fi/q1nalujzx6x9b7qbkj0lt/TestingGrounds-1.0-pc.zip?rlkey=vv5rv6zjpix8d7uo0jdsjbjtl&dl=0

Super empty game, just has the sprite and showcases the problem.
The script resizes the screen as you play through, to show the issue.

**Comment by colinharvie** [comment]
I've figured out a way to stop this from happening. Adding `mesh True` to the transforms for the images keeps this from happening. 

Still seems like it's an error (and if for whatever reason someone can't use `mesh True`, it would still be a problem), but it works for my needs.

**Comment by renpytom** [comment]
This was a complex one, as the (fairly slight) size difference of the images after optimization caused OpenGL to select a slightly different mipmap level between some of the frames. There's one variable that controls this, config.gl_lod_bias, and I've adjusted it so that the problem occurs at somewhat different sizes. 


0b257c350593fd2ed882c4e7535726ac6ce9985f
