### ISSUE TITLE
Displayable Mouse Cursor return key error 

### ISSUE THREAD

**Issue by maliefrr** [renpy/renpy#5467]
I tried to follow the documentation https://www.renpy.org/doc/html/mouse.html#MouseDisplayable
```
image mouse spin:
    "gui/spin0.png"
    rotate 0.0
    linear 1.0 rotate 360.0

    # Pause so image prediction can happen.
    pause 1.0

    repeat

define config.mouse_displayable = MouseDisplayable(
    "gui/arrow.png", 0, 0).add("spin", "mouse spin", 9.9, 9.9)
    
  $ default_mouse = "spin"
  ```
 but i change it like this
 
```
image mc bedroom = "images/BG/bedroom.png"
image cursor pia:
    "gui/button/cursor_1.png"

define config.mouse_displayable = MouseDisplayable(
    "gui/button/cursor.png", 0, 0).add("mouse pia","cursor pia", 0, 0)

label mainpia:
    $ renpy.block_rollback()
    $ quick_menu = True
    $ default_mouse = "mouse pia"
    scene black with dissolve
    show text "Chapter I\nThe Choosen One" with Pause(1.5) 
    scene black with dissolve
    scene mc bedroom with dissolve
```
but returning this is it the documentation wrong or my code? because i have follow like the documentation said
![image](https://github.com/renpy/renpy/assets/61228297/3ffa50e9-c7f9-4c98-9636-41dc9507357b)

**Comment by renpytom** [comment]
2c09515c4d33ca0528b755d3732e9f696e448d7f adds a check to prevent this error, though I don't see the underlying cause here.

**Comment by maliefrr** [comment]
> [2c09515](https://github.com/renpy/renpy/commit/2c09515c4d33ca0528b755d3732e9f696e448d7f) adds a check to prevent this error, though I don't see the underlying cause here.
the thing is i don't know the cause that trigger this error, because i followed the documentation that renpy provide maybe is there any mistake that i missed, maybe the documentation need to give more example to implement this function

**Comment by maliefrr** [comment]
Any idea to check it?

**Comment by renpytom** [comment]
The change should be in the nightly fix branch, and should show the real error.
