### ISSUE TITLE
org.renpy.android.PythonSDLActivity.onPause causing high ANR rate

### ISSUE THREAD

**Issue by marchare555** [renpy/renpy#5468]
I rolled out an update on Google Play that replaces a "full" build with a "downloader" build that pulls the actual game from a remote server. It was done with Ren'py 8.2.2.

Two weeks after the update, Google Play is reporting a very high (3.2%) ANR rate. 

81% of the ANR's are caused by "org.renpy.android.PythonSDLActivity.onPause". I joined the sacktrace provided by Google Play.
[stacktrace.log](https://github.com/renpy/renpy/files/15022899/stacktrace.log)

Hopefully the logs can provide useful information on what could be causing the ANR.

**Comment by renpytom** [comment]
Hopefuly fixed with the recent change to audio locking in the nightly fix branch.
