### ISSUE TITLE
Returning a JSON object gives non-revertable nested data types.

### ISSUE THREAD

**Issue by MapMappening** [renpy/renpy#5472]
For each key-pair, if the entry contains a list then the following code will return regular python lists instead of revertable lists:
```
init python:
  file = "my_data.json"
  data = json.load(renpy.open_file(file))
  my_list = data["My Key"]
  print(isinstance(my_list, list)) # this will return false
```

**Comment by renpytom** [comment]
In general, this is the case if you go outside of Ren'Py to use Python functions (like json.load). I don't think that this is a problem that Ren'Py should address - you can convert the object to a Ren'Py form if you need to.

**Comment by MapMappening** [comment]
Noted

**Comment by renpytom** [comment]
This can probably go into renpy.exports, as it'll be small and genuinely useful. (Also, that file needs to be broken up.)
