### ISSUE TITLE
crashes when trying to launch on a secondary monitor

### ISSUE THREAD

**Issue by Momotye** [renpy/renpy#5475]
i found a bug while trying to play katawa shoujo re-engineered, and was told to report it to you guys since it's an engine bug. here's the issue:

game fails to load when trying to launch on a monitor other than the computer's main monitor. i'm running on windows 10, and wanted the game on a secondary monitor, so i used the classic trick of opening the game, and then resizing and moving it to the desired monitor where i close it, but then upon reopening it, the initial loading splash when you first click the icon loads on my main monitor, and then the game window opens to an immediate white screen and time out on the second monitor. this happens regardless of which monitor is primary/secondary, so long as the game opening is not on the main monitor.

**Comment by renpytom** [comment]
Hi there. Do you have a log.txt from the game? 

Generally there shouldn't be any difference between the primary and secondary monitors, but I can check the log and see if anything is wrong. Chances are it's a video driver issue.

**Comment by Momotye** [comment]
[log.txt](https://github.com/renpy/renpy/files/15081217/log.txt)

thanks for the response, here's the log.txt right after freshly causing the error

**Comment by renpytom** [comment]
I don't see an obvious problem, though Nvidia has released a newer driver. You probably want to upgrade. Also make sure that you're not running any game enhancement, screen capture, or streaming software that could improperly implement OpenGL.

**Comment by Momotye** [comment]
I've updated my driver and made sure i don't have any capture/streaming stuff installed, and the problem is still here. i also tried reinstalling the game, which didn't fix the issue, but here's the new log file in case it has different info
[log.txt](https://github.com/renpy/renpy/files/15087219/log.txt)

**Comment by renpytom** [comment]
Unfortunately, I don't see any obvious way in which your computer differs from a working one, so I don't really have much to do. One thing you might try is holding shift on startup, and see if you can enable the angle renderer. I don't think this is a problem in Ren'Py, just because the current version has been out long enough I would have expected this to be reported by now.

**Comment by Momotye** [comment]
changing the renderer seems to have resolved the issue. Thanks for the help!
