### ISSUE TITLE
Buttons with default_focus True don't update variables

### ISSUE THREAD

**Issue by Charmareian** [renpy/renpy#5477]
For some reason my buttons don't update when they're the default focus, here's a video of it in action.

https://github.com/renpy/renpy/assets/24770185/76e119f3-8d5d-4ee2-8b09-8f9350882223

Here is the button code in question.

![code](https://github.com/renpy/renpy/assets/24770185/1b3b5bf3-955d-428b-8bd9-5ad213154864)

If you need a build to test, let me know.

**Comment by renpytom** [comment]
A build to test would be helpful.

**Comment by Charmareian** [comment]
Should be sent
