### ISSUE TITLE
Game crash on RenPy 7 Web due to video errors

### ISSUE THREAD

**Issue by andrigamerita** [renpy/renpy#5478]
Hello everyone, I've been trying to port a RenPy game from my tasklist to a web application yesterday, but I've been encountering huge issues. I haven't had issues with RenPy 8 in a while, but this game is really really old and it won't run under Python 3, so I currently have to use RenPy 7, considering that porting it to 8 would probably require a big rewrite.

Everything initially seemed to go smoothly with the latest RenPy 7 SDK (7.7.1), and the game ran in my Firefox browser on Windows Server 2022. But then, I tried it on literally any other platform, and it just crashed after a while of loading. I tried to see if I could replicate the issue with a much smaller and actually open-source game, so I tried compiling the included example one, _The Question_, for the web: exact same issue. I can't consider this a problem with my devices, however, since they all present the issue except for the Windows one, and as I said this only happens with RenPy 7, while 8 works normally.

After reading a bit online, I've come to learn that something between RenPy 7.3 and 7.5 has changed about the video system, something about old video backends being dropped in favour of newer ones, but I couldn't really understand more. Especially considering that, from reading, it seems that the change was done in just one release with the switch from 7.3 and 7.4, but I've actually tried building my game for the web with the latest 7.4 (7.4.11), and it actually works fine on any platform (only Firefox browsers though, since that version hadn't yet fixed a memory issue affecting WebKit)! And, sure enough, building the game with 7.5 makes the issue arise. I obviously can't just consider the porting done with 7.4.11, however, since incompatibility with 2 of 3 of the major browser engines is a big deal, and that version seems to also have a bug with audio and songs not playing.

I will include RenPy logs below for all the devices I've verified the issue on using _The Question_ compiled with RenPy 7.7.1, but even with my limited knowledge I can definitely see that this problem has something to do with the video system. Sure enough, the logs all contain more or less the following in their error traceback that leads to program termination, something which again I couldn't really find a lot on the Internet to try and fix myself:
```
Initializing gles2 renderer:
primary display bounds: [varies with device]
swap interval: 1 frames
Windowed mode.
[Full traceback ...]
While running game code:
AttributeError: 'module' object has no attribute 'webgl_enable_extension'
[...]
```

Logs for browsers on my Linux desktop, latest Linux Mint Debian Edition with stock video server and desktop environment on an AMD Ryzen 3 3200G:
* Firefox 125.0.1 (Flatpak): [firefox-linux.txt](https://github.com/renpy/renpy/files/15106699/firefox-linux.txt)
* Chromium 124.0.6367.60 (Flatpak): [chromium-linux.txt](https://github.com/renpy/renpy/files/15106695/chromium-linux.txt)
* Epiphany (browser based on Apple's WebKit) 46.0 (Flatpak): [epiphany-linux.txt](https://github.com/renpy/renpy/files/15106697/epiphany-linux.txt)

Logs for browsers on my Android, Xiaomi Redmi 9T running chinese edition of MIUI 14 (I've also verified the issue on a Samsung tablet, but I'm not including logs for that since it would be really redundant):
* Chromium (Mulch 123.0.6312.40): [chromium-android.txt](https://github.com/renpy/renpy/files/15106694/chromium-android.txt)
* Firefox Beta 124.0b9: [firefox-android.txt](https://github.com/renpy/renpy/files/15106698/firefox-android.txt)

Finally, logs for Firefox on Windows, which is the only platform that I've confirmed is working, just for reference: [firefox-windows.txt](https://github.com/renpy/renpy/files/15106700/firefox-windows.txt). It's interesting to see that it also errors on initially trying to use the `gles2` renderer, but then simply falls back to the `gles` one.
(I'm not including any logs about Chromium on Windows since that gives me a different error, still video-related but which has nothing to do with this issue, since it also happens with RenPy 8; that probably has something to do with the fact that I'm actually using a VM and RDP)

Thank you for reading, and I hope this can get fixed soon! Because right now I can't possibly think of any other possible solution to run RenPy 7 games in the browser, if this is how things currently are. (...unless by emulating Linux in the browser, but that won't go smoothly.)

**Comment by Kassy2048** [comment]
The crash comes from the fact that `emscripten.webgl_enable_extension()` is not defined for [Ren'Py 7](https://github.com/renpy/renpyweb/blob/master/python-emscripten/emscripten.pyx). Either we define it the same way as in [renpy-build#f875ff4](https://github.com/renpy/renpy-build/commit/f875ff4e2c8ea29da69804a668ea077b479b63b7) or just prevent [the call](https://github.com/renpy/renpy/blob/a2529e3af51308df5eaea4390ecae2d4f879e506/renpy/gl2/gl2draw.pyx#L468) for python 2.

It is strange that using gles2 fails on your Windows box though, as even the oldest WebGL version supports it. There might be something to fix here, but I'm not OpenGL savvy enough to figure out what.

**Comment by renpytom** [comment]
@Kassy2048 Finds the underlying issue. We'll fix that, but in general we don't support Ren'Py under emulation/virtualization/etc, unless it's platform provided.

**Comment by Kassy2048** [comment]
My bad, I didn't see your Windows tests were done in a VM. That's indeed expected.

I've pushed [a PR in renpyweb](https://github.com/renpy/renpyweb/pull/39) to fix the crash on the other (non-VM) platforms.
