### ISSUE TITLE
RenPy Games played in Safari and Other Web Browsers Crash Randomly and  for No reason

### ISSUE THREAD

**Issue by R1un** [renpy/renpy#5479]
Many games face the this problem No matter if the game is a light or Heavy Load (By Heavy load i mean games that are filled with animations and transitions ) and to make sure the problem isn't associated with my device i tried multiple devices still the same problem appeared ( all of them ran IOS Or IPadOS operating system and in all of them i have used Safari Web Browser) and just to make sure that the problem isn't just with Safari Web Browser I Ran the same Game (and other Games to make sure the issue isn't just with this game )in All the different devices using Chrome,Microsoft Edge,FireFox, FireFox Focus,Opera,Opera GX,Brave Web Browser and Expectedly i had the Same Problem just thought this Info might be Helpful to fix this issue in the future,and if you can give me any tips and tricks to avoid these random crashes I would be Grateful and i am player not developer

**Comment by renpytom** [comment]
Are these older games using older versions of Ren'Py? There were changes in browsers that made older  games stop working, but those should be fixed. 

Beyond that - not every computer can run every game.

**Comment by R1un** [comment]
No most of the games ran the latest RenPy version,and well maybe your right not every device can run every game i guess but that is not really the problem here the games do run smoothly until they crash out of nowhere the crashes happen randomly it could take one minute for the game to crash again or maybe it could take an hour it happens randomly and what makes it even weirder is that some of my older devices that are weaker ran some games perfectly fine while my new phone couldn't i guess i am just unlucky after all i am clueless and sorry if appear eager and maybe annoying for this

**Comment by renpytom** [comment]
I haven't had any experience of this, and without any leads I have to close this issue.
