### ISSUE TITLE
is it possible to contain multiple different stories in a Renpy project?

### ISSUE THREAD

**Issue by MaxTran96** [renpy/renpy#5483]
is it possible to contain multiple different stories in a Renpy project? So that user can come in and choose story they want to read.

**Comment by qTich** [comment]
I think you need this - [action Start](https://www.renpy.org/doc/html/screen_actions.html#Start)

**Comment by MaxTran96** [comment]
@qTich  do you know if its possible to call api within a renpy project (using flask maybe)? im working on building a visual novel project that can integrate with AWS services to pull image and text file from server via AWS lambda instead of having it within the client. Is that possible?

**Comment by qTich** [comment]
> @qTich do you know if its possible to call api within a renpy project (using flask maybe)? im working on building a visual novel project that can integrate with AWS services to pull image and text file from server via AWS lambda instead of having it within the client. Is that possible?

[renpy.fetch](https://www.renpy.org/doc/html/fetch.html#https-http-fetch)

**Comment by renpytom** [comment]
Ren'Py really isn't designed to support multiple stories in one project. 

The one thing you can do is to download your project to another location on your computer, and then use the subprocess module to run :

/path/to/game1/game1.exe /path/to/game2

to use the version of Ren'Py in game1 to launch game2. 

**BE VERY CAREFUL**

Ren'Py's security model assumes that the game and all its data are trusted. That's not the case if the data for the game comes from a server. Before deploying this, ask yourself what would happen if the server was stolen from you - how are you going to guarantee that your players don't get served malware?
