### ISSUE TITLE
Can renpy hosted on a mobile web be responsive?

### ISSUE THREAD

**Issue by MaxTran96** [renpy/renpy#5484]
i was looking at https://comfyanonymous.github.io/ComfyUI_tutorial_vn/ vs https://monogatari.io/ 
The one using Renpy (Comfyui vn) doesn't seem to render well on mobile web

**Comment by Kassy2048** [comment]
Please elaborate what you mean by "[it] doesn't seem to render well on mobile web", and note that site uses Ren'Py 7.5.3 which is a pretty old version (current is 8.2.1).

Ren'Py uses Python as its main scripting language, and running Python inside browsers is slower than using a native JS engine. AFAIK, there have been multiple attempts to create a VN engine that looks and feels like Ren'Py using only native Web technologies, but their development was all eventually abandoned. For instance, the last version of Monogatari was released 2 years ago and it's no better for RenJS 🙁

**Comment by MaxTran96** [comment]
as in it feels a bit clunky loading https://comfyanonymous.github.io/ComfyUI_tutorial_vn/  on a mobile chrome browser, the resolution also is still in landscape mode. So the only way of making the VN fit the mobile web is to provide the portrait resolution version of the VN images right?

**Comment by Kassy2048** [comment]
Indeed, the game aspect ratio can only be set when the game loads so it cannot change afterwards if the user changes their phone orientation. Some Ren'Py games that simulate a phone UI set a portrait aspect ratio and they fill the whole screen when the phone screen is in portrait mode (and look bad in landscape mode ofc). Even for native mobile games, it is uncommon to support both modes, but at least, native games can force the screen orientation (which is not possible for Web pages).

**Comment by MaxTran96** [comment]
got it. Thank you! Ill close this out
