### ISSUE TITLE
Set GamepadExists(developer=False) globally?

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#5490]
Is there a way to easily toggle that **ALL** `GamepadExists()` statements either check if `config.developer` is True or not?

Sometimes I want to test it, sometimes I don't. Going back to add "False" each time I don't need it anymore is a bit inconvenient.

**Comment by MiiNiPaa** [comment]
Any problem in computer science can be solved by another layer of indirection
```
init python:
    check_developer = True
# . . .

# SOmewhere where you want to use it
GamepadExist(developer=check_developer)
```
Now you just need to change value of `check_developer` to change behavior of all `GamepadExist` that uses it.

**Comment by renpytom** [comment]
@MiiNiPaa Has the right answer.
