### ISSUE TITLE
Relationship Hierarchy

### ISSUE THREAD

**Issue by N0lla** [renpy/renpy#5494]
Feature Request:

Is it possible to add character relationships, so a hierarchy can be made. That way you can add friends, family together and any notes regarding them.

I know a number of renpy games kinda add this feature, but if was already built in it would be beneficial.

**Comment by renpytom** [comment]
This doesn't really seem like the sort of thing that belongs in the engine proper. I'm not actually sure what you mean by this, and I suspect it would vary from game to game, such that an engine implementation would be inadequate.

**Comment by N0lla** [comment]
Like in a database, where you can indicate how they relate to each other. I, believe it would be like a class implementation; where you can set up that character and the relationship between each of the different characters.

ie. 
MC -> stepsister (called to MC) 
stepsister (daughter to mom) (called mom by MC)
stepmom (called mom by daughter and MC)

**Comment by renpytom** [comment]
This doesn't really have anything to do with Python classes - at least, at the engine level. You can implement something specific to your game, but everything would want it differently, and so this isn't a candidate to be implemented in Ren'Py.
