### ISSUE TITLE
[Feature Request]: scene expression disable exception throwing, show text instead for missing image name

### ISSUE THREAD

**Issue by levicki** [renpy/renpy#5499]
Is there a way that you could modify `scene expression` so that it only shows name of the (dynamic) image which is missing on the screen like `scene` does when file is not found instead of crashing and burning?

The way it is now it's really inconvenient for testing the game when you don't have all the image combinations ready in advance.

So basically, if I have code:
```
$ location = "basement"
$ timeofday = "night"
$ clothes = "dirty_rags"
scene expression "[location]_[timeofday]_[clothes].png"
```
And if the image `basement_night_dirty_rags.png` doesn't exist then just write it on the screen as if the code was:
```
scene basement_night_dirty_rags.png
```
Thanks in advance for considering it.

**Comment by mal** [comment]
I think you're looking for `config.raise_image_exceptions` which can be set to `False`.

**Comment by renpytom** [comment]
cbf17de9b adds the new config.raise_image_load_exceptions variable. Setting this to false will produce error text rather than the exception handling mechanism.

**Comment by levicki** [comment]
> [cbf17de](https://github.com/renpy/renpy/commit/cbf17de9bcf030edc9f018b829ce67adc9473307) adds the new config.raise_image_load_exceptions variable. Setting this to false will produce error text rather than the exception handling mechanism.

Thanks for implementing this. I am not sure it deserved a separate config option though.
