### ISSUE TITLE
[Usage Question] How to use Live2D on iOS‘s RenPy

### ISSUE THREAD

**Issue by Longtianmu** [renpy/renpy#5502]
As the document, I manually linked libLive2DCubismCore.a to my Xcode project.
But RenPy keep asking me about .so file.
RenPy Version: 8.1.3
SDK Version: 4.7R1
![image0](https://github.com/renpy/renpy/assets/60567448/ba11f570-1d0c-4d2f-a8fd-e64e7075962b)

**Comment by renpytom** [comment]
Try the 2024-05-11 nightly fix build, and let me know if it works. If not, I'll make a different fix.

**Comment by Longtianmu** [comment]
> Try the 2024-05-11 nightly fix build, and let me know if it works. If not, I'll make a different fix.

Sorry I didn't find this version on nightly site?
I just found 2024-05-10

**Comment by renpytom** [comment]
It'll be built sometime in the next 6 hours.

**Comment by Longtianmu** [comment]
> Try the 2024-05-11 nightly fix build, and let me know if it works. If not, I'll make a different fix.

![IMG_3903](https://github.com/renpy/renpy/assets/60567448/08511dba-8dd5-41f9-ba37-ff096d406c72)

Well still broken.
I suppose it may just use function from Live2D instead of loading any dlls, since Live2D core has already been linked.

**Comment by renpytom** [comment]
Can you try the latest build, please? IT looks like the fix may not have been pushed live.

**Comment by devmlew** [comment]
I can confirm that the commit fixed the issue.

**Comment by renpytom** [comment]
Thank you for letting me know.
