### ISSUE TITLE
`exec.py` broken in nightly?

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5503]
I recently updated my Ren'Py nightly to the most recent version and it appears the `exec.py` feature no longer seems to work. The file just sits there in the root directory, and doesn't get consumed.

**Comment by renpytom** [comment]
Where are you putting it?

**Comment by furudean** [comment]
In the root, like this
```
.
├── errors.txt
├── exec.py
├── files.txt
├── game
├── log.txt
└── traceback.txt
```

**Comment by renpytom** [comment]
Hm... it works for me. 

Can you take a look at config.basedir in the console, and see if that matches where you put exec.py ?

**Comment by furudean** [comment]
`config.basedir` gives me `/Users/meri/Code/kavaya/src` which is what I'd expect

```
→ pwd
/Users/meri/Code/kavaya/src
→ ls
errors.txt  exec.py  files.txt  game  log.txt  traceback.txt
```

**Comment by furudean** [comment]
Going to close this. I downloaded nightly from the binary and it started working again. I'm not really sure what happened here
