### ISSUE TITLE
Show() action mishandles non-keyword arguments

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5505]
In Ren'Py 8.1.3, the Show() action interprets the first non-keyword argument it is given to be the value of the `transition` keyword, even when `transition=None` is also specified.

This is easily fixed by rearranging Show()'s parameters in accordance with [Python 3 practice](https://www.digitalocean.com/community/tutorials/how-to-use-args-and-kwargs-in-python-3#ordering-arguments), i.e. by changing `screen, transition=None, *args, **kwargs` to `screen, *args, transition=None, **kwargs`.

I suspect this bug persists across all versions of Ren'Py 8, though I am unable to test them myself at the moment.

Code example:

```
init python:

    def show__init__(self, screen, *args, transition=None, **kwargs):
        self.screen = screen
        self.transition = transition
        self.args = args
        self.kwargs = kwargs

    #Show.__init__ = show__init__ # Uncomment to fix all errors.

screen test_screen(arg):
    text "Argument: {}".format(arg) color "#f00" align (.5, .5)

# Fails
$ Show("test_screen", "my_arg")()
"Test1."

# Fails
$ Show("test_screen", "my_arg", transition=None)()
"Test2."

# Succeeds
$ Show("test_screen", arg="my_arg")()
"Test3."
```

**Comment by renpytom** [comment]
Not a bug, this is necessary to keep compatibility with older games. (Or rather, it's a mistake that would be hard to fix now.)

**Comment by renpytom** [comment]
I'd recommend not changing Ren'Py, but just making your own MyShow function that returns a Show object.
