### ISSUE TITLE
Ren'Py Launcher does not contain accurate mapping for a bold font

### ISSUE THREAD

**Issue by EtchJetty** [renpy/renpy#5506]
The Ren'Py launcher contains one notable instance of a bolded version of Roboto, when viewing the version number. However, this usage does not contain accurate font mapping, and thus looks strange.
![image](https://github.com/renpy/renpy/assets/12105244/60b7fbf5-6b3d-493a-8e43-b237cffc0375)
**(Above: The default look of the launcher.)**
![image](https://github.com/renpy/renpy/assets/12105244/77465eea-672f-4b55-a1bc-b0223c7d7da7)
**(Above: The font mapping fixed by using `config.font_replacement_map` to accurately assign the bold font to Roboto.)**

The bolded line in question is in `about.rpy` in the launcher project. Below is my modified code that fixes the issue.

```renpy
screen about:

    $ version = renpy.version()

    frame:
        style_group "l"
        style "l_root"

        window:
            xfill True

            has vbox xfill True

            add "images/logo.png" xalign 0.5 yoffset -5

            null height 15

            text _("[version!q]") xalign 0.5 bold True font "Roboto-Light.ttf"

            null height 20

            textbutton _("View license") action interface.OpenLicense() xalign 0.5

    textbutton _("Return") action Jump("front_page") style "l_left_button"

label about:
    call screen about

init python:
    config.font_replacement_map["Roboto-Light.ttf", True, False] = ("Roboto-Bold.ttf", False, False)
```

The project does not currently come shipped with Roboto Bold.

**Comment by renpytom** [comment]
I don't think it's worth shipping a new font file for one line.
