### ISSUE TITLE
renpy crashing after running requests.get() function

### ISSUE THREAD

**Issue by GachaYTB** [renpy/renpy#5512]
Im trying to get data from a link, from my renpy game with requests and after i put the the requests.get() function, my renpy game crashes when i load it.

I used this code to use the function:
```
python:
    import requests
    r = requests.get("url") # this is the part that crashes it
    print(str(r.json))
```
also im using renpy 8.2.1
I dont know if its more because of the website, or because of the function.

**Comment by GachaYTB** [comment]
there isnt any error??? it just crashes nothing else

**Comment by renpytom** [comment]
I'd suggest using renpy.fetch instead. I don't have a great answer for you.

**Comment by GachaYTB** [comment]
ok
