### ISSUE TITLE
Steam library dll doesn't update with Ren'Py

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5516]
About a year ago, I did a first build of a game and integrated with steam with the steam libraries. It worked fine at the time. Now, a year later, it wasn't working.

After looking into it, it seems that the problem is that, after updating Ren'Py via the launcher several times, it was still using the steam dll from when I initially installed the steam library, and that was causing an error. I solved the problem by deleting the dll, and re-installing the steam lib through the launcher.

Suggest that the steam dll updates with the renpy version? Or lets the creator know there is an update and allow them to trigger it?

**Comment by renpytom** [comment]
Finally tracked this down. It's been fixed by 335f07604870fba12c232d97514b90c253e36e71 and 584073f8243e47d665c9acfd78e54382aa23ba7f
