### ISSUE TITLE
Roll forward?

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5526]
Rollback / roll forward is unlocked once a particular line of dialogue has been seen. Is it possible to enable roll forward on scroll wheel to advance the dialogue without having to have seen it first? 

I'm mostly asking out of a developer need -- It's nice to be able to zoom around quickly to get to a particular line. This isn't actually something you'd want when you're playing the final game.

**Comment by renpytom** [comment]
No, but you can just use skip for this. Rollforward will re-input the same things the user did before, which isn't great.
