### ISSUE TITLE
A feature to prevent screen resolution letterboxing

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5527]
If you stretch the window horizontally or vertically, Ren'Py letterboxes the game. It would be sensible to implement a snapping feature that preserves the aspect ratio of the window if it's scaled up.

**Comment by renpytom** [comment]
No, it wouldn't. Having tried it, resizing a window that has its own opinions about what size it should be is terrible.

**Comment by furudean** [comment]
Fair enough
