### ISSUE TITLE
6.99.0.183 console bug

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#553]
One big issue is Shift+O shows the console at the first time only. After hiding it, it never shows up. 
There's another minor issue. When the keymap "K_space" is mapped to some function, it can't be used in the console. For example, if K_space is mapped to "hide_window", pressing  the space key hides the console window instead of typing a space.

**Comment by renpytom** [comment]
This should be fixed in the next nightly. 

Good catch.
