### ISSUE TITLE
Execute Python when dialogue strings are said

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5533]
I have a need where I want to run python based on the text being said, on a per-character basis. As far as I know, there is no way to accomplish this currently.

This _could_ be implemented using character callbacks, if they provided the relevant text. Psuedocode to follow

```renpy
init python:
    def pike_callback(event, text, **kwargs):
        if event == "show":
          print("pike:", text)

define pike = Character("Christopher Pike", callback=pike_callback)

pike "I'm saying some words.{w} Here is a paragraph to show how the text would be segmented."
```

This above code should output

```
pike: I'm saying some words.
pike: Here is a paragraph to show how the text would be segmented.
```

It would make sense to me if `text` contains whatever text is associated with that event. The user may also want to get the full text for some reason. The `begin` and `end` events could carry that meaning, while `slow_end` etc could carry segmented text.

There might be a better way to implement this than with character callbacks.

**Comment by mal** [comment]
I believe you're looking for the [`renpy.lasy_say()`](https://www.renpy.org/doc/html/other.html#renpy.last_say) function, which can be used inside a character callback to return information about the line being said.

```renpy
init python:
    def pike_callback(ev, **kwargs):
        if ev == 'begin':
            ls = renpy.last_say()
            print("pike:", ls.what)
```

**Comment by furudean** [comment]
That does get me half the way there, but does it contain information about where in the current statement we are? Figuring out how the `{w}` factors in here is not trivial.
