### ISSUE TITLE
Add functionality for toggling Shaders on and off

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5534]
I have some shaders that I use which run fine on MOST machines, but some lower end machines wind up lagging / having trouble. These shaders aren't required to play the game, they just make it look nice. 

So I set up a few toggles in my preferences screen to let players turn these extra bits of visual flare off in exchange for some smoother gameplay. 

To get this to work, I had to override `renpy.gl2.gl2shadercache.ShaderCache.get` to just remove any of the 'disabled' shaders, based on the preference that was toggled in the preference screen, like so:
(replaceMethod is a helper function I wrote that makes it easier to... replace methods)
```
def _ShaderCacheGet(self,partsname):
    if (preferences.gfx_dof == False):
        partsname = tuple([x for x in partsname if x != "blur2"])
    return renpy.gl2.gl2shadercache.ShaderCache.get._old(self,partsname)

replaceMethod(renpy.gl2.gl2shadercache.ShaderCache,"get",_ShaderCacheGet)
```
This works wonderfully, but it'd be better if implemented directly, rather than replacing the method.

In my quest to accomplish this, I came across several threads and reddit questions of people trying to accomplish similar things, so I'm sure other people would find this feature useful. 

Maybe something like `renpy.toggle_shader(shader)` or `renpy.set_shader(shader,False)` and accompanying actions for screens.

**Comment by furudean** [comment]
Why not supply your shader with a uniform that it can branch on to disable itself?

**Comment by colinharvie** [comment]
Is there a way to globally set a uniform property  for all Transforms?

**Comment by furudean** [comment]
Here's an example, but it depends on how you use your shader ultimately

```
transform warbly:
    shader "watt.wave"
    mesh True

    u_enabled (0 if persistent.reduce_motion else 1)

    u_wave_amp (0.5, 1.0)
    u_wave_period (3.0, 3.0)
    u_wave_speed (0.3, 0.3)
```

**Comment by colinharvie** [comment]
I did try something like this initially, but it got real wonky when rollback and cached images got involved.

**Comment by furudean** [comment]
Try making it a persistent variable. Persistent should not interact with rollback and make things reevaluate.
