### ISSUE TITLE
add the ability to create const expressions at runtime

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#5537]
context:
im making another framework (a fire emblem framework this time). basically it creates an object and does stuff with it, and some fields of said object (like the background of the map, the size of the map, etc...) are guarenteed to be (or at least should be treated as) constant. so this object would be different from battle to battle, but for the battle it was created for, it would have fields that are constant

**Comment by renpytom** [comment]
Um... 

That's not a constant.  It means Ren'Py would have to re-optimized screens each time that object changes. 

This isn't going to happen.
