### ISSUE TITLE
Rolling back automatically 

### ISSUE THREAD

**Issue by evilashv02** [renpy/renpy#5538]
Every game Rolls back automatically. When I load a save it rolls back as far as it can by itself. When I try to start a new game I can't even get it to go past the first screen.

**Comment by renpytom** [comment]
Check your keyboard, to see if something is causing page up to happen, something like that. This is unlikely to be a Ren'Py problem, and is more likely a problem with your computer.

**Comment by evilashv02** [comment]
New computer and new mouse. The computer is still fairly new and I can't find anything wrong with it. It is only the ren py games that seem to be doing it. Other game engines work no problem. That's so odd.

**Comment by renpytom** [comment]
Can you grab the next 2024-05-26 nightly fix build from https://nightly.renpy.org/ please? Then add to a game a file named test.rpy with the line: 

define config.log_events = True 

And run a game. That will produce a ton of events in log.txt, and maybe I can find out what's happening there. 

The nightly build will be available in about 12 hours.

**Comment by paranormalized-encryptid** [comment]
I came across the exact same problem just now in Ren'Py 8.1.3. In my case I had both a controller and a keyboard plugged in at the same time, and as soon as I disconnected the controller the game stopped trying to rollback constantly. Could this be the case for you, @evilashv02?

**Comment by renpytom** [comment]
Closing for no response, feel free to re-open as necessary.

**Comment by RAVAN007in** [comment]
> I came across the exact same problem just now in Ren'Py 8.1.3. In my case I had both a controller and a keyboard plugged in at the same time, and as soon as I disconnected the controller the game stopped trying to rollback constantly. Could this be the case for you, [@evilashv02](https://github.com/evilashv02)?

**Comment by RAVAN007in** [comment]
> I came across the exact same problem just now in Ren'Py 8.1.3. In my case I had both a controller and a keyboard plugged in at the same time, and as soon as I disconnected the controller the game stopped trying to rollback constantly. Could this be the case for you, [@evilashv02](https://github.com/evilashv02)?

thanks man that work @paranormalized-encryptid

**Comment by evilashv02** [comment]
Yes! This was the case. I forgot all about this thread. Thank you for sharing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
