### ISSUE TITLE
Some `exec.py` scripts don't work if executed while the game is starting

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5539]
If you create an `exec.py` file containing a script like `renpy.set_autoreload(True)` and then launch the game, it will set `config.autoreload = True` and change the title bar to contain "autoreload" but the game will not actually reload when game files change. This may also be true for other functions, but this is the only one I've tried so far.

**Comment by renpytom** [comment]
You'd also need to call renpy.reload_script(). 

I don't think that this is a class of bug I'm interested in addressing - exec.py lets you attempt to do things at the wrong time or in the wrong order, and some if it won't work.

**Comment by furudean** [comment]
Yeah this has nothing to do with `exec.py`, I thought it was working to just console in `renpy.set_autoreload(True)` for some reason, but it actually never did.

**Comment by furudean** [comment]
Thanks for the pointer about `renpy.reload_script()`, I got what I wanted to work to work 🙂
