### ISSUE TITLE
Alt+F quits renpy ignoring a prompt in v6.99.0.190

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#554]
In v6.99.0.190, Alt+F key quits a renpy game before replying to a yesno prompt.
I used windows 7

**Comment by renpytom** [comment]
What do you mean by this? Alt+F4? It's normal that Alt+F4 twice in a row will immediately quit the game. (That provides a quick-quit, and lets the player quit even if the game customization is broken.)

**Comment by kyouryuukunn** [comment]
Sorry, I means Alt+F4.
In v6.18, pressing Alt+F4 show a yesno_prompt, and pressing again quit a game.
But in v6.99, first pressing quits a game before replying to a yesno prompt.
