### ISSUE TITLE
How to alter the dialogue in a game if there is no tl file?

### ISSUE THREAD

**Issue by GitHubuser12234556** [renpy/renpy#5542]
I am trying to change some dialogue outcomes from a game I installed online which is template project so I can't find the tl file in the usual spot by going to the game folder then the tl file and when I use developer mode it shows me that the line exists at tl/english/script/ActorScript/dana.rpyc:1087, so how can I change it?

**Comment by danac78** [comment]
This issue sounds a little confusing. If it is saying it exists in tl/english...., it is in the game folder (game/tl/english/script....). If that is not showing up in the game folder, it might be in an RPA (which by default hides the folder if the file is put into an RPA.) So, either you need to get the source or extract it from the RPA (plenty of unrpa tools out there). Also, you would need to change it in dana.rpy, not dana.rpyc. The rpyc is the compiled version, which is more machine language than high-level. Unclear if it is a template project why the source code wouldn't be available?

**Comment by Gouvernathor** [comment]
We do not support editing or decompiling games. Contact the game's developers.

**Comment by GitHubuser12234556** [comment]
Ok thanks a bunch
