### ISSUE TITLE
[Feature Request]: adjust error message text size to display resolution

### ISSUE THREAD

**Issue by 8o8b14Ka** [renpy/renpy#5544]
When working on projects with anything larger than 1080p error messages are too small to be readable. 

https://lemmasoft.renai.us/forums/viewtopic.php?t=65690
here is a problem description with a fix suggestion but everyone have to make it by themself every time they reinstall renpy. Please save their time by this feature. Thanks!

**Comment by renpytom** [comment]
Ren'Py should be doing this already, provided the game has run on a user's system successfully once.
