### ISSUE TITLE
config.gl_test_image seems to not work

### ISSUE THREAD

**Issue by bober-gith** [renpy/renpy#5547]
Tried both:
`define config.gl_test_image = "black"`
or 
`define config.gl_test_image = "images/blackscreen.png"`
with a black image.

But when the game is launching, it still shows all white. 
It is a very minor thing, it's just something I wanted to change because the first screen in this project is pure black so the switch from white to black is quite noticeable in this case.

**Comment by renpytom** [comment]
The GL test doesn't run for the gl2 renderer. 

There isn't anything displayed before the first frame of the game.

**Comment by Booplicate** [comment]
@bober-gith, perhaps you're looking for [this](https://www.renpy.org/dev-doc/html/splashscreen_presplash.html).
