### ISSUE TITLE
`config.quit_callbacks` is called on restart

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5548]
I have some resources that need freeing on shutdown which I've realized are being prematurely freed every time Ren'Py restarts. Consequently I'm a bit confused as to what the intended difference between `config.quit_callbacks` and `config.at_exit_callbacks` is and I can't seem to find a callback that executes only when Ren'Py is _actually_ quitting/terminating.

Is this intentional? If so, is there something else I can use?

**Comment by renpytom** [comment]
I think you're right. 

I've removed config.at_exit_callbacks as too confusing for anything but internal use. I've redocumented config.quit_callbacks, and I've added config.python_exit_callbacks.

**Comment by paranormalized-encryptid** [comment]
Great stuff. Thanks PyTom.
