### ISSUE TITLE
A event isn't called when click a close button in v6.99.0.190

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#555]
I use a "show" event on a yesno_prompt screen like below,

    screen yesno_prompt(message, yes_action, no_action):

        modal True
        on "show" action MouseMove(560, 170, 0.2)

But, a "show" event isn't called in v6.99.0.190 when click a close button on the window.
I use v6.99.0.190 and windows7

**Comment by nyaatrap** [comment]
It's works for me only if a mouse cursor is placed inside of the window. The problem is when a mouse cursor is on the window frame ('x' button), it's deactivated in 6.99.

**Comment by kyouryuukunn** [comment]
OK. Thank you.
