### ISSUE TITLE
Add argument to call_in_new_context so developer may opt out from clearing layers

### ISSUE THREAD

**Issue by Drachenfels** [renpy/renpy#5550]
This is a very niche problem I encountered when adding debugging capabilities to the game.

I had to use `call_in_new_context()` and observed that it's clearing layers I meticulously set before that. 

After digging into renpy source I found that:

https://github.com/renpy/renpy/blob/f5d065e1816388a16c50aab4833042fd1ff8eb3e/renpy/game.py#L321C1-L341C1

```py
def call_in_new_context(label, *args, **kwargs):
    """
    :doc: context

    This creates a new context, and then starts executing Ren'Py script
    from the given label in that context. Rollback is disabled in the
    new context, and saving/loading will occur in the top level
    context.

    Use this to begin a second interaction with the user while
    inside an interaction.
    """

    if renpy.game.log.current is not None:
        renpy.game.log.complete()

    renpy.display.focus.clear_focus()

    context = renpy.execution.Context(False, contexts[-1], clear=True)
    contexts.append(context)
```

Clear is always set to True.

It would be lovely to allow us to retain layers:

So change it from:

```py
-def call_in_new_context(label, *args, **kwargs):
+def call_in_new_context(label, *args, clear_layers=True, **kwargs):
```

And:
```py
-context = renpy.execution.Context(False, contexts[-1], clear=True)
+context = renpy.execution.Context(False, contexts[-1], clear=clear_layers)
```

**Comment by mal** [comment]
If it's for debugging, perhaps you can just remove the layers you are interested in retaining from `config.context_clear_layers` while in you're debugging?

**Comment by colinharvie** [comment]
Or just remove them from `context_clear_layers` before using `call_in_new_context` and then putting them back after?
I'm told you're not really supposed to change config after game start... but that hasn't stopped me.

**Comment by renpytom** [comment]
Look for this to be added.
