### ISSUE TITLE
Adult content links on Ren'Py home page

### ISSUE THREAD

**Issue by brylie** [renpy/renpy#5552]
We are considering Ren'Py for a kids' game development workshop, but we noticed that the renpy.org website prominently features games with adult content. While it's great that Ren'Py has sponsors and supports a variety of games, it’s concerning to have links to pornographic content directly on the front page. This can be problematic when parents and kids are directed to the site to learn about Ren'Py and access its documentation. 

It might be better if adult-oriented games weren’t highlighted so prominently on the open-source project’s website (even when behind an "adult content" warning page.)

**Comment by renpytom** [comment]
Thank you for your feedback. We're careful to age-gate games we consider to be adult, and do limit what goes in the banner ads, but fundamentally those are sponsors that help support development, so can't be removed.

**Comment by brylie** [comment]
>We're careful to age-gate games we consider to be adult

Currently, the renpy.org website features the following banner:

![Screenshot 2024-06-08 at 8 54 51](https://github.com/renpy/renpy/assets/17307/e852e987-38ec-4a29-beb4-0ca9c594d8a2)

When I click on that banner, I am redirected to the following pornographic website without any "age gate":

https://raspberrysoft.itch.io/indecent-wife-hana?utm_source=renpy&utm_medium=banner_half&utm_campaign=meet_hana

> fundamentally those are sponsors that help support development, so can't be removed

Ren'py can show gratitude for sponsors without linking to pornographic content in a couple of ways:

- extend the policy that limits what can go in banner ads to disallow linking to pages that feature pornographic material
- instead of linking to games, link instead to the game studios (who are the actual sponsors)

This latter approach can be seen, for example, on the Godot website, where the sponsored links are game studios.

![Screenshot 2024-06-08 at 9 03 37](https://github.com/renpy/renpy/assets/17307/76f69bbb-5a8a-47e9-afd6-6025855bf6f4)

**Comment by renpytom** [comment]
I checked, and the link you provided does trigger an itch.io age gate, unless you've chosen to disable it. (Try opening in incognito mode, and clicking through.) 

I don't plan to change things.

**Comment by brylie** [comment]
Ok thanks for checking. I must have clicked through and forgotten.

> I don't plan to change things.

Understandable. 

We’ve already moved onward with a different IF framework.

In any case, great work on Ren’Py ☀️
