### ISSUE TITLE
Third party sites link to malware.

### ISSUE THREAD

**Issue by JacSkulls** [renpy/renpy#5553]
Unfortunately, you read this right. Malware attack. I'm not talking about one of those false positive, either. This is someone going into the files to edit it so it'd automatically open the link to these Malware Viruses. It's happening more and more often.

I think the only way to prevent it is MAYBE through the whole "Turning it into a game" thing and maybe by exe file instead of through the scripts. This MIGHT actually help prevent it if these guys do not know how the exe files would work but it's a long shot and nothing is ever guaranteed.

If you can make one that is specifically for the purpose of preventing links from opening, I don't think it would interfere with anything as it would only ask users if they want to continue with the links that automatically open itself. And maybe some kind of line detector of where these links are in there.
To get the picture... Link tries to open automatically, gets stopped and ask players if they want to open the link with a warning below or above. If yes, they go to the links. If no, link is nulled.

From what I'm gathering, these links only become active when the game launches. It's often spread throughout the scripts and in different places.

I know I was told not to by our fellow Devs and Admin of Ren'Py in Discord but I have hundreds of people relying on me. I'll be trying to make a temporary fix for this kind of thing until something gets sorted out with you and your team. Will even share the file that I create with you all to be on the safe side and as a sign of trust that I have no intention of harming anyone's games or players or reputations and the like.

Good luck and I hope we can both minimize the damage to some extent. -JacSkulls

**Comment by renpytom** [comment]
Sorry? I don't understand what  you're asking for here.

**Comment by renpytom** [comment]
I don't think this is an issue with Ren'Py.

Reading your discord thread, it looks like people are downloading games from unofficial sources, and getting burned by malware. That's not a problem a game engine can fix. I'd suggest banning links to unofficial source of games.

**Comment by JacSkulls** [comment]
> I don't think this is an issue with Ren'Py.
> 
> Reading your discord thread, it looks like people are downloading games from unofficial sources, and getting burned by malware. That's not a problem a game engine can fix. I'd suggest banning links to unofficial source of games.

Is there a reason why I was kicked out of or banned from Ren'Py community?

Forget it. Won't come back if you folks are going to be this disrespectful.

Do you want the script me and my partner created to help aid you and your team? It's still flawed but seems to work.
