### ISSUE TITLE
External console

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5554]
It would be very useful for debugging if there was an external console. There's many times where I've wanted to see the output of a print statement at specific moments, but having to open up the console in the middle of transitions or at very specific points makes that difficult.

Similarly, there are times where I want to run code, but having the console over everything causes issues in seeing the effects. It'd would be real nice if there were some sort of external console to view output and run commands from. (I couldn't find anything in the documentation about this)

**Comment by Gouvernathor** [comment]
There is an option in the launcher to have another window showing the console output. You can type in there, but you can read in real time while your game runs.

**Comment by colinharvie** [comment]
Fantastic! That's 90% of what I needed. I can live without being able to enter commands, just being able to look at the output live helps tremendously.

**Comment by HorBro38** [comment]
You may also want to look into the `watch` command as well, you can use it to place specific variables on screen and track them as you're playing.
