### ISSUE TITLE
Link Camera/Layer transforms between layers

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5555]
It would be useful to specify camera/transform linkages between layers. Basically have certain layers take all their layer transforms / camera transforms from another layer. I'm using it for censors,

I've implemented it by modifying `renpy.display.scenelists.SceneLists.set_layer_at_list` so that the `at_list` is copied to the relevant layers, when the controlling layer has it's at_list changed. 

```
clone_layer_at_list = {
    "master":["ghostworld", "censor"]
}

def _set_layer_at_list(self,layer,at_list,reset=True,camera=False):
    if layer in clone_layer_at_list:
        clone_layers = list(clone_layer_at_list.get(layer))
        for clone in clone_layers:
            renpy.display.scenelists.SceneLists.set_layer_at_list._old(self,clone,at_list,reset,camera)
    return renpy.display.scenelists.SceneLists.set_layer_at_list._old(self,layer,at_list,reset,camera)

replaceMethod(renpy.display.scenelists.SceneLists,"set_layer_at_list",_set_layer_at_list)
```

(`replaceMethod `is just a helper function I wrote to replace methods on default classes and give me access to the originals)

**Comment by renpytom** [comment]
You should probably just implement a function that sets multiple layers' at_lists with a single command. This doesn't need engine support.

**Comment by colinharvie** [comment]
Maybe instead a callback for **set_layer_at_list**? 
My purposes of layer linking aside, I can see many reasons for wanting to intercept, modify, or execute other code at this point.

**Comment by renpytom** [comment]
Can you give some of those reasons? I'm trying to figure out why they wouldn't be covered by a custom function.

**Comment by colinharvie** [comment]
Sure! Most of the reasons I'm thinking are for achieving or automating various visual effects
- Layer Linking - ensuring two layers have the same camera / at_list, useful for things such as using a detached / rear layer as a texture/mask sent to a shader so things match up with the master layer (or whichever layer intended), or having a sort of alternate dimension overlay, etc.
- Modify / Adjust the positions of other elements on the same layer OR on other layers, like Speech Bubbles, which don't quite work if you are using the 3D Stage. 
- Trigger effects / visuals / sound effects tied to the camera positioning / orientation, etc (such as environmental effects, but particularly in cases when the player has some measure of control over the camera)
- Similarly, automating visuals (hide/show, transforms, etc) based on the layer / camera transform, (assuming this is something done frequently enough to warrant adding the function)
- Altering some of the transform properties (zoom, positioning come to mind) based on some other variables

All this said, I don't think this callback is something someone new to game dev and Ren'Py would use, but neither are most of the other callbacks already in ren'py. 

Although I think that last one can probably be achieved with the config.layer_transforms, now that I think about it.
