### ISSUE TITLE
Live2D models not having natural idle poses after their animations is completed in game

### ISSUE THREAD

**Issue by Rezar0Fura** [renpy/renpy#5559]
I believe someone had addressed this similar issue here before. But since I couldn't relate my problem and their solution to it (or maybe I am dumb), I will specify my issue here.

After integrating a few Live2D models I found in my game using Renpy, I am facing this issue regarding the animations made by the motions of the models. This video properly sums up my problem.

https://github.com/renpy/renpy/assets/140922879/59cef27c-1012-4f9d-9b0f-6089f311a357

When I set the loop to true, the animation gets repeatedly played with no proper transition. [The left character]

When I set the loop to false, the animation gets frozen after the action is played. [The right character]

I am tending towards the right of the character, but I don't want my character to be a goddamn blank statue as the rest of the dialogue still plays.

When I initially tested the models on the cubism viewer, they worked as I wanted. After the animation is played they stay still or fall back into a default idle state. The difference is they still seem animate, with natural blinking, breathing and slight hair movements. Like this:

https://github.com/renpy/renpy/assets/140922879/2c503b26-8d8a-4c4a-9607-257f07672ac2

How to achieve this effect?

**Comment by renpytom** [comment]
You should use loop, and specify the idle pose you want to use.

**Comment by Rezar0Fura** [comment]
@renpytom I am not a code expert. But I found during experimentation that the viewer, model3.json or motion3.json file have some code which tells it to still keep eyes, breathing and hair still in motion. Even if loop with some functioning file, the "looping" file will have no corelation with the last file, hence it will not show similar results like the viewer. Why do I say this?

digging in the original model file, I found an idle motion3.json file which kinda solves my probelm, but its far from what I want.

`show bust_10204_new id_normal_12 idle at center`

As you suggested, I made an animation link with idle motion. Here is the result


https://github.com/renpy/renpy/assets/140922879/7a20e722-0186-499c-83f4-7ec2127cf885

It is close, but I believe we can get to the bottom of this. I played just the id_normal_12  in the cubism viewer, the result is different.



https://github.com/renpy/renpy/assets/140922879/237c6fb4-e08b-45f5-842c-c6a23d8bc826


The difference: The eyes and body were moving in a slower and more subtle state in veiwer, while in renpy it became repetative and too quick. Even the body was in a fixed state with the same natural body movements in viewer, while the model broke its connections with previous motion file and entirely became a one.

Frankly I belive this has something to do with physics3.json file. Maybe its instructing the viewer to treat the model as an model with some function movements like natural blinking and such (However, I think it more so relates to using the mouse to make the character follow the cursor.). Again, being not a code expert, this is my guess.

I am dropping the entire zipped folder of the model here, just so someone can open it in something like visual code studio and get to the bottom of this. Its like 5 in the morning and the issue is eating me alive.


 
[bust_10204_new.zip](https://github.com/user-attachments/files/15749896/bust_10204_new.zip)

**Comment by renpytom** [comment]
Ren'Py doesn't currently support live2d physics.

**Comment by Rezar0Fura** [comment]
Oh, I knew it. You think the issue I am facing is related to this?

**Comment by renpytom** [comment]
Just from your description, it seems possible.

**Comment by Rezar0Fura** [comment]
@renpytom Thanks. I mean yeah, it should possible. I just down know if it accounts from a single code of line to a whole new modding and updates. I would be happy if you could work out what is taking me hours if not days, since I have no prior knowledge as coding :) 

Thanks in advance. I will be hoping good news

**Comment by renpytom** [comment]
I think we've had it - you need to bake the physics into the motions.

**Comment by Rezar0Fura** [comment]
Really! How so? Just to clarify, I have many other character folders from which I want same results?

**Comment by renpytom** [comment]
I don't know. That's live2d modelling, which is outside my experience.

**Comment by Rezar0Fura** [comment]
@renpytom Well. That sucks. Can either of us do something? Like can you implement this feature in future renpy updates or suggest me other ways I can get my issue fixed?

Or, should I use other software like unity? Which may avoid the issue if I remember.

**Comment by renpytom** [comment]
It's an issue I'm aware of, but it's not going to be in the next major release, probably. I'd rather you use Ren'Py, but it's up to you what you choose. As policy, I don't predict when features will enter Ren'Py.
