### ISSUE TITLE
Saving screenshots broken on Mac

### ISSUE THREAD

**Issue by lucinfernos** [renpy/renpy#5560]
In any Ren'Py project I make on my Mac, the screenshotting function is broken and I get a "Failed to save screenshots as (file path)" notification. I've tried
- creating a new project and not changing anything about it to see if something in my code is the issue
- changing config.screenshot_crop
- changing display size
- checking permissions
- updating the Ren'Py launcher
etc. and so far none of these issues has worked.
Here's a Lemma Soft Forum thread about everything we tried: https://lemmasoft.renai.us/forums/viewtopic.php?t=68428

Googling around resulted in some similar experiences but I couldn't find any solution.

**Comment by HorBro38** [comment]
What version are you running?  A fix was made for this in April: https://github.com/renpy/renpy/issues/4509

**Comment by HorBro38** [comment]
Looking over the lemmasoft forum; I see what you're getting now.  Extremely strange; this does appear to be specific to you though - both my Intel and ARM Macs do not have this issue.  Try updating to the nightly fix and see if the issue persists.

**Comment by qTich** [comment]
> * changing config.screenshot_crop

What value did you use?

**Comment by lucinfernos** [comment]
> Looking over the lemmasoft forum; I see what you're getting now. Extremely strange; this does appear to be specific to you though - both my Intel and ARM Macs do not have this issue. Try updating to the nightly fix and see if the issue persists.

Oh, the nightly fix did it! How strange. Now I know what to do if I ever get the problem again in the future, thanks!

**Comment by lucinfernos** [comment]
So, the issue has come back. If I try to  define screenshot_crop as anything, the screenshot saving fails.

**Comment by renpytom** [comment]
Is any error showing up in the log?

**Comment by lucinfernos** [comment]
> Is any error showing up in the log?

This is what I got:

`Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'Apple'"
Renderer: b'Apple M2'
Version: b'2.1 Metal - 88.1'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1054, 593) drawable=(1054, 593)
Maximum texture size: 4096x4096
Traceback (most recent call last):
  File "renpy/common/00keymap.rpy", line 322, in _screenshot
    if not renpy.screenshot(fn):
  File "/Users/cheswidberg/Documents/renpy-8.2.1-sdk/renpy/exports.py", line 2099, in screenshot
    return renpy.game.interface.save_screenshot(filename)
  File "/Users/cheswidberg/Documents/renpy-8.2.1-sdk/renpy/display/core.py", line 1469, in save_screenshot
    window = window.subsurface(renpy.config.screenshot_crop)
  File "src/pygame_sdl2/surface.pyx", line 642, in pygame_sdl2.surface.Surface.subsurface
pygame_sdl2.error.error: subsurface rectangle outside surface area.`

**Comment by qTich** [comment]
> > Is any error showing up in the log?
> 
> This is what I got:
> 
> ```
> Initializing gl2 renderer:
> primary display bounds: (0, 0, 1920, 1080)
> swap interval: 1 frames
> Windowed mode.
> Vendor: "b'Apple'"
> Renderer: b'Apple M2'
> Version: b'2.1 Metal - 88.1'
> Display Info: None
> Screen sizes: virtual=(1920, 1080) physical=(1054, 593) drawable=(1054, 593)
> Maximum texture size: 4096x4096
> Traceback (most recent call last):
>   File "renpy/common/00keymap.rpy", line 322, in _screenshot
>     if not renpy.screenshot(fn):
>   File "/Users/cheswidberg/Documents/renpy-8.2.1-sdk/renpy/exports.py", line 2099, in screenshot
>     return renpy.game.interface.save_screenshot(filename)
>   File "/Users/cheswidberg/Documents/renpy-8.2.1-sdk/renpy/display/core.py", line 1469, in save_screenshot
>     window = window.subsurface(renpy.config.screenshot_crop)
>   File "src/pygame_sdl2/surface.pyx", line 642, in pygame_sdl2.surface.Surface.subsurface
> pygame_sdl2.error.error: subsurface rectangle outside surface area.
> ```

Again, what value did you set in `config.screenshot_crop`?

**Comment by lucinfernos** [comment]
> > > Is any error showing up in the log?
> > 
> > 
> > This is what I got:
> > ```
> > Initializing gl2 renderer:
> > primary display bounds: (0, 0, 1920, 1080)
> > swap interval: 1 frames
> > Windowed mode.
> > Vendor: "b'Apple'"
> > Renderer: b'Apple M2'
> > Version: b'2.1 Metal - 88.1'
> > Display Info: None
> > Screen sizes: virtual=(1920, 1080) physical=(1054, 593) drawable=(1054, 593)
> > Maximum texture size: 4096x4096
> > Traceback (most recent call last):
> >   File "renpy/common/00keymap.rpy", line 322, in _screenshot
> >     if not renpy.screenshot(fn):
> >   File "/Users/cheswidberg/Documents/renpy-8.2.1-sdk/renpy/exports.py", line 2099, in screenshot
> >     return renpy.game.interface.save_screenshot(filename)
> >   File "/Users/cheswidberg/Documents/renpy-8.2.1-sdk/renpy/display/core.py", line 1469, in save_screenshot
> >     window = window.subsurface(renpy.config.screenshot_crop)
> >   File "src/pygame_sdl2/surface.pyx", line 642, in pygame_sdl2.surface.Surface.subsurface
> > pygame_sdl2.error.error: subsurface rectangle outside surface area.
> > ```
> 
> Again, what value did you set in `config.screenshot_crop`?

define config.screenshot_crop = (606, 30, 707, 1027)

**Comment by qTich** [comment]
> > > > Is any error showing up in the log?
> > > 
> > > 
> > > This is what I got:
> > > ```
> > > Initializing gl2 renderer:
> > > primary display bounds: (0, 0, 1920, 1080)
> > > swap interval: 1 frames
> > > Windowed mode.
> > > Vendor: "b'Apple'"
> > > Renderer: b'Apple M2'
> > > Version: b'2.1 Metal - 88.1'
> > > Display Info: None
> > > Screen sizes: virtual=(1920, 1080) physical=(1054, 593) drawable=(1054, 593)
> > > Maximum texture size: 4096x4096
> > > Traceback (most recent call last):
> > >   File "renpy/common/00keymap.rpy", line 322, in _screenshot
> > >     if not renpy.screenshot(fn):
> > >   File "/Users/cheswidberg/Documents/renpy-8.2.1-sdk/renpy/exports.py", line 2099, in screenshot
> > >     return renpy.game.interface.save_screenshot(filename)
> > >   File "/Users/cheswidberg/Documents/renpy-8.2.1-sdk/renpy/display/core.py", line 1469, in save_screenshot
> > >     window = window.subsurface(renpy.config.screenshot_crop)
> > >   File "src/pygame_sdl2/surface.pyx", line 642, in pygame_sdl2.surface.Surface.subsurface
> > > pygame_sdl2.error.error: subsurface rectangle outside surface area.
> > > ```
> > 
> > 
> > Again, what value did you set in `config.screenshot_crop`?
> 
> define config.screenshot_crop = (606, 30, 707, 1027)

As you can see from your `log.txt`, the window size is `(1054, 593)` and the area you specified is `(606, 30, 707, 1027)` to `(1313, 1057)`, which is outside the window, as indicated by the error.

**Comment by renpytom** [comment]
I think there may be an issue with Ren'Py here. My guess is that screenshot_crop hasn't kept up with some of the resizing work.
