### ISSUE TITLE
Live2d Android + Web Support

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5562]
I realize this is a low priority item, but the Live2D SDK does now include dlls for Android, and also has support for Web. 

It'd be nice to have support for both of those in Ren'Py, eventually.

**Comment by renpytom** [comment]
Android support has been around for a while. 

Web isn't supported by the Live2D Native SDK, so isn't going to happen.

**Comment by colinharvie** [comment]
Oh, sweet. The documentation still says it's not available for Android, so that's why I thought it wasn't available.

**Comment by renpytom** [comment]
Do you remember where you saw this?

**Comment by colinharvie** [comment]
https://www.renpy.org/doc/html/live2d.html

Right there in the big orange warning box:
`Live2D is not supported on the x86_64 Android platform, as a DLL is not provided for this platform. This means that it may have problems running on the Android emulator or ChromeOS.`

**Comment by renpytom** [comment]
Ah, that's one specific (rarely used) platform. Though it looks like there is an x86_64 dll now, so I'll re-open this.

**Comment by colinharvie** [comment]
I just found this in the change logs for 8.1, perhaps it was already taken care of?
`Live2D is now supported on x86_64 Android.`

**Comment by renpytom** [comment]
Fixed by 36690cd413b0100cb417021d6784dc342500d494
