### ISSUE TITLE
How to loop a defined order of motion/expression files continuously? (Live2D integration)

### ISSUE THREAD

**Issue by Rezar0Fura** [renpy/renpy#5567]
I have my code which is:

`show Origami_Raizen_uniform shy idleness idleness idleness idleness idleness idleness idleness idle at center
    with fade`
    
What does it do: In attempts to make an idle animation (since Renpy doesn't support that for now), I tried playing the animation in order which helped me archive what I want. However, I don't want to make long sentences of the same line to try making it a long loop.

if I keep the loop=True, the code will only loop the last "idle" motion. But I want a code which loops the entire line of (shy idleness idleness idleness idleness idleness idleness idleness idle) itself. How can I achieve this?

**Comment by renpytom** [comment]
There isn't currently a way top do this. Let me think if this should be added.

**Comment by Rezar0Fura** [comment]
Good then. While I think it should be added(assume its a simple command), I guess you may find better ways to introduce it with more flexibility

**Comment by thynetruly** [comment]
> Good then. While I think it should be added(assume its a simple command), I guess you may find better ways to introduce it with more flexibility

Did you figure out a solution that warranted closing the issue?

**Comment by Rezar0Fura** [comment]
No, I didn't saw it that it closed as completed.
