### ISSUE TITLE
Contains statement doesn't restart when it's reshow.

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#557]
In 6.99.0.190, contains statement in ATL works only the first time when it's shown. After hiding it, reshowing the same image doesn't restart ATL block from the first line. Here's an example code:

    image test:
        contains:
            "presplash.png"
            xalign .0
            linear 1.0 xalign 1.0
    
    show test # The image moves form the left to the right
    hide test
    show test # The image is sticked to the right

**Comment by renpytom** [comment]
I see this, but I'm going to push it to the second 6.99 pre-release, since it's bug rather an a regression.
