### ISSUE TITLE
get translation info with the id

### ISSUE THREAD

**Issue by Neyunse** [renpy/renpy#5570]
Since renpy.get_translation_identifier() exists, I think it would be a good idea to add something like renpy.get_translation_info(id). This could be useful to use when debugging the project. The result of this could be something like this:

```
statement = renpy.get_translation_info("start_xxxxxx") # if the id is not specified it will use renpy.get_translation_identifier() instead for the current statement

print(statement)

{
   "id": "start_xxxxxx",
   "character": "e",
   "statement": "hola mundo.",
   "translation" "hello world.",
   "line": 6,
   "file: "script.rpy"
}
``` 

Basically, this would allow to display the details of a dialog using its id.

**Comment by mal** [comment]
Related to https://github.com/renpy/renpy/issues/5414.

**Comment by renpytom** [comment]
I don't think this is possible with the way Ren'Py's translation system is designed. The translation system maps a single line of dialogue onto multiple lines of Ren'Py script. And so a one-to-one mapping like this isn't possible. 

I'm going to close this, as while #5414 is possible, this isn't.
