### ISSUE TITLE
Unsafe app blocked warning in android 13

### ISSUE THREAD

**Issue by stranger54321** [renpy/renpy#5572]
Hi,

Recently, I have been getting a warning from Google while installing Ren'Py builds. I have built many apps in Ren'Py and never encountered this error before.

![Screenshot_20240615_153101_Google Play Store](https://github.com/renpy/renpy/assets/71636301/eb41b692-cae7-4a04-a64c-8dcec38ba04e)

I have Android 13, so the required target SDK is 33, but Ren'Py's Android target SDK is only 29. Google does not consider a version more than two versions behind as safe.

So, the question is: how do I change the target SDK? I tried changing the value in the RAPT file, but I get an invalid error while installing the application.

**Comment by qTich** [comment]
> I have Android 13, so the required target SDK is 33, but Ren'Py's Android target SDK is only 29. Google does not consider a version more than two versions behind as safe.

https://github.com/renpy/renpy-build/blob/master/rapt/prototype/renpyandroid/build.gradle#L12

The current `targetSdkVersion` in `rapt` is version 33, what version of `Ren'Py` are you using?

**Comment by stranger54321** [comment]
> > I have Android 13, so the required target SDK is 33, but Ren'Py's Android target SDK is only 29. Google does not consider a version more than two versions behind as safe.
> 
> https://github.com/renpy/renpy-build/blob/master/rapt/prototype/renpyandroid/build.gradle#L12
> 
> The current `targetSdkVersion` in `rapt` is version 33, what version of `Ren'Py` are you using?

Strange.  I have  8.0.3,  8.1.2, 8.2.1, 8.6.3, 8.5.2  all looks like throwing same warning

**Comment by renpytom** [comment]
Check that you have Ren'Py set to update the java on build. If you don't, you need to update it yourself. 

(I'm assuming some of those are 7.x versions.)

**Comment by stranger54321** [comment]
Ok i have manually updated `compileSdkVersion 30` to `compileSdkVersion 33`(which was same in 8.2.1 SDK).  `minSdkVersion 21` to `minSdkVersion 19` & `targetSdkVersion 29` to `targetSdkVersion 33` .  Build Works fine Without any warning with 8.2.1SDK but getting invalid error in lower versions(renpy-8.0.2-sdk,,renpy-8.1.3-sdk, renpy-7.5.2-sdk, renpy-7.6.3-sdk)

**Comment by renpytom** [comment]
Can you post your android.json file?

**Comment by stranger54321** [comment]
sure
[android.json](https://github.com/user-attachments/files/15880450/android.json)


Build in 8.1.3-sdk

**Comment by renpytom** [comment]
I don't believe this is an issue with the latest Ren'Py, so i'm going to close this. Certainly, your examples have long since been changed.
