### ISSUE TITLE
Extract Dialogue option's IDs are unstable and are a pain to reference (See #5373)

### ISSUE THREAD

**Issue by PasixTheValkyrie** [renpy/renpy#5574]
This problem (#5373) is still persistent and as someone who followed the documentation both for translation and auto voice-lines, I'm now stuck in a debacle where multiple of my lines somehow were given a different ID and i'm now to figure out which ones changed and add a "id x" to the line, which is absolutely less than ideal.

For most lines I have not even made any changes, which is quite confusing. They've remained on the same line, had no changes in the content, etc.

It'd be great if there was an option to just auto-add the id after the line so you don't have to do that tedious work yourself, and ensures you're still using the same id henceforth.

**Comment by renpytom** [comment]
What do the id changes look like?

**Comment by PasixTheValkyrie** [comment]
One example is where it changed from;

scene1_postmenu3_995a1a28
to
scene1_postmenu3_0825939e

Nothing was changed in terms of the line in question.

**Comment by renpytom** [comment]
That isn't possible. The part at the end is a hash of the contents of the line, and so will remain the same if the line doesn't change. Do you have a diff or something?

**Comment by PasixTheValkyrie** [comment]
None for the script, no.

Some in the later stages, but this is scene 1, which already has multiple lines.

I sent out the translation files about a month ago, lines for the voice actor about two months ago. I didn't notice a difference between those, but upon getting the translation in, I noticed some of the lines were still English, which was weird.

Exported the dialogue again and noticed these changes.

The lines that still work obviously still have the right ID.

**Comment by renpytom** [comment]
I don't think this is possible without changing the line, in which case the id should change, since it's a new line. 

If you see it again, maybe use ctrl-z to undo changes to the file so we can compare. But I don't think I can repeat the problem without an example.

**Comment by PasixTheValkyrie** [comment]
This specific scene was finished months ago, so I'd have to do some serious digging to be able to uncover anything of the sort.

That said, I did delete the (at the time empty) translation files and re-generated these later due to prepping for a build. Would this count as a change?

Alternatively, I'd still quite like to ask for an option to append an ID to every line. This'd be a double solution at the point where it can ensure the line retains the same ID always and I don't have to sift through tens of thousands of lines to add the correct ID back now.

**Comment by PasixTheValkyrie** [comment]
![image](https://github.com/renpy/renpy/assets/43132310/36ee06b3-dcf2-411f-9e8b-1e5846be0f4e)
I did note this, but interestingly these IDs have not changed. Haven't found a trace of the ones that *did* change, yet.

**Comment by renpytom** [comment]
This isn't making a lot of sense to me, and I'm not planning on adding a tool to annotate files with dialogue ids, as that will make script files very ugly. Without a good example of what's causing this, I'm going to have to close this issue, as I don't see how to repeat the problem.
