### ISSUE TITLE
Exclude specific texts from translation files in Ren'Py.

### ISSUE THREAD

**Issue by DebatingPanda** [renpy/renpy#5575]
Hello!

I'm requesting a feature to prevent certain texts/label in Ren'Py from being included in the translation files. I frequently use debug messages in my code and do not want them to appear in the translation files. Currently, I have to manually remove these lines/labels each time I update the translation files.

Possible solutions:
- An option to prevent entire labels from being shown in the translation files.
- Allow for individual dialogue lines to be excluded from the translation files.

Thanks for providing this awesome framework!

**Comment by renpytom** [comment]
How are you invoking this text?

**Comment by DebatingPanda** [comment]
For example:
I have a menu at the start of the game for beta testers to jump to certain scenes.
Or I just a custom character for this. For personal debug messages I mostly use renpy.log() or print() ofc.

Some examples:
```
translate YOUR_LANG strings:

    # game/chapters/00/ch_00_00.rpy:5
    old "[[Debug Menu] Do you want to play a selected section or a normal playthrough?"
    new "[[Debug Menu] Do you want to play a selected section or a normal playthrough?"

# game/chapters/01/ch_01_00.rpy:145
translate YOUR_LANG ch01_02_pre_5f80f92c:

    # centered "Debug info: Scene 2"
    centered "Debug info: Scene 2"

# game/chapters/01/ch_01_16.rpy:116
translate YOUR_LANG ch01_16_02_ParkersHouseRouteFloor_22cd3d95:

    # dev.say "[[Debug Message] In this instance, you have to choose between [anya.ColoredName] and [jane.ColoredName] (going downstairs)."
    dev.say "[[Debug Message] In this instance, you have to choose between [anya.ColoredName] and [jane.ColoredName] (going downstairs)."
```

**Comment by renpytom** [comment]
I guess the question is, could I make it so that specific characters are not translated? Such that dev.say is not translated?

**Comment by DebatingPanda** [comment]
My first thoughts were like something similar to:
```
mc.say "I mean, could you imagine saying \"no\" to [lucy.ColoredName]? This [lucy.ColoredName]?" id ch02_04_BaristaLady_be149b59
```
Where I had to fix a typo but had to keep the translation id, maybe something with "id None"? Not sure how your code works in the end, but it would be helpful in either way, making specific character texts not showing up or anything.
