### ISSUE TITLE
com.google.android.play and target SDK update required for Google Play by August 31

### ISSUE THREAD

**Issue by npckc** [renpy/renpy#5580]
Hello, sorry if this is the wrong place to share, but I received this warning on all my apps built with Ren'Py on Google Play Console.

> com.google.android.play:core has added this note for core:1.10.0:
> 
> Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration
> 
> You may not be able to release future versions of your app with this SDK version to production or open testing.

I believe that Ren'Py current targets SDK 33, but SDK 34 will be required starting August 31 and Play Core library 1.10.0 used in Ren'Py may cause app crashes.

**Comment by renpytom** [comment]
This should be done with tomorrow's nightly.

**Comment by dannygaray60** [comment]
I tried with one of latest nightly and sdk target is still on 33

**Comment by renpytom** [comment]
@dannygaray60 I checked, and the latest 8.3 nightly targets SDK 35.
