### ISSUE TITLE
Texture2D function in shaders seems to work badly on AMD GPU(S?) 

### ISSUE THREAD

**Issue by Inoix** [renpy/renpy#5582]
Hi! I've been doing some shaders for my game, and it seems like texture2D is giving me some incorrect output on my RX 6600.
I use the following code:
```
define e = Character("Eileen")
define config.log_gl_shaders = True

init python:
    testVars ="""
    uniform sampler2D tex0;
    varying vec2 v_tex_coord;
    """
    testShader = """
        vec4 color = texture2D(tex0, v_tex_coord);
        gl_FragColor = color;
    """


    renpy.register_shader("T.test1",
        variables=testVars,
        fragment_200=testShader)
transform TEST1:
    shader "T.test1"
label start:
    scene black
    show sylvie
    e "Sprite with no effects" #without the shader
    show sylvie at TEST1
    e "Sprite with test1 (just setting gl_FragColor = color)" #with the shader
    return
```
Here how it looks without the shader (good): [link](https://imgur.com/a/a9o0L4e), with the shader (pixelated) - [link](https://imgur.com/a/SFa84ak)
I asked my friend with a Nvidia GTX 1060 3gb to try it, and it looked non-pixelated to him even with the shader, so I guess it is my gpu that is at fault here. here are my logs on pastebin: [log.txt](https://pastebin.com/JpPmRRJA)
For my exact usecase setting vec4 color to gl_FragColor is good enough, but it may not be enough in other cases.

**Comment by Inoix** [comment]
By the way, updating to the latest version (8.2.1) doesn't seem to change anything, here are the logs from it: [log.txt](https://pastebin.com/uX7QcSaD)

**Comment by qTich** [comment]
I have nothing to do with AMD.
Check your video card drivers.

**Comment by Inoix** [comment]
> Check your video card drivers.
Turned out that they were in face not the latest. I updated them to the latest version from amd.com (24.5.1 08.05.2024) and rebooted, but it doesn't seem to fix the issue.
log file: [log.txt](https://pastebin.com/A6BBUwZA)

**Comment by renpytom** [comment]
The default Ren'Py shader is:

```

    renpy.register_shader("renpy.texture", variables="""
        uniform float u_lod_bias;
        uniform sampler2D tex0;
        attribute vec2 a_tex_coord;
        varying vec2 v_tex_coord;
    """, vertex_200="""
        v_tex_coord = a_tex_coord;
    """, fragment_200="""
        gl_FragColor = texture2D(tex0, v_tex_coord.xy, u_lod_bias);
    """)

```

Which injects a level-of-detail bias. Your shader doesn't have that, so maybe it will help?

**Comment by Inoix** [comment]
Thanks, It fixes the issue! I guess the bias defaults to a wrong value in my case.
