### ISSUE TITLE
Access Displayable IDs

### ISSUE THREAD

**Issue by shawna-p** [renpy/renpy#5583]
I've been working on some Ren'Py plugins, and one feature which would be very useful for additional functionality is if displayables saved their ID as a property, or provided it in some other easily-accessible manner. If there's a method I've missed, do let me know.

This would help in situations where I would like to find out the ID of the currently focused displayable, such that a user could provide some action to happen if the IDs match. `renpy.display.focus.get_focused()` will return a Displayable, from which I am unable to directly get the provided ID.  If I want to find out the ID of a displayable, I end up reverse-engineering it from the ScreenDisplayable's widgets property until I find a match among the displayables and can then determine which ID it had in the dictionary.

A secondary request for a similar purpose is if Displayables which calculate the sizes of their children (aka boxes and grids) could save that information to a field after rendering so it could be fetched, in the same way the offsets are saved.

**Comment by renpytom** [comment]
I can see the id thing. 

I'm not sure about the sizes. In general, you're not supposed to look into the Displayables, as their implementation is not part of the Ren'Py API.

**Comment by shawna-p** [comment]
Understood about it not being part of the Ren'Py API. The reason I make these requests is because a lot of the time I build features off the existing features of Ren'Py to expand their functionality without fundamentally changing them. Usually I inherit directly where possible so it remains compatible even when the engine is updated, though I'm aware I'm on the hook if something changes enough to break my plugins.

The size being saved in particular would just save me from having to run a separate function to calculate the sizes after they've already been rendered and determined, or alternatively from having to copypaste the entire render method of a displayable to add this myself (thus rendering it much less future-proof). I use the sizes and offsets to calculate the locations of items in the viewport for keyboard & controller-compatible focus calculations. I'm not certain my current implementation is robust enough to be in the engine directly without some peer-review and testing. I also have a penchant for adding a bunch of tiny properties for minute tweaks which may be too specific for an engine feature.

**Comment by renpytom** [comment]
Yeah, that isn't a use case I'd want to support in-engine, as it means that I'd be locking the engine down too much.
