### ISSUE TITLE
Problem with Android Build! Getting Error on Ren'py 8.2.3

### ISSUE THREAD

**Issue by papalon** [renpy/renpy#5584]
Hello!
I can't build an Android package
I tried to download the files but I got error on Google (Also I tried by VPN)

![image](https://github.com/renpy/renpy/assets/166012871/a21fa0fb-510d-4646-8f71-f0139f00b82c)

Please help!

`Ren'Py 8.2.3.24061702

I'm compiling a short test program, to see if you have a working JDK on your system.

Java version: 21
Target version: 21
OK

The JDK is present and working. Good!

Updating project.

Creating assets directory.

Packaging internal data.

I'm using Gradle to build the package.
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.5/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build
> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :app:javaPreCompileRelease UP-TO-DATE
> Task :renpyandroid:preBuild UP-TO-DATE
> Task :renpyandroid:preReleaseBuild UP-TO-DATE
> Task :renpyandroid:writeReleaseAarMetadata UP-TO-DATE
> Task :app:checkReleaseAarMetadata UP-TO-DATE
> Task :app:generateReleaseResValues UP-TO-DATE
> Task :renpyandroid:generateReleaseResValues UP-TO-DATE
> Task :renpyandroid:generateReleaseResources UP-TO-DATE
> Task :renpyandroid:packageReleaseResources UP-TO-DATE
> Task :app:mapReleaseSourceSetPaths
> Task :app:generateReleaseResources UP-TO-DATE
> Task :app:packageReleaseResources
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease UP-TO-DATE
> Task :renpyandroid:extractDeepLinksRelease UP-TO-DATE
> Task :renpyandroid:processReleaseManifest UP-TO-DATE
> Task :app:parseReleaseLocalResources
> Task :app:mergeReleaseResources
> Task :app:processReleaseMainManifest
> Task :app:processReleaseManifest
> Task :renpyandroid:compileReleaseLibraryResources UP-TO-DATE
> Task :renpyandroid:parseReleaseLocalResources UP-TO-DATE
> Task :renpyandroid:generateReleaseRFile UP-TO-DATE
> Task :renpyandroid:javaPreCompileRelease UP-TO-DATE
> Task :renpyandroid:compileReleaseJavaWithJavac UP-TO-DATE
> Task :renpyandroid:bundleLibCompileToJarRelease UP-TO-DATE
> Task :app:processReleaseManifestForPackage
> Task :app:extractProguardFiles UP-TO-DATE
> Task :renpyandroid:bundleLibRuntimeToJarRelease UP-TO-DATE
> Task :renpyandroid:processReleaseJavaRes NO-SOURCE
> Task :renpyandroid:createFullJarRelease UP-TO-DATE
> Task :renpyandroid:mergeReleaseJniLibFolders UP-TO-DATE
> Task :renpyandroid:mergeReleaseNativeLibs UP-TO-DATE
> Task :renpyandroid:stripReleaseDebugSymbols UP-TO-DATE
> Task :renpyandroid:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :renpyandroid:extractDeepLinksForAarRelease UP-TO-DATE
> Task :renpyandroid:extractReleaseAnnotations UP-TO-DATE
> Task :renpyandroid:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :renpyandroid:mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :renpyandroid:mergeReleaseShaders UP-TO-DATE
> Task :renpyandroid:compileReleaseShaders NO-SOURCE
> Task :renpyandroid:generateReleaseAssets UP-TO-DATE
> Task :renpyandroid:packageReleaseAssets UP-TO-DATE
> Task :renpyandroid:prepareLintJarForPublish UP-TO-DATE
> Task :renpyandroid:prepareReleaseArtProfile UP-TO-DATE
> Task :renpyandroid:mergeReleaseJavaResource UP-TO-DATE
> Task :renpyandroid:syncReleaseLibJars UP-TO-DATE
> Task :renpyandroid:bundleReleaseLocalLintAar UP-TO-DATE
> Task :renpyandroid:extractProguardFiles UP-TO-DATE
> Task :renpyandroid:writeReleaseLintModelMetadata UP-TO-DATE
> Task :renpyandroid:generateReleaseLintModel UP-TO-DATE
> Task :renpyandroid:generateReleaseLintVitalModel UP-TO-DATE
> Task :renpyandroid:lintVitalAnalyzeRelease UP-TO-DATE
> Task :app:mergeReleaseJniLibFolders UP-TO-DATE
> Task :renpyandroid:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :app:mergeReleaseNativeLibs UP-TO-DATE
> Task :app:stripReleaseDebugSymbols UP-TO-DATE
> Task :app:extractReleaseNativeSymbolTables UP-TO-DATE
> Task :app:mergeReleaseNativeDebugMetadata NO-SOURCE
> Task :app:checkReleaseDuplicateClasses UP-TO-DATE
> Task :app:desugarReleaseFileDependencies UP-TO-DATE
> Task :app:mergeExtDexRelease UP-TO-DATE
> Task :app:mergeReleaseArtProfile UP-TO-DATE
> Task :app:mergeReleaseShaders UP-TO-DATE
> Task :app:compileReleaseShaders NO-SOURCE
> Task :app:generateReleaseAssets UP-TO-DATE
> Task :app:processReleaseResources
> Task :app:mergeReleaseAssets
> Task :app:compileReleaseJavaWithJavac NO-SOURCE
> Task :app:generateReleaseLintVitalReportModel
> Task :app:dexBuilderRelease UP-TO-DATE
> Task :app:mergeDexRelease UP-TO-DATE
> Task :app:compileReleaseArtProfile UP-TO-DATE
> Task :app:processReleaseJavaRes NO-SOURCE
> Task :app:compressReleaseAssets
> Task :app:mergeReleaseJavaResource UP-TO-DATE
> Task :app:collectReleaseDependencies UP-TO-DATE
> Task :app:sdkReleaseDependencyData UP-TO-DATE
> Task :app:validateSigningRelease UP-TO-DATE
> Task :app:writeReleaseAppMetadata UP-TO-DATE
> Task :app:writeReleaseSigningConfigVersions UP-TO-DATE
> Task :renpyandroid:bundleReleaseAar UP-TO-DATE
> Task :renpyandroid:mapReleaseSourceSetPaths UP-TO-DATE
> Task :renpyandroid:mergeReleaseResources UP-TO-DATE
> Task :renpyandroid:verifyReleaseResources UP-TO-DATE
> Task :renpyandroid:assembleRelease UP-TO-DATE
> Task :renpyiap:preBuild UP-TO-DATE
> Task :renpyiap:preReleaseBuild UP-TO-DATE
> Task :renpyiap:mergeReleaseJniLibFolders UP-TO-DATE
> Task :renpyiap:mergeReleaseNativeLibs NO-SOURCE
> Task :renpyiap:stripReleaseDebugSymbols NO-SOURCE
> Task :renpyiap:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :renpyiap:generateReleaseResValues UP-TO-DATE
> Task :renpyiap:extractDeepLinksForAarRelease UP-TO-DATE
> Task :renpyiap:generateReleaseResources UP-TO-DATE
> Task :renpyiap:packageReleaseResources UP-TO-DATE
> Task :renpyiap:parseReleaseLocalResources UP-TO-DATE
> Task :renpyiap:processReleaseManifest UP-TO-DATE
> Task :renpyiap:javaPreCompileRelease UP-TO-DATE
> Task :renpyiap:mergeReleaseShaders UP-TO-DATE
> Task :renpyiap:compileReleaseShaders NO-SOURCE
> Task :renpyiap:generateReleaseAssets UP-TO-DATE
> Task :renpyiap:packageReleaseAssets UP-TO-DATE
> Task :renpyiap:prepareLintJarForPublish UP-TO-DATE
> Task :renpyiap:prepareReleaseArtProfile UP-TO-DATE
> Task :renpyiap:processReleaseJavaRes NO-SOURCE
> Task :renpyiap:mergeReleaseJavaResource UP-TO-DATE
> Task :renpyiap:writeReleaseAarMetadata UP-TO-DATE
> Task :renpyiap:mapReleaseSourceSetPaths FAILED
> Task :renpyiap:generateReleaseRFile
> Task :app:optimizeReleaseResources
> Task :app:lintVitalAnalyzeRelease

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':renpyiap:mapReleaseSourceSetPaths'.
> Could not resolve all files for configuration ':renpyiap:releaseRuntimeClasspath'.
   > Failed to transform review-2.0.1.aar (com.google.android.play:review:2.0.1) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find review-2.0.1.aar (com.google.android.play:review:2.0.1).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/play/review/2.0.1/review-2.0.1.aar
            https://dl.google.com/dl/android/maven2/com/google/android/play/review/2.0.1/review-2.0.1.jar
   > Failed to transform billing-6.0.1.aar (com.android.billingclient:billing:6.0.1) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find billing-6.0.1.aar (com.android.billingclient:billing:6.0.1).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/android/billingclient/billing/6.0.1/billing-6.0.1.aar
            https://dl.google.com/dl/android/maven2/com/android/billingclient/billing/6.0.1/billing-6.0.1.jar
   > Failed to transform transport-backend-cct-3.1.8.aar (com.google.android.datatransport:transport-backend-cct:3.1.8) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.status=release}.
      > Could not find transport-backend-cct-3.1.8.aar (com.google.android.datatransport:transport-backend-cct:3.1.8).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/datatransport/transport-backend-cct/3.1.8/transport-backend-cct-3.1.8.aar
   > Failed to transform transport-runtime-3.1.8.aar (com.google.android.datatransport:transport-runtime:3.1.8) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.status=release}.
      > Could not find transport-runtime-3.1.8.aar (com.google.android.datatransport:transport-runtime:3.1.8).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/datatransport/transport-runtime/3.1.8/transport-runtime-3.1.8.aar
   > Failed to transform transport-runtime-3.1.8.aar (com.google.android.datatransport:transport-runtime:3.1.8) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.status=release}.
      > Could not find transport-runtime-3.1.8.aar (com.google.android.datatransport:transport-runtime:3.1.8).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/datatransport/transport-runtime/3.1.8/transport-runtime-3.1.8.aar
   > Failed to transform transport-api-3.0.0.aar (com.google.android.datatransport:transport-api:3.0.0) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.status=release}.
      > Could not find transport-api-3.0.0.aar (com.google.android.datatransport:transport-api:3.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/datatransport/transport-api/3.0.0/transport-api-3.0.0.aar
   > Failed to transform transport-api-3.0.0.aar (com.google.android.datatransport:transport-api:3.0.0) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.status=release}.
      > Could not find transport-api-3.0.0.aar (com.google.android.datatransport:transport-api:3.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/datatransport/transport-api/3.0.0/transport-api-3.0.0.aar
   > Failed to transform transport-api-3.0.0.aar (com.google.android.datatransport:transport-api:3.0.0) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.status=release}.
      > Could not find transport-api-3.0.0.aar (com.google.android.datatransport:transport-api:3.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/datatransport/transport-api/3.0.0/transport-api-3.0.0.aar
   > Failed to transform firebase-encoders-json-18.0.0.aar (com.google.firebase:firebase-encoders-json:18.0.0) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.status=release}.
      > Could not find firebase-encoders-json-18.0.0.aar (com.google.firebase:firebase-encoders-json:18.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-encoders-json/18.0.0/firebase-encoders-json-18.0.0.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 44s
91 actionable tasks: 16 executed, 75 up-to-date

The build seems to have failed.`

**Comment by papalon** [comment]
I could download .aar files, But the .jar files can't be downloaded. Btw, I don't know where to put them

**Comment by renpytom** [comment]
I don't control this part of the Android build process. To build, you need to be able to download the proper files off of google's servers without your computer blocking them.

**Comment by papalon** [comment]
I removed the Rapt folder and installed it again but it didn't help
Then the problem was solved by updating the Rne'py to 8.2.3, but this time, my live 2d motions messed up and didn't work correctly in this version
Finally, I removed Renpy and installed version 8.2.1 again and the problem solved

Thank you

**Comment by n0neb0t** [comment]
same problem I dont know why it happens, even I can download files from browser but renpy can't
I have sdk version 8.2.0 to 8.2.3 all of them stop working even I had a success android build last month but now my sdk stop working 
any updated news?
