### ISSUE TITLE
Web build won't advance frames while cursor is moving on Firefox

### ISSUE THREAD

**Issue by NarwhalKid** [renpy/renpy#5585]
When playing any Ren'Py web build on Firefox, the frames freeze while the mouse is moving. Depending on what is being displayed on screen, sometimes it will still continue despite the mouse movement, but most things just completely freeze up. Once the cursor stops moving, the frames will skip ahead to where they should be.

Edit: Turns out, it happens no matter the input. Holding down a key on the keyboard achieves the same effect.

**Comment by renpytom** [comment]
I can't repeat this on Firefox 127.0.1 (64-bit), running on Ubuntu. It does repeat on Firefox 127.0.1, on Windows. 

Honestly, this looks to be more of a Firefox problem than a Ren'Py problem. I'd suggest working with Mozilla to get this solved, as it's weird that this works fine on one platform and not the other. (I've confirmed that it works in Chrome/windows as well.)
