### ISSUE TITLE
Default gui folder optimization

### ISSUE THREAD

**Issue by Raffael7777** [renpy/renpy#5586]
I'm not sure how the images in the gui folder are created for new Renpy projects, whether they are being copied from a source folder or if they are being generated through an image library function. Regardless, the size of the files within are shockingly large compared to what they _could_ be. Throwing the gui folder into an image compressor reduced its size by **91%**. I used Caesium Image Compressor. I set it to use **lossless** compression, png optimization level 6, no resizing or loss of metadata, and the same file-format as all the originals (still png, other formats might save slightly more still). **100% visually identical to the originals**. The folder went from 458,700 bytes (447.95 KB) to 42,052 bytes (41.57 KB).

At least four of the original files were 100 times larger than their counterparts. There's no reason 1920x1080 single-color images (some opaque, some with transparency) are 37.7 KB when a 100% visually identical lossless version is a mere 359 bytes.

Now, saving ~406 KB might seem extremely minor, but **at scale** it's not. While many game creators replace these files, some don't and use the default gui, and some merely add their custom gui files into the folder without replacing the originals, only changing the file names used in the relevant rpy file. Itch.io lists over 6k Renpy games. Estimates of how many games include these files, how many times they are uploaded or downloaded with every update a creator makes, or the extra storage and bandwidth used are impossible to make, but those numbers are constantly growing. I think it's safe to assume the inefficiencies of these files quickly adds up at this scale. The bandwidth could be reduced if more game creators used the web updater, but that is out of Renpy's control. The files are not.

I'm not saying that the files in the gui folder should be reduced to this "91% savings" number in my example. But in seeing how much savings is possible, I think it's very obvious some optimizations could be made to reduce these files' size, to save the collective amount of future storage and bandwidth used when Renpy games that include these default images are created and shared online.

**Comment by renpytom** [comment]
The images are compressed so the images load fast, not for minimum size. There's actually a bit of redundancy in them - having checked, going from the current png compression level of 3 to level 9 decreases the zipped-up size of the game/gui directory by 8KB, from 60 to 68 KB. 

To do this, it adds about 50ms to startup time. 

I don't thin kthis change is worth it.
