### ISSUE TITLE
ATL statement to flip/mirror displayables

### ISSUE THREAD

**Issue by blue-lt** [renpy/renpy#5597]
Now, I am aware `xzoom`/`yzoom` exist, but those only accept warpers. That means it is not easily possible to dissolve between flip/noflip in ATL. For games which rely on flipping images to rotate characters, this can be a problem. Take the following example of a character walking and turning around:

```py
show e:
    ease 1 xpos 0.8
    xflip with Dissolve(0.3)   #linear 0.3 xflip might be a more proper syntax
    ease 1 xpos 0.2
    
e "Look at me walk and talk"
```

This is, as far as I am aware, not possible currently. You have to settle for pausing until you can do another `show`:

```py
show e:
    ease 1 xpos 0.8

pause 1

show e with Dissolve(0.3):
    xzoom -1
    pause 0.3
    ease 1 xpos 0.2

e "Now I have to wait before talking"
```

Which obviously interrupts the dialogue. Another option is `linear 0.3 xzoom -1`, but that results in a paper Mario style flip. Dissolving isn't possible inside ATL.

**Comment by paranormalized-encryptid** [comment]
Could this work for you?

```python
transform dissolve_xflip(child, t):
	transform(child, xzoom=-1) with Dissolve(t)

show e:
	ease 1 xpos 0.8
	contains dissolve_xflip("eileen.png", 0.3) # Or whichever image you're using
	pause 0.3
	ease 1 xpos 0.2

e "I'm walking and talking!"
```

**Comment by renpytom** [comment]
@paranormalized-encryptid 's version (the general technique of transforming the child) is the right answer here. ATL can't dissolve between transform property changes, and isn't going to get that ability.

**Comment by blue-lt** [comment]
@paranormalized-encryptid and tom, apologies for the late response and thank you for the help. Unfortunately it took me quite a while to realize the second Transform should be capitalized, but now it works perfectly as such:

```py
transform flip_dissolve(child, t):
        Transform(child, xzoom=-1) with Dissolve(t)
```

It does cause the displayable to invert again on the next show for a reason I don't quite understand, but simply resetting the correct xzoom at that point solves that problem.

**Comment by paranormalized-encryptid** [comment]
> @paranormalized-encryptid and tom, apologies for the late response and thank you for the help. Unfortunately it took me quite a while to realize the second Transform should be capitalized, but now it works perfectly as such:
> 
> ```python
> transform dissolve_xflip(child, t):
>         Transform(child, xzoom=-1) with Dissolve(t)
> ```
> 
> It does cause the displayable to invert again on the next show for a reason I don't quite understand, but simply resetting the correct xzoom at that point solves that problem.

Oh, I didn't catch that typo -- I'm so sorry about that! Glad to hear you got it working though. It can be hard to get to grips with the language at first. And yes, transforms can persist like that sometimes.

Let me know if you run into any more trouble with it, I'm always happy to help.
