### ISSUE TITLE
Giving a button on confirm screen default_focus will focus even though input was a mouse click

### ISSUE THREAD

**Issue by brimbel** [renpy/renpy#5600]
Tested on 8.2.3.

Edit the confirm screen to add `default_focus True` to one of the buttons, mouse click a button that would prompt the confirm screen (such as quitting while in-game), and the button will be focused even though input was a mouse click
```
screen confirm(message, yes_action, no_action):

    ## Ensure other screens do not get input while this screen is displayed.
    modal True

    zorder 200

    style_prefix "confirm"

    add "gui/overlay/confirm.png"

    frame:

        vbox:
            xalign .5
            yalign .5
            spacing 45

            label _(message):
                style "confirm_prompt"
                xalign 0.5

            hbox:
                xalign 0.5
                spacing 150

                textbutton _("Yes") action yes_action default_focus True
                textbutton _("No") action no_action

    ## Right-click and escape answer "no".
    key "game_menu" action no_action
```

https://github.com/renpy/renpy/assets/106859253/5a70ec7e-e24a-46f7-a9b0-cf9409f1484c

**Comment by brimbel** [comment]
Tested on 8.3.0.

This fix only works sometimes. In the default Ren'Py game and other projects of mine, I get a very high failure rate. But in another project of mine (that I can't show here), I get a low but non-zero failure rate.

https://github.com/user-attachments/assets/85c59584-fad4-485e-88b6-c208065b5911

**Comment by renpytom** [comment]
Not 100% sure what you're doing, but it will only trigger if the mouse hasn't moved recently.

**Comment by brimbel** [comment]
In that case, it does still trigger after a mouse movement if you come to stop 

https://github.com/user-attachments/assets/fc7ffbf3-d320-4ebc-8c32-96620ca0c9fc
