### ISSUE TITLE
Shaders added to `Render()` break z-perspective via `mesh=True`

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5602]
It doesn't seem possible to ensure that a displayable blitted to a `Render()` object maintains its `zpos` with shaders applied because setting `mesh=True` destroys the z-positional information and 'flattens' the displayable. Is there a way to add shaders to a `Render()` and get it to apply everything correctly without having to set `mesh=True`? The Ren'Py documentation mentions that the `mesh` flag causes a few things to happen regarding textures and such, but I don't know how to manually implement the required steps (and without recreating the problem).

**Comment by renpytom** [comment]
If I'm understanding what you're asking - no. mesh=True creates a mesh and texture, and that's geometry, so the zpos inside it won't work.

**Comment by paranormalized-encryptid** [comment]
What I'm asking is if there's some way to apply shaders to a `Render()` (rather than, for example, a `transform`) _without_ setting `mesh=True`, so that the `zpos` can work? I don't know to get `Render()` to accept the shaders added to it without setting `mesh=True`.

I've also read something about Ren'Py creating and using 3D matrices throughout this process, but I don't know how those are accessed and manipulated or whether they relate to the `perspective`/z-axis system in a counterintuitive manner, given that Ren'Py seems to handle `z` in a special manner compared to `x` and `y`.

**Comment by renpytom** [comment]
If you don't need a texture, you can apply the shader - just call Render.add_shader.

**Comment by paranormalized-encryptid** [comment]
Unfortunately I do need at least one other actual texture which can't be reduced to a vector.

**Comment by renpytom** [comment]
In 8.3, you'll be able to supply a texture as a uniform.

**Comment by paranormalized-encryptid** [comment]
Fantastic, that'll probably do it! Thanks, PyTom.
