### ISSUE TITLE
In core.py, the hide_mouse function does not have a Store or Config variable for game developers to Toggle the feature.

### ISSUE THREAD

**Issue by SypherZent** [renpy/renpy#5610]
In Point & Click games that have Controller Support to navigate the mouse cursor using renpy.set_mouse_pos(x, y), this hide_mouse feature (introduced in v7.4.6) causes the mouse cursor to flicker between hidden and reappearing.

A simple recommended fix would be to include a new Store or Config variable and document it with the other Mouse variables (such as config.mouse_hide_time) that would allow developers to disable this feature.

For example:
default config.controller_hides_mouse = False

In the hide_mouse function (or perhaps in controller.py where hide_mouse is called), this config variable could be checked before executing the hide_mouse feature.

This would solve the problem of Controller supported Point & Click games having a flickering cursor when using the Gamepad.

**Comment by qTich** [comment]
https://github.com/renpy/renpy/blob/master/renpy/defaultstore.py#L363-L364
https://github.com/renpy/renpy/blob/master/renpy/main.py#L581

**Comment by qTich** [comment]
> mouse_visible has no effect on the hide_mouse function in core.py. Verifying the source code in GitHub can easily confirm this. Even so, I tested it myself in-game, before posting this.

`mouse_visible` controls method `Interface.is_mouse_visible`

I'm not quite sure what you're looking for:

Inside `Context`:
If you want to hide the mouse, then use `$ mouse_visible = False`.
If you want to show it, then `$ config.mouse_hide_time = None`.

You reference a method that solved the problem:  #2843

**Comment by SypherZent** [comment]
Those features do not work. I wouldn't be posting here if the feature I am requesting did not require an actual change in the engine's source code. Are you one of the developers?

Ren'Py version 7.4.6 added a feature **that automatically hides the mouse cursor when a button on the Gamepad is pressed**.

This feature cannot be turned off in the .rpy files. There needs to be a config variable that allows the feature to be turned off, so that Point & Click games that use Controller support to move the mouse cursor don't cause the actual cursor to be hidden.

Right now, using the LStick or DPad to move the mouse cursor causes the cursor to be hidden due to the hide_mouse function in core.py.

This hide_mouse function runs in controller.py line 200:

    def event(self, state):

        self.state = state
        self.repeat_time = renpy.display.core.get_time() + renpy.config.controller_first_repeat

        post_event(self.control, self.state, False)

        if renpy.display.interface is not None:
            renpy.display.interface.hide_mouse()



So, what I am requesting is this:

        if renpy.display.interface is not None and config.controller_hides_mouse:
            renpy.display.interface.hide_mouse()

This way, the config variable is required to be enabled for this hide_mouse feature to force the mouse cursor to be hidden.

Sorry if my original post was not self-explanatory. Hopefully this is enough context to help clarify the issue.

**Comment by qTich** [comment]
Again, if you set `config.mouse_hide_time = None`,
the cursor behavior will be adjusted according to `mouse_visible`,
as indicated by the `is_mouse_visible` method.

https://github.com/renpy/renpy/blob/master/renpy/display/core.py#L1824-L1829

**Comment by SypherZent** [comment]
Ahh okay. Note that mouse_visible did not work. I tested this multiple times.
I tested config.mouse_hide_time set to None in v8.2.1 and that solved the issue.
Also, it allows me to change it in mid-gameplay without any problems.

Actually, if the documentation for this could be updated, it would be really helpful (https://www.renpy.org/doc/html/config.html#var-config.mouse_hide_time).

Currently the documentation says "define config.mouse_hide_time = 30" but "define" variables are generally taken to be set at initialization and static (never changed during gameplay), and it has no mention of affecting the Controller auto-hide-mouse feature. However, this config setting actually can be changed during gameplay and it does take effect (so far, no unpredictable side effects), so it functions more like a "default" than a "define".

Anyway, I'll close this now, since this solved the problem. Thank you for your patience, qTich. I appreciate the help.

**Comment by qTich** [comment]
> Ahh okay. Note that mouse_visible did not work. 

`mouse_visible` is a dynamic variable and its value returns to its previous value after return.

> "define" variables are generally taken to be set at initialization and static

Exactly, if you make a save and quit the game, then come back in and load,
the value will be the original value. That's why I specified `Context` originally.
If you call the label in a new context, that context will be ignored on save/load.
(https://www.renpy.org/doc/html/label.html#renpy.call_in_new_context)

**Comment by SypherZent** [comment]
Okay, thanks for explaining.

Also, note, when I originally tested config.mouse_hide_time, I set it to 0 instead of None. But setting it to 0 does not work. So, that was the reason I thought it was not working. I feel like a quick update to the documentation will help clarify this for anyone else running into this issue (although, it's probably rare so maybe not a priority task).

Thanks again for your help and sorry for the confusion. ^^
