### ISSUE TITLE
Sync Error trying to upload android saves to sync.renpy.org

### ISSUE THREAD

**Issue by varkhan** [renpy/renpy#5612]
On Android 14, trying to sync app saves using the Upload Sync feature always result in a "Sync Error Could not connect to the Ren'Py Sync server". 

This is not a connectivity or DNS issue, as at the exact same time `https://sync.renpy.org/` can be successfully opened in a browser on the device.
However I don't have access to the details of the actual ConnectionError raised in 00sync.py so I can't tell more.

**Comment by renpytom** [comment]
The server ran out of memory and shut down. It's back up.

**Comment by renpytom** [comment]
Down again.

**Comment by renpytom** [comment]
Okay, should be back up now.

**Comment by varkhan** [comment]
I just tested right now, and it's still not working.

Having some kind of monitoring, and a health endpoint for this, e.g. `https://sync.renpy.org/api/sync/health`, would be really helpful. Maybe embed the results of the calls into https://sync.renpy.org/` as well, so users have an idea whether they have a chance rather than hammering the server.

**Comment by varkhan** [comment]
So, is the server down again, or there is some other bug preventing it from working? I am not so knowledgeable about Ren'Py dev, but I know quite a bit about cloud services, if that can help.

Though the idea of a server sync rather than a local / device sync to some shareable location, which has no dependency on infrastructure, may have drawbacks. 

Anyhow, if you welcome help, please say so.

**Comment by renpytom** [comment]
I just checked, and it's up.

**Comment by varkhan** [comment]
And yet, from the 3 games that use this feature I have installed, all of them say "Could not connect" even though the connection to `https://sync.renpy.org/api/sync/v1/` works (and returns 404, as expected).

Bottom line: this feature does not work. It need fixing.

**Comment by qTich** [comment]
> And yet, from the 3 games that use this feature I have installed, all of them say "Could not connect" even though the connection to `https://sync.renpy.org/api/sync/v1/` works (and returns 404, as expected).
> 
> Bottom line: this feature does not work. It need fixing.

`https://sync.renpy.org/api/sync/v1/` should return 404 because the sync id parameter is required.
Checked and sync works correctly (`PUT` & `GET`).

**Comment by varkhan** [comment]
> `https://sync.renpy.org/api/sync/v1/` should return 404 because the sync id parameter is required. Checked and sync works correctly (`PUT` & `GET`).

Yes. The point I was making mentioning this is that this is not an issue with the device, as its able to reach this URL on a browser and elicit the correct response.

If the Ren'Py app shows the "Could not connect to the Ren'Py Sync server" message, it's _entirely and uniquely_ an issue with the Ren'Py code. 
As I mentioned before, I have *no way* to debug further because the actual connection error is not shown.

As it stands, I repeat, this feature DOES NOT WORK on all my android devices and all the games I have tested.
