### ISSUE TITLE
Zoom and rotation anchor points

### ISSUE THREAD

**Issue by dwrein** [renpy/renpy#5613]
It would be really helpful to have separate anchor points for zoom and rotate. Right now, I have to adjust positioning every time I need to zoom in on certain parts of an image or rotate it. Something like "zoom_xanchor", "zoom_yanchor", "rotate_xanchor", and "rotate_yanchor" transform properties.

**Comment by renpytom** [comment]
Check out transform_anchor:

https://www.renpy.org/doc/html/atl.html#transform-property-transform_anchor
