### ISSUE TITLE
`.rpe` files are not read from the base directory

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5614]
Unlike what is documented in https://github.com/renpy/renpy/commit/c99a9052d4731d3a8c81d89b339f7568c8d626d3, `.rpe`/`.rpe.py` files are not loaded from the base directory

**Comment by brunoais** [comment]
Was that version already released?

**Comment by furudean** [comment]
No, this is in nightly

**Comment by mal** [comment]
This is working as documented in `8.3.0.24071002+nightly-sdk`.

Remember that `config.renpy_base` is the root of the SDK during development, **not** the root of your project. If you want to install an RPE for an individual project you must place it inside the `game` directory. The current behaviour allows you to install an extension for use with **all** your projects by adding it once to your SDK directory, or on a project-by-project basis by adding it to that project's `game` directory.

**Comment by furudean** [comment]
Oh, awesome. That's actually even better than what I thought.
