### ISSUE TITLE
Shader claims it cannot find `resN` uniform

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5615]
Ren'Py will sometimes claim that a shader has not been given a `resN` uniform even though it has no trouble finding the accompanying `texN`. Sometimes it will fail to find any resolution uniforms at all, sometimes it only finds some of them -- and not necessarily in order (e.g. it might find `res1` but not `res0`). Bizarrely, it might only complain when `resN` is used in one specific calculation but not another, and sometimes the issue seems to disappear without any obvious explanation. This behavior seems more or less completely random, at least to me.

The only thing I have noticed is that, in one of my test shaders, it only makes this complaint when I take something like this:

```python
// fragment shader

vec2 diff = res0/res1;

vec4 base = texture2D(tex0, v_tex_coord.xy, u_lod_bias);
vec4 example = texture2D(tex1, v_tex_coord.xy * diff, u_lod_bias);

gl_FragColor = vec4(example.xyz, base.w);
```

And change the last line to this:

```python
gl_FragColor = vec4(example.xyz, 1.0);
```

Where Ren'Py then throws an error claiming the shader wasn't given `res1`.

**Comment by renpytom** [comment]
Can you put together a short example that shows the problem? 

I'm guesssing that resn may not be provided if texn isn't used, but I would like to trace a full example through Ren'Py.

**Comment by paranormalized-encryptid** [comment]
Sure thing:

```python
init python:

    renpy.register_shader("example.bug", variables="""

        uniform float u_lod_bias;

        uniform sampler2D tex0;
        uniform sampler2D tex1;

        uniform vec2 res0;
        uniform vec2 res1;

        attribute vec2 a_tex_coord;
        varying vec2 v_tex_coord;

    """, vertex_300="""

        v_tex_coord = a_tex_coord;

    """, fragment_300="""

        vec2 diff = res0/res1;

        vec4 base = texture2D(tex0, v_tex_coord.xy, u_lod_bias);
        vec4 example = texture2D(tex1, v_tex_coord.xy * diff, u_lod_bias);

        gl_FragColor = vec4(example.xyz, base.w); // This works
        //gl_FragColor = vec4(example.xyz, 1.0); // This doesn't

    """)

    class ExampleDisplayable(renpy.Displayable):

        def __init__(self, child, other):
            self.child = renpy.easy.displayable(child)
            self.other = renpy.easy.displayable(other)
            super().__init__()

        def render(self, width, height, st, at):

            child_render = renpy.render(self.child, width, height, st, at)
            other_render = renpy.render(self.other, width, height, st, at)

            rv = renpy.Render(width, height)
            rv.mesh = True
            rv.add_shader("example.bug")
            rv.blit(child_render, (0, 0))
            rv.blit(other_render, (0, 0))

            return rv

image example = ExampleDisplayable("eileen", "sylvie") # Whatever images you have on hand

show example
"Shader test."
```

I suspect the same thing, though I can't say for sure that I've never had this happen even when using all the textures -- this problem has appeared a number of times and I honestly can't remember.
