### ISSUE TITLE
Show built-in screens on a specific layer

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#5618]
My game menu is on a custom `game_menu` layer (which is over `screens`), and so I noticed the Upload Sync / Download Sync screens don't show up properly.

(The same also applies to other built-in screens like the accessibility menu, developer console, and so on...)

Would it be possible to supply a specific layer all these screens will be shown on (instead of the default `screens`)?

**Comment by mal** [comment]
Are you able to elaborate on why your `game_menu` needs to be on a layer higher than `screens`? Knowing what the overarching goal is might help justify the feature, or the presentation of alternative solutions already that are possible/available.

**Comment by shawna-p** [comment]
I'll back this up - occasionally I do side sprites on a special layer above screens (so it's above the dialogue box) and they'll be in front of the console. It's possible to put dialogue on its own layer and sandwich the side image in between, but I agree it would make the most sense to just have debug/developer screens always on some kind of topmost layer.

**Comment by renpytom** [comment]
Is there a reason why you are using a layer for this rather than zorder? Zorder is the intended way to specify screen order.

**Comment by kigyo** [comment]
One of the reasons on my end was that there are many effects that I want to show on top of the say screen or other screens, while making sure that the game menu always stays on top of everything else.

To me, the benefit of layers is exactly that I don't have to remember whatever arbitrarily high number I gave a certain group of things, but rather that I can determine a human-readable hierarchy. And I definitely still make use of `zorder`, just for more granular control within each layer.

I think the general "issue" is that as long as it is possible to display things on top of the `screens` layer, it is possible to cover up the accessibility menu, console, etc.
