### ISSUE TITLE
transform_anchor messes with 3d stage

### ISSUE THREAD

**Issue by brimbel** [renpy/renpy#5624]
Tested on 8.2.3

When `transform_anchor` is True, certain 3d stage effects act (almost, though not quite the same) as though their matrixanchor is (0,0), resulting in bizarre behavior

```
label start:

    "START"

    camera:
        perspective True
    scene bg
    show eileen:
        align (0.5,0.5) transform_anchor True
        pause 0.25
        easein 1.0 yrotate 180

    "transform_anchor True"

    scene bg
    show eileen:
        align (0.5,0.5)
        pause 0.25
        easein 1.0 yrotate 180

    "transform_anchor False"

    scene bg
    show eileen:
        align (0.5,0.5) matrixanchor (1.0,1.0) transform_anchor True
        pause 0.25
        easein 1.0 yrotate 180

    "transform_anchor True + matrixanchor (1.0,1.0)"

    scene bg
    show eileen:
        align (0.5,0.5) matrixanchor (1.0,1.0)
        pause 0.25
        easein 1.0 yrotate 180

    "transform_anchor False + matrixanchor (1.0,1.0)"

    return
```

https://github.com/renpy/renpy/assets/106859253/5ad8f108-093e-4bf6-b7a4-15e48ac29079

**Comment by renpytom** [comment]
I don't think transform_anchor makes sense with the 3d stage functionality.

**Comment by brimbel** [comment]
If I'm animating a scene in 2d and have any number of displayables with transform_anchor True, and then I feel the need to do 3d briefly, that's already annoying to have to set transform_anchor False for all of those displayables and readjust their positions to be correct as it is with transform_anchor True.

Never mind that the way certain ATL properties interact and move with transform_anchor True can't be recreated with 3d stage properties (xzoom and yzoom manipulated in parallel blocks with different warpers and/or durations can't be recreated with matrixtransform ScaleMatrix(), crop/corner1/corner2 have no 3d stage equivalent at all).

transform_anchor is just very useful for the number of things that it affects, and 3d stage messing with that is inconvenient.
