### ISSUE TITLE
Expression in a button's If() action evaluated out of order

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5627]
I don't know if this is something that can easily be fixed, but here is what I consider a problem or bug:

```
screen myscreen():
    default clicked = False
    textbutton "Click Me!" action [ SetScreenVariable("clicked", True), If(clicked, Return()) ]
```

The documentation states: "A list of actions can usually be provided in lieu of a single action, in which case the actions in the list **are run in order.**"

I expect the screen to return after a single click, but the expression inside the `If()` function doesn't use the variable's current value, but instead the value from the moment the button was clicked (I guess, or maybe from the moment the screen was last drawn). This of course also happens with other kinds of variables.

If there is no bugfix for this, is there a workaround?

**Comment by Elckarow** [comment]
`action If(clicked, Return(), SetScreenVariable("clicked", True))`

**Comment by m-from-space** [comment]
> ~`action If(clicked, Return(), SetScreenVariable("clicked", True))`~ nvm i read that wrong

Maybe I should have added: Clicking the button the first time, won't return from the screen. Even though you would expect it to do.

**Comment by Elckarow** [comment]
well, if you want your screen to return after a single click, why the `If`? do you have another action in your screen that causes `clicked` to be False? because if that's not the case, you can just `action [SetScreenVariable("clicked", True), Return()]`

**Comment by Elckarow** [comment]
> Clicking the button the first time, won't return from the screen
then what i sent previously will work

**Comment by m-from-space** [comment]
> > Clicking the button the first time, won't return from the screen
> 
> then what i sent previously will work

Okay, calm down please, you may still not understanding what I am on about. xD

Maybe just put my example in a test project and see for yourself!

This is just an example, it's not about what I am doing here. But the fact that changing a variable's value in a list of screen actions, doesn't affect the expression inside the `If()` function that should be evaluated afterwards.

**Comment by Elckarow** [comment]
> But the fact that changing a variable's value in a list of screen actions, doesn't affect the expression inside the If() function that should be evaluated afterwards.

that's normal and expected behavior. the list of action is evaluated before it is ran.

**Comment by m-from-space** [comment]
> > But the fact that changing a variable's value in a list of screen actions, doesn't affect the expression inside the If() function that should be evaluated afterwards.
> 
> that's normal and expected behavior. the list of action is evaluated before it is ran.

It's interesting that you consider this expected or normal, since the documentation states the actions are run in order. People don't care about how the internals work, they just expect that something that is run later, will also contain all the later states. That's just programming logic.

**Comment by Elckarow** [comment]
i think you are confusing code evaluation and code execution

```
init python:
    myvar = 0

    def myprint():
        print(myvar)

screen test():
    textbutton "test 1" action (SetVariable("myvar", myvar + 1), Function(print, myvar))
    textbutton "test 2" action (SetVariable("myvar", myvar + 1), Function(myprint))
```

say this is the first time you're showing the screen
in the first action, the `Function(print, myvar)` has for arguments passed to the print function `myvar` which, when evaluated, is `0`. changing this variable when clicking `"test 1"` will not change this value as it has already been evaluated once, and therefore, `0` will be printed.

if you click `"test 2"` instead, `Function(myprint)` will grab the value of `myvar` when called (since it is not passed as argument), and will print `1`

**Comment by Elckarow** [comment]
`run in order` means that each action will be ran after the other, not that the entire list of actions will be reevaluated after each action ran

**Comment by m-from-space** [comment]
> i think you are confusing code evaluation and code execution

Oh, yeah, now it's hitting me. What I actually was expecting is, that Renpy does this in the background (so to speak):

`if eval(expression):`

But of course, it's not a string here, but already an expression in itself.

Well, maybe it would be an idea to change the function to:

`If("expression", true=None, false=None)`

instead of

`If(expression, true=None, false=None)`

Or at least provide a similar function expecting a string as an expression. Otherwise you cannot use simple logic inside screens actions, but instead call functions for that. But those functions cannot actually immediately execute other screen actions. At least I don't know how.

**Comment by Gouvernathor** [comment]
Strings in python are true if they are non-empty. There are games out there passing strings to an If condition and expecting it to cast the string to boolean, we can't change that now.

**Comment by m-from-space** [comment]
> Strings in python are true if they are non-empty. There are games out there passing strings to an If condition and expecting it to cast the string to boolean, we can't change that now.

Yeah that's a problem. Maybe something like this would be possible:

`if(expression, true=None, false=None, string_evaluation=False)`

**Comment by Elckarow** [comment]
> functions cannot actually immediately execute other screen actions. At least I don't know how.

they can with `renpy.run`

**Comment by renpytom** [comment]
I don't believe there is a change that needs to be made here.

**Comment by m-from-space** [comment]
> I don't believe there is a change that needs to be made here.

That's too bad, because I still think that clicking a button that changes one or more variables and then being able to use the `If()` function to check for the variable's contents seems something very profound to me. I encountered this multiple times. Instead of doing it like this you have to use strange if-else logic inside the screen that then uses a timer to check for changes or call your own function, which seems rather complex for something so simple.
