### ISSUE TITLE
`renpy.render_to_surface` breaks color texture when color is transparent

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#5630]
```rpy
init python:
    class TestSurfaceAlphaColor(renpy.Displayable):
        def __init__(self, width, height, color, **kwargs):
            super(TestSurfaceAlphaColor, self).__init__(**kwargs)

            self.width = width
            self.height = height
            self.color = Color(color)
        
        def render(self, w, h, st, at):
            rv = renpy.Render(self.width, self.height)

            cr = renpy.Render(self.width, self.height)
            cr.blit(renpy.display.draw.solid_texture(self.width, self.height, self.color), (0, 0))

            # cr = renpy.render_to_surface(cr, resize=True)
            rv.blit(cr, (0, 0))

            return rv

label start:
    scene expression "#000"
    show expression TestSurfaceAlphaColor(400, 400, "#ffffff76"):
        align (0.5, 0.5)
    "..."
```

without the call to `render_to_surface`, it looks like this
![screenshot0005](https://github.com/user-attachments/assets/4fe7f1fd-ea78-4503-aaa6-6f60abfd69ad)

uncommenting it gives you this
![screenshot0006](https://github.com/user-attachments/assets/8a6db299-a06e-4925-a1a9-03439a65ef75)

i tested with a regular image that had transparency and didn't have this problem.

**Comment by renpytom** [comment]
Fixed this, though your use of renpy.display.draw.solid_texture is both undocumented and wrong. (Calling renpy.render on a Solid is the right way to do this.)

**Comment by Elckarow** [comment]
how is it wrong exactly?

and i know it's undocumented, but what im making is quite expensive on the rendering side so i can't really afford to create a solid object and calling `renpy.render` each time i need to render a color

**Comment by renpytom** [comment]
I'm not going to go into that. It's undocumented for a reason.

**Comment by renpytom** [comment]
Solid/Render should be fine if you cache the Solids, as the Renders will be cached.
