### ISSUE TITLE
Ability to choose a start and an end point for ImageDissolve transitions

### ISSUE THREAD

**Issue by Charmareian** [renpy/renpy#5631]
I'm trying to make a transition for all four directions(right to left, left to right, down to up, up to down) and it doesn't seem possible with ImageDissolve currently? Maybe there's another way I could achieve this effect?

CropMove appears close to what I'm looking for, but it doesn't let you specify an image. So maybe an advancement for CropMove?

Current transition code:
![Screenshot_123](https://github.com/user-attachments/assets/683f1a63-2bf3-4b68-9584-097ce0d523c3)

Example of usage:

https://github.com/user-attachments/assets/9e69a8b6-64fe-4be3-bb39-3ebaabeae197

**Comment by MiiNiPaa** [comment]
It looks like a job for [MultipleTransitions](https://www.renpy.org/doc/html/transitions.html#MultipleTransition)

Old scene, Dissolve into black, Dissolve into new scene.

**Comment by renpytom** [comment]
@MiiNiPaa is right. This is: 

```renpy 
define mapwipe_left = MultipleTransition(
    False,
    ImageDissolve("wipeleft.png", 0.25, ramplen=128),
    "#000",
    ImageDissolve("wipeleft.png", 0.25, ramplen=128),
    True
)
```

**Comment by Charmareian** [comment]
Yes, but can I choose where the transition starts and ends with this method? Say I want the transition to start from the bottom of the screen and move towards the top, how would I do that and vice versa?

**Comment by renpytom** [comment]
You'd need to use the four different images to make four different transitions.

**Comment by Charmareian** [comment]
Oh okay, I see now. I don't understand how that works exactly, but it seems to do exactly what I wanted.
