### ISSUE TITLE
Button tooltip restarting interaction causes issues with AlphaMask on side image + config.side_image_same_transform

### ISSUE THREAD

**Issue by WindChimesGames** [renpy/renpy#5633]
So I discovered an issue caused by a very specific combination of things. 

I have a quick menu button with a tooltip (nearrect text), a side image that has an AlphaMask() applied to it in the say screen, and then a config.side_image_same_transform set. Whenever I hover or unhover the tooltip, the interaction restarts, which means if the current line had an attribute / expression change on the side sprite, it refreshes and dissolves from old attribute to new attribute again. 

...That's probably a horrible explanation, but here's a video: 

https://github.com/user-attachments/assets/43c133ec-7280-4e79-b5a5-1d2394502dbe

I found that if I remove any of three components (e.g. setting config.side_image_same_transform to None, or removing the AlphaMask() in the say screen, or removing the tooltip from the quick menu button), the issue goes away. But I can persistently reproduce this issue in other projects if all three elements are present. 

The code bits in question: 
```
screen say(who, what):
    style_prefix "say"

    window:
        id "window"

        if who is not None:

            window:
                style "namebox"
                text who id "who"

        text what id "what"

    if show_side_sprite:
        add AlphaMask(SideImage(), "sprites/raenelle/mask.webp") xoffset -39 yoffset -110 at side_image_size
```

```
screen quick_menu():

    zorder 100

    if settings_on:
        imagebutton auto "gui/textbox/setting_%s.webp" action ShowMenu('preferences') xalign 1.0 yalign 0.0 focus_mask True tooltip _("Settings")

    $ tt = GetTooltip()

    if tt:
        nearrect:
            focus "tooltip"
            prefer_top False
            text tt.upper() xalign 0.5 xoffset 18 yoffset -10 style "qm_tooltip_text"
```

```
transform same_transform(old, new):
    old
    new with Dissolve(0.2, alpha=True)

define config.side_image_same_transform = same_transform
```

**Comment by Elckarow** [comment]
what happens if you force the atl to use animation time (add the `animation` keyword)?

**Comment by renpytom** [comment]
Can you put together a demo game?

**Comment by WindChimesGames** [comment]
@renpytom 
> Can you put together a demo game?

Here you go! I used Deji's Agustina sprite to make a couple examples real quick. In case it matters, I'm usually on Ren'Py 8.2.2 but I tested this with Ren'Py 8.2.3 and the same issue still occurs 

[Tooltip AlphaMask Same Transform Issue.zip](https://github.com/user-attachments/files/16215606/Tooltip.AlphaMask.Same.Transform.Issue.zip)


@Elckarow 
> what happens if you force the atl to use animation time (add the `animation` keyword)?

Tried this if this is what you meant, and the same issue occurs
```
transform same_transform(old, new):
    animation
    old
    new with Dissolve(0.2, alpha=True)
```
