### ISSUE TITLE
Android - SDK target is still in 33 on AAB file

### ISSUE THREAD

**Issue by dannygaray60** [renpy/renpy#5634]
I have used `8.2.4.24071501`+nightly-sdk version of renpy, and the generated aab still has the target SDK at 33, when the playstore requirement is 34. The first time I compiled to AAB was using Renpy 8 stable, I don't know if there is any extra step to update the target SDK.

**Comment by renpytom** [comment]
The new target is coming in 8.3.

**Comment by renpytom** [comment]
I did check, and the latest 8.3 nightly targets Android 35.
