### ISSUE TITLE
"Selected" Style Property Prefixes fail to work for scrollbar elements.

### ISSUE THREAD

**Issue by geoWaffle** [renpy/renpy#5635]
While scrollbar (that is, scrollbar and vscrollbar) screen elements can be selected (i.e. put in a state that prevents the game from losing focus on the element during interaction), they fail to actually respond to "selected" style properties, using the appropriate Style Property Prefixes.

This can be seen by adding a unique "selected" image for the element to automatically pull from with [prefix_], which it will fail to do.

This has been tested thoroughly with "selected_", and tested a little with "selected_hover" and "selected_idle". The issue seemingly persists regardless of whether the images are stated specifically, or stated with the [prefix_] system.

Not sure if this is a bug or simply an intentionally missing feature not mentioned in the docs, but it seems so inconsistent with other aspects of screen language that I'm assuming it's a bug.

[This thread on the Lemma Soft forums](https://lemmasoft.renai.us/forums/viewtopic.php?p=568363&sid=b956bed8d5552a8d9a5c9fd2832c3087#p568363) has more information on the issue.

**Comment by the66F95** [comment]
hasn't this been fixed already with 0e6522f8673d990a3258390623519ff7c4c4cae8?
however, it is to mention that only associated "selected_hover" images are used, there is practically no visible "selected_idle" state.

**Comment by renpytom** [comment]
This seems to have been fixed. selected_idle isn't a thing with scrollbars.
