### ISSUE TITLE
Playstore upload error: You must tell us if your application uses any foreground service permissions.

### ISSUE THREAD

**Issue by dannygaray60** [renpy/renpy#5637]
When uploading the app bundle to playstore, an error appears "You must tell us if your app uses any foreground service permissions." And the following appears: ![Screenshot 2024-07-16 084848](https://github.com/user-attachments/assets/15c8240c-cc9f-49e5-8913-5dcdaca0e7a7)

And this is the android documentation page that appears: https://support.google.com/googleplay/android-developer/answer/13392821

I tried to add the permission in android.json but it didn't work ![Screenshot 2024-07-16 085009](https://github.com/user-attachments/assets/06d8a848-5830-442b-ae67-0e19c2ad53b9)

renpy version: renpy-8.3.0.24071502+nightly

**Comment by renpytom** [comment]
Did you add something to Ren'Py that requires that permission?

**Comment by dannygaray60** [comment]
No, i didn't added anything, just in the renpy launcher added the options to enable the playstore in app purchase

**Comment by renpytom** [comment]
Question: How big is the aab file containing your game?

**Comment by renpytom** [comment]
Also, can you go down to the App Content tab at the bottom of the play console, and screenshot what you see there?

**Comment by dannygaray60** [comment]
okay I tried reuploading again the aab file (around 100mb of size), but now changing the version and numeric_version in android.json and now the error is gone... Just in case I share a picture of the app bundle content, the permissions are the same as in previous versions of renpy, I don't really know if only the version change fixed it. 
![Screenshot 2024-07-16 195520](https://github.com/user-attachments/assets/f332a6ee-7fc0-48fb-97ce-d36f9816b510)

**Comment by renpytom** [comment]
I'm not 100% sure what happened, but if it works, it works. Can we close this out?

**Comment by dannygaray60** [comment]
Yeah hehe is working, thanks!
