### ISSUE TITLE
games not booting up 

### ISSUE THREAD

**Issue by Marwan1O1** [renpy/renpy#5638]
i have been having this issue recently where multiple games do not work i run it, and it shows me the loading screen then after the loading is over nothing happens here is the log that i have been getting from all of them i would ask the game devs but it seems like a ren'py issue rather than the game it self

Windows-10-10.0.19045
Ren'Py 8.2.3.24061702

Early init took 0.32s
Loading error handling took 0.11s
Loading script took 0.62s
Loading save slot metadata took 0.05s
Loading persistent took 0.02s

**Comment by danac78** [comment]
It is probably not a Ren'py issue because 8.2.3 had been out for a while, and it works fine in most circumstances.

Quick Question: Are you using Windows 10 32 or 64-bit? 8.0 and above run on 64-bit rather than 32 without the option for building a 32-bit version for Windows (Python 3).

Have you tried a different profile because that log is short and needs to run? For example, Initializing the gl2 renderer is not in there. Have you tried running this in a separate profile (Windows user account)? On a different computer? Have you checked your video drivers to make sure they are functioning properly?

**Comment by danac78** [comment]
```
2024-07-17 10:43:17 UTC
Windows-10-10.0.22631
Ren'Py 8.2.3.24061501+nightly

Fire Of Life: New Day 
0.48s.20240428
Built at 2024-04-28 13:25:19 UTC

Early init took 0.16s
Loading error handling took 0.12s
483 script files skipped.
Loading script took 1.51s
Loading save slot metadata took 0.78s
Loading persistent took 0.31s
Initialized steam.
 - Init at renpy/common/00steam.rpy:712 took 0.34352 s.
Set script version to: (8, 2, 3)
Running init code took 0.90s
Loading analysis data took 0.14s
Analyze and compile ATL took 0.06s
Reloading save slot metadata took 0.58s
Index archives took 0.02s
Dump and make backups took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.20s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.43s
Cleaning stores took 0.00s
405 script files skipped.
Init translation took 0.61s
Build styles took 0.02s
Load screen analysis took 0.12s
Analyze screens took 0.03s
Save screen analysis took 0.00s
Prepare screens took 0.40s
Save pyanalysis. took 0.02s
Save bytecode. took 0.00s
Running _start took 0.00s
Interface start took 0.35s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'ATI Technologies Inc.'"
Renderer: b'AMD Radeon(TM) Graphics'
Version: b'4.6.0 Compatibility Profile Context 24.3.1.240216'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1720, 968) drawable=(1720, 968)
Maximum texture size: 4096x4096

```
Except for the Steam mention, this is an average log.txt. So based on this, something is stopping before the Set script version.

**Comment by Marwan1O1** [comment]
to answer your first question i run it on 64 bit, second question no i havent tried to run it on a different profile i did test an older version of the game which still runs well for me for some reason so i am assuming my drivers are fine and one of the differences i noticed as well that i missed to add is that the older version that worked for me didnt ask for firewall permission even though i never installed it before but the games that do not run always ask

**Comment by danac78** [comment]
The only thing I can think of is that it legitimately needs Internet Access if they implemented the HTTP/HTTPS Updater. However, that usually happens during the Splash page phases (which you still need to reach). The only other legitimate reason could be asking if it is trying to talk to Steam. There are two reasons why the Firewall would ask for permission to connect to the network.

The illegitimate reason (that I can think of) why it would need permission to ask for network permission is that it tried to run something in the initial phases to download software other than the game. I suggest checking with the game developers to see if there is a reason why they need to connect with the network.

As far as video drivers, older versions of Renpy could turn off gl2. In 8.2 I believe, the default renderer is gl2 without a config variable to set it to False. So if the video drivers does not cooperate with gl2 but it should, uninstalling and reinstalling the video drivers should help with that situation.

**Comment by Marwan1O1** [comment]
so i opened renpy and changed my render off from the default to the other one i think it is called angel or something idk if that is the right way to do it but that also didnt work i contacted the dev for one of the games to see if there is a response on why it asks for firewall permission and i dont think it trying to connect to steam because i didnt download it from steam

**Comment by Marwan1O1** [comment]
issue found: the reason why that happens was due to steam being old since i didnt update it in a while and that is why games crash from it, anyway thanks for the help i couldnt pinpoint the issue until i carefully read your comment
