### ISSUE TITLE
Building documentation doesn't mention pygame_sdl2

### ISSUE THREAD

**Issue by caryoscelus** [renpy/renpy#564]
Tried to build renpy using instructions in README, got the error about missing pygame_sdl2.h

    gen/_renpy.c:252:37: fatal error: pygame_sdl2/pygame_sdl2.h: No such file or directory
    #include "pygame_sdl2/pygame_sdl2.h"

Found https://github.com/renpy/pygame_sdl2, installed it into the same virtualenv as renpy, no effect. No includes were installed (perhaps that's pygame_sdl2 build script bug or i did something wrong..).

In the end manual adding required .h files from pygame_sdl2 src/ and gen/ worked, but that's not how building supposed to be.

Please update building instructions to include pygame_sdl2 related actions.

**Comment by hasufell** [comment]
Is pygame_sdl2 supposed to be an actual generic module/library or is it only worked on in regard to renpy. If the latter is the case, then it's unlikely that it will get packaged by distributions... and that may also block/delay packaging the new renpy version.

**Comment by renpytom** [comment]
The answer is something between "I intend for it to be generic" and "I don't know yet". For now, I've been focused on getting Ren'Py out - but pygame_sdl2 should be suitable for a large number of pygame games, and provides an obvious path to Android and iOS. 

So I'm hoping other pygame projects will make use of it as it matures.
