### ISSUE TITLE
renpy.exports has no attribute proxies

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#5640]
As I was going to the update page in the Launcher, this is the message I receive:
While downloading the list of update channels, an error occurred. AttributeError: module 'renpy.exports' has no attribute 'proxies'.

**Comment by renpytom** [comment]
Should be fixed now, but you may need to re-download the nightly to get the fix.

**Comment by danac78** [comment]
@renpytom Yep. Now fixed.
