### ISSUE TITLE
Movie loop lag

### ISSUE THREAD

**Issue by leonholly** [renpy/renpy#5646]
I've been experimenting with a huge amount of different codecs and extensions (mostly VP9 webm/mp4), but there's one huge issue in every case. None of them can do a smooth movie loop.

Let's say we have a movie with a duration about 1 second. Every time it loops, there's a visible freeze for about 0.1 second, which is not very nice for such a short video.

I've tried both of Movie() class and renpy.movie_cutscene(). Changing 60 fps to 30 did help a bit, but it still noticeable. Also running the project on a better PC did nothing. Unsurprisingly, when I made the video longer and looped it in advance for, like, 5 times in a row, this lag became visible only after 5 prior loops, so the video's fine, it's something with RenPy's playback, hardware or it's just my lack of knowledge.

I'd be happy to hear it's not standard RenPy's behavior and the problem is on my side, so workaround is technically possible.

**Comment by renpytom** [comment]
Please post a project that uses the video.

**Comment by leonholly** [comment]
I tried it on a brand new project to avoid any other problems, so now it's that simple.
```
image my_example = Movie(play="images/anim/my example.webm", loop=True)

screen example_screen:
    add "my_example"

label example_label:
    call screen example_animations
    return
```
This one leads to the same result
```
label example_label:
    $ renpy.movie_cutscene("images/anim/my example.webm", loops=-1)
```

I think I should also post a videos I'm using, but it's NSFW and I don't have any other samples, so not sure if it would be a good idea, but I can say that the most promising vid was exported from Live2D as mp4 h.264+AAC and converted through ffmpeg, now it's 30fps 80kb 1920x1080 VP9 webm with 656kb/s bit rate, according to MediaInfo. I chose video instead of animation, because my project is mainly oriented on web. Bigger videos (max about 5mb) with better quality, that I'd like to use, show the same behavior, so I decided to test everything on the lightest one.

Do you have any suggestions where the problem might be?

**Comment by renpytom** [comment]
Please post the actual video file, so I can take a look and see if it's a file encoding problem.

**Comment by leonholly** [comment]
Not the same exact video I was talking about, but was processed like the previous one and shows with this lag too + raw Live2D output
https://dropmefiles.com/xCcU6

**Comment by renpytom** [comment]
Can you please resend the file? I just got to this today, but the file had been deleted.

**Comment by leonholly** [comment]
Sure, here it is
https://dropmefiles.com/k8zwW

**Comment by renpytom** [comment]
I'm not able to repeat the problem. 

I do occasionally see a frame that comes in early when the movie loops, but I don't see .1s lags. Do you have the problem in a new game?
