### ISSUE TITLE
pickle <module 'time' (built-in)> error when Ren'Py engine version differs

### ISSUE THREAD

**Issue by blackcatstudiosdevelopment** [renpy/renpy#5650]
**Issue**: When loading a save created by a previous engine version a pickle error is thrown related to the time module.

**Steps To Reproduce**:

1. Old Save Check
  1. Create or grab a save created in 'old' engine version.
  2. Copy/paste into 'new' engine's `saves` folder
  3. Launch game in 'new' engine and load save
2. New Save Check
  1. Create a save in 'new' engine
  2. Close game and relaunch
  3. Load save

**Expected Results**: Based on changelogs there should be no reason why any difference in save files is noticed.

**Actual Results**:
1. Old Save Check
  - Pickle error occurs
2. New Save Check
  - No pickle error occurs 

**Data**:

- Old engine version: 8.2.3.24061702
- New engine version: 8.3.0.24072302+nightly
- I do not know if this affects more than just the time module, but the error is noticed in this specific instance.
- I also do not know if this is due to the nightly version being unstable or caused by a difference in engine version string regardless of version.

**Related Discord Thread**: https://discord.com/channels/286633898581164032/286633898581164032/1265310855071928331

**Comment by qTich** [comment]
Have you tried to replicate that outside of your game?
