### ISSUE TITLE
`rpe` raising `MemoryError`

### ISSUE THREAD

**Issue by qTich** [renpy/renpy#5651]
On MacOS `exec` raises `MemoryError` after reading a file of `2.9 kB` size.

`exec(autorun, {'__file__': fn})` -> `exec(autorun.replace("\n", ""), {'__file__': fn})`
This solves the problem, but doesn't seem like a solution.

**Comment by renpytom** [comment]
That seems incorrect. What's the contents of the file?

**Comment by qTich** [comment]
https://github.com/python/cpython/issues/86854
