### ISSUE TITLE
add a "peek" method on the object returned by `renpy.open_file`

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#5653]
this would enable many 3rd party python libraries that require file handlers (like tinytag for instance) to use these objects

**Comment by renpytom** [comment]
Did you check that it doesn't exist? At least as far as I can see, these objects have a .tell method. If you can't get to it, I'd like to know what you're doing.

**Comment by Elckarow** [comment]
uhhhhh yes my bad. it's the "peek" method that i'm talking about
