### ISSUE TITLE
Renpy 8.2.3 keyboard mapping setting ctrl_alt combination error

### ISSUE THREAD

**Issue by molinghu** [renpy/renpy#5656]
As shown in the figure, as long as this key combination is set, an error will be triggered
![224E8F87F1693C4645978E58C261AE55](https://github.com/user-attachments/assets/29f236d0-e80f-4e9b-af9a-ad83bf1052cd)
![F39FF2EDC16355086BA543208E82391C](https://github.com/user-attachments/assets/94cbea00-516a-41df-8044-649b0cdb00a6)

**Comment by renpytom** [comment]
That's not a valid keysym. (You could use ctrl_K_LALT.)
