### ISSUE TITLE
`renpy.restart_interaction() was called 100 times without processing any input` error occured when using `tooltip` on `textbutton`

### ISSUE THREAD

**Issue by Kane-Joshua** [renpy/renpy#5658]
Below the error msg: 
![图片](https://github.com/user-attachments/assets/63e82a83-d244-4683-a6ac-c1464875411c)
- the tooltip did popped up with correct msg. **But** `renpy.restart_interaction() was called 100 times without processing any input` error popped up as long as you hover on the testbutton a bit longer(eg 1s). 
    - dont know  **what** or **what input was waiting** exactly these `100 times call` refers to. 
    - no error occur if the action is null (eg `action None` or `action NullAction`) for: no focus the textbutton gained → no tooltip display → no error
---
Codes Below:
```
#>>screens.rpy
...
screen quick_menu():
    ...
            textbutton _("Hist"):
                tooltip "Hist Tips Test"
                action ShowMenu('history')
            $ ttins1 = GetTooltip()
            if ttins1:
                nearrect:
                    focus "tooltip"
                    prefer_top True
                    text "[ttins1]"
    ...
```
---
- putting the following part of codes to the end of the block (ie under all the textbutton def blocks) make no changes.
```
...
            $ ttins1 = GetTooltip()
            if ttins1:
                nearrect:
                    focus "tooltip"
                    prefer_top True
                    text "[ttins1]"
...
```

**Comment by MiiNiPaa** [comment]
Don't stuff `nearrect` inside of `hbox`.

**Comment by renpytom** [comment]
I believe this has been solved by @MiiNiPaa . Just to elaborate, the showing and hiding of nearrect is breaking the layout, causing focus to be constantly gained and lost.
