### ISSUE TITLE
Imagemaps break after updating hotspot coordinates

### ISSUE THREAD

**Issue by caryoscelus** [renpy/renpy#566]
Removing cache/ seems to help, so maybe at least perfom it on "Delete Persistent" or "Force Recompile" (in launcher) or just on every reload when config.developer is True? Obviously, proper fix should be better, though.

Here's test game to reproduce: http://my-files.ru/DownloadSave/hszgcm/imagemaps-test.zip

Reproduction:

1. launch -> back button is displayed & hovers ok
2. edit script.rpy: comment first hotspot line & uncomment second
3. reload game -> back button is displayed off & hover is weird
4. remove cache/ & reload -> works ok

![imagemap-1](https://cloud.githubusercontent.com/assets/1758893/6487943/5bc00fb8-c2a5-11e4-88e4-7cde27f596f1.png)

**Comment by renpytom** [comment]
Thank you for the really good test case.

**Comment by caryoscelus** [comment]
Thanks for fixing this :) I'm preparing another test case for somewhat related issue now
