### ISSUE TITLE
Aliasing on Mesh Polygon Edges

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5660]
Although texture and subpixel smoothing works fine within the mesh and texture, meshes can still be aliased on the edges of their polygons. When it's a normal rectangular image, this is noticeable if the texture has no alpha or extends all the way to the edges of the mesh, and is mostly noticeable with very slow movements, as the edge of the mesh will snap to new pixels. This can be fixed by either using a larger texture with an alpha that does not extend to the edges, OR by using mesh_pad to extend the mesh.

However, this still poses a problem for Live2D sprites, as mesh_pad doesn't work on the submeshes used for rendering the sprites. Any meshes that have textures which extend to or off the edge of the mesh will appear as aliased.

I know there is a way to enable the smoothing of the polygon edges in opengl, but how to do it is beyond my skill level right now.

**Comment by renpytom** [comment]
I don't think this is really an issue with Ren'Py - it's just part of how computers display images. You can enable multisample antialiasing to disable this (at least in theory - in practice, it's expensive, so I wouldn't want to enable it by default.) Or better, you can just design your images to not have this problem.
