### ISSUE TITLE
subpixel True not working on layer displayable (detached layer) ?

### ISSUE THREAD

**Issue by NaughtyRoad** [renpy/renpy#5661]
I'm really excited about the use of the layer displayable to create a scene-in-scene/splitscreen sequence. 
So far it's doing everything I want it to, but it doesn't seem to work with subpixel True. Zoom/align transforms are janky and jumpy as you'd expect with subpixel set to False.

I've tried applying it directly in the atl for images displayed on a newly added detachable layer 'splitscene', like so:

```
    scene backdrop onlayer splitscene:
        subpixel True xalign 0.6 yalign 0.2 zoom 1.0
        0.5
        ease 28.1 zoom 1.1
    show background onlayer splitscene:
        subpixel True xalign 0.6 yalign 0.2 zoom 1.0
        0.5
        ease 28.1 zoom 1.2
    show mycharacter happy onlayer splitscene:
        subpixel True xalign 0.6 yalign 0.2 zoom 1.0
        0.5
        ease 28.1 zoom 1.4
```

When displaying the 'splitscene' layer (using a regular show of a displayable defined as Layer("splitscene")), it looks as if subpixel rendering is not applied. Rendering those above statements directly on the master layer (e.g. leaving the "onlayer splitscene" bits out of those statements, it's renders as smoothly as you'd expect with subpixel turned on.

I'm on 8.1.1, but downloaded and tried 8.2.3 to see if that fixed it and that has the same results.

When the above didn't pan out, I tried creating three separate detachable layer for the backdrop, background, and foreground, and instead of applying the transform to the images , I showed the appropriate image on each, and tried applying the transforms to the entire layer through the show layer statement:

```
    show layer splitscene_bd:
        subpixel True xalign 0.6 yalign 0.2 zoom 1.0
        0.5
        ease 28.1 zoom 1.1
    show layer splitscene_bg:
        subpixel True xalign 0.6 yalign 0.2 zoom 1.0
        0.5
        ease 28.1 zoom 1.2
    show layer splitscene_fg:
        subpixel True xalign 0.6 yalign 0.2 zoom 1.0
        0.5
        ease 28.1 zoom 1.4
```
But that yields the same result, so it seems to be something that applies to all rendering on a layer displayable?

Is this a limitation of layer displayables, or am I missing something else?

I can make a sample project available if that would help.

**Comment by lauwurence** [comment]
@renpytom, I believe there's another issue appeared after the fix. A lot of text displayables, especially on a 2K monitor, began to appear blurry even thought their and their parents' `subpixel` are not set to True.

<details>
  <summary>Screenshots</summary>

renpy 8.2.3
![renpy_8 2 3](https://github.com/user-attachments/assets/3c2beafd-08f1-463c-ae63-49aa7ad7e453)

renpy 8.3.0.24080101+nightly
![renpy_8 3 0](https://github.com/user-attachments/assets/68e060b1-57e5-4725-bd4d-92a3bd4403b1)
</details>

This behavior can be seen in default projects by switching into window mode and opening the console.
<details>
  <summary>Screenshots</summary>

renpy 8.2.3
![image](https://github.com/user-attachments/assets/5bc6feb7-d585-4948-89d7-ff2df8adc65a)

renpy 8.3.0.24080101+nightly
![image](https://github.com/user-attachments/assets/0b7ac7f5-6bd4-4036-b155-9dae188e340d)
</details>

What if we could control `subpixel_blit` per displayable and disable it for each one we want to be rendered as sharp as possible?
