### ISSUE TITLE
Infinite values in displayables

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#5663]
I don't know how to reproduce this issues in a fresh renpy project, but this exception started appearing in `renpy-8.3.0.24073102-nightly`.

```
Traceback (most recent call last):
  File "E:\Ren'Py\renpy-8.3.0.24073102+nightly-sdk\renpy\display\displayable.py", line 505, in place
    dest.blit(surf, pos, main, main, None)
OverflowError: cannot convert float infinity to integer
Exception ignored in: 'renpy.display.render.Render.blit'
```

It doesn't really crash a game, but floods the console with infinite error messages.
Probably related to this commit: https://github.com/renpy/renpy/commit/99a12807b2f6df4098dbf56a5555d0420e6d8863

**Comment by renpytom** [comment]
Can you post the entire traceback file, and not something minimal? The more information I have, the easier it will be to fix this.

**Comment by renpytom** [comment]
This should be fixed in the August 3 nightly.

**Comment by renpytom** [comment]
Closing this out - please let me know if you see it again.

**Comment by lauwurence** [comment]
Now it's good. Thank you!
