### ISSUE TITLE
Screenshot_crop is not working correctly

### ISSUE THREAD

**Issue by oldhiccup** [renpy/renpy#5664]
screenshot_crop is not working correctly when the game window is resized, resulting in the following error:

```
Traceback (most recent call last):
  File "renpy/common/00keymap.rpy", line 322, in _screenshot
    if not renpy.screenshot(fn):
  File "C:\projects\renpy\renpy\exports.py", line 2099, in screenshot
    return renpy.game.interface.save_screenshot(filename)
  File "C:\projects\renpy\renpy\display\core.py", line 1469, in save_screenshot
    window = window.subsurface(renpy.config.screenshot_crop)
  File "src/pygame_sdl2/surface.pyx", line 642, in pygame_sdl2.surface.Surface.subsurface
pygame_sdl2.error.error: subsurface rectangle outside surface area.
```
**Steps to reproduce the bug:**

1. Set a crop area, for example: 534, 18, 393, 862.
2. Resize the game window.
3. Attempt to take a screenshot.

**Expected result:**
The screenshot should be taken with the specified crop area.

**Actual result:**
The mentioned error occurs, indicating that the subsurface rectangle is outside the surface area.

Additional information:
    Operating system: Windows 10
    Ren'Py version: 8.2.3

**Comment by renpytom** [comment]
This has been fixed in the nightly for a while, but I just backported it to the nightly fix branch. That will become available in the 2024-08-03 nightly, in about 4 hours at https://nightly.renpy.org/

**Comment by oldhiccup** [comment]
I forgot to open the issue, great to know it's already been fixed. I'll test it in the nightly build. Thank you for your hard work.
