### ISSUE TITLE
"schinese" as language string makes language always selectable in UI even when translations are absent

### ISSUE THREAD

**Issue by tranefrancks** [renpy/renpy#5668]
Greetings, all.

In adding languages to my game, I've noted unexpected behaviour for using "schinese" as the identification string for Simplified Chinese: Even if the language translations have _not been generated_ , the following code results in the Simplified Chinese being selectable in Preferences. Other language strings, e.g., "dutch" and "german" do **not** exhibit this behaviour.

To reproduce, use current Ren'Py (8.2.3 at time of writing) and add the following code to screens.rpy:

```
                vbox:
                    style_prefix "radio"
                    label _("Language")

                    textbutton "English" text_font "gui/fonts/Ubuntu-Regular.ttf" action Language(None)
                    textbutton "Deutsch" text_font "gui/fonts/Ubuntu-Regular.ttf" action Language("german")
                    textbutton "Nederlands" text_font "gui/fonts/Ubuntu-Regular.ttf" action Language("dutch")
                    textbutton "简体中文" text_font "gui/fonts/NotoSansSC-Medium.ttf" action Language("schinese")
```
Then in another area/file, add this specific code. In my case, it resides in style.rpy:

```
translate schinese python:
    gui.text_font = "gui/fonts/NotoSansSC-Regular.ttf"
    gui.name_text_font = "gui/fonts/NotoSerifSC-SemiBold.otf"
    gui.interface_text_font = "gui/fonts/NotoSansSC-Medium.ttf"
    gui.choice_button_text_font = "gui/fonts/NotoSansSC-Medium.ttf"
    gui.button_text_font = "gui/fonts/NotoSansSC-Medium.ttf"
    

translate schinese style default:
    font "gui/fonts/NotoSansSC-Medium.ttf"
```

Immediately upon the presence of these translate sections, Simplified Chinese is now selectable in the Preferences language screen even when the '/game/tl/schinese' language folder/files are missing.

It appears that Ren'Py is somehow treating 'schinese' as a special string … almost like a reserved word. There is no mention in the Ren'Py docs about _schinese_ having special processing related to other strings. I consider it a bug. 

Use case clarification: I  would expect translation languages missing from '/game/tl' to be displayed yet unable to be selected.

If you need further information, please let me know.

<img width="231" alt="Screen Shot 2024-08-04 at 12 22 14" src="https://github.com/user-attachments/assets/db5bedd1-5cd6-48a4-afc3-7784c78c376f">

**Comment by renpytom** [comment]
>  I would expect translation languages missing from '/game/tl' to be displayed yet unable to be selected.

Your understanding is incorrect. The presence or absences of the translation files doesn't really matter, it's the presence or absence of the translations that does. In this case, there are multiple lines of translate schinese, and that's enough to tell Ren'Py the translation exists. 

You probably do not use translate python or translate style for the other languages, and so those languages do not have any translations.

**Comment by tranefrancks** [comment]
Understood. I have found that I can work around the issue simply by commenting out the lines in style.rpy. Thanks for the feedback and a great engine.

**Comment by renpytom** [comment]
You can also just move them into tl/schinese/style.rpy, so the lines only exist when the language does.
