### ISSUE TITLE
Nested dynamic imagemaps weird behaviour

### ISSUE THREAD

**Issue by caryoscelus** [renpy/renpy#567]
Dynamic nested imagemap uses parent imagemap images for hotspots, at least when first appearing.

Test case: http://my-files.ru/DownloadSave/e1ffka/imagemaps-nested-test.zip

Reproduction:

1. Launch game, click on "back" button, broken nested imagemap is displayed.
2. Click again, imagemap gets "repaired"

![imagemap-2](https://cloud.githubusercontent.com/assets/1758893/6505752/5e68aa02-c356-11e4-8027-ddbada59625d.png)

**Comment by renpytom** [comment]
For my reference, this is the test case I used to demonstrate this problem:

```
screen imap:
    imagemap:
        ground Solid(a, xysize=(800, 600))
        hover Solid("#fff", xysize=(800, 600))

        hotspot (0, 0, 100, 100) action SetVariable("a", "#400")
        hotspot (100, 0, 100, 100) action SetVariable("a", "#040")
        hotspot (200, 0, 100, 100) action SetVariable("a", "#004")
```

**Comment by renpytom** [comment]
Thanks for the report. When this lands in a nightly or prerelease, you'll need to click "Force Recompile" in the launcher to get Ren'Py to re-analyze your code properly.
