### ISSUE TITLE
CDD `event()` acts strangely with `perspective True`

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5672]
The `x` and `y` mouse position variables supplied to the `event()` method take on some very strange and confusing values when camera perspective is enabled. I hesitate to say they're "incorrect", but I have no idea what to do with them to bring them back into proportion with the game window/displayable and make them usable. Is this intentional?

**Comment by renpytom** [comment]
At least for now, yes. Perspective doesn't work with interface elements. 

(There's an issue here that when perspective is True, pixels on the screen may correspond to multiple (x, y, z) locations. I need to figure out the way to resolve this, but I haven't yet.)

**Comment by paranormalized-encryptid** [comment]
It actually isn't an interface element; I'm trying to shade a character displayable with a mouse light (not in a `screen`). Is the problem still the same? Sorry, just trying to work out what you mean wrt pixel position ambiguity.

**Comment by renpytom** [comment]
Sorry for the late reply. 

Basically: In 2d mode, each screen pixel corresponds to a single x, y coordinate. But there are multiple (x, y, z) coordinates corresponding to each screen pixel.

**Comment by paranormalized-encryptid** [comment]
Understood. Is it not possible to just collapse the image bounds' perspective for an apples-to-apples comparison to the 2D mouse position? That's what I would have expected, anyway.

**Comment by renpytom** [comment]
It's not straightforward, anyway.
