### ISSUE TITLE
Why I have to use new VSCode Extension for nightly version?

### ISSUE THREAD

**Issue by Koji-Huang** [renpy/renpy#5673]
A hour ago, I found RenPy'Language extension is been ban in VScode. It told me I it had been abandoned and I have to download another extension. Them... I found the extension is for RenPy 8.3+, but my Renpy version is 8.2. If I wanna use 'Ren'Py Launch and Sync' extension, I have to use the newest extension.
I don't think this is reasonable. Why not use different extension of each version? One for normal version another for nightly version?

**Comment by renpytom** [comment]
So, the development of the Ren'Py Language extension has moved into the Ren'Py project. For the time being, its' called 8.3+, but it will work with older versions too. It's the same extension (with new thing for 8.3+ added), so you can use it with 8.2.

**Comment by Koji-Huang** [comment]
Wait...There seem something wrong with me...The 'Ren'Py Launch and Sync' extension is bind with old extension, that's my fault. But I still think two kind of extension is better, just consider it as a suggest. I'm sorry to create a issue for it.

**Comment by Koji-Huang** [comment]
> So, the development of the Ren'Py Language extension has moved into the Ren'Py project. For the time being, its' called 8.3+, but it will work with older versions too. It's the same extension (with new thing for 8.3+ added), so you can use it with 8.2.

OK, thank u very much😊

**Comment by Koji-Huang** [comment]
There is still a problem that the 'Ren'Py Launch and Sync' extension is bind with old extension. That's a easy work I think.
By the way, I'm just afraid the new version will change some interface's build ( some engine's update will change a lot, my project team was once ruined by this kind of thing ), and the new version of extension will lead me to a wrong path... It won't happen, will it?

**Comment by Gouvernathor** [comment]
The VSCode extension will not change anything about how your game runs, it's only about how the text editor understands the code you write.

**Comment by Koji-Huang** [comment]
> The VSCode extension will not change anything about how your game runs, it's only about how the text editor understands the code you write.

But if I trust the code completion or prompt them write the wrong thing into my project. That will cause error ( actually, that's how I did ). Anyway, thank you for your concern (*^▽^*)

**Comment by Koji-Huang** [comment]
> You need to contact the author of Ren'Py Launch and Sync about problems in their extension.

Oh, I think that extension is made by Renpy. I'm sorry about trouble you. Thank u for your patience😊
