### ISSUE TITLE
Confirm() Yes action still insensitive despite "sensitive True"

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5675]
If you want to Add a lot of values to a set, but the set is already filled with some of them, the button will become insensitive. If you add `sensitive True` then you can click it. `AddToSet()` will fill it completely even if it’s partially filled, which is it's intended function. However, if you use `Confirm()` then the "Yes" button is insensitive regardless `sensitive True`.

‌
TLDR: When the set is partially filled. the code below doesn’t work:

```renpy
default persistent.endings = set()

    $ all_endings = ["end1", "end2", "end3", "end4"]
    textbutton "Unlock All Routes":
        action Confirm(
            "This will unlock all routes.\n¿Are You Sure?",
            [AddToSet(persistent.endings, end) for end in all_endings],
        )
        sensitive True
```

But this does:

```renpy
textbutton "Unlock All Routes":
    action [AddToSet(persistent.endings, end) for end in all_endings]
    sensitive True
```

**Comment by renpytom** [comment]
You're setting sensitive for the textbutton, not the Confirm Yes button. You can use the SensitiveIf action to do the latter: 

```renpy
    textbutton "Unlock All Routes":
        action Confirm(
            "This will unlock all routes.\n¿Are You Sure?",
            [AddToSet(persistent.endings, end) for end in all_endings] + [ SensitiveIf(NullAction()) ],
        )
```
