### ISSUE TITLE
Relative Python module import errors with Python 3.12

### ISSUE THREAD

**Issue by onitake** [renpy/renpy#5682]
The Debian package of Ren'Py executes in the system's default Python interpreter, which is Python 3.12 in Debian trixie and sid at this time.

With Python 3.12, Ren'Py fails to start due to ModuleImportErrors caused by relative imports in .rpy code:
```
    File "launcher/game/gui7.rpy", line 31, in <module>
      import gui7
 ModuleNotFoundError: No module named 'gui7'
```

When logging `sys.path` just before the import statement, it is as follows: 
```python
sys.path=['/usr/share/games/renpy', '/usr/share/games/renpy', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/usr/local/lib/python3.12/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.12/dist-packages', '/usr/share/games/renpy']
```

The Python code is definitely installed, and the issue can be fixed by changing all submodule-relative imports to installation-relative ones.

For example:
```python
    #import gui7
    from launcher.game import gui7
    #from gui7 import translate_define, translate_copy, translate_code
    from launcher.game.gui7 import translate_define, translate_copy, translate_code
```

Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1077202

**Comment by lordmatt** [comment]
I'm also seeing this error
