### ISSUE TITLE
Regression in screen layouts in 8.3-pre

### ISSUE THREAD

**Issue by mal** [renpy/renpy#5684]
A `Window` with a `margin` is now being forced to exceed screen bounds by one or more of its children, where previously the children would not be offered the margin space. Will try and come up with a minimal reproduction example when I can find the time.

**Comment by renpytom** [comment]
Could this be https://www.renpy.org/dev-doc/html/incompatible.html#incompatible-7-7-2 ?

**Comment by mal** [comment]
I don't believe so, as I'm seeing the difference between 8.2.3 and 8.3.0-pre. To be sure I tried setting `config.fill_shrinks_frame = True` as documented but had no effect on this issue.

**Comment by mal** [comment]
Appears to be some kind of potentially bad interaction between the margin on the window, the vbox spacing. Seems probable that the spacing isn't being correctly factored into the calculation of what area to offer to the viewport. Only thing that springs to mind with respect to change in that area is the box justification work that went in recently.

```rpy
label main_menu:
    $ _confirm_quit = False
    return

label start:
    call screen test()
    return

screen test():
    window:
        margin (50, 50)

        has vbox
        spacing 50

        add Solid('7ff7', ysize=30)

        viewport:
            text 'hello world ' * 400 substitute False
```

**8.2.3**
![8 2 3](https://github.com/user-attachments/assets/b734b91a-527e-4d67-b7fb-02d63da91777)

**8.3.0-pre**
![8 3 0](https://github.com/user-attachments/assets/f6220a6a-6c6a-49a3-ae45-da2394d2b5ec)
