### ISSUE TITLE
dissolve textshader issue

### ISSUE THREAD

**Issue by Jaybe-Games** [renpy/renpy#5685]
If dissolve is active and an extend follows, then the previous text disappears and reappears and then the text continues

see attachment

https://github.com/user-attachments/assets/52201202-f488-4d58-bbe0-2dd1785be9b6

**Comment by dev-inspired-dev** [comment]
```rpy
mc "{shader=zoom:5.0:1.0|typewriter}THIS. {w}IS. {w}COOL!"
```
Seems like this also affects the zoom shader as well (see attachment).

[attachment.webm](https://github.com/user-attachments/assets/62502888-dade-40a5-9d58-9f3bdda746a4)

**Comment by Gouvernathor** [comment]
The issue is (likely) that the text before the {fast} text tag, and used by extend, applies the shader to all its letters at the same time, rather than not applying it to them. Regardless of the shader.

**Comment by renpytom** [comment]
Yeah, that's it. I need to think about what the right way to fix this is.
