### ISSUE TITLE
Transforms using `Model()` throw undefined `texture_wrap` error

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5691]
Setting `Model().child(...)` or `Model().texture(...)` in a transform now results in the error message:
`NameError: name 'texture_wrap' is not defined`
This error occurs in the 8.3.0 prerelease. It is absent in 8.1.3.

**Comment by danac78** [comment]
Isn't this fixed by #5688 ?

**Comment by paranormalized-encryptid** [comment]
Oh. Didn't see that, but I literally just downloaded the latest prelease. Is it in the nightly?

**Comment by danac78** [comment]
Yes.

**Comment by paranormalized-encryptid** [comment]
Oh yes, it's fixed. Sorry, didn't know the problem had been picked up!
