### ISSUE TITLE
Shaders fail in CDDs without `mesh=True`

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5692]
I have a basic shader that takes no uniforms or properties and just sets `gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0)`, but adding it to a `renpy.Render(...)` results in nothing being rendered. I wondered if this was because it couldn't take its size from anything, but blitting a texture that _should be_ ignored results in that texture being used instead, meaning that the fragment shader code just gets ignored entirely if `mesh` isn't `True`. Am I missing something?

**Comment by renpytom** [comment]
You almost  certainly want to use Model for this. A render doesn't include any geometry as part of itself, while a Model will create a mesh.

**Comment by paranormalized-encryptid** [comment]
I'm just really confused about how to implement the new functionality mentioned in https://github.com/renpy/renpy/issues/5602? I can't use a Model() there because the mesh destroys camera perspective.

**Comment by renpytom** [comment]
I don't know what you're trying to do.

**Comment by paranormalized-encryptid** [comment]
I thought the new functionality would allow us to supply texture uniforms directly to `Render()` and do stuff with them without having to blit them with `mesh=True`, which destroys the z-positioning of 3D-transformed textures. I don't want the z-positioning to be discarded, I want it to be kept.

**Comment by renpytom** [comment]
And it can do that, but you need something inside the Render to actually provide geometry. As far as I can tell, you don't have any geometry.

**Comment by paranormalized-encryptid** [comment]
I thought there would be a new mechanism to let us do that. How do I manually provide the geometry?

**Comment by renpytom** [comment]
That's what model is for. It shouldn't destroy any perspectives.

**Comment by paranormalized-encryptid** [comment]
It does though, that's the problem.

```python

init python:

    renpy.register_shader("test.myshader", variables="""

        uniform sampler2D tex0;
        attribute vec2 a_tex_coord;
        varying vec2 v_tex_coord;

    """, vertex_200="""

        v_tex_coord = a_tex_coord;

    """, fragment_200="""

        gl_FragColor = texture2D(tex0, v_tex_coord);

    """)

    class ModelTest(renpy.Displayable):

        def __init__(self, child):

            self.child = renpy.easy.displayable(child)
            super().__init__()

        def render(self, width, height, st, at):

            model = Model().child(self.child)

            mr = renpy.render(model, width, height, st, at)

            rv = renpy.Render(width, height)
            rv.add_shader("test.myshader")
            rv.blit(mr, (0, 0))

            renpy.redraw(self, 0)

            return rv

image my_displayable = Transform("eileen", xrotate=30)

image test1 = Model().child("my_displayable").shader("test.myshader")

image test2 = ModelTest("my_displayable")

label model_test:

    camera:
        perspective True

    show test1

    "This doesn't work."

    hide test1
    show test2

    "Nor does this."
```

**Comment by renpytom** [comment]
A couple things here, and sorry about the delay - brain fog is a terrible thing. 

The first was that Model wasn't creating meshes propertly, that's fixed. 

The second thing is that

```renpy
image my_displayable = Transform("eileen", xrotate=30)`
image test1 = Model().child("my_displayable").shader("test.myshader")
```

Isn't  expected to work. That's because the xrotate happens before the texture is made, and so it won't propagate past the model. By contrast: 

```renpy
image test2 = Transform(Model().child("my_displayable").shader("test.myshader"), xrotate=30)
```

Should work fine. You can also create a render, and do:

```renpy
        def render(self, width, height, st, at):

            cr = renpy.render(self.child, width, height, st, at)

            rv = renpy.Render(width, height)
            rv.add_shader("test.myshader")
            rv.add_uniform("mask", self.mask)

            return rv
```

To add a texture to things. What you can't do is to not have any geometry whatsoever - if you want something that has just a shader, you can do:


```renpy
image shaderbased = Model(size=(500, 200)).add_shader("text.solidshader")
```
