### ISSUE TITLE
Live2D crash on load in 8.2.2+

### ISSUE THREAD

**Issue by Eliont** [renpy/renpy#5698]
Hello and good time of day. 8.2.1 works all right, but can't update to later version.

`Exception: Refusing to open _live2d_/day_map/day_map.model3.json while predicting.`

**Comment by renpytom** [comment]
Can you post what's causing this, and perhaps a small example? This isn't close to enough to figure out what's going wrong.

**Comment by renpytom** [comment]
Just looking, this error only happens on the web, and Live2D was never supported on the web - so I don't know what's going on.

**Comment by qTich** [comment]
> Just looking, this error only happens on the web, and Live2D was never supported on the web - so I don't know what's going on.

Isn't there a typo in the condition [there](https://github.com/renpy/renpy/blob/master/renpy/loader.py#L655-L660)? 

```py
if not (renpy.emscripten or os.environ.get('RENPY_SIMULATE_DOWNLOAD', False)):
```
to
```py
if renpy.emscripten or os.environ.get('RENPY_SIMULATE_DOWNLOAD', False):
```

**Comment by qTich** [comment]
Oh, I think I found the cause.

```renpy
label splashscreen():
    $ renpy.start_predict("...")
    return
```

**Comment by Eliont** [comment]
> what's going wrong
> found the cause

Yes, removing prediction from splashscree solve issue, but can build test project if you need to track issue on live example.
