### ISSUE TITLE
Including videos in game.zip for web

### ISSUE THREAD

**Issue by leonholly** [renpy/renpy#5703]
Is there a way to include videos in web archive? progressive_download.txt seem to ignore them, when referring to them as images.
I use these videos in a pretty complex screens, so prediction isn't really a thing here.

Size shouldn't be a problem for me, since game.zip with these videos is already under 200mb, like itch.io requires.

**Comment by leonholly** [comment]
Also would be nice to know if hamburger menu is hideable or not.

**Comment by Kassy2048** [comment]
Videos are rendered by the Web browser directly, so it can only access them using the HTTP protocol currently (the same way it does for Web pages). We could probably give a blob URL to the browser that would map to the emscripten file system to access the files in "game.zip" though, but this is probably better to let the Web browser knows it needs to prefetch these videos and put them in the cache instead. You can do that manually by editing the "index.html" that has been generated by Ren'Py and add [link elements with rel=prefetch](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/prefetch) in the HEAD part (one for each file to preload).

There is no way to remove the hamburger menu using a Ren'Py setting, but you can hide it using CSS by manually editing the "index.html" file as well (using a rule like `#ContextContainer { display: none }`).

The main drawback with editing the "index.html" file is that your changes are erased when you build the project for Web again (but the generated "index.html" file barely changes between builds, so you can generally re-use the one with your changes directly).
