### ISSUE TITLE
Using two different transitions with two different images at the same time

### ISSUE THREAD

**Issue by Charmareian** [renpy/renpy#5705]
Unless I'm missing something, there's no way to do two different transitions with two different images at the same time?

If I do:
define wipeleft_slow = ImageDissolve("wipeleft.png", 2.0, ramplen=128)
define wiperight_slow = ImageDissolve("wiperight.png", 2.0, ramplen=128)

show letterbox1 with wiperight_slow:
        ypos 0
show letterbox2 with wipeleft_slow: # letterbox2 will not appear until letterbox1 is done with its two second transition 
        ypos 1800   

You can do something like:
show letterbox1:
        ypos 0
show letterbox2: 
        ypos 1800   
with wiperight_slow

The letterboxes appear at the same time, however, you are restricted to one transition, not two.

**Comment by Gouvernathor** [comment]
That's right, the move transitions are limited this way, though you can set a different direction and interpolation for a) introduced images, b) moved images and c) outgoing images.
The solution is to use ATL to animate the separate images and use a pause for instance to wait for the move to finish.

**Comment by Charmareian** [comment]
Not home at the moment, but are you saying I can do something like this to use two wipe transitions at the same time?:

image letterboxAnimated:
    letterbox1 with wiperight_slow
    letterbox2 with wipeleft_slow
    pause 2

If so, that would be pretty powerful.

**Comment by Gouvernathor** [comment]
You can do something similar, but that would mean defining a single-use image just for that one transition and that's not very useful.

What you can do is this :
```rpy
show letterbox1:
    Null()
    "letterbox1" with wiperight_slow
show letterbox2:
    Null()
    "letterbox2" with wipeleft_slow
pause 2
```
and to make them go away :
```rpy
show letterbox1:
    Null() with wiperight_slow
show letterbox2:
    Null() with wipeleft_slow
pause 2
hide letterbox1
hide letterbox2
```

**Comment by Charmareian** [comment]
I'm curious about the usage of "Null()". Don't think I've seen something like that for Renpy before.

**Comment by Gouvernathor** [comment]
It's just a [documented](https://www.renpy.org/dev-doc/html/displayables.html#Null) transparent displayable.
The ATL statements that I used are the [displayable expression](https://www.renpy.org/dev-doc/html/transforms.html#displayable-statement) statement and the [inline contains](https://www.renpy.org/dev-doc/html/transforms.html#inline-contains-statement) statement.

**Comment by Charmareian** [comment]
I tried:
show letterbox1:
    contains Null()
    "letterbox1" with wiperight_slow
show letterbox2:
    contains Null()
    "letterbox2" with wipeleft_slow
pause 2

Result: Only letterbox1 appears with no transition after the 2 second pause

I also tried:
show letterbox1:
    Null() with wiperight_slow
show letterbox2:
    Null() with wipeleft_slow
pause 2

Result: Nothing appeared on screen at all

**Comment by Charmareian** [comment]
https://github.com/user-attachments/assets/dbc888fe-d7fb-4e42-ad01-d8c3ed86fa4c

This is what I'm trying to replicate.

**Comment by Gouvernathor** [comment]
> Result: Only letterbox1 appears with no transition after the 2 second pause

That's not what happens on my end using the built-in wipeleft and wiperight transitions with a 1-second pause. It just works.
In any case, there doesn't seem to be a bug here or something requiring a new feature.

**Comment by Charmareian** [comment]
![Screenshot_10](https://github.com/user-attachments/assets/e1ebdc3c-d07e-4cc5-9df5-932ee4b244e7)

Interesting, it does work with the default wipe, but that's not what I'm looking for. Redefining the wipes with a custom image seems to break it. Do you know of a way to get it working?

**Comment by Gouvernathor** [comment]
Using what the documentation says is the type of the wipe transforms, [CropMove](https://www.renpy.org/doc/html/transitions.html#CropMove), should help you.

**Comment by Charmareian** [comment]
CropMove doesn't appear to allow a custom image

![wipeleft](https://github.com/user-attachments/assets/bfb66750-8bdf-4e1f-96c4-c150caef0a5e)

I'm trying to have the letterbox appear smoothly with the image above. That's why I'm trying to use ImageDissolve, but no transition appears at all.

**Comment by levicratic** [comment]
@Charmareian What happens if you use one ImageDissolve with an image like this, instead of two ImageDissolves?
![dissolve_image](https://github.com/user-attachments/assets/da432cce-02f2-4201-bf5d-5d6b83f519fb)

**Comment by Charmareian** [comment]
That is a hilariously creative solution, nice. Works well, thanks for your help.
