### ISSUE TITLE
Replace obsolete renpy.file() function in mobilebuild.rpy

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5706]
In `mobilebuild.rpy line 35` the obsolete `renpy.file()` function is still used. It should be replaced by `renpy.open_file()`

https://github.com/renpy/renpy/blob/ea3c2f32ff5b08808e698872e96881fc918e2ad0/launcher/game/mobilebuild.rpy#L35

**Comment by renpytom** [comment]
This was fixed a little while ago.
