### ISSUE TITLE
RenPy can not load png with non-zero eXIf block that came before data.

### ISSUE THREAD

**Issue by Andykl** [renpy/renpy#5707]
This project contain the same file with zeroed and non-zeroed eXIf data before and after IDAT blocks to test it. Problem file is `icon_exif_before_nonzero.png`.
[bad_png.zip](https://github.com/user-attachments/files/16631677/bad_png.zip)

**Comment by renpytom** [comment]
This was fixed by renpy/renpy-build@5b2e200
