### ISSUE TITLE
Using more system resources in 6.99

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#571]
Another thing I noticed is that now the game seems to use much more system resources. I notice it immediately for example when I alt-tab and browse with Firefox. Clicking on each tab has 1 second delay, like if something else was using a lot of system resources, slowing down everything. As soon as I shut down the game, things are back normal.
I think happens mostly if there's a screen shown (screen language). If it's just normal dialogue the system load is more or less the same as before.

**Comment by renpytom** [comment]
Based on http://lemmasoft.renai.us/forums/viewtopic.php?p=362653#p362653, I believe this has been fixed.
