### ISSUE TITLE
Svg is not rendered correctly

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5717]
Testing this svg file yields different results when rendered by Ren'Py. See the differences (see the top of the letters, it lacks the shading):

Original (screenshoted when opened by microsoft edge browser, and also with this [converter website](https://svgtopng.com)):
![2024-08-18 01_14_57-iwh_logo svg and 3 more pages - Profile 1 - Microsoft​ Edge](https://github.com/user-attachments/assets/039d28bc-1aca-4928-a5b3-f25932b378f4)

By Renpy 8.2.3:
![2024-08-18 01_14_40-Indecent Wife Hana Ver 0 42 0 - autoreload](https://github.com/user-attachments/assets/fbba425a-e222-41b8-823a-084d316b6e24)

This is the files in Mega link [here](https://mega.nz/file/EAAFDLTa#ubgHHl_t0OheXFLv-F_YyAZxx3x07XVxImZDPC1AW4I) and [here](https://mega.nz/file/hQhXjIgK#H1JbqFsV3HJf-7_e5hwZ1Z4A1jW8EvjN8TkjaRuIjYM). If you use github to render it's displayed correctly too.

**Comment by renpytom** [comment]
Ren'Py renders SVG how Ren'Py renders SVG. The limitations should be in the documentation, and are unlikely to change.
