### ISSUE TITLE
New a_text_pos_rect attribute changes behaviour for final line of text

### ISSUE THREAD

**Issue by mal** [renpy/renpy#5718]
Not sure if it's bug, or just a quirk, but `a_text_pos_rect.w` appears to be significantly larger for the final line, compared to others. This makes it unsuitable for calculating per-line gradients in the y-axis.

```
        vertex_300 = """
        v__test = smoothstep(a_text_pos_rect.y, a_text_pos_rect.y + a_text_pos_rect.w, a_position.y);
        """,

        fragment_300="""
        gl_FragColor += vec4(1., 0., 0., 1.) * v__test;
        """,
```

![screenshot0013](https://github.com/user-attachments/assets/1aed81f8-4767-4cbf-b2cd-0e8a05258183)

**Comment by renpytom** [comment]
a_text_pos_rect isn't really meant for this - it's the total side of the blit, meant for morphing geometry - it's not meant for texturing like this. 

I just added a_text_ascent, which should be usable with a_text_center to get this sort of effect.

**Comment by renpytom** [comment]
I've made a second change to cover the glyphs more directly, so your code should work. (It may not work in all circumstances perfectly, but should work where it's possible to get this right.)
