### ISSUE TITLE
`Warning: write error: FS error` happening on autosave in browser builds on Ren'Py 8.3.0

### ISSUE THREAD

**Issue by EtchJetty** [renpy/renpy#5725]
Upon hitting a choice, quitting to main menu, or prompting an autosave in any other way, games built in Ren'Py 8.3.0 targeting the web will provide a generic "FS error". 
<img width="1608" alt="Screenshot 2024-08-23 at 3 05 06 AM (1)" src="https://github.com/user-attachments/assets/80271d38-b687-4c8b-a7a2-411e66a73bfc">

Attached is the [log.txt](https://github.com/user-attachments/files/16724985/log.5.txt) from this game. 

The example I used for this screenshot is unchanged from generated default, minus the inclusion of a background and Eileen. The `script.rpy` for the example is below:

```renpy
define e = Character("Eileen")

label start:
    scene bg room
    show eileen happy

    e "You've created a new Ren'Py game."
    e "Once you add a story, pictures, and music, you can release it to the world!"
    e "Got that?"

    menu: 
        e "Got that?{fast}{done}"

        "Yep! I got it!":
            e "Great to hear!"
        "No... could you explain from the start?":
            e "Alrighty then..."
            jump start 
    # This ends the game.

    return
```

A live example of a game with this issue is my current project, [Pesterquest Rewritten](https://pesterquest.com/).

**Comment by Kassy2048** [comment]
This happens during syncfs while it tries to sync "/home/web_user/.renpy/PesterquestRewritten/_auto-LT1.save". Maybe this if a temporary file that exists when syncfs starts but gets deleted before that function tries to synchronize it? If so, this is probably linked to [this commit](https://github.com/renpy/renpy/commit/720a57bad0b59ab650253f9de20a61c268a3767f).
