### ISSUE TITLE
button activate_sound delayed by music change

### ISSUE THREAD

**Issue by nomnomnami** [renpy/renpy#5730]
i think this has something to do with synchro_start being True by default? i have a sound that plays when you click a choice button, but some scenes in my game have the music fade to a new track directly after the choice. in all the instances where there's a fadeout on the previous track, the button sound doesn't play until the new track begins. when there's no track change, the button sound plays when clicked, as normal.

is there a config option to change sync's default back to False, or to at least disable sync on the sound channel? the delay keeps making me think my game is lagging, haha.

**Comment by renpytom** [comment]
Can you give me a demo? I can look into changing this behavior (like turning it off when renpy.play is used).

**Comment by nomnomnami** [comment]
sure, i threw together a test project here: https://drive.google.com/file/d/1Aj8mYIQyFhpIlW5WVT4ddw7Wqr5kRVLa/view?usp=sharing
