### ISSUE TITLE
Performing a fast skip while slow skipping stops skipping altogether

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5731]
1. Press `Skip` button on the quick menu.
2. While Ren'Py is skipping right-click the `Skip` button.
3. Fast skipping confirm prompt appears. Click "Yes"

**Expected result:** fast skipping
**Actual result:** stop skipping

The prompt gives the impression you are about to fast skip but instead it stops skipping so it may appear as a bug.

I think ideally fast skipping while slow skipping should set the skipping variable to `"fast"` instead of `None`

**Comment by renpytom** [comment]
I don't think this is correct. When skipping, clicking the skip button should end a skip.

**Comment by renpytom** [comment]
Ah, that's the actual issue. Let me make that change.

**Comment by the66F95** [comment]
personally i use
```py
if self.fast and config.skipping in ["slow", None]:
    config.skipping = "fast"
elif not config.skipping:
    config.skipping = "slow"
else:
    config.skipping = None
```
in the relevant spot in `00action_menu.rpy` but that's just me.
