### ISSUE TITLE
Blackscreen when tabbing out on android version 8.2.3.24061702

### ISSUE THREAD

**Issue by darkomen202** [renpy/renpy#5739]
Hi. Playing Innocent Witches 0.10.8B, the game goes black screen on my Galaxy S10+ when I switch tabs

**Comment by benq66** [comment]
I guess for better understanding and as a starting point it would greatly help to provide a snippet from a log captured with logcat during the moment when the issue happens. There are many guides on google that describe how to do that, for example by searching for "How to use LogCat to capture debug logs from an Android device" :)

**Comment by Andykl** [comment]
Probably related to https://github.com/renpy/renpy/issues/5292#issuecomment-2119052879.

I don't think any of our code is related to this problem. 
The build is made on unmodified 8.2.3 release SDK and RAPT.

@darkomen202 Does this problem happen every time or only occasionally?

**Comment by renpytom** [comment]
Closing this, as it doesn't pertain to an up-to-date Ren'Py.
