### ISSUE TITLE
Crop() inside a viewport extends backwards outside its x/y start

### ISSUE THREAD

**Issue by Tayruu** [renpy/renpy#5752]
Regression in 8.3.1 that wasn't present in 8.3.0 - my uses of Crop to slice from a UI spriteset appears to have fallen to pieces in certain places - the crops are extending beyond their x/y starting positions, though relative position is maintained.

**8.3.0 vs 8.3.1 Prerelease. (Also tried Nightly Fix.)**
![screen1](https://github.com/user-attachments/assets/d51ab808-f7ff-4827-9da8-099dcd9665db)

Just to confirm, this appears to be affect viewports, as I added an element to a viewport and then tried without the viewport. 
Left is no viewport and expected behaviour, right is with viewport.
![screen2](https://github.com/user-attachments/assets/1d661017-f8c2-462c-b3b2-644919fb5a04)
The code here was `add Crop((264, 96, 66, 18), "system/common.png") xalign 1.0`.

**Comment by renpytom** [comment]
Can you please put together an example? It's hard to test this just from pictures.
