### ISSUE TITLE
[Feature Request]: Add option to limit maximum rendering resolution for performance

### ISSUE THREAD

**Issue by hoshito-yurei** [renpy/renpy#5754]
![a0](https://github.com/user-attachments/assets/f9d9484a-a03f-443e-a8fc-87562611a335)

Ren'py's system resolution and actual rendering resolution are distinct. For instance, when expanding the game window to 3840x2160, it doesn't simply upscale the 1920x1080 system resolution. Instead, the rendering resolution increases to match the physical resolution (window size) of 3840x2160, and then renders the 1920x1080 system resolution virtually within that 3840x2160 rendering space.

This approach offers several advantages. For example, the resolution of assets like images isn't constrained by the system resolution. A 3840x2160 background in a game with a 1920x1080 system resolution, when played fullscreen on a 3840x2160 monitor, will render at its full 3840x2160 resolution rather than being downscaled.

However, since the introduction of Model-Based Rendering, I believe users or developers should have the ability to limit and adjust the maximum rendering resolution, rather than having it always forced to match the physical resolution.

Previously, when Ren'py was primarily used for displaying text, images, and occasional videos, the old method didn't cause significant performance issues or GPU usage. It even had advantages like crisp text rendering. But with Model-Based Rendering, the landscape has changed. Developers can now apply GLSL shaders to games, creating impressive visual effects.

The challenge is that these shaders are computationally intensive, and the load increases with higher rendering resolutions. This results in unnecessary graphical strain on high-resolution displays.

One might question the necessity of this feature. Most people still use 96 PPI FHD monitors that have been standard for decades, and we might assume that users with 4K monitors likely have powerful GPUs. However, we can't always assume 4K monitor owners have high-end GPUs. For instance, someone might connect a mini PC with an Intel N100 to a 4K monitor for its AV1 decoding capabilities.

Moreover, the trend is shifting, especially in the mobile device market. Many high-end Windows laptops now come with QHD resolution, and some even feature 4K displays. Examples include the ASUS Vivobook series, Lenovo Yoga Slim7, DELL Inspiron 14, Samsung Galaxy Book4 Pro, Microsoft Surface Pro or Surface Laptop, and flagship products like DELL XPS. These typically have 14-16 inch screens, so native high-resolution rendering isn't always necessary or beneficial.

We also have devices like MacBooks and iMacs that have long featured high-resolution displays. However, these products often have less powerful GPUs as they're not primarily designed for gaming.

For these devices, rendering at high resolutions can be extremely taxing on system resources. In some cases, you might even need to render a 1920x1080 game at 1280x720 to maintain acceptable performance. (This isn't a major issue given the small screen sizes of 14-16 inches.)

https://github.com/user-attachments/assets/0fdddf28-d9ee-4881-bd83-d6c62f28b5b0

The video above demonstrates the performance difference of the same shader-enhanced game running at two different resolutions on my iMac. The left side intentionally lowers the resolution to 1920x1080 through Windows settings, while the right side uses the native resolution. Both are in fullscreen mode, so the left side has a physical and rendering resolution of 1920x1080, while the right side is at the iMac's native 5120x2880.

As evident, there's no perceptible delay on the 1920x1080 side, but significant lag on the 5120x2880 side. (Similar issues occur even at intermediate resolutions like 2560x1440, which is still relatively high resolution.)

Currently, there's no standardized way to address this issue within Ren'py. Users need to manually change their display resolution in the operating system before launching the game and revert it afterward, or simply avoid using shaders altogether.

If there was an in-game option to set or limit the actual rendering resolution, users wouldn't need to modify their system settings.

![a11](https://github.com/user-attachments/assets/295e137f-439c-4dc1-a990-dc47b27bc9f2)
![a2](https://github.com/user-attachments/assets/f660d925-bcc3-40cc-aa2e-1678af6e1312)

Many games have long included options to limit rendering resolution. Ren'py lacked this option and forced rendering resolution to match physical resolution, but this wasn't a significant issue before as Ren'py games typically didn't utilize intensive graphical effects.

However, with the introduction of Model-Based Rendering and shader usage, Ren'py games can now be as graphically demanding as other game genres, necessitating this feature.

![a3](https://github.com/user-attachments/assets/338341f5-d0fa-44ca-99b1-083d095728a5)
![a44](https://github.com/user-attachments/assets/92796903-3717-4555-a630-07184b811d3d)

In fact, many other visual novels now include options to limit rendering resolution, demonstrating the need for this feature in the visual novel space as well.

I propose adding variables like `config.max_rendering_width` and `config.max_rendering_height`. These should be adjustable in-game, similar to other games.

(Of course, this might lead to unavoidable issues like reduced text readability. Perhaps there's a way to limit rendering resolution for everything except text, or to limit resolution for certain layers like the master layer (background and characters) while maintaining full resolution for upper layers like the screen layer. I'm not certain if this is feasible within Ren'py's GLSL shader system, though.)

As a developer who actively utilizes Model-Based Rendering and shaders, I would greatly appreciate your consideration of this suggestion. It would significantly improve the performance and accessibility of Ren'py games on a wide range of hardware configurations.

**Comment by Noriverwater** [comment]
Ren'py's current rendering method has sufficient advantages over other engines, at least it used to. However, as you mentioned, in this case it significantly affects performance, so I think it's reasonable to introduce this feature. A better approach would be to render at a smaller fixed resolution and then apply technologies like FidelityFX FSR for upscaling (which people have discussed in #2909).

**Comment by colinharvie** [comment]
You can "sort of" do this a little bit with a set of layer transforms on the master,  that scale down the screen to the ratio you want, set Mesh = True, and then scale back up. (Or make a custom displayable which does this on the renders). It's a little hacky, but I've seen some small performance gain with this.

That said, a better solution I think would be a built in cross platform method to resize the monitor resolution when entering Fullscreen mode, and resetting it upon exiting fullscreen mode or quitting (like many games do). 

I'm trying to implement this myself at the moment, though I'm only having success with Windows... and still not quite there yet,

**Comment by renpytom** [comment]
This should probably happen at the engine level, though I do need to see if this can work without a render-to-texture, which might kill all performance.

**Comment by renpytom** [comment]
Do we have any evidence this is an actual problem, rather than a theoretical one? This would kill text sharpness, and I'd be surprise if there are any platforms that can't fill the screen a couple of times over the course of a 16ms frame.

**Comment by colinharvie** [comment]
I encounter this problem with my game, usually only at resolutions higher than 1920x1080(so on my 4k monitor). Additionally I actually purposefully kill text sharpness, because my GUI assets are created for a 1920x1080 screen, and when those are scaled up next to sharp text, it doesn't look good. If nothing else, this would be good so creators can ensure a consistent visual experience regardless if the end user has a screen resolution larger than 1920x1080. 

I also make heavy use of shaders and Live2D assets, and it does start to chug a bit when I go higher than 1920x1080 for screen size, and sometimes ATL transformations won't run as smoothly or visibly skip a frame, and I have a fairly powerful desktop. Just as @hoshito-yurei shows in their video, if I reduce the monitor resolution to 1920x1080 (instead of 4k), it's then perfectly smooth.

I've written a script for my game that provides a second fullscreen option, which resizes the monitor resolution to match; and though it currently works, I'm really just messing around with windows api stuff I don't understand and can't get it to always resize the correct monitor on a multi-monitor setup.

**Comment by hoshito-yurei** [comment]
> Do we have any evidence this is an actual problem, rather than a theoretical one? This would kill text sharpness, and I'd be surprise if there are any platforms that can't fill the screen a couple of times over the course of a 16ms frame.
> 
> There's a big difference between Visual novels - fill rate limited - and games that have complex geometry.

Please take a look at the video embedded in the middle of my issue post. This isn't just a simple example, but actual footage recorded on my PC, which serves as evidence. This isn't an extreme case; there are many users with laptops that have fairly average GPUs but relatively high-resolution displays. The same applies to desktop setups - not all users with 4K or other high-resolution monitors necessarily own high-end GPUs. On these devices, this phenomenon can be easily reproduced.

I understand that without applying shaders, this stuttering issue rarely manifests, and that the current approach has advantages in text rendering. However, when applying graphical effects through shaders (and as @colinharvie mentioned, when using graphically intensive resources like multiple Live2D assets), this stuttering problem becomes clearly apparent, making this feature essential. As mentioned in the original issue post, for users with 14-16 inch laptops that have high-resolution but small screens, the reduction in text resolution may not be as noticeable, whereas frame rate drops would be far more disruptive. In these device environments, rendering at the maximum physical resolution of the screen is not an ideal approach.

And yes, as mentioned in the post, other engines - for example, visual novels using Unity, which easily allows for enhanced graphical effects - often come with built-in features to set rendering resolution to address this issue. If you'd like, I can send you the project used in the video for further examination.

**Comment by renpytom** [comment]
What are the specs of your pc?

**Comment by hoshito-yurei** [comment]
The device I used for the video demonstration is an iMac 27" 5K (2019) running Windows, with the following specifications:

```
Operating System: Windows 11 Pro 64-bit
CPU: Intel Core i9-9900K @ 3.60GHz
Graphics: 8192MB ATI Radeon Pro 580X
RAM: 32.0GB Dual-Channel DDR4 @ 2666MHz (19-19-19-43)
Monitor: iMac (5120x2880@60Hz)
```

**Comment by renpytom** [comment]
Does it have the problem running on macOS? I'm trying to figure out if this is a Ren'Py problem or an issue with the windows drivers for mac.

**Comment by hoshito-yurei** [comment]
This issue occurs on macOS as well. Please refer to the video below.

https://github.com/user-attachments/assets/d92d39f6-ec18-4ecd-9bf3-43888f3d3582

In the video, I start with a smaller screen where the lag isn't very noticeable, then expand to full screen. This demonstrates how higher resolutions increase GPU computations and usage, ultimately resulting in stuttering.

The exponential increase in computational load with higher resolutions, especially for effects like blur, is a common issue. Therefore, I don't believe this is specific to any particular OS platform or driver. You should be able to reproduce this frame stuttering on recent Windows laptops with high-resolution displays like 4K or QHD as well.

**Comment by colinharvie** [comment]
At the very least, having a "true" fullscreen mode that resizes the monitor resolution, instead of the standard windowed/desktop fullscreen (which is basically just a borderless, maximized window), would alleviate a lot of issues for lower end computers. 

I managed to get it to work myself via some methods in the SDL dll, though I don't know if this works cross platform or if it's going to cause any other problems. 

https://github.com/user-attachments/assets/94ad8b85-7157-4a3e-8b6a-11d4f9066d51

Biggest issue was handling a multiple monitor setup. I was initially playing around with the `pygame.display.set_mode`, but the version in Ren'Py currently doesn't support the display parameter. Not sure if there's a way around that, so I ditched it and went back to figuring out how to use the commands in the dll.

**Comment by renpytom** [comment]
No way we'll go back to changing the desktop resolution. That was a mess back when we tried it.

**Comment by renpytom** [comment]
I suspect the right approach here would be to let the user limit the amount of oversampling allowed in Ren'Py, which would reduce the size of the internal textures used for things like the blur shader. But I need to think about this more - I really dislike the idea of exposing settings like this to the player.

**Comment by hoshito-yurei** [comment]
To clarify, what I suggested wasn't changing the desktop resolution (I agree that this method is only temporarily usable and not ideal), but rather adding settings to limit the game's maximum rendering resolution, such as `config.max_rendering_width` and `config.max_rendering_height`, as mentioned in the original post. This way, there's no need to alter the desktop resolution.

This issue primarily affects laptops with smaller screens, and I thought it might not be efficient to render at the device's maximum resolution on these smaller laptops (especially since these devices often have weak GPUs paired with high-resolution displays). I also believed that due to the small screen size, there wouldn't be a noticeable impact on text quality. However, I completely understand your concern about potentially degrading text quality, which could be considered one of Ren'Py's strengths.

I proposed this idea because I thought it was a good one, considering that visual novels made with other engines like Unity already commonly offer this feature. In any case, I hope we can find an even better solution.

**Comment by Noriverwater** [comment]
I agree with your viewpoint. From the players' perspective, they actually don't care about the specific resolution; they just want to improve performance in fullscreen mode while minimizing any reduction in image quality. A "true" fullscreen mode—changing the desktop resolution—is not a good approach because it doesn't involve integer scaling, and everything ends up looking terrible. Achieving integer scaling is really important, such as scaling 720p to 1440p or 1080p to 4K. 

To this end, limiting the rendering resolution to an appropriate fixed size and applying a suitable upscaling algorithm is definitely a better approach.

**Comment by hoshito-yurei** [comment]
> > some text being part of images means it mis-matches in-engine text.
> 
> For the past decade or so, including text in images has been a mistake.

Well, these seem to be veering a bit off-topic from the original purpose of the discussion I started (which was about limiting rendering resolution to reduce stuttering).

**Comment by qinlili23333** [comment]
Actually, I think the biggest issue for performance is "Copy with GDI" in windowed mode.
![image](https://github.com/user-attachments/assets/80c1c434-abd7-4a46-9bea-b8aee46af750)
In this mode, DWM has to copy buffer from renpy, and compose to screen buffer. This costs a lot on low end GPU and siginificantly increases latency (~100ms even on RTX4080). 

Currently most modern games use Flip model instead of GDI Copy, the game requests a flipped layer so that it directly output image above DWM layer, so DWM doesn't need to copy it. 

To implement Flip model, we must create a DXGI swapchain and put GL context to this swapchain.

**Comment by renpytom** [comment]
@qinlili23333 

I don't think Copy with GDI is as big an issue as it seems, though it probably does introduced a little latency. 

On my computer, with Ren'Py in performance mode (f3, performance), I'm getting 47ms latency using GDI copy. That's comparing favorably Peglin, which using the Flip composer has a latency of 66ms. 

My guess is that what's happening is that there is some problems with the measurement tool when Ren'Py adjusts its framerate down. 

I'm not opposed to a DXGI swapchain, but this is certainly something that will wait for SDL3 (they look like they might be implementing this in SDL 3.2.) 


#5867 is a new issue to decrease latency by making sure frames are presented immediately when transitioning from a high framerate to 5fps.


I don't think there's much else to this issue, as I don't plan to limit the maximum resolution.

**Comment by hoshito-yurei** [comment]
@renpytom Well, in that case, are there any other methods you are considering to prevent excessive GPU resource consumption, for example in gaussian blur shaders?

**Comment by AJolly** [comment]
> I suspect the right approach here would be to let the user limit the amount of oversampling allowed in Ren'Py, which would reduce the size of the internal textures used for things like the blur shader. But I need to think about this more - I really dislike the idea of exposing settings like this to the player.

Some sort of advanced/debug settings?

**Comment by mirh** [comment]
If you are concerned about SDL and performance
https://github.com/libsdl-org/SDL/issues/13733
https://github.com/libsdl-org/SDL/issues/14791
https://github.com/libsdl-org/SDL/issues/15036
