### ISSUE TITLE
Count the number of dialogues within a label

### ISSUE THREAD

**Issue by Noriverwater** [renpy/renpy#5755]
There are currently `renpy.count_dialogue_blocks()` and `renpy.count_seen_dialogue_blocks()`, but I would like to be able to count the number of dialogues within specific labels or multiple labels. This would be very helpful for displaying the progress of different character routes in the game.

**Comment by Gouvernathor** [comment]
"within" a label doesn't mean anything in Ren'Py, as labels don't have scopes (unlike python functions).

**Comment by Noriverwater** [comment]
Oh, I overlooked this. Does that mean this feature can't be implemented?

**Comment by renpytom** [comment]
It can't be implemented.
