### ISSUE TITLE
Using a transition inside a Gallery makes videos restart when returning to Gallery overview

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5758]
Here is the sample code for seeing the bug (latest nightly fix). If you click on the unlocked image (just a purple rectangle) the video will play. If you then click on the video you return to the gallery overview, but the video restarts playing in the background (not visible anymore at that stage). This doesn't happen if you remove the gallery transition. [The video needs sound for you to experience it.]

```
image test_video = Movie(play="images/video.avi")

init python:

    g = Gallery()

    g.button("myvideo")
    g.image("test_video")

    g.transition = dissolve

screen gallery():

    vbox:
        add g.make_button("myvideo", Solid("#f0f5", xysize=(100, 100)), Solid("#ff05", xysize=(100, 100)))

        textbutton "Return" action Return() xalign 0.5 yalign 0.5

label start:
    call screen gallery
    return
```

**Comment by renpytom** [comment]
There isn't a great way to solve this, and given that it's an image gallery and not a general media gallery, I don't want to make major changes to Ren'Py to support this. 

I did add g.image("test_video", movie=True) to support this case - it will cause the gallery to forcibly stop the movie after the user clicks, without a transition.
