### ISSUE TITLE
Live2D model is broken when alpha is set to under 1.0.

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#5759]
After updated to 8.3.1, live2D models are not shown correctly with dissolve transform.
When models are shown with transform:alpha 0.9, it looks all layers of live2d models are shown with alpha 0.9, even if those layers are set to 0.0 in live2d editor.  
![screenshot0014](https://github.com/user-attachments/assets/fa232fe2-8fa5-46ef-ad02-6f85062a56b2)
(tears and 2 clothes are visible in the pic, but those are set to alpha 0.0 in the original live2d model)

**Comment by renpytom** [comment]
Can you put together a demo if this, please, so I can work on it? Thank you.

**Comment by nyaatrap** [comment]
Sure.
[test.zip](https://github.com/user-attachments/files/16830737/test.zip)

**Comment by renpytom** [comment]
So, I fixed the merging of uniforms, but I don't think I can fix the underlying properties. When you apply alpha 0.5 to a Live2D, it applies to each of the layers individually. 

That's a problem, as it means that her clothes will be transparent, letting you see her transparent body through the. 

To fix that, you want: 

```
image kirari = Flatten(Live2D(...))
```
