### ISSUE TITLE
Text object is not fully rendered when using a textshader and exceeding a character limit

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5760]
In one of my projects I have a big (scrollable) wall of text inside a viewport, which is displayed using a text object inside a screen.

With the new update, the text is only rendered until 20250 characters or so (I am including text tags like `{color}` here, I don't know about the raw text to be honest). Setting `textshader` to `None` inside the object, gets rid of the problem. It wasn't a problem before of course.

I don't know if shaders have a problem with too long text in general or this can be fixed, but I still wanna post this.

**Comment by renpytom** [comment]
Fixed, though there's an issue with text of more than 4096 pixels in height right now. (It works, but the text will be blurry.)

**Comment by m-from-space** [comment]
> Fixed, though there's an issue with text of more than 4096 pixels in height right now. (It works, but the text will be blurry.)

Do you mean that the whole object (if scrolled) will be blurred when it reaches 4096 pixel height or is it about *visible* pixel height? Because I don't need 8K UHD resolution anyway.

**Comment by renpytom** [comment]
The whole object, not just visible. I need to look into how to fix this.
