### ISSUE TITLE
feature request to register _imagebutton style suffix along with _image_button

### ISSUE THREAD

**Issue by 8o8b14Ka** [renpy/renpy#5764]
[According to this issue](https://github.com/renpy/renpy/issues/3649)
Maybe please just add style suffix _imagebutton along with _image_button it would be way more intuitive to style it same way as assign the button itself

**Comment by renpytom** [comment]
This won't work. The reason is that many of the properties of button (like padding) don't work for image_button, and so need to be avoided.
