### ISSUE TITLE
Top Level Default Statement

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#577]
After start or load, this will check to see if a variable is undefined. If it is, it will define the variable.

**Comment by evilantishad0w** [comment]
I'm hoping this will be optional (and rarely used); it can make debugging hell.

**Comment by renpytom** [comment]
Why? It will be optional, but I don't see why it would make debugging hell.

**Comment by evilantishad0w** [comment]
Because it will make typos in variable names much more difficult to track down.

**Comment by renpytom** [comment]
I think you're misunderstanding the proposed semantics. The semantics of default foo = True will roughly be equivalent to:

```
label after_load:
    if not hasattr(store, 'foo'):
         $ foo = True

   return

label start:
    $ foo = True

```

**Comment by evilantishad0w** [comment]
Yup, I misunderstood.  Sorry.

```
_defaults = {}
def default(s,v):
    _defaults[s]=v

def _setdefaults():
    for s,v in _defaults.items:
        if not hasattr(store,s):
            setattr(store,s,v)
```
