### ISSUE TITLE
Renpy crash on starting windowed project 

### ISSUE THREAD

**Issue by SoundGuyInc** [renpy/renpy#5773]
Full traceback:
  File "renpy/common/00start.rpy", line 296, in script
    python:
  File "D:\renpy-8.1.1-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.1.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 299, in <module>
    _enter_menu()
  File "renpy/common/00gamemenu.rpy", line 85, in _enter_menu
    renpy.take_screenshot((config.thumbnail_width, config.thumbnail_height))
  File "D:\renpy-8.1.1-sdk\renpy\exports\displayexports.py", line 596, in take_screenshot
    renpy.game.interface.take_screenshot(scale, background=background)
  File "D:\renpy-8.1.1-sdk\renpy\display\core.py", line 1438, in take_screenshot
    surf = renpy.display.draw.screenshot(self.surftree)
  File "gl2draw.pyx", line 1218, in renpy.gl2.gl2draw.GL2Draw.screenshot
AttributeError: 'NoneType' object has no attribute 'width'

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.1.24090601

Steps to reproduce - run in windowed mode
Error can be ignored

**Comment by renpytom** [comment]
I can't repeat this, using the launcher or the tutorial game. Are you having your problem with these games, or is it only happening with your game? If the latter, can I have access to your game to see if you can repeat it here?

**Comment by danac78** [comment]
I have run into this error, but only during an auto-reload when I was working on screens. Outside of that, I have no experienced that message come up. I typically just close the game, open it, and continue working on the screen I was working on.:)

The only other thing I was doing at the time when this screen came up was writing a python function so I put gallery images into HBox rows of threes without using grid so the last row could be centered if it only had two in it. There were times I wrote something in the code, it reloaded, and gave that error.

**Comment by SoundGuyInc** [comment]
Error on our end
We called the language choice screen in splash screen while main menu loaded in the background. We used return on button action.

**Comment by SoundGuyInc** [comment]
Error on our end
We called the language choice screen in splash screen while main menu loaded in the background. We used return on button action.
