### ISSUE TITLE
Upgrate the signature system to py3-only

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#5774]

**Comment by renpytom** [comment]
The signature system?

**Comment by Gouvernathor** [comment]
The Signature class and its Parameter adjascent class, it could use some parameters being kw-only for API clarity (and adherence to the inspect module's API to help maintenance) and using MappingProxyType o dict instead of OrderedDict, for both readonly security and memory use. There may be some other things I marked in comments.

**Comment by renpytom** [comment]
Ah, gotcha. For a moment I was thinking crypto signatures.
