### ISSUE TITLE
Suggestion: Reduce (re)load times by excluding script files

### ISSUE THREAD

**Issue by arsym-dev** [renpy/renpy#5777]
# Problem Description
On larger projects, it can take a lot of time to load and reload the game. **Personally I sometimes wait up to 15-20 seconds for a reload to complete.**

After doing some profiling, I found that certain files can take a long time to load up. In particular, **translation files** and longer **`init python:` blocks** can take a while to run, as well as earlier/later story scripts that you're not currently interacting with.

On my particular project, it takes:
- 8.3s to load scripts
- 5.4s to init code

These numbers can easily be cut if they're not done on each reload.

# Suggestion 1: Improved Profiling Data
At the minimum, I would suggest giving the developer a warning if a file took longer than a certain threshold to load.

This can be done by modifying `load_script()` in `renpy/script.py`:
```python
time_start = time.time()
self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
time_taken = time.time()-time_start

if time_taken >= 0.1:
    renpy.display.log.write(" - Loading %s took %.2fs" % (fn, time_taken))
```
(NOTE: I have no idea how to correctly format `fn` to include `.rpyc`, `.rpy` or `_ren.py` as appropriate)

# Suggestion 2: Exclude File List
The developer can tell the engine not to load certain files. During the startup phase, Ren'Py can read a file in the game folder (eg. `<game>/exclude.txt`) with a list of files to exclude. A sample file might look like this:

```
# This line is a comment
# All files below are not loaded during startup and reload

scripts/heavy_script.rpy
scripts/dir/*.rpy
tl/**
```

This may also take the form of a config variable:
```renpy
define config.exclude_files = [
    "scripts/heavy_script.rpy",
    "scripts/dir/*.rpy",
    "tl/**",
    ]
```

These entries will modify the behavior of `renpy.loader.listdirfiles` (or rather `renpy.loader.scandirfiles_from_filesystem` and possibly `renpy.loader.scandirfiles_from_archives`) such that they will ignore the excluded files.

Benefits:
- Developers can quickly exclude entire directories if they're testing changes in just a few files
Concerns:
- If a developer tries to access anything in the excluded files, an exception will be thrown. This may lead a developer to become confused if they forgot that a certain file is excluded. It may be necessary to modify the exception message to minimize frustration.

# Suggestion 3: Custom Scandirfiles Callbacks
During startup, functions in a particular directory (eg. `<game>/startup/scanfiles/*.py`) will automatically be imported and added to `renpy.loader.scandirfiles_callbacks` and allow users to create their own callback functions.

In this case I suggest adding a `remove()` method as a parameter in addition to the existing `add` parameter here:
```python
    for i in scandirfiles_callbacks:
        i(add, seen)
```

and the developer's function would look like:
```python
def scandirfiles_callback(add, remove, seen):
    ...
```

Benefits:
- Can allow a developer to quickly include tools from other projects/directories without including them in the game itself
- If these functions run after Ren'Py's default callbacks, the developer can manipulate the output of all the preceding callbacks, not just `scandirfiles_from_filesystem` and/or `scandirfiles_from_archives`

Drawbacks:
- Can be more cumbersome to set up than Suggestion 2

# Suggestion 4: Only reload changed files
This might be done by checking which files have a modification time past a certain point and reloading only those, but I imagine the engine dumps everything and reloads from scratch. This would be ideal but probably the least feasible.

# Conclusion
I can help develop any of these options, I'm curious to know which (if any) of these is a good idea.

**Comment by danac78** [comment]
For translations, are you using

`define config.defer_tl_scripts = True`

This cuts down on load times for translations because instead of loading all of them at once, it just loads the one being used (or none if it is currently on None).

**Comment by renpytom** [comment]
@danac78 has it right. 

I don't think it would be a good idea to allow finer-grained control over loading. Beyond that, disallowing the game from loading some files seems like it would cause more problems than it would solve.

**Comment by Andykl** [comment]
@arsym-dev Our team already have pretty much what you need, leveraging git knowledge of files state we increase load of the game by 2x and have an option to not load plot scripts at all. And also it rewrites how rpyc's in git are handled so not changed files are compile-compatiable between two instances of repo as a bonus.

But I agree with Tom and danac. Excluding scripts from loading is something very fragile (speaking from the expierence), it will cause more problems for teams without expierenced developer. I believe we should focus on how to improve script read-parse-compile time in engline and let the big projects cut corners on their own.

**Comment by MiiNiPaa** [comment]
4th is kinda hard to implement, because it will require tagging each piece of data in memory by file it came from. AST nodes already have that information, but everything else does not AFAIK. Then you will have problems with keeping references, handling some data value depending on reloaded data in init time, etc. Creating, keeping and using dependency graph for all that is too much work for not enough profit.

2nd can be trivially done with external scripts. Also for the same reason as in 4, you cannot realy distinguish entity not found because of file exclusion from entity not found for other reasons, so you cannot include that info in exception message.

**Comment by arsym-dev** [comment]
@danac78 Thank you, I wasn't aware of that feature. Using it I was able to cut load times from 13 seconds to 11 seconds.

@renpytom By excluding scripts from earlier episodes/chapters of the project, I was able to cut load times to 5 seconds. When you're making many incremental changes it really adds up.

I admit that excluding files will trip up some creators, especially if their scripts are messy, but a feature like this is targeted at larger projects who (hopefully) know how Ren'Py works.

@Andykl I'd be interested to know what git tricks you use to make it work. I agree with you that improving read-parse-compile time is a better solution overall.

@MiiNiPaa 4th is not really feasible, just throwing it out there as an idea. As for the 2nd being trivial, I would be open to hear a rough outline of what that looks like.

If an exception is thrown then it would not pinpoint the cause of the error. It would just say that "Some files were not loaded. Including them may resolve the issue".

----
Also, I discovered the existence of `Script.script_filter(self, fn, dir)` which returns a boolean that decides if a given filename should be loaded or not. It may be modified to read a variable like:
```renpy
define config.exclude_files = [
    "scripts/heavy_script.rpy",
    "scripts/episode1/*.rpy",
    "tl/**",
    ]
```

It could be implemented quick quickly, but it does have those pitfalls mentioned earlier. Personally I would prefer something native rather than spinning up my own spaghetti.

Maybe I'm underestimating how big of a problem it would be to inexperienced developers.

**Comment by MiiNiPaa** [comment]
@arsym-dev a script reads filenames from a file and adds `.ex` extention to it. Another script recursively removes `.ex` from all file in a folder. Run second script then first each time you edit exclusion file. Run second script before commits (you can even add it to the commit hooks)

**Comment by arsym-dev** [comment]
@MiiNiPaa Thanks for the suggestion. I went ahead and created a [script that does exactly that](https://github.com/arsym-dev/renpy_modify_script_load). I leave it here in case any one else wants to use it.

The issue in the title has been resolved (for me, at least), so perhaps it can be closed.

I still think that improved profiling data (as per Suggestion 1) is a good idea. The engine already reports if an init takes longer than `renpy.config.profile_init`. It would be nice if it also reports when a script takes longer than, say, `renpy.config.profile_script_loading` seconds.

**Comment by renpytom** [comment]
I'm going to close this, as I don't expect this to go into Ren'Py proper, and it seems to be resolved. I'm not sure what renpy.config.profile_script_loading would accomplish - in the end, all the scripts get loaded,  and so I don't know what it could tell you that would change anything.
