### ISSUE TITLE
how does renpy engine works?

### ISSUE THREAD

**Issue by Minokori** [renpy/renpy#5779]
I've reviewed the Ren'Py documentation, but its operation remains unclear to me. Specifically, as a game engine, I'm uncertain about the roles of classes such as Character, Image, and others during gameplay. Unlike Unity, Ren'Py lacks a clear declaration of its lifecycle. I've examined the Python source code within the Ren'Py SDK, yet it too offers scant details on the functions of a submodule or its timing within a game. Could someone succinctly explain how Ren'Py functions? Is it similar to other game engines like Unity, or is there an article that elucidates this?

**Comment by MiiNiPaa** [comment]
Did you check [Game Lificycle](https://www.renpy.org/doc/html/lifecycle.html) page? Did you try to follow [Quickstart Guide](https://www.renpy.org/doc/html/quickstart.html) to see what are different parts of engine do?

**Comment by renpytom** [comment]
Ren'Py functions as an interpreter that walks a tree of abstract syntax tree nodes. These nodes then call Python functions defined in othe files (like Characters, which are just callable objects). The objects then set up a scene graph, which then gets displayed to the player. 

That's the succinctly version - I don't really think there's a great way to expand this out shorty of just reading the source closely.
