### ISSUE TITLE
Added channels don't stop when load a game

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#578]
Added channels don't stop when load a game.

For example

 I added a new channel.
    renpy.music.register_channel("sound2", mixer="sfx", loop = False)

I played sound by the channel.
    play sound2 hogehoge loop

I loaded some game, but the channel is playing even if after load.

**Comment by kyouryuukunn** [comment]
I used v6.18.3.761
Windows7 64bit

**Comment by renpytom** [comment]
Isn't that true of all non-looping channels?

**Comment by kyouryuukunn** [comment]
I also tried the default "sound" channel, but this problem didn't occur.

**Comment by renpytom** [comment]
I'll look into it.
