### ISSUE TITLE
Css like effects for gui?

### ISSUE THREAD

**Issue by ewolf201** [renpy/renpy#5784]
Really stupid request but bear with me. I want their to be better means to make renpy look nice without having to write massive amounts of code to do so. I still remember one user asking if he could do a nice ease in hover for his game only to be met with "gotta use advanced Python for that". No shame against using Python, it's a lovely language, but you do start to feel it's limits eventually. It is with this that I want you to reconsider implementing better means of customizing gui that anyone can make beautiful menus without really trying.

I simply want ren'py to be better, do better, because I see potential in this software. (And I'm still wondering about the 3D perspective bug with the buttons)

**Comment by renpytom** [comment]
Please take a look at ATL, the Animation and Transform Language: 

https://www.renpy.org/doc/html/transforms.html

It's documented there, and there's a section in the tutorial game about it.
