### ISSUE TITLE
Input objects inside buttons don't fire on K_RETURN events

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5785]
The following input does not react when being active and then hitting "K_RETURN". Neither when hovering it with the mouse, nor when outside of it:

```
default name = "Eileen"
define input_object = VariableInputValue("name", default=False)

screen input_screen():
    modal True
    vbox:
        button:
            action input_object.Toggle()
            # doesn't react to hitting K_RETURN at all
            input value input_object
        textbutton "Close" action Return()

label start:
    call screen input_screen
    return
```

Also: The screen doesn't react to "K_RETURN" when using a key and having an **active** input, neither when hovering the input (which worked until recently), nor being outside of the input (which never worked):

```
screen input_screen():
    modal True
    # doesn't fire if an input is active (which would be okay if the input would react to it)
    key "K_RETURN" action DisableAllInputValues()
    ...
```

**Comment by m-from-space** [comment]
Hmm, is it because I explicitely have to define an action inside the input? I mean it works like that. But I expected it to disable itself, since it is not allowed to return.

`input value input_object action input_object.Disable()`

**Comment by renpytom** [comment]
In the input action world, which is intended to support multiple inputs on the screen at once, return does nothing. You need to provide a button or something similar that will dismiss the screen when all edits are done.

**Comment by m-from-space** [comment]
> In the input action world, which is intended to support multiple inputs on the screen at once, return does nothing. You need to provide a button or something similar that will dismiss the screen when all edits are done.

Uhm, maybe I wasn't clear when it comes to the problem I faced. The button example above works fine, if you click it, then the caret starts to blink and you can edit it. If you then hit "Enter", I expected the input to disable itself, since it is not allowed to return (being a VariableInputValue if returnable = False).

But then I figured that I have to put an action inside, that overwrites the standard return action (which isn't allowed to fire). So it works now as I would expect from it. I close this.

Thank you nevertheless.
