### ISSUE TITLE
Combining shaders

### ISSUE THREAD

**Issue by furudean** [renpy/renpy#5786]
Is there a way to use two shaders registered with Ren'Py on a single model? Is there such a thing as a shader pipeline? Is this a planned feature?

My use case specifically is to utilize a transform with multiple shaders, but there might be some other ways this could be used as well.

**Comment by renpytom** [comment]
Yes. Transforms can take a list of shaders.

**Comment by furudean** [comment]
How?

**Comment by renpytom** [comment]
```
show eileen happy:
    shader [ 'foo', 'bar' ]
```
