### ISSUE TITLE
button receives hover event despite not being hovered

### ISSUE THREAD

**Issue by brimbel** [renpy/renpy#5788]
Tested on 8.4.0.24091501+nightly

```
image changes_state:
    on idle:
        Solid('#f0f')
    on hover:
        Solid('#f00')

screen foo():
    grid 15 5:
        for i in range (75):
            button xysize (100,100) action NullAction():
                add "changes_state"

label start:

    scene

    "START"

    call screen foo

    "FOO"

    return
```

https://github.com/user-attachments/assets/537ceccc-5c2f-470a-82a5-d1e29cd5439d

**Comment by renpytom** [comment]
Can you please write what you're doing. It's not clear in the video what causes the button to transition from working to not.

**Comment by brimbel** [comment]
I'm moving my mouse over the buttons, then I move my mouse off the buttons, wait for a bit, and then see buttons start hovering. Then after a bit, I move my mouse back over the buttons.

The whole time, I'm not clicking or doing any sort of keyboard/controller inputs.

**Comment by smer44** [comment]
Yes i have reproduced it. Started the script, than I wait some time, while mouse is over one cell, so one cell is hovered. Then, other cells may randomly hover after some time.
