### ISSUE TITLE
The warp function doesn't work

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#579]
I tried warp like below
    renpy.exe tutorial --warp scripty.rpy:89
Then a game was launched, but it starts not the line but the main menu.

In v6.99.0.257, windows7 64bit

**Comment by renpytom** [comment]
Works for me. There's a typo in your example - it should be script.rpy, not scripty.rpy.

**Comment by kyouryuukunn** [comment]
Sorry, I actually typed like below.
    renpy.exe tutorial --warp script.rpy:89

In v6.18.3.761, this problem doesn't occur.
