### ISSUE TITLE
renpy.say doesn't save _last_say_what and therefore won't be able to "extend"

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5799]
This might be a rare use case, but here it is, the following either throws an exception or creates weird output if something was said normally (meaning without renpy.say) before:

```
$ renpy.say(e, "Hello my name is...")
pause 0.4
extend "Eileen"
```

**Comment by m-from-space** [comment]
The same is true when using the character's speak function directly by the way:

```
$ e("My name is")
extend " Eileen"
```

**Comment by renpytom** [comment]
This is true, but there's a huge chicken-and-egg problem here. I don't plan to support extend with anything but normal say statements.
