### ISSUE TITLE
Does the RenPy translation system support rpy-scripts spoofing?

### ISSUE THREAD

**Issue by norz3n** [renpy/renpy#5800]
Good afternoon!!!

I am doing embedded translation for a project, and in this project there is an interactive map that uses Python. 

And this map does not lend itself to translation properly

So my question is. Can RenPy spoof a file if it is in ``tl/language/script,rpy``, or a similar relative directory for the file?

**Comment by renpytom** [comment]
Yes, if you put a file in tl/language, it takes precendence over the one in the main game. Make sure you include the full path - so if the file is images/map.png, you'd want tl/language/images/map.png.
