### ISSUE TITLE
Presplash makes IME not appear when typing input

### ISSUE THREAD

**Issue by WindChimesGames** [renpy/renpy#5801]
I have a bit of a strange issue here. I discovered that in my game, typing in a language like Chinese in the input field does not result in the IME popping up for me to select a character. After some testing, I found out that it's the presplash images for some reason — if I remove presplash_background.png and presplash_foreground.png, IME is back when I type. 

I've tested in a fresh project by adding a presplash.png to game folder, and can reproduce the issue consistently.

**Comment by renpytom** [comment]
What platform(s) are you experiencing this on?

**Comment by WindChimesGames** [comment]
> What platform(s) are you experiencing this on?

It was on Windows 11!
