### ISSUE TITLE
If a screen is placed in a custom layer it's listed in Image Attributes dev screen

### ISSUE THREAD

**Issue by brunoais** [renpy/renpy#5804]
## Currently

If I create a layer that is on top of master and then make a screen which is designed to be on top of it, it's listed as if it's an image in `Image Attributes` screen:

```py
screen _brunoais_getDataAtPos_shortcuts():
    layer 'manipulate'
    text "I'm the cause of your demise"

init python:
    renpy.exports.add_layer("manipulate", above='master', menu_clear=False)
    renpy.config.always_shown_screens.append(("_brunoais_getDataAtPos_shortcuts"))
```

![image](https://github.com/user-attachments/assets/bc4809c4-b968-45a3-8af4-45d86fe1efd8)

Making it display in master also breaks it:

```py
screen _brunoais_getDataAtPos_shortcuts():
    layer 'master'
    text "I'm the cause of your demise"

init python:
    renpy.config.always_shown_screens.append(("_brunoais_getDataAtPos_shortcuts"))
```

![image](https://github.com/user-attachments/assets/7a17d2bd-8861-4fee-9c20-f4b193518003)

Apparently, the only layer that causes the screen to not be listed is by adding the screen to the `screens` layer (which is its default)

```py
screen _brunoais_getDataAtPos_shortcuts():
    layer 'screens'
    text "I'm the cause of your demise"

init python:
    renpy.config.always_shown_screens.append(("_brunoais_getDataAtPos_shortcuts"))
```
![image](https://github.com/user-attachments/assets/59030975-0b9e-4c85-9d67-2c6e029278af)

## Expected

A screen is never part of `Image Attributes`  because it's a screen and not an image, ~~not even a displayable.
![image](https://github.com/user-attachments/assets/8cde7ec8-8b25-4e7d-8c3b-a8a098f8d435)~~
Found `ScreenDisplayable`. So, nevermind about not being a Displayable.

**Comment by renpytom** [comment]
I kind of feel that I don't want to be too clever about screens versus images here. You're not likely to show an image on the screens layer, but if you somehow show a screen on the master layer, it should show up so you can see what's going on. A screen can conflict with images. 

And as you mentioned, a screen is a displayable. 

I don't think this needs to be changed, since it's an edge case.

**Comment by brunoais** [comment]
@renpytom In that case, at least marking a screen as a screen or, instead, marking all displayables that are listed with their type would be useful.
