### ISSUE TITLE
Lag when moving mouse if mouse polling rate is above 1000

### ISSUE THREAD

**Issue by RckStr8** [renpy/renpy#5807]
Hi!
I have made a screen that acts as a end credits for our game. It's basically a long vbox containing some 667 x 1080 sprites and text displayed as images. Then I use this transform to scroll the screen top to bottom -

```
transform credits_roll_effect:
    subpixel True
    yalign 0.0
    linear 71.0 yalign 1.0
```

This works fine without any lag or what so ever. But as soon as I move my mouse it stutters heavily. The stutter seems to occur only when I am moving my mouse. Also happens with other people in my team.

I read somewhere in Reddit that reducing mouse polling rate below 1000 can solve this issue. My mouse has a default polling rate of 1000. Reducing it to 500 using my mouse software completely fixes this issue. 

Reducing the amount of images or text doesn't resolve this issue anyhow.

Sorry, if this issue is already known but I couldn't find any open issue regarding this topic.
Also I don't know if there is any other solution to this instead of reducing the mouse polling rate.

Thank you.

**Comment by renpytom** [comment]
What kind of mouse are you using? Ren'Py should be merging mouse events together already, but your drivers might be causing problems.

**Comment by renpytom** [comment]
I haven't  been able to repeat thios, with a G102. 

Can you produce a small game that exhibits the problem? When I try it here, I get a steady 60fps.

**Comment by RckStr8** [comment]
I tried to reproduce this issue in a new project and just added the scrolling credits code. In the new project I don't have any issue what so ever. Can the lag possibly happen because of the project size? Our project side is around 8 GB.

**Comment by renpytom** [comment]
I wouldn't think it's due to the size, but it's possible there's something in your project that's triggering the slowdown, because it's reacting to the mouse move events.

**Comment by renpytom** [comment]
I'm closing this just to get it out of the way until the issue becomes repeatable in a new game. I don't see any obvious way mouse polling could cause this, as Ren'Py merges MOUSEMOTION events, but it's possible there are so many that coupled with slow event handlers Ren'Py is getting overwhelmed somehow. 

Without seeing the event handlers (which don't have to be particulary mouse related, or custom), it's hard to figure out what's slow.
