### ISSUE TITLE
[Enhancement] renpy.show_screen / renpy.hide_screen / renpy.call_screen need transition support

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy#5810]
In Renpy script you can easily use a transition to **show**, **hide** or **call** a screen. This isn't easily possible with the function equivalents, for example doing this:

```
show screen myscreen with Dissolve(1.0)
hide screen myscreen with Dissolve(1.0)

# expected equivalent (not working)
$ renpy.show_screen("myscreen", transition=Dissolve(1.0))
$ renpy.hide_screen("myscreen", transition=Dissolve(1.0))
```

The **transition** keyword is unknown, which is available for `renpy.show()` and `renpy.hide()`, when it comes to images.

The same goes for the call method, which I expected to work like this:

```
call screen myscreen(_with_none=False) with Dissolve(1.0)
with Dissolve(1.0)

# expected equivalent (not working)
$ renpy.call_screen("myscreen", _with_none=False, transition=Dissolve(1.0))
$ renpy.with_statement(Dissolve(1.0))
```

I hope this will change in a future release, because the workaround here is to call a label instead that uses Renpy script, which creates a lot of overhead.

**Comment by renpytom** [comment]
Call renpy.transition before renpy.call_screen.
