### ISSUE TITLE
Movie() behavior changed in 8.3.x

### ISSUE THREAD

**Issue by point-dot** [renpy/renpy#5814]
I think I found a bug.
In 8.3.1 and 8.3.2 my custom movie screen doesn't seem to loop/stitch movies together, it only works if all audio is muted (settings).
(sometimes it doesn't even show)

my movie screen:
```
screen movie_screen():
    frame:
        background None
        padding (0,0)
        at transform:
            subpixel True
            on show:
                alpha 0
                easein movieTransitionTime alpha 1
            on hide:
                alpha 1
                easein movieTransitionTime alpha 0
        add Movie(channel='stitchmovie',size=(1920, 1080))
```

changing the channel to 'movie' would fix the not looping/ stitching part, but introduces different problems

renpy 8.3.1 and 8.3.2
 - audio muted: movies work
 - audio unmuted: get stuck
8.3.0:
 - audio muted: movies work
 - audio unmuted: movies work

(audio playing)

https://github.com/user-attachments/assets/6a0c42b7-d6a8-4f19-9aa9-1b0e22a0e0f7

(audio not playing)

https://github.com/user-attachments/assets/1d0a0005-80a4-4f02-8014-22eb8bd31e7d

**Comment by renpytom** [comment]
Can you please upload the movie file so I can replicate this?

**Comment by point-dot** [comment]
Here you go.

[movies.zip](https://github.com/user-attachments/files/17186298/movies.zip)

**Comment by renpytom** [comment]
Do you have the demo game you used above? I don't think I understand the issue enough to fix it, and a replication will help me with that.

**Comment by point-dot** [comment]
Ok after creating a lil demo for you i realized that this problem is truly a mystery for me.
When creating a demo containing my "movie manager" with which i want to smoothly integrates movies i was unable to replicate the problem.
The only strange behavior was that after setting the channel on which the movies should play to "movie" the entire screen was blocked (unable to interact with buttons and dialogue), but worked after changing the channel once to "stitchmovie" and back everything worked as expected.
Now seeing everything "work" startled me and i did some more experiments in my game, with even more confusing results.
I realized that multiple things surrounding my "moviemanager" can create or prevent the "getting stuck" problem, for example after removing the transform from my choice menu (to change between movies) also impacted the "failure rate" of the movie getting stuck...
One interesting discovery i made is that the video sometimes gets stuck not perfectly at the end (looping point), but can stop a few frames before or after that…

My project has grown quite a bit over the years (which is why I don't know how helpful it might be sending it), should I still send it to you?

**Comment by point-dot** [comment]
Here is the demo i created where frustratingly everything works.
One interesting thing is that there is sometimes some noticeable slowdown before the first movie loops.

[movie demo.zip](https://github.com/user-attachments/files/17445303/movie.demo.zip)

One more thing reloading the game (Shift + R) always gets the movies unstuck

**Comment by renpytom** [comment]
I don't think the full game is likely to be very helpful. What's likely to need to happen is that you'll need to copy things from the old game to the new game bit by bit until something breaks, and since you know how everything is supposed to work together, that's going to have to be you. 

I did make a pair of commits, 906788fe8815a8b2e6b158ec41d19235f5a2d892 and 69b019f03c95253684a1b5867e645ae66b95258e, that improve the one path in the code that seems like it's even possibly relevant. But I have no confidence this is the problem you're having, it just disables the one place Ren'Py might have stopped the video itself.

**Comment by point-dot** [comment]
This change had no effect as far as i can see.

https://github.com/user-attachments/assets/64d22d0b-357d-4e65-a377-719bbec6c61d

Just to be sure i tested multiple renpy versions to maybe get a clearer view.

8.3.0 seems to recover

https://github.com/user-attachments/assets/68761f26-c2f5-431a-aa93-a3943b21664d

so did 8.2.3 (it might be even soother)

https://github.com/user-attachments/assets/09e5c588-2ef7-41b3-b114-e2aabf0df7d1

The thing that i think is most likely creating some sort of problem could be my "audio manager" which i use to create a 3d audio effect. When the player moves the audio pans and changes its volume accordingly. The audio manager is also the reason why i want to use 8.3.x because of the amazing audio filters.

On a somewhat related note (this might actually be the root problem). is the following wanted behavior:
My audio manager creates multiple channels (renpy.music.register_channel(channelName, 'music', loop = True)), but what i noticed is that tracks only loop once all tracks reached their end.
If the same thing happens to the movies this could be the reason.

**Comment by point-dot** [comment]
Thats it! After 6 min the background audio ends and the music as well as the video start looping!

https://github.com/user-attachments/assets/8ea55a4d-bfca-4da2-a064-717653066237

**Comment by renpytom** [comment]
I believe that I just fixed this in 9f3be6e, should be in tomorrow's nightly fix build.

**Comment by point-dot** [comment]
That seemed to be it!
Movies  are now behaving as expected again!
Many thanks for your efforts to fix the problem!
Let me take this moment to thank you for the love, time and effort you put into renpy.
I love the engine! Keep up the fantastic work!

**Comment by renpytom** [comment]
Sometimes hitting the close button is very satisfying. This is one of those times. 

Thanks for working with me to solve this.
