### ISSUE TITLE
Undefined Behavior in Ren'Py 8.2.3 (Runtime / Path issue)

### ISSUE THREAD

**Issue by Wendy-Nam** [renpy/renpy#5815]
I've been experiencing **undefined behavior** in Ren'Py (version 8.2.3), particularly when using third-party tools. I'm reaching out as this behavior is unclear and puzzling.

#### 1. Case 1: Issue with 3rd party shader tool

I encountered problems after moving a script file that used a third-party **outline shader** tool from:

`game/src/my_code.rpy -> game/libs/`

After this change, the script stopped working. The tool uses `init -50 python`, and moving my code into the same directory caused my script (`init python`) to stop working. It only worked after I changed my code to `init 100 python`. The issue seems to only happen when my code is in the same directory or a subdirectory of the tool's location.

#### 2. Case 2 : Issue with 3rd party viewport tool

While using the **parallax_viewport** tool (`python early`), I encountered the error: `"parallax_viewport: is not a valid child of vbox"` when calling it from `game/my_code.rpy`. I was calling the custom displayable in the standard Ren'Py way (not using `init` or `init python`). However, jumping in the label and running the provided examples in `game/parallax_viewport/parallax_vp_examples.rpy` worked perfectly.

When I made new directory and moved `my_code.rpy` to `game/src/`, Ren'Py recognized the CDD and it worked as expected:

`game/my_code.rpy -> game/src/my_code.rpy`

### My Questions:

1. Is this undefined behavior a bug or something expected in certain situations?
2. Are there any specific rules about how files and directories should be structured for calling third-party tools?
3. If this is a known issue, is there a way to prevent or mitigate these errors in larger projects with multiple external/internal sources?

Currently, the issue only affects small scripts, but I’m concerned about more complex projects with many CDDs or third-party tools, as this could cause undetected issues and impact the player’s experience.

I appreciate any insights or guidance you can provide!

**Comment by renpytom** [comment]
Ren'Py doesn't enforce any layout for script files in game, other than that the files are loaded in unicode order, which means that game/lib/my_code.rpy would be loaded before game/script.rpy, which is loaded before game/src/my_code.rpy. 

Other than that, there's not a lot of guidance I can give for third-party tools, please contact the creator of those tools for support.
