### ISSUE TITLE
Using Live2D in a custom displayable result in a crash if an array isn't provided for used_nonexclusive

### ISSUE THREAD

**Issue by Grimo0** [renpy/renpy#5816]
Creating a unique Live2D object will result in a crash here: 
https://github.com/renpy/renpy/blob/b430ca22439e55c0a9ed113898e0d945b710df80/renpy/gl2/live2d.py#L862

This is because `used_nonexclusive` is by default initialized with None instead of an empty array as it is in the the `_duplicate` method.
https://github.com/renpy/renpy/blob/b430ca22439e55c0a9ed113898e0d945b710df80/renpy/gl2/live2d.py#L552
https://github.com/renpy/renpy/blob/b430ca22439e55c0a9ed113898e0d945b710df80/renpy/gl2/live2d.py#L567

**Comment by renpytom** [comment]
You always want to use Live2D through an image reference, never directly. That being said, I'll look into this.

**Comment by Grimo0** [comment]
> You always want to use Live2D through an image reference, never directly.

Is there a specific reason for that ? I'm using it inside a custom class.

**Comment by renpytom** [comment]
How are you supplying the attributes to show to it? There isn't a way in the public api.

**Comment by Grimo0** [comment]
My custom class (it's unique) inherits from Container so the Live2D object is added as a child.

I create it like that and it works fine.
```
l = Live2D(
    filename,
    zoom=zoom,
    loop=True,
    fade=True,
    seamless=True,
    default_fade=0,
    motions=["m01"],
    used_nonexclusive=[],
)
self.add(l)
```
