### ISSUE TITLE
Regarding the Issue of Dialogue Box and Content Being Hidden During "call screen"

### ISSUE THREAD

**Issue by caqingtgas** [renpy/renpy#5819]
Currently, when using ‘call screen’ in Ren'Py, the dialogue box and its contents are automatically hidden. Is there a way to keep the dialogue box and its contents visible during ‘call screen’, similar to the behavior of the ‘show’ statement? I simply want to prevent anything from being hidden when ‘call screen’ is called.

While ‘show screen’ allows displaying additional screens while keeping the dialogue box visible, it doesn’t participate in the game flow like ‘call screen’, nor does it return a value using ‘_return’ as ‘call screen’ does. Manually saving and restoring the dialogue content is not only cumbersome but also unintuitive.

**Comment by renpytom** [comment]
Outside of a line of dialogue, the dialogue box has no contents. You can prevent the dialogue window from hiding with: 

```
init python:
    config.window_auto_hide.remove("call screen")
```

**Comment by caqingtgas** [comment]
@renpytom 

Thank you for the reply! 

However, I not only need an empty dialogue box, but also the original content to be displayed. How can I prevent the content from being cleared? 

I have an idea: would it be possible to merge the 'call screen' statement and the next 'say' statement into the same process? That is, when 'call screen' is executed, the following 'say' statement would proceed simultaneously, and after the 'call screen' interaction is completed, the game flow would continue. 

I am not very experienced in this area, so I would greatly appreciate your guidance.
