### ISSUE TITLE
Make "Image Attributes" indicate if layer is in non-default state

### ISSUE THREAD

**Issue by brimbel** [renpy/renpy#5822]
I have a lot of layers (sixteen!), and it's really hard keeping track of which layers have which transforms or ATL properties set to them via camera or show layer, especially when there's nothing on the layers (sometimes, I need those transforms for later, and sometimes, I forget to clear them).

Ideally, Image Attributes would just list all the non-default transforms and properties that are applied to a layer (and I would hope that would be possible), but falling short of that, I'll take something like "Layer [name] (Transform(s) applied)"

**Comment by renpytom** [comment]
I now have it indicate if transforms are applied to a layer or not, and where the transforms come from. 

Ren'Py doesn't keep transform properties or names handy internally (it can't, as it's easy to do a = b = Transform()), so all it does is show what kinds of transforms are on a layer.
