### ISSUE TITLE
Directly changing L2D parameters

### ISSUE THREAD

**Issue by Eliont** [renpy/renpy#5825]
Hello and good time of day.

There are update function, but seems can only overwrite parameters at render time.

How to change parameters directly on shown l2d?

For example pseudocode:

```
show expression "scene_1_l2d anim1"
"dialogue block"
$scene_1_l2d.update("parameter name", "parameter value", "time to blend into new value")
"dialogue block"
```
Where scene_1_l2d is Live2D class instance, not renpy.image associated one.

Thanks in advance.

**Comment by renpytom** [comment]
There isn't direct access to parameters like this, outside of update_function. You'd want to make an update function callback that reads the parameter from wherever else you set it.
