### ISSUE TITLE
Support for normal maps or secondary textures??

### ISSUE THREAD

**Issue by ewolf201** [renpy/renpy#5828]
Seems daunting so take this at your own risk: I was wondering if you had plans for normals support or bump maps. I'm in no rush but some other people might like the idea.

**Comment by renpytom** [comment]
Are you talking about 2d or 3d stuff? For 2d, you can probably add them with a shader, though Ren'Py doesn't really have a lighting system.

**Comment by ewolf201** [comment]
> Are you talking about 2d or 3d stuff? For 2d, you can probably add them with a shader, though Ren'Py doesn't really have a lighting system.

I'm curious about the 2d solution but the 3d one i'm not sure of.

**Comment by renpytom** [comment]
There isn't a system now - this is just a note that secondary textures are available in the Model class, and shaders you write can use them. I'm going to close this as an outstanding issue, but this will be addressed as 3D support is added to Ren'Py.
