### ISSUE TITLE
Image Attributes screen shows more than just images

### ISSUE THREAD

**Issue by brunoais** [renpy/renpy#5836]
Followup to:https://github.com/renpy/renpy/issues/5804

Given that `Image Attributes` screen shows all displayables not in the screens layer, I suggest it makes sense to both (or either):

1. Rename so it's called, for example, `Displayable attributes`
2. Also show what kind of displayable the listed Displayable is. (Screen, Image, etc...)

**Comment by renpytom** [comment]
These are image attributes, so it doesn't make sense to change the screen.
