### ISSUE TITLE
simultaneous atl causes weird mix-ups or stops working entirely 

### ISSUE THREAD

**Issue by ewolf201** [renpy/renpy#5839]
So I want my character to enter a scene right via dropping down or going up? but then when paired with an idle animation ontop of using a cinematic bar effect, suddenly it stops working.  I tried every combo in the book and nothing seems to work. In some cases, it breaks the game.

![ezgif-4-7242ee714d](https://github.com/user-attachments/assets/de119290-2296-4ff2-a301-d88c634a84ef)

**Comment by renpytom** [comment]
So, you can only have 1 ypos associated with a displayable. If you try to set it in two places, there will be conflicts. 

If that doesn't solve it, please create a short game demonstrating the problem, and take a look.

**Comment by ewolf201** [comment]
> So, you can only have 1 ypos associated with a displayable. If you try to set it in two places, there will be conflicts.
> 
> If that doesn't solve it, please create a short game demonstrating the problem, and take a look.


I assume there was something with align that might be the culprit so I'll update to see if it's not a bug and only a simple mishap

**Comment by ewolf201** [comment]
align might've been the issue lol. Had to do a layer setup and put at after the layer I named which managed to fix the issue.

**Comment by renpytom** [comment]
Okay, closing this.
