### ISSUE TITLE
using the transform `zoom` on `drag` causes the `drag` to drift when it's zoomed too small.

### ISSUE THREAD

**Issue by distortme** [renpy/renpy#5847]
This is a minimum-reproduction. Just delete all files in `game` directory and add a `rpy` file:
```rpy
default num = 0.5
init python:
    gui.init(1280, 720)
    def my_zoom(a):
        global num
        num += a
        renpy.restart_interaction()
screen main_menu():
    drag:
        pos (0.5, 0.5)
        child "eileen happy.png"
        at transform:
            anchor (0.5, 0.5)
            zoom num
        drag_offscreen (0, 320, 0, 720)
    key "K_q" action Function(my_zoom, 0.1)
    key "K_w" action Function(my_zoom, -0.1)
label start:
    "This is where the game starts."
```
From the `renpy-8.3.2-sdk\tutorial\game\images` copy `eileen happy.png` and paste it to your `game\img` directory. Then run it. When the key `W` is pressed enough times to make the `num` less than `0.4`, dragging will cause the `Drag` to drift. While it performs well in other cases. I guess that's because it's zoomed too small. But how can I achieve the same effect and avoid such problems?

Sorry, I don't speak English well.

**Comment by renpytom** [comment]
Because of how Drag works, transforms can't be applied to it. Instead, apply the transform to the child of the drag: 

```renpy
screen test():
    drag:
        pos (0.5, 0.5)
        anchor (0.5, 0.5)
        drag_offscreen (0, 320, 0, 720)

        add "eileen happy.png" at transform:
            zoom num

    key "K_q" action Function(my_zoom, 0.1)
    key "K_w" action Function(my_zoom, -0.1)
```

**Comment by distortme** [comment]
They are different. In this way, central scaling cannot be achieved by `anchor (0.5, 0.5)`.

**Comment by distortme** [comment]
You are right. Thank you.
