### ISSUE TITLE
AttributeError: module 'renpy.exports' has no attribute 'web'

### ISSUE THREAD

**Issue by NavyashreeChandraiah** [renpy/renpy#5848]
As I run my renpy game in a web broswer using a localhost,  I see - AttributeError: module 'renpy.exports' has no attribute 'web'. I am trying to communicate between renpy and javascript index.html code. For ex- 
 if is_web():
            # Web version - Call JavaScript SDK via Ren'Py's web execute
            properties_json = json.dumps(properties)  # Convert properties to JSON
            js_command = f'trackMixpanelEvent("{event_name}", {properties_json})'
            renpy.exports.web("execute_js", js_command)

I've tried using "jump_to_link", "web_location" but get the same attribute missing error

**Comment by qTich** [comment]
To execute `JavaScript` you should use the following - https://www.renpy.org/doc/html/web.html#javascript

**Comment by NavyashreeChandraiah** [comment]
When I user emscripten, I get the ModuleNotFoundError
`While running game code:
  File "game/1-welcome.rpy", line 85, in script
    $ identify_user()
  File "game/1-welcome.rpy", line 85, in <module>
    $ identify_user()
  File "game/analytics.rpy", line 95, in identify_user
    log_message(f"Mixpanel identify failed: {e}")
  File "game/analytics.rpy", line 37, in log_message
    import renpy.emscripten as emscripten
ModuleNotFoundError: No module named 'renpy.emscripten'`

**Comment by qTich** [comment]
`renpy.emscripten` is not module.
It variable - https://www.renpy.org/doc/html/other.html#var-renpy.emscripten 

```py
if renpy.emscripten:
    import emscripten
```
