### ISSUE TITLE
add a function for manually marking strings as translatable

### ISSUE THREAD

**Issue by Elckarow** [renpy/renpy#5849]
in case you need to import them from a file, like a `json` or `csv`

**Comment by renpytom** [comment]
You can use the _  and __ functions for this. 

See: 

https://github.com/renpy/renpy/blob/master/launcher/game/androidstrings.rpy#L7

for an example of this.

**Comment by Elckarow** [comment]
`_("this")` marks it as traslatable

but
```
that = "that"
_(that)
```
doesn't

**Comment by Gouvernathor** [comment]
Yep, that's how it works.

**Comment by Elckarow** [comment]
yeah, and the idea would be a function that actually adds the string as translatable, instead of letting the parser do it

**Comment by renpytom** [comment]
So something like:

```
init python:
    that = "that" 
    renpy.add_string(that, "filename.rpy", 1234) 
``` 

?

**Comment by Elckarow** [comment]
pretty much

**Comment by GiovanH** [comment]
I'm surprised this is budgeted low. I was looking into fixing this myself and submitting a patch, but it looks like the `scan` function only ever statically scans existing files. I don't see any mechanism for dynamically marking strings with runtime-only information, i.e. calling a function from within the script.

**Comment by renpytom** [comment]
So, I'm thinking of a callback that can generate the strings. I don't think the goal of this is to save data, but to allow portions of the game to be generated by other tools.
