### ISSUE TITLE
Is there anything the user can do regarding Fedora 41's removal of Python 2.7 breaking the many many pre-Ren'Py 8 VNs?

### ISSUE THREAD

**Issue by NintendoManiac64** [renpy/renpy#5853]
~~I just confirmed via testing myself that Ren'Py 7 VNs (and presumably Ren'Py 6, 5, etc) no longer work on Fedora 41 beta despite the exact same VN working on Fedora 40, presumably due to Fedora 41's removal of Python 2.7.~~

~~Considering just how many Ren'Py VNs use Ren'Py 7 and older (even some relatively recent commercial VNs!), I'm wondering if there's anything that the user can do in such a situation other than "avoid Fedora 41+"? (for reference, I already don't use Fedora as my distro of choice)~~

~~(also from my testing, it doesn't seem like wine works with Ren'Py 7, so one can't "cheat" by running the Windows EXE on a Linux system... at least not yet anyway)~~

　

**MAJOR UPDATE**: Turns out Fedora 41 beta doesn't like it when you use VirtualBox's default graphics controller for Windows OS (VBoxSVGA) rather than the default graphics controller for Linux OSes (VMSVGA) despire Fedora 40 having no issue.

However, this is very likely to be an unsupported configuration for all parties involved, not to mention has nothing to do with Ren'Py itself.

**Comment by renpytom** [comment]
Have you tried it? 

Ren'Py games don't use the system Python, and so should continue working.

**Comment by NintendoManiac64** [comment]
> Have you tried it?

I just did which is why I made this issue. Would you like me to record a demonstration video? I can do that—it'd be quite easy, but I'd need to redownload the Fedora 41 beta ISO first.

**Comment by renpytom** [comment]
Sure, or just the output of running ./lib/py2-linux-x86_64/python in a Ren'Py game. Or perhaps:

ldd ./lib/py2-linux-x86_64/python 

my guess is some necessary library is missing and needs to be installed.

**Comment by renpytom** [comment]
I did just bring up the beta 1.2 iso, and theRen'Py 7.8.2 SDK seems to work for me.

**Comment by NintendoManiac64** [comment]
Well this is peculiar... on real hardware and with VirtualBox set to the default graphics controller for Linux OSes (VMSVGA), everything "just works" on both Fedora 40 and Fedora 41 beta.

But if you have VirtualBox set to the default graphics driver for Windows OSes (VBoxSVGA), you very much get an error in Fedora 41 beta despite it working without issue in Fedora 40.

I realize this is not only not the fault of Ren'Py but is also probably an unsupported configuration as well from the Fedora and/or VirtualBox side of things, so I guess I'll close this issue.

...but since I *did* gather the logs and record & encode videos of this issue, I'll at least post those anyway.
