### ISSUE TITLE
8.0.3 selected slider not showing correct image when incremented

### ISSUE THREAD

**Issue by blacktabbygames** [renpy/renpy#5854]
https://github.com/user-attachments/assets/2bd7ebe6-85c3-4e57-b676-bbf388bc62ce

Trying to improve controller support by adding an extra png for sliders to change its color when selected (vs hovered)

File name for this new png is horizontal_selected_hover_bar.png

The color changes correctly when the bar is initially selected, but it changes back to the "hovered" style as soon as it's incremented in either direction.

**Comment by renpytom** [comment]
Is the problem in a currenty version of Ren'Py? 8.0.3 is a bit old at this point.

**Comment by blacktabbygames** [comment]
Tested in 8.3.2 and the issue persisted.

**Comment by the66F95** [comment]
isn't the selected state and thus its idle, hover and insensitive sub properties meant for showing a reached condition of the object?
while moving a slider you basically change the current value represented by the slider so the selected condition is no longer met until you finalize your selection.
i don't know if using selected* style properties makes much sense with sliders/bars.

**Comment by renpytom** [comment]
For a slider, selected is intended to be set when it's grabbed/changeable. So this is likely something I need to fix.

**Comment by blacktabbygames** [comment]
I added this fix and on testing it, it functioned correctly for sliders, but caused issues with hovered, sensitive imagebuttons.

Hovering would no longer switch from the idle to hover image.

**Comment by renpytom** [comment]
Did you get the second fix?

**Comment by blacktabbygames** [comment]
I only got the one in Commit 3cbe6fa.

Do you know where I can find the second one?

**Comment by renpytom** [comment]
It should be in the nightly fix build, or a few commits after that one (whjich I backed out).

**Comment by blacktabbygames** [comment]
Thank you Tom, this fixed it!
