### ISSUE TITLE
Try to update an array with after_load don't do anything

### ISSUE THREAD

**Issue by 00pandora00** [renpy/renpy#5859]
i currently working on a game an i trying  to make a menu inside a screen "upgradable between game versions"  To be more precise, I want the "saved games" to be able to see changes between versions. 

for that i'm **trying to use**  the  "after load label" to try to updates the data inside of an array variable (and consequently the screen menu)

but no matter what I try in the code, the menu (or to be precise the array variable) keeps the old values ​​in the "saved game".

things that i have try: 

-change the variable with the data 's type: default,define and persistent
- try to use direct transfer of values: example:
`  $ variable = ["xd" , "xd"] `
renpy ignores that if a previous version of that code exists in the "game saves"
example of old:
`  $ variable = ["xd xd" , "xd"] `
that will be display  instead of the new code.

is funny because i have done labels , change type of variables,etc.  and renpy update all that but still keep the old data values xd. 

meaby is bug with my renpy version (8.2.3 linux lutris)

but i report this because the after_load  label is useless if a can't update variables values at will

**Comment by 00pandora00** [comment]
note: i even try clean the variables before inserting the update value with `variable.clear()` .renpy ignored that it an insert the old values xD

**Comment by danac78** [comment]
Could you please post a sample code of how you use label after_load? What you have written is not clear as to where the problem is. Not saying it may not be a bug, but it is not clear based on what you have written.:)

-change the variable with the data 's type: default,define and persistent

These are not data types, and neither can be used in after_load to change the value. Persistent will change, but default and define are read once, and it does not apply to saved games.

**Comment by 00pandora00** [comment]
> Could you please post a sample code of how you use label after_load? What you have written is not clear as to where the problem is. Not saying it may not be a bug, but it is not clear based on what you have written.:)
> 
> -change the variable with the data 's type: default,define and persistent
> 
> These are not data types, and neither can be used in after_load to change the value. Persistent will change, but default and define are read once, and it does not apply to saved games.
variables related to the after_load
```
#IDIOMAS (variables generales)
default  persistent.sset_idioma = 1
default  persistent.sset_idioma2 = 0

#DIALOGOS
#configuracion y menus
# default opciones_y_menus_dial=[] #donde se usa esto? xd (pendiente)
default menus_y_otros_dial=[]

#items
default lista_items_dial=[]
#personajes
default narrador_dial = []

#otros
default e_nombres_y_relaciones_dial = []





#espanol
default  lista_items_dial_es = []
default e_nombres_y_relaciones_dial_es = []
default nombre_tiempos_en_dia_y_dias_dial_es= []
default narrador_dial_es = []
default menus_y_otros_dial_es = []
#english
```

all my after_load code (Note: if you see code of "insert value" Duplicate is because i have try putting it in different places)
```
label after_load:
    #limpiando variables de dialogo
    $ lista_items_dial.clear()
    $ lista_items_dial_es.clear()
    $ menus_y_otros_dial.clear()
    $ narrador_dial.clear()
    $ nombre_desconocido =" "
    $ reloj_nombres_td_y_d.clear()
    $ e_nombres_y_relaciones_dial.clear()
    call idiom_items_info_es
    call idiom_narrador_es
    call idiom_relaciones_y_tiempos_es

    $ lista_items_dial_es = [
        [
        1,
        "Maiz xd xd XD",
        "Fruta pequeña (sí, fruta) que sirve de alime \nnto. Su precio por unidad es 1.",
        "Fruta pequeña (sí, fruta) que sirve de alimento. Su precio por unidad es 1."
        ],

        [2,"","",""]
    ]
    if persistent.sset_idioma == 2:
        #espanol
            #menus y items
      
        $ lista_items_dial = lista_items_dial_es #idioma de lista info items
        $ menus_y_otros_dial = menus_y_otros_dial_es
            #####
            #dialogos de sistema y nombres random
        $ narrador_dial = narrador_dial_es
        $ nombre_desconocido = "desconocido"  
        $ reloj_nombres_td_y_d = nombre_tiempos_en_dia_y_dias_dial_es
        
            #intro post main menu
        $ e_nombres_y_relaciones_dial = e_nombres_y_relaciones_dial_es

  
    elif persistent.sset_idioma == 3:
            #english
            #menus y items
        $ lista_items_dial = lista_items_dial_en #idioma de lista info items
        $ menus_y_otros_dial = menus_y_otros_dial_en
            #####
            #dialogos de sistema y nombres random
        $ narrador_dial = narrador_dial_en
        $ nombre_desconocido = "unknown"
        $ reloj_nombres_td_y_d = nombre_tiempos_en_dia_y_dias_dial_en

            #intro post main menu
        $ e_nombres_y_relaciones_dial = e_nombres_y_relaciones_dial_en
```

example of label called in after_load

```
label idiom_items_info_es:
    $ lista_items_dial_es = [
        [
        1,
        "Maiz xd xd XD",
        "Fruta pequeña (sí, fruta) que sirve de alime \nnto. Su precio por unidad es 1.",
        "Fruta pequeña (sí, fruta) que sirve de alimento. Su precio por unidad es 1."
        ],

        [2,"","",""]
    ]
    return
```
Note: i have run all this code  
Note 2: if is too much to read a can make a "short version" to explain my point.

**Comment by 00pandora00** [comment]
> Maybe a shorter example. But on a different point, is there a reason you are not using _() to mark translations and using the TL folder to put the translations in?
> 
> https://www.renpy.org/doc/html/translation.html
> 
> For example,
> 
> ```
> $something[_("something"),_("something else"), _("Something more")]
> 
> textchar "[something[0]!t]"
> ```
> 
> Will take the the string, see the !t, and translate it into the selected language. If it is None, it will use what is there. If it is another language, it will subtitute the strings. The reason I say this is because that screen displays may be doing more work then necessary.:) when Ren'py could do it for you. :) It will create the TL folder for it and you can translate it there. It also keeps the code looking cleaner.:)

regarding the language don't worry i will take care of that soon of late. but i don't think it is wise to worry about a translation if a can't update arrays's values. that say here is a short version of my code:
 
```
default Lista_items_dial=["hello", "xd" ] # variable with old data 
#########
label after_load: 
$ Lista_items_dial.clear() #opcional
$ Lista_items_dial=["hello my name is","lol lol " ] #value updated
```
if you create a "game save" before the "update value"  in after_load ranpy ignores the "new value" and shows the "old" one.
after_load is not doing anything.

**Comment by 00pandora00** [comment]
> > Maybe a shorter example. But on a different point, is there a reason you are not using _() to mark translations and using the TL folder to put the translations in?
> > https://www.renpy.org/doc/html/translation.html
> > For example,
> > ```
> > $something[_("something"),_("something else"), _("Something more")]
> > 
> > textchar "[something[0]!t]"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Will take the the string, see the !t, and translate it into the selected language. If it is None, it will use what is there. If it is another language, it will subtitute the strings. The reason I say this is because that screen displays may be doing more work then necessary.:) when Ren'py could do it for you. :) It will create the TL folder for it and you can translate it there. It also keeps the code looking cleaner.:)
> 
> regarding the language don't worry i will take care of that soon of late. but i don't think it is wise to worry about a translation if a can't update arrays's values. that say here is a short version of my code:
> 
> ```
> default Lista_items_dial=["hello", "xd" ] # variable with old data 
> #########
> label after_load: 
> $ Lista_items_dial.clear() #opcional
> $ Lista_items_dial=["hello my name is","lol lol " ] #value updated
> ```
> 
> if you create a "game save" before the "update value" in after_load ranpy ignores the "new value" and shows the "old" one. after_load is not doing anything.

i have try to make multiple variations of that code an nothing. renpy pass of the new code.

**Comment by danac78** [comment]
I used this to try to replicate it (small sample game):
```
define e = Character("Eileen")
default Lista_items_dial=["hello", "xd" ]

# The game starts here.
label after_load:
    $Lista_items_dial.clear()
    $ Lista_items_dial=["hello my name is","lol lol " ]
    return

label start:

    # Show a background. This uses a placeholder by default, but you can
    # add a file (named either "bg room.png" or "bg room.jpg") to the
    # images directory to show it.

    scene bg room

    # This shows a character sprite. A placeholder is used, but you can
    # replace it by adding a file named "eileen happy.png" to the images
    # directory.

    show eileen happy
    # These display lines of dialogue.

    e "You've created a new Ren'Py game."
    #saved to this point
    e "[Lista_items_dial]"
    e "Once you add a story, pictures, and music, you can release it to the world!"

    # This ends the game.

    return
```
I click on Start to run it, and it shows the default. I scroll back to You've created a new Ren'py game" and saved it. I load the save, and it shows the new values.

**Comment by 00pandora00** [comment]
> I used this to try to replicate it (small sample game):
> 
> ```
> define e = Character("Eileen")
> default Lista_items_dial=["hello", "xd" ]
> 
> # The game starts here.
> label after_load:
>     $Lista_items_dial.clear()
>     $ Lista_items_dial=["hello my name is","lol lol " ]
>     return
> 
> label start:
> 
>     # Show a background. This uses a placeholder by default, but you can
>     # add a file (named either "bg room.png" or "bg room.jpg") to the
>     # images directory to show it.
> 
>     scene bg room
> 
>     # This shows a character sprite. A placeholder is used, but you can
>     # replace it by adding a file named "eileen happy.png" to the images
>     # directory.
> 
>     show eileen happy
>     # These display lines of dialogue.
> 
>     e "You've created a new Ren'Py game."
>     #saved to this point
>     e "[Lista_items_dial]"
>     e "Once you add a story, pictures, and music, you can release it to the world!"
> 
>     # This ends the game.
> 
>     return
> ```
> 
> I click on Start to run it, and it shows the default. I scroll back to You've created a new Ren'py game" and saved it. I load the save, and it shows the new values.

can you try with a screen (using text or textbuttons)? if that work fine, them my version of renpy is probably the problem.

**Comment by danac78** [comment]
Tested in a screen and it works.  I am saving it at the first eileen dialog. Default is already setting it when I click on Start, so it has the old value. When I click on load, it replaces it with the new value. However, there is something you said I need clarification on: 

>  if you create a "game save" before the "update value" in after_load ranpy ignores the "new value" and shows the "old" one. after_load is not doing anything.

How are you creating a save in after_load? Unlike the special label start (which basically Ren'py sees as the first script to run no matter what you name the .rpy file), you should not see after_load, let alone be able to save to it. When you click on load and open a save, it automatically (if it sees the label after_load) runs all of that label and ends at the return for that label. It takes a split second to do it so you should not see anything running let alone have time to save anything.:)

**Comment by 00pandora00** [comment]
> Tested in a screen and it works. I am saving it at the first eileen dialog. Default is already setting it when I click on Start, so it has the old value. When I click on load, it replaces it with the new value. However, there is something you said I need clarification on:
> 
> > if you create a "game save" before the "update value" in after_load ranpy ignores the "new value" and shows the "old" one. after_load is not doing anything.
> 
> How are you creating a save in after_load? Unlike the special label start (which basically Ren'py sees as the first script to run no matter what you name the .rpy file), you should not see after_load, let alone be able to save to it. When you click on load and open a save, it automatically (if it sees the label after_load) runs all of that label and ends at the return for that label. It takes a split second to do it so you should not see anything running let alone have time to save anything.:)

i not "saving in after_load" i'm using it to change a variable value that is all. (i understand i least that of renpy)
that said if your code is running fine after change values in after_load then my code have a problem or my version of renpy. 
i will tests some things and report  back here after that

**Comment by juniorthejunior** [comment]
You need `return` at the end of your `after_load` Label.
As well as `$ renpy.block_rollback()` to prevent the player from performing a rollback that undoes `after_load`'s code: https://www.renpy.org/doc/html/label.html#special-labels

**Comment by 00pandora00** [comment]
> You need `return` at the end of your `after_load` Label. As well as `$ renpy.block_rollback()` to prevent the player from performing a rollback that undoes `after_load`'s code: https://www.renpy.org/doc/html/label.html#special-labels

0_0 if that is true you save me (let me try that)

**Comment by danac78** [comment]
You should be using return for all labels. Otherwise, (unlike function in init python), it will keep going until it sees a return.

**Comment by 00pandora00** [comment]
> > You need `return` at the end of your `after_load` Label. As well as `$ renpy.block_rollback()` to prevent the player from performing a rollback that undoes `after_load`'s code: https://www.renpy.org/doc/html/label.html#special-labels
> 
> that don't work.

that i know was using  that to call for multiple label xD.

**Comment by danac78** [comment]
It is unlikely a Renpy version issue because after_load has not changed much afaik in quite awhile. And .clear() and $array = [" "] is straightup python that works in 2.7 and 3.9.

**Comment by juniorthejunior** [comment]
This is what it should ultimately look like (using your own example above):
```py
default Lista_items_dial = ["hello", "xd"] # variable with old data 

label after_load: 
    $ Lista_items_dial.clear() # opcional
    $ Lista_items_dial = ["hello my name is", "lol lol"] # value updated

    $ renpy.block_rollback()
    return
```
Compare your real code to this and see what you're doing differently. This is also working correctly in the latest SDK version at the moment (8.3.2), so do update yours if you are not on the latest.

**Comment by 00pandora00** [comment]
update: after checking me code, i found problem.

i was sending the data to the wrong variable xd.
Sorry for all the trouble, but all of you help me pointing me to the right direction.
Note: men i really need clean my code, i was going insane checking  the code multiple times xd

Again thank for the help xD
