### ISSUE TITLE
[Feature Request] Add the ability to pass args / kwargs to say screen

### ISSUE THREAD

**Issue by FiresparqProgramming** [renpy/renpy#5860]
I was under the impression we could pass arguments to the say screen based on this section of the API docs, however after digging through the code itself, I seem to have confirmed the functionality I'm seeing when I attempt it.

https://www.renpy.org/doc/html/dialogue.html#say-with-arguments

It seems that args / kwargs get passed to the underlying python code, however by the time it reaches the the say screen, they've been cleansed.

I additionally tried using _args / _kwargs as I thought perhaps that would work, but no dice.
Adding *args and **kwargs parameters

script line:
`theodore.say "This is a test of the say screen display. Now I just need to figure out how to flip this" (direction="right")`

from screen say:
![image](https://github.com/user-attachments/assets/a0f20c33-d0dd-4a36-9f7b-23c39588b22f)

from renpy.exports.say (printing output after handling renpy.config.say_arguments_callback):
`args: () kwargs: {'direction': 'right', 'interact': True}`

From character.say (`ADVCharacter()`):
kwargs: {'direction': 'right'}
kwargs: {'_mode': None, '_with_none': None}

What seems to be happening is that this line of code:
`
if kwargs:
            return Character(kind=self, **kwargs)(what, interact=interact, _call_done=_call_done, multiple=multiple, _mode=_mode, _with_none=_with_none)
 `
 is cleansing kwargs, preventing them from being passed along to anything further down the line.

**Comment by MiiNiPaa** [comment]
`(direction="right")` → `(show_direction="right")`
https://www.renpy.org/doc/html/dialogue.html#defining-character-objects
> Keyword arguments beginning with show_ have the prefix stripped off, and are passed to the screen as arguments. For example, the value of show_myflag will become the value of the myflag variable in the screen. (The myflag variable isn't used by default, but can be used by a custom say screen.)

**Comment by FiresparqProgramming** [comment]
Fuck.....
![image](https://github.com/user-attachments/assets/fbb2678a-609c-4a37-9c23-318543392b45)

Thank you so much MiiNiPaa. I read this too, and it didn't click.

> `(direction="right")` → `(show_direction="right")` https://www.renpy.org/doc/html/dialogue.html#defining-character-objects
> 
> > Keyword arguments beginning with show_ have the prefix stripped off, and are passed to the screen as arguments. For example, the value of show_myflag will become the value of the myflag variable in the screen. (The myflag variable isn't used by default, but can be used by a custom say screen.)
