### ISSUE TITLE
Request: preventing self-closing and sometimes extend from resetting ATLs applied to dialogue and nameboxes 

### ISSUE THREAD

**Issue by ewolf201** [renpy/renpy#5869]
This could be a intended feature given how dialogue segments work but it would be nice to find ways of making nameboxes more dynamic, having past dialogue history fade without resetting during transitions or clicks and whole lot of other things I didn't list.

**Comment by renpytom** [comment]
This would require a major rethink of how Ren'Py handles dialogue. That isn't a never, but it's far enough away that I'm going to close this request rather than leaving it open until that rethink happens. I understand that you want it, but don't expect it in the next few releases.
