### ISSUE TITLE
`avif` broken in web (8.4 only)

### ISSUE THREAD

**Issue by qTich** [renpy/renpy#5871]
Generating placeholders throws an error because the format is missing:

https://github.com/renpy/pygame_sdl2/blob/cc7ee10e5581f1e42e9620d6c9cb68ba340bad01/src/pygame_sdl2/image.pyx#L171-L182

Even if you bypass generation, loading an `avif` image will still result in an error:

```sh
Firefox: Uncaught RuntimeError: index out of bounds
Chrome: Uncaught RuntimeError: memory access out of bounds
```
Errors refer to `renpy.wasm` in the console.

`pygame.image.has_init(renpy.display.pgrender.formats["avif"])` returns `True`

**Comment by renpytom** [comment]
What version is this with?

**Comment by qTich** [comment]
`8.4.0.24102503+nightly`

**Comment by renpytom** [comment]
I can't repeat this in the current nightly. Here's a game that loads a .avif image, built with 8.4.0.24102804+nightly. 

http://share.renpy.org/gui-1.0-web

My guess is you have a subtly invalid avif file, and that's causing problems when it's loaded. (Which could be platform specific.) The placeholder generation code always forces .png, regardless of the original format, so the missing .avif save logic doesn't matter here.

**Comment by qTich** [comment]
I'm not sure which side the error is on.
However, if you use `--speed` less than `5`, the error above will occur.

`avifenc --jobs 2 --min 6 --max 6 --speed 3 --yuv 444 --premultiply`

**Comment by renpytom** [comment]
I compressed an image with those settings, using the avifenc that came with Ubuntut, and it worked. The version is: 

Version: 1.0.4 (dav1d [dec]:1.4.1, libgav1 [dec]:0.18.0, aom [enc/dec]:v3.8.2, rav1e [enc]:0.7.1 (UNKNOWN), svt [enc]:v1.7.0)

**Comment by qTich** [comment]
I still don't quite get it.

Because `Chrome`, that `Firefox` calmly opens these images,
as well as `Linux (Ubuntu 23.10)` or `Android (14)` (via `Ren'Py`),
but it is through the web there is a problem.

For this case, I used:
[lucy mad.zip](https://github.com/user-attachments/files/17563931/lucy.mad.zip)

`avifenc --jobs all --min 1 --max 1 --speed 0`

**Comment by qTich** [comment]
The problem is independent of the avifenc version, as I have several:
```
Version: 0.11.1 (dav1d [dec]:1.2.1, libgav1 [dec]:0.18.0, aom [enc/dec]:v3.6.1, rav1e [enc]:0.6.6 (UNKNOWN), svt [enc]:v1.6.0)
libyuv : available (1838)
```

```
Version : 1.1.1 (aom [enc/dec]:v3.9.1)
libyuv : available (1887)
```

**Comment by renpytom** [comment]
Okay, I can repeat this on 8.4 web, though I can't repeat the thumbnail part. Still not sure if it's Ren'Py or the image, but I don't think it's blocking 8.3. Can you repeatedly create images with the problem, using both tools?

**Comment by qTich** [comment]
That's right, thumbnails are always created in `.png`,
I only thought at the time that it was possible to save in `.avif`.

**Comment by qTich** [comment]
Oh, yes, the error shows up with both versions.

For this case, I used:
[bg washington.zip](https://github.com/user-attachments/files/17579745/bg.washington.zip)

`avifenc --jobs all --min 12 --max 12 --speed 0`
