### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by rniroi** [renpy/renpy#5872]
I am an amateur python programmer.. 
While writing the script for my visual novel, I got an attribute error and I don't know how I can deal with it. I tried completely reinstalling Renpy and the latest nightly build (released on 29/10/2024), but this didn't help :(
Here's the traceback I got, it was the same every time:
[traceback.txt](https://github.com/user-attachments/files/17558678/traceback.txt)
I would be really grateful for some help!

**Comment by danac78** [comment]
1.  https://nightly.renpy.org/ - You are using the latest development build. Try using the Fix build 8.3.3.24102802+nightly. The development is listed as "bleeding edge..may not work:)" while the other fixes issues, but otherwise stable.:)
2. Is there any part of the script you have written that lists anything?




</body>
</html>[8.3.3.24102802+nightly](https://nightly.renpy.org/8.3.3.24102802+nightly)

**Comment by danac78** [comment]
Particularly, 'list' object has no attribute 'rollback'. As far as I am aware, rollback is Renpy while list is Python. So if you try to list.rollback(), it will have a problem (an example rather than stating that what you did).

**Comment by renpytom** [comment]
@danac78 It's counterproductive to discourage people from reporting issue with the nightly builds, as that's how we find errors. 

@rniroi 
This is likely to be an error in Ren'Py. Could you send me the text of your script.rpy? I need to figure out what's causing this. It's very likely to be some sort of script error, too, but Ren'Py is not reporting that error correctly. 

Thank you.

**Comment by rniroi** [comment]
1. I still got the same error :(
2. No, if I get it right, I don't have any lists in my script
3. Here is the script itself: 
[scripttxt.txt](https://github.com/user-attachments/files/17560061/scripttxt.txt)

**Comment by the66F95** [comment]
i don't think `Monologue Mode` is supported in a say statement of a choice menu.
use
```py
    menu:
        e "Сэр Тоад Фроггинстон III..."
        "Вас не учила мама, что тыкать мечом в незнакомого человека некрасиво?":
            jump choice_toadd_enemy
        "Одна из фей попросила красного вина. Разве вы не были на вчерашнем балу?":
            jump choice_toadd_friend
```
instead.

**Comment by danac78** [comment]
Just quickly tested that in a known-good project, and yep...Monologue will cause a list attribute rollback error.

**Comment by rniroi** [comment]
Omg it works thank you so much! You are a life saver)

**Comment by renpytom** [comment]
This is still a bug, it needs to support a sensible error.
