### ISSUE TITLE
Strange behavior of saving system when I open the developer console

### ISSUE THREAD

**Issue by DolmatovNick** [renpy/renpy#5874]
My game has a weird loading and saving system. (**But my issue is not about my game!**)

I was trying to figure out why and I saw this weird behavior.
1. I go from location A to location B
2. I save the game
3. I load the game
4. I end up back in location A

But if I
1. I go from location A to location B
**1.1 I open the developer console, I don't write anything in it, I just open**
2. I save the game
3. I load the game
4. I end up in location B

What happens when I open the console that it fixes the saving system? And is there a way to reproduce this programmatically?

https://github.com/user-attachments/assets/facb2887-dfb3-44a8-b848-992eee424d93

**Comment by renpytom** [comment]
There's a non-greedy rollback that happens there, and a new checkpoint starts. 

My guess is you're not producing enough checkpoints to satisfy Ren'Py, but that's an issue with your game, not Ren'Py.
