### ISSUE TITLE
Function( ) as an action of a button gets called whenever the screen refreshes instead of whenever the button is clicked

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#5878]
I have this very simple button inside of a screen menu

textbutton ("Test") action Function(testing())

And this is the testing function

init python:
    def testing():
        print("Testing string")

Expected behavior:
The "Testing string" string gets printed when I press the button
Current behavior:
Whenever I show the menu the string "Testing string" gets printed twice and it also gets printed when something refreshes the screen

**Comment by Gouvernathor** [comment]
You want `Function(testing)`.
`Function(testing())` is just `Function(None)` since that's what the testing() function returns.
