### ISSUE TITLE
[8.0.3] When main menu plays a movie as the background, opening certain screens hides the interface and does not show the screen.

### ISSUE THREAD

**Issue by blacktabbygames** [renpy/renpy#5880]
The screens in question are the graphics acceleration menu and the ren'py console (if an error is thrown enroute to the main menu)

Here's the code for setting up the movie on the main menu.

`screen main_menu():

    ## This ensures that any other menu screen is replaced.
    tag menu

    if persistent.performance_mode == False and persistent.flickering:
        add Movie(size=(1920, 1080))
        on "show" action Play("movie", "images/menu/main_menu.webm", loop=True)
        on "hide" action Stop("movie")
        on "hide" action Hide(screen = "navigation")
        on "replace" action Play("movie", "images/menu/main_menu.webm", loop=True)
        on "replace" action Show(screen = "navigation")
        on "replaced" action Stop("movie")
    else:
        add "menu static"`
        
Everything overlayed on top of the animation disappears if users hit shift-g to bring up graphics options. Including screenshots of before and after hitting shift-g.

<img width="1166" alt="Screenshot 2024-11-01 at 12 04 07 PM" src="https://github.com/user-attachments/assets/18163146-b692-4d29-b9d8-86164cf91c69">
<img width="1170" alt="Screenshot 2024-11-01 at 12 02 54 PM" src="https://github.com/user-attachments/assets/a55892d2-4559-4e5e-86a9-14e6b78068c9">

**Comment by renpytom** [comment]
This looks like an issue with your game to me. 

The movie channel is a bit special. If something is playing on it, it's played fullscreen - unless there's a Movie displayable there to take the result of the image. In your case, you're hiding the Movie displayable but keeping the movie channel playing (showing these screens won't stop it by default), and so you get this problem. 

Probably your easiest solution for this is:

```renpy
screen main_menu:
  ## This ensures that any other menu screen is replaced.
  tag menu
  
  if persistent.performance_mode == False and persistent.flickering:
      add Movie(size=(1920, 1080), channel="mm_movie")
      on "show" action Play("mm_movie", "images/menu/main_menu.webm", loop=True)
      on "hide" action Stop("mm_movie")
      on "hide" action Hide(screen = "navigation")
      on "replace" action Play("mm_movie", "images/menu/main_menu.webm", loop=True)
      on "replace" action Show(screen = "navigation")
      on "replaced" action Stop("mm_movie")
  else:
      add "menu static"`
```

That is, to just show the main menu movie on a different channel.

**Comment by blacktabbygames** [comment]
Thank you, Tom, this worked great!
