### ISSUE TITLE
Suggestion: Would it be possible to make show/hide work with enumerate/one-by-one transforms? 

### ISSUE THREAD

**Issue by ewolf201** [renpy/renpy#5886]
![choiceexample](https://github.com/user-attachments/assets/d551443d-39cc-48e9-be14-b1b6d7c58400)

Note: the gif as shown is from a non-renpy game 

Like having it to where it shows one by one and hides one by one. One workaround is having the choice buttons outside the vbox, making the show/hide function properly. Alternatively, a screen for fake choice buttons with their own timers, but that raises more questions than answers like how will it track the amount of choices, the general complexity, and methods of making sure none of them break. If it feels too bothersome you're free to close this request, i'm not fussed about it. 

edit: as in choices.

**Comment by renpytom** [comment]
Why was this closed as not planned? I'm sort of thinking about it.
