### ISSUE TITLE
CardGame.py: Card marker implementation not complete?

### ISSUE THREAD

**Issue by Queex** [renpy/renpy#589]
Looks like a renaming of 'highlights' to 'markers' was left incomplete;

    I'm sorry, but an uncaught exception occurred.

    While running game code:
    ...
      File "game/cardgame.rpy", line 207, in render
        c.render_to(rv, width, height, st, at)
      File "game/cardgame.rpy", line 614, in render_to
        if self.highlights:
    AttributeError: '_m1_cardgame__Card' object has no attribute 'highlights'

However, renaming the attributes consistently doesn't fix the feature, as there's a rendering problem once markers are added:

    I'm sorry, but an uncaught exception occurred.

    While running game code:
      ...
      File "game/cardgame.rpy", line 207, in render
        c.render_to(rv, width, height, st, at)
      File "game/cardgame.rpy", line 617, in render_to
        surf = renpy.render(d, width, height, st, at)
    ValueError: subsurface rectangle outside surface area

Is this an implementation that was never quite finished?

**Comment by evilantishad0w** [comment]
The Cardgame framework appears to be only available on the deprecated wiki, and says it was last tested with Ren'py 6.7.0.  I'd check the Lemmasoft forum for an updated version.

**Comment by Queex** [comment]
I've not been able to find any newer version, despite searching the forum. It might be that it's not supported any more, but I can't find any definite information anywhere.

**Comment by evilantishad0w** [comment]
Just downloaded and ran the game demo for Cardgame-2.zip and it ran fine.  Please provide source that is triggering this error.

**Comment by Queex** [comment]
The underlying problem with rendering I've tracked down to a mistake on my part (the marker image overflowing the card image, which perhaps should be handled better).

I'm away from my main computer, but any attempt to use add_marker() should run into the variable naming problem.

After fixing that name and correcting my mistake, drag-n-drop seems to have stopped working, but I've not had chance to investigate that problem further.

**Comment by evilantishad0w** [comment]
Prease provide example source, in a test game, that triggers this error.

**Comment by Queex** [comment]
Example game provided here: http://chthonic.150m.com/scratch/game_test.zip
It offers a choice as to whether to attempt to use markers or not. If not, it runs as expected but without markers. If so, the images with markers applied are not rendered, and drag and drop does not work at all.
Note that the cardgame.py version in this test is not stock, as it has had the naming error concerning markers corrected.
