### ISSUE TITLE
Can't get sys.modules['renpy.error'].report_exception() to work.

### ISSUE THREAD

**Issue by McBakonMahn** [renpy/renpy#5898]
I use the same method as DDLC uses. I know this function is supposed to be hidden or smth like that.

I get no traceback.

```rpy
python:
        try: sys.modules['renpy.error'].report_exception("exception-test", False)
        except: pass
```

**Comment by renpytom** [comment]
That's not a supported API. (There is some magic as to not break DDLC, but this is not something we support for new games.)
