### ISSUE TITLE
Unresponsive screen buttons with arrowkeys/gamepad until recompile

### ISSUE THREAD

**Issue by Charmareian** [renpy/renpy#5902]
https://github.com/user-attachments/assets/97dd670e-7847-43e5-8c4a-9a1889805034

The above video shows a Renpy screen with the following buttons:
-6 buttons on the top in an hbox
-2 buttons to increase and decrease the page in between
-30 buttons in a 6x5 vpgrid

With arrowkeys/gamepad, this menu isn't navigate-able. The first couple of seconds of the video are me spamming the keyboard. 

What's strange is after recompiling my code, the menu is perfectly navigate-able with arrowkeys/gamepad. This seems like a bug?

If you need a build, let me know.

**Comment by renpytom** [comment]
> What's strange is after recompiling my code, the menu is perfectly navigate-able with arrowkeys/gamepad. 

Sure, send the game (ideally in source) to renpytom@gmail.com, and I'll see what I can do.

**Comment by Charmareian** [comment]
Build sent.

**Comment by renpytom** [comment]
This looks like an issue with Pink engine, or how your game works. When you enter the rumblemenu screen, the map is active with controls enabled, and so it's eating the arrow key events. (And assumedly the gamepad events.) 

One possible fix is to add "modal True" to the rumblemenu screeen, so that other screens do not get the keypad events.

**Comment by Charmareian** [comment]
Hmm. I previously had modal True on my rumblemenu, but I had issues were I could click out of that screen somehow(couldn't figure out how to reproduce the issue consistently) and returned to the Pink Engine map. Perhaps not as I also did a major refactor around that time. Regardless, this might be an issue than has to get solved with Pink Engine, not Renpy itself.

**Comment by renpytom** [comment]
You may also need to somehow tell Pink Engine to not respond to keyboard events. (The OrthagonalTiledMap class has enable_controls and disable_controls methods, but I don't know if those are meant to be called from screens.) 

In any case, this isn't a problem with Ren'Py.
