### ISSUE TITLE
Ran'Py was unable to run python with tkinter to choose the directory

### ISSUE THREAD

**Issue by Cyan1dE09** [renpy/renpy#5906]
whenever I go into the preferences in renpy on mac (this is version 6.99.12.4), it gives me the error that "ren py was unable to run python with tkinter to choose the directory". Do u know how I can fix it?
![Uploading Screenshot 2024-11-13 at 7.34.58 pm.png…]()

**Comment by Elckarow** [comment]
update your renpy version. 6.xx is prehistoric

**Comment by renpytom** [comment]
Yes, this is an ancient version (from 2017) and this problem has long since been fixed.
