### ISSUE TITLE
Could there be a list to what contained in each RPU for developers?

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#5908]
Currently using the Large Game for Mobile for PC/Linux. I have a 1.8 GB game that breaks down into 50MB files. However, since all the dates come out to be what the Build Process does, it is difficult to tell which is new information and what has not changed from an uploader point of view. The only option is to upload it all even if the change is 13MB at best. Knowing which RPU represents what files may decrease what RPU get uploaded for an update since the others may be the same.

I am willing to admit I do not get how RPU are made, so I am aware it may or may not be possible.:)

**Comment by renpytom** [comment]
Files should have the same name if the data in the file is the same.

**Comment by danac78** [comment]
@renpytom So to clarify this:

1f6d45cf095b4e8541e131db6042640a7cc49a0958a0aceca4c88979001a51fe.rpu will stay the same if nothing changes in these files. But if I go into script.rpy and do $print("Yoohoo"), it will create a brand new rpu file while the others remain the same? The reason I ask I looked through the documentation for mentions of RPU (which only come up with HTTPS/HTTP and Large Games for Mobile" does not mention that tidbit.
