### ISSUE TITLE
Google Suspends renpy game app because its play asset delivery doesn't work.

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [renpy/renpy#5911]
Hi,

I have been facing problems with Renpy's android build for google play, typically the AAB file it generates. 

Google play reviewers are unable to download assets from play asset delivery. They said that that App is broken and the "opens but doesn't load", then they send a screen shot of the loading screen with 0 percent completed, in it. 

We even got [our app suspended](https://support.google.com/googleplay/android-developer/thread/307655685) due to it and somehow got it conditionally back. 

My question is from what I understand the renpy uses ~~`on-demand`~~ `fast-follow` asset packs, which is causing most of the issue, so can't I change it to `install-time` ~~or `fast-follow`~~ asset packs? or do not use the play asset delivery all together (since the whole game is less than 2GB), while the game engine development fixes this issue?

Google said that it's not an issue from their side as they only conditionally accepted our appeal stating that the still the app is still violating broken app policy. 

We were using custom graphics for the loading screen changing `android-downloading.jpg` and `android-presplash.jpg`

I have attached the issue screen forwarded by google play reviewers.
![Untitled](https://github.com/user-attachments/assets/ea240da9-b192-4cc5-84cf-8475fd1b070f)

I was and am using engine version `8.3.2` stable release.

Also a thing to note, this issue was not found during internal or closed testing weirdly.

**Comment by danac78** [comment]
Have you tried to the latest version of Renpy (or the prerelease). This particular issue was addressed I believe in that.

**Comment by danac78** [comment]
https://www.renpy.org/dev-doc/html/changelog.html#other-changes

From 8.3.3

**Comment by danac78** [comment]
You could also use the latest use the Nightly Fix update as well for the same difference. The Prelease is basically that with under 8.3.3 without the nightly designation. Long story short, it is just essentially fixes that has been tested and applied to reolve issues that have been reported after 8.3.2.

The only difference between 8.3.3 and 7.8.3 is Python 2 and a few other things that related to that. Android and most of Ren'Py functionality is the same between the two. So by using 8.3.2, you have the Android Build issue that was causing a problem at that point.

If I recall correctly, the difference between Nightly and Nightly fix is so fixes could go out to reolve issues without waiting for a whole new Ren'Py version. The Nightly (8.4) is in development and could break. Nightly Fixes (8.3.3) are just things that came up after 8.3.2 came up and Tom and others fixed to resolve the issues. The install-time and fast-follow issue is one of them.

Ultimately it is up to you, but do not see the harm in installing the Pre-release.

**Comment by danac78** [comment]
To answer the question if you should wait or go with it, that is up to you. I was merely pointing out that it was addressed in a Nightly Fix.

The changelog goes for 7x and beyond, so 8.x applies to it. The only difference between stable releases and Nightly fixes is Nightly Fixes are not as tested as thoroughly as releases.

**Comment by danac78** [comment]
@Mr-Kumar-Abhishek 8.3.3 is now the stable release.

**Comment by Mr-Kumar-Abhishek** [comment]
Well, I have submitted the app with renpy version 8.3.3 , lets see what happens.

**Comment by Mr-Kumar-Abhishek** [comment]
@danac78 There are issues with renpy version `8.3.3` , its not stable yet, typically when movie is played at `splashscreen`, and player the starts the game after going through the `splashscreen` , the movie's audio which was in `splashscreen` repeats in start label.

**Comment by renpytom** [comment]
How do you play the movie? Since if a movie is playing, play asset delivery worked.

**Comment by Mr-Kumar-Abhishek** [comment]
Yes in `8.3.3` play asset delivery worked for the closed testing at least , I will promote it to open testing once the engine bugs are resolved. I tested this code with `8.3.2` and `8.3.3`. In `8.3.2` it worked fine but in `8.3.3` the `splashscreen` movie audio repeats in start label:

This is the how I implemented the `splashscreen` movie.

```
image trailer = Movie(channel="trailer", play="images/trailer.webm")

label splashscreen:

    scene black with dissolve

    show trailer with dissolve

    pause(128)

    return

label start:

    "Other texts.. doesn't matter what..."

```

I am no expert in renpy code, but if it works in previous version and not in latest version then something might be off.

**Comment by renpytom** [comment]
@Mr-Kumar-Abhishek 

I'm unable to replicate the issue your'e having in my codebase, which is similar to the 8.3.3 nightlies. Can you replicate it with a small game, like: 

```renpy
image trailer = Movie(channel="trailer", play="oa4_launch.webm")

label splashscreen:

    scene black with dissolve

    show trailer with dissolve

    pause 2

    return

label start:

    "Other texts.. doesn't matter what..."
```

If you can repeat it on a new project, please file a new issue with the new project attached. (This one looks like it's solved, and any splashscreen-related issue is likely to be unrelated.)

**Comment by Mr-Kumar-Abhishek** [comment]
@renpytom Yes, I will try to replicate it and make new issue about it if it replicates. But regarding Play Asset Delivery issue previously Renpy used `fast-follow` it was working in internal testing and closed testing but didn't worked in production (which eventually lead to app suspension). So not sure if this `install-time` play asset delivery will work on production, but we will see when that time comes I suppose.
