### ISSUE TITLE
Question about updater.UpdateVersion

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#5912]
If I understand the documentation right, it is supposed to contact the server and get a new version number or returns None. However, what I am unclear about is what is supposed to happen.

The reason I ask is what I wanted to do:

```
if updater.UpdateVersion(urlupdate,check_interval=21600,simulate=None) != None:
     updater.Update(urlupdate,restart='utter')
```

But if I put that in (to avoid the updater splashscreen), it will constantly bypass the update screen because the if statement will be false. 

Now, another way I have read the documentation is that if there is a new version, it will send the new version. Is it referring to running the updater.Update() method or does it mean the version number in the JSON?

**Comment by renpytom** [comment]
The way this works is that sometimes (up to a bit more than half a day) after you post an update to the server, this will start returning the the new version (the value of build.version) as a string. 

The intended use is: 

```renpy
screen main_menu:
     # ... 
    $ update_version = updater.UpdateVersion(URL)
     if update_version:
           textbutton "Update to version [update_version]." action updater.Update(URL)
     else:
           text "You're on the latest version.
```

**Comment by renpytom** [comment]
Note that this can be hard to test if you don't set check_interval to something small. (But set it back, so your server doesnt' get hammered.)

**Comment by danac78** [comment]
@renpytom Thanks for that note.
