### ISSUE TITLE
Skip and RollFoward action.

### ISSUE THREAD

**Issue by Alex200R0** [renpy/renpy#5918]
I’m working on implementing voice control in RenPy.

To implement the "Forward" command, I need to trigger the `Skip` or `RollForward` actions from the `renpy` object. However, at the moment, these actions can only be bound to buttons.

Could you add methods to directly call these actions in the `renpy` object, similar to how the `Rollback` action is handled (e.g., `renpy.rollback()`) ?

**Comment by Elckarow** [comment]
you can call actions with `renpy.run`
ie

```
renpy.run((RollForward(), Skip()))
```

**Comment by Lezalith** [comment]
Linking the docs page for reference.
https://www.renpy.org/doc/html/screen_python.html#renpy.run
