### ISSUE TITLE
AttributeError: 'org.renpy.android.PythonSDLActivity' object has no attribute 'bind' (or 'unbind' for that matter).

### ISSUE THREAD

**Issue by NaughtyRoad** [renpy/renpy#5920]
On Android, when attempting to call `activity.bind`, an exception is thrown: _AttributeError: 'org.renpy.android.PythonSDLActivity' object has no attribute 'bind'_. A similar exception will be thrown when calling `activity.unbind`.

Note, I'm primarily looking for a way to implement an activity for ACTION_CREATE_DOCUMENT to write a file (and ACTION_OPEN_DOCUMENT to read it later on). If Ren'Py requires a different implementation than the one provided in the example, I'd happily adopt that. Specifics on why I want to use ACTION_CREATE_DOCUMENT are detailed in _Use Case_ below.

### Example code:

The following example demonstrates this issue. Note the code is just exploratory at this point and full of other issues I'm sure, I'm trying to get the basic blocks to function before I actually implement it doing anything useful, and I got stuck on this part. 

All examples I can find for this are based on Kivy, and so the code I cobbled together is somewhat too in that regard. Kivy and Ren'Py diverged some time back I understand, so I'm aware there's a chance that I might be looking at one such divergence. [Python for android](https://python-for-android.readthedocs.io/en/latest/apis.html#module-android.activity) seem to implement bind, but I'm not sure if that has any bearing at on all on Ren'Py's implementation.

```
init python:
    import json
    import os

    REQUEST_STORAGE_ACCESS = 1
    CLS_Activity = None
    CLS_Intent = None
    CLS_Bundle = None
    mActivity = None

    class my_file_interop:
 
        def my_android_create_document(self):
            if renpy.android:
                from jnius import autoclass
                from android import activity

                CLS_Intent = autoclass('android.content.Intent')
                CLS_Bundle = autoclass('android.os.Bundle')

                intent = CLS_Intent(CLS_Intent.ACTION_CREATE_DOCUMENT)
                intent.setType('text/plain')
                bundle = CLS_Bundle()
                bundle.putString(CLS_Intent.EXTRA_TITLE, "export.txt")
                intent.putExtras(bundle)
                intent.addCategory(CLS_Intent.CATEGORY_OPENABLE)

                mActivity = autoclass("org.renpy.android.PythonSDLActivity").mActivity

                # this bit neatly pops up Androids file picker and creates an empty file at least, so so far so good.
                mActivity.startActivityForResult(intent, REQUEST_STORAGE_ACCESS)

                # but here's where it goes off the rails with
                # AttributeError: 'org.renpy.android.PythonSDLActivity' object has no attribute 'bind'
                activity.bind(on_activity_result=self.on_activity_result)

        def on_activity_result(self, request_code, result_code, intent):
            global user_entered_file_path
            try:
                if request_code == REQUEST_STORAGE_ACCESS:
                    if result_code == Activity.RESULT_CANCELED:
                        user_entered_file_path = ""
                    if result_code != Activity.RESULT_OK:
                        raise NotImplementedError('Unknown result_code "{}"'.format(result_code))
                    user_entered_file_path = intent.getData().getPath()
                    #TODO: implement writing json to file

            finally:
                from android import activity
                android.activity.unbind(on_activity_result=self.on_activity_result)

label start:

    $ user_entered_file_path = ""

    "about to call create document"
    $ my_file_interop().my_android_create_document()

    "URI returned = '[user_entered_file_path]'"

    return

```

### What this code does do before crashing.:

When executing, it's actually launching the Android file picker (even as my Ren'Py code crashes in the background), and that file picker lets me select a save location for a file, and it creates a file with a length of 0 bytes that I can see in Android's standard file browser, so that's hopeful. But without the callback, I am unable to write to the file (or even know what the user selected).

### The use case:

I want to carry my player's choices from one ren'py game to another. Ideally, I'd use _Multi-Game Persistent_ files for this, but this is not supported on Android (at least not for passing data between two packages). So for my Android users, I'm trying to work around this by saving a dictionary of relevant choices to a json file (as plain text), and then importing it in the new game. 

However, in the latest versions of Android, files created by a package are scoped to that package and cannot be opened by another package, even if you attempt to request the "android.permission.READ_EXTERNAL_STORAGE" permission. 

So this is where the [Documents Provider](https://developer.android.com/training/data-storage/shared/documents-files) comes in. The documentation seems to suggest that the act of going through the _Documents Provider_, which involves a user interaction to select specific files, allows us to get around the scoping of files in shared storage to the package that created it, presumably because it's the user performing the action thus mitigating risks. So I want to let my users save the file to a location they chose, and then in the new game, load it from the location they chose as another user action.

This code is my attempt to test that, and it requires to call mActivity.startActivityForResult and provide a callback to android.activity.bind(). But, if there's other ways to implement REQUEST_STORAGE_ACCESS and it's counterpart, ACTION_OPEN_DOCUMENT, I'll be happy to adopt that. :)

**Comment by renpytom** [comment]
So, this example is invalid - you're using a method from Kivy in Ren'Py, and that's not something you can expect to work. 

If you'd like someway of handling onActivityResult, we can talk about that. But just taking things from other Python libraries and expecting them to work isn't likely to be useful.

**Comment by NaughtyRoad** [comment]
Cheers, thank you, that's very much what I want to do.
Is there currently a way to handle onActivityResult with the current implementation?

**Comment by NaughtyRoad** [comment]
In fact, a little polling loop works just fine.

```
while (mActivity.mActivityResultResultCode == -1) and (mActivity.mActivityResultRequestCode != REQUEST_STORAGE_ACCESS):
    renpy.pause(0.1)
renpy.pause(0.1)
my_handle_activity_result(mActivity.mActivityResultRequestCode, mActivity.mActivityResultResultCode, mActivity.mActivityResultResultData)
```

Not sure if that second pause in there is entirely needed to prevent race conditions with not all parameters set, but I figure it can't hurt either. I should probably have some sort of way to break out of the waiting if it turns out to be infinite, but, meh.

**Comment by NaughtyRoad** [comment]
Oh, and I can also confirm that files saved in this manner can be opened by it's counterpart from a different package, so this can work if you're seeking an alternative to Multi-Game Persistent files for sharing choices between games, and don't mind the user has to perform a manual action exporting and importing.

**Comment by qTich** [comment]
> Oh, and I can also confirm that files saved in this manner can be opened by it's counterpart from a different package, so this can work if you're seeking an alternative to Multi-Game Persistent files for sharing choices between games, and don't mind the user has to perform a manual action exporting and importing.

I believe this has already been discussed there - #5432.
For your game you are free to patch however you want,
but most people don't need it and may not like write access.

**Comment by NaughtyRoad** [comment]
> > Oh, and I can also confirm that files saved in this manner can be opened by it's counterpart from a different package, so this can work if you're seeking an alternative to Multi-Game Persistent files for sharing choices between games, and don't mind the user has to perform a manual action exporting and importing.
> 
> I believe this has already been discussed there - #5432. For your game you are free to patch however you want, but most people don't need it and may not like write access.

Slightly different case I think. And note, using this way, no access is requested (or granted) at all.

The thing is, I'm not interested in giving an existing package permission to look at files a pervious version of it wrote, I'm looking to have one package (the new game) be able to read a file another package (the old game) exported somewhere earlier. Two packages, because I want the old and new game to be able to be installed side by side on the device.

The problem then is that files written to external storage or elsewhere by one package cannot be accessed by another package, no matter what permissions you request (in fact, requesting READ_EXTERNAL_STORAGE now seems to always fail), because files are scoped to the package that created them. 

I've tested this: the code that reads a file from the documents folder fine when it's executed from the package that wrote that file, fails when you build an APK with a different package name from the same code, and install and execute it on the device. 

But, as the documentation on the Documents Provider linked to a few posts up states, writing and reading files does not require any system permissions to be granted to the app in question if done through the documents provider, available from API level 29+ (and ren'py's on 35 now), because of the user performing those actions explicitly. 

It's the most hassle-free way I can think of to get a bunch of data from one package to another.

**Comment by qTich** [comment]
> Slightly different case I think. And note, using this way, no access is requested (or granted) at all.

I see an explicit access check with the 2 messages above in the `while` loop.

> The thing is, I'm not interested in giving an existing package permission to look at files a pervious version of it wrote, I'm looking to have one package (the new game) be able to read a file another package (the old game) exported somewhere earlier. Two packages, because I want the old and new game to be able to be installed side by side on the device.
> 
> The problem then is that files written to external storage or elsewhere by one package cannot be accessed by another package, no matter what permissions you request (in fact, requesting READ_EXTERNAL_STORAGE now seems to always fail), because files are scoped to the package that created them.
>
> I've tested this: the code that reads a file from the documents folder fine when it's executed from the package that wrote that file, fails when you build an APK with a different package name from the same code, and install and execute it on the device.

Again:
```
For your game you are free to patch however you want,
but most people don't need it and may not like write access.
```

> But, as the documentation on the Documents Provider linked to a few posts up states, writing and reading files does not require any system permissions to be granted to the app in question if done through the documents provider, available from API level 29+ (and ren'py's on 35 now), because of the user performing those actions explicitly.

I think you have a lack of understanding of how API access works.
The minimum supported device version at the moment is `API 21 (Android 5.0)`, and you in turn cite an implementation of `API 29 (Android 10.0)` which is lower than that, and you would need to make a case for lower versions.
Example: https://github.com/renpy/renpy-build/blob/af70b727cc9025e19fa55246f9c17595776da7de/rapt/prototype/renpyandroid/src/main/java/org/renpy/android/PythonSDLActivity.java#L571-L580

> It's the most hassle-free way I can think of to get a bunch of data from one package to another when the Multi-Game Persistent files are not an option on Android.

Again:
```
For your game you are free to patch however you want,
but most people don't need it and may not like write access.
```

**Comment by qTich** [comment]
> > I see an explicit access check with the 2 messages above in the `while` loop.
> 
> Nope, you misread that (I misread that too when I first saw that sample I lifted it from). Snippets below, with some comments added for clarification.
> 
> ```
>     # developer defined magic number, that can be anything you like. In fact, in the bit that's going in production, I changed it to 12345 for the hell of it.
>     REQUEST_STORAGE_ACCESS = 1
>     (...)
>     # this arbitrary values is then passed to the startActivityForResult...
>     mActivity.startActivityForResult(intent, REQUEST_STORAGE_ACCESS)
> 
>     (...)
>     # ...so that you can check  that random number you made up in your handle activity result code, 
>     # and that create a generic handler for multiple types of request (write, read, folder access).
>     if request_code == REQUEST_STORAGE_ACCESS:
>        #  So here, you get some code to pull a URI from the data returned in the Intent, and write data to the user-selected file it describes.
> ```
> 
> > I think you have a lack of understanding of how API access works. The minimum supported device version at the moment is `API 21 (Android 5.0)`, and you in turn cite an implementation of `API 29 (Android 10.0)` which is lower than that, and you would need to make a case for lower versions.
> 
> From https://www.renpy.org/release/8.3.3
> 
> "Ren'Py's Android support now targets Android 15 (API Level 35)."
> 
> Unless I completely misunderstand what that says, I believe that means the latest release of ren'py is well above what is required for my code, but I'm very much open to have my lack of understanding enlightened if I mistook that.
> 
> > > It's the most hassle-free way I can think of to get a bunch of data from one package to another when the Multi-Game Persistent files are not an option on Android.
> > 
> > 
> > Again:
> > ```
> > For your game you are free to patch however you want,
> > but most people don't need it and may not like write access.
> > ```
> 
> Again: no write access required.
> 
> But maybe let me turn this around: feel free not to use this code at all, or see any merit in it. But it does the trick for me at absolute minimum level of intrusion to the user including not requesting access (I've tested it), so I'm happy as a bug. :)

I'll answer briefly.

Via direct access:
Depending on the Android version you will need to request different permissions:
`<= API 29 (Android 10)` - `WRITE_EXTERNAL_STORAGE`.
`>= API 30 (Android 11)` - `MANAGE_EXTERNAL_STORAGE`.

Via `Documents Provider`:
It does not have access to all dirrectories, and starting with `API 30` access is limited to `Android/data`, `Android/obb` and more. Again, it requires user interaction to use it - there is no way it can be used as `MultiPersistent`.

As an export option for you - maybe it's a good choice, but globally it's bad.

**Comment by NaughtyRoad** [comment]
> (...)
> Via Documents Provider:
> It does not have access to all dirrectories, and starting with API 30 access is limited to Android/data, Android/obb and more. > Again, it requires user interaction to use it - there is no way it can be used as MultiPersistent.

Alright, let's have one more go and then call it quits? This feels like it's devolving into a contest, and that's not my intention (nor yours, I presume).

I think you misread my post, I never intended it should replace `MultiPersistent`, or argued for it to be included in Ren'Py. In fact, this issue wasn't about that, it was about me mistakenly thinking that `org.renpy.android.PythonSDLActivity` had a missing implementation for `bind()`.

After Tom nudged me out of my mistaken impression that `.bind()` was an Android pattern instead of a Kivy one, I was quickly able to find out how to interact with `org.renpy.android.PythonSDLActivity` no-nonsese implementation for `startActivityForResult` and get a result, case (or issue) closed. 

Now, the use case that I described is a quite specific one: one game ends its storyline, user choices are to be saved, then the user starts another game, and their choices are to be imported at the start of that. 

For my PC, Linux, and Mac players, I'd implemented that use case already using `MultiPersitent`, Ren'Py all the way, gods I love that engine.  For my Android players, I needed a different solution, and finding a way that does so with two dozen or so lines of _custom code_, and adding two rather straight forward user interactions and _no permission hassles_, that is perfectly acceptable _for my use case_. 

> access is limited to Android/data, Android/obb and more.

That wording is a bit ambiguous, so just to clarify, that means you _don't_ get access to `Android/data` and `Android/obb` when using _Document Provider_. And that is fine by me for _this use case_. I want my users to store this file somewhere that makes sense to them, like `Documents`, or `Downloads`. Average consumers have no business going into `Data` or `OBB` anyway I feel.

> .>= API 30 (Android 11) - MANAGE_EXTERNAL_STORAGE.

I'm not sure if you were giving an overview of options (which is helpful and much appreciated), or suggesting it as an alternative. It may be for some, but for _my use case_, `MANAGE_EXTERNAL_STORAGE` seems overkill, given posts like this: https://support.google.com/googleplay/android-developer/answer/10467955, and _my personal_ preference would be not to mess with it unless I had no choice.

> As an export option for you - maybe it's a good choice, but globally it's bad.

I wholeheartedly agree with the first part of that, and I thank you for your clarifications. Now how about we let this thread be indexed in peace, a nice pointer for anyone in the future that runs into that particular misconception I had when it comes to `startActivityForResult` and `bind()`? And maybe as a nudge in the right direction if they are looking to have users interact with files for very specific cases. God knows it's hard to find useful examples when you're a complete novice when it comes to Java, Android, and autoclass, like me.
