### ISSUE TITLE
`config.per_frame_screens` Breaks `on show` Transform Events (Regression?)

### ISSUE THREAD

**Issue by loafylemon** [renpy/renpy#5926]
**Description:**
Upon upgrading from Ren'Py version 8.3.2 to 8.3.3, certain animations no longer trigger their `on show` events as expected. This issue can be resolved by removing the affected screen from `config.per_frame_screens`.

**Steps to Reproduce:**
1. Create a new project in Ren'Py 8.3.3.
2. Add a screen with a transform animation that includes an `on show` event.
3. Add this screen to `config.per_frame_screens`.
4. Run the game and observe that the `on show` animation does not play.

**Expected Behavior:**
The `on show` animation should trigger as it did in version 8.3.2.

**Actual Behavior:**
The `on show` animation is not triggered when the screen is included in `config.per_frame_screens`.

**Workarounds:**
1. Remove the affected screen from `config.per_frame_screens`. This allows the `on show` event to trigger the animation correctly.
2. Adding `on start, show:` to the transform fixes it as well.

**Code:**
```renpy
label start:
    scene bg room

    call screen wheelmenu

    jump start

init python:
    config.per_frame_screens.append("wheelmenu") # <-- Breaks `on show` events in the screen

screen wheelmenu():
    tag wheelmenu
    zorder 1

    default start_pos = renpy.get_mouse_pos()

    window at wheelmenu_anim:
        id "wheelmenu"
        style "empty"
        pos (start_pos[0] - 30, start_pos[1] - 30)

        button:
            align (0.5, 0.5)
            add "#ff0000" at transform:
                subpixel True
                xysize (48, 48)

    button action Return() style "empty"

transform wheelmenu_anim:
    on show: # <-- animation won't play when screen exists in `per_frame_screens`
        zoom 0.0
        alpha 0.0
        easein_back 0.2 zoom 1.0 alpha 1.0
    on hide:
        easeout 0.15 zoom 0.0 alpha 0.0
```

**Comment by loafylemon** [comment]
Possibly related to #5916

**Comment by the66F95** [comment]
caused by 1a7f0ca.
it seems that your window never receives a `show` event.
