### ISSUE TITLE
Can we have renpy.get_movie_duration added?

### ISSUE THREAD

**Issue by HorBro38** [renpy/renpy#5928]
`renpy.music.get_duration(channel='music')` already exists to find out the duration of the music playing, I was wondering if we could get similar code to allow us to see how long a movie file is.  I assume the code exists for this somewhere already since it is likely used in `renpy.movie_cutscene`, I'm building something similar and not having to manually enter a movie's duration would be useful.

**Comment by loafylemon** [comment]
You can already do that (although it's not documented or intuitive) by getting the duration from the movie sound channel:

```renpy
renpy.music.get_duration("movie")
```

If there's no film playing, function returns `0.0`.

**Comment by HorBro38** [comment]
Yeah, using `renpy.music.get_duration` was able to resolve this.  Closing.
