### ISSUE TITLE
SpriteManager() + LayeredImage resulting in error about pickling render sometimes?

### ISSUE THREAD

**Issue by WindChimesGames** [renpy/renpy#5938]
Hi! Sorry for the vague weird title, I'm not sure how to describe my issue lol 

Basically, I'm working on this project that has a customizable MC sprite, and it uses a shader (Feniks' colorize shader) to color many of the layer parts like hair/skin/eyes, etc. so that the player can choose a color in game. 

Due to performance issues, I've been using SpriteManager() for most of the shader-colored parts and then adding it to my LayeredImage sprite for the MC. Like this: 

```
default mc_back_layer = Null()
image mc_sprite_back_layer = DynamicDisplayable(return_mc_sprite, variable="mc_back_layer")
default mc_front_layer = Null()
image mc_sprite_front_layer = DynamicDisplayable(return_mc_sprite, variable="mc_front_layer")

init python:

    def create_mc_sprite():
        store.mc_back_layer = SpriteManager()

        if store.mc_backhair:
            store.mc_back_layer.create("mc_backhair_dd")
        store.mc_back_layer.create("mc_colorized_body")
        if store.mc_bodymark:
            store.mc_backmost_layer.create("mc_bodymark_dd")
        
       # ....... remaining layer parts to mc_back_layer and mc_front_layer omitted here

    def return_mc_sprite(st, at, variable):
        comp_img = [(1500, 1000)]
        comp_img.append((0, 0))
        comp_img.append(getattr(store, variable))
        return Composite(*comp_img), None

layeredimage mc:
    always:
        "mc_sprite_back_layer"

    # ....... groups for eyes / mouths / brows w/ attributes omitted here 

    always:
        "mc_sprite_front_layer"
```

Now this does work to show the MC sprite correctly with improved performance (compared to if I just dropped all the DynamicDisplayables for each part separately into the LayeredImage. 

The problem is that I've been receiving a weird bug report from a small portion of players where they sometimes find that trying to load a save file results in an error like this:
```
While running game code:
  File "game/script/general5.rpy", line 2190, in script
    menu(nvl=True):
  File "renpy/common/00nvl_mode.rpy", line 496, in nvl_menu
    return renpy.display_menu(
TypeError: 'NoneType' object is not iterable
```
And this error will continue to show up for every line no matter how you Ignore it, until it reaches a scene where MC sprite has been cleared from the screen. 

Upon investigating the save file that I asked to be sent to me, I also found that if I try to make a save or even just Auto-Reload with Shift + R, it then throws pickling errors regarding the render:
```I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00action_file.rpy", line 415, in __call__
    renpy.save(fn, extra_info=save_name)
Exception: Can't pickle a Render. (perhaps store.mc_back_layer.children[0].cache.render = <Render a0642a0 of None>)
```
```
While running game code:
  File "renpy/common/00action_file.rpy", line 415, in __call__
    renpy.save(fn, extra_info=save_name)
Exception: Can't pickle a Render. (perhaps renpy.game.log.log[125].stores['store']['mc_front_layer'].children[0].cache.render = <Render a42fe80 of None>)
```
I'm kinda assuming the Pickling error is related to the TypeError one above due to the fact that the latter error goes away once the scene is cleared and MC sprite isn't shown anymore? 

Anyway I don't know why it's only happening to some players and I'm kind of stumped on this. So I'm hoping someone here will have insight on how to: 
1. avoid saving the unpickleable SpriteManager() render — maybe I'm not using SpriteManager() mixed with LayeredImage the right way? if there's a different method that I can put a SpriteManager() object into a LayeredImage, please let me know 
2. if I'm not supposed to use SpriteManager() with LayeredImage, is there another way to improve performance for showing a large amount of shader-colored DynamicDisplayable images as part of a LayeredImage sprite at once? 

Thank you!

**Comment by renpytom** [comment]
I just made a fix to SpriteManager. 

That being said, you probably want to use "[mc_back_layer]" instead of a DynamicDisplayable.

**Comment by renpytom** [comment]
Actually no, never mind - that wouldn't work. Dynamic displayables are okayish here - but creating a new composite isn't. You want to store the image in a variable, including the Composite, rather than returning a new Composite every time. If you do that, Ren'Py should be able to use the render cache to make everything faster.
