### ISSUE TITLE
how to make a minigame?

### ISSUE THREAD

**Issue by farzher** [renpy/renpy#5941]
i came up with this SpriteManager loop, which works great, except it doesn't support rotation or anything, which is now a problem.

```rpy
label start:
  call minigame_loop
  
label minigame_loop:
  show expression game_manager # i don't know why this is "show expression", but it works to render the minigame
  while minigame_result == 0:
        $ renpy.pause(0)
  return

init python:
  bullet_image = Image("bullet.png")
  game_manager = SpriteManager(update=minigame_update)

  def minigame_update(st):
    bullet = game_manager.create(bullet_image) # create a countless amount of sprites, great!
    bullet.x += 1 # update gamestate
    if bullet.x > 1000: bullet.destroy() # destroy a sprite
    return 0

  def minigameover(): # cleanup the game, before returning back to the normal renpy script 
    game_manager.destroy_all()
    renpy.hide('game_manager')
```

what's the proper way to do a minigame loop so that i have the ability to rotate / tint / etc (apply transforms to) my sprites?

**Comment by Andykl** [comment]
Hi, this issue tracker is mostly intended to file bug reports and ask for Ren'Py enchancements, and lemmasoft forum and Ren'Py discord server is better suited for asking for help.

Those said, I think you want to create an ATL transform with needed properties and apply it to your bullet_image and add that transform to sprite manager, however this can tank the performance if there are a lot of particles, so probably you want to do it programatically.

**Comment by farzher** [comment]
i think this is what i was looking for! https://www.renpy.org/doc/html/cdd.html
i didn't realize minigames were covered at all in the documentation
