### ISSUE TITLE
Live2D fade glitches out most of the time

### ISSUE THREAD

**Issue by farzher** [renpy/renpy#5946]
is this a known issue? i have seen tutorials telling me to just disable fade using `default_fade=0.0`, so i assume they're having the same problem? but the fade looks so good when it works!

https://github.com/user-attachments/assets/01803cec-0139-46cc-af27-6a62232b0cda

is there anything i can do to make it twitch less?

**Comment by renpytom** [comment]
I don't have a great sense of what you expect versus what's happening here. I think we did implement it according to the spec.

**Comment by farzher** [comment]
> I don't have a great sense of what you expect versus what's happening here. I think we did implement it according to the spec.

really? it looks totally busted. glitching / twitching / t-posing into the wrong animation state for a few frames.

at 13 seconds it fades between animations perfectly, as expected for a while.

at 28 seconds, it looks like it jumps to the end of the next animation for a few frames, then goes back and fades correctly.
this happens most of the time, jumping into the wrong part of the animation, then jumping back.

also her arm teleports around a lot, which i would expect to never happen. and if i'm lucky, i can get through a few animations in a row with no teleports.

**Comment by farzher** [comment]
another example of the face / eyes glitching out for a few frames most of the time when i switch expressions.


https://github.com/user-attachments/assets/b3f3b7eb-6ce4-4d77-8fd9-273a781711c5

**Comment by farzher** [comment]
can you point me to the relevant code in renpy that runs these animation fades? i can take a peak for bugs

**Comment by renpytom** [comment]
renpy/gl2/live2d.py

**Comment by farzher** [comment]
the issues only happen when `seamless=True`

and `default_fade=0.4` or lower seems to have significantly less issues.
i'd prefer to have a longer fade time, but `default_fade=0.4` is working well enough for me for now
