### ISSUE TITLE
Quick menu should have style for hbox

### ISSUE THREAD

**Issue by AVN-Snax** [renpy/renpy#5948]
Right now, the quick menu in `screens.rpy` has hard-coded `xalign` and `yalign` values. These should really be part of a `quick_hbox` style so as to be more readily modified, imho.

**Comment by AVN-Snax** [comment]
The issue is not my knowing how to accomplish the task. You have to modify the `quick_menu` screen code to make any positional changes to it. If there were a default style, the style could just be added/replaced in a user's code instead of having to modify the `screens.rpy` file itself to do it. I started to tell someone that on reddit only to discover that it's hard-coded.

Seriously, we're talking about a couple of lines of code, and it ought to be done if for no better reason than to make the whole styles system consistent amongst the default screens that Ren'Py supplies in new projects.

**Comment by danac78** [comment]
@the66F95 Not sure what you are referring to? If you do style quick_hbox, it would be under the prefix of quick. And the commit that Tom made was exactly that.

**Comment by the66F95** [comment]
not really, he was adding a new style `quick_menu` exclusively for the hbox.
