### ISSUE TITLE
gui7 problem on Ubuntu install

### ISSUE THREAD

**Issue by lordmatt** [renpy/renpy#5949]
I tried installing Renpy on Ubuntu and saw the following warning:

```
Preparing to unpack .../renpy_8.1.3+dfsg-1build2_all.deb ...
Unpacking renpy (8.1.3+dfsg-1build2) over (8.1.3+dfsg-1build2) ...
Setting up renpy (8.1.3+dfsg-1build2) ...
/usr/share/games/renpy/launcher/game/gui7/code.py:170: SyntaxWarning: invalid escape sequence '\s'
  m = re.match('^(\s*)define (.*?) =', l)
```

While Renpy launches it throws an error about being unable to find gui7.

![image](https://github.com/user-attachments/assets/00cd549a-194e-49e3-bc25-41026dff2a56)

After searching and trying a bunch of apt-get commands, I'm completely stuck. Is this something I might be able to fix?

**Comment by qTich** [comment]
Do not use builds from the package manager.

Use official - https://www.renpy.org/

**Comment by renpytom** [comment]
Yes, please go through their support process for issues that aren't present in the downloads from renpy.org.

**Comment by lordmatt** [comment]
Thanks. I filed a report with the maintainer. I did try the direct download but I think I am just getting old. I couldn't figure out what to do with the files after unpacking them which is why I used the package manager version. I'd love to know what actually broke and how to fix it but I guess I'll just wait for a patch or something.
