### ISSUE TITLE
How do I use this tar ball thing once I've unpacked it?

### ISSUE THREAD

**Issue by lordmatt** [renpy/renpy#5951]
As per my last report, the .deb is broken and does not deliver a working version of Renpy.

Forgive me getting old and slow but is there some guise somewhere for actually setting Renpy up on Linux? I've got the files I just don't know what to do with them. I assume the .exe is a windows file and the .sh is a script but it just opens in a text editor.

Is there a guide for old geezers who are starting to feel left behind by technology?

**Comment by qTich** [comment]
I think it should help - https://www.renpy.org/doc/html/quickstart.html#quickstart
