### ISSUE TITLE
When a displayable does a transition between images using ATL, it does a short jump to the 'from' image's position before settling on right location for 'to' image

### ISSUE THREAD

**Issue by NaughtyRoad** [renpy/renpy#5954]
When switching between two images using ATL, there is a a short jump to the 'from' image's position before settling on right position for the 'to' image given the displayable's alignment, when a transform is used. This doesn't really show unless they are of a different size, and it's quite short, but long enough to be very noticeable. 

That sounds super vague, but the following code should help explain/demonstrate. It's assuming the screen size of the ren'py project is 1920x1080. The used images are attached below.

```
    scene eileen happy1920w:
        xalign 0.8
    with dissolve
    "I'm actually 1920 pixels wide, but x-aligned to the right, so for now I'm centered and take up the whole screen."

    show eileen happy479w
    with dissolve
    "Now I switched to a less-wide image. I didn't jump left first, but went straight to x-alignment 0.8."

    scene eileen happy1920w:
        xalign 0.8
    with dissolve
    "Scene reset back to 1920 wide but secretly still centered right."

    show eileen happy1920w:
        2.0
        "eileen happy479w" with dissolve
    with dissolve
    "Now I'll switch to a less-wide image in ATL after 2 secs."
    "I showed at the wide image's starting position on the left before properly x-aligning to the right."
    "Note, I didn't use to do that in renpy 8.1.1. I do in renpy 8.3.2 and 8.3.3 though."

    show eileen happy1920w:
        2.0
        "eileen happy479w" 
    with dissolve
    "Additional test: switch to less-wide image in ATL, but not using the 'dissolve' transition."
    "Now I don't jump from left to right, but correctly align straight away."

    show eileen happy1920w:
        2.0
        "eileen happy479w" with fade
    with dissolve
    "Additional test: switch in ATL, using 'fade'. I jump from left to right again."
    "So it's the transition that makes me jump, if I am displayed using ATL blocks..."
    "..but not when using a 'show' statement with the 'with dissolve' statement on the line below."

```

This behavior is recent-ish, it is not present in Ren'py 8.1.1, where the to image will immediately start at the right position given the alignment of the displayable. But it is present in 8.3.2 and 8.3.3. 

images used:
[eileen happy479w.png](https://github.com/user-attachments/assets/90125430-df22-4edc-8fc5-c016e31f7cb9)
[eileen happy1920w.png](https://github.com/user-attachments/assets/f4ba0d9e-496f-446b-aecd-52abc738968e)

Sorry, you'll have to manually rename them as github's attachments don't seem to remember the name.

**Comment by NaughtyRoad** [comment]
I'm aware that when images of two sizes are involved, there's always gonna be some weirdness. in 8.1.1's behavior, it'd crop the 'from' image to the size of the 'to' image, which is not ideal either. 

I'm guessing (like, really just taking a blind stab here) that in the new behavior, if it was intentional, is preventing that from happening. Maybe (another stab) by resizing both images to the larger one for the duration of the transition so no cropping takes place? If so, maybe by placing the smaller image where it'll end up being placed once the transition ends can prevent this behavior? Note, all this last bit wild speculation so feel free to ignore it completely. :)

**Comment by renpytom** [comment]
This is the change in https://github.com/renpy/renpy/pull/4717 . 

I don't think there's a satisfying resolution of this - the way Ren'Py works, the final position can't be computed until the size of the Dissolve is known, at which point it's too late to change the contents of the Disslove. 

So, my first response is "don't do that", but I could add a compat variable around https://github.com/renpy/renpy/pull/4717 to let you pick the old behavior. Fundamentally, don't dissolve between images of different sizes - it doesn't make sense.
