### ISSUE TITLE
8.3.4 Nightly fix bug: animation happens twice when a enumerate parameter is used

### ISSUE THREAD

**Issue by ewolf201** [renpy/renpy#5956]
```transform enter(p=0.0):
    subpixel True
    xcenter 0.5
    matrixcolor SaturationMatrix(0.25) * OpacityMatrix(0.0)
    pause p
    easein .5 matrixcolor SaturationMatrix(0.25) * OpacityMatrix(1.0)
```

I'm not good with words, but during some testing I found a bug where the first menu choice blinks twice before the animation resumes. When I'm not using a atl parameter, the bug doesn't occur. 

![atlbug](https://github.com/user-attachments/assets/9ee3e88b-3f8c-457c-a92e-e0c5f8affab7)

maybe you can gleam where I'm coming from as the bug's a little hard to describe on my end.  I'll fill you in as I test this in other projects to see if it's simply the shaders I'm using or the atl itself. 

edit: It might have something to do with the template I'm using as the normal renpy gui hasn't given me any issues in terms of weird atl glitches.

**Comment by renpytom** [comment]
Can you please post a short example game?

**Comment by ewolf201** [comment]
Sure thing (the file was too big so I posted all three versions on google drive):

https://drive.google.com/file/d/1vKiHhnhVPRcAF_f98zCb3PUqa3fCgAM9/view?usp=drive_link

https://drive.google.com/file/d/1Frt09bRdiwNJmcCMYH7SXDcNmV2uyDWN/view?usp=drive_link

https://drive.google.com/file/d/1sazHX8fl-HgyUgSYb5R9CJzIQJtpXWE6/view?usp=drive_link

**Comment by renpytom** [comment]
Can you please grant access to renpytom@gmail.com ?

**Comment by ewolf201** [comment]
> Can you please grant access to [renpytom@gmail.com](mailto:renpytom@gmail.com) ?

I think you can access them now

**Comment by renpytom** [comment]
I believe this has been fixed in the 11-30 nightly release.
