### ISSUE TITLE
Better documentation for transitions using python syntax

### ISSUE THREAD

**Issue by TakodaS** [renpy/renpy#5958]
The documentation contains this cryptic statement (emphasis mine): 

> Transitions can be used as part of the [with statement](https://www.renpy.org/doc/html/displaying_images.html#with-statement), as well as in other parts of Ren'Py, to apply effects to changes in the scene **(or sometimes to turn a displayable into another)**.

I have not not seen any examples of this online so I went ahead and implemented it myself:
```renpy
init python:
    transition = Pixellate(2,10,old_widget = Image("img1.jpg"), new_widget = Image("img2.jpg"))

screen Test:
    frame:
        background "#00ffffff"
        add transition() # note the function call here because Pixellate is exposed curried to the user!

label start:
    call screen Test
    return 
```
The documentation includes the following section
> Applying transforms to displayables in Python

And I think there should be an equivalent section
> Applying transitions to displayables in Python

I see many use cases for this in animating objects in minigames etc. What do you think?

**Comment by TakodaS** [comment]
Pray tell, why is this bad style? What is the preferred way? If I were to create the same effect through my own displayable, would i not be reinventing the transition's render method?

**Comment by renpytom** [comment]
You can either use the transition through ATL, or through renpy.with_statement or renpy.transition. Those are how a transition is expected to be used, not directly.

**Comment by TakodaS** [comment]
I am guessing the answer to "Why is this bad style?" is because renpy gives you everything you need to create custom transitions using Transform Properties in the event loop. The python logic is far easier to follow this way than using renpy's transitions in python.
