### ISSUE TITLE
Text Input function for Screens disables left and right controls

### ISSUE THREAD

**Issue by Charmareian** [renpy/renpy#5959]
I'm creating an on-screen-keyboard for controller users. 

I want to combine this with Renpy's screen text input for a smooth renaming screen that works for gamepad and keyboard users alike. I have this on my on-screen-keyboard screen:

input:
            xalign 0.5 yalign 0.25
            length 12
            value VariableInputValue("keyboard_input")

However, because of this addition, I can no longer move left or right on my on-screen-keyboard. This is because the text input functionality allowing you to go left and right to cleanly remove text without having to backspace all of the way. 

https://github.com/user-attachments/assets/66feea7a-f90d-4184-bdcc-3761e7a51725

I think a solution to this would be giving the user the option to disable these input controls. Though maybe there's a simple solution to this that doesn't require new functionality?

**Comment by mal** [comment]
You can do something like this to manage the enabling/disabling of inputs:

```rpy
# quick untested borderline pseudo code

# You may wish to set default to True here if you already know a keyboard is being used.
default inputval = VariableInputValue("keyboard_input", default=False)

input:
    xalign 0.5 yalign 0.25
    length 12
    value inputval

textbutton 'Use Keyboard':
    action inputval.Enable()
textbutton 'Use Gamepad':
    action inputval.Disable()
textbutton 'Toogle to the other input':
    action inputval.Toggle()
```

Relevant docs page: https://www.renpy.org/doc/html/screen_python.html#inputvalue

**Comment by renpytom** [comment]
I think it's reasonable to have an arrowkeys toggle for input.

**Comment by Charmareian** [comment]
> You can do something like this to manage the enabling/disabling of inputs:
> 
> ```python
> # quick untested borderline pseudo code
> 
> # You may wish to set default to True here if you already know a keyboard is being used.
> default inputval = VariableInputValue("keyboard_input", default=False)
> 
> input:
>     xalign 0.5 yalign 0.25
>     length 12
>     value inputval
> 
> textbutton 'Use Keyboard':
>     action inputval.Enable()
> textbutton 'Use Gamepad':
>     action inputval.Disable()
> textbutton 'Toogle to the other input':
>     action inputval.Toggle()
> ```
> 
> Relevant docs page: https://www.renpy.org/doc/html/screen_python.html#inputvalue

My idea was to avoid needing a button to toggle between modes. I'd like both users to immediately be able to start naming things

**Comment by Charmareian** [comment]
> I think it's reasonable to have an arrowkeys toggle for input.

Yeah, I think a new setting for Input would be ideal
