### ISSUE TITLE
enhancement of `is_seen_allowed`

### ISSUE THREAD

**Issue by qTich** [renpy/renpy#5961]
It would be good to extend the `is_seen_allowed` capabilities to allow for more control.

For example, through a callback option:
```py
def test_seen_should_be_allowed_callback(identifier):
    return identifier == "ever"

def is_seen_allowed(identifier: Literal["audio", "image", "translate", "ever"]):
    If renpy.config.seen_should_be_allowed_callback is not None:
        return renpy.config.seen_should_be_allowed_callback(identifier)

    return not (renpy.store._in_replay and renpy.config.no_replay_seen)
```

For example `_seen_translates` acts as a counter and bloats the size of `persistent`.
`_seen_audio` and `_seen_images` are also not used by default.
The `_seen_ever` in turn is at least used when skipping text.

Of course, I take into account large games where the number of nodes is essential.

Also, if I understand correctly, since `.rpyc` can be regenerated,
the identifier of a node changes and, conventionally,
the same node can be written again in `_seen_ever`.

**Comment by renpytom** [comment]
> It would be good to extend the is_seen_allowed capabilities to allow for more control.

I don't get from this what sort of control you'd like.

The identifier of a node should be stable, assuming that .rpy discipline is followed correctly. (That is, you're providing the .rpyc files so that Ren'Py can assign the same names to the same nodes.)

**Comment by renpytom** [comment]
Do you have an example of this actually being a problem, or is this entirely hypothetical?

**Comment by qTich** [comment]
Regarding the first one, I had something similar to this - #5965,
but not quite sure if it's a good implementation.

Regarding `_seen_ever`, I've looked at the diff of the contents
of `renpy.game.script.namemap` of several versions and indeed - there is no such problem.

**Comment by renpytom** [comment]
I still don't get the motivation for the callback - it seems like a solution in search of a problem.

**Comment by qTich** [comment]
I don't like the mere presence of data that isn't being used.

`is_seen_allowed`, may help, but it affects globally.
Again - only `_seen_ever` is used by default.

I just simulated the situation:
```py
# 432.1kB - all data:
renpy.game.persistent._seen_audio = {
    str(v): True for k, v in audio.__dict__.items()
    if k does not startswith("__")}  # namespace with audio
renpy.game.persistent._seen_translates = set(renpy.game.script.translator.default_translates)
renpy.game.persistent._seen_images = {i: True for i renpy.display.image.images}
renpy.game.persistent._seen_ever = {
    i: True for i in renpy.game.script.namemap}  # omit that not all nodes are used
# 430.1kB - without `_seen_audio`
# 200.7kB - without `_seen_translates`
# 180.1kB - without `_seen_images`
# 4.0kB - without `_seen_ever`
```

In summary, the main part is taken up by `_seen_translates` which cannot even be affected by `is_seen_allowed`.
Of course, it is possible to clear fields from `persistent` at save time via a hook.

**Comment by renpytom** [comment]
I still don't see a good reason for this, as we're saving under a megabyte of space. That's not a ton, especially  because having the information there makes various functions available in future releases of the game. 

How big is the game you're testing with?

**Comment by qTich** [comment]
> How big is the game you're testing with?

If you want to draw a parallel between file size and game size, I'll say it again -
`I don't like the mere presence of data that isn't being used.`.

My concern was that not all data is important to me,
but I can't selectively control it, or delete it at the time of saving.
