### ISSUE TITLE
Callbacks for transforms / interpolations

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5963]
It would be very useful to be able to set callbacks for when transforms are set / interpolated, similar to `config.statement_callbacks` or `config.periodic_callbacks`. 

Essentially I want to be able to intercept a transform (actually interpolations would be more ideal, since even instant transforms appear to be "interpolations" with a duration of 0), and be able to know the current transform, the new transform, and the duration of the interpolation (and maybe the warper?). Possibly even being able to return an altered New Transform, ideally.

Use case: Automation (especially if ATL parameters are extended, as mentioned in #5957)
I currently have a lot of functions that automate little effects through out my VN (using a CDS, currently). 
- When a character moves more than X distance in X amount of time, a sound is played (clothing sound, armor clink, etc)
- When a character head turns (using live 2D Parameters) more than X distance in X amount of time, the function that triggers a "blink" on the sprite is run.
- Animating other parameters under certain conditions (depending on where other values are at, other toggles, etc).

I don't think this is a feature that Everyone will use, which is why it'd be best to just adding in a simple callback instead of something more comprehensive, so the functionality is there for advanced users, without having to modify the base engine to work with these values.

**Comment by renpytom** [comment]
I don't think this is likely to be a good idea, because Ren'Py is going to be doing some of this behind the scenes, as part of the prediction system. 

I'd suggest that you flip things around - instead of expecting to intercept the transform, have something (could be your own transform, or something else) that applies the transform, and also plays the sound.

**Comment by colinharvie** [comment]
Could this work with a CDS that takes an ATL block, without screwing with things? Instead of a callback, it's modified when the statement is parsed to include whatever additional effects are desired?

**Comment by renpytom** [comment]
I'd think you could do it that way. You'd have the ATL block, and you could also do whatever else you'd like as part of the process of showing the displayable.
