### ISSUE TITLE
Get current "velocity" or "speed" of Transform properties

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5964]
Having property "speed" or "velocity" (the delta from previous update) available for Transforms (with an ongoing interpolation) would be very useful for eventually implementing Physics (for Live2D Parameters, or other displayables) or other automating other effects (faux motion blur, speed lines, etc) based on how fast certain properties are changing.

Alternatively, the ability to get the property from the previous update + elapsed time (then we can calculate our own current speed) would work as well. 

This would probably mostly be used in be used `render` or `update` methods, or possibly with `function` in child `Transforms` or in `parallel` blocks.

**Comment by renpytom** [comment]
This isn't likely to happen either, for the same reason as #5963  - you're expected to know what's going on with what your game chooses to display. (This also isn't possible with how Ren'Py renders things - Ren'Py only determines the actual location of a displayable after it's done processing the Transform.)
