### ISSUE TITLE
(Help! The tutorial won't open in the new renpy version!)救命!教程在新renpy版本里打不开了!

### ISSUE THREAD

**Issue by gkkgll** [renpy/renpy#5966]
无论是11月30号的每夜修复版还是每夜版都会有这种问题!我不确定是否是我电脑或者是编辑器的原因,但我只更新了renpy就变成这样，我怀疑是更新的原因，请快点帮忙解决!
Neither the nightly fix version on November 30th nor the nightly version is correct! I'm not sure if it's due to my computer or the editor, but it became like this after I only updated Ren'Py. I suspect it's because of the update, please help resolve it! quickly!

**Comment by danac78** [comment]
Is there a log.txt or traceback.txt? You will find it in the base folder of the Tutorial. :) This would give information as to why it is not opening.

**Comment by renpytom** [comment]
I just tried with the December 1st nightly, and I was able to download Ren'Py, run it, download Visual Studio Code, and run that. 

Please reboot your computer, in case it's gotten into some sort of weird state. 

Beyond that, please post log.txt or traceback.txt files.

**Comment by Noriverwater** [comment]
I had the same issue.

[traceback.txt](https://github.com/user-attachments/files/17969225/traceback.txt)
