### ISSUE TITLE
Doc Request - Provide example of group="" on Movie()

### ISSUE THREAD

**Issue by ShaneCourtrille** [renpy/renpy#5967]
It would be helpful if there was a code example for the group="" property showing how to play two movies in a row using the group attribute. If you just show them at the same time then you only see the last one. Are we supposed to use pause based on the time of the first movie?

**Comment by renpytom** [comment]
That's not really what group is for - it's there to stop the flash of blankness when going from one movie of the same character to another. 

You can do this using the play_callback argument to Movie to first play one movie, then queue the looping animation.
