### ISSUE TITLE
Possible bug/regression: Added images and the like don't accept transform events

### ISSUE THREAD

**Issue by ewolf201** [renpy/renpy#5971]
while testing out some CDD code, any image or similar that uses the "add" function no longer accepts transform events. They accept transforms, but not show/hide or idle/hover effects (as an example, there could be more). I'm not sure if it's intentional as a means to fix another bug but it would be nice if you looked into it. 

https://drive.google.com/file/d/1OAIgrE5NpGgXQbogTLTad4J7htjrvB-7/view?usp=sharing

edit: show and hide do work, it's just idle and hover that doesn't.

**Comment by renpytom** [comment]
Any reason for the close?
