### ISSUE TITLE
It's impossible to properly set a style_prefix to the say screen as it always uses what_style and who_style

### ISSUE THREAD

**Issue by Galo223344** [renpy/renpy#5973]
At one point in the story of my game, it becomes "trippy" and I want the UI to change, so I wanted to use two different style prefixes for my say screen that is determined by a variable changed by the game script. However I soon realized that it was impossible to change the style of the what and the who since they always use the default say_dialogue and say_label (and say_window, but in my case I didn't change that). Upon further inspection I discovered that this is caused because by default all characters are based on the adv character, and that character has set by default who_style='say_label',  what_style='say_dialogue', window_style='say_window'. I tried setting what_style to None in my characters to see if that gave style control back to the screen but it only resulted in a crash.

Please either fix the character styles being forced upon the screen or remove the say_prefix from the default say screen and add a comment about it on the documentation since it's deceptive.

**Comment by renpytom** [comment]
I've removed the style_prefix from everything, though I don't see a reason to change the documentation, as I don't see documenting something that doesn't exist.

**Comment by Galo223344** [comment]
You should add a comment about it on the special say screen page so that people don't waste time trying to force the style prefix like I did
