### ISSUE TITLE
Itch.io Butler reports "no savings" for Linux builds

### ISSUE THREAD

**Issue by kigyo** [renpy/renpy#5974]
I make use of the Itch.io Butler to distribute my games and always create a separate Windows, MacOS, and Linux build.

While the Windows and MacOS builds work fine and only take around 20 seconds per update, the Linux build is always reuploaded in full and reports that it couldn't make any file savings. It takes around 5 minutes longer to upload than the other builds as a result.

Is it possible to avoid/improve this somehow?

**Comment by renpytom** [comment]
My guess is "probably not". 

Windows and MacOS use a .zip format, which compresses file-by-file, which butler handles. Linux uses .tar.bz2, which butler doesn't handle, and so it uploads the whole thing. To fix this, we'd need to ship .zip files for  Linux, which isn't really something I think is a good idea.

**Comment by kigyo** [comment]
Good to know, thank you! I submitted this directly to itch.io support instead.
