### ISSUE TITLE
Butler in Renpy error

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#5975]
`Version check failed: Get "https://broth.itch.ovh/butler/windows-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host`

Not sure if that is me or Renpy but have been getting that message the last few days. It still uploads regardless.

**Comment by mal** [comment]
Fixed by https://github.com/renpy/renpy/commit/6470a37b40f9e7763b938652fa6ef003e6b09431.
