### ISSUE TITLE
Triple quotes with translation identifier

### ISSUE THREAD

**Issue by lauwurence** [renpy/renpy#5980]
Hello🫡 When using triple quotes, if there is an empty string, then it is impossible to assign an ID to the dialog. 

```renpy
label start:
    mc """Line 1

Line 3""" id translation_identifier
```
```
File "game/script.rpy", line 2: Line with id translation_identifier appears twice. The other line is game/script.rpy:2
```
If I delete the second line, the exception does not appear.

Ren'Py 8.4.0.24120404+nightly

**Comment by Andykl** [comment]
That happens because RenPy treats it as if yuo write
```
label start:
    mc "Line 1" id translation_identifier
    mc "Line 3"  id translation_identifier
```
aka. monologue string.
I don't know what the correct solution for that is. We could assign `translation_identifier_N` or made a better error message.

**Comment by lauwurence** [comment]
Oh right, thank you! I forgot that writing dialogues is different from writing python strings. 

https://www.renpy.org/doc/html/dialogue.html#monologue-mode
Adding `rpy monologue none` makes it work for me, but yeah, the error message was a little bit confusing.
