### ISSUE TITLE
ATL: if shader property is set, set mesh to True

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5988]
The `mesh` property should automatically be set to `True` if there's valid value on the `shader` property.
This would remove the need to always add `mesh True` to the transform or show statement when using shaders.

Unless there is some reason to have the `shader` property set while `mesh` is not set to `True`?

**Comment by renpytom** [comment]
There are many uses of shaders that don't require new geometry - for example, a color matrix shader. I'd say most shaders don't need new geometry.
