### ISSUE TITLE
Unable to Delete rpu because an rpa is in use

### ISSUE THREAD

**Issue by danac78** [renpy/renpy#5989]
Getting an error where it is unable to delete my ui.rpa because it is in use. As far as I am aware, nothing in the RPA is in the updater screen. The only thing I can think it is colliding with is the main menu. My question is: would there be a way (since it has to restart) for it to do the restart upon init before RPAs are loaded?

**Comment by renpytom** [comment]
Can you please post the actual error message? It will be in use, but the updater should be able to handle updating files that are in use.

**Comment by danac78** [comment]
[log.txt](https://github.com/user-attachments/files/18046011/log.txt)

Here is the log file from the update in the game test I have my system to make sure updates work and what not outside the SDK.

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\FOLGame\\base\\game/ui.rpa' -> 'E:\\FOLGame\\base\\update\\deleted\\ui.rpa.delete.1.rpu'

**Comment by renpytom** [comment]
Hm... could you have two copies of the game open? This error shouldn't be possible with only one copy of the game open. 

Apart from that,  can you post the test game so I can try it? If you share on google drive, my account is renpytom@gmail.com.

**Comment by danac78** [comment]
Ok, let me try it without the one from the launcher running.

**Comment by danac78** [comment]
Uploading a new update to see if it causes the same issue if I keep the dev version (ran by the launcher) closed and don't have any additional Pythonw in the process list.

**Comment by danac78** [comment]
Ok, apparently I had a copy of my game in the background or it was seeing the launcher version. It works as expected now.

**Comment by danac78** [comment]
@renpytom  Thanks for pointing me in the right direction to solve that one.

**Comment by renpytom** [comment]
Probably the former, because the launcher version shouldn't let you update it.
