### ISSUE TITLE
Question about `renpy.music.set_queue_empty_callback` behavior?

### ISSUE THREAD

**Issue by paranormalized-encryptid** [renpy/renpy#5992]
I was trying to figure out exactly when this callback fires and was surprised to see that it's called almost constantly, assumedly by the `periodic` method of the `Channel()` object.

My question is this: are there any circumstances (besides the queue not being empty) under which these periodic calls to the empty queue callback don't occur? They seem to continue even after I stop, pause, and mute the channel. This suits my purposes just fine, but I'm just wondering how reliable it is?

**Comment by renpytom** [comment]
So, the documentation is: 

> This callback is called when the queue first becomes empty, and at least once per interaction while the queue is empty.

That means it can be called more than once per interaction (and it is, currently), but might not be. Generally, all the ways to stop, pause, and mute trigger interaction restarts, but you can always call renpy.restart_interaction() yourself.

**Comment by paranormalized-encryptid** [comment]
Hmm. I'm looking for a way to automatically check when the channel has both emptied its queue _and_ finished playing. My initial thought was to use a periodic callback to check the latter condition. Maybe that would be better after all?

**Comment by renpytom** [comment]
That's a reasonable way of doing it. Queue empty callback is about the queue, not what's playing - the idea is dynamic soundtracks.

**Comment by paranormalized-encryptid** [comment]
Yeah, that's what I thought. Thanks for the advice.
