### ISSUE TITLE
ATL does not respect adjust_attributes function

### ISSUE THREAD

**Issue by harjup** [renpy/renpy#5996]
[In the documentation](https://www.renpy.org/doc/html/layeredimage.html#selecting-attributes-to-display), this example is provided for using the `adjust_attributes` function to change the look of a sprite based on global state:
```
layeredimage eileen:
    attribute base default
    group outfit auto
    group ribbon prefix "ribbon":
        attribute red
        attribute blue

default eileen_ribbon_color = "red"

init python:
    def eileen_adjuster(names):
        atts = set(names[1:])
        if "ribbon" in atts:
            atts.remove("ribbon")
            atts.add("ribbon_" + eileen_ribbon_color)
        return names[0], *atts

define config.adjust_attributes["eileen"] = eileen_adjuster
```

This example works for me and renders `elieen ribbon_red` if I use a `show` statement:
```
show elieen ribbon
```

However, if I were to adjust this sprite's attributes within an ATL block, the `eileen_adjuster` will not get run:
```
show elieen:
    ease 1.0 xcenter .5
    "elieen ribbon"
```
So in this example, instead of getting an expected output of `eileen ribbon_red`, you'd just get `elieen ribbon` without any of those transformations being applied.

Ideally, ATL would still run the same adjustment function so the behavior is consistent.

**Comment by Gouvernathor** [comment]
The ATL transform you're writing erases the child of the image you actually want to show, and adjust_attributes, as the name implies, adjusts the attributes of an image you're showing with the `show` statement. But when you write `"eileen ribbon"`, ATL takes the image as-is and doesn't add or remove attributes via adjust_attributes.
What you should do is to use a transform that doesn't replace its child:
```rpy
show eileen ribbon:
    ease 1.0 xcenter .5
```

**Comment by harjup** [comment]
That statement isn't equivalent to my example. For this statement,
```
show elieen:
    xcenter .2
    ease 1.0 xcenter .5
    "elieen ribbon"
```
The following occurs:
1. elieen moves from `xcenter .2` to  `xcenter .5` over the course of 1 second
2. elieen puts on a ribbon

While for this statement,
```
show eileen ribbon:
    ease 1.0 xcenter .5
```
The following occurs:
1. elieen puts on a ribbon
2. elieen moves from `xcenter .2` to  `xcenter .5` for 1 second

Let's say the point of this animation is to show elieen walking to a dresser and putting on a ribbon, with a dynamic color based on  `eileen_ribbon_color`. If I were to use your solution, the ribbon would teleport onto her head before she reached the dresser!

Since I need to be able to change sprites in sync with ATL animations like moving to a certain point of the screen or shaking a few times before changing its properties, it makes the `adjust_attributes` unusable in certain cases and forces cludgy stuff like this:

```
if include_extra_attr:
    show char base_a:
        ease .1 yoffset 10
        ease .1 yoffset 0        
        "char base_a extra_attr"
else:
    show char base_a:
        ease .1 yoffset 10
        ease .1 yoffset 0        
        "char base_a"
```

**Comment by Gouvernathor** [comment]
In that case, you should include the changing of attributes in the script. For instance:
```rpy
show eileen:
    ease 1. xcenter .5
pause 1
show eileen ribbon
```
In any case, adjust_attributes is strongly tied, not to the image tag (= the first element of its name, "eileen" here) an image is _defined with_, but with the image tag it is _show with_. If you show `show eileen as noteileen`, eileen's adjust_attributes will not be called.
So, it's not compatible with displaying images without any show-tag, i.e included in screens or in ATL for instance.

**Comment by renpytom** [comment]
This kind of hinges on the definition of showing an image, as compared to referencing it. The show statement shows an image, which involves combining the attributes the image was previously shown with to come up with a new set of attributes, then adjusting that set of attributes, and storing it. 

One that's done, there's an image name which can be referenced. By contrast, ATL only references images by name, and doesn't do any of the other things associated with showing an image. So I think it makes sense that config.adjust_attributes is not being run. 

There is a very similar thing, the attribute_function of layered images, which is probably what you want here - it takes a set  of attributes, and then returns a set. 

But that being said, the easiest way to do this is probably just to use a dynamic image: 

```renpy
layeredimage eileen:
    attribute base default
    group outfit auto
    attribute ribbon "ribbon_[eileen_ribbon_color]"
```

And not mess with it adjusting attributes at all.
