### ISSUE TITLE
Allow for different distribution folder and zip names

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#5999]
I'd like all distributions of my game to be in the same folder, but at the moment there doesn't seem to be a way to do this given renpy's build options. If you leave `build.directory_name` empty, it will create a directory called `{build.name}-{config.version}-dists`, and a zip inside it named `{build.name}-{config.version}-{operating system}`. When you bump version, it's going to make a *new* build directory when you build it next time, because the version number changed. If you set a `build.directory_name` yourself, it's either going to produce the same result, or if you don't include version information, then it's just going to overwrite the old build. This is a bit cumbersome, and spreads builds out into multiple folders unnecessarily (or deletes old builds). I want to be able to tell renpy what the distributions folder name is, and what the zip name is, separately, such that it may reuse the same distributions folder for every (different-version-suffixed) build of my game. 

Honestly I think this should be the default behavior, but at the very least I'd like the option to make it work this way.

**Comment by renpytom** [comment]
This already exists, as the build.destination variable: 

https://www.renpy.org/doc/html/build.html#var-build.destination

**Comment by Kuroonehalf** [comment]
Ah. I did not expect such a variable to be documented in a different place in the documentation page. My bad.
