### ISSUE TITLE
Mouse coordinates passed into displayables embedded in text are incorrect.

### ISSUE THREAD

**Issue by CharlieMcVicker** [renpy/renpy#6013]
## Device info
I am on MacOS (14.3.1), with an arm/apple silicon processor. 

## Bug description
Hi y'all,

New renpy user here 👋. I am trying to make a displayable which is blacked out (ie. `fill((0,0,0,255))`) unless the users cursor is on top of it. I hope to use this for optional in-line translations that don't break immersion for language learning games. I'm struggling to detect when the cursor is inside a rendered displayable because of the values I'm receiving for mouse x/y.

According to the Ren'py docs, the `x` and `y` arguments passed into the `Displayable.event` function should be relative to the upper-left corner of the displayable:
> **x, y**
>      The x and y coordinates of the event, relative to the upper-left corner of the displayable. These should be used in preference to position information found in the pygame event objects.
> https://www.renpy.org/doc/html/cdd.html#renpy.Displayable.event

In my testing, this seems to only be the case when the displayble is the only thing being rendered in the dialog box. If the displayable is at the end of a line, the `x` coordinate will not be `0` at the left edge. If the displayable is on the second line or lower, `y` will not have `0` at the top of the displayable.

Here is a clip of the bug:
1. On the first line, the mouse is at `(0,0)` when at the top-left of the displayable, as docs suggest
2. On the second, the `x` coordinate is not `0` when the cursor is at the left edge of the rendered area
3. On the third, the `y` coordinate is not `0` when the cursor is on the top edge of the rendered area

https://github.com/user-attachments/assets/a9204b16-7092-4571-aad2-83b092e70a1a

## Code to reproduce
Here is minimal code that reproduces the issue (created from a stock renpy project): https://github.com/CharlieMcVicker/renpy-mouse-pos-bug

Or if you just want the `script.rpy` (the only file that is changed after making the project): https://github.com/CharlieMcVicker/renpy-mouse-pos-bug/blob/2fa1e7c9014fb434966b5397769bf9f34619a72e/game/script.rpy

## Expected behavior
The mouse position `(0,0)` will be the top-left corner of the rendered displayable, regardless where the displayable is rendered.

## Actual behavior
This is only true when the displayable is rendered by itself. When the displayable is not at the top-left of the dialog box, `(0,0)` is not at the upper-left corner of the displayable.

**Comment by renpytom** [comment]
This only occurs when the displayable is embedded in text, right?

**Comment by CharlieMcVicker** [comment]
> This only occurs when the displayable is embedded in text, right?

Those are the only contexts I have tested, just because they fit my use-case. I find that (0,0) isn't at the top of the whole text section either.
