### ISSUE TITLE
`style_prefix` does not cascade as expected

### ISSUE THREAD

**Issue by TakodaS** [renpy/renpy#6017]
```renpy
style main_menu_text:
    color "#f00"

style size:
    size 64

screen main_menu:
    style_prefix "main_menu"
    vbox:
        align (0.5,0.5)
        text "Text" 
        text "Text2" style "size"
        text "Text3" size 64
```
## Expected:
Three lines of red text, the second and third in a larger font size.

## Actual:
First line is red, second line is white with a larger font size, third line is red with a larger font size.

I would have expected both styles to apply to the second line of text since color and size are independent, as is the case with the third line. This makes it hard to define and apply custom styles to nested content.

Tested using renpy 8.3.4

**Comment by renpytom** [comment]
Ren'Py styles are single inheritance. So line 3 inherits from main_menu_text, and then overrides it. (In the same way main_menu_text inherits from text.)
