### ISSUE TITLE
Ultrawide monitors fullscreen mode crash

### ISSUE THREAD

**Issue by NaughtyRoad** [renpy/renpy#6021]
I couldn't find this one in issues, so opening a new ticket. 

I'm getting some reports from users that using full screen mode on startup on ultrawide monitors is causing renpy 8.3.3 games to stop working.

One user reported: 
_Log looks like it tried to launch at 1080p but im at 5120x1440p so my monitor crashed and wouldnt respond
Screen sizes: virtual=(1920, 1080) physical=(5120, 1440) drawable=(5120, 1440)
Maximum texture size: 5184x4096_

This issue's aggravated because I'd included `define config.default_fullscreen = True` in my latest release, and it means affected users that start the game for the first time have to recover from the unresponsive screen, set their monitor natively to 1920x1080, start the game, set it to Display-Window in preferences, then return their monitor settings to normal. 
My obvious fix for now it to roll out a version that removes "config.default_fullscreen = True" and have users that prefer full screen manually set that in their preferences, so I can mitigate, and it's not extremely urgent.
Wish I could test myself but I don't have a nice monitor like that. 

I assume that having `default_fullscreen` set to `True` is not a terribly common situation for most games (although probably not entirely unheard of either).
I've only had a couple of reports for several thousand grabs so far, so it doesn't seem a very widespread issue either from my point of view.

**Comment by renpytom** [comment]
I'll take a list at this, but can you gather log.txt files from the affected users? 

And when you say "unresponsive screen", is it the game that's unresponsive, or is something going wrong with the monitor itself, the gpu, etc?

**Comment by NaughtyRoad** [comment]
> I'll take a list at this, but can you gather log.txt files from the affected users?
> 
> And when you say "unresponsive screen", is it the game that's unresponsive, or is something going wrong with the monitor itself, the gpu, etc?

I got the attached log file and dxdiag from one of my users, and the following description:

[DxDiag.txt](https://github.com/user-attachments/files/18220199/DxDiag.txt)
[log.txt](https://github.com/user-attachments/files/18220200/log.txt)

_"Here's the log, I went to full screen and it worked as long as I started it in windowed mode but when I tried to launch with it set to full screen I saw the menu for a second and then I could hear the music but my screen was black, I had to alt f4 to close it and now my text and such on the desktop is blurred"_

So switching to full screen while in game: no black screen. Starting with full screen: black screen, and it's not resetting the display correctly after exit.

They found an interesting clue in their dxdiag. It has the monitor's current mode as 5120 x 1440 (32 bit) (240Hz) (it's [this one](https://www.samsung.com/us/computing/monitors/gaming/49-odyssey-oled-g95sc-dqhd-neo-quantum-processor-pro-0-03ms-240hz-curved-smart-gaming-monitor-ls49cg954snxza/), and that's correct). But dxdiag also thinks the native mode is 3840 x 1080(p) (119.999Hz) (so both lower framerate and resolution).

They figured it may have something to do with the 240Hz refresh rate, and when they locked it to 60Hz in their display settings, they had this result:
_"Renpy doesnt like high refresh rate. Still washes my monitor colors out when I exit but its not crashing now"_

So locking framerate alleviates the black screen when starting in full screen mode, but still leaves the display in a weird state upon exit.

Another use reported this:
_"One pet peev however is the game opening in fullscreen mode, which on exit or changing to window mode [messes] up my HDR in Windows 11 on my Nvidia Graphics card (every renpy game does this for me) meaning I have to cycle HDR from the windows display menu to get the screen displaying properly (not dark)."_

So they apparently have the same issue of the display settings not reverting back after exiting, but not the black screen. I've reached out to them for logs but not heard back yet.

**Comment by renpytom** [comment]
Can you ask them to delete <game>\lib\py3-windows-x86_64/nvdrs.dll , and see if that helps any? That makes and restores a single change in the Nvidia session, so disabling it might help. Though the setting doesn't have anything to do with monitor resolutions or color profiles, so I'm not expecting it to help. 

Has the user reached out to their monitor and gpu vendor yet?

**Comment by NaughtyRoad** [comment]
(@renpytom )
The user did not reach out to the monitor or GPU vender, they don't expect to get meaningful support on this issue from either Samsung or nVidia in this case. 

**With regards to removing the dll...**

...they reported:
"That somehow made it worse. My monitor totally lost signal but I could hear the music."

With regards to the after affect after closing the game:
"Still blurred. I had to cycle HDR [to get it back to normal]" 

On the subject of HDR, they also noted: 
"HDR if it only affects text outside of game isnt as much of an issue, it does darken the game significantly though"

Asking what was darker, they said:
"I think its mainly at the main menu"

I've not heard back from the other user.

**Some thoughts from my side.**
I imagine this is a hard issue to tackle without access to the hardware.

I haven't gotten any new reports, in about 10-20k grabs from the free version dl. mirrors I can monitor (which possibly means anything like several times to an order of magnitude higher for everything else out there combined, and that boggles the mind a bit). So it's likely not a very widespread issue (at least while HDR ultrawide monitors stay as rare as they are now). 

I also rolled the change out that removes `define config.default_fullscreen = True`, so I'm not expecting many more reports. Affected users probably feel having to cycle HDR isn't a biggie, or are content running in maximized windowed mode.

**Comment by renpytom** [comment]
> they don't expect to get meaningful support on this issue from either Samsung or nVidia in this case.

Thousands of bucks to Samsung and Nvidia... 

My feeling is this is unlikely to be an issue with Ren'Py, especially if removing nvdrs.dll doesn't fix it. Ren'Py uses the nvdrs API to disable threaded rendering system-wide when a Ren'Py game is active, as it was causing absurd lag. Everything else Ren'Py does is incredibly standard in terms of opening a fullscreen borderless window with an OpenGL context, and then filling it with OpenGL information. 

This feels like a bug in the GPU, Driver, Monitor, or some combination. Ren'Py might be triggering the bug, but fundamentally part of the mission of the drivers is to ensure that once a program like Ren'Py terminates, it stops affecting the user's system. If a program like Ren'Py can  cause persistent problems like this, it's at least to some extent an issue with the driver or lower levels. 

I'd be happy to work with Nvidia and Samsung to support them on this, but as it is I have no idea how anything Ren'Py is doing could cause this issue, so I don't know where to begin. I don't want to take the lead on this, as I've had nothing but frustration trying to get in touch with Nvidia, but if someone can open a case I'd be happy to participate. 

You can let them know the 'f' key toggles fullscreen, which might help them get out of other games that trigger this issue.

**Comment by NaughtyRoad** [comment]
I agree, it's very hard to diagnose the exact cause, and high likelyhood of driver/hardware issues.  And with easy ways to mitigate the issue, it probably doesn't warrant any further investigations at this point. Thanks for having a look.

**Comment by NaughtyRoad** [comment]
Had a report back from the second user I approached. It seems to be zooming in as HDR as the main culprit again. They report having experienced this issues on a few different monitor makes.

> Every Renpy game that launches in Full screen, when i reduce it down to Windowed mode or when I exit the game from Fullscreen mode, my screen gets darker ( game and desktop barely visable). The fix is to go into windows display settings and turn HDR off and then on again so the screen displays correctly.
> 
> It might be a me only problem or a problem with the resolution of the monitor. The main monitor is a 3440x1440 monitor (has been doing it with a couple of different manufacturers including asus, gigabyte, Samsung and Prism, all 3440x1440 widescreen) and the secondary is a 2560x1440 which is ok and doesnt go darker when switching between Full or window mode or exiting the game.
> 
> It also sometimes does it with Unity Games when switching from full screen to windowed mode, but doesnt do it if exiting from fullscreen to desktop.
> 
> I checked the log.txts from multiple renpy games that open in fullscreen and I cant see any obvious errors (most recent run of LOL below). Im not sure if it isnt something in the combo of Windows 11, the graphics card / driver and the screen resolution than Renpy doesnt like.
> 
> I have over 1000 Steam games (had yours wishlisted) and its only Renpy (and sometimes unity) that does it.

[renpy log.txt](https://github.com/user-attachments/files/18245482/renpy.log.txt)

And I also found a third report here: https://www.reddit.com/r/RenPy/comments/1e82sbj/fullscreen_hdr_support_in_windows/

This report suggest the culprit might be Windows, proposing that it turns of HDR partially for non HDR games running in full screen, but not toggling the setting in config. 

For anyone stumbling on this post looking for a solution, this may help make life easier:  [This report for a game of unknown origin](https://answers.microsoft.com/en-us/windows/forum/all/is-it-possible-to-make-hdr-exceptions-for-specific/18740a69-31de-4b9b-9e38-06a89e16c52d) has a response from Microsoft where they suggest using Win + Alt + B to manually toggle HDR on/off (it needs game bar enabled through).

**Comment by neyunse** [comment]
hey tom @renpytom can you try to update pygame or pygame-ce?


### Pygame: 2.6.1
SDL (2, 28, 4) Ok

### Pygame: 2.5.6 (CE)
SDL (2, 32, 10) Ok



### Pygame: 2.1.0 (renpy)
SDL: (2, 0, 20)  Not work

i think this issue and this other are related: #5258

I tested this simple code with recent versions of pygame and there doesn't seem to be a problem.
```py
import pygame
pygame.init()

info = pygame.display.Info()
screen_width, screen_height = info.current_w, info.current_h

screen = pygame.display.set_mode((screen_width, screen_height), pygame.FULLSCREEN) 

pygame.display.set_caption("HDR Friendly Pygame Window")

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    screen.fill((255, 255, 255))
    
 
    print("Pygame:", pygame.version.ver)
    print("SDL:", pygame.get_sdl_version())
    pygame.display.flip()


pygame.quit()
```

I wanted to try using version 2.1.0, but I'm having trouble installing it. However, I think it's because of the version of SDL and Pygame that Ren'Py uses.

Personally, I have a monitor with HDR support, and when I go full screen, the colors in the game change, and when I close the game, HDR is forced to turn off along with the brightness change in Windows (this is a Windows bug, but it's probably caused by SDL).

Having auto HDR enabled doesn't seem to work; this is probably a Windows bug. 

As I mentioned, I have an HDR monitor, and the changes that occur are:

1. When running the game, whether compiled or not, in full screen mode, the monitor flickers and the color of the game changes.

2. When closing, HDR is forcibly disabled and the brightness is lowered.

**Comment by renpytom** [comment]
Ren'Py doesn't use Pygame or Pygame CE. 

I'll be looking at upgrading SDL in Ren'Py 8.6, but it's a nontrivial project.
