### ISSUE TITLE
Error creating android package

### ISSUE THREAD

**Issue by shinoxd** [renpy/renpy#6022]
When trying to create an android package I get the following error: 

> Task :renpyandroid:lintVitalAnalyzeRelease FAILED
G: is not a JRE/JDK

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':renpyandroid:lintVitalAnalyzeRelease'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
   > Internal error: Unexpected lint invalid arguments

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 46s
46 actionable tasks: 46 executed

La construcción parece haber fallado.

I previously had the nightly version but thinking it was a bug in that version I decided to upgrade to 8.3.4 and I still get the error.

**Comment by renpytom** [comment]
You probably have JAVA_HOME set incorrectly.

**Comment by shinoxd** [comment]
> You probably have JAVA_HOME set incorrectly.

How do I reconfigure it or verify that it is misconfigured?

**Comment by renpytom** [comment]
https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10/985947#985947

Looks like a reasonable guide as to how to set (or delete in this case) an environment variable on windows. Note that I don't know why you'd have had it set in the first place.

**Comment by shinoxd** [comment]
> https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10/985947#985947
> 
> Looks like a reasonable guide as to how to set (or delete in this case) an environment variable on windows. Note that I don't know why you'd have had it set in the first place.

I don't know why that would have been changed since I never changed anything like that but everything works correctly now, thank you very much
