### ISSUE TITLE
slow_cps style property does not respect {fast} text tag

### ISSUE THREAD

**Issue by GiovanH** [renpy/renpy#6027]
In screen language, the `slow_cps` style property can be set to `True` to use the default typewriter speed. This should make it possible to reproduce the standard "what" textbox. However, if `slow_cps` is set on a text element, this takes priority over explicit `{fast}` tags in the text, and the text types out at the default speed. 

This also happens with the implicit instant-text effect that rollback should prompt.

Given this dummy say screen, which should display the `what` text twice:

```
screen say(who, what):
    style_prefix "say"

    window:
        id "window"

        if who is not None:

            window:
                style "namebox"
                text who id "who"

        text what id "what"

        text what:
            slow_cps True
```

and the script

```
    "I've had a lot of other thoughts on my mind...thoughts that culminate in a question."

    "It's a question that I've been meaning to ask a certain someone.{fast}"
```

The first line renders as expected: both lines type themselves out simultaneously. The second line causes the unexpected behavior: the stock `text what id "what"` statement respects the fast tag and skips the typewriter effect, but the one marked with `slow_cps` performs the typewriter effect even though it's been explicitly disabled in the script. 

This may be user error, but this might be incorrect behavior. I would expect precedence to work the opposite way. Currently my only workaround is to have each line of text announce whether it should be instant or not and have screen language set `slow_cps` conditionally, but even this only works as an all-or-nothing approach. 

But `slow_cps` may fundamentally be the wrong tool for the job, which would make this fixable in user space. I'm expecting it to "enable" cps on text with the `True` value, not force it. If I'm just implementing the "what" typewriter effect the wrong way, what would be the correct way to mimic the standard text behavior on an element with a different style and ID?

**Comment by GiovanH** [comment]
Demo of the above code:

https://github.com/user-attachments/assets/ba7c0048-bf82-4fc6-acc6-68a607aed739

And rollback:

https://github.com/user-attachments/assets/5c96bcd7-bbbe-401c-98b9-b34be88a328e

**Comment by renpytom** [comment]
https://www.renpy.org/doc/html/text.html#dialogue-text-tags

{fast} only applies to dialogue, not arbitrary text in screens. You could plausibly use multiple dialogue or text shaders, but replacing Ren'Py's dialogue system with your own is out of the scope of things that are supported.

**Comment by GiovanH** [comment]
I am trying to use this for dialogue, actually, just not the "what" text element. The complicating factor is my `say` screen has two text areas.

**Comment by renpytom** [comment]
That's what the multiple dialogue system is for. 

https://www.renpy.org/doc/html/multiple.html
https://www.patreon.com/posts/multiple-block-16120865

**Comment by GiovanH** [comment]
Interesting! This would take some game rewriting to use, but it looks like the answer to my question.
