### ISSUE TITLE
32bit linux not contains executable

### ISSUE THREAD

**Issue by qTich** [renpy/renpy#6028]
Build for `32bit` does not behave correctly.

https://github.com/renpy/renpy/blob/fba051737feed08c3f6b15ad132f91434a7e6ba5/launcher/game/distribute.rpy#L1096-L1102

But even if you change the condition:
```py
i686fn = os.path.join(config.renpy_base, prefix + "linux-i686/renpy")

if os.path.exists(i686fn):

    self.add_file(
        linux_i686,
        prefix + "linux-i686/" + self.executable_name,
        i686fn,
        True)
 ```
 
 The executable will still not be added.
 
 I guess it has to do with the way `merge` behaves and it prevents you from adding another file with the same name:
 ```py
 @staticmethod
def merge(l):
    """
    Merges a list of file lists into a single file list with no
    duplicate entries.
    """

    rv = FileList()

    seen = set()

    for fl in l:
        for f in fl:
            if f.name in seen:
                continue

            rv.append(f)
            seen.add(f.name)

    return rv
 ```

**Comment by renpytom** [comment]
You need to write better issue reports. "Does not behave correctly" doesn't tell me what the problems is. "Doesn't include the executable in the py-linux-i686 directory" does. Taking a minute or two to write out what you were expecting and what Ren'Py is doing means I don't have to spend time figuring out what the problem is.

**Comment by qTich** [comment]
`PC` build for `The Question` of `Ren'Py 7.8.4`

![image](https://github.com/user-attachments/assets/a287015a-36ee-432d-9d72-2db5302841aa)
![image](https://github.com/user-attachments/assets/a98c8d37-b61f-413a-b8a5-75d092aa1212)

**Comment by renpytom** [comment]
At least for me, changing the condition fixes it.
