### ISSUE TITLE
[8.3.4] Camel case image naming prevents Ren'Py from finding them.

### ISSUE THREAD

**Issue by DebatingPanda** [renpy/renpy#6046]
Hey!

Basically as the title states, when I rename an image (e.g. anyaBleh.png to anya_bleh.png) it will be found by the Ren'Py image search functionality, so I can just reference it by name without extension or path. If I have the name in camel case though, it will not be found.

Unsure if folder depth matters, since it worked at some point in the earlier development stages:
- game\images\specials\minigames\click-game\anyaBleh.png

```
imageButton:
    idle Transform(emote) # where emote is the string "anyaBleh" vs. "anya_bleh"
```

**Comment by juniorthejunior** [comment]
Ren'Py auto-imports images in the `images/` directory with the image names forced to lowercase, per https://www.renpy.org/doc/html/displaying_images.html#images-directory
So in your case you should be looking for `"anyableh"` if the file is named `"anyaBleh"`.

**Comment by DebatingPanda** [comment]
> Ren'Py auto-imports images in the `images/` directory with the image names forced to lowercase, per https://www.renpy.org/doc/html/displaying_images.html#images-directory So in your case you should be looking for `"anyableh"` if the file is named `"anyaBleh"`.

Thanks for clarifying! That solves the issue indeed.
