### ISSUE TITLE
RNG issues

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#607]
Had a few issues using renpy.random a few days ago, and wanted to make some suggestions because of it.

I was writing an element for a screen that used random numbers to add a bit of variation.  Using renpy.random to get those numbers, though, resulted in some images jumping around as the screen re-rendered.  I'm not sure whether this is fixable without a major overhaul.

Well, I didn't need *really* random numbers for my application, so I decided to create a small pool at init time, where I discovered that renpy.random was set to None, probably to maintain serialization of the RNG during game run.  Understandable.  I finally imported python's random and used that.

This leads me to two suggestions:

(1) Make renpy.random available at init for coder convenience, perhaps with a different salt from game time, then reset it when game is started.

(2) Make new PRNG instances available at run time.  Suggested format:
```
$ pool = renpy.random.pool(<seed>)
```
If \<seed\> isn't present, find a way to seed this consistently, perhaps from a hash of the file name and line #.  Then, access pool with pool.random(), pool.randint(), pool.choice().

**Comment by renpytom** [comment]
Screens aren't allowed to have side effects. Since the renpy.random RNG has side-effects, you aren't allowed to do it.

(1) seems reasonable, but for now you can just use Python's random.

**Comment by renpytom** [comment]
I checked the code, and we do (1) already. It doesn't appear to be set to None here - the code:

```
init python:
    renpy.random.random()
```

works for me.

**Comment by evilantishad0w** [comment]
Above code tested...
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 12, in script
    init python:
  File "game/script.rpy", line 13, in <module>
    renpy.random.random()
AttributeError: 'NoneType' object has no attribute 'random'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 12, in script
    init python:
  File "C:\Python27\renpy_experimental\renpy\ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Python27\renpy_experimental\renpy\python.py", line 1432, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 13, in <module>
    renpy.random.random()
  File "C:\Python27\renpy_experimental\renpy\python.py", line 741, in random
    renpy.game.log.current.random.append(rv)
AttributeError: 'NoneType' object has no attribute 'random'

Windows-7-6.1.7601-SP1
Ren'Py 6.99.2.370
TEST GAME 0.0
```
