### ISSUE TITLE
enhancement req: Method for passing more params to char func

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#618]
"Narrator speaking",extra=True -> $ narrator("Narrator speaking",extra=True)
charfunc "Character speaking",extra=True -> $ charfunc("Character speaking",extra=True)

Not useful for default Ren'py, but makes things much neater for when Character is wrapped and extra parameters need to be passed.

**Comment by renpytom** [comment]
I'm not totally opposed to this, but what's the use case. And why is that use case common enough that it needs special syntax, as opposed to the second form you give, which isn't much longer?

**Comment by evilantishad0w** [comment]
Oh, the 2nd form is for a specific character, while the first is for narrator.

I'd personally be using it to adjust placement for word bubbles.  I'm sure it'd be handy for other purposes as well.

**Comment by renpytom** [comment]
I'm leaning towards this, using a syntax where the properties are registered in advance, and are just simple expressions. So one would be able to do:

```
python early:
    renpy.register_say_property("extra")
```

and then

```
"Hello, world." extra True
e "Hello, you." extra True
```

Like that. I'm considering a similar syntax for annotations on in-game menu choices as well.

**Comment by evilantishad0w** [comment]
Sounds good to me...  One issue is line length getting longer though.  Colon indent also, like other parameters?

**Comment by evilantishad0w** [comment]
*bump*

So, suggested syntax:

```
python early::
  renpy.register_say_property("extra")

...

"Hello, world." extra True
e "Hello, you." extra True
e "How go?":
  extra True
```

**Comment by renpytom** [comment]
This was added in 6.99.13.
