### ISSUE TITLE
Slideshow doesn't work

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#621]
In 6.99.3.404, 

1: Click ToggleSlideshow button.
2: A next image is shown after slideshow_delay second.
3: But, nothing happens slideshow_delay second after it is shown.

**Comment by renpytom** [comment]
Do you have an example?

**Comment by kyouryuukunn** [comment]
sample
https://dl.dropboxusercontent.com/u/122050682/sample2.zip

1: launch this game.
2: click "gallery" in main_menu.
3: And click "slideshow" button.
