### ISSUE TITLE
Can't create a project using ubuntu 14.04

### ISSUE THREAD

**Issue by FractalBobz** [renpy/renpy#629]
When I move to create a new project I get a permission denied error,

![screenshot from 2015-05-10 06 37 06](https://cloud.githubusercontent.com/assets/1397393/7553191/747dc39c-f6df-11e4-95f8-4ec0b0b6de69.png)

I can understand why as it's trying to create a new folder in usr/share/games instead of ..games/renpy

Additionally, trying to change the projects directory didn't work as no launcher appears to edit this option

**Comment by renpytom** [comment]
Are you usinga Ren'Py downloaded from http://www.renpy.org ? I don't support distro packages directly.

You probably want to install python-tkinter, as that enables the directory picker.

**Comment by FractalBobz** [comment]
I am using the release that's in the Ubuntu software centre.

Thanks for the suggestion, I'll certainly try that solution, but I'd suggest an update to the distro package as currently it's not working and kinda makes ren'py look bad and unusable.

**Comment by renpytom** [comment]
Please file a bug with the distro. I don't maintain the package myself, and can't change it.

**Comment by FractalBobz** [comment]
Thanks again tom. I will indeed.
