### ISSUE TITLE
high resolution games on android

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#657]
Some notes on attempting to get a 4K resolution game running on Android devices.

Test game is in 3840x2160 resolution.  Game is also running with config.image_cache_size = 32.  Game in this resolution is proprietary and unfortunately can not be posted.

Devices tested were NVidia Shield (2GB RAM), and OnePlus One (3GB RAM).  Want to test on Samsung Galaxy S, none yet available.

Shield device crashed during playback. OnePlus made it farther on first run-through [with some odd artifacting](http://imgur.com/a/cK037) but crashed on subsequent tests.

**Comment by evilantishad0w** [comment]
After more testing, it appears that Ren'py-produced Android apps hit a wall at 1GB of RAM even with more available on the device.  Tweaking the settings to keep the RAM below this level prevented the app from crashing, though it became laggy at times.  It appears that, for the moment, 4K-resolution games aren't quite feasible on Android yet.

**Comment by renpytom** [comment]
I'm thinking some of the RAM improvements in 6.99.13 should really help here. New features like setting config.cache_surfaces to False and the non-power-of-two textures should significantly reduce memory consumption when enabled.
