### ISSUE TITLE
selected items in launcher are not displayed/invisible

### ISSUE THREAD

**Issue by empty-fortress** [renpy/renpy#666]
in this screenshot I have selected the tutorial project but as you can (not) see it's not displayed:
![renpy_menudisplaybug](https://cloud.githubusercontent.com/assets/2658281/8270092/bdbbeaee-17cc-11e5-8cee-ef818028a9e6.png)
It does the same for language choice in the launcher preferences.

I thought it was a problem with the update, there was indeed a problem with replacing a font file (Roboto-Light.ttf, the update logfile had a traceback mentioning not being able to replace the file since it was opened by something else) but replacing manually didn't solve the issue.

**Comment by renpytom** [comment]
I'd try a re-download, and if that doesn't work, consider using Steam to update your video drivers.

**Comment by empty-fortress** [comment]
Thanks for the quick answer! Sadly, no luck with a re-download of the zip of the latest version, nor with the driver update.
I forgot to mention it's a very old laptop (lenovo X200, windows vista 32 bits), with Intel integrated graphics (GM45, if that helps).

**Comment by empty-fortress** [comment]
So I fiddled a bit with the launcher code, and changing REVERSE_TEXT in launcher/game/style.rpy (line 35) to anything other than "#ffffff" makes the text reappear.

**Comment by renpytom** [comment]
Can you go into the launcher preferences, uncheck "hardware rendering", and restart?

**Comment by empty-fortress** [comment]
I should have thought about trying this, sorry! Turning off hardware rendering fixed the problem (also brought back the background highlight, which I didn't notice was missing, but maybe it wasn't displayed on this machine in previous ren'py versions either?)

![renpymenudisplaybug_fixed](https://cloud.githubusercontent.com/assets/2658281/8272241/7859f35a-183b-11e5-953e-6f5703bf59cb.png)

Thanks a lot for the fix!

**Comment by renpytom** [comment]
The issue is almost certainly bad video drivers. I suggest upgrading them, since I don't think Ren'Py can work around bad drivers. If the problem shows up in the launcher, it's also likely to show up in the games you make - so if you see weirdness like things not being drawn, that's why.

**Comment by empty-fortress** [comment]
Gfx weirdness while developing isn't a problem (I mostly use this machine as a typewriter anyway), the sad thing for me is not being able to support older intel graphic chipsets. But as you say it's a video driver problem, we can't do anything about it.

Thanks a lot for looking into this!
