### ISSUE TITLE
text_align in Character doesn't work

### ISSUE THREAD

**Issue by barsunduk** [renpy/renpy#668]
$ narrator = Character(None, what_xalign=0.5, what_text_align=0.5, show_say_vbox_properties=dict(xalign=0.5)) 

all align parameters i remember = 0.5 – text must be aligned by center. but align = 0 always, left side...
in which part i am wrong?

(Renpy v 6.99.4.467)

**Comment by renpytom** [comment]
text_align only works for multi-line text. To get what you probably want (totally centered text), use

what_text_align=0.5, what_xalign=0.5

**Comment by barsunduk** [comment]
thanx a lot for your answer!
p.s.:
init:
   $ e = Character("Eibleen", what_text_align=0.5, what_xalign=0.5,
       who_text_align=0.5, who_xalign=0.5)

label start:
    e "«what(/who)_text_align=0.5» # OK\n «what(who)_xalign=0.5» # fail..."
    return

http://s7.hostingkartinok.com/uploads/images/2015/07/c5b5edd5e1defe35c2b517023d2eb047.png
