### ISSUE TITLE
Screen language: 'use', screen actions & screen variables don't work together

### ISSUE THREAD

**Issue by caryoscelus** [renpy/renpy#682]
When screen is embedded inside another screen with 'use' statement, actions which work with its variables (e.g. SetScreenVariable, ToggleScreenVariable) stop working properly. Perhaps this means that renpy.current_screen() does not work properly with nested screens.

https://github.com/caryoscelus/renpy-fail/blob/master/use-screen-variable-test/game/script.rpy

(Complete test game: https://github.com/caryoscelus/renpy-fail/tree/master/use-screen-variable-test)

**Comment by renpytom** [comment]
I'm closing this as an old issue. With the current behavior, you're expected to pass the set variables from the outer screen to the used screen, that's not a behavior I expect to change in the future.

**Comment by morganwillcock** [comment]
Hi @renpytom,

I think I've just hit this same issue, where the included inner screen has an if statement, and whether I pass the value to the inner screen or just initialize it, `SetScreenVariable` doesn't seem to be working and the interaction doesn't get restarted (I think the action list gets broken and the UI seems to hang).

> you're expected to pass the set variables from the outer screen to the used screen

Are you saying that it is impossible to modify any values in the inner screen, which only exist in the inner screen?

Here are the two ways that I've tried, and I can't see an easy alternative that keeps the logic of the inner screen separate from the outer screen.

<pre>screen use_example():
    default confirmed = False

    if confirmed:
        text "CONFIRMED" xalign 0.5 yalign 0.3
    else:
        fixed:
            text "Are you sure?" xalign 0.5 yalign 0.3
            textbutton "Yes" xalign 0.45 yalign 0.5 action SetScreenVariable("confirmed", True)
            textbutton "No" xalign 0.55 yalign 0.5 action [SetScreenVariable("pushed_button", False), Hide("use_example")]

screen test_screen():
    default pushed_button = False
    
    if pushed_button:
      use use_example()
    else:
      textbutton "use":
          xalign 0.5
          yalign 0.5
          action SetScreenVariable("pushed_button", True)

label start:
    call screen test_screen
    return</pre>

<pre>screen use_example(confirmed):
    if confirmed:
        text "CONFIRMED" xalign 0.5 yalign 0.3
    else:
        fixed:
            text "Are you sure?" xalign 0.5 yalign 0.3
            textbutton "Yes" xalign 0.45 yalign 0.5 action SetScreenVariable("confirmed", True)
            textbutton "No" xalign 0.55 yalign 0.5 action [SetScreenVariable("pushed_button", False), Hide("use_example")]

screen test_screen():
    default pushed_button = False
    
    if pushed_button:
      use use_example(False)
    else:
      textbutton "use":
          xalign 0.5
          yalign 0.5
          action SetScreenVariable("pushed_button", True)

label start:
    call screen test_screen
    return</pre>
