### ISSUE TITLE
Music&Sound Volume controls is not working in 6.99.5.

### ISSUE THREAD

**Issue by Arisae** [renpy/renpy#685]
When I click each button until V6.99.4, it has changed the volume.
But in V6.99.5, when I click each button, it has changed to muted.
The code is changed?

Here is my code:

textbutton "Mute" action Preference("music mute", "toggle")
textbutton "Min" action Preference("music volume", 0.2)
textbutton "Medium" action Preference("music volume", 0.5)
textbutton "Loud" action Preference("music volume", 0.7)
textbutton "Max" action Preference("music volume", 1.0)

textbutton "Mute" action Preference("sound mute", "toggle")
textbutton "Min" action Preference("sound volume", 0.2)
textbutton "Medium" action Preference("sound volume", 0.5)
textbutton "Loud" action Preference("sound volume", 0.7)
textbutton "Max" action Preference("sound volume", 1.0)

**Comment by renpytom** [comment]
Sorry about that, it was a mistake on my part. Thank you for reporting it, it will be fixed in the next 6.99.5 release.

**Comment by Arisae** [comment]
Thank you for checking it!
