### ISSUE TITLE
00definitions.rpyc errors when running Lint

### ISSUE THREAD

**Issue by palmtoptiger42** [renpy/renpy#693]
Ever since I updated to the newest version, running lint brings back this on every project:

Ren'Py 6.99.5.602 lint report, generated at: Thu Jul 23 11:14:12 2015

lib/windows-i686/00definitions.rpyc:333 'define fade' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:334 'define dissolve' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:335 'define pixellate' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:338 'define wiperight' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:339 'define wipeleft' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:340 'define wipeup' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:341 'define wipedown' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:343 'define slideright' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:344 'define slideleft' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:345 'define slideup' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:346 'define slidedown' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:348 'define slideawayright' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:349 'define slideawayleft' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:350 'define slideawayup' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:351 'define slideawaydown' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:353 'define irisout' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:354 'define irisin' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:357 'define zoomin' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:358 'define zoomout' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:359 'define zoominout' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:363 'define vpunch' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:364 'define hpunch' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:367 'define blinds' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:368 'define squares' replaces a Ren'Py built-in name, which may cause problems.

lib/windows-i686/00definitions.rpyc:371 'define _narrator' replaces a Ren'Py built-in name, which may cause problems.

**Comment by renpytom** [comment]
Something looks seriously wrong there - like a version of Ren'Py was unpacked inside Ren'Py. 

I'd suggest re-downloading from renpy.org.
