### ISSUE TITLE
On ubuntu renpy.sh produces 'No module named _renpysteam' error

### ISSUE THREAD

**Issue by spankrat** [renpy/renpy#694]
Downloaded newest Renpy [Ren'Py 6.99.5.602] tar file extracted files and ran Renpy.sh file.
it created a log file with a 'No module named _renpysteam' error.

![log_txt file](https://cloud.githubusercontent.com/assets/3829108/8863549/5040a23c-315f-11e5-9250-6294da7210c2.png)

**Comment by renpytom** [comment]
This is normal and expected if you don't have the steam support. (The debug print is there to help people who do have steam support, but it's installed incorrectly.)

**Comment by spankrat** [comment]
"Ren'Py launcher" does not start and that was the only error presented...
are there prerequisites that need to be installed first..

Sincerely Steven Pankratz

Please visit http://www.linkedin.com/in/stevenpankratz for more information
about me.

**Comment by renpytom** [comment]
Okay, way to bury the lede there. 

Is that the last thing in  the file? Does a traceback.txt come into existence?

**Comment by spankrat** [comment]
Just the Log.txt that I gave you a screen shot of...

Sincerely Steven Pankratz

Please visit http://www.linkedin.com/in/stevenpankratz for more information
about me.

**Comment by renpytom** [comment]
Is that the entire log.txt? Usually, there's much more than that.

If it is, can you try running:

./renpy.sh launcher --trace 1 

That will dump a trace.txt file which might help me figure out where in the code things are going wrong.

**Comment by renpytom** [comment]
Closed as an obsolete issue with no response.
