### ISSUE TITLE
ios simulator i386

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#699]
http://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=33311

**Comment by jeffbalk** [comment]
FYI I commented on the forum - I think the solution is just that the prebuilt libraries need an i386 build target as well as ARM and x86_64

**Comment by jeffbalk** [comment]
Did some work on getting libffi to work with an i386 target. This workaround is needed:

https://github.com/rolfbjarne/libffi/commit/bde396d1acd99ee9bee043d9b4c3de501d3cba73
