### ISSUE TITLE
Title Screen "Help" Button fails to launch Help on Windows 10 / IE 11

### ISSUE THREAD

**Issue by mercurytw** [renpy/renpy#713]
I'm running Windows 10, and it seems that the default behavior (the Help() action) of the title screen does not launch the help file correctly. When I click the button, it launches Internet Explorer, but does not display the help page. It just loads up my homepage.

Details:
* This behavior (Launching IE) is the same regardless of what my default browser is set as.
* My IE version is 11.0.10240.16384
* My Windows 10 Build is 10240
* I upgraded from Win 7 to Win 10, which is why I have IE 11
* My RenPy version is 6.99.5.602

**Comment by mercurytw** [comment]
Edit: I originally said that it only happened from the Launcher, but it's happening in installed builds too.

**Comment by mercurytw** [comment]
Not a bug

**Comment by renpytom** [comment]
Why isn't it a bug?

**Comment by mercurytw** [comment]
Because I'm an idiot. The problem was on my end.
