### ISSUE TITLE
MoviTransition disables key

### ISSUE THREAD

**Issue by kyouryuukunn** [renpy/renpy#734]
I used below screen.

            screen say(who, what, side_image=None, two_window=False, centered=False):
                key "h" action [With(MoveTransition(3, leave=Transform(ypos=1.5, yanchor=1.0),layers=['screens'])),HideInterface(),With(MoveTransition(3,enter=Transform(ypos=1.5, yanchor=1.0),layers=['screens']))] 
         .
         .
         .

I pressed "h" and the screen was hiden with movetransition.
I pressed "h" and the screen was shown with movetransiton.
But, I pressed "h" again and the screen was hiden with none transition.

**Comment by renpytom** [comment]
I don't believe this _should_ work. You're applying two transitions at the same time. That's not going to work. I think your best bet is to just rewrite hide_interface so that it calls the transitions you want in the right order.
