### ISSUE TITLE
Add  [Screen Reader] support for individuals who are blind or visually impaired.

### ISSUE THREAD

**Issue by coadde** [renpy/renpy#744]
Add  [Screen Reader] support for individuals who are blind or visually impaired.

**Comment by renpytom** [comment]
We have self-voicing support that can be enabled by pressing v, and clipboard voicing support that is enabled with shift+C. 

I've looked into interfacing more directly with screenreaders, but I don't see that being practical -  last I checked, it would require the distribution of DLLs with licenses that don't allow me to distribute them. If you know of a good way of binding SDL2 code to a screenreader, please let me know - I'd love to look into improving this.

Until them, I don't have a good course of action.
