### ISSUE TITLE
the apk does not work on low-end phones

### ISSUE THREAD

**Issue by stwkun** [renpy/renpy#745]
I've always used two methods to test app created with Ren'Py

Use the Bluestack (android emulator for Windows) and use my phone Galaxy Young GT S5360L with android 2.3.6 to test the app created with ren'py

The problem is that in recent updates, RenPy 6.99 on, the game menú buttons on my phone hardly respond (I usually use large buttons for my application)

That has not happened with previous versions of RenPy

The app in Bluestack works well.

I hope you can help me with this little problem.

**Comment by renpytom** [comment]
Closing as an old bug, and Android 2.3 is now obsolete.
