### ISSUE TITLE
Issues with SL and Viewport.

### ISSUE THREAD

**Issue by XelaPy** [renpy/renpy#746]
I've reported this on the forum: http://lemmasoft.renai.us/forums/viewtopic.php?f=32&t=34185 but that seemed to be a useless action without a single response.

```python
screen testing_scr():
    viewport:
        align (0.5, 0.5)
        xysize (360, 400)
        scrollbars "vertical"
        has vbox spacing 3
        
        for item in xrange(10):
            add Solid("F00", xysize=(350, 100))
    
label start:
    call screen testing_scr
```

There is no alignment.

```python
screen testing_scr():
    viewport:
        pos (0.5, 0.5)
        xysize (360, 400)
        scrollbars "vertical"
        has vbox spacing 3
        
        for item in xrange(10):
            add Solid("F00", xysize=(350, 100))
    
label start:
    call screen testing_scr
```

Positioning and the bar are messed up.

```python
screen testing_scr():
    viewport:
        xysize (360, 400)
        scrollbars "vertical"
        # side "l"
        # or
        # side_vbar "l"
        has vbox spacing 3
        
        for item in xrange(10):
            add Solid("F00", xysize=(350, 100))
    
label start:
    call screen testing_scr
```

No argument can be passed to a side (assuming that one is created by ui/SL code).

====================================
http://www.renpy.org/doc/html/screens.html#viewport

Adding a container like a Box or a Side seems to help the issue a bit but there are still clear misrepresentations of this really would be nice to have feature in the documentation...

**Comment by renpytom** [comment]
This isn't a bug. The side created with scrollbars takes properties prefixed with side_, so if you give side_align (.5, .5), it will work.
