### ISSUE TITLE
iOS LaunchImage problems

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#765]
http://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=34264

**Comment by Jibus-** [comment]
Any news on this ?

**Comment by renpytom** [comment]
I haven't been able to repeat it, as I can't get the emulator to do it and I don't have any of the relevant devices. Is it stopping you from being accepted into the app store?

**Comment by Jibus-** [comment]
I can make some tests.

Could you confirm me that with the inital project (shipped with Renpy), the launchimage stays (on ios 9.0) ?

**Comment by renpytom** [comment]
Closing, as we don't use LaunchImages anymore, which presumably fixes this.
