### ISSUE TITLE
Dialogue window background not predicted

### ISSUE THREAD

**Issue by emmeken** [renpy/renpy#769]
If different characters have different background images for the dialogue window, prediction only works for the first window. I traced it to `renpy.display.predict.prediction_coroutine`, where the loop at the end refuses to call `renpy.display.screen.predict_screen` for the second dialogue window and beyond, since `predicted_screens` already contains `"say"`.

Maybe this is caused by the changes made to solve #747?

**Comment by emmeken** [comment]
Thanks for the quick fix. However, it may have been a bit too quick: since `predicted_screens` is now a list, `add` should be changed to `append` (line 172).

**Comment by renpytom** [comment]
I actually fixed that last night - but forgot to push the fix. It should be up now.
