### ISSUE TITLE
$ renpy.pause() is not working in auto-play mode

### ISSUE THREAD

**Issue by Arisae** [renpy/renpy#785]
In **6.99.7.858**,
**$ renpy.pause()** is not working in my replay labels.

**Comment by renpytom** [comment]
Can you throw together an example so I can debug it?

**Comment by Arisae** [comment]
I identified this issue. **It is not working in auto-play mode.**

if persistent.unlock_14 is False:
    button xsize 320 ysize 180:
        add 'lock'
    else:
        imagebutton idle 'bridgen_ko' hover 'bridges' hover_sound None action Replay('bridgeg', locked = False)


label bridgeg:
    scene bridge 
    show bridgeg 
    $ renpy.pause()
    hide bridge 
    hide bridgeg
    $ renpy.end_replay()

// show bridgeg is image with transform

**Comment by renpytom** [comment]
Why did you close this? Was it not a problem after all?
