### ISSUE TITLE
Screen "add" function is not recalled when a variable is updated

### ISSUE THREAD

**Issue by ahmelevsky** [renpy/renpy#786]
It is easy to reproduce with the script publicated here: 
http://www.renpy.org/wiki/renpy/doc/cookbook/Adding_a_simple_Analog_Clock

The code works fine in old renpy (for example 6.13), but doesnt work in the last builds (the clockhands don't rotate when 'minutes' changed).

**Comment by renpytom** [comment]
Like the rest of the wiki, that page is obsolete. For performance reasons, since 6.18 we don't re-evaluate transforms each time the screen is update. My suggestion would be to pass minutes to the transforms as a parameter. Ren'Py will be able to track the parameter change, and update the screen.

**Comment by ahmelevsky** [comment]
I see, thanks. Transformation is updated successfully when using python alternative.
