### ISSUE TITLE
$renpy.music.set_volume doesn't seem to work right

### ISSUE THREAD

**Issue by Renimator** [renpy/renpy#806]
It's me again. 
In my test $renpy.music.set_volume doesn't do what it should do. 
Could you take a look? 
[Volume_Test.zip](https://github.com/renpy/renpy/files/62133/Volume_Test.zip)

**Comment by vollschauer** [comment]
Why don't you use the forum? 
http://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=35574

**Comment by Renimator** [comment]
Thanks for the link. It's gotta be related. My test implies you cannot manipulate sound channels while the voice channel is in use.

**Comment by XelaPy** [comment]
And more info here: http://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=36082#p396160

This only works weird if when using voice channel for the first sound and when next interaction is called right away. If you wait for the sound on voice channel to finish playing and click for the next interaction then, volume is set appropriately.

Also stopping the first channel does not cause the second one to play the sound under any scenario.

@vollschauer
I am not sure what's there but there is already a perfectly workable workaround. It's just a very odd behavior, even if it's not a bug, why we get two different results using the same code with fast/slow clicking in a nice thing to understand. This obviously is not a priority case of any sorts.
