### ISSUE TITLE
The voice() function ignores the tag argument.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#807]

**Comment by vollschauer** [comment]
Still not working :/

**Comment by renpytom** [comment]
Was this tested against the nightly?

**Comment by vollschauer** [comment]
Yes was tested against the nightly build, I did a recheck with the 19.12. today....just to make sure.

**Comment by vollschauer** [comment]
No luck :/ It seems to me the whole function voice() in line 67 is going to be ignored.
(I commented there everything out and voice is still playing...huh?)
"volume = persistent._character_volume.get(_voice.tag, 1.0)" in Line 361 is still getting None as _voice.tag ....I speak to less python to figure out why. Maybe it's an issue of the renpy.statement.register
in line 455? where is the tag argument passed to the voice function?

**Comment by renpytom** [comment]
Can I see your code, in the form of a runnable Ren'Py game? I checked, and the latest code is working for me.

**Comment by vollschauer** [comment]
I setup a new project to realized every is working as it should! A silent WTF came to my mind....
It took me a while to find out where all the trouble came from: The readback module from (http://www.renpy.org/wiki/renpy/doc/cookbook/Text_History) with it's voice_replay function :/
I'm really sorry to keep you that busy....I knew the wiki/cookbook was outdated :/

**Comment by vollschauer** [comment]
We can close that one ;) Thanks for your help.
