### ISSUE TITLE
Positional arguments with DynamicImage (Feature request)

### ISSUE THREAD

**Issue by koroshiya** [renpy/renpy#809]
Using DynamicImage, we can define images like:

<code>
image eileen = "eileen [mood]"
</code>

The problem is, this means manually updating the variable used, which can be messy and repetitive.

<code>
label start:
  $ mood = 'happy'
  eileen "I'm happy!"
  $ mood = 'angry'
  eileen "I'm angry!"
  $ mood = 'happy'
  eileen "I'm happy again!"
  $ mood = 'angry'
  eileen "Nope, still angry!"
</code>

Usually in renpy, we'd be able to use who arguments to change images.

<code>
label start:
  eileen happy "I'm happy!"
  eileen angry "I'm angry!"
  eileen happy "I'm happy again!"
  eileen angry "Nope, still angry!"
</code>

Naturally this won't work with dynamic images, since the arguments are mapped to variables which need updating.

My idea to overcome this is to include optional indices in the dynamic image statement, resolving them from last to first.

<code>
image eileen = "eileen [0:pose] [1:mood]"

label start:
  $pose = 'standing'
  eileen happy "I'm happy!" #happy maps to 1, the last index, and pose is already set
  eileen standing sad "...Not." #sad maps to 1, and standing maps to 0
</code>

This would retain compatibility with existing dynamic images, but also allow for more flexibility going forward, allowing someone to effectively use one "image" statement per character while also allowing for the traditional dialogue image swapping syntax.

**Comment by renpytom** [comment]
Why not go with 0 image statements in this case, and just let Ren'Py auto-define images for you using the images/ directory?

**Comment by koroshiya** [comment]
My bad, the example image statement used above doesn't really show what my goal is.
I'm thinking moreso of LiveComposite images, such as the dress-up example.

**Comment by renpytom** [comment]
I believe that Layered Images take care of this.

**Comment by koroshiya** [comment]
Agreed. I've used LayeredImage for this purpose in a couple of games now and it achieves this perfectly.
