### ISSUE TITLE
Vertical text doen't render at the display resolution

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#814]
When vertical is True, text is blurry in full screen mode.

**Comment by renpytom** [comment]
Can you try this out using a font with proper vertical hinting, and let me know? You might also need to set  the hinting style property to "bytecode".

**Comment by nyaatrap** [comment]
I've tried several japanese vertical fonts with the above commit, but all of them are blurry in some resolution.

![clipboard-1](https://cloud.githubusercontent.com/assets/3129985/12073642/d9f730cc-b16b-11e5-9f12-15c6d2fb03f3.png)

I don't know if there is a font with proper hinting. hinting property doesn't change how they look in all fonts I know.
The sample project I tested is http://adobe.ly/1UlxlQm (A plain template with several japanese fonts)

**Comment by vbkaisetsu** [comment]
This commit contains pyx changes, so I checked it in Debian.
I think this report can be closed.
I attached results of the sample project.

![comparison](https://cloud.githubusercontent.com/assets/2175479/12471426/ccf96faa-c040-11e5-941a-67950b1aed14.png)

**Comment by renpytom** [comment]
Ok. Nyaatrap, feel free to reopen if it's bad on some other platform.
