### ISSUE TITLE
Hope can realize these functions

### ISSUE THREAD

**Issue by bbs3223474** [renpy/renpy#822]
I'm writing scripts like this:
show bg2 is_ecg01a_s02 as top
with Dis
play sound "vo1/ayumu_10001.ogg"

show bg2 is_ecg01a_s03 as top
with Dis
play sound "vo1/ayumu_10002.ogg"

Here I want image can wait for voice(played by "play" statement) to finish because every voices is related with images. But now, those images can only show continuously. I don't want to use "pause" statement because every voices has different length, it's too ineffective to figure out all the number and I have a plenty of them.
In another engine like BURIKO General Interpreter, I can realize this by writing like this:
IS_ECG01A_s02
_DrawBS
AYUMU_10001
_PlayVoice
_WaitToFinishVoice  // This is the key point! Image will wait for the voice to finish.
_Wait  // This statement in Ren'py is "pause 1"
So I hope Ren'py can add a statement like this, then I can control the play time easily.
————————————————————————
I hope Ren'py can add a configureation which can play a voice when entering the main menu. I know I can set the music in main menu, but I also want to play a voice(like there's a character saying the title of the game) whenever I enter the main menu. It's better if I can set multiple files and Ren'py will play them randomly or one of them by player settings.
————————————————————————
Also, I hope Ren'py can add a statement which can delay audio play. For example, I write script like this:
play sound "vo1/ayumu_10001.ogg" delay 3
show bg2 is_ecg01a_s02
with dissolve

Then the image will show immediately but the audio will play after 3sec. I think it's useful when I don't want to use "pause" in some cases.

**Comment by renpytom** [comment]
It should be possible to do this using a python function, and then (currently undocumented, but I'll fix that) ui.soundstopbehavior function. Something like:

    init python:
        def waitsound(fn):
            renpy.music.play(fn, channel="sound")
            ui.soundstopbehavior("sound")
            renpy.pause()

    show bg2 is_ecg01a_s02 as top
    with Dis
    $ waitsound("vo1/ayumu_10001.ogg")

**Comment by bbs3223474** [comment]
I'll try and review later, thanks a lot.

**Comment by bbs3223474** [comment]
By the way, the second question (play a sound when entering main menu) also need solution. Now I'm using "play" statement in label splashscreen, so I can hear the sound when passing the splash screen, but that still not so perfect.

**Comment by bbs3223474** [comment]
I've tried $ waitsound statement, but there's a thing:
Now images can wait for the sounds, but actually I want sounds play at first, not after the images, any way to solve this? (If not, I may also accept the "$ waitsound" solution)

**Comment by renpytom** [comment]
You could make "waitsound" a separate step, with code like:

    init python:
        def waitsound():
            ui.soundstopbehavior("sound")
            renpy.pause()

    play sound "vo1/ayumu_10001.ogg"
    show bg2 is_ecg01a_s02 as top
    with Dis
    $ waitsound()

**Comment by bbs3223474** [comment]
That's okay, problem solved.
