### ISSUE TITLE
Can't Ren'py recognize a filename begin with numbers?

### ISSUE THREAD

**Issue by bbs3223474** [renpy/renpy#824]
I'm using "config.automatic_images = [ '/' ]" and "config.automatic_images_strip = [ '/' ]" configuration variable in my project. But I found Ren'py cannot show some image because those files have filenames begin with numbers, like:
ch1c/01ayua02m01.png

Then when I'm using "show ch1c 01ayua02m01", Ren'py shows nothing on the screen. But after rename the file and let the filename begin with letters, it works normally.
I'm confusing about whether Ren'py cannot recognize those file which filename begin with numbers. Can it be fixed?

**Comment by renpytom** [comment]
This should be in the next nightly build, if you need it ASAP.
