### ISSUE TITLE
Missing modules when importing

### ISSUE THREAD

**Issue by jrmedd** [renpy/renpy#845]
Hi,

I'm working on a game for which I'd like to import pySerial to communicate with an Arduino at certain points. When I import serial, it complains:

```
ImportError: No module named termios
```

I experienced a similar dependency error when importing another module (Queue, I think it was) earlier on when trying out Ren'Py. I know that ultimately I might be pushing beyond the scope of the engine, but I was just wondering how easy it would be to work around something like this.

Loving everything else about the engine so far. Bravo.

**Comment by renpytom** [comment]
What platform do you need this for? It's probably out of scope to include in normal builds of Ren'Py, but I could go in and grab the copy built as part of the build process, and you could stick it into place.

**Comment by jrmedd** [comment]
Thanks for responding. I'm working on Ubuntu 14.04 (64-bit) at the moment, but can't guarantee where I'm going to be deploying it yet. It's for an installation project with the Arduino stuff. I figured it'd probably be outside Ren'Py's scope, but thought it was worth asking.

**Comment by renpytom** [comment]
Here's the 64-bit linux version, to get you started. You should be able to
drop this into lib/linux-x86_64/lib/python2.7/lib-dynload and things will
likely work.

**Comment by renpytom** [comment]
And by "Here", I clearly mean http://share.renpy.org/termios.so

**Comment by jrmedd** [comment]
That works perfectly, thanks so much. Any chance of providing this for other platforms in the future too?

**Comment by renpytom** [comment]
When you decide where you're going to deploy, let me know and I'll give you a second termios.so for that platform.
