### ISSUE TITLE
undefined symbol: PySurface_New

### ISSUE THREAD

**Issue by caryoscelus** [renpy/renpy#876]
After c3e464311e244da1980d6f9cc365cf3df25b949f, launching manually built renpy fails with the following message:

```
Traceback (most recent call last):
  File "renpy.py", line 195, in <module>
    main()
  File "renpy.py", line 192, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "renpy/bootstrap.py", line 252, in bootstrap
    renpy.import_all()
  File "renpy/__init__.py", line 427, in import_all
    import renpy.audio.audio
  File "renpy/audio/audio.py", line 40, in <module>
    import renpy.audio.renpysound as renpysound
ImportError: env/local/lib/python2.7/site-packages/renpy/audio/renpysound.so: undefined symbol: PySurface_New
```

Looks like there's missing dependency on pgext (or alternative implementation).

**Comment by renpytom** [comment]
The dependency is on https://github.com/renpy/pygame_sdl2

**Comment by caryoscelus** [comment]
Well, i even tried fully rebuilding it, still doesn't work.

**Comment by renpytom** [comment]
Can you check the modification times on the installed copies of renpysound.so and surface.so, and use nm to make sure the latter exports PySurface_New? This was added recently, and it's possible something prevented the new version from installing.

**Comment by caryoscelus** [comment]
I actually removed both installed packages and build files, so those
are updated. And yes, surface.so exports something like it:

0000000000008280 t __pyx_f_11pygame_sdl2_7surface_PySurface_New

**Comment by caryoscelus** [comment]
Hmm, it seems that problem could be due to the way how pygame_sdl2/ include files were placed: apparently i just copied it long time ago to fix build. Reporting the real issue now :)
