### ISSUE TITLE
DirectX error when starting any game or SDK version 6.99.9

### ISSUE THREAD

**Issue by KosMos-pv** [renpy/renpy#877]
When I start RenPy SDK 6.99.9 I get following traceback. I can press Ignore and continue but this error is annoying. I found this bug in my favorite game which updated today to RenPy Engine 6.99.9 and I decided to test this in SDK (maybe this is engine-specific error, not game-specific).
[traceback.txt](https://github.com/renpy/renpy/files/174150/traceback.txt)

I run Windows 10, build 10586. GPU - Nvidia Geforce GTX 550 Ti, driver version 353.82.
There is no problems with visual novels that run on older versions of RenPy.

ps sorry for my bad english,

**Comment by nyaatrap** [comment]
I think it's a same error I got http://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=37513#p407679
I'm also windows10 & Nvidia. DId you plugged in a joypad or something?

**Comment by renpytom** [comment]
Does the latest nightly make this problem go away?

http://nightly.renpy.org/current/

**Comment by nyaatrap** [comment]
It doesn't crash, but I still get 'no gamepads available'.

**Comment by KosMos-pv** [comment]
Latest nightly did not solve a problem. But problem was in my Logitech F-510 gamepad in Dinput mode. When I switch it to Xinput there is no problems at all in release version and in nightly.
Traceback if needed from latest nightly - 
[traceback.txt](https://github.com/renpy/renpy/files/174569/traceback.txt)
