### ISSUE TITLE
Android build of game crashes with SDL Error

### ISSUE THREAD

**Issue by d3nzil** [renpy/renpy#880]
Android build of my game crashes on tablet (Android 4.4.4, Intel) with SDL Error message, but works on phone.
You can get the build from: http://lunaen.com/games/fairy/#shopping (it's the second in list - Fairy: Shopping Day, PC build has sources included)
Screenshot of the error: https://www.dropbox.com/s/vjm1jeq433vnv0f/Screenshot_2016-03-20-17-40-01.png?dl=0

**Comment by renpytom** [comment]
It looks like the ARM emulator on your tablet isn't working. We don't support intel tablets, except through that emulation, so you'll need to fix that before you can run Ren'Py.

**Comment by d3nzil** [comment]
Ah, ok. Thanks for the help.
I didn't know that Intel is not supported and was surprised because the projects I built last year worked on it. I don't think I can do anything about the ARM emulation, so I guess I'll try building with older version of RenPy and see.

**Comment by renpytom** [comment]
Ther thing is - intel should be supported. The builds work on my father's tablet, for example, via emulation. So it's weird that it's not working for you, but I'm not sure it's Ren'Py's fault. Maybe do an adb logcat to see if an error is being logged.

**Comment by d3nzil** [comment]
If I understand the output correctly, then the emulator cannot handle this kind of ARM binary. I'm attaching output with both the new not working game and the working old game, if it helps.
[logcat_new_game.txt](https://github.com/renpy/renpy/files/181468/logcat_new_game.txt)
[logcat_old_game.txt](https://github.com/renpy/renpy/files/181469/logcat_old_game.txt)

**Comment by renpytom** [comment]
Can you try switching to the nightly channel and updating? There's an issue I fixed there (literally yesterday)  that this might be a terrible error-report of.

**Comment by d3nzil** [comment]
The nightly version starts and plays correctly. Thanks for the help. (:

**Comment by renpytom** [comment]
No problem.
