### ISSUE TITLE
Windows 10 RAPT issues

### ISSUE THREAD

**Issue by insciq** [renpy/renpy#882]
Renpy version: `6.99.9`
For some reason `run_slow` function in `install_sdk.py` always returns false, but i've JDK installed and it works well in my %path%
```
C:\Users\insci>javac -version
javac 1.8.0_74
```
I don't know how to debug in renpy so i can't provide tracebacks or some detailed info. Also i reinstalled renpy and rapt few times, it didn't help. I've changed run_slow to return always true for solve this problem.

Next issue i faced with android SDK, for some reason SDK downloaded by rapt don't have `\extras \google\play_licensing\library\build.xml` file, even when i reinstalled `Google play licensing library` few times. This problem caused by old SDK version, when i changed `sdk_version = "r23"` for `r24.4.1` in `plat.py` manually and reinstall android SDK everything started working well. Is this some reason to use old SDK version?
Finally i successfully builded android app and ran it, so i guess these problems may occur to other people.

**Comment by renpytom** [comment]
I've gone ahead and made that change.
