### ISSUE TITLE
Android app crashed after start

### ISSUE THREAD

**Issue by nerox8664** [renpy/renpy#885]
I/python  (11372): TypeError('render_movie() takes exactly 2 arguments (3 given)',)
I/python  (11372): Full traceback:
I/python  (11372):   File "renpy/common/_layout/screen_main_menu.rpym", line 29, in script
I/python  (11372):   File "/usr/share/renpy/renpy/ast.py", line 805, in execute
I/python  (11372):   File "/usr/share/renpy/renpy/python.py", line 1461, in py_exec_bytecode
I/python  (11372):   File "renpy/common/_layout/screen_main_menu.rpym", line 29, in <module>
I/python  (11372):   File "/usr/share/renpy/renpy/ui.py", line 277, in interact
I/python  (11372):   File "/usr/share/renpy/renpy/display/core.py", line 2424, in interact
I/python  (11372):   File "/usr/share/renpy/renpy/display/core.py", line 2765, in interact_core
I/python  (11372):   File "/usr/share/renpy/renpy/display/core.py", line 1853, in draw_screen
I/python  (11372):   File "renpy/gl/gldraw.pyx", line 760, in renpy.gl.gldraw.GLDraw.draw_screen (gen/renpy.gl.gldraw.c:11099)

Renpy version: renpy-nightly-2016-03-27
RAPT version: renpy-nightly-2016-03-27-rapt
Android version: 4.2

Full tracelog: https://gist.github.com/nerox8664/55a7b4d6314bbf5db1cb

UPD. Tried in both 6.99.8 and nightly.
On another device (Android 5.0) all is ok.

**Comment by evilantishad0w** [comment]
http://pastebin.com/QgTapKch full traceback

**Comment by pratomoastan** [comment]
Try to remove the movie i dont think android suport ogv format 
Maybe you should make 2 version of it one for pc include the movie 
One for android is doesnt include the movie.

**Comment by pratomoastan** [comment]
My android version is crashed when i was including the video for the game. 
After i remove the video along with $ renpy.movie_cutscene from the script its working fine.
For my amdroid version instead using $ renpy.movie_cutscene i use 
Show text "" with dissolve
With pause (2)
Hide text
For my splash and cut scene .
Hope this help.

**Comment by evilantishad0w** [comment]
You could also convert the movie to a file format Android supports...

**Comment by pratomoastan** [comment]
here's the supported format for android : 
Android Supported Video Format/Codec	Supported Video File Types/Container Formats
=
H.264 AVC	
• 3GPP (.3gp) • MPEG-4 (.mp4) • MPEG-TS (.ts, AAC audio only, not seekable, Android 3.0+)
=
MPEG-4 SP	•3GPP (.3gp)
=
VP8	• WebM (.webm) • Matroska (.mkv, Android 4.0+)
==============================
supported format for renpy : 
Ren'Py is capable of using ffmpeg (included) to play movies using the video codecs:
Theora
MPEG 4 part 2 (including Xvid and DivX)
MPEG 2
MPEG 1
and the following audio codecs:
Vorbis
MP3
MP2
PCM
inside the following container formats:
Matroska
Ogg
Avi
Various kinds of MPEG stream.

you must see the both compatibility for android and renpy .

**Comment by pratomoastan** [comment]
oh this is already solved.
it should be closed .
