### ISSUE TITLE
Inconsistency between show and hide tag handling

### ISSUE THREAD

**Issue by KonssnoK** [renpy/renpy#886]
The hide function should accept a TAG or a name as input

```
def hide(name, layer=None):
    if renpy.game.context().init_phase:
        raise Exception("Hide may not run while in init phase.")

    if not isinstance(name, tuple):
        name = tuple(name.split())
```

as you can see the given tag is stripped after any space.
Instead if we look at the show function:

```
def show(name, at_list=[ ], layer=None, what=None, zorder=None, tag=None, behind=[ ], atl=None, transient=False, munge_name=True):

    if not isinstance(name, tuple):
        name = tuple(name.split())

    if zorder is None and not renpy.config.preserve_zorder:
        zorder = 0
    
    sls = scene_lists()
    key = tag or name[0]
```
the tag value is never stripped.

Therefore using a tag with spaces will result in an inconsistent state where you cannot hide displaying elements.

I temporary patched by adding
```
  if tag:
        if not isinstance(tag, tuple):
            tag = tuple(tag.split())[0]
```

to the show statement, 
but i don't know if it affects any other function

**Comment by renpytom** [comment]
I don't think this is a real bug, since if you want that stripping, you can just do:

renpy.hide(('name with space'))

(also, names with spaces in them are a terrible idea - you can't create them with the image statement, and you shouldn't consider them supported.)
