### ISSUE TITLE
window_icon not showing under ubuntu!?

### ISSUE THREAD

**Issue by vollschauer** [renpy/renpy#891]
I noticed this under Ubuntu (Unity Launcher) that sometimes the icon appears and sometimes its shows just a "question mark" icon...

http://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=37821&p=410330#p410330

**Comment by vollschauer** [comment]
This also applies to the launcher itself. Most of the time you see a question mark and sometimes you see the propper renpy logo
![screenshot from 2017-03-06 12-56-16](https://cloud.githubusercontent.com/assets/5165216/23611499/fde89efe-0277-11e7-8533-ebe4791f45c6.png)
![screenshot from 2017-03-06 12-56-46](https://cloud.githubusercontent.com/assets/5165216/23611502/ffdaa522-0277-11e7-930f-c8518a642381.png)

**Comment by Ria-kon** [comment]
Sometimes similar problem on windows, when python icon showed, instead of game icon.

**Comment by renpytom** [comment]
Closing as an old bug, plus unity is now leaving ubuntu, and it seems to work in Gnome.
