### ISSUE TITLE
Cropped screenshots for save slots in iOS iPhone 6 plus (actual device only)

### ISSUE THREAD

**Issue by ahlun** [renpy/renpy#900]
Screenshots taken for save slots are cropped. See the screenshots attached for example. This only happen in actual devices,but _not_ in the iPhone 6 plus simulator.

![img_4953](https://cloud.githubusercontent.com/assets/18313056/14327292/3af23aa0-fc64-11e5-8a70-986eeb4f4602.jpg)

![img_4954](https://cloud.githubusercontent.com/assets/18313056/14327250/0f6e9b4e-fc64-11e5-82a9-5eebb46eabc2.jpg)

**Comment by renpytom** [comment]
I don't have an iPhone 6 Plus, and there have been no further reports of this, so I'm closing it as an old bug.
