### ISSUE TITLE
auto advance coudn't work.

### ISSUE THREAD

**Issue by nyaatrap** [renpy/renpy#905]
http://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=37798#p410967
I tried several thing, but I still have no clue what caused it.
Thought we have this consistent issue so I think it should be marked on the issue.

**Comment by renpytom** [comment]
Can you explain how the problem manifests? I find that thread really unclear.

**Comment by nyaatrap** [comment]
1: Launch the tutorial game in 6.99.10.
2: Press the auto button to start auto-forward
3: After checked auto-forward is working (sometimes not working though), click again to disable auto-forward.
4: Now auto-forward is buggy. Even when I clicked the auto button again, it doesn't start auto-forwarding.

**Comment by renpytom** [comment]
Thank you. I can now repeat the problem.
