### ISSUE TITLE
Invisible text in menus

### ISSUE THREAD

**Issue by Tomoyo-Ichijouji** [renpy/renpy#909]
I've updated to the latest version, but for some reason in all the menus in the launcher, like selecting projects, themes, or languages, the text won't show up.  This will happen also in the Tutorial game, making me unable to read what the tutorial topic is.  I've tried reinstalling and refreshing, but nothing seems to make this bug go away!  Any suggestions as to what I can do?  I've attached screenshots of the bug in action.
![renpybug_languages](https://cloud.githubusercontent.com/assets/18447937/14503605/e125f3d4-017e-11e6-9202-cf0f7ffab7f9.png)
![renpybug_projects](https://cloud.githubusercontent.com/assets/18447937/14503603/e11f66b8-017e-11e6-838a-9f7251132257.png)
![renpybug_themes](https://cloud.githubusercontent.com/assets/18447937/14503602/e11e971a-017e-11e6-97b5-95e2db9ea126.png)
![renpybug_tutorialgame](https://cloud.githubusercontent.com/assets/18447937/14503604/e124aad8-017e-11e6-924c-7a9ad8c00995.png)

**Comment by renpytom** [comment]
This is almost certainly a bug with your video drivers. Please update them.
