### ISSUE TITLE
Some things work weirdly on windows 10 with scaling

### ISSUE THREAD

**Issue by DarkTl** [renpy/renpy#919]
While on other systems, from XP to 8.1, it works as intended, on 10 at first it appears without resizing and centering, closer to right bottom corner. Then, after 2-3 seconds, the game resizes and centers it.

**Comment by renpytom** [comment]
Question: What DPI is your monitor running at?

**Comment by DarkTl** [comment]
1920x1080
Here is screenshot I made: https://www.dropbox.com/s/67abhvvr9jger6o/1.png?dl=0

**Comment by renpytom** [comment]
It's not the resolution that matters, it's the DPI scaling factor. You can get that by right clicking on the desktop, display settings, and looking at the "Change the size of text, apps, and other items" slider.

**Comment by DarkTl** [comment]
125% atm. I tried to change it, the weird behavior remains.

**Comment by renpytom** [comment]
Thanks. I'll look into this when I get a chance, to see if I can repeat it.

**Comment by DarkTl** [comment]
*Correction. After changing it to 100% AND rebooting it works as intended. So I suppose it's a matter of win10 scaling factor, something that was fixed for older systems in 6.99.9 renpy according to changelogs.

**Comment by renpytom** [comment]
Actually, I suspect it's because I totally forgot about how the scaling factor would apply to presplash.

**Comment by DarkTl** [comment]
I tested it on Win7 with 125% scaling and the same resolution, works normally.

**Comment by DarkTl** [comment]
Update: presplash is not the only thing that has issues when used on win10 with scaling. When you use extend to output more text, it changes text size a bit. I don't mean font size, I mean spacing between letters.

**Comment by renpytom** [comment]
I fixed the scaling problem.

The text spacing issue can be mitigated using the adjust_spacing style property, but is fundamental to text that can change its shape with the size of the window.

https://www.renpy.org/doc/html/style_properties.html#style-property-adjust_spacing
