### ISSUE TITLE
Should window auto hide the window before "call screen"?

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#929]
Probably. And if so, does it?

**Comment by XelaPy** [comment]
Last say screen will be hidden as an interaction ends before we move to the statement that calls a screen. With interact=False it will stay put. Seems like a very reasonable behavior, or is this about something else?

**Comment by renpytom** [comment]
No, it's as much about me making a note to think more about it to work out all the implications before I go ahead and implement it.
