### ISSUE TITLE
Cannot perform data action with image button

### ISSUE THREAD

**Issue by pandadeath** [renpy/renpy#938]
Hi, I apologize if this has been answered (in my defense I have been searching online for hours and have not found the answer).  I have an imagebutton and would like to have data action performed when it is clicked.  I can perform other actions such as Hide and Jump with no problem, however, the SetVariable action does not appear to do anything.  

I defined a variable to "count" thusly:
init python:
    showcompletion= False
    completion = 0
    def display_completion():
        if showcompletion:   
            ui.frame() #This is optional. It adds a frame around the text.
            ui.text("Completion: %d" %completion)
    config.overlay_functions.append(display_completion)

 I copied this directly from  https://www.renpy.org/wiki/renpy/doc/cookbook/Simple_Onscreen_Inventory to try to avoid issues.  

An example of my image button is:
    screen P_tube_options00:
        modal False
        imagebutton:
            xpos 0 ypos 500
            idle "idle.png"
            hover "hover_text.png"
            action [Hide("imagebutton")]
        imagebutton:
            xpos 180 ypos 180
            idle "blank.png"
            hover "hover.png"
            action [Jump("P_tube00_description"), SetVariable("completion",completion+1), SetVariable('T_options00a',True)]

I got this from https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=9412 .

I have tried "clicked" instead of "action".  I have done just SetVariable("completion",completion+1) alone and just SetVariable('T_options00a',True) [I then set up an if statement, if blah == True: $completion+=1] alone, however, when I do showcompletion=True or just %(completion)d, it reads 0.  If I put $completion+=1 or even SetVariable("completion", completion+=1) into the imagebutton tabs, I get an error.  

I am sure this is very simple and I very sorry for wasting your time, but the help is greatly appreciated.  

Thanks.

**Comment by xavi-mat** [comment]
1. I think this is not an issue in renpy, but a question about using it. Better ask in the forum: https://lemmasoft.renai.us/forums/viewforum.php?f=8

2. The ui.functions are really old, better use the new Screen Language. Search the doc in https://www.renpy.org/doc/html/screens.html (and not in the old renpy.org/wiki).

**Comment by pandadeath** [comment]
Thanks for the reply. Yes I am sure it is not a problem with the code. I have looked at both those before and I am sorry for bothering you. I can hard code another solution in.

**Comment by renpytom** [comment]
The issue is with 

```action [Jump("P_tube00_description"), SetVariable("completion",completion+1), SetVariable('T_options00a',True)]```

The Jump takes place immediately, preventing the second two actions from executing.

**Comment by pandadeath** [comment]
Thank you.  That makes sense and works well.  Sorry for bothering you with
the silly question.
