### ISSUE TITLE
Strange text render behaviour on renpy version 6.99 and higher

### ISSUE THREAD

**Issue by roxygen** [renpy/renpy#941]
The problem occurs only when CTC definition is present in the narrator definition. So far it occured only on my PC.
OS: Windows 8.1
Video card: Intel(R) HD Graphics 4000 with last driver update

EN
[One](https://cloud.githubusercontent.com/assets/3707285/15268783/400d0718-1a14-11e6-9de8-6a6e527c9f70.jpg) [Two](https://cloud.githubusercontent.com/assets/3707285/15268785/4c44d57e-1a14-11e6-82b7-244a7b6d89bc.jpg)
RU
[One](https://cloud.githubusercontent.com/assets/3707285/15268833/64b84058-1a16-11e6-9166-ea99a760d9f1.jpg) [Two](https://cloud.githubusercontent.com/assets/3707285/15268837/67d09394-1a16-11e6-9e20-12b1451b9e2f.jpg) [Three](https://cloud.githubusercontent.com/assets/3707285/15268838/696145a0-1a16-11e6-9a2c-3fff421052c1.jpg)

NVL screen:

``` python
screen nvl:
    window:
        background Frame(im.Alpha(_("gfx/ui/tbox3.png"),persistent.win['opacity']),0,0)

        xsize 680
        ysize 720

        left_padding 0
        right_padding 0
        top_padding 0
        bottom_padding 0
        left_margin 0
        right_margin 0
        xpos(persistent.win['xpos'])
        ypos(persistent.win['ypos'])
        xanchor(persistent.win['xanchor'])
        yanchor(persistent.win['yanchor'])

        has vbox

        $ i = len(dialogue)
        for who, what, who_id, what_id, window_id in dialogue:
            $ i -= 1
            window:
                xpos 50
                ypos 25
                xsize 580

                background None

                id window_id

                has hbox:
                    spacing 15

                if who is not None:
                    text who id who_id

                text (what) id what_id:
                    size 23
                    first_indent 10
                    line_spacing 5
                    if persistent.win['text_shade']:
                        if i == 0:
                            color "#FFF"
                            outlines [(1,"#000F",0,0),(1,"#000F",1,1)]
                        else:
                            color "#FFF8"
                            outlines [(1,"#0004",0,0),(1,"#0004",1,1)]
                    else:
                        color "#FFF"
                        outlines [(1,"#000F",0,0),(1,"#000F",1,1)]

    use quick_menu

    imagebutton id "hide":
        action HideInterface()
        idle _("gfx/ui/onscreen/hide_off.png")
        hover _("gfx/ui/onscreen/hide_on.png")
        xpos persistent.win['xpos'] + 620
        ypos 20
        xanchor 0.5
        yanchor 0.5
```

Narrator definition:

``` python
define narrator = Character(None, kind=nvl, ctc="wink")
```

CTC definition:

``` python
image wink = Animation("gfx/ui/wink/wink0.png", 0.1, "gfx/ui/wink/wink1.png", 0.1, "gfx/ui/wink/wink2.png", 0.1, "gfx/ui/wink/wink3.png", 0.1, "gfx/ui/wink/wink4.png", 0.1,  "gfx/ui/wink/wink5.png", 0.1, "gfx/ui/wink/wink6.png", 0.1, "gfx/ui/wink/wink7.png", 0.1, ypos =- 10)
```

CTC file [wink.zip](https://github.com/renpy/renpy/files/264531/wink.zip)

**Comment by renpytom** [comment]
Sorry, but you can explain in words what you think the problem is?

**Comment by roxygen** [comment]
Compare the screenshots. Kerning breaks and line spacing increases after updating the contents of the text window. This only happens when using CTC.

**Comment by renpytom** [comment]
I've looked into this, and I can't figure it out. Can you post the code that runs this, or better yet a game I can download to try this out? 

I think it may be specific to how the game is being code, and perhaps setting:

```
style default:
    adjust_spacing False
```

might fix this (but could cause its own problems).

**Comment by roxygen** [comment]
Sorry for not having replied.

After testing on different PC it became clear that the kerning in the game is broken when changing window size.

Especially with these parameters:
Screen sizes: virtual=(1280, 720) physical=(1184, 666)
When sizeof the  game window is larger or smaller kerning is also broken.

Our game with partial English translation: https://mega.nz/#!sMBxQIQB!zSerf5WtrcHPf-bCIFr5PJMsAynPf7JQTeDGbBK9cHA

You can also see a similar issue in this game: http://steamcommunity.com/sharedfiles/filedetails/?id=675592264&result=1
