### ISSUE TITLE
build for android under linux not working

### ISSUE THREAD

**Issue by evilantishad0w** [renpy/renpy#945]
http://pastebin.com/6uK3dnP0

Maybe due to an update in the SDK

**Comment by renpytom** [comment]
Is this on the nightlies?

**Comment by evilantishad0w** [comment]
Javabean> nightly-2016-05-20-a855d91 status: installed successfully(no errors to konsole that called it) , only available option is the "Install SDK & Create Keys".  everything below that is greyed out, emulation calls the game directly(ie not as an emulation)

**Comment by evilantishad0w** [comment]
fixed as of 5/31 nightly
