### ISSUE TITLE
Create new project - selected highlight

### ISSUE THREAD

**Issue by normundy** [renpy/renpy#949]
In the 'Choose Project Template' and 'Choose Theme' screens when creating a new project, selected choices seem to be highlighted in white

![renpy_createprojectbug1](https://cloud.githubusercontent.com/assets/10818718/15591377/a7981b84-2351-11e6-87f6-ba23573b26bd.png)

![renpy_createprojectbug2](https://cloud.githubusercontent.com/assets/10818718/15591380/aef07444-2351-11e6-98d7-9c9a81dca62f.png)

I am using Ren'Py 6.99.10 on Windows 7

**Comment by renpytom** [comment]
I think this is a bug with your video drivers.

**Comment by normundy** [comment]
Ah yeah this was a problem with my video drivers
