### ISSUE TITLE
Game autosaving on quit when config.autosave_on_quit = False

### ISSUE THREAD

**Issue by DragoonHP** [renpy/renpy#953]
If the game is closed via the title bar (the cross button on top), the game always auto saves, no matter the value of autosave_on_quit.

**Comment by renpytom** [comment]
I'm unable to repeat this using a modified version of the tutorial, and I checked the relevant code paths - no luck. Can you explain what you did?

**Comment by DragoonHP** [comment]
This is embarrasing. I was manually autosaving the game on quit and hadn't realised it. Sorry for wasting your time Tom.
