### ISSUE TITLE
doing a simple check for _from call duplicates?

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#958]
I think would be useful, during the Build phase, to do a simple check in the script for duplicate _from call labels.
Since having a duplicate can lead to some really weird bug that people might be unable to figure out (today just happened to me).
Doing duplicate labels is easier than it seems, editing an old game using copy/paste to copy block of texts for example ;)
So when you have time I think this should be a good idea and also probably reduce support :) thanks

**Comment by evilantishad0w** [comment]
Add to lint, perhaps?
