### ISSUE TITLE
renpy.call breaks Python loops

### ISSUE THREAD

**Issue by Alex-Tracer** [renpy/renpy#959]
If `renpy.call()` function is used inside python loop it breaks the loop. Exact behavior may vary depending on calling python code.

Example: 

``` renpy
init python:
    my_custom_list = [1,2,3]

label my_label(my_param):
    "in"
    $ renpy.say(None, "Inside: " + str(my_param))
    "out"

label start:
    "Start"
    python:
        renpy.say(None, "Python block start")
        for foo in my_custom_list:
            # Comment out the next line to let the for loop finish well
            renpy.call("my_label", foo)
            renpy.say(None, "Outside: " + str(foo))
        renpy.say(None, "Python block end")
    "End"
    return
```

This loop should call "my_label" 3 times. However it's executed only one time. All python code after the call is skipped.

Expected output:

```
Start
Python block start
in
Inside: 1
out
Outside: 1
in
Inside: 2
out
Outside: 2
in
Inside: 3
out
Outside: 3
Python block end
End
```

Actual output:

```
tart
Python block start
in
Inside: 1
out
End
```

**Comment by caryoscelus** [comment]
Well, there is no `return` at the end of `my_label`. That must be your issue.

//btw, github actually supports renpy syntax highlight now

**Comment by caryoscelus** [comment]
However it is true that call won't return you back to python code, but i think that is mentioned in the docs:

https://www.renpy.org/doc/html/statement_equivalents.html#renpy.call "When the jump returns, control will be passed to the statement following the current statement."

**Comment by Alex-Tracer** [comment]
My bad, I've lost the "return" statement when was building the test case. Fixed the first comment.

**Comment by Alex-Tracer** [comment]
> https://www.renpy.org/doc/html/statement_equivalents.html#renpy.call
That explains the problem. I've bit incorrectly understood that part.
So seems like everything works just as documented. Issue can be closed.

**Comment by caryoscelus** [comment]
Yeah, its a bit vague in docs. Anyway, i'm actually considering fixing this, though that seems to require some magic.

**Comment by renpytom** [comment]
I don't think this is fixable. To fix it, you'd have to somehow be able to return to the middle of a python block. Sort of crazier-than-usual python code transformations, I don't see how you do this.

**Comment by caryoscelus** [comment]
One way to do just that is to wrap every python line (statement) into `try-except` closure and catch `CallException`s from there. However, then the problem is how to return to `Context.run` to actually perform call.

**Comment by renpytom** [comment]
That's the first problem. The second is how to return to the middle of arbitrary python code, once the call returns - and how to do that through a save/load cycle. 

I've given it a bit of thought, and short of implementing some sort of python-python compiler that can remove all of the control flow from the program - and a lot of the performance, while we're at it - I don't think this is possible.

Alex-Tracer, I plan to simply clarify the documentation so people don't get confused.

**Comment by caryoscelus** [comment]
Yeah, sounds like that won't help. Another possible solution could be multi-threading - put python block execution into separate thread while main is on hold and on `renpy.call` switch back - but i'm not sure how much other stuff may be affected and how hard in the end it would be.

**Comment by renpytom** [comment]
Still won't work - the thread dies when you save, quit, launch, and load.

**Comment by caryoscelus** [comment]
Right.

**Comment by Alex-Tracer** [comment]
Is it easier to do the magic when code author wraps original code into try/catch blocks? So if somebody wants to get back to Python code then he will need to write something like that:

```renpy
label start:
    "Start"
    python:
        renpy.say(None, "Python block start")
        for foo in my_custom_list:
            # Comment out the next line to let the for loop finish well
            try:
                renpy.call("my_label", foo, use_magic_exception=True)
            except RenpyMagicException:
                pass 
            renpy.say(None, "Outside: " + str(foo))
        renpy.say(None, "Python block end")
    "End"
    return
```

**Comment by Alex-Tracer** [comment]
> The second is how to return to the middle of arbitrary python code, once the call returns

This there any chance to utilize Python's `yeld` for that? Or that's will not survive save-load anyway?

**Comment by caryoscelus** [comment]
@Alex-Tracer , `try-except` won't really help. Not sure if `yield` can improve something here, but save-load would indeed be broken as well anyway. As far as i understand, Ren'py saves only "current statement" as a kind of execution pointer.

Thus the best that could be done, perhaps, is to implement loops (and other control structures; `if` is already there though) in renpy syntax and translate python blocks into regular renpy nodes. However i don't see how that will actually be useful; it won't help with python functions either.

**Comment by caryoscelus** [comment]
Using stackless (or PyPy which has stackless feature as well) python might actually provide a proper solution. But that might (and probably will) require a lot of work, nevertheless.
