### ISSUE TITLE
Support non-english script keywords.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#961]
It would probably be valuable to allow other keywords to substitute for the default script language keywords - at least the most common ones. This would let us write

```
owshay eileen happy atray right ithway dissolve
```

instead of 

```
show eileen happy at right
```

The idea is that we should make it possible for people to enter common script code in their native language, especially if doing otherwise would require them to change keyboards. 

We should standardize the set of keywords on a per-language basis, so code can be shared within a language community. And it probably makes sense to only do this with buy-in from the main Ren'Py community for a language.

**Comment by pratomoastan** [comment]
this is good idea ...

**Comment by vollschauer** [comment]
Tom I wouldn't do that. Stick to english.... like any other programming/scripting language.
And I'm saying this as non-english native speaker. I even try to write all my comments in proper english, because the day will come when you need help or have to share your stuff.... 

And my first look at:

`
owshay eileen happy atray right ithway dissolve
`

bam... I have no idea what this does. But....

`
    show eileen happy at right
`

and I know exactly what this does....

**Comment by pratomoastan** [comment]
But this will make the ren'py more word wide.

What if the programmer/scripter not very good at english ? .

Still, i think this is a very good idea/concept.

**Comment by caryoscelus** [comment]
Some thoughts on this:

## general considerations
It doesn't make much sense to use translated keywords with non-native (latin) variable names. But while keywords (and ren'py variables) can be quite easily translated back and forth for international communication, this won't work with user-defined variable names. If somebody uses native names now, they still have to transliterate them to latin alphabet and thus names are at least readable (if not understandable) and editable for everybody. If non-latin names are allowed, this is no longer true.

## possible advantages
1. Provided there is a documentation (and perhaps error messages) translation, this will allow people with zero english knowledge to use ren'py.
  While this may sound nice, it actually depends on documentation much more than translated keywords or unicode names support. Provided that docs are translated it is possible to write with little to no english knowledge even with programming language using english keywords.

2. It will also allow people unfamiliar with programming and ren'py (and again no or little english) to partly understand the code (to the same degree as it is now for english-speaking people).
  If this is critical for the team, comments in native language can give the same or even better effect (while cluttering the code, however).

3. It will minimize keyboard layouts switching required for non-latin alphabet languages.

4. Some people might be more happy to write code with native language even if they are capable of writing code with english keywords and latin names.

## possible disadvantages
1. Community split.
  If this change will be widely adopted by language communities and it will lead to their further isolation. It is less likely that someone using fully localized ren'py code will look at unlocalized code snippets and third-party modules. This in turn might lead to translating/forking those modules, without any sync guarantees. Or to reinventing existing code.

2. Maintaining effort.
  This shouldn't be too hard for keywords if there are people willing to do it. Maintaining documentation is much bigger problem though.

3. Ugly code and increased keyboard layout switching when using untranslated stuff (e.g. python libraries, third-party code).

## personal experience
I am non-native english speaker; in fact, i didn't have much english knowledge when started learning programming and it wasn't too much of a problem.

Also in my experience, understanding (or better speaking) english makes any computer-related problem solving much easier and thus learning english is justified for any programmer (while ren'py script-writers are not necessarily programmers, it is also not necessary to know english to use english keywords).

**Comment by renpytom** [comment]
The goal is not to fully localize Ren'Py, or even to localize a lot of it it. And it's probably not something I'm going to do for latin languages.

The goal of this is to allow writing - the initial input of the script - to occur without having to constantly toggle between latin and cyrillic/japanese/whatever. So we're talking about a small subset of statements, for what I think will be a big win to usability.

**Comment by caryoscelus** [comment]
Well, what about variable names? I think that majority of used statements use some names. If they stay latin only, the amount of toggling is likely to stay at same level or even increase.

**Comment by renpytom** [comment]
The eventual plan would be to aim for allowing unicode names. (We support that when it comes to things like character and image names. I don't think we support it for python variables and defines, but we will once we have Python 3 support.)

**Comment by pratomoastan** [comment]
hmm okay then ><

**Comment by caryoscelus** [comment]
Character names sounds nice (didn't know about it), because they are natural part of text. Anything else seems too much, but maybe it's just me being too skeptical.

**Comment by renpytom** [comment]
Probably not going to happen.
