### ISSUE TITLE
Stuttering movement with overlapping textbuttons and focus_mask True

### ISSUE THREAD

**Issue by TrickWithAKnife** [renpy/renpy#962]
Example code [here](http://pastebin.com/r5zzHZmP).

When moving, overlapping textbuttons are hovered with the mouse and `focus_mask True`, the movement of all buttons stutters quite badly, especially fullscreen.

Everything is smooth with `focus_mask None` or when the buttons do not overlap.

**Comment by renpytom** [comment]
This is old, please let me know if there's a problem with newer versions of Ren'Py.
