### ISSUE TITLE
Doc still have 'config.translations' as a 'common used config var'

### ISSUE THREAD

**Issue by xavi-mat** [renpy/renpy#963]
https://www.renpy.org/doc/html/config.html#var-config.translations
Is this variable still used? Isn't it obsolete?

Also, the doc has the sentence: "See Localizing Ren'Py for how to use it, and here for a list of available translations.", without links (the links would be to the very old wiki, anyway).

**Comment by renpytom** [comment]
This has been fixed, by removing the variable from the documentation. Thanks for reporting this.
