### ISSUE TITLE
config.developer = "auto" allows the console to be used

### ISSUE THREAD

**Issue by xavi-mat** [renpy/renpy#964]
In 6.99.10.1227 the "config.developer" var is set to "auto". It's True when developing and False in a build. But it seems the console is allowed in the build (Shift + O) (not the other developer options).

![screenshot](https://cloud.githubusercontent.com/assets/1102677/16190529/043165f2-36e0-11e6-805e-25e3123fa90b.jpg)

(It's not allowed if I add manually "config.developer = False" in options.rpy)

**Comment by renpytom** [comment]
This should be fixed now.
