### ISSUE TITLE
Android game screen not aligned on top

### ISSUE THREAD

**Issue by jacknorton** [renpy/renpy#967]
In the latest Ren'Py version (the nightly) the game screen on android aren't aligned on top, so the Android menu bar goes over the bottom of the game screen.
More info and screenshots (comparing it with older Ren'Py versions) in this thread:
https://lemmasoft.renai.us/forums/viewtopic.php?f=8&t=39324

**Comment by renpytom** [comment]
This seems to only occur with Android pre-4.4.
