### ISSUE TITLE
Divizion by zero error on alt+tabbing/virtual screen changing

### ISSUE THREAD

**Issue by Atrboomy** [renpy/renpy#969]
**Details:**
Windows 7
VirtualWin 4.4 for multiple virtual desktops
**How to reproduce:**
Exact cause is unknown
Something with switching virtual desktops/alt tabbing, maybe during phrase render
**Traceback:**
[traceback.txt](https://github.com/renpy/renpy/files/354817/traceback.txt)

**Comment by renpytom** [comment]
Ren'Py doesn't support being scaled down to zero size. We set a minimum window size to prevent this from happening.

Could there be a problem with VirtualWin that's causing this?

**Comment by Atrboomy** [comment]
Probably. The error isn't arising constantly, either. I switched about 50 times or so, and bug only showed once.
Wontfix, I suppose?

**Comment by renpytom** [comment]
Leave it. I might as well add a check for this case.
