### ISSUE TITLE
How to change opacity of say screen background in preference screen by Bar

### ISSUE THREAD

**Issue by sirlis** [renpy/renpy#970]
my say screen has a background:
```
screen say:
        window:
            id "window"
            background None
            add "saybg.png" alpha persistent.sayopacity
            ...
```

with opacity given by persistent.sayopacity

how to change its value by bar?
Currently im writing like follows:

```
screen preferences:
    ....
    bar value FieldValue(??,"persistent.sayopacity",?? .... )
    ....
```

I don't know how to finish this or if this is the correct way to do it.

plz help and thx a lot.

**Comment by vollschauer** [comment]
There is a forum for such questions: http://lemmasoft.renai.us/forums/

**Comment by sirlis** [comment]
got it.

`value FieldValue(persistent,"sayopacity",1.0,step=0.01)`
