### ISSUE TITLE
Gallery advance through locked images not working.

### ISSUE THREAD

**Issue by vollschauer** [renpy/renpy#971]
I'm trying to figure out why "g.locked = True" dosen't show me only my unlocked images.
(I'm using unlock_image(*images) in my gallery)
Well, looking a the 00gallery.rpy I can't really figure out how the result gets the "next_unlocked" value... so that this condition "if self.locked and result.endswith("_unlocked")" will be True.

            # Loop, displaying the images.
            while True:

                b = self.button_list[button]
                i = b.images[image]

                result = i.show((button, image) not in unlocked_images, image, len(b.images))

                # Default action for click.

                if result is True:
                    result = "next"

                if result == 'return':
                    break

                # At this point, result is either 'next', "next_unlocked", "previous", or "previous_unlocked"
                # Go through the common advance code.

                if self.locked and result.endswith("_unlocked"):
                    images = unlocked_images
                else:
                    images = all_images

wouldn't that be enought?: 

                if self.locked:
                    images = unlocked_images
                else:
                    images = all_images

or this?:

            if self.locked or result.endswith("_unlocked"):
                images = unlocked_images
            else:
                images = all_images

**Comment by renpytom** [comment]
No, Ren'Py is correct here. 

g.Next(unlocked=True) advances to the next unlocked image, while g.Previous(unlocked=True) goes to the previous one. Otherwise, the gallery will show you the "Image is Locked" indicator.
