### ISSUE TITLE
game in window mode, use windows default close button will cause a small flash

### ISSUE THREAD

**Issue by sirlis** [renpy/renpy#972]
OS: Windows 10 64 bit

1\ Run renpy game in ‘winows mode’ (not full screen mode)
2\ Activate transitions (set the transitions preference to be ‘True’)
3\ Use the system default red close button on the upper right to try to close the game.
4\ Click ‘cancel’ on the popup confirmation window.

Problem：
The game window will flash for one or two times before the confirmation window disappear(dissolve). 
This tiny problem will not appear when close transition (transitions preference set 'False').
Closing game by using buttons with 'action Quit()' and then choose 'cancel' will not cause this problem.

the yes_no prompt code is as follows:

```
screen yesno_prompt(message, yes_action, no_action):
    tag yesno
    modal True

    window:

        xpadding 0.0
        ypadding 0.0

        if not in_game or _in_replay:
            if message == layout.QUIT:
                add "black_bg.png"
        else:
            if message == layout.QUIT:
                add "black_bg.png" alpha 0.2
        add "dialog_bg.png":
            align 0.5,0.5

        text _(message):
            align 0.5,0.43

        imagebutton:
            idle "ui/dialog/dialog_yes.png"
            action yes_action

        imagebutton:
            idle "ui/dialog/dialog_no.png"
            action no_action

    key "mouseup_3" action no_action
    key "game_menu" action no_action
```

while black_bg.png is a full game window size pure color image with no opacity, dialog_bg.png is a smaller picture.
Seems that only the confirmation window background (dialog_bg.png) in the center will flash, the black background (black_bg.png) dissolves smoothly.

**Comment by sirlis** [comment]
Update:
I delete all image, only left text and two imagebutton, the flash exists.
I moved the text and imagebuttons outside the 'window',the flash exists.
I delete the 'window', the ‘tag yesno‘ and 'modal True’, the flash exists.
I replace the two imagebutton to textbutton, the flash exists.
I delete all things in yesno_prompt, only left the key action, the flash exists.
I don't know what to do now ....

**Comment by renpytom** [comment]
Can you post more details about this problem. I'd want to know if there are any transitions in use.

**Comment by sirlis** [comment]
sorry for the delay..

I've found a possible reason for the problem, when i switch the "yesno transition" in options.rpy from "Dissolve(.1)" to "None", the problem never happens.

‘’‘config.exit_yesno_transition = None #Dissolve(.1)’‘’

However, the reason why closing game by using buttons with 'action Quit()' and then choose 'cancel' will not cause this problem is still unknown. Only close game by windows default red close button will cause the flash when there is a dissolve transition on the yesno prompt.

**Comment by renpytom** [comment]
Closing this, as I've never been able to repeat it.
