### ISSUE TITLE
Error installing rapt on 6.99.10

### ISSUE THREAD

**Issue by ogiqtpcq** [renpy/renpy#973]
There's been an update of the Android SDK recently that changes the name of two folders. 
And since RenPy hasn't taken that into account yet, there's a conflict.
Go to : renpy-sdk\rapt\android-sdk/extras/google/
The folders previously known as « play_apk_expansion » and « play_licensing » are now called 
« market_apk_expansion » and 
« market_licensing ».

**Comment by evilantishad0w** [comment]
Try latest nightly please.

**Comment by EnragedViper** [comment]
The latest nightly works (as of today, 18/08/2016). I did need to download Rapt and the Android SDK manually, but it does compile APK files successfully.
