### ISSUE TITLE
Lambdas inside screen use global namespace

### ISSUE THREAD

**Issue by caryoscelus** [renpy/renpy#978]
Short (and synthetic) demonstration:

```renpy
label main_menu:
    return

label start:
    $ x = 'fail'
    show screen test_screen
    "..."
    return

screen test_screen:
    frame:
        xalign 0.5 yalign 0.5
        has vbox
        $ x = 'ok'
        $ f = lambda: x
        $ r = f()
        text "[r]" # expected: 'ok', got: 'fail'
```

I think that makes lambdas inside screen useless and even potentially harmful, if name collisions occur. Perhaps it could be too complicated (compared to gain) to properly implement screen lambdas, but in that case it might be a good idea to forbid them.

**Comment by XelaPy** [comment]
This will kill save/load and roll back systems. You can't pickle lambda if it is persists at the end of your current statement.

It might not be worth doing anything about it as devs who write custom save/loading systems or develop games without save/load options are a rare breed.
