### ISSUE TITLE
renpy.music.get_duration() returns 0.0

### ISSUE THREAD

**Issue by sashaaero** [renpy/renpy#981]
If music is started by MusicRoom get_duration() returns 0.0, if music started in game using 'play' keyword - functions works okay.
So AudioPositionValue (that seems works using this function) does strange things.
![Screenshot](http://puu.sh/qcwc3/65bebdafc2.png)

**Comment by renpytom** [comment]
I just tested, and it works for me. 

What format is the music in? Not every file format supports determining the duration.

**Comment by sashaaero** [comment]
It is just mp3 file. It seems to be bug, but circumstances too hard to explain how did I get this result.
